#!/bin/bash
# publish org files.

# check references
echo ">>>>>>>>>> check references <<<<<<<<<<"
python ./scripts/check-ref-images.py
if [ $? != 0 ]; then
    echo "resolve ref issues!"
    exit 1
fi

# compress images
echo ">>>>>>>>>> compress images <<<<<<<<<<"
python ./scripts/compress-images.py
if [ $? != 0 ]; then
    echo "compress images failed"
    exit 1
fi

# echo ">>>>>>>>>> git rebase master <<<<<<<<<<"
# git pull origin master
# if [ $? != 0 ]; then
#     echo "git add & commit!"
#     exit 1
# fi

echo ">>>>>>>>>> emacs publish  <<<<<<<<<<"
# find emacs binary.
kernel=`uname -s`
emacs="emacs"
if [ $kernel"X" == "DarwinX" ]; then
    emacs="/Applications/Emacs.app/Contents/MacOS/Emacs"
fi

# generate html files.
$emacs --batch --script ./scripts/publish.el
if [ $? != 0 ]; then
    echo "emacs publish failed!"
    exit 1
fi

# post processing html files.
echo ">>>>>>>>>> post publish  <<<<<<<<<<"
python3 ./scripts/pp-html

echo ">>>>>>>>>> git push master  <<<<<<<<<<"
git add .
git commit -a -m 'BUILD HTML'
git push origin master
