#!/bin/bash
# publish org files.

# find emacs binary.
kernel=`uname -s`
emacs="emacs"
if [ $kernel"X" == "DarwinX" ]; then
    emacs="/Applications/Emacs.app/Contents/MacOS/Emacs"
fi

git pull origin master
# generate html files.
$emacs --batch --script ./scripts/publish.el
if [ $? != 0 ]
then
    echo "publish failed!"
    exit 1
fi

# post processing html files.
python ./scripts/pp-html
git add .
git commit -a -m 'BUILD HTML'
git push origin master
