#+title: 10 Lessons Learned from the Early Days of Google

中文：http://www.techug.com/matt-cutts-10-lessons-learned-from-google

原文：http://highscalability.com/blog/2015/2/4/matt-cutts-10-lessons-learned-from-the-early-days-of-google.html

挺强烈推荐的。其中3，6，9，10对我最有启发。

- 3. Be proactive. No one cares about your career or your money than you do. Ask for what you want. You miss 100% of the shots you don’t take.  # 不要等别人告诉你应该做什么事情，那样自己会比较被动不太可能做自己想做的事情。主动去发现自己想做的事情，这样你（和你的经理）会发现自己会比以往更加投入。
#+BEGIN_QUOTE
Matt was “volunteered” to work on the front-end of the ads product, where he worked for about a year. During this experience Matt could see people starting to spam Google. So Matt went to a VP of Engineering and said “I want to work on spam” and the VP said OK. Just like that. Before that Matt largely went along with what others thought he should do.

You would be amazed what a difference it makes to just tell someone “I would like to do X.” If you are manager, if someone wants to work on something they will work twice as hard.
#+END_QUOTE

- 6. Was commodity hardware why Google succeeded? # 不断地创新才能成功
#+BEGIN_QUOTE
No, success is hundreds of innovations. It’s not like there’s one shining epiphany and everything is set. So it wasn’t just cheap hardware, it wasn’t just Page Rank, it was Map Reduce, Spanner, and so on. It takes many innovations to make a successful company or a successful career.
#+END_QUOTE

- 9. No matter what bad things are going to happen. Have some fun along the way and take some pictures. # 革命精神，"苦"中作乐。目标很重要，过程也很重要。从过程中寻找快乐并且记录下来，生活会更加有意义。
#+BEGIN_QUOTE
You could record every meeting if you wanted too. Digital is cheap. Ten years from now you’ll want to remember that ping pong table where eight of you would sit around and talk about making Google search quality better. You’re going to want to remember that huge dog. You’re going to want to remember the good old days.

Try to take pictures when something funny or quirky happens. One example was a giant cookie sent in by someone wanting reinclusion into search. Other examples are April fools pranks and Halloween traditions.

There was a bet Matt made with his team where they could do anything they wanted to his hair of they did a really good job fighting spam for a quarter. They cut it all off

Interesting story about weekly meetings where employees could grill the execs about why they made the decisions they made.
#+END_QUOTE

- 10. Whatever you are working on, try to make sure it matters, it’s something you care about, and it’s something people want. # 做别人和自己都在乎的东西。
#+BEGIN_QUOTE
Matt has always thought of Google as a tool and they try to make it the best tool they can.

Fred Brooks in The "Computer Scientist as Toolsmith": If we perceive our role aright, we then see more clearly the proper criterion for success: a toolmaker succeeds as, and only as, the users of his tool succeed with his aid.
#+END_QUOTE
