#+title: A Decade at Google

[原文地址](http://wp.sigmod.org/?p=1851)

*如何选择项目*

One of the key challenges you face in an industrial research lab is how to choose your projects. You want your projects to be interesting research but also contribute to your company. As a junior researcher, you’re typically in the situation of choosing a project to join, while later in your career you are expected to come up with and lead your own projects. Regardless of your age, you have to make an educated decision. 选择项目很重要, 无论你阅历如何. 初期你可能选择一个项目加入, 之后可能会主导自己的项目.

It is common wisdom that you should not choose a project that a product team is likely to be embarking on in the short term (e.g., up to a year). By the time you’ll get any results, they will have done it already. They might not do it as well as or as elegantly as you can, but that won’t matter at that point. This advice can be challenging to follow in a fast moving company like Google and its cohorts, in which a third of the engineers have Ph.Ds. On the other hand, you also don’t want to be too far ahead of your company’s trajectory, so you need to choose projects that you can imagine applying once you have substantial results. 不要选择那些短期(1年内)就完成的项目. 这些项目完成之后虽然还有很大的改进空间, 但是已经无关紧要了, 因为没有人会在乎它了; 另一方面, 也不需要选择太超前于公司发展轨迹的项目, 否则有可能得不到实质性成果(对于公司直接的贡献)

Choose projects that play to your strengths 选择能发挥你能力的项目(这点是不是更适合PhD? 对于本科研究生都不知道自己能力在哪方面)

*Concluding Remarks*
- Never stop writing code 撸代码不能停

- Never stop looking at data 看数据不能停.
#+BEGIN_QUOTE
Over the years, I realized there was a trait that correlated well with success when addressing complex and data-heavy tasks: the ability to obsessively look at great amounts of data until you gain insights. As Ph.D’s in Computer Science, we’re not necessarily trained to spend hours looking at data. We’re much better at obsessively tweaking the algorithm to get it to do the right thing, but we often get bored after looking at a handful of example data items (us database management folks are probably even worse than average!). At Google we have the gift of data, but it surprised me to see how often researchers and engineers would shy away from it. I have found time and time again that engineers and researchers that obsess over their data end up discovering the critical observations that enable them to develop effective algorithms. Additionally, when you present an idea, you sound much more compelling when you have examples rolling off your tongue.
#+END_QUOTE

- Academia vs. Industry 学术和工业界差别. 简单来说学术界一个自我为中心, 以自己的idea作为出发点, 然后不断地polish这个idea. 而工业界则则是以团队为中心, 以product为出发点, 不断混合各种ideas不断地polish这个product. 你可以说某个idea是你自己的, 但是却不能说某个product是你的. 学术界带给你的成就是, 你在学术圈的知名度不断提高, 而工业界带给你的成就是, 你交付了让用户满意的产品. 
#+BEGIN_QUOTE
As a former academic, I’m often asked about the difference between academia and industry. There are many answers to this, including the fact that in industry you need to solve the entire problem rather than cherry pick the nugget you wish to solve elegantly. The main difference, however, which can be very subtle and perhaps only obvious in hindsight is the following. (I originally heard this observation from Prabhakar Raghavan before joining Google, but it took me a decade to internalize it). In academia, as you pursue your passion for science and technology, the evaluation of faculty creates pressure to further your career as an individual, whether it is through publications, graduating and promoting your students or being an excellent educator. You are by necessity the champion of your own ideas, which I think is ultimately a critical ingredient to scientific progress. In contrast, to be successful in industry, whether in engineering or in research, you often need to put your individual goals and ideas aside. You need to find the most effective way to get to a great product or service (or part thereof) even if it means finding the right mix of ideas. You will be rewarded for contributing key ideas to a product, but you will be rewarded even more for getting the job done, collaborating effectively across teams, and pleasing customers. This advice may be even more useful for academics founding startups. Once you founded your company based on the great research you conducted at the university, the company takes a life of its own and the most important goal is to create a product that users want.
#+END_QUOTE

- Work life balance. balance不是靠减少工作来达到的, 而是靠一些自己感兴趣的事情, 把自己从工作中脱离出来.
#+BEGIN_QUOTE
Much has been written about finding work life balance. My 2 cents are simple. You do not reach balance by reducing work. You reach balance by finding a passion that draws you out of work. Of course, family comes first on this ladder, but we often need some other passion. In my case, I had the most wonderful experience writing a [book about coffee](http://www.amazon.com/Infinite-Emotions-Coffee-Alon-Halevy/dp/0984771506). I did not plan it as a worklife balance treatment, I just realized it in hindsight. With the exception of spending time with my kids, I found that the evenings spent researching and writing about coffee (let alone the exotic trips I had to take as part of this learning) gave me hours of respite without thinking about work.
#+END_QUOTE
