#+title: A great developer can come from anywhere

[原文链接](http://www.manton.org/2015/10/a-great-developer-can-come-from-anywhere.html)

正所谓英雄不问出处. 这位作者(iOS/Mac Developer)在大会上遇见了Tumblr的CTO Marco. Marco当时演讲主题是关于MySQL scaling. 私下聊天的时候问了这位作者觉得Marco自己开发的Instapaper如何并且询问他自己是否应该参加WWDC, 这位作者也没有怎么放在心上就随便回答了两句. 结果Instapaper火了. 作者总结就是, 别小看那些现在看起来不起眼的开发者, 搞不好哪天他们就成功了. 一个好的开发者可能来自于任何地方.

I believe that’s equally true for developers. We often see someone go from nothing to a top app in the App Store. We often see someone start without an audience and then make friends on Twitter and blogs through the quality of their writing alone. And so we welcome new voices all the time if they’re respectful.

There’s been some debate about [[http://www.marco.org/2015/10/13/pragmatic-pricing][Overcast 2.0’s patronage model]]. Some of the discussion is healthy — how does a successful business model for one developer apply to other apps? — and some of the discussion is divisive. Instead of asking the right questions, it’s easy to jump straight to a *conclusion* with the dismissive statement: “that’s fine for Marco, but his approach would never work for other developers”.(一些"谁本来就很牛B, 所以他成功并不奇怪"的论调本身是非常有害的)

The “that’s fine for Marco” attitude is poison for our community because it takes the opposite approach as that Ratatouille quote above. It implies that some developers have such an advantage that the rest of us shouldn’t even bother, because it’s not a level playing field. It’s true that some developers today have an advantage, whether through good timing or just a long history of shipping apps, but the lesson isn’t to give up; it’s to instead learn from it, and look at our own strengths. What small head start do we have that could grow into a great success tomorrow, too? (我们不应该简单地将成功归为先发优势或者是已有优势, 相反应该从中深入发掘和学习他们成功的真正原因)
