#+title: 数学家妙谈股市(A Mathematician Plays the Stock Market)

https://book.douban.com/subject/1083994/

** 第一章 对他人预测结果的预期

像这样的故事向我们提出了一个问题，如果你十分聪明，为什么你不富有呢？哪怕那些只有一点点智力和一两张未付的账单的人们，都反复被这样的问题所困扰着。但是就像聪明和富有之间存在不同一样，正确选择和市场波动之间，也存在着相似的不同。

阿瑟提出的这个模型，阐明了一种市场投资者的行为。像我的学生和酒吧的顾客，他们必须预测到别人对他们的预期。一个人是买入股票还是卖出股票，圈定方框还是不圈定方框，去那家酒吧还是不去那家酒吧，依靠一个人对其他人可能的行为和想法的判定。

为了改变从共识到共同知识的信息的逻辑地位，必须要有一个独立的仲裁者。在这个寓言里有一个女族长，类似于市场中的证券交易委员会(SEC)。如果没有一个人被大家信任和依赖的话，那么这个警告的激发和影响就会失去。幸好不像是故事中可怜的丈夫们那样，市场是能够再生的。

** 第二章 恐惧，贪婪和认知幻想

我们可以把市场比喻成一辆好的赛车。赛车的那种精致敏感的车轮定位系统，使它不可能一直走一条直线，在我们前进的路上稍微有一点障碍，都会使我们大范围的转向。因此我们在这种贪婪恐惧的心理状态下，像走Z字形一样的前进和倒退，从毫无原因的非理性失望到不合理的非理性繁荣。

另一方面，“锚”定的更多的极端形式，通过投资者的注意力展现出来。投资者往往把他们的注意力集中到公司每季度宣布的盈利和基于宣称的估算分析是否一致。当公司的盈利每股仅仅下降一分或者两分时，投资者有时候也会像公司接近破产一样的产生反应。他们看起来好像不仅仅把他们心里的“锚”定位于盈利估算上面。

相关的研究表明，那种由于被动而导致可以忍受的损失，远没有那种积极行为而导致的损失更遗憾。如果某一个人固守着他以前的投资，尽管已经跌了25%，但是跟他转换投资从而导致失去自己失去了25%比起来，他没有后者感到的那么痛苦。

考虑一个极端的例子，认知幻象使得思维成为一种封闭的系统，并且这种思维对外界有一定的免疫能力，不会被外界的驳斥和试图改变而影响。奥地利的讽刺文学作家卡尔克劳斯曾经描述过：“心理分析是一种心理的幻觉，而它却自认为是一套理论。”这对于市场来说更是真实的，因为投资者关于股票的信念，或者选择股票的方法成为一种自我实现的信念。市场有时候扮演一个充满希望的陌生的野兽。研究它不像研究其他的科学及数学一样，它的所有假定和法律，都是依靠我们这些投资者的。如果足够的人们突然清醒的相信股市，那么股市一定会马上抬高它的股价，来逢迎它的那些支持者的信念。

一些真正懂股票的“正规军”们往往很真诚地出现在聊天室里，和你非常认真的理性的探讨股票的走势以及交易的思考。也有少部分看起来知道很多，但他们是那种非常偏僻的各种各样的奇怪的阴谋理论的爱好者，也通常毫无道理，而且有时候表现得非常笨。

当然在聊天室里发表文章的那些人所发表的一些他们可笑的操作行为，然后从这些操作中得出的一些建议的讨论是愚蠢的，但是这种在站点上实时的交流，类似于偷听一个你感兴趣的人的闲聊。看起来是多么的无聊，不可信和夸张，但它确实有一定的道理并且吸引人。另外一个类比就是听警察电台，并且深切感受到大街上自然的生命和死亡。

** 第三章 趋势，量和波浪

不论这些信条和技术分析通常是否有效，我必须承认集体行为的讨厌之处，它就像一个劝告：随大流。正是因为讨厌区趋众才阻止我卖掉世通，我不停的对自己说这家公司是不良公共关系的受害者，投资者的误解，媒体的攻击，对CEO的不满，恶劣的商业气候，错误的时间选择或恐慌的买卖。总之我认为大多数人是错误的，而且我厌烦这种必须要遵守的思想。后来我慢慢意识到，有时候藐视多数人就是自大。

标准的股市投资根本不能用这类游戏做模型，但是这些游戏的变体可以产生违背直觉的投资策略。概率能够通过各种金融工具的复杂组合计算出来，但是上述复杂游戏里决定抛（做）哪个硬币（投资），必须根据除了某人持有的股票是否是3美元（或者3000美元）的倍数之外的其他东西，也许会根据两只股票的相关性，或者一些指数值是否是3的倍数。如果这样的策略发挥作用，他们将会产生一种帕隆多（Parrondo）收益。

关于帕隆多效应，书里面给了一个例子做说明。简单地说，这个效应是，如果有两种期望收益为负的游戏策略(比如AB)，可以通过恰当的组合(比如AABB这样)得到期望收益为正的结果。
这个游戏是，在一个台阶序列上比如[-500, 500], 起点是0.  每次投一次硬币，头向上+1，背向上-1.
- 第一个策略A是，一个硬币头49.5%向上，背50.5%向上
- 第二个策略B是，两个硬币，坏的9.5%向上，好的74.5%向上。但是台阶数是3的倍数，那么就抛坏的；其他情况抛好的。
两个策略独立来看，最终结果都是到-500. 但是如果按照AABB, 或者是ABAB策略的话，那么最终会到500. 我们可以用计算机模拟这个实验。


** 第四章 偶然性和效率市场

** 第五章 价值投资和基础分析
