#+title: 心中的邪火

这阵邪火在我心中有好一阵子了。大约是从14年年末开始吧，主要表现就是焦躁不安。你若问要是我为什么会这样，我可能会恶狠狠地盯着你，然后用黑人英语给你来句"fuck off". 但是对老婆不能这么回答。我给我老婆的回答通常有这么几个：1. "感觉自己在家里没有什么人交流" 2. ”没有机会参加创业公司来钱不够快" 3. "对自己的前途发展缺少规划也缺乏安全感". 这些回答，现在依我来看，都只是真实答案的碎片，合在一起才有可能真正地解释我为什么焦躁不安。可是我老婆也不是福尔摩斯，没有那么多耐心去把这些碎片一片片地拼起来。

我心中的邪火，乃是没有平衡各种舍得引起的。三样东西吧: 时间，金钱，个人发展。对于我来说，每一份工作在这三个东西上的舍得都不太一样。

在老东家后期，时间和金钱上满足得不错，但是自己是在是觉得太无聊了，所以才会找了一份part time startup来做（当然我不会告诉那个startup我是part time的，而且即便如此我的工作产出也远超过那些full time的employee).但是做着做着，老是感觉这些项目来钱不够快啊，大家进度有点慢啊，tech leader每天都在瞎BB各种bike shed, 渐渐地我便失去了耐心，最后从这个单位撤了。本来挺好的平衡，结果对于金钱过分渴望，而被打破，又回到了之前的不平衡。回过头来看看，其实在这家公司做得挺开心的，tech leader对我也非常不错，虽然大家每天都在瞎BB，但是pay roll还是照发，团队也经常会讨论一些非工作的问题。甚至最后面我要撤的时候，CTO给我写了一封长长的挽留信。这件事就到这里，说多了都是泪。

同样还是在老东家的中后期，有一段时间本来我也是心生撤意的，因为我找了一家full time remote job. 但是老板挺照顾我的，让我暂时先别离职，每周只要来公司两天即可，其他时间你就做你的remote job. 我心想，嚓，有这么好的事情，连忙感谢老板。哦忘记说我为什么想找个remote job了, 不是因为酷，也不是因为时间自由，也不是因为钱多，是因为既酷而且时间自由钱还多。可以和朋友说我找了一个remote job搞，响应DHH的号召; 我每天不用commute, 充分利用时间, work life balance; 至于钱嘛，比原来单位稍微多一些，也不差。可是即使这份起初看起来简直是perfect的job, 我也就干了大约半年多些吧。为什么呢？还是那股邪火，还是嫌founder那种小富即安的思想。founder做事情其实非常扎实，但是特别慢，可是代码质量却非常的高。我头半年基本上就是修修bug, 问founder要我做一些什么feature的话，他偶尔会给一两个。我们每天下午4点左右在skype上写写今天的work和明天的plan(注意这里是用文字交流，不用语音的哦!!!) 和上一段经历一样，我一看这个founder没什么野心把公司搞大啊，觉得算了吧还是撤吧，这事就这样地结束了。

可能你会好奇，丫的，这两段经历你不最后都是因为觉得来钱太慢撤的嘛，别和我说什么没处理好"时间，金钱，个人发展"的平衡，直接说觉得来钱太慢得了。没错，这两段经历最后失败，都是因为我钻到钱眼子里面去了。可是当初为什么在老东家做的挺好的，还想找个remote job来做，还是因为考虑到需要有一定的在家时间来照顾家里，同时也不想落下个人发展。这事其实不少见，抱着良好的初衷和愿望，结果做了一件傻X透顶的事情，还是为智商交了税。

so你的观点是什么? 我想说的是，择业这件事情，其实是时间，金钱和个人发展的平衡。每一份工作都在这三个方面有不同的优势和劣势。不要想着三个都占优，那是一个不稳态，最终会回到一个两方面相对占优的稳态。所以尝试跳到那个不稳态人，只不过频繁地无意义地更换工作的傻瓜。只求得而不舍，这事只能被意淫。另外一件经常被大众意淫的事情，就是"低风险高回报"，这事和本文无关。












