#+title: 动物庄园(Animal Farm)

http://baike.baidu.com/subview/155123/5370757.htm

-----

七诫 
- 1. 凡靠两条腿行走者皆为仇敌； 
- 2. 凡靠四肢行走者，或者长翅膀者，皆为亲友； 
- 3. 任何动物不得着衣； 
- 4. 任何动物不得卧床； 
- 5. 任何动物不得饮酒； 
- 6. 任何动物不得伤害其他动物； 
- 7. 所有动物一律平等。

-----

于是，斯诺鲍经过反复思忖，宣布“七诫” 实际上可以简化为一条准则，那就是“四条腿好，两条腿坏”。他说，这条准则包含了 动物主义的基本原则，无论是谁，一旦完全掌握了这个准则，便免除了受到人类影响的 危险。

-----

“同志们”，他大声嚷道，“你们不会把我们猪这样做看成是出于自私和特权吧？ 我希望你们不。实际上，我们中有许多猪根本不喜欢牛奶和苹果。我自己就很不喜欢。 我们食用这些东西的唯一目的是要保护我们的健康。牛奶和苹果（这一点已经被科学所 证明，同志们）包含的营养对猪的健康来说是绝对必需的。我们猪是脑力劳动者。庄园 的全部管理和组织工作都要依靠我们。我们夜以继日地为大家的幸福费尽心机。因此， 这是为了你们，我们才喝牛奶，才吃苹果的。你们知道吧，万一我们猪失职了，那会发 生什么事情呢？琼斯会卷土重来！是的，琼斯会卷土重来！真的，同志们！”

-----

拿破仑默默地来回 踱着步，偶尔在地面上闻一闻，他的尾巴变得僵硬，并且还忽左忽右急剧地抽动，对他 来说，这是紧张思维活动的表现。突然，他不动了，似乎心里已有了主意。 “同志们，”他平静地说，“你们知道这是谁做的孽吗？那个昨晚来毁了我们风车 的仇敌你们认识吗？斯诺鲍！”他突然用雷鸣般的嗓音吼道：“这是斯诺鲍干的！这个 叛徒用心何其毒也，他摸黑爬到这儿，毁了我们近一年的劳动成果。他企图借此阻挠我 们的计划，并为他可耻的被逐报复。同志们，此时此刻，我宣布判处斯诺鲍死刑。并给 任何对他依法惩处的动物授予‘二级动物英雄’勋章和半莆式耳苹果，活捉他的动物将 得到一整莆式耳苹果。”

-----

“那么，同志们，你们已经听到我们猪现在睡到庄主院床上的事了？为什么不呢？ 你们不想想，真的有过什么诫律反对床吗？床只不过是指一个睡觉的地方。如果正确看 待的话，窝棚里的稻草堆就是一张床。这条诫律是反对被褥的，因为被褥是人类发明的。 我们已经把庄主院床上的被褥全撤掉了，而睡在毯子里。它们也是多么舒服的床啊！可 是同志们，我可以告诉你们，现在所有的脑力工作得靠我们来做，和我们所需要的程度 相比，这些东西并不见得舒服多少。同志们，你们不会不让我们休息吧？你们不愿使我 们过于劳累而失职吧？肯定你们谁都不愿意看到琼斯回来吧？” 在这一点上，动物们立刻就使他消除了疑虑，也不再说什么有关猪睡在庄主院床上 的事了。而且数日之后，当宣布说，往后猪的起床时间要比其他动物晚一小时，也没有 谁对此抱怨。

-----

‘英格兰兽’是起义用的歌。但起义 已经成功，今天下午对叛徒的处决就是最后的行动。另外仇敌已经全部打垮了。我们在 ‘英格兰兽’中表达的是在当时对未来美好社会的渴望，但这个社会现在已经建立。这 首歌明显不再有任何意义了。”

-----

在庄园里， 把每遇到一件幸运之事，每取得一项成就的荣誉归于拿破仑已成了家常便饭。你会常常 听到一只鸡对另一只鸡这样讲道：“在我们的领袖拿破仑的指引下，我在六天之内下了 五只蛋”，或者两头正在饮水的牛声称：“多亏拿破仑同志的领导，这水喝起来真甜！”

-----

不论在什么情况下，他都毫不费力地向其他动物证明，无论表面现象是什 么，他们事实上并不缺粮。当然，暂时有必要调整一下供应量（斯奎拉总说这是“调整”， 从不认为是“减少”）。但与琼斯时代相比，进步是巨大的。为了向大家详细说明这一 点，斯奎拉用他那尖细的嗓音一口气念了一大串数字。这些数字反映出，和琼斯时代相 比，他们现在有了更多的燕麦、干草、萝卜，工作的时间更短，饮用的水质更好，寿命 延长了，年轻一代的存活率提高了，窝棚里有了更多的草垫，而且跳蚤少多了。

-----

但是，当年谈论风车时，斯诺鲍引导动物们所想像的那种享受 不尽的舒适，那种带电灯和冷热水的窝棚，那种每周三天工作制，如今不再谈论了。拿 破仑早就斥责说，这些想法是与动物主义的精神背道而驰的。他说，最纯粹的幸福在于 工作勤奋和生活俭朴。

