#+title: Atlassian $5.5b user onboarding magic

[原文链接](http://www.appcues.com/blog/atlassian-5-billion-dollar-user-onboarding-magic/)

**先看看这个公司的表现**

> While the median SaaS company spends between 50-100% of their annual revenue of sales and marketing, Atlassian has spent between 12 and 21% of their revenue on customer acquisition in the last three years. These metrics simply unheard of.

> Atlassian spends aggressively in research and development, investing more than 40% of revenues of late into improving their products, optimizing the funnels which fuels the growth [its business model].

> Atlassian has grown to $320M in annual revenue with virtually no sales team. Damn.

在过去三年内只使用了12-21%的收入用于客户买入，而其他中型SaaS的公司这个比例则在50-100%.  同时投入超过40%的收入用于开发和改进自己的产品。现在收入规模是每年$320M。

**然后公司的几个主打产品**

- **JIRA** is a project management tool to help teams collaborate (similar to Asana)
- **HipChat** is a team chat tool (similar to Slack)
- **Confluence** is a wiki-style knowledge base for teams (similar to SharePoint)
- **BitBucket** is a code collaboration tool for teams (similar to GitHub)

**产品方面设计优点**

- Try before you buy
- Simple Sign Up Process
- Explaining key parts of the interface 将CS的概念/术语翻译成用户可以理解的词语
- Driving users to take meaningful action 每个产品都精心地设计了一个task, 用户完成后就可以使用产品的核心功能了。

`产品简单并且容易上手` 就是onboarding magic

-----
虽然这家公司做的产品不错，但是股价却不怎么样。我在这只股上亏损了将近$4k.

file:images/atlassian-stock-price.png
