#+title: Avoiding burnout: lessons learned from a 19th century philosopher

https://codewithoutrules.com/2018/09/27/avoiding-burnout/

文中很多词汇都不太懂。大致有这么几点：

不要将焦点放在如何获得快乐这个目的上，而更应该关注过程和你关心的事情上。
#+BEGIN_QUOTE
Mill’s first conclusion was that happiness is a side-effect, not a goal you can achieve directly, nor verify directly by rational self-interrogation. Whenever you ask yourself “can I prove that I’m happy?” the self-consciousness involved will make the answer be “no”. Instead of choosing happiness as your goal, you need to focus on some other thing you care about:

It’s worth noticing that Mill is suggesting focusing on something you actually care about. If you’re spending your time working on something that meaningless to you, you will probably have a harder time of it.
#+END_QUOTE

做事情之前不能计较太多或者说过分思考。过分思考可以制定严密的计划，但是却也容易产生恐惧降低兴趣。
#+BEGIN_QUOTE
On the one hand, rational logical thought is immensely useful in understanding the world: “it enables us mentally to separate ideas which have only casually clung together”. But this ability to analyze also has its costs, since “the habit of analysis has a tendency to wear away the feelings”. In particular, analysis “fearfully undermine all desires, and all pleasures”.

Why should this make you happy? You try to analyze it logically, and eventually conclude there is no reason it should—and now you’re no longer happy.
#+END_QUOTE

通过自然和艺术来培养和提升你的感受力。
#+BEGIN_QUOTE
Mill’s second conclusion was that logical thought and analysis are not enough on their own. He still believed in the value of “intellectual culture”, but he also aimed to become a more balanced person by “the cultivation of the feelings”. And in particular, he learned the value of “poetry and art as instruments of human culture”.

Both nature and art cultivate the feelings, an additional and distinct way of being human beyond logical analysis:
#+END_QUOTE

总结下来就是:
- Aim in your work not for happiness, but for a goal you care about: improving the world, or even just applying and honing a skill you value.
- Your work—and the rational thought it entails—will not suffice to make you happy; rational thought on its own will undermine your feelings.
- You should therefore also cultivate your feelings: through nature, and through art.
