#+title: aws ec2的几种实例

[aws ec2 定价](http://aws.amazon.com/cn/ec2/pricing/)

专用主机(dedicated-hosts)就不说了，这个应该是物理主机，其他三种实例都是虚拟主机。
- 专用实例(dedicated-instance). 这个是按需付费，并且每个小时的费用是固定的。适合产品初期，不知道要用多少实例，也不知道要用多久。
- 竞价实例(spot-instance). 同样是按需付费，但是每个小时的价格是浮动的。只要你的出价高于当时的实例价格，那么实例就可以一直运行，否则就会终止。比较适合离线batch job, 比如运行MapReduce/Spark来做数据分析, 或者跑个caffe做深度学习等。
- 预留实例(reserved-instance). 预先(up-front)付费.  预先支付越多，那个均摊到每个小时计算费用越低。比较适合产品中后期，知道自己大概需要多少实例，以及要运行多长时间。

这些说的都是计算费用，还有网络传输费用以及存储费用。前面两个按需付费的实例，如果不运行(stop)那么是不会有任何计算费用/网络费用的。但是会收取EBS的费用，因为你的代码和系统都存在EBS上. EBS定价可以看[这里](https://aws.amazon.com/cn/ebs/pricing/)

----------

https://docs.amazonaws.cn/AmazonS3/latest/dev/aws-usage-report-understand.html

Amazon S3 账单和使用率报告使用代码和缩写。例如，对于在下表中定义的使用类型，region 将被替换为以下缩写之一：
- APN1: 亚太区域（东京）
- APN2: 亚太区域（首尔）
- APS1: 亚太区域（新加坡）
- APS2: 亚太区域（悉尼）
- APS3: 亚太地区（孟买）
- CAN1: 加拿大 (中部)
- EUC1: 欧洲（法兰克福）
- EU: 欧洲（爱尔兰）
- EUW2: 欧洲 (伦敦)
- EUW3: 欧洲 (巴黎)
- SAE1: 南美洲（圣保罗）
- UGW1: AWS GovCloud (US-West)
- USE1 (or no prefix): 美国东部（弗吉尼亚北部）
- USE2: 美国东部（俄亥俄州）
- USW1: 美国西部（加利福尼亚北部）
- USW2: 美国西部（俄勒冈）

----------

EC2 归一化因子 NormalizationFactor

https://docs.aws.amazon.com/zh_cn/awsaccountbilling/latest/aboutv2/enhanced-lineitem-columns.html

#+BEGIN_QUOTE
lineItem/NormalizationFactor

AWS 可将所有区域 Linux 或 Unix Amazon EC2 和 Amazon RDS RI 折扣应用于某个实例系列和 AWS 区域内的所有实例大小，前提是实例具有共享租赁。这也适用于组织中的成员账户的 RI 折扣。对于所有新的及现有 Amazon EC2 和 Amazon RDS 大小灵活的 RI，其大小将根据基于实例大小的标准化因子调整。下表显示 AWS 对每个实例大小应用的标准化因子。

适用于 Amazon EC2 大小灵活的 RI 的标准化因子
#+END_QUOTE

| 实例大小 | 标准化因子 |
|----------+------------|
| nano     |       0.25 |
| micro    |        0.5 |
| small    |          1 |
| medium   |          2 |
| large    |          4 |
| xlarge   |          8 |
| 2xlarge  |         16 |
| 4xlarge  |         32 |
| 8xlarge  |         64 |
| 10xlarge |         80 |
| 16xlarge |        128 |
| 32xlarge |        256 |

s, m, l 分别是1, 2, 4, 然后xl, 2xl就是8, 16这个系数
