#+title: 睡眠训练实战操作经验

http://www.aibaimm.com/thread-131966-1-1.html

** 写在开头的话
这是一篇综合性宝宝睡眠总结帖，帖子主题是一直有很大争议的“睡眠训练”，以个人实践经历为主，同时也记录和引用了许多其它权威专家观点以及深入了解研究过宝宝睡眠的妈妈们的经验。写这篇东西需要下很大决心，一来耗费时间与精力会很大，二来估计会引来许多极端主义者的拍砖。然而，促使我做这么费劲的一件事儿的主要原因，是我太深刻地了解：如果一个妈妈拥有一个很难入睡、夜醒无数的宝宝，她是多么需要有人理解以及可能存在的帮助，毕竟过去这半年多以来，我一直是这样过来的，没被产后抑郁击中，那已是万幸。

其实育儿是件挺私人的事儿，每家都有自己的方法，每个人的理念和观点也会不同，包括每个孩子的性格与特点都不一样，所以，我分享我的经验和方法，是给真正需要的妈妈参考；如果你的育儿理念与我相差太大，你家宝贝也不存在睡眠问题，你或许并不理解并认同我说的这些，也请你不要随意进行攻击，你可以就当没看见，绕道离开即可，谢谢。如果有妈妈遇到类似问题，想一起交流，可以加我微博：林小暖Bella （也可以直接去微博看帖，这里转过来之后格式不太方便看哈～）

** 为什么要进行睡眠训练？
*** 潼妞糟糕的睡眠情况
几乎我所有的朋友都知道我家潼妞在睡眠问题上一直是个“恶魔宝宝”，半岁的她白天一觉就半小时，一晚夜醒七、八次那是平常事儿，十几次也是司空见惯，有时甚至刚睡着几分钟就醒。而每次醒来，她根本不会自己接着睡，而是直接叼上她的专属人肉安抚奶嘴——neinei，基本整夜不撒嘴，像是没睡着一样。

而我，又恰巧是一个入睡相当难的人，她这半小时一小时的醒，基本上我连进入睡眠状态的时间都达不到，即使是躺喂，也根本睡不着觉。往好了说，一晚上我能睡个三小时那就是幸福的了。而且每晚七八点她一睡觉我就必须陪着，时刻躺在旁边当奶嘴，无法与家人有任何交流、放弃一切自己的爱好、一周洗一次头、洗澡一次两分钟、吃饭五分钟……长期缺乏睡眠让我心情极度郁闷，经常焦躁，甚至有压抑不住的暴力倾向（但凡是一个正常人长期缺乏睡眠都会如此吧）。当然，对待宝宝我需要一如既往的耐心，这些压抑和压力只能向自己与其它家人发泄。

如果说我自己遇到的这些客观困难我还能够凭着当妈的奉献精神一一克服的话，这样的睡眠模式对潼自己的影响却让我无法视而不见。潼从两个月开始打疫苗就在医院对生长发育情况做过生长曲线，她的身高在前四个月都是97%的上限，体重在50%平均值，然而自从她从四个月开始超频繁夜醒、夜奶无数之后，她的身高曲线迅速下降，体重曲线却一直上升；同时每天她都顶着两个青色的大眼袋，白天也呵欠连天，自己能专注地玩儿的时间越来越短，哭闹越来越多。

最让我担心的是这一睡眠问题对她日后的影响，一来婴儿时期是她身体与大脑等各方面发育最快速的时期，如果没有良好的睡眠很容易对生长发育有影响；二来我自己就是一个很难入睡的人，我深知这其中的痛苦，我很怕如果她现在在婴儿时期学不会自己睡觉，以后也会变得像我一样，那将是一生的痛苦。

*** 睡眠习惯对于婴儿的重要性
相信大家都能认同，睡眠对于人类的重要性，如果你一晚上醒来个十几回，早上起来之后很可能会感觉像是没睡过一样。即使是这样的睡眠状况只出现了一天都会让一个成年人感觉筋疲力尽，那如果持续几个月，你觉得这是不是大问题？

推己及人，如果这样的情况发生在你的宝宝身上，你是否能够体会她的感受？更何况，这是一个才几个月大的宝宝，她还处于大脑和身体都快速生长发育的时期，她的中枢神经还没有发育完全，可她却得不到良好的睡眠和休息，甚至无法得到持续几个小时的连续睡眠，你认为，这些难道不会对她的生长发育造成影响？

全美最著名的儿童睡眠和发展研究专家、35年儿科临床经验的马克·维斯布朗博士在《婴幼儿睡眠圣经》里提到：
#+BEGIN_QUOTE
对于婴幼儿来说，如果长期缺乏睡眠，会影响他们认知能力的发展。良好的睡眠习惯对孩子大脑的发育很重要，孩子在童年缺乏睡眠的恶果不会立刻显现，可能要在成人之后显现出来。不良睡眠习惯与孩子在校表现不佳有关，如注意力不足、多动症或是学习障碍。睡眠问题会导致孩子反应不够灵敏、难以集中注意力、很容易分神，也会造成孩子易冲动、多动，或者懒惰。而如果孩子能够得到充分的睡眠，就会保持最佳的觉醒状态，机敏，能顺利完成学习任务。
#+END_QUOTE

当然，如果你的宝宝只是一晚上醒个两、三回，吃几分钟奶就能接着自己入睡，那这完全不在我所探讨的糟糕睡眠的范围之列。

*** 睡眠训练的必要性
关于这个话题，我觉得每个妈妈都会有自己的判断。你的孩子睡眠情况到底是不是糟糕到了根本不能忍受的地步？是不是对她的成长以及你的生活带来了巨大的负面影响？这样的状态持续下去会不会造成你们家庭的大问题？这些问题对每个家庭来说都有不同的答案，所以，到底要不要开始睡眠训练，要问你自己的内心。如果你觉得问题没那么严重，那自然可以不考虑睡眠训练；而如果你已经在长期忍耐，那你可以考虑花时间看完我这篇帖子再做打算。

当一个宝宝白天晚上都不好好睡觉时，很多老人们都会说，这是宝宝天生不爱睡觉，事实上真的是这样么？说起来，在不同宝宝之间的确存在个性差异，有的孩子天生安静爱睡，很小的时候就能自己入睡，中途醒来也能自己接着睡去，如果你有一个这样优质睡眠的宝宝，那就谢谢上帝吧。然而如果你的宝宝入睡困难，哄睡也很难，即使好不容易睡着了也很容易醒来，那她的确是天生不需要那么多睡眠么？答案往往是否定的，尤其是如果她在醒来之后仍然哭闹，无法自己单独玩一段时间，或是很快就揉眼睛表现出不耐烦的样子，那就说明她仍然处于疲倦状态，需要更多的睡眠。真正睡够的孩子在醒来的时候应该是安静的，或是自己能自言自语躺着玩一会儿，在你去察看的时候看见你就会笑，这样的睡醒才是真正睡够的表现。

不管孩子天生是“猫头鹰”还是“云雀”，他们每个阶段需要的睡眠时长其实相差无几，顶多一天相差一两个小时（具体每个年龄阶段平均睡眠时长我会在后面的“规律作息”里涉及），如果相差太多，那一定是宝宝的睡眠习惯出现了问题。

那么另一个问题是：是不是宝宝睡眠不好只是某一个年龄阶段的常见问题，过了这段就好了？这个问题应该可以向那些经历过的妈妈咨询，就我所知，许多在几个月大的时候睡眠不好的孩子即使长到了一岁、两岁、甚至三五岁，仍然被睡眠问题困扰着。如果说我个人的了解还比较粗浅、不具有代表性，那以下文字也许能从权威观点给你以参考：
#+BEGIN_QUOTE
不要简单的以为孩子在不同年龄段必须经历相应阶段的睡眠问题，事实上，过了三四个月大，所有宝宝都可以开始学习如何更好地睡眠，这个学习的过程会像孩子学走路一样自然发生。孩子学习走路时，需要花时间来发展力量、发展协调性、平衡性以及自信心。同样，你的孩子想要睡得沉，也需要花时间培养夜间睡眠、白天规律的小睡习惯，以及自我入睡的技巧。

预防和纠正婴儿的不良睡眠习惯非常重要，因为如果不及时纠正，这些习惯就很难根除。孩子是不会自动纠正这些不健康的习惯的，他们不会自己摆脱这些问题。如果父母对孩子进行纠正，不良睡眠给孩子带来的伤害就会减少，孩子年龄越小，纠正不良睡眠习惯的成功率就越高。

无休止的等待总不是办法，如果你的宝宝睡眠不好，你也不想纠正，那么请自问：如果放任不管，任由宝宝自己调整好睡眠，需要多长时间？3个月还是3年？如果有专家告诉你，为了让宝宝觉得安全，你应当尽量在夜里尽可能陪着宝宝，那就要问问这个专家，如果这样做，在多长时间以内，宝宝可以建立良好的睡眠习惯。

——《婴幼儿睡眠圣经》马克•维斯布朗
#+END_QUOTE

而美国亚马逊最长销的婴儿睡眠书籍《法伯睡眠宝典》的作者、哈佛医学院神经学教授、美国波士顿儿童医院儿童睡眠障碍中心主任、从事儿童睡眠研究20多年的理查德•法伯教授也这样写道：
#+BEGIN_QUOTE
如果孩子在三个月之后还不能自已入睡，夜间频繁哭闹，家长就要注意了，因为一般情况下这个年龄的孩子已经可以自己入睡了。如果到了5个月，孩子还是夜间频繁醒来，家长就必须采取应对措施。       儿童的睡眠障碍既不是家长的失职，也不是一个所谓的“自然阶段”能等它自然度过。儿童睡眠状况不仅会影响其以后的行为习惯，更会影响家长对孩子的评价。这种评价很容易影响家长对孩子的态度，如果孩子有睡眠问题，家长就会焦躁不安，如果夜夜都要起来照顾一个哭闹不休的孩子，反复起来安抚他，家长的睡眠就会完全被剥夺，如果情况严重，家长的负面情绪还会延续到第二天白天，他们会感觉心力交瘁。如果你正在遭受如上所说的痛苦生活，那我可以肯定地告诉你，你的孩子可以睡得更好，你也可以。

——《法伯睡眠宝典》理查德•法伯
#+END_QUOTE

以下观点来自德国实用育儿经典书籍《每个孩子都能好好睡觉》，作者一位是心理学硕士、提供父母咨询与儿童辅导的行为治疗师，另一位是有20多年临床经验的儿科大夫。
#+BEGIN_QUOTE
我们的调查反映出一个事实：宝宝的睡眠问题在3岁之前不会自动消失，如果半岁大的宝宝还不能一觉到天明，可以预见的是，一年后的夜里父母还是会围着宝宝团团转。

——《每个孩子都能好好睡觉》
#+END_QUOTE

除了国外的专家们给出的这些几乎相同的建议以外，我也想提及国内一些知名医学专家们的观点：
#+BEGIN_QUOTE
北京协和医院儿科主任鲍秀兰一直在微博上向大家介绍睡眠训练的方法，她的方法其实类似我后面会说到的理查德·法伯一直推崇的“哭泣控制法”；而一直被各位妈妈们频繁请教与咨询的著名儿科大夫张思莱，也认同鲍秀兰的睡眠训练方法；潼妞四个月时感冒，我们曾经带她去看过天津儿童医院创办人之子、权威儿科专家范崇济主任，提及了潼的睡眠问题，他明确表示这种情况可以通过两三天的睡眠训练快速解决，而他提供的方法类似马克•维斯布朗博士的方法，cry it out，也就是传说中的哭声免疫法；潼六个月时打疫苗，预约的大夫是和睦家首席儿科大夫崔玉涛，听到潼的睡眠情况，他表示说这是孩子的睡眠习惯问题，大部分是养育人过度纵容造成的问题，他同时也认为这样的情况可以通过两三天的睡眠训练得到改善。
#+END_QUOTE

除了专家观点之外，我也想简单聊聊一些感性上的看法。一提起睡眠训练就会有人问，睡觉明明是天生的本能，有什么需要训练的？微博里有个叫“爱莘麻麻”的朋友，她是英国心理学的博士，她曾经针对这个问题这样写道：“我们都有吃饭睡觉的本能，但本能只是一种学习的渴望和潜力，这种潜力只有在适当的环境，给予一定的引导和支持，再有足够锻炼的情况下，才能发展成为能力。”

她同时提及了一个案例，一个孩子从小失去所有亲人，被一个养狗的男人领养，养狗的男人完全不懂得养孩子，只好把男孩跟狗一样关在笼子里饲养，导致男孩五岁了仍然不会说话和走路。那说话和走路明明是人的本能，为什么男孩不会？因为没有锻炼的机会，男孩就没办法把本能发展成为能力。事实上，睡眠能力的养成，也是如此。

也许以上的文字已经给了你答案，当然，如果你仍然认为孩子的睡眠习惯不是问题，你和宝宝都可以照此情况坚持下去，并且这不会对你的宝宝和你的家庭造成巨大影响，那么也请你尊重自己的内心。

对于我来说，给孩子进行睡眠训练是经过长期考虑而做出的选择，这个选择也得到了家人（尤其是我的先生和婆婆）的支持，他们最能够体会到孩子的不良睡眠习惯对孩子自身以及整个家庭里每个人造成的影响。在这里我想提醒一下：如果整个过程你想凭一己之力坚持下来那是不可能的，你必须需要家人的支持和鼓励。所以，如果你们没有真正想好，下定决心，那一定不要开始。

** 睡眠训练会对孩子的心理造成伤害吗？
*** 如何看待让孩子哭？
说到这个问题，咱们可以先从怎么看待“让孩子哭”开始说起。

首先，我想说睡眠训练的一个前提，那就是睡眠训练开始的时间。除了台湾大热的育儿书、引述全美最有经验的百岁儿科医师丹玛观点的《百岁医师教我的育儿宝典》推荐可以从新生儿就开始用cry it out方法进行训练以外，其它的各种睡眠训练方法都是建议在孩子三四个月大以后进行训练，为了保守起见，如果你打算用哭免，最好在孩子六个月以后进行睡眠训练，因为这时候的孩子懂得了物体永恒，不会因为妈妈的离开而觉得恐慌。而八个月之后进行睡眠训练的话难度会加大，因为有的孩子会站起来或是爬出小床了。

当然，睡眠训练肯定免不了让孩子哭，即使是“无泪法”，也难免会让孩子哭一会儿。相信大家也能够理解，如果想要解决一个长期的不良习惯，一开始肯定是很艰难的，就像抽烟的人戒烟、或是一直睡懒觉的人突然必须早起一样，想让孩子突然从依赖你抱着悠着哄着入睡或是吃着neinei入睡，突然变成要自己躺在床上入睡，这一定是一件不容易的事儿。对于孩子来说，他也只会用哭来表达自己的不舒服和不习惯，那么让孩子在睡眠训练时期哭一会儿是否值得呢？对于这个话题，还是用马克·维斯布朗博士的两段话作为开场：
#+BEGIN_QUOTE
哪个父母也不愿意孩子哭，从长远来看，鼓励孩子形成良好的睡眠习惯会使孩子哭得更少。但在治疗孩子不良睡眠习惯的初期，孩子可能会哭得更多，但睡眠次数是增加的。等孩子形成良好的睡眠习惯后，就不怎么哭了。

要想让孩子保持良好的睡眠习惯，父母的态度必须坚决，不要担心孩子因此恨你，或是不那么爱你。事实上，治疗睡眠问题的最佳药方是：建立一个孩子和父母都充分休息、充满爱的家庭。
#+END_QUOTE

套用一句老话，长痛不如短痛，与其每次让孩子在睡觉前都因为“闹觉”而哭，这样的时间持续几个月甚至几年，那么为什么不选择只让孩子在睡眠训练时期哭几天呢？“我们都能认同在学习走路的过程中偶尔有些磕碰是正常的，但在学习睡觉的过程中让孩子哭几声却为什么又那么不可接受呢？”这笔帐，相信每个妈妈都能算清楚。
#+BEGIN_QUOTE
有些人认为，让宝宝一直哭很残忍，其实刚好相反，我们认为不训练宝宝一觉到天明才是残忍，因为爱宝宝，才要训练他一觉睡得久一点。一觉到天明的宝宝可以得到较多的休息，会更满足，更健康。

——《百岁医师教我的育儿宝典》
#+END_QUOTE

对于孩子在睡眠训练时期的哭，另一本书《从零岁开始》专门用了一个章节来叙述，这本书也是对我震撼相当大的，我会在后面的“育儿观念”里详细说，在这里我仅仅引述它对于孩子哭的一些描述：
#+BEGIN_QUOTE
想要让宝宝尽量少哭，或完全不哭，很容易使宝宝紧张，特别是情绪的眼泪可以带出体内化学的活化紧张荷尔蒙。我们个人不喜欢听见宝宝哭，但是我们了解有些时候，宝宝甚至需要一场好哭。
#+END_QUOTE

真正爱孩子的父母如果为了宝宝更大的好处(例如宝宝需要小睡)，应该稍微忍耐一下宝宝哭。发展好的睡眠习惯很重要。付上让宝宝哭一会儿的少许代价，与建立健康的小睡模式及用睡过夜换来的健康利益，是无法相较的。
身为父母的，你将学会如何辨认你孩子不同的哭声，且能够充满信心来做反应。聪明的父母将倾听、思想、然后采取行动。如果你的宝宝吃饱了，身体干净了、尿布没有湿，且很健康，但是在入睡以前哭，你就可以考虑那是正常发展的一个阶段。

关于睡眠训练期间难免会让孩子哭这个问题，我也曾经与先生进行过交流和讨论。我们最终都获得了这样的观念认同：在孩子成长的过程中，哭泣是在所难免的，尤其是当父母不能满足孩子的非正常要求，或是帮助孩子建立良好的行为习惯时。

比如说，让孩子坐汽车安全座椅，孩子不习惯会哭闹，那就真的不顾危险不让她坐了？孩子想玩一些尖锐的物品，你从她手里夺走她马上大哭，那就接着交到她手里让她把玩吗？生病打针会疼，打疫苗也会疼，那因为害怕孩子哭闹就不打了吗？孩子非得要一样非必要的东西，以致在商场里哭闹打滚，那为了不让她哭就马上买给她吗？以上这些问题，在孩子成长的过程中还会有许多，那我们就把睡眠训练当成改变孩子不良习惯的第一关吧。

看到这儿也许你也开始认同，为了让孩子获得更好的睡眠，付出哭一会儿的代价应该是值得的，那么另一个问题又来了——

*** 睡眠训练时期的哭会不会造成心理创伤？
这个问题，相信是所有打算进行睡眠训练却又一直犹豫的妈妈们唯一考虑和担心的问题，同样也正是因为这种纠结，我对潼的睡眠训练从两个多月开始就计划，直到半岁以后才开始正式实施。

当然，这个问题的前提是：只是在睡眠训练期间让孩子哭一会儿，而不是引申在整个生活中对孩子的哭泣都不予理会。如果真的按照之前流传的那个什么坑爹的“美国妈妈带孩子的多少个绝招”里说的那样，哭的时候不抱，不哭的时候才抱起来，那一定是脑袋坏掉了的妈妈，这种情况不在我们正常讨论的范围之列。

对于在睡眠训练期间让孩子适当哭一会儿的这个问题，有些人曾经在毫无理论论据以及实例证明的前提下提出过一些耸人听闻的观点，比如说这会造成孩子精神上的问题，或是让孩子没有安全感、与父母疏离等等。我其实一开始在这里想好好写写那个制造这类观点的某位心理咨询师，但想了想还是算了，没必要，一个根本不是研究婴儿心理学的人突然跳出来把自己当成既能解决成人心理问题，又能解决儿童和婴儿的心理问题，还莫名其妙抛出一堆自己臆想的观点，这样的人的说法真的可靠么？这个需要各位妈妈自己分析。也许她的其它的一些观点有正确的地方，包括我也认同爱与·自由的教育理念，但仅就睡眠训练这一个观点上，我认为她是相当不负责任的。更可笑的是，她曾在微博上盛赞某位妈妈真正了解爱与自由的真谛，让自己的孩子成长得非常快乐并与妈妈之间充满信任安全感，然而后来据这位妈妈所说，她是从月子里就开始实行改良版的cry it out方法训练孩子睡眠，而这一行为在促进孩子睡眠之外也没有产生任何所谓安全感、信任感的缺失。因此我也希望大家多去了解真正权威的儿科医生、专家，以及真正研究婴儿心理的心理咨询师的观点，而不是被这种无依据的论点蒙蔽。

回归正题，真相究竟是怎么样的呢？作为英国心理学博士，“爱莘麻麻”曾经整理过一篇发表在美国《时代》杂志上的文章，这是美国儿科学会出版的《儿科》学术期刊研究的最新结果，翻译摘录如下：（原文地址 http://pediatrics.aappublications.org/content/130/4/643）
#+BEGIN_QUOTE
让婴儿有限制地哭泣的训练法可以在短期内帮助婴儿学会自主睡眠，不会造成长期的心理损伤，也不会伤害孩子和父母之间的亲密关系。这项研究着眼于两种训练睡眠的方法，分别为“控制哭泣法”和“逐渐远离”法，两种对策都是让婴儿在短时间内哭个够。“控制哭泣法”要求父母每隔段时间回应孩子的哭泣，而间隔的时间逐渐延长，以试图鼓励孩子自己能够安心下来；在逐渐远离法中，父母静坐在孩子旁边的椅子上，让孩子学着去入睡，慢慢地，随着时间的过去，父母把椅子搬离的越来越远，直到最后离开房间，婴儿独自进入睡眠。

这项由澳大利亚研究人员进行的研究涉及了326个小孩，他们的父母在7个月内报告了睡眠问题。一半的小孩在睡眠训练小组内，他们的父母学会了一些有用睡前习惯以及受控安慰法或逐渐远离法的技巧（父母可以选择他们使用哪种对策），另外一半小孩在对照组中，不使用任何睡眠训练方法。研究人员追踪了这些参与者及其父母们五年。（到研究结束，大约30%的家庭放弃了。）

到那些孩子6岁的时候，研究人员并没有发现这两组孩子在情绪健康，行为或是睡眠问题方面存在重大的差异。事实上，对照组中的孩子拥有情绪或行为问题比睡眠训练组中的孩子稍微多一些。

与此同时，这项研究的早期数据显示睡眠训练确实是起作用的：婴儿学会了在睡觉时更容易地入睡并且在晚上能够熟睡得更久。基于这些发现，作者认为睡眠训练是既安全又有效的，呼吁更多的家长接受这些方法的教育，并希望健康专家能够提供更多的培训来推荐这些方法。
#+END_QUOTE

与一些人的主观推测和臆想相比，以上文章的立场和研究结果应当是相当客观的，值得作为参考依据。另外，在其它的几本睡眠书籍里，这些身为儿科医生的作者们也有过类似的记载：
#+BEGIN_QUOTE
没有任何的证据证明孩子一哭，妈妈立即反应，可以教导孩子关于爱的任何东西，正如没有证据证明让孩子哭一下子，会使孩子觉得没有安全感。孩子学习爱及得到安全感，乃是来自于父母和孩子间整体的关系，而非单一的特别事件。

宝宝哭了15～20分钟，甚至30分钟，并不会对他的身心造成伤害，特别如果是哭哭停停的哭法。宝宝并不会因此丧失一些脑细胞，或智商变低，或是觉得被拒绝，而在30岁时得忧郁症。你在宝宝醒着时，对他的爱及照顾，并不会因为让他哭几分钟而一笔勾销。相反的，如果你想要一个常常哭闹的宝宝，你可以在他一哭闹时，便立刻抱他、摇他、喂他，一点儿都不要让他哭，这样我们保证你一定可以达到你的目标。
——《从零岁开始》

 孩子不会受到什么伤害，相反的，他们会开始觉得有安全感，当孩子知道一切都是由父母掌控时，他们就会觉得有安全感。如果你希望宝宝有安全感，你的做法就要一致。如果宝宝每次一哭你就紧张兮兮，宝宝很快就会知道这个家是谁在做主，他会养成习惯，用哭来得到他想要的东西，但这些得到掌控权的孩子，在长大后却反而容易没有安全感，因为他们其实并不知道自己想要什么，因为父母没有为他设定界限。
——《百岁医师教我的育儿宝典》
#+END_QUOTE

另外，即使自己静心想想，短短几天的睡眠训练时期的短暂哭泣，真的会影响到孩子的整个性格？从非专业的角度来说，这个说法都是站不住脚的。如果真是这样，父母为了避免让孩子哭，在孩子提出无理要求的时候也无条件答应，那结局应该不是我们想看到的吧？

如果以上的这些内容已经能够打消你心里的顾虑，让你终于决定为了孩子以及整个家庭着想而着手纠正孩子的不良睡眠习惯，那么相信你学会的不仅仅是如何教会孩子正确的行为，还有如何倾听孩子内心的声音，以及尊重自己作为父母的需要。如果你仍然犹豫，那或许说明你家宝宝的睡眠情况还不算太糟糕，没有对他的生长发育以及你们的生活带来灾难性的影响，那么你仍然可以选择维持现状。

如果看到这里你还是决定继续，那么咱们接下来说说—
** 如何进行睡眠训练？
这个话题相当大也相当复杂，各个流派的方法都有，而且一个观点就能写出一本书来，因此，我如果想要用较短篇幅来介绍这个问题，就只能有所侧重，而不能顾及全面。我会尽量简洁却完整地介绍有关睡眠训练的各家之言，如果你选择了某种训练方法，建议你可以去买这个方法的书籍来详细参考，这样应该会更加可靠。

为了鼓励你，先借用《每个孩子都能好好睡觉》这本书的第一句话：“每个健康的孩子自6个月大都能学会好好睡觉，而且通常只需要几天的时间，就可以让孩子独自入睡并睡到天亮。”但是同时也希望你做好心理准备，用《法伯睡眠宝典》里的话来说：“充分认识到这是一个辛苦的过程，要抱着体谅的心态，耐心的坚持下去。”

*** 睡眠训练的前提
我想再次声明睡眠训练的前提：孩子满六个月（当然有的方法声称可以更早，你可以自行决定），且没有任何身体上的疾病与情绪上的不适（长牙、搬家、换保姆等等）；你与孩子已经建立起了良好的信任关系，同时你的家庭关系是和睦健康的，孩子也不会时常感到焦虑或是紧张（否则孩子晚上哭闹也许是为了赢得父母的关爱和注意）。

另外，睡眠训练需要全家齐心，父母意志力也要足够坚强，并有相当的理智与清醒能判断所有状况；一旦制定计划就要坚持到底，否则半途而废只会让孩子和父母都白受罪。如果这些条件都满足，那么咱们来探讨第一个问题——

**** 找到孩子睡眠问题的原因
想要解决孩子的睡眠问题，第一步自然是找到原因，对症下药。对这个问题，大家可以看看美国的超级保姆特蕾西写的那本《实用程序育儿法》，里面有专门的章节。另外，关注宝宝睡眠的草根妈妈@小土大橙子 也对此进行过很详细的穷举排查法的说明，如果有兴趣大家可以去她的微博找来看看。我简单列举一下可能影响宝宝睡眠的因素，大家可以对照参考，找到原因才好解决。

- 缺乏常规程序：作息不规律、入睡前刺激过多（睡前半小时不逗玩尽量保持安静）、错过睡眠时机（学会观察宝宝犯困信号）、醒着时间太长过度疲倦（各月龄孩子清醒时间下文会提及）、运动量不够（导致不够疲惫难以入睡）、没有睡前例行程序（没有从活动到静止的过度，具体下文细说）；

- 睡眠工具依赖：简单地说，孩子入睡时的环境是什么样的，她醒来时就希望还保持这样的环境，否则就无法入睡。常见的睡眠工具依赖有：抱哄晃悠入睡（相当常见，孩子醒来也希望有人抱着晃）、安抚奶嘴（如果奶嘴掉了孩子就醒来哭闹就是依赖）、过度响应（有时候孩子睡觉时突然哭几声不用着急安抚，他可能自己马上接着睡着）。当然，并不是所有的孩子都会因为睡眠环境而产生依赖，这需要你对照自己宝宝的实际情况判断。

- 夜间哺乳：其实这也是睡眠工具依赖的一种，只是因为太典型所以专门拿出来说。夜间哺乳过频容易让孩子将哺乳与入睡联系起来，只能吃奶才能睡着；奶量摄入过多容易导致尿多、醒得更频繁，从而恶性循环；频繁进食刺激消化系统，影响其它身体器官，最终导致身体许多生理节律出现问题，影响睡眠。

- 身体原因：胃食管返流（严重吐奶）、肠绞痛（四个月以内的孩子肚子疼莫名大哭）、长牙、发热、湿疹、尿布疹、便秘、营养缺乏（除了生长极其快速的孩子，其它宝宝六个月以内不会缺钙，除非没补充VD。六个月以后的宝宝只要辅食添加得当也不会缺钙）、大运动发展（学习翻身、爬、站、走路等时期都容易导致晚上练习）、大脑跳跃期（20个月以内会有十次大脑快速发育的跳跃期）、肚子饿（如果养成规律作息与喂养就不会有这个原因，具体的规律作息下文会提及）；

- 环境原因：冷了或热了（摸后颈部判断）、尿布湿了（晚上最好用纸尿裤）、室内光线太强（白天小睡也应该避免过强光线）、睡衣不舒服；

- 情绪原因：受到惊吓（有许多土方可以尝试解决受惊吓问题）、换护理人、妈妈上班（回家后应当有高质量陪伴）、分离焦虑（7-9个月比较明显，多安慰陪伴）、家庭不和睦等。

上面列举的这些原因也许只是一部分，你的宝宝睡眠不好的原因或许能从这里找到症结也或许不能，如果不能，那就需要父母耐心而清醒地接着寻找。如果你能找到不止一种原因，许多原因互相交织，那就先处理最紧要的问题。

**** 建立规律作息的常规程序
 这是所有睡眠训练方法的第一步，但事实上我感觉建立规律与睡眠训练是相辅相成的，无法养成宝宝的规律作息绝大部分原因都是睡眠问题造成的。有关规律作息，强烈推荐特蕾西的《实用程序育儿法》，那里面介绍得相当清楚。给宝宝建立常规程序，一方面能够让宝宝觉得有安全感，她能知道接下来将要发生的事情；另一方面也让父母和整个家庭的日程安排都能够井井有条。这样的常规程序可以给父母带来信心，因为你能理解宝宝，并很快分辨出她的哭声是因为什么原因。

常规程序可以用一个单词来总结，EASY，E是eat进食, A是activity活动, S是sleeping睡觉, Y是you给你自己一些时间。它的核心是这四件事情的顺序，也就是从一天的开始时，当宝宝醒来后先喂食，然后让他玩一会儿，接下来是睡觉，在这个时间你可以享受自己的时光。

特蕾西建议，四个月以内的宝宝应当遵循三小时循环的常规程序，四个月以上的宝宝可以遵循四小时的常规程序。而当宝宝开始进食固体食物之后，可以在四小时的程序基础上进行调整。宝宝一岁半以后也许上午第一个小觉就没有了，那时候又会变成另一种规律。然而，需要说明的是，这并非一个固定的时间表，而是一套程序而已，不用拘泥于绝对精准的时间，只需要保持相对一致的程序即可。

3小时EASY程序
#+BEGIN_QUOTE
E：7：00起床进食
A：7：30或7：45
S：8：30（小睡1.5小时）
Y：你自己选择
E：10：00
A：10：30或10：45
S：11：30（小睡1.5小时）
Y：你自己选择
E：13：00
A：13：30或13：45
S：14：30（小睡1.5小时）
Y：你自己选择
E：16：00进食
A：16：30或16：45
S：17：00-18：00之间（小憩40分钟）
Y：你自己选择
E：19：00（如果在生长突增期，可安排19：00与21：00两次密集进食）
A：洗澡
S：19：30睡觉
Y：晚上是你的了
E：22：00或23：00梦中进食
#+END_QUOTE

4小时EASY程序
#+BEGIN_QUOTE
E：7：00起床进食
A：7：30
S：9：00（小睡1.5-2小时）
Y：你自己选择
E：11：00
A：11：30
S：13：30（小睡1.5-2小时）
Y：你自己选择
E：15：00
A：15：30
S：17：00-18：00之间（小憩40分钟）
Y：你自己选择
E：19：00（如果在生长突增期，可安排19：00与21：00两次密集进食）
A：洗澡
S：19：30睡觉
Y：晚上是你的了
E：23：00梦中进食（直到七八个月大或是稳定进食固体食物为止）
#+END_QUOTE

需要说明的是，新生儿不在此列，他们的喂养和睡觉时间应当先顺其自然，随后再慢慢调整。我也一直赞成三个月以内的宝宝应当按需哺乳，但按需不是一小时吃一次、半小时吃一次，过了刚出生的那几天之后，所有的宝宝都应该能够至少相隔2-2.5小时喂一次，正常都可以调整成为3小时一次。另外，凡事不能走极端，多观察宝宝发出的信号，如果她上一次吃奶吃得不多，那偶尔调整一下是可以的，但注意不要形成“零食鬼”的模式，也就是每次吃奶都当零嘴吃，过一会儿就又要吃一次，这样对宝宝对妈妈都不是好事儿。

虽然说大家都知道母乳是越吃越有，但如果宝宝相隔很短时间就吃，难免每次吃的都不多，这样也容易使母乳的分泌变少；而如果建立相对一致的喂食间隔，会让孩子一次吃得充足，也会给母体需要更多乳汁的信号，宝宝的需要量增加，母乳的分泌就会增加，而分泌量的增加也会使得两次喂食的间隔增加。

所以，建立常规程序，你不会饿着你的宝宝，反而会因此对这一天宝宝的所有行为表现更加心里有数，生活也能越来越有规律。相反，无限制、无规律的喂食时间，容易造成宝宝饥饿周期的不稳定，这也会很大程度上影响宝宝的睡眠，以及整个身体机能的运转。

-----

- 睡眠总量：
  - 说起睡眠总量，其实没有绝对精确的数字，但一定是有一个大概范围。一般情况下，新生儿几乎一整天都在睡；二、三个月大的婴儿每天睡眠16-18小时；四、五个月大的婴儿每天15-16小时；六个月以上的婴儿每天需要14-15小时的睡眠。
  - 事实上，每个国家的婴儿平均睡眠时长都会有不同，当然每个孩子都有自己的习惯与天性，妈妈们还是应当先记录与观察自己宝宝的睡眠情况，并根据她睡醒后的表现来判断她是否已经获得充足的睡眠，然后找到她需要的睡眠总量。

- 睡眠信号：
  - 每个宝宝在困的时候都会发出自己的独特信号，如果你能把握住这些信号，及时让宝宝睡觉，那么，这就不会是一件困难的事儿。然而如果你错过了最佳的时机，宝宝开始变得有些闹、不好哄、或是过度疲倦导致的神经兴奋，那就会是很棘手的问题了，因此，观察并了解你家宝宝的睡眠信号非常重要。
  - 在最佳入睡时机这个魔幻的时刻，宝宝会有些镇静，有些安静，有点迷离，有点平静。一般来说，许多宝宝都会用揉眼睛、打呵欠来表示困了，也有宝宝会把头埋在你胸前蹭，或是对玩具以及其它的东西不感兴趣，一旦发现这些信号，就一定放下手里的事儿，赶紧让宝宝睡觉吧。

- 清醒时间：
  - 睡眠信号也需要结合宝宝的清醒时间来看。每个阶段宝宝的清醒时间是有规律可循的，新生儿清醒15-30分钟就会累了（前两周清醒15分钟，后两周拉长到30分钟，后面月龄的清醒时间都基本遵循前后两周这个原则）；1个月大宝宝清醒30分钟至1小时就会累了（前两周30分钟，后两周1小时）； 2个月大宝宝清醒1-1.5小时就会累了；3-5个月大宝宝清醒1.5-2小时就会累了；6-8个月大的宝宝清醒2-2.5小时会累；9个月以上的宝宝清醒时间可以增加到3小时；18个月以后删除上午那次小睡后，清醒时间会被生活习惯而延长。
  - 掌握住清醒时间，在宝宝接近清醒时间末期时开始准备让宝宝睡觉，这样的话相信就比较不容易引来宝宝累极了大闹的场面。

- 小睡安排：
  - 按照每个月龄宝宝的作息规律与清醒时间来看的话，前四个月清醒加睡眠的时间应该是三小时一周期，每天三次小睡，前两次小睡1.5-2小时左右，傍晚小憩40分钟左右；自从三四个月大开始，宝宝白天的小睡也会变得规律起来，由于四个月之后是四小时一周期的程序，也就是说宝宝每次小睡1.5-2小时左右。如果傍晚还会安排一次小睡的话，这次小睡的时间会比较短，大概也就一个睡眠周期，也就是40分钟左右；六个月进食辅食以后清醒与睡眠的周期也许能拉到4.5-5小时，仍然按照喂奶——活动——睡眠的程序即可。
  - 每次小睡如果超过3小时一定要叫醒孩子，否则会影响晚上的睡眠；如果一次小睡不足45分钟必须接着再睡，否则睡眠的修复力相当差（傍晚的小觉不在此列）。
  - 一般来说，6个月以前的宝宝每天会睡三觉，上午9点左右，下午1点左右，傍晚5点左右；6-9个月的宝宝会开始自动调成两觉，傍晚那一觉取消了，傍晚到晚上入睡那一段清醒的时间能长一些；18个月以后的宝宝会只睡午觉一觉了。

- 作息养成：
  - 规律作息还是离不开固定时间与程序，白天的规律还是按照“喂奶-清醒-小睡”这样的模式来进行。对于如何养成规律作息，台湾的“瓜老师”曾经提出过这样的方法：第一步，你可以先花几天时间来记录宝宝每天的作息，观察一下她的睡眠与活动情况；第二步先固定晚上入睡时间；第三步固定喂奶的间隔；第四步固定早上第一次喂奶的时间；第五步固定每次喂奶的时间；第六步固定白天小睡时间。
  - 而夜晚就是睡觉时间了，理论上来说，最保守的说法也是当宝宝9个月大的时候就从睡觉到早上起床不需要一切夜奶（当然如果你愿意，你可以一直接着喂一两次夜奶，但从儿科大夫的观点来看，这样应该是妈妈的意愿大于宝宝的实际需要了），更多的说法是当宝宝六个月之后固定添加辅食之后就可以删除一切夜奶，而从三个月开始晚上可以只吃一顿夜奶即可。
  - 因此，如果你的宝宝已经足够大，你大可以不必担心她晚上会不会肚子饿，而如果夜奶不再提供，白天孩子也会把需要的奶量补回来。
  - 另外，几乎所有睡眠专家的建议都是让一岁以内的孩子在七点左右睡觉，一岁以后可以延迟到八点左右。但如果这样的睡眠时间对你们的家庭来说不太现实，比如爸爸回家比较晚，那也可以适当延迟，但一般建议孩子睡觉的时间不能超过晚上九点。

- 如何接觉：
  - 为了让宝宝能够符合规律作息的程序，白天睡得更长，恢复更好，还需要了解的是接觉的方法。一般宝宝睡眠周期在30-45分钟左右，入睡后30分钟她会从深睡眠转入浅睡眠层面，这时候非常容易醒，不会自己接觉的宝宝就只能一觉睡一个周期，醒了就哭。如果等到宝宝哭了之后再着急抱起来或拍拍给她接觉，有时候已经来不及了。
  - 如果要想顺利接觉，建议可以在宝宝入睡后，在她平时醒来那个时刻提前几分钟主动走进卧室，把手放在宝宝身上，或是拍拍她，持续几分钟，直到看见她又全身放松下来，慢慢进入深睡眠，过了她平时醒的那个时间，应该就安全了。接觉可以先接几天，等宝宝慢慢适应睡长觉了，也就不用再帮她接觉了。

- 睡前程序：
  - 你有没有过这种感觉，每天晚上你洗完澡，穿上睡衣，躺上床，打开床头小灯，随手翻看一本书，慢慢地，睡意就开始来了，你关灯睡觉，一切都发生得非常自然。对于宝宝来说，拥有一套固定的睡前程序，也会让她养成一开始做睡前程序就睡意来袭的习惯。
  - 不管是哪种睡眠训练方法，睡前程序都是必不可少的基础。结合清醒时间来看，睡前程序就是需要你在发现宝宝困了之后，不是直接把宝宝放倒让她睡觉，而是给她一点儿缓冲的时间，让她从活动状态过度到睡眠状态，睡前程序就是在告诉宝宝：该睡觉了。
  - 对于睡前程序，《实用程序育儿法》里特蕾西的建议是4s法，也就是：布置环境setting the stage（拉上窗帘，播放音乐等，确保环境安静）；裹上襁褓swaddling（大点儿的孩子就穿上睡袋）；坐着sitting（抱着她安静地坐一会儿，不要摇晃）；嘘拍法shush-pat（把她放进小床，如果她无法平静，可以在她耳边发出嘘声并拍拍她帮助她平静，直到她睡着为止，这方法适用于六个月以前的宝宝，大宝宝只需要把手放在她身上）。
  - 4s法的前两个还是比较容易做到的，这也是传统意义上的睡前程序，后两者其实已经涉及教宝宝睡觉了，咱们可以后续讨论。另外，经常被用到的睡前程序包括洗澡（晚上睡觉前）、喂奶（晚上睡觉前）、讲故事、唱歌等等。睡前与妈妈多一些亲密的依偎，能够让宝宝不那么害怕一个人睡觉，让她有安全感和信赖感，从而更加容易入睡。
  - 总之，睡前程序必不可少，而且应当在同样的时间用固定的程序，至少培养一星期等养成习惯之后才能开始进行睡眠训练。睡前程序的目的是让宝宝情绪平静下来，慢慢进入睡眠。

*** 睡眠训练的几种主流方法
其实睡眠训练的方法有很多，找出最适合你和你家孩子的才是正经事儿。“有些方法对于极端哭闹的孩子压根不起作用，有些方法对于资源有限的父母不起作用，有些方法只对年龄大一点的孩子起作用。当然，某种方法对一些家庭很有效，而对另一些家庭无所帮助。”

主流方法主要有三种，按照让孩子哭泣的程度来分，分别是“无泪法”（以特蕾西的“抱起放下法”为代表）、“控制哭泣法”（法伯的循序渐进法）和“cry it out”（也就是“让孩子哭”的方法）。

通常情况下，最快见效的是第三种方法，但如果你实在做不到眼见着孩子哭太久时间而不理会，你可以选择第二种循序渐进法；而如果你根本不想让孩子哭，希望一直在身边安抚，那可以选择第一种无泪法。然而必须说明的是，“无泪法”见效所需的时间会最长，所耗费的精力和体力也最大，如果你只能自己一个人做睡眠训练，可能很难坚持下来；第二种控制哭泣法界于两者之间，一般三四天即可见效；而“cry it out”据说改变只需要一天。当然，所有的说法都只是平均值，具体还得由不同宝宝的性格和习惯来决定。

**** 睡眠训练前的准备
 “爱莘麻麻”曾经对此做过介绍：
- 原则上来说应该是让孩子自己睡小床，才能培养独立入睡。但是从实际操作中，如果客观上做不到分床睡，同床睡应该也是可行的；
- 确保宝宝睡眠区的安全，床上不放任何枕头和过多的毛绒玩具，以免孩子贴上去有窒息的危险；
- 用睡袋而不是盖被子，否则宝宝哭闹把被子踢了容易着凉；
- 确保白天宝宝的奶和辅食都吃得比较好，晚上醒来不是因为饿；
- 抹上厚厚一层护臀霜。

**** 无泪法
无泪的方法应该有不少，但最著名的应该是超级保姆特蕾西的程序育儿派的“抱起放下法”。可其实在我看来，这也并非“无泪”，孩子还是会哭，只是这个方法确保在孩子哭的时候妈妈能够积极响应而已。另外，西尔斯有一本书叫《宝宝安睡魔术书》，他赞成的方法除了让宝宝保持规律作息、白天固定小睡、实行睡前程序之外，建议用各种方式哄宝宝入睡，并在宝宝睡着之后把手搭在宝宝身上一段时间、留下一些有妈妈气味的东西在宝宝身边、睡前喂饱肚子但不能太撑等等，有兴趣的可以找来看看（个人认为西尔斯的方法对于已经有强烈睡眠依赖以及夜间超频醒的宝宝来说没有作用）。另外，马克维斯布朗博士也曾经提及，如果你想采用“不让孩子哭”的方式，那应当避免孩子过度疲倦、让孩子放松、逐渐让孩子自己入睡。

回头说“抱起放下法”吧，它是《实用程序育儿法》作者特蕾西提出的睡眠训练方法，简单说来这个方法就是一旦孩子哭就抱起她来，一旦停止哭泣就放下。这是相对中庸的一种睡眠训练方式，它既强调让孩子自己入睡，同时也不会任由孩子一个人哭泣。她说这个方法她曾用在上千个婴儿身上，不管是什么性格的，都会在一个星期之内见效。然而，她也说，最多的时候，一次可能需要抱起放下上百次才能成功，当然这是极端案例。特蕾西说这个方法使用时平均需要时间20分钟，也有可能需要1小时或以上。它的核心思想是慢慢向孩子灌输信任。

“抱起放下法”要求宝宝应该在四个月大以上，具体步骤为：做完睡前程序把仍然醒着的孩子放入小床，然后离开。她应该会哭，你先判断哭声的性质，如果是自我安慰的哼哼唧唧就不用及时理会，如果发展成情绪性大哭，你走进房间先试着言语安慰，把手放在她背上，如果宝宝六个月以内，可以试着拍拍，或是发出嘘声安慰。如果她还哭，就把她抱起来，尽量不摇晃，一旦她停止哭泣就马上放回小床。如果你抱着她时她往后仰，就应该立即把她放下。哪怕她一离开你的肩头就哭，或是放下的过程中哭，你也应该坚持放下，然后再抱起来。

不要觉得内疚，她不是在生你的气，她只是有些受挫，因为她从来没有学习过自己入睡。放下之后多用言语安慰，如果你的方法做得正确——她哭的时候抱起来，哭声一停止马上放下——最终她会消气，逐渐平和下来，你可以继续把手放在孩子身上，直到她最终睡着。

值得一提的是，这个方法针对不同月龄的孩子方法是有所不同的，刚刚说的这种是最基础的方法，也是4-6个月的孩子应当采用的方法； 但如果你的宝宝已经6-8个月，那每次抱起之后你应当横着抱，并且马上放下她；如果她已经8个月以上，基本可以不用抱起，只需要把已经站起来或坐起来的孩子放躺下就行。具体操作还是建议看看书，里面会更详细。“抱起放下法”只适用于1岁以的宝宝，1岁以上的幼儿，特蕾西的书里也有专门的章节介绍不同的方法。

我曾经在潼四个月大的时候试过这个方法，我抱起放下十多次之后，潼哭得越来越厉害。后来我也反省过，也许这个方法的确不是所有孩子都适合，潼就是一放下哭得比上一次更大声，一直没有停止过，最终我放弃了这个方法。但也许以后我还有可能会运用到它，因为我发现经过法伯法训练之后的潼，如果被吵醒大哭的话，基本只需要我进屋把手放在她身上她就会马上睡着。也就是说，如果是现在训练，我会选择抱起放下法，因为这种相对温和的方法就已经管用了，何必再让孩子多哭呢？

关于“抱起放下法”，我必须推荐一个微博，“小土大橙子”，她是实际应用这个方法，基本在几天之内解决了五个月大宝宝夜间频繁醒来以及白天小睡不好的问题，对于这个方法，她研究得相当透彻。同时她又是一个非常乐于分享的妈妈，如果大家想尝试这个方法，可以与她做进一步交流沟通。

**** 哭泣控制法
这个方法在《法伯睡眠宝典》里会有详细说明。它是采取循序渐进的方式，以延长响应孩子哭泣时间为方法来操作。我对潼潼的睡眠训练最终采用的这种方法，基本上只用了一晚上就有颠覆性的改善。

详细方法：矫正睡眠开始的时候适当推迟宝宝入睡时间，大约推迟30-60分钟，以便于当时宝宝的确昏昏欲睡，但要确保宝宝起床时间与平时一样，白天小睡的时候也不能任意增加，否则孩子就会补觉，影响夜间训练；睡前程序完成后，将清醒着的宝宝放入小床，不能抱着或是摇着她，确保她入睡时的环境与醒来时一样；如果宝宝在入睡时或是半夜醒来时哭闹不休，可有意识地延长响应时间，等待一段时间之后才进入安抚（建议的等待时间可看下表）；如果夜里孩子哭闹的次数超过了表里给出的次数，也应该继续按照当天最大值重复执行，直到孩子在父母不在的情况下自己睡去为止；到了第三、四天时，情况应该已经有了很大的改善，如果一星期后仍然没有彻底根除，可以在第七天的基础上适当延长等待时间，但如果一星期后情况一点儿也没有改善，那父母应当反思（可能造成的原因下文会提及）；每一次等待时间之后，父母应当走进房间里看看孩子，言语或轻拍安慰，不能抱起或摇晃，停留的时间不超过两分钟，不能让孩子当着自己的面睡着；如果孩子在过程中哭闹停止或是哭泣变小，就不再进入安慰，因为孩子正在学习自我安慰；一旦孩子在清晨醒来，不管是比平时早还是晚，都应该让她起床；如果孩子能站起来走路了，把房门锁上，到等待时间走到门边去；如果孩子与父母同床，当孩子哭闹时，父母应当与孩子保持距离，根据等待时间适时忽略孩子的任何要求；下表的等待时间不仅适用于晚上睡眠，同样适用于白天小睡，如果孩子经过半小时还睡不着，或者睡了一会儿就醒来哭闹，父母应当中止这次小睡，如果稍后她自己在游戏垫上睡着了就让她小睡一会儿；父母应当记录下睡眠情况，以观测整个矫正过程。

帮助孩子建立新的睡眠环境：循序渐进法。放任孩子哭闹的时间长度（分钟）如果孩子在放任的时间里一直哭闹）

| 第几日 | 第一次放任时间 | 第二次 | 第三次 | 三次以后 |
|--------+----------------+--------+--------+----------|
|      1 |              3 |      5 |     10 |       10 |
|      2 |              5 |     10 |     12 |       12 |
|      3 |             10 |     12 |     15 |       15 |
|      4 |             12 |     15 |     17 |       17 |
|      5 |             15 |     17 |     20 |       20 |
|      6 |             17 |     20 |     25 |       25 |
|      7 |             20 |     25 |     30 |       30 |

循序渐进的方法允许家长在孩子哭闹时进入房间，一方面让孩子知道父母的存在，另一方面也可以让父母看看孩子好不好。在使用这个方法时，走进房间去看孩子的等待时间是有弹性的，父母如果不能长时间忍受孩子的哭闹，可以根据自己的实际情况制定出更缓和的方案，但方案一旦制定就应当坚持。

另外，法伯认为睡眠矫正可以整体矫正，也可以分步矫正。整体矫正效果会更快实现，但如果家长认为分步矫正更适合孩子，也完全可以分步实行。法伯也建议断奶可以与睡眠矫正分开进行，但他认为如果孩子非常依赖最后一场奶，可以在哺乳后尽量把孩子叫醒再放入小床。

对于睡眠哺乳依赖，法伯建议应当先减少夜间哺乳次数，然后逐渐改变对睡眠哺乳的依赖。法伯认为五个月大的孩子就可以不用任何夜奶了，如果保留夜奶，反而容易打扰孩子睡眠，让孩子养成定时醒来要奶的习惯。如果是母乳，就延长每次喂养的间隔，如果奶瓶，就减少每次进食量。当成功解决夜间进食问题之后，睡眠矫正会变得容易许多。但把停止夜间进食与睡眠矫正同步进行也是没有问题的。

由于潼妞是采取这种方式进行睡眠矫正，我将会在后面详细写出她的整个矫正过程，与大家分享，供有需要的妈妈参考。

**** Cry it out
顾名思义，这就是“让孩子哭吧”的方法，它要求在执行完睡前程序之后，在孩子清醒时将她放入小床，从此不再对她的哭泣有任何理会，直到孩子睡着。据说这是解决睡眠问题最快的方法，但是也并不一定适用于所有宝宝，父母们可以按照自己的实际情况来。

由于这种方法看起来相当简单，所以我并没有对此查阅过多的资料并进行深入了解，只是在看到《百岁医师教我的育儿宝典》时，发现那里提出的丹玛医生的方法是从新生儿开始就可以用这种方式训练，十天之内孩子就可以睡整觉。但从心底来说我是觉得这样对待新生儿太过残酷，为了稳妥起见我没有采用这个方法，但对于一些极端缠人或是用了其它所有睡眠方法都没有效果的孩子，也许可以尝试这一方法。建议不要在孩子太小的时候尝试，最好六个月大以后。

在《婴幼儿睡眠圣经》的作者马克维斯布朗博士对睡眠训练的建议当中，也有认同cry it out的成分。他认为从孩子五六周大时就可以尝试在他们入睡时容许他们哭闹一会儿以培养良好的独自入睡的习惯，如果需要使用睡眠训练的方式，那么采用“一次耗尽”的方法会使孩子哭闹的总量减少一些，因为可以更快起效。另外如果有旅行或生病的事情发生过后需要矫正睡眠，也可以采用这种方式。但他也同时提到，9个月以内的孩子可能晚上哭闹你会不确定她是不是饿了，所以判断起来会比较困难，但如果是大宝宝的话，采用这种方式会更容易执行一些。总之，他更推荐使用一次耗尽的cry it out方法。

当然，马克维斯布朗博士事实上还在书里提出过不少其它的能帮助孩子睡眠的方法，针对不同年龄、不同睡眠问题的宝宝都有不同的方案，有兴趣的妈妈可以自己去详细阅读。

**** 潼妞的睡眠训练记录
潼潼是一个相对高需求，又非常敏感，还有些倔强的宝宝，我试过先用相对温和的“抱起放下法”，但对她无用，相反是在激怒她；而如果用cry it out的方法，我自己下不了决心，于是最终选择了法伯循序渐进的哭泣控制法。实际操作来看，效果好得惊人。

由于潼之前是严重依赖夜间哺乳，整夜基本都在吃，我有些担心突然断了夜间哺乳她会非常不适应，于是我是采用了分步矫正的方法，也就是先减少夜奶再矫正睡眠。但据我所知，“爱莘麻麻”曾经也与我经历相似，她是采用整体矫正，也就是断夜奶与睡眠训练同时进行，效果也非常好，所以用哪种方法大家可以自行选择。

从潼六个月大开始，我们先是着手解决她的夜奶问题，晚上醒了不给吃奶，硬哄。按照崔玉涛医生的建议，最好妈妈不在现场，于是换成了奶奶晚上跟潼睡觉。第一个晚上她还是一小时左右就醒，醒来一看是奶奶，也没太玩命折腾，抱着哄了十来分钟就睡着了。这一晚上醒了六七次左右，直到早上六点多，实在哄不好了，而且小嘴一直在找，于是我进屋喂奶，把潼放在大床上，像以前一样，她就边吃边睡着了，睡到七八点起床。

此后的几天里一直如此，她的夜奶很快变成了固定只吃早上五六点左右那一顿，但之前还是频繁醒来，只是很多时候已经不用抱起，拍拍就接着睡了。按说进步不小，但仍然解决不了她频醒的问题，夜里醒来的时间跟以前类似。实在没招之后，过了一个多星期，睡眠训练开始。

第一天晚上，8点20喂奶，20分钟后把已经习惯性吃着睡觉的潼妞放入小床，过程中她醒了，我拍拍她，对她说：“宝宝，自己睡觉好吗？妈妈就在外面陪着你。”转身走出门，身后马上响起她瞬间嚎哭的声音。都说第一晚是最难熬的，我和潼爹俩人坐在客厅沙发里，手机用秒表倒计时，他看着IPAD缓解纠结的心情，我拿着《法伯睡眠宝典》给自己打气。3分钟后进门，潼一见我哭得更厉害，接着安慰，一分钟后出来，转身的时候她扯着嗓子玩命喊了起来。第二次等待时间是5分钟，第三次变成10分钟，大约过了半小时左右，她哭声也开始小了，一见我进门马上不哭，揪着我衣服扣子，看着我。那叫一个让人心碎！但我心里明白还得坚持，不然更是让她白受罪。

如此往复，一个半小时后，她终于没动静了，我悄悄走进门，发现她抱着小海马，把脸贴在海马身上，睡着了。而那时，我的眼泪也快掉下来了。半小时后，她喊了几声，马上接着翻身睡着了。两小时后，又喊了几声，继续睡下。直到半夜三点，她算是彻底清醒了，不睡了。哭了3分钟后，她自己抓着手绢玩了20分钟，随后继续哭起来，这次持续时间1小时后才睡下。此后，五点半、六点半，她分别又喊了几嗓子，直到七点她醒了，我把她抱上大床喂奶，她接着睡到了8点20起床了，起床时满脸笑容。

这天白天，她上午的小睡小声哭了20分钟，睡了一个半小时；下午基本没哭，睡了三个小时。要知道她以前是半小时必醒的。

第二天晚上，入睡时我只进去了两次，她在九点半左右睡下，半夜四点喊了几声，直到六点又哭起来，我发现她是拉臭了，换完裤子只好抱大床喂奶。吃完之后她接着睡到八点。但这一夜，她已经连续睡了八个半小时。这天白天上午睡一小时，下午睡两小时。

第三天晚上，开始有些哭着玩儿，折腾了半小时后，九点睡下，五点半醒来要吃奶，吃完睡到8：20，仍然是八个多小时的连续睡眠。
从前三天来看，其实睡眠训练只用了一天就已经把她晚上的连续睡眠拉长到了八小时以上，对我来说，这简直是不可思议。但是，我接下来犯了很严重的错误，那就是看见改善之后没有继续坚持，而是不舍得让她哭，在她入睡的哭闹时安抚到了她睡着才出门。因为我发现这时候的她，只需要我呆在房间里几分钟，就可以睡着，于是我心疼了，不想让她再哭个二十分钟，然而没想到最大的反弹就此开始。

从第四天晚上开始，她继续频繁醒来，我一看情况不妙，不敢再安抚到她睡着，于是这天她入睡时哭的时间回到了第一晚的模式。这天，我在客厅听着她在房间里哭，想抽自己的心都有，都怨我自己，白白让孩子又开始折腾自己。这一晚，我开始反思整个过程，并马上重新开始坚持严格的安抚时间，很快她又回到正轨。

然而在这个睡眠训练过程中，其实我并没有完全按照法伯的方法，而是根据潼的特点，有了自己的处理。因为我没打算就此给潼戒夜奶，于是清晨五六点那顿奶我还是她一醒就喂，其实这样也养成了她习惯性夜醒的模式。而且按法伯所说，是不应该把她抱到大床上的，但我觉得有些时候可以灵活处理，这样能让她多睡会儿，也没发现对之前的睡眠有什么影响，于是我坚持了。

白天的睡眠我当时没有同时训练，按说白天晚上一起训练会更快见效，但我的目的其实是让她晚上醒来能自己接着睡，而不是要求她学会自己入睡，所以让她白天也哭我觉得没什么必要，等晚上睡眠习惯养成，我认为白天自然会有改善。

事实上，从第二天开始，她哭的时间都只是在晚上喂完奶入睡时，我发现这一情况后就马上换了一种方法，就是让她吃奶吃到睡着，我不弄醒她，直接放小床。其实这一招很冒险，这还是没切断哺乳睡眠联想，但是，以我的实际操作来看，完全不影响夜里睡眠，她仍然一睡八小时以上，而且更重要的是，从换了方法之后，她整夜基本再也没哭过一声，只是清晨会醒来哭几声要吃奶。当然，我还是认为这样的方法存在一定风险，最好尽量提前半小时哺乳，然后安静陪伴孩子半小时，最后让孩子独自在床上入睡比较可靠。

就这样兜兜转转，大约用了一星期的时间，我终于理清了状况。每晚还是喂奶让她睡着，正常情况下，她有时候会隔几小时喊几嗓子自己接着睡，有时候就一点儿也不醒，直到睡到四点到六点之间会习惯性醒来吃奶，然后接着睡到早上。

而睡眠训练期结束后，现的情况是：她晚上入睡前吃奶也不睡了，总是吃了十几分钟后就从我身上爬起来，自己揉眼睛，我把她放入小床，她抱着小海马，翻几次身就睡了。有时实在睡不下我就拍拍她，或是把手放在她身上，很快她就能闭眼睡着。有时候她半夜醒来哭起来不睡了，我会走进屋安抚一会儿，基本她用不了一分钟就会睡着。而这种安抚已经不再对她之后的睡眠有影响了，也就是说，她新的睡眠模式已经基本形成。但白天的小睡由于没同时训练，目前还是不太好，需要推车睡，有时候能睡一个半小时不醒，有时候是四十分钟醒来，抱抱接着睡，上午基本一个半小时，下午两至两个半小时。

下一步我的计划是等到九个月，先把清晨五六点那顿奶停了，但那时候我可能不会采取法伯的方法，可能会用“提前唤醒”法（如果你判断宝宝已经是习惯性夜醒，可以在她固定醒来的时间之前半小时或一小时轻轻拍拍她或是挪动她等一些小动作让她处于半清醒状态，然后再接着入睡，这种方法可以破除习惯性夜醒的魔咒），或是其它更温和的方式来处理；再接下来，打算把白天的小睡稳定下来，也许会重新尝试“抱起放下法”，如果不管用，那就接着回归到法伯的方式，但我相信用不了两天，也能把她白天的睡眠调整过来（在写此文的过程中，我已经开始尝试用抱起放下训练白天的小睡，平均每次抱起放下一至两次，基本不哭，睡眠时间为一个半小时至两小时。抱起放下的难度比以前低了不止N个等级）。

这样说，是想说睡眠训练的确有许多方法，我也不打算一直只用一种，而是打算在不同阶段，针对不同的目标，选择最适合孩子的那一种。或者相对严厉，也或者相对柔和，看当时宝宝的情况决定。我也同样建议想要对宝宝进行睡眠训练的妈妈们，能充分考虑到自己宝宝的性格特点选择不同的方法，比如分离焦虑严重的宝宝可以一开始陪睡但减少安抚，慢慢分步进行矫正。

*** 睡眠训练如果不成功可能因为哪些原因
Cry it out的方法我了解不多，不太确定可能因为什么原因会导致不成功，但我注意到马克维斯布朗的建议是白天小睡最多让孩子哭一小时，晚上则不限定任何放任的时间。如果这方法不行，那也有可能是孩子性格的原因所致。

至于“抱起放下法”，特蕾西强调：一定是要在孩子哭的时候先判断哭的性质，如果是哼哼唧唧的哭，可能是因为孩子学习入睡时的受挫哭泣，可以先不理会或是言语与拍拍安抚；如果哭声越来越大，是情绪性的大哭，那样才抱起来安抚。而抱起来后，一旦孩子停止哭泣，就应该马上放下，不能抱到睡熟，要确保孩子是自己清醒着在小床里入睡的。但据@小土大橙子的实际操作，她认为不一定非得每次都在一停止哭马上放下，因为这样也许引起更大反弹，可以允许逐渐改善的方法，比如抱到有些困的时候，或是前几天尝试的时候抱到睡着也可以，但后来就慢慢要做到清醒时放下。她认为，情绪平静才是睡眠的关键（这一点我也相当认同），所以能安抚到情绪平静最重要。抱起的时间也有一定的要求，不能太长，三五分钟是极限。而从我使用这个方法的体会来说，抱起来也不一定必须静止，也可以适当走走晃晃，还是安抚情绪为主，但不能晃到睡熟了再放，而是平静下来就应当放下。

特蕾西同时也提到以下几种情形也会对睡眠训练的效果有影响：如果父母不理解自己为什么要运用抱起放下法，因此做得不对；如果没有调整宝宝全天的生活与作息；父母自己的情感，尤其是内疚感；没有考虑到宝宝的脾性；房间没有准备好，比如有刺眼的光线；父母没有同心协力，有一人没有准备好；父母气馁了，并且不再坚持；另外，我之前说过，针对不要同月龄的孩子，做法会有些许的区别，大家应当按照宝宝的年龄分别采用不同的方法。

“哭泣控制法”可能失败的原因法伯在书里做过总结，他强调循序渐进的这种方法只适用于孩子对睡眠环境有不正确的依赖感（比如抱哄、哺乳等），导致无法在醒来后再次入睡的情况。如果矫正七天没有改善，家长应当从以下角度反思：一是程序错误，比如执行不够彻底，让孩子在小床自己入睡，但半夜醒来时又采取以前的方式快速哄孩子入睡；或是在孩子入睡时陪伴到孩子睡着，但半夜醒来时突然对孩子不闻不问；或是孩子独自入睡，却在清晨醒来时把孩子挪到大床跟家长一起入睡；或是睡眠训练方法不坚持，一天一个样儿；或是家里只有一个人执行睡眠训练，其它人完全不理会……掌握放任孩子哭泣的时间也很重要，有的家长按照时间表进入房间，进去后却一直哄到孩子睡着才出来（以我实际体会来说这个应该坚决禁止）；有的家长没有延长每次的等待时间，让孩子养成了哭到家长进来的习惯。总之，只要坚持明确的规则与程序，应当就不会出现问题。第二种可能是无视孩子的作息规律，比如在孩子根本不困的时候让孩子睡觉；矫正时期夜间睡眠不够，允许孩子在白天增加小睡时间，或是早晨没按时间表叫醒孩子让她接着补觉等等。这需要大家按照之前我写过的那个规律作息的环节，先建立好孩子的作息规律，了解孩子困倦的时间与信号，在孩子应当睡觉的时候才让他躺下练习自行入睡。第三种可能是忽视孩子的焦虑感，有的孩子在白天就离不开大人，夜间也难免会抵触独自睡觉，这样的情况也许放任她哭再久都没用，可以考虑在矫正前期仍然陪着孩子入睡，比如孩子躺小床，自己躺在大床边上陪着，但绝对不抱哄，要让孩子自己睡着。

即使是已经经过睡眠训练养成了良好作息，在睡眠训练结束后也偶尔会出现反常，有可能孩子突然被大的声响吵醒，或是突然做噩梦，这种情况下家长应当进行安抚，一般不会形成新的依赖。另外，在孩子长牙、练习大动作、生病、外出旅行等特殊时期，孩子如果出现不良睡眠情况也应当及时响应安抚，但这一时期结束后就应该尽快恢复到正常的情况。

** 常见的与睡眠有关的误区
>>> 夜晚醒来频繁是因为母乳孩子没吃饱，喂奶粉吧！

我曾尝试过用瓶在睡前一次喂240ml母乳，当时她的饭量是一顿150ml左右，结果还是20分钟就醒。如果夜醒的频率与白天吃奶的时间差不多可以考虑是饿，但如果半小时、一小时这样醒，只是习惯性夜醒，与饥饿无关。

>>> 宝宝这么兴奋，她根本不想睡觉！

宝宝越疲倦会显得越兴奋，哭闹表明已经太困了。

>>> 想要宝宝晚上睡得久，白天就不能让她睡觉！

睡眠促进睡眠，在适当的范围内安排白天的小睡，才能使宝宝不至于过度疲倦，导致晚上频繁醒来。

>>> 宝宝现在还小，大了自然就会睡觉了。

3-4个月是学习睡眠的最佳时机，如果错过，有可能延续到3岁以后仍然建立不了良好的睡眠习惯。

>>> 想让宝宝不在清晨太早醒来，只能延迟她的入睡时间到十点以后

五岁以内的孩子应该在八点以前睡觉，早醒往往是因为睡得太晚。

>>> 每天晚上上床睡觉的时间应该完全固定、雷打不动。

从某种意义上来说，固定晚上入睡时间是正确的，这样有利于孩子生物钟的形成，但想要做到这一点就需要确保白天小睡的完全规律化与一致性，不一定每一天都可以做到。晚上上床睡觉的时间应该与白天小睡时长、上床睡觉前清醒的时间等结合起来判断，尽量在30-60分钟之内灵活安排。

>>> 宝宝容易醒是因为缺钙，赶紧补钙吧！

正常生长发育的宝宝，不管是母乳还是配方奶喂养，六个月以内都不会缺钙，六个月以后只要辅食添加得当也不会缺钙。

>>> 经过睡眠训练之后就不再需要在睡前对孩子有任何安抚！

关键还是在于情绪上的平静，在进入睡眠状态之前可以抱着孩子安静地说说话或是做别的有助于孩子情绪平稳的事情。让宝宝觉得入睡前的时光安静而快乐，更有利于她平静快乐地入睡。

** 如何哄宝宝睡觉
这一部分内容其实有一些题外话，一般而言，从新生儿开始做睡眠引导的话，应当尽量杜绝用抱哄等方式哄睡，因为这样就会造成日后的依赖与麻烦，还是尽量让宝宝自行入睡。但如果你的宝宝还不到四个月或六个月大，你不愿意这么早对她做睡眠训练，但由于长期的不良睡眠习惯，她入睡相当困难，很不好哄，也拒绝被引导，同时，她或许已经积累得过度疲倦，或是她就是极度缠人的性格，怎么办？

如果的确如此，或许你需要学习哄睡技巧。事实上，在宝宝满三个月大之前，你也可以在睡眠方面尽量满足与抚慰她，这并不会宠坏她，只要你记得在三四个月大的睡眠形成窗口期及时调整与引导。

如果你坚持要哄睡，那应当记住一个原则，哄的目的是让宝宝回归平静。你可以采取她最喜欢被抱着的方式有节奏地温和晃动；拥抱宝宝，保持尽量多的身体接触；试着给她按摩；让她用吸吮的方式平静下来；裹上襁褓或是睡袋，让她觉得有安全感；可以尝试比如像吹风机、抽油烟机、空白收音频率、吸尘器的声音之类的白噪音（这对于四个月大之前的我家潼妞简直是哄睡利器）。最重要的是一定要记住她清醒的时间，在犯困初期就开始哄睡。

另外，在宝宝第二个月大时开始，除非是一开始就放下自己睡的，否则都容易出现抱哄睡着之后一放下就醒的情况。这是因为四个月之前的宝宝在入睡时都有一段REM浅睡眠期，大概持续20分钟，在这个时间段内放下就容易醒来。如果想要抱哄后放下睡，尽量抱的时间超过20分钟，待孩子睡熟了就能放下了。四个月之后孩子会入睡后直接进入深睡眠，那时候就不会存在放下就醒的情况了。但值得注意的是，那个时候也许抱哄摇晃入睡的种子已经深深种下……

** 与睡眠以及育儿理念相关的反思
自打潼潼的睡眠情况越来越糟糕之后，我也一直在反思，这几个月当中到底发生了什么，我做错了什么吗？在翻阅许多与睡眠、育儿相关的书籍，并与许多妈妈做了交流之后，我发现了自己的问题，而这些问题，都与育儿理念密切相关。

在潼出生之前以及之后的几个月里，我一直奉行的是西尔斯的亲密育儿法，但遗憾的是，我或许完全没掌握其中的真谛，反而把亲密育儿做到了极端，也就是，有任何动静都及时响应，最终导致过度响应过度安抚，剥夺了让孩子学会自我安抚的机会。其实就像你一直抱着孩子，她就学不会自己爬行、走路一样，偶尔适当的放手是为了让孩子更好的掌握她应当学会的技能，包括睡眠。

宝宝的睡眠周期大概在35-40分钟，每个周期她会从深睡眠转为浅睡眠，这时候她易醒，也可能醒来后哭几声，但如果你不理会，她就能够自己接着入睡。但如果你贸然打扰了她，用你那颗敏感的心第一时间冲过去抱起宝宝，那她永远学不会自己如何度过这个浅眠期，以后在宝宝每觉都只睡半小时之后，你也不能怪宝宝睡太少，其实是你剥夺了她学习的权利。

潼的睡眠之所以变得越来越糟糕，在我看来完全是养育者的问题。在月子里我还没太着手带孩子时，月嫂就几乎24小时抱着她，抱着晃着哄着睡觉，从来没有尝试过把她放下拍拍让她自己入睡；第二个月月嫂走了，我和婆婆几乎是整天抱着她睡觉，一抱就两三个小时，或者让她趴在我身上睡，枕着我胳膊睡，用背带背着睡，总之就是用各种人为加工的方式与工具让她睡觉，并把她搬到了大床与我一起睡；第三个月临时请了一星期的育儿嫂，人家就完全可以让孩子躺在床上拍着睡觉，晚上原本两小时左右醒一次的潼居然那几天都一觉睡到五点，遗憾的是，这位阿姨走了之后我们又恢复了以前的方式，当时我还完全对婴儿睡眠的问题一无所知。就这样，我错过了引导潼学会睡觉的最关键的三个月（如果你的宝宝还处在三个月以内，恭喜你，你或许不需要任何睡眠训练，但你需要进行睡眠引导，比如尽量让宝宝在累的时候不借助外力，自己躺在床上学习入睡）。

从第四个月开始，我又发现了一个省事儿的方法，那就是哺乳。之前每晚哄睡需要两三个小时（当时我或许也完全不懂清醒时间与规律作息这回事），后来就直接上奶喂到她睡着，基本上她半小时后就会再醒，以前是抱起来哄，或许也要哄一小时，但后来我就直接继续喂奶直到她睡下，晚上她醒来也喂奶。不看时间、不管醒来的原因而一味喂奶导致的后果就是潼开始超频醒，一晚半小时、一小时醒的噩梦就此开始。现在回忆起来，我都想狠狠抽自己一顿啊，或许什么时候都一样的道理，如果你想走捷径，那么现实可能会给你残忍的耳光。

事实上，我愿意每晚上进行两三次左右的夜奶，但如果是七八次、甚至十几次，那真的是对妈妈和宝宝都是折磨。因此强烈建议妈妈们一定要谨慎对待夜奶，三四个小时一次的频率是完全可以接受的，但如果孩子醒来的频率更勤，一定不要直接喂奶，以免造成习惯性夜醒，依赖哺乳才能入睡的习惯。即使是西尔斯，也是如此建议。我身边也有不少妈妈朋友，因为孩子夜晚超频醒来必须吃奶睡，从而打算让孩子提前断母乳。这样的选择，相信不是任何一个妈妈愿意做的，但却又不得不为，与其这样，其实不如狠心几天切断哺乳睡眠联想即可。

正因为我从来没有尝试过让潼自己入睡，而是一直都用我的方式哄她睡觉，因此她没能学会如何睡觉，以及在醒来后如何不借助外力接着睡着。如果时间还能重来一次，我将会在抱哄安抚之后，在她清醒时就把她放入小床让她自己睡觉。而这一失误也让我真正明白，任何事情，都不能过度，包括爱孩子。否则一味的无限制的爱，或许只会培养出一个李某某那样的孩子，到时候就没地儿哭去了。

对育儿理念的反思，直到我看到《从零岁开始》这本书，才终于有醍醐灌顶的感觉。这本书里的观点认为，下面两种育儿方法，可能影响育儿的成功，并导致家庭破裂：一是在育儿过程中忽略了夫妻关系的重要，二是以孩子为中心的育儿方式。以下我摘录几段让我深受触动的话：
#+BEGIN_QUOTE
你对孩子最大的影响，并非你所扮演的父亲或母亲的角色，而是丈夫或妻子的角色。我们的社会已经遗忘或摒弃这样的真理。这种结果使得社会被“以孩子为中心”的观念所吞没——这便是自我中心的开始。很多时候父母不了解，当孩子来到他们家庭时，这意味着孩子进入了一个早已存在的社会结构中。

父母经常离开他们对彼此起初的爱，而把注意力转移到孩子的身上。他们美其名曰要把孩子养育好，但这却是家庭关系开始疏离、破裂的第一步。不把孩子当作家庭中受欢迎的一分子，而视其为家庭的中心，这将危及成功地养育儿女。以孩子为中心的父母亲，把养育儿女看为他们世界的中心，他们把整个世界带到孩子面前，而非把孩子带入他们的世界。因此，这孩子的权利无时无刻不被提高，他错误的行为也被加强。

以孩子为中心这一原本良好的动机，却促使孩子变得“自我主义”或“自我中心”。如果那些刺激导致他看自己为家庭的中心，他将发展出自我中心的人生观，当他的世界越来越大时，他将把这样的人生观带入每一种人际关系中。而当一个孩子视他自己为家庭中受欢迎的一员，而非家庭的中心，他在崭新且不断扩大的社会人际关系中，便能进出自如，并且在情感上得到满足，成为家庭中受欢迎的一分子，会培养出“我们主义”，呈现出我属于这个家庭团队的态度——给予别人像别人给自己那么多。这种人际关系是平衡的生活所必备的。
#+END_QUOTE

究竟是完全以孩子为中心的育儿理念好，还是给孩子建立规则与限定界限更好，或许这也要依照每个孩子的性格来决定，但从我的体会来说，我会倾向于选择后者。并非一切能让孩子不高兴或是哭的事情就都不做了，尽早设立家庭规则，才能避免更多麻烦，也是对孩子负责的真正体现。建立父母的权威与爱孩子之间并不冲突，亲密育儿不是无底线无界限，我想这并不是我一个人会犯的错误。

新手妈咪们往往都有一颗愿意为孩子奉献一切的心，我们害怕听到孩子哭泣，宁愿做一切事情换得他们的宁静。很难要求第一次做妈妈的人能淡定而理智地思考许多问题，正因为如此，无规则养育的种子就此生根发芽，而等到它已经发展得无法控制时，可能我们才能回头去反省与思考。

我已经开始认同，孩子不应当成长在无菌的温室里，爱是必须的，但是适当的放手也是必须的。我同时认同，母亲并非我唯一的社会角色，做更完整与更健康快乐的自己，才能传递给孩子更多的温暖与能量。与睡眠有关的事儿，就写到这里吧。希望大家都能拥有一个健康快乐的宝宝，以及和睦幸福的家庭。

** 推荐书籍与致谢
书籍建议参考这几本：《婴幼儿睡眠圣经》、《法伯睡眠宝典》、《实用程序育儿法》、《从零岁开始》（这更是一本有关育儿理念的好书）
