#+title: 百度BIT上海行

总体行程时间 2011.5.4-2011.5.5. 去外地出差的话，那么必须申请差旅。关于如何申请差旅，可以查看 http://family.baidu.com/core/index.jsp?chc=695059348

回来之后，等到飞机电子客票行程单回来之后，你手上应该有： 行程单; 住宿发票; 往返机场发票; 其他发票. 

然后填写报销单，选择差旅费逐项写好，同时需要单独添加一项”出差天数”这么一个东西，报销费用为0元，里面填写好出差天数，然后提交报销单。等待经理批复之后，就可以提交报销单到财务部了。

我的时间安排是这样的:
- 2011.5.4 11:30-13:40 上海航空 FM9104 首都国际机场二号航站楼->虹桥国际机场二号航站楼（晚点1个小时）
- 2011.5.5 18:00-20:25 东方航空 MU5121 虹桥国际机场二号航站楼->首都国际机场二号航站楼
- 讲课时间 2011.5.5 10:00-12:00

个人没有心情在那里待很久，最多带一些吃的，所以时间安排相对来说不是很宽松。根据个人喜好吧：）。百度上海研发中心在浦东新区，据了解最近的酒店就是”锦江之星上海张江店“。据了解条件般般。BIT上海培训专员说也可以考虑住在市中心一带。但是想到离公司太远不方便就算了。旁边有一个博雅酒店，但是消费相当的贵，很可能会超过住宿费用超标。公司和携程网合作，所以可能在携程网上面订会更好一些。在携程网上订机票的话，可以让携程网将发票寄到公司。在酒店住宿保留好发票回来报销。不用等到每月中旬，对于差旅费用可以随时报销。另外就是锦江之星里面是有餐厅的，你完全可以在里面吃晚餐和早餐，然后开发票的时候和住宿费用一起开就可以。
行程安排

从上海虹桥机场二号航站楼乘坐地铁2号线，大约1小时20分钟在广兰路下，5号口出，步行到张江店。票价6元。张江店是在祖冲之郭守敬路上。在广兰路下车出来之后，沿着张江路/紫薇路 /青桐路的牌子显示的张江路方向走，然后需要穿过田园路，可以看到高斯路/川北公路/郭守敬路的交叉口，然后沿郭守敬路走大概10分钟就可以看到锦江之星 了。锦江之星附近有一个张江动漫谷，因为我比较晚到，所以没有时间去看。

从张江店附近找到公交车站，乘坐东川专线到张江地铁站下车，然后步行至百度上海研发中心，大约30分钟。票价1元。在张江地铁站下车之后，你要是问路人“baidu上海研发中心在哪里？“， 他们都不知道。因为上海研发中心刚成立。上海研发中心的位置是在张江微电子港（碧波路690）的4号楼里面。其中3，4层是baidu租下的，和当时北京 baidu在普天情况一样。张江微电子港那里有很多吃饭的店，并且因为公司没有食堂，所以中午有多人在那里吃饭。

从百度上海研发中心，步行至张江高科站5号口，乘坐地铁2号线到南京东路下车，从7号口出来插着明珠塔方向走到外滩，大约40分钟。票价4元。从7号口出来之后，运气好的话你就能够看到东方明珠塔了。然后朝着塔的方向 走，就可以找到外滩了。外滩就是能看到黄浦江，并且眺望过江可以看到明珠塔。另外两个标志性建筑就是陈毅广场和公牛广场。最令我吃惊的是，这里汇聚了很多 金融机构和品牌点，Omega,Rolex,Breguet,和平饭店，Jahwa,上海浦发银行，曼谷银行，华夏银行，招商银行，中国银行，工商银行， 农业银行，上海海关，上海银行，上海市总工会，上海黄金交易所，中国外汇交易中心，花旗银行，汇丰银行，罗斯福，Aurora。而且这里的建筑风格都是民 国时代上海的风格，顶多局部翻新了一下。

从南京东路7号口进入，乘坐2号线到人民广场站下车，9号口出到南京路新世界，大约2分钟。票价3元。从南京东路到南京路可能很近，但是为了赶时间还是坐地铁了，另外一方面不至 于迷失方向。新世界这里有黄河路美食休闲街（不过似乎不太好），有南京路步行街，新世界城（里面就有有名的杜莎夫人蜡像馆，收费好像是100元每位），还有上海市第一百货商店（在里面可以购买一些特产）。

从人民广场9号口进入，乘坐2号线到虹桥2号航站楼，大约40分钟。票价4元。

综合感受是:
- 地铁交通有点贵。机场的那个升降电梯控制系统能让人疯掉，不知道控制逻辑是怎么写的。
- 来上海一定要到南京路来转转，包括外滩和新世界这一带。
- 上海人比较不愿意帮人忙，我几次问路他们都立刻加快步伐离开。
- 后在来12年3月份又去了一次做dstream-udw的联合项目。给我另外一个感觉就是，上海司机开车好猛，不管是公交车还是出租车。我见到公交车司机直接走逆向道的，见到出租车司机拐弯不减速。
