#+title: 经济学的思维方式(Basic Economics : A Common Sense Guide to the Economy)

https://book.douban.com/subject/30274068/

《经济学的思维方式（人人都能看懂的经济学入门佳作，长居美国亚马逊经济类榜首、美国国民经济学读本。） (Chinese Edition)》
作者：托马斯·索维尔

** 什么是经济学?

要做到这一点，一种方法是考察经济决策产生的激励，而不是只考察其所追求的目标。这意味着，结果比意愿更重要——不仅是就直接后果而言，也指运行的长期影响。抱有良好意愿是再容易不过了，但是倘若不能对经济的运行方式有正确的理解，再好的意愿也可能给整个国家带来灾难性后果。相当数量的经济灾难其实是出于“好”政策，这些政策往往标榜要为人民造福。事实上，如果那些曾提出或支持这些政策的人懂经济学的话，这些灾难本可以避免。

要做出经济的决策，并不一定要涉及金钱。当某个军事医疗队抵达战场，见到各种各样的伤员，他们面临的就是一个经典的经济学问题，即如何分配具有多种用途的稀缺资源。在这种情况下，几乎不可能有足够的医生、护士或护理人员，也没有足够的药物。一些伤员濒临死亡，几乎没有救活的可能；而另一些伤员如果得到及时救护，就很可能活下来；还有一些伤员只受了轻伤，不管他们是否得到及时的医疗救助都很可能康复。如果医疗队不能有效分配时间和药物，就会在不需要紧急救护的伤员身上浪费时间，或把时间和药物分配给不管怎么救治死亡率都很高的伤员，而那些及时救治就能活下来的伤员将会无谓地死去。尽管不涉及任何金钱交易，这却是个经济学问题。我们中的大多数人，甚至不愿想象要做出这种生死攸关的选择。但事实是，一些美国中产阶级为不得不做的温和选择和权衡取舍而苦恼。生活并不会询问我们需要什么。它为我们提供选择。经济学就是试图教会我们做出这些选择的一种方法。

** 第一部分 价格与市场

由政府机构随时掌握2,400万种价格几乎不可能做到。在一个人口超过1亿的国家中，让个人自己追踪这些价格会更容易，因为任何个人或企业只要掌握与自己决策相关的几个价格就可以了。通过供求对价格的影响，以及价格对消费者和生产者行为的影响，无数独立的决策得到全面协调。让价格来说话，人们只当听众，他们的反应通常要比中央计划者整合报告资料快得多。虽然指挥人们采取行动看上去是一种更合理有序地调节经济的方式，实践中却缺乏效率。在苏联的中央计划经济时期，许多其他的商品也和鼹鼠毛皮一样。这是一个老大难的问题，仓库堆积大量滞销商品，其他商品却存在令人痛苦的短缺，而用于生产滞销商品的资源本可以用来生产短缺商品。在市场经济中，过剩商品的价格会根据供需关系自动下降，短缺商品的价格也会由于相同的原因自动提高，最终的结果是：当生产者追求利润避免损失的时候，资源自动从过剩产品转移到了短缺商品的生产中。

正如苏联经济学家指出的，苏联的企业不像市场经济国家的企业一样受财务约束，它们可以得到超过实际所需的机器，“这些机器要么在仓库里堆积灰尘，要么丟在户外生锈腐烂”。简而言之，苏联的企业没有动力去节约资源，换句话说，他们没有意识到资源是稀缺的，而且有其他有价值的用途，并且其他用途的使用者也没有像在市场经济中那样和他们竞争资源。虽然这些浪费不会给单个苏联企业带来损失，却使苏联人民付出了昂贵的代价，他们生活标准远远低于他们的资源和技术所具有的生产能力。

早在1978年，只有不到10%的中国农产品在公开市场上出售，而不是交由政府分配。但是到1990年，80%的农产品都直接在市场上出售。最终的结果是中国城市居民可以买到各种各样的食物，并且农民的收入在几年时间之内就增加了50%以上。不同于此前严厉的政府管制及其带来的严重经济问题，中国政府在1976年放松对市场价格的管制，随之而来的是1978年到1995年间令人震惊的年均9%的经济增长率。

为什么没有一种客观或“真实”价值？最根本原因是如果存在客观或真实价值，经济交易将失去理性基础。你会花1美元买份报纸，唯一的原因是报纸对你而言要比1美元更有价值；同样，人们愿意以1美元的价格出售报纸，唯一原因也是对他们而言1美元的价值要远远大于报纸。如果报纸或其他任何事物真的存在“真实”或客观的价值，而交易价格等于这一客观价值，那么不论是买方还是卖方都无法从中获益，因为此时他们获得的价值不会大于他们放弃的价值。既然这样，人们何必还要自寻烦恼地去做交易呢？另一方面，如果买方或卖方从交易中获得的价值大于客观价值，那么交易的另一方获得的价值必定小于客观价值。在这样的情况下，另一方为什么还要继续交易下去，继续受骗呢？只有当价值是主观的，每个人更依赖主观价值，买方和卖方之间的这种持续交易才能说得通。一个人的所得即他人所失，这是一种零和博弈，但是经济交易并不是一个零和博弈过程。

这意味着，从该地区饥饿的民众的角度来看，正是“贪婪”的供应商以最快的速度将食物运来，比执行人道主义任务的政府雇员将同样的食物运到他们面前快得多。想要通过销售食物赚取最高利润的那部分人，会披星戴月、披荆斩棘；而那些以“公益”之名行事的人，往往会不疾不徐，也不愿涉险。总而言之，人们总是利己多过利人，而自由波动的价格却能使人们在利己的同时也能利人。

总之，不论在某时某地如何紧急，都没有绝对的“需要”。不幸的是，大多数法律和政策都是绝对实施，因为在解释这些法律和政策的意思和它们应该应用的情况时，可能会出现政府官员独裁的危险。在这种情况下，声称绝对“需要”某种东西都是在玩火自焚。许多人抱怨一些本质上很好的政府政策实施效果很差，而他们没有看到在一个逐渐变化的世界中绝对的法律带来的根本问题。想要绝对推行某项致力于满足欲求的政策是不太可能的，因为这些欲求带来的收益是不断变化的，并在超过某一节点后，就不再是收益。

虽然人均住房空间并没有比第二次世界大战之前减少，但是在当时的价格下，短缺是真实而令人痛苦的，因为战争期间通过的房租管制法案，使得当时的价格被人为地降低到本应达到的价格水平以下。在这一人为的低价格水平下，更多的人产生了比房租管制法案实施前更多的住房空间需求。

虽然房租管制造成了很多严重的经济和社会问题，但是却往往能在政治上获得成功。政治家知道租户常常要比房东多，不懂得经济学的人要比懂经济学的人多。于是，提倡房租管制法的政客很容易赢得更多选票。把房租管制描绘成防止贪婪的房东向穷人“索要过高”房租的手段，在政治上往往很有效。但事实上，住房投资的回报率很少高于其他投资，而且房东往往也并不富有，特别是小面积低端公寓的房东，这些出租房需要不断修缮，所处地段往往也只能吸引低收入的租户。拥有这样住房的房东，很多本身就是身兼木匠和电工的杂工，他们用自己的劳动和技能维护和修缮房屋，希望用收来的租金还清房贷。总而言之，很大程度上由穷人租住的房屋的房主绝对算不上富裕。

购买相同的商品和服务，穷人最后总是比富人支付的更多，这一令人痛心的事实有一种非常直白的系统性解释：在低收入社区提供商品和服务的成本通常要高很多。为了应对高发的犯罪和恶意破坏行为所支付的高额保险费和各种各样的高额安保措施，是导致低收入社区商业成本较高的系统性原因，而这些原因却被那些想从个人动机方面寻求解释的人所忽略。此外，在低收入社区，每一美元的生意都要面临更高的成本。典当行或信贷公司贷给50个低收入者每人100美元和银行一次性贷款给一个中产阶级客户5,000美元相比，虽然金额总数一样，但是花费的时间和金钱都更多。

“首先，不要造成伤害。”这条原则已延续了数个世纪。明白系统性因果关系和意向因果关系的区别，是减少经济政策负面作用的一种方式。尤其重要的是，不能去伤害那些已经处于艰难经济环境中的人。我们也应该知道，即使在犯罪高发社区，大多数人也并不是罪犯。这些社区中的一小部分不正直的人，才是导致社区商业运营成本较高的真正源头，进而导致企业收取更高的价格。但是，不管是从理智上还是情感上来说，人们都很容易把高价格怪罪于收钱的人，而不是真正导致高价格的人。在政治上更是盛行谴责外来者，特别是当这些外来者有着不同的种族背景。

当高层政治领导制定某项政策或制度后，政府官员就会服从当局权威，他们可能会对违背自己的信念感到犹豫，但是不要指望他们指出这些政策和制度会出现的负面影响。带来坏消息的信使往往需要赌上自己的职业，甚至生命。对政府官员来说，执行某项具体政策可能是理性的；但对整个社会而言，这些政策却可能产生负面影响。例如，苏联在斯大林时期曾出现采矿设备的极度短缺，但是生产该设备的工厂管理人员却把生产出来的设备存入仓库，而不是把它们运送到急需这些设备的矿场。原因是官方命令要求这些设备必须涂上红色耐油性涂料，但是工厂只有绿色耐油性涂料，没有红色耐油性涂料。而且由于不存在自由市场，工厂很难买到符合规定的涂料。当时，不服从官方命令是一种重罪。“我可不想坐八年牢。”该厂的管理人员说。当他把这种情况解释给一名高级官员，并请求批准使用绿色耐油性涂料时，这名官员的回答是：“你要知道，我也不想坐八年牢。”不过，这名高级官员还是发电报给政府部门请求获得批准。经过很长一段时间的拖延，政府部门最终批准了他的请求，采矿设备也终于运到了矿场。这些人的行为并不愚蠢，他们在面对工作制度设定的激励和约束时，做出了相当理性的反应。在任何一种经济或政治体制中，人们只能在可行的多种备选方案中选择，只不过不同的经济体制提供的备选方案是不同的。

虽然自由市场中的系统性因果关系从某种意义上说是非人性化的，即它的结果并不是由任何特定个人预先确定的，但是“市场”归根结底是人们将自己的个人欲望与他人的欲望相互协调的一种方式。人们常常会错误地比较非人性化的市场与各种各样据称是富有仁慈心的政府政策。实际上，这两种体制都同样面临着资源的稀缺性，都同样要在资源稀缺性的约束下做出选择。不同之处在于：前者每一个单独个体为了自己的利益做出选择，后者则是一小部分人为成千上万其他人的利益做出选择。

依靠等待来获得想要的东西是非价格配置的一种常见形式。在商店排长队，比如在苏联；或加入手术候补名单，在政府提供免费医疗或大幅度补贴医疗的国家，病人就是这样做的。幸运和腐败也是价格配置的替代方式。当某种供不应求的产品补货到商店时，不管是谁，只要他恰好在该商店，就能够在第一时间买到该商品，而那些后来碰巧知道的人，在到达商店时会发现他们梦寐以求的商品已经销售一空。在其他情况下，为了得到优先权，个人或政治的偏袒抑或行贿受贿就会取代幸运；或者用一些正式的分配体系，比如官方机构制定的放之四海皆准的政策取代偏袒。但是不管怎样，忽视价格的作用，或是政府降低价格的做法，都无法取代市场经济体制中的价格配置机制。

明白替代机制的作用很重要，同样重要的是牢记有效配置资源需要渐进替代，而不是全部替换。比如说，一个人可能会认为健康比娱乐活动更重要，然而不管它作为一个一般性原理听起来多么合理，没有人会真的认为值得放弃所有的音乐转而购买20年份的创可贴放在壁橱里。一个价格调节的经济体制有助于渐进性替代，但是政治决策则倾向于确定优先事项——也就是说，它会宣布某件事情绝对要比其他事情更重要，并制定相应的法律和政策。当一位政治家说我们需要将某件事情“作为国家优先考虑的事”，也就相当于说要使A绝对地比B更重要。这与渐进性替代相反，因为在渐进性替代中，每一件东西的价值取决于我们当时拥有的数量，以及为了获得B，我们愿意放弃的A的数量。

有时候，人们会问：怎样给艺术定价？或怎样为教育、健康、音乐等定价？他们想用这样的理由让某些东西免于成本与收益的权衡。隐藏在这个问题下的是一个根本性错误，即人们认为价格仅仅是“施加”在事物之上的。只要艺术、教育、健康、音乐以及无数其他的东西都需要时间、努力和原材料，成本就是不可避免的。这些成本不会因为法律不允许它们在市场上通过价格传递而消失。最后，对整个社会而言，成本就是用相同的资源可以生产的其他东西。资金流量与价格变动就是这一事实的表现，即使抑制这些表现也不会改变隐藏的事实。

价格最有价值的经济作用是它传递了有关基本现实的信息，同时也提供了响应基本现实的激励。从这个意义上说，价格可以用一个简单的数字总览复杂现实的最终结果。举例来说，假设有一个专业摄影师想要买一个长焦镜头，这时他需要在两种镜头之间做出选择，这两种镜头的照片质量相当，放大倍数也相同，但其中一个镜头的采光是另一个的两倍。采光更好的镜片能够在弱光环境下拍摄照片，但是为了达到更好的采光而采用更大光圈也会带来一些光学问题。摄影师可能完全不知道这些光学问题，而且解决方案可能需要使用更昂贵的玻璃制成的更复杂镜片。摄影师要知道的只是，光圈更大的镜片价格也更高。摄影师唯一要决定的，是较高的价格对于他的拍摄需求是否值得。通常在阳光明媚的天气里进行户外摄影的风景摄影师会认为没有必要买更昂贵的镜头。然而，对于在博物馆内进行室内拍摄的摄影师来说，由于不允许用闪光灯，他只能花更多的钱购买镜片。知识是最稀缺的一种资源，价格使个人和组织在做决策时不必具备大量知识。摄影师不需要专门的光学知识就能在各种镜片间做出有效的选择，了解专业光学知识的镜片设计师也并不需要了解诸如博物馆的开放规则、博物馆照片的市场前景，以及其他有限光源场所的摄影需求等。

** 第二部分 工业与商业

不管在什么经济体中，知识都是最稀缺的资源之一，从知识中提炼的洞察力则更是稀缺。基于价格、利润和亏损的经济体，能够赋予拥有更多知识和洞察力的企业决定性的优势。换言之，知识和远见能够引导资源配置，即使大多数人——包括国家政治领导人并不具备相关的知识，也没有理解所发生之事的洞察力。显然，在政治领导人控制经济决策的经济体制中，事情却不是这样的，因为那些领导人有限的知识和洞察力变成了整个经济体进步的主要障碍。即使领导人比普通社会成员有着更多的知识和更敏锐的洞察力，他们也未必及得上散落在人民大众间的大量知识和洞察力。

由政治当局来运作经济的一大缺陷是，来自大众的洞察力没有足够的影响力让当权者改变其行为方式。不管在何种形式的经济或政治体系下，掌权者往往会变得自满、傲慢。说服他们做任何事都不容易，尤其是要说服他们以完全不同于以往的新的行为方式做事。自由市场的一大优点是，你不必就任何事说服任何人，你只要在市场上与他们竞争，让市场来检验哪种做法效果最好。想象詹姆斯·卡什·彭尼必须以口头方式说服西尔斯和蒙哥马利·沃德：不要以邮购方式从事零售业经营，而是建立一个全美国范围的连锁商店。在这样的经济体系中，这两家巨头的反应很可能是：“这个叫彭尼的家伙是谁？一个犄角旮旯的乡下小镇上的小商店合伙人也敢指手画脚，教导我们怎样去经营世界上最大的零售公司？”在市场经济里，彭尼不必努力说服任何人做任何事。他需要做的仅仅是把商品以更低的价格提供给消费者。结果就是彭尼获得了成功，西尔斯和蒙哥马利·沃德则出现巨额亏损，为了再次盈利，这两家行业巨头不得不仿照这个后起之秀的经营方式。彭尼成长于赤贫，比今天享有福利救济的大多数人还要贫困，但是他的思想和洞察力却战胜了那个时代最富有的人，这些人最终意识到：如果放任彭尼或其他人抢走顾客，公司每年将损失数百万美元，他们将无法保持富有。

一个只有世袭贵族、军政府或执政党成员才能做出重大决策的社会，是一个抛弃了大多数人的知识、洞察力和天赋的社会；一个只有男人才能做出重大决策的社会，是一个抛弃了人类一半的知识、洞察力和天赋的社会。

像其他事情一样，外人眼里，经营一家企业看起来很容易。布尔什维克革命前夕，共产主义运动领袖列宁宣称，“核算与控制”是经营企业的关键因素，并且资本主义已经将企业监管“简化”成“极其简单的操作”，“任何有点文化的人都能胜任”，不过就是“监督和记账，懂点算术四则运算，填制相应的票据”。在列宁看来，这些“登记、归档和检查都是极其简单的活动”，可以由获得平均工资的人“很容易地执行”。然而，作为苏联的领导者，几年之后列宁就面临了一个与预想非常不同又十分痛苦的现实。他写道，经济领域发生的“燃油危机”已经“威胁到整个苏联的运转”，并在国家内部造成“破坏、饥荒和灾难”，他甚至承认农民暴动已成为“一种普遍现象”。简而言之，一些看起来非常简单且容易执行的经济功能，变得极其困难。事后，列宁才认识到需要“精通管理艺术”的人才，并承认“这类人只存在于旧阶级中”，也就是那些资本主义商人。在1920年共产主义大会上，列宁警告他的同志：“对企业管理的看法，往往充满了十足的无知，一种反对专家的错误精神。”就在三年前还想当然觉得的简单事情，此时转而需要寻求专家的帮助。由此开始了列宁的新经济政策，该政策允许更多的市场活动，苏联的经济于是开始复苏。

即使不同产品的周转率不同，利润率也会有所不同，但为了获得投资而进行的竞争会使利润率趋向均等化。钢琴商店要经营下去，就必须在售价中包含高额的毛利，以弥补较低的周转率。否则投资者就会把钱投资到其他地方，而钢琴商店就会渐渐消失。如果超市在较短的时间里就能收回资金，那么它就能进行再周转和再投资，购买更多的面包和日用品。在一年时间里，同样的资金会在超市周转许多次，且每一次都会获得利润，因此同样的初始投资，即使超市的1美元只赚1美分利润，一年当中能产生的总利润率，也会与毛利很高但周转很慢的钢琴商店的利润率相当。

销售利润与投资利润不仅是概念上的区别，它们会向相反的方向变动。20世纪20年代，A&P百货连锁店能够占据统治地位的关键因素之一，就是公司管理人员做出了一个明智的决定，即通过削减销售利润率来增加投资利润率。由于降低了每件商品的销售利润，A&P百货连锁店的新定价也随之降低，从而吸引了大量的新顾客，而销售量的增加使得总利润比以前大得多。虽然卖出1美元的物品只能赚几美分，但是由于存货一年周转了近30次,因此A&P百货连锁店的投资利润率急剧飙升。这种薄利多销的策略于是成为一种模式，并扩展到其他连锁百货和其他类型的企业。消费者受益于较低的价格，而A&P百货连锁店也从其投资中获得了较高利润——这一点进一步证明，经济交易不是一个零和博弈的过程。后来，大型超市具有了更大的销售规模，能够把销售利润率削减得更低，从而使它们能够凭借更低的价格，取代A&P百货连锁店的领导地位。

低收入社区的商店也可以提高价格来补偿高额的成本，但是它们面临一个限制因素，那就是许多低收入社区的居民会去高收入社区的商店购物，高收入社区的商店售价要低很多，即使需要支付公交费用或出租车费用也是值得的。低收入社区的价格越高，越多的人就会到其他地方购物。因此，这些低收入社区的商店只能在一定范围内提高价格以弥补高额的成本和低周转率，并常常会陷入财务危机，即便如此，它们还要被谴责为“剥削顾客”。

每一个企业增加产量都会面临一个临界点，超出这个临界点，单位产出的生产成本就不再随着生产量的增加而减少。事实上，当一家企业的规模变得过于庞大，监督和协调就很难进行，单位产出的成本实际上是上升的，因为右手不可能总能知道左手在干什么。②追溯到20世纪60年代，美国电话电报公司（AT&T）还是世界上最大的公司，其首席执行官曾这样说道：“AT&T是如此庞大，如果你今天在它的屁股上踢一脚，两年后它才会发出‘哎哟’一声。”

苏联曾痴迷于规模经济，而忽视了规模不经济，因此它的工业企业和农业企业都是世界上最大的。例如，苏联农场的平均规模是美国的10倍，雇用的工人则是美国的10倍还多，但是苏联农场的效率之低众所周知。引用苏联经济学家的话来解释，效率低是因为“缺乏协调性”。我们可以用一个例子来解释这个一般性问题：在广阔的公地上，成队的拖拉机呈扇形展开耕作。计划完成情况是基于耕种的公顷数来评判，因此这就会导致工人尽可能快地耕作尽可能多的土地。工人们会逐渐从田地边缘开始减少犁沟的深度。当他们逐渐深入田地，就会开始抬高犁头，并加速拖拉机，因此犁沟就会越来越浅。第一道沟深9~10英寸，再远一点，深度只有5~6英寸；在田地中央，拖拉机司机很确定没有人会监督他们，因此犁沟就会浅至2英寸。一般而言，没有人会发现田地中央的犁沟是这么浅，直到农作物发育不良，人们才会发现这些问题。

这些苏联经济学家说：“我们的库存几乎跟我们一年的产量一样多。”换句话说，苏联工厂中的大部分工人即使“带薪休假一年”，经济还可以依赖库存维持下来。但这并不是优点，而是一种障碍，因为库存也有成本，而且不挣钱。从整个经济的角度来看，产品库存消耗了资源但却没有提高公众的生活水平。正如苏联经济学家指出的那样：“我们的经济一直受到大量库存的重压，甚至比资本主义经济在最严重的衰退期的压力还大。”

幸运的是，若没有保护垄断企业不受竞争的法律，垄断很难维持。投资者不断寻找最高的回报率，最终使投资涌进经济中任何能获得更高利润的部门，直到流入的投资相互之间的竞争加剧，使该部门的利润率降低，这就像水总是往低处流。但是，正如水坝可以阻止水往低处流，政府干预能够让垄断的高利润率不受竞争的影响。

一个成功的卡特尔不仅需要企业间的协议，而且也需要可以相互监督并防止成员违反协议，同时还需要限制卡特尔之外的公司引起的竞争。这些事情都是说起来容易，做起来难。美国最成功的卡特尔是钢铁行业的卡特尔，它有一个企业很容易相互监督的价格体系①，但它最终被法院判定为违反了反托拉斯法。

在世界的另一端，印度试图提高电价，却引来人们的街头示威抗议，这与美国加利福尼亚州的情形一样。印度国民大会党在印度卡纳塔克邦是执政党，该党曾努力调整电价，却遭到某个反对党的街头游行反对。然而，在相邻的安得拉邦，印度国民大会党是当地的反对党，却领导了游行示威来反对电价的上涨。换句话说，这些游行示威既不关乎意识形态，也不关乎政党，而是对公众误解的伺机玩弄。

政治复杂性加剧了监管委员会设定价格时包含的经济复杂性。监管机构的设立往往是因为，一些政治改革倡导者的成功调查或公共活动说服了当局建立一个常设委员会，来监督和控制一个垄断或一些企业数量非常少且有可能联合起来形成垄断企业集团的行业。然而，在委员会成立并拥有权力之后，改革倡导者和媒体就对它失去了兴趣，并将注意力转向其他事情。与此同时，被监管的企业会继续密切关注这个委员会的行动，并游说政府，从而获得有利的管制政策和有利的委员会成员任命。这些机构的外部利益不对称，带来的最终结果是，为了消费者的利益而建立起来管制某些企业或行业的委员会，往往会变成保护现有被监管公司的机构，让它们免受来自拥有新技术或新管理方法的新公司的威胁。美国的州际商务委员会建立的初衷是防止铁路公司向公众收取垄断价格，现在却把控制能力扩展到货车运输业，以此回应货车运输的崛起，因为货运在运货方面的竞争威胁到了铁路行业的经济效益。

各行各业实施管制的最初理由是防止价格过度上涨，但是多年后，管制却变为监管限制，为了让现有的企业生存下去而防止价格下降。政治改革倡导者常常信奉于似是而非的理论，然而即使这些理论依据确实可信且能被正确实施，实际的结果也可能与最初的目标南辕北辙。在人类活动的各个领域，人们都会犯错。但是，在竞争经济中出现重大错误时，犯错误的人会因错误带来的损失被清理出市场。然而，在政治上，即使最初存在的理由消失之后，监管机构往往也能继续保留下来，而他们之后的所作所为，也远远超过该机构设立或获得权力时的设想。

对生产商而言，比起需要通过加班来完成的许多同时期的意外小订单，可以超前安排生产计划的大订单的生产成本更低。反复无常的订单很可能带来空闲期，到那时候，工厂将因为订单不足而解雇工人。而在空闲期遭到解雇的工人可能会找到其他工作，并不会因原雇主订单再次增加而返回。这样，雇主就需要雇用新工人，这必然会产生培训成本并降低生产率，直到新工人获得足够的经验，达到最高效率。不仅如此，无法提供稳定工作的雇主会发现，招募工人越来越困难，除非支付更高的报酬来弥补工作的不确定性。

虽然卖方可以在法庭上为自己辩护，指出销售产品时，成本会因不同类型的买方而不同，但是与反方律师、会计师和经济学家辩论时，看似简单的“成本”概念却会变得不再简单。通常的情形是双方都不能确切地证明成本是什么，而被告往往会败诉。在这些诉讼中，美国政府从根本上背离了英美法系几个世纪以来的传统，它仅需要做一些表面或初步的辩护，基于总量，将举证责任推卸给被告。多年后，同样的原则和程序又在民权法下的就业歧视案中重演。企业非常明白，不论实情如何，自证清白在事实上是不可能的，因此与反托拉斯案一样，就业歧视案也产生了大量的自愿协议和庭外和解。

这就带来了一个远超铝业的问题。说这家或那家公司“控制”了市场的百分之多少实际上忽视了替代品的作用，而替代品可能被官方归类在其他行业，但如果垄断产品的价格大幅度上涨，许多买者就会选择替代品。不论是在垄断市场上还是在竞争市场上，从技术上看非常不同的产品也可能作为替代品使用，如电视机替代了报纸作为信息来源和娱乐方式，又如带拍照功能的智能手机严重威胁到了简易低价的柯达相机，后者曾长期为柯达公司创造大量利润。计算柯达公司“控制”的市场份额时，手机和相机被归类在两个相互分离的行业，但经济现实却不这么认为。

作为反托拉斯法传统的一部分，“掠夺性”定价是一个引人注目的理论。根据这一理论，想要除掉小竞争者并占领更多市场份额的大公司，会将产品价格降低到亏损的水平，迫使不能承受持续损失的竞争者在耗尽资源后退出市场。然后，获得垄断地位的大公司就会提高价格，而且价格不仅会回到以前的水平，还会提高到垄断地位带来的更高水平。这样，根据掠夺性定价理论，它会以牺牲消费者的利益为代价，弥补之前的损失，并在此后享受超额利润。

由于这一理论几乎不可能进行证伪，被起诉的企业不能辩称它没有追求这一目标，问题就仅仅变成了法官是否选择相信它。掠夺性定价不只是一个没有证据的理论，它也几乎或根本没有经济意义。为了将一个竞争者逐出市场，以低于成本的价格出售产品，这个公司遵循的是非常危险的策略，它会不断亏损。它唯一能确定的是一开始会赔钱。长期来看能否获得足够的额外利润以补偿这笔赌资是未知的。它能否得到补偿并同时避免反托拉斯法的制裁就更不可知了，而且反托拉斯法会带来数百万的罚款并导致公司被拆分。但是，即使这家可能的掠夺者公司成功地克服了这些难以克服的问题，也并不能保证消灭现存的所有竞争者就意味着消除了竞争。即使一家竞争对手被迫破产，它的实物设备和技术人员也并不会随风消逝。这些设备和人员可能会被新产生的企业家获得，而且获得这些实物设备和失业工人的成本很可能非常低，使得这个新竞争者的成本比破产的竞争者更低，这样它就成为更危险的竞争者，因为它能用更低的价格或相同的价格提供更高的质量。

破产可以消除特定企业的所有者和管理者，但是它并不能消除新进入者带来的竞争。这些新进入者既可以接管一个已破产的企业，也可以在该产业中白手起家创办自己的企业。摧毁某个竞争者，或是摧毁所有现存的竞争者，都不意味着消除了竞争，它还会以新企业的方式出现。总之，“掠夺性”定价是一个成本高昂的险招，要想用随之而来的垄断利润来补偿初始损失，希望微乎其微。它不过是一个没有具体实例的理论，这一点我们不用感到惊讶。我们应该惊讶的是，这一未经证实的理论在反托拉斯案件中受到如此的重视。

不管是在市场经济中还是计划经济中，垄断都是效率的敌人。而这两种经济的不同之处就在于，计划经济体制下垄断更常见。在混合经济中，一些经济活动由政府来实行，另一些由私人行业来实行，政府的活动往往就是典型的垄断，而私人市场中的经济活动一般由竞争企业来实行。因此，当飓风、洪水和其他自然灾害袭击美国某一地区时，参与紧急救援的通常既有美国联邦应急管理署FEMA，也有众多私人保险公司，因为后者的客户遭受了房屋与财产损失。与私人保险公司相比，FEMA是出了名的拖拉和低效率。保险公司把钱交到投保人手里的速度，不能比它的竞争对手慢。因为如果保险公司不能及时把钱给投保人，而他们的邻居却已经从另一家保险公司收到巨额预付款来渡过难关，不仅灾区的现有客户会转换保险公司，有关的消息也会在整个国家散播，导致其他地方的数百万人将价值数亿美元的保险业务从效率低的公司转移到效率高的公司。然而，政府机构不用面对这种压力。不管FEMA因没有及时将救援设备送到灾区受害者手里受到多大的批评或嘲弄，并没有与之竞争的政府机构能够给人们带来同样的服务。此外，掌管这些政府机构的人拿的是固定薪资，而不是基于他们能够多快或多好地服务于灾民。

在鸡肉上，美国农业部为学校提供的成千上万吨鸡肉都是劣质品，这些鸡肉甚至可以拿去做堆肥或宠物食品。这些鸡肉都来自“衰竭的母鸡”，因为它们已经过了产蛋期，这些鸡不符合山德士上校的要求，肯德基不会去购买，而且它们也不符合做汤的要求。金宝汤公司声称出于“质量的考虑”，一年前就停止使用这样的鸡肉了。

虽然所有经济部门以同样的步伐同时发展，能够让我们的生活更愉悦、更简单，但是在任何一个变化的经济体中，这都不可能成为现实。我们无法预测新的技术和组织方式或融资方法什么时候在哪里出现。想要知道新发现是什么，就需要在新发现之前先发现它。很明显，这是相互矛盾的。

** 第三部分 劳动与报酬

在一些只能勉强维持生存的极度贫困的国家，从事体力劳动的性别差异非常巨大，以至于最贫穷的人常常杀死女婴。虽然母亲对于一个家庭来说是必要的，但是额外的女性家庭成员运用原始的工具，在小块土地上从事艰苦的农业劳动，生产的食物还不够自己活命，而且在营养不良和饥荒盛行的时期，她消耗了其他人生产的食物，也威胁到整个家庭的生存。经济发展的好处之一就是，人们不必再面对令人绝望的残酷选择。

实施歧视的人要付出歧视成本，这是理解这类行为的关键。花别人钱的雇主——比如政府机构或非营利组织，歧视成本的影响更小。因此相较在竞争性私营市场中经营的企业，政府施加的歧视要更大，世界各国都是如此。了解歧视的基本经济学原理，能使我们更容易理解为什么20世纪20年代黑人能够在百老汇成功演出，当时他们不被允许参加美国海军，而且也不被允许担任政府文职工作。雇用黑人演艺者能够吸引大量观众，百老汇的制片人自然不想失去赚大钱的机会，但是政府的歧视成本由纳税人承担，而不管政府是否意识到歧视要付出代价。

在生产过程中，资本补充了劳动，但是也与劳动就业形成竞争。换句话说，生产商品和服务，要么用大量劳动和少量资本，要么用大量资本和少量劳动。当运输工人工会迫使运输公司将司机工资水平提高到超过竞争市场上本应有的水平时，为了节省更加昂贵的劳动，运输公司往往会增加资本。于是公共汽车变得更长，有时甚至把两个公共汽车用一个具有弹性的设备连到一块，这样一个司机也就使用两倍于以前的资本了，并可以运输两倍于以前的乘客。

长期以来，欧洲人认为美国的农业是“低效率”的，因为美国每英亩的产量要比大多数欧洲国家低很多。然而，美国每个农民的产量要比欧洲高出很多。原因是美国土地资源丰富，而劳动力稀缺。一个美国农民要看顾更多的土地，在每英亩土地上的投入就相应地减少。而欧洲土地稀缺，根据供求关系，土地也更昂贵，欧洲农民专注于在能得到的土地上精耕细作，花费更多的时间清理杂草和石块，或者投入更多的精力，确保每英亩获得最大产量。

同样，第三世界国家往往要比更富有、工业化程度更高的国家更能充分利用资本设备。像锤子、螺丝刀这样的工具，在美国的工厂或车间里几乎人手一套，但是在贫穷国家，这些工具通常由几个人共用，或在大范围内共用，而生产同样产品的美国工人则不需要这么大范围地共用工具。从另一个角度来看，在贫穷的国家，每把锤子每年钉的钉子也更多，因为它在更多的人之间共用且闲置时间更少。但是，这并没有使这些贫穷的国家更有“效率”，只是资本和劳动的相对稀缺性不同而已。

总而言之，富裕国家的人可以在使用很短的时间后就丢弃汽车、冰箱和其他资本设备，贫穷国家的人却不能这么做。这也不是能不能承受得起“浪费”的问题。在日本、美国或德国这些经济体中，花费同样的精力能够生产足够多的替代品，因此继续维修这个设备就是一种浪费。但是，在贫穷国家，工人的时间没有高效的可替代用途，因此像富裕国家的人那样使用很短的时间就废弃设备是不明智的。迪拜的劳动力比日本便宜，这并不是一种偶然。富裕国家的劳动力有更高的产出。这也是富裕国家更富有的主要原因之一。从富裕国家向贫穷国家出售使用过的设施，是这两种国家应对要素稀缺程度和生产效率不同的一种有效方式。在现代工业化经济中，许多物品都是批量生产的，因此规模经济降低了它们的成本。但是，修理这些产品仍然由个人手工完成，没有了规模经济带来的利益，产品的维修也就相对昂贵。在这种批量生产的经济中，反复修理会达到一个临界点，超过这一点更换一个新的、批量生产的替代品会更便宜。美国的电视机维修店的数量远远赶不上电视机的增长，因为批量生产已经把电视机的价格降低到这一点，即对于许多发生故障的电视机来说，更换新的要比维修旧的更便宜。

由两位俄罗斯经济学家著述的一本书回顾了苏联时代，指出苏联的“设备被无休止地修理、修补”，以至于“苏联每件资本品的平均使用期限达到了47年，而美国仅为17年”。这不是炫耀，而是在抱怨。

明确的最低工资标准低估了欧洲国家政府施加的劳动成本，而且欧洲国家政府还强制雇主参与退休金计划，支付健康福利等。强制性福利的高成本产生的经济效果，与最低工资带来的高成本产生的经济效果相当。20世纪八九十年代，当雇主支付的政府强制性福利大幅增加时，欧洲的失业率也随之急剧上升。

工会也能从最低工资法中受益，它们还是这些法律最强有力的支持者，即使工会成员的工资远远高于最低工资水平。工会这样做是有原因的。生产大多数产品和服务可以选择使用较多劳动力和较少资金，也可以选择使用较少劳动力和较多的资金；同样地，生产大多数东西，也可以根据相对成本，使用不同比例的非熟练劳动力和熟练劳动力。有经验的工会工人会与那些年轻、缺少经验、缺乏技能并且工资可能接近最低工资水平的工人竞争工作。最低工资标准越高，可能就会有越多的没有技能、没有经验的工人被经验更丰富和技能更高的工会工人所取代。

各种各样的群体在围绕最低工资法的议题中投入了巨大的财力、政治、情感和思想，这就意味着要进行冷静的分析是不可能的。此外，影响就业有许多不断变化的变量，从中分离出最低工资水平对就业的影响在统计上非常复杂，因此在检视经验数据的时候，确实有可能存在分歧。然而说到底，大多数经验研究（empiricalstudy）表明，最低工资法在总体上减少了就业，特别是减少了低技能的年轻人和少数工人的就业。

第三世界国家的工人总体上是否从人为设定的高工资水平受益还不清楚。有工作的工人，也就是那些向外观望的局内人，显然是受益者，而那些想受雇用的局外人却遭受了损失。对于整个国家的人口（包括消费者在内）来说，我们也很难判断是否会有净收益，因为当人们愿意工作却很难找到工作时，就会导致消费品生产的减少。唯一明确的受益者是那些生活在较富裕国家中的人，他们可以享受帮助贫穷国家人民的感觉，或是觉得第三世界国家的领导人都太自负了，不能让他们的工人按照与生产力相称的工资水平得到雇用。

虽然失业统计数据极具价值，但如果不牢记其定义，失业统计数据也可能会产生误导。失业率依据的是劳动力中没有工作的人所占的比重。然而，人们可以进行选择，决定是否在某些时间参与劳动，这意味着失业率并不是完全客观的数据，它会随不同环境下人们的选择不同而变化，在国与国之间也存在差异。虽然失业率应该能够显示劳动力中拥有工作与没有工作的人口比例，但是有时候失业率随着失业人口的增加反而会下降。原因在于，长期的衰退或萧条会导致一些人在经过漫长而徒劳的搜索后，放弃寻找工作。由于这些人不再被计入劳动力，他们的退出将减少失业率，即使没有工作的人口比例并没有降低。

虽然对政府来讲，强制由雇主为提高工人待遇买单，总是具有政治上的吸引力——因为相较流失的雇主选票，政府能从工人那里赢得更多的选票，而且不费一分一毫——但是出台这些政策的政界人士和选民却很少关注由此引发的经济影响。当经济摆脱萧条开始回暖的时候，随着产出的增加，失业者却不能重新得到雇用的一个原因就是，延长现有工人的工作时间对雇主来说要比雇用新的工人更便宜。因为增加现有雇员的工作时间不需要支付额外的强制福利，而雇用新的工人就要增加福利支出。尽管延长工作时间要支付更高的工资，然而在许多情况下，让已有的这些工人工作更长时间，仍然要比雇用新的工人便宜。

就人道主义组织推动童工法立法的最初原因而言，禁止青少年在空调办公室内工作似乎是不合理的，但是从这些新选民的利益来看，却完全讲得通。暂且不论从社会整体的角度来看，阻止这么多年轻人用合法途径赚钱是否合理，逼得这些年轻人通过非法途径谋生又是另一个问题了。

市场竞争带来的工作条件改善和政府强制改善工作环境不同，市场带来的改善来自于工人具有了更多的选择权，因为有更多的雇主为得到具有更多工作经验和更高生产率的工人而展开竞争，而政府管制无谓地提高用工成本——不论这些成本是否超过劳动生产率，只会减少工人现有的选择空间。

曾经人们一致认为工会对工人来说是一件好事和必需品，现在已经有越来越多的人开始对工会在经济衰退和许多行业的失业中所起作用产生怀疑和担忧。面对众多用人单位濒临倒闭、大幅度减少招工，许多工会不得不“做出让步”，即放弃他们过去为自己的成员所争取的各种报酬和福利。虽然这样做很痛苦，但许多工会还是声称这是保护工会成员获得工作的唯一方式。

多年来，工会和它们的成员经过一番曲折，才懂得经济学的入门知识——价格降低时人们增加购买，价格升高时人们减少购买。这并不是一个复杂难懂的原理，但是常常迷失在时间的漩涡和振奋的辞藻中。多年来，美国劳动力加入工会的比例已经下降。因为对工会产生的经济影响的怀疑已经在工人间传播开来，他们渐渐开始投票反对工会来代表他们。20世纪中叶，有32%的工人加入工会，但是到20世纪末，只有14%的工人加入工会。此外，工会成员的构成也发生了巨大变化。20世纪上半叶，美国经济中的大型工会组织主要集中在矿产、汽车、钢铁和货运部门。但是到了20世纪末，最大且发展最迅速的工会是由政府雇员组成的工会。2007年，只有8%的私营企业雇员加入工会。到目前为止，美国最大的工会是教师工会，即美国国家教育协会。

然而，如果政府支付所有的医疗费用或雇用所有的医生，那么现有的医生几乎没得选择，只能接受政府的管制。现有的医生可以进入并能获得更好报酬的行业非常稀有，因为要成为律师或工程师，需要再次投入昂贵的教育和培训成本。因此，大多数医生很少有现实可行的替代职业，他们也不太可能成为卡车司机或木匠，因为如果他们事先知道今后的实际收入水平，就根本不会进入医疗行业。

若是某种特殊类型的劳动力，只有一个雇主可以选择，那么当然这个唯一的雇主可以将薪酬设置在低于吸引新人进入的水平。但是，这种情况更可能发生在高度专业化的熟练员工身上，如宇航员，非专业工人则很少遇到这种情况，因为非专业工人可以受雇于各种各样的企业、政府机构，甚至私人雇主。在现代交通普及之前，地方上的劳动力市场往往是孤立的，而某个雇主可能是当地某个职业唯一的劳动购买者。但是，随着低成本交通的普及，这样的情况变得稀有。

人们往往倾向于把低工资看作工人正在遭受剥削，如果把这一倾向作为一种寻求纠错的道德诉求或政治运动，将很容易理解。但是，正如经济学家亨利·黑兹利特（HenryHazlitt）多年前所说的：贫困的真正问题不在于“分配”，而在于生产。穷人之所以贫穷，不是因为他们被剥夺，而是因为他们没有足够的产出，无论这是出于什么原因。把剥削视为原因对贫困问题没有丝毫帮助，只会让解决方案变得更困难、更不确定，也更耗时。同时这样的解决方案还会要求，除了和愿意施以援手的人合作，同处贫困的人也要相互合作，但是没有他人的帮助，他们并不能解决问题。穷人自身也许并没有什么好指责的，因为他们的贫穷可能是由于许多身不由己的因素，包括以往的经历等，这些都远非人们当下所能控制。

** 第四部分 时间与风险

当然，教育也对经济发展以及生活水平的提高做出了重要贡献。但这并不是说所有的教育都是如此。从经济角度来看，有些教育有很大的价值，有些则没有价值，还有些甚至会产生负面效应。例如，虽然我们很容易理解医学、工程学方面的专业技能具有巨大的价值，数学也能为许多行业提供基础，然而许多其他的学科，如文学，就无法说自己也能使人获得具有市场价值的技能，但是它会以其他方式做出贡献。在教育或高等教育刚刚起步或匮乏的国家，许多已经获得文凭或学位的人可能会觉得，自己的能力足以胜任许多工作。在这样的社会，即使是工程师也更愿意待在办公室里，而不愿意穿着长筒橡胶靴去泥泞的建筑工地。基于他们的所学，新接受教育的人可能会有更高的期望，而他们的能力水平所能创造的财富却远远满足不了他们的期望。

特别是在第三世界国家，家庭中第一批接受高等教育的成员，往往并不会学习科学、医学、工程学这类难度大、要求高的学科，他们倾向于更简单、更笼统的学科，这些学科并不会给他们带来具有市场价值的技能，而正是科学、医学、工程学这些具有市场价值的技能才能够为他们自己或国家创造财富。大量接受教育却没有获得具有经济价值的技能的年轻人，在第三世界国家造成了大批失业。由于市场不能为他们提供期望的职业，政府不得不建立臃肿的官僚机构来雇用他们，以此消除潜在的政治不满、国内动乱或叛乱。反过来，这些官僚机构和他们冗长、费时的繁文缛节，却阻碍了真正具有技能和企业家精神并且能为国家经济进步做出贡献的人。

根据一名印度主管的说法，印度有大量的政府规章对企业进行微观管理，“确保每家企业每月都会违反这条或那条法律”。企业在自由市场经济中可以自行从事的许多活动，在印度却需要提出申请，取得政府许可。为此，大量印度企业在新德里建立了与政府机构类似的自己的官僚机构，以便时刻跟踪申请的进展情况；并且在必要时进行贿赂，以获得政府许可。

金融中介机构跟其他经济制度一样，通过观察它们无法履行职能时的后果，我们能够更清楚地看到金融中介机构的作用。一个缺乏良好运作的金融机构的社会很少有机会创造更大的财富。贫穷的国家会因此一直贫穷，虽然它们有丰富的自然资源，但是它们还没有建立起综合完善的金融机构，没有办法将无数个体手中的零散存款筹集起来，也就没有办法进行更大的投资，把自然资源转化成可以使用的产出。有时候，在金融机构完善的国家，外国投资者是唯一能够行使这些职能的人。而大部分贫穷国家并不具备可靠的法律和保障财产所有权的法律框架，来保护国内或国外的机构行使职能。

人们很容易将可见因素当作唯一的或最重要的因素，即使一家管理有方的企业因这些因素繁荣壮大，同时同一行业中有些具有相同可见因素的企业却在破产。不论是在经济上，还是在政治上，这种误解并非无关紧要。许多法律和政府经济政策都基于这些误解。复杂的意识形态和大众运动都是基于这样的观点，即只有工人才“真正地”创造财富，而其他人只是捞取利润，他们没有对财富做出任何贡献，却不道义地分享了财富。

当商品投机者购买尚未种植的小麦时，农民种植小麦就会变得简单，因为农民不必知道收获季节的小麦市场价格。期货合约保障了卖方预先指定的价格，而不管交割时点的市场价格如何。这就将农业和经济预测分离，分别交给擅长不同活动的专业人士来做。投机者利用市场知识、经济与统计分析资料，尽力做到比农民的猜测更准确。于是给出对农民有吸引力的价格，让农民觉得可以现在卖出小麦，而不是等到收获季节按照那时的价格卖出。

风险的全部成本不只包括投入的金钱，还包括在等待过程中的担惊受怕。农民期望自己的作物可以每吨卖1,000美元，但是他也知道有可能每吨只能卖500美元，或卖到1,500美元。如果有投机者愿意用每吨900美元的价格购买他的作物，而且这个价格能够使他避免几个月的失眠担忧，那么这就是合意的价格。因为农民不用再担心收获时的价格太低不能弥补种植作物的成本，无法养家糊口。投机者不仅财务状况更加良好，足以应对投机失败，而且在心理上也做好了准备，因为过分担忧的人通常不会参与商品投机。我认识一位商品投机者，有一年他的公司一直到12月份都还在亏损，但是就在12月出现了诸多变化，让他在这一年最终实现盈利。他为此感到很惊讶，其他人同样也很惊讶。这个职业并不适合心理脆弱的人。

经济投机是配置稀缺资源的又一种方式，而它配置的稀缺资源就是知识。投机者和农民都不知道作物收获时的价格将会如何。但是，投机者比农民具有更多的市场和经济学知识，以及更多的统计分析知识，而农民则拥有更多的种植农作物的知识。我的商品投机商朋友承认说，他从没见过大豆，也不知道它们长什么样子，尽管数年来他可能已经买进卖出了价值数百万美元的大豆。他只是在收获的季节，将纸面上的大豆所有权转移给大豆购买商。他真正做的并不是大豆生意，而是风险管理生意。

许多关于风险的经济学原理同样适用于与市场无关的活动。即将要上战场士兵不会仅仅携带射击所需的子弹，或只带上受伤时会用到的急救用品，因为谁都不可能预见战场上的形势。士兵需要携带一定量的弹药和医药用品以应对各种各样的意外。但同时，如果他过多地携带每一种可能用到的东西，他就无法投入战斗。因为这会使他行动缓慢，减少他的机动性，使他很容易成为敌人的靶子。换句话说，超过了某一个临界点，任何试图使他更安全的行为都只会让他更危险。

库存还以另一种方式与知识和风险关联在一起。在正常年代里，每一个企业都会持有一定量的库存，并且这些库存和销售成一定比例。然而，当人们所处的年代变得不稳定，比如在经济衰退或经济大萧条时期，他们就会卖出存货并且不再生产新产品。例如，2003年第三季度，随着美国逐渐从经济衰退中恢复过来，销售额、出口额以及利润额都上升了，但是《商业周刊》杂志报道称它的生产商、批发商以及零售商“卖的都是货架上的商品”，而且“库存率也创造了最低纪录”。最终结果是，创造的就业要远远少于过去同期贸易活动增加所创造的就业机会，我们可以用“失业型复苏”来描述这一情形，因为企业并不相信复苏会持续下去。总之，对卖方来说，出售库存是应对经济风险的一种方式。只有在库存见底之后，企业才会雇用更多的人来生产更多的产品，随着规模的扩大，再用“失业型复苏”来描述就不合适了。

生产石油的成本不仅包括地质勘探的费用，还包括最终发现石油之前钻取干井所花费的昂贵成本。随着投入成本的增加，全世界有越来越多的石油被发现，而不断增多的已探明石油储量会通过供求关系降低石油价格。最终达到一个临界点，即在某个地方每多发现一桶石油并进行提炼的成本，超过了可能会发现的每桶石油的现值。达到这一点时，就不值得再继续勘探石油了。在许多情况下，在这一点发现的石油总量，能够使用的年份可能并不会比13年更长，这就产生了我们正在耗尽石油的可怕预测。但是，随着现有的石油渐渐被用光，上升的价格就会使人们对石油勘探进行更大的投资。

虽然人们通常会从实际数量方面来谈论一个国家的自然资源储量，但是要想得出有实际意义的结论就必须考虑成本、价格和现值等经济概念。除了自然资源将会耗尽的警告，还存在一种相反的不合情理的乐观言论，即许多贫穷的国家拥有价值数十亿美元的“自然财富”，这些财富以铁矿石、铝土矿或其他自然资源的形式存在。这些言论没有考虑开采和提炼的成本，而且不同的地方成本差别也很大，因此它们是毫无意义的。例如，从加拿大的油砂中提取石油的成本非常巨大，直到最近几年那里出产的石油才被纳入世界石油储量。但是，当石油价格上涨到每桶100美元，加拿大就成为世界石油储量最大的国家之一。

在理想状态下，如果有前途的学生可以而且确实会发行股票和债券，那么就没有必要让父母或纳税人补贴他们的教育了，即使是非常贫困的学生也可以在没有助学金的情况下去上最昂贵的大学。然而，法律问题、制度惯性和社会态度，阻碍了这种措施在高校中普及。耶鲁大学在20世纪70年代提供一种未来还款额随借款人的未来收入变化而变化的贷款，法律、商业和医疗专业的新生往往都不会通过这项计划从学校贷款，因为他们有很高的预期收入，参加这项计划意味着他们需要偿还的金额远多于贷款额。他们更愿意发行债券而不是股票。

强迫所有银行和储蓄贷款协会购买存款保险消除了逆向选择的问题，但也增加了道德风险。储户不用再担心已投保的金融机构的决策是谨慎还是轻率，因为他们的存款已经投保，即使银行或储蓄贷款协会破产，他们也能得到一定的金钱。换句话说，这些机构的管理者不用再担心管理层进行高风险投资时，储户会撤回存款。最终它们做出了更多的冒险行为，正是因为道德风险，储蓄贷款协会在20世纪80年代损失了超过5,000亿美元。

过度关注政治上定义的“公平”而非风险，导致了2003年美国参议员以95对0的投票通过了一项法案，禁止保险公司对基因测试显示的某些疾病的高发病率人群实施“歧视”。当然，这些人的基因恰巧如此，并不是他们的错误，但保险费基于的是风险而不是错误。通过法律禁止风险反映在保险费和保险范围中，意味着保险费总体上必然会上升，因为不仅要补偿禁止获得关于某种风险的知识所带来的不确定性，还要补偿来自那些声称遭到歧视的投保者日益增多的诉讼所带来的成本，不论这些诉讼是否属实。这种政治思维并不是美国所特有的。法国禁止向不同性别的人收取不同的保险费，并且欧盟其他成员国也在尽力推广这项禁令。在自由市场上，保险费或养老金费用能够反映男性更易发生交通事故，而女性寿命更长这一事实。因此男性为汽车保险和一般寿险支付的费用更高，而女性为了拿到和男性相同的养老金收入必须支付更多的养老金费用，因为支付给女性的养老金年限更长。

与真正的保险不同，联邦紧急事务管理署和国家洪水保险计划这类保险项目并不会降低总体风险。人们常常会在飓风和洪水高发的地方重建家园和企业，而且媒体还常常对他们的这种“勇气”大肆赞扬。但是，由此引发的经济风险并不像保险那样由造成风险的人承担，而是由纳税人承担。这就意味着，政府的介入使得住在高风险地区的人所要承担的代价降低，而整个社会要承担的成本却增加了；当人们必须自己承担住在高风险地区的成本时，他们将面临高昂保险费、财产损失和时时刻刻的担忧。

古谚说：“时间就是金钱。”这句话不仅正确，而且含义深刻。它意味着，谁有能力拖延，谁就能够把成本强加给其他人，而且有时候是极其巨大的成本。

全世界的人都喜欢抱怨政府官僚效率低下，这不仅是因为官僚不论效率高低都能领取相同数额的薪水，而且还因为许多国家的腐败官僚能够在收受贿赂后加快办事速度，并用这样的方式来增加自己的收入。政府权力范围越大，繁文缛节越多，因延误而强加的成本就越大，可以敲诈的贿赂也就越多。

在腐败不太严重的国家，贿赂的形式可能包括为了政治目的强制他人做某事，比如强制建筑商建造第三方想要的建筑，或为了迎合当地房东和环境保护运动更愿意保持现状的意愿而禁止建筑商在当地建造楼房。相比建筑商因强制要求准备一份环境评估报告而延误建设进程所增加的成本，提供环境评估报告的直接成本相当低廉。因为延误所增加的成本，是数百万美元贷款的巨额利息，贷款也会因为这一耗时的过程拖累而闲置。即使报告最终认定建造过程不会造成任何环境危害，报告本身却引起了相当大的经济损失，有时这些损失足以令建筑商放弃建设计划。这种做法导致的结果是，考虑到监管机构用强权随意施加的强大不确定性，以及由此带来的不可预测，其他建筑商可能会远离这一领域。

当城市交通系统变得很糟糕，人们就会迁离城市，进而导致税收流失。此时，已经离公交票价的政治争议过去许多年了，很少会有人记起这场争议或明白它与当前问题之间的关系。与此同时，那些因扮演维护公交乘客利益的角色而深受欢迎，并在市政选举中获胜的政治家，现在也已晋升到州政府甚至国家政府中了。随着税基的下降，城市服务恶化，基础设施被忽略，昔日公交乘客心中的英雄人物甚至会自诩说他们担任市政官员时情况要好得多，并将当前的问题归罪于继任者的无能。

在其他情况下，市场经济使得精确的知识能够有效地影响决策制定，即使99%的人并不具备这样的知识。然而在政治上，无知的99%的人却能够立刻使民选官员和那些最终危害整个社会的政策在政治上获胜。期望公众都成为金融或其他方面的专家显然是不理智的，因为一天只有24小时，而且人们还要生活。更理智的做法是，让更多选民认识到通过政治过程制定经济决策的危险性。

“铁锈地带”并非仅仅指失去工作岗位的地区。即使是在高度繁荣的地区，工作也一直在消失。区别在于，商业发达地区一直有新的工作取代原有的工作。但是“铁锈地带”或因高税收、政府和工会的繁文缛节等损害效率而导致企业无利可图的地区，几乎不会有足够多的新工作来代替原有的工作，而原有的工作随着时间推移以及经济环境的正常变迁将逐步消失。然而，政治家和媒体工作人员可能只注意到原来的工作已经消失，却未曾注意到没有出现替代的新工作，这些新的工作没有留在那些仇视经济活动的“铁锈地带”，而是转移到了其他的地方。

有些第三世界国家的政府试图没收土地重新分配给贫穷的农民，而重新分配土地的政治运动与实际转让土地之间可能相隔多年。在这些年里，现有土地所有者对未来的预期会导致他们放松对土地的维护，并放弃获得长期受益，因为这些长期收益需要投入时间和金钱除草、灌溉、筑栅栏和其他土地看护工作来获得。当土地真正到穷人手上时，土地状况可能变得非常差。正如一位发展经济学家曾提出的，土地改革有可能是“无力承受者的一个糟糕的玩笑”。

** 第五部分 国民经济

为总产出会超过实际总收入这一观点披上合理外衣的，是产出和收入都会随时间而波动，而且有时候波动非常剧烈，比如在20世纪30年代。在某些时候，出于某种原因，消费者或企业或两者都可能不愿意花费他们的收入。由于每个人的收入都取决于别人的消费，这种迟疑就会降低总的货币收入，以及与之相关的总货币需求。如果各项政府政策带来不确定性和担忧，也会让个人和企业不愿意花钱，直到他们看清楚结果会如何。

当数百万人同时采取这样的行动，就会让事情恶化，因为总需求将在总收入和总产出以下。如果人们不再尽其所能地消费和投资，经济就不能继续全力生产，因而产量削减和失业就会随之而来，直到这一问题得到自我调整。这种情况是如何发生的？自我调整需要多长时间？什么政策最有利于解决问题？对于这些问题，不同学派的经济学家并没有达成一致。然而，经济学家普遍同意，这种情况区别于有些人担忧的单纯由于人们缺少购买所有物品的收入而供过于求的情况。人们所缺少的只是将他们的收入进行消费和投资的意愿。

一年中的国民产出可以用多种方式来衡量。目前最常用的衡量指标是国内生产总值（GrossDomesticProduct，简称GDP），它指一国国境内生产的所有产品和劳务的总和。一个历史更悠久的相关指标是国民生产总值（GrossNationalProduct，简称GNP），它指一国国民生产的所有产品或劳务的总和，不论这些国民及他们拥有的资源处于哪个国家。这两种衡量国民产出的指标非常相近，若不是经济学家，根本不必在意其中的差别。比如说美国的国内生产总值与国民生产总值之间的差异还不到1%。

正如国民收入并不是指货币或其他票据资产一样，国民财富也不是由这些纸制品构成的，它由货币能够购买到的商品和劳务构成。否则，任何国家只要印更多的货币就能立刻变得富有了。有时候，国民产出或国民财富是由当时的货币价格加总而成的，但是大多数严谨的长期研究使用实际值来衡量产出和财富，把不同时间的价格考虑在内。对产出或财富的衡量必然是一个不准确的过程，因为不同物品的价格会随着时间的变化而变化。

从只有富人购买的稀有奢侈品转变为大多数消费者都能消费的普通物品，无数其他的商品也经历了这种一般模式，因为只有变成常用商品，才能被纳入决定居民消费价格指数的商品和劳务组合中，而它们的价格决定了居民消费价格指数。

如果能够从国民统计中移除所有额外的轮椅、心脏起搏器、养老院以及从巨力多到伟哥的药品，那么国家间的实际收入对比将能够更精确地反映经济福利的实际水平，因为国家为老年人口提供的这些东西，年轻人从自然中已经免费获得。毕竟，坐着轮椅的老年人很愿意与不需要轮椅的年轻人换位，因此不能依据轮椅的价值，就说这个老年人相较年轻人具有更多的经济优势，而国家间的统计数据比较会表现出这种优势。

在一些国家，尤其是第三世界国家，很多的经济活动发生在“表外”，可以说国民产出的官方数据漏掉了许多该经济体生产的商品与劳务。世界各国，家庭内部不需支付薪资的劳务，如做饭、抚养孩子、打扫房间，是不会计入国民产出的。如果每个时期没有计入国民产出的经济活动占比相同，那么这种误差就不会随时间直接影响趋势。但实际上，随着时间的推移，许多国家的家内经济活动都经历了重大变化，并且在特定时期，不同社会中的家内经济活动也存在很大差异。

位于太平洋的雅蒲岛是密克罗尼西亚的一部分，岛上使用环形的石头来行使货币职能。这些石头中最大的直径有12英尺，很显然它们不可能真正地进行流通，流通的只是这些石头的所有权。从这方面来看，这一原始的货币体系的运转跟今天最先进的机制很相像，货币所有权可以通过电子转账迅速地发生转移而无须货币发生真正地转移。所有这些不同的东西之所以能够成为货币，缘于人们接受其作为付款方式，用来购买包含真正财富的产品和服务。对个人来说，货币等同于财富只是因为其他人会为了得到货币而提供真正的产品与服务。但对于国民经济整体来讲，货币并不等于财富。它只是一件用来转移财富或激励人们创造财富的人造物。虽然货币只是促进了真实财富的创造，就像油脂给车轮润滑一样，但并不能说它的作用无关紧要。油脂润滑之后的车轮行进更顺利。当金融体系因为这样或那样的原因崩溃，人们不得不回到物物交换时，很快就会发现其中的不便。

一般来说，每个人都想得到货币，但在某些特殊的国家或特殊的时期，却没有人想要货币，因为人们认为货币没有价值。事实上，人们不会接受毫无价值的货币。当货币买不到任何东西，它就成了废纸或没用的小金属圆片。18世纪90年代，绝望的法国政府颁布了一项法律，对不使用货币交易的人处以死刑。这都意味着政府发行货币并不代表人们就会自动接受，而政府发行的货币也不一定会真正执行货币的职能。因此，我们需要知道货币是如何行使其职能的，以避免其功能失常。而货币功能失常带来的最严重的两个问题就是通货膨胀与通货紧缩。

通货膨胀不仅是一种隐性税收，而且还是一种大范围税收。政府可以宣布不提高税收或只对“富人”（然而这需要界定）提高税收，但是通过制造通货膨胀，政府实际上能够从所有货币持有者那里拿走一部分财富；也就是说，它从各个阶层吸走财富，从最富有的人到最贫穷的人。富人会将一部分钱投资股票、房地产或其他随通货膨胀升值的有形资产，于是能够轻松免于这种事实上的税收，而低收入群体却无法幸免。

商品数量保持不变的时候，货币供应量增加一倍，物价水平可能增加不止一倍，因为当人们对保持货币价值失去信心，货币的流通速度就会加快。1998年俄罗斯卢布急剧贬值期间，一位莫斯科的记者曾报道：“许多人赶在货币还有一些价值时尽可能快地花掉缩水的俄罗斯卢布。”俄罗斯在第一次世界大战期间和1917年革命之后的数年间也发生过非常类似的情况。到1921年，俄罗斯政府发行的货币量与1913年战争前夕流通的货币量相比，增加了数百倍，物价水平与1913年相比上涨了数千倍。货币流通速度加快对物价的影响，相当于流通中的货币增加。当货币增加和货币流通速度加快同时大范围地发生，就会引起恶性通货膨胀。1991年，苏联的最后一年，也是暗涛汹涌的一年，俄罗斯卢布的价值低到人们用它来作墙纸和厕纸，而墙纸和厕纸则供不应求。

20世纪最著名的一次通货膨胀发生在20世纪20年代的德国。1920年6月，40马克相当于1美元，但到了1923年11月，4万亿马克才值1美元。人们发现他们毕生的储蓄还不够买一包香烟。事实上，德国政府仅靠1,700多台印刷机夜以继日地开工印刷货币，就几乎夺走了人们拥有的每一件东西。有些人指责这一时期的经济混乱和急剧崩溃为希特勒和纳粹的登台铺平了道路。就在德国恶性通货膨胀期间，希特勒生动地将德国人描述为“饥饿的亿万富翁”，因为那些拥有10亿马克的德国人却买不起足够的食物来养活自己。

为了在货币进一步丧失价值之前购买商品，人们会比以往更快地花掉贬值的货币，这就让通货膨胀雪上加霜；同样，人们持有货币的时间更长也会让通货紧缩进一步恶化，特别是在经济萧条时期，大范围的失业导致人们的工作或生意得不到保障。1929年到1932年的经济低迷时期，不仅流通中的货币减少了，而且货币流通速度也减慢了，这就进一步减少了对产品和服务的需求，进而减少了对生产产品和服务的劳动者的需求，从而引起大规模的失业。

威尔逊总统解释说，联邦储备系统“在需要时增加货币供应，在不需要时缩减货币供应”，而且“指挥这一信用系统的权力要交给一个由公正的官员组成的政府公开委员会手中”，以避免被银行家或其他特殊利益人控制。不论这听起来多么合理，理论上政府能够做的事情并不一定等同于政治上会执行的事情，或政府领导人能够深刻理解的事情。此外，政府官员在制定决策时不涉及个人经济利益，并不意味着从政治利益来说他们在制定决策时就是“大公无私的”。即使美国联邦储备官员没有受到经济和政治利益的影响，也不意味着他们的决策就必定正确，而且与那些决策受到市场矫正的人不同，政府决策制定者不需要面对这一自动矫正机制。回顾20世纪30年代的大萧条，不管是保守派经济学家，还是自由主义经济学家，都认为当时美国联邦储备系统制定的货币政策混乱且适得其反。米尔顿·弗里德曼称那些年执掌美国联邦储备系统的人是“笨拙”之人，而约翰·肯尼斯·加尔布雷斯则称他们“惊人得无能”。例如，美联储在1931年时提高了利率，结果使经济衰退接近谷底，全美国数千家企业破产、银行倒闭，并随之引起大量失业。

显然，不是经济学家也能明白胡佛和罗斯福两位总统未能明白的道理。专栏作家沃尔特·李普曼在1934年的一篇文章中写道：“大萧条中，人们不能按照大萧条前的价格出售商品或服务。如果坚持如此，商品就卖不出去。如果人们坚持要大萧条前的工资水平，他们就会失去工作。”数百万人失业——许多人处于绝望的经济环境中——并不是因为他们想要得到大萧条前的工资率，而是由于政府试图维持大萧条前的工资率。

虽然货币本身不是财富，但从社会整体来看，它在促进生产和财富转移方面具有非常重要的作用。人们有权从国民产出中获得的真正财富，也就是有形的东西，可以通过银行和其他金融机构，利用货币作为转移工具，重新进入其他生产领域。因此，如果消费者愿意花钱购买家具，木材就会被用来制造家具，但是当这些消费者更愿意把钱存入银行而不是消费，并且银行把这些钱贷给杂志出版商的时候，木材就会转而用来制造印刷杂志的纸张。

这样，现代银行就具有了两个主要的特点：一是只需持有一部分必要的储备金来支付存款；二是增加总的货币供应量。存款人不会同时取走所有的钱，因此银行可以把大部分钱借给其他人，用这些贷款赚取利息。银行通过给存款账户支付利息，将其中一部分贷款利息与存款人分享。另外，存款人也会用自己的账户开出支票，于是存款账户中的一部分资金也会因此进入流通，所以银行系统实际上为国家货币供应贡献的增长数量，远远超过政府的货币发行量。而一部分银行信贷又可以存入其他银行，随之产生新一轮的货币供应，因此经济中的银行存款总额往往要超过政府发行的现金总额。

评价美国联邦储备系统和政府其他部门的作用，必须明确区分它们声称的目标与它们的实际成果或影响。1914年建立美国联邦储备系统是出于对通货紧缩和银行破产的恐惧。然而，美国历史上最严重的通货紧缩和最严重的银行破产却是在美国联邦储备系统建立之后出现的。1907年的金融危机促成了美国联邦储备系统的建立，但它与1929年因股票市场崩溃而引发的金融危机和20世纪30年代的经济大萧条相比，就可谓小巫见大巫了。

中国的储蓄率甚至比印度更高，国有银行吸纳了90%的储蓄，并以低利率借给国有企业，实际上是对那些资本回报率较低甚至处在亏损状态的国有企业的补贴。总之，中国大部分的储蓄都由银行分配给了国有企业，而不是分配给效率更优、效益更好的企业，因为这些企业多在私营部门或具有外资性质。印度和中国的情况显然并不利于有效配置具有多种用途的稀缺资源，但是它们都非常适合政府官员进行管理。如果私有银行可以在这些国家自由运营，那么它们会把钱贷给或投资到投资收益率最高的地方，也就是那些最成功的公司和产业。这样，私有银行也就能够支付更高的利率给存款人，进而将利率较低的国有银行的存款吸收过来。给存款人支付更高的利率，最终结果往往会提高储蓄率，以及更有效地将这些存款配置给更成功的企业，从而提高整体经济的增长率。但是，它也会让政府官员更感头痛，他们必须努力防止国有银行和国有企业破产。尽管经济学家可能会说，为了经济发展，这些低效率的企业应该被淘汰出局，但是政府工作人员却不太可能愿意为了他人的利益而损害自己的职业。

如今，高犯罪率的地区以及恶意破坏行为或骚乱高发地区，也同样由于缺乏法律与秩序而在经济上备受折磨。很多企业根本不会在那里落户；而建在那里的企业，与建在其他地方的企业相比，效率更低或更不合人意，并且在其他地方，这些不合格的企业将无法从竞争中胜出。商店内外增加的额外安全设备，以及雇用保安的成本都增加了营业成本，反映在价格上就是高犯罪率地区的居民购买产品和服务的价格更高，尽管在这些地区居住的大多数人都不是罪犯，而且也难以承受由犯罪者带来的额外成本。

当法律和政策抬高了诚实的成本，政府实际上就是在鼓励不诚实行为。这种不诚实行为很快就会超越所涉及的特定法律和政策，使人们普遍地养成不遵守法律的习惯，从而对整个经济和社会产生不利影响。正如一位俄罗斯母亲所说：如今，我的孩子抱怨我用错了抚养方式。现在已经没有人需要诚实与公平了。诚实的人会被当作傻瓜。不论在哪个国家，当这种习惯普遍蔓延，将是经济和社会的共同灾难。

还有一些利益是不可分割的。要么每个人都获得这种利益，要么就没人能获得。国防就是其中一个例子。如果个人必须在市场上购买国防，那么感受到外国势力威胁的人就会为枪支、军队、大炮和其他军事威慑和防御手段付费；而看不到这些危险的人就会拒绝为这些物品付费。但是，对于这两种人而言，军事安全水平是相同的，因为军队的支持者和反对者杂居在同一个社会里，敌人的行动带来的危险也是相同的。鉴于这种利益的不可分割性，即使是完全意识到军事威胁的人，以及那些认为国防收益大于成本的人，可能也会感到没有必要为此花费自己的钱，因为他们个人的贡献并不会对他们自己的安全（它主要取决于其他人贡献了多少）产生重大影响。在这种情况下，最终很可能会没有足够的国防，即使每个人都了解有效防御的成本，并认为收益要大于成本。通过将国防决定集体化，并让政府做出决策，最终将更接近大多数人想要的结果，这是让单个个人分别做出决定无法达到的。即使是自由市场的倡导者，也很少有人建议让个人在市场上购买国防。总之，有些事情政府能够比个人更有效率，因为外部成本、外部收益或不可分割性使得市场上基于个人利益的个人决策，不能很有效地衡量整个社会的成本和收益。

或者我们可以说，政治的时间跨度总是要短于经济的时间跨度。在工资和价格管制政策的负面经济后果完全显现出来之前，尼克松已经以压倒多数的得票率再次当选。没有现值因素，来迫使政治决策制定者在当前的决策中考虑长期后果。教育是因政治短视而被忽视的重要领域之一。正如一位印度作家所说：“没有人关心教育，因为要在教育领域取得成果需要很长的时间。”这种情况并不是印度特有的。从根本上改革教育，困难重重又耗时弥久，改革的结果也要等接受更好教育的人成年之后才会显现，因此在政治上，民选官员的权宜之计是将纳税人的钱更多地投向教育，以展示他们对教育的迫切“关心”，尽管这样只会增加漂亮的建筑物，对教育毫无益处。

危机创造了权力，但是权力不会随危机的终止而终止。立法者也并没有太大的兴趣废除过时的陈旧法律。当促使某些机构成立的环境消退时，这些机构更是不可能自行关闭。

除了特定的政府政策或计划的某些优点或不足，在扩大政府作用时还应进行其他方面的考虑。约翰·斯图亚特·穆勒早在一个多世纪前就对此有所表述：在政府现有职能之外增加的每一项功能，它对人们希望和恐惧心理的影响都会得到更广泛地扩展，并且越来越多地使活跃而富于进取的那部分公众变成政府的依存者，或者变成旨在组成政府的某一党派的依存者。假如公路、铁路、银行、保险机关、巨大的股份公司、大学以及各种公共慈善机构等，都变成政府的分支机构；假如市政公会和地方议事会以及现在委任给它们的一切，也都变成中央行政系统下的部门；又假如所有这些不同企业的雇员都由政府任命并支付薪金，指望政府来赐予它们生活上的提升；那么，即使宪法规定有新闻自由和民众参与立法的自由，也不足以使这个国家或任何国家成为一个名副其实的自由之国。

政治和媒体上经常提到政府“增税”或“减税”，这些名词模糊了税率和税收收入之间的本质区别，政府能够改变税率，但是公众对此的反应也许能够带来税收收入增加，也可能带来税收收入的减少，到底是增加还是减少则取决于环境和反应。“5,000亿美元减税”或“7,000亿美元增税”的提案是彻头彻尾的误导，因为政府所能做的只有改变税率，只有等税率变动产生实际影响，纳税人做出相应调整之后，政府对税收收入的实际影响才能确定。

失业补偿金与农业补贴只是所有“政府津贴”项目中的两个。只要补贴这些项目有相关的法律支持，它们的支出就不为任何行政管理部门所控制。只有将已实施的既定法律废止，才能终止该项支出，然而这样做就意味着，要冒犯所有从这些法律中获益的人，他们的数量要比起初支持该法律通过的人数多得多。总之，人们往往将政府支出及其造成的年度赤字与不断膨胀的国债总量归咎于执政的官员，但是大部分这类支出并不由他们的决断，而是来自已有的法律规定。比如，美国2008年年度财政预算在医疗保险、医疗补助计划和社会保险上的非自主性支出比军费预算还要多，而此时美国正处于战争状态。

政府支出带来的另一个严重误导是，“再开发项目”或“开敞空间”政策下的土地购置成本。地方政府官员用征用权拆毁现有住房和企业，“重建”某特定社区，只要政府官员公开讨论这样的愿景，就足以让想要购买该社区房屋或企业的潜在买家产生负面情绪，于是这些房屋和企业的现值在政府采取具体行动前就会开始下降。到政府采取行动时（通常可能在数年后），这个受影响的社区的资产价值很可能已经远低于政府公开讨论重新开发计划之前的价值了。因此，即使按照法律要求支付给房产所有者“公平补偿价”，他们得到的也只是房产贬值后的价值，而不是政府官员开始讨论重建该社区以前的价值。因此，政府的补偿开支可能远低于社会失去这些资源造成的实际成本。

对民选官员而言，最高优先级是再次当选，这就需要源源不断的有利宣传，使该官员的名字能够经常出现在公众眼前。例如，任何重大设施开张——不论是否必要——都可以吸引媒体来报道剪彩仪式，从而为这些官员创造政治机遇。而修整路面、修护桥梁或更新污水处理厂的设备，却不会为他们带来剪彩或演讲的机会。政府支出模式源于这种激励和约束并不新鲜，也不仅仅存在于某些国家。亚当·斯密针对18世纪法国的情形，提出了一个类似的模式：浮华的朝廷中那些好慕虚荣的官员，往往非常愿意从事壮丽辉煌的工作，如修一条大公路，这种项目常常会受到重要贵族的关注。这些贵族的赞赏，不仅能激起他们的虚荣心，而且还能提高他们在朝廷中的地位。但是，许多琐碎的工作既无法引人注目，也几乎不能引起别人的钦佩，总之不能让他们感受到自己的巨大效用，从各方面来看，都太卑微而不能引起长官的重视。

不论是美国国会预算办公室还是其他任何人，都无法精准预测某种税率的提高或降低会带来怎样的结果。而无法预测的不仅仅是准确的收入数量，收入会向哪个方向变动也无法事先得出。结果都靠有根据的猜测，或者更糟，只是机械地估计人们的行为不会因为税收变化而变动时收入是多少。但是，人们的行为变化得太快，也太剧烈，根本无法根据这样的假设来做出正确的预测。早在1933年，约翰·梅纳德·凯恩斯就观察到，“税负太高将无法实现目标”，而且“若有足够的时间来收获成果，降低税率，而不是提高税率，更有利于平衡预算”。预算并不是记录已经发生了什么，而是预测未来将会发生什么，这取决于所做的假设以及由谁来做假设。虽然国会预算办公室会预测未来的成本和支出，但他们得出这些预测所依据的假设来自国会。如果国会不切实际地假设经济增速很高，因此税收收入也会很多，国会预算办公室就会根据国会的假设，计划未来预算赤字或盈余，而不管国会的假设在现实中能否实现。媒体或公众可能会以为国会预算办公室的预测出自一群中立的经济学家和统计学家，但决定最终结果的是由政客提供的假设。

经济决策不仅影响经济，它们还影响政府权力的范围，以及政府财政债务的扩张——包括但不限于国债。人们有时也会对政府性质产生一些误解，于是向政府提出不切实际的要求，当这些要求无法得到满足时，就立刻谴责政府官员“愚蠢”和“非理性”。要理解国民经济中的诸多问题，既需要了解经济过程，还要洞察政治程序。

公众为表达他们的意愿，可以在投票站做出选择，也可以通过市场做出选择。然而，政治选择并不常有，并且受选举时点的限制。此外，政治程序提供的是“一揽子交易”的选择，在与另一个候选人比较后，候选人的总体观点，包括经济、军事、环境和其他问题上的立场，必然作为一个整体被接受或拒绝。选民可能在一些问题上偏爱其中一位候选人的立场，而在另一些问题上偏爱另一位候选人的立场，但是在投票时却没有这样的选择。

大部分政府，尤其是民选政府，都承受着一种压力，就是要“有所作为”，即使它们无法改善现状，甚至只能使状况恶化。经济过程与其他过程一样，也需要时间，但政治家可能不愿给经济过程留出运行必需的时间，尤其是政治对手正在倡导迅速的解决办法时，比如尼克松执政时期的工资和价格管制，或20世纪30年代大萧条时期的国际贸易限制政策。在大萧条以前的150多年间美国政府对经济自由放任。21世纪，美国政府不可能在政治上任由经济衰退自然发展，大萧条期间共和党的赫伯特·胡佛总统和民主党的罗斯福总统，都以史无前例的力度干预经济。现在，人们普遍认为在经济下行时政府必须“做些什么”是不证自明的公理。很少有人会将政府干预的结果与政府没有干预的效果进行比较。

要理解政治激励与经济激励之间的区别，可以观察政府提供的养老金与保险公司提供的年金之间的差别。通过将政府保障计划称为“社会保险”，它们可以和保险公司的活动进行类比，但实际上，这些计划并不具有与私营保险公司一样的激励、法律责任和结果。私人年金与政府养老金之间最根本的区别，是前者通过投资保费创造实际财富，而后者并没有创造实际财富，仅仅是用来自当前劳动人口的保费来支付当前退休人员的养老金。

虽然我们在谈论“政府”时，就好像它是一个统一的整体，但事实上，任何时候政府都被不同且对立的利益所分割，而且不同时期的政府领导层是由完全不同的人组成的。因此，终止成本高昂的协和式飞机项目的，并不是最初发起这一项目的人。承认别人的错误总是容易得多，并且还能为此受到赞扬。相反，在竞争市场中，错误的代价会不断攀升，因此除了承认自己的错误并在破产之前迅速纠正，别无他法。市场上的清算总是比政治上的来得更早，私营部门中不仅有更大的压力促使人们承认错误，也有更大的压力促使人们避免在起步阶段就犯错。在不同部门中提议新的风险投资项目时，政府官员的提议只需要在对他们来说重要的时间跨度内（往往是在下次选举前），说服足够多的民众就能成行。在竞争市场上，这些提议必须令那些以自己的钱财承担风险的人信服，这些投资者有充分的动机去获得相应的专业知识，在实施之前评估该项目的未来。

** 第六部分 国际经济

正如20世纪30年代大萧条期间，美国每年都是贸易“顺差”一样，20世纪90年代经济繁荣发展期间，美国破纪录地成为“债务国”。显然，这些语句不能以其字面意思作为一个国家经济福利的指标。

21世纪初，全世界一半以上的咖啡只在三个国家种植——巴西、越南、哥伦比亚。但这并不意味着其他国家就完全没有能力种植咖啡。只是大多数国家能够生产的咖啡数量和质量并不值得去投入成本，因为从以上三个国家完全能够以更低的成本进口咖啡。

印度玩具产业的噩梦来自于一种小型塑料玩具。这种玩具由中国制造，能够播放流行的印度电影歌曲，售价只需要大约100印度卢比（2美元）。印度的家长们在全印度的市场上抢购它，本地的玩具公司惊呆了。要想跟上这些玩具的生产速度、规模和技术（正是这三个因素使得这些玩具能够以极低的价格出售），印度公司远没有这样的能力……在玩具生产、鞋子制造等行业中，中国已经发展出巨大的规模经济，而印度却人为地限制了生产商的规模。

有时，确实有些行业会受进口产品竞争的不利影响，就像它们也会受到其他更好、更便宜的产品的不利影响一样，不管这些竞争产品来自国内还是国外。市场上总是会有其他效率更高的产品，迫使公司走向现代化、削减规模，不然就倒闭。然而，当这种情况是因为外国人而发生时，政治上就会把它描述成我们国家与其他国家的对立，实际上，它一直都是国内特殊利益集团与消费者的对立。

经济学家很早就认同的一种关于国际贸易限制的观点（至少在理论上），就是认为需要暂时保护“幼稚产业”，直到它们具备必要的技术和经验，能够与国外老牌的竞争者相抗衡。一旦它们具备了技术和经验，就可以取消这种保护（不管是关税、进口配额，还是其他措施），让这个产业在市场竞争中自生自灭。然而，在现实中，一个新生产业在幼稚时期很少具备足够的政治力量——雇员选票、雇主对政治活动的资助以及政府对他们税收的依赖性——来保护它们免受国外竞争。另一方面，陈旧、低效率但曾经辉煌过的产业，却可能会有一些政治力量，能够得到立法的保护或政府津贴，以使自己免于淘汰，但这样做却牺牲了消费者、纳税人共同的利益。

除了各种投资，居住在国外的人也会汇款给原籍国的家庭成员。2012年，全世界2.5亿移民汇回了4,100亿美元。2011年，墨西哥的一项调查发现，该国1.12亿人口中，有1/5的人从居住在美国的家庭成员那里收到总量接近230亿美元的汇款。这既不是新现象，也不只出现在墨西哥。2011年，印度移民向印度国内寄回了640亿美元，而世界各地的中国移民，则向中国寄回了620亿美元。大笔钱被寄回贫穷的祖国，也随之产生了重大的经济影响。

从国外寄回黎巴嫩的钱，相当于该国国内生产总值的22%。给摩尔多瓦的侨汇占该国国内生产总值的23%，这一比例在塔吉克斯坦是35%。长期以来，对于贫穷国家的穷人来说，国际汇款一直起着极其重要的作用。早在19世纪40年代，美国的爱尔兰移民汇回给他们在爱尔兰的家庭成员的汇款，不仅使许多家庭成员度过了饥荒，还帮助许多人移民到了美国。

出现这样的情况是有原因的，正如为什么一些国家富裕而另一些国家贫穷有其根源一样。不论是向哪个国家投资，最大的风险是不能收回投资。投资者对不稳定的政府很警惕，因为政府人员或政策的改变可能会改变投资决策所依据的条件，最坏的后果是被政府没收，即政治上所谓的“国有化”。普遍腐败是阻碍投资的另一个因素，正如它会阻碍普遍的经济活动一样。在国际腐败指数中排名较高的国家，如尼日利亚或俄罗斯，能够吸引的国际投资规模无法与它们拥有的自然资源或其他经济潜力相匹配。相反，腐败指数较低的国家都是富裕国家，大部分是欧洲国家，以及欧洲分支国家，再加上日本和新加坡。正如第18章指出的，一个国家的诚信程度具有重要的经济影响。据《经济学人》报道，除了没收和腐败外，许多贫穷国家还“不允许资本自由进出”。资本无法轻易撤出的地方，一开始就不容易进入。当中国香港还是英国殖民地的时候，最初也非常贫穷，后来却发展成为一个工业发达的地区，并且曾一度拥有很大份额的国际贸易量，甚至超过印度这样的大经济体。它拥有低税率，允许资本最自由地流动，与世界各地进行广泛的贸易，因此资本的大量流入带动了香港经济的发展。

关键是，国际贸易赤字和盈余都不是繁荣或贫穷的必然结果，另外，语句本身也无法说明某个国家的经济状况。“债务”这个词包含了各种各样的情况，其中一些在实际中可能会带来问题，另一些则不尽然。每当你将100美元存入一家银行，这家银行就多了100美元的债务，因为这笔钱是你的，而他们欠你这笔钱。如果得知保管其毕生积蓄的银行债务每月都在不断增长，人们就会变得很恐慌。但是，如果银行债务的增加，只是由于其他人也将他们的收入存入这家银行，那么这种恐慌是完全不必要的。如果你只是为了购买物品而负债，那么这笔钱就是你要偿还的债务。并且，如果债务超出了你的偿还能力，那你就陷入了大麻烦。然而，将数百万美元存入一家银行，并不会给银行带来麻烦，虽然这意味着该银行的负债又多了数百万美元。相反，银行主管很可能会为得到数百万美元而高兴，因为他们可以发放更多的贷款，赚取更多的利息了。

曾几何时，生活在马来西亚、印度尼西亚和其他东南亚国家的海外华人，因向中国的家人汇款而闻名。这些国家的政治家和媒体常常宣称，这些汇款让中国获利，使汇出国变得贫穷。实际上，中国人在这些东南亚国家建立了许多企业，有时甚至建立了整个行业。他们汇回中国的资金，只是他们给现在所生活的这个国家创造和增加的财富的一小部分。同样的指控也指向了西非的黎巴嫩人，东非的印度人、巴基斯坦人，以及世界各地的其他民族。在这些例子中，最根本的谬误是忽视了这些人所创造的财富，他们移居的那个国家由于他们的存在而增加了财富而不是减少了财富。有时候对这些民族的敌对行为导致他们离开这些国家，或是遭到驱逐，随之而来的往往是这些国家的经济下滑。

然而，仅仅根据移民积极的贡献来评价它的经济影响将产生误解。移民也会带来疾病、犯罪、内乱以及恐怖主义。我们也不能将所有移民混为一谈。在美国的日本移民，只有2%的人靠领取政府福利救济金生活；而来自老挝的移民，却有46%都靠政府救济，并没有一种单一的模式适用于所有移民。同样，来自不同国家的移民给美国或世界其他国家带来的犯罪率水平以及其他积极或消极影响也具有很大差异。俄罗斯和尼日利亚常被排在世界上最腐败的国家之列，俄罗斯和尼日利亚移民带来的犯罪活动在美国也是臭名昭著。

金本位终结后，各国为国家间的货币稳定做出了各种努力。例如，一些国家将货币等同于一定数量的美元。欧洲国家也联合起来，创造了他们自己的国际货币——欧元，而日元也成为另一种在国际金融交易中被广泛接受的稳定货币。然而，南美洲各国却走向了另一个极端，它们的货币价值经历了大幅波动，年度通货膨胀率有时达到两位数甚至三位数。这些货币波动会影响产出、就业等实实在在的事情，当货币的价值面临诸多不确定时，计划和投资就很难进行，即使这些投资本来应该获得成功。阿根廷和巴西的经济问题尤其瞩目，这两个国家都拥有丰富的自然资源，并且都没有受到20世纪席卷其他大洲的战争破坏。随着货币电子转账业务的发展，任何国家的货币可靠性发生变化几乎都会引起即时反应。任何想要制造通货膨胀的政府，都明白资金能够瞬间逃离。这样的货币体系所施行的规则与金本位下的规则完全不同，但是，只有国际货币体系在未来的经济压力中接受了现实的考验，我们才能知道它是否同样有效。

“强”货币并不意味着使用该货币的经济体就一定会从中获得利益。有时它意味着相反的情况。使用“强”货币的国家，出口价格在其他国家的人看来是上升了。因此，一些欧洲公司抱怨欧元在2003年的升值使它们对美国的出口下降了，因为按美元计算的产品价格上涨了，于是购买其产品的美国人变少了。同样，英镑变“弱”，则产生了相反的效果。据《商业周刊》杂志报道：处于困境中的英国企业，喜欢英镑贬值。因此，在过去的一年中英镑对欧元的汇率下降了11%，企业都对此表示了热烈欢迎……随着英镑对欧元转弱，英国商品在欧洲大陆的竞争力变强了，而欧洲大陆是它们最大的出口市场。而且当来自欧元区的收益被转换成英镑时，公司的利润又增加了。

让我们从最基本的因素谈起，土地的肥沃程度在各个地方是不同的。被科学家们称之为黑土的肥沃土壤，在全球的分布极不均衡。这类肥沃的土壤广泛聚集在美国中西部平原地区，延伸到加拿大境内；而大片肥沃的土壤也贯穿整个欧亚大陆，从东欧南部一直到中国东北。在南美洲的温带，阿根廷南部、巴西南部和乌拉圭，也有一小部分这类土壤。虽然在北半球和南半球的大部分温带地区都存在这些土壤，但是热带地区则鲜有其身影。撒哈拉沙漠以南的非洲地区，土壤有很多很严重的缺陷，因此该地区作物产量只是中国或美国的几十分之一。在非洲的许多地方，表层土壤很浅，植物的根部没有足够的空间获取养分和水。而非洲大部分地区的干旱也抑制了化肥的使用，无法为土壤补充缺少的营养，因为在没有足够水分的情况下使用化肥只会抑制作物生长。虽然非洲也有湿地，并且这类湿地在亚洲被成功用于作物种植，但是在热带非洲，很少有人在这些湿地从事种植作业，因为非洲湿地是疟疾和河盲症等疾病的温床。

地底价值巨大的自然资源——无论是铁矿、煤炭、石油，还是其他众多资源——在地球上的分布都是不均匀的。不仅是因为特定的自然资源倾向于集聚在特定的地区，例如石油之于中东，而且还因为如何提取和处理这些资源的知识在不同时期也在演变，因此一种特定的物质会在不同国家、不同历史时期，成为一种宝贵的资源。虽然中东地区几千年来一直保有大量的石油储量，但是直到科学和技术足够发达，石油成为工业国家不可缺少的物资之后，石油才成为一种宝贵的资源，并给中东国家带来了大量财富。

类似地，世界上有些地区拥有的港湾也比其他地方少。虽然非洲的面积是欧洲的两倍多，但是非洲的海岸线比欧洲海岸线短。因为欧洲的海岸线更曲折，形成了更多适合船只停靠的港湾，让船只能够躲避汹涌的海水。此外，欧洲的许多港湾是深水港，这意味着大型远洋船只可以紧邻陆地停靠，例如斯德哥尔摩或摩纳哥的港湾，而在许多撒哈拉沙漠以南的非洲地区，沿岸水深很浅，大型船只必须在近海岸下锚，并将货物卸载到较小的、可以在浅水区航行的船只上。这是一个高成本过程，人们常常因为高昂的费用而放弃使用这一办法。几个世纪以来，欧洲和亚洲之间货船，通常会绕行非洲，不做停留。

生活在山地的人，在经济和文化上都要落后于山下的同代人，这种模式普遍见于美国的阿巴拉契亚山脉、摩洛哥的里夫山脉以及希腊的品都斯山脉。过去，这种对照也曾见于锡兰殖民地高地地区的人与山下的同种族人之间，以及苏格兰高地人和苏格兰低地人之间。此外，即使双方都已经移民到澳大利亚或美国，苏格兰高地人和苏格兰低地人在经济和文化上的差距仍然存在——低地人在经济上普遍更成功，并在祖国和移居国都保持着更紧密的社会联系。几个世纪以来演化形成的文化差异，不会随着人们从一个环境迁移到另一个环境，或者周围的环境发生变化就在一夜之间消失。在现代交通运输和通信技术出现以前，山地社区往往特别孤立，缺乏与低地社区的交流，也缺乏与其他山地的交流。虽然山地社区并没有与整个外部世界隔绝，低地文化到达高地的时间往往也会延迟很久。因此，居住在希腊品都斯山脉的人，在低地人讲了几百年希腊语后，仍在说弗拉其语，而苏格兰高地人在苏格兰低地人开始讲英语后，仍在用盖尔语交流。生活在摩洛哥里夫山地区的人，在山下人成为穆斯林若干世纪之后，才将伊斯兰教作为他们的宗教。

虽然第二次世界大战的轰炸和大规模破坏性地面战斗造成了巨大物质破坏，战后西欧经济仍然快速复苏。美国按照马歇尔计划施与的援助常常被视为复苏的原因，但后来得到外国援助的许多第三世界国家却没有产生如此显著的经济增长。不同之处在于，工业化的西欧国家在战争开始之前，就已经发展出了能够建立现代工业社会的人力资本，但是第三世界国家还没有开发出相应的人力资本，没有这种人力资本，外国援助捐赠的物质资本通常并无用武之地。马歇尔计划推动了西欧向和平时期经济复苏的过渡，但是对于原本并不具有相应的人力资本的地方，外国援助无法产生必要规模的人力资本。

黎巴嫩人、犹太人和其他人身上也有类似的故事，这些人开始都是身无分文的移民，但拥有在更恶劣环境下磨炼出来的丰富人力资本。许多其他群体也跟这些移民一样，在他们国家内部创造出了相似模式：发达群体中有一类人尤为引人注目，他们的家乡贫瘠且人口过剩。斯里兰卡的泰米尔人、喀麦隆的巴米累克人、阿尔及利亚的卡拜尔柏柏尔人、肯尼亚的吉库尤人、印度尼西亚的多巴塔克人、菲律宾的伊洛卡诺人、印度喀拉拉邦的马来利亚人，以及尼日利亚的伊博人，他们都来自贫困的地区，他们的家乡无法支撑那么多人生存，于是很大一部分人都迁移到家乡之外的地方，并且在现代社会中获得了很多机会。在欧洲殖民时代，原本较贫困的原住民，如尼日利亚的伊博人和斯里兰卡的泰米尔人，接触到了西方的教育、工业、商业和行政管理，他们因此崛起，并获得相较原始精英阶层更大的成功。由此招来的怨恨，以及随之而来的政治极化效应，导致这两个国家都陷入了血腥的内战。

文化自我限制的另一种表现是，限制人口中的某些群体从事某些经济或社会活动。只有预先选定的群体——不论是以阶层、种姓、部落、种族、宗教还是性别划分——才被允许从事特定的职业，像这样根据文化划分经济角色，与根据个人的内在禀赋划分有着很大的差异。最终的结果就是，由于放弃了国家内部许多人的潜能，相较不对人民发挥天赋和潜能施以自我限制的社会，施加文化自我限制的社会只能获得较少的经济产出。历史上遍布这样的例子，很多社会通过文化规范，限定特定人口从事特定职业，有些甚至将国内最富生产力的人群驱逐出境，因为这些群体获得的繁荣，招来了其他人的不满，他们因此遭到迫害、暴力或彻底驱逐。而对于文化限制较弱的其他国家，往往由于这些难民的到来，在经济上受益匪浅，即使难民们并没有随身携带多少金钱，但他们带来了宝贵的技能和才华。

然而，关于贫穷的“人口过剩”理论仍未消失，并不时出现在媒体和政客言论中，这种情况很像各种自然资源枯竭理论。此外，这两类理论的论据也很相似。每种自然资源数量有限这是不容争辩的事实，但是却引出了不合理的推论，即认为我们正在接近这些限度。同样，地球可以养活的人口数量有限，这也是不争的事实，但同样推出了不合理的结论，即我们正在接近这种限度。

总之，从一些国家或民族到其他国家或民族的强制性财富转移，无论是通过征服还是奴役的形式，并不能产生持续的经济增长。人类遭受的巨大痛苦，只有当时的精英享受了短暂的富足，这些人生活在奢侈之中，很少或几乎不为后代的利益进行投资。有人曾评价俄国农奴制，说它只是把“大部分财富放到挥霍无度的贵族手中”，这一说法也适用于其他地方的压迫制度，这些制度很少或几乎没有为经济发展做出贡献。总的来说，我们并不能明确地指出帝国主义会对被征服民族带来经济净效益或净损失，但它显然会带来其中一种影响。虽然罗马人征服西欧国家后给被征服者的后代带来了长期利益，但是当时被罗马人征服并在他们统治下受到压迫的人，肯定不曾获得更好的生活。然而，即使如温斯顿·丘吉尔这样的英国爱国者也会指出“伦敦城的建立多亏了罗马”，因为古代英国人自己创造的东西都没法与罗马人比拟。然而，遭受了苦难和屈辱的古代英国人掀起了大规模起义，却被罗马人用残忍的屠杀手段给镇压了下来。

其他偶然事件还包括西半球土著人在面对欧洲人带来的疾病时极为脆弱，这些疾病给当地造成的人口损伤远远超过欧洲的武器。而欧洲人则不易受到西半球疾病的攻击，这两个种族之间的斗争结果本质上已经由微生物预先决定了，而当时他们都还不知道微生物的存在。⑧据说有一位慈祥友好的西班牙牧师作为传教士，来到当地土著人中，而他很可能要对土著人的众多死亡负责，这位传教士身上的病菌带来的死亡，甚至要超过最残酷的征服者的屠刀。

** 第七部分 经济学的一些问题

有一种政治言论由来已久，即努力使住房、医疗或其他物品和服务的价格保持“合理”或“可承受”。但是，说价格应该合理或承担得起，相当于说经济现实要根据我们的预算或想要支付的价格进行调整，因为我们不会根据经济现实来进行调整。然而，制造并运输我们想要的物品所需的资源数量，完全独立于我们愿意或能够支付的价格。期望合理的价格，本身就是不合理的。价格管制当然能够通过政府强制实施，但我们已经在第3章中看到了这样做的结果。我们也可以用补贴来保持低价格，但是这样做丝毫不能改变生产产品与服务的成本。它只意味着部分成本将由税收来弥补。

由于品牌如同某些知识的替代品一样，它们的价值大小，取决于你对产品或服务了解多少。很了解摄影知识的人，可以很有把握地花更少的钱购买一个杂牌照相机或镜头，甚至是一个二手照相机或镜头。但是，对于这个拥有很多摄影知识，却没有多少音响设备知识的人来说，去购买著名品牌的新音响设备会是更好的选择。许多批评品牌的人认为，那些大品牌“都差不多”。即使这是真的，品牌也仍然发挥着重要作用。问题并不在于金宝汤公司的产品是否比其他品牌好，而是如果这两种汤都以匿名方式出售或贴上通用标签，它们是否都会拥有更好的销量。如果金宝汤公司的产品仅仅被标成“汤”或“番茄汤”“蛤肉汤”“蔬菜汤”，而没有贴上商标，那么所有罐头汤生产商在保证产品安全和质量方面的压力就会变小。

即使各种品牌都要根据法律规定的相同程序来生产产品，例如阿司匹林，当每瓶阿司匹林的生产者都可以被识别时，质量要比生产者匿名时更利于控制。此外，如果阿司匹林在生产过程中被混入杂质，并导致人们生病或死亡，那么损失最大的将是最著名的企业。对于食品和药品来说，尤其重要。和其他事物一样，我们可以通过考察品牌不存在时会发生什么情况，进而更清晰地认识品牌的重要性。在没有品牌或只有政府创办或批准的唯一生产者的国家，产品或服务的质量往往更低。苏联唯一的航空公司——俄罗斯国家航空（Aeroflot），以差劲的服务、粗鲁的态度而声名狼藉。苏联解体后，一家由私人出资的新航空公司取得了巨大的成功，部分原因是消费者因受到了人性化的对待而心存感激。这家新航空公司的管理部门声称，他们不会雇用曾在俄罗斯国家航空工作过的任何人。

一家企业的资产，包括资金、机器、不动产、存货和其他有形资产，其中最大的资产可能就是它的品牌，虽然品牌是无形的。据估计，可口可乐公司的市场价值超出其有形资产价值1,000多亿美元，其中有700亿美元是来自品牌价值。对它来说，为了保持自身资产的金融价值，它有充分的理由来保持产品的质量和安全。

管理组织的人，不论他所管理的组织是追求利润，还是非营利、军事、宗教、教育或是其他类型，都倾向于以各种方式利用组织资源为自己牟利，甚至会牺牲组织宣称的目标。这种趋势能走多远受强大的外部利益的影响，而组织正是依靠外部利益才能存在，如投资者和消费者。投资者既能从投资中得到满意的回报，也能将钱投资于其他地方；而消费者既能以愿意支付的价格购买他们想要的商品和服务，也能将钱花在其他地方。对于非营利组织，这些外部利益并不具有决定性的作用。这并不意味着非营利组织的钱是无限的或者不需要担心支出超过收入。这意味着，不论非营利组织的资金如何，它们在最大限度地利用所有资源追求组织目标上压力很小。提供这些资源的人士包括广大民众，以及向非营利组织捐款的人，他们都不能严密地监视资助款项的使用情况。许多捐赠，有时甚至是绝大部分，是由那些如今已经去世的人士留下的，他们当然不能再进行监督了。

在中东，第一个基布兹成立于1910年，它是一个非营利社区，个体成员之间相互间提供物品和服务，并在平等的基础上分享产出。2007年，这个首创的基布兹经投票表决，决定放弃非营利性和平等主义，当时61%的以色列基布兹做出了同样的决定。第一个成立的基布兹之所以决定做出变革，一个重要因素是年轻人倾向于离开该组织，选择生活在市场导向的经济中。总之，即使在基布兹等非营利机构理念中成长起来的人，也通过用脚投票的方式选择参与市场经济。

虽然经济学给我们提供了许多深刻的洞见，让我们能够更容易地识破一些听起来不错但却经不起推敲的流行观念，但是经济学还被称为“沉闷的科学”（thedismalscience），因为在世界的组织方式上，它向许多看起来很有吸引力且令人兴奋，但实质却异常荒谬的观点泼了一盆冷水。当一些受人喜爱的计划或理论，被认为在经济学上是胡说八道时，它们可以利用的最后一个庇护方法就是大声宣称：“经济学是很不错，但是我们还需要考虑一些非经济价值。”想必，应该就是指那些凌驾于极端物质主义之上的，价值更大、更高尚的东西。

有关非经济价值的高谈阔论，经常可以归结为一些人不想把他们自己的价值观与其他事情进行比较。如果他们正在拯救莫诺湖，或是在保护一些历史建筑，他们就不愿权衡付出的成本——也就是说，最终也不会与同样资源可以用来做的其他事情进行权衡比较。对这样的人来说，拯救莫诺湖或保护历史建筑花费的钱，可以让多少第三世界国家的儿童接种疫苗以对抗致命性疾病，思考这样的事是毫无意义的。按照这种看待世界的方式，我们应该给这些孩子接种疫苗，并且还要拯救莫诺湖及保护历史建筑——同时还要做无数其他的事情。对于那些以这种方式思考——或是做出反应的人来说，经济学充其量也不过是阻碍人们做他们想做的事情的一种令人讨厌的东西。最糟糕的是，经济学被认为是一种过于狭隘的（如果不是道德扭曲的话）看待世界的方式。对经济学的这种谴责是出于这一基本事实，即经济学研究的是如何利用具有多种用途的稀缺资源的问题。如果没有稀缺性限制迫使我们做出不想面对的选择或是权衡，我们可能会活得更开心。在有记载的数千年历史中，没有限制的世界并不存在。

同样地，与苏格兰政府控制的供水系统相比，英格兰供水系统的私有化降低了水价、提高了饮用水质量、减少了漏水现象，并且提升了符合环境要求的污水处理系统的效率。这些证据可能只具有暗示性，而没有决定性，然而那些赞成政府控制水资源供给的人，则很少会看到这些证据的必要性。对许多人来说，经验性结果并不如根深蒂固的信念和态度一般重要。不论事情紧急与否，许多人都认为，拥有政治权力的人比直接涉及自己利益的私人更可能做出符合道德的决定。

市场批评者想要的通常是对某个个人或群体进行特殊分配，不管他们是报业、种族群体还是其他人，而不承认这种分配不可避免地会牺牲其他个人或群体的利益——这些个人或群体要么被随意地忽视掉，要么就被用非人性化的术语归结为“市场”。例如，《纽约时报》的一名记者在描述一位中年低收入妇女面临的问题时写道：“如果工厂只是让卡洛琳上白班的话，她的问题就会得到解决。”但是，他继而表达了自己的遗憾：“工资和工作时间是由市场决定的，你不能期望从市场那里得到慷慨大度。”

由于道德感受到个人、团体和国家间巨大的经济不平等的触动，许多人便将这些差异归因于特定群体拥有的“优势”或“特权”。但是，关键是要在成就和特权之间做出区分。这不是简单的语义问题。特权以牺牲他人为代价，但成就增加了他人的利益。

道德不是一种奢侈品，而是必需品，因为没有哪个社会能够只靠武力来维系。即使是极权主义统治，也以其独特的道德观培植一种理念，因为即使是具有强权镇压和恐怖统治力量的政治机器，也不足以创造或维持社会的良性运转。然而，虽然道德原则对所有社会都是必要的，但光有道德原则并不充分。把道德原则应用于一个经济体，需要理解该经济体并具备相关知识，以及如奥利弗·温德尔·霍姆斯法官所说的，一种“思考事实，而非语句”的能力。

重商主义者的目的不同于现代经济学家。重商主义者关心的是，增进他们各自国家相对于其他国家的力量。他们的目标并不是用一种能够最大化大多数人的生活水平的方式配置稀缺资源。他们的目标是获得并保持一个国家相对于其他国家在总财富和实力上的相对优势，从而在战争爆发时能够取胜，或者通过拥有能够直接用于军事目的的大量财富，来吓退潜在的敌人。囤积黄金是实现这一目标的理想方式。

亚当·斯密与重商主义者的根本区别在于，亚当·斯密并不将黄金看作财富。《国富论》一书的书名就引出了财富包含什么这一基本问题。亚当·斯密提出，财富由决定人民生活水平的商品和服务构成，而且这里的人民指一国内的所有人。基于经济和道德两个方面原因，亚当·斯密反对帝国主义和奴隶制。他指出，维系帝国主义所需的“大型舰队和庞大军队……所带来的收益，并不足以补偿它们的维护费用”。在《国富论》的结尾，他还呼吁英国放弃帝国主义迷梦。至于奴隶制，亚当·斯密认为，它在经济上是无效率的，在道德上也应当被唾弃，他还轻蔑地反驳了受奴役的非洲人比欧洲人低贱这一观点。

我们今天所说的“经济学”，在19世纪的大部分时期内曾被称作“政治经济学”。当古典经济学家提到“政治经济学”时，他们指的是整个国家（政府体制）的经济学，区别于家庭的经济学，或现在被称为“家庭经济学”的学科。“政治经济学”一词并不意味着经济学和政治学的合并，后来有些人曾使用这个词来表达这种意思。

经济学原理并不是现成的，也不是在灵光一闪间迸发。相反，需要连续几代渊博而勤奋的思想家，摸索出对真实世界的经济活动的理解，逐步掌握对此进行系统研究的学术概念。如今初学者在一个星期内就能学会的供求分析，始于19世纪初的思想家——如大卫·李嘉图、托马斯·马尔萨斯（ThomasMalthus）和让·巴蒂斯特·萨伊（JeanBaptisteSay）等的争论，并且花了至少一个世纪的时间才得以形成。

凯恩斯主义经济学不仅为总产出和就业的变化给出了经济学解释，而且也为政府实施干预恢复萧条经济提供了理论依据。与其等待市场通过自身力量调整并恢复充分就业，凯恩斯主义认为政府支出可以用更小的副作用、更快的速度取得相同的效果。尽管凯恩斯及其追随者认识到政府支出会引发通货膨胀风险，尤其是当“充分就业”变成政府政策时，但是他们认为，这个风险是可接受且可控的，因为在大萧条期间，失业规模产生了变化。

然而，芝加哥学派开始从理论和实证研究两方面，逐步瓦解一般凯恩斯理论，尤其是菲利普斯曲线。芝加哥学派的经济学家发现，市场一般要比凯恩斯主义者认为的更理性也更敏感，而政府在这两方面都更欠缺，至少从提高国家利益的意义上是如此，从抬高政治家权位的方面来看则不然。此时，经济学已变得非常专业化和数学化，以至于大多数人，甚至大多数经济学领域之外的学者，也难以理解杰出经济学学者的著作。人们所能看到的是，凯恩斯主义经济学的正统地位逐渐受到侵蚀，尤其是在20世纪70年代，通货膨胀和失业同时升高，削弱了菲利普斯曲线提出的概念，即政府可以在通货膨胀和失业之间权衡取舍。

科学充满了争论，但是促使某一领域成为科学的，并不是对特定问题无意识的一致同意，而是在有足够数据时，被普遍接受并用于解决某一问题分歧的一组程序。爱因斯坦的相对论一开始并没有被大多数物理学家接受，而爱因斯坦也并不想在没有实证测试的情况下，让人接受这一理论。一次日食期间光线的运动，给他的理论提供了检验机会，意想不到的结果让其他科学家终于相信，爱因斯坦是对的。杰出的科学史学家托马斯·库恩（ThomasKuhn）认为，相互矛盾的理论不能在科学领域无限期共存，这一点将科学与其他领域区分开，当能够获得足够的数据时，某一种观点肯定会胜出，而其他的观点则会消失。

依据熊彼特的观点，“科学本身并不是要我们放弃自己的价值判断，或放弃提倡某些利益的主张”。他更直白地说，“提倡并不意味着撒谎”，虽然有时候意识形态会“升华”成“不受别人观点”影响的“信条”。但是，科学领域的标志之一是“程序规则”，据此可以通过分析来“消除意识形态方面的错误”。此外，明白自己要“构想、捍卫和批判的东西”能够推动实际工作和分析工作，即使这个过程有时会受到意识形态的干扰。因此“尽管由于自身的意识形态，我们进展缓慢，但是若没有它们，我们也许就不会取得任何进步”。

事实虽然重要，但理解这些事实的含义更重要，这一点我们可以通过理解经济学达到。例如，伊士曼柯达公司在一个多世纪的时间里一直是国际摄影工业的巨头，却被数码相机的崛起击垮，柯达公司的众多产品建立在已经过时的胶片技术之上，而它们的市场受到了数码相机的冲击。然而，柯达公司缺乏的并不是关于数码相机的知识（数码相机正是由柯达公司发明的），而是未能看出这项新技术的含义以及其他公司开发这项技术的潜能，正是这些公司迫使柯达走向破产。这些其他公司不仅包括尼康、佳能等传统的相机制造商，还有摄影工业以外的公司，如索尼和三星，它们也开始涉足数码相机生产。重要的并不是摄影行业或其他行业中的某家公司战胜了某个对手，而是知识与洞察力在市场竞争中的决定性作用。公众能够从中获益，是因为企业基于对当时当地的经济现实更准确的理解做出了商业决策，并存活了下来，具有替代用途的稀缺资源在这些企业中也得到了更有效地使用。在中央计划经济体中，计划者要设定数百万个价格，并让这些价格对环境的诸多不可预知的变化做出反应，这根本就是不可能完成的任务。他们不断失败一点都不令人惊奇。奇怪的是有人竟相信他们能够成功——因为要成功地安排价格，某个地方的某一群人需要使用并掌握的知识是海量的。

事实上，知识分子还有很多不知道的知识，并且这些知识对经济体系的运作至关重要。我们很容易蔑视那些非常具体、十分平凡的知识及它们的含义，但是它们在经济上往往具有决定性的作用，例如人们会问：“煎个汉堡包需要多少知识？”麦当劳能够在世界各地拥有成千上万家专营店，成为一家价值数十亿美元的公司，这并不是没有原因，它有那么多的对手为了同一个目标拼命努力却没有成功，而且其中一些对手甚至无法获取足够的收入把企业办下去。研究过这家特许经营连锁店历史②的人都会惊讶于它运用的大量细节性知识、洞察力、组织和技术创新、财务应变能力、全力以赴以及巨大牺牲，这些知识将麦当劳从销售品种有限的普通食品小店，变成了在经济上取得巨大成功的大型公司。

所有的经济制度，不论是社会主义、资本主义、封建主义还是其他，本质上都是协调商品与服务生产和分配的方式，不论效率是高还是低，是出于自愿还是非自愿。个人或群体自然地都希望自己在这个过程中的贡献能得到更多的回报，但是他们的抱怨或冲突只是余兴节目，真正的大事件是所有人共同努力，制造赖以生存的产出。不公平的比较与互相残杀的斗争只是社会闹剧，却成为媒体、政治以及部分知识分子的命脉。
