#+title: 黑天鹅(Black Swan)

提出了一个观点，一个与我们的许多思维习惯相反的观点，即我们的世界是由极端、未知和非常不可能发生的（以我们现有的知识而言非常不可能发生的）事物所主导的，而我们却一直把时间花在讨论琐碎的事情上，只关注已知和重复发生的事物。这意味着必须把极端事件当做起点，而不是把它当做意外事件置之不理。我还表达了更为大胆（以及引起愤怒）的观点，那就是，即使我们取得了知识上的进步和成长（或者正因为这种进步和成长），未来仍会越来越不可预测，而人性和社会“科学”合谋起来向我们隐藏了这一点。

我的存在是低概率事件的重大结果，而我经常忘记这一点。

我再次强调，我们是寻找原因的动物，习惯于认为一切事情都有确定的原因，并且把最明显的那一个当做最终解释。但实际上可能并没有可见的原因，相反，很多情况下什么也没有，甚至没有任何可供选择的原因。沉默的证据掩盖了这一事实。每当涉及我们的幸存时，原因就被严重削弱了。幸存的条件消灭了所有可能的解释。亚里士多德的“因为”不是为了把两件事联系起来（如我们在第六章看到的），而是为了满足我们习惯寻找原因的潜藏弱点。

只要涉及你的幸存，不要忙着寻找因果。我们可能根本无法了解我们从这种疾病中幸存下来的主要原因：我们活下来了，因为卡萨诺瓦式的温馨情境出现了，如果这看上去太难以理解，那是因为我们被因果观念洗脑了，而且我们以为说“因为”比接受随机性看上去更聪明。

我之前说过，我们的认知系统对于不出现在我们眼前或不引起我们情感注意的事物可能没有反应。我们天生肤浅，只注意我们看到的东西，不注意没给我们留下生动印象的东西。我们向沉默的证据发动了双重战争。潜意识的推理机制（确实存在这样的机制）忽视沉默的证据，即使我们知道需要考虑它。不进入视线则不进入大脑：我们对抽象的东西怀有天性上的甚至行动上的蔑视。

可惜，现存的人类天性不愿理解抽象事物，我们需要具体背景。随机性和不确定性是抽象事物。我们尊重发生的事，忽视本来可能发生的事。也就是说，我们天生肤浅，却浑然不知。这不是心理学问题，它来自信息的主要特性。人们很难看到月亮的阴面，照亮它是花费能量的。同样，照亮没有被看到的事物既费力又劳神。

对一个信息不完整或信息缺失的不具随机性的变量（比如凯瑟琳二世的情人数量）的猜测，与对一个随机变量（比如明天的失业率或明年的股票市场情况）的预测是没有区别的。从这个意义上讲，猜测（我不知道但别人可能知道的事情）与预测（还没有发生的事情）是同一回事。

当你受雇于人，因此依赖于他人的评价时，显得忙碌能帮助你在结果不确定的环境中邀功。显得忙碌能够加强人们对结果与你的作用之间的因果关系的判断。对于那些鼓吹自己的“存在”与“领导”在公司业绩中的作用的大公司CEO们更是如此。我没有听说过谁研究他们用于谈话和接受琐碎信息的时间有多大有效性，也没有几个作者有勇气质问CEO在公司成功中究竟有多大作用。

把一张模糊的消火栓图片——模糊到使他们无法认出图片上是什么——给两组人看。对其中一组，分10次逐步提高图片的清晰度，对另一组分5次提高清晰度。在某个使两组人看到相同清晰度图片的时候停下来，请他们说出看到的是什么。经过较少中间步骤的那一组可能更快地辨认出消火栓。这意味着什么？你提供的信息越多，他们就会形成越多假设，他们的结论就越糟糕。他们看到了更多的随机噪点并将其当成了信息。

有些学科的确存在真正的专家。我们考虑下面这几个问题：你愿意让某报纸的科学记者还是有执照的脑外科医生为你做脑部手术？另一方面，你愿意听某个“著名”学院（比如沃顿商学院）毕业的金融博士还是某报纸的商业版作家对经济作出预测？虽然对第一个问题的回答非常明显，但对第二个问题不是。我们已经认识了“技术”和“知识”的区别。

是专家的专家：牲畜检验员、宇航员、飞机试驾员、土壤检验员、国际象棋大师、物理学家、数学家（研究数学问题而非经验问题）、会计师、谷物检验员、图像分析员、保险分析师（研究钟形曲线统计问题的）。不是专家的专家：证券经纪商、临床心理医生、精神病医生、大学招生负责人、法官、顾问、人事官员、情报分析师（虽然花了那么多钱，但美国中央情报局的历史表现很令人遗憾）。我还要加上我自己分析文献的结果：经济学家、金融预测者、金融学教授、政治科学家、“风险专家”、国际清算银行员工、国际金融工程师协会的傲慢成员以及个人金融咨询师。

很简单，因变化而需要知识的事物，通常是没有专家的，而不变的事物似乎会有专家。也就是说，与未来有关，并且其研究是基于不可重复的过去的行业则通常没有专家（天气预测以及从事短期物理活动，而非社会经济活动的行业除外）。我并不是说任何从事未来预测的人都不能提供有价值的信息（如我之前指出的，报纸能够非常准确地预测剧院开门的时间），而是说那些无法提供具有可见价值信息的人通常从事预测行业。

我已经提过结婚者对未来的不现实预期。想一想有多少家庭对未来进行筛选性假设，他们把自己锁在牢固的房产中，以为会在那里生活一辈子，而不知道人们过稳定生活的记录很糟糕。他们难道没有看见那些衣冠楚楚的房地产经纪人开着漂亮的德国轿车到处转吗？我们是极为漂泊不定的，比我们计划的不稳定得多，而且不得不如此。想一想有多少突然失去工作的人料到了这一点，即使只提前几天，或者想一想有多少瘾君子在一开始是打算长期吸毒的。

为了开会，经理们满世界飞：巴塞罗那、香港等等。他们千里迢迢只为了一大堆空话。毫无疑问，他们通常没法睡觉。当一名管理者不需要非常发达的头脑，而是需要同时拥有人格魅力、忍受无聊的能力和草草执行匆匆制定的时间表的能力。除了这些“任务”之外，他们还有出席歌剧表演的“职责”。

亨利·彭加莱虽然名声显赫，但通常被认为是价值被低估的科学思想家，因为他的一些思想过了近一个世纪才得到人们的赞赏。他或许是最后一位伟大的思想数学家（或者数学思想家）。每次我看到印有现代偶像爱因斯坦头像的T恤衫时，我就无法不想到彭加莱。爱因斯坦值得我们尊敬，但他掩盖了别人应得的许多尊敬。我们的意识空间太狭小了，这也是一种赢家通吃。

彭加莱在30多岁时成为多产的论文作者，他似乎在赶时间。他58岁时便英年早逝。他如此匆忙，即使发现了文字中的打字和语法错误，也懒得改正，因为他认为改错是浪费时间。人类再也没有产生这样的天才，或者说再也不让天才以他们自己的方式写作。

彭加莱的理论很简单：在预测未来的过程中，你所模型化的过程需要越来越精确，因为你的错误率会迅速上升。而仅仅达到近似的精确是不行的，因为你的预测会突然失效，最终需要对过去进行无穷精确的解释。

20世纪60年代，麻省理工学院的气象学家爱德华·洛伦茨独立地再次发现了彭加莱的理论，同样是出于偶然。他正在建立一个天气变化模型，并对一个天气系统几天后的情况进行了模拟预测。后来他使用同一模型进行重复模拟，而且他认为自己输入的是相同的参数，但得到的结果却大相径庭。他起初以为差异来自计算机漏洞或计算错误。当时的计算机较为笨重和迟缓，与我们今天的计算机完全不一样，所以使用者受到时间的严重约束。洛伦茨后来意识到，计算结果的巨大差异不是来自计算错误，而是来自输入参数的小小的四舍五入。这就是著名的蝴蝶效应，一只在印度震动翅膀的蝴蝶能够引起两年之后纽约的飓风。洛伦茨的发现引起了人们对混沌理论的兴趣。

在正统经济学中，理性成了一件紧身衣。柏拉图化的经济学家忽视了一个事实，那就是人们可能喜欢别的东西胜过喜欢最大化他们的经济利益。这导致一些数学技巧的诞生，比如“最大化”或“最优化”，保罗·萨缪尔森的大部分工作正是基于此。最优化是指为一个经济问题找到数学上的最优解决方案。例如，你对不同股票的“最优”购买数量是多少？它涉及复杂的数学，因此对非数学学者设立了进入障碍。我不是第一个提出这种最优化阻碍了社会科学的人，它把社会科学从一个思考和沉思的学科降低为一种“精确的科学”。“精确的科学”指的是那些假装热爱物理学或患有物理嫉妒病的人从事的二流工程问题。换句话说，它是智力骗局。

我们在总体上高估了不幸事件的影响持续的时间。你以为你的财富或当前的地位遭受的损失将是灾难性的，但你很可能错了。更可能的情况是，你将能适应任何事情，正如你面对过去的不幸时所做的那样。你可能会感到痛苦，但不会像你预期的那样糟糕。这种错误预测可能存在一种目的：刺激我们采取重要的行为（比如购买新车或努力致富），防止我们冒不必要的风险。这是一个更为一般化的问题的一部分：人类喜欢不时地自我欺骗。根据特里弗斯的自欺理论，这会使我们以更有利的方式走向未来。但自欺在其自然领域之外不是一种值得期待的特点。它防止我们冒不必要的风险，但我们在第六章看到，它无法为我们阻挡现代风险的洪流。我们不害怕这些风险，因为我们根本没有觉察到，比如投资风险、环境危机和长期安全。

不从事随机性工作的人不会明白其复杂性。通常，在哲学家（有时候是数学家）听我谈论不确定性和随机性的会议上，他们会向我提出最不相关的问题，比如我所说的随机性是“真正的随机性”，还是伪装为随机性的“确定性混沌”。真正的随机系统确实是随机的，而且不存在可预测的特性。混沌系统有完全可测的特性，但人们很难找到，所以我对他们的回答是双重的。1.这两者之间不存在重要差别，因为我们永远也区分不出来，差别是数学上的，不是现实中的。如果我看到一名怀孕的女性，她的孩子的性别对我来说是纯粹的随机问题（两种性别各50%的可能），但对她的医生不是，他可能已经为她做过超声波检查。2.一个人谈论这一区别，这表明他从未在不确定性的条件下做过有意义的决策，这正是他没有认识到在现实中不可能区分的原因。随机性最终只是反知识。世界隐藏在迷雾中，而表象在愚弄我们。

历史就像博物馆，人们可以进去看过去的收藏，感受昔日的魅力。它是一面奇妙的镜子，你可以看见我们的自我叙述。你甚至可以利用DNA分析追踪过去。我很喜欢文学史。古代历史满足我建立自我叙述、自我认同和与我（复杂的）东地中海的根源建立联系的愿望。我喜欢古老的、不那么精确的书胜过喜欢现代书籍。在

历史能使我们陶醉地以为了解了过去，满足了我们讲故事的愿望（确实），只不过是非常有害的故事。人们应该极为谨慎地学习。如果没有谨慎的态度，历史显然不是一个理论化和得出一般知识的地方，也不会对未来有所帮助。我们能从历史中得到负面认知，这一点是无价的，但同时我们也得到了太多知识的假象。

经验主义的医生对待归纳问题的方法是了解历史，而不是将它理论化。学会阅读历史，吸取所有可能的知识，不要对奇闻逸事皱眉，也不要建立任何因果链条，不要试图过多地求方程，但如果你这样做了，也不要大张旗鼓地提出科学观点。请记住，经验怀疑主义者尊重习惯：他们把它当做默认状态，行为的基础，但仅此而已。他们称这种对待过去的明确方法为结语主义。

对小问题的建议就是：保持人性！在你自己的问题中，接受人类存在认知自大这一事实。不要为此羞愧。不要试图总是不作判断，生活中离不开观点。不要试图避免预测，是的，在批判了预测之后，我不要求你不再犯傻，但要在正确的地方犯傻。你应该避免的是对大范围的有害预测的依赖，仅此而已。避免那些可能损害你的未来的大主题：在小事上当傻瓜，而不是在大事上。不要听经济预测者或社会科学预测者的话（他们只是演员），但要作你自己的预测。尽一切努力，确定下一次野餐的情况，但不要相信政府对2040年社会保障情况的预测。学会根据观点可能造成的损害而不是好听的程度来辨别它们。

我努力在此把我作为一名证券交易者所使用的“杠铃”策略推广到真实生活中。如果你知道容易犯预测错误，并且承认由于有黑天鹅事件的影响，大部分“风险管理方法”是有缺陷的，那么你的策略应该极度保守或极度冒险，而不是一般保守或一般冒险。

这与“杠铃”策略是吻合的，在将正面黑天鹅事件的影响最大化的同时，保持对负面黑天鹅事件的警惕。要从正面黑天鹅事件中获益，你不需要对不确定性有任何精确的理解。有一点我很难解释，那就是在你只有非常有限的损失的时候，你必须尽可能主动出击，大胆投机，甚至“失去理智”。

不要寻找精确和局部的东西。简而言之，不要狭隘。提出“机会青睐有准备的人”的伟大微生物学家巴斯德懂得，不要在每天早上寻找某种特定的东西，而要努力工作，并让意外进入你的生活。正如另一位伟大的思想家优吉·贝拉所说：“假如你不知道往何处去，请一定小心，因为你可能到不了那里。”

所有这些建议有一个共同点：不对称性。请把你自己放入一个好结果比坏结果大得多的条件下。实际上，不对称结果是本书的核心思想：我永远不可能知道未知，因为从定义上讲，它是未知的。但是，我总是可以猜测它会怎样影响我，并且我应该基于这一点做出自己的决策。

有一个更微妙的认知问题。请记住，在正面黑天鹅行业，过去没有揭示的东西几乎一定对你有利。当你回顾生物科技行业的收益时，你没有看超级火暴的记录，但由于它们有可能发现治愈癌症（或者头痛、秃顶、缺乏幽默感等）的方法，这个行业在很小的可能性上会实现巨大的销量，比人们预料的大得多。另一方面，考虑一下负面黑天鹅行业。你看到的过去的记录很可能高估了相关特征。回忆一下1982年美国银行的纷纷破产：它们在天真的观察者眼中比看上去更赚钱。保险公司有两类：属于平均斯坦的常规多样化保险公司（比如人寿保险）和更危险的、易受黑天鹅事件影响的保险公司，它们通常会进行再保险。根据数据，再保险公司的再保险业务在过去20年里是赔钱的，但与银行家不同的是，它们进行了足够的反省，知道情况本可能更糟，因为过去20年里没有发生重大灾难，而100年里只需要一次灾难就能让这些公司破产。许多对保险进行“估值”的金融学者似乎都忽略了这一点。

一切都是暂时的。运气缔造和毁灭了迦太基，运气缔造和毁灭了罗马。我已说过，随机性是不好的，但并非总是如此。运气甚至比智慧更公平。如果人们严格根据能力获得报酬，有可能仍然不公平，因为人们无法选择自己的能力。随机性能够对社会进行重新洗牌，把那些大人物拉下马。

记住：高斯钟形曲线都受到一种阻力，使偏离平均值的概率下降得越来越快，突破性分布或者曼德尔布罗特分布则不受这种限制。这基本上就是你需要知道的。

模型的构想者不得不浪费时间写关于哪些模型可以产生突破性分布的理论，似乎他们必须为此道歉一样。理论！我对这一点有一个认知上的问题，我不明白为什么我们要为世界不能满足某个理想模型找理由，而这个模型只不过是得到了对现实视而不见的人的追捧。

我不知道的是，1987年并不是高斯方法第一次显露出欺骗性。曼德尔布罗特在1960年左右向经济学界提出突破性分布的观点，向他们展示高斯曲线不能描述当时的市场价格。但在兴奋之后，他们意识到他们不得不重新学习。当时一位具有影响力的经济学家、已故的保罗·库特纳（PaulCootner）写道：“就像之前的丘吉尔首相一样，曼德尔布罗特不是向我们许诺乌托邦，而是向我们许诺血、汗、苦役和眼泪。假如他是正确的，我们几乎全部的统计工具都是过时或毫无意义的。”我要对库特纳的话作两点更正。首先，我要把“几乎全部”替换为“全部”。其次，我不同意血和汗的说法。我认为曼德尔布罗特的随机理论比传统统计学易懂得多。假如你是新入行的，就不要依赖老的理论工具，也不要对确定性有很高的期望。

确实，该奖曾颁给一些有价值的思想家，比如经验心理学家丹尼·卡尼曼和思想经济学家弗里德里希·哈耶克。但评奖委员会已经习惯于把诺贝尔奖发给那些用伪科学和伪数学为经济学“带来严谨”的人。在股市崩盘之后，他们授奖给两名理论学家哈里·马克威茨和威廉·夏普，他们以高斯方法为基础，建立了漂亮的柏拉图化模型，对所谓的现代投资组合理论作出贡献。很简单，假如你去掉他们的高斯假设，把价格当做突破性变量，你就只剩下吹牛。诺贝尔委员会可能验证过夏普和马克威茨的模型，其作用就像网上出售的江湖偏方，但斯德哥尔摩似乎没人考虑这一点。委员会也没有征求我们这些实践者的意见；相反，它依赖于某种学术审查，而在有些学科，这种审查可能已经腐败到骨子里了。这次颁奖之后，我作了一个预测：“在这两个人能够获得诺贝尔奖的世界里，任何事都有可能发生。任何人都可能成为总统。”

事情在1997年变得更加糟糕。瑞典学院再次将诺贝尔奖发给以高斯方法为基础的迈伦·斯科尔斯（MyronScholes）和罗伯特·C·默顿，他们改进了一个老的数学公式，使它与现有的高斯一般金融均衡理论兼容，于是得到了经济学界的认可。这个公式现在“能用了”。它有许多被人们遗忘的先行研究者，包括数学家兼赌徒爱德华·索普（EdwardThorp）。他撰写了畅销书《击败庄家》（BeattheDealer），告诉人们如何在玩21点时赢钱，但人们却认为是斯科尔斯和默顿发明了这种方法，实际上他们只是使它被学术界接受而已。那个公式就是我的谋生之道。交易员比学术界更知道它是怎么回事，因为他们日夜担心风险，只不过他们很少有人能够用术语表达想法，所以我感觉我代表的是他们。斯科尔斯和默顿使这个公式变得依赖高斯分布，而他们的“先驱者”没有对它作过这类限制。

小罗伯特·默顿和迈伦·斯科尔斯是一家大型投机性证券公司的创始合伙人，该公司就是长期资本管理公司，我在第四章提到过。它聚集了学术界的顶尖人才，他们被称为精英。投资组合理论是他们进行风险管理的灵感来源，他们会进行精密的“计算”。他们成功地把游戏谬误放大到整个金融业。然后，1998年夏天，由俄罗斯金融危机引发的一系列大事件发生了，这些事件在他们的模型之外。这是一只黑天鹅。长期资本管理公司破产，并几乎把整个金融系统拖下水，它的影响太大了。由于他们的模型排除了大离差的可能性，所以他们把自己置于可怕的风险之下。默顿和斯科尔斯的思想以及现代投资组合理论开始动摇了。损失太惨重了，惨重到我们无法再忽略知识的闹剧。我和许多朋友以为投资组合理论家会面临烟草公司的命运：他们害得人们损失了积蓄，并很快为自己的高斯方法造成的后果负责。但这并没有发生。相反，商学院的MBA们继续学习投资组合理论。期权定价公式继续被冠以布莱克-斯科尔斯-默顿的名字，而不是其真正发现者的名字，如路易斯·巴切里亚（LouisBachelier）、爱德华·索普等。

我选出默顿是因为我发现他非常突出地体现了学术愚昧。我从他寄给我的一封7页的愤怒而带有威胁色彩的信中发现了他的弱点，这封信给我的印象是他对我们如何交易期权并不熟悉，而期权正是他的研究对象。他似乎以为交易员依赖于“严格”的经济理论，就好像鸟必须学习（糟糕的）工程学才能飞一样。

最终存在一个小小的决策法则：当我能够受到正面黑天鹅事件影响时，我会非常冒险，这时失败只有很小的影响；当我有可能受到负面黑天鹅事件的袭击时，我会非常保守。当某个模型中的错误对我有好处时，我会非常冒险；当错误对我有害时，我会非常多疑。这可能并不十分有趣，但这正是别人没有做到的。例如，在金融业，人们使用脆弱的理论来管理风险，把狂野的思想置于“理性”的审视之下。

藐视命运。我一直教我自己拒绝追赶时间表。这可能只是一条很小的建议，但它印在了我的脑海里。从拒绝追赶列车中，我体会到“优雅”的真正价值和行为中的美学，一种控制我的时间、行程和生活的感觉。错过列车，只有在你追赶它时才是痛苦的！同样，不能达到别人对你期望的成功，只有在它也是你所追求的东西时才是痛苦的。你凌驾于争斗与名利思想之上，而不是之外，只要你愿意这样选择。只要是你的决定，放弃一份高薪职位带来的回报会超过金钱带给你的效用（这似乎很疯狂，但我试过并且确实如此）。这是向命运说“随你怎么样”的第一步。如果你确定了自己的标准，你对自己的生活会有大得多的控制。大自然给了我们一些防御机制：如伊索寓言中写到的一样，其中之一就是把我们不能（或没有）吃到的葡萄想成酸的，但如果你更加主动地在之前就鄙视并拒绝葡萄，你的满足感会更大。主动出击，主动辞职，只要你有勇气。

年以来，我经历了诸多变化，其中大部分的变化都是令人鼓舞振奋的。像聚会一样，一本书会使你交到意想不到的好运，并且会使你有机会得到更多的聚会邀请。在那段艰难的日子里，别人都把我讽刺为巴黎的商人（极端粗俗的代表）、伦敦的哲学家（极端学究的代表）、纽约的预言家（当时我曾给出了错误的预言）以及耶路撒冷的经济学家（极端现实主义的代表）。而现在，别人都把我恭奉为以色列的预言家（这需要我付出很多的努力）、法国的哲学家、伦敦的经济学家和纽约的商人（商人在纽约备受尊重），这又令我受用不起。

冗余的对立面是天真的优化。我会告诉每个人不要去参加一些所谓正统的经济课，并告诉他们，经济会使我们垮掉。（我们将会看到，我们有证据证明经济会搞垮我们。但是，正如我在书中所提到的，我们并不需要这些证据，我们需要的是看到科学的缺乏严密和道德的缺失。）之所以如此，是因为这在很大程度上依靠天真优化的观念。这一观念由保罗·萨缪尔森进行了数学化处理（拙劣的），这一数学行为为错误倾向社会的建立作出了贡献。经济学家会认为，两个肺与两个肾的效率并不高，他们会考虑这些器官的物流成本。这种优化最终会伤害到你。同时，如果我们的大自然由经济学家来控制，那么我们便会被省去一个肾，因为我们并不是任何时候都需要两个肾。更为“有效”的做法是我们将自己的肾脏卖掉，而仅在需要的时候使用公用肾。并且，你可以在夜间出租你的眼睛，因为你在夜间做梦时并不需要它们。

正因为如此，我发现，目前关于全球化的观点（比如记者托马斯·弗里德曼所推崇的观点）过于天真，会对社会造成极大的危害。全球化看上去会带来高效率，然而运行杠杆不同部分之间的交互作用会引起某个点的裂隙，从而影响整个体系，结果就像是许多脑细胞同时崩溃而引发大脑癫痫发作。而我们知道，运作机制复杂的大脑体系并没有达到“全球化”的程度。

大家都想当然地认为，规模大了便会更稳定，殊不知公司规模的扩大只是迎合了华尔街分析师们的胃口。华尔街的分析师们（MBA）会敦促公司出售多余的那只肾脏，冒着风险提高公司的每股收益率并提高公司的盈亏底线。然而这样做，最终只会导致公司的破产。

后来，我便致力于极端斯坦生活方式的研究：在令人激动的城市环境中漫步与思考，偶尔小跑上一段，跑的时候我会想象自己正手握棍棒追赶银匪罗伯特·鲁宾，试图将他抓住之后绳之以法。我会来到任意某处举重场所，进行一次彻底的随机测试——一般是在酒店里。像灰天鹅事件一样，这些虽非常罕见，但在一天的半饥饿状态过后，却使我精疲力竭。然后，我会在数周时间里无所事事，整日在咖啡店里度日。甚至连测试的时间都是随意的，多数情况下都很短，不超过15分钟。我尽量使我的测试充满乐趣。我对体育馆的员工彬彬有礼，尽管他们认为我的测试“不可理喻”。同时，我还使自己处于一种冷热变化的状态，偶尔不穿外套便在大冷天外出。由于环球旅行和飞行时差的原因，我经常会长时间不睡之后大睡一觉。每当我来到美食之都（比如意大利），我便会造访知名餐馆放开肚皮大吃一通，令那些肥头大耳的吃客都自愧不如。然后，我便会连续几顿不吃饭，倒也没什么事。在度过了两年半时间看上去“不健康”的生活方式之后，我却发现自己的诸多身体指标发生了显著的改善——多余脂肪消失，血压恢复正常，思维更加清楚敏捷等。

然而，这些有关生活方式的观点并不仅来自自我实验或者某一种庸俗的理论。所有结论都来自有真凭实据的调查研究。饥饿（或者短暂的体能欠缺）会增强人的体质和免疫系统，并会激活大脑细胞，甚至会削弱癌细胞和预防糖尿病的发生。现在的思维方式（某些程度上类似于经济学）来自与实验法研究的同步。我能够通过最少的努力重新创造出饥饿者生活方式的90%的利益，而不受现代生活方式的约束（我对大自然的景色已经产生了厌倦心理，我宁愿选择在威尼斯的犹太人地区散步，也不愿意在旅游胜地波拉波拉岛游玩）。

没有知识，我们不能做任何事情，除非我们知道知识的止境和运用知识的代价。后启蒙运动科学及其后来者明星科学，非常幸运地大大促进了线性物理学、化学和工程学的发展。然而，在某种程度上，我们需要放弃精密，转而将视线投向长期不被重视的事情上：能够展示出现代知识和现代方法所不能展示的地图；对于一般科学医源性的严谨研究，科学可以引起何种伤害（或者说科学已经带来了哪些伤害）。我认为，这是最值得探寻的一点。

过于专门化也不是一件好事。可以想象，一旦你完全丢掉你的工作，你会去做什么？面对金融危机，相对于单一的华尔街分析师（预测型的），在夜间跳肚皮舞作为第二职业的华尔街分析师受到的影响会更小。
