#+title: 眨眼之间: 不假思索的决断力

Blink: The Power of Thinking Without Thinking

薄片理论：通过观察事情的某些切片或者是traits来快速做出评估和决策。这些都是发生在眨眼之间的。如果平时经过良好的训练的话，那么这种决策会卓有成效，相反如果平时没有经过训练而只是单纯地依照原始反应的话，那么容易酿成大错。

他发现我们仅需把重点放在他称为四骑士(four horsemen)的4个因素上：戒备，一言不发，指责和蔑视，问题便十有八九能迎刃而解了。而在这四骑士中，蔑视被看作是重中之重的因素。如果戈特曼关注到，夫妻双方或一方对另一方表现出蔑视的情绪，他们也会将视为婚姻出现危机的最重要的标志。戈特曼说：“因为指责对一个人性格的全盘否定，所以你可能会认为指责才是最伤人的，但是指责和蔑视二者之间存在着本质差别。”蔑视往往是一种侮辱：“你是个泼妇败类”，这其实是在试着把对方强压到低你一头的位置，是在划分等级。

我们的直觉在我们的经历和环境中产生，这意味着通过构改变构成直觉的经历环境，我们便可以改变我们的直觉。换句话说我们可以对运用薄片分析法的方式加以改动。假如你是一位希望对黑人一视同仁的白人，假如你想要对黑人建立起同白人一样积极的联系，那么你会发现，种族平等所需要的不仅仅是一个承诺那么简单。你需要改变自己的生活方式，频繁的接触少数人中，与他们和睦相处，你还要熟悉少数族裔文化中的精华部分，从而避免在会面，雇佣，约会或交谈的过程中，显得扭捏迟疑，局促不安。如果我们想重视快速认知的作用，想要认识到直觉对我们生活好坏参半的巨大影响，我们就必须要积极行动起来，学会管理和控制自己的直觉。

早在执掌红军指挥权之初，范里佩尔就将这一经验烂熟于心。他借用了管理学大师凯文凯利的一句箴言：“我向我的团队所讲的第一件事情就是，我们要掌握主动权，我们也要失控。”这句话的意思是，虽然总体的战略方向和目标上是由我和高级将领们设计的，但在战场上，战士们实际要遵循的可不是上级下发的难度的指令，他们需要在行动中运用自己的直觉来判断，并采取出乎敌人意料的行动。几乎每天，我们红军的空军长官都本着令人猝不及防的战略原则，萌发出各式各样的新点子，从各个角度对别人进行攻击。但他从未从我这里得到过任何具体的行动指示，我只是把战略目标告诉了他而已。

范里佩尔不喜欢在交战过程中进行自我分析，不喜欢各种形式的解释说明，也不爱举行冗长的会议。他说：“我告诉我的部队，我们要坚决避免像蓝军那样满口专业术语，除非是在日常谈话中，否则你甭在我这边提’效应'这种事，我也不想听别人拿作战评估跟我说事儿。我不希望我的部队流于这种机械的做事方式，而是希望大家能够运用才智和经验，并且相信自己的判断力。”

那个实验相互表明，自我分析会妨碍和摧毁人们的洞察能力，通过要求实验对象对果酱进行理性的剖析，把他们变成了果酱白痴。

我们的潜意识来自紧锁的密室中，我们无法窥探其究竟。但是熟能生巧，通过锻炼，我们是能做到自如地解读和破译快速决断与第一印象背后的玄机的。

但这并不是说在对待不擅长或不热衷的事物时，我们的看法无一例外都是错误的。只能说这是我们的看法，都是流于表面，难以阐释，易受干扰的，因为这些看法并不是基于对事物的深刻理解而得来的。

要做到这一点，我们就必须对形容味道的专有词汇有一定的认识和理解。希维尔和赫尔曼都能以优异的准确率通过三角测试的考验，因为两人掌握的知识让他们的第一印象韧性十足，变通自如。

然而在对参与过枪击事件的警官的采访中，同样的细节却频频出现：视觉高度清晰，隧视野出现，声音减弱，以及时间降速的感觉，这是人类身体应对极度压力的方式，各种奥妙并不难理解。当威胁生命的情况出现时，我们的大脑会急剧缩减我们需要处理的信息数量及范围，为了增强对眼前咫尺之遥的危机的感知，声音，记忆以及笼统的社会认知都成为牺牲品。

面对不公正的评审体制，管弦乐团采取了什么样的措施呢？他们选择了解决问题。而这，也是《眨眼之间》一书的第二个重点。对于在眨眼之间发生的事情，我们往往会采取听之任之的态度，看起来我们好像对于从潜意识浮现的东西没有什么控制力，但其实我们是可以掌握主动权的。如果我们能够控制任快速认知发生的环境，那么我们就能控制快速认知本身，我们是有力量去帮助那些身处于战争，就职于急诊室，或巡逻街道的人避免失误的。
