#+title: Boots of Spanish Leather

第一次听到这首歌的时候，有些想流泪的感觉。旋律很优美，唱法也比较朴实，像是在写信或是和朋友讲自己的故事，用词也相当的考究。

每个人都有过一段和心上人分开和重聚的时刻，那种内心感觉有期盼兴奋焦虑紧张，很难用语言描述。

Dylan的这首歌，用文字构造了各种大家熟悉场景，让每个曾经有过这种经历的人产生强烈的共鸣。

#+BEGIN_VERSE
Oh, I’m sailin’ away my own true love
哦，我在远航，我的真心爱人
I’m sailin’ away in the morning
我在早晨远航
Is there something I can send you from across the sea
需要我从对面的大海给你寄点什么东西吗
From the place that I’ll be landing?
从那个我将登陆的地方

No, there’s nothin’ you can send me, my own true love
不，没有什么需要你寄给我的，我的真心爱人
There’s nothin’ I wish to be ownin’
我不希望拥有别的什么
Just carry yourself back to me unspoiled
只要把你自己完好无损地带回来给我
From across that lonesome ocean
从对面那个寂寞的海洋

Oh, but I just thought you might want something fine
哦，但我只是认为你或许想要些精美的小玩意儿
Made of silver or of golden
用银或金制的
Either from the mountains of Madrid
从马德里山脉
Or from the coast of Barcelona
或者巴塞罗那海岸

Oh, but if I had the stars from the darkest night
哦，但假如我从最黑暗的夜空摘到了星星
And the diamonds from the deepest ocean
还有从最深的海洋捞到了钻石
I’d forsake them all for your sweet kiss
我全都会为了你甜蜜的吻而放弃它们
For that’s all I’m wishin’ to be ownin’
那些都是我自己想要的

That I might be gone a long time
我或许会离开许久
And it’s only that I’m askin’
我只想问
Is there something I can send you to remember me by
需要我给你寄点什么东西吗，好让你记得我
To make your time more easy passin’
好让你的日子更好打发

Oh, how can, how can you ask me again
哦，你怎么，你怎么能再三问我
It only brings me sorrow
这只会给我带来悲伤
The same thing I want from you today
我今天想要你给的东西
I would want again tomorrow
明天我还会想要

I got a letter on a lonesome day
我在一个寂寞的日子里收到一封信
It was from her ship a-sailin’
从她航行的轮船上
Saying I don’t know when I’ll be comin’ back again
说着我不知道我将何时归来
It depends on how I’m a-feelin’
这取决于我的感觉

Well, if you, my love, must think that-a-way
哦，假如你，我的爱人，一定要那样想的话
I’m sure your mind is roamin’
我敢说你的脑子一定在流浪
I’m sure your heart is not with me
我敢说你的心已经离我而去
But with the country to where you’re goin’
而是到了你将去的国度

So take heed, take heed of the western wind
所以要注意，要注意西风
Take heed of the stormy weather
要注意暴风雨的天气
And yes, there’s something you can send back to me
是的，你可以给我寄些东西
Spanish boots of Spanish leather
西班牙皮革的西班牙靴子
#+END_VERSE
