#+title: Building a Career in Technology

http://www.benstopford.com/2015/01/02/a-career-in-technology/

写得很好，我这里对照每一点简单翻译下。

1. Don’t assume progress means a career into management – unless you really love management. If you do, great, do that. You’ll get paid well, but it will come with downsides too. Focus on what you enjoy. (选择自己喜欢的事情，不一定进入管理层才是成功)

2. Don’t confuse management with autonomy or power, it alone will give you neither. If you work in a company, you will always have a boss. The value you provide to the company gives you autonomy. Power comes mostly from the respect others have for you. Leadership and management are not synonymous. Be valuable by doing things that you love.（管理和领导力是不同的东西，管理是个职位，领导力是结果）

3. Practice communicating your ideas. Blog, convince friends, colleagues, use github, whatever. If you want to change things you need to communicate your ideas, finding ways to reach your different audiences. If you spot something that seems wrong, try to change it by both communicating and by doing.（不断练习和别人交流自己的想法）

4. Sometimes things don’t come off the way you expect. Normally there is something good in there anyway. This is ok.（独自等待，默默承受，幸福总是出现在我梦中 - Don't break my heart - 黑豹）

5. The T-shaped people idea from the Valve handbook is a good way to think about your personal development. Have a specialty, but don’t be monomaniacal. What’s your heavy weaponry?（有自己的特长，但是不要过分偏执于其中）

6. Whatever speciality you find yourself in, start by really knowing the fundamentals. Dig deep sooner rather than later as knowledge compounds.（了解根本，早点深入，知识是会累积起来的）

7. Always have a side project bubbling along. Something that’s not directly part of your job. Go to a hack night, learn a new language, teach yourself to paint, whatever, it doesn’t need to be vocational, just something that broadens your horizons and keeps you learning.（side project可以帮助你打开自己的眼界，并且让自己不断地学习）

8. If you find yourself thinking any particular technology is the best thing since sliced bread, and it’s somewhere near a top of the Gartner hype-curve, you are probably not seeing the full picture yet. Be critical of your own opinions and look for bias in yourself.（如果你觉得某项技术牛B并且许多地方都在热炒的时候，你需要批判性地看待这个技术。比如DL计算量的问题）

9. Pick projects that where you have some implicit physical or tactical advantage over the competition. Don’t assume that you will do a better job just because you are smarter.（选择对自己有利的项目，而不仅仅是因为这个项目中自己比别人更聪明。 引申一点就是选择项目应该从value出发，而不是是否自己可以应对）

10. In my experience the most telling characteristic of a good company is that its employee’s assume their colleagues are smart people, implicitly trusting their opinions and capabilities until explicitly proven otherwise. If the modus operandi of a company (or worse, a team) is ‘everyone else is an idiot’ look elsewhere.（好的工作氛围应该是相信大家是最好的，而差的就是只觉得自己是最好的）

11. If you’re motivated to do something, try to capitalise on that motivation there and then and enjoy the productivity that comes with it. Motivation is your most precious commodity.（利用好动力）

12. If you find yourself supervising people, always think of their success as your success and work to maximise that. Smart people don’t need to be controlled, they need to be enabled.（好的领导者应该将别人的成功当做自己的成功，enable people not control people。当然如果认为自己牛X别人傻X，那执行起来肯定也是control people）

13. Learn to control your reaction to negative situations. The term ‘well-adjusted’ means exactly that. It’s not an innate skill. Start with email. Never press send if you feel angry or slighted. In tricky situations stick purely to facts and remove all subjective or emotional content. Let the tricky situation diffuse organically. Doing this face to face takes more practice as you need to notice the onset of stress and then cage your reaction, but the rules are the same (stick to facts, avoid emotional language, let it diffuse). （控制自己的情绪，这个对于处理人际关系非常重要，可能是最重要的。当自己情绪失控时记录下的东西，不要发出去，等冷静下来之后，删除所有情绪相关的反馈，只陈述事实部分）

14. If you offend someone always apologies. Always. Even if you are right, it is unlikely your intention was to offend.（不管自己是对是错，如果冒犯到别人就要道歉。即使自己是对的，自己的本意肯定也不希望冒犯别人）

15. Recognise the difference between being politically right and emotionally right. As humans we’re great at creating plausible rationalisations and justifications for our actions, both to ourselves and others. Making such rationalisations is often a ‘sign’ of us covering an emotional mistake. Learn to notice these signs in yourself. Look past them to your moral compass.（我不太理解这里的政治正确和情感正确。我们非常容易为自己的行为找到合理的借口或者解释，来掩盖情感错误）
