#+title: Career Path(职业规划的迷思)

https://zhuanlan.zhihu.com/p/21233881

经过长达十年的观察，我终于意识到大多数工程师想要的是一个完美的线性排序，或者说所谓的 Pecking Order。我的老板们并不关心我写的程序如何，他们只需要根据我的成果就能做出判断，我的基本原则不过是“Get shit done”。但是我的下属们的心态要微妙很多，不少人暗示或者明示我是一个合格的技术领导者——因为我会写代码。作为一个口无遮拦的段子手，我在某个小圈子里面还是颇有一些声望——虽然很多人压根没见过我一行代码。

举一个非常不恰当的例子，我的很多（前）下属真诚地认为，哪怕我只会写 Perl 脚本，只要能写一手好代码，不管市场有没有需求，我走在市场上都是炙手可热。如果我是牛人就应该拿高工资，否则我就是欺上瞒下的骗子。很显然，这和猎头、雇主们想的截然不同，否则我不可能囤积一大堆拒信。

我很早就有了类似的直觉，但是我一直没办法建立一个很好的概念模型。不过，这是社会心理学里面研究烂了的题材。在社会动物中，这种心态是一种很简单的适应性进化，毕竟 Pecking Order 就是最早研究鸟类啄食所归纳出来的。这个结论让我觉得有些难以接受——我们互联网工程师是技术时代的先锋，怎么可能被这些原始的社会性本能所左右？

所以我前面会说，互联网行业很多一线工程师对职业的理解连三岁小孩都不如。三岁小孩是会改变自己信念的，但是很多有信念的人是无法被说服的。如果没有足够好的运气，这样的人多半会受到市场的惩罚。

由于程序员必须转型经理这样的神话流行了好几十年，我很希望让我的下属别走弯路，尽早开始管理相关的积累。我经常试探性地问我的下属是不是想走管理路线，是否想继续专注于技术。然而我得到了反馈几乎总是一致的，大多数一线工程师不想放弃技术，想要一颗红心两手准备。就好像他们担心我在质疑他们的纯洁性一样，他们需要表明自己的原教旨主义立场。我非常理解他们的顾虑，这就像一个手艺人怕丢了自己吃饭的本事一样自然。我以前的老板会很诚实的告诉我，走管理路线会受到组织结构的影响，一个机构里面所需要的管理者是有限的，而且在扁平化潮流中职位只会减少而不会增多，因此职业发展受到了组织的硬性限制。

如果你想要正确的后验分布，最好的办法就是先验分布尽可能准确。跳槽时谈一个好 offer 的充分条件是，你现在就有很好的职位和薪酬待遇。很多一线工程师试图通过一两次跳槽就能转型 CTO 然后顺带发财，我通常会（在心里）建议他们去买彩票。最近几年我参与发放的 offer 很多，我几乎不会考虑 50% 以上的加薪幅度。
