#+title: 成都天府之旅

国庆节没什么事情，想带着小胖出去转转。老婆之前去过一趟成都，对那边的印象非常不错：美食，饮茶，麻将，还有悠闲的生活，所以希望再去一次。但是因为带着小胖去，所以就范围限定在了市区里面。

我想因为范围限定在市区，去哪个地方打车就好了，所以就没想过要到当地租车，也没有带驾驶本。要是带了驾驶本租辆车的话，还可以去附近的都江堰和青城山看看，听本地的大学同学说那里景色非常不错。

-----
Day1: 早上11点左右的飞机，下午大约3点左右到宾馆。宾馆定在宽窄巷子附近，所以晚上就走到西安南路那边看看有什么好吃的馆子。西安北路和西安南路真的是小吃一条街，我们晚上大概7:30左右到那边的，一路上每个馆子都是爆满的，外面有许多人在排队等候。四川美食都是以麻辣为主，那条街上火锅和烤串的店居多，老婆和小胖都不太方便吃，所以最后找了一个看上去能炒川菜的馆子"人民食堂"。说来也巧，当天因为人民食堂停电了，所以把桌子摆到了外面，还有几个桌子上点着蜡烛。我一看觉得人不少，而且搞的还挺有气氛的，觉得很有意思，就选了这家店，第二天再过来才知道是停电了。来了一个"厨王大刀白肉"和"黑豆花"，本来还想再来个"拿手烧肥肠"，可惜已经卖完了。so pitty! 下图是那个店的菜单。

file:images/chengdu-travel-0.jpg file:images/chengdu-travel-1.jpg

-----
Day2: 早上10点左右出发去了杜甫草堂瞻仰一下古人，可惜人太多没有办法进他老人家的茅草屋里面参观，就在外面稍微走了走。出来差不多12点多了，打车跑到春熙路的龙抄手总店。春熙路是成都的CBD，离市中心天府广场很近。总店有三层楼：一楼是散卖的不同窗口有不同口味的抄手，价格合适但是人太多；二楼是套餐人也不少但是比一楼就好多了，一份套餐69，抄手担担面钟水饺就都有了，但是分量很小；三楼是包间应该更贵。带着小胖不太方便去排队买散装的，所以就决定在二楼点套餐了。味道还好，但是不是惊艳的那种。吃完了稍作休息就朝武侯祠和锦里去了，那边藏民还有喇嘛很多，从肤色上看一眼就能分辨出藏民和汉民。快到武侯祠的小路口，车就开不进去了，我们就只好穿过一条小街走到正门口。人人人！锦里就是武侯祠旁边，也是围的水泄不通不通。人太多了，而且天气又热，大众点评看到附近有个评价不错的茶馆，于是就躲进去要了杯竹叶青和苦荞。晚上回去稍作休息，又杀回人民食堂。这这次来电了，多拍了几张照片。后两张是热拌肥肠和川味小炒肉。

file:images/chengdu-travel-2.jpg file:images/chengdu-travel-3.jpg file:images/chengdu-travel-4.jpg file:images/chengdu-travel-5.jpg

我们住的地方离永陵博物馆比较近，那边还有个公园，所以早上吃完饭都会去那里转转。早上公园里面有打太极拳的，也有跳舞的，有打羽毛球的，还有拉二胡练嗓子的，甚至还有坐在亭子里面围圈打牌的（而且还不少）。这个地方是前蜀高祖王建的墓地，后来改名叫做永陵。在博物馆前面有一个石雕，四个半身托起一个石印。这个石印是王建的谥宝，在谥宝上还有一个兔头龙身。在这个谥宝周围有一圈演奏各种乐器的艺妓石雕。

file:images/chengdu-travel-6.jpg file:images/chengdu-travel-7.jpg file:images/chengdu-travel-9.jpg

file:images/chengdu-travel-8.jpg

-----
Day3: 早上去宽窄巷子看了看，还是那么多人，从宽巷子进去没多久，就从窄巷子绕出来了。晚上和zqw约好一起吃个饭，所以下午就没有再去更多的地方，就在附近转了转。成都市中心有许多看上去非常破旧的楼房和商场，看上去应该是很久都没有使用，但是一直没有被拆掉。后来问了同学才知道，那些地方都不太好动，拆掉的话需要花费很多钱，所以政府就没有动而选择在新城区做开发。虽然如此，这些破旧楼房在市中心还是显得非常的奇怪。

file:images/chengdu-travel-10.jpg file:images/chengdu-travel-11.jpg file:images/chengdu-travel-12.jpg

不仅是楼房和商场，居民区里面的楼房看上去也是破旧不堪，墙上都长满了苔藓，很像我印象中90年代时期老家粮食局的房子。

file:images/chengdu-travel-13.jpg file:images/chengdu-travel-14.jpg

晚上zqw请我吃蜀九香火锅。他家正好就在东郊记忆旁边，所以我们晚上正好就来了个夜游音乐广场。东郊记忆这块地，原来苏联在这边建设了许多工厂，都来苏联撤离后这种工厂风格就一直保留下来了，所以可谓记忆。这个地方和北京798很像，里面都是浓浓的金属钢铁气息的艺术作品。一些不知名的歌手也都会选择在这个地方的酒吧里面唱歌。这次和zqw聊天也学习到不少东西，尤其是关于自信和知己知彼这两点。

-----
Day4: 今天没有安排什么活动，晚上和jinyu同学开车去阳平吃了顿全鱼大餐。成都人一般周末和节假日都希望往郊外跑，我猜想这也是为什么成都的汽车保有量这么高，成都交通这么堵吧:). 而且成都人消费习惯都是有点超前消费，所以在汽车上投入都比较大，一辆舒适的好车对郊外游还是相当重要的。我们大约下午3点左右出发，开到城外开进山里，到了那个店差不多快5点了。也就是说，成都人愿意为一顿美食驱车2个小时开到山里，完了后驱车两个小时再开回来... 不过这顿全鱼大餐确实不虚此行，一条5斤的鲟鱼做了7个菜，其中还有两个汤，并且味道非常非常好。[[http://map.baidu.com/?newmap=1&s=inf%26uid%3Ddad991bea8ba52e93b221cc3%26wd%3D%E9%98%B3%E5%B9%B3%E9%B2%9F%E9%B1%BC%E5%BA%84%26all%3D1%26c%3D332&from=alamap&tpl=mapdots][位置]] 是"阳平鲟鱼庄, 彭州其他阳平观后山(加油站对面)", 超赞的。

-----
Day5: 8:35的回程飞机。回来没有像去的时候那么幸运选到了经济舱的第一排，大概是倒数5排的位置。
