#+title: 市井雄心 Cities and Ambition

http://www.paulgraham.com/cities.html

译文: http://article.yeeyan.org/view/11304/9681

PG的文章里面通常有太多难懂的词汇，所以选择还是读中文：） 文章的大致意思就是，每个城市都有一种或者是几种独特的符号和象征，而每个城市里面的人的雄心壮志要想得以施展，那么一定要和这个城市的文化匹配。这个城市要能鼓励你的这种雄心壮志，重视你处的行业以及你所的事情。某些较特殊的行业（比如数学，物理）可以无关乎城市的文化，但是大部分行业包括科技金融行业，和所处的城市关系很大。

-----
不同城市传达出来的信息。


#+BEGIN_QUOTE
伟大的城市吸引有抱负的人。在城市里徜徉时，就能感觉得到。城市在通过几百种方式向你传递着信息：你能做得更多；你应该再努力一点。

这些信息千差万别，令人瞠目。纽约告诉你最重要的是：你要赚更多的钱。当然，也有其他信息 – 你应该更时髦一点；你应该打扮得更帅一点。但是最清楚不过的信息就是：你的钱包得再鼓点。

我喜欢波士顿（或者剑桥）的一点就是这里城市在告诉你：你应当更聪明。你真的需要读那些在你曾经列进的读书计划的书了。

你探究一个城市在发出什么消息时，答案常常会出乎意料。硅谷对聪明脑瓜很是偏爱，它传递的消息却是：你应当更强大。

这和纽约的有所不同。权力在纽约也有作用，不过纽约人有点见钱眼开，即使那是你不费吹灰之力继承来的。而在硅谷，飞来横财除了地产商，没人看得上眼。这里在乎的是你如何影响这个世界的。人们关注拉里和赛奇不是因为他们腰缠万贯，而是这两个家伙控制着Google，而Google影响着我们每一个人。

剑桥就像一个生产想法的城镇，相比之下，纽约是造钱的，硅谷是孵蛋的。

在洛杉矶，出人头地似乎事关重大。跻身于炙手可热的名人榜，或者跟着榜里的朋友一起鸡犬升天都会受到追捧。除此之外，洛杉矶的消息和纽约的就差不多了，健康俊朗在这里更被看重一点。

在华盛顿似乎最重要的是你的圈子。你最想成为一个圈内人。实际上和洛杉矶差不多，你都想冲进那个榜单或者跟榜上有名的人物攀亲。差别就在于这两个榜单的选择标准不同 － 其实也差别不大。

我至今没有看到可作为智慧中心能与剑桥比肩的城市。英国的牛津和剑桥感觉就像伊萨卡岛或者汉诺威：虽然也在发着类似的消息，但是比较微弱。

现在三藩市发出的消息和伯克利类似：你要过得更好。不过要是为数众多的创业公司选择三藩市而非硅谷的话，情况就会变化。在网络泡沫的年代，这种近似奢侈的选择就像花大钱装修办公室一样是失败的前兆。到现在我还是觉着创业地点选在三藩市不是个好主意。但是如果很多好的创业公司都这么做，就不再是个奢侈的标志了，因为硅谷的吸引力就将转移到那里去了。

巴黎曾经是一个伟大的知识分子聚集的中心。如果你1300年去的话，它也许和剑桥现在发出的信息一样。但是去年我在那里住了一阵子，住在那里的人们的雄心已经与智慧无关了。巴黎现在发出的消息是：做事要有风格。我打心底也赞同这个观点。我旅居的城市里，巴黎是唯一一个人们真心在乎艺术的城市。在美国，只有阔佬们才买原画，即使那些久经世故的老手最多也只能冲着画家的名头去买画的。但是在巴黎，你黄昏时分透过玻璃窗，会看到人们真的在乎画作画的好不好。可谓巴黎一瞥，美不胜收。

从很多城市里我还听到另外一个消息：在伦敦你仍能依稀听见“你得象个贵族”这样的消息。如果你刻意去倾听，在巴黎，纽约和波士顿也是能听到的。但是这个消息在哪里都很微弱。也许100年前会很强烈，而现在湮没在其他声音里了，我要抽丝剥茧的才能寻得半点蛛丝马迹。
#+END_QUOTE

-----
城市的影响力有多大呢？

#+BEGIN_QUOTE
一个城市发出什么消息有多大的影响呢？经验告诉我们：很大。你也许认为如果自己要是有一根钢筋般的神经支撑着自己去做大事，就可以忽视环境的影响 – 生活地点的不同对你充其量就只有区区百分之几的影响。然而反观历史，似乎影响颇大。在每个时代里，大多数做出大事的人都扎堆在少数几个地方。

你可以从我以前写的文章里看到城市是如何有强大的影响力的：比如生活在米兰的达芬奇。实际上每个你有所耳闻的十五世纪的意大利画家都住在佛罗伦萨，尽管米兰的城市规模毫不逊色。既然米兰人的天分也并不差，那么我们可以假定在米兰也诞生了一位和达芬奇同样天资聪颖的小家伙。可是他后来呢？

如果和达芬奇一样厉害的家伙都被环境埋没了，你觉得自己又有多大胜算呢？

我是不行。即使我相当顽固，我也不会去争这个“人定胜天”。我试图去利用环境 – 我着实为住在哪里费了不少心思。
#+END_QUOTE

-----
城市会不断地给你反馈。

#+BEGIN_QUOTE
无论你如何坚定不移，周围的人对你的影响也是不可忽视的。虽然没到沦为城市意志的傀儡的地步，但是身边如果没有一个志同道合的人，难免有点沮丧。

环境的积极影响和消极影响的程度是不同的，就和收入和支出的差别类似。绝大多数人对支出比较反感：为了不损失一美元他们竭力工作，而要是为了挣一美元，他们就没有那么卖力了。同样，尽管很多人意志坚强，不会入乡随俗人云亦云，但是周围的人要是对你心中的事业不屑一顾，能坚持去做的人就不多了。

由于志气之间一定程度上有点互斥，而推崇多个又难免费神，所以每个城市都倾向于一种雄心壮志。剑桥人才济济不只是聪明人扎堆的结果，更重要的是在那边人们不在乎别的。纽约和湾区的教授走路都抬不起头，直到有一天弄到了点风投或者开了家小公司，腰杆这才稍稍直起来一点。
#+END_QUOTE

-----
某些行业对于城市文化的依赖程度是不同的

#+BEGIN_QUOTE
是不是你胸怀大志就一定要去一个伟大的城市居住呢？非也；所有的伟大的城市都激发着某种雄心，但是它们并不是唯一的地方。一些工作，你只要一帮聪明的同事一起打拼就够了。

城市能够提供听众，选择同行。而这些对于像数学或者物理这种学科不那么重要 – 除了你的同事，没人关心你的工作，而是否优秀也很好辨别，管理委员会就能很好的招到聪明人过来。在这些领域你需要的只是一个办公室，几个不错的同事。地点就无所谓了 – 拉莫斯，新墨西哥，哪儿都行。

在艺术，写作或者科技这类领域里，大环境的影响就不可忽视了。这里，顶尖高手并不扎堆在几所好大学或者实验室里 – 一方面是因为天才很难鉴别，另一方面他们能赚到钱，懒得去大学里教书或者争取研究资金。在这样鱼龙混杂的领域里，身居一个伟大的城市就会收益无穷：你需要来自关心你的事业的人们的鼓励；因为你自己得去找些志同道合的家伙来切磋，为了避免大海捞针，就要学会借城市的吸引力的东风。

你不必在一个伟大城市终老就可撷取其精华。至关重要的几年集中在你的青年和中年时期。很明显，你不必非得在这样的城市里长大，你也不必去其中的一所大学求学。对于大多数大学生来说，有几千人的校园般的世界就够大了。而在大学里你还不必触及最难的事情 － 发现并解决新问题。

当你开始面对这些棘手的问题时，身处一个四周都是同党的令人振奋的环境就可令你受益匪浅。一旦发现并找到了想要的东西，如果你想，就可以离开。在印象派画家的圈子里，这个现象很普遍：他们都不在法国出生（毕加索在加勒比出生），也都不在法国去世。但是成就他们的却是那些在法国一起待过的时光。
#+END_QUOTE

-----
年轻的时候应该多在几个城市居住，去聆听这个城市传递出的信息，观察自己是否适合这个城市。除非你真的居住过一段时间，否则你不一定能感受到它传递的信息。

#+BEGIN_QUOTE
不是所有城市都有话要对你说。只有那些成为远大理想聚集中心的地方才会。除非你住在那里，否则要辨别出城市到底发出什么样的消息很难。我能说出纽约，剑桥和硅谷的消息是因为我在每个地方都住过几年。华盛顿和洛杉矶似乎也在说点什么，不过我在那里都只是短暂停留，甄别不出他们的呢喃。

除非你已经确定了要做什么以及哪里是事业的中心，否则你年轻时最好多挪几次窝。不在一个城市生活，很难辨别出来它发出什么消息，甚至你都很难发现它是否在发消息。而且你得到的信息经常是错的：我25岁时在佛罗伦萨待了一阵子，我原以为这里是个艺术圣殿，结果我来晚了，晚了450年。

即使一个城市是一个激荡着雄心的地方，在听到它的声音前你也不能确信你和它是否能产生共鸣。当我搬到纽约住时，一开始就激动的不得了。这地方真不错。我花了不少时间才意识到我和他们不是同路人。我一直在纽约找剑桥 － 还真的找到了，在非商业区，不远，一小时的飞机就到了。

有些人16岁就知道自己一生的目标，但对于绝大多数有雄心的年轻人，领悟到“天生我才必有用”要比“天生我才有嘛用”早一点。他们知道得做点不平凡的事情。只是还没确定是要做一个摇滚明星还是脑外科医生。这也没什么错。只是如果你壮志在胸，就得反复试验去找到去哪里生活。你要是在一个城市过得很自在，有找到家的感觉，那么倾听它在诉说什么，也许这就是你的志向所在了。
#+END_QUOTE
