#+title: 香农传(A Mind at Play)

https://book.douban.com/subject/30320103/

笔记本导出
香农传（信息论创始人，数字通信奠基者；与艾伦·图灵齐名的科学巨人；没有香农，就没有互联网）
吉米·索尼; 罗伯·古德曼

** 第1章 小镇男孩的科学基因

事后反思自己所接受的教育，香农说他对数学的兴趣，除了源自与姐姐玩的数学游戏，还有另一个简单的原因，数学对于他来说很容易。“我认为人们趋向于选择自己能够得心应手的工作。”香农后来对一名采访者说道。他比照片里的其他孩子早一年毕业：克劳德用 3年读完了高中。他不是班上学习最好的学生，当地报纸在 1932年的一篇报道中写道，他所在的高中有 3名学生拿到了全 A的好成绩，而香农并不在其中。他喜爱科学，讨厌事实。或者说，他讨厌那种没有规则、不能抽象出方法的事实。化学尤其考验了他的耐心。“它对于我来说很乏味，”他在给科学老师的信里写道，“太多独立的现象，而合我心意的通则太少了。”

我们中的大多数人，包括香农在内，在选择偶像时并不像我们想的那样，有很高的要求。在全宇宙所有可能成为英雄的人里，我们选定了那些时常能够让我们联想到自身的人。可能香农和他的远房表亲爱迪生的例子正是如此，他刚离开美国密歇根州不过数年，就发现了彼此的亲属关系。得知自己的偶像是自己家族的成员是一件非常幸运的事情，而香农的运气也确实比其他大多数人都要好。

** 第2章 安娜堡的大学生活

安娜堡位于盖洛德东南 195英里处，是一座满布陡峭山丘与山谷的城市，缓慢流淌的休伦河冲击着山体，形成了大量泥泞的浅滩和低矮的坡地。受休伦河制约，安娜堡发展成为一座工业城镇——沿岸遍布的锯木厂和面粉厂，推动了当地经济的发展。大量移民涌入这里，他们主要来自德国，也有希腊人、意大利人、俄国人和波兰人。不同种族的差异日渐明显，而教会又加深了社会地位与宗族的联系。 20世纪初，安娜堡约一半的人是一代移民或者二代移民。

密歇根大学也有着这座城市沉着的自信。“我一点儿也不气馁”，大学校长 A. G.鲁思文说道，“我必须承认，削减资源使我能够在组织中做出一些变革，我认为，从长远来看，这大有裨益。”然而，克劳德·香农入学的时候已是 1932年秋，这所大学坚定的积极态度已经跌到谷底。金融危机迫使安娜堡最大的雇主、经济引擎密歇根大学不再扩招、停止长期规划的基建项目，并且将教职工收入削减了 10%。

虽然双学位十分普遍，香农的这种犹豫不决（他从来没有完全做出过选择）对他后来的工作至关重要。有些喜爱建筑的人可能只乐于拿工程学位，而另一些偏爱理论的人可能满足于只学习数学。香农倾向于数学和机械两者，难以抉择，（双学位）使得他在两个领域都得到了学术训练，而不是在两方面相互怀疑。实际上，有些工程师指责数学是在盲目追寻抽象的事物，而有些数学家又控诉工程师们只讲求实用。香农的天资和偏好，使得他没有对这两门学科产生任何教条与偏颇的观点。

** 第3章 机械大脑

1924年，布什和他的学生们在福特积分器的基础上对其做了改进，发明了一种新的积分机器。 1928年，为寻找稳定的电网解决方案，他们已经能够在 50平方英尺的实验室里模拟 200英里范围的输电线路了。同年，他们开始设计一款通用的微分分析仪。 3年后，他们花费了 25000美元制造了这种机器。它是一个如房间般大小的大脑，这种金属做的计算机为了解决问题可以日夜运转，直至问题解决才停下来。要测量地球磁场对宇宙射线的影响的问题，需要齿轮机器日夜运转 30周，但当它完成计算后我们可以发现，微分分析仪用强力解决的复杂方程是人力所望尘莫及的。实际上，当时布什的实验室拥有将工业难题转化为基本物理学问题的计算能力。

数学无限复杂，但是范内瓦·布什的割草机可能是这个大型计算器的远祖。微分分析仪书写了科学史的一部分，“仍然以机械运转的方式解释数学，仍然依赖于专业机械化的滚轮–圆盘积分器，仍然以曲线形式绘制答案。微分方程和等高线意味着，布什的计算机在很大程度上是其早期地形追踪器的衍生物”。这就是数字革命前的计算机，它是一种在解决方程式的过程中实实在在地运转着的机器。只要机器在运转塑造原子形状的方程式，从意义的角度来说，它就是一个巨大的原子；只要机器在运转为星星供给能量的方程式，它就是一颗微型星星。“这是一种模拟机器，”布什说，“当某人遇到一个难题，比如要知道一座待建的桥在疾风中摇晃的程度，他可以通过结合机械或电气元素来模拟桥的实际情况，它们遵循同样的微分方程。”对于物理学家或工程师来说，这两种系统都遵循相同的方程式，它们具有同质性，或者至少可以做类比。但说到底，是我们在“模拟”。数字显示电子表与太阳大相径庭，指针式电子表是对围绕表盘的电路阴影的记忆。

** 第4章 麻省理工学院里的开关

直到 1935年，也就是香农到坎布里奇的前一年，微分分析仪已经达到了它的极限。虽然此机械设计精巧，但每个新方程都必须先使之解构再重组。布什和他的团队发明的机器并不是单一的机器，而是一系列巨大的机器，它们需要为每类问题重建，在每种方案中分解。为了实现它的多功能性，他们需要以降低效率为代价。而因为分析仪的全部使命是使计算更有效率，使之至少能够在理论层面被人工计算出来，需要不断重复的瓶颈使得它存在的价值大打折扣。为了应对这种情况，布什想要发明一种分析仪，它可以在运转的过程中对自身进行基础性重组。它装有自动控制器，能够使自身不间断地从一个方程式自动转到下一个方程式，或者甚至能够同时解决多种相互作用的方程式。它装了开关来代替螺丝刀。在经济大萧条时期，麻省理工学院的经费预算远远不能满足布什的雄心，但他仍然能从洛克菲勒基金会募集到 265000美元私人捐款来研发新一代计算机。同时，他将克劳德·香农带进麻省理工学院，来帮助他开展新的研究。

从逻辑到符号再到电路的飞跃，香农依然欣喜地记得：“我觉得这比生活中的任何其他事情都有趣。”这很可能是一种古怪而富有学究气的乐趣，但他当时只是一个 21岁的年轻人，他满心激动于从开关盒子和继电器中看到了别人没有看出来的东西。剩下的就都是细节了，在未来的岁月中，他似乎忘记了杰出的科学家仍然需要发表论文。他漫无目的地孕育出数年来最有价值的成果，最终在阁楼里塞满笔记和半成品论文，并在格子纸上记录下各种“颇具价值的问题”。但是现在，他雄心勃勃却尚未完成证明，他完全沉浸在工作里。

** 第5章 与众不同的年轻人

比邻这种佳作，香农的论文在深度与性质上都与众不同。他一生喜爱捣鼓小发明，即使没有必要，他也会亲自尝试。但与其他发明家不同的是，他拥有一套探寻事物本质的方法。他喜欢研究手中的物件，从中提炼出自己的方法。对于他而言，开关不仅是开关，而且是一种数学表征。世界上有无数魔术师与独轮车骑手，但是几乎没有人像香农一样，非要将这些活动转化为方程式。最重要的是，他会从所有的人类交流中抽象出每条信息所蕴含的共同结构与形式。在这些努力中，他最引人注目的不是可定量的马力而是对模型制造的掌握，即将大问题转化为核心能力。在摒弃技术和模糊性，寻找人类制造仅代表数学逻辑方法的过程中，香农 21岁时的工作为他后来所有的工作开启了一扇窗。

更重要的是，布什执着地相信，专业化会导致天才陨落。“在那些专业细化趋势日趋明显的日子里，我们需要谨记，博大精深的可能性并未随达·芬奇，甚至本杰明·富兰克林的去世而消失，”布什在麻省理工学院的一次演讲中说道，“使教师这个职业印象深刻的，必然是年轻人一种愈加明显的趋势，也就是他们发达的思维只对科学的冰山一角感兴趣，而忽略了其他部分。假如一位有才气且富有创造力的青年坚持把自己局限于现代修道院式的牢笼里，这将是一件非常不幸的事情。”

** 第6章 放弃遗传学研究

伯克斯和布什本人，以及他们对香农成果的赞誉，坦率地评估了它产生影响的概率。伯克斯在给麻省理工学院的信中写道：“很少有科学家能创造性地运用由别人发明的全新的、非常规的方法，至少在我们这一代非常难。”在表扬他的学生的同时，布什也对香农提出了忠告：“我怀疑你发表的成果是否能影响其他学者，让他们继续使用你的方法进行后续研究，因为在这个领域中很少有人会这样做。”香农方法的独特性，即他发明过程中的孤立性，导致这种方法很容易被忽视，或者充其量它也就是使香农的事业被判定为遭遇挫折，因为这位外行遗传学家试图向怀疑论者兜售独特的方法。作为一名已经成名的最富才华的年轻工程师，这样的发展前景并不令人看好，或者是毫无必要的。

** 第7章 贝尔实验室中一流的应用数学家

当代，众所周知，具备高水平数学能力（量化能力）的人能够找到高收入的工作。但现实并非总是如此，尤其对于 20世纪初期的数学精英们来说。当时数学界所认定的最高水平在实际应用中几乎毫无作用。抽象问题的解决方法受到追捧，因而数学家们都在寻找深奥谜题的解决方法，如黎曼猜想、庞加莱猜想、柯拉兹猜想以及费马大定理。这些都是数学界最伟大的谜题，而几十年过去了，它们仍旧无解的情况使数学家们跃跃欲试。它们被认真对待，如果有任何人思考这些问题，无论解决方法是否有实际目标或应用价值，它们都变成了事后的参照。弗赖伊自己是一名数学博士，他比任何人都懂得这一点——“典型的数学家”：他并不会从事工业项目的研发。他是梦想家，对能赚到的物或钱并不感兴趣。他是完美主义者，不愿意妥协。他理想化到不切实际的程度。他拥有如此广阔的视野，却不能将视线聚焦于眼前。这一切导致许多研究生除了拥有对数学的热爱，在解题方法上受到了良好的训练外，并没有其他用处。那么，一个工业实验室对数学家的价值就好像一条鱼对自行车的价值，除非……弗赖伊的直觉是，并非所有的数学家都想写论文、追求终身教职。他也猜测到，合适的环境能够发挥他们的优势，使他们投身实际的事务中，解决“日常问题”，进行“具体的研发”。同时，他也是少数一群促使这种情况发生的人之一，想要将“工业数学家”培育成为全新的思想家。

** 第9章 火力控制研究

当香农考虑教授一门艰深的必修课的时候，韦弗十分欣赏。香农会持续攻克数学难题或研究问题，直到产生思想的火花为止，但韦弗不具备这样的特质。当深入地反思自己的优缺点时，韦弗说：“我拥有良好的吸纳信息的能力，掌握了组织活动的诀窍，具备与人共事的能力，乐于为人答疑，对激发我的想法充满热情。但是我缺乏一位优秀的研究员所需要的离奇而精彩的创造性灵感。因此，我意识到，要想成为一名数学教授，我的发展是会受到局限的。”虽然有瓶颈，但韦弗也是一位非同寻常的思考者，他感兴趣的领域涉及方方面面，他在工程学、数学、机械、翻译、生物、自然科学和概率学方面都有论述和研究。但与许多他的同事不同的是，他相信科学与数学之外的世界，他避免了这一领域以及这些学者普遍存在的与外界隔绝的生活状态。“不要高估科学，不要认为科学就是一切，”他在 1966年的一次演讲中告诫学生，“不要完全沉浸在科学里，这里没有人能在未来的 7天里只做研究不读诗书。我希望这个房间里没有人在未来的 7天里不听音乐——好音乐，现代音乐，某种音乐。”

** 第12章 与图灵的友谊

他们的谈话没有被记录下来，但是我们都知道他们所回避的话题。“我们一点儿也没谈到密码学……我认为在这方面我们一个字都没有交流过。”香农解释说。当被问及是否知道图灵的工作内容时，香农说自己只了解了大概：“肯定不知道具体细节。我知道或者能够猜测到他在做哪些工作……但我不了解恩尼格玛密码机……我不知道它是什么，也不知道他是一个重要角色。”采访者进一步追问，香农对密码学满怀激情、经验丰富，他为什么没有进一步探索图灵机。香农的回答言简意赅：“在战争时期人们不会问很多问题。”

由于竞争系统、方式和个性不同，英美两国长久以来都对对方持怀疑态度。他们耗尽耐心，且自我膨胀。在某种程度上，英美之间的冲突是因为两国的战争机制有本质差别，以及他们之间的“不完全联盟”。在扩大军事用品的工业生产方面，无论是在规模上还是速度上，英国都赶不上美国。图灵直观地感受到了这些，在某种程度上，与图灵对美国人脑力的敬佩有限相反的是，图灵对美国人体力的尊重。例如，在参观过海军部队之后，他这样写道：“当谈论到与密码相关的事情时，美国人的话很不可信，对此我现在深信不疑。但是我认为，他们的密码装置值得好好利用。”这种不信任是相互的。比如，当英国人对密码破解取得成就时，他们对美国人也是保密的。图灵也不清楚哪些信息可以对美国人讲，哪些不能说。由于图灵已经给美国人留下了傲慢无礼、令人不快的印象，所以在任务不明朗、不确定的情况下，他不愿意逢迎美国人。况且，他也不是天生的外交官，所以他不擅长处理这类问题。

两人谈论了图灵在编程上所做的工作，尽管 10年过去了，香农依然记得图灵的一项发明：我问他在干什么，他说在研究如何更好地得到电脑的反馈，以便了解电脑内部正在发生什么。那时他已经发明了这个神奇的指令。那些天，他们一直在研究各种指令，想从中找到最合适的一个。我问他，这个神奇的指令是什么？他说，这个指令就是给“警笛”（ hooter）添加一个脉冲，给它安一个脉搏。我来解释一下，“ hooter”在英国指的是警笛，添加脉冲意味着掌握了它的脉搏。这个疯狂的指令好在哪里？可以这么说，如果将指令添加到某回路中，那么执行指令时会产生脉冲，你能听到的频率就等同于指令在回路中流转的时间。依此类推，你可以将指令放到更大的回路中。你能听到这一切，全是“嘘嘘嘘嘘嘘嘘”（ boo boo boo boo boo boo）的声音。按照图灵的说法，你很快能听懂这些声音，然后能知道回路中是否发生拖延或其他问题，而且能了解其运行情况，这些在以前都是无从知晓的。

** 第13章 贝尔实验室的三人组

数学的古老艺术……并不崇尚速度，而更重视耐心、技巧，且更重要的是协作和即兴创作的天赋，这也是优秀爵士乐的特点。——加雷斯·库克

** 第16章 信息论炸弹

信息到底衡量了什么？它衡量了我们所克服的不确定性。它衡量了我们学习新事物的可能性，或者更具体地说，当一件事物承载了关于其他事物的信息（正如计数器能够告诉我们一个物理量，或一本书能够告诉我们人生），它所涵盖的信息数量反映了未知情况的减少。能够解析最大程度的不确定性的消息，即以最公平的方式从最广泛的符号集合中选择出的包含最丰富的信息。但当一切都充满确定性的时候，并不能产生信息，因为没有什么可以传达。“你是否发誓你所说的都是事实，全部的事实，只有事实？”在法庭宣誓的历史上，回答“是的”有多少次？因为能够想象到的只有一个答案，这个答案几乎不能为我们提供任何新的信息，我们早在宣誓人回答之前就能猜测到他们的答案。在大多数的人类仪式中，在一切我们被预先安排好预期答复的场合（比如，你是否接受这个男人？……），情况大抵相同。当我们将意义与信息分离开，我们会发现一些最有意义的话，它们也正是提供最少信息的话语。

当他的近似文本变得越来越像英文，它们也就变得越来越冗余。倘若这种冗余超出我们检查自由与否的规则，这也是由相互交流的实际情况所决定的。每种人类语言都高度冗余。根据信息论专家冷静的观点，我们所说的大部分内容，无论是惯例还是语法，乃至习惯，可能都没有实际意义。在香农的信息论中，他认为世界上英语的文本量在毫不影响信息内容的情况下，可以减半。他说：“当我们书写英文的时候，写下的一半词语都受到语言结构的限制，而另一半则是自由选择的结果。”后来，他对冗余成分的预估上升到 80%，只有 20%的单词承载了实际信息。

** 第18章 杜博的批评

更接近我们时代的 20世纪的数学家 G. H.哈代曾写过有关什么是纯数学的初稿。《一个数学家的辩白》是“数学本身的宣言”，它有针对性地从苏格拉底面对资本的论点中借鉴了标题。对于哈代来说，优雅是数学本身的目的。他坚持认为：“美是第一重考验，丑陋的数学在世界上没有永恒的位置。”那么，数学家就不应当是单纯解决实际问题的人。他应当“像画家或者诗人一样”，是一种模式的缔造者。倘若他的模式比其他人的更持久，那是因为这些模式是应运想法而生的。相比之下，普通的应用数学是“无趣”、“丑陋”、“微不足道”和“最基本的”。

** 第19章 维纳的控制论

从纯粹的专业角度来说，高压式的教育带来了回报。维纳 11岁的时候已经读完了高中课程。 3年之后，在他 14岁的时候，维纳获得了塔夫茨大学的数学学位。从那之后，他在哈佛大学学习动物学，又在康纳尔大学学习哲学，最后回到哈佛大学拿到了数学逻辑学博士学位。那一年，他年仅 17岁。他进入了数学的精英阶层，而他父亲期望儿子能实现的那种生活，也由此开始了。

然而， 20世纪五六十年代，香农和维纳都更谨慎。两人都没有争论对方的观点，虽然他们常常参与同一个会议，在同样的期刊上发表文章，却并没有出现两者公然相互攻击的情况。但是到 20世纪 80年代，香农似乎得出了维纳并没有完全理解他的研究的结论：“当我与诺伯特交谈的时候，如在 50年代，我感到他一直不明白我在说什么。”在另一次采访中，香农则更直率：“我不认为维纳与信息论有什么关系。他对我的观点并没有产生重要的影响，虽然我一度借鉴了他的用语。”鉴于香农一贯缺乏对这类交锋的兴趣，那些声明是很有说服力的。但在大多数情况下，他总是将争取声誉的行为留待他人。

香农给人的印象是一名无忧无虑的学者，是一名对自身的智力和声誉有着足够的自信，从而可以将他人的意见撇在一边的人。维纳的观点和贡献确实重要，但这不是因为香农担心谁能够或者谁不能够赢得声望。香农更关心的是他们的争论对信息论本身的实质影响，而非宣称信息论“所有权”的机会。说到底，声誉并没有精确性重要。

** 第20章 终身伴侣

他的另一名同事罗伯特·加拉格尔进一步说道：“他有不可思议的洞察力，能够看透事物本身。他会说‘这样的情况应该是真的’，而且，通常他说的都对……倘若没有卓越的直觉，你就不可能开发出完整的新领域。”这种直觉带来的困难在于，他会先得出解决方案，之后才去完善细节和中间环节。香农和直觉精准的前辈大师们一样，并不情愿去展示他的研究。于是贝蒂就利用自己数学上的优势，成为他的记录员，也成为他许多思想的第一读者。正如她所说的，她成为他独特的合作伙伴，因为这个内向的人“不愿意背离他的行为方式，与他人合作”。她会记下他的口述内容，并加以完善和编辑，添加历史文献引注。在后来的日子里，当香农忘记数学论文中这样或那样的文献的时候，她会介入并提醒他。

** 第21章 信息狂热

罗伯特·加拉格尔观察到香农应对这一问题的方式：“香农是一个非常温和的人，他认为每个人都有权坚持自己的道路。倘若某些人在谈话中说出了非常愚蠢的观点，香农也有办法使之听起来合理而不会让那个人显得愚蠢。”考虑到他一贯克制的习惯，《潮流》这篇声明有力地表明了他的心声。他受到感染并写下了这篇文章，以显示自己对信息论使用和滥用的真实而深层次的忧虑，同时他也担心，他并没有孕育出一个全新的科学领域，而只是膨胀了投机的泡沫。
第22章 服务于美国国家安全

香农有理由保持戒备，他接触过这个国家的高度机密和制度，并与美国国家安全机制的创始人及相关文本保持联系。他既明白这份工作的重要性，也知道保持特权信息秘密性的需求。这可不是无聊的闲话。香农的顾问同事约翰·冯·诺依曼，临终前在沃尔特·里德陆军医院里被穿着制服的军事人员日夜监管。尽管冯·诺依曼的思想令人印象深刻，但他也不能免于被外部渗透的可能，或者政府担心这种情况发生。还能有什么时候能比他在接受医学治疗、迷糊不清时，更容易成为被渗透从而套取宝贵的国家机密，更好的时机呢？

** 第23章 人造机器

香农曾经说过：“我认为科学史已经表明，宝贵的成果往往来源于单纯的兴趣。”极端的兴趣可能会导致不求甚解的态度，倾向于尝试一切却又没有任何收获，但是香农的好奇心却不是这样的。他是那种，通常能自己发现问题，然后自己构建出合理答案的人。机器老鼠能够通过迷宫吗？自己造一个，来找到答案。机器能够自动关闭吗？自己造一个，训练它自己终止运行。其他人称为兴趣的东西，他会当作试验，通过简化问题来进行测试，建造模型将难题精炼到最简形式。他深信机器化的未来，迫切地希望探索它的边界，甚至愿意忍受某种程度的荒谬性来使之达成。当他写信给记者的时候，他正全神贯注于“大规模电子计算机的可能功能及其应用”。鉴于那样的未来（也就是我们的现在），他发明机器不单纯是出于业余爱好，而且是用试验进行证明的。

事实上，当涉及人类优于机器的时候，“思维是人类拿来抵抗的最后一件东西”。虽然香农没有预料到，在他的有生之年，电脑能够通过著名的无限制的图灵测试，无差别地模拟人类，但是 1984年，他的确提出了一套更零散的人工智能目标。根据他的预测，到 2001年，计算机科学家可能希望创造出打败世界冠军的象棋程序，写出被《纽约客》认可的诗文的诗歌程序，能够证明难以捉摸的黎曼假设的数学程序，以及“最重要的”，收益超过 50%的选股程序。他有一半都说对了， 1997年，即香农去世的 4年前，计算机的确打败了世界象棋冠军，电脑也确实管理着世界上大部分的股票交易。

然而，在香农为未来机器厌恶人类而欢欣鼓舞的时候，也有些人充满忧虑。有人写道：“支持人工智能的人是不会满足的。”香农半开玩笑地说道，一旦机器打败了我们的大师，写出了我们的诗歌，完成了我们的数学证明，管理了我们的财产，我们就需要做好“灭绝”的准备。“这些目标可能意味着逐步淘汰愚蠢的、熵增加的、好战的人类，转而支持更合乎逻辑的、节约能源的、友善的物种，即计算机。”

** 第26章 香农教授

在一定程度上，贝尔实验室位于新泽西州的郊区，这本身就是一个复杂的因素。“贝尔实验室的隐避、独立，既有优点也有缺点。他阻碍了很多浪费时间的访客，但这也导致许多有意思的会面不能进行。外国学者通常只会在贝尔实验室待一天，却能在麻省理工学院待半年。这对于交流思想而言，是非常好的机会。”香农承认，贝尔实验室的学术水平与麻省理工学院相当，甚至超过了麻省理工学院。但最后：“在我看来，学术生活的自由性是其最重要的特征。长时间的假期十分诱人，这也是工作中的一种自由感。”这两个机构“大体相当”。这意味着并没有决定性因素导致香农选择了麻省理工学院，只是香农对在一家机构工作了超过 15年，产生了某种不安全感。香农写道：“我在贝尔实验室工作了 15年，发现自己有点状态欠佳，不再能萌生新的思想，而换一个环境、换一帮同事对于我来说是一种刺激。”

不过，香农与贝尔实验室的联系实在太过紧密，直到最后，贝尔实验室也没能与他断绝所有联系，所以香农的名字一直在工资单上。贝尔实验室主席比尔·贝克之后对亨利·波拉克说：“香农是贝尔实验室众所周知的伟大人物之一，我是不会让他陷入贫穷的。”波拉克后来开玩笑说，这符合贝尔实验室的精神：“贝尔实验室有两种研究员，有些人因为过去所为得到回报，而另一些人因为其将要做的事得到报酬，但没有人因为现在的所作所为得到收入。”可能出于对香农再回贝尔实验室的期望，他的办公室被保留了下来，名牌也一直镶嵌在紧闭的房门上。

回想起来，香农愉快地总结了自己这些没用的发明：“我总是想单纯地追寻我的兴趣，而不考虑经济价值或者对世界的贡献。我在毫无用途的事情上花费了很多时间。”很明显，在他看来，他对信息的兴趣和对独轮车的兴趣并没有差别，它们是同一游戏中不同的步法而已。数十年后，罗伯特·加拉格尔评论了香农的古怪思想，这一评论也符合当时许多领军人物的观点：“这些都是正常、杰出的科学家不会去做的事情！”加拉格尔是香农的支持者，这一充满感情的评论也只是模拟了贬低者的态度，但不难想象，香农同时代充满怀疑精神的人，是如何猜想这位贝尔实验室的传奇人物的。毕竟，他来到麻省理工学院时被赋予了很高的期望，他被授予名誉主席，终身教职，以及数学和工程学两个系的教授职位。香农以前的学生特伦查德·莫尔说：“他非常受欢迎。他将成为带领电气工程系走向未来信息论的领军人物。”

** 第28章 发明家的天堂

索普写道，比这些发明更令他印象深刻的是这位主人“看出”难题解决方法的杰出能力，而非通过无休止的工作来强行试验。“香农似乎是用‘想法’而不是文字或者公式去思考。他遇到新难题时就像雕刻家摆弄石块，香农的想法将障碍物逐一凿去，直到呈现出近似解决方案的图像，然后他会继续用更多想法使之精细化。”

** 第30章 京都奖

我不知道日本如何教授历史，但是我在美国读大学的时候，大部分时间被花在学习政治领袖和战争上，包括恺撒、拿破仑和希特勒。我认为这是非常错误的。历史上重要的人物与事件应当是思想家与发明家，像达尔文、牛顿、贝多芬这样的人，他们的成就持续产生着积极的影响。他特别提到了一类创新：科学探索“本身就是奇妙的成就，但是倘若没有工程师与发明家，即像爱迪生、贝尔、马可尼这群人，从中努力，它们并不会对普通人的生活带来影响”。香农对 20世纪的进步感到惊叹，在这之前，“人们与几世纪之前的人一样，主要过着农耕生活，很少迁移，也没有远距离的通信”。并没有经过很多年，这种人类生活方式就经历了彻底的变革。他认为，这都要归功于工程师的工作。

** 第32章 余震

伟大的俄罗斯数学家安德雷·柯尔莫哥洛夫在 1963年这样说道：在我们的时代，当人类的知识变得越来越专业化，克劳德·香农却是一个例外，他是一名能够将深刻抽象的数学思想与对关键技术问题广泛而具体的理解结合在一起的科学家。他能够被称作过去几十年来最伟大的一位数学家与最伟大的工程师。这种看似矛盾的中庸也延伸至他的生活方式。他本可以选择闻名全球，但他宁愿保持默默无闻的状态。他写出了开创性的论文，但之后又不满足于它们的现状，无限期地搁浅了这些论文以迎合自己更急切的好奇心。虽然他通过研究市场的动向和创业的潜力来充实自己，但他过着非常低调的生活。他到达了象牙塔的顶端，所有荣誉和专业地位都证明了这一点，而他仍可以毫不羞怯地玩孩子们玩的游戏，写关于杂技的短文。他有强烈的好奇心，但有时又不带歉意地懒惰。他是自己所在领域最高产、最受尊重的思想者，但他又表现出随时可以放弃全身心的投入，转而在他的发明室里敲敲打打、摆弄小发明的姿态。

重要的是，除了勇气，他非常独立，甚至从某种角度来看，他缺乏自我。这便是香农的基本原则，是一切其他品质的基础。香农几乎放弃了每一次自抬身价的机会。数学家们担心把时间花在了没有足够难度的问题上，他们嘲弄地将之称作“游戏问题”。然而，克劳德·香农却在公众场合研究真实的玩具！他一次又一次地研究了其他人可能会觉得尴尬的项目，从事看起来微不足道的问题的研究，并成功地从这些问题中取得突破。他试图建造出能够超越自身的大脑，这需要非常强大的自信。就此而言，他曾试图建造一种机器，它唯一的功能就是会自我终止运行。

至少对于我来说，这似乎并不是香农所乐见的。香农是一名工程师，他比大部分人都更习惯于实用性，但是他被“知识本身是宝贵的”和“探索它们蕴含着的无限乐趣”的想法所深深吸引。正如他自己所说的：“我更感兴趣的是，一个问题是否令人兴奋，而非它能够做些什么。”关于如何正确看待香农对这些奇怪机器的热爱以及他广泛的喜好，一名和他同时代的人，对这位世界顶尖的数学家热爱骑独轮车的癖好这样评论道：“他的兴趣不在于成立一家公司生产独轮车，而在于找出是什么使独轮车如此有趣，并对此进行更深入的研究。”他的方式激励了一代人创造出非同寻常的发明。想象鲍勃·加拉格尔的话，他描述了和香农同时代的、信息论研究者的心态：当我还是一名麻省理工学院研究生的时候，香农解谜式的研究风格风头正盛。到处都是追求知识的人。每个人都想理解数学、物理学和通信科学。开公司、成为百万富翁、开发真正的应用都是次要的。大家确实有将这一理论拉近现实的兴趣，但这仍是基于理论的。我们的榜样都是放松的、好奇的、有时间进行反思的人。
