#+title: Codehaus宣言

https://github.com/oldratlee/translations/blob/master/codehaus-manifesto/README.md


Codehaus Manifesto

- The Codehaus recognizes that some committers, based upon metrics, longevity and appointed management, have greater say on a project than others. （谁贡献的多，谁说了算）
- The Codehaus is a place where people are encouraged to get on with code rather than tie their projects up with bureaucracy. （代码甚于流程）
- The Codehaus encourages projects to strive for quality and for frequent small releases. （讲求质量，小步快跑）
- The Codehaus encourages committers to be respectful friends, meet up with each other as often as possible. Face-to-face is superior to email. （交流靠吼，优于电邮）
- The Codehaus stands in favour of diversity (where appropriate) over enforced convergence and homogeneity. （要百花齐放，不要千篇一律）
- The Codehaus places a high bar on entry for committers. Referral is a common means. A new committer is expected to show strong character elements as well as a talent for code. Maturity and wisdom (possibly in advance of years if a youngster) should be demonstrated. （严选成员，推荐制，有实力的入）
- New committers to an existing project are expected to ease themselves in with small and deferrent commits to start, and greater free-will may be assumed later.（项目中的新客，从提交 bug ﬁx 开始，别一上来就重构优化）
- The Codehaus places a high bar on entry for projects. They should be released or near it.（严选项目，成熟的入 v0.1 的滚）
- The Codehaus encourages people to be brief in email and to honor internet etiquette. Ten furlongs of text justifying a position is poor form; better would be a (failing) unit test. （高效沟通，能用代码绝不文字）
- In case of disagreement, The Despots are right. （必要独裁）
