#+title: 关于网络安全学习的合辑

https://weibo.com/1401527553/Idpdy9wfZ?pagetype=fav

关于网络安全学习的合辑：
- 答一位热爱网络安全的同学的来信：[[https://weibo.com/1401527553/BAVVMC53q][微博正文]]
- 信息安全走向漫谈：[[https://weibo.com/1401527553/DoZ0C9uJC][微博正文]]
- 安全研究者的个人成长：[[https://weibo.com/1401527553/FacHzEHFb][微博正文]]
- 如何学习：[[https://weibo.com/1401527553/Hz2wHelol][微博正文]]
- 如何研究：[[https://weibo.com/1401527553/Hzjb8fwfr][微博正文]]
- 如何成长：[[https://weibo.com/1401527553/HzG6Yl3cl][微博正文]]
- 敲代码的如何转行挖掘漏洞：[[https://weibo.com/1401527553/GEDqK4FmT][微博正文]]
- 网络安全初学者应该看什么书：[[https://weibo.com/1401527553/I2cBS3o9k][微博正文]]
- 网络安全的书读不懂怎么办：[[https://weibo.com/1401527553/GEM6DBlTa][微博正文]]
- 学习网络安全最重要的是什么：[[https://weibo.com/1401527553/FxasXgEDL][微博正文]]
- 如何才能系统的学习逆向：[[https://weibo.com/1401527553/J3A33j1Ji][微博正文]]
- 学习网络安全的最佳路线是什么：[[https://weibo.com/1401527553/EoOFhd1kc][微博正文]]
- 程序员如何判断自己是否适合做安全研究：[[https://weibo.com/1401527553/Bgjv1g256][微博正文]]
- 学习网络安全多久后水平能达到一定程度：[[https://weibo.com/1401527553/HDekX17cE][微博正文]]
- 信息安全方向就业要考哪些证书：[[https://weibo.com/1401527553/GEVy8uZMF][微博正文]]
- 信息安全专业有必要考研吗：[[https://weibo.com/1401527553/GEFmKihL3][微博正文]]
- 想读某个导师的博士应该如何与之沟通：[[https://weibo.com/1401527553/FtEwjpE8n][微博正文]]
- 学院派信息安全指的是什么：[[https://weibo.com/1401527553/GEE2Kkcxu][微博正文]]
- 信息安全专业的发展会受到文凭的限制吗：[[https://weibo.com/1401527553/GEPmwlGow][微博正文]]
- 为什么很多高中生都能比大学生强：[[https://weibo.com/1401527553/GEPjZdYAX][微博正文]]
- 做黑产能挣很多钱吗：[[https://weibo.com/1401527553/GEL0wr8Zz][微博正文]]
- 信息安全工程师有全栈一说吗：[[https://weibo.com/1401527553/GEUMEeZiH][微博正文]]
- 网站越来越难渗透怎么办：[[https://weibo.com/1401527553/IcmJIiraI][微博正文]]
- 做安全研究挖不到漏洞怎么办：[[https://weibo.com/1401527553/Gb0TzkPNh][微博正文]]
- 学习网络安全时遇到瓶颈怎么办：[[https://weibo.com/1401527553/GEUUAeq3Z][微博正文]]
- 高手不愿和我交流交流怎么办：[[https://weibo.com/1401527553/HfHXiuhy9][微博正文]]
- 有了量子计算信息安全还有用吗：[[https://weibo.com/1401527553/GEUJR7aHp][微博正文]]
- 有哪些 Linux 逆向相关的学习资料推荐：[[https://weibo.com/1401527553/GEVyhoWi2][微博正文]]
- DEFCON 1 到 DEFCON 24 的所有资料：[[https://weibo.com/1401527553/GCR3Pp7Md][微博正文]]

如果在上面没找到答案，可以看看这个：[[https://weibo.com/1401527553/G6TnH0OUh][微博正文]]

----------
https://weibo.com/1401527553/G6TnH0OUh

有很多问题的答案其实是“你的智力不适合干这个”，但又不能直接这么说，必须绕很大一个弯子，但由于毕竟“你的智力不适合干这个”，所以绕个弯子对方就看不懂这层意思了……

----------
https://weibo.com/1401527553/GEUUAeq3Z

【学习网络安全时遇到瓶颈了该怎么办？】
“基础的那些sql，xss，csrf那些基本的都会了，但是想更进一步，不知道该怎么办了，有点迷茫，然后我就开始学习python和php，但是，学了一个月，回想一下，发现现在连一个小的脚本都不会写，应聘公司想以实习的目的去学习（ps：中专毕业的渣渣），没有上大学是不是很难应聘公司啊，请大神指点我一下，谢谢”

从事任何方向的技术研究，不知道该干什么的时候，就问自己四个问题：
- 这个方向上最新进展是什么？ 都知道吗？
- 这个方向上最著名的专家有哪些？他们的研究都看过吗？
- 这个方向上最著名的技术社区有哪些？精华帖都看过一遍吗？
- 这个方向上最重要的文章、工具有哪些？文章都看过吗？工具都分析过吗？


----------
https://weibo.com/1401527553/Hz2wHelol

学校教育的方式是：由浅入深，先理论再实践，多门基础课一起平面推进。这种方式的好处是学得扎实，适合批量培养人。缺点是出活儿慢，没有利用人的内驱力。

师傅带徒弟或者自学的情况下就不一定要按批量教学的方式来。

我个人的经验是不管会不会，先动手搞起来。而且不搞太入门的，要难度中等，这样才有成就感，能形成正反馈，调动内驱力。过程中会遇到很多不懂的东西，没关系，遇到什么就去学什么。这个阶段不求多求全，以把手头的东西搞起来为目标。搞成了再设定一个更难的新目标。新老目标之间要有继承性。最后等高难度目标也能搞定了，再转过头系统性地去看看相关技术资料，加固一下地基。

----------
https://weibo.com/1401527553/HzG6Yl3cl

刚参加工作的时候，部门接到各类任务，领导问我能不能干，我一般都说让我去试试吧。然后抓紧时间查资料，学习和这项工作有关的内容。

勇敢接受工作挑战，可以让人快速成长。也会让你有更多的机会，这是个马太效应的事儿。我记得当时的领导给过我这样一个评语：“不管什么工作，交给你我就放心了，反正你总有办法搞定”。

当然也要了解清楚需求，特别是对时间的要求，评估好是否在自己跳一跳能够得着的范围内。

----------
https://weibo.com/1401527553/Hzjb8fwfr

十几年前流行过一篇文章叫《把信带给加西亚》。前些年又流行过批判这篇文章。研究工作大多和那位送信者面临的情况差不多：有一封信交给你，让你送给加西亚。加西亚在哪儿？没人知道。你得自己找，把信送到。

做研究工作，第一步是资料查找。这是从事研究探索最基础的能力，非常重要。而且也没有想象的那么简单，并不是每次把想问的问题输入搜索引擎都能得到答案。所以没找到答案可能不是没有答案。具体用哪些关键词、怎么组合这些词、怎么根据第一步搜索结果中的线索再提取关键词、怎么判断搜索结果有效性，等等，这些都需要反复实践和归纳思考。

通过资料查找，就可以知道是否有人做过类似工作，是否有可直接参考的资料。有时候你会发现全世界也没人做过类似工作。这时就需要针对目标，进行路径分析，看看有哪些路可能通往目标，然后再针对这些分解出的路径再进行资料查找。

这种目标分解有时候会不止一层。也就是说那些分解出来的路径也可能没有资料。那就需要针对路径再作路径分解。然后遍历这些路径。

从历史经验看，天分高、脑子快、手速快、对技术路径有敏锐直觉的人，当然能干得快一些。而一般人只要愿意坚持遍历路径，能扛得住长期得不到正反馈，大部分也能干出成绩。就是会痛苦一些。别人乐在其中，你苦在其中。不怕苦的话也行。
