#+title: Confessions of a Advertising Man(一个广告人的自白)

https://book.douban.com/subject/1031526/

《一个广告人的自白：纪念版》
奥格威
59个笔记

** 本书背后的故事

>> 第一个问题是，一向是广告业中流砥柱的包装货物类产品的制造商，现在花在打折销售上的钱是他们花在广告上的钱的两倍。他们用打折的办法获取销量，而不是使用广告来建立强有力的品牌。任何一个傻瓜蛋都可以搞削价，但是要创建一个品牌需要头脑和坚忍不拔。

>> 是敲响警钟的时候了，该警告那些把钱都花在打折销售上，而没有花钱来做广告建立品牌的制造商，他们的品牌会发生什么。
靠打折促销建立不起无法摧毁的形象，而只有无法摧毁的形象才能使你的品牌成为人们生活的一部分。

>> 第二个问题是，广告公司特别是英国、法国和美国的，今天受到把广告看成是一种前卫艺术形式的人的骚扰。他们一生里什么也没有卖出去；他们的野心是获得戛纳广告节的奖项；他们诱骗不幸的客户一年花几百万来让他们展示他们的独创性；他们对他们宣传的产品不感兴趣，还认为消费者也不，所以，他们几乎一点儿不提产品的优点。

>> 绝大多数广告的职责不是劝说人们来试用你的产品，而是劝说他们在日常生活中比使用其他品牌产品更多地使用你的产品

** 第一章 怎样经营广告公司

>> 一些执牛耳的广告公司现在都由第二代当家人经营了。他们之所以能爬到领导层，是因为他们温文尔雅、对人圆滑，但这可不是创作高质量广告的要素。可悲的事实是，尽管现代的广告公司设备精良，但广告却不像拉斯克尔和霍普金斯在草创时代创作的广告那样有效。我们的事业需要大量注入天才。而天才，我以为最可能从那些不受清规戒律约束、持独特见解、略带反叛性格的人中发掘出来。

>> 我几乎无逻辑性思考的能力，但我和潜意识的联系却畅通，以从不同的领域中获得灵感，创出新的意念。我听过大量的音乐，很喜欢约翰·巴利科恩的作品。我长时间地进行热水浴。我从事园艺活动。我常和门诺教派的神职人员一起静修。我观察鸟类。我常常散步乡间。我经常度假，休息头脑——没有高尔夫、没有鸡尾酒会、没有网球、没有桥牌、没有牵挂，有的只是一辆自行车。
在这样无所事事的时刻，我的潜意识长流不断地给我传来信息。这些都成了我创作广告的意念素材。可是这还不够，还要有刻苦的工作精神、开放的头脑和不受任何限制的好奇心。

** 第二章 怎样争取客户

>> 相形之下，美国对广告和广告从业人员的偏见就不那么厉害。尼尔·麦克尔罗伊（Neil McElroy）——宝洁公司的一位前广告部经理，当上了艾森豪威尔政府的国防部长。切斯特·鲍尔斯（Chester Bowles）在麦迪逊大道干了一段时间后，当上了康涅狄格州州长、驻印度大使和副国务卿。但是，即使在美国，广告人被任命在政府里担任要职的事也是少见的。这很令人感到遗憾，因为有些广告人比起受宠的律师、教授、银行家、记者来更具才华。资深的广告人更能判定问题的优劣；更好地厘定短期和长远的目标，权衡效果；更好地领导大量的行政人员；更好地向委员会介绍情况；更好地在预算内精打细算。据我的观察，我确信我们同业中不少比我年长的、比我高明的人较之许多法律、教育、银行和新闻业的人更客观、更有条理、更有活力、更勤奋。

>> 广告公司争取第一家客户是最难的，因为这时广告公司还没有业绩，没有成功的实例，没有声望。在这个阶段，不妨为一些有希望争取的客户搞一点产品初步调研，作为自荐之阶。在你把调研结果给广告主看的时候，他们的好奇心很少会不被触动。

>> 1958年，新泽西标准石油公司（Standard Oil，New Jersey）向我们了解，若是他们聘用我们的话，我们能做什么样的广告。10天之后，我给他们提交了14套广告方案。我们争取到了他们的广告业务。猎取新的业务，除运气外，高效率和勤奋就是最佳的武器。

>> 荷兰皇家航空公司（KLM Royal Dutch Airlines）决定换广告公司的时候，他们邀请奥美公司和其他4家公司各自准备方案来争取他们的业务。他们头一个视察了我们公司。会谈开始的时候我说：“我们什么也没有准备。相反，我们倒要请你给我们讲讲你们的问题。然后，你们可以去看看你们名单上的其他4家公司。他们都为你们准备了方案，如果你们看中了他们当中的一家，你们的选择就容易了。如果你们都看不上，就请你们回来聘用我们。我们就会开始调查研究。在我们公司，调查研究总是先于准备方案的。”
荷兰人接受了这种冷冰冰的建议。5天之后，他们在看过了其他公司准备的方案以后折回来聘用了我们，使我大为高兴。
但也不能一概而论。有些情况下，主动拿出广告方案去投标是值得的，新泽西标准石油公司和赫莲娜·鲁宾斯坦就是这样的例子。有些时候当一个拒绝这样去做的广告公司是值得的，荷兰皇家航空公司就是这样的例子。最成功的广告公司，是那些高层人士对可能成为他们客户的广告主的心理特征有最敏感的洞察力的公司。死板和推销艺术是搞不到一块儿的。

>> 有一种战略好像对任何情况都实用，即让可能成为你的客户的广告主滔滔不绝地说。你听得越倾心，他就认为你越聪明。

>> 一旦你争取到了客户，对待他们却来不得半点马虎。你花的是人家的钱，他们公司的命运往往由你掌握着。不过我把猎取新的客户看作是体育运动。如果在比赛中你神经紧张，那你会死于溃疡病；如果你轻松愉快地进行比赛，就算失败了你也不致失眠。参加运动比赛当然是为了取胜，但是要享受比赛的乐趣。
我青年时代在伦敦“理想家庭展览会”上卖厨房灶具。每卖一件，都要按顾客的个性慢慢地费一番口舌，这要花去我40分钟时间。问题是要从乱哄哄的人群中找出买得起每台400英镑的灶具的人。我学会了用鼻子把他们闻出来的本事：他们抽土耳其香烟，这是贵族派头的标记，就像爱沙尼亚领带一样。
晚些年，我学会了在一大堆人中嗅出大广告主味道的本事。有一次我去参加苏格兰人协会在纽约举行的午餐会。散会出来的时候，我有一种预感，在那天我头一回遇到的人当中有4个终有一天会成为我的客户。事实果然如此。

>> 我在开发新的客户时，还干过不计后果的傻事。我遇到英国旅游假日协会（British Travel & Holidays Association）的负责人亚历山大·马克斯韦尔爵士（Sir Alexander H.Maxwell）的时候，我们急切需要一些新业务。一开始他就奚落我。“我们的广告，”他说，“好得很，的确好得很。我丝毫没有改换广告公司的意思。”
我回答说：“亨利三世病入膏肓的时候，大家都以为要是有人敢把可怕的真实情况告诉他，这个人准会被砍头。可是由于国家的需要，总得有个自告奋勇的人。亨利·丹尼于是挺身而出。亨利三世非常感谢丹尼有勇气这样做，赐给了他一副手套，封他为爵士。亨利·丹尼是我的先人。他的榜样启发我告诉你，你的广告做得非常之糟。”

>> 我从来不想揽那种很大很大的客户，因为一旦失掉这样的客户，后果是我承受不起的。要是揽上了这样的客户，从你给他们做广告的头一天起，你就不得不战战兢兢地过日子。一个广告公司如果被吓得失魂落魄，它就失掉了提出坦率意见的勇气，而一旦你失掉了这种勇气，你也就变成低贱的奴才了。

>> 我谢绝产品销售长期下降的客户。出现销售不良的情况，几乎总是因为产品存在缺点，或是因为厂家管理不善。这两种缺陷是不论多么好的广告也补救不了的。一个新的公司不论他多么渴望得到客户，总应该能够约束自己，拒绝这种客户。有名气的外科医生可以经得起偶然在他的手术台上死去一位病人的打击，但是一个年轻的医生若是碰上了这样的不幸事故，他的前程就可能断送掉了。我常常害怕我们的客户在我们的“手术台”上死掉。

>> 搞清楚可能成为你的客户的广告主是不是希望他的广告公司有利可图是很重要的。我有过蒙受损失的经验。我帮助我的客户发展成千万富翁，可是我自己却在为他们服务的过程中连衬衫都赔了进去。广告业的平均纯利现在不到5‰。我们在锋利的刀刃上耍平衡：既不能给客户过分的服务而使自己破产，也不能轻率服务丧失业务。

>> 我谢绝把广告看成全部营销活动中的边际因素的客户。他们有一种很令人尴尬的做法：每逢别处要用现钱，他们总是从广告费上打主意。我更喜欢那些视广告为须臾不可缺少的必需之物的客户。就像医生动手术一样，我们为客户的生意开刀的地方是那不可或缺的心脏，而不是随便一个无关紧要的部位。

>> 如果你有创作有效广告的抱负，千万不要揽“协会”为客户。

>> 差不多所有的协会客户的情况都像他们一样。“婆婆”太多，目标太多，钱则太少。

>> 我们必须为波多黎各树立一个可爱的形象来冲掉美国人头脑中的那个污秽的形象。这对你们的工业、朗姆酒业、旅游业的发展和你们的政治改革都有极重要的意义。
波多黎各是什么？这个岛国有什么样的特点？它要让世人看的是什么？是不是说它只不过是正在致力于发展工业的落后国家？是不是说这个岛国将永远是马克斯·阿斯科利（Max Ascoli）所称的“新政派人士的沿海岛屿”？是不是说它将发展成为日后的北费城（North Philadelphia）？或是说，在这个经济体上还有着活跃的基因？是不是要让粗俗的游客麇集波多黎各，使它变成二等迈阿密海滩？波多黎各人这么狂热地表现自己美国化的程度，是不是他们已经忘掉了自己的西班牙传统了？
完全可以避免产生这些混乱可悲的形象。最保险的办法就是为波多黎各制订一套长远的广告宣传方案，通过宣传在世人中树立一个振奋人心的波多黎各的形象——欣欣向荣的波多黎各。

>> 热情并不总是获得成功的最佳因素。我有五六次回绝了不符合我们条件的客户，结果发现，拒绝反而激起了客户要求聘用我们的愿望。一家有名的瑞士表厂提出把广告业务交给我们，我们回绝了。因为他们的广告不仅要经瑞士厂，而且要经美国进口商方面的批准。哪家广告公司也不可能伺候两个主子。可是，我们并没有直言拒绝，而是对他们说，只要他们肯付25%的佣金，而不是通常的15%，我们可以接受他们的聘请。客户立刻接受了。

>> 只要有4家以上的广告公司卷入了对一家客户的角逐，我就回避。争宠的俗套做法是开许多长会。大多数的客户选择广告公司的时候，都会考虑有名气的。作为这样的公司的领导人，如果来者不拒，就会使自己的时间在没完没了的会议中耗尽，更何况我们还有别的事要干——为我们已有的客户提供高水平的服务。
最理想的是无须与别的公司竞争就能得到客户。可是这种情形是越来越少了。因为广告主现在似乎觉得，若不在几家广告公司之间比较一下各家的长和短就决定聘用一家新广告公司，未免显得幼稚。

** 第三章 怎样维系客户

>> 当公司总裁明白是由于自己领导无方致使客户丧失的时候，他会怎么样对待自己的良心呢？他怎么可以随随便便就把负责管理这家客户、尽了最大努力来冲销他所干的蠢事的那些职员撤掉？这些人当中可能就有难得的良才，而他也需要这些人来管理日后争取来的客户。可是，作为公司的总裁，他又担得起让他们闲着无所事事的责任吗？一般说来是不可能的。我见过广告公司为丢失一家客户而辞掉上百个职员的事，那些可怜的家伙里有些因为年龄过大而找不到别的工作。广告公司的员工工资总是很高，就是由于这个原因。除了戏剧业外，广告业也许就是最没有保障的行业了。
如果你渴望经营广告公司的话，那你就必须接受你经常如履薄冰的事实。要是你生来胆小怕事，那你注定要失败。你走上的是一条长满荆棘的路。

>> 第二，你不要任用处事草率、很不随和的人做客户主管。麦迪逊大道到处都是这种会莫名其妙地刺激客户使其对自己反感的受虐狂。我知道不少很有头脑却把客户丧失得一干二净的人。我知道也有平凡得不足道但很善于在广告公司与客户之间建立平稳关系的人。
第三，要避免揽进那些一再辞掉自己的广告公司的客户。你可能以为你能治好他们心胸狭窄的毛病，可是这于你很不利，就像娶了一位一再闹离婚的妇人一样。

>> 我从没有对一位客户说过因为我事前已经和另外一家客户有了约会而不能去参加他的会议。一夫多妻成功的秘诀在于丈夫能使每个妻子都相信她是他唯一宠爱的。如果有一个客户向我打听我为另外一家客户开发广告计划的情况，我总是用别的话题把它岔开。这可能使他不快，但是把他要知道的事都告诉了他，他很可能会得出这样的结论：我也会同样轻率地对待他的秘密的。一旦客户觉得你不能守口如瓶，那你可要吃大苦头了。

>> 客户总是会非难我们的客户主管。有时他们有理，可是有时却是他们不对。但是不论孰是孰非，把有关的人调任他职对各方都有好处，而且要在小事未酿大，没有影响到广告代理与客户的全面关系之前处理妥善。
我有一位很有才华的同事一年中遭到3个客户的非难，这一段遭遇深深地伤害了他，使他完全洗手再不干广告。要是你的脸皮太薄，经不起这种肆虐，你就不应该来干广告公司客户主管这一行。

>> 对广告公司来说，最危险的事莫过于依赖单一的个人来联系客户了。要是一家大厂商的总裁聘用你的公司做他的广告代理是因为他喜欢你们的总裁，那么，你必须马上采取措施，在低一些的层次上和他们建立关系。只有广告公司在各个层次上和客户都建立了稳固的关系，你才能指望比较长期地代理这家客户的广告业务。
我不相信和客户的接触应该限制在客户主管身上。让你的调查研究、媒体、文案、美术、电视广告制作、营销等其他部门的人熟识你的客户，工作起来就会更好一些。这样做，有时也会闹笑话，因为这些幕后人员并不都善于待人接物，有些人总无法给人以好印象。只有真具慧眼的客户才能看出，口拙舌笨的人也可能写出令生意备加兴旺的好广告来。

>> 广告公司领导人手里的事有千千万，于是他常常在出现危机的时候才会见他的客户。这是不对的。如果你养成了在风平浪静的时候会见你的客户的习惯，你就可能和客户建立起一种在大风大浪来临时能救你性命的融洽关系。

>> 有些公司热衷于把什么事都弄到委员会里去。他们吹捧“集体协作”而贬低个人的作用。可是没什么“集体”可以协作出广告来，我怀疑有哪家有作为的广告公司能不靠某个个人的撑持。

>> 向委员会介绍复杂方案的最好手段莫过于提高嗓门大声朗读了。它能起到把满屋人的注意力都吸引到你的讲话上来的作用。在这方面我有些建议可供参考。听起来好像事情不大，但是它却可能对一个提案的成功有关键性的意义：你高声朗读的时候，一个字也不要离开你印发给大家的文稿。诀窍在于它可以从听和看两个方面同时触及他们的感官。如果眼睛看到的是这样的词句，耳朵听到的却是另外一种，他们就会糊涂，注意力就会分散。

>> 在某些广告公司里，客户主管可以差遣创作人员。有些客户因此而得到好印象，以为他们的广告是由“会做生意的人”掌管着，很安全。但是它制造了一种压制文案撰稿人的气氛，客户最终得到的是二流广告。在另外一些公司里，客户主管又变得和饭店的服务员差不多，只是把广告从创作部门端到客户跟前。如不向总部汇报，客户提出的最微小的修改意见他们都不可能接受。他们被剥夺了对问题做出判断的权利，最终成了跑腿的人。
两种做法我都不赞成。我有能干的文案撰稿人，他们和那些有权和客户打交道的客户主管一道和谐地工作。客户主管则很成熟，能老练地掌握他们主管的客户业务的每一个环节，也不至冒犯撰稿人的权威。这是极微妙的平衡，我知道只有另外一家广告公司能做到这一点。

** 第四章 怎样当一个好客户

>> 我知道有一位啤酒生产商，在他的顾客当中，没有看过他的啤酒广告的要比看过的多。低劣的广告会使产品滞销。
出现这种灾难，责任有时在广告公司，但往往该责怪的是客户。有什么样的客户就有什么样的广告宣传。我为96家客户做过广告，有很难得的机会来比较他们的态度和办事程序。有的人所作所为极其糟糕，使得没有一家广告公司能为他们创作出有效的广告来。有的则表现得很好，无论哪家广告公司都会为他做出有效的广告来。

>> 经营广告公司大部分时间是令人胆战心惊的。这一方面是因为在广告公司工作的人很自然地都缺乏职业保障。另一方面，许多客户都明白无误地把自己总是在物色新的广告公司的事形之于色。在战战兢兢的环境里是无法创作出好广告的。
拒绝了劳斯莱斯的业务以后，我毛遂自荐拜访了福特汽车公司，以求“认识认识”。他们的广告经理拒绝见我，使我终生感激不尽。他说：“底特律是一个小城市。如果你来拜访我，就会有人知道。我们现在的广告代理就会有所闻而产生惶恐。我不想让他们担惊受怕。”
若我是客户的话，我定会竭尽全力使我的广告公司从恐惧中解脱出来，甚至为此签订长期合同也在所不惜。

>> 不在行的人会利用招标办法来吸引一些广告公司提供免费的投标广告方案。在这种竞争中获胜的是那些把公司最有才干的人员投在竞争新广告业务上的广告公司，他们把已经揽到手的客户交给二流人员照管。如果我是广告客户，我就要找一家不设新客户开发部门的广告公司。最好的广告公司不需要这种部门，他们不做投标性的广告活动，而是按照自己的业务能力发展广告业务。

>> 邀请竞争你的业务的各个广告公司的最高主管各带上两位他的骨干人物分别去你家晚餐。让他们放松敞开地谈话，看看他们对他们已有客户的秘密是否能够守口如瓶，看他们在你说了些蠢话时是不是有勇气表示异议。观察他们之间的关系，是忠诚合作的同事呢还是各怀鬼胎的耍手腕的人？他们是不是对你做出明显是夸大了的承诺？他们是死气沉沉还是干劲十足？他们是不是善于倾听别人的意见？他们是不是真诚？
特别是，看看你是不是喜欢他们。客户和广告公司之间的关系必须是亲密的，如果双方的人际关系不协调，那就无法进行合作。

>> 在后座对司机指手画脚，这种做法必然要让优秀的创作人员丧失灵感。要是你这样做了，我只好请上帝保佑你。应该向你的广告经理讲清楚，创作广告是广告公司的责任，不是他的，告诫他无须去分担广告公司的责任。

>> 在我写这一段的时候，我正在做这样的工作。这种新产品是100多位科学家花了两年时间研制出来的。但客户只让我用30天的时间来塑造这种产品的个性，筹划如何把它成功地推进市场。如果我干得好，我对这个产品成功方面的贡献就相当于那100多位科学家所做的。
这不是新手能干的事。它要求策划广告活动的人能洞悉市场、有丰富的幻想力，还能运用调查研究得来的资料厘定产品名称、包装和对消费者应该做出怎样的承诺。同时他还要考虑到在竞争者推出同样产品的时候的对策。另外，同样重要的是，他必须有创作能力，能为产品创作有效的广告。环顾美国市场，我以为具有这等才能和素质的人才，可以说真是凤毛麟角。而客户一般又都要广告公司承担制作这种提案的花费。若厂商能像他们投资于新产品开发一样投资于新产品的广告宣传和促销活动的话，新产品在市场上的成功率将会大大增加。

>> 不要打短打。要明确表示你要求你的广告公司打本垒打￼。他们若是做到这一点，就多给他们奖励。
许多客户在他们的产品销售不好的时候轻易责怪广告公司，可是在产品销售上升的时候又舍不得把功劳归给它们。这是不体面的。
可是千万不要让你的广告公司躺在成绩的桂冠上，要不断地鼓励它们攀登更高的巅峰。也许你目前已有了一套很好的广告活动方案，可是你应该马上要求你的广告公司开始研究创作另一套更好的。

>> 大公司里的年轻人不懂得时间之可贵，就好像利润不是时间的产物。杰里·兰伯特以李斯德林漱口水取得突破性成功的时候，他把时间按月分段，以加速整个市场营销进程。兰伯特每月查核一次他的广告和利润，结果他在8年的时间里赚了2500万美元，而大部分人却要花12倍时间才能做到这一点。杰里·兰伯特主持兰伯特医药公司（Lambert Pharmacal Company）的那些年，公司不是按年，而是按月过日子的。我向所有的广告主推荐这种做法。

** 1. 广告的内容比表现内容的方法更重要

>> 舒坦和安全的感觉。有些人则对在这些严格的原则指导下工作的前景而感到不安。
他们说：“可以肯定地说，这些教条会把广告搞得很枯燥。”
“不见得。”我回答说。接下去我向他们讲艺术领域中法则的重要性。莎士比亚按照严格的格律写十四行诗，总共14行，抑扬顿挫，韵律、起承转合，无不严谨不紊。难道说他的十四行诗枯燥吗？莫扎特写奏鸣曲所遵循的是同样严格的章法——呈现、发展、再现，也都井井有条。难道这样的作品也枯燥无味吗？
这些论点使大部分自命不凡的人折服。接着我对他们说，如果他们按着我说的原则去做，不用多久他们就会制作出好广告来的。

>> 什么是好广告？有3种不同的观点。对什么东西都无所谓的人说，客户认可的广告就是好的。另一种人同意雷蒙·罗必凯的定义：“上乘广告的最好标志是，它不仅能影响群众争购它所宣传的产品，而且它能使群众和广告界都把它作为一件可钦可佩的杰作而长记不忘。”我创作过广告界长记不忘的“可钦可佩的杰作”，可是我却属于第三派。我认为广告佳作是不引公众注意它自己就把产品推销掉的作品。它应该把广告诉求对象的注意力引向产品。好广告要诉求对象说的不是：“多妙的广告啊！”而是：“我从来没有听说过这种产品，我一定要买它来试试。”

>> 6. 使你的广告具有现代意识
1963年的年轻家庭主妇们出生于罗斯福总统去世之后，她们生活在一个新的世界里。我51岁了，我发现，要和那些刚刚开始闯入生活的年轻夫妇的思想感情协调一致是越来越难了。所以我们公司的大部分撰稿人都是年轻人，他们比我更懂得年轻消费者的心理。

>> . 若是你运气好，创作了一则很好的广告，就不妨重复地使用它，直到它的号召力减退
许多广告还没有发挥尽潜力就被替换搁置。这往往是由于主宰这些广告的人厌烦它们。斯特林·格彻（Sterling Getchel）为普利茅斯轿车写的著名广告“3部都看看”（Look at All Three）只出现了一次就被一系列拙劣的变种所取代，这些次品后来很快就被人遗忘了。可是，舍温·科德英语学校（Sherwin Cody School of English）坚持使用“你用英语时犯这些错误吗？”（Do You Make These Mistakes in Eng-lish？）这则广告42年，其间只是换了换广告字体和科德先生胡子的颜色。
你不是对一队立正站着的军人，而是对一队行动中的士兵做广告。如果一则广告对去年结婚的夫妇推销了电冰箱，那么它也同样能对今年结婚的夫妇起作用。每年有170万消费者去世，有400万新的消费者诞生。有人进入市场，也有人辞别市场。广告就像雷达，总是在搜寻新踏进市场的潜在对象。采用一部好雷达，让它不停地为你扫描。

>> 每一则广告都应该看成是对品牌形象（brand image）这种复杂现象在做贡献。如果你具有这种长远的眼光，许许多多日常的麻烦事都自会化为乌有。
你怎么判定树立什么样的形象呢？这不是三言两语可以说清的。调查研究对此也帮不了多大的忙。实际上你非使用判断力不可。（我注意到，营销主管方面不愿意使用判断力的倾向在增长。他们过分依赖调查，他们使用调查研究的结果就像醉鬼使用电线杆一样，是把它当扶手而不是当作照明工具。）
绝大部分厂商不接受他们的品牌形象有一定局限性的事实。他们希望他们的品牌对人人都适用。他们希望他们的品牌既适合男性也适合女性，既能适合上流社会也适合广大群众。结果他们的产品就什么个性都没有了，成了一种不伦不类不男不女的东西。阉鸡绝不能称雄于鸡的王国。

>> 个厂商要是让自己的广告宣传在一段长时间里保持前后协调的风格，那将是何等的奇迹！想想看，有多少人施加压力费尽心机要改变它。广告经理新的来了，旧的走了，文案撰稿人也换来换去，甚至广告公司也在不停地换着。
广告主每6个月就要你“换上新鲜东西”，在压力面前坚持统一的风格，的确是很需要点勇气的。胡乱更改广告是极其容易的事情，但是，金光灿灿的奖杯却只颁给对塑造协调一致的形象有远见而且能持之以恒的广告主。甘浦罐头汤公司、象牙香皂（Ivory Soap）、埃索石油公司（Esso）、贝蒂陶瓷公司（Betty Crocker）和英国健力士黑啤酒就是这样的例子。这些活力长年不衰的公司的广告负责人都懂得，不论做什么广告都不是一劳永逸的事，而是对他们的品牌个性的长期投资。他们向世界推出的是前后一致的品牌形象，而且这个形象还在不断地成长丰满。

>> 绝大多数认为改变他们品牌形象是好事的厂家希望的是“提高”他们品牌的印象。通常的情况是，他们的产品已经给人一种是廉价推销品的印象。在经济活力匮乏的时期，这倒是有好处的；但是在经济繁荣、大多数消费者都向更高的社会阶梯迈进的时候，这样的形象却很令人尴尬。
改变这种廉价货的老面孔，使之焕然一新是极不容易的事。换一个新牌子推倒重来往往更容易一些。

>> 削价以及其他类似的求存方法为营销经理们所乐用，但它的效果是短暂的，它还会让你形成坏习惯。创造阿尔特·尼尔森（Art Niels-en）公司的消费者购买状况衡量法、后来在甘浦罐头汤公司当上了总裁的贝弗·墨菲（Bev Murphy）说：“销售是生产价值和广告的函数。促销产生的只不过是销售曲线上的一个靠不住的点。”杰里·兰伯特从不为李斯德林漱口水搞促销活动，他明白销售曲线上那个靠不住的点会使他无法评估广告的绩效。

** 标题（Headline）

>> 其他会产生良好效果的字眼是：如何、突然、当今、宣布、引进、就在此地、最新到货、重大发展、改进、惊人、轰动一时、了不起、划时代、令人叹为观止、奇迹、魔力、奉献、快捷、简易、需求、挑战、奉劝、实情、比较、廉价、从速、最后机会等等。
不要对这些字眼儿嗤之以鼻。它们也许是老生常谈，但是在广告上却很起作用。正是这个原因，你经常能在邮购广告和其他可以衡量自己绩效的广告的标题中看到这些字眼。

>> 40年前广告界好像很受这几则名噪一时却华而不实的散文所影响，而我却一直觉得这类广告很无聊，连一点儿事实也没有提供给读者。我很同意克劳德·霍普金斯的观点：“高雅的文字对广告是明显的不利因素。精雕细刻的笔法也如此。它们喧宾夺主地把对广告主题的注意力攫走了。”

** 第七章 怎样使用插图和编排文案

>> 我再不把我们公司的广告编排稿送去参加美术指导组织举办的竞赛了，害怕其中某一幅会因获得某种奖励而被亵渎。他们的神并不是我的神。我有我自己的信条，它来自对人的行为的观察，而这种观察记录在盖洛普博士、斯塔奇博士的调研和邮购广告专家的经验中。
广告一定要针对它所要刊登的刊物来设计，在它被排进出版物、你看到它被排进去的样子之前千万不要最后敲定。那种极为流行的不顾具体环境，把布局设计稿裱在灰色纸板上，蒙上一层透明薄膜，然后就进行评价的做法是极其危险并会引起误解的。必须把广告设计放在与它相关联的报纸或杂志的整体编排气氛里来考虑。
一位缺乏经验的年轻客户不久前对我说：“你的设计稿一钉上我的布告牌，我就立刻可以判断哪一份是最好的。”这样的环境绝不是读者看广告的环境。

>> 我不喜欢路牌广告。驾车飞驰而过的驾驶员只来得及读路牌广告上的6个字，而依我过去挨门挨户兜售的经验来看，只用6个字来推销商品无论如何是不成的。在报纸或者杂志上，我可以使用上百个字。路牌广告只能是喊喊口号而已。
抛开广告职业不谈，作为个人，我对风景有强烈的喜爱。任何景致都不会因路牌广告而增色。在事事都令人心旷神怡的野外要是竖起一块路牌广告，任何罪恶都莫过于此。有朝一日我从麦迪逊大道引退，我定要发起组织一个秘密的环境维护者社团，蒙着面骑乘无声摩托车走遍世界，在黑夜里砍倒一切路牌广告。若是我们在为公民们行此大善之时被抓住，又有多少陪审员会判我们有罪呢？
路牌广告的所有者都是些放肆的说客，他们全力攻击不准在新修建的高速公路设置路牌广告的法案。他们借口有成千上万的工人依赖路牌广告维生。妓院不是也如此吗？

** 第八章 怎样制作上乘的电视广告

>> 在报纸和杂志上做广告，你是从吸引读者的注意力开始的，但是就电视广告而言，观众在一开始的时候就已经在注意了，问题是不要把观众吓跑。最要命的是广告一开始就提醒他们将要听到“来自我们赞助商的友好保证”，他们会像巴甫洛夫的小狗听到铃声一样，一听到这话就跑去上厕所。

>> 大部分电视广告的目的是宣传你的销售承诺，使观众在下次采购时能想起来。因此我建议在每一则广告中至少要把这种销售承诺重复两遍，用图表表达或者把它作为字幕打在荧屏上。
可怜的一般消费者现在一年要碰到1万条电视广告，所以一定要让观众知道你的电视广告里宣传的商品的名字，要从头到尾、“令人厌烦”（ad nauseam）￼ 地多次重复它。￼ 至少用打字幕的方法表示一次。还要让观众看看这种商品的包装，以使他们在商店中认得出它来。

** 第九章 怎样为食品、旅游地和专利药品制作优良广告

>> （2）旅游者不远万里而来，不是为了看那些自家门口就可以看到的东西。比如说，你无法说服瑞士人跑上5000英里到美国来看科罗拉多山。要把你的国家最能吸引游客之处拿来做广告。
（3）你的广告应该为你的读者树立一个难以忘却的印象。看到广告与决心买机票启程之间酝酿时间大概是很长的。
（4）刊登你的广告的媒介是给有条件做长途旅行的人看的。这些人受过良好的教育。不要低估他们的智力。用成熟的文字写广告——而不用一般惯用的旅游广告套话来写。
（5）国际旅行的最大障碍是费用。你的广告应该强调文化和个人身份的特点，让读者觉得他的旅行消费是合理的。
（6）旅游线路极易受潮流影响。广告应该把你的国家说成世界热门旅游点。潮流具有引导旅游消费的魔力。

>> （8）避免采用外国人不易理解的话题。有些话题本国人是极易心领神会的，但文化背景不同的外国旅游者——顾客们，是无法领略它们的神韵的。

>> 美国旅游者决定去某个国家旅行时，他打算去的国家的居民的态度对他的选择有很大影响。我的调查表明，他们心目中的英国人有礼貌、有文化修养、诚挚直爽、清洁、讲公德。但是，他们也觉得英国人冷漠、自负和多愁善感。所以，在我们的广告宣传里，我们尽最大努力来纠正人们心目中这些令人不愉快的方面，加强宣传英国人民友好的一面。

** 第十章 怎样才能功成名就——对年轻人的进言

>> 首先，要有大志但却不可咄咄逼人，以免引得你的同事对你群起而攻之。每个士兵的腰里都可以挂上一根将军用的指挥棍，但是不要让它暴露在外。
若你是从哈佛商学院毕业后直接进入广告公司的，那你切不可锋芒毕露，而且要坚持继续学习。经过一年的艰苦训练，你也许可以当上一位助理客户主管——一种不高不低的职务。一旦这一点实现，你就应该下决心成为本公司里对与你所主管的客户有关的一切情况和知识最为熟悉的人。比如，如果你主管一家经营石油的客户，那么你就要阅读化学、地质和关于石油产品销售的书籍；遍读你的公司关于石油产品的所有研究报告和营销计划；把你的星期六上午花在汽油站、加油点，和开车的人交谈；深入到客户的炼油厂、研究实验室里去，研究他们的市场对手的广告宣传。第二年之末，你对石油各方面的知识就会懂得比你的领导还多，你就具备了接替他的条件。
广告公司的青年人绝大部分过于疏懒，不肯做这类“深入了解”的工作，满足于一知半解

>> 要记住你的工资比你在其他行业的同辈要高，这有三种原因：
首先，能干的广告人供不应求；其次，广告公司的福利比其他行业少；最后，广告职业保障也比其他行业低。所以要尽力使你的支出低于收入，这样你就可以忍受一段时间的失业。如果可能购买你们公司的股票，你切莫错失良机。在其他方面也搞些投资。生活保障是广告人65岁以后共同的严重问题。

** 第十一章 广告是否应予废止

>> 广告能使人买他不需要的东西吗？若你认为人不需要香体剂，那你尽可以自由地批评广告宣传劝服了美国87%的妇女和66%的男人使用香体剂。若你不以为人需要啤酒，那么你批评广告宣传说服了58%的成年人饮用各种啤酒也就一点也不错。如果你不赞成社交活动和人生的某些享受如国外旅行等，那么你指责广告鼓励了这些坏事也是正当的。若你不喜欢丰衣足食的社会，你责怪广告鼓动大众追求物质生活也是无可非议的。
若你是这样的清教徒，我和你是无理可讲的，我只好把你当作受虐狂，只好像莱顿大主教那样祈祷：“啊，主啊，我错生为聪明善良之人，请您把我从中解脱出来吧。”
英国工人运动之父、受人尊敬的老约翰·伯恩斯￼常说，工人阶级的悲剧在于其寡欲。对我怂恿工人争取较好的生活，我绝不后悔。
