#+title: 亲爱的安德烈

在写作的过程里，我们人生哲学的差异被凸显了：他把写作当“玩”，我把写作当“事”。我们的价值观和生活态度，也出现对比：他有三分玩世不恭，二分黑色幽默，五分的认真；我有八分的认真，二分的知性怀疑。他对我嘲笑有加，我对他认真研究。

生活是抑郁的，人生是浪费的。可是整个社会，如果历史拉长来看，却是在抑郁中逐渐成熟，在浪费中逐渐累积能量。因为，经验过压迫的人更认识自由的脆弱，更珍惜自由的难得。你没发现，经过纳粹历史的德国人就比一向和平的瑞士人深沉一点吗？

你知道，一个被长年灌食某种饲料的人，见到饲料都想吐。民族主义的饲料——不管是中国牌还是台湾牌的，我们都被灌得撑了，被剥夺的，就是一份本来可以自自然然、单单纯纯的乡土之爱，纯洁而珍贵的群体归属感。它被操弄得变形了。

我们这一代人，心有太多的不信任，太多的不屑，太多的不赞成，对于我们的所谓国家，尤其是一些自称代表国家的人。

在这种与“国家”保持距离的文化和教育中长大，我看见它的优点：在我们这一代人身上，真的很少很少爱国宣传的影响；当你对“国家”抱一种不信任的时候，你比较能够冷静地去分析它的问题所在。

我其实跟美国文化很疏离。很少同龄人关心政治。他们说他们反对布什，事实上那样说只是为了表现自己“酷”。反布什是流行的。年轻人每个都反，除非你是个基督徒或是好战主义者。

我们在一个富强的国家，富强的意思就是，年轻人可以对政治经济国际情势一概幼稚无知，他反正承受得起，让别人来为他思考。美国青年的悲哀就是这个，我们对世界完全淡漠，只关心自己的小圈。

德语有个说法：如果你年轻却不激进，那么你就是个没心的人；如果你老了却不保守，那么你就是个没脑的人。

那时我23岁，刚从台湾到美国，很震惊为什么欧洲的青年人和台湾的青年人世界那样不一样。他们为什么显得没有任何畏惧，背起背包就敢千里闯荡？他们为什么满脑子都是玩，懂得玩、热爱玩、拼命玩？他们的父母难道对他们没有要求，要求他们努力读书，出人头地；他们的学校难道对他们没有期待，期待他们回馈社会，报效国家？

人生，其实像一条从宽阔的平原走进森林的路。在平原上同伴可以结伙而行，欢乐地前推后挤、相濡以沫；一旦进入森林，草丛和荆棘挡路，各人专心走各人的路，寻找各人的方向，那推推挤挤的群体情感，那无忧无虑无猜忌的同侪深情，在人的一生中也只有少年期有。离开这段纯洁而明亮的阶段，路其实可能愈走愈孤独。你将被家庭羁绊，被责任捆绑，被自己的野心套牢，被人生的复杂和矛盾压抑，你往丛林深处走去，愈走愈深，不复再有阳光似的伙伴。到了熟透的年龄，即使在群众的怀抱中，你都可能觉得寂寞无比。

如果一个孩子在他的生活里没接触过大自然，譬如摸过树的皮、踩过干脆的落叶，她就没办法教他美术。因为，他没第一手接触过美。

中国有一个我非常欣赏的作者，叫沈从文，他的文学魅力，我觉得，来自他小时逃学，到街上看杀猪屠狗、打铁磨刀的小贩，看革命军杀人、农民头颅滚地的人生百态。在街上撒野给予他的成熟和智能，可能远超过课堂里的背诵。

但我担心的不是你职业的贵贱、金钱的多寡、地位的高低，而是，你的工作能给你多少自由？“性、药、摇滚乐”是少年清狂时的自由概念，一种反叛的手势；走进人生的丛林之后，自由却往往要看你被迫花多少时间在闪避道路上的荆棘。

你将来会碰到很多你不欣赏、不赞成的人，而且必须与他们共事。这人可能是你的上司、同事或部属，这人可能是你的市长或国家领导。你必须每一次都作出决定：是与他决裂、抗争，还是妥协、接受。抗争，值不值得？妥协，安不安心？在信仰和现实之间，很困难地找出一条路来。

你不用道歉，我明白我不是你最重要的一部分。那个阶段，早就过去了。父母亲，对于一个20岁的人而言，恐怕就像一栋旧房子：你住在它里面，它为你遮风挡雨，给你温暖和安全，但是房子就是房子，你不会和房子去说话，去沟通，去体贴它、讨好它。搬家具时碰破了一个墙角，你也不会去说“对不起”。父母啊，只是你完全视若无睹的住惯了的旧房子吧。

所谓父母，就是那不断对着背影既欣喜又悲伤、想追回拥抱又不敢声张的人。

我曾经看过信徒祈祷、香火鼎盛的寺庙被栅栏围住，收门票。也看过宫殿和王府被关起来，收了门票才打开；也看过古老的村子被圈起来──连同里头的人，收门票。但是，天一样大的草原，地一样老的湖泊，日月星辰一样长长久久的野花，青草怒长的无边无际的山谷，也被围起来，收门票──唉，可真超过了我能忍受的限度！ 可是我能做什么？ 　

国际学生跟本地生没有来往，我觉得还有一个原因，就是语言障碍。港大的所有课程都是英语教学，所以你会以为学生的英语一定是不错的。告诉你，事实完全不是如此。我发现，很多学生确实能读能写，但是，他们讲得非常吃力。大部分的学生不会用英语聊天。最吃惊的发现是，香港学生可能可以用文法正确的英语句型跟你讲爱因斯坦的相对论是什么东西，但是，你要他讲清楚昨天在酒吧里听来的一个好玩的笑话，他就完了，他不会。

你问我愿不愿意干脆在香港读完大学？我真的不知道，因为，两个月下来，发现这里的生活质量跟欧洲有一个最根本的差别，那就是——我觉得，香港缺少文化。 我说“文化”，不是指戏剧、舞蹈、音乐演出、艺术展览等等。我指的是，一种生活态度，一种生活情趣。 用欧洲做例子来说吧。我最享受的事情，譬如说，在徒步区的街头咖啡座跟好朋友坐下来，喝一杯意大利咖啡，暖暖的秋天午后，感觉风轻轻吹过房子与房子之间的窄巷。 美好的并非只是那个地点，而是笼罩着那个地点的整个情调和氛围，一种生活方式，一种文化的沉淀。

我还发现，香港人永远在赶时间。如果他们在餐厅、咖啡馆或者酒吧里会面，也只是为了在行事日历上面打个勾，表示事情做完了。这个约会还在进行，心里已经在盘算下一个约会的地点跟交通路线。

人跟人之间愿意花时间交流，坐下来为了喝咖啡而喝咖啡，为了聊天而聊天，在欧洲是生活里很大的一部分，是很重要的一种生活艺术。香港没有这样的生活艺术。

文化来自逗留——“逗”，才有思想的刺激、灵感的挑逗、能量的爆发；“留”，才有沉淀、累积、酝酿、培养。我们能不能说，没有逗留空间，就没有逗留文化；没有逗留文化，就根本没有文化？

思想需要经验的累积，灵感需要感受的沉淀，最细致的体验需要最宁静透彻的观照。累积、沉淀、宁静观照，哪一样可以在忙碌中产生呢？我相信，奔忙，使作家无法写作，音乐家无法谱曲，画家无法作画，学者无法著述。奔忙，使思想家变成名嘴，使名嘴变成娱乐家，使娱乐家变成聒噪小丑。闲暇、逗留，确实是创造力的有机土壤，不可或缺。

温和理性是公民素养和法治精神的外在体现，在民主的实践里是重要的人民“品性”。台湾人比起香港人不是那么“温和理性”的，因为他们是经过长期的“抗暴”走出来的──抗日本殖民的“暴”，抗国民黨高压统治的“暴”，现在又抗民进黨无能腐败、滥用权力的“暴”。在台湾，愈来愈多“温和理性”的人民，但是他们的“温和理性”是在从不间断的“抗暴”过程里一点一滴酝酿出来的。台湾人的“温和理性”是受过伤害后的平静。香港人的“温和理性”来自哪里？不是来自“抗暴”；他们既不曾抗过英国殖民的“暴”，也不曾抗过共產黨的“暴”。在历史的命运里，香港人只有“逃走”和“移民”的经验，没有“抗暴”的经验。他们的“温合理性”，是混杂着英国人喝下午茶的“教养”训练和面对坎坷又暴虐的中国所培养出来的一种“无可奈何”。

中年父母的挫折，安德烈，可能多半来自于，他们正在成长的孩子不愿意把门打开，让他们进入自己的世界，而不是父母不愿意进入。

无法表达自己的人──不论是由于贫穷，或是由于不自由，或者单单因为自己心灵的封闭，而无法表达自己的人，我最同情。

对我最重要的，安德烈，不是你有否成就，而是你是否快乐。而在现代的生活架构里，什么样的工作比较可能给你快乐？第一，它给你意义；第二，它给你时间。你的工作是你觉得有意义的，你的工作不绑架你使你成为工作的俘虏，容许你去充分体验生活，你就比较可能是快乐的。

当你的工作在你心目中有意义，你就有成就感。当你的工作给你时间，不剥夺你的生活，你就有尊严。成就感和尊严，给你快乐。

十四岁的MM，不见得知道所谓“在人生竞争的跑道上，跑得不够快就会被淘汰”，但是城乡差距、贫富不均是什么意思，永远不会忘记。有意思的是，这次的“失败启蒙”教给我的，不是“你以后一定要做那城市里的人”，而是，“你以后一定不能忍受城乡差距、贫富不均所带来的不公平”。也就是说，“失败启蒙”给我的教训，不是打入“成功者”的行列，而是，你要去挑战、去质疑“成功者”的定义。

MM，如果媒体不维持一种高度的批判精神，一个社会是可以集体变“笨”的是不是？香港的媒体在做什么呢？我看见很多香港人很辛苦地在争取普选，可是媒体还是把最大的力气和钱花在影星八卦上。那些力气和钱，为什么不拿来为香港的民主做点努力呢？提供公开论坛，激发公众辩论，挑战政府决策，培养年轻人独立批判精神……

至于人们的“期待”，那是一种你自己必须学会去“抵御”的东西，因为那个东西是最容易把你绑死的圈套。不知道就不要说话，傻就不假装聪明。你现在明白为何我推掉几乎所有的演讲、座谈、上电视的邀请吧？我本来就没那么多知识和智能可以天天去讲。

最平凡、最普通的恐惧吧？我恐惧失去所爱。你们小的时候，放学时若不准时到家，我就幻想你们是否被人绑走或者被车子撞倒。你们长大了，我害怕你们得忧郁症或吸毒或者飞机掉下来。 我恐惧失去所能。能走路、能看花、能赏月、能饮酒、能作文、能会友、能思想、能感受、能记忆、能坚持、能分辨是非、能有所不为、能爱。每一样都是能力，每一种能力，都是可以瞬间失去的。

但是，我不敢企求，因为，我也觉得，刚成年的人跟母亲太亲近、太“乖”，恐怕代表着他本身的人格独立性不够完整。我渴望和你们保持儿时的亲密，但是又知道这是不可能的幻想。我其实是一个非常不典型的亚洲母亲了，而且还一直认真地在上你和菲利普给我的“课”。

十六岁的菲利普，在我们做过多次的实验后，曾经下过这样的观察归纳，他说：“妈，我觉得，差别在于，欧洲人是看年龄的，譬如在德国学校里，你只要满十四岁了，老师便要用‘您’来称呼学生。但是，中国人看的不是年龄，而是辈分，不管你几岁，只要你站在你妈或爸身边，你就是‘小孩’，你就没有身分，没有声音，不是他讲话的对象。所以，他才会眼睛盯着你的妈或爸发问，由‘大人’来为你代言。”

 
