#+title: Don't base your business on a paid app

[原文地址](https://signalvnoise.com/posts/3956-dont-base-your-business-on-a-paid-app)

At a buck or few per app, how could it be otherwise? That type of pricing will work for Angry Birds and a handful of other games, but very poorly for most other types of software products. The scale you need, the sustained influx of new customers, well, it’s a place for mega stars, and people who think they can beat the odds at becoming just that. 一个App几美元，这种定价策略只适合于游戏但是不适合其他软件产品，因为这种策略需要规模，需要持续的新用户流入。

That’s why I’ve been discouraging people from chasing dreams of a successful, sustainable software product business by pursuing paid apps. Far better be your odds at succeeding with a service where the app is simply a gateway, not the destination.  理想方式更应该是做service, 然后将app作为入口。

Apple and Google both benefit from having apps be as cheap as possible. For Apple, that means people will buy an iPhone more readily when the cost to fill it with software is near nil. For Google, it means app makers have to shove ads into products to make them pay. Win-win-lose.  Apple和Google从这些廉价的APP中获益。人们会更加愿意购买iPhone，并且google则可以将更多的ads接入。

What’s good for platform makers is often not good for those who build upon it. That’s where the whole picking up pennies in front of a steamroller comes from. Yes, a few may be quick enough to pickup enough pennies to fill a jar, but for most, it’s not a wise trade of risk vs reward.
