#+title: Don't Call Yourself A Programmer

原文链接 http://www.kalzumeus.com/2011/10/28/dont-call-yourself-a-programmer/

-----
*90% of programming jobs are in creating Line of Business software* 大部分编程工作都是编写商业相关的软件.
#+BEGIN_QUOTE
Most software is boring one-off applications in corporations, under-girding every imaginable facet of the global economy.  It tracks expenses, it optimizes shipping costs, it assists the accounting department in preparing projections, it helps design new widgets, it prices insurance policies, it flags orders for manual review by the fraud department, etc etc.

Software solves business problems. Software often solves business problems despite being soul-crushingly boring and of minimal technical complexity. 解决商业问题，虽然无聊并且没有技术挑战

It does not matter to the company that the reporting form is the world’s simplest CRUD app, it only matters that it either saves the company costs or generates additional revenue. 可能这个软件仅仅是一个最简单的CRUD app, 但是没有关系，只要它可以帮助公司节省成本或者是产生额外收入.

There are companies which create software which actually gets used by customers, which describes almost everything that you probably think of when you think of software.  It is unlikely that you will work at one unless you work towards making this happen.  Even if you actually work at one, many of the programmers there do not work on customer-facing software, either.
#+END_QUOTE

-----
*Engineers are hired to create business value, not to program things* 工程师价值在于创造商业价值，而不只是编程
#+BEGIN_QUOTE
Businesses do things for irrational and political reasons all the time (see below), but in the main they converge on doing things which increase revenue or reduce costs.  Status in well-run businesses generally is awarded to people who successfully take credit for doing one of these things.  (That can, but does not necessarily, entail actually doing them.)

The person who has decided to bring on one more engineer is not doing it because they love having a geek around the room, they are doing it because adding the geek allows them to complete a project (or projects) which will add revenue or decrease costs.

 Producing beautiful software is not a goal.  Solving complex technical problems is not a goal.  Writing bug-free code is not a goal.  Using sexy programming languages is not a goal.  Add revenue.  Reduce costs.  Those are your only goals.
#+END_QUOTE
每一个公司都有profit center和cost center. 哪些是profit centers呢？就是那些有收入的部门，除此之外都是cost centers. 尤其工程师是highly paid cost centers```Profit Centers are the part of an organization that bring in the bacon: partners at law firms, sales at enterprise software companies, “masters of the uniquote” on Wall Street, etc etc.  Cost Centers are, well, everybody else.```

*You really want to be attached to Profit Centers* because it will bring you higher wages, more respect, and greater opportunities for everything of value to you.

-----
*Don’t call yourself a programmer* 顺着上面的逻辑，那么不要称呼自己为程序员

#+BEGIN_QUOTE
“Programmer” sounds like “anomalously high-cost peon who types some mumbo-jumbo into some other mumbo-jumbo.” 因为程序员听上去像是一个高开销的人员，整天瞎折腾。

Instead, describe yourself by what you have accomplished for previously employers vis-a-vis increasing revenues or reducing costs.  If you have not had the opportunity to do this yet, describe things which suggest you have the ability to increase revenue or reduce costs, or ideas to do so. 相反强调自己中创造价值和减少成本的工作。如果你没有机会做过这种工作的话，那么强调自己能够完成这类工作的能力。

下面是两个这类的例子

There are many varieties of well-paid professionals who sling code but do not describe themselves as slinging code for a living.  Quants on Wall Street are the first and best-known example: they use computers and math as a lever to make high-consequence decisions better and faster than an unaided human could, and the punchline to those decisions is “our firm make billions of dollars.”  Successful quants make more in bonuses in a good year than many equivalently talented engineers will earn in a decade or lifetime.

Similarly, even though you might think Google sounds like a programmer-friendly company, there are programmers and then there’s the people who are closely tied to 1% improvements in AdWords click-through rates.  (Hint: provably worth billions of dollars.)  I recently stumbled across a web-page from the guy whose professional bio is “wrote the backend billing code that 97% of Google’s revenue passes through.”  He’s now an angel investor (a polite synonym for “rich”).
#+END_QUOTE

-----

*You are not defined by your chosen software stack* 不要讲自己限制在一个software stack里面.
#+BEGIN_QUOTE
In the real world, picking up a new language takes a few weeks of effort and after 6 to 12 months nobody will ever notice you haven’t been doing that one for your entire career.

Talented engineers are rare — vastly rarer than opportunities to use them — and it is a seller’s market for talent right now in almost every facet of the field.  Everybody at Matasano uses Ruby.  If you don’t, but are a good engineer, they’ll hire you anyway.

#+END_QUOTE

-----

*Co-workers and bosses are not usually your friends* 多么地现实!

*You radically overestimate the average skill of the competition because of the crowd you hang around with:*  Many people already successfully employed as senior engineers cannot actually implement FizzBuzz.  Just read it and weep.  Key takeaway: you probably are good enough to work at that company you think you’re not good enough for.  They hire better mortals, but they still hire mortals 因为你长期混的圈子的缘故，所以会过高地估计竞争的平均skill. 我理解的意思是，比如你身边都是和自己级别相当的码农，大家之间相互比较编程水平，所以理所当然地认为那些比较senior工程师水平会高很多很多，但是事实却并不是这样的。

-----
*“Read ad.  Send in resume.  Go to job interview.  Receive offer.” is the exception, not the typical case, for getting employment* 大部分工作机会并不是从广告上找的，而是别人介绍的。

#+BEGIN_QUOTE
Most jobs are never available publicly, just like most worthwhile candidates are not available publicly (see here).  Information about the position travels at approximately the speed of beer, sometimes lubricated by email.  The decisionmaker at a company knows he needs someone.  He tells his friends and business contacts.  One of them knows someone — family, a roommate from college, someone they met at a conference, an ex-colleague, whatever.  Introductions are made, a meeting happens, and they achieve agreement in principle on the job offer.  Then the resume/HR department/formal offer dance comes about.

This is disproportionately true of jobs you actually want to get.  “First employee at a successful startup” has a certain cachet for a lot of geeks, and virtually none of those got placed by sending in a cover letter to an HR department, in part because two-man startups don’t have enough scar tissue to form HR departments yet.  (P.S. You probably don’t want to be first employee for a startup.  Be the last co-founder instead.)

There are many reasons why most hiring happens privately.  One is that publicly visible job offers get spammed by hundreds of resumes (particularly in this economy) from people who are stunningly inappropriate for the position.  The other is that other companies are so bad at hiring that, if you don’t have close personal knowledge about the candidate, you might accidentally hire a non-FizzBuzzer.
#+END_QUOTE

-----
*Networking: it isn’t just for TCP packets* 不要一说到networking就想到TCP packets. networking还表示各种social. Networking just means a) meeting people who at some point can do things for you (or vice versa) and b) making a favorable impression on them.

#+BEGIN_QUOTE
There are many places to meet people.  Events in your industry, such as conferences or academic symposia which get seen by non-academics, are one.  User groups are another.  Keep in mind that user groups draw a very different crowd than industry conferences and optimize accordingly. 用户组和研讨会是两个选择，两个场合的人群也有些差别。

Strive to help people.  It is the right thing to do, and people are keenly aware of who have in the past given them or theirs favors.  If you ever can’t help someone but know someone who can, pass them to the appropriate person with a recommendation.  If you do this right, two people will be happy with you and favorably disposed to helping you out in the future. 乐于助人

You can meet people over the Internet (oh God, can you), but something in our monkey brains makes in-the-flesh meeting a bigger thing.  I’ve Internet-met a great many people who I’ve then gone on to meet in real life.  The physical handshake is a major step up in the relationship, even when Internet-meeting lead to very consequential things like “Made them a lot of money through good advice.”  Definitely blog and participate on your industry-appropriate watering holes like HN, but make it out to the meetups for it. 虽然可以在intenet上认识许多朋友，但是真实世界的见面依然意义重大。因为我们都是monkey brains:)
#+END_QUOTE


-----
*Academia is not like the real world*

#+BEGIN_QUOTE
Your GPA largely doesn’t matter (modulo one high profile exception: a multinational advertising firm).  To the extent that it does matter, it only determines whether your resume gets selected for job interviews. 大部分时候GPA没有任何意义.

Your major and minor don’t matter.  Most decisionmakers in industry couldn’t tell the difference between a major in Computer Science and a major in Mathematics if they tried. 在工业界对你所读专业没有任何兴趣.

Your professors might understand how the academic job market works (short story: it is ridiculously inefficient in engineering and fubared beyond mortal comprehension in English) but they often have quixotic understandings of how the real world works. 通常教授可能了解学术界的job market是如何工作的，但是却不怎么了解工业界的job market.

The prof in charge of my research project offered me a spot in his lab, a tuition waiver, and a whole $12,000 dollars as a stipend if I would commit 4~6 years to him.  That’s a great deal if, and only if, you have recently immigrated from a low-wage country and need someone to intervene with the government to get you a visa. 只有当你从非常贫穷的国家移民过来，并且需要有人帮你搞定visa时候，才考虑这种deal.
#+END_QUOTE

-----
*How much money do engineers make?*

#+BEGIN_QUOTE
In general, big companies pay more (money, benefits, etc) than startups.  Engineers with high perceived value make more than those with low perceived value.  Senior engineers make more than junior engineers.  People working in high-cost areas make more than people in low-cost areas.  People who are skilled in negotiation make more than those who are not.

There are other benefits like “free soda”, “catered lunches”, “free programming books”, etc.  These are social signals more than anything else.  When I say that I’m going to buy you soda, that says a specific thing about how I run my workplace, who I expect to work for me, and how I expect to treat them.  (It says “I like to move the behavior of unsophisticated young engineers by making this job seem fun by buying 20 cent cans of soda, saving myself tens of thousands in compensation while simultaneously encouraging them to ruin their health.”  And I like soda.)  Read social signals and react appropriately — someone who signals that, e.g., employee education is worth paying money for might very well be a great company to work for — but don’t give up huge amounts of compensation in return for perks that you could trivially buy. 清楚解读各种benifits传递出来的含义.
#+END_QUOTE

-----

*How do I become better at negotiation?*

#+BEGIN_QUOTE
a)  Remember you’re selling the solution to a business need (raise revenue or decrease costs) rather than programming skill or your beautiful face.

b)  Negotiate aggressively with appropriate confidence, like the ethical professional you are.  It is what your counterparty is probably doing.  You’re aiming for a mutual beneficial offer, not for saying Yes every time they say something.

c)  “What is your previous salary?” is employer-speak for “Please give me reasons to pay you less money.”  Answer appropriately.

d)  Always have a counteroffer.  Be comfortable counteroffering around axes you care about other than money.  If they can’t go higher on salary then talk about vacation instead.

e)  The only time to ever discuss salary is after you have reached agreement in principle that they will hire you if you can strike a mutually beneficial deal.  This is late in the process after they have invested a lot of time and money in you, specifically, not at the interview.  Remember that there are large costs associated with them saying “No, we can’t make that work” and, appropriately, they will probably not scuttle the deal over comparatively small issues which matter quite a bit to you, like e.g. taking their offer and countering for that plus a few thousand bucks then sticking to it. 当你们达成协议，确定要hire你的时候，在来决定讨论薪水。

f)  Read a book.  Many have been written about negotiation.  I like Getting To Yes.  It is a little disconcerting that negotiation skills are worth thousands of dollars per year for your entire career but engineers think that directed effort to study them is crazy when that could be applied to trivialities about a technology that briefly caught their fancy.
#+END_QUOTE

-----
*How to value an equity grant* 如何确定期权价值. 我们可以假设一个rand(100)的随机数
#+BEGIN_QUOTE
0~70: Your equity grant is worth nothing. 一文不值
71~94: 和你在大公司高工资所赚的钱差不多
95~99: Your equity grant is a lifechanging amount of money. 虽然你依然不会觉得very rich, 但是不会觉得说"后悔当初去xxx公司"
100: You worked at the next Google, and are rich beyond the dreams of avarice.  Congratulations.
#+END_QUOTE

-----
*Are startups great for your career as a fresh graduate?* 毕业生加入startup是否合适

#+BEGIN_QUOTE
The high-percentage outcome is you work really hard for the next couple of years, fail ingloriously, and then be jobless and looking to get into another startup.  If you really wanted to get into a startup two years out of school, you could also just go work at a megacorp for the next two years, earn a bit of money, then take your warchest, domain knowledge, and contacts and found one. 很大的可能性是努力工作，失败，失业，然后加入另外一个startup. 如果你真的想毕业就去startup, 失败之后最好再去大公司工作两年，赚些自己可以支配的钱，学习一些领域知识，然后在考虑加入创业单位

Working at a startup, you tend to meet people doing startups.  Most of them will not be able to hire you in two years.  Working at a large corporation, you tend to meet other people in large corporations in your area.  Many of them either will be able to hire you or will have the ear of someone able to hire you in two years.
#+END_QUOTE

-----
*So would you recommend working at a startup?* 是否加入创业公司，更像是一种生活方式的选择。

#+BEGIN_QUOTE
Working in a startup is a career path but, more than that, it is a lifestyle choice.  This is similar to working in investment banking or academia.  Those are three very different lifestyles.  Many people will attempt to sell you those lifestyles as being in your interests, for their own reasons.  If you genuinely would enjoy that lifestyle, go nuts.  If you only enjoy certain bits of it, remember that many things are available a la carte if you really want them.  For example, if you want to work on cutting-edge technology but also want to see your kids at 5:30 PM, you can work on cutting-edge technology at many, many, many megacorps.
#+END_QUOTE

-----
*Your most important professional skill is communication*

#+BEGIN_QUOTE
Remember engineers are not hired to create programs and how they are hired to create business value?  The dominant quality which gets you jobs is the ability to give people the perception that you will create value.  This is not necessarily coextensive with ability to create value. 帮助你获得jobs的主要因素，不是因为你有能力创造价值，而是你有能力让人相信你可以创造价值。有能力，和别人相信你有能力，是完全不一样的。

Communication is a skill.  Practice it: you will get better.  One key sub-skill is being able to quickly, concisely, and confidently explain how you create value to someone who is not an expert in your field and who does not have a priori reasons to love you.  If when you attempt to do this technical buzzwords keep coming up (“Reduced 99th percentile query times by 200 ms by optimizing indexes on…”), take them out and try again.  You should be able to explain what you do to a bright 8 year old, the CFO of your company, or a programmer in a different specialty, at whatever the appropriate level of abstraction is. 向外行人快速，准确，清楚地说明你所创造的价值.
#+END_QUOTE

-----
*You will often be called to do Enterprise Sales and other stuff you got into engineering to avoid* 你会被要求做enterprise sales以及一些原本在工程方面回避的问题. 这种sales其实很常见，你让别人使用你的lib,framework, system都是在做sales

#+BEGIN_QUOTE
Enterprise Sales is going into a corporation and trying to convince them to spend six or seven figures on buying a system which will either improve their revenue or reduce costs.  Every job interview you will ever have is Enterprise Sales.  Politics, relationships, and communication skills matter a heck of a lot, technical reality not quite so much.

When you have meetings with coworkers and are attempting to convince  them to implement your suggestions, you will also be doing Enterprise Sales.  If getting stuff done is your job description, then convincing people to get stuff done is a core job skill for you.  Spend appropriate effort on getting good at it.  This means being able to communicate effectively in memos, emails, conversations, meetings, and PowerPoint (when appropriate).  It means understanding how to make a business case for a technological initiative.  It means knowing that sometimes you will make technological sacrifices in pursuit of business objectives and that this is the right call.
#+END_QUOTE

-----
*Modesty is not a career-enhancing character trait* 谦虚并不是一个有助于职业发展的性格特点

#+BEGIN_QUOTE
Many engineers have self-confidence issues (hello, self).  Many also come from upbringings where modesty with regards to one’s accomplishments is culturally celebrated.  American businesses largely do not value modesty about one’s accomplishments.  The right tone to aim for in interviews, interactions with other people, and life is closer to “restrained, confident professionalism.” 美国人民并不喜欢对自己的成就表示谦虚，正确的态度应该是"克制但是自信地表现出自己的专业一面"

If you are part of a team effort and the team effort succeeds, the right note to hit is not “I owe it all to my team” unless your position is such that everyone will understand you are lying to be modest.  Try for “It was a privilege to assist my team by leading their efforts with regards to $YOUR_SPECIALTY.”  Say it in a mirror a thousand times until you can say it with a straight face. 除非你所在的位置太明显了(比如是项目负责人), 否则不要说"这次功劳是整个team的". 而应该说"非常荣幸可以用自己在哪方面专业技术帮助整个team完成project".

You might feel like you’re overstating your accomplishments.  Screw that.  Someone who claims to Lead Efforts To Optimize Production while having the title Sandwich Artist is overstating their accomplishments.  You are an engineer.  You work magic which makes people’s lives better.  If you were in charge of the database specifically on an important project involving people then heck yes you lead the database effort which was crucial for the success of the project.  This is how the game is played. 不要觉得这样是夸大其词.
#+END_QUOTE

-----
*All business decisions are ultimately made by one or a handful of multi-cellular organisms closely related to chimpanzees, not by rules or by algorithms* 所有的商业决定都是由一个或者多个多细胞，和黑猩猩有关的，有机体(也就是人)制定的，而不是算法。

#+BEGIN_QUOTE
People are people.  Social grooming is a really important skill.  People will often back suggestions by friends because they are friends, even when other suggestions might actually be better.  People will often be favoritably disposed to people they have broken bread with.  (There is a business book called Never Eat Alone.  It might be worth reading, but that title is whatever the antonym of deceptive advertising is.)  People routinely favor people who they think are like them over people they think are not like them.  (This can be good, neutral, or invidious.  Accepting that it happens is the first step to profitably exploiting it.) 好友关系

Actual grooming is at least moderately important, too, because people are hilariously easy to hack by expedients such as dressing appropriately for the situation, maintaining a professional appearance, speaking in a confident tone of voice, etc.  Your business suit will probably cost about as much as a computer monitor.  You only need it once in a blue moon, but when you need it you’ll be really, really, really glad that you have it.  Take my word for it, if I wear everyday casual when I visit e.g. City Hall I get treated like a hapless awkward twenty-something, if I wear the suit I get treated like the CEO of a multinational company.  I’m actually the awkward twenty-something CEO of a multinational company, but I get to pick which side to emphasize when I want favorable treatment from a bureaucrat. 穿着打扮
#+END_QUOTE

-----
*At the end of the day, your life happiness will not be dominated by your career.* work life balance.

#+BEGIN_QUOTE
Either talk to older people or trust the social scientists who have: family, faith, hobbies, etc etc generally swamp career achievements and money in terms of things which actually produce happiness.  Optimize appropriately.  Your career is important, and right now it might seem like the most important thing in your life, but odds are that is not what you’ll believe forever.  Work to live, don’t live to work.
#+END_QUOTE
