#+title: 学车经历

-----

今天（2011.12.17）终于过了科目三，可以坐等驾照了（还要等差不多2-3天吧）。我是在北方驾校学的C2皮卡，发票上面开出的日期是5月17日，安全法规课本上记录科目一考试时间是6月23日上午9点，计时手册模拟训练完成日期是7月10日，其他时间里程碑就不可考了，这就意味着从报名到真正拿到驾照大概有7个月。7个月啊，从短袖偏偏的少年，到包裹羽绒的少年，浪费了不少青春啊：（

发票上面显示我们是首先交了160元的考试费和工本费（科目一），然后交了200元的法培费，以及3740的皮卡双休64学时培训费（科目二时间）。总共加起来有160+200+3740=4100，也算是相当贵了的。此外我在科目二的时候做了2次模拟训练（一次50元），并且在科目三挂了一次补考（25元），全部花在驾校学车上的钱是4225。

当时是北方驾校来我们单位方便我们集体报名，差不多有100多人报了吧，没有进行体检就直接填写报名单了。当时给我们公司的优惠是提供了双休学车的计划，每周六日晚上5:00-9:00，也不用自己约车教练保证一定能够约上车，但是必须每周六日晚上都去。如果按照这样的计划学习的话，2个月就可以学完科目二，还是比较快的。另外还提供了一种优惠就是双休日只是确保一定可以约到车，这样一来时间可能会拖得比较长。但是最终没有选择计划一是因为女朋友在天津，如果按照计划一学习的话意味着两个月可能见不了面（虽然是下午5:00学车，但是因为北方驾校是在昌平一带，所以从我住的立水桥到那里基本也需要花去2个小时），所以还是选择了计划二，但是结果是并没有他们宣传得那么得到位可以确保每周都约上，这个后面再说。后来我也发现计划一也是打了折扣的，因为教练一般都住在比较远的地方，从北方驾校进城的昌68最后一趟是7:30，所以大部分学到7:30之后教练就回去了，我们在读卡站等到8:45刷卡。

说到刷卡，应该现在大部分驾校都用刷卡的方式签到了吧。科目一完成之后我就会被给到一张卡片，我们把自己的卡片放在教练手上，然后教练如果可以帮助我们约到车之后，就给我们打电话约时间，如果都OK的话那么教练就帮我们约车。练车当天我们到停车场从教练手里拿到卡，学车之前刷一次，学车之后刷一次，证明这段时间确实学车了。学车时间有3个段，8:00-12:00,1:00-5:00,5:00-9:00，发现了吗？下午和晚上是有时间冲突的，除非教练不吃饭。学车刷卡必须在前后15分钟内，完毕刷卡可以提前15分钟。刷卡需要附上你的指纹，这样就不会被冒充了，指纹采集是在学习科目一之前完成了的。

未完待续…

-----

科目一就是法律知识培训，教材是《道路交通安全法规与相关知识必读》，反正就是上两天的课，从早上9点左右到下午4点左右，挺累的。其实老师也没有讲什么内容，课堂上大部分人都在睡觉。但是老师时不时会叫我们仔细看一段内容或者是记录一些东西，比如当时知道了驻车制动（手刹）和行车制动（脚刹）以及发动机制动（档位），还有就是为了防抱死使用点刹（后来科目二知道点刹只是气刹时候用的，现在大部分汽车都是油刹而且都有ABS，所以要刹车直接踩下去就好了）。老师讲了这么多内容，我觉得最关键的点就是一定要慢点开车（但是后来在科目三因为转弯的时候过慢，教练觉得不爽直接让我挂了。后来同学和我说，安全是一方面的考虑，保持交通通畅也是需要考虑的）。教材的后面有试题库，我们考试的内容都是从试题库里面抽取的，好像是60道判断题40道选择题。第二天的时候在剩下的3个小时吧，老师会集中帮我们过一遍后面的试题库并且勾出重点出来。其实大部分题目呢，怎么说都是符合我们常识的，一眼就可以知道哪个是正确的哪个是错误的，所以同学们只需要关注那些不符合我们常识（就是按照我们自己的推理）的题目，另外一些题目可能就需要记住了，比如每个交通手势是什么意思，不过幸运的是这类题目不多。值得一提的是，教我们的老师相当的有文采，在课程结束之后让我们写下了几句我们自己都觉得吐血的话：
1. 我听的不是课，是方向
2. 发光体，爱生活
3. 我一定会尊严地生活着
4. 心存一份美好情感，做一个好人
5. 一个好人就是在明白了生活的真相之后，依然热爱生活
6. 时刻提醒振作起来
7. 学会劳动，学会生存，学会等待成功。让每一个明天都比今天奔向更远的地方。
8. 时势造就人，梦想让人变得特别
9. 我不同意你，但是我支持你，这是一种科学精神。
10. 从此生活完全可以更美好，我会常常想起这些话。
科目一考试是完全的电脑进行的，因为只有选择题和判断题目，只需要键盘上面的小键盘就可以进行输入了。一定要非常注意使用这些按键，一不小心按成了交卷就悲剧了。科目一考试90分是合格，否则就需要当场补考。科目一考试之前都会要求同学输入自己的指纹，这样在科目二学习时候刷卡需要配上指纹，以免顶替来学习。我记得自己的科目一成绩是95分，很一般。

未完待续…

-----

科目二就是各种专项练习，包括桩考和路考。桩考的过程非常简单包括贴库(把车从一个库贴着库开出去),倒库(把车从外面给倒到库里面来),移库(在库里面从一个库移到另外一个库).而路考项目非常多包括0.侧方停车(必考) 1.定点停车(必考) 2.半坡起步(必考) 3.连续障碍(过井盖) 4.单边桥 5.起伏路 6.限宽门 7.直角转弯 8.连续曲线转弯 9.百米加减档(废弃).首先3个必考，然后从剩余的6项里面选择2个(我当时考试科目就是连续曲线转弯以及单边桥).

很早之前就听说各个驾校约不上车这个情况，但是觉得这个不是一个问题，练习的时间长就长呗，反正我也不急立刻学完。但是很快就发现了，一旦开始学习之后发现如果训练时间没有跟上的话，那么会比较容易遗忘细节，难形成肌肉记忆或者通俗的说法就是”车感”.当然如果你像我一样认真学习的话，我觉得这个遗忘完全不是问题。如果愿意仔细琢磨每一个细节的话，那么非常不容易遗忘细节。但是即使是这样，也很难形成车感。不过我不太知道那些连续突击的人是否积累了车感，我猜想他们也是没有的。会容易遗忘是一个问题，最重要的问题就是，一旦开始学车之后过程可能会比较麻烦(这个之后会详细说),那么这个时候你就想早点完成这个过程，这个才是最重要的原因。所以给学车的同学一个建议，就是尽快学完，不是像教练说的时间长容易遗忘，而是你可能开始学习之后，自己就非常想快点学完。

第一天打电话给教练约车，老师就说周六周日都满了，要不给我调整到周一。因为我之前听说学车很难约到，所以马上给我约到车就很不错了，所以我就答应了。但是我发现不对，如果这样下去的话那么我可能永远都是周一练习的，所以我马上给教练说还是安排在周末吧，毕竟这个是报名时候就说好的。教练立刻不高兴了，甚至旁边有个教练说”操，别理他”.但是我的教练还是比较好的，说我两句之后就说那可能就到等一段时间了，说完就挂电话了。之后学车有几次我想临时修改一下时间，教练都觉得麻烦。所以给学车的同学另外一个建议，就是如果约好时间(比如说好周六上午，那么以后就每个周六上午都来)之后最好就不要更改了，尽量按照这个计划执行，教练不太喜欢更换计划。不过我觉得是可以理解的，因为我后来看到教练手里面有约摸50张学车卡，这就意味着必须协调好我们这些人的计划，还是非常不容易的。

学车的过程还是非常艰苦的。那个时候我住在立水桥城铁站附件，然后北方驾校是在昌平那一带。我约的时间是周六上午(8:00-12:00).有两种方法到那里，一个是做地铁到龙泽然后做公交昌68到北方驾校，这条路线可以学完回来，但是如果早上要去的话因为昌68没有那么早。另外一个方法就是做学校班车，但是学校班车6:30立水桥那里。我一般需要5:30就要起来，然后前一天需要买一些吃的东西早上吃好然后6:30赶到那里。夏天还好吧，但是冬天真的真的不愿意起来:(.那个时候在车上的时候就听歌，eminem的lose yourself,beautiful,skylar的invisible.现在每次听到他们的歌都会想起那段经历。谢谢你们了。

因为之前让教练调整了时间，不知道因为这个原因，还是因为夏天比较烦躁，总之第一次去练习的时候，感觉教练对我非常不友好。话他只会说一遍。记得我问他怎么调整座椅，他的回答是”你傻吗?就是这样拧上来”.然后第一次贴库的时候可能忘记了一个要领，他的回答是”你没听我说话吗?”。害得当时有很多问题不敢问他.:(.但是现在想起来还是可以理解他的，而且熟练之后只要他不需要给过多指导的话就不容易烦躁了。现在学完车后，回想起这些经历，觉得他还是一个很不错的人，可能这是他的教学方法吧(当然我不是觉得他这样说我我不生气).他教学比较严格，所以你必须仔细听多想，当你回过头来就会发现，这些对自己以后都是有好处的。

–to be continued.

-----

回想一下学习科目二的经历吧。

教练第一节课就让我练习换挡大概2个小时吧，然后就把我拉到练习路考的场地上让我熟悉一下如何驾车。练习换挡就是为了练习一下离合与档位之间的配合，并且练出一种感觉，能够不看档位就可以很方便并且正确地进行换挡。换挡的话必须从1-2-3-4-5逐级加上，因为如果不逐级加上而直接跳档的话，那么很可能因为油没有跟上而导致熄火。对于减档的话可以跳档减档，比如4-2,3-1但是最好只是限制跳1档。一开始不太明白档位，转速，油门和速度之间的关系，现在理解可能是这样的，不同档位对应不同的齿轮，可能5档齿轮最小(最大?I don’t know)这样转一圈的话路程更长。这就意味着如果仪表盘上相同转速的话，实际行驶速度的话5档会更快。，而转速是由油门控制的，如果油门开得越大，那么转速会越高。因为最终之间的关系是这样的，如果想要速度更快的话，必须使得1.油门尽可能开大，这样发动机(仪表盘)转速会越高 2.档位尽可能高，这样发送一圈可能走更远的距离。

让车开动起来的过程就像做爱一样，紧张又兴奋。主要是因为之前没有一次让车动起来的经历，当然自己在下面推车不算。1.系好安全带打左灯 2.踩下离合，挂2档(有的师傅说挂1档。其实差别不大，2档起步快但是可能对车比较损，1档起步慢但是对车比较好并且可以很快就到2档，所以可能以后实际开车还是使用1档。我猜想当时是师傅想快点). 3.踩下油门到1.5k-2k转 4.松下手刹然后看左镜后方没有车 5.然后慢慢抬起离合向前方行驶。然后沿着场地开始兜圈超车，然后期间教练会教我们大概如何换档。实际换档非常简单，如果需要加速的话那么首先让速度提起来，踩油门提起来之后然后踩离合换档。如果需要减速的话首先踩刹车让速度减下来然后踩离合换档。可能开始时候会有很多细节忘掉，比如转向的时候忘记打灯，或者是一些细节处理不好比如拐弯的时候方向盘打早了。我觉得这些都没有问题，时间长了的话都会记住并且处理好的。其实最重要的还是根据当时的路面情况作出处理。当然你一开始认为的路面情况可能和教练的看法不同，教练会说你是因为一开始自己并没有形成一个正确的对于路面行驶的看法，可能自己实际驾驶之后然后不断地思考的话，就会形成自己对路面的正确认识，这个是最重要的。

说说练习中的事情吧。对于桩考的话，教练都会教我们看车的点的，到某个点打多少圈然后怎么走，这些教练都会说的。没错，这些要领你需要记住，但是这还没完。我觉得完了之后你可能需要仔细想想为什么需要在这个点打，如果不在这个点打会有什么问题，如果过了这个点的话那么车的位置是什么样的情况，如果没有在这个点打的话那么后面我应该如何调整。我觉得这些问题最好思考一下，因为事实上考试的时候车可能和我们练习车不同，甚至位置都可能不太样，方向盘可能没有那么多圈。如果一味地按照练习的时候驾驶的话，那么很可能撞杆。所以我们必须应对一些紧急情况，比如在这个位置应该如何调整。这样考试的时候才可以随机应变。随机应变，应该是学习驾驶最应该注意的一点。随机应变对于同样重要，就好比单边桥和井盖，可能我们行驶时候会有点偏差，而这些最后考官是不关心的，他只关心你是否压线，是有压井盖，是否从单边掉下，练习的时候就如果和教练教的位置有偏差的话，这是一个好机会，给你机会让自己领悟如何进行调整。

– to be continued.

ps:因为她在天津每周都会见一次面，然后每周周六5:30起来，练到12:00回家收拾一下东西然后就出发去天津。那段时间还是比较累的，晚上可能也很晚到天津，但是一般她都会等我晚上一起出去吃饭，然后周日在天津呆一天周一早上7:00出发回北京上班。那段时间每周只有一天出去逛逛，要不就在家里自己弄饭吃。谢谢她的体谅:)

-----

科目二学完了就要科目二的考试了。教练最后一次练车练到上午10点之后，就让我去做一次模拟(然后让我考试前一天模拟一次，然后第二天考试)。模拟一次50块，分桩考模拟和路考模拟。考试如果你的桩考挂了的话那么路考直接不考，而模拟的话是分开如果桩考模拟失败的话可以模拟路考。通常来说大家都是在考前一天去模拟的，好比如果我下午考试的话那么上午模拟，第二天上午模拟的话那么前一天下午模拟。因为模拟的话可以知道考试的内容，所以还是有很多人去模拟的。我去的那天差不多有50个人在模拟。因为模拟场地和考试场地是一起的，所以如果模拟的话需要等待考试完成之后，通常考试10:30才完成，下午的话需要等到3:30之后才完成。这就意味着只有1:30左右的时间给我们50个人模拟，可想而知教练的态度了。如果你犯了非常小的错误的话，那么教练立刻让你下车。因为这个是模拟，所以大家可能并不纠缠，而教练也早点下班赚了50元。

第一次模拟心情非常紧张。桩考没有问题，但是我路考的时候，起步的项目都记住了系好安全带，打左灯，起步时候也没有熄火，侧方停车也没有问题，但是在定点停车扣了20分(侧方空隙太大),然后半坡起步的时候因为手刹没有放到底扣了20分(实话说那个手刹很紧)，就直接下来了。后来预约到星期一上午考试，所以我星期日下午去做模拟的。我还记得那个周末非常紧张，那个周六还专门申请加班来帮公司进行面试，然后周日很早起来再公司待着看harry potter。因为当时什么心情都没有，只想着要让这次模拟完美，这样明天考试就心情就比较舒服一些。但是很悲剧的是，虽然我再定点停车与半坡起步没有任何错误，但是在直角拐弯的时候，因为训练场地和我们考试场地的直角转弯不太一样，后来压线了，然后就直接下来。我记得当时还和教练说能不能直接给他100块让我开完:(.考官和我说明天考试科目就是直角转弯和井盖。那天非常郁闷，因为我井盖本来就不是很好，然后估摸是不是要再模拟一次。但是看看那里模拟要是重新排的话可能需要等很久，就没有直接回去了。教练还特意打电话问我模拟怎么样，我说我直接转弯压线了好像和训练不太一样。因为明天考试，所以当晚压力非常大…:(.10点钟就躺下了但是整个晚上睡不着觉，心里都在想着当时井盖需要注意哪些事情。

第二天去考试才发现，原来大家都和我一样的，晚上都没有睡好，很多人都是4点钟就醒了。所以考试之前没有睡着是很正常的，要是睡着的话，记得告诉我你的联系方式，我觉得你肯定是一个很有能力的人。我们被安排在房间里面等。因为考试人员超过60(还是80,我记不太清楚了)人，所以需要抽出20%来考其他项目。很不幸的是，我在里面，我的考试项目是连续曲线转弯和单边桥。当时我没有任何想法，基本上是抱着”这次肯定能过桩考,路考下次再说”的心态(因为如果考过桩考的话，那么下次补考直接考路考即可).桩考的时候我差点碰杆了，还是当时仔细想过应该如何调整，所以离杆非常近地到进来了。而路考就更加扯淡了， 我做梦都没有想到考官会在旁边提醒我说”往这边来点”。我虽然在我定点停车离前线还差一些距离停车了(被考官骂了,扣20分),但是后来没有什么事情.因为单边桥教练没有办法提醒，而我自己还是挺有把握的，所以最终过了。下车的心情当时真激动啊，下车之后第一个就是给她电话，把学车卡给教练之后，然后去上班了。当时，感觉天都蓝了.:)接下来就等教练电话学习科目三了。

–to be continued.

-----

教练非常希望我快点学完科目三，原因很简单，是因为学校准备改革对于科目三的教学，就是一个教练拉着7-8个人，每个人可能最多一次开两圈然后考试。如果尽快学习的话，那么教练还可以拿他的车让我正规地学习两次。后面练习的时间一次是晚上，一次是上午。科目三实际上没有太多的教学内容，就是一些实际驾驶时候需要处理的问题。比如起步之前一定要看后视镜，过人行道的时候一定需要在20米左右就看看是否有人穿过，右转弯(考试只有右转弯)不要压旁边的线以及一般要到车头过了人行道再转弯，转弯之后不要转到快车道而应该在慢车道上，过人行道或者是公交站牌前面脚备刹车，超车之后并车一定需要看到过了之后才并过来等这些事情，如果是晚上的话停车需要关掉近光灯打双闪，侧方停车的话一定需要看右后视镜等。我记得第一次开得很一般，第二次就开得好多了，加档减档都非常自如，偶尔侧方停车位置不是很好，练习完成之后就把卡片直接给训练队坐等科目三考试。

第一次科目三考试被分到了12月2号吧，因为12月三号周六参加了北京婚博会。哎，那天天气可能就意味着我可能不走运，那天是北京今年第一次下雪，而且因为12月2-4号是HIC(Hadoop In China)大会，而Doug Cutting在2号被邀请到来baidu演讲，哎，错过了和Doug Cutting这种重量级牛人交流啊.不过心里也没有什么特别遗憾，因为我觉得自己身边有很多以后会成为Doug Cutting的人，比如Dr Yang, Lin Shiding, BinLing Chang等人。那天天气特别的冷，到了那里大家脑袋上都头顶着白雪，被分好各自考试的车子并且排好顺序之后，大家就在班车上等。我记得我开得是6号车，那个考官长得满脸横肉。我被排到倒数第二。很不幸的是，那个满脸横肉的教练考试相当的慢，别的车队都考完了，我这里差不多猜到3/4.轮到我上车的时候已经快到11点了。可能我还是按照自己的节奏来吧，但是没有考虑到这个时候教练可能已经想吃饭了，而且这个教官自己的说的下雪天大家开慢点，我就真开慢了.:(.第一个是在直角路口，我没有直接拐弯而在等待考官说，这个时候考官说”怎么不拐了”.然后我才开起来，然后我当时解释说这个是我们教练说需要等待考官指示的，估计他当时对我就心里不舒服。第二个是在直线之后，我考虑路面问题没有加档，他又说了一句”你这么开要到什么时候啊”.我才意识到需要加档了。第三个是我在右转弯的时候，旁边有个三轮车在右边的人行道上，他说了一句”右转弯”,但是我觉得应该避让行人吧，所以我停了一下，这时他非常不高兴了。然后我右转弯之后转到了快车道上，这时候他说了”你怎么开的啊,教练是教你这么开的吗?行,回去吧”。哎，反正当时脑子里里面一篇空白。回到了原点之后，我和他磨了很久，但是最终没有磨过，拿了一个不合格的单子回家了。这么冷的天，本来想婚博会之前搞定驾照，然后又没有见到Doug Cutting,亏大了。回到训练队，申请了补考。

补考的时候安排在12月17号，当时有一个问题就是，如果这次考不过的话那么可能过年之前都没有机会了，心里还是有点压力的。但是驾校有一个流言，就是如果是周六周日的话特别好过，因为考官都想早点回去而且，而且和驾校达成了一个秘密协议似的。现在回想起来，可能我当时科目二有考官提醒，也可能是因为驾校为了提高通过率所以才这么做的。我是下午考的，12点就到了，在那里等到1点做校车去考场。考试时候，果然发现没有上次周五考试那么严格了，而且每个人只是开一小段距离即可。驾校教练开车在考试车辆后面跟着，开一段距离之后下一个考生就直接上去，而不是像往常一样开一圈。轮到我上去的时候，我仔细提醒自己每一个小细节，绕车子一圈半，安全带，手刹到底，打灯，看镜，然后慢抬离合。开起来之后，可能在50米左右吧，我从2加到了4档，然后在临近红绿灯之前50米将4档减到3档，右转弯之后考官就让我侧方停车。右灯，右反光镜，然后挂到二档，右拐一下然后立刻左拐接着回正。拉手刹摘档。当考官说我合格的时候，又激动了一回。虽然来说没有那么正规，但是总算是拿到驾照心里舒服好多了，以后也不用早起来这里了。考完之后立刻打车回家，然后等驾校给我信息让我去取驾照。

–to be continued.

-----

同期报名的同学一般都是托人领本的，但是我基本上算是比较后期学完的，没有人可以托只有自己去领本。为了让自己的学车经历稍微圆满一些，我特意选择早上坐班车去驾校领本。我拍下了当时等车的照片，可以看得出非常冷。

到了驾校把当时的报名发票，计时手册，乘车卡以及身份证给他们，就可以领取驾照了。然后后来在旁边的窗口还办理了一个建行（还是工行，我记不清楚了）的牡丹卡，说是为了能够方便缴纳交通罚款费用开通的卡。办理那卡透露了很多信息，希望以后没有什么事情。拿到驾照之后，还是做昌68回去。我记得那天昌68特别难等，差不多等了半个小时吧。回去的路上我在想可能以后都不会去那个地方了吧，可能就作为一段往事尘封起来。但是临走时拍了两张照片，也是为了时不时可以翻开来回忆回忆。

–the end.
