#+title: Employee Equity

[原文链接](http://blog.samaltman.com/employee-equity)

文章后面有一些sam altman对于改进股权分配和发放的建议. 不过我看不太懂, 也就是看个大概.

It’s very difficult to put precise numbers on this because the specifics of every situation matter so much.  Perhaps the best way to think about it is to try to come up with a total compensation package with the same expected value (using the company valuation of the last round, or a best-efforts guess if it’s been a long time since the round) as the employee would get at a big company like Google.  As an extremely rough stab at actual numbers, I think a company ought to be giving at least 10% in total to the first 10 employees, 5% to the next 20, and 5% to the next 50. In practice, the optimal numbers may be much higher. (10%给到前10个， 5%给剩下20个， 5%给剩下50个)

Most startups do a bad job of helping employees think about the value of their options.  At a minimum, any startup should tell a prospective employee what percentage of the company the equity grant represents (number of shares is meaningless).  Some startups are very hesitant to do this—they don’t want to disclose the number of shares outstanding. Employees should demand to know what percentage of the fully-diluted shares their stock options represent, and be very suspect of any startup that won’t tell them.

A specific question worth asking is some version of “so if I have 0.5% of company and it gets acquired tomorrow for $100 million dollars, will I get $500,000?”  There are many ways for this not to be the case—there can be a huge liquidation preference, for example—that most employees don’t know to think about. So it’s worth asking about a specific scenario.

UPDATE@2016-06: 陈利人前段时间在微博上写了一篇关于期权很通俗的 [[http://note.youdao.com/yws/public/redirect/share?id=8f65d66da5620d90ea75bbbe479c1738&type=false][文章]] ([[http://weibo.com/1915548291/DByel6vyP][2]]) ，也建议看看.
