#+title: 业余做研究的经验 - 田渊栋

天下什么样的观点都有，但有用的思路并不多。做研究是要分析，哪些思路能拧成
一股绳，哪些其实本质上相互矛盾，哪些需要妥协甚至放弃，哪些则是毫不动摇的
真理。把这些整理出来变成协调一致的理论，才能算是有了成果。要做到这个，是
需要有长久的积累功夫的。思路要系统化理论化，把每天想到的都放在一个大背景
和大框架下，时常拿出来反复思量推敲，慢慢地去粗存精，取本舍末，才能见别人
所未见。发别人所未发。

以我的经验，做任何工作，全神贯注是最好的选择，做完一件再做另一件。随意在
不同任务间切换所需要的代价是非常大的。同时做两件事情所需的时间，是先后或
者分别做两件事情所花时间的两倍不止，并且更麻烦的是工作质量不高。试想下花
十五分钟的写的破烂程序，却要花几个小时去调试它，还不如花三十分钟精工细作
来得有效。我见过有同时做很多任务，也做得很好的人。但我自己觉得不是那块材
料，还是老老实实地一件一件做完。

借通信的术语来说，大脑不擅长频分复用(同时干多件事)，但很擅长时分复用(
每次干一件事)。大脑更像激光而不是日光，要么不打开，一打开就在纸上烧洞的
。所以牛人们虽然平日里谈笑风生，但都有大脑周期性抽风的症状，这不是病，而
是大脑集中力的体现。真要每天工作十几个小时，把战线无限延长，虽说没功劳也
有苦劳，但效率如何很难讲，至少我是做不到高效率的。

读别人的文章，首先读到的是它的思路它的贡献，细节往往放在最后讲，这样显得
条理清晰，逻辑清楚，论证有据。但真实做研究则截然不同，往往是先找到正确的
细节，然后推广而成理论;先有乱七八糟但管用的方法，然后回头整理，扮一副堂
皇的样子出来见人。事实上，就如同哲学理论不能解决任何具体问题一样，一个不
为特定问题量身定做的理论，直接拿过来管用的概率是很小的。若是它真的管用(
比如说深度学习)，那么一定是有未被发现的深刻逻辑隐藏其中。因此，读的时候
，不要被文章中的各种卖点迷惑住，通过思考，通过重复别人的实验，想方设法找
出其中真正重要的东西，才是明路。

实验科学要怎么办呢?以我这半年在谷歌的经验，虽然要解决的问题截然不同，但
同样要遵循上述原则。一方面在已有解法上小修小补，找到能让效果更好的管用小
设计，让自己至少出点活有绩效，这时，细节决定成败;另一方面则要推翻现在的
解法，从大方向出发，思考现在手头做的是不是有长远意义，能否解决长远问题，
如果答案是否定的，那么就应该尽早开始做正确的事情。后者传统上来说是项目经
理要负责的，但是若是自己能提前想到，那效率会高很多。
