#+title: DDB入职当天

入职前天还去取了一下体检报告，有好几个指标都不太乐观：双侧淋巴结肿大，甘油三脂和血尿酸偏高，窦性心律过缓，甲状腺左侧叶结节，胆囊息肉，幽门口杆菌，双侧动脉弹性稍差。一个原因是因为缺少锻炼，另外一个原因则是因为吃主食（米饭）太多，还有就是饮食时间不规律。主食太多了会转换成为脂肪，导致超重和甘油三脂提高。血尿酸偏高可能是和家族遗传史有关系，我记得父亲经常痛风，所以他的血尿酸可能也偏高。胆囊息肉和油脂过高以及饮食时间不规律，以及睡眠时间太晚有习惯。息肉的原因很可能是因为胆汁没有办法分泌，积累下来就成为了息肉。

虽然情况不是特别糟糕，但是考虑到加入了一个创业公司，许多东西还不懂，短时间精神压力可能会比较大，所以自己需要特别控制这些指标，否则大概率会变得更加糟糕。少吃主食，早点睡觉，吃早饭，多喝水，以及适当的活动锻炼，希望后面从这里出来的时候，指标不要更加糟糕了。

接着就是入职当天的事情。因为公司离这边比较远，打车差不多需要30分钟，距离还行，就是需要避开早晚高峰。我打算6：30出发，晚上回去就直接睡觉了，也好，少点其他事情。早上7：00就到了，在外面晃悠晃悠等待了9点多，终于办理了入职。公司比较拥挤，桌子也不是很大，感觉自己离屏幕有点太近了，需要刻意把自己放的远些。

搭建环境没有什么障碍，接着就是说了下后面要做的事情。codebase看起来太费劲了，各种历史遗留代码以及新的代码混在一起，抽象也做的不是很好，往里面增加点东西需要捏着鼻子（不过哪个项目不是呢？）唯一的选择就是只关注自己需要加的代码，参考之前的代码， 写好之后做好测试。

一天下来感觉还是挺累的，而且和大家交流的也不多，到了晚上情绪稍微有点低落，想找人说说话。回去的时候，和出租车司机聊到这个，他倒是给了我不少安慰。他75年生人，学的是计算机软件，但是家里上面两代都是当兵的，所以他也算是被迫去当兵了，没有读硕士。他后来转去做了特种兵，在新疆和云南那边执行任务，后来肺部受损就退了下来，记了二等功（每个月4700的补贴，另外看病不用掏钱）。他说自己执行了17次特殊任务，每次都写好了遗书。从那边退下来之后，就越感觉到生命的可贵，越珍惜现在的生活，能活着就好。

----------

再接一篇那时候入职微软时候的情况

原以为amazon的工作环境（特指开发环境）已经够糟糕的了，但是来了微软之后才知道什么才是更加糟糕的。清一色的windows操作系统，开发和生产环境都是windows. 说几个从mac系统切换到windows系统的几个不适应的地方吧。

第一就是字体。windows上那个字体难看啊，看久了mac上的字体之后，觉得windows上的字体简直没有办法看。mac上的字看上去是比较圆润的，每个比划粗细看上去差不多，并且显示出来非常清晰。而windows上的字体，有些比划粗有些比划细，看上去就像是劣质油墨印刷机打印出来的。后面再折腾折腾，看看有什么办法可以让字体看上去，更加舒服一些。

第二就是软件。我常用的几个软件，比如evernote，微信，以及dropbox在windows上的体验和mac相比真的是差远了。以evernote来说吧，在mac上面切换笔记的时候，基本上是瞬间载入的，看上去就像是一个完全的本地应用。而在windows上面，撇开前面是说的字体了，切换笔记的时候看上去像是来了一次网页加载。而微信这个常用软件呢，看上去还凑合，但是从我观察到的一点来看，比如点击个人头像看详情的时候，mac上的信息明显比windows上丰富并且可以修改备注。后面再折腾折腾，看看能不能把这些常用软件设置更好，用起来更加舒服一些。

第三就是按键。常用的mac快捷键在windows下面都发生了变化，包括但不限于：剪切复制全选，截屏，关闭窗口，保存。好在同事给我推荐了一个工具叫做powertoys，可以shortcut mapping. 把常用的可以想到的快捷键一一映射，能缓解部分问题。

第四就是编程环境。虽说有了powershell这个东西，但是和unix/shell还是不太一样。不能说孰优孰劣，但是对于用惯了unix/shell的人来说真的不习惯。另外我还攒了一系列工作在linux/mac上面可以工作的脚本以及emacs配置等，在windows上彻底没有用途了。后面还想做些什么脚本开发的话，只能重新学习powershell这样的东西了。intellij肯定是没有办法使用了，只能使用高大上的visual studio. 或许这是一件好事情，看看不同的开发方式，是否真的可以更加有效率。

总之来这边的第一天真的是非常不适应。但是积极地看，这是一件好事情，至少在未来的半个年，熟悉这件环境对开阔自己的眼界，可能是会挺有帮助的。以前挺林仕鼎说windows的设计远远好于linux，我倒是要看看怎么个远远好于。有人说，如果一门编程语言没有改变你的思维，那么这么语言就不值得学习。嫁接过来，windows上面开发既然转变这么大，那么学习下来肯定会对自己的思维和眼界是有帮助的。
