#+title: 献给阿尔吉侬的花束(Flowers for Algernon)

奇怪的是，虽然我清晰地记得他们的声音，他们的面貌却始终模糊，我只能看到大概的轮廓。爸爸块头大但萎靡，妈妈瘦小而灵敏。时隔多年，现在听到他们相互争吵的声音，我有股冲动想对他们高叫：“看看他，看着查理，他得去厕所！” 当他们为了他吵架时，查理站在那里拉扯着他的红格子衬衫。他们之间的言语交锋闪烁着愤怒的火花，但那是他无法辨识的愤怒与罪过。

“查理，你让我惊讶。你在某些方面进步飞快，可是在需要做决定的时候，却还像个孩子。我不能帮你做决定，查理。你要的答案不在书本里，也不能靠别人来解决，除非你想一辈子当小孩。你必须在自我内部找到答案，感受到该做的正确事情。查理，你必须学习信任自己。”

“但一个人想要变聪明、获得知识，认识自己和世界，有什么不对吗？” “如果你读圣经的话，查理，你就会了解，人不可以比上帝要他知道的懂得更多，人不可以吃禁忌之树的果实。查理，如果你做了任何不该做的事─例如，和魔鬼或某些东西打交道─也许现在摆脱还不算太迟。或许你还能回复到以前善良、单纯的那个你。” “走回头路是不可能的，范妮。我没做错任何事。我就像个天生的盲人获得重见光明的机会，这绝对不是罪恶。很快地，世界各地就会有千百万像我一样的人。这是科学的功劳，范妮。”

智慧离间了我和所有我爱的人，也让我从面包店被赶出来。现在，我比以前更孤独。我怀疑如果他们把阿尔吉侬放回大笼子，和其他老鼠放在一起会发生什么事。它们会群起对付它吗？

我真希望这段记忆可以化作一张相片，这样我就可以把相片撕碎，当着她的面丢过去。我想要唤回消逝的时光，告诉她我无意让她失去养狗的机会。她可以拥有完全属于她的狗，我不会喂它、帮它刷毛或和它玩，我也绝不会让狗变得像我甚于像她。我只希望她和以前一样，陪我玩游戏。我从来不会想做任何可能伤害她的事。

突然间，了解自己能否像其他男人一样要求一个女人和我分享生活，变成很重要的事。光有智能与知识是不够的，我也需要拥有这个。现在我有种强烈的放松与解放感，觉得这是可能的。我在亲吻她时感受到的那股兴奋，已明显传达这种感觉，我确定和她在一起会很正常。她和艾丽斯不一样，她是那种原本就存在的女人。

“如果我们没有从外人，或从他们那里听到消息，我们就假设他们已在外面适应得不错。你必须了解，高登先生，这里不是监狱。州政府要求我们尽一切合理的努力找回病人，但我们没有配备可以随时密切监督四千人。有办法离开的都是那些低智能者，但我们接受的低智能者已愈来愈少。我们现在收留的很多是脑部受损，需要经常照护的病患，低智能者比较能自由行动，在外面游荡个一周左右，当他们发现没有留在外面的理由后，多数便会自己回来。这世界并不要他们，他们很快就会知道。”

开车离开沃伦之家，我不知道该想些什么。寒冷、灰扑扑的感觉笼罩在我四周……一种认命的无奈感。人们绝口不谈复健、治疗，或是把病人重新送回世界，没有人谈到希望。那种感觉就像活生生的死亡……或是更糟，根本不曾充分活着与了解。灵魂从一开始就在枯萎，并注定要对着每一天的时间与空间凝望。

“不要误解我的意思，”我说，“智慧是人类最伟大的恩赐之一，只是在追寻知识的过程中，对爱的追寻往往就被搁在一旁。这是我自己最近发现的结论。我可以把这个假设提供你参考：没有能力给予和接受爱情的智慧，会促成心智与道德上的崩溃，形成神经官能症，甚至精神病。而且我还要说，只知专注在心智本身，以致排除人际关系并因此形成封闭的自我中心，只会导致暴力与痛苦。 “
