#+title: 从0到1(From Zero To One)

中国是全球化的范例，它的20年计划就是成为今天的美国。中国已经直接复制了发达国家的有用之物：19世纪的铁路、20世纪的空调，甚至整个城市。

但科技不仅限于计算机技术。任何新方法，任何可以使事情更易完成的方法都是科技，这才是对科技的正确理解。

没有科技创新，也许中国能源产量在未来20年会加倍，但造成的空气污染同样也会加倍。如果印度的亿万家庭也都像现在的美国家庭那样生活——只用现代工具，结果也将是对环境造成毁灭性的破坏。如果全世界都用同一种旧方法去创造财富，那么创造的就不是财富，而是灾难。

在功能极端失调的组织中，要想获得晋升机会，告诉别人你在工作比挽起袖子做事更重要。（如果你所在的公司就是这样，你应该现在就辞职。）

在功能极端失调的组织中，要想获得晋升机会，告诉别人你在工作比挽起袖子做事更重要。（如果你所在的公司就是这样，你应该现在就辞职。）从另一个极端说，如果舍弃团体，一个孤独的天才可能会创造出经典的文学艺术作品，却不能创造出整个产业。初创公司遵守这样一个原则，你需要和其他人合作来完成工作，但也需要控制规模，使组织有效运转。

每一个错误的传统观念都像破灭的泡沫，但是泡沫破灭了，它给世界带来的改变却没有消失。

我认识一个40多岁的研究生，他在1999年开了6家不同的公司。（通常，40岁的研究生就很让人感觉奇怪，一次开6家公司更是疯狂，但是在90年代末，人们却认为这些特质是成功的组合。）

不能沉溺在宏大的愿景中，否则会使泡沫膨胀。自称可以成大事的人都不可信，因为心存改变世界之雄心的人通常要更加谦逊。小幅地循序渐进地成长是安全前进的唯一道路。

所有的公司都必须留出一定空间，不要事事都严格计划。你不知道你的事业会变成什么样，事先规划通常既死板又不现实。相反，你应该做些尝试，反复实践，把创业当成未知的实验。

不要贸然创造一个新市场。以现成的客户作为出发点创业才更有保障。成功者已经创造出被认可的产品，在此基础上加以改进，才是可取之道。

如果你的产品需要广告或营销人员去推销，就说明你的产品还不够好：科技应用于商业应该主打产品开发，而不是分销。在泡沫年代打广告显然都是浪费，唯一持久的成长是爆发式成长。

然而这些法则的对立面可能更正确： 1. 大胆尝试胜过平庸保守。 2. 坏计划也好过没有计划。 3. 竞争性市场很难赚钱。 4. 营销和产品同样重要。

美国人神话了竞争，赞颂竞争使他们免于排队领面包的窘境。事实上，资本主义和竞争的概念恰恰相反。资本主义基于资本的累积，而如果处于完全竞争之下，利润就会消失。企业家们从中获得的教训很清楚：如果你想创造并获得持久的价值，不要只是跟风建立一个没有特色的企业。

托尔斯泰在《安娜·卡列尼娜》中以下面这段文字作为开头：“幸福的家庭总是相似的，不幸的家庭各有各的不幸。”而在商业中，情形恰恰相反。企业成功的原因各有不同：每个垄断企业都是靠解决一个独一无二的问题获得垄断地位；而企业失败的原因却相同：它们都无法逃脱竞争。

越到高等教育阶段，这种现象越严重。优秀的学生自信地“往高处走”，直到竞争激烈到把他们的梦想吞噬殆尽。高等教育是一场困局，在高中时对未来有宏伟规划的学生，最后却陷入了与智力程度不相上下的同侪在传统职场上的竞争，如企业管理咨询和投资银行业务。为了获得把自己转变成一个墨守成规之人的特权，学生（或者家长）要支付数十万美元，并且学费仍在飙升，涨幅持续超过通货膨胀。为什么我们要对自己做这种事呢？

模仿性竞争的危害也许能解释为什么患有像阿斯伯格综合征（患者有社交障碍）这种病的人目前在硅谷更占优势。这些人对社会动态没那么敏感，因此不会盲从跟风。如果你对发明创造和电脑编程有兴趣，你就有勇气全身心投入其中，最终成为这些领域的精英。把技能运用到实际中时，你就不会那么容易放弃自己的信念：这可以使你免于陷入追求虚名浮利的竞争当中。

对于哈姆雷特，伟大是肯为了微不足道的理由抗争：每个人都会为重要的事进行斗争；而真正的英雄把他们个人的荣誉看得更重要，即使事情不重要，他们也会一争到底。这个扭曲的逻辑是人的天性，但是用在商业上却很致命。如果你能看出竞争不能带来价值的提升，而是充满破坏力，那你就比大多数人要理智。下一章我们就来讨论一下如何以清醒的头脑去打造垄断的事业。

如果你把短期增长看成重中之重，就会错过最重要的问题： 10年之后，你的公司还能存在吗？仅凭数字不能告诉你答案： 你必须认真思考公司的本质特征。

所以如果你准备扩张到相邻市场，不要“破坏”，要尽可能地躲开竞争。

把未来看成不确定的态度正好可以解释当今世界功能失调的原因，就是把过程看得比实质重要：当人们缺少具体的实施计划，他们就会依照惯例，尽量把多种选择组合起来。美国现在就是这样。在初中时，我们被鼓励积极参加“课外活动”。到了高中，目标高远的学生竞争得更激烈，个个都想生出三头六臂，变得无所不能。直到进入大学我们才发现，这10年的努力只不过是为一个完全不了解的未来填写了一张令人困惑的多元化的简历罢了。不管怎么样，也算是做好了准备——没有目标的准备。

而一个明确的愿景可以坚定人的信念。与其努力成为一个各方面都一知半解的庸才，还美其名曰“全能人才”，一个目标明确的人往往会选择一件最该做的事，并专心去做好这一件事。与其不知疲倦地工作，最终却只把自己变得毫无特色，不如努力培养实力，以求独霸一方。现今的年轻人并没有做到这些，因为他们周围的每个人都已经对明确的世界丧失信心。没有人会因为仅仅一方面特别杰出而进入斯坦福大学，除非他擅长的那一方面碰巧和传接球有关。

中国公众也知道“冬天”即将来临。局外人着迷于中国内部的巨大财富，但是他们没有注意到，富有的中国人正努力把自己的财产转移出国，贫穷一些的则能省就省，以求储备充足。中国各阶层人士都对未来严阵以待。

但是如果放在今天，会有人一开始就把这样的想象当回事儿吗？在20世纪50年代，人们广纳计划，而且探求计划的可行性。而今天，一个在校教师提出的富有雄心的计划肯定会被当成怪诞想法，弃之不用；稍有权势的人提出的长远愿景都会被嘲笑为狂妄自大。现在你仍旧可以在索萨利托的仓库里看到那个湾区模型，但那里也不过是一个观光景点罢了：这个对未来的宏伟规划现在只被当成过往的好奇心而已。

统计学家纳特·希尔弗对选举结果预测的准确度令人惊讶，但是更让人注目的是每四年一次的预测造成的话题有多大。现在让我们更着迷的是利用统计学预测未来几周国民的想法，而不是10年或20后的国家蓝图。

倒摩尔定律”（Eroom’s Law），揭示了药物开发面临的困境，自1950年起，批准投资10亿美元研发的新药数量每9年就会减半。

初创企业是你可以明确掌握尽最大努力的机会。你不只拥有自己生命的代理权，还拥有这世界上某个重要角落的代理权。而这一切都要从抵制不公平的概率主宰开始，因为你并不是一张被概率决定命运的彩票。

Founders Fund的绩效表现解释了这个扭曲的模式：Facebook是我们2005年的投资组合里表现最好的公司，回报比其他所投资公司加起来的还要多。帕兰提尔，是表现第二好的公司，带来的回报比刨除Facebook外所有公司加起来的还要多。这个高度不平均的模式并非偶然：我们其他的基金也都出现过这种情况。风险投资中最大的秘密是：成功基金的最佳投资所获的回报要等于或超过其他所有投资对象的总和。

我们的创始人基金，大约只关注五到七家企业，因为这些企业具有独特的基本面，我们认为它们以后都会拥有数十亿美元的价值。不管何时，如果你不关注事业本质，而是关注其是否适合多元化避险策略的财务问题，那么投资就像是在买彩票。而一旦你认为自己在抽奖，你就已经做好了亏损的心理准备。

但是人生对初创公司创建者和任何个人都不是投资组合。一个创业者不能把自身“多元化”：总不能同时运营十几家公司，然后期待其中一家会脱颖而出吧。而个人也不能为了人生多元化，同时留住十几种可能性差不多的职业。

第二是风险规避。人们害怕秘密是因为怕犯错。显然，秘密还没有经过主流的审查。如果你的目标是一生不犯错，你就不应该去探索秘密。将一生奉献于别人不相信的事情，在正确的路途上孑孓独行已是艰难，而在错误的路途上独自前行更是不可忍受。

第四是“扁平化”。随着全球化的推进，人们认为世界是一个同质的、激烈竞争的市场：世界是“平”的。鉴于这一假设，任何一个有雄心壮志的人，在探索秘密之前都会先问自己一个问题： 如果有可能发现新事物，难道全球人才库中更加聪明、更加有创造力的人还没有发现吗？这种怀疑的声音阻止了人们去探索秘密，因为身处的世界似乎大到任何个人都无法做出独特的贡献。

他的成功需要智慧，更需要坚信秘密的存在。如果你认为有些困难的事情无法完成，就不会做出尝试。相信秘密才是探索有效进行的关键所在。

那么要告诉谁呢？不管你必须要对谁说，都不要多讲。实际上，选择谁也不告诉和选择人人都告诉之间有一个黄金平衡——那就是公司存在的秘密。最好的企业家深谙此理：所有成功的企业都是基于鲜为人知的秘密创立的。好企业是改变世界的密谋者，当你与人分享秘密时，听众就成为了你的谋士。

但是高额的现金报酬会让员工取走公司已有的价值，而不是投入时间为未来创造新的价值。现金红利比现金薪酬要好——它至少取决于工作完成的好坏。但即使是所谓的激励报酬，也鼓励了短期想法和价值掠夺。任何用现金支付的薪资都关乎现在，而非着眼未来。

公司做得越好，首席执行官的薪酬就越少——投资过数百家的初创公司，我发现这一点最为明确。任何情况下，有风险资本注入的初创企业的首席执行官，年薪都不应超过15万美元。他以前是否在谷歌赚更多钱，或者他是否有大额抵押贷款要偿还和高额私立学校学费要付，都不是重点。如果一个首席执行官的年薪为30万美元，那他就变成了政客而不是创始人。高薪会诱使他保持现状，维持目前的收入，而不是与其他人一起发现问题，积极解决问题。相比之下，低薪的首席执行官则致力于为公司创造更多价值。

时间是最宝贵的资产，将时间浪费在不能长久合作的人身上得不偿失。如果你不能在工作上建立持久的关系，那么你就浪费了时间——即使纯粹从财务的角度来看，也是如此。

从一开始，我就想让PayPal员工紧密团结，而不是出于事务关系待在一起。我认为较为牢固的关系不仅能使我们更加开心、更加高效地工作，而且能使我们的职业生涯更成功，即使不在PayPal，亦是如此。因此我们打算雇用真正喜欢团队合作的人。他们必须有才华，但更为重要的是，他们要由衷地喜欢与我们共事。这就是“PayPal黑帮”的开端。

有才华的人不需要为你工作，因为他们有众多选择。你应该自问得再直截了当一些：为什么放弃去谷歌获取高薪和威望的机会，而去你的公司做第20位工程师呢？

总之，不要打福利待遇之战。奔着免费洗衣或宠物看护而来的人是不会成为你团队中一名合格成员的。你只需提供健康保险之类的基本福利，并许之其他公司无法提供的，即同优秀同事一道完成不可替代工作的机会。在薪酬福利上你可能比不上2014年的谷歌，但如果能就公司使命和团队给出好的回答，你便与1999年的谷歌站在同一高度。

界定角色可减少矛盾。公司里绝大多数矛盾是由同事竞争同一岗位引起的。由于初创公司初期的工作角色流动性大，所以面临很大的风险。消除竞争更易于建立长久的纯粹的工作关系以外的交情。

技术精英希望可以忽视销售，把销售人员都放逐到其他星球。我们都认为自己才是做决定的人，销售对我们没有用处，但这不是真的。每个人都有产品需要销售——不论是员工、创始人还是投资者。即使你的公司仅仅由你和电脑组成，也是如此。环视四周，如果没有看到销售员，那么你就是。

我们开发新的计算机技术来解决问题，这意味着我们拥有了一个超级专业的伙伴为我们提供高效的服务，却不和我们争夺资源。

先进的软件为此提供了可能性，但更为重要的是人类分析师、检察官、科学家、金融专家，没有他们的积极参与，软件毫无用处。

我们痴迷于大数据仅仅是因为觉得科技很奇特。我们为计算机单独取得的一些小成就而惊叹，却忽视了人类在计算机的辅助下取得的巨大进步，因为人类的参与淡化了其神秘性。沃森、深蓝电脑和越来越厉害的算法虽然很酷，但未来最有价值的公司肯定不是靠计算机单独解决问题，而是关注计算机如何才能帮助人类解决难题。

找到能源解决方案的小型市场并不容易——你可以致力于改变偏远岛屿以柴油为能源的现状，或者为敌对地区的军事设施进行快速部署建立模块化反应堆。看似矛盾的是，想要建立能源2.0公司，企业家面临的挑战首先是找到小型市场。

声名远扬之人与臭名昭著之人组成了大众情感宣泄的通道： 他们因成功而被赞美，因灾难而被指责。远古社会面临一个最重要的基本问题：如果无法解决冲突，社会就会四分五裂。因此，当瘟疫、灾难、暴力斗争威胁和平宁静时，将骂名转嫁到所有人一致赞同的替罪羊身上对社会是有益的。

苹果的价值主要依赖于某个人的个人愿景。这表明公司创造新技术所运用的这种奇怪方式通常与封建君主制很像，而不是我们想象中的更“现代”的组织。独树一帜的创始人能做出权威决策，激发员工强烈的忠诚度，提前做出未来几十年的规划。自相矛盾的是，由训练有素的专业人士组成的毫无人情味的官僚机构虽能够长久持续下去，却鼠目寸光。

然而，加上对稀有资源的争夺，我们很难看到全球稳定能够无限存续。没有新技术来消除竞争压力，停滞很可能爆发为冲突。万一爆发全球范围的冲突，停滞最终会演变为灭绝。
