#+title: 从跑步想到生活

最近一段时间跑步，每次开始都是有点不太情愿，有主观也有客观原因，比如昨晚上没有睡好觉，或者是单纯地觉得身体有点皱皱巴巴的。不过最后都是，喝了一碗黑芝麻糊，刷了一会微博之后，带上装备又出去跑步了。刚开始，身体或多或少有点不适，身体感觉没有力气，换气也有点不太顺畅，于是就刻意地降低速度下来。我给自己的目标是，今天只要跑完4km-5km即可，至于跑多久没有要求。跑步的目的就是为了可以让一天充满精力地应对工作和生活，也不是为了刷成绩或者什么的，所以想怎么跑就怎么跑，只要能坚持下来就行。

奇怪的是，一旦这么调整了心态之后，跑起来心里就没有那么多杂念了。我也刻意不去听咕咚App给我的计时，脑子里也没有任何计算，只是看着前面的路，然后不断地挪动自己的身体。期间也会注意到自己的身体发出的信号，比如膝盖稍微有点疼痛，或者是脚脖子稍微有点疼，或者是心脏或者是肺部有点喘不过气等等，我都只是放慢节奏而已，然后适应这种疼痛和不适。有时候跑下来，反而比之前计时得到的速度要快，当然也有慢的时候。不过那都不是什么事情，毕竟我的目标只是跑完这段路程。

近期我的生活也会有比较大的调整，这些调整在去年12月份和老婆断断续续地讨论了好长时间。我觉得近期生活的调整，可能和我平时的跑步很像，而之前这断断续续的讨论，则是为了能够让我更好地进入状态。到现在，我已经逐渐地调整好了自己的心里预期，开始接受这即将到来的生活调整。如果拿跑步来作类比的话，那这段生活调整的目的就是为了坚持下来未来的10年，我不在乎这10年需要跑多快跑多远，只要能坚持啊下来。如果继续类比的话，则可以预先到接下来会有诸多不适，各种问题，各种声音，而我所要做的则是倾听、调整、忽略或者是改变，不用带着太多的情绪波动，只需要关注眼前的路或者是眼下的问题就好。

我看了村上春树的书，我觉得跑步的确是件很有意思的事情。它是一门很像生活的运动，从中可以领悟到许多生活的道理。最奇妙的是，你不必经历过着一辈子，就可以学到其他人要一辈子才能学到的道理。我有时候在想，现在我只是跑5km，如果跑10km，半马，全马，会不会能得到更多的生命感悟呢？不过说到底，我现在跑步的目的是为了健康，还不是为了挑战自我，半马或者是全马在我未来的几年可能是不会被考虑的，10km或许可以多多尝试一下。总之，我想跑步的确是一门非常好的运动，我必须坚持下去。
