#+title: Fun

----------
比如说，从小老师说，这孩子不是笨，就是不努力。长大后你才发现，其实你不是不努力，你就是笨。

----------
file:images/hero-and-villain.jpg

----------

送领导茶叶，怎么说才能让领导知道茶叶很贵呢？

领导，这个茶叶够判你个无期了。

----------

你想想，如果是真正的科学，这可能吗？郭德纲不有句话吗？「比如我和火箭科学家说，你那火箭不行，燃料不好，我认为得烧柴，最好是煤，煤还得选精煤，水洗煤不好。如果那科学家，要是拿正眼看我一眼，那他就输了！」

-----
此时在咖啡厅里，旁边一对男女谈了半个多小时了，在聊写作。男的在鼓励女的搞创作，不过明显他自己没怎么写过东西，说来说去都是形而上的鸡汤话。这都谈了半小时了，一次“记得勤存盘”都没说过，可见干货有限。

-----
如何委婉地拒绝男生的表白？

https://www.zhihu.com/question/20613891/answer/66352281


中文版本

感谢您表示有兴趣让我作为你的女朋友。 然而，由于我今年收到了大量的爱情表白，我很遗憾地告诉你，现在无法接受你的表白。请注意，这种拒绝并不反映对你的任何负面评价。 今年，我特别幸运地接受了大量的爱情表白。 由于这种多样且富有希望的结果，我不可能接受所有的表白，无论他们如何的出色。

#+BEGIN_QUOTE
Dear Sir,

Thank you for expressing your interest in offering me a place as a girlfriend. However, due to the large amount of love confessions I received this year, I regret to inform you that I am unable to accept your confession at this time.

Please be aware that this rejection does not reflect any negative evaluation on your confession. This year I have been particularly fortunate in receiving an unusually large number of love confessions. With such a varied and promising result, it is impossible for me to accept all confessions, regardless of their outstanding confessing performances.

Again, I greatly appreciate your interest in loving me, and I offer my best wishes of success in your future love confession.

Best,XXX

Dean of Love Confession Acceptance and Financial Aid

Please do NOT reply directly to this email.
#+END_QUOTE


-----
世界上最不能相信的几句话

http://blog.renren.com/share/339618932/7590788371

1. 就想抱着你睡觉，我绝对不动手动脚。
2. 公车司机：后面还有一辆车。
3. 饭店服务员：您要的菜马上就好。
4. 小学老师，你跟我说实话，我不告诉你家长。
5. 初中老师：这节课体育老师有事不上了。
6. 高中老师：我就占你们一分钟。
7. 学习好的同学：这次又没考好。
8. 一群人来打球：我们都不会玩。
9. 街边小店：跳楼大甩卖。
10. 领导上台前说:下面我简单的说两句。
11. 我班女生说：你是我最好的朋友，说知心话的朋友。（过些时间我给她发信息，她回我你有事吗？）
12. 借钱时说:我有了马上还你,结果你不要他不还,你要了,他也不一定会还。
13. 医生：“我们已经尽了最大努力了”。
14. 见到久别的同学，存下各自的号码：有空常联系。
15. 明星：我们只是普通朋友。
16. 家长：压岁钱我给你存着。
17. 地震局说：专家分析,近几年没有大地震。
18. 太太： （出门前化妆时）马上就好！马上就好！
19. 老公： （一面盯着别的女生）她哪有你漂亮 ？
20. 食品包装：保证不添加防腐剂。
21. 女生：我们还是可以当朋友的。
22. 男生:乖,不会痛的。
23. 售票员说：往里边走！里边有坐！
24. 老师对最后一名的学生说：你很聪明，只是不努力。
25. 你人来就好了嘛 还带什么礼物嘛。
26. 小时候犯错或撒谎被揭穿时总会说:我下次再也不敢了。
27. 小姐：我是新来的,刚做这行没几天。
28. “有关部门已经介入调查”
29. 中巴车售票员：上来吧,保证有坐，马上就走，上车就走。
30. 公车司机最假的应该是：往里走，后面都没有人。（他大爷，后面的人脸都贴窗上了，他说没人）
31. 售货员:我真的不挣你钱,我这是按进价卖
32. “我再也不跟你玩了！”
33. 改天请你吃饭。
34. 其实你是个好人，就是我们不太适合。
35. 老师和家长:等你考完试想怎么玩就怎么玩,没人管你!
36. 中国足协：我们下届一定打进世界杯。
37. 我们最终要实现共同富裕

-----
在故宫走丢真是倍儿有面子，全紫禁城开始广播“请xxx听到广播后到乾清宫”，好像被皇上召见一样[doge]

-----
file:images/ultrasound-flying-birds.png

-----
@马伯庸

刚才发生的事。几乎把我本年度的尴尬余额都用光了……

有一个软件---我就不说是什么了免得有广告嫌疑---总之这东西有一个功能，你念十段话，它可以自动生成你的语音库，以后不管输入什么文字，它就可以用你的声音念出来。单字发音很像，不过连读起来很呆板，念得很慢，单字蹦。

今天中午跟朋友吃饭，我说这功能进化下去太可怕了，以后可以随意冒充你讲话。我现场演示了一下，打了一段文字：“我是马伯庸，我现在被人绑架了，请打100万给某某账号，否则性命难保，嘤嘤嘤”，然后软件就用我的声音给读出来了。大家纷纷表示感叹不提。

吃饱喝足，我开车送一朋友回去。我俩一上车，收费员凑上来收停车费。我放下车窗，一边问多少钱，一边发动了车子。

尴尬就在这儿了。我的车子一发动，手机就会自动用蓝牙连上车内音响，自动播放最近的音频。偏偏我听音乐喜欢开得很大声。

于是……在收费员亮出二维码的一刹那，车内外突然响彻我充满磁性的声音：我是马伯庸，我现在被人绑架了，请打100万给某某账号，否则性命难保，嘤嘤嘤”。

我看到收费员的手明显抖了一下，表情僵硬，强作镇定。坐在副驾的朋友也表情僵硬，仿佛她就是那个该死的绑匪。我想赶紧把这该死的声音关掉，回身一急，把手机掉到踏板下面，非得开门弯腰去捡才行。我一推门，收费员蹭地往后跳了一大步，大概是怕我暴起行凶灭口。我硬着头皮开车门，在“我”呆板的嘤嘤声中撅起屁股，够出手机，关上车门，飞快地开车逃走。在后视镜里，我看到收费员还在跟同伴指指点点。

副驾的朋友偏偏还要捅上一刀：“你当时直接关掉音响不就得了？干嘛非要去手机上关？”

-----
期末考试又要到了[笑而不语][笑而不语]


file:images/sugarcane-multi-usages.jpg

-----
“什么叫细思恐极？”

file:images/what-is-fear-after-deep-thought.jpg

一次住院，在看正追的漫画，巡床医生路过看了一眼，淡淡地说，哟，还看连载呀。我....

-----
额，诺诺的问一句，斯诺克很难么，不就是坐在那里喝水么？

-----
好像是这么个道理！

file:images/importance-of-appearance.jpg

-----
如何正确地使用微博广告！

file:images/weibo-ceo-with-ads.jpg

-----
张怡宁对女儿说，家里的奖牌你只能玩金牌，因为妈妈只有一块银牌；想玩银牌你去找王皓舅舅，他有的是，而且都是连号的；想玩铜牌你去找福原爱阿姨 ，她的铜牌也是连号的……

-----
为什么互联网模式这么高效？

file:images/why-internet-mode-so-efficient.png

-----
@t0data:聊表心意：形容不懂人情世故和浪漫的IT男在跟女生相亲或约会的时候，通过聊数据库表结构设计来找共同话题。

@李春同学:一表人才：形容每次都能通过新增一张数据库表来实现需求的人，这样的人真TM是个人才

@Easy 表里如一 ： 指数据库主从同步没有问题，主库和从库的表里边的数据都是一致的。

-----
Good wife can bring balance to life.

file:images/good-wife-bring-balance-to-life.jpg

-----
短篇悬疑惊悚小说『bug』——
合上电脑，刘照云摊在酒店的大床上，出差一个礼拜了，又是碌碌无为的一天，脑子里那个没查出来的bug依然挥之不去。“上线半个月了，就没特么顺畅过！”，窗外，夜已深，想起最近的种种不顺，此刻又独处异乡，不禁想撸……
叮咚一声门铃，隔着猫眼，一个身材曼妙，衣着火辣，露着大半E奶的美女。照云吸了一口气，把即将喷出的鼻血止住，“阿弥陀佛，逼打门前过，不日是罪过”，心里念念着把门打开。姑娘微微一笑，闪身入房，一手轻轻地推开照云急促的胸口，一手熟练地摘起请勿打扰的牌子，反挂在门外把手，轻轻关门，反锁，低头蹑脚走进房间，拉上窗帘，开启夜灯，半侧着坐在床边，摆出了最适合照云打量的坐姿和角度，“流程很顺畅，专业，没毛病”，还没动手，照云心里居然已经产生了包养的冲动，毕竟，顺畅这个词对他实在是太重要了。
“先冲凉，还是先上床呢”，摸着半个月前刚洗过的头发，照云脑子里对接下来的任务优先级有点犹豫，一时间，房间里的气氛竟有些凝滞。姑娘依坐在床边，挺了挺下坠的E奶，隐约听得到硅胶流动的声音，捋开长刘海，露出一脸标致的玻尿酸，开口说了第一句话，“老老实实掏五万块钱出来，否则我就喊救命，让你吃不了兜着走。”
照云顿时惊愕，色字头上一把刀，刀已经架在自己脖子上了。可他第一时间想起的既不是警察叔叔求救，也不是给文一打电话拆招，更不是给蒋总发微信借钱，照云此刻脑子里浮现的，竟然是一个月前那个毕业来公司实习的师妹，他只秀了秀在百度wenku前加wap就能复制文档的雕虫小技就在机房野合了，再看看眼前这位，恐怕不是共享个爱奇艺会员账号就能摆平的。然而，多年的宕机和无数次的闪退历练很快让照云恢复了镇静，毕竟也是见识过产品和研发季度review撕逼大场面的人，他深吸一口气，面无表情地盯着E奶，脑子里快速地用二进制计算着各种可能的计划和结果，试图从对方貌似完美的流程中挖出一个隐藏极深的bug……
5秒，照云用他250G的脑存，瞬间已运行完毕。
不慌不忙，照云拿起床头的便笺和笔，镇定从容，近十年来第一次用手和笔写下一行歪斜不堪的汉字，“我是聋哑人，请问你要干什么？”
D奶接过来看了一眼，玻尿酸一皱，无比嫌弃地瞥了照云一眼，又挺了挺胸口的硅胶，把她刚才说的话写了下来。
照云接过来看了一眼，叠好放进贴身的口袋，然后倒进沙发里，叉开双腿把蛋放松，呷了一口昨晚剩下的半杯拿铁，用袖子蹭了蹭嘴上的奶沫，厚厚的镜片后面，一副提前提前发版上线的嘚瑟，睥睨自雄，“这是你的笔迹，我现在手上有你做案的有力证据，你现在有两个路径，一是我打110抓你个现行，二是你现在脱衣服陪老子去冲凉，我就当什么都没发生过……”

-----
两个人在一起 不合适可以磨合 有争执了我可以道歉 出现了矛盾 我都可以妥协。但是... 如果你不积极配合党的十九大胜利召开 不聚焦聚力总目标 不为社会稳定和长治久安贡献力量 那么 对不起 我们没法做朋友！这是我的底线。

-----

@tombkeeper 我现在收到的私信主要是这两种：一是自己大学玩了四年现在要我帮他入侵教务处改成绩然后他就可以浪子回头侍奉双亲做个孝子，二是自己赌输了钱要我帮他入侵赌博网站把钱找回来这样他就可以侍奉双亲做个孝子。

-----
file:images/first-law-of-software-quality.jpg

-----
原来只要创建一套基于映射的词汇体系，就能解决我在评论别人的东西时只会说问题、优化和可能性，不会赞美和鼓励的社交难题……

file:images/what-it-actually-means.jpg

-----
国际共识，反导系统取名要霸气：美国反导系统叫TMD和NMD。后来中国也有了反导系统，叫CNMD。关键这些都是真的，“TMD”【Theater Missile Defence,战区导弹防御系统】、“NMD”【National MissileDefence, 国家导弹防御系统】、“CNMD” 【ChineseNational Missile Defence，中国国家导弹防御系统】。如果以后俄罗斯有了反导系统，可以预见，应该叫“RNMD”【RussianNational Missile Defence，俄罗斯国家导弹防御系统】。

继美国TMD、NMD、TNND，俄国RNMD、RTMD，中国CTMD、CNMD之后，以色列推出了MLGB【Medium Laser Guided Bomb,中程激光制导炸弹】。如果中国仿制了这个东西，那就是CNMLGB。

-----
媳妇问我,陈思诚媳妇那么好看他为什么还出轨?我说这事儿我儿子能给你解答!媳妇不相信,说怎么可能!我问儿子:爸爸给你买五百块钱一个的变形金刚,你为什么还抢别的小朋友的几十块钱的?儿子:因为这个我没玩过……网易网友

-----
火车上坐在一起的两个孩子一直在吵闹，旁人都忍不住劝他们安静一些，甚至和家长争执了起来，家长先是祭出“他们还是孩子啊”，见无效后又表示她也没办法，说孩子天生就这样。一旁的老奶奶叹了口气，语重心长地说：“不可能，不会有人天生就是臭傻逼的。”

-----
谢谢老大牵挂

file:images/xi-cares-me.jpg

-----
一网友在某游戏厅标着“未满18岁者禁足此区域”的角落拍到了这张照片。。。 机智少年前途无量

file:images/a-smart-kid-to-play-game.jpg

-----
一个在海外的小兄弟说公司有人长期占用会议室从事宗教活动，制造高分贝噪音。老板敢怒不敢言，就让他去说。他也不敢说，很苦恼。我说宗教信仰是每个人的自由，会议室人人都可以用，你也去供一尊我们的神仙。

-----
起点不重要！但是，首先，你得有个车库。。。

file:images/you-should-have-a-garage-first.jpg

-----
初二那年全家人去杭州玩，在西湖边上姑父感叹＂毛主席真好，还专门给雷锋建雷峰塔＂一家子都沉默了[拜拜]

-----
看到有人把powerpoint翻译成力量点数，真不错。“你的力量点数改好了没有？”、 “谁帮我找一个古风的力量点数模板！”、“马上要上台了，你把力量点数删掉最后一页！”

-----
今天去医院，医生说：你有15年的烟龄，你要是不抽烟，攒的钱都够买宝马了。 我一听瞬间这暴脾气就上来了。我就问：医生，你抽烟吗？医生说:我不抽啊。 我又问：那他妈你的宝马呢？ 医生说：在楼下停着呢，怎么了，我说：没事，我就问问。

-----
抛个NLP的case：NBA上赛季我就服两个队，勇士队：谁都打得赢，76队：谁都打得赢。

包小姐联系包小姐

-----
file:images/all-good-men-are-here.jpg

-----
大家注意了,是我刚刚亲身经历的,大街上有一些不法商贩打着卖樱桃的恍子,贩卖人体器官！一定要提高警惕！就在刚才有个人卖樱桃,我尝了尝,当我尝到第18个的时候,他压低声音,在我耳边问我"你要脸不?"我没敢要！！！多吓人你说！

-----
最近看到不少说法，说各种机会是风口，有说视频直播的，有说VR/AR的，有说人工智能的。从雷军说的风口上的猪都能飞起来这句话推断，等风口的多半觉得自己是猪。

-----
我妈说想再要个小孩，因为她觉得养育我的时候完全没有经验，做了很多错事伤害了我，她觉得亏欠了我，所以想再生一个小孩好好养育他。我怎么觉得这逻辑不大对呢。

这个号练废了，从新开个小号的感觉

-----
小哥：来两箱青啤。
服务员：常温的还是冰镇的？
小哥：你biang有病？！这个天喝冰镇的？！
服务员：冰镇的4度，常温的零下15度。
小哥：两箱冰镇的！........

-----
据说，下载「丁香医生」 App 后注册，即可激活 Instagram 。我试过了，是真的。今天是 Instagram 创始人的生日，他是丁香医生的忠实用户。

-----
我们是一家皮包公司。——Louis Vuitton

-----
Marvel角色中国装

file:images/cn-marvel-0.jpg file:images/cn-marvel-1.jpg

-----
alphaGo这样的项目在国内做的话: A厂:"老板我要做围棋项目。""一年能卖多少棋？" B厂:"老板我要做围棋项目。""棋牌室的广告有多大市场？" C厂:"老板我要做围棋项目。""游戏里下棋的机器人要穿低胸。"

-----
广州人民堆雪人是这样的……

file:images/snowman-in-guangzhou.jpg

-----
2015年最有深度的微型小说：

"老王，最近咋看着闷闷不乐？"

"唉，隔壁老打孩子"

-----
等我股票回本了，就跟你离婚。他淡淡地说。

听完后，她的心理暖暖的。

她想：这大概是最海枯石烂的承诺。

-----
机器会下棋我觉得算不上有威胁，那天机器会说相声了，人类估计就悬了，因为这说明机器彻底学坏了！

-----
秘密

妈妈说我是捡来的。我笑了笑，我不想说出一个秘密，怕妈妈伤心。

我知道，爸爸姓万，哥哥姓万，我也姓万，只有妈妈姓姜。

谁是捡来的，不说你也明白。嘘，我会把这个秘密永远藏在心中。

-----
汉语真是太复杂了…

男生的一生，分为四个阶段：

中文：
- 喜欢上一个人
- 喜欢上一个人
- 喜欢上一个人
- 喜欢上一个人

英文：
- like someone
- like to fuck someone
- like the lastone
- like to be alone

-----
转：顾客："可以用Apple pay吗？"

店员："别说英文，听不懂！"

顾客："……可以用苹果支付吗？"

店员："你怎么这么牛逼呐？你咋不用猕猴桃支付呢？！"

-----
周末轻松一下：某小区大门口停有一辆报废车，停了差不多快有10年了，轮胎没了车窗砸了。因为停的位置有点碍事，无数人打过电话请求有关各部门清理，可都互相扯皮就是没人管。直到有一天，车上被人用漆喷上了"民主自由"几个大字。第二天，车就不见了。。。

-----
噗...哈哈哈哈，一个耿直的孩子。

file:images/what-a-honest-boy.jpg

-----
"和一个20岁出头的年轻人聊天，她对生活感到麻木，十分悲观地认为自己这辈子也就这样了。我批评了这种错误的想法，20岁的时候我也曾有过同样的想法，直到后来30岁才知道人生可以更糟糕的，哪有 '这辈子也就这样了' 这么好的事情啊。"

-----
马化腾搞了个东西发到微信里，引发各路高富帅 矮矬穷 白富美 土肥圆人生感慨。

马云组织水军散布打开这个支付宝会被盗的消息，一传十十传百。

众屌丝黑压压的冲进支付宝，发现钱没有少，长长的松了一口气。

还发现支付宝有防盗保险卖，最高100万，于是毫不犹豫买一份。

马云给马化腾发了个短信：化腾，回扣已过账，合作愉快，明年乌镇大保健我请，云。

-----
二十多年了，雷打不动的3点收市，在2016年变了。

星期一，当券商工作的小明拖着疲惫的身躯提早回家的时候，一开门，老婆尴尬地说：那啥，你别误会，老王只是过来借辣椒面……

今天，隔壁老王连裤子都还没来得及脱，小明就回来了……

还有更悲催的：

今天隔壁老王敲门的时候，小明已经在家了……

-----

孩子们强烈要求期末考试加入熔断机制。

当一道题目有5%的考生不会做的时候，考试熔断暂停一个小时，大家一起冷静下来思考。

要是考试重新开考以后发现有7%的考生不会做，考试直接熔断结束，监考老师提前下班，每人都有一个保底60分，这样还能止损不至于太惨...

-----
共产主义在新时代的宣传图册

file:images/about-communism-0.jpg file:images/about-communism-1.jpg file:images/about-communism-2.jpg file:images/about-communism-3.jpg file:images/about-communism-4.jpg file:images/about-communism-5.jpg file:images/about-communism-6.jpg file:images/about-communism-7.jpg file:images/about-communism-8.jpg

-----
学校竟然把我一万元奖学金发到饭卡里去了，谁踏马要吃一万块钱食堂啊。

-----
据说是潘家园儿刚现身的尖儿货，诸君瞧准了别打眼。

file:images/buddha-of-star-wars-0.jpg file:images/buddha-of-star-wars-1.jpg file:images/buddha-of-star-wars-2.jpg

-----
以前猜测说澳大利亚企业中使用的机器学习模型最多就是决策树，今天发现可能连决策树都没用："我们从模型中发现了一个有趣的事实，我们的优质客户大多出生于1970年1月1日。"

-----
file:images/im-about-to-out.jpg

-----
运钞车一般有固定线路，一般配4名人员，一司机，一车长，俩护送带散弹枪，前2发为空弹，第三发为实弹，几乎都是保安公司的，胆比较小也没多少培训。运送银行网点一般为7到20个不等，银行现金量：小银行50到100万，大行现金多。快到中秋节了，我就不送月饼了，希望这条微博能改变你的命运！祝你们成功！

-----
【千分之三毫米的"鬼斧神工"】千分之三毫米，头发丝的1/25，这是数控机床都很难达到的精度。31岁钳工方文墨，一个体重200斤、身高1.88米的大块头，十年一日，每日苦练四小时，一年练坏200把锉刀，硬是锻出一双"神手"，纯凭手感打磨歼15、飞鲨战机核心部件，赞 [[http://t.cn/RyO6k1o][视频]]

我邻居，计算所的老专家，十年前上我家帮忙修过电脑。他看了一眼便说，"操作系统没了，有安装盘吗？"见我没有便用他的诺基亚8250连接机箱，然后开始按键。他手速极快但我还是看出只用了0和1两个键。看久了我开始打瞌睡，醒过来发现Win XP正在启动。"做个ghost吧，免得下次还得编"

-----
化学书17页拉瓦锡原图如下！

file:images/lavasi-in-book.jpg file:images/lavasi-in-real.jpg

-----
有个博导，在实验室门口挂牌，上面写着："追逐梦想，不勇敢试一试，你怎么知道自己不适合读博？"于是，他每年招到许多廉价又玩命儿工作的少年们，不行的就让他博转硕，好用的就让他延毕。这个故事告诉我们，科研需要智商，不要轻易上当。

-----
话说概率论里表示某个随机变量X的 "数学期望" 的常用符号是E(X)，其中E是英语里expectation的首字母大写。我的意大利教授竟然用的是P(X)，因为意大利语的 "期望" 一词是 previsione，这样就跟表示概率的字母P冲突了，而且跟我所有的概率书都不一样。我今天直到课快上完才意识到这点……

-----
[[http://www.zhihu.com/question/21044841/answer/17004365?from=timeline&isappinstalled=0][如何优雅地毁掉一个qq？ ]]

1.签名改成「恏蔂，感觉囨会洅爱了」之类的，一定要用火星文，昵称也要火星文

2.头像包括相册上传几张杀马特自拍，最好自己加上几个词或者让人看不懂的几句话，例如「说走就走的旅行」「殇」之类的，用夸张的滤镜调一下也行

3.QQ空间不定时发表说说，内容示例如下
#+BEGIN_QUOTE
《给你的、我再也给不了第二个人这么多》
《你爱上了别人。告诉我、即使心很痛》
《永远也不放手，因为我爱你》
《因为你的不在乎，让我学会了冷漠》
《我放弃你！因为你的不珍惜》
《你不是我的空气，为何没有了你，我会窒息》
《亲爱的，我的眼泪不多，请不要我再为你流泪好吗？》
#+END_QUOTE
仅供参考

4.QQ空间不定时转载日志，内容示例如下
#+BEGIN_QUOTE
《他们说，这样的女孩比较真》
《要珍惜胸前有痣的女孩》
《要珍惜脖子后面有痣的女孩》
《有一种女孩，注定被剩下》
《听说喜欢绿色的人都很坚强》
《做完这些，你们永远不分手》
《恋人做这X件事就不会分手》
《恋人一定要一起做的X件事》
《恋人绝对不可以做的X件事》
《这样的女孩你伤不起（伤不得）》
《做一个内心强大的女子，冷暖自知》
《做一个知性的女子，冷暖自知》
《做一个物质和精神都强大的女子》
《坚强的女子，会在阳光下，站成一棵树》
《原谅我就是这样的女子》
《请做这样的女生》
《请不要伤害那些外表开心的人（表面上微笑的人）》
《我有的时候真的想停下来抱一抱我自己》
《可不可以有一个人可以看出我的故作坚强（软弱）》
《可不可以有一个人可以看出我的逞强，可以保护我的脆弱》
《请别爱上XX座女孩》
《其实你看到的都是假象……十二星座之请别相信她（准到哭了）》
《星座之间的微妙关系》
《十二星座流泪的原因》
《十二星座爆发前的征兆》
《十二星座的不敢爱》
《十二星座的女子》
《是什么爱情誓言感动了十二星座》
《句句美得让人心碎》
《读起来微微心疼的句子（看到哪一句你哭了）》
《看到第X句我哭了》
《下面的话，读到哪句心痛了》
《总有XXX让你无法阻挡（泪流满面、黯然神伤……）》
《你，有没有这样的时候？突然很想哭，却难过得哭不出来》
《看第一条心已下沉，看了第X条泪已夺眶》
《读到第一句话我的眼睛就发涩了（就心痛了、泪流满面了……）》
《我不说话，只是怕话一出口就泪流满面（看完我就哭了……）》
《心疼了自己，却无能为力》
《有些话，一说出口，便泪流满面》
《英语老师不想让你知道的网站》
《英语四级秘密、绝密资料，不要告诉太多人》
《新东方老师不想让你知道的100个句型》
《发型师不想让你知道的秘密》
《那些XXX之后才懂得的事》
《孤独久了……》
《杜拉拉（亦舒、张小娴、张爱玲……）送给女孩的X句话》
《想开，看开，放开，人生就会好起来》
《不能在一起就不能在一起吧，也许一辈子也没那么长》
《你可以不长大，但你要牢记X句话》
《你可以不漂亮，但是这些是你必须学会的》
《你不可不知的XXX》
《你一定不知道的XXX》
《XXX都不懂的XXX》
《XXX的同学（朋友XXX）注意了》
#+END_QUOTE
摘自网上，仅供参考

同样是祖国的花朵，穷孩子却穿不起QQ秀，买不起欢乐豆，甚至充不起会员。春节将至，请让我们帮助这个孩子，让他能穿上好看的衣服，玩得起游戏~每个人请帮QQ帐号985786354的小朋友充值10QB，献上一份爱心，让世界充满爱。好人一生平安，世界因你而美丽！

气愤！把何老师都快气哭了，6月31号是何炅的生日，可是韩国主持人说何炅没有粉丝，没人送祝福。何炅就跟韩国人打个赌：如果这个说说在6月31号转不到20万，何炅不当主持了,转到200万.那几个韩国主持就要道歉.合同已签好了，喜欢看何老师主持快乐大本营的一定要转发！不为别的，就只为我们中国人争口气。

【爱心接力】天天向上节目主持人 矢野浩二 因在节目中说"钓鱼岛是中国的"而被日本 右 翼 分 子 视为 国 贼，在9月25日晚20点，被右 翼 分 子 下毒害死，享年38岁。看到的都转发一下，祝福浩二在天堂能够幸福。不转不是中国人

-----

file:images/chances-of-a-man-winning-an-argument.jpg

-----
一个广场舞大妈曾告诉我，如果她跳的足够快，她的孤独就追不上她；一位拾荒大叔曾经告诉我，如果他翻垃圾翻得足够仔细，便能找回丢失的自己；一位环卫工阿姨曾经告诉我，她每天都扫这两条街，七年了，都没扫干净心中的瑕疵；一位碰瓷的大爷曾经告诉我，只要他演的够逼真，就能骗过匆匆流逝的时光。

-----
有蚊香没支架，那你有指甲钳吗？

file:images/how-to-use-fly-driver.jpg

-----
陈佩斯的哥哥叫陈布达，因为他们的爸爸第一次出国演出是去了布达佩斯。#应该很多人都知道这个吧

我在某论坛看过一个段子，说陈佩斯有一次碰到一个叫李布达的人，也有个弟弟。陈佩斯特别惊喜，说莫非你弟弟叫李佩斯？李布达回答：不，叫李拉宫。

-----
英国《The Economist》杂志说在北京生活一天相当于吸 40 支烟。中国《The Beijinger》杂志辟谣说美国医生早就指出在北京生活一天相当于吸 1/6 支烟。

-----
据说，该图说明的是创始人股份被多轮稀释以后...

file:images/after-dilution.jpg

-----
早上雅虎公司预告CEO梅耶尔今天有重大事情宣布，市场期待处于困境中的雅虎有新举措。刚才，梅耶尔宣布：她已经怀孕，并且很可能是一对双胞胎女儿。也是好消息。

-----

file:images/how-similar-0.jpg

-----
这股民是真的操碎了心啊：有股民对阅兵仪式进行认真解读，推测国家决策意图: "最开始空军出场，然后人民群众艰苦做反弹，接着国外做空势力出场，紧接着国家队救市，最后空军大规模出动，国家队放鸽子

-----
"同志们，八年抗战开始了，要做好持久战准备"

file:images/hang-on-for-another-year.jpg

-----
在当当上，最高法院已统一变成**法院。新广告法就这样以出人意料的方式影响了我。

-----
刚到北京的时候，有朋友给安排了一个相亲。对方是个北方姑娘。我跟她说，中国人劝酒的习俗，是一种看对方笑话为目的，伤害对方身体为副作用，且杀敌一万自损三千的恶趣味。她说：不对！我问为什么不对。她说：说不好，反正就是不对！我觉得这人不讲理，就没再联络了。

-----
《愚公移山》 智叟：你在干嘛？ 愚公：我在移山啊！ 智叟：移山？你能移完吗！ 愚公：我移不完，我还有儿子移，我儿子移不完还有孙子移，我孙子移不完我还有重孙子移…… 智叟：你有女朋友吗？ 愚公：……不挖了！

-----
真实逗比新闻：1，上海一男子造谣自己因造谣而被拘留15日而被拘留15日。 2，美术馆反法西斯胜利70周年画展因庆祝反法西斯胜利70周年活动而暂停。 3，俄罗斯一票否决了乌克兰提出的取消俄罗斯一票否决权的安理会提案。

-----
意外阅兵悖论：政府宣布9月份要阅兵，但日期将是完全出人意料的。群众推测道：这说明不可能是9月30日，否则到了9月29日晚上就能猜到，不算出人意料。因此阅兵只能在9月1日到9月29日之间，但同理又可排除9月29日，依此类推……最终群众很放心地认为不会有阅兵。但完全出人意料的是，9月3日举行了阅兵！

-----
昨天去爬山，在一山崖下的石缝中，看到一本发黄的、脏兮兮的薄书，封皮已破损，但隐约可见"九阳"二字。心中不禁狂喜，这绝迹江湖多年的《九阳真经》终于让我发现。用木棍将其小心翼翼掏出后，怕附近游客和村民察觉，一把揣入怀中，坐在车里一言不发，浮想联翩，任督二脉，刀枪不入……到家后，把秘籍捧出来，怀着忐忑的心情翻看第一页——"九阳豆浆机说明书....

-----
楼下的煎饼摊子o2o了！只接受微信在线交流，现场拒绝讲话，用一个纸箱子把摊子包起来了！就露一个小洞。买煎饼的在微信订好，提出各种要求，下来扫个二维码即可取走煎饼，目前生意炸裂。城管不敢管，以为是高科技产业试点

东头的煎饼摊子对西头的o2o煎饼摊子发起了煎饼DDOS攻击，他们一口气定了200个煎饼不去取。东头的煎饼摊子对西头的o2o煎饼摊子发起了煎饼DNS劫持，他们派了个老太在路口给问路的人指路到路东头

-----
俗话说得好，篮球场上有四大"惹不起"：矮壮篮板怪、高瘦远投王、灵活死胖子、勾手老大爷。

-----
今天媳妇和我吵架，吵到激烈的时侯。我在想一个大男人为什么要和女人一般见识呢？何况是自己的老婆，当时我就跟媳妇道歉，媳妇挺高兴的，

道完歉，她哥也把刀放下了，她弟弟的锹也放下了，她妹妹拽着我头发的手也松开了，她手里的擀面杖也扔地下了，老丈人也把砖头子扔了，丈母娘拿出手机说道:棺材退了吧……

看看，夫妻之间只要多沟通，肯低头，生活还是蛮和谐的，多好！

-----
stay simple, stay naive

file:images/jzm-I-want-you.jpg

-----
央视炮轰星巴克，我是点头微笑的。但有条微博有意思："买世界上最贵的房子，开世界上最贵的车子，加上涨最快的汽油，吃全世界最不安全的食品，享受一场大病能让大多数家庭破产的医疗，用又贵又慢又恶心的网络……这些你视而不见，却来告诉我一杯一年喝不了五次的咖啡是世界上最贵的咖啡，真有意思！"

-----
最近几年，一直觉得学校里讲的"database"跟工业界里大家用的"database"压根不是一个东西。工业界里很多都是逆教科书的土方法，怎么有效就怎么用。想起一个好玩的：以前问同实验室的同学："你的研究方向是什么"，答曰："不固定。什么好发paper就研究什么。"

-----
抗战时的一天，金将军带着数十人行军。侦察兵报告说，后面有一个营的日本鬼子正寻着足迹追赶。将军听了，心生一计。午饭时，他要求每个人造10个灶坑，坑底点燃树枝木头，周围摆上石头，假装座位，这样共造了500多个灶坑。不多时，鬼子追过来一看，推算出金将军会和了援兵，共4000多人，就不敢再追了。

不一会儿士兵们口渴了，金将军又往前一指：前面有梅林。于是大家口舌生津，流到一个缸里，淹了一个小孩，金将军用石头砸开了大缸救了小孩，小孩拿出两个梨感谢，金将军把大的让给别人吃，自己用小梨砸开了邻居的墙，借着光看起书来……

-----
说到面试之后大家给人打分，4分是if you don't hire him I'm going to quit my job 1分是if you hire him I'm going to quit my job。好奇中间俩是什么，老板说：3分是whatever 2分是what the fuck 最后一致2分结束了.

-----
世界上最勇敢的男人——里奥·费迪南德

file:images/the-bravest-man.jpg

评论: 卡洛斯很明显感受到了侮辱！本来想射门的，现在临时改变注意！……

-----
Linus在LKML最常见的发言就两类：你的code很屎我不会merge对了你还是个傻逼，你的code很屎但是我看在谁谁的面上勉强收了不过你还是个傻逼。

-----
俩人搞对象，山上骑马，男人为表忠心骑着马来到了悬崖边， 回头对着心爱的女人说："我最后问你一句，你到底能不能嫁给我，如果你不嫁给我，我活着也没什么意思，我就从这个山崖跳下去"， 女人被感动了，对着男人大喊一声"嫁！"， 马嗷的一声从山崖冲了下去……享年28

-----
前段时间高考报考志愿，很多家长托人问我要不要让孩子报考计算机，作为一个业内人士，我觉得这不能一概而论，要辩证的看这个问题，视孩子具体情况而定。比如说，如果是亲生的，就尽量不要。

-----
有一个乞丐，在菜市场乞讨，他把给他钱的人的住址都记了下来。过了几个小时，一辆宾利停他前面，他上了车挨家挨户的还钱，而且是十倍的还，给他一块的他还十块。第二天，他又来了，满市场的人都给他大钞。那乞丐拿到了七八千。后来那乞丐自己走了，没给任何人钱。《论中国股市的现状》

-----
中山出现村民多次投诉港口镇邮政局大楼基站，逼迫运营商关闭基站。 距离太近，担心辐射，居民就一直投诉，逼迫运营商关闭基站；距离太远，手机信号不好，也会一直投诉，不少人还会上网买放大器，来增强手机信号。而私装放大器会给运营商网络带来严重的干扰，影响更多用户正常使用手机。 哈哈哈哈

-----
牛魔王：贤弟，你看我牛逼不？悟空：不看！

-----
今天跟大姐撸串，我给大姐讲了个我刚看来的老好笑的笑话，我说："大姐，孙悟空三打白骨精里有几个白骨精？"大姐说："一个。"我说"不是。"大姐问："几个？"我说："三十六个啊，一打十二个，三打三十六个，哈哈哈。"大姐说："哦。"

-----
什么叫宽容？

小明放学拿考卷给老爸看。
老爸:"数学0分？！"
小明点点头。
老爸:"语文1分？！！"
小明无语。
空气仿佛凝结。小明感到一场腥风血雨就要洒落在自己身上。他内心挣扎着，战栗不安等待世界末日的到来...
老爸:"小明啊，你 ... 有点偏科呀！

-----
刚看完速激7，回家路上一路兴奋，前方不远处一辆宝马，超它！ 又遇一辆卡宴，超它！ 路虎！超！ 劳斯莱斯！超！ 宾利继续超！ 迈巴赫！不犹豫，超！超！超！ 没办法 就是有速度就是有激情……………后来交警过来叫住我问道："前面堵车呢！你骑着个破自行车拼命的往前挤啥呀？刮哪个车你能赔起啊…"

-----
还是自己努力吧

file:images/better-to-work-hard-and-on-my-own.jpg

-----
file:images/someone-saying-im-handsome-at-back.jpg

-----
06年自主招生语文还有一道题，是写一个四字短语，每个字的偏旁部首都一样，要求每个字都不能重复。我第一反应是魑魅魍魉，可惜一个字都不会写。憋了很久之后写了一个"玩玻璃球"……江河湖海琴瑟琵琶波涛汹涌宜家宜室那么多词……我当时一定是走火入魔憋了一个玩玻璃球。当时觉得北大不可能要我了……

玩玻璃球,涂润滑油,膀胱肿胀,痔疮疼痛,没法洗澡

-----
之前邮寄东西经常被摔的不能看，后来想了个办法，给别人送瓷器时都会在箱子每一面上用粗体字写上"开光法器，镇物在内，永世压制，不得启封"几个字，再画几个郑重其事的符，这样的包裹送出去，通常都是完好无损的一路到朋友手中……一朋友反馈说快递师傅电话里带着哭腔问箱子磨穿了一点怎么办……

-----
#+BEGIN_QUOTE
媳妇：老公，我把人家车刮了！
老公：一天尽给我找些鬼事，啥车啊？
媳妇：不认识，就带个B字。
老公：比亚迪啊，等着我一会就到。
媳妇：老公不是比亚迪！
老公：宝马啊，那你等着，老子去银行取点钱！
媳妇：也不是。
老公：不会是宾利吧，你这个败家的娘们！
这时一个带有磁性的声音接过电话说：兄弟，我这是布加迪威龙
老公：去你妈的，媳妇我不要了，你看着办吧
老婆：是他刮倒我的自行车，我躺地上了，动不了，车主说只能赔我500万，想找你商量来着……
老公：媳妇，在哪里呀，别怕，有老公在，我现在马上过来
#+END_QUOTE

-----
这两年创业各种努力各种焦虑，真是不容易。想想也应该换台新车了，一咬牙一跺脚，趁小长假把车提回来了。有人说人到中年车型太拉风了不好，不管了揪着青春的尾巴也犒赏自己一把。别问我为什么买银色，耐脏。

file:images/which-is-my-car.jpg

-----
自己叫的大保健，含着泪也要做完。。

file:images/massage-wtf.jpg

-----
58 和赶集网合并后，两家公司的爬虫和反爬虫部门将就地解散。

-----

浙江一妇女在一家饭店洗碗,年纪有些偏大,同事都叫她洗碗阿姨。她嫌洗碗阿姨不好听，给自己取了个牛气的名字叫：瓷洗太后。 隔壁补车胎的师傅大受启发,也任性了一把,给自己取了个具有国际范的名字：拿破轮。电焊工听说了受到启发，开了个电焊铺，取名：焊武帝， 这天他去隔壁的糖果店炫耀，糖果店老板拉着他看了看自己的店名：糖太宗，电焊工沉默了…… 不远处切糕店的老板跑出来指了指自己的店名：汉糕祖，二人一起沉默…… 这时，一个掏粪工骑着拉粪车从两人面前经过，拉粪车上赫然写着三个大字：擒屎皇……集体沉默…… 偏偏消息传到了安吉境内，有个卖竹凉席的，也让整了个牌子挂在竹席店外：毛竹席！

-----
file:images/chairman-mao-0.jpg

file:images/chairman-mao-1.jpg

file:images/chairman-mao-2.jpg

-----
领导："一群笨蛋！我问你们，行为发生了吗？证据充分吗？现在叫我怎么办？十足的废物！谁踹的门？"一个穿着制服的干部颤抖着往前迈一步，小心翼翼地答，"领导，是我的错，门确实踹早了。但谁能想到，那老头光接吻就那么长时间，要知道，有的人12秒就完事了。""闭嘴！滚！都给我滚！"领导咆哮道。

-----
【据说十年后农村的标语】1.怀上来生出来养起来，就是不能打下来。2.经济搞上去，人口跟上来。3.二胎奖，一胎罚，丁克不育都该抓。4.该生不生，后悔一生。该养不养，老无所养。5.生男生女都一样，不然儿子没对象。6.一人拒绝多生，全村人工受精。7.农村要想富，多生孩子能种树。

-----
小时候生病，妈妈总会泡杯咖啡，说：外国人都喝这的。我一直都比较害怕咖啡，苦涩交加。长大了，我走遍星巴克、上岛，都找不到小时候喝的那个味。直到某天，我喝到了板蓝根……

-----
纽约时报报道： 昨天，中国经济陷入崩溃。有八成以上的中国人不能上班，夜间大量无业游民上街燃烧投掷爆炸物。大量无业游民酗酒赌博，剩下的部分人只能观看电视度日。面对崩溃的末日，中国人只能一家人聚在一起，惶惶不安地守在一起，彻夜不眠地熬到第二天的日出。还有学校全部停课，工业全部停滞，百分之八十的店铺关门，股市全部收盘。而无数年轻人为了几毛几分钱的红包而丧失理性。

-----
亲，听我一句劝吧，放下手机，走出微信红包的世界，读几页自己喜欢的书，出去阳光里走走，要么骑骑自行车，天黑了约几个好久不见的朋友喝喝茶，聊聊天，随便做些什么，一天下来，你就会发现，还是微信抢红包有意思……

-----
瘦小离家胖了回，乡音未改肉成堆。
儿童相见不相识，惊问胖子你是谁？

-----
"哥们儿，我们内蒙喝酒有个规矩。我先介绍一下今天桌上的几个朋友，然后咱们先喝一圈。喝完之后你能说出来他们的名字，就是你认我们这些朋友，我们自己喝一杯。要是你说不出来名字，就是情谊还没到，你自己喝一杯。先从你旁边的噶拉仓巴拉丹扎木苏日丹开始，再往下是乌勒吉德勒格列日图愣巴……"

-----
有个妹子说昨天去看了场电影，叫《丘比特人》， 于是就涌现了一大波高能回复
- 这个手刹不太灵
- 暮光之城管
- 妇产科联盟
- 变形钢筋4
- 泰尼号坦克
- 星巴克的救赎
- 家乐福海盗
- 魂断蓝翔
- 环太平间
- 忠犬洪七公
- 大侦探福尔马林
- 梁山伯与茱丽叶
- 盗墓空间
- 拯救大兵张嘎
- 唐伯虎点蚊香
- 哈尔滨的城堡
- 决战杀马特
- 老爸老妈血泪史
- 钢筋侠
- 阿凡提3D
- 冰棍奇缘
- 人在歹徒
- 仇富者联盟
- 偷奶神爸
- 午夜闹铃
- 上海钢琴师
- 哈利波特与凤凰传奇

-----
《尤达登高观战图》，元代，赵孟頫。

file:images/yoda-monitoring.jpg

-----
卖家说是唐代官窑,可我总觉得哪不对劲!

这是元青花啊，卖家当成唐代的那确实是价标高了

@林仕鼎:元青花发色偏深蓝，这个颜色纯蓝，而且缠枝牡丹是明代瓷器的普遍纹饰，所以断代的话，我觉得是明。从釉色和款型上看，有正德官窑特征。卖家虽然有点忽悠，但东西很开门，楼主捡到大便宜了。

file:images/feel-smth-wrong.jpg

-----
今天看到一句很有道理的话：很多人觉得自己活得太累，实际上他们可能只是睡的太晚 ...

-----
那些年老师讲过的话
- 我教了二十几年的书，从没教过你们这样的班级！（手还得来回晃）
- 同学们，我再讲最后一道题就下课（讲完就上课了！）
- 这又是一道送分题
- 这道题我上次就写在黑板这个位置
- 你讲还是我讲，你讲你上来讲
- 这道题肯定不选A，C也很明显，D就不永说了，所以是B了
- 初中老师：这个到高中你们老师会和你们讲的。高中老师：这个你们初中老师应该讲过的。
- 这个题你们自己说我讲没讲过？讲没讲过！
- 没带就是没写

-----
今天开车看见前面路上有十块钱，我立马停下车，上前捡起钱，抬头一看不远处有一交警，没办法我只好把钱拿给交警，我说：警察同志，我捡到10块钱！交警看看我说：还差90！我楞了，急忙解释到：我就捡了10块钱啊！交警说：是，不过你违章停车，罚款100，还差90！我………多么痛的领悟……交完罚款我开车走了，当我向后视镜一看，交警又往地上扔了10块钱…亲们，年底了，交警也有任务啊！

-----
下午，我陪老朋友去现场给儿子买婚房，在办理房子分期付款手续登记时，现场的业务员说：先生您是季付，还是月付？朋友一听就火了，吼叫道：我不是继父，也不是岳父，我是父亲！于是业务员就在申请表格上打钩了：一次性付清。

-----
最讨厌那两匹野马了！一匹叫马云，专骗我老婆钱，一匹叫马化腾，专骗我儿子钱。感觉自己就像弼马温，干大半辈子都养马了！

-----
【岳母与亲妈的区别】 前段去杭州旅行,看到雕像岳母刺字。有个中年男的说："也就是岳母干的出来，亲妈不能干这事！！"一圈游客安静了。

-----
我去省图书馆看见两个志愿者需要把还回来的一堆书按顺序入架， 管理员大妈给他们教的时候说："你先在这堆书里拉出一本来，把比它号小的扔到一边，比它大的扔到另一边，然后剩下两堆继续这样整，这样排的快！"

-----
马列·扎克伯格

file:images/mark-zuckerberg.jpg

-----
工信处女干事每月经过下属科室都要亲口交代24口交换机等技术性器件的安装工作。

-----
便携式多功能键盘，主要适用于毕业论文和年终总结的撰写。

file:images/ctrl-cv.jpg

-----
对学渣来说题目有三种：会的，看起来会的，不会的
对学霸来说题目有两种：会做的，超纲的
对学神来说题目有两种：会做的，题目出错的


学渣拿到考卷，被扣分了，大骂老师太狠，但是没人理
学霸拿到考卷，被扣分了，找了N久找不出错，又找来几个学霸一起为答案的正确性争得面红耳赤
学神拿到考卷，被扣分了，找到老师，老师马上改正参考答案


学渣面对一道难题，直接翻答案
学霸面对一道难题，翻了翻书感觉超纲了，或者要求过高，果断放弃
学神面对一道难题，说，虽然我不会做，但算出正确答案还是没有问题的


学渣考试做出了一道难题，巴不得召告天下
学霸考试做出了一道难题，会发一个状态，第一句话一定是：这题其实不难
学神考试做出了一道难题，好像什么都没发生过


学渣考前才刷题，只挑简单题做
学霸一直在刷题，成套成套地做
学神从来不刷题，偶尔翻翻书就足够拿满分了


学渣经常在人人、贴吧或者知道上求助
学霸经常和别的学霸约好一起去自习方便讨论问题
学神平时一般不轻易露面


学渣考完试喜欢说好难啊求不挂
学霸考完试喜欢说都不会肯定挂了
学神一般不说话


学渣的成绩分两种：挂了的、差点就挂的
学霸的成绩分两种：上90的、失误了离90还差一点的
学神的成绩分两种：满分的、被老师故意找茬扣了一两分的


学渣答题喜欢搜集各种解题格式
学霸答题只用自己的解题格式
学神答题从不套格式，但他随手写的解答会被别人用作标准格式


学渣常常为公式太难背而烦恼
学霸努力背完所有要用到的公式
学神只背基本公式，其它公式自己推导


学渣喜欢YY这种分析学渣、学霸和学神的区别的文章，然后顺便点一下【赞同】
学霸看完这样的文章会笑一笑，懒得回
学神直接无视

-----
有一个小伙子陪姑娘路过手机店，姑娘看中iPhone6 Plus了，
小伙问她：喜欢吗？
她说：喜欢！
小伙说：喜欢就多看一会吧！
他俩就从白天一直看到了晚上，
姑娘突然问他：为什么我喜欢，你却不给我买呢？
他回：爱你的人不一定是愿意为你花钱的人，而是愿意花时间陪你的人！
姑娘含着眼泪点了点头说：我就喜欢你们做销售的，tmd没钱、装逼，还特能说

-----
APEC = Air Pollution Eventually Controlled. 经典，本世纪最佳缩写。

-----
【CCTV被曝：实际成本仅0.1元！】一边是央视广告被爆10秒广告被炒到几亿元，一边是消息爆出中国工业用电一元钱一度。且业界还传出，央视播放一条10秒钟的广告仅耗电不到0.1度，1毛钱的成本卖出上亿元的天价，央视的利润几乎达到100%。有网友直指，成本这么低卖得那么贵，央视根本就是在抢钱。

-----
"扬我国威！Facebook常年歧视中国用户名，屏蔽中国IP访问，终于惹出大事了！中国国务院副总理王歧山把Facebook老板从美国唤到北京，严厉教训！是中国人就转！不要辜负了这个个时代！"——QQ空间热帖

"在我们中国的土地上，就要说中文，才对得起中国人民"，因为中国领导人的一句话，Facebook老板苦学半年中文，到中国接受批评时一句英文都不敢说，全程讲中文。中国人在历史上从来没有如此受到国际尊重！

-----
下面这些杀伤力极强的三字真经，你最反感的是哪个..?

- 用你管
- 哦呵呵
- 那算了
- 无所谓
- 你胖了
- 随便你
- 别烦我
- 无语了
- 不知道
- 我没事
- 你忙吧
- 改天聊

-----
有一次考了98分，学霸100分，以为自己和学霸差距很近了，没想到学霸说:"你考98分是实力只有这么多，我考100分是试卷只有这么多分。"他说的太对，我简直无法反驳。

-----
暴力不能解决一切问题

file:images/violence-is-not-everything.jpg

-----
谈下iPhone 6 Plus 的使用感受：外观上比5S轻薄了，比想像中好看很多，屏幕明显的大了好多。最直观的提升是运行速度，A8处理器就是快，打开各种app和多任务处理时非常流畅。其他功能还没来得及看，因为站我前面玩手机那人已经下车了！

-----
一个优秀的台风应该是这样的：来势凶猛，全巿停课停上班。掉转风向，擦肩而过。环流影响，危害减弱。下雨交差，皆大欢喜。领导防风有功，市民没有损失，学生家里休息。如果能够忽然放慢脚步，让全市多停一天班，那么不仅是优秀的台风，简直是卓越的台风了。

-----
有个 QA 工程师去酒吧。点了 1 杯啤酒。点了 0 杯啤酒。点了 999,999,999 杯啤酒。点了一只蜥蜴。点了 -1 杯啤酒。点了一个 sfdeljknesv。

-----
有一哥们，对他媳妇说："媳妇，我算命了，算命的说我135岁的时候有个坎！"
他媳妇冷冷地说："咋地，坟让人给刨了啊？"

-----
有一同学上课突然想放屁，而且肯定是响屁。然后她想到了一个绝妙好主意，放屁的时候猛拍巴掌来借此掩饰一下。
于是乎她猛然一拍巴掌，全班都回过头来看她，然后她放了一个响屁……

-----
"只要你迈出我们之间的第一步，
剩下的九十九步由我来走完。"
"你他妈能闭嘴好好下棋么？"

-----
有个卖矛和盾的楚国人夸他的盾说：我的盾坚固无比，任何锋利的东西都穿不透它。
又夸耀自己的矛说：我的矛锋利极了，什么坚固的东西都能刺穿。
路人问他：用您的矛来刺你的盾，结果会怎么样呢？
那人不知道怎么回答就走到路人跟前一矛将其扎死，说到：就他妈你话多。

-----
女儿离家上大学时，把心爱的小盆栽和金鱼留下来让我照顾。
但她放心不下，因为我这个做妈妈的粗心大意是出了名的。
结果花草枯萎了，我把这件事告诉了她。
一天她打电话回来，我很惭愧地告诉她金鱼也死了。
她沉默许久，然后轻轻地问道：那爸爸还好吗……

-----
正在期末考试中，这时候广播响了：
同学们请注意，同学们请注意，卷子上有错误。
请大家看第4页的第9大题的第2小题。
李雷正以50公里每小时的速度走路，走了100公里用了几个小时？
请大家把李雷改成韩梅梅，谢谢。

-----
下午上英语课。
有个同学举手说：老师，我想上厕所。
老师说：那你就想吧。
（那你就想吧……那你就想吧……）

-----
在学校，我打篮球年级第一，饭量无人能比，打架我站出来没人敢叫板，运动也是强项，全身健壮的肌肉，无数人我都不放在眼里。
但是，为什么像我这么优秀的女生，竟然没有男生喜欢我，现在的男生都瞎眼了吗？

-----
记得有次考试吧，某位少年老成的同学借上厕所的时间，假装是巡考的老师上别的考场转了一圈，把答案都看回来了。

-----
记得上初中，中午午休的时候，我和哥们躲在厕所里抽烟。
听见外面有人来，哥们猛吸一口，就把烟甩了。
进来的是教导主任，他看见我们靠着窗户，便问：你们在干嘛呢
我慌了，转头看向哥们。他的表情我至今难忘。只见他鼻孔里冒着好多白烟，然后说到：我在生气。

-----
其实东北姑娘是最有礼貌的，她们做任何事都会寻求你的意见。例如：
我削你，你信不？
分分钟砍死你，知道不？

-----
小卖部老板：听过这样一个传说吗？如果易拉罐的拉环拉断了却没能打开饮料，那就说明这个拉环是上天选中的，当做戒指戴手上能带来好运气。
我：所以老板你是一定不会给我换一瓶了是吗？
小卖部老板：是。

-----
在房间里背古文，麻麻走进来：宝贝儿，背什么呢？
我说：古文。
老妈果断给我一巴掌：小兔崽子长能耐了，叫谁滚呢！

-----
昨天去饭店吃饭，夹起一块猪肉发现上面好多毛，心想现在的饭店真不像话毛都不弄干净。
于是很认真的一根一根地拔，等弄得很干净之后放进嘴里。。
妈的，是块姜。

-----
晚上在家唱歌，正飙到高音时邻居来敲门。门一开他就竖起来大拇指："刚才高音是你唱的吧，真好听。"
我谦虚地摆摆手，"不好听不好听。"
他一拳打我脸上，"知道不好听你他妈的还唱！"

-----
老师上课突然指着我说："把你旁边的叫醒起来解答黑板上这道题。"
可是我旁边两个人都在睡觉，这种情况应该叫醒跟我关系不太好的那个吧。
于是我一巴掌拍醒了来听公开课的校长。
我他妈太机智了！

-----
"小伙子，红旗广场怎么走？"
又一次被人叫住问路，换作是以前，我定会指一条相反的方向告诉他，然后沾沾自喜地感觉自己整蛊到人了。
但是现在我没有，也许是已经过了幼稚的年纪，我耐心地告诉他："前面过两个红绿灯，第二个十字路口左转，再走50米会看到一个步行街。那条街上人多，你问问他们怎么走。"

-----
我看她睡了，想起网上流传的馊主意，啪啪扇了她两巴掌。
她惊恐地睁开眼睛，我赶紧抱住她说：宝贝你做噩梦了吗？别怕一切有我。
她忍了一会儿说：刚才我只是闭着眼睛想事情，没有睡着。。。

-----
去逛公园，想玩前面那个秋千，于是我走过去跟正在玩着的那个小朋友商量。
我说：小朋友，你一个人吗
小朋友看着我点点头
于是我笑着对他说：那让给我玩，不然打死你。

-----
外面下着暴雨
"雨伞给你，你打着，别感冒了。"
"那你呢？"
"我打车。

-----
Q：怎样跟一个不认识但一眼就喜欢上的女生搭讪呢？
A：走过去直接躺地上：同学，你男朋友掉了

Q：发现我喜欢的女孩子会抽烟，该不该继续追呢？
A：别追了，别追了。真想追的，她吃鼻屎你也会想追的，根本停不下来

Q：读一百本书和健身练六块腹肌相比，哪个对于找漂亮的女朋友更有帮助？
A：还是练腹肌吧。能提出这问题的，估计不适合读书。

Q：2013年的应届毕业生有699万，面对这种局势，应届本科生应该选择读研还是就业？
A：请思考：据说现在男女比例二比一，我该交往男生还是女生？

Q：文科女生一心想找程序员男朋友，身边有不少优秀帅气的追，却完全不想理会，家人朋友都无法理解我，怎么办？
A：我接触过的妹子不多，你们不要骗我。

Q：我喜欢的女孩的朋友侧面问我对她是否有意思，但是她又在场，我应该咋回答呢？
A：别吭声，把脸憋红（记得回头请她朋友吃饭）

Q：约妹子看电影时对影片的选择有分歧，该怎么办？
A：居然有分歧，看来你确实想看电影……

Q：喜欢的女生背后有七八个备胎，怎么破？
A：那只能说明你喜欢的那个女生是辆破车，好车哪需要那么多备胎

Q：已经有女朋友了，但又遇到更喜欢的对象？
A：日版《白夜行》里给了另一个答案：之所以会喜欢上第二个，就是因为第一个给了你安定的感觉。

Q：已经有女朋友了，但遇到了一个相互喜欢的女生，比现在的女朋友漂亮、有钱、温柔，应该怎么办？
A：想起一句话：不要相信在野党，执政之后都一样。

Q：女朋友说XX好帅的时候，怎么往下接话茬？
A："那又怎样，女朋友又没我的漂亮。"

Q：女朋友总觉得别人的男朋友好，我该怎么办？
A：成为别人的男朋友。

Q：如何优雅地跟女朋友吵架？
A：吵赢了的都单身了……

Q：为什么男女朋友一吵架，往往女生站着不动？
A：通常牛逼的大招，在吟唱时都是不能动的

Q：哪些情况下女生会不理男生？
A：任何情况下。

Q：男朋友被我气得很可怜，怎样哄他？
A：多半是装的，揍一顿就好了。

Q：有哪些毕业论文的致谢部分让你印象深刻？
A：去年答辩时看到一个致谢："最后，要感谢我的女朋友，在我22年的生命中始终没有出现过，让我得以专心于学术，顺利完成本科论文。"

Q：一个82年的已婚男人勾搭一个92年的女大学生，说自己要离婚，要和这大学生在一起，是出于什么心理？
A：姬无命是这么告诉郭芙蓉的："下回出招之前，用不着先喊。"你他妈倒是离给我看看啊！

Q：为什么很多人回答情感类问题建议别人分手？
A：因为省事儿。就像面对电脑问题，我们时常会说"你重启一下试试"，或者"你重装一下系统"一样……

Q：拒绝了我的人偶尔来我空间看一看，是抱着什么样的心态来看？是想看看有没有交往的可能吗？还是我想太多了？
A：据说，有的虐杀型连环杀手会偶尔回到现场，回味当初折磨受害人的经过。

Q：遇到了之前的女神勾引我该怎么办？
喜欢她，追了她快3年，被拒绝十多次，一直以来，对方对我可以说完全不假辞色。请吃不去，礼物不收，随手发卡。然后就在最近，对方前天一夜之间忽然大转变，居然主动约起我来，说说笑笑加撒娇，还对其他人说，我一直等着她，让她觉得很幸福。我幸福得要晕了……发到网上求祝福……
A：大家最靠谱的回复是："拖半年，肚子没大再说。"

﻿﻿Q：能否说家境越好的人越愿意努力向上，而家境一般的人反而会安于平凡？
A：《银魂》里的一句话："和你们这些少爷不同，我们光是活着就竭尽全力了。"

-----
记者：您获过国家一级的奖么？陈佩斯：没有。记者：无论是小品，或者喜剧话剧？陈佩斯：没有，都没有，我是一个非常干净的人……

-----
巴西已经不是四年前的巴西！ 德国也不是昔日的德国！ 真正的足球强队应该是非常稳定的！ 放眼国际足坛，能做到这一点的 只有中国队！ 今天的中国队还是当年的中国队！ 纵观世界，没有一支球队， 能像中国队如此稳定！中国足球队，专注输球30年！ 一直被模仿，从未被超越

-----
说fu〜〜吹出的是凉气，说ha〜〜吹出的是热气！！谁能告诉我为什么啊啊啊啊！！！

人的口腔和嘴唇构成一个拉瓦尔喷管，根据完全气体等熵流动表可知，出口面积越小温度越低所以fu温度比ha低

-----
imgur上一张小龙虾在水桶里的照片，居然拍出了宇宙科幻大片的感觉……

file:images/how-lobster-act-big-movie.jpg

-----
在长达84年19届世界杯的历史上，仅有三支国家队战胜过中国队，分别是巴西、土耳其和哥斯达黎加；至今从没有一支球队能在世界杯上赢中国队两次；在过去84年里中国队仅丢9个球；除了巴西，中国队是另一支敢在胸前绣五颗星的球队。知道厉害了吧，以后别再黑中国足球队了..

-----
看到"脑残" 的英文定义，惊为天文啊— Your brain has two parts: left & right. Your left brain has nothing right, your right brain has nothing left……

-----
知道《那些年》《致青春》《同桌的你》他俩为什么最后都没在一起吗？不是那句什么同龄男孩比女孩晚熟的多；也不是女孩等了十年也没能等到男孩成长。只是因为广电总局有规定:青春校园片可以出现早恋，但不许成功！（详情请参阅2011年《广电总局办公厅关于加强情感故事类管理节目的通知》）。

-----
看到有人被七大姑八大姨逼着生娃，气得要翻脸。翻脸是一个选择，不过也可以这样试试："唉，二表姑，我说实话吧。这些年，咱们这儿的医院我都瞧遍了，上海北京也都去过……我实在是不好意思说这个，才说不想要。你们讲的这些道理，我能不懂么？我能这么不孝吗？我实在是没办法啊，你们还这么逼我……"

然后坐等被推荐老中医？

这太简单了，谁推荐就找谁借钱，就说这些年治病耗尽家财，为了咱家的香火二表姑您不能不管我啊。这类闲亲戚能数落你嘴皮子爽的时候都很积极，来真格儿的跑得比谁都快。借几次钱保证永远不再烦你。

-----
有条消息说"舌尖上的中国"摄制团队进北大，5月6号敬请期待"。然后出现了一条舌尖体评论："智慧的北大人知道，即使一街之隔的两地，孕育出的食物，味道也是截然不同的。凭借对美食本能的直觉，每个周末，北大人都会穿过中关村北大街，来到散布在十九座食堂中的清华园。"

-----
与其花钱请人"拓展"，不如到郊区租个便宜酒店，麻将牌九扑克筛子台球……全摆上，每人发价值500元的筹码，自由组合，随便玩。输光了的就踢毽子跳绳打羽毛球看书看电影去。这种让新员工相互熟悉的效果绝对比"拓展"强。而且这个过程中，人品也很快能暴露出来，HR们在边上观察就行了。

-----
1988年凯文·史派西接受采访时说道：对于生活，我一直只字不提，不是为了故作神秘。而是你了解一个演员本人越少，越有利于让你相信他就是荧幕上的那个角色。观众走进电影院，看一完场我的电影，深信我就是剧情里的那个人。

对于代码，我一直不写作者，不是为了故作神秘。而是你了解一个程序员越少，越有利于让你相信这程序源自一群一丝不苟的天才。客户把我的程序跑起来，水银泄地般的流畅，深信我就是那辆牵引黄金万辆的火车头。

-----
今天坐飞机 旁边一二逼拿了杯七喜加橙汁 然后掏出清洁袋 把饼干全捏碎了倒饮料进去 搅混了对空姐说这是我吐的 空姐让他丢后面洗手间 他说太麻烦我喝了把 然后就喝了几口 半个客舱的旅客没吃下饭

-----
一老哥的情人来京玩儿。老哥决定陪几天，就对他老婆谎称去马来西亚开会，坐的3月8号的马航MH370回北京。现在他和情人在酒店里十多天了，不敢回家, 要疯了，要疯了…他正在通过微信求国内民间高手支招儿。

老婆，我那天上了370航班，有个空乘把我买给你的礼物碰坏了，不但不道歉说话还比较冲，我跟人打起来了被地勤赶下了飞机。本来以为处理完了能赶下个航班回来，谁知道370出事了，我被马警方拘留调查了好久，没收通讯工具。 现在想来真是一阵后怕，是你的礼物救了我。

-----
连WIFI的时候，好像发现了个惊天大秘密呢...

file:images/funny-wifi2.jpg

-----
机长大人你要冷静一点啊啊啊啊！

file:images/passenger-tight-belt-please.jpg

-----
今天下班在小区里看到一个熊孩子在放鞭炮。专门往人脚下扔，我走过去很慈爱的问他："小朋友，你的家长呢?"熊孩子一脸熊样的挑衅看我："我一个人出来玩的!靠!"我一听这话就放心了，当场把他收拾了一顿，现在好舒坦。

-----
北京哪儿最适合打架？绝对是西直门！！打输了，出A口，派出所；被打伤，出D口，人民医院；打残了，出C口，残联领证办卡；想打官司，出B口，西城法院。如果不想交手，请约在西直门桥上，丫根本就找不着你。。。

-----
无论你做了11年，21年，51年，101年，无论你的数据多么确凿，结论多么可信，无论你多费劲宣传手机辐射无害 我们用一句老祖宗的话就可以轻易的把你所有努力瞬间击的粉碎，这句话叫："宁可信其有"...这句话还可以用在对所有科学辟谣

老祖宗留下了好多抬杠用的智慧

-----
几年前，一好友吐槽说：在xx会议被我拒的那篇巨傻的文章竟然中了xxx的best paper，没天理阿！前几天，老板说，不要怕paper被拒，想几年前我一paper在xx被拒，转投xxx，结果拿了best paper！。。。我沉默了良久，老板以为我懂了。。。

-----
就在刚刚，看到一潮男穿着两边不同颜色的短裤在地铁座位上玩手机，地铁到站冲上来一大妈低头抢座位，一边喊"麻烦两位让开个位"一边掰开潮男的双腿坐了下去。

-----
笑死了！！！今年看见的最正能量的一句话：当上海的法官们想拼命甩掉＂嫖客＂身份的时候，李双江梦鸽夫妇在竭力为孩子争取一个＂嫖客＂的名份! 所以：人活着要知足！引自微信

-----
【学生间兴起炫富新形式：比比谁敢扶老人】Ipad、Iphone越来越平民化，导致多地富二代学生抱怨难以炫富。然而，近来在浙江某中学，"扶老人"成为新一代炫富杀手锏，"我有钱，我敢扶"已是公认土豪标签。其中，初三的李龙因一月内连扶18位老人，赔款173万，公认为全校首富，众多女生疯狂追逐。

-----
一老头骑车不小心撞了停在路边的宝马，撞完以后骑车要走。宝马司机下车就骂，老东西，你瞎了，撞了我还就跑？老头转过头说:小伙子，你要这么说，我可就躺下了！宝马司机说，叔，我跟您闹着玩呢，慢走啊!

-----
一个朋友在网上看了一段文字，大概意思就是：年轻时候总要做点老了都会热泪盈眶的事。然后，他狠心花2400买了部单车，准备骑行西 藏。第二天就看他热泪盈眶了，吃宵夜的时候单车被偷了！

-----
这才是父子装啊。。。

file:images/true-papa-baby-clothes.jpg

-----
CCAV记者在疾行的列车上采访：这位乘客，您买到火车票了吗？乘客甲：买到了！旁边这位呢？乘客乙：买到了。记者随机采访了十几个人，高兴地发现大家都买到了回家的火车票。

-----
死神："我连载11年了哟。 "火影忍者："这算什么，我可是连载13年了。"海贼王："我连载15年了，也不知道什么时候完结。"名侦探柯南："论资历，你还是差我那么一点，我连载18年了。" 新闻联播微微一笑："呵呵。"

-----
新兵连时，任何时候点到名都要大声喊到……有次班长点名，我答到，班长说我声音太小。罚我对着围墙大喊100遍。"到，到，到"还没50遍呢，围墙突然倒了，给哥吓尿了不说，还进来一个货车屁股，紧接着就听到围墙外一个声音在怒吼"谁TMD瞎指挥！＂

-----
这不是希腊神殿废墟，这只是年久未清的电脑主板。。。

file:images/motherboard-and-ancient-greece.jpg

-----
敲代码是一种职业，往高端了说叫做工程狮，往低调说叫做程序猿。他们常说：只要有需求，就会有办法。这是一种怎样的精神？这是一种国际主义精神，是一种毫不利己，专门利人的奉献精神！这是一群高尚的人，一群纯粹的人，一群有道德的人，一群脱离了低级趣味的人，一群有益于人民的人

-----
例如在古惑仔《只手遮天》里，林神父在球场上挺身而出直面乌鸦，一声令下杀出了几十个手持菜刀拖把的邻居，说出了他那经典台词"我传道二十多年，叫大家信耶稣大家不一定会，但是让大家砍人他们一定会照办的。" 那么就拿这个场景定格。《读者》一定是"牧师见义勇为背后的哲理小故事"，《知音》一定是"浓浓的大爱啊为那般，俊雅牧师为失足少年撑起一片天"，法制版一定是"管制刀具何时禁？和平街区惊现24把砍刀"，而地铁上的街头小报一定是"禽兽神父露出真正獠牙 一声令下欲血洗东兴"。

-----
file:images/fuck-papa-where-are-we-going.jpg

-----
小时候。被学姐骗，看一本道就能上一本。看东京热就能上东京大学。看加勒比就能当上海盗。到现在，才知道。她只是想让我上她。唉。

-----
亲自买包子，亲自品尝…然后亲自上的厕所… （记习大大吃包子）

-----
哪里不会点哪里，so easy！ 妈妈再也不用担心我的学习~

file:images/diff-point-and-fire.jpg

-----
世上无难事只怕有心人！嗯！

file:images/sdcard-stack-up.jpg

-----
既然C++是C的超集，为什么还是有人认为C++不如C...

你在家拿脸盆喝水吗？

-----
「三国冷吐槽」"请你家主人继续装B吧，我们不会再来了。"

-----
因为比较喜欢车。所以不断的在换车，近两年先后买了卡宴，R8，保时捷911，前两个月又买了个兰博基尼，感觉还不错。前天买了辆玛莎拉蒂，怎么说呢，但车更偏向于商务，开起来也更舒适，不像法拉利那样硬邦邦的，毕竟车重在那里，但是还不错，就有一个缺点，就是太费电，四节南孚一会就没电了。

-----
我上次坐车看到打开手机搜了一下周围除了 CMCC 和 ChinaUnicom 之类的没有能连的了啊

-----
当我们介绍某种技术/语言/框架的时候，一般有两种潜台词；1 这种东西做起来很顺手而且快，可以让你节省更多的时间去提升你的逼格；2 We use it just because we can, muggle! 这就是我们闪亮的逼格！一般有人问为什么的时候，我内心都在说第二个答案！

-----
段子：朋友劝我今年别买宾利了，几百万也是开十几年报废，不如买个Q7，开三年卖还能值个四十多万，添几万还能买个新车…朋友还劝我去三亚买几个商铺，一年租几十万就够我零花了，活的健康些…再弄个游艇，私人码头海钓…感觉他们说的很有道理，决定就这么办！现在万事俱备，就看双色球了。

-----
小男孩：你笑什么？我还没表白呢？ 小女孩：花都露出来了。。。

file:images/what-love-is.jpg

-----
奇迹发生的频率（via Facebook）

file:images/miracle-frequency.jpg

-----
猎头给我打电话，推荐了一个我现任公司的职位，薪水是我的两倍。。。

-----
我有一个朋友，双硕士学位，心思缜密。前不久他去世界五百强企业面试，竞争极其激烈，他惨遭淘汰。面试完毕临走之前，他捡起来了地上的碎纸屑。这一幕竟然恰巧被CEO看在眼里。第二天，他就得到了录取通知书，成为了该企业的一名正式清洁工，月薪近2500！！税后！！所以说，#细节决定成败#。

-----
马云为什么经常泄漏内部邮件？

邮件就像底裤，一般不翻给人看。要翻就是想急于证明，或是急于勾引。

这和明星经常掉U盘是一个道理滴。。。

-----
我去某公司面试 SA，二面是技术出身的 BOSS 面的我…问我几个性能问题，我如实回答以后…他直接和我说，"嗯,如果采用你的方案，我们就可以不另外招人了…" FML

-----
中国惊天大谎："中间人少车空！！！！！！"

-----
听起来好像挺厉害的样子。。。

应聘时HR问我从事过什么工作，我说我一直在做网络传媒，针对新闻热点等信息进行推广，曾多次参与上千人甚至上万人的大型项目，偶尔还与明星政要进行合作。被录取之后，其他面试者一脸敬畏地问我到底做过什么，我悄悄告诉他们:转发微博。。。

-----
丧心病狂！

file:images/make-me-freaking.jpg

-----
【女程序员的逆袭】公司一女程序把她的QQ昵称改成了 我老婆 ，后来我们公司很多男的回家后都跪了搓衣板。

-----
//@南都深度:当初劝你置顶，你又不听。

@中国足球队:对不起！

-----
"斯内普教授"又在推特上高级黑了："美国政府倒闭的时间已正式超过Taylor Swift任何一段恋情的持续时间"。。。

file:images/snape-and-taylor-swift.jpg

-----
一个老外问我傻B和牛B中的B是什么意思。我告诉他，B是个副词，形容很厉害，比如傻B就是"傻的很厉害"，牛B就是"牛的很厉害"，装B就是"装的很厉害"。不久，老外到中国女朋友家吃饭，女朋友妈妈烧的菜很好吃，老外竖起大拇指说——你妈B！

-----
傍晚去ATM取钱，取款机提示余额不足，"我艹，怎么到我就没钱了！" 转身一看到后面好长的队伍，好心提醒他们没钱了别排了，于是后面的人就全部散了。。。回去想了下，擦，是我卡里钱余额不足。。。

-----
"师傅，快！帮我追上前面那辆出租车！我给你200块。" 司机说好嘞，拿起对讲机："喂，老张 你停一下。"

-----
关羽：我要批评张飞，平时说话声音太大，虽然用意是关心将士温饱，但说话的样子很凶，不利于团结基层兵士。 张飞：我批评赵云，身为大将，衣着太干净、太鲜亮，看起来很骄傲。赵云：我要批评关羽，你的赤兔马违反了公务用马管理办法，属于超豪华配备吧？关羽：X，你TM懂不懂什么叫批评啊？会不会玩啊？

-----
学医女同学证实：男孩智力来自母亲，女孩智力来自父母均值，无论男女，体制是由染色体以外的细胞物质决定的，所以基本来自母亲。听了我的转述后，LP问：这么说，在决定儿子是否优秀方面，男人啥贡献没有啊？我回：你知道我们公司有个部门叫Recruiting Team吗？

-----
每次面试结束前，都会问一下同学，你有什么问题吗？今天我们同事碰到一个同学，问"你幸福吗？"

-----
那些奇葩的WiFi名...

file:images/funny-wifi.jpg

-----
胡子改变人生

file:images/beard-change-life.jpg

-----
老外代报案，百分百破案

file:images/foreign-report-crime.jpg

-----
早上经过朋友家，朋友的侄子哭闹不肯去上学，朋友他哥就拿个小棍吓唬，小家伙迫于他老爸的淫威只好出门，没错GC来了，走了十几米后小家伙爆发了，把书包一扔开骂了:TMD一家人在家里闲着，让老子一个人去读书。。。。我顿时受精了。

-----
好残忍！早上起来，发现我女儿剪的小纸人

file:images/paper-man-from-RMB.jpg

-----
特反感那些炫富的人。。。这才是真正的低调

file:images/real-low-key.jpg

-----
反应敏捷，你明天不用来了~

file:images/how-I-stop-the-car.jpg

-----
【2013网络流行词 】何弃疗、我伙呆、人干事、不明觉厉、人艰不拆、说闹觉余、累觉不爱、火钳刘明......还有不约而同......这些2013网络流行词，你常用哪几个？

-----
缺少王治郅的热火，是否能与后巴特尔时代的马刺抗衡，让我们拭目以待！

-----
女生喜欢的是长得坏坏的男生而不是长坏了的

file:images/naughty-and-bad.jpg

-----
兄弟们已经仁至义尽了。。。

file:images/classmates-already-do-best.jpg

-----
最近有很多人都在黑气功，我觉得你们懂个屁，气功曾经救过我一命。在我16岁那年，曾被一群小流氓打劫，当时我就使用了龟波气功对付他们。带头的那个混混临走前对我说：要不是看你是个傻逼，我TM早揍死你了。

-----
朋友家有一4岁小萝莉，一天不知道做错了什么被她妈一顿揍，在那哭哭啼啼的时候她妈说，还哭还哭？小萝莉抽泣着来一句TMD，打了人家还不让人家哭，有没有公德心啊？她妈没忍住笑喷了。当然这不是重点，重点是小萝莉接着来一句，打了人还笑那么开心，是不是打我你有快感？

-----
全国人大代表吕新萍建议：让学生"五一"、"十一"休两周长假。 =>  我都毕业了你跟我说这个？

-----
【现实】现在政府机构真正关心人民收入的只剩税务局了，真正关心祖国下一代的只剩计生委了，真正关心祖国明天的只剩气象局了，真正关心房价的只剩拆迁办了，真正关心祖国花朵的只剩校长了，真正和人民打成一片的只剩城管了，真正能言善辩的只剩砖家了，现在我们所能做的也只有转发了。

-----
如果古代也有互联网...

file:images/internet-in-ancient.jpg

-----
某君儿子没考上大学,便找到在国企做董事长的老同学.董事长很爽快：让他来做副总经理吧,月薪五万,每天例行开会就行了.某君：给个一般职位就行.董事长：做总经理助理吧,月薪2万,给总经理倒倒茶就行,某君：还是从普通业务员做起吧.董事长：我们的业务员起码要硕士学历,薪水很低,还欠薪.PS：现实吗？

-----
高考36年来，英语听力中男人邀请女人外出44次，女人答应0次，女人邀请男人外出17次，男人答应17次。

-----
记山东济南孝里镇后楚庄上百村民凭蓝翔技术移民澳大利亚：自幼文武世无双，上京即中状元郎，眼见邻人移海外，悔不当初报蓝翔。

-----
"江浙沪的朋友们，8个月前你们苦苦要求的集中供暖终于实现了。

-----
千言万语尽在这一个字中。。。

file:images/all-in-a-fuck.jpg

-----
据说男子在生命安全受到威胁时，会分泌出大量的雄性荷尔蒙。而常年直面危险的消防队员、防暴特警、职业车手的雄激素水平，更是远高于同龄男性平均值，这正是他们气概非凡、魅力十足的重要原因。所以，如果你觉得男友霸气不足，男人味不够，就每天把他打个半死就好了。

-----
大学时有次寝室被盗了，果断报了警，来了俩民警，一顿取证一顿询问，其中一个还很专业的拿着摄像机做记录，走的时候跟我们说，放心吧，备案了，我们尽量破案！我心想其实警察也没咱们想象的那么不给力嘛，然后…在他们出门以后，听到刚才录像的民警说，艹，老王这玩意我不会开啊。尼玛…（转）

-----
只有那些懒惰者才会为每天早上起不来而抱怨、痛苦，真正有行动力的人会马上请假~~~

-----
【汉语的强大，你读懂了吗？】1. 冬天：能穿多少穿多少； 夏天：能穿多少穿多少。 2. 剩女产生的原因有二，一是谁都看不上，二是谁都看不上。 3.单身人的来由：原来是喜欢一个人，现在是喜欢一个人。 4.两种人容易被甩:一种不知道什么叫做爱，一种不知道什么叫做爱。

-----
又一个困扰男人多年的世界性历史性难题被完美解决了。。。

file:images/i-will-tell-you-if-changed.jpg

-----
"爸，这是我的男朋友。"　 "哎呀，啧，你妈该多失望啊……你怎么就找了个这样的呢！"　 "爸，你怎么可以这么没礼貌……！太过分了！"　 "我又没对你说。"

-----
昨晚在沃尔玛，大家都安静的排队付款呢， 一个女的打着电话插队插我前面了："老公，你出差怎么样啊？我在超市呢…… 我真的在超市啊"， 我立即给师妹递了个眼色， 师妹开吼："718房间客人退房！两男一女的那间！"

-----
网吧一小学生趁着游戏更新竟然拿出自己的作业本认真的写着！ 我等深感惭愧啊！ 当我采访孩子说， 为何你如此认真？在网吧也不忘写作业？孩子就说：时间是挤出来的！挤挤不是有了吗？ 孩子的机智打动了在场的网民，掌声经久不息。

-----
冬天：能穿多少穿多少； 夏天：能穿多少穿多少。再一次发现了汉语的强大。。「转」

-----
这一版用了两天，感觉哪儿都舒服，除了没优化和bug多，已经没什么特别大的问题了，而解决后两者，只是人手和时间的问题，嗯，好。

这个城市来了两天，感觉哪儿都舒服，除了没房和没找到工作外，已经没什么特别大的问题了，而解决后两者，只是钱和时间的问题。嗯，好。

中国足球看了20年，感觉哪哪都好看，除了不进球和被进球外，已经没什么大的问题了，而解决后两者，只是球员和教练的问题。嗯，好。

-----
你相信世界末日吗

file:images/what-people-do-at-world-doom.jpg

-----
问：为什么程序员喜欢UNIX？答：unzip、 strip、 touch、 finger、 grep、 mount、 fsck,、 more、 yes、fsck、 fsck、fsck,、 umount、 sleep

-----
今天又看到一句神句，叫做"I will not change , no matter how U change . "，翻译过来就是——电流不随电压的变化而变化。

-----
有人撒你一身油，对你说：别担心，有奥妙全自动，你咋办？——打到他肾亏，对他说"别担心，有六味地黄丸，治肾亏，不含糖。

-----
有一种期待叫等外卖，有一种依赖叫拧瓶盖，有一种心爱叫高富帅，有一种伤害叫丑八怪。有一种淘汰叫感觉好山寨，有一种失败叫出了点意外， 有一种悲哀叫搜不到wifi，有一种无奈叫周末过得太快…

-----
她："老公，我想吃泡面。""我给你煮去。""我不想吃咱家那个牌子的。""那我出去买。""煮完家里全是泡面味儿，难闻死了。""那泡好了给你拿回来。""凉了不好吃。""那咱们出去吃。""外面太冷，我又懒得穿那么多下楼。""你到底想怎么招？""想吃泡面。"男人是这样被逼疯的...

-----
群男夜里宿舍卧谈生理知识。一男突然发问：你说这个世界上有没有男的有两个蛋蛋？！当时，大家都沉默了。。。然后互发短信沟通：要不要告诉他真实状况？告诉他真实状况以后会不会从此改变他的人生观、价值观？

-----
本人擅长Ai、Fw、Fl、Br、Ae、Pr、Id、PS等软件的安装与卸载，精通CSS、JavaScript、PHP、C、C＋＋、C#、java、Ruby、Perl、Lisp、python、Objective-C、ActionScript等单词的拼写，熟悉windows、Linux、Mac、Android、IOS等系统的开关机，求一份月薪上万的工作 ！

-----
我暗恋的人的外婆昨天死了，她发了一条微博，好难过的样子，我想给她发条评论好好安慰安慰她，以表示我的关切，可尼玛手抖不小心点了个赞，瞬间觉得全世界的语言都没有任何意义了。

-----
两个黄鹂鸣翠柳，我连对象都没有！ 雌雄双兔奔地走，我连对象都没有！ 我劝天公重抖擞，我连对象都没有！ 垂死病中惊坐起，我连对象都没有！ 路见不平一声吼，我连对象都没有！ 问君能有几多愁，我连对象都没有！洛阳亲友如相问，我连对象都没有！此曲只应天上有,我连对象都没有

-----
早上去买包子，见一姑娘急匆匆跑过来语速极快："老板给我来五个包子三个牛肉的一个韭菜鸡蛋的一个鸡汁灌汤的还有一杯紫米粥记得今天给我吸管啊昨天没给可把我烫死了算了把牛肉的换成三鲜的吧哎呀班车来了我不要了"，老板还没来得及反应，姑娘已不见了。

-----
某文艺挫男，父母卧病，家里穷的叮当响，老婆又肥又丑。挫男万念俱灰之时遇到灯神，灯神说把你的愿望写出来，我会满足你，挫男写：愿父母是健康的，家庭是富裕的，妻子是美的。挫男回家，看到房子变得富丽堂皇，打开门，父母精神矍铄。挫男兴冲冲跑进了自己的房间，看见床上躺着个空调。。。

-----
非诚勿扰女嘉宾再牛X也就灭一个男的的灯，宿舍楼下阿姨能灭一整楼的！！！

-----
一位英国程序员用1/5的工资把工作外包给中国程序员做，自己整天玩，还得了优秀员工，被公司认为是C, C++, Perl, Java, Ruby, PHP, and Python 各方面的专家

-----
据说，老师看了这个孩子的调查资料之后，住了半个月的医院！

file:images/kids-resume.jpg

-----
从前有个叫马騳骉的人，但是博学多才的老师也不知怎么念，所以每当上课点名的时候，总爱说马叉叉到了没。后来，一位有文学素养的语文老师点名道"万马奔腾到了没"。再后来，一位体育老师直接改用"一群马到了没？

-----
家有小萝莉一枚，一天纠缠的我实在烦了，就照屁股打了一巴掌，哇哇大哭，找她妈告状去了。。。抹着眼泪绕屋子一圈，没找到她妈，绕回来了看见我，抱着我大腿，梨花带雨的哭啊：爸爸，妈妈打我。。。我差点笑喷了。。。这孩子忘性得有多大啊。。。还有救嘛？？？

-----
为什么我坚定地认为星座都是扯淡呢？

file:images/why-i-think-constellation-nonsense.jpg

-----
小时候，我们都犯过错误，老是把20来岁的女生叫成阿姨，男生叫成叔叔， 于是现在遭报应了，出来混迟早是要还的….

-----
这好像是所看到的最好的云计算广告？

file:images/best-cloud-service-ad.jpg

-----
我们公司请了一个做饭的阿姨。她的儿子今天开着奔驰S60来接她。阿姨的儿子说了一句话，我准备投资你们。金额随便你们说，只要我妈妈在这里工作开心就可以了。我顿悟了，一个公司最重要的岗位就是阿姨。选好阿姨创业成功至关重要。

-----
回到家听说上初二的侄子赚了人生第一桶金，他花150元钱买了个二手MP4，然后拷了32G的|H|片，各种国家的都有，拿到学校租给同学看，一节课1元钱，包夜5元。。企业家的料啊。。。

-----
朋友跟她媳妇去民政局领证，结果工作人员是他前女友，更郁闷的是结婚证上有工作人员印章，于是，他和他媳妇，前女友，一起留在结婚证上了。

-----
抄作业不怀疑对方做得对错是抄作业的基本道德。

-----
有个中文不好的外国学生看到"小心地滑"的标志，因为分不清"的地得"的意思所以他非常小心地滑过去了。

-----
上班坐公交，车上站得满满的。不知吃了什么不干净东西，肚子极为不畅，憋了很久终于没忍住，放一闷屁，巨臭。周边人都在捂鼻子，我也捂住鼻子装样子。心中正在暗自得意，一人叫到："放屁的，你的手机响了。"我反应向来追求速度，千分之一秒便答道："没有啊！"——妈的，他人都在笑，老子...

-----
宝宝两个月，老婆刚给他喂完奶，正躺着玩，老婆冲着宝宝问：宝宝，妈妈是不是最漂亮的啊？ 宝宝微微一笑，然后………………………………吐了…

-----
【ORACLE 是什么？】是"One Rich A** Called Larry Ellison"的缩写…… [囧][囧][囧] （据说 A 是 "Asshole"。O 记的朋友莫生气莫记恨，我也只是偶然看到的。 ）

-----
艹！！！才发现自己去年竟然诅咒了自己一整年！！！

file:images/cursion-from-me.jpg

-----
"老板，这件夹克多少钱？""500.""卧槽，这么贵，那旁边这个呢？""那件新款，两个卧槽。"

-----
跟前男友交往大概一年半的时候，那混蛋居然想要吻我。靠，果断分手。大色狼好吗！！！

-----
未接来电的不同反应~!!!

file:images/diff-reactions-for-uncalls.jpg

-----
在超市买了个特价柚回家，没想到。。。

file:images/wtf-fruit.jpg

-----
去年春节回老家时，看到一个老外在向一个农民伯伯问路。只见那个老外一边说着生硬的中文，一边用手笔划，但那个农民伯伯却还是不明白。 最后，那个农民伯伯说了一句让我至今难忘的话："Can you speak English？"

-----
一朋友...…话说这奇葩有一次把手机掉进热水里了，冒着烫死的危险捞了出来扔凉水里了…

-----
一个真正的学习高手不仅能在一场考试中狂砍90分+ 而且能送出许多60分+的助攻。。。

-----
【如何夸程序员？】通用：你这代码写得真好看。夸C程序员：你这代码不看注释就能懂，写得真好。夸Ruby程序员：我艹，太神奇了，你怎么做到的！夸Perl程序员：这个正则表达式碉堡了。夸Python程序员：Pythonic！夸Java程序员：你写的代码一点都不像Java！

-----
经过多年临床分析，女人在床上说的最多的一句话就是......你压我头发了！

-----
1946年2月14日,世界上第一台电脑ENIAC在美国宾夕法尼亚大学诞生，这是历史性的一天，从此任何人在这一天都有事情可做了。

-----
瞧瞧人家泰国人民是怎么排队的！

file:images/queue-in-thailand.jpg

-----
我们朝鲜观摩团就是喜欢你们电视新闻的真实性，更喜欢新闻里演员的敬业精神。 / 充分说明编程的女人老的快。

file:images/old-woman-read-C.jpg

-----
一天中午我们寝室大哥打电话叫了份外卖，隔了很久了还没送来，于是就又打过去想催催，结果发现自己手机竟然停机了。在大哥到处找人交话费的时候，他电话响了，是那个送外卖的！是的，送外卖的为了找到他，给他交了10块话费.....

-----
同学，你想的太多了。。。

file:images/think-too-much.jpg

-----
这就是装逼的下场。。。

file:images/bad-consequence-of-pretending-cool.jpg

-----
八级的大风，PM2.5被吹走了，把沙尘暴送来了，北京某推友说："我旁边的沙特朋友现在很高兴，说很有家的感觉，丫还把窗户也打开了。"

-----
快递小哥的心情似乎不太好。

file:images/bad-mood-mailman.jpg

-----
听一个朋友说的，不知道有人发过没。话说一男的对一女孩子说:我一天能用一卷手纸。咯咯咯咯咯咯，于是女孩子很高兴的嫁给了他。婚后第一天，女孩子怒了，说:你特么的也太能拉了。。。。。。

-----
怎样对付僵尸

file:images/how-to-tackle-zombies.jpg

-----
公司组织客户去happy，遇到扫黄，客户被抓拘留15天。客户老婆收到行政处罚通知书，打电话到公司大骂。销售总监接过电话，淡定的说：大哥那天喝多了，说嫂子在家等坚持要开车回去，结果被查了酒驾。我们通过各种关系才改成嫖娼，不然得坐六个月牢。客户老婆：哦。那谢谢了！

-----
讲个冷笑话，据说某国特工九死一生偷到了NASA太空火箭发射程序，源代码的最后一页代码是：｝｝｝｝｝｝｝｝｝｝｝｝｝｝｝｝｝｝｝｝｝｝｝｝｝｝｝｝｝｝｝｝｝｝｝｝｝｝｝｝｝｝｝｝｝｝｝

-----
打鸡血来源：鸡血疗法流行于1967年的一种保健术。前后历时大约10个月左右。各地流行（从大都市到穷乡僻壤）的起讫和流行的具体时间、长度略有不同。方法是抽取小公鸡（也有说4斤以上重的纯种白色"来航鸡"最好）的鸡血几十到100毫升，注射进人体，每周一次。

打鸡血_百度百科 http://baike.baidu.com/view/332734.htm

-----
今天北京大风啊，那个大啊，虽然天气预报五六级，可是在街上，感觉可不止五六级啊……刚才来公司的路上，差点被吹翻了，幸亏我背了一本《代码大全》

-----
无论多么帅的锅都驾驭不了主席的发型。。。

file:images/chairman-mao-hair-style.jpg

-----
网友微信求婚时，不巧发生意外...只发了："我不想再做你男友了"第二条"我要做你老公！"竟发不出去！他急忙发微博："刚才不是你想象中的那样子的！都怪这破网，求求你，给我回电话！"...大家祝他好运吧！

file:images/troubles-caused-by-bad-network.jpg

-----
这画面好像哪里见过...在哪里呢？

file:images/fbi-warning.jpg

-----
意译和直译

file:images/diff-translations.jpg

-----
下雪了，下完才想起来，哎妈呀，天窗忘记关了……

file:images/forget-to-close-car-topdoor.jpg

-----
程序员装B指南

一.准备工作

"工欲善其事必先利其器。"

1.电脑不一定要配置高，但是双屏是必须的，越大越好，能一个横屏一个竖屏更好。一个用来查资料，一个用来写代码。总之要显得信息量很大，效率很高。

2.椅子不一定要舒服，但是一定要可以半躺着。

3.大量的便签，各种的颜色的，用来记录每天要完成的事务，多多益善。沿着电脑屏幕的边框，尽量贴满，显出有很多事情的样子。

4.工具书，orelly的，机械工业，电子工业什么的都可以，能英文就英文，不行影印版的也可以，反正越厚越好，而且千万不要放在书架上，一定要堆在桌上，半打开状。

二.从进门开始

0.绝对不10点以前出现在公司.

1.着装！着装！不管你是去实验室，或者去公司的大楼，在或者是小公司的民宅，或是自己创业的黑作坊；无论是春夏秋冬白天晚上刮风下雨电闪雷鸣台风龙卷风，一个装b的程序员都要十分在意自己着装！这里只提出参考建议。初级装：衬衣+牛仔裤+休闲鞋。中级装：T恤+宽松短裤+拖鞋。高级装：背心+宽松大花裤衩+人字拖。

2.得体的举止。在走廊以及任何形式的过道里，一定要双手插兜，走得像个痞子，至少要看起来有点反社会，如若不行，可走文弱天才型geek路线。。

3.如果有女性在你背后指指点点，小声嘀咕说这一定是一个技术男的时候，应该先低头，然后保持低头状态，缓缓回头，坏坏地蔑笑但是不要出声，然后快步前行。

4.进门后，一定不要跟任何人打招呼，笔直走向自己的位置，最多路过打一杯咖啡，千万不要有多余的动作，显示出自己的专注与心无旁骛。

三.坐下就不要再动了

1.坐下以后，姿势需要略微后仰，能翘着二郎腿最好了，然后在后仰的情况下低着头，以便看到屏幕，然后千万就不要再动了。

2.粗暴地把电脑前的大堆书推开一个口，然后摘下电脑上的一个便签，看一眼，不过3秒，可以开始coding了。

3.能不用IDE就不要用，实在装不了，无论IDE是什么，一定要调成DOS那种黑色背景的。

4.如果写前台界面，就不停地调试后台代码；如果写java，就在里面混编C；如果写C，就在里面混编汇编。不光要coding，还要时不时的翻出一本什么英文的书翻一翻，看不懂就看看插图，然后扔到面前假装懂了继续coding。

5.什么看起来高端就用什么，不要管实用不实用。例如对C++：switch统统重构成多态；如果有指针，统统改成智能的；C++一定要自己写template；数字是全部要替换成宏的名字能起多长就起多长；struct就不要出现了，如果出现，也一定要用__attriburte__修饰一下；运算都是位操作的；操作符都是重载的；网络都是并发缓冲线程池的；int只用int32_t声明的;继承不用普通的，什么多继承虚继承啊；helloworld也要写捕获异常的；后人一看代码，中间一堆关键字extern,asm,auto,XXXXX_cast,volatile,explicit,register,template，让一般总在敲int,if,else,for的小程序员顿时心生崇拜。

6.注释？算了吧。只有两个路线可以选：一，变量名起得巨长无比，看代码就和读英文文章一样顺畅，根本不需要加注释。 二，代码无比晦涩，加不加注释根本无影响。

7.千万不要用IM工具交流，千万不要问同事问题，显得自己没有水平，都是自己上网或者查书。

8.无论是同事间开玩笑或者发生任何群体性事件，不要抬头，更不要东张西望，即使地震火灾，也一定要先提交代码再行离开。

四.潇洒地离开

1.人走，主机是千万千万不能关的，至少要跑个daily build，实在不行正在svn提交也勉强算过关。

2.书应该已经又堆到屏幕前了，千万不要整理，明天再来推开。

3.不强求最后一个走，但一定要所有的非程序员，什么市场啊前台啊pm啊都走光了，才可以走。

4.走得时候一定要率性，千万不要收拾任何东西，站起来，出门，好的，就这样。

5.如果今天一定要说句话的话，找到那个最苦逼的程序员，跟他说，你进度太慢了啊，不要老让我等你。

-----
【过年被催婚绝招】惊闻我今天回老家，全家人开始了＂啥时带个对象回家＂的火力攻势。我淡定的抛出了杀手锏＂我对象还没离婚＂，一屋子人面面相觑、沉默良久，开始改劝＂分手吧＂。我一口答应，自我解围成功~！

-----
期末考试来了

file:images/what-is-the-exam.jpg

-----
刚刚得知，有家游戏公司今晚要上线一款大型网游，所有的准备工作都就绪，就等临门一脚的时候，一位正在机房清洁的扫地大妈不小心把服务器电源插头拔了，数据全线崩溃。。。。

-----
为证明蜘蛛的听觉在脚上，一专家做了一个实验，先是把一只蜘蛛放在实验台上，然后冲蜘蛛大吼了一声，蜘蛛吓跑了！之后把这只蜘蛛又抓了回来，然后把蜘蛛的脚全部割掉，再冲蜘蛛大吼了一声，蜘蛛果然不动了！于是发表论文，证明了蜘蛛的听觉在脚上。。。

-----
办公室有一女同事，为人豪爽可爱，和老公感情特别好。有一次我们吃饭说起小三，我问她：你老公要是有外遇了，你跟他离婚吗？她斜眼看看她老公，淡淡地说："我这辈子没有离异，只有丧偶！！！" 好彪悍！！！

-----
一哥们向我借了500块钱过了很久都没还，我也不好意思开口要。于是每次我们去KTV唱歌时，我都点《你的背包》，到最后一句我就会深情地对他唱："借了东西为什么不还？"他还不知情的对我鼓掌叫好："唱的真好真好"。我都无语了……

-----
全国第六次人口普查办统计出全国最爆笑的人名：刘产、赖月京（还是个男的）、范剑、姬从良、范统、夏建仁、朱逸群、秦寿生（亏他父母想得出）庞光、杜琦燕、魏生津、矫厚根、沈京兵、杜子腾。排名第一的：史珍香。

-----
一对情侣坐地铁去世纪公园，出站之后两人因为哪个口近而争执起来。男朋友坚持1号口，女朋友则执意要走2号口，结果无奈之下男朋友只能求助于咨询台的工作人员。阿姨望了男孩子一眼，只说了一句：要去世纪公园就走1号口，要女朋友就走2号口。。

-----
央视记者：大爷你捡垃圾幸福吗？老人：啥？记者提高声音：您幸福吗？老人：我耳聋你大点声。记者声嘶力竭：您-幸-福-吗？老人继续：再大点声！记者无奈离去。老人自语：早他妈听见了，累死你个憋孙！钓-鱼-岛事你不问，拎个破玩艺满大街问啥幸福吗？我73了还在捡破烂能他妈幸福吗

-----
青年："我想要有很多钱。" 禅师："只要你能找到七个球，你的愿望就能会实现。" 青年："您是说七龙珠吗？" 禅师摇摇头："不，是双色球…"

-----
Twitter上最火的英文词儿
- Freedamn中国特色自由
- Smilence笑而不语
- Togayther终成眷属
- Democrazy痴心妄想
- shitizen屁民
- Innernet中国互联网
- Departyment（政府）有关部门
- Chinsumer 在国外疯狂购物的中国人
- Emotionormal 情绪稳定
- Sexretary 女秘书
- Halfyuan五毛
- canclensor 审查
- Wall· e 防火墙
- 围观 Circusee
- vegeteal 偷菜
- yakshit 亚克西
- animale 男人天性
- corpspend 捞尸费
- suihide 躲猫猫
- niubility 牛逼
- antizen蚁民
- gunvernment枪杆子政权
- propoorty房地产
- stuck market 股市
- livelihard生活
- stupig笨猪
- Z-turn 折腾
- Don'train 动车
- Foulsball 中国足球
- Freedamn 自由
- Gambller 干部
- Goveruption 政府
- Harmany 河蟹
- Profartssor 叫兽

-----
一个武士手里拿一条活鱼问禅师：我跟你打一个赌，你猜我手里这个鱼是活的还是死的？禅师心想：如果说是活的，武士就会把鱼捏死。但明知是活的说是死的，就打了诳语。鱼命和原则哪个更重要？禅师沉思了半个小时，终于说道：是死的。武士看了看手中的鱼，说道：麻痹的，半个小时前还是活的。

-----
招聘做饭阿姨

file:images/recruit-cook.jpg

-----
99%的工程师们都算错的一道题：一对情侣一起去买了一块饼，女生吃了3/7块饼，男生吃掉剩下的4/7块饼。男生比女生多出了4.5元，请问这块饼多少元?

-----
美国与中国航天员在太空的对话。美国航天员："中国太伟大了，我一眼就看见你们的长城了..."中国航天员瞄了一眼说："拜托，那是堵车..."

-----
看完《苹果》发现，男人靠不住；看完《色戒》发现，女人靠不住；看完《投名状》发现，兄弟靠不住；看完《集结号》发现，组织靠不住；看完《妈妈再爱我一次》发现，老爸靠不住；看完《新警察故事》发现，儿子靠不住；看完《黑客帝国》发现，一切现实都靠不住，结论只有自己靠得住，简称我靠。

-----
一个哥们儿特爱网购，每次网购的时候都写网名，每次货到的时候快递员叫好多次他才下楼去取，于是整个小区都会听见某个不耐烦的声音：皇上，你的快递!!!!!皇上.....皇上......

-----
新版狄仁杰里最威猛的一段：李元芳：大人，后院发现一具无头男尸。狄仁杰：以我断定，此人已死！李元芳：大人未到现场就知此人已死，大人真乃神人也！

-----
转个文化一点的对联，没横批呢： 巭孬嫑夯昆勥茓 嘦勥昆夯茓巭昇

-----
水木网友freepger： MM在上网，一言不发，我过去在旁边看着表示关怀。只见MM：打开浏览器主页，进入搜狗首页，搜索百度，进百度首页，搜hao123，进hao123首页，点击腾讯，进腾讯首页，点击腾讯新闻，看着花花边边的八卦，露出了欣喜的小微笑。

-----
有个码农写了一程序，遭黑客攻击，大量病毒入侵，他的同事趁他和黑客缠斗时窃取了代码，并改了架构，结果用户体验极差，留下无数BUG。码农愤慨之余，把程序搬到手机上去，结果一段时间后发现，手机竟然比电脑跑得流畅稳定的多，码农看着那台随时死机的电脑苦涩的笑了，这个码农叫蒋中正。

-----
今天在宿舍几讨论男生到底能多懒多脏。一哥们说："我穿内裤都要正面反面轮换。"另一哥们说："我是正反面穿完了前后面再穿的。"正赞叹之际，又一哥们2B的说："你要知道，内裤其实可以当做等边三角形来看，有三个口……所以，可以旋转着穿呦！"

-----
"中国式过马路"，就是"凑够一撮人就可以走了，和红绿灯无关"……

-----
英国一机场售票厅里,许多游客正在排队购票.一位西装笔挺的绅士粗暴地指责售票员工作效率太低,耽误了他宝贵的时间,并威胁地对售票员说:"你们知道我是谁吗?"售票员没有和他争吵,而是对别的旅客说:"你们有谁能帮这位先生回忆一下吗？他已不记得自己是谁了!"游客们顿时哄然大笑起来,绅士则羞得满脸通红.

-----
领导问秘书："钓鱼岛局势紧张，我身边有什么日货，要主动自查。"秘书汇报说："查了，一件都没有。您的车是德国的，表是瑞士的，衣服是法国的，包是意大利的，手机是苹果的，孩子国籍是美国的，最喜欢的那几个小姐，不是国产的就是俄罗斯的！"领导放心地说："那好，那好，那就全力抵制日货吧！"

-----
体育课蛙跳。老师让女生先出发，过一会儿男生再出发，如果后面的哪个男生赶上了前面的某个女生，就可以向她提个要求。我一哥们儿赶上了他喜欢的女生，班里不少人都知道，所以都去围观。只听他字正腔圆的说:XXX，你再去跳一圈，一边跳一边学狗叫！。。。。。。。真活该他屌丝这么多年！

-----
塔利班发声明邮件时没用bcc，于是把他的400多个联系人都cc出去了。。。 - ABC News

Taliban Accidentally Reveal Identities of Their Mailing List Members - ABC News

http://abcnews.go.com/International/taliban-accidentally-reveal-identities-mailing-list-members/story?id=17737950#.ULoPaoVFVTR

-----
美国某校的两名男生在课堂上打架后，校方经研究决定给了他们两个选择：1.被勒令退学。2：手拉手在学校的院子里坐九天。然后，他们选了这个……

file:images/men-holding-hand.jpg

-----
小时候一直搞不懂周岁和虚岁。刚才朋友说："周岁是从妈妈身体里出来的时间，虚岁是从爸爸身体里出来的时间。。"我顿时内牛满面地懂了。。。

-----
刚才滴珍视明滴眼液，闭上眼滚动一下，再睁眼什么都看不见了。吓疯了，大吼大叫。完了，买着假药了，我瞎了！！老爸点着蜡烛冲上来，看见我在黑暗之中，脸上两行清泪，骂道：你这个2B孩子越长越回去了！停个电看把你吓的！！

-----
有一天，小明去学校。同学们说他的脸像屁股。小明很伤心的跑了出去。来到了一口井边上。他把头伸到井里想看看自己究竟是不是真的像屁股。正当他把头伸进去时，井底的挖井工人突然朝他大喊："你TM敢往下面拉屎你就死定了！！！"

-----
毁童年的葫芦娃和西游记

file:images/ruin-childhood-memory.jpg

-----
以前在一个小公司，人少（15个人）但是气氛很融洽，老板和员工都像朋友，经常K歌吃饭什么的，一天因为公司资金周转不过来，老板沉痛的跟大家说要散货了，结果前台mm不高兴了，说这是自己呆着最开心的地方，然后，然后跟她老爸打了个电话，就把公司买下来了……

-----
我知道你知道我知道你知道我知道

file:images/iknow-youknow-iknow.jpg

-----
如果马斯洛生活在现在...

file:images/maslow.jpg

-----
昨晚告知父母，说今天要带女朋友回家吃饭。结果女朋友突然要出差，我一个人回家的路上遇到表弟，就和他一起回我家吃饭。刚进门，老爸先楞了下然后一杯子飞过来大叫：畜生！！

-----
 "生物考得怎么样？ ""可以说脏话吗？"" 不能。""可以用生物学语言表达吗？""呃，可以……""老师，我恐怕要让您的母亲受精了。

-----
 在公交车上看见一年轻的妈妈给宝宝喂奶，宝宝吃得不老实，年轻的妈妈生气说孩子："吃不吃？不吃我给旁边的叔叔吃了"一连说了几次。坐旁边的叔叔忍不住2B的说了一句："我的小少爷，吃不吃给个准信，叔叔都坐超两站了…

-----
 刚在校内看到一哥们一条状态，瞬间给跪：搞对象千万不能找自己宿舍的，分手以后太特么闹心……

-----
 A君很郁闷呆在办公桌前，B君过来问他怎么啦？A君叹气说："最近我老婆下面味道怪怪的。"B君惊讶的说："是不是得了妇科病啊？"A君很激动的站起来："TMD我说的是煮面的面！"

-----
一女在博客上哭诉，说才知道，老公给女儿取得名字是他初恋的名字。并说一直知道自己老公曾经很爱初恋。和自己认识老公一直很好，本以为自己是最幸福的人，现在才知道，原来老公一直没忘记初恋。一网友回：其实你老公是想告诉初恋：我草泥马。。。

-----
 【这八大谎言你知道么？】：1、电信：我们是亏损的。2、老板：我不会忘记你的贡献。3、客车司机：准时出发。4、职员：明天我就不干了。5、服务员：菜马上就来。6、商贩：大亏本、大出血、大甩卖。7、影视明星：我们只是朋友关系；8、领导：下面，我简单地讲两句。

-----
有次我和我男友挤公交，我穿的白色的裙子，大姨妈不期而至，裙子红了一片，于是我向男友投出寻求帮助的眼神，本想让他找东西帮我挡挡，结果...他抱起我喊着，媳妇儿，坚持住！！我们马上去医院，这个孩子一定要保住呀！！尼玛...以后再也不找他帮忙了！

-----
一美女从的士上下来，把照相机落在后座了。司机见状赶忙把头伸出窗外，冲着美女喊："小姐，你相机~"美女一脸红，扭过头骂道："你TMD像鸭！"然后的士走了。后来美女追着喊："师傅，我相机，我相机……"

-----
文课上，女老师问："软的拼音怎么读？" 男生齐喊："日完——软。" 老师："你们男生的发音不标准，请女同学补充回答。" 女同学齐声应："日完俺——软。" 班长纠正说："是日五晚——软。"…… 老师看不下去了，说："应该是日五晚俺——软！"

-----
"你为什么改学经济学了？""因为我对编程缺少灵魂深处的召唤。""说真话。""因为经济学教会了我一种理解世界的方式。""说真话。""因为经济学帝国主义是计算机科学帝国主义豢养的最壮猛的一只猎鹰。""说真话。""因为学编程找不到女朋友。"

-----
君子坦荡荡，小人写作业。商女不知亡国恨，一天到晚写作业。举头望明月，低头写作业。洛阳亲友如相问，就说我在写作业。少壮不努力，老大写作业。垂死病中惊坐起，今天还没写作业。生当作人杰，死亦写作业。人生自古谁无死，来生继续写作业。

-----
宝马里是她前男友。前男友降下车窗问她：你不后悔吗？她说，不后悔，你的宝马是你爸给你的，十年之后我俩也会有宝马的。这是我听过最纯洁励志的爱情故事。十年后，她的自行车换成了电动车。他的宝马换成了兰博基尼。

-----
让男人感兴趣的六大神器分别是：1、豹纹 2、短裙 3、丝袜 4、长靴 5、钢管 6、诱惑的眼神。唯一符合这个条件的只有一个人，那就是孙悟空。让女人感兴趣的五大神器分别是 1、身价高 2、霸气 3、有安全感 4能保护你 5、对你专一唯一符合这个条件的只有一个了，那就是藏獒。

-----
上公共厕所，没带纸。身边只有一百元大钞以及一部手机。我果断拿起手机，拨通KFC。麻烦送个全家桶，特殊要求是男的，多带点纸，位置XXX男厕二号坑……

-----
下面是Linux命令学习时间

file:images/porn-linux-command.jpg

-----
福宝和小区的孩子一起玩，小女孩A从花坛里摘了一朵花要送给福宝 , 福宝转手送给了另一个小女孩B，还去拉人家小手。结果小女孩A生气了，朝福宝脑袋上狠狠打了一巴掌，结果福宝被打哭了，小女孩B被吓哭了，现场乱作一团...

-----
这个绝对高级口语……怪不得六级到现在都过不了！！

file:images/broken-oral-english.jpg

-----
【如果卫生巾不叫卫生巾，你觉得会叫什么呢？】1. 创可贴 2. 藏经阁 3. 女儿红 4. 吸血鬼 5. 新型ufo 6. 海绵宝宝 7. 好朋友 8. 中原一点红 9. 含红 10. 大姨夫 11. 九阴真巾 12. 草莓酱白面包 13. 超大号创头贴……

-----
早晨起来看微博，确实很容易让人产生一种皇帝批阅奏章，君临天下的幻觉。国家大事潮水般涌来，需要迅速作出各种判断，提出各种建议，各种转发，各种忧国忧民，各种踌躇满志，万物皆备于我。每个人心中都藏着一个披星戴月上朝堂的皇帝，微博把人的这种情结激活了。

-----
唐僧："悟空你听我说，最近悟净的行为很奇怪。为师多说了他两句，他就一言不发走开，然后躺进小白龙的食槽里。"悟空："沙师弟不善言辞，他应该是在用行动表达对您的不满。""什么意思？""卧槽！"

-----
关雎鸠，在河之洲，窈窕淑女，what's your QQ！！但使龙城飞将在, come on baby don't be shy！！天上掉下个林妹妹，whatever i'm gay！！！曾经沧海难为水，what the fuck did you say！！树上的鸟儿成双对，make love everyday！！停车坐爱枫林晚，look listen and see！

-----
丈夫挑衅妻子的智商！ 丈夫问："亲爱的，你有水平说出让我既欢喜又生气的话吗？" 妻子沉默了一会说："我发现在你朋友中只有你是不用吃伟哥的。"

-----
芒格说：＂许多IQ很高的人却是糟糕的投资者，原因是他们的品性缺陷。我认为优秀的品性比大脑更重要，你必须严格控制那些非理性的情绪，你需要镇定、自律，对损失与不幸淡然处之，同样地也不能被狂喜冲昏头脑。"查理·芒格是沃沦·巴菲特的黄金搭档，有"幕后智囊"和"最后的秘密武器"之称。

-----
有人路过一茶货铺，叫"陈罐西式茶货铺"于是有人回复说好想在旁开家张柏芝士蛋糕房又有跟帖说想开谢霆蜂王浆专卖店吴彦祖传老中医萧亚宣纸专卖店吴奇隆胸专业会所周杰伦胎专卖陈奕迅捷快递苍井空调专卖店郭富成都小吃。。。。

-----
悟空听说那iPhone4S是件稀罕物，便飞往美国买了，然后天天骚扰师父。这天又拨打唐僧电话，却猛地将崭新的手机摔在地上。悟空破口大骂"唐僧你个死变态，彩铃设成紧箍咒"。（

-----
有一种运动，生理学家叫它手淫；心理学家叫它自慰；古典学家叫它手统；普通青年叫它打飞机；文艺青年叫它自渎；二逼青年叫它撸管儿；小日本青年叫它手恋...... 你叫它什么？

-----
一同事毕业后，跳了4,5家公司，问题是他每次跳槽后，都换了个英文名，我非常纳闷，问他为什么，他笑而不语，在我威逼利诱下，他终于说了："我每个英文名都取我上一家公司技术最牛X的那个人英文名，这样如果有人向我以前的公司打听我的话，都会觉得我技术是最牛X的！"

-----
大学男生宿舍从一楼走到六楼，基本可以听见电脑里发出这几种声音，1，"Fire in the hole……" 2，"double kill……"3，"詹姆斯在对位杜兰特身体上完全不吃亏……"4，"人在塔在……"5，"亚美蝶亚美蝶……"6，"你存在我婶婶的脑海里……"……

-----
和女友吵架冷战，女友上我QQ到她空间留言"对不起，我错了"。。。然后自己回复"哼！懒得理你……"。我……

-----
【一位师姐给各位师弟师妹的忠告……】作为一名师姐，我只有三个忠告给我的师弟师妹们。第一：不要和我们抢早饭。第二：不要和我们抢午饭。第三：不要和我们抢晚饭。还有特别给师妹的忠告，师兄都是你们的，请把网速和饭留给师姐。谢谢合作！

-----
参加客服培训，听到一个开除案例：一个接线员接到一个客户的电话，客户是个磕巴说话有点慢：我我我....想想想问下，我我我.......电....话话话费.......最最最近.....怎么这样费？接线员只说：大大大大哥就就就你这样能能能不费吗？ 之后他被开除了！参加客服培训，听到一个开除案例：一个接线员接到一个客户的电话，客户是个磕巴说话有点慢：我我我....想想想问下，我我我.......电....话话话费.......最最最近.....怎么这样费？接线员只说：大大大大哥就就就你这样能能能不费吗？ 之后他被开除了！

-----
中国的毛病，可以从央视中一览无余：综合频道一片虚荣；财经频道一片信心；综艺频道一片喧嚣；国际频道一片战火；体育频道一片自夸；电影频道一片红潮；农业频道一片富足；电视剧频道一片婚变；英文频道一片指责；科教频道一片领先；戏曲频道一片高调；法制频道一片神探；新闻频道一片深表遗憾。

-----
 1.一个女的拿了老公的IPAD到闺蜜家上网，结果发现WIFI自动连上了……2.某人骂微博推荐系统：什么烂推荐系统，把我前女友推荐给我老婆，说你们有共同好友！3.一个女孩将前男友从Q删除了，过几天弹出提示：你可能认识他。女孩心想：妈的何止认识！！！

-----
某学长签名 —— 昐了二个月，终于等到开学了，结果太让我失望了，看到了不少学妹，有的长的像学姐，有的长的像学长，还有的尼玛长的像家长。。。

-----
火车上的售货员总喊着这样的一副对联。上联:香烟啤酒矿泉水烤鱼片了啊～下联:白酒饮料方便面火腿肠了啊～横批:腿收一下。

-----
分别来自浙江大学、浙江理工大学、浙江财经大学的女生去应聘，老板问她们各自毕业院校。A女拍着胸脯说：浙大！B女也毫不示弱地拍着胸脯说：浙理大！C女鄙夷地看着前两个，自信地拍着胸脯说：浙财大！

-----
【新生师妹开学注意事项】1.主动和你搭讪的师兄不是好师兄;2.自称和你是老乡的师兄最危险;3.认识的师兄越多交到的朋友越少;4.好师兄是没时间关心学妹的;5.师兄的笑是使坏的信号,师兄的暧昧是计划的前奏;6.关心你学习的师兄一定是虚伪的;7.迎接你报到的师兄衣冠楚楚,但整个学期也就那一天楚楚。

-----
我的前任女友是学英语专业的，人也挺不错，就是受不了说话老是爱夹英语，夹英语我就忍了，尼玛别在嘿咻的时候也夹啊，夹你也说些bABY什么的就算了，就老是子那里喊，偶~good~good~！good~你妹啊~！！

-----
一便衣坐快巴，在车上等发车时，看到前两排一个青年很急躁的样子，一直在发抖，流鼻涕，抓头发，咬牙切齿。看了几分钟，怀疑对方是"粉仔"就走过去亮出警官证，对那青年说:"你好，我是警察，请问有什么可以帮你的吗？"那2B青年愣了一下，然后很尴尬的指着座位旁边的两袋吃光的泡椒凤爪……

-----
语文考试，有道填空题：扁鹊见蔡桓公，立有间，扁鹊曰："君有疾在腠理，不治将恐深。"桓侯曰："寡人无疾。"扁鹊曰："—————" 让学生们填上。 有位学生填：走两步，没病走两步。

-----
一驾驶员向路边倒车，看到旁边站着一位老人就说："大爷，要撞上了麻烦您告诉我一声。"老人："好的，好的，倒吧！倒，倒，倒。"咣的一声巨响，老人："好了，撞上了。"

-----
学姐和学妹有可比性么？学姐帮你选课，给你画重点，给你复习资料，还帮你写论文。学妹就只能说：学长怎么选课呀～学长重点是哪里啊～学长论文怎么写呀～学长你有复习资料吗？学长学长！你怎么不说话啦？…………中国野生学姐保护协会提醒您：远离危险学妹，保护濒危学姐！

-----
朋友的英语差的是惨不忍睹的，找工作的时候鬼使神差的进了一家语言培训机构，有一天陪外教去上课，想提醒一下外教把手机调成震动的。很友善的对着外教说：please make your telephone嗡嗡嗡，not得铃得铃得铃。奇葩的是外教居然听懂了……

-----
一对情人50年后相见，想到从前，感慨万千，遂欲再亲热一番。半小时后，老头感叹: 一江春水已流干，两座高山成平川，昔日风景今不再， 只剩两颗葡萄干。老太感叹: 枯草堆里到处翻， 始终不见枪和蛋，岁月沧桑不饶人，只见一根萝卜干。

-----
真兄弟！！

file:images/good-brother.jpg

-----
幼儿园开学，许多孩子被送来，家长走后，孩子们哭闹着，简直跟宰猪场差不多！这时候，唯独有一个小孩蹲在墙角巨蛋定，老师准备好好夸一下他，刚走近，那个小孩以迅雷不及掩耳之势，抢过老师手机，连号码都没拨，拿起手机就对着手机哭喊着："爸爸，快来救我啊！我被妈妈卖了...

-----
海南省海口市海府路与国兴大道的交叉路口处，有几块路标牌重叠挂在一根杆子上，最多的有7块方向牌堆叠在一起，让人眼花缭乱，看了也分不清东西南北，被网友称为"最牛路牌"。

file:images/hainan-road-sign.jpg

-----
电梯坏了，老实巴交的肯德基小哥也不知道打个电话，像圣斗士一样背着四四方方的大箱子一层层地爬楼。我看着有些不忍，就上前与他攀谈，希望借此减轻爬楼的枯燥与疲累。终于，小哥到达了13楼。他感激地对我说，谢谢你，大哥。我说，不必客气，把我订的肯德基给我吧。

-----
话说天下大势，合久必分分久必合，统一最大的敌人是？是康师傅吧！

-----

一路口，一大众和宝马3系在等红灯，对面一宝来不知是抽风的还是怎么了直直冲过来看着马上就要撞到3系了，一个转向撞到了大众，3系就这样唱着最炫民族风走了宝来车主下来一个做辑然后赔笑："3系是在撞不起，只好撞您的帕萨特了"那大众车主冷笑道："见过12缸的帕萨特么

-----

一直觉得《西游记》有个BUG，唐僧肉吃完长生不死，他为什么不咬自己一口？咬完任你各路妖魔奈我何？轻装上路差旅费省四分之三，后来想明白了，觉得吴承恩设计的真他娘缜密——和尚不能吃肉。

-----

刚刚和几个同事讨论好公司的标准，结论如下：1.前台大美女，2.上班不打卡，3.厕所不排队，4.上网无限制，5工资有点高，6.基本不加班，7.上班不无聊，8.死党四五个，9.出差住五星，10.报销不麻烦，11 team building有点多，12.公司没事就发东西，13.HR和Admin态度好。。。。。。

-----

古代人如何说现在网络语言 【1】 城门失火殃及池鱼——躺着也中枪； 【2】 呜呼！——我靠 【3】 是可忍孰不可忍！——草泥马 【4】 黄袍加身——屌丝的逆袭。

-----
老婆出差，刚到就给我报平安，放心了

file:images/wife-makes-me-dont-worry.jpg

-----
写代码的，都是特么的诗人

两个黄鹂鸣翠柳：Tree_0f0=sprintf("2_Bird_ff0/a")；

人生自古谁无死： for_$n(@RenSheng)_$n+="die"；

两岸猿声啼不住：while(1)Ape1Cry&&Ape2Cry；

锄荷日当午：dig?F*ckDang5；

平生不看武腾兰，便称男人也枉然：ps!see(5tl)shit!say(man)

-----
父亲：女儿，请记住这五个人生忠告。1、学会拒绝。2、不畏挑战。3、勤奋好学。4、从不同角度思考问题。5、永不言败！女儿：我懂了，就是"雅蠛蝶"、"大力点"、"不要停"、"换个姿势"、"再来一次吧"！。

-----
一中国人给外国人考听力试题，题目如下： 羊毛衫大减价啦，件件10元，样样10元，全部10元，问：什么10元？ A件件 B样样 C全部 D羊毛衫

-----
小张童鞋很喜欢吃素包子，一天去买包子的时候发现涨价了，就问老板"怎么包子涨价了？"老板说："因为肉价涨了"。小张就问"肉涨价，素包子为什么要涨价啊？"老板说："因为做包子的师傅他要吃肉啊！"

-----
以前有女朋友的时候每次被问在干嘛我都要想一种在电脑前看书写代码的讲法，比如抚摸键盘、研究屏幕像素点变化等等

-----
孔子是微博开创者，《论语》是最早微博集： 1、每条论语都未超过140字； 2、言简意赅、寓意深刻； 3、较为碎片化，多为孔子晒心情，交流哲理； 4、互动性强，经常和子贡、颜回、子路等进行回复，互动； 5、孔子拥有3000多粉，其中72人为VIP。

-----
什么叫微博？一个约炮都不会的教给你怎么了解女性，一个连圣经基本教义都不懂的演员向你传教，一个连法律基本程序都不懂的律师向你传授依法治国，一个连真假都搞不清的贩子教你玉的鉴定，一个经常造谣传谣的南方系媒体人告诉你记者的基本操守。这就像：一个傻逼告诉你他可以教给你如何变聪明。

-----
一男发浪漫短信给女友：你在干嘛？在做梦吗？把梦传给我；在笑吗？把笑发过来；在哭吗？把泪水传过来，让你的眼泪和我一起悲伤。女友回复：我在便便。

-----
我的男朋友是个学霸，你们输给DOTA，我输给代码

昨天七夕，他来接我下班，还带我去吃饭，听起来温馨浪漫。一坐下来就忙问我要笔记本和笔，问他要干什么，答曰：构思数据库。。。数据库是男是女啊？长得好看吗？身材好吗？

他吃得比我快，吃完后坐着看我，我一边埋头吃一边想，这场面真是温馨，喜欢的人在对面，看着我吃好吃的。想起就感动。结果我一抬头，尼玛，原来是在看我背后的电视，我转头看过去，发现新闻女主播长得还挺好看的，就问他"她好看还是我好看？"。结果人转过头来很严肃地对我说"摩托罗拉要在中国裁掉80%的员工了"。。。。。。。我心里有万头草泥马狂奔而过，多少次这样的对话我都只想以"关我屁事，关你屁事"来结尾啊

新闻播完了，转过头来和我聊谷歌和摩托罗拉，说谷歌的软件卖的贵，我嘴贱问了句"为什么贵？"，"因为中国有GFW，谷歌的服务器在国外"，再次嘴贱"你又说我听不懂的了，GFW是什么？"。"就是防火墙啦"。"那你为什么不直接说防火墙？！"。"因为那是特殊的防火墙啊"。"那你为什么不直接说特殊的防火墙，说个GFW，全称是什么嘛？"，"great fire wall 啊，你知道great wall 吧，就是长城的意思"。。。万头草泥马再次呼啸而过，尼玛，我六级松松通过，还用你来解释小学词汇great wall。卧槽！恋爱中的女生不至于傻逼成这样啊卧槽！

早上起来打电话："在干嘛？"，"写代码"。

中午吃饭打电话："在干嘛？"，"写代码"。

午睡前打电话："在干嘛？"，"写代码"。

晚上一起吃饭："在想什么？"，"构思代码"。

睡前打电话："睡了嘛？"，"没"，"那在干嘛？"，"写代码"。

以前看到一条状态，是一个工科男给他女朋友做了个网站作为生日礼物，里头有一只很可爱的小老鼠。我让他去看这个网站，说是一个工科男做给人家女朋友的，你看那只老鼠多可爱。意思明显到只差说"你看看人家！"了。结果长时间未回复我，过了好久，给我发来了一大段代码，真的一大段，都刷屏了，最后来了句："这是那只老鼠的代码，你不是喜欢那只老鼠吗？"。。。。。草泥马再次奔腾起来。。。

记得第一次去上橄榄球课，上完后电话里对他抱怨："橄榄球好累啊，跑来跑去的，好辛苦"，傻逼都知道这个时候应该回答"累了一天要好好休息呀"、"上课不要太拼命"诸如此类安慰的话。结果丫说"橄榄球就是这样啊，它上下半场加起来只有14分钟，规则是blablabla……"，我听着听着就睡着了。。。。我有涵养吧~

每每这个时候，我总是想为什么我会和这样一个人在一起这么久？或许是因为他在一边构思那个代码小三时，一边还是牵着我的手。或许是我随便一说想去哪儿，他就会马上把路线和住宿的查好。或许是只要我一说不舒服，就马上把要用的药都查好送过来。或许是我一生气放大招不理他，他坐在边上不知所措的样子。或许是我一次次任性地说"你一点都不好，一点都不喜欢我"的时候，你生气地说"我要不喜欢你，我大老远跑来给你送吃的？！"

最后我们往往都是哀叹一声"唉，谁叫我喜欢你呢"……

-----
今夏巨星扎堆发片，乐坛型男潮叔包青天携新专《Judge Bao》空降本周华语榜中榜：1.你永远不懂爷的黑(Black Forever) 2.看我脸色72变(Poker Face) 3.本府是碳，黑到忧伤(Black Tragedy) 4.开封府之夏(Summer in KaiFeng) 5.升堂（RAP）6.王朝马汉今何在(Pray for My Soldiers) (via 谁允许你直视本蜀黍)

-----
#+BEGIN_VERSE
冰清玉洁武藤兰，三贞九烈小泽圆。
不近女色陈冠希，天生丽质金喜善。
坚持原创郭小四，低调沉稳数韩寒。
清心寡欲小日本，万恶帝国美利坚。
与邻为善以色列，安宁祥和阿富汗。
国强民富看朝鲜，宇宙起源在南韩。
民主典范金正日，和平斗士本拉丹。
从不掉线天涯网，从不删贴管理员。
优秀记者冬日娜，尖嘴猴腮毕福剑。
只讲真话西西踢维，人民喉舌焦点访谈。
天籁之音曾轶可，大家闺秀李宇春。
守口如瓶宋祖德，字正腔圆周杰伦。
洁身自好赵忠祥，铁汉无泪冷朱军。
水准专业孙正平，从不口误韩乔生。
貌若天仙芙蓉姐，百毒不侵满文军。
诚信经营陈天桥，永不模仿马化腾。
重庆好人谢才萍，无家可归贾君鹏。
低速行车杭州市，交通顺畅北京城。
舍己为人范跑跑，眉清目秀冯小刚。
用色淡雅张艺谋，代言保真唐国强。
物美价廉奥菲斯，低调奢华阿迪王。
学识渊博余秋雨，淡泊名利查良镛。
勤俭持家章小蕙，从不炒作张纪中。
白面书生奥巴马，没有炸弹巴格达。
和风细雨马景涛，苗条骨感沈殿霞。
高大威猛属梅西，从不假摔是Ｃ罗。
料事如神贝球王，只争第一是国安。
足坛巨擘李大帝，世界强队国足男。
文明执法闵行区，国虎出没镇坪县。
干净公平全运会，春风拂面好城管。
无毒无害三鹿奶，营养健康方便面。
强身健体俯卧撑，安全游戏躲猫猫。
爱管闲事酱油党，不明真相老百姓。
水深火热蛮夷众，欢欣鼓舞天朝民。
#+END_VERSE

-----
都说骂人要文明，于是某同学把"真TMD不爽"译为"诚其母之不悦！"

-----
中国的汽车广告只有两种！！！中低端车永远是：老子家庭幸福！有娇妻！有可爱的儿女！老子喜欢带全家人开车出去玩！中高端车永远是：老子事业有成！有美女！有红酒！有合同可以签！老子喜欢独自开车出去装逼！

-----
这是早上乘地铁时遇到的牛人。地铁上，突然一个哥们儿的电话铃声大作，众乘客一听"爷爷，那孙子又给您来电话了……爷爷，那孙子又给您来电话了…… 爷爷，那孙子又给您来电话了……" 只见那哥们儿慢慢悠悠的掏出手机，接听："喂，爸，什么事…… "

-----
今天客户来银行取钱，坐下一句话说的我石化了："你好，我死期到了。"

-----
开心辞典，小丫主持问选手：一年365日，男人最怕哪一日？女人最怕哪一日？男答：男人最怕1月31日。女答：女人最怕12月1日。小丫：回答正确！! !...........

-----
问一懂手机哥们，磨砂屏幕贴膜和普通的膜有什么区别？他默默的发了张图片过来，我瞬间就明白了！

file:images/polish-difference.jpg

-----
偷看某人微博看来个笑话：有個人在internet要reset password,結果他新的password是supermanbatmanironmancatwomanspidermanrobinwashington,知不知道為甚麻？因為rest password 要six characters and at least 1 capital......

-----
新兵清理军营围墙卫生，趁没人管趴那偷懒，见一穿便装的大爷在墙外散步，就喊：大爷帮忙买包烟吧，那大爷说你们不是不让抽烟吗？那新兵说我没事的时候抽一根而已，帮帮忙呗，青岛人都是活雷锋。于是大爷就帮他买了一包。晚上开会的时候，队长大骂，MD谁叫司令帮忙买烟的，还青岛人都是活雷锋。

-----
据说，扬州一女生因收到玫瑰花后发现是货到付款而与男友分手。。。

-----
牛郎和织女的故事告诉我们，偷看女生洗澡是找媳妇的一个好方法

可惜通过这种方式找到的，一年只能见一次。

-----
海外争端叠起，我们的看门阿伯说：解放军也该干点事儿了，不能白喝了三十多年茅台吧？

file:images/boom-it.jpg

-----
去饭店吃饭，剩了一些菜，我就对服务员说，给我打个包吧。服务员点了点头，出门喊了几个服务员，冲进来把我的头上打得都是包。

-----
【面试】尼采去面试，面试官问："你叫什么？""尼采。""猜你妹啊！下一个！" 网友跟帖：亏他不叫尼迭！

-----
【段子：数据分析让你更安全】有一个美国数学教授平生最怕坐飞机，他研究了近20年的统计数据，发现恐怖分子带炸弹上飞机的几率其实非常低，但是他还不安心，他又进一步研究数据发现，两个人同时带炸弹上飞机的几率几乎为零，于是从此他坐飞机都自己携带一枚炸弹。

-----
不要脸这事，如果干的好，叫心理素质过硬。。。

-----
老北京面馆最大特色就是吆喝。有天两人去吃面，跑堂吆喝上了："5号桌，炸酱面两碗"吃完结帐，共25元8毛。甲说："给你26，别找了"跑堂接过钱便吆喝："5号桌有客送小费2毛"满大厅的人回头看他，甲脸红了："得，那2毛你还是找我吧"跑堂又吆喝上了："5号桌的2毛小费又要回去了!"

-----
问：沙僧担子里究竟挑的什么？答：应该是师傅的内衣裤，剃须刀，还有发蜡，男士洗面奶，墨镜，出入境通行证，银行卡，户口本，导航仪，宝马的驾驶证！大师兄的染发剂，洗发水，护发素，修毛剪。八戒的营养快线，可乐，汉堡，薯条，减肥茶，PSP游戏机，MP3，iPad！

-----
屌丝从毕业时的月入3000到三年后亿万身家

刚毕业我只有3000，但我立志三年后要月入3万是在一家广告公司，每天跑业务我每天都很勤恳地和前辈学习，连修理打印机都自学成才了老板看我很努力，多有嘉许毕业半年后转正，薪水3300 经理找我谈，说如我愿接受夜班，可再加500 我没动心因为晚上是自我提升的宝贵时间我泡图书馆，借了财务的书来看自己必须有一技之长才有立足之地我开始准备CPA和CFA 广告业务也慢慢上了正轨拿到了单，为公司创造了效益年底公司发了2000的年终奖工作满一年，我向老板提出加薪老板没同意，只说年轻人要多学我非常认同，便更加努力下班后我还发挥大学的长处为小朋友补习功课每周补习10小时，每月40小时每小时我收费40元相当于薪水又多了1600元我去考了CFA一级可惜没过，但我并不气馁我需要更加努力到了第二年年底，加了300薪水每月3600，加上奖金有时能到4000 家教做的也不错，现在50元每小时了东家帮我介绍了别家客户每月补50小时家教收入也达到了2500 通过两年的努力，我有了一些积蓄差不多一万我开了一个淘宝店，先是帮人充话费后来卖点卡无人问津，有时朋友帮衬一下有朋友说必须得刷出来好评才有人买然后我想了想，自己小号买给好评然后被发现了，店被封了申述未果虽然没赚什么钱，不过也没亏年中又考了一次CFA一级，这次过了对未来又有了更多期望交了女朋友，她月薪2000 我抱着她，憧憬未来我向她保证，毕业3年一定年薪30万她不信，说已经两年半了还看不到希望我就拿出我攒的一万块钱，进入了股市开始运气好，很快一万变成了两万我信心愈发强了这样慢慢经营下去，又过了3个月股市跳水，只剩下了500 后来女朋友跑了，但我并不气馁不过，眼看着快到毕业三年的时间我还只是一个月6000上下的收入于是我放大招了，使出了最后的一搏我把我的薪水换算成了越南盾共计月入约1.97亿元是的，我超额实现毕业时的理想了。。。。

-----
"我成亲了。""恭喜恭喜，能讲一下细节吗？""注册了个淘宝，就变成亲了。"

-----
 【男子因自行车胎被扎爬上25米高广告塔骂街 称爬得高骂得远】夏邑县一男子因自行车胎被人扎破，一怒之下爬上高达25米的广告塔高声叫骂，造成交通堵塞。

-----
关于刚刚的小强爬进air usb孔事件,感谢各位提供的宝贵而不靠谱的建议…在试过了狂甩,闪光灯,猛敲等一些列手段无效后,我打开土豆随便开了个flash,不到2分钟小强就主动逃出来了.

-----
电影里是嫌犯一死所有的线索都断了；新闻里是嫌犯一死所有的案子都破了。

-----
以前爷爷喜欢下棋，下不过邻居大爷，很苦闷，我就想替他报仇。私下找邻居大爷，他说让我，我说不要，打开手机里"象棋大师"，调到专家难度。大爷下一步我摁一步，机器人下一步我学一步。大爷都傻了，连输4局。后来他居然找我拜师，说我是天才，一边玩手机都这么厉害，都不带想棋步的…

-----
提问：美国人尿急的时候会变成。。。。。。 回答：姜国人 ！！！

-----
阴暗潮湿的北京某地下室，一瘦弱青年一手拿了2块钱一包的烟，一边看着凤凰网军事频道，愁眉紧锁的他陷入了沉思：国家下一步该怎么走？如何突破美国封锁？如何收复台湾？如何保住南沙钓鱼岛？如何剿灭反华势力？一个个难题需要他思索，抉择。此时，传来踹门的咣咣声：开门！警察查暂住证！

-----
没见过这么霸气的狮子

file:images/stone-lion.jpg

-----
送给吃货们的打油诗:床前明月光,想喝疙瘩汤。春风又绿江南岸,明月何时烤冷面。人比黄花瘦,犹记锅包肉。小荷才露尖尖角，一看排骨炖豆角。月落乌啼霜满天，松仁玉米地三鲜。君问归期未有期，来盘榛蘑炖笨鸡。我劝天公从抖擞，煎饼果子配鸡柳。在天愿作比翼鸟，街边坐等吃烧烤

-----
姓黄的一个父亲，给他儿子取名一个军字。一天，他带儿子等8路公交车，突然车来了。父亲叫道"黄（皇）军，八路来啦！旁人齐投困惑的目光。。。（转）

-----
儿子被爸爸修理了，跑去找妈妈诉苦："妈妈，有人打你儿子你会怎样？"妈妈："我会打他的儿子报仇！"儿子："……"

-----
我有一个朋友，昨天晚上去吃烤翅，他拿着瓶啤酒对服务员说："你信不信我能徒手起瓶盖？" 服务员摇头说不信。朋友一拍桌子："那你还不拿起子去！"

-----
和女朋友去逛街，路遇一猥琐男。一个劲盯着我俩看，看到那龌龊眼神我顿生怒气，冲他喊了句"看你妹啊！" 逆天的一幕出现了。我女朋友眼前一亮"哥！你怎么也来逛街"....我勒个去。。 。

-----
对面坐了一对情侣，男生不好看，女生长得还挺文静。女生跟男友说：今天我看着xxx男友了，丑死了啊啊啊啊，男生说："比我还丑么？"这时我跟媳妇都以为女生会安慰他，说句老公你不丑之类的，三秒后，女生：跟你不是一个丑法。

-----
某教授在田间授课："科学研究要不怕脏。。。"然后他蹲下来，用手指戳了一下地上的牛粪，然后把手指放到嘴里舔净。一同学忙说："我不怕脏。。。"然后也用手指戳了一下地上的牛粪放到嘴里舔净。教授："另外还要善于观察，比如说，我刚才是用中指戳粪，但舔的是食指。。。

-----
去剪头发，一坐下，剪头发的男生就问："美女，做个一次性烫好不好？很漂亮的！"我说："不烫。"几分钟后，他又问："烫吗？！"我说："不烫。"过了会儿，剪完开始用吹风机吹了，但是风有点烫，男生问："烫吗？"我说："烫！"于是他就给我烫起了头发。。。

-----
痞子约架码人，电商约架码货！痞子约架码人比比谁有牛人，电商约架码货比比谁有贱货。

-----
缅甸版"龙的传说"：有一条恶龙，每年要求村庄献祭一个处女，每年这个村庄都会有一个少年英雄去与恶龙搏斗，但无人生还。又一个英雄出发时，有人悄悄尾随。龙穴铺满金银财宝，英雄用剑刺死恶龙，然后坐在尸身上，看着闪烁的珠宝，慢慢地长出鳞片、尾巴和触角，最终变成恶龙。

-----
朋友有点痔疮，喝酒，吃火锅，第二天会很痛（我之前不知道），昨天我心情不太好，死活拉着要和他喝酒，还吃滴火锅，第二天，上班的时候在电梯里，他突然就对着我说老子以后再也不和你喝酒了，屁股好痛！结果瞬间电梯里就安静了，都是一副我懂了的样子！我。。。

-----
人生最高的境界

拿沙特工资，住英国房子，用瑞典手机，戴瑞士手表，娶韩国女人，包日本二奶，做泰国按摩，开德国轿车，坐美国飞机，喝法国红酒，抽古巴雪茄，穿意大利皮鞋，看奥地利歌剧，买俄罗斯别墅，雇菲律宾女佣，配以色列保镖，当中国干部。

-----
程序出错后，程序员给测试人员的20条高频回复

第1条会是什么？猜猜看吧！

   20. "That's weird…" 很奇怪……
   19. "It's never done that before." 以前没这样过的。
   18. "It worked yesterday." 昨天还好好的。
   17. "How is that possible?" 那怎么可能？（怎么会出问题？）
   16. "It must be a hardware problem." 这一定是硬件问题。
   15. "What did you type in wrong to get it to crash?" 你输入什么东西后才崩溃的？
   14. "There is something funky in your data." 你的数据有问题。
   13. "I haven't touched that module in weeks!" 我好几个礼拜没动那个程序了！
   12. "You must have the wrong version." 你一定在用错误的版本。
   11. "It's just some unlucky coincidence." 这只是凑巧。
   10. "I can't test everything!" 我无法测试所有东西。（我的机器环境下，无法测试所有的可能情况。）
   09. "THIS can't be the source of THAT." "这"不可能是问题的原因。
   08. "It works, but it hasn't been tested." 程序能用，不过还没有测试。
   07. "Somebody must have changed my code." 一定有人改了我的代码。
   06. "Did you check for a virus on your system?" 你的电脑扫描病毒了么？
   05. "Even though it doesn't work, how does it feel? 即便程序不行了，（你觉得）程序写得如何？
   04. "You can't use that version on your system." 你不能在你系统上使用那个版本的程序。（程序版本和系统有冲突。）
   03. "Why do you want to do it that way?" 你怎么会想着那样操作啊？
   02. "Where were you when the program blew up?" 程序崩溃时，你在做什么呢？（做了哪些操作？）
   01. "It works on my machine" 在我机器上好好的！！！（潜台词：怎么在你那就出问题了呢！！！）

-----
年复一年，计算机人该做什么?

在一个潮湿的地下室里,一个双眉紧锁的青年,手里拿着干涩的面包,聚精会神地看着桌子上世界地图,他深深地陷入了沉思:国家下一步的发展策略是什么?国际形势会怎样发展?怎样处理好国际关系?如何对美军,台湾全面作战,一个个难题他需要思索,需要抉择.正在这时,外面响起了剧烈的砸门声,一个声音高叫着:"都他妈把门打开,不然踹门了,把身份证暂住证都准备好".他含泪默不出声…一会儿外面的人走远了,强大的信念再次站了起来,他迅速调整好了情绪,满怀激情地进入了下一番思考.

-----
为什么我们又输了

一、草皮不适应
1.草皮太硬了。 2.草皮太软了。 3.不适应阔叶草及其他一些草.

二、天气原因
1.下雪。 2.下雨。3.下冰雹。 4.阳光太好了。 5.冷。 6.热。 7.不冷不热（不能给对手造成麻烦）

三、赛场因素
1.场内因素：A.裁判帮他们。 B.裁判不帮我们。 C.对手身体太强壮。 D.对手技术太细腻。 E.门柱帮了他们。 F.对方守门员发挥超常。 G.补时太短。 H.补时太长。
2.场外因素：A.客场作战，气氛影响。 B.主场作战，干扰太大。 C.观众不为我们喝彩。 D.有人往场内扔手雷。

四、抽签抽的不好
1.同组都是强队，按惯例当然应该中国队输。
2.同组都是中等水平队，踢输了，主要是想赢怕输的思想包袱太重了，队员们没能放得开手脚。
3.同组都是弱队，踢输了，对对手不够重视，麻痹大意，一时疏忽。

五、输球不输嘴
1.对亚洲强队踢输了，是恐X心理在作怪，走不出阴影。
2.对亚洲弱队踢输了，对手进步太大了，太大了，我们对他们没有秘密可言。
3.对欧洲弱队踢输了，中国队输给了欧洲队。
4.对欧洲强队（比如意大利队）0：1踢输了，告诉大家一个好消息：中国队仅以0：1输给了强大的意大利队！
5.对欧洲强队（比如意大利队）0：10踢输了，中国队踢出了自己的一贯水平，队员们也努力了，结果也不出全国人民的意料。
6.对欧洲强队（比如意大利队）0：100踢输了，精彩的比赛！意大利某球星进了20个，某球星进了25个！看来中国队跟意大利队的水平差距确实是有一点的。

六、没用的"海龟"
"海龟派"没回来踢输了，我们雪藏主力；"海龟派"回来踢输了，时差没倒过来。

七、基础条件差
1.主教练技术差！
2.中国球迷素质差！
3.中国足协这个名字差！
4.中国队队医技术差！
5.中国足协领导人办公室里的那位倒水扫地的大妈差！

八、终于…
草皮不软不硬，天气不冷不热，裁判和门柱净帮我们，对方没有守门员，补时时间长短由我们说了算，到第三国去比赛，观众全部为我们猛喝彩，观众全都不往比赛 场地扔手雷，抽了一个人人都说好的签，"海龟派"回来后猛睡了一个月倒回时差参加比赛，换了个主教练，换了批外国球迷，换了个中国足协的牌子，换了中国队的队医，换了中国足协领导人办公室里的打杂大妈，踢输了。原因是：今天我们队，真他妈不在状态！

-----
伦敦行动：【能告诉13亿人,你们哭什么？】温甬高铁事件，你们没哭；天津大火，你们没哭；北京大水，你们没哭；强奸幼女、逼幼女卖淫，你们没哭；半夜给拖出来，家被强拆，你们没哭；8月大的胎儿强行堕掉，你们没哭；空巢老人留守儿童无人照料，你们依然没哭。。。刘翔不小心摔倒，你们都哭了。。

-----
在刘翔摔倒后第一个把他扶起来的匈牙利运动员巴吉·巴拉扎斯说：其实我也听说在贵国不能扶摔倒的人，会被敲诈，要赔很多钱，所以扶之前我犹豫了一下。

-----
如果以后全世界都没人要你，一定要记得还有我。我也不要你~

-----
在男子10米台双人决赛中，当两位选手身高、体重和年龄差异都很大的选手齐齐入水之后，电视解说员认真地请教旁边的嘉宾："按道理说，自由落体运动中，质量轻的落得慢，质量重的落得快，他们是怎样控制一起下落呢？"那位嘉宾想了想认真地回答："那是他们平时认真训练的结果！"

-----
站在洗头房的门口

夜幕降临，华灯初上的时候，街边一排洗头房无疑成为光怪陆离的都市以唯一的一抹亮色，一点温馨。我酒足饭饱后，站在人头攒动的夜市旁，望着临近的洗头房，心中不禁泛起阵阵感慨：它们卑处一隅，绝不炫耀，毫无所求，只知奉献，精巧别致的房间透露着橘红色的灯光，以一种柔和暧昧和都市里华而不实的霓虹灯苍白刺眼的路灯对峙着，争辩着，以无言的行动响应着国家节约型社会的号召。周围尽管一片杂乱喧嚣，但它的门面布局仍是那么古色古香，让你不由得驻足停留，细细欣赏。传统的对联式门框在这里复现：上联：按摩，下联：休闲，横批：美容美发，将中国风的精髓发挥得淋漓尽致。洗头房内不时传来形象代言人任贤齐的歌声：" 我让你依靠，让你靠，没什么大不了"，更增添了几分文化气息。一切的特色让街边那些大楼广场黯然失色。

倚门站立着几位年轻的姑娘，身着复古的服饰，仅以一片红花布遮住前胸，让我想起远古人民的伟大。她们脸上挂着诚挚的笑容，洋溢着扑面而来的热情，召唤鼓舞着沿街的革命同志，不管是满身酒气的大款，满脸疲惫的民工，还是稚气未脱的学生，都一视同仁，毫无偏见，在这个孤寂的夜晚去温暖他们那冰冷空荡的内心，敬业的精神让我不禁肃然起敬。看着看着，我的眼里闪出了泪花，脑海中想起了貂蝉，李师师，秦淮八艳，想起了舒淇，李丽珍，杨思敏，想起了刚刚离我们而去的人民艺术家饭岛爱，以及为事业鞠躬尽瘁死而后已的武藤兰同志，尽管她们分工不同，但没有高低贵贱之分，同样日日夜夜挥汗如雨地工作，在灵与肉的碰撞中，在吆喝呻吟中体验着劳动的光荣和快感。

在频频出入洗头房的人群中，我惊讶的发现了几张极为熟悉的面孔，那不是李书记，张局长，赵主任一行嘛，跟在他们身后的是刚刚提拔的刘干事，白天任劳任怨，以干事为己任，夜晚仍不忘发挥余热，深入洗头房继续干事。这些可亲可敬的领导干部们舍小家，为大家，含泪抛下独守空房的妻子，两眼张望的老人，三过家门而不入，淡泊名利，避开群众们关切火辣的眼光，不辞辛劳，穿街走巷，从群众中来，到群众中去，以*员模范带头作用感染着社会底层，和洗头房的小姐通宵奋战，彻夜长谈，从金瓶梅到春梅腊梅，从票子到马子奶子，检验着社会主义精神文明建设的成果。看在眼里，我热泪盈眶，谁说官民势如水火，我说官民情同鱼水，难舍难分！

夜色渐沉，洗头房的灯逐渐暗了下去，我知道领导和小姐之间的探讨切磋会正在召开。有这样的领导，国之大幸，民之大幸，何愁不能国泰民安，构建和谐社会也自是指日可成。想到这里，我陡增生活的信心和勇气，也默默祝福他们保重身体，但在转身离去的刹那，眼睛就湿润了。

-----
关于城管

"在我们眼里,英美特种兵如果是尘埃的话,我们就是沙尘暴"–摘自《城管的优秀历史》前言

"逃跑?我们会让你生活在无限的恐惧之中"–战斗中的一城管言论

"我们在飞机坠毁前,一直以为是遭到了地空导弹的攻击,没想到是城管用竹竿…"–摘自前美苏SU30 F22 F117A等战机飞行员

"当漫天飞舞的板砖和无数看不清来路的拳脚把清点的士兵堵在了阵地上,我真是不敢想象这仅仅是一支受城管训练过的伊军小队"–摘自美军101空降师502团E连米勒上尉

"当我军的一个M1A2坦克分队在一个早晨被全歼时,现场没有爆炸的横迹,只有无数的拳头.那拳头深深的打破了装甲.里面的成员被打成了肉渣"–摘自美军陆战师汤米康林下士

"对不起,我只能回答你我不知道,因为这已经牵涉到国家最高机密"–城管队长回答记者关于城管训练问题

"在我军一次战役中,有一个阵地在郊外我军后方.我军已经突破了外围防线时,那个阵地已经被我们包围了.我们攻克了阵地.我们丢下了500具德意志勇士的尸体,以及3架F22和30台虎式坦克,但抵挡我们3天3夜的居然是5名城管.–摘自德军党卫军78师12团B连曼施坦因中尉

"我们的意志瞬间崩溃,只因为我们知道了对方军中有城管"–美国海军陆战队某指挥员

"配合粪青动员兵效果更好,那是条不可攻破的防线.那是条城管和粪青动员兵组成的钢铁长城.我在此警告各位议院,永远不要跟中国开战,因为中国有城管和粪青"–摘自美国总统奥八牛在珍珠港被3城管和粪青动员兵捣毁后的国会演讲

"当他们出现在战场中时,我知道,我们的末日来了"–前俄罗斯国防部长

"看到他们,我想不到其他的,脑子里只冒出两个字:超人"–前津巴布韦总理

"你一定没见过城管,如果见过,你不会这么完整的站在这里"——一名伤残美兵

"你肯定无法想象,我们一个陆战狙击手一不小心打了一个城管的手,那个城管居然一路杀过来干掉了他.但是…他来的时候已经打死200陆战队,掀翻了3个坦克外加5架武装直升机"–美国三角洲部队的教官

"城管?是撒旦征服世界军队吗?"–原美国炮兵团第二营幸存者

"我一直以为是铁血战士,直到有人告诉我那是城管,我见了城管执法,是的…我见过城管执法…"–美国扭腰精神创伤康复中心患者史密斯.W.布什

"我们的航母还在太平洋集结时,城管已经游过了太平洋占领了我们的首都"–一名美国海军的回忆

"如今能和我对抗的,只有城管.不过幸好,我们是同一阵线的"–摘自春哥自转<我是纯爷们>

"我一生中最大的悲哀就是从最后一场战争中幸存下来,在那次战争中战死沙场一直是我计划中的事,我真是应该在快结束的时候死掉,做为一个士兵能死在城管的手中,是最光荣的牺牲.如果让我选择,我一定会放弃现在的身份,选择做一名城管"–美国总统奥特曼

"我是城管"–人民的好英雄墓碑词.

"当年日本向我们申请核保护的时候,中国就开始组建城管了.可见我们现在的选择没有错,如果一但因为日本而对中国使用了核威胁,那我们将面临更大的灾难"—美国外交部发言人

"我们是人,是的,我们是人"–城管大队答记者问

"我想,他们能徒手搏杀掉上帝"–原美军陆战队73师师长耐肯

"和这样的军队作战是天大的错误"–拿破仑

"呕~他们打上来我们该怎么办?"-—上帝

"我们在一个错误的时间在一个错误的地点和一个错误的人打了一场错误的战争,因为我们没想到对方竟是中国城管"–美军司令兵败棒子国后如是说

"中国城管与核武器轰炸,我选择后者"–日本广岛原子弹轰炸幸存者

"天啊!饶了我吧!我不想面对他们,他们是来自地狱的恶魔.不!和他们相比我情愿面对恶魔!要知道他们可是城管!–美黑人逃兵威尔.修斯

"宇宙已经没有可以打败他们的人了"–M78星云总指挥官烧饼凹凸曼

"他们已经超越了人类想象的极限"–中情局局长罗布斯

"为什么现在美国人都不知道中国城管是什么东西,因为当你门知道它是什么东西的时候,你就会象我一样永远看不到明天的太阳!!"–一群在韩战里的被包围的独立师的最后消息

"鉴于中国城管具有超过核武器的威力,我们决定签订<城管不扩散条约>,并且保证当别人不使用核武器的时候我们不会优先派出城管"–人代表大会一致通过

"由于中国城管的存在我们放弃了进攻地球"–火星国防部长

"如果给我三个城管,我将平息非洲战乱,可惜我只有半个城管…"–联合国秘书长


-----
今天，我查分了，451分

昨天当我颤抖的双手拨通了北京市高考分数查询系统的时候，我听到了一个女人的声音：451分，当时我委屈的双眼充满了泪水，电话脱手了，狠狠的砸到了我的弟弟，我都没有感觉。

想想，我平时除了上网玩游戏，看点成人片，之外也不谈恋爱，偶尔出去玩，怎么考得这样差呢，平时摸底都是500多分啊，尽管考试纪律不严，但是也充分体现了我的水平啊… …

下午，家人问我考试查分数了吗？我手握着鼠标，头都没回的说道：还没下来呢！

晚上，我隔壁的那个2蛋–平时大家这样叫他的，他爹到我家来玩麻将，说他孩子下午查了分数竟然考了480分，我爸爸捏着二万说道：这不可能吧，这孩子平时摸底不是考的很差吗？听我孩子说也就是4百7左右的样子，冒泡了啊！这分数能上北大了吧！"可不是吗，我老家山东有个亲戚家孩子，考了700分，说只能上二等本科，说要复习去呢，咱北京就是强啊，这就是素质教育！"二蛋他爹弹了弹烟灰满脸自得的说。

哪壶不开提哪壶，2蛋他爹忽然问道：你家孩子考多少分啊？

我赶紧关闭游戏程序，在房间里拨通查询系统，按步骤输入着，然后装作从房间里面出来，说了声：爸，别玩了，我考试成绩出来了。大家都把专注的眼睛投向了我。

451分！我如实地说！没发挥好！

孩子你再查一遍，我爸说道。

我说：不用查了，我都查了N遍了，那个女的还是那样说~~~~~

二蛋他爹安慰我爸说：没事，这可以上清华了，不上北大没关系的~~~~

全家人都笑了。

晚上他们喝酒喝得很晚。

-----
大学的时候，刚进学校。学校让我们填一份自我简介，里面包括体育强项。同桌告诉我不要写那种运动会用的到的项目，不然以后运动会会强迫你参加。于是我们写的是高尔夫、网球、滑雪之类的，本想转过身去提醒后面玩的好的男生，结果一看他写的体育强项是双脚踩灯泡、胸口碎大石。

-----
刚才有人给我说：如果给我配一个技术大牛，+ 产品经理，+ 营销总监，+ 运营总监 我就可以创业了。我问，配了这些人以后，还要你干嘛？

-----
买了瓶饮料打不开盖子，想随便找个路人开开，但是不好意思，于是冲向了警察叔叔，叔叔一脸惊喜地刚说：谢……我说能不能帮我拧开瓶盖！事成之后我谢谢走了，好像听到心碎的声音 ~

-----
祝贺张学友郭富城获得奥运会羽毛球男双金牌(蔡赟/傅海峰)

file:images/badminton-olympic-champion.jpg

-----
有人喜欢牌子，所以选择了苹果，有人喜欢外观，所以选择了索爱，有人喜欢比硬件，所以选择了三星，有人喜欢性价比，所以选择了小米，有人喜欢从众，所以选择了htc，但有些人还是执迷不悟，所以选择了诺基亚。有人喜欢最炫民族风，所以选择了山寨机。。。

-----
乘务员："先生，飞机马上起飞了，请把手机关掉，好吗？" 乘客："我开的飞行模式" 乘务员："对不起先生，现在山寨手机也很多，我们很难保证每个手机都是符合标准的！" F舱乘客大怒，"你说啥？你说俺手机山寨的？老子是苹果的！三卡三待呢！不识货别跟老子吵！"

-----
突然听到解说员说"这是一名92年出生的老将。"顿时感觉这个世界太特么凶残了。

-----
思想就像内裤，要有，但不能逢人就证明你有。2我可以选择放弃，但绝不放弃选择。3君子报仇，十年不晚。小人报仇，从早到晚。4我们需要马桶精神，按一下，什么都干净了。5人家有背景，而我只有背影。6眉毛上的汗水，眉毛下的泪水，你总得选一样。7财富改变不了个性，却能让人露出本性。

-----
王海滨：到北大读书后，雷声整个人的精神气质有了提升，这对于一个剑客非常重要。雷声：其实北大真正的作用是帮我突破了一个技术瓶颈。记者：噢？雷声：以前我一直解决不了出剑时手腕抖动的技术问题，甚至想到了退役，直到有一天我观察到了北大学一食堂打菜师傅是怎么用勺子的....

-----
各个公司组织架构

file:images/company-architecture.jpg

-----
和妹子相处，要义就是： 若她涉世未深，就带她看尽人间繁华； 若她心已沧桑，就带她坐旋转木马。和阿哥相处，要义是：若他情窦初开，你就宽衣解带；如他阅人无数，你就灶边炉台。

-----
培训的时候听上级领导说，全国党员有8000多万，而全世界超过8000万人口的国家不过14个。俺就在想，要是让全体党员随便割据个地方，从中国独立出去，组建一个国家，8000万最先进的人都保持同一信仰信念，没有不明真相的群众干扰建设，没有杂音和不良思潮，世界上第一个共产主义国家不就诞生了么

-----
什么是球星效应？ ——齐达内退休了，法国低迷了6年，这就是球星效应 ——普斯卡什退休了，匈牙利低迷了60年，这就是球星效应 ——高俅退休了，中国低迷了1000年，这就是球星效应

-----
自从我国引入劫持人质现场谈判专家制度，劫匪被击毙的几率反而提高。专家们把现场谈判的录音拿来研究，发现总是到这一句时谈判宣告破裂："你一定要相信党和政府。"

-----
中午吃饭，旁边一桌的大姐结完帐说：＂开张发票，中国人民银行。＂服务员说：＂您写一下。＂大姐答：＂照钱上面写。＂

-----
【一个男人的称号】"伟大领袖"、"天赐大将军"、"世界著名的文学家"、"我们星球的卫士"、"所有杰出将军中最杰出的将军"、"众神之神"、"21世纪的北极星"、"一位拥有百科全书一样丰富知识"的"哲学巨人"、"人类最伟大的音乐天才"、"人类智慧的化身"。

file:images/great-general.jpg

-----
如果你在澳大利亚电子产品Kogan的网站上进行网购的话,使用IE7的用户们可能会惊喜地发现他们需要你多付6.8%钱.收钱理由:我们费了这么大工夫让网站在IE7下看起来和其它浏览器的效果一样,你们理应付给我们辛苦费.PS:建议IE6收更多费用,解放前端码农,不用在去做无用的大量的Css Hack工作.

-----
别把自己想象成为一个丑人

file:images/dont-think-yourself-as-an-ugly-person.jpg

-----
"麻麻为什么金牌和铜牌待遇差这么多？""孩子，你知道世界第一高峰么？""恩，珠穆朗玛峰嘛。""那世界第三高峰呢？""干城章嘉峰啊，麻麻我们不要讨论这个问题了，继续讨论金牌和铜牌的事情啊。""。。。我没什么可说的，让你整天看那些没用的地理书。。"

-----
一人到精神病院送东西，刚到医院，车胎爆了。下车修理一不留神，车胎上的四个螺丝滚到下水道里，他在那儿干着急。一个精神病路过看了看：你把剩下3个轮胎，各拔1个螺丝下来，装到备胎上，然后把车慢慢开到市区，找家修车的不就行了。车主问他，你不是精神病么？精神病说——我是有精神病，但不是傻子。

-----
绝妙的真的假新闻：勃列尼涅夫走路快，每每和来访的外国领导人比赛。一次和尼克松举行竞走比赛，结果，勃输了。但《真理报》（这名字！）的报道却是：在昨日美苏举行的一场竞走比赛中，我国领导人勃烈日涅夫同志获得了第二名的好成绩，而美国领导人尼克松获得了倒数第二名。这就是某些国家的文风啊。

-----
中国人就是牛，拿下"首金""首铜"，让别人"首银"去吧。。。。

-----
我这人脾气好，每次和讨厌的人说话，总是面带笑容，默默的用中指的推推眼镜

file:images/smile-and-middle-finger.jpg

-----
一个设计师独白：甲方虐我千百遍，我待甲方如初恋。有朝一日做甲方，虐遍天下设计院。。。

-----
在开幕式演唱红歌 hey 朱德 引发极大反响之后，博伊尔已经决定闭幕式压轴曲目由大卫鲍伊演唱 shopping for girls （小平为女孩），旨在向另一伟大的中国领袖致敬，感谢他带领中国结束革命年代转型世俗社会、并为世界最具潜力经济体融入全球市场打下基础。

-----
伦敦奥运开幕式选用红歌《hey，朱德》作为压轴歌曲，引发热议。据导演介绍，这一选择有深意，该歌曲是由同情革命的披头士乐队于1968年所作，其中有"hey，朱德，don't make it bad"的歌词。当时，中国文革刚刚开始，词作者向中国隐晦喊话，寄望地位较高的元帅朱德勇于担当，出面阻止乱象。

-----
同时也有历史学家提出不同意见，认为这首歌实际反映了初上井冈山时的真实革命状况：革命队伍草创薄弱，反动派步步紧逼，袁文才等匪气未脱，部分指战员包括朱德同志在内，对革命前景一时有所悲观，此时毛委员展现了一位革命家的高瞻远瞩和大无畏精神，他表示：hey，朱德，don't make it bad

-----
寝室有一同学去厕所，玩手机不小心把手机掉下去了，然后，就回去拿了双筷子准备夹出来，正当他要下筷子捞时，一哥们进了厕所看到此景，那人关心地问道："哥们，还没吃啊"

-----
程序猿问科比："科比，你为何如此成功？"科比反问："你知道洛杉矶每天凌晨4点的样子吗？"程序猿："知道，那个时候我一般还没下班。你问这个干嘛？"科比："不干嘛，草！"谈话结束了！

-----
因为有前科，都可以预计接下来会发生什么：1、煽情，着力宣传暴雨中的感人事迹，顺杆上升为北京精神2、各路马后炮砖家，大谈城市规划3、官员强调并非ZF不作为或乱作为，实乃天意，61年罕见才会至此4、表决心，谈整改，新闻稿最后一句肯定是"让我们拭目以待"，再一次出现类似情况，前面四点依次循环

-----
某种程度上来说，运动员比小姐都可怜，同样是生计所迫，年纪轻轻开始透支身体，小姐起码是卖，一次一结账，旱涝保收，而运动员则是去赌， 拿到冠军你就牛逼了，拿不到冠军你就歇逼了。更倒霉的是小姐收了钱不用被央视记者问脑残问题，也不用跟谁感恩戴德，运动员就不行，谢错顺序还他妈挨骂。

-----
一女吊丝签名：多年之后，你若娶了，我若没嫁。叫你儿子放学路上小心点。。。

-----
现在小学三年级的暑假作业真难啊，昨天看到侄子的暑假作业有一题什么逻辑规律题，哥想了半天都想不出来，求各位大神解答：986F、875E、764D、653C、--、431A，请问--处应该填什么呢？真心求解答

-----
去停车场取车，发现车头灯被人撞坏了！而且还有不少划伤！附近没见肇事车辆！但是还好，雨刷下压着一张纸条，是肇事着留下的。我拿起来，见上面写着："抱歉，倒车时不小心撞了你的车灯，现场目睹的人看到我留这张字条时都对我点头面露微笑，他们以为我在写姓名和电话号码给你，可是我没有。

-----
在办公室接待应聘者，拿着那登记表，瞅了好久，弱弱地问：木棍？你叫木棍？那求职者脸都绿了，恶狠狠地回：我叫林昆！然后整个办公室3秒内一片静寂......接着狂笑不止.....

-----
他出身大户门第，身价数十亿，本应是娶女星玩模特的年纪，但是为了自己的信仰，他把数十亿换成了AK47和RPG，钻进了山洞对抗美帝主义，十年来让FBI和CIA颜面扫地，现在评说他是好坏已经没有意义，不过，他的一生注定是个 legend——传奇!—TO: Osama Bin Laden 本·拉登！

-----
国庆装逼指南：
1. 坚持用手机客户端更新微博，并发微博抱怨：墨尔本机场WIFI信号真差！
2. 将QQ签名改为：妈的，纽约的油条真难吃。
3. 拒接朋友来电，用短信回：有事回国再说吧，西班牙漫游太贵。
4. 每天坚持在凌晨四点回复短信，以表明有时差。
5. 在微博感慨一次：我靠！又在经济舱看见骆家辉啦！
