#+title: 极客时间|技术与商业案例解读 文章目录
#+options: num:nil


** [[https://time.geekbang.org/column/article/49][开篇词 | 突破技术思维，站在商业的角度看问题]]

从今天开始，我要和你聊聊过去30年那些有意思的互联网公司，它们起落沉浮，或风头正劲，但都有一个共通点，就是...


** [[https://time.geekbang.org/column/article/34][001 | 西雅图IT公司之RealNetworks：一个帝国的兴衰（上）]]

今天的主角，是一个曾经兴起，最终又倒下的帝国。在西雅图派克市场周围一个不起眼的楼宇里面，有一家叫作RealNe...


** [[https://time.geekbang.org/column/article/39][002 | 西雅图IT公司之RealNetworks：一个帝国的兴衰（下）]]

上回讲到微软进军RealNetworks的市场，RealNetworks面对这场战争，又是如何应对的呢？


** [[https://time.geekbang.org/column/article/314][003 | 以RealNetworks为例，谈谈初创公司如何应对巨头碾压]]

微软利用一贯的“免费加捆绑”策略杀入媒体领域，苹果也带着QuickTime进入竞争行列，RealNetworks公司又将...


** [[https://time.geekbang.org/column/article/321][004 | 文档数据库的缔造者MongoDB（上）]]

MongoDB的诞生像一场意外。这个文档型数据库以易用性知名并不断发展，今天就来揭秘其团队的开发重心、商业运作...


** [[https://time.geekbang.org/column/article/326][005 | 文档数据库的缔造者MongoDB（下）]]

MongoDB重视用户体验超过核心功能的传统，让其陷入巨大的安全危机，而从具有CIA背景的风投公司拿钱，又让人多...


** [[https://time.geekbang.org/column/article/333][006 | 以MongoDB为例，看基础架构类产品创业]]

作为一款基础架构产品，MongoDB以易用性著称，但不够注重系统的可靠性，致使用户频频转向其他产品。那么，基...


** [[https://time.geekbang.org/column/article/401][007 | 直面MongoDB，谈微软的NoSQL战略]]

2013年，MongoDB占据美好而巨大的数据库市场，成为很多初创企业的首选。微软究竟做了哪些举措，让Cosmos DB成...


** [[https://time.geekbang.org/column/article/412][008 | 免费还是收费？WinRAR的生意经]]

压缩软件WinRAR的普遍使用与广泛传播，可谓代表了一个时代，并一度成为压缩软件里事实上的标配。其发行公司在...


** [[https://time.geekbang.org/column/article/415][009 | 可视化分析鼻祖Tableau]]

Tableau作为可视化分析软件领域的奠基人，算是学术界人士创业成功的典范，今天就来看一看其成长的历程。


** [[https://time.geekbang.org/column/article/473][010 | 从Tableau上市，看学术界和工业界人士创业]]

Tableau和RealNetworks的创业和发展史，恰好可以代表现实中的两类创业者。今天，我就来分析下学术界和工业界人...


** [[https://time.geekbang.org/column/article/475][011 | 周鸿祎和BAT的沉浮录（上）]]

周鸿祎，作为中国互联网发展史上非常重要又很有特色的人，曾在不同时期与BAT进行了战斗，却依旧风生水起。他出...


** [[https://time.geekbang.org/column/article/544][012 | 周鸿祎和BAT的沉浮录（中）]]

与百度的战斗告一段落，3721迎来了雅虎的收购。而阿里巴巴随后入局雅虎，让另一场战斗悄然而至。今天，我就带你...


** [[https://time.geekbang.org/column/article/546][013 | 周鸿祎和BAT的沉浮录（下）]]

和阿里的战斗告一段落，奇虎360又和腾讯共视战场，这就是中国互联网发展史上里程碑式的“3Q大战”。此事对中国...


** [[https://time.geekbang.org/column/article/556][014 | 周鸿祎和BAT的沉浮录（后记）]]

中国互联网的发展史上，周鸿祎不可不提，他有着非常鲜明的个人特点，又有着非同寻常的经历。他与百度、阿里、腾...


** [[https://time.geekbang.org/column/article/557][015 | 在线旅游帝国Expedia崛起的背后]]

Expedia原是巴顿自微软内部发起的项目，拆分上市后被IAC买下。而作为绝对的企业经营和资本运作高手，IAC董事长...


** [[https://time.geekbang.org/column/article/619][016 | 亚马逊领导力准则之要有硬骨头]]

但凡能看到的企业，从IBM到微软到谷歌，其实都无法避免官僚化，亚马逊则在最高领导层上通过贯彻领导力准则，很...


** [[https://time.geekbang.org/column/article/620][017 | Hadoop三国之魏国Cloudera]]

Hadoop领域曾经有三家发行商互相角逐，这其中不乏各种战术与谋略，商业的演进和帝国的历史总是惊人得相似。今天...


** [[https://time.geekbang.org/column/article/622][018 | Hadoop三国之吴国MapR]]

Hadoop领域曾经有三家发行商互相角逐，这其中不乏各种战术与谋略，商业的演进和帝国的历史总是惊人得相似。MapR...


** [[https://time.geekbang.org/column/article/623][019 | Hadoop三国之蜀国Hortonworks]]

Hadoop领域曾经有三家发行商互相角逐，这其中不乏各种战术与谋略，商业的演进和帝国的历史总是惊人得相似。今天...


** [[https://time.geekbang.org/column/article/624][020 | Hadoop及其发行商的未来]]

Hadoop诞生十多年间，其生态圈逐渐兴盛又衰落，围绕其生态圈又诞生了诸多企业，而亚马逊却最终成为最大的受益者...


** [[https://time.geekbang.org/column/article/901][021 | 彼得 · 蒂尔的投资人生]]

他是“PayPal黑帮”里的重要人物、Facebook的首位投资人、“创业圣经”《从0到1》的作者，他被誉为“硅谷创投...


** [[https://time.geekbang.org/column/article/903][022 | 商业之外的彼得 · 蒂尔]]

商业之外的彼得 · 蒂尔有着鲜明的个人理想和信念，并擅于付诸于实际行动。这是否也是其能够成功的重要因素呢...


** [[https://time.geekbang.org/column/article/917][023 | 创业的智慧：从彼得·蒂尔的创投哲学说起]]

彼得·蒂尔的创业和投资哲学言简意赅，似乎通俗易懂、老少皆宜，直指真理的本质，背后却有着一些值得我们去挖掘...


** [[https://time.geekbang.org/column/article/1047][024 | 房产经纪的颠覆者Redfin：在“传统”与“现代”间徘徊]]

Redfin是房产经纪的颠覆者、“二手房电商”之父，之后包括链家等很多公司都复制和延伸了它的商业模式。作为如今...


** [[https://time.geekbang.org/column/article/1048][025 | 房产经纪的“协作者”Zillow：一个地产数据平台]]

相比房产经纪的“颠覆者”Redfin，Zillow通过建立数据平台，找到了与各大房产经纪公司的共生之道，甚至从Redfin...


** [[https://time.geekbang.org/column/article/1049][026 | 颠覆还是协作，房地产市场上Redfin和Zillow的抉择]]

技术改变世界的时代，Redfin用技术武装成新型房地产经纪公司，Zillow则构建数据平台，给传统房地产经纪公司提供...


** [[https://time.geekbang.org/column/article/1282][027 | 应用交付网络大厂F5：“一招鲜”之殇]]

F5是ADN领域的先驱，十余通过为其他互联网厂商提供设备支持来赢利。但是SDN的概念出来，微软等各大厂商开始自...


** [[https://time.geekbang.org/column/article/1288][028 | 在线差旅报销鼻祖Concur：在转型中获得发展]]

作为在线差旅报销市场的领导者，Concur一路从卖软件到销售许可证，到最终成为成功的SaaS公司，不断转型并发展...


** [[https://time.geekbang.org/column/article/1289][029 | 漫谈企业转型：在市场变迁中寻找生机]]

企业转型是每家企业在不同时期都需要面对的选择。企业转型艰难，困难在哪里？从Concur和F5的发展经历里面，我们...


** [[https://time.geekbang.org/column/article/1395][030 | 克雷公司沉浮录：行走在超级计算机市场]]

克雷公司最初由“超级计算机之父”西摩 · 克雷创建，主要研发销售超级计算机，是市场上绝对的领导者，却先后...


** [[https://time.geekbang.org/column/article/1532][031 | “单一化”的隐忧：从克雷公司看“一条腿走路”]]

克雷公司商业模式单一，因此“一条腿”出问题就会导致整个公司层面出问题。那么，如何成功寻找到“第二条腿”，...


** [[https://time.geekbang.org/column/article/1571][032 | 亚马逊领导力准则之决策正确]]

决策正确是亚马逊领导力准则之一，它强调领导者需要具备正确的决策能力。而如何才可以具备正确的决策能力，是这...


** [[https://time.geekbang.org/column/article/1574][033 | Halo的开发者Bungie：与微软的聚散]]

Bungie是全球最大的游戏工作室之一，曾经开发出一系列备受赞誉的游戏，并被微软收购专门开发Halo系列，让Xbox走...


** [[https://time.geekbang.org/column/article/1575][034 | “卖身”须谨慎：创业公司面临的抉择]]

创业公司发展到一定阶段，经常面临被收购还是独立发展并上市的选择。但是究竟孰优孰劣，这就要看具体的收购方式...


** [[https://time.geekbang.org/column/article/1803][035 | 亚马逊领导力准则之客户至尚]]

“客户至尚”是亚马逊领导力准则里面非常重要的一条，并被贝佐斯视为第一准则贯彻和落实，哪怕牺牲一部分企业利...


** [[https://time.geekbang.org/column/article/1875][036 | 智能音箱的战斗：亚马逊的硬件路]]

亚马逊推出的智能音箱Echo引起了广泛关注，我将通过智能音箱系列回顾这个新生事物的发展历程。让我们先来了解亚...


** [[https://time.geekbang.org/column/article/1876][037 | 智能音箱的战斗：Echo攻城略地]]

Echo曾是亚马逊硬件研发部门Lab126优先级最低的研发项目，却因Fire Phone大败而获得发展契机，并在相对保守的...


** [[https://time.geekbang.org/column/article/1877][038 | 智能音箱的战斗：语音助手Alexa]]

Alexa原本是亚马逊Echo音箱的语音助手，在后续发展中独立出来成为了一个软件语音平台，亚马逊又围绕Alexa平台构...


** [[https://time.geekbang.org/column/article/1878][039 | 智能音箱的战斗：谷歌的杀入]]

谷歌对于智能家居市场的觊觎由来已久，在亚马逊占据两年先发优势之后，它终于杀入智能音箱市场，一次“势均力敌...


** [[https://time.geekbang.org/column/article/1879][040 | 智能音箱的战斗：亚马逊的战略布局]]

亚马逊对智能音箱和相关硬件的布局有自己的打算，但在谷歌入场之前以广撒网为主。但谷歌来势汹汹，亚马逊又将如...


** [[https://time.geekbang.org/column/article/1880][041 | 智能音箱的战斗：巨头纷纷入场]]

在谷歌入场一年后，苹果和微软也加入了智能音箱市场，国内也有诸多大厂杀入，它们将如何谋求发展和布局？


** [[https://time.geekbang.org/column/article/1881][042 | 智能音箱的战斗：白马非马]]

凭借语音这一天然的交互媒介火起来的智能音箱，“音箱”只是其基本属性。亚马逊、谷歌、苹果、微软，以及众多国...


** [[https://time.geekbang.org/column/article/2328][043 | 如何透过一个领域去联合分析多家企业？]]

前面讲解了在智能音箱领域，亚马逊、谷歌、苹果、微软分别采取的入场方式和举措，并分析了其成败。那么，你是否...


** [[https://time.geekbang.org/column/article/2329][044 | 谷歌的创新精神：好的、坏的和丑陋的（上）]]

谷歌可说是最具创新精神的互联网公司，创新不仅为它赢得声誉和品牌，同样给它带来实际利益。那么，谷歌是如何践...


** [[https://time.geekbang.org/column/article/2449][045 | 谷歌的创新精神：好的、坏的和丑陋的（下）]]

谷歌可说是最具创新精神的互联网公司，创新不仅为它赢得声誉和品牌，同样给它带来实际利益。但是事情总有两面性...


** [[https://time.geekbang.org/column/article/2515][046 | 仁科：被迫再创业的David Duffield]]

David Duffield曾经创办多家公司，三次带领公司完成上市，并在这一过程中展现了非常优秀的技术洞察力。其中，...


** [[https://time.geekbang.org/column/article/2604][047 | 仁科：飞跃发展的企业级软件帝国]]

在大卫 · 杜菲尔德的领导下，仁科开始了飞速发展。这次高速发展以仁科软件的多元化为契机，自1992年开始一直...


** [[https://time.geekbang.org/column/article/2606][048 | 仁科：收购和被收购]]

进入新世纪，当时企业级软件市场排名第三的仁科打算和排名第四的JD Edwards合并，强强联合以便对抗前两名的SAP...


** [[https://time.geekbang.org/column/article/2608][049 | 仁科的成与败]]

仁科的故事讲完了，我们来看看仁科发展过程中成功和失败的地方。“往者不可谏，来者犹可追”，历史上发生的事情...


** [[https://time.geekbang.org/column/article/2693][050 | 亚马逊领导力准则之勤俭节约]]

亚马逊是一家把节俭写入领导力准则的公司，它把自身成功的很大一部分原因归结于处处贯彻这一准则，但勤俭节约也...


** [[https://time.geekbang.org/column/article/2840][051 | WorkDay：杜菲尔德复仇记]]

Oracle恶意收购仁科后立刻大裁员，仁科创始人杜菲尔德也被迫离开。为了被裁的仁科员工，也为了向Oracle复仇，...


** [[https://time.geekbang.org/column/article/2900][052 | David Duffield的眼界和成败]]

David Duffield是一位极具传奇色彩的创业人，先后四次创业，三次是以人力资源软件起家，而且全部成功IPO。但是...


** [[https://time.geekbang.org/column/article/3206][053 | 分析企业的两要素：远见和执行力]]

本文介绍飞总分析企业时的一种方法：通过看企业的远见和执行力对企业进行分析。这种方法源于Gartner魔力象限图...


** [[https://time.geekbang.org/column/article/3208][054 | 互联网第一股雅虎的兴衰：霸主的诞生]]

雅虎诞生于1994年，最初以人工整理互联网信息的分类目录而知名，后给各大企业做显示广告，成立2年便成功上市。...


** [[https://time.geekbang.org/column/article/3421][055 | 互联网第一股雅虎的兴衰：运气不敌技术]]

雅虎在互联网泡沫破灭时遭受重创，同时迎来新CEO塞梅尔，此后在商业上采取了一系列措施，包括分别购买搜索引擎...


** [[https://time.geekbang.org/column/article/3618][056 | 互联网第一股雅虎的兴衰：没有救世主]]

杨致远曾在全球复制雅虎的成功，而雅虎美国却在塞梅尔的带领下连连失利，杨致远回归做CEO却也英雄败北，此后便...


** [[https://time.geekbang.org/column/article/3640][057 | 成也杨致远，败也杨致远]]

雅虎曾经是互联网上访问量最大的网站，是曾经的“互联网第一股”，但是其后来的发展却每况愈下。无论前期的成功...


** [[https://time.geekbang.org/column/article/3642][058 | 企业因人成事，领导人很重要]]

“兵熊熊一个，将熊熊一窝。”一个企业最后所能达成的成就，往往和企业的领导人有莫大的关系。因此，通过分析企...


** [[https://time.geekbang.org/column/article/3674][059 | 亚马逊领导力准则之主人翁精神]]

主人翁精神似乎老生常谈，但在亚马逊领导力准则里却有很重要的地位和比较明确的定义，主要体现在两个方面：一是...


** [[https://time.geekbang.org/column/article/3675][060 | 半条命的Dota帝国Valve：半条命]]

知名游戏公司Valve，创始人均出身微软，是Windows操作系统的早期开发者，衣食无忧选择创业。它在创立早期就成功...


** [[https://time.geekbang.org/column/article/3676][061 | 半条命的Dota帝国Valve：Steam平台]]

《半条命3》始终没有出现，Valve在专心打造“游戏界的iTunes”，即自己的游戏平台Steam，并不惜借助自己的多款...


** [[https://time.geekbang.org/column/article/3677][062 | 半条命的Dota帝国Valve：Dota 2]]

Dota 2的加入，让Steam平台得以将更多游戏展现给更多玩家。这种相辅相成的发展模式，让Valve公司的未来呈现...


** [[https://time.geekbang.org/column/article/3678][063 | 半条命的Dota帝国Valve：无领导管理]]

Valve公司奉行一种无领导管理的理念，公司所有人都是平级的。一家公司没有老板，干活凭兴趣，招人看缘分，这可...


** [[https://time.geekbang.org/column/article/3679][064 | 半条命的Dota帝国Valve：虚拟现实]]

Valve以创新著称，《半条命》最早引入游戏情节，游戏分发平台Steam更是早于iTunes，如今更与HTC合作Vive，为游...


** [[https://time.geekbang.org/column/article/4209][065 | Gabe Newell：Valve帝国制度的利弊]]

Valve是一家非常成功的游戏公司，其制度、运作方式极具特色。然而，Valve的优点和缺点都极为鲜明，却不可复制。


** [[https://time.geekbang.org/column/article/4321][066 | 管中窥豹之从面试看企业文化：微软]]

微软的招聘过程自成体系很有特色，具有AA资格的人拥有最终决定权。这背后，则是一套自上而下的管理模式和领导者...


** [[https://time.geekbang.org/column/article/4339][067 | 管中窥豹之从面试看企业文化：亚马逊]]

亚马逊的领导力准则就像企业文化的DNA，并且极为知名。在招聘这件事情上，亚马逊也是处处体现它的领导力准则。...


** [[https://time.geekbang.org/column/article/4344][068 | 管中窥豹之从面试看企业文化：谷歌]]

作为硅谷新兴互联网企业代表的谷歌，面试遵循了一套完全不同的模式。这种模式被硅谷的其他互联网上市公司和尚未...


** [[https://time.geekbang.org/column/article/4346][069 | 管中窥豹之从面试看企业文化：甲骨文]]

甲骨文是硅谷老牌公司的代表，面试规则充分体现出了其作为老牌硅谷公司“唯出身论”的特质。


** [[https://time.geekbang.org/column/article/4351][070 | 管中窥豹之从面试看企业文化：Facebook]]

Facebook的面试有很多模仿谷歌的痕迹，却也独具特色。“勤奋”是它非常重要的企业文化，并在面试中得到了体现。


** [[https://time.geekbang.org/column/article/4477][071 | 透过企业用人之道看企业发展]]

企业用人之道能够反映出企业特质，也决定着企业的发展。而和员工息息相关的招聘、升迁，正是我们管中窥豹分析企...


** [[https://time.geekbang.org/column/article/4772][072 | Zenefits：一个卖保险的创业公司]]

Zenefits是创业圈里迅速升起的独角兽，但创始人“利令智昏”的一系列违规操作，又让其迅速倒下。企业作弊式扩张...


** [[https://time.geekbang.org/column/article/4896][073 | Glassdoor：让公司信息对个人透明]]

求职市场上，公司和求职者之间信息向来不对等。Glassdoor致力于解决这一痛点，让公司信息对个人透明，并借由发...


** [[https://time.geekbang.org/column/article/4897][074 | 从巴顿的创业史看巴顿]]

巴顿先后创立了Expedia、Zillow和Glassdoor，第三次创业时已经财富自由，所以他是真正为了做事而做事。巴顿创业...


** [[https://time.geekbang.org/column/article/4999][075 | 办公软件的战斗：开篇]]

很多企业不是死于外敌，而是自己太作；很多企业不够作，却败于没有跟上时代的变化。我们将回到20世纪80年代，观...


** [[https://time.geekbang.org/column/article/5094][076 | VisiCalc：第一个电子表格软件的诞生]]

Excel已是电子表格软件的事实标准，是人们工作中不可或缺的一部分，但电子表格并非Excel首创。


** [[https://time.geekbang.org/column/article/5196][077 | 亚马逊领导力准则之选贤育能]]

招聘到可提升公司整体水平的新员工，这条内容被写进了亚马逊的领导力准则。亚马逊还因此诞生了一个独特的角色：...


** [[https://time.geekbang.org/column/article/5349][078 | WordStar：第一个字处理软件的故事]]

WordStar作为第一个字处理软件，在办公软件历史上有着举足轻重的地位，开发商MicroPro一度借它成为全球最大的软...


** [[https://time.geekbang.org/column/article/5524][079 | 微软：办公软件战场的螳螂]]

“螳螂捕蝉，黄雀在后。”在办公软件领域，微软在电子表格和字处理软件领域都向当时的霸主发起了挑战，却一次又...


** [[https://time.geekbang.org/column/article/5572][080 | 亚马逊领导力准则之最高标准]]

“最高标准”这条亚马逊领导力准则与“选贤育能”相关联，亚马逊坚持选用最优秀的人才，来保证贯彻对于常人来说...


** [[https://time.geekbang.org/column/article/5635][081 | WordPerfect：字处理软件的新秀]]

微软正面进攻WordStar，却被不起眼的WordPerfect反超，后者更通过独特的推广和服务方式，成功坐上新一代字处理...


** [[https://time.geekbang.org/column/article/5711][082 | Lotus 1-2-3：莲花公司的电子表格帝国]]

和字处理软件市场一样，微软在电子表格市场也遭遇了劲敌：莲花公司。在软件发展史上具有里程碑意义的Lotus 1-...


** [[https://time.geekbang.org/column/article/5722][083 | 亚马逊领导力准则之创新简化]]

贝佐斯认为“创新”和“简化”密不可分，创新的过程中更要眼界开阔，并做好接受被长期误解的准备。


** [[https://time.geekbang.org/column/article/5826][084 | 红狮会战：微软的反击]]

微软屡战屡败，决定组织一次“红狮会战”再次进军电子表格市场。全新产品Excel就此诞生，微软不惜抛开自家产品...


** [[https://time.geekbang.org/column/article/6053][085 | 大杀器Lotus Notes 和被收购的莲花公司]]

微软通过“红狮会战”终于取胜电子表格战场，莲花公司决定避开正面交锋，转而推出领先时代二十年的企业协作系统...


** [[https://time.geekbang.org/column/article/6179][086 | 亚马逊领导力准则之崇尚行动]]

在亚马逊里面，一件事情如果不是很确定，亚马逊的领导力准则倾向于先采取行动，边做边看。这正是“崇尚行动”的...


** [[https://time.geekbang.org/column/article/6185][087 | 无敌寂寞的微软之为创新而创新]]

微软终于成了办公软件的霸主，此时却创新疲软，只是不断迭代软件版本，创收成了问题。此时，微软似乎为创新而创...


** [[https://time.geekbang.org/column/article/6333][088 | 办公软件的新时代：微软和谷歌的战斗]]

在微软的办公软件帝国，Google Docs带着“云服务”和“协同办公”两大利器闯入，并狠赚了一把眼球儿。但微软却...


** [[https://time.geekbang.org/column/article/6337][089 | 亚马逊领导力准则之远见卓识]]

亚马逊要求领导者要有“远见卓识”，要从多角度多维度纵深思考问题，从而产生良好的结果。


** [[https://time.geekbang.org/column/article/6534][090 | 异军突起的Slack]]

新时代有新挑战，遭遇谷歌之后，微软的霸主地位又受到了新创公司Slack，这家企业协同软件厂商的挑战。为此，微...


** [[https://time.geekbang.org/column/article/6542][091 | 办公软件战斗的启示：内忧总是强于外患]]

办公软件行业的战斗史告诉我们，“内忧”往往是终结企业命运的罪魁祸首。


** [[https://time.geekbang.org/column/article/6760][092 | 亚马逊领导力准则之好奇求知与赢得信任]]

领导者需要有“好奇求知”的精神，和“赢得信任”的能力，也就是不断探索外部世界，不断学习提高并能够付诸行动...


** [[https://time.geekbang.org/column/article/6764][093 | 办公软件战斗的启示：敌人的出现常常出其不意]]

办公软件的战斗告诉我们，敌人的出现，不一定在同一个领域，有时候一个领域、一个产品被颠覆，甚至可能是看起来...


** [[https://time.geekbang.org/column/article/6984][094 | 亚马逊领导力准则之刨根问底与达成业绩]]

“刨根问底”要求领导者深入各个环节，掌握细节，经常审核，不遗漏任何工作。但这还不够，你还必须能够“达成业...


** [[https://time.geekbang.org/column/article/7140][095 | 谷歌的大数据路：从“三驾马车”到一无所有]]

谷歌的“三架马车”开启了大数据时代，然而在这个新时代里，谷歌却既无江湖地位也没赚到钱。那么，谷歌究竟是如...


** [[https://time.geekbang.org/column/article/7291][096 | 谷歌的大数据路：一场影响深远的论战]]

在大数据发展史上，以迈克尔 · 斯通布雷克为代表的数据库元老级人物，针对MapReduce向谷歌提出了质疑。这场...


** [[https://time.geekbang.org/column/article/7487][097 | 谷歌的大数据路：谷歌的“黑科技”]]

在大数据的路上，前半场谷歌以“三驾马车”开始，但因为决策失误丧失了先发优势；而在大数据的下半场，谷歌携带...


** [[https://time.geekbang.org/column/article/7493][098 | 如何读懂类似谷歌“三驾马车”这样的技术论文？]]

读懂一篇技术论文，首先需要明白“论文是写给谁看的”和“论文是怎么写出来的”这两个基本问题，然后就可以有针...


** [[https://time.geekbang.org/column/article/7705][099 | 雅虎：大数据领域的“活雷锋”]]

雅虎，这个早已消逝在我们视线中的公司，却是大数据领域的“活雷锋”，可以说正是它成就了今天的Hadoop生态圈。


** [[https://time.geekbang.org/column/article/7964][100 | IBM的大数据路之起早贪黑赶了晚集]]

作为历史悠久的计算机公司，IBM早早进入了大数据领域，最终却一事无成，只能寄希望于比它起步还要晚的Spark。


** [[https://time.geekbang.org/column/article/7965][101 | 社交公司们的大数据贡献]]

雅虎把Hadoop开源以后，当时著名的三大社交公司Facebook、LinkedIn和Twitter都加入了这个生态圈，并做出了巨大...


** [[https://time.geekbang.org/column/article/8211][102 | 微软的大数据发展史：微软硅谷研究院]]

微软硅谷研究院曾在微软的大数据发展史上扮演了非常奇特的角色，它推出的Dryad和DryadLINQ可以说是两个另类，...


** [[https://time.geekbang.org/column/article/8212][103 | 微软的大数据发展史：必应的Cosmos]]

Cosmos是微软必应搜索引擎下开发的大数据基础架构，代表了微软在大数据方面的最高成就。


** [[https://time.geekbang.org/column/article/8468][104 | 微软的大数据发展史：Azure的大数据发展]]

微软大数据发展史上的另一个分支，是云计算平台下的大数据项目Azure。微软在这个项目上投入巨大，但最后只有Co...


** [[https://time.geekbang.org/column/article/8570][105 | 亚马逊的大数据故事：从先驱者到插管吸血开源]]

亚马逊对大数据的贡献，除了发展早期的Dynamo系统的论文外，对大数据圈的贡献基本上是负数，但却从中获得了巨...


** [[https://time.geekbang.org/column/article/8747][106 | 亚马逊的大数据故事：创新和拿来并存的云服务]]

亚马逊除了在Hadoop生态系统里蓬勃发展，还推出了自己的数据分析产品。这些产品有些是亚马逊自己研发的，有些则...


** [[https://time.geekbang.org/column/article/8770][107 | 阿里巴巴的大数据故事：数据分析平台发展史]]

国内大数据平台做得最好的公司当属阿里巴巴。今天我们介绍一下阿里巴巴数据分析平台的发展情况。


** [[https://time.geekbang.org/column/article/9015][108 | 阿里巴巴的大数据故事：流计算引擎发展史]]

流数据处理在阿里巴巴的发展过程中一直十分重要，阿里巴巴也在此基础上做出了很多有意义的项目。今天我们就来介...


** [[https://time.geekbang.org/column/article/9017][109 | 大公司的大数据战略得失：自建轮子成本高]]

在大公司里，大数据平台一般分为两类，一类是自己搭的基础架构，一类是抱团取暖用的Hadoop生态圈，这两者各有利...


** [[https://time.geekbang.org/column/article/9019][110 | 大公司的大数据战略得失：抱团取暖难敌插管吸血者]]

开源项目最讨厌的就是只进不出的参与者。一个公司如果只把开源项目拿去赚钱，却不拿自己的改动和成果反哺社区，...


** [[https://time.geekbang.org/column/article/9327][111 | Palantir：神秘的大数据独角兽]]

Palantir是一家神秘的大数据创业公司，由硅谷著名投资人彼得·蒂尔创办，其主要服务对象是美国政府部门、特情组...


** [[https://time.geekbang.org/column/article/9328][112 | Splunk：机器大数据的分析帝国]]

Splunk是大数据圈里少有的盈利并且蓬勃发展的企业。它主要服务在机器日志数据分析领域，随后又不断拓展业务，演...


** [[https://time.geekbang.org/column/article/2412][113 | Confluent：在Kafka上飞驰的数据交换者]]

今天我们要讲的大数据公司叫作Confluent，这个公司是前LinkedIn员工出来后联合创办的，而创业的基础是一款叫作A...


** [[https://time.geekbang.org/column/article/9329][114 | Powerset：HBase的老东家]]

Powerset是一家被微软收购多年的创业公司，目前在语义搜索方面创业。它为开源社区贡献了BigTable的Hadoop版实现...


** [[https://time.geekbang.org/column/article/9889][115 | Cassandra和DataStax的故事]]

Cassandra是开源社区Dynamo的仿品，最初由Facebook开发并开源，后被抛弃。而DataStax对它的支持，才有了它今天...


** [[https://time.geekbang.org/column/article/10041][116 | Databricks之Spark的数据金砖王国]]

Spark是Hadoop生态圈里大红大紫的项目，它甚至已经取代了Hadoop MapReduce的地位。Databricks是商业化这个项目...


** [[https://time.geekbang.org/column/article/10052][117 | Data Artisans：浴火重生的新一代大数据计算引擎Flink]]

Apache Flink是一个年轻的新型处理引擎，是Hadoop社区里Spark的主要竞争对手。Flink设计理念先进，但是工程实...


** [[https://time.geekbang.org/column/article/10054][118 | Dremio:在Drill和Arrow上的大数据公司]]

Dremio是另外一家大数据创业公司，创始人从MapR出来后，以开源Arrow为核心制作了Dremio项目。


** [[https://time.geekbang.org/column/article/10056][119 | Imply：基于Druid的大数据分析公司]]

开源大数据项目Druid由Metamarkets开发。开始时籍籍无名，后来被一些大公司，尤其是Airbnb使用和推广以后，受到...


** [[https://time.geekbang.org/column/article/10058][120 | Kyligence：阿帕奇麒麟背后的大数据公司]]

Apache Kylin是第一个全部由中国人主导的Hadoop生态圈的开源项目。Kyligence则是这个项目背后负责商业化的公...


** [[https://time.geekbang.org/column/article/10059][121 | Snowflake:云端的弹性数据仓库]]

Snowflake是一个构建在云端的弹性数据仓库，也是这个产品背后公司的名字。它的创始人和管理层都有强大的背景。


** [[https://time.geekbang.org/column/article/10942][122 | TiDB：一个国产新数据库的创业故事]]

TiDB是位于北京的一家创业公司PingCAP的产品，它的目标是实现一个开源的类似谷歌Spanner一样的系统，这个产品非...


** [[https://time.geekbang.org/column/article/10945][123 | 大数据创业公司的前景：红海创业多艰辛]]

创业通常有红海和蓝海的说法，蓝海容易红海艰难。对大数据创业公司来说，蓝海多半指的是做应用层面的，而红海则...


** [[https://time.geekbang.org/column/article/10946][124 | 如何通过企业技术积累去分析一家企业？]]

通过技术积累分析一家企业是一种行之有效的办法，我们需要关注三个方面：技术适用的场景是否有巨大的盈利空间，...


** [[https://time.geekbang.org/column/article/10947][125 | Facebook的黑客精神]]

“Move Fast and Break Things”是Facebook创始人马克·扎克伯格的名言。它的意思是让公司尽快开发尽快发布...


** [[https://time.geekbang.org/column/article/10953][126 | Twitter：蓝色小鸟还能飞多久（上）]]

今天我们一起看看Twitter的早期发展史，并了解一下杰克·多西这个Twitter的早期创业人员和CEO，发挥了什么作用...


** [[https://time.geekbang.org/column/article/10958][127 | Twitter：蓝色小鸟还能飞多久（下）]]

伴随着Twitter的上市，最终杰克如愿以偿再次回到Twitter做CEO，但是Twitter因为缺乏盈利能力，而导致股价一度下...


** [[https://time.geekbang.org/column/article/10959][128 | 赚钱是根本，换CEO也没救]]

对于企业来说，盈利是非常重要的。Twitter既不能做到现在盈利，也不告诉大家将来怎么盈利，只是通过不断换CEO来...


** [[https://time.geekbang.org/column/article/10960][129 | Square：手机POS机和比特币交易]]

Square是杰克 · 多西被迫离开Twitter管理层以后创立的公司，它的主要经营方式是通过为客户提供移动收款能力...


** [[https://time.geekbang.org/column/article/12344][130 | 创意很重要，但不是一切]]

创业公司中创意很重要，但是创业公司要长久发展下去，还需要创意以外的东西，要有长期一贯的执行能力和在关键时...


** [[https://time.geekbang.org/column/article/12355][131 | 杰克·多西：分身有术之兼任两家上市公司CEO]]

杰克·多西目前身兼Twitter和Square两家公司CEO，是近些年互联网行业颇具影响力的人物，很多人将他视为“活着的...


** [[https://time.geekbang.org/column/article/12356][132 | Groupon：团购鼻祖的兴衰]]

团购浪潮兴起于美国一家叫做Groupon的公司。然而，它在美国的发展却是一波三折，经历了高潮，又历经了衰落，如...


** [[https://time.geekbang.org/column/article/12357][133 | 卖掉自己是不是更好]]

创业公司发展到一定阶段有两条路：被收购和上市。到底哪条路更好，今天我就来分析一下这个复杂的问题。


** [[https://time.geekbang.org/column/article/12360][134 | 企业在线存储Box]]

Box是最早进入到在线存储行业的公司。“从无到有”的过程中，Box将业务的重点转变到企业用户上来。后又深耕垂直...


** [[https://time.geekbang.org/column/article/12368][135 | 个人在线存储 Dropbox]]

Dropbox是个人在线存储领域最大的公司，起初专注于个人在线存储服务，但是近几年也进行了一些其他商务扩展。


** [[https://time.geekbang.org/column/article/12369][136 | 做产品先做消费者市场，还是先做企业市场]]

Box和Dropbox是两家在存储领域很有名的公司。前者专注于企业市场，后者则专注于个人消费者市场，


** [[https://time.geekbang.org/column/article/12370][137 | 今天我们都来Pin图片之Pinterest的图片社交路]]

Pinterest是目前最大的图片社交网站，但至今尚未IPO。它的主要盈利模式就是通过广告。


** [[https://time.geekbang.org/column/article/12371][138 | 企业不上市为哪般]]

加入一个创业公司，尤其是独角兽公司，很多人是冲着股票上市去的。但是有些独角兽公司却选择不上市或者不急着上...


** [[https://time.geekbang.org/column/article/13802][139 | 微软的综合工程师改革]]

陆奇在就职于微软的那几年，推行了一场综合工程师改革。整个微软的研发部门所有的开发人员和测试人员合并，每个...


** [[https://time.geekbang.org/column/article/13803][140 | SaaS先驱Salesforce]]

Salseforce是云计算先驱，也是全球知名的CRM服务提供商。在20多年前就超前地提出了云计算和SaaS服务的概念，如...


** [[https://time.geekbang.org/column/article/13813][141 | 太超前好不好]]

在计算机和互联网的发展过程中，你经常可以看到某些公司的想法和理念很超前。有些超前的公司死掉了，有些超前的...


** [[https://time.geekbang.org/column/article/14346][142 | Sun：太阳的升起]]

Sun是一个在计算机发展史上有着重要历史地位的公司，2009年被Oracle收购。Sun的发展经历过升起和壮大，又经历过...


** [[https://time.geekbang.org/column/article/14347][143 | Sun：太阳的陨落]]

上回我说到Sun公司是怎么样从成立到快速发展，一步一步走向巅峰的。可惜Sun的巅峰没有维持多久，伴随.com的泡...


** [[https://time.geekbang.org/column/article/14348][144 | 看错敌人多可怕]]

Sun公司攫取小型机市场的时候，个人计算机也在攫取它的市场。可是Sun却从来没把个人计算机这个真正的敌人当回事...


** [[https://time.geekbang.org/column/article/16617][145 | SAP的HANA战略（上）]]

2009年全球知名ERP公司SAP开始了一场声势浩大的战略转型。这场以HANA这个内存数据库为核心的转型波澜壮阔，集技...


** [[https://time.geekbang.org/column/article/16625][146 | SAP的HANA战略（下）]]

今天，我们一起来看看忽悠以后SAP是怎样通过几年的时间成功实施了战略转型的。SAP的HANA转型概括起来就是四个字...


** [[https://time.geekbang.org/column/article/16640][147 | 成功的忽悠加成功的执行等于成功的产品]]

SAP HANA的战略转型可谓精彩绝伦。我们能从中学到什么呢？成功的忽悠加成功的执行等于成功的产品。两者缺一不...


** [[https://time.geekbang.org/column/article/16656][148 | SQL Server发展史]]

坊间传闻，微软从Sybase买了一份源代码，从此有了SQL Server。Sybase因此而被收购了，微软却蒸蒸日上。


** [[https://time.geekbang.org/column/article/16665][149 | 眼光决定一切]]

做产品的很多时候，眼光是很重要的。眼光决定了努力的方向。方向对了，努力才能成功；方向错了，即便再努力也白...


** [[https://time.geekbang.org/column/article/16682][150 | Ashton-Tate：桌面数据库王者的兴衰]]

dBase这款产品现在对我们来说已经很陌生了，但是它曾经是一款非常著名的桌面数据库产品。它由已经不存在的Ashto...


** [[https://time.geekbang.org/column/article/16691][151 | 无敌不可以肆意妄为]]

亚马逊领导力准则教导我们要客户至尚。但是我们经常看到有些企业做大了以后就不把客户当回事，肆意妄为了。这些...


** [[https://time.geekbang.org/column/article/16700][152 | Reddit：天涯论坛美国版]]

Reddit是美国非常著名的一个论坛，按照访问量来说，它也是美国第四大网站，全球第八大。Reddit同时是一个看起来...


** [[https://time.geekbang.org/column/article/16722][153 | Hacker News：创业社交两不误]]

Hacker News是作为Arc语言的一个样板产品出现的，但Hacker News本身却很快吸引了投资人和创业者，并逐渐成为...


** [[https://time.geekbang.org/column/article/40503][154 | Y Combinator：孵化器还是培训班？]]

Y Combinator是由Paul Graham创立的著名孵化器，成功孵化出了Dropbox、Airbnb等很多著名的独角兽。


** [[https://time.geekbang.org/column/article/40535][155 | 创业公司进孵化器真的值得吗？]]

伴随Y Combinator孵化器在全球范围内的成功，越来越多的创业公司都要面临着一个选择：到底应不应该进孵化器？


** [[https://time.geekbang.org/column/article/40536][156 | Paul Graham：硅谷创业教父]]

创业是很多人都想做的事情，但是创业也很危险。如果有一位经验丰富的人指导你，创业机会大增的话，你是不是愿意...


** [[https://time.geekbang.org/column/article/40537][157 | Zynga：发家从农场开始]]

Zynga曾是网络游戏市场上一家著名的公司。它在当年PC机社交时代占据了重要的地位，但是Zynga自从上市以后就开...


** [[https://time.geekbang.org/column/article/40538][158 | 论Zynga的倒台]]

Zynga兴起以后就开始慢慢的走向下坡路了。那么Zynga是怎么倒台的呢，我们来看看。


** [[https://time.geekbang.org/column/article/40539][159 | 企业分析要求综合素质]]

本文作为专栏的最后一篇，总结一下我对企业分析的看法。企业分析需要综合素质，这是我这一年来对企业分析的理解...


** [[https://time.geekbang.org/column/article/40936][结束语 | 积跬步，而终至千里]]

陪君一年，终有一别。希望我的专栏故事，让每一个“你”都有一份不同的收获。


** [[https://time.geekbang.org/column/article/40949][一键直达 | 系列解读文章回顾]]

这些系列文章虽有序却分散在全年的专栏目录中，专栏的最后，我们整理了几大系列文章的直达目录，以方便你按行业...

