#+title: 极客时间|朱赟的技术管理课 文章目录
#+options: num:nil


** [[https://time.geekbang.org/column/article/780][开篇词 | 从工程师到管理者，我的思考与实践]]

我是朱赟。和我一样从工程师转成管理者的人很多，我会把自己在实践中的思考、经验和解决过的困难第一时间分享给...


** [[https://time.geekbang.org/column/article/802][01 | 职场分身术：从给答案到做引导]]

我花大把时间在“带新人”上，每天都在回答各种随机的问题。我越来越忙，似乎越来越重要。当组里人多起来时，我...


** [[https://time.geekbang.org/column/article/817][02 | Bug引发事故，该不该追究责任？]]

技术人员也是人，在编程过程中难免会出 Bug，各种因为代码问题引起的麻烦也是屡见不鲜。那么，在 Bug 引发问...


** [[https://time.geekbang.org/column/article/821][03 | 每个工程师都应该了解的：A/B测试]]

A/B 测试是一种数据分析手段，它可以对产品特性、设计、市场、营销等方面进行受控实验。 那么，在做A/B 测...


** [[https://time.geekbang.org/column/article/886][04 | 如何帮助团队成员成长]]

如何帮助团队成员成长？要回答这个问题，我们不妨先换位思考一下。如果我们是下属，那么：“老板或上级的哪些举...


** [[https://time.geekbang.org/column/article/893][05 | 当我们给别人提意见时，要注意些什么？]]

即使是最好的意见、最客观的表达，如果传递方式不合理，也很可能达不到预期的效果。提意见，显然是一门艺术。


** [[https://time.geekbang.org/column/article/896][06 | 每个工程师都应该了解的：聊聊幂等]]

一个操作如果任意多次执行所产生的影响均与一次执行的影响相同，我们就称为幂等。只有当你把实现中所有的细节都...


** [[https://time.geekbang.org/column/article/1026][07 | 当别人给我们提意见时，该如何应对？]]

现实生活中，你接收到的所有意见，并不是都以一种愉快的方式不期而至。当收到那些让我们觉得不太舒服的意见时，...


** [[https://time.geekbang.org/column/article/1031][08 | 说说硅谷公司中的一对一沟通]]

每两周会有一次到两次的一对一面谈。经理人会和每位团队成员进行一次大约二三十分钟的跟进谈话，这个行为差不多...


** [[https://time.geekbang.org/column/article/1055][09 | 每个工程师都应该了解的：大数据时代的算法]]

在大数据时代，算法的重要性日渐明晰。一个合格的程序员，必须掌握算法。


** [[https://time.geekbang.org/column/article/1250][10 | 项目延期了，作为负责人该怎么办？]]

互联网时代瞬息万变，不变的永远是变化，只要我们参与软件研发，总会遇到项目延期的情况。一旦发现项目延期了，...


** [[https://time.geekbang.org/column/article/1256][11 | 管理和被管理：期望值差异]]

在我们的职场生涯中，管理者与被管理者之间会存在各种各样的关系。我觉得其中最需要避免的情况之一，就是期望值...


** [[https://time.geekbang.org/column/article/1294][12 | 每个工程师都应该了解的：数据库知识]]

数据库可以说是互联网公司最宝贵的资产，这块不出问题也罢，一出问题，即是见血封喉，服务直接宕机。


** [[https://time.geekbang.org/column/article/1434][13 | 管理者在进行工作分配时，会考虑哪些问题？]]

我们在分配任务给别人的时候，别人也在分配任务给我们。我们在别人身上寻找某种品质，别人也在我们身上找寻类似...


** [[https://time.geekbang.org/column/article/1441][14 | 硅谷人到底忙不忙？]]

对在硅谷奋战的工程师而言，忙不忙完全是由他们决定的，是他们自己的选择。一切工作压力并不来自升职、同事或管...


** [[https://time.geekbang.org/column/article/1539][15 | 每个工程师都应该了解的：系统拆分]]

系统拆分是一个实践性很强的工作，并无一定之规，只有亲自参与了这个过程，才会有更深入的体会。


** [[https://time.geekbang.org/column/article/1640][16 | 技术人如何建立个人影响力?]]

建立个人的影响力并不是为了凸显你自己有多重要，或者让别人更加认可你，而是通过影响力把事情做成。


** [[https://time.geekbang.org/column/article/1688][17 | 管理者不用亲力亲为：关键是什么？]]

技术能力强悍的工程师刚刚走上管理岗位时，最爱做的事情就是亲力亲为，看谁干活都不放心，恨不得自己把所有的事...


** [[https://time.geekbang.org/column/article/1691][18 | 每个工程师都应该了解的：API 的设计和实现]]

API 设计是现代软件系统中不可或缺的一个环节，不同的系统需求和不同编程语言下，API 的设计都大不相同，但总...


** [[https://time.geekbang.org/column/article/1836][19 | 硅谷面试：那些你应该知道的事儿]]

硅谷为什么会有那么多轮的面试，面试前要不要刷题，面试过程中与面试官的交流是怎样的，面试题的难度分级和内推...


** [[https://time.geekbang.org/column/article/1839][20 | 项目管理中的三个技巧]]

作为管理者，我们平时在项目管理的过程中，更侧重的是要保证团队成员能够按照你的期望值完成任务。那么，该如何...


** [[https://time.geekbang.org/column/article/1894][21 | 每个工程师都应该了解的：中美在支付技术和大环境下的差异]]

一笔钱从甲方转移到乙方。这笔转移可能是商家和顾客间的货款交易，也可能是个人对个人的转账，支付系统就是让这...


** [[https://time.geekbang.org/column/article/1959][22 | 不要做微观的管理者]]

在管理的过程中，既不要事必躬亲，也别做甩手掌柜。根据具体的人和事采取不同的管理方式，适当调整跟进的粒度，...


** [[https://time.geekbang.org/column/article/1981][23 | 如何处理工作中的人际关系？]]

生活中亲疏有别，有些人不愿意理也就懒得交流，但工作中的很多交流是不可避免的，所以常常需要比生活中的关系更...


** [[https://time.geekbang.org/column/article/2049][24 | 编程语言漫谈]]

编程语言，你看它是山，它就是山；看它是水，它就是水。一门编程语言到底能做什么，完全和工程师怎么去用，在什...


** [[https://time.geekbang.org/column/article/2200][25 | 兼容并包的领导方式]]

产品或者平台怎样才能让每个用户都体验到想要的个性化呢？这就要求设计者必须意识到用户的多样化和需求的差异化...


** [[https://time.geekbang.org/column/article/2206][26 | 如何做自己的职场规划？]]

做一个职场规划时，你作为当事人，自己要先想清楚很多问题，然后再和你的领导者交流沟通，寻求他的支持和帮助。


** [[https://time.geekbang.org/column/article/2239][27 | 小议Java语言]]

很多新人入门会要求我推荐编程语言，Java 属于我推荐的语言之一，因为 Java 标准、规范，是面向对象编程的代...


** [[https://time.geekbang.org/column/article/2452][28 | 如何激发团队人员的责任心]]

有效的责任制，在开始的时候就要让所有人明确责任与权利，而不是最后追究责任或推卸责任。


** [[https://time.geekbang.org/column/article/2462][29 | 说说硅谷互联网公司的开发流程]]

硅谷里稍具规模的互联网公司都会遵循类似的流程，他们就是通过这样的流程开发出了创新性的产品。


** [[https://time.geekbang.org/column/article/2517][30 | 编程马拉松]]

终于有机会说出我自己一直很喜欢的一句话：Geek is the new sexy! 会写代码的人真的就是很帅！


** [[https://time.geekbang.org/column/article/2611][31 | 工程师、产品经理、数据工程师是如何一起工作的？]]

做为一个软件工程师，如果有机会和产品经理和数据工程师一起工作，我们可以从他们视角去看待问题，可以拓展自己...


** [[https://time.geekbang.org/column/article/2679][32 | 硅谷人如何做 Code Review]]

Code Review 主要是在软件开发的过程中，对源代码进行同级评审，其目的是找出并修正软件开发过程中出现的错误...


** [[https://time.geekbang.org/column/article/2623][33 | 技术人的犯错成本]]

一个工程师手抖把公司的用户数据库删掉了，而恰恰这个数据库的自动备份在一个月前停掉了，最后这个公司真的就倒...


** [[https://time.geekbang.org/column/article/2795][34 | 如何从错误中成长？]]

在竞争激烈的互联网时代，试错当然是好事，但了解错误成本，避免不应该犯的错误，最大可能地从错误中成长，才是...


** [[https://time.geekbang.org/column/article/2812][35 | 理解并建立自己的工作弹性]]

一个好的软件系统就像是一个具备弹性的有机生命体，能够动态地改变自己的特性或功能，调配资源，去适应外界的变...


** [[https://time.geekbang.org/column/article/2816][36 | 如何对更多的工作说“不”]]

越来越多的“ Yes ”会让你背上沉重的包袱，无效的社交、超出能力范围的帮助、不合理的要求等等，都会耗尽你...


** [[https://time.geekbang.org/column/article/3227][尾声：成长不是顿悟，而是练习]]

这个专栏里记录的，不是我的顿悟，而是我的练习。希望给你带来的，也不是顿悟，而是在你成长的道路上练习的时候...


** [[https://time.geekbang.org/column/article/6167][新书 |《跃迁：从技术到管理的硅谷路径》]]

在专栏结束的第 77 天后，我出了一本书：《跃迁：从技术到管理的硅谷路径》。专栏是这本书的起点，也是书中的...

