#+title: Getting Things Done When You're Only a Grunt

http://www.joelonsoftware.com/articles/fog0000000332.html

如果你在一个烂单位工作, 但是又因为各种原因暂时没有办法离开, 你能够做点什么呢? 这篇文章给了一些建议.

You could just leave, I suppose. But presumably, there's some reason you're stuck there. The stock options haven't quite vested, there's no better place to work in Podunk, or perhaps your boss is holding someone you love hostage. In any case, dealing with life on a bad team can be infuriating. But there are strategies for improving your team from the bottom, and I'd like to share a few of them.

我这里就大致地总结一下, 有兴趣的朋友可以点进去看

- Strategy 1 Just Do It. 单纯地, 默默地做点事情
- Strategy 2 Harness the Power of Viral Marketing. 开始把自己做的事情告诉整个team, 鼓励团队提高自身水平.
- Strategy 3 Create a Pocket of Excellence. 帮助团队里面一些态度好(愿意学习)的队员, 或者是招一些高水平的队员, 改进自己的团队.
- Strategy 4 Neutralize The Bozos. 把team里面的bozo给屏蔽掉.
- Strategy 5 Get Away From Interruptions. 这点我的理解是, 如果其他部门频繁地打断你做一些没有意义的事情的话, 就自己找个小隔间待着吧.
- Strategy 6 Become Invaluable. 最重要的一点是, 如果想改变别人, 那么最好先改变自己, 给别人树立一个榜样.
