#+title: 论"目标导向"和"过程导向"
from 硅谷王川公号2018年合集

2/ 目标导向，适合于战术上的，目标比较明确，有先例可循的事情，这个很好理解.

3/ 过程导向 (process oriented)，适合于战略上的，目标方向有很大模糊性的，没有太多先例可循的事情。其特性在于，只要按照一个流程和框架，去摸索去打基础，最终你所希望的战略目标，会自然而然的浮现而唾手可得。 但不能保证具体的时间，也不能保证是按照你所设想的方式.

4/ 常常想把目标导向的习惯，代入到对战略的追求上，然后不断被现实打脸.

5/ 目标导向的误区在于，你追求的目标，可能只是全部客观现实的冰山一角。看得到的目标背后，有成体系的一大堆东西，需要你把基础打好，体系建设好，才能够真正获得。你以为走一条捷径，唾手可得的东西； 实际上是需要编织一个密集的网络，基础打好后，自然落网的.

6/ 目标导向的第二个误区，在于环境是迅速变化的。所有目标导向的行为，都是依靠对过去经验的拟合与简化后的捷径。环境的变化，可能导致过去的经验和捷径迅速失效.

7/ 拿目标导向的风格，用于对战略的追求，使用的是错误的评测标准。因为你心中一直想的是一个捷径，直逼想象中的战略目标，所以你一直把现实和想象目标的直线距离，作为评测进展的指标，并用来感动麻醉自己。 同时因为忽略在其它方面全方位打基础的工作，会出现一种，总是想靠近战略目标，却总是无法接近的深深挫折感.

9/ 过程导向的哲学，评判进步的标准可能是:
- 我是不是又纠正了对一些概念的错误理解？
- 我是不是又学到了新的，完全不同的知识，思维框架和方法论 ？
- 我是不是又积聚到新的资源，人脉，让我更加反脆弱 ?
- 我的学习速度，纠错速度，是不是又更快了？ 大脑内存是不是更多了 ？ (这也许要到脑机结合的技术实现后才会真正有大突破 :)
- 我从外界获取的信息，是否更加全面 /细致 /迅速 /真实地反映客观现实?

10/ 目标导向的行为，获取的收益都是可以预见的，有上限的，回报和投入线性相关。过程导向的行为，很长时间都在打基础，但一旦抓住一个指数型的增长点，其增长会远超常人预计，出现一年挣的钱是过去几十年的总和的现象. 但多数人没有耐心熬到这一天，因此其认知框架将永远定格在目标导向，线性增长的世界里.

11/ 一个例子是律师和医生这些高收入专业人士. 做到极致也就是靠卖体力按照时间获得线性收益，他们很难理解一个指数增长的好生意的境界。

12/ 有哲人说，“如果你专注于成果，你永远无法改变；如果你专注于改变，你会得到成果” (If you focus on results, you will never change; If you focus on change,you will gget results). 专注于过程导向来改变自己，你终将获得超越预期和想象的结果。
