#+title: 教父(GodFather)
** 第一部
人物：
- 维托柯里昂 纽约首领，教父
- 麦克柯里昂 三儿子，冷静能干，但是不愿意陷入家族事业
- 弗雷多柯里昂 二儿子，懦弱怕事
- 山提诺柯里昂 大儿子，冲动
- 康妮柯里昂 女儿
- 强尼方亭 教子
- 汤姆海根 教父的参谋私人律师
- 保利 教父的司机，属于克里门沙的手下
- 安索 面包师，是一个意大利人，来美国参战但是因为战争的结束可能会被遣返意大利，因为教父的原因能够留在美国:-)
- 克里门沙 教父手下
- 包纳萨拉 殡仪师，他的女儿被两个很有势力的人打得很重，但是自己没有办法对付那两个有势力的人，在教父的帮助下对付了两个有势力的人，后来帮助教父美容了一下满身疮痍的山提诺的尸体
- 巴西尼 黑帮家族
- 塔塔基利亚 黑帮家族
- 路卡布拉西 教父得力打手
- 华尔斯 好莱坞导演
- 布诺塔塔基利亚 塔塔基利亚家族人
- 麦克劳斯 纽约警局警长
- 路 索隆索的司机
- 卡洛 康妮的老公
- 汤马西诺 教父在西西里亚认识的人
- 艾波洛尼亚 麦克在西西里亚的妻子
- 法布里奇奥 麦克在西西里亚的保镖，但是被塔塔基利亚收买
- 卡罗 麦克在西西里亚的另一个保镖
- 卡麦克瑞安诺 布朗区首领
- 飞利浦塔塔基利亚 布鲁克林首领，塔塔基利亚家族首领
- 维多史特基 斯坦登岛首领
- 凯特 麦克的老婆
- 莫格林 拉斯维加斯赌场的经理，可以说是创建了拉斯维加斯赌城
- 沙尔泰西欧 教父手下

故事实在是很难描述清楚，主线只有一条就是索隆索+塔塔基利亚+巴西尼家族和柯里昂家族的斗争，但是事情发展确实是很很曲折，这里面只是记录下一些重要的点，前几遍看的时候没有反应过来
- 和索隆索的谈判中，山提诺的一句话造成了教父的杀身之祸，因为索隆索知道教父没有心思介入毒品，但是他的儿子愿意，儿子继承父业就能够合作了
- 保利的叛变是在整个冬天都假装生病并且向索隆索报告了教父的出行习惯，在某个点才会出办公室并且回家，为索隆索的杀手汇报了情况。因为保利之前都是替教父开车的人
- 山提诺说漏嘴了教父就立刻派路卡布拉奇去杀掉索隆索，因为他知道事态的严重， 但是索隆索把路卡杀掉并且立刻封锁消息，直到后面通过西西里人的口信，就是路卡的防弹衣+一条死鱼告诉柯里昂家族，路卡和鱼长眠了。封锁消息然后让教父认为路卡成功打入塔塔基利亚内部，放松警惕，真是…
- 卡洛被巴奇尼收买并且殴打康妮，让山提诺冲动单独出行结果被塔塔基利亚家族干掉，这是因 为之前山提诺干掉了布诺塔塔基利亚，造成了事件的升级，因为之前只是索隆索和柯里昂家族的事情，现在到了塔塔基利亚和柯里昂家族之间的事情，这就是冲动的后果
- 沙尔泰西欧后来是不服麦克柯里昂的管理， 因为麦克柯里昂希望将自己的发展向内华达州前，而在此之前不希望泰西欧和克里门沙自立门户，而且承诺他们需要六个月才能够独立门户。泰西欧而认为这六个月如果不能够独立门户将会被巴西尼踩在头上，结果投靠了巴西尼家族:-(

-----
这类事情每十年左右总要发生一次，这是恶感积累到一定程度的必然结果。如果咱们再小事情上让人家牵着鼻子走，他们就会得寸进尺，逼得咱们走投无路。

一个人只有一个命运。

我要同他讲道理。这是不流血又解决问题的最后机会。

维托在年轻的时候就被认为是通情达理的人，他从来没有说过一句威胁的话，他始终使用的是不可抗拒的逻辑。他办事终归要根据的原则是：别人也得到了应得的一份利益，各方都不吃亏。他为达到这个目的，采用的是公开手法。他像许多天才商人一样懂得
：自由竞争是浪费，垄断是有效的。因此他追求的目标就是要达到那种有效的垄断

哪怕有些人眼瞎帮不了咱们的忙也要，我相信友谊，我也愿意首先表示我的友谊

使用威胁乃是最愚蠢的自我暴露，事前不想想就大发脾气是最危险的任性表现。谁也没有听到过老头子脱口而出说过一句赤裸裸的威胁的话，

谁也没有看到她发脾气的不能控制。就这样，他竭力把自己的戒律交给桑儿，他认为：人生除了有一个敌人过高估计你的缺点，就在没有更大的自然优势了。

我为人一向谨慎小心。在生活中，我发现粗心大意最不和我的脾气。女人儿童粗心大意一下倒没有什么，男人以粗心大意就不得了。

塔塔格里亚只不过是一个拉皮条，他根本不可能斗过桑蒂诺，这就是我为什么认为不必对事情进行调查了解的主要原因了。知道巴齐尼插手，这就足够了

你对你所爱的人不能随便说‘不’字，也不能常常说，这就是诀窍。当你说‘不’字时，你得把‘不’字说得像‘是’字一样悦耳。另一个办法就是让他们说‘不’字。你得耐心，还得不怕麻烦。

诀窍就是首先要发现哪个人不怕死，甚至找死。接着就是使你自己成为世界上他所希望的不要把他打死的唯一的人。他只有一个恐惧，不是怕死，而是怕你可能会成为打死他的人。做到这一部，那它就是你的贴心人了。

一个男子汉在自己子女面前拿不出爸爸的气度出来，绝对不可能是真正的男子汉

友谊就是一切，它比天赋更重要。朋友比政府更重要，朋友简直等于自家人。

一个带着公事包的律师能够闭一百个带着枪的强盗榨取更多的财物

千万别动肝火，千万不可作出威胁的样子，要和别人说理。说理的艺术就在于撇开一切侮辱，一切威胁。他打了你左脸，那么把右脸转过来让他再打。黑根曾经亲眼见过教父一连八个钟头稳坐在谈判桌旁，一再忍受侮辱，试图说服一个臭名昭著，狂妄自大，

飞扬跋扈的狂人改过自新。八个钟头谈判无效，可里昂无可奈何的举起双手，对谈判桌旁其余人说：谁也无法和这号人说话。说完昂首阔步离开会议室。那个狂妄自大的人吓得脸色苍白，然后秘密请克利昂回到会议室。协议达成了，但是三个月后，那个狂人就在他常去的理发店被击毙。

我希望你的事业能够继续兴旺发达，我们国家需要你从事的事业

在克利昂一家的世界里，肉体美，女人的性魅力，在处理世俗事务的过程中一点分量也没有。男女之间的问题是无足轻重的私人小事，当然，除非涉及到婚姻和家庭荣辱。

** 第二部
人物：
- 保罗柯里昂 维托柯里昂的哥哥
- 西西欧 西西里亚的一个黑帮老大
- 安东尼柯里昂 维托柯里昂的儿子
- 玛莉柯里昂 维托柯里昂的女儿
- 法兰吉潘坦居利 以前属于克里门沙的手下,克里门沙死后归麦克管理
- 派特格瑞 内华达的一个参议院
- 威利奇奇 法兰吉潘坦居利的一个保镖
- 强尼欧拉 海门罗斯的一个助手
- 艾尔纳利 麦克柯里昂的一个保镖,这个人在第一部的时候最后面是去杀巴西尼的
- 罗萨罗 克里门沙打算死后把布朗区的三个地区给他处理,但是他算是海门罗斯的人
- 范伦奇 在维托柯里昂时代那个地区的黑手党的人
- 海门罗斯 维托柯里昂的一个合作伙伴,维托柯里昂尊敬他,但是从来不相信他:-)
- 汤马西诺 维托柯里昂在西西里的一个朋友

这集有很多人牵扯进来了，但是大部分都不是很重要，这里也只是写下一些要点的东西， 我比较喜欢第二部，因为第二部有着更多的利益冲突在里面而不仅仅是恐怖，而且如果需要恐怖的话，你可以站在mike的角度去找杀手的，你会觉得很恐怖。因为你不知道是法兰吉潘坦居利还是海门罗斯，两个人都是自己父亲的得力助手
- mike希望把在内华达和拉斯维加斯的赌场扩大到托比卡拉，在那边扩充赌场,但是那边没有营业执照，所以希望从派特格瑞这个内华达的参议员这里买到营业执照，但是派特格瑞将营业执照从2万提到25万，并且希望每个月能够收到4个赌场营业总额的5%，这是不能够接受的。 我猜应该是mike知道派特格瑞经常去妓院，所以故意弄出一件命案嫁祸给派特格瑞并且威胁他，这也是为什么之后派特格瑞被拉到柯里昂家族这边了，够手段:-)
- 我猜想第一次麦克柯里昂被刺杀的时候，怀疑的对象是法兰吉潘坦居利而不是海门罗斯。因为对于海门罗斯，麦克柯里昂一直没有采取什么行动，但是对于法兰吉，麦克柯里昂劝法兰吉去和罗萨罗讲和，并且告诉海门罗斯让罗萨罗杀掉法兰吉，但是法兰吉命大没有杀死，这也是之后法兰吉会去举报柯里昂是一个犯罪集团。虽然汤姆海根后来还和麦克柯里昂说”潘坦居利认为是你陷害他所以去揭发你”,但是麦克柯里昂之前的一句哈直接反映了这点”潘坦居利还活着??”，一个疑问句明显说明了麦克柯里昂第一次还是怀疑到了法兰吉的
- 麦克柯里昂最后确定是弗雷多窜通强尼欧拉和海门罗斯杀害他，是在哈瓦那的总统府看表演的时候，弗雷多说了一句”这个地方是强尼欧拉告诉我的”，而之前弗雷多和强尼欧拉见面的时候都假装不认识:-)
- 法兰吉潘坦居利最后自杀还是因为希望自己的家人能够保住性命:-)
- 汤马西诺在和维托柯里昂回西西里的时候，杀掉维托柯里昂的弑族仇人西西欧的时候，被一个强手打中了腿，这也是为什么第一部还有第三步，汤玛西诺先是一瘸一拐，后来是作在轮椅上的:-)

-----
你的父亲尊重海门罗斯，但是他从来不相信海门罗斯

想想他们怎么想的，建立生意上面的话，没有什么事情是不可能发生的

历史的车轮告诉我们，没有人是干不掉的

close to your firends,closer to your enemies

** 第三部
人物:
- 麦克柯里昂 第二代教父
- 玛莉柯里昂 麦克柯里昂女儿
- 安东尼柯里昂 麦克柯里昂儿子
- 乔扎萨 柯里昂在纽约生意的接管人
- 文森曼西尼 桑尼柯里昂的儿子
- 艾图贝洛 维多柯里昂的朋友
- 强尼方亭 维多柯里昂的教子
- 安东尼史基拉罗 乔扎萨的保镖
- 安德鲁海根 汤姆海根的儿子
- 特里莎海根 汤姆海根的妻子
- 安索 维多柯里昂帮助过的面包师
- 汤马西诺 维托柯里昂在西西里的朋友
- 鲁卡西 反对柯里昂掌管immobiliare的头头
- 龙巴度枢机主教 若望保禄一世
- 凯斯济 大主教的朋友[应该也掌握部分梵蒂冈银行的资金]

一些细节:
- 影片的开头叙述了上一部未完的事情就是弗雷多柯里昂的命运。麦克站在玻璃前面，接着湖上面一个枪声，接着麦克低下了头
- 麦克在授勋的时候看前妻Kate的眼神，真是感觉无限沧桑
- 文森曼西尼是桑尼柯里昂和外面女人胡搞生的，所以一直不被柯里昂家族所接受，也是文森曼西尼开始不认识玛利柯里昂的原因
- 注意麦克柯里昂所办的基金不是叫柯里昂基金，而是以父亲名字命名的维多柯良基金
- 教廷派大主教掌管梵蒂冈银行，同时梵蒂冈银行持有immobiliare的25%的股份。然后当时大主教损失了近8亿，然后这个时候麦克通过存入6亿美元来控制梵蒂冈银行以获得immobiliare的控制，但是最后梵蒂冈银行的决定还必须经由罗马教廷定夺，但是问题就是在这个时候罗马教皇[教宗保罗六世]一病不起，然后议程进入了僵局。
- 麦克之所以想进入immobiliare的原因是因为他想摆脱非法生意所以他也想解散赌场，但是出乎意料的是在那些看上去像是合法生意里面也充斥着非法的活动，充斥着卑劣的手段
- 麦克派出文森曼西尼探探艾图贝洛的关系如何…，从刺杀之后麦克就一直怀疑艾图贝洛，因为他知道乔扎萨的性格和实力不可能做出刺杀这种行动，而期间艾图贝洛又离席。但是他始终感觉艾图贝洛还是不够实力，所以派出曼西尼探艾图贝洛的关系网有多深….[而且他从汤马西诺口里也知道，艾图贝洛维护着西西里和美国友人的关系，所以关系网势必非常大]

知道整个故事情节之后就知道第三部没有第一，二部好看。基本上里面的人物关系一开始就定下来了，没有任何转变的过程。相反觉得第二部非常好看，怀疑到了海门罗斯和法兰吉潘坦居利，通过两边有进行威慑最后发现是海门罗斯，但是同时法兰吉潘坦居利又变节指控麦克。最后追查海门罗斯在家族里面的内鬼居然是自己的弟弟。第一部也有这种查证过程，但是更加突出了恐怖的气氛。我估摸这是黑帮电影的套路:
- 涉及到了暗杀[1.杀害维多柯里昂和桑尼柯里昂 2.杀害麦克柯里昂 3.杀害麦克柯里昂]
- 找到凶手但是凶手都有后台[1.索隆索 2.凶手自杀了 3.乔扎萨]
- 找到后台[1.巴西尼和其他三大家族 2.海门罗斯 3.鲁卡西]

-----

”I protected all of you from all horror in the world.” “But you became my horror”

Friendship and money, oil and water[朋友和金钱，像油和水一样].

Never hate your enemies. It will affect your judgement.

Never let anyone know what you are thinking

Even the strongest man needs friends.

But you know guns. Finance is a gun, politics is knowing when to put the trigger.

you won’t be able to go back, you will be my being.[没有机会回头，步我的后尘]
