#+title: Good and Bad Reasons to Become an Entrepreneur

https://medium.com/i-m-h-o/good-and-bad-reasons-to-become-an-entrepreneur-decf0766de8d

So for our audience at the time, entrepreneur meant “Silicon Valley startup technology entrepreneur.” （这里企业家是指硅谷科技创业企业家）

The reason we like best for becoming an entrepreneur is that you are extremely passionate about an idea and believe that starting a new company is the best way to bring it into the world. The passion is important because entrepreneurship is hard and you’ll need it to endure the struggle, as well as to convince other people to help you. Believing that starting a new company is the best way to bring it into the world is important to ensure that resources—including most importantly your own time — are being put to the best possible use. If the idea is best brought into the world by an existing team, then it is tautologically optimal for the world for it to happen that way. Of course, not everyone is actually trying to optimize their impact, but many entrepreneurs are, by their own admission, and it is important for those people to consider this angle.（好处1： maximize impact）

If you’re not trying to maximize impact, then it seems like a reasonable assumption that you are instead optimizing around personal lifestyle preferences of some kind. You want total freedom to choose how you make your living, regardless of if it necessarily provide large amounts of value to other people or perhaps is even redundant with something that already exists. Or you want extreme flexibility in your schedule, maybe including the ability to stop working altogether for long periods of time at short notice. Or you want to work on a certain kind of problem or with certain kinds of people. For many kinds of preference, you likely can actually find a company able to give them to you, but certainly starting your own is a great shortcut and I personally think that’s totally reasonable. I like people who are seeking to have big impact on the world, but it is not the only path worth taking, and I have no reason to denigrate this type of entrepreneur.（好处2：灵活地安排个人时间和工作生活）

You want to be your own boss in a big company. Evernote CEO Phil Libin [[http://thenextweb.com/video/2012/04/27/evernote-ceo-phil-libin-my-advice-to-aspiring-entrepreneurs-dont-do-it-video/][put it well last year]]: （坏处1：要管理所有的事情）
#+BEGIN_QUOTE
“People have this vision of being the CEO of a company they started and being on top of the pyramid. Some people are motivated by that, but that’s not at all what it’s like.

What it’s really like: everyone else is your boss – all of your employees, customers, partners, users, media are your boss. I’ve never had more bosses and needed to account for more people today.

The life of most CEOs is reporting to everyone else, at least that’s what it feels like to me and most CEOs I know. If you want to exercise power and authority over people, join the military or go into politics. Don’t be an entrepreneur.”
#+END_QUOTE

You think it’s glamorous. The media does a great job idolizing various entrepreneurs, crowning Kings and designating Godfathers of various mafias, but this is all colorful narrative. The reality is years of hard work, throughout which you usually have no idea if you’re even moving in the right direction.（坏处2：没有想象的那么光鲜。你必须努力工作，并且有时候你甚至不确定自己是否沿着正确方向前进）

You believe you’re extremely talented and that this is the way to maximize your financial return on that talent. Why wouldn’t you want more of the cap table? This is flawed logic, since the 100th engineer at Facebook made far more money than 99% of Silicon Valley entrepreneurs. Small slices of gigantic pies are still themselves gigantic. If you’re extremely talented, you can easily identify a company with high growth potential and relatively low risk and get an aggressive compensation package from them. If you turn out to be wrong after a few years, you can try again. Within 2 or 3 tries, and likely on the first one, you’ll have a great outcome and can be confident you contributed serious lasting value to the world. If you instead try to immediately start “the next Google or Facebook”, there is a very high likelihood that you will fail completely, or be forced to settle for a much smaller outcome. It will take a long time to reach success or failure, so you won’t have many tries.（如果你只是最大化自己投资回报，那么完全没有必要来创业。加入快速增长公司会以更低的风险得到丰厚的回报，即便公司失败完全可以做下次尝试；可以如果自己创业并且获得相同回报的话，失败几率非常高并且周期也很长，基本上你只有几次机会）

file:images/financial-reward-and-impact.png
