#+title: 桂林山水

*2013-07-20（初到桂林）*

上午11：55在首都国际机场T2坐南方航空CZ3282，下午2：55到桂林的两江机场。刚下飞机就可以从各个方向看到山，属于那种群山环绕的感觉。出发之前预定了在锦江之星的七星店，上面还有一行小字是如果预定成功的话，可以通过发送短信方式告知自己的航班来预约接机的汽车。当天我就把自己的航班信息发送过去了，可是当时我也是半信半疑。因为虽然是在桂林，但是我估计从机场到市区里面还有会有很长的距离的，这个出租车的费用应该也是不便宜的。可以下午2：55刚下飞机的时候果然有一个女的给我了电话，告诉自己就在出口等我。而当我告诉她我还要取行李的时候，她说没有关系可以等不急。当时我就震惊了，尼玛的服务这么到位。即使见到她本人并且上车之后，我脑子里面还一直在想这个问题，会不会到时候她会问我要钱。路上我还特意问她从机场到市区里面打车不太方便吧，她说还是比较远的，打车要100多。

上了车之后，虽然我脑子里面还在想费用这个问题，眼睛却停留在车外面，在观察这个城市。不得不说桂林的绿化做得非常的好，机场到市区整条路上两边都有树而且长得很好，天空的蔚蓝也是许久在京津未见的。差不多开了将近半个小时到一个小时吧，到市区里面了。可是在市区里面绿化也和郊外一样没有马虎，两边马路见的最多的就是桂花树。我没有赶上好的季节，当地人说如果是在秋天桂花树花开的时候，整个桂林市都有一股淡淡的桂花香味。没有赶上好季节的第二个原因是天气太热而湿度太高，这点一出飞机场就感受到了，本来快遗忘蒸桑拿的感觉现在又回忆起来了。但是这个季节来有一个好处，就是人相对比较少还不算是旺季，我去风景区旅游最怕的就是人多破坏了意境。虽然桂林各个时候人都比较多，但是相对来说这个季节这个时分还算是可以的。另外桂林一个比较有意思的现象就是，从地形上来说上下坡比较多（可能没有青岛多），而人们非常喜欢骑电动车和摩托车。后来想清楚大概是为什么了。整个城市上下坡比较多，就决定了自行车这种纯粹靠人力的交通运输方式是不行了，可是汽车相对来说价格比较贵而且机动性不是很好，有些地方还只能是电动车和摩托车才能过，而且电动车和摩托车相对汽车来说便宜不少。在路上我看到了桂林山水甲天下的全对“桂林山水甲天下，玉碧螺清意可参”。

终于到了住的地方，我非常紧张地下车了，但是阿姨很热心地说直接进去就行了，让我一颗悬着的心掉了下来，顿生好感，但是同时思索这个费用怎么来呢？进来酒店办理入住的时候，那里的职员开始给我推荐行程了。因为之前我虽然调查过，但是好多地方还是比较模糊仅仅知道一个地方，各个地方之间的距离以及交通方式都不是很熟悉，也不知道一些经典是否值得去，所以就随意听了一下，然后拿着她给我的报价单上楼看了一下。她给的报价单里面最吸引我的就是，他们所有的行程都是可以包车的，并且不需要添加任何费用，只要从他们那里订购景点游玩，所以我当时在想是否这些交通费用从景点费用里面扣除。但是当时上去拿着报价单和网上的景点零售价格对比才发现，其实是一样的。so why not?!. 到住宿的地方差不多下午5：30了，打算下楼尝一下桂林米线（出门右转就有），顺便就订下来了明天在象鼻山附近做轮船和游靖江王城和独秀峰两个项目和后天去阳朔的项目。轮船费用是100, 靖江王城费用是130，两人一共460.去阳朔的项目首先是去世外桃源，然后到十里画廊上面的几个景点包括鑑山寺，大榕树，月亮山，然后从兴坪做竹筏到杨堤然后返回到兴坪，然后再回阳朔然后回桂林。这个项目是1日游，当天从桂林出发当天回来，费用在350.但是我们打算留在阳朔在看看，所以当晚就不回来了，这样加钱减去了30，两人一共640.

米粉确实不错。开始我和我老婆各点了牛腩粉和汤粉二两，价格还算是比较便宜，牛腩粉5.5汤粉5. 粉分为宽粉和圆粉，我觉得圆粉比较好吃，弄好之后可以添加一些排骨汤。一般大家吃粉都是不加汤的，但是我觉得加一些汤会更加好吃。吃完之后还是觉得汤粉是最好吃的，因为它本身没有什么其他的材料还衬托，更加凸显其米粉的味道。所以我建议如果吃桂林米粉的话汤粉会好吃多一点。

吃完了米粉我们就乘坐附近的14路公交车到正阳步行街看看。桂林的公交只有1元和2元两种，1元的没有空调，2元的有空调。正阳步行街在刚过解放桥的地方下，走两部就可以看到正阳步行街了。正阳步行街正对的就是靖江王城。沿着步行街很快就走到了末尾，因为整条街也只有666米。走过了步行街就可以看到日月双塔了，再走一下就可以看到两江四湖码头了。可以乘坐船只在绕两江四湖看看，但是我觉得没啥意思，就没有上船只是在附近走走。其实走走还行，晚上虽然还是桑拿天，但是也有习习凉风，走起来还是蛮舒服的。走出日月双塔就有一个电动三轮师傅上前主动询问我们去附近吃小吃，我们正好想在附近吃吃田螺所以就让他带我们去，非常便宜也就是1元，大概走了1公里吧。寻思怎么这么便宜，到了之后才发现，原来大排档和师傅是否回扣可以拿得。去的路上，师傅问我们是否订好了出游路线等。我和他说了我们去阳朔的那段行程，他说我们买贵了实际上我们那段他们只需要275就可以搞下来。当时悔恨不已，后来才知道这个价格和350项目是不同的，低价在漓江上坐的是大船，而高价在漓江上坐的是电动竹筏，而且这个差价在100元。在大排档吃完后在附近买了一些山竹和红毛丹就回宾馆了，这里的山竹不是很贵。

*这里我想提前说一下，整个桂林的旅游业相对来说还是比较正规的。* 一分钱一分货，旅行团给出的价格和散客购买的价格差不多，而且旅行团还附带了一些额外的服务比如包车等。大部分的景点都是明码标价，而且东西是否想要完全是取决于你自己，整体旅游环境还是不错的。但是中途我经过的两个景点不太正规被坑了。一个是阳朔的鉴山寺 ，一个是阳朔的榕树。
- 桂林鉴山寺和尚大肆骗敛钱财让谁蒙羞？-舆情观察 - : http://forum.china.com.cn/thread-1092447-1-1.html
- 桂林阳朔大榕树景区“百越壮寨”骗钱坑人！_网易旅游论坛 : http://bbs.travel.163.com/photoalbum/guilin/257641823.html

*2013-07-21（市内一瞥）*

今天的行程是：上午做轮船在漓江上看看象鼻山，伏波山和叠彩山，下午去靖江王府看看顺便爬一下独秀峰。因为行程不是很多，所以出发得比较晚。早上还是在附近吃了一些米粉之后，大约9点左右出发了。接我们的出租车师傅姓蒋，人很不错，后面还推荐吃的地方，而且去机场的前一天拉我们去机场。轮船是在解放桥下面做，从8：30开发，一个小时一班，所以我们赶上了9：30的那班，轮船票价大概就是100元吧。那是我做的那种轮船类似快艇的那种，开得还是比较快的，同时甲板不是很大上面不是能够站很多人，所以在象鼻山拍照的时候只能够分批上去轮流拍照。事实上那里还有另外一种轮船开得比较慢，是两层的那种，上层不能够坐人只是用来方便来拍照的，我觉得坐这种船游漓江会比较合适一点。码头那里有两个比较有特色的建筑，一个是六匹铜马，一个是有时间柱群上面有各个其他大城市的时间。轮船首先经过象鼻山，然后经过伏波山，然后到达叠彩山。可能每个山上的景色很不错，但是我感觉从漓江上看更能够凸显他们的魅力，所以我也就没有选择单独买票上去看。另外一个原因是因为我老婆怕累不愿意上去看。第三个原因是每个景点的票价还不便宜。经过象鼻山上甲板拍照的时候，因为时间比较有限，所以大家一定需要调整好焦距这样上去就可以直接拍照了。经过象鼻山的时候，可以清楚地看到在大象鼻子上面写着“放生池“，具体典故我不记得了，但是主要也是和为善相关的事情了。

感觉上午最有意思的还不是在船上的这一程，而是上岸之后的一程。因为轮船航行也就大约一个小时，我们10：30就上岸了。上岸之后我们并没有直接就叫蒋师傅，而是在叠彩上码头附近走了一下。当地有人就住在叠彩山里面，我们看到几个人在岸边，有一个洗衣服的，有一个在洗鸭子拔毛。而且从他们的房子看，觉得应该有一段历史了的，然后又住在水边，觉得特别的惬意。而且在那里我应该是第一次见到了竹桥，下面是钢筋拉起来的，钢筋上面放了很多竹子。别看走的时候整个桥晃晃悠悠，但是桥还是非常结实的，我看到有三轮摩托车在上面骑过。随便看看之后就打算撤了。撤的时候还看到一个打着吊瓶的病号在游漓江，OMG！找到蒋师傅之后，师傅推荐我们到安新小区附近的安新家味馆吃吃那里的啤酒鱼，味道还可以。我们让师傅先回去，吃完之后乘坐23路就回住的地方了。

下午大约2：30左右出发，3点到靖江王城的。值得一提的是，广西师范大学王城小区也就在这里，王城也有非常悠久的历史。王城的最北面就是独秀峰，其实独秀峰不高，但是游览完之后我独自登上了独秀峰，却可以从上面很好地尽收整个桂林的风景。王府里面是有专门解说的，介绍了很多东西，但是对于影响比较深刻的有两个。一个是古代人寒窗苦读的历程以及对于读书人最高的荣誉 [[http://baike.baidu.com/view/183444.htm][三元及第]] ，并且让我们在里面过了一把体验古代人乡试的感觉。 另外一个就是太岁。感觉太对对于靖江王城来说意义还是重大的，主要原因就是因为历史上“xx王”（忘记名字了）从民间收集了所有太岁的人物形象，然后将这些人物形象刻在洞里的石碑上，而靖江王城是保存这些太岁形象最完整的地方。人们为了不犯太岁，需要将和太岁相关的东西放在自己的身上，这样才能够趋福避祸，而最好的东西就是拓片。所谓拓片就是用纸在这些石雕上面不断地拍打，然后在纸上形成图案，通过拓片可以将这些太岁的形象拓到纸上。但是这样拓的方法对于石碑不好，因为不断地拍打会造成石碑拍平，这样拓的难度就不断地加大。在那里保存比较好的石碑拓片最便宜的大约在399，而保存不好的拓片最便宜的也在1800左右。当然这个其实完全看自己是否相信。老婆替岳父求了一个岳父的太岁，希望他可以随身携带保平安。在洞里面我也找到了自己的太岁 [[http://baike.baidu.com/view/2971628.htm][沈兴]] 。之后我还独自登上了独秀峰看了一下，然后就撤了。晚上师傅推荐我们去附近的椿记烧鹅试试，正好就在我住的附近。还行价格不是很贵，要了1/4只，但是我觉得没啥特色的。

*2013-07-22（初到阳朔）*

今天的行程是非常地满，也发生了非常多的事情，写起来手估计会酸了。或者我可能会先写一点摘要性东西，然后以后有时间慢慢补上=）。
- 导游拉客购买猫眼石
  - 早上8：00左右我们在宾馆门口等到包车，上去之后导游没有把我们直接拉去世外桃源，而是先让我们去买猫眼石，我就实在不同猫眼石到底有什么好的，不过老婆还是买了一颗。
- 世外桃源
  - 大约9：30左右到了。据说是台湾人在阳朔发现了一处非常类似陶渊明《桃花源记》里面描绘的仙境的地方，然后投资建设的。
  - 里面有一些特产，比如柚子皮果脯，板栗，黑蚂蚁（主要用来泡酒入药的，治疗风湿比较好）
  - 里面真的有一处地方很像《桃花源记》里面描绘的： *“晋太元中，武陵人捕鱼为业。缘溪行，忘路之远近。忽逢桃花林， 夹岸数百步，中无杂树，芳草鲜美，落英缤纷。渔人甚异之，复前行，欲穷其林。林尽水源，便得一山，山有小口，仿佛若有光。便舍船，从口入。初极狭，才通人。复行数十步，豁然开朗。土地平旷，屋舍俨然，有良田美池桑竹之属。阡陌交通，鸡犬相闻。其中往来种作，男女衣着，悉如外人。黄发垂髫，并怡然自乐。”* 这个地方是在燕子洞刚出去的地方，那个地方可能是人工栽培了很多桃花，而且附近也有很多居民在那里生活。
- 坑钱之地1：鉴山寺 #note: 下次再也不去什么佛门圣地了！
- 坑钱之地2：大榕树 #note: 下次再也不去什么民族寨子了！
- 月亮山
- 坑钱之地3：饭庄
  - 菜贵不好吃，茶水要收费。
- 片段漓江
  - 最著名的景点就是20元背面的风景照。其实那里还有两个比较有名的景点，一个是 [[http://baike.baidu.com/view/2182119.htm][黄布倒影]] ，一个 [[http://baike.baidu.com/view/2182119.htm][九马画山]] 。不过我倒是没有啥特别感觉那两个景点有什么特别的。
  - 不过整个漓江上确实就是一副美丽的画，这幅画需要阳光照耀，需要蓝天白云的衬托，需要青山绿水环绕，而自己置身画中，缺一不可。
  - 我们的行程大约2：00开始，4：30结束。从兴坪码头往杨堤方向开，开到九马画山附近就返回，而没有到杨堤。

这里有必要说一下阳朔的交通，比较特殊。在县里面打车是不会打表的，都是谈价钱，起步价是20元，所以除非包车否则在没有必要坐车。事实上阳朔县甚至桂林市都是一样的，就是几乎所有的出租车都会挂在某个旅行团下面。好比第一天带我出去的蒋师傅也是挂在旅行社下面的，当然他们也是可以单干的。单干这件事情在桂林市里面可以这么高，但是在县里面因为本来县就不是很大，所以搞头不是很大，因为在阳朔县里面的出租车基本上都是包车的那种，如果你遇见的话，那很有可能他正要回家或者是去接其他人，你们顺便遇见的。县里面自行车是比较方便的，可以租一天也不是很贵的那种，大约就20元吧。甚至是在遇龙河漂流终点，你可以在那里租自行车，然后骑回到西街还，侧面也可以说明自行车这种交通工具在阳朔还是非常受欢迎的。另外一种交通工具就是公交车了，但是这种公交车不是烧油的而是用电的，载客量不是很大一趟最多也就是我10多个人吧，价格非常便宜1元，不过感觉时间点不是很好掐的那种。

*2013-07-23（遇龙河下段）*

上午几乎没有出门，除了在附近买些米粉做早饭以及昨晚预定行程的师傅过来收取我费用我下楼之外，整个上午都是呆在宾馆里面的。师傅说这几天刚好有一些筏工罢工了，所以需要加30元，原因他说是当地政府补贴力度不够，不过具体我也没有搞懂。师傅说话的时候态度还是比较诚恳的，所以感觉他不像是在骗我，而且下午我证实了确实有一些筏工罢工了。网上看路线的时候我就听说这些筏工很辛苦，叫我们不要在意那些10元20元的，所以我当时也没怎么说。中午就住的附近一家叫做“我家食堂”的小馆子吃了，感觉不是很好吃，凑合吧。中午非常热！

下午大约2：00左右的时候包车到了宾馆下面，在市区里面绕了几个弯接了一些其他旅游团的客之外，就直奔遇龙河下半段了。下半段的起点是朝阳码头，终点是工农桥。我们大约2：30左右上船，4：30左右下船，整个过程大约就2个小时。这里的竹筏和漓江上的竹筏有本质的区别，就是这里的竹筏是人工划的，船走起来非常慢而且重要的是非常安静，而漓江上的竹筏是马达发动的，走起来非常快而且非常吵。竹筏上面只能做两人，坐稳之后师傅就开动了。泛筏于遇龙河上，景色和漓江还是有很大差别的。漓江都是树和山没有人居住，而遇龙河附近虽然也都是树和山但是都是有人居住的，并且遇龙河水面感觉要比我游的漓江那段要宽不少，同样考虑到那天人相对较少，所以那天下午的感觉非常放松，景色感觉也比漓江好了不少。整个遇龙河上有几个水坝，每过一个水坝都会溅起浪花，感觉非常爽。

坐竹筏的同时我们和筏工也聊起来了。开始聊起的话题自然就是罢工的事情。其实罢工的主要原因是因为政府要规范在河中心的烧烤，但是烧烤其实回给这部分筏工很大一部分回扣的。实际上这些筏工平时的工资并不高，虽然一趟筏大约在120元左右，但是实际上有80多被政府收去，另外一部分费用可能是被公司收去，筏工一筏大约只能赚到20多元。一天下来最多也就是3-4趟，所以如果烧烤生意好的话，回扣金额占比还是会比较大的，所以也不难明白为什么取消烧烤这件事情对于筏工来说影响这么大了。再说说他们的运营，其实这些筏以及上面的座椅都是公司购买的，筏工到这里来只需要出人力就可。他们从上游划到下游，然后下游有专门的车将这些筏和人拉到上游，感觉他们还是非常辛苦的。而且随着阳朔县逐渐转变成为旅游城市，医疗和住宿等费用也在不断地上涨，对这些筏工来说压力还是非常大的。

搞完之后回到酒店休息了一下，就在酒店附近找了一家馆子开吃起来。由于吃了几次啤酒鱼了，所以想换换口味，试试也是当地的一道名菜叫做干笋黄焖鸡，确实非常不错。馆子服务也是非常地到位，他们还自己沏了一些茶然后放在雪碧瓶子里面然后冷藏起来，有客来了之后就给一瓶，喝起来非常舒服，真的非常周到。整顿下来价格61，也不是很贵的那种。感觉在阳朔的话，去那种馆子或者是大排档比去那些饭店吃得要更实惠一些。吃完之后我们往西街走了走，从西街的正门进去发现人太多了，我们只是走了前面一小段便从小道回宾馆了。人多再好的气氛和景色都都会被毁了的。

*2013-07-24（遇龙河上段）*

可能是因为昨晚着凉的原因，早起的时候头特别地疼，浑身都没有力气。早上我们约好8：30在金龙桥开始遇龙河上半段，所以还必须早点起来。大约我们6：30就出发了，在附近吃了些混沌，不过吃完之后不知道为什么肚子还是不舒服了=（。本来我们是打算不行到阳朔汽车站的，离得也不是很远，但是因为肚子疼所以知道做摩的到车站，坐上了7：15的班车。从阳朔到金龙桥很快，大约也就是20-30分钟，到了金龙桥就开始联系师傅。因为我们要逆漂到富里桥一段，当时给中介师傅的150里面是没有包的，本来逆漂大约也就是20每筏，但是师傅当时要20每人也就是40每筏，算了。我们顺便要师傅帮我们介绍一个包车，将我们从终点载回阳朔，50元。

老实说这段和昨天那段风景差不多，而且因为我是上午去人还特别多，因为中间有几段比如遇龙桥一段是短游的，也就是说有好多人只是游那么一段。或许和昨天最大的差别就在于，这次下水了。没错，是我这只旱鸭子下水了。我们要求师傅划到一个浅水区，然后我穿着救生衣抱着竹筏下水了，感觉水是特别的清凉啊。划船的师傅说，这里的水和泳池的水有点不同，泳池的水游起来的时候会感觉胸闷，而这里的水不会。不过好吧，因为我们从没有在泳池有过，所以我也没有啥可以对比的。

下船之后我们等包车师傅过来，正好也有一群人想回阳朔，所以和我们拼车，他们给我了25元。回到酒店我是感觉彻底中暑了，在宾馆睡到了下午4点左右才离开宾馆坐那里的电瓶公交车到汽车站。车站发往桂林的车非常多，20元每个人也不是很贵，差不多开了1个小时左右。班车开到火车站之后我们打的回到了宾馆。虽然已经是晚上7点多了，但是我们都没有什么胃口。她先睡了，看电视差不多到11点左右才睡的。

*2013-07-25（市区重游）*

原本这一天是打算在桂林市区走走的，但是因为我们两个身体都有点不是很舒服所以就呆在宾馆里面了。早上在附近吃了米粉之后就回宾馆看电视了，中午也没有吃饭直到下午大约4点的时候才出去。从石油六公司乘坐23路公交车到安新小区北口下，在那里的安新家味馆吃了顿晚饭。老婆还想尝尝啤酒鱼，所以要了78每斤的的剑骨鱼两斤，加了一个清炒空心菜下饭。吃完之后到了附近的世纪华联买了一些当地的土特产。这个世纪华联就在民航大厦附近，有直接去机场的大巴，但是老婆觉得行李比较多，所以觉得还是想直接打车去机场。我联系了一下21号载我在附近玩的蒋师傅，80元从住的地方拉到机场，所以就没有坐机场大巴了。买完之后没有直接去步行街，而是先坐公交回到了住的地方把东西放下，稍微休息一下之后大约7点从锦江之星做14路空调车到了解放桥，重游了日月双塔，然后在那里顺便帮朋友也提了诗，买个了纪念品。

*2013-07-26（再见桂林）*

早上上午10：10从锦江之星的七星店出发，11：00就到了机场，在市区内还堵了一小会。所以如果不堵车的话，从市区到机场快的话也就是30分钟吧。桂林机场检查没有北京机场安检那么严格，安检的时候只是把电脑拿出来单独检查，原本在北京机场需要单独检查的相机没有拿出来检查，另外我还带了一个水杯里面乘满了水也没啥问题。航班是GS6612，12：30从桂林的两江机场起飞，中途经过郑州停机，16：25到达天津的滨海机场。可能是因为最近北京机场比较乱的原因，不知道为什么到了郑州转机的时候他们说北京这边的航班实行交通管制，搞得我们在郑州机场停留了将近1个小时，下午6点左右才到天津机场。
