#+title: 万万没想到:用理工科思维理解世界

-----
2019-03-28T10:09:42

现代社会与古代最大的不同，是人们的生活变得越来越复杂。除了工作和休息，我们还要娱乐、参加社交活动、学习和发展以及随时对遥远的公众事务发表意见。我们的每一个决定都可能以一种不直截了当的方式影响他人，然后再影响自己。面对这种复杂的局面，最基本的一个结果是好东西虽然多，你却不能都要。

这种担心会左右公共政策。文人可能从“是不是纯天然的”这个角度认为有机农业很美而核电很可怕，这不是一个好标准。可是他们总希望自己的声音大到能够调动很多人感情乃至于按照他说的“常识”采取行动的地步。他们号称是“民意”的代表，但他们代表的只是未经过“tradeoff”的原始民意。在大多数公共问题上，常识是不好使的。资源调配即使做不到完全依赖市场，也不应该谁声音大就听谁的。

你不用笑我，你也有同样的毛病。蒙洛迪诺说，人做判断的时候有两种机制：一种是“科学家机制”，先有证据再下结论；一种是“律师机制”，先有了结论再去找证据。世界上科学家很少，你猜绝大多数人使用什么机制思考？每个人都爱看能印证自己已有观念的东西。我们不但不爱看，而且还会直接忽略，那些不符合我们已有观念的证据。

当你年轻的时候，你看着电视就会想，这里面一定有阴谋。电视台想把我们变傻。可是等你长大一点，你发现不是这么回事儿。电视台的业务就是人们想要什么它们就给什么。这个想法更令人沮丧．阴谋论还算乐观的！至少你还有个坏人可以打，我们还可以革命！而现实是电视台只不过给我们想要的东西。

美国人玩的这一套，中国也有人早就玩明白了。今天，我们的媒体和网络上有各种观点鲜明的文章和报道，它们或者骂得特别犀利或者捧得特别动人，观众看得畅快淋漓，十分过瘾。但是这些文章提出什么切实可行的解决方案没有？说过什么能够修正我们现有思想的新信息没有？它们只是在迎合和肯定人们已有的观念而已。因为它们的生产者知道他们不需要取悦所有人。他们只要能让自己的“粉丝基本盘”高兴就已经足够获利的了。他们是“肯定贩卖者”。政治辩论？其实是一种娱乐。

恐惧使人害怕损失，浪漫使人热爱冒险。但这两种情绪的重要性并不一样，人一出生就有自我保护本能，而求偶本能则是在长大后才有。进化使我们大脑中恐惧的优先级高于浪漫，也许这就是负面偏见存在的原因。

实际上，现代职业化竞技体育中参赛者之间的实力差距往往并没有天壤之别，决定比赛结果的偶然因素非常大。强队也能输给弱队，是现代体育的重要特征，也是其魅力所在。如果强队一定胜利，比赛还有什么悬念？从这个意义上说，我们看比赛看的就是这个随机性。这就难怪《黑天鹅》的作者塔勒布（Nassim Nicholas Taleb）在《黑天鹅语录》（The Bed of Procrustes）一书中说：  Sports are commoditized and, alas, prostituted randomness. 体育是商品化，甚至是卖淫化了的随机性。

管理者有个常见的思维模式，一旦出了事就必须全体反思，制定相关政策以避免类似事故再次发生，但极小概率事故其实是不值得过度反应的。哪怕是因为员工犯了错而引起的也没必要如此。37signals公司的两位创始人弗莱德（Jason Fried）和汉森（David Heinemeier Hansson）在2010年出了一本书《重来》（Rework），讲公司创业和管理之道。在我看来此书一个亮点就是它强调不要一看有人犯了错就为此大张旗鼓地制定政策来纠正错误。那样只会把错误变成伤疤，而且会让公司越来越官僚主义。正确的办法是告诉犯错的员工这是一个错误，然后就完了。

我们的本能工作得如此之好，以至于我们在明明没有规律的地方也能找出规律来。人脑很擅长理解规律，但是很不擅长理解随机性。发现规律任何时候都可以帮助我们更好地生存下去，而理解随机性却是只在现代社会才有意义的一个技能。

如果统计数字很少，就很容易出现特别不均匀的情况。这个现象被诺贝尔经济学奖得主丹尼尔·卡尼曼戏称为“小数定律”。卡尼曼说如果我们不理解小数定律，我们就不能真正理解大数定律。

大数定律是我们从统计数字中推测真相的理论基础。大数定律[9]说如果统计样本足够大，那么事物出现的频率就能无限接近它的理论概率——也就是它的“本性”。所以，如果抽样调查发现一个地区某种疾病的发病率较高，我们就可以大致认为这个地区的这种疾病发病率真的很高。 而小数定律说如果样本不够大，那么它就会表现为各种极端情况，而这些情况可能跟本性一点关系没有。

如果你觉得这个逻辑太不可思议，那是因为你不经常上网看时事或军事论坛。有人[2]专门写这种文章。他们旁征博引，无所不知，从国际政治讲到国内形势，最后归于两点：第一，所有坏事，都是国际敌对势力故意针对中国搞出来的；第二，所有好事，都是中国政府巧妙安排的。总而言之，中央正在跟美国下一盘很大的棋。

近代著名儿童心理学家让·皮亚杰（Jean Piaget）说[7]，在儿童成长的某个阶段，他的世界观会有两个基本点。一个是“animism”，万物有灵。他认为每个物体都是活的，比如汽车之所以不走是因为它累了需要休息。更重要的是，任何东西都有它自己的意愿，比如“太阳在跟着我们走”。另一个是“artificialism”，人为主义。小孩认为一切东西都是人出于某种目的造出来的。比如为什么会有太阳？太阳是人用火柴造出来照亮用的。

最后让我把本文开头的笑话讲完。  有一个人站起来叫道，“G-6！”，这时每一个人都捧腹大笑起来。这个客人问究竟是什么笑话如此可笑。他朋友答道：“哦，这是乔·史蒙，他笨透了，他还不知道根本没有G-6这种类型的笑话呢！”  因为一个人说错编号而引发的笑话本身必然也在笑话俱乐部的数据库中，但是亲眼目睹一个笑话发生还是值得捧腹大笑一次——说明就算所有桥段都已经被发明了，商业片仍然可以拍得很好看。有了各种库函数，编程是如此的简单，以至于高中生也会写程序，可是最好的程序员仍然可以把编程从技术上升到艺术的境界。

五年收入换一年生命，这就是墨西哥妓女健康风险的价值。也许很多人会认为这个交易根本不值，但中国煤矿工人很可能还拿不到这个价。所谓“健康无价”，其实是不可能的。我们每一次出行都冒着交通事故的风险，但我们还是决定冒这个险。所以对待健康和工作的正确态度，不是一味地强调某一端，而是需要根据自己的情况合理计算。

经济学大概解释不了邓稼先和蒂尔曼的行为，而且也不是所有东西都可以用钱来衡量。但不管算什么，大多数人的大多数工作是做了计算的。有人参加美军去伊拉克服役只不过为了一家人的医疗保险。日本核泄漏事故，前往清理福岛核电站的全部志愿者的年龄都超过60岁。人们把这些志愿者视为英雄，他们的确是英雄，但他们是有理性的英雄。据一个志愿者跟记者说[8]，他们的决定不是出于勇敢，而是出于逻辑：“我今年72岁，大概还有十几年的寿命。而就算被辐射了，也需要至少二三十年才能形成癌症。所以我们这些年长的人得癌症的可能性更小。”

在最坏的情况下，哪怕有一帮科学家彻底疯了，要自爆核电站以报复人类，核电站也不会像原子弹一样爆炸。你可能会获得一次常规当量的爆炸，像动作电影里那样，几个房子被炸毁，但绝不是原子弹。因为原材料纯度远远不够。这个知识是容易理解的，如果核爆炸这么容易，某些国家早就有核武器了。事实上，维持核电站反应堆中的链式反应是很不容易的，以至于如果失控，链式反应会立即停止。燃料会继续变热，像日本这样需要灌水冷却，但这种变热不是链式反应，也就是说哪怕你不管了，让燃料自己慢慢冷却，它也不会发生核爆。

核电事故的有害性在于辐射。在最坏的情况下核电站的工作人员会因为辐射在几周之内死亡。但这种辐射引起的直接死亡并不影响公众利益，所有工厂的大事故都可能导致工作人员死亡，核电站并不特殊。

国家标准其实是个人治标准。对于决策者而言，辐射-癌症关系远远比国家标准更有参考价值。因为国家标准的存在，公众得到的是经过封装的科学知识。公众害怕的不是辐射，而是对国家标准的践踏。这正如公众恐惧的不是癌症，而是因为“奇怪”原因导致的癌症。

在科学家看来，乔布斯的个性管理也许根本不值得推广，而扎克伯格的所谓天才霸业，远远比不上一群普通学生在几个月内的整体进步有研究价值。科学家，是励志领域一股拨乱反正的势力。比如著名记者格拉德威尔的《决断2秒间》（Blink）一书曾经被视为新思想的代表，如今在科学家的著作里却经常被当成反面教材引用。

意志力是一种有限的资源，你用在这里就没法用在那里。为什么统计表明总能按时交作业的学生反而经常穿脏袜子？为什么每当期末考试之前学生们更容易吸烟，不注意饮食和个人卫生？因为他们的意志力用在学习上了。如果一个人在工作中用到很多意志力，回家以后就很难再用。双职工夫妇很容易为了小事吵架，因为他们懒得控制自己的情绪。反过来说，如果让他们早点下班，虽然在一起的时间增加了，但是却会更少发生争吵。

真正有效的办法是“常立志”。意志力是一种通用资源，这意味着你可以通过做一些日常小事来提高意志力，然后把它用在其他事情上。本书提出的一个有效的练习办法是做自己不习惯做的事。比如你习惯用右手，你可以有意识地用左手。你还可以强迫自己说的每一句话都必须是书面语的完整句子，而不得出现俚语、省略语和脏话。在一项实验中有三组学生分别想提高自己的学习、省钱和健身能力，结果通过一段时间内在实验室对着屏幕锻炼注意力来提高意志力后，他们不但各自想要提高的能力提高了，而且还顺带提高了其他两个能力。

亚裔靠的是意志力。有实验发现，中国的小孩从两岁开始就比美国的小孩有更强的自控能力。可能是基因的问题，因为中国的多动症儿童比美国少得多。也可能是传统的问题，因为中国的父母更早地要求孩子控制大小便。不管是什么，中国文化虽然不怎么擅长科学思维，也不太明白意志力到底是怎么回事，它却在意志力的实践上遥遥领先。这难道不是我们的优势吗？那些全神贯注听讲的小孩，比每隔三分钟就得吃点零食的小孩酷多了。

格拉德威尔说，想要战胜歌利亚，关键在于两点。  第一，你要知道你的不利条件，在某些情况下可能是你的有利条件；而巨人的所谓有利条件，在某些情况下可能是他的不利条件。 第二，你绝对不能按照对手的打法去跟他玩，你有时候得使用非常规手段。

这套统一的练习方法，就是“刻意练习（deliberate practice）”。首次提出“刻意练习”这个概念的是佛罗里达大学心理学家安德斯·埃里克森（K. Anders Ericsson）[4]，此后，不同研究者和作者对“刻意练习”的具体内容有各种解读。这里我把我所了解的内容综合起来，去除一些不重要的，总结成以下四点：  1．只在“学习区”练习； 2．把要训练的内容分成有针对性的小块，对每一个小块进行重复练习； 3．在整个练习过程中，随时能获得有效的反馈； 4．练习时注意力必须高度集中。

我不太赞同这种凡事往特别简单或者往特别复杂了说的思维。首先，干事业不是靠拼命就行，不但证明数学定理不是拼命得出的，就连打仗也不是仅靠拼命就能取胜的。其次，干事业就是干事业：想去世界杯赢两场球，你研究足球就可以了，没必要先把官场文化和春秋以来的儒家思想都研究、批判和改造一遍。

如果你想成为一个科学家，你就应该好好学习基础知识，掌握基本技能，比如算算微积分，写写计算机程序，然后尽快找到一个好的导师，在他的指导下，从学徒开始做，做真正的科学研究。如果有一个人，认为搞科研“功夫在诗外”，一天到晚研读牛顿等古代科学家的传记，给古今中外的科学家搞排行榜，在博客上写好多科学家的趣闻轶事，跟伪科学和民间科学家作斗争，甚至希望通过研读西方近代哲学和中国古代哲学，提升自己的人文素养这样的办法去学习搞科研，那就是缘木求鱼了。

科学家们考察花样滑冰运动员的训练，发现在同样的练习时间内，普通的运动员更喜欢练自己早已掌握了的动作，而顶尖运动员则更多地练习各种高难度的跳跃动作；普通爱好者打高尔夫球纯粹是为了享受打球的过程，而职业运动员则在各种极端不舒服的位置打不好打的球。真正的练习不是为了完成运动量，练习的精髓是要持续地做自己做不好的事。

只在学习区练习，这很难。学校里的教学往往是几十人按照相同的进度学习知识，这种学习是没有针对性的。同样的内容，对某些同学来说是舒适区，根本无须再练，而对某些学生则是恐慌区。科学教学必须因材施教，小班学习，甚至是一对一的传授。真正的训练与其说是老师教学生，不如说是师傅带学徒。

这种传中方法显然早就已经是运动员的舒适区，可是他还在练！他可能已经能够完成非常准确的传中球，只不过这种机械化的准确就如同有的民间运动员专门练习在无人防守的情况下远距离投篮一样没用。这就是为什么德拉甘在同一篇访谈中说“过于追求单个技术动作的准确性是我看到的最不可取的方式。”

心理学研究认为人的工作能力主要依靠两种记忆力：“短期工作记忆”（short term working memory，有时候也简单地称为“短期记忆”）和“长期工作记忆”（long term working memory）。短期工作记忆有点类似于电脑的内存，是指人脑在同一时刻能够处理的事情的个数——一般来说，我们只能同时应付四个东西，多了就不行了。短期工作记忆与逻辑推理能力、创造性思维有关，换句话说，跟智商非常有关系，它很难通过训练得到提高。

长期工作记忆存储了我们的知识和技能。它有点类似于计算机硬盘，但比硬盘高级得多。关键在于，长期工作记忆并非是杂乱无章、随便存储的，它是以神经网络的形式运作，必须通过训练才能存储，而且具有高度的结构性。心理学家把这种结构称为“块”（chunks）。

人的技能，取决于这两种工作记忆。专家做的事情，就是使用有限的短期工作记忆，去调动自己几乎无限的长期工作记忆。而刻意练习，就是在大脑中建立长期工作记忆的过程。

如此一来，高手与普通人就有了本质的区别。高手拥有长期训练获得的特殊神经脑结构，他的一举一动可能都带着不一般气质，连眼神都与众不同，简直是用特殊材料制成的人。练习，是对人体的改造。

再牛的科学家，也需要同行评议，这就正如世界排名第一的网球运动员也需要教练一样。反馈者不见得比你的水平高，关键是他们不是你，他们可以从你看不到的角度看你。

刻意练习不好玩。它要求练习者调动大量的身体和精神资源，全力投入。如果你觉得你在享受练习的过程，那你就不是刻意练习。找一本小说边喝咖啡边看，在一个空闲的下午打场球，这样的活动都非常令人愉快，但是做得再多也不会提高技艺。很多人每周都打一场网球或者高尔夫，打了25年也没成为高手，因为他们不是在刻意练习，他们是享受打球的乐趣。很多年轻人追求一种散漫的风格，干什么事情都是一副无所谓的态度，认为在打打闹闹中学习的人很酷，这是非常愚蠢的。能够特别专注地干一件事才是最酷的。

《舌尖上的中国》是一部非常成功的纪录片，它之所以成功就是因为它非常符合观众的需求。有一个理论说，观众在看纪录片的时候疲劳周期只有8分钟，所以陈晓卿导演需确保任何一个故事都必须在8分钟内讲完[35]。我们看了《舌尖上的中国》，会对中国的饮食文化产生极大的兴趣和自豪感，但是谁如果说要从这个片中学到什么理论，那就是胡说了。纪录片对科学的作用并不在于让观众学到什么知识，而是激发观众对科学的兴趣。电影和电视是一种很好的激励手段，但不是好的教育手段。

教育哲学家认为获得知识是一件困难的事情，认为其中必然有各种约束的介入。他们认为学习是要付出代价的，耐力和汗水不可少，个人的兴趣要让位于集体的利益。要想获得出色的思辨能力对年轻人来说绝非易事，它是异常艰苦卓绝的斗争．西塞罗说过，教育的目的本来应该是摆脱现实的奴役，而现在的年轻人正竭力做着相反的努力——为了适应现实而改变自己。

花钱收买孩子学习！这对中国人来说未必有多么令人震惊，大概每个家长都用过物质刺激的办法。我和我弟弟小时候如果考得好，父母至少也会奖励一顿好吃的，只不过从来没有这么赤裸裸地直接发钱而已。罗伊·鲍迈斯特（Roy F. Baumeister）和约翰·提尔内（John Tierney）在《意志力》（Willpower）这本书中认为，亚裔家庭的孩子之所以意志力更强，跟家长给的奖励制度很有关系。其他族裔的家长给孩子买东西往往是兴之所至，或者过生日的时候买。而亚洲家长往往对孩子有清晰的目标：你必须完成这个目标才能获得奖励。比如一个韩国人的两个女儿如果在超市柜台要巧克力，家长就会借机要求她们在一周之内看完一本书，如果能做到这一点，那么在下次来超市的时候就可以买巧克力了。想要车可以，但不马上买，必须考进医学院才给买。

对这些奖励办法的批评是：“要我练”怎么也比不上“我要练”。但我所见到的与刻意练习有关的理论并不区分“要我练”和“我要练”，你只要按要求练了就行。无论如何，设定一个具体的阶段性目标并且按照这个目标努力不失为一个好办法。有了目标就有了参照物，你就可以自己监督自己，甚至让别人监督自己。

我们的社会就是这样，如果一个人说他苦练是为了出人头地，记者们就会鄙视他；如果他说苦练仅仅是为了兴趣，记者们就会仰慕他。但兴趣是真的。有的孩子似乎天生就对某一领域感兴趣，别人觉得很枯燥的活动，他们乐此不疲。就算明知干这个不能带来金钱和荣誉，他们还是愿意干。他们觉得干这个是他们生活的一部分，甚至这就是他们生活的目的。“感兴趣”当然并不一定说明他能做好，就算不感兴趣只要愿意练，也能练成。兴趣最大的作用是让人自己愿意在这个领域内苦练。 学习一个技能的初期，智商可能是决定性因素。但是随着学习的深入，兴趣的作用可能就越来越大了，因为兴趣可以在相当大的程度上决定谁能坚持下来。

在《费曼物理讲义》这本当初加州理工学院的物理教科书中专门有一小节，叫做《相对论与哲学家》。费曼说，相对论流行以后，很多哲学家跳出来说“坐标系是相对的，这难道不是最自然的哲学要求吗？这个我们早就知道了！”可是如果你告诉他们光速在所有坐标系下不变，他们就会目瞪口呆。所以真正的科学家其实比“想象家”更有想象力。一个理论物理学家可能每天都有无数个怪异的想法，真正的困难不是产生“怪异”的想法，而是产生“对”的想法。

现在已经没人能看完《战争与和平》了。高质量的读书要把自己沉浸在书中，有的地方反复看，甚至还要记笔记。这种读法似乎有点丧失自我，好像成了书本的奴隶。而上网则是一个居高临下的姿态，我们游离在内容之外，面对众多等着被“临幸”的超链接想点哪篇随心所欲。可是在尼古拉斯·卡尔（Nicholas Carr）的《浅薄》（The Shallows）这本书看来，上网者才是真正的奴隶。相对于读书，网络阅读使我们能记住的信息更少，理解力和创造力下降，形成不了知识体系：互联网把我们的大脑变浅薄了。

更进一步，卡尔认为谷歌正在把互联网向更肤浅推动。YouTube这样的业务对谷歌来说只是为了给搜索引擎带来流量，收集信息，以及排挤潜在的竞争对手，对公司利润几乎没有贡献。谷歌的真正业务是搜索，利润的绝对大头是广告。一个盯着屏幕看的用户不会给它带来任何广告收入，你必须不停地搜索和点击。正如其用户体验设计师艾琳尼·奥（Irene Au）所言，谷歌的核心战略就是让用户快来快走，它做的一切都是为这个战略服务。对谷歌来说，短而新的信息可以带来更多点击，价值远远超过经典长篇大论，它把所有书籍上网，正是把整体的书变成一堆可搜索的短信息的集合。

哪种人最善于对信息定制、整理和排序？有自闭症倾向的人。自闭症患者往往因为大脑的缺陷而缺少对情感交流的解读能力。对人情的不解反而使他们的思想保持冷静客观。他们把更多的精力投入到对特定信息的收集、整理、分类和记忆中，是最极端的信息爱好者。也许自闭症者不怎么了解自己的邻居，但他们往往对某个特定领域了如指掌。一个小男孩爱好火车时刻表，他可以整日在网上看时刻表。

知识是有等级的。八卦新闻、实效性强的信息、网友对时局的看法，本来就不值得印在纸上浪费树木，在网上看看正好。扫读网页不见得是什么毛病，相反，能够以不同速度读不同等级的内容是最有用的阅读技术。 上网的关键态度是要成为网络的主人，而不做各种超链接的奴隶。高效率的上网应该像自闭症患者一样具有很强的目的性，以我为主，不被无关信息左右。就算是纯粹为了娱乐上网也无可厚非，这时候读得快就是优点。一个真正的智者不会让上网占用读书时间，他应该经常能够平静地深入思考，只有电话接线员才随叫随到。

上网的关键态度是要成为网络的主人，而不做各种超链接的奴隶。高效率的上网应该像自闭症患者一样具有很强的目的性，以我为主，不被无关信息左右。就算是纯粹为了娱乐上网也无可厚非，这时候读得快就是优点。一个真正的智者不会让上网占用读书时间，他应该经常能够平静地深入思考，只有电话接线员才随叫随到。 高效“冲浪”的办法 “新闻”是个听起来相当正面的词，看新闻代表关心时事，就好像是个正事儿似的。

这种先集中选择再采取行动的办法并不仅限于新闻阅读，其实有更为广泛的应用。诺贝尔经济学奖得主丹尼尔·卡尼曼在《思考，快与慢》一书中介绍了两个著名的心理学概念：“窄框架”（narrow framing）和“宽框架”（broad framing）。所谓窄框架，就是遇到一个东西做一次决策，一事一议；而宽框架则是把所有东西都摆在桌面上集中选择。

哪怕有一天维基百科、百度知道再加上人工智能可以向我们提供所有问题的答案，它们仍然不能取代人脑中真正的知识。这是因为真正的知识是分层的。你必须完全理解基础的一层，才能谈得上去看懂上面的一层。如果你没学过微积分，就算有人把人类历史上广义相对论的全部文本摆在你面前也没用。知识，不能仅仅机械地“存”在你的脑子里，而必须以一种个性化的结构“长”在你的脑子里。通过个人笔记本来不断总结自己个性化的理解，恰恰可以帮助我们“长”知识。

真正的专家，都有自己的一整套知识体系。这套体系就如同长在他们心中的一棵不断生枝长叶的树，又如同一张随时变大变复杂的网。每当有新的知识进来，他们都知道该把这个知识放到体系的什么位置上去。有人管这套体系叫做心智模式（mental model），有人管它叫矩阵（matrix）。有了这套体系，你才可能对相关事务作出出神入化的“眨眼判断”，而不是靠什么“灵感”或者“直觉”。

而创业者最重要的一个素质，恰恰是明知道很可能失败却还要干。这帮人之所以成功不是因为他们善于计算概率，而是因为他们过度自信。

如此算来，这个世界属于爱冒险的人，它的运行规律是撑死胆大的饿死胆小的。那些过度自信的人失败的次数也会比一般人更多，如果要死的话也会死得非常快，但只要他们没死，只要他们还在继续尝试，那么他们最终成功的可能性要比一般人大得多。

男孩什么都想竞争，每时每刻都想跟人比，而且还过度自信。上一所好大学之前，女孩能清楚地估计到自己面对这么多好学生将不会具备什么优势，所以在大学遇到困难时能主动去寻求帮助，并且会得到帮助。而男孩从来没想过自己会输。如果输了他也不会去寻求帮助，他会拒绝承认自己输了，实在不行就干脆放弃这个项目。

男人在决定参与竞争之前并不在乎失败的风险，可是竞争中一旦遇到挫折就容易放弃。女人却总能合理评估竞争风险，一般不爱竞争，但是一旦参与了，就算遇到挫折也常常能坚持下来。 这样看来男人的竞争模式似乎比较愚蠢……但真实世界不只是大学生考研。过度自信和敢出手恰恰是男人的优势。

达到这个境界的玩家把玩游戏变成了一个体育运动，甚至是一项科学研究。他们可以反复打某个单机游戏中的同一张地图而不觉枯燥，因为他们追求的不是简单的快感，而是更高的技艺水平，是艺术。他们仿佛在游戏之中，又好像在游戏之外。

所有人都喜欢强联系，哪怕是风险投资者和斯坦福MBA也是如此。我们愿意跟他们混在一起，我们愿意给他们打电话，我们愿意转发他们的微博。但是熟归熟，工作归工作。当我们考虑找人创业，找人合作，哪怕是找人了解什么信息的时候，“弱联系”才是最佳选择。现在社会学已经有了足够多的证据说明，对工作来说，同乡会和校友录不是扩展人脉的好地方。

科学知识是一种高度结构化的知识，其有一个很酷的性质：只要学会了一般原理，就能解决无穷多表面看来千奇百怪的问题。掌握科学知识的人可以一听你的问题，不必亲临现场，完全凭借逻辑推理就能告诉你答案。有时候他们推理出来的答案可能出乎意料甚至违反常识，然而你却不得不服。

这个世界比绝大多数人的想象要复杂得多，我们对它所知甚少。我们不但不知道宇宙为什么会加速膨胀，甚至不知道小鸟为什么一边走路一边点头。与宇宙问题不同的是小鸟的问题就算将来得到确定的答案，这个答案恐怕也不会向我们揭示有关世界的什么重大秘密。但是“尚无答案”这个情状本身，已经足够让人感到安慰了。试想要是不管谁提个什么问题，你都明确知道尽管你不能解答，维基百科上却总有现成的答案，这样没有悬念的世界岂不是毫无乐趣可言。我们仍然幸运地生活在剥个鸡蛋都能写篇论文的时代。这个世界仍然在等着被破解。

判断一个物理理论的好坏不在于这个理论是否符合人的直觉，或者是否够漂亮，而在于它能不能做出预言。

正如量子力学中的一个粒子可以有多种不同的状态，创世之后也可以产生多种不同类型的宇宙状态。每一个可能的宇宙中都有自己的一套物理定律和物理常数，我们只不过恰好生活在其中一个允许星系和人类出现的宇宙中而已。这个道理就如同既然有非常多的行星系统存在，我们恰好得到一个适合人类生存的地球就并不奇怪。

在医学界和心理学界，如果科学家想要研究某个因素对人的影响，比如吸烟是否有害健康或者受虐待儿童长大以后是否犯罪率更高之类，往往无法直接做实验，而只能采取搜集案例做统计分析的办法，这个方法称为“流行病学（epidemiology）”。流行病学的结果远远不能作为最后的科学结论，但是这个方法仍然是科学的方法，也可以说是在你没有别的办法的时候所能使用的最科学办法。

不管调查到什么程度，都只是对真实世界的管中窥豹。科学研究的是有限的真理。当一篇论文说什么东西可能或者不可能导致什么疾病的时候，它说的其实是在这次研究所调查的这帮人里面有这么一个结论。这个结论能推广到所有人群吗？记者一定比科学家更乐观。

把学术论文的结论推广为真实世界的真理，有时候是非常危险的事情。因为不理解科学研究的思维方式，导致大多数人对科学有两个重大误解：第一，认为科学研究绝对真理；第二，认为每一项科研都是在生产我们日常决策的答案。真实的科学研究其实是一个充满曲折，甚至有时候错进错出的过程。

-----

据说是斯大林说的，“杀死一个人是悲剧，杀死一万个人是统计数字”。这个捐款实验证明，统计数字的力量远远比不上一个人，一个具体的人。受试者对远在天边的国家的抽象数字没有多大兴趣，而他们对一个具体人物——哪怕仅仅听说了她的名字和最简单的背景——则更乐于出手相助。

比如修改新闻标题这件事，从技术角度说并不是网站编辑的选择，而是读者自己的选择。很多新闻网站，比如赫芬顿邮报（The Huffington Post），使用一个叫做多变量测试（multivariate testing，也叫A/B testing）的技术：在一篇文章刚贴出来的时候，读者打开网站首页看到的是随机显示的这篇文章的两个不同标题之一，网站会在五分钟内判断哪个标题获得的点击率更高，然后就统一使用这个标题。事实证明在读者的选择下最后胜出的标题都是耸人听闻型的。

也许因为手机已经买了或者政治态度已经表过了，人们为了付出的沉没成本而不得不死命拥护自己的派别，也许是为了表明自己的身份，也许是为了寻找一种归属感。但不管是什么，这种阵营划分肯定不是个人科学推理的结果。

甚至认为人的逻辑推理能力本来就不是用来追求真理的，而是用来说服别人的。也就是说我们天生就都是律师思维，我们的大脑本来就是个争论设备。这也许是因为进化总是奖励那些能说服别人的人，而不是那些能发现真理的人吧。

诺贝尔奖得主罗伯特·奥曼（Robert Aumann）在1976年发表了一篇论文Agreeing to Disagree，这篇论文堪称是传世之作，它指出，如果是两个理性而真诚的真理追求者争论问题，争论的结果必然是两人达成一致。换句话说如果争论不欢而散，那么其中必然有一方是虚伪的。

本能归本能，有些人可以超越自己的本能。他们知道自己强烈的负面情绪会带来偏见，所以他们不轻易纵容这种情绪。他们看到好的冒险机会敢上，遭遇损失却不放在心上。他们看到好人好事主动夸，听说坏消息却能够保持淡定。

人在复杂的现代社会中运动，很大程度上类似于原子在电磁场中运动，个人意愿能改变的事情很少，绝大多数人都是在随波逐流。但即使所有人都随波逐流，复杂的系统也会出现非常激烈的“事件”。有人用计算机模拟发现，哪怕没有任何消息输入，仅仅是交易者之间的简单互动，也可能让股价产生很大的波动。这些波动发生就发生了，并没有什么目的。每一次金融危机都会有阴谋论者站出来说这是谁谁为了某个目的故意制造的，但事实上，美联储对金融市场的控制手段非常有限。在正经的经济学家看来，把1997年亚洲金融危机归罪于索罗斯是非常可笑的事情。

不但大学生如此，在职场上也是自控能力强的人更受欢迎。他们不仅工作干得好，而且更善于控制自己的感情，更能从别人的角度思考，更不容易出现偏执和抑郁之类的心理问题。研究者普遍认为，排除智力因素，不管你心目中的成功是个人成就、家庭幸福还是人际关系，最能决定成功的只有自控。

格拉德威尔说，一般有创造性的人物，都要有点特立独行（disagreeableness）的气质：你要敢于做一些社会上通常认为不应该做的事。你不是去适应这个社会，而是让这个社会去适应你。他们追求取胜，他们根本不追求别人的喜欢。 维护现有的社会格局和强调遵守游戏规则，那是高富帅的事。而改变规则则是屌丝的特权。

在体育和音乐训练中，比较强调“分块”练习。首先你要把整个动作或者整首曲子过一遍，然后把它分解为很多小块，一块一块地反复练习。在这种训练中一定要慢，只有慢下来才能感知技能的内部结构，注意到自己的错误。《天才密码》一书介绍，美国最好的一所音乐学校里的一位老师甚至干脆禁止学生把一支曲子连贯地演奏。学生只能跟着她练分块的小段。她规定如果别人听出来你拉的是什么曲子，那就说明你没有正确地在练习！

搞科研的最好办法是尽快找个实验室进去跟着开干。先做一些处理数据之类的打杂的事，给导师和师兄当个学徒，慢慢耳濡目染之下，自己就会知道怎么做研究了。毛泽东说在战争中学习战争，解放军很多高级将领文化程度一般，为什么总能打胜仗，靠的就是在实践中学习。学习知识不是为了考试，不是为了耍酷，不是为了有谈资，是为了用！对比之下，美国大学里面的理工科课程就非常注重联系实际，在考试和作业之外特别强调做项目。一学期让学生做好几个有实战意义的项目，追求学以致用，逼着学生为了完成项目而学习知识。这些项目往往需要学生组成小组合作完成，比如分工编程组装一个机器人，其需要调用的知识并不限于课堂讲过的，跟真正的科研没什么区别。

一个动作做得好与不好，最好有教练随时指出，本人必须能够随时了解练习结果。看不到结果的练习等于没有练习：如果只是应付了事，你不但不会变好，而且会对好坏不再关心。在某种程度上，刻意练习是以错误为中心的练习。练习者必须要对错误极度敏感，一旦发现自己错了就会感到非常不舒服，一直练习到改正为止。

我认为真正的人才不是靠课程、院系、考试大纲的设置培养出来的。培养人才的有效办法只有一个，那就是学徒制。师父带着徒弟参与一个实际的项目，徒弟在试错中提高。不管是科研、工程还是艺术，都是如此。一个教育体制的关键不在于往学校里投入多少钱，而在于其是否提供了足够多、足够好的动手机会。

被难题缠身的菜鸟员工，惶恐不安的无名小辈，他们在贝尔都有自己的导师，这些导师可都与那些“写书人”和大牛一起工作，关系密切．一些贝尔实验室的新员工往往对此感到震撼，因为他们被告知可以向著名的数学家，诸如Claude Shannon，或者传奇物理学家William Shockley直接提出自己的疑问。而且，贝尔实验室的策略是，大牛们不允许回避菜鸟们提出的问题。

有个著名的小提琴家说过，如果你是练习手指，你可以练一整天；可是如果你是练习脑子，你每天能练2个小时就不错了。高手的练习每次最多1～1.5小时，每天最多4～5小时。没人受得了更多。女球迷们可能认为像贝克汉姆那样的球星整天就知道耍酷，她们不知道的是很少有球员能完成贝克汉姆的训练强度，因为太苦了。

如果你想学点知识，最好的办法是找本书——最好是正规的教科书或者专业著作——然后老老实实地找个没有人的地方坐下反复读，而且还要自己整理笔记，甚至做习题获得反馈。如果你坚持不了8分钟，你不适合学这个。 练习需要重复，而重复一定不好玩。教育需要全面，而娱乐一定只关注其中好玩的部分。所以娱乐跟学习必然是不相容的，如果你是在娱乐，你就不是在学习。你可以用娱乐的手段号召人去学习，但娱乐本身绝对不是学习。

世界并不需要一千个钢琴大师或者一万个足球明星，这些少数的幸运儿已经把所有位置都占满了。如果你想享受快乐童年，你的位置在观众席。

当时场上的九个球员都在“例行公事”，而有一个孩子却在全力以赴。看他打得那么拼命，我以为他的球队正以1分落后，而比赛还有两分钟结束。然后我看了一眼记分牌，现在他的球队落后20分，而比赛还剩一分钟！ 乔丹在整个职业生涯都是所有球员中最想赢球的，他总是有极强的目的性，永远都想改进自己的技术弱点。他对赢球是如此渴望，以至于他会骂那些不努力的队友，公牛队的新秀在第一年时往往都会抱怨受不了乔丹的骂。

所以，一个人爱好什么，喜欢干什么，能死心塌地地在什么方向上刻意练习，基本上是天生的。 人并不仅仅被动地等着被环境改变，有一个理论认为，自然选择给了每个人不同的基因，而人可以出去寻找自己的基因所喜欢的环境，也就是那些能给我们“自私的基因”提供最大的生存和复制机会的环境。基因决定喜好，喜好决定我们追求什么。


好书之所以要读两遍，最重要的目的就是为了这些心得、灵感和联系。对一本讲我们不太熟悉的领域的书，在第一次读的时候，我们往往会陷入作者的思想之中，我们大脑的全部带宽都被用于理解作者的思想，而没有更多的余地去产生别的想法了。“幽默是智力过剩的体现”，想法也只在带宽过剩的时候才会冒出来。只有当你读第二遍的时候，你才能气定神闲地发表意见。第一遍读是为了陷进去，第二遍读是为了跳出来。

世界上有很多比读书重要的事。在做事和读书之间，做事优先。但读书是除实践外迅速积累见识的最好办法。在电视出现以前，人们无事可做的时候最主要的活动就是读书。现代人因为有洗衣机、洗碗机这些自动化设备，每天空闲时间比过去多得多，可是人们把大部分认知剩余都奉献给电视了。而电视这个东西从根本上就是面向尽可能多的大众的，就如同广场上的集体舞。读书人不屑于广场舞，我们追求的是武功。

如果你是一个有心的领导者，你每时每刻都能接触到各种号称可以改变世界，至少可以改变你们公司的“新思想”。这些思想逻辑上都无懈可击，但实施的过程是有风险的。上面的两个故事中的新思想都要求对企业运行方式做一次彻底的改革。企业不能每年都搞一次这种彻底改革。对于领先的企业，更没有必要冒这种风险。谚语说，If it works, don't fix it！ 只有落后者，光脚不怕穿鞋的，反而可以冒这个险。冒险至少还有赢的机会，不冒险就输定了。 这就是为什么本文不说创新是落后者的“权利”，而说，创新是落后者的“特权”。

人生面临着一个风险悖论。如果你一辈子谨慎小心，干什么事情都谋定而后动，你的生活再差也差不到哪去；而如果你勇于承担风险、大胆尝试，你可能会特别失败，但也可能特别成功。那么平均而言，我们到底应该更冒险一点好，还是更谨慎一点好呢？ 根据2011年发表在《自然》上的一篇论文，答案是冒险更好。生活中有自信和不自信的人，还有一种过度自信的人，他们过高估计了自己的能力，尝试去干一些比他们水平高的人都不敢干的事情，而这种人却往往能够侥幸成功。而且平均而言，他们比能正确评估自己能力的人更成功。

打赢一场仗，经验值立即上升，战利品立即到手。这个规则看似简单，在现实生活中却是非常少见的。即时的回报会给做事的人一个正反馈，使他更投入地继续工作，这种正反馈一旦运行起来，只有人的生理极限才能限制他的工作强度。我们经常看到一个政府职员在上班时间悠闲地看报纸，而一个小商贩却可能在工资更低的情况下拼命地加班加点，其根本的技术原因是这个小商贩的每一个动作都可立即转化为收益。即时正反馈，就是游戏上瘾动力学。

“弱联系”的真正意义是把不同的社交圈子连接起来，从圈外给你提供有用的信息。根据弱联系理论，一个人在社会上获得机会的多少，与他的社交网络结构很有关系。如果你只跟亲朋好友交往，或者认识的人都是与自己的背景类似的人，那么你大概就不如那些什么人都认识的人机会多。人脉的关键不在于你融入了哪个圈子，而在于你能接触多少圈外的人。这样来说，岂不是从一个人的社交网络结构，就能判断这个人的经济地位如何了吗？

看来经常出去参加饭局的确比在家待着强，但是那些连饭局都不参加的创业者有可能更强。现在我们再考虑公司开起来以后的信息来源。如果你在创业过程中的信息网络主要由弱联系构成，你的创新能力是那些指望强联系的公司的1.36倍。而如果你干脆不靠熟人，直接从媒体和不认识的专家那里获得信息，你的创新能力则是强联系公司的1.5倍。而从社交网络来看，跟前面的数据的结果一致，你的社交网络越多样化，你的创新能力就越强。那些拥有极度多样化社交网络的企业家，他们既有强联系也有弱联系，还接受从未打过交道的人的意见，其创新能力是那些只有单一社交网络的人的3倍。

更大的困难在于，大多数情况下你不能拿人做试验，比如不能逼人吸烟。这时候就只能被动地集邮，而通过纯粹的被动调查来做研究的方法叫做流行病学（epidemiology）。最容易的流行病学研究是所谓回顾性（retrospective）的问卷调查：先找到病人，然后询问并比较他们的生活方式。这种调查的难度在于病人对自己以往生活的回忆常常不准确，甚至是有偏见的。他们可能会自己推断出一种病因，然后刻意地强调这种病因。

一个更可靠的办法是前瞻性（prospective）调查。比如说科学家想知道核辐射对人体的损害，现在日本地震导致核泄漏之后哪些地区的哪些人受到了辐射是非常明确的，根本不用对他们进行问卷调查，自然也就没有偏见。有了干净的初始数据，科学家只要长期跟踪这些被打了核辐射标签的人群，再跟正常人对比，就可以知道辐射对人体的影响。可是这里的困难就在于“长期”，核辐射的影响也许几十年才能看出来，那时候也许病人还没死科学家已经先死了。

如果这条新闻说的是医学研究，那么最理性的选择是……（d），别当真。那些写在晚报副刊上的各种所谓健康指南，连看都别看。而那些刊登在主流媒体上，有最新的论文支持的科学新闻，比如说英国某个团队又发现什么东西对儿童的智力有新影响，我们大概可以看，但是看完就可以直接把它忘了。
