#+title: 宝宝出生了2

@2019-12-11 两次突破预期的生产

在家陪了快半个月的产假，加上生之前在家准备生陪了一个月，这次加起来一共在家窝了快一个半月了。今天来上班，感觉还是比在家里要轻松不少，至少她们没有办法使唤我做事情了。

这次生的也还算是比较顺利。因为大宝是在37周出来的，所以以为二宝会在37周左右的时候出来，心理预期就定在了37周。但是到了37周，什么事情都没有发生，看上去也没有发动的迹象，一天一天下来，警惕性就有所放松。

11.14号早上大约4：30的样子，老婆突然叫我起来，说羊水破了。这个把我吓了一大跳，之前还没有做过这种生产的预案。而且昨天早上我们刚去过医院做胎心监护，觉得可能会拖到39周打催产，所以更觉得会几天之后生。之前听说过很多因为羊水耗尽胎儿死在腹中的故事，那些故事在这个时候一股脑儿都进入了我的大脑。

经过几秒钟的调整，冷静下来，把另外一个屋子的老姑和大姑叫醒，让她们给老婆转衣服，我则跑出去开车进小区接她医院。因为车停在小区外面，平时走过去至少要10分钟，那天早上我是一直小跑，估计大约5分钟跑到了吧，中间没有停下来过，这个还得益于之前每周都要跑步一次。把车开进小区，她们也帮老婆穿好了衣服，虽然我平时能抱动她，但是现在她肚子里还有10多斤的小家伙，抱起来还是略微费劲，不过最终还是上车了。看了一下时间，正好是5点从家里出发。

这里顺便提两个需要注意的事情。一个是在生产前一定要把生产包都准备好，可以的话尽可能都放在车上，这样不至于突发事情的时候手忙搅乱。哪些事情可以预先准备好，就一定要预先准备好。另外一个就是，羊水破了不要惊慌，只要平躺就不容易流出来，有足够的时间去医院。（这点我之前是不知道的，老婆上车了才和我说，平躺时基本不流）

早上车很少，开到医院也有很多停车位，这就是早上生产的好处，避开高峰和排队停车。5：00出发，5：20就开到了医院，然后就进入急症室做个简单的B超，接着就是办理住院手续。在病房里面安顿下来的时候，已经差不多是6：30了。

然而虽然羊水破了，但是宝宝依然没有发动的意思。早上8：00左右主治医生过来看了一下情况，简单地检查了一下胎心和宫缩压以及血糖之后，9：30就开始注射催产针了。这个时候老婆已经是38+5天了，可以打催产针了。老婆之前也说过她单位好几个人打催产针，有些人一会就下来了，有些人等了好几天最后还是剖了，所以她让我有心理预期，最坏情况会在医院待好几天。

有了这个预期，我觉得至少要到今天下午吧，就下楼去便利蜂买咖啡了。刚下楼还没有多久，她就和我说让我不要走远，感觉现在肚子一阵阵地疼了，我便赶紧上楼。到了病房，她已经自己开始记录疼痛的间隔了，10：30，10：35，10：40：，10：45，10：45，10：50. 感觉这个时间是越来越密集了，叫赶紧叫护士过来看看。

因为我10：40叫了一次，等到10：50叫的时候，这个护士已经有点不耐烦了，也可能是她见多了这种事情，觉得我们是大惊小怪。可是经过她简单的观测之后，发现老婆肚子好像起伏比较大，赶紧把催产针的速率调小，来医生过来处理。本还想让医生确认一下宫缩压，医生说不用了，她已经可以摸到小孩头部胎毛了。这个时候我看到，我老婆基本是大小便失禁了，屎全拉了出来，应该是没有力气控制住肛门了。我们赶紧把床推到产房那边，期间医生不断地叫老婆，加紧双腿不要拉出来。我的理解是，如果这个时候拉出来，那小孩就直接生在了楼道里，没有办法做接下来的处理了。

11：02推进去的，11：28就生了，这个速度也是够快的。在产房里面观察了2个小时之后，就推到了病房休息了。本以为至少要晚上才能生的，下午1：28就搞定了。这个节奏和 [[file:have-a-baby.org][大宝]] 也是差不多的。也是他运气比较好，这次正好有个VIP病房空出来了，我们就住进去了，不然还要挤在3人一间的房子，也是够受罪的。

关于名字嘛，中间的字还是希望和大哥一样，叫“钰”。大宝五行什么都不缺，二宝则缺金和土。因为“钰"里面有了”金“，那只要有”土“就行。然后这个字最好还和大宝的“骐”一个笔画数（11），好几个字供选择 “培，隆，帷，堃”。
