#+title: 住房
** 租房注意事项
+在北京也算是租过一些房子吧，写写注意事项以后可能在天津租房子用得上。+

*合同*

首先租房子尽可能找中介吧，而且一定要找大中介，一定要签订合同。因为自己找房子一方面没有信息，另外一方面没有第三方介入比较容易出现纠纷问题。然后签订合同的时候一定要让业主本人亲自来，看他们的房本以及身份证。然后确定抵押和实际费用，付款日期是什么时候，确认一下房子中现有的财产，以及出了问题之后如何解决和赔偿（比如煤气管道坏了或者是暖气不暖了，可以的话房东都帮搞好），具体的这些规定都应该写入合同里面。最后一定一定要看看房东人如何。因为我遇到过一个很小气的房东，我老婆也遇到过一个很蛮横的房东，住起来都很憋屈，很短的时间又换了一家。

*交通*

临近城铁最好，但是一般较贵。最好到实地看看，比如霍营这个地方，虽然看上去离城铁很近，但是去城铁需要绕道而行，要不就走非常危险的小坡，一般都要花上30分钟，所以一定需要看好。如果是公交车的话，需要实际乘坐一下，看看去单位的车是否多，是否会有很堵的地方。然后也看看出租车是否都愿意去这个地方，这样晚上如果加班的话至少还可以比较方便地打车回去。

*安全*

通常来说，小区都比较安全。主要是看看防盗门，门禁，还有是否有值班的人，晚上楼道是否灯光明亮。除了看小区本身，还需要看看小区周围是否安全，这个才是最重要的。所以安全这个问题最好是晚上去实际看看会比较好，或者是问问看看当地人的生活习惯（一般从他们生活习惯就可以看得出来）。

*设施*

一个是外部设施，包括饮食，超市，药店，诊所这些是否都有以及是是不远，以及看看他们的经营时间，如果一旦很早关门就悲剧了。个人在北京住的地方都比较晚关门，饮食可能到12:00都还生意很火，超市大部分9:00以后，药店也早11:00以后。另外一个就是内部设施，比如楼层高不高，如果是电梯房的话，看看楼道是否通常，楼道是否灯光明亮（因为电梯房如果停电就悲剧了）。还有看看房间采光如何，曾经在立水桥看到一个房子业主宣称两室一厅但是另外一室简直就是储藏室，因为房间本身就不是南北通透的。然后看看装修程度如何，洗澡洗衣做饭是否方便，夏天看看是否有空调，冬天看看供暖集体还是自己烧，书桌椅子洗衣机，阳台以及卫生间等。如果楼层高的话看看水和煤气是否上的来。

** 北漂租房经历
*2008.8-2009.1*

这个是在北大南门面前的一个小区。当时第一次去百度实习，而且身上也没有什么钱，所以麻烦在北京的同学tp / tangpeng(大学认识，一直到现在都应该是最好的朋友，check him out http://blog.kwkwkw.info/ ）帮我找了一个房子。房租400，租的是床位，有一个小隔间，里面住了4个人，外面住了6个人，我和6个人住在一起，就在那里碰到了叶伟民(当时是一个外包项目主要负责人，现在他应该去silicon valley了吧）。房东应该是租一个大房间然后转租的。400块基本上全包了，偶尔需要交少量水费电费。因为那里全是考研的人，而且人也多，所以费用就还好。房东也非常客气，选择押一付三的方式付款。回想起来当时的生活，真的就是两点一线。只是当时自己情感不那么丰富，也没有多想所以觉得一切都很好。那年我10月份我买了一个PSP:).

*2009.10-2009.12*

之前会学校写论文，所以中途实习断了。2009.10又来这里实习，同样时间比较仓促，就还是租了之前同样的房子。但是因为公司2009.11月搬迁到西二旗了，从中关村到西二旗每天大概需要单程1个小时，非常耗，所以12月份换了房子。从上班地到家里有两条路线，一条是13(西二旗)-10(知春路)-4(中关村),或者是13(五道口-西二旗),按后从五道口直接走到中关村。第二种方式时间会比较长，但是允许我晚上11点左右从单位会住的地方，而且还可以稍微走远一点的路锻炼一下：）。

*2009.12-2010.4*

这开始是一个真正意义上的租房。因为公司搬了，所以打算就离公司近的地方租一个房子。就是上地的清上园。当时找房子没有经验，在水木上翻了一下就打了电话，然后听房东说自己老公也是百度工作的，所以感觉还好。而且去看了一下，房间条件都还不错，冬天是集体供暖而且暖气很足。那个房间是1个独立卫生间和一个卧室，1700。当时没有什么金钱概念，想着还在实习就租了。但是后来觉得有很多不方便：
1. 房东和我们一起住，感觉非常不自在。比如做饭都是她做，然后费用平摊等。
2. 房东有点过于计较，只是觉得不太习惯，没有太大影响。
3. 清上园去公司只有333，但是太难等了并且333在某个丁字路口非常堵车。
不过附近其他设施比如药店，超市(超市发），吃饭（赵姐串吧），水果都还齐全，并且人也很多不冷清。

*2010.4-2011.4*

在那里不爽并不是让我搬出来的原因，而是因为在那里认识的一个玩得很好的朋友yulei合约到期了，所以拉上我两人合租。开始尝试自己找，但是发现一天找的人实在是太少了，而且质量也不高。最记得就是霍营附近找的房子，看上去离地铁站很近，但是需要绕一个大圈才能够到，而且霍营那个地方本来管理就不太好。后来干脆找中介了，中介带我们看了几个，当天晚上就找到西北旺镇政府秋露园的房子，两室一居非常干净，而且设备齐全，不是集体供暖自己烧暖气（但是也花不了多少钱）。并且秋露园本身就是一个很好成熟小区，所以设施都非常齐全。价格来说2900，来可以接受。公正地说，租到的房子还是相当不错的。出门就有982和333以及963直接到我们单位附近，不太会堵车，基本上15分钟到，而且982直接到中关村西买东西逛街都很方便。

*2011.4-2012.6*

那个室友在完美工作，原来公司在西二旗和我在一起，但是后来搬到了立水桥南一带。每天上班非常郁闷。而且当时限购令出来，租房价格都在上涨，我在天津买了房子需要钱，所以也想换一个便宜的地方。对于我们来说觉得立水桥这一带还不错，因为找秋露园房子那次也看过这一带，当时觉得也还好，人多而且设施也齐全。13号线在立水桥下，就能够发现一片中介，而且没走多远又一个同一家公司的中介。后来我们选择了我爱我家，在嘉诚花园找到了房子。缺点来说就是有点老，但是住起来还比较舒服，集体供暖，旁边设施还齐全。每天要花10分钟走到城铁，然后20分钟到西二旗，5分钟到公司，还是比较方便的吧。1300.

*2012.6-2013.8*

yulei跳槽公司在五道口一带，公司给租房住在那一带的员工不住1k+，而且他老婆也住在附近所以他就去五道口住了。但是对于像我这样没有补助的人来说那边租房是非常贵的，所以搬到了新龙城这一带了。这边房价还是有点偏贵1700，离公司牡丹园还是有一段距离的大约1hour吧。因为周末都去天津，所以也没有仔细关注过住房本身如何。这个房间是zhujianwei去深圳创业空出来的房子，两个舍友都是原来baidu的同事，所以相处起来还是非常融洽的。房间不算大，但是住起来比较舒服，晚上自己一个人做什么事情也比较安静。交通还算是便利，5min走到地铁站。附近有小的超市，但是感觉里面卖的东西不是很新鲜。

*2013.8-2014.4*

觉得离单位太远，每天上下班都要花1.5个小时左右，所以打算在单位附近找个房子租下来。正好有3个同事在单位附近租了房子，但是其中2个人想打算换房子，所以就商量和剩下的那个同学一起租了。我单位在牡丹园附近，房子在健德门附近的裕中西里小区，走路比较快的话大概20分钟左右就可以到，公交车的话4站地，打车也就是起步价，确实比较近。房子比较老，大约60-70平米，房子租金包括水电暖气下来每个月4300。因为我平时住得比较少，所以就给2100，基本上期间这个房子还是那个同学在用。除了比较近以及安静之外，这个小区还有个好处附近有个公园，早上或者是晚上可以到那里跑步。小区不能说是非常安全。刚去的时候dyy给我留了一样giant自行车，虽然普通但是看上去还行，没到一个月就丢了。丢车这种事情郁闷的不是钱，而是它改变了原本的生活习惯。

和wangyuxi相处的这段时间还是比较愉快的。我自己是一个不太注重生活质量的人，但是yuxi则非常注意生活质量，所以潜移默化地我受了他很多影响。他经常自己做饭做菜吃，周二周四还会去奥体游泳健身。他曾经专门研究和对比过不同空气净化器和过滤PM2.5的口罩，在卧室里放了一台Honeywell空气净化器然后基本上一直开着的，每天上下班都带着totobobo的口罩。我在他的影响下在自己房子里面也搞了一套空气净化器，每天上下班也带着3M/totoobo口罩。这哥们坚持每周二上网去和老鬼英语对话，坚持上Cousera学习课程，经常浏览国外网站了解国外最新新闻和生活状态，并且决定以后的某一天要出国离开这个"切尔诺贝利"。我很是被他的精神感动，在他的鼓舞下我也开始尝试走出去，也上Cousera课程拿证书。不过我贯彻的没有他这么彻底，每天上网看的还是新浪微博而不是twitter, 用百度比用google的次数更多，也没有打算来离开天朝。anyway, it's a really fun experience.

** 买房装修办证
update@2014-11-29: 2011.4买的, 到现在三年多了. 当时没有记下来, 现在也忘得差不多了.

装修房子大概是下面这些事情:
- 验房
  - 墙面是否开裂
  - 水管是否渗水
  - 卫生间防水测试
- 空间改造
  - 做好设计规划
  - 砸墙
- 水电改造
  - 电线有2.5平和4平。大平的电线可以支撑更高的功率，比如厨房（微波炉）和卫生间（浴霸）
  - 卫生间水管一定要走顶上，并且水管走线一定要直。冷热水管必须平行，间隔在10cm左右。
  - 插座需要预先上好在哪些地方留上（或者是移动到什么地方，或者是在哪些地方加上插座），尽可能地确保在墙的四周都有插座。
  - 卫生间靠近地面部分也需要涂料来做防水处理。
  - 水电改造完成之前，最好让师傅出一份图纸表明具体每根水管的位置以及电线的分布，这样避免安装五金或者是以后维修的话碰到这些东西。
- 墙面
  - 先刷腻子，后刷乳胶漆（多乐士）
  - 如果不刷乳胶漆，可以直接贴壁纸
- 吊顶
  - 空间造型
  - 轻钢龙骨
  - 石膏板（可耐福）
- 瓷砖(马可波罗)
  - 客厅，走廊，餐厅以及厨房通铺
  - 瓷砖踢脚线
  - 过门石。最好选择天然石，其次选择石英石，最后选择人造石
  - 人造石相对来说不耐高温，稍微烫点的东西放上容易开裂
  - 卧室和阳台台面
- 地板(大自然)
  - 卧室
  - 木制踢脚线
  - 和过门石部门衔接部分有压条
- 木门
  - 卧室，卫生间
  - 木制包框
- 橱柜(凯斯宝)
  - 石英石台面。上面需要开水槽，水槽安装最好比台面低，这样台面上水就可以直接被抹入水槽
  - 天然气管道不要包起来，不然后续接通天然气的时候，会因为检查管道而被拆除

*办理产权证*

物业会给出一张清单需要携带哪些东西，然后自己去房管局办理，过程比较简单。但是需要注意下面三点：
- 一定确保带好所有材料，东西什么的都提前复印好。
- 一定确保物业提供的材料都盖好了章，不要漏盖。
- 如果是外地户口的话一定需要看好还需要携带哪些附加材料。
