#+title: How To Build Good Software

https://www.csc.gov.sg/articles/how-to-build-good-software

做好软件开发有三个核心点：
- 做好重用。Reusing good software is easy; it is what allows you to build good things quickly;
- 控制好复杂性。Software is limited not by the amount of resources put into building it, but by how complex it can get before it breaks down; and
- 管理好团队。The main value in software is not the code produced, but the knowledge accumulated by the people who produced it.

三个核心点对应三个行动准则：
1. Start as simple as possible; （不要老是想搞个大新闻）
2. Seek out problems and iterate; and（不断地迭代控制复杂性）
3. Hire the best engineers you can.（雇佣最好的开发人员）

-----

让系统和任务充分自动化。Software engineering is about building automated systems, and one of the first things that gets automated away is routine software engineering work.

开发好的软件是有周期的：增加需求和复杂性，重构减少复杂性。Building good software involves alternating cycles of expanding and reducing complexity.

产品开发完并不意味着开发知识就可以丢弃了。产品是运行在系统上的，系统会变化，产品会升级，这些都需要开发知识的支撑。This knowledge continues to be important even after the product is built. If a new team takes over the code for an unfamiliar piece of software, the software will soon start to degrade. Operating systems will update, business requirements will change, and security problems will be discovered that need to be fixed. Handling these subtle errors is often harder than building the software in the first place, since it requires intimate knowledge of the system’s architecture and design principles.

不能把软件看做一个静态的产品，它其实是开发团队的集体智慧的表现。这也解释了为什么不要把重要项目给外包团队，因为这些开发知识是没有办法打包返回给你的。Software should be treated not as a static product, but as a living manifestation of the development team’s collective understanding.
