#+title: How to Read a Paper

http://blizzard.cs.uwaterloo.ca/keshav/home/Papers/data/07/paper-reading.pdf

** Abstract
** Introduction
** The Three-Pass Approach
*** The first pass
The first pass is a quick scan to get a bird’s-eye view of the paper. You can also decide whether you need to do any more passes. This pass should take about five to ten minutes and consists of the following steps: (快速浏览掌握大意)
   1. Carefully read the title, abstract, and introduction
   2. Read the section and sub-section headings, but ignore everything else
   3. Glance at the mathematical content (if any) to deter- mine the underlying theoretical foundations
   4. Read the conclusions
   5. Glance over the references, mentally ticking off the ones you’ve already read

At the end of the first pass, you should be able to answer the five Cs :
   1. Category: What type of paper is this? A measure- ment paper? An analysis of an existing system? A description of a research prototype?
   2. Context: Which other papers is it related to? Which theoretical bases were used to analyze the problem?
   3. Correctness: Do the assumptions appear to be valid?
   4. Contributions: What are the paper’s main contribu-tions?
   5. Clarity: Is the paper well written?

Using this information, you may choose not to read fur- ther (and not print it out, thus saving trees). This could be because the paper doesn’t interest you, or you don’t know enough about the area to understand the paper, or that the authors make invalid assumptions. The first pass is ade- quate for papers that aren’t in your research area, but may someday prove relevant.(决定是否需要继续阅读)

*** The Second Pass
In the second pass, read the paper with greater care, but ignore details such as proofs. It helps to jot down the key points, or to make comments in the margins, as you read. Dominik Grusemann from Uni Augsburg suggests that you “note down terms you didn’t understand, or questions you may want to ask the author.” If you are acting as a paper referee, these comments will help you when you are writing your review, and to back up your review during the program committee meeting.(仔细阅读内容但是忽略具体细节比如证明等，同时在margin部分做comment)

The second pass should take up to an hour for an expe- rienced reader. After this pass, you should be able to grasp the content of the paper. You should be able to summarize the main thrust of the paper, with supporting evidence, to someone else. This level of detail is appropriate for a paper in which you are interested, but does not lie in your research speciality.(理解论文内容)

Sometimes you won’t understand a paper even at the end of the second pass. This may be because the subject matter is new to you, with unfamiliar terminology and acronyms. Or the authors may use a proof or experimental technique that you don’t understand, so that the bulk of the pa- per is incomprehensible. The paper may be poorly written with unsubstantiated assertions and numerous forward ref- erences. Or it could just be that it’s late at night and you’re tired. You can now choose to: (a) set the paper aside, hoping you don’t need to understand the material to be successful in your career, (b) return to the paper later, perhaps after reading background material or (c) persevere and go on to the third pass.(如果second-pass之后不能够理解内容的话，可以选择将论文放在一边认为这篇论文不是足够重要，或者是在掌握足够背景知识之后继续阅读，或者是进行third-pass)

*** The Third Pass
To fully understand a paper, particularly if you are re- viewer, requires a third pass. The key to the third pass is to attempt to virtually re-implement the paper: that is, making the same assumptions as the authors, re-create the work. By comparing this re-creation with the actual paper, you can easily identify not only a paper’s innovations, but also its hidden failings and assumptions.(third-pass关键是假设自己来实现，使用相同的前提条件来完成相同的目的。这样不仅能够理解作者的创新之处，也能够发现一些陷阱或者是不太容易注意到的地方)

This pass requires great attention to detail. You should identify and challenge every assumption in every statement. Moreover, you should think about how you yourself would present a particular idea. This comparison of the actual with the virtual lends a sharp insight into the proof and presentation techniques in the paper and you can very likely add this to your repertoire of tools. During this pass, you should also jot down ideas for future work.

This pass can take many hours for beginners and more than an hour or two even for an experienced reader. At the end of this pass, you should be able to reconstruct the entire structure of the paper from memory, as well as be able to identify its strong and weak points. In particular, you should be able to pinpoint implicit assumptions, missing citations to relevant work, and potential issues with experimental or analytical techniques.

** Doing a Literature Survey
Paper reading skills are put to the test in doing a literature survey. This will require you to read tens of papers, perhaps in an unfamiliar field. What papers should you read? Here is how you can use the three-pass approach to help.(引用频率高的文章，作者牛X的文章，以及高质量会议的文章)
- First, use an academic search engine such as Google Scholar or CiteSeer and some well-chosen keywords to find three to five recent highly-cited papers in the area. Do one pass on each paper to get a sense of the work, then read their re- lated work sections. You will find a thumbnail summary of the recent work, and perhaps, if you are lucky, a pointer to a recent survey paper. If you can find such a survey, you are done. Read the survey, congratulating yourself on your good luck.
- Otherwise, in the second step, find shared citations and repeated author names in the bibliography. These are the key papers and researchers in that area. Download the key papers and set them aside. Then go to the websites of the key researchers and see where they’ve published recently. That will help you identify the top conferences in that field because the best researchers usually publish in the top con- ferences.
- The third step is to go to the website for these top con- ferences and look through their recent proceedings. A quick scan will usually identify recent high-quality related work. These papers, along with the ones you set aside earlier, con- stitute the first version of your survey. Make two passes through these papers. If they all cite a key paper that you did not find earlier, obtain and read it, iterating as neces- sary.

** Related Work
** References
