#+title: How The Economic Machine Works

这两天看Ray Dalio的《原则》这本书，里面说到他制作了一个30分钟 [[https://www.youtube.com/watch?v=PHe0bXAIuk0][视频]] ([[https://www.youtube.com/watch?v=rFV7wdEX-Mo&t=5s][中文]]) 帮助初学者来理解经济学。[[https://www.zhihu.com/question/24504039][知乎]] 上面也有关于这个视频和相关文章的讨论。

我之前业余地学习过宏观和微观经济学（曼昆的那两本书），但是没有办法很好地将两者联系起来，两者是如何相互影响的。我觉得这个视频将这两者联系了起来，从微观角度出发(transaction, 交易), 到次宏观角度(market，市场），然后到宏观角度(economy, 经济)，既照顾到了细节又不忽视整体。

写几个值得记录的点吧：
1. money/debt 都算是货币，可以用来买卖商品
2. 我们需要提前消费，所以就需要debt. 不管这个提前消费是因为人性贪婪还是需要，比如买房大部分人都需要贷款事情。
3. debt越来越多，这个过程就是leverage(杠杆化); 减少debt的这个过程就是deleverage(去杠杆化)
4. 我的理解是，short-term debt cycle是控制debt的增速，或者说少量减少debt, 而long-term debt cycle是彻底地降低debt.
5. 在long-term debt cycle阶段，中央银行降低利率来增加货币流动性这种做法彻底失效。
6. 虽然视频里面认为productivity growth是个基本恒定量，但是我以为合理地使用debt可以让productivity growth更快，技术发展也会更快。
7. 开始我不太理解最后面三条原则中的2，为什么需要让income growth低于produce growth. 我们生产的东西需要贩卖出去才可以获得income, 如果income growth超过produce growth的话，你可以认为是在透支生产这个过程。

下面是从知乎转过来的总结，我觉得第2点他的解释不错。视频最后，Dalio提出了他的三条建议：
1. 不要让债务比你的收入增加的更快
2. 不要让你的收入比生产力增加的更快（举个栗子，公司的分红不要超过公司增长的速度，留存收益要足够多）
3. 尽可能的增长你的生产力
