#+title: 中国人应该这样用药

[[https://book.douban.com/subject/25768216/][冀连梅谈：中国人应该这样用药 (豆瓣)]]

事实上，大多数普通老百姓不仅不知道滥用抗生素的危害，往往连哪些药是抗生素都搞不清楚，因此有时候滥用了也不知情。不妨来看看老百姓常用的哪些药是抗生素，并请记住这些药，自己不要随便去药店买。它们包括：青霉素类（如阿莫西林）、头孢类（如××头孢，俗称“先锋×号”）、红霉素类（如阿奇霉素）、四环素类（如多西环素）、喹诺酮类（如氟哌酸，××沙星）、磺胺类（如复方新诺明、增效联磺）、甲硝唑、氯霉素、庆大霉素等。

炎症不是特定的一种疾病的名称，而是很多疾病都会表现出来的一种症状。细菌感染、病毒感染、真菌感染、过敏、跌打损伤等都可以导致身体表现出红、肿、热、痛等炎症的症状。而抗生素只针对细菌等敏感菌的治疗，对病毒、真菌、过敏、跌打损伤等引发的炎症没有消炎作用。使用抗生素把敏感菌造成的感染控制住后，由这些敏感菌感染引发的炎症自然也就消了。消炎是因为抗生素与敏感菌作斗争并且取得了胜利。换句话说，如果身体的炎症不是敏感菌引发的，用了抗生素也起不到消炎的作用。

还有另外一种广泛滥用抗生素消炎的疾病是急性支气管炎。患有急性支气管炎的病人去看医生时，80%左右的人会被开出抗生素的药方，而且通常还是广谱抗生素。其实，急性支气管炎常常是感冒以后，感冒病毒进入支气管，刺激支气管引发咳嗽导致的。也就是说，急性支气管炎绝大多数是病毒感染引起的，细菌引起的比例非常少。如果咳嗽超过10天，咳嗽时伴有胸痛、咳血或者呼吸困难，才考虑去看医生开抗生素来吃。

另外，长期滥用抗生素去治疗病毒引起的感染，不仅不会将身体里的病毒杀死，反倒会帮倒忙：抗生素在没找到有害菌的情况下会滥杀无辜，将身体里的有益菌杀死，从而可能导致腹泻，还会使人体免疫力下降，进而使疾病病程延长！你看，本来就一个小病，反倒有可能被治成大病，得不偿失。

既然抗生素不等于消炎药，那消炎药都指哪些药呢？临床上通常把下面的两类药叫消炎药：一类就是我们常说的激素，如可的松、氢化可的松、地塞米松等；另一类是消炎止痛药，如布洛芬、阿司匹林等。但请注意，对于具有正常免疫功能的人而言，可的松类激素是人体可以自己分泌的。它有抗炎功效，所以感冒等引起的嗓子发炎是不需要额外使用消炎药来消炎的，好好休息，提高免疫力可以达到自愈的效果，也就是人们常说的“吃药一周好，不吃药七天好”，吃不吃药都要经历一样的病程。

遗憾的是，新抗生素研发的速度远远赶不上老抗生素失效的速度，其数量呈现的是逐年递减状态。进入2000年后，全球范围内新上市的抗生素只有几个，远远抵不上失效抗生素的数量。你想啊，一个新抗生素的研制要花费至少数亿美金，要被批准上市，需要经历一期、二期、三期临床试验，审批上市阶段最短也要十年。辛辛苦苦开发出来的新抗生素上市后，两三年内就可能出现耐药的超级细菌，新抗生素就没作用了。这种情形一出现，药厂那些研发经费就等于大半打了水漂，因此药厂也就没有太多的动力去生产新抗生素，这也是抗生素青黄不接的原因

只有医生才有能力指出具体病因以及感染的部位，比如“细菌性肺炎”，这一具体名称明确了引起生病的是“细菌”，给出了感染部位是“肺”，而不是其他地方。甚至更细一点，医院的化验室还能检测出是哪种细菌感染，不同的细菌对应着不同的抗生素选择，比如链球菌感染对应的选择可能是青霉素类的抗生素，而支原体感染对应的选择可能就是红霉素类的抗生素，等等。

不需要用抗生素时坚决不滥用，但真正需要抗生素时，一定要足剂量足疗程地规范使用，这个道理欧美发达国家的老百姓多数都懂。我在美国药房工作期间，每次给病人发抗生素的时候，除了在口头上和病人强调这一点外，还会随药发给病人一份文字版的用药指导，那上面除了介绍这个药是做什么用的、有什么不良反应和注意事项外，还特别强调：即使吃抗生素后症状有所好转，也不要提前停药，更不能随意减量，一定要把医生开的抗生素全部吃完。

普通感冒在医学上的名称是“上呼吸道感染”（俗称“上感”），上呼吸道包括鼻、口、咽、喉，也就是说从鼻子到喉咙这些部位的急性感染都算感冒，表现出来的症状是打喷嚏、流鼻涕、鼻塞、发烧、头疼、嗓子疼、咳嗽等，明确的致病原因就是病毒感染。

在美国，利巴韦林的雾化剂型只允许用于治疗呼吸道合胞病毒引起的重度下呼吸道感染。注意，这里说的是“重度”，而且是气管以下的下呼吸道感染，尤其是原来就有肺部疾病的住院病人的治疗。而利巴韦林的口服剂型只用于与干扰素联合使用治疗成人的慢性丙型肝炎。

我们有自己的免疫系统，如果我们的免疫系统功能正常，完全可以把普通感冒病毒从身体里清除出去，只是我们的免疫系统和普通感冒病毒作斗争需要一个练兵的过程，不是一看到病毒进入身体就能把它清剿，而是要先花1～2天的时间试探一下对方的实力，然后再花1～2天的时间产生特异性的抗体有针对性地把病毒清剿，所以普通感冒有时会有3～4天的反复发烧。另外，在这场免疫系统与普通感冒病毒作战的战役中，将病毒赶走后清理战场（即咳出呼吸道分泌物以及修复受损的呼吸道黏膜）则需要更长的时间，因此患普通感冒后咳嗽两周左右也很常见。

实际上，地塞米松不是退烧药，它属于糖皮质激素的一种，也就是老百姓常说的激素。激素能起到抑制免疫的作用，免疫系统不工作了，烧也就退了，但它同时阻碍了人体自身对抗疾病的能力，使得病菌趁机生长繁殖引发新的感染，也就是说，容易使人的体质变差，可能会导致严重感染。

如果是口服药物，我们人体的胃肠道还能作为一道天然的屏障来阻挡药品中的杂质，而注射液这种剂型是毫无阻挡地直接把药物打到血管里，因此对制剂的要求非常高，溶液一定要无菌、无热原，要和身体有相等的渗透压、相等的pH值等。

听说在不少医院的药房，中药注射液从西药取药窗口发药，如果你不知道如何区分中药注射液和西药注射液，我建议你在药盒或者药品说明书里找一下药品批准文号，批准文号以拼音字母“Z”开头的代表中药，以拼音字母“H”开头的代表西药（化学药品）。

事实上，感冒药的品种虽多，但不同品种包含的有效成分却大同小异，而且这些成分的数量也非常有限，熟悉这些有效成分比记住感冒药的商品名更重要。西药感冒药里的有效成分无外乎下列六类：1.抗过敏成分，2.减轻鼻黏膜充血的成分，3.解热镇痛成分，4.祛痰成分，5.镇咳成分，6.抗病毒成分。

目前市售的口服补液盐都是按照世界卫生组织推荐的配方生产的。配方里不仅含钠，还含钾，除了这些盐成分外，还有固定配比的糖成分。糖起到往身体里运盐的作用，不可或缺但量又不能太大，否则会像海绵一样把体内的水吸到肠道，恶化腹泻。

比如，消除症状的药物药效发挥就比较快，像退烧药大约30分钟～2小时就能起效。但针对病因治疗的抗生素等药物起效就比较慢，因为抗生素的杀菌或抑菌作用需要药物在人体内达到一定的血药浓度才能产生，而达到有效的血药浓度没有想象的那么快。另外，细菌感染被控制也需要一段时间。就拿最常见的肺炎而言，即使确定是由细菌感染引起的，使用抗生素后也需要观察2～3天才能看到效果，此时才能大致判断选择抗生素的种类和给药途径等是否正确。

取的莨菪碱类物质，有严格的用法用量要求。因此，哈内曼并不是把这些物质直接作为药物使用，而是首先把某种物质在酒精中浸泡几个星期，过滤浸泡液得到该物质的“母酊剂”。然后，他使用一些“母酊剂”通过用水反复地稀释和强烈地摇动（振荡），得到最终的产品。直到现在，仍然用这套基本程序来制造顺势疗法的产品。

另外，咳嗽是咳不出肺炎的，感冒的时候伴随咳嗽也很常见，你看她咳的时候还有痰，要是吃了止咳药，痰咳不出来，倒是有可能感染到肺导致肺炎。另外，您知道吗？国外已经不推荐给4岁以下的儿童使用止咳感冒药了，今年美国开出‘医生不该作为’列表，继续呼吁不要给4岁以下的儿童使用止咳感冒药。

从药品组成上看，这类感冒药都属于复方制剂，即一个药品里含有多种有效成分，比如护彤，也叫“小儿氨酚黄那敏”，它的药品说明书里有效成分这一项中标明它不仅含退烧止痛成分对乙酰氨基酚，还含马来酸氯苯那敏等成分。再比如氨酚甲麻、氨酚烷胺、氨金黄敏、美敏伪麻、酚麻美敏等药品，里面的有效成分都不止一种，因此这些都是复方感冒药，也正是欧美等发达国家目前不推荐给4岁以下儿童使用的药品。目前更有呼声建议把不推荐的年龄扩大到6岁。

咳嗽跟呼吸的空气有很大关系。如果空气太脏，或者是太干燥，宝宝就咳得厉害。所以，在家里护理宝宝时，若天气好，应多开门窗通气，使屋里的空气保持清新；若天气不好，可以使用空气净化器来改善室内的空气；若空气干燥，要用加湿器增加室内湿度，使用加湿器使室内湿度保持在40%～50%，湿度太大也不行，容易使房间滋生霉菌。也可以选择让宝宝吸入水蒸气的方式缓解咳嗽。睡前在浴室内放会儿热水，待蒸气充满浴室，把宝宝抱进去尽可能多待一些时间，让呼吸道通过多吸入一些水蒸汽获得充分的滋润，这个方法也有助于缓解鼻塞和咳嗽。

物理降温的方法有两种：一种是洗温水澡，通过洗澡的方式达到全身散热的目的。给宝宝洗澡时，建议使用的水温是35℃～37℃。还要注意调整好浴室和其他房间的温度，不要使二者相差太多。如果其他房间的温度低于浴室温度很多，给宝宝洗完澡后，要给他擦干再抱出浴室。另一种方法是用温湿的毛巾给宝宝擦身体。毛巾的温度最好控制在37℃左右。用温湿毛巾擦拭宝宝的额头、颈部、腋下和四肢等。毛巾擦身体降温的原理是让宝宝的皮肤血管扩张，让他体内产生的热量及时散发出去，而且用温湿毛巾擦拭身体时，沾在身上的水蒸发，也会带走一部分热量。

栓剂的吸收不经过肝脏，也不刺激胃肠道，比口服的方式起效要快，因为药物直接就从肠道黏膜进入血液了。但是，从吸收率角度来讲，口服吸收率高，栓剂通过黏膜对药物进行吸收，吸收率就低一点。

回答这个问题之前我先介绍一下什么是丙种球蛋白。它是一种由健康人血浆分离提取并经过病毒灭活处理的免疫球蛋白制品，属于血液来源的生物制品。生物制品是很容易导致严重过敏反应的一类药品。另外，一旦制造这种药品的血浆受到污染，注射后感染传染病如乙肝、丙肝等的概率极大，而且临床中也不断发现由于注射受污染的血液制品而感染的病例，所以，现代传染病学认为丙种球蛋白不能大量、广泛地在临床上应用于免疫预防，更不能用于感冒这类小病的预防。临床上对它的使用非常严格，仅用于某些严重疾病的治疗，例如免疫缺陷病、大面积烧伤、严重创伤感染以及败血症等。

这个方面日本人做得非常好，我接触的日本病人，他们如果感冒了，都会戴着口罩来药房取药。还有，在国外的幼儿园，老师常会教小朋友们正确打喷嚏的方式，是拿胳膊肘挡住口鼻，而不是用手挡着。因为病毒很容易通过手传播，而胳膊肘和手比起来，接触人的机会要少很多，传播疾病的概率也就低得多。

另外一点，对于退烧药的使用，我一直强调，首选的退烧药应该是对乙酰氨基酚，也就是家长们熟知的泰诺林，只有吃了泰诺林烧退不下来，才会考虑到要用美林，也就是布洛芬。因为在布洛芬的说明书中，按作用排序应该是消炎、镇痛、解热，布洛芬的首要药理作用不是退烧，而是消炎，解热的作用是排在最后的。

如果宝宝只是排便间隔时间长，排出的大便不干、不硬，排便的过程也不费力、不痛苦，这类情况不算便秘。就像我们常说的“攒肚”现象：宝宝对母乳消化吸收得好，体内的食物残渣少，所以排便间隔会比较长，但是大便不干。这属于正常的生理现象，不需要人为干预。临床上，通常将宝宝排便次数减少，排便时费力、疼痛，同时伴随排出的粪便干、硬、粗、体积大这样的症状定义为便秘。

秋季腹泻如果治疗及时，是可以自愈的疾病，治疗及时指的是及时纠正脱水。秋季腹泻很容易引发脱水，宝宝在刚开始发病时，6个小时内会快速脱水。对于轻、中度脱水的宝宝，首选的治疗方式是补液，而首选的补液方式是口服补液盐。轻、中度脱水的表现包括嘴巴发干，嘴唇干裂，少尿，或者尿的颜色深黄，皮肤弹性变差，哭时少泪等。

目前针对腹泻的治疗，推荐腹泻前是母乳喂养的宝宝，即使腹泻，也应该继续让他吃母乳。不仅可以让他继续吃，还应该让他多吃。因为让他继续吃母乳是在帮助他补充能量。要不要给腹泻的宝宝继续使用配方奶？这个问题取决于宝宝的腹泻是不是因为乳糖不耐受造成的，如果是，可以将配方奶换成不含乳糖的。目前也有一些医生建议在这个阶段可以将配方奶换成不含乳糖的配方奶粉吃一段时间，以保护肠道，等腹泻症状消失后，再换回原来的配方奶。

小儿秋季腹泻是感染轮状病毒引起的，所以为了避免宝宝患上小儿腹泻，就要避免宝宝染上这种病毒。轮状病毒属肠道病毒，是靠手口传播的，所以宝宝若接触了感染轮状病毒的人，或者是感染轮状病毒的人接触过的物体，就可能会感染此病毒。因此，家长平时要给宝宝勤洗手。让他饭前、便后洗手，不吃生冷食物，并定期给宝宝的餐具、玩具消毒。 在疾病流行的季节，尽量避免让自己的宝宝和别的宝宝你吃一口、我吃一口地分享食物，因为这样更容易使宝宝感染轮状病毒。

第二，更换尿布时，要用流动的温水冲洗屁股，之后用柔软的棉布或者纱布拍干屁股。注意“拍”这个词，只有当过妈妈的人才能体会这个词精准的意思，是要用我们轻柔的动作倍加呵护宝宝的小屁股才行。另外，避免使用卫生湿巾擦拭宝宝的屁股，湿巾里的消毒剂会对皮肤产生新的刺激，同时湿巾擦拭也会在皮肤上残留水分，而患有尿布疹的皮肤需要保持干爽才能尽早恢复。必要时，可以像我在文章开头提到的我朋友一样，使用吹风机的低温挡吹干宝宝屁股，或者阳光好时，让宝宝不用尿布趴一会儿晒晒屁股。第三，除了上述保持宝宝屁股干爽的护理手段外，避免粪便尿液直接刺激皮肤的手段还包括在干爽的屁股上面涂抹皮肤保护剂，这类保护剂可以是油脂类物质，包括家长们常说的橄榄油、茶油、麻油、鱼肝油等，利用的是油水分离的原理。也可以是涂抹护臀霜，包括含氧化锌、凡士林等有效成分的护臀霜，利用的是隔离的原理。给宝宝涂抹护臀霜，需要厚厚地涂抹一层才能有效隔离刺激物。凡士林等有效成分的护臀霜，利用的是隔离的原理。

其实，作为外用药的激素药膏并不存在上述家长联想到的副作用，通常只有长期大剂量口服激素或者注射激素，才会产生累及内分泌系统而抑制生长的副作用，而治疗湿疹一般不主张用口服或者注射的激素。外用激素长期使用的不良反应仅局限于皮肤，最严重的副作用是激素依赖性皮炎，而产生这类严重副作用的前提也是长期、大剂量滥用强效激素药膏，而短期使用弱效激素药膏只可能会出现皮肤变薄和色素沉着等副作用。另外，即使不用激素药膏，患湿疹的皮肤在恢复期也会有皮肤色素的改变，这种情况是疾病自身引起的皮肤颜色变化，不一定是激素造成的色斑，随着时间的推移，色斑会慢慢褪去。

常用的外用激素由弱到强排序是：正规大医院自制的含地塞米松的药膏→1%氢化可的松、0.1%丁酸氢化可的松（尤卓尔）→0.1%糠酸莫米松（艾洛松）、0.05%地奈德→倍他米松→氯倍他索。治疗幼儿湿疹，通常不会选用最后两种强效激素，一般1%氢化可的松就可以止痒消炎，遗憾的是1%氢化可的松中国市场上没有，因此我们常用和它强度相当的尤卓尔。当需要比尤卓尔更弱的激素时，可以咨询药房，通常药房会自己配制。

被蚊子叮咬后身体会释放组胺炎性物质，引起叮咬部位肿胀，这很正常。蚊虫叮咬后可以立刻用碱性皂液清洗患处来防止起包，如果已经起包，可以使用持续凉敷的方法消肿止痒，如取毛巾包冰块敷在被咬的部位，或者把湿毛巾放入冰箱冻冷后敷在被叮咬的部位，可以每2～3个小时进行一次。此外，也可以选择外用炉甘石洗剂止痒。要避免宝宝抓挠肿胀处，否则可能抓破进而感染。

我曾听一个治疗矮小症的专科医生说，有一个不到10岁的小女孩，乱吃增高药，不到一年就性早熟了，估计成年后身高也到不了一米四，这让医生恨得牙痒痒，恨骗子太缺德，恨家长太无知！家长们要注意，性早熟容易导致宝宝身材矮小，这是因为宝宝出现性早熟时，性激素提前大量分泌，生长激素也伴随大量分泌，使宝宝身高短期加速增长，导致宝宝早期身高暂时比同龄宝宝高。但由于性激素的刺激，骨成熟变早，骨骺会提前闭合，导致宝宝骨骼生长期缩短，身高发育过早停止，最终导致身材矮小。

一般出水痘可以用炉甘石洗剂止痒，长痱子、蚊虫叮咬也可以涂，但炉甘石洗剂不是万能止痒药。尽管中文的药品说明书上写着可以用于湿疹，但我个人不建议用它涂湿疹。因为这个药是水剂的剂型，水在皮肤上蒸发会让皮肤变干燥，不利于湿疹皮肤的保湿，所以不利于湿疹的恢复。
