#+title: 如何定义软件稳定

@2012-8-30 redis作者在自己的 [[http://antirez.com/post/redis-26-sentinel-update.html][博客]] 中提到了如何定义软件到达了production-ready状态

#+BEGIN_QUOTE
There are probably much more software engineering books than there should be ;) So despite of the general title of this section my goal here is to state what stable means for me and for the Redis project. After all there are a number of possible metrics, but mine is very simple and in the latest three years worked very reliably.

A Redis branch without active development (major changes to the source code that are not just additions without impacts to what we already have) is stable when the number of critical bugs discovered in the latest 8 weeks is near to zero.

In this context a critical bug is a bug that corrupts data, that crashes the server, that creates an inconsistency between master and slave, and that, at the same time, is not triggered by a crazy edge-case, so edge that it is unlikely to run into it involuntarily.
#+END_QUOTE

在作者看来，一个稳定的版本意味着：
- 不会有影响到现有功能的修改
- 在过去8周内没有严重的bug（比如宕机或者是数据损坏等），但是不考虑一些非常极端的case
