#+title: 谷歌是如何运营的(How Google Works)

大多数人并没有接触过这种如登月般异想天开的思维方式，他们习惯用“不可能”来否定自己的想法，而不是从基本物理原则出发去探索可能性。

如果我们把传统知识工作者与谷歌十几年来招徕的工程师等人才放在一起对比，就会发现谷歌的人才是一个截然不同的员工群体。这些人并不拘泥于特定的任务，也不受公司信息和计算能力的约束。他们不惧怕冒险，即便在冒险中失败，也不会受到惩罚或牵制。他们不被职位头衔或企业的组织结构羁绊住手脚，甚至还有人鼓励他们将自己的构想付诸实现。如果出现不同意见，他们不会选择缄口不言。他们很容易失去耐心，经常变换职位。他们具有多领域的能力，经常会将前沿技术、商业头脑以及奇思妙想结合在一起。换句话说，至少从传统意义上来说，这些人已经不能算是知识工作者了。这是一个新的物种，我们称之为“创意精英”，他们，便是互联网时代取得成功的关键所在。

企业文化一旦形成，想要改变绝非易事，因为企业在成立之初容易受“自我选择倾向”的影响。也就是说，与企业秉持相似理念的人会被吸引而来，而与企业理念相左的人则不会。

先思考一下你理想中的企业文化或现有的企业文化。然后，让我们把时间快进几个月或几年，想象一下这样一个场景：一位员工为了一个困难的抉择纠结许久，一直熬到深夜。25他走到厨房里去拿一杯咖啡，回想起企业的价值观。这些价值观，领导在会议上传达过，同事们在午餐休息时议论过，德高望重的公司前辈也身体力行过。那么对于这位员工或者所有员工而言，这些企业价值观应当简明扼要地阐述出企业最为重视什么以及企业成员最为关注什么。否则，这些价值观宣言就毫无意义，根本无法帮助创意精英们做出正确的抉择。

而我们的理念则完全相反，我们认为，办公状态应鼓励大家多多交流，让大家在喧闹拥挤的办公室里畅所欲言、激情碰撞。在参与完团队活动后，员工可以到清静之地换换脑子。正因如此，谷歌的办公室里设置了许多休闲设施：咖啡馆和小型厨房里有僻静的位子，另外还有私密的会议室、露天阳台和院落，甚至还有睡袋呢。然而，休整完毕后，他们应当回到同事中间继续办公。

但正如乔纳森常说的，在家办公其实无异于一种会在整个公司内蔓延、让员工士气萎靡不振的瘟疫。已故的贝尔实验室前董事长默文·凯利就是本着鼓励员工相互沟通的理念来设计公司办公格局的。34走过长长的走廊，贝尔实验室的工程师和科学家们要么会与同事打个照面，要么就直接被拽进某间办公室里去了，而这种偶遇的机会是在家办公者绝对不会碰到的。

一条至关重要的组织原则是：找出最有影响力的人物，组织就以此人为中心。不要把岗位或经验作为选择管理者的标尺，而要看他的表现和热情。

不”对于创意精英而言犹如当头一棒，这表明企业已然失去成立之初的活力，披上了过于形式化的外衣。在遭遇一次次“不”的重重打击后，创意精英们便不再多费口舌，开始盘算另谋高就了。

一家初创的伟大企业、一个炙手可热的项目或者一份好工作，都应该充满乐趣。如果你忙得焦头烂额，却没收获快乐，那就有问题了。对未来成功的憧憬会令人振奋，但更多的乐趣却来自同事间的欢声笑语、幽默调侃。

但我们敢百分百地打包票：如果你有商业计划，那你的计划一定是错误的。只要是MBA式的商业计划，无论经过怎样的深思熟虑，一定在某些方面存在硬伤。如果你硬要一心一意按照这份有瑕疵的计划一步步走下去，那么就会像企业家埃里克·莱斯说的一样“实现失败”。54因此，风险投资家应永远遵守投团队而不投计划的准则。既然计划会错，那么人就得对。成功的团队懂得如何发现计划中的瑕疵，并及时做出调整。

计划的无常可能会让一些想加入团队的人望而却步，因为绝大部分人都不喜欢不确定性。而创意精英与一般人不同，他们就爱自己动脑筋想对策。

不断改进以及使用巧妙的商业手段无可厚非，但如果把市场调查看得比技术创新还要重要，那就本末倒置了。大多数企业都是以技术洞见为基础起步的，但在前进的路上却往往偏离了航道（这就是舍本逐末）。

如果你把注意力放在竞争对手身上，那你绝不会实现真正的创新。当你与竞争对手为了市场占有率的几个百分点争得不可开交时，半路往往会杀出一个不在乎市场占有率的竞争者，用全新的平台颠覆整个游戏。

想要留住创意精英，最好的方法就是避免让他们太过安逸，而是不断用新的想法保持他们工作的趣味性。

假如你在走廊里遇到了上司的上司，他询问你正在做什么项目。好吧，我们就假设你遇到的是首席执行官吧。那么，你会如何作答呢？首席执行官可不是在跟你寒暄：现在就大声说出你的回答。快点，你只有30秒。

思考一下，5年之后，你理想中的工作是什么样的。你想做什么样的工作？想要什么样的收入？描述一下你心目中的理想职位：如果你在网上看到了这份工作的招聘信息，那么这广告具体会是什么样的呢？现在，把时间快进四五年，假设自己已经得到了这份工作。那么，你5年后的简历会是什么样的？想要得到5年后心中理想的位置，你从现在起需要如何选择前面的路？

谷歌于2004年上市以来，我们每一季度都会把致董事会信函与大家分享，迄今为止，还没有出现信息泄漏问题。另外，也没有人因为缺少对公司总体情况的了解而提出过抱怨。就算有人抱怨，我们只要让当事人读一读致董事会信函、看一看埃里克的演讲就行了。

在生活中，很多情况下一件事情需要重复大约20遍才能被人真正听进去。143如果你只重复几遍，对方会因为忙碌而充耳不闻。多重复几遍，他们才能感受到耳边隐约有动静。等到重复了15~20遍的时候，你自己可能都懒得说了，而这时，听者才刚刚开始有所触动。因此，作为领导者，你必须习惯于苦口婆心、诲人不倦。埃里克喜欢说：“祷文不会因重复而失色。”

仙童半导体及英特尔公司的联合创始人罗伯特·诺伊斯曾说：“乐观是创新的一个必要条件。否则，你怎能放弃安逸而追求改变，或离开舒适的环境而选择冒险呢？”159你所雇用的人，不仅要有能够产生新构想的头脑，也要足够疯狂地相信这些构想有机会实现。你需要挖掘和吸引这些乐观的人才，并提供平台，让他们创造改变、大胆冒险。

谷歌明白，在互联网时代，用户的信赖与美元、欧元、英镑、日元或任何其他货币一样重要。要让企业获得持续的成功，除了依靠产品质量以外别无他法。因此，我们的产品战略，就是聚集用户。就像拉里和谢尔盖在谷歌首次公开募股说明书中说的那样：“为终端用户服务是谷歌业务的核心，是我们的第一要务。”

但是，“聚焦用户”这句话只说了一半，完整的句子应该是：“聚焦用户，一切水到渠成。”意思是说，我们会始终为用户做对的事情，也相信我们的创意精英能够想办法从中获利。这个过程需要时间，因此要坚持这样做需要信心。160但这通常是值得的。

如果当初谷歌动用了一支工程师团队并慷慨投资，自然可能研发出谷歌图书这款应用程序。但是，充沛的投资也有可能在这个项目动工之前就形成了阻力。事实证明，如果拉里投入时间、砸下预算买下先进的数字化系统，其性价比也不会高于他用从Fry’s超级家电连锁店175买到的零件随意拼凑出来的简陋系统。没有什么比过度投资更能损害创意的发展，就像建筑大师弗兰克·劳埃德·赖特所说的：“人类建筑最为辉煌的时期，就是那些限制最多的时期。”176

具体实行交付——迭代模式的时候，尽量不要在产品上市时借助市场营销手段和公关宣传的力量。在餐饮业，这种做法叫作“试营业”。当你把小鸟赶出鸟巢时，不要给它们配备什么喷气背囊和降落伞，而是让它们靠自己的力量飞起来。

交付——迭代模式并不意味着你可以随意把糟糕的产品推出去，然后坐等这些产品自己越变越好。实际上，乔纳森常常警告他的团队，不要把糟糕的产品投放市场，指望着靠谷歌的品牌力量在早期吸引人气。产品应当具有卓越的性能，但刚上市时，功能有限是可以接受的。在推出产品的时候，限制铺天盖地的市场营销及公关宣传是有利的，因为相比于一款低调上市的产品，一款被吹捧上天的产品更容易让消费者感到名不符实。上市之后，再添加新功能完善产品（以及对现有功能做微调）也不晚。

要想创新，就要学会把败仗打漂亮，学会从失误中汲取教训。所有失败的项目都会衍生有关技术、用户以及营销方面的宝贵信息，为你的下一次出征做准备。修改创意，而不要否决创意：世界上多数伟大发明的最终用途与最初设想都是天差地别。因此在放弃一个项目时，要仔细审视其组成部分，看看有无可能重新投放在其他领域。拉里说过，如果你的眼光够远大，那就很难全盘皆输。失败中往往会隐藏着珍宝。另外，不要拿失败的团队问罪，而要确保他们能在公司里找到合适的岗位。因为下一批创新者正在静观其变，想看看失败的团队会不会受到惩罚。他们的失败虽然不值得称颂，但也是一种荣誉。因为，至少他们努力了。

对于正在经营的企业而言，遇到难题是不可避免的。人们往往不会触及这些难题，要么是因为没有好的解决方案，要么就是因为触及这些难题会让人不安。但正因如此，我们才需要提出这些难题，为的就是要让大家不安。相比于竞争者想要置你于死地而造成的不安，我们宁愿这种不安是自己人造成的，这是埃里克在太阳公司的亲身体会。即便没有好的解决方案，那些难题至少能带来一线生机。那些无法轻易解决的难题，往往能对大企业文化中规避风险和拒绝改变的风气起到一定的扭转作用。

多数企业现行管理模式的设计都跟时代的变化趋势完全不同。这些管理模式诞生于100多年之前，当时，失误所造成的成本损失很高，且只有企业最高管理者才能掌握全面的信息。这些管理者的首要目标就是降低成本，确保只有掌握大量信息的少数总裁级人物才有权制定决策。在这种传统的“指挥——控制”式企业结构中，信息自下而上流动，而决策则由上而下传达。这种方法旨在放慢速度，也的确有效地减缓了速度。也就是说，当企业必须一直加速时，这种结构就会失灵，阻碍企业发展。
