#+title: 如何学习理工科 - 田渊栋

理工科也是一样，说穿了就是大自然千百年来玩的不变把戏，不理解的人认为其神
秘，只是因为肉眼凡胎，被各种纷繁的表面现象所迷惑，或是掌握的台前幕后的信
息不足，而没能看见隐藏在现象之后的关键原因。一旦明白和理解其机理之后，都
会有“原来如此，其实说穿了十分简单”的感悟，就像魔术师的把戏被揭穿了一样。

明白了这个总纲，学习过程就很简单:从基本假设出发，严格地沿着逻辑体系和推
理链条一步一步地走到终点，然后做一些习题，思考一些现象，试着检验自己的理
解是否准确明晰，是否能得到习题的正解，或是预测现象的发展，仅此而已，没什
么需要灵感或是创造力的地方。最后，就看自己是不是能够有“原来如此”甚至
“不过如此”的感叹，若是仍然觉得十分神秘，那学习就要算是失败了。

解决的办法，就只有两个字:耐心。看不懂走偏了，就从头再看，或者换一本书看，
或者与人讨论，或者以自己的理解，试着写简明提纲，直到从头到尾都大致通顺了
为止。等到通顺了，知道基本思想了，再回头看书，就会有豁然开朗之感，那些烦
人的二义性自然消失。一旦达到这个层次了，基本上不会对这门学科的脉络有大的
误解，可以说是小有所成了。

从刚才分析的学习过程，我们可以把学习材料分成以下几类:一本入门读物能让读
者知道这个学科的存在，历史，展望，应用前景，并激发读者深入探求的好奇心;
一本合格的导论会将学科的脉络讲述清楚，对概念的解读大体正确，但未必精确;
一般教科书会深入介绍各种学科细节，会出现数学公式和习题，但在粗细主次的把
握上不一定合理;一本经典教科书则会有意识地强调重点、难点和易混淆点，来帮
助读者作细致深入的理解;最后，真正的神作则会透过流畅的故事、生动的比喻、
清晰的逻辑来自然而然地将本学科的大体结构和最重要的细节同时呈现在读者面前，
给读者留下全面正确又深刻的印象。

其中有一点要注意的是，科普书一般会归在入门读物里面，有些好的科普可以当简
明导论来看，但是我个人意见是科普文永远不能当教科书用。我高中时候看过很多
量子力学和相对论的科普文，看完了之后对理论物理学充满憧憬，但是每一次看完，
都有一种好像没有抓住要点的感觉，那些概念如断线的风筝，在天上飘着的。只有
当数学基础变好了，仔细研究了理论背后的数学体系之后，科普文里一些模棱两可
或者高深的句子，才开始有了数学上明确的含义，反过来数学上的抽象符号，也有
了形象生动的解释。至此，再重读这些科普文，思路才不会走偏，甚至会心一笑，
知道作者这么写，有他搔破头皮却辞不达意的苦衷。
