#+title:  How to build your personal brand as a new developer

[[https://medium.freecodecamp.org/building-your-personal-brand-as-a-new-web-developer-f6d4150fd217]]

为什么你需要打造自己的个人品牌呢？从作者下面这亲身经历就知道了

#+BEGIN_VERSE
My company was recruiting for several positions and had received a large number of applications. To my surprise, I saw my boss Googling applicant’s names to evaluate their online presence.

My boss was using this as a way of looking for positive contributions and information. He wasn’t browsing Facebook trying to find out what the candidate does on a Friday night. He was more interested in:
- Did the applicant have a blog?
- Any special interests?
- Any passion projects outside of work?

I’m sure at other companies though, this could well be a different story.
#+END_VERSE

作为一个新手，下面是几个很容易上手的打造个人品牌的方法：

*Start and maintain a blog*
- This isn’t about getting 1,000’s of visitors to your website. This is about developing a personal brand. And ultimately, it’s about what happens when a prospective employer or customer types your name into Google. 不用一味地追求UV/PV, 记住这个只是为了展示你的个人品牌，而不是产生更多的流量
- Your actual blog doesn’t need to be anything flashy or expensive. A Wordpress blog with a free theme will be more than enough to get you started. There are other platforms that you could use like Jekyll. Wordpress was so easy for me to set up and get started with that I never felt the need to try anything else. 展现形式不是特别重要，wordpress/jekyll都可以。或者是像我一样使用 [[file:use-emacs-org-mode-to-build-site.org][emacs]] 来创建站点。
- Don’t get too caught up on what to write or spend hours and hours tinkering with your blog. It shouldn’t take any time away from your learning or your family time. Try to post regularly and be consistent with it. 不要让blogging占据你太多的时间，牺牲你学习以及和家人相处的时间。经常花一点时间在上面，然后坚持下去。
- Finally, try and remember that all your posts don’t have to be too technical. Even if you are a complete beginner, you will always have 1 day, 1 week or 1 month’s more experience than someone else. Someone will find value in what you have to say. 写的东西不一定要是特别技术性的。我理解这点对于developer蛮重要的，因为作为dev很容易过于陷入技术细节。
- Don’t be afraid to take the opportunity to write about something non-technical. Write about a hobby or interest. Use your blog as a way to show your personality and interests outside of code. Just try not to be too controversial.

*Sign up for a Twitter account*
- twitter上面还是有很多技术业界大拿的，而且他们在twitter上面也非常活跃，可以很好地形成自己的social network.
- As well as being part of a community, it’s a great way to keep up to date with industry news and events. It’s also a great way to break the ice and say a virtual “hello” before bumping into someone at an in-person conference or meet-up. 跟上业界的发展趋势，创建自己的社交网络
- Remember that your tweets are there for the whole world to see. So with that in mind please be helpful, be kind, and try and offer some kind of value. Pointless tweets about what you had for dinner and auntie Madge’s bad back are going to get you swiftly un-followed. 因为在twitter上你的信息会出现在别人的news feed上的，所以你的tweet应该尽可能地对别人有价值。
- Social media is a great opportunity to build your personal brand so use it correctly to network, and share your enthusiasm and knowledge.

*Be consistent across all platforms*

在各个平台上的展现信息应该尽可能地一致，包括logo, slogan, image, name等等各种个人信息。

#+BEGIN_VERSE
When you think of any brand, no doubt you will associate it with a particular logo, slogan or image. This is exactly the same when evaluating your personal brand.

Make sure that you have the same profile picture and bio across all platforms. I made the mistake of having a different profile picture on Medium to what I had on Twitter. People didn’t immediately associate the two. Your aim is for people to recognize you and your personal brand no matter what the platform.
#+END_VERSE

*You ARE a developer*

可能你只是一个业余开发者，或者是你现在正在学习如何开发，但是无论如何，你都应该对外宣称自己是developer. 几个原因：
- What hiring manager is going to be interested in an aspiring developer? It’s a sure fire way to get dismissed at the first cut. （招聘经理筛选的时候会特别注意你是否生成自己是developer)
- Even if you work a regular day job and have been learning to code in the evenings, you’re still a “developer” (who just happens to work a job during the day and write code in the evenings!). （即便是大公司的开发人员，基本上也都是白天开会晚上写代码）
- There will be plenty of opportunities to explain your level of experience at a later date. But first impressions count, so don’t stumble at the first hurdle. （你完全可以在后面证明自己的经验和水平，但是第一印象非常重要）

*What exactly does Junior even mean anyway?*

和上面一定要声称自己是"developer"之外，一定不要称自己是"junior developer". 因为这完全没有意义

#+BEGIN_VERSE
Seriously though, junior has no meaning. It comes down to an individual’s perception. A junior developer could be someone with little to no work experience. But what if that person has been writing code in their spare time for the past 10 years? Are they junior then? Or someone could have a few years commercial experience yet still not be very good?

If you’re referring to yourself as a junior developer, stop. It’s not doing you any favors. You are limiting your employment potential. What company or recruiter is going to consider a “junior” when they are advertising for a mid-level developer role?

You don’t want them to say: “Hang on a minute. You meet all the job criteria and have several years experience. But sorry, we aren’t looking for a junior.”
#+END_VERSE


*If you have a niche, emphasize it*

强调自己的技术优势

*Tidy up your Github account*

好好管理自己的github账号，把一些过期和废弃的项目删除掉，展现一些可以表现自己技术水平的projects是比较好的。

#+BEGIN_VERSE
My advice — being active on GitHub is great, but if you are never going to finish those projects, delete them. You need to make sure that any hiring manager or recruiter is seeing the projects that you have completed and the ones that you are proud of — not the ones that you “were meaning to work on but didn’t have time to.”
#+END_VERSE

*Passion vs. Experience*

对于用人单位来说，Passion和Experience哪个比较重要呢？答案是 [[https://softwareengineering.stackexchange.com/questions/37339/choosing-between-two-programmers-experience-vs-passion][Passion]]

#+BEGIN_VERSE
Hire the inexperienced programmer with a passion for the craft. A passionate programmer will learn quickly, care about their work and enjoy doing it. I’ve worked with both types of programmers and I would always hire the passionate type over the experienced.

People who don’t care about their work eventually lead to problems in quality as well as in meeting deadlines.

Since you explicitly state that you have the resources to train someone, this is a no brainer. Hire the passionate programmer.
#+END_VERSE

所以对于开发者来说，展现自己对于技术的热情，是打造个人品牌的核心。
