#+title: 重要的东西，往往是看不见的
from 硅谷王川公号2019合集

决定房价的最重要因素是位置，位置背后最根本的因素是就业市场的增长和人口的增长。而影响就业市场的因素，往往是看不见的， 甚至非常遥远的。08 年金融危机后，高科技行业的迅速增长，远超其它传统行业。世界经济增长的红利，基本上被高科技最发达的少数几个区域获取了。行业兴衰趋势，这个根本因素，是看多少房子，也看不出来的。

南加州的洛杉矶县，拥有大量军工企业， 1991 年底苏联突然解体后，美国削减军费，大批军工企业裁员，洛杉矶县房价指数从 1991 年的 95 下跌到 1996 年的77. 一些城市的房价下跌一半以上，很多人因此破产。房价指数到 2000 年后才创新高。

历史数据的预测价值是有限的。重要的东西，往往是看不见的。

----------

如果要猜测，半导体行业和 IT 行业两种截然不同的现象的原因，恐怕要追溯到两个行业发展的不同历史路径。

半导体行业，兴起于七八十年代，当时大批台湾和东南亚的华裔工程师入行，几十年下来自然会留下来极少数成为行业的高管。

印度裔工程师大规模移民美国，是九十年代的事情了，集中在 IT 外包行业。过去十年 美国 H-1 工作签证一半以上的配额都给印度人了 （这后面又有更复杂的历史原因，但现实就是如此）。

公司发展招新人，如果别的地方没有大差别，管理层都会有更大概率选择和自己文化接近，各方面更相似的人， 然后这种趋势在发展中不断自我强化。这是人性，是客观的群体现象。这不是一个简单的靠个人练好口语，提高交际能力就可以解决的问题。

----------

信贷扩张的时候，离钱最近的公司和个人，受益最大。他们拿到央行的钱, 然后去放贷，投资，所到之处，房价和其他资产价格被推高，形成正反馈，还会催生各种影子银行体系的繁荣， 这时候有房有资产的人的金融财富迅速增加，看上去像天才。各种高逼格的致富方法论也应运而生。

其他大部分人还没有被增加的流动性所惠及，老老实实出卖体力赚辛苦钱的人还在九九六努力挣扎，蜂蜜还没有流到外围，暂时还看不到日常生活物资的价格上涨， 但是人们已经要为房价的上涨买单，或者被央行人为制造的价格信号所诱惑也去参与投机。

当蜂蜜渗透到外围，开始影响日常生活物价指数时，央行会采用各种手段减少信贷扩张，平衡物价指数。但这时可能会产生意想不到的效果， 一些金融资产的市值会因为来自信贷源头的蜂蜜的减少而突然暴跌，这就是 2018 年底美联储不断缩表的后果，导致 S&P 指数一度下跌到 2300 点左右。直到美联储官员出来表态要迅速结束缩表， 才稳定了市场。可以参见笔者的老文章。


----------

投资创业者想要赚钱，但是如果对于商业银行，影子银行，中央银行，信贷的创造，扩张和萎缩的机制，缺乏一个基本的理解，不能顺大势而为，难道不是一件极为荒谬可笑的事情吗？

多少家长望子成龙，希望孩子能够上名校学上好专业，但是如果不能从事离央行，离蜂蜜源头最近的行业，而一直在蜂蜜传递链下端的很远处苦苦修行，和瞎子摸象，缘木求鱼又有什么区别？

重要的东西，往往是看不见的。

----------

理工科做技术的人，类似古代的武将，虽然出活出力流血流汗，但是如果不能掌握产业链各个环节上关键资源的控制力，则往往悲催的沦为他人的工具，其下行的风险远远大于上行的回报。

有些理工科背景者长期唯技术论，对于整个产业链的架构/市场定位等等，缺乏基本理解，迷恋于一种对于硬核技术的自我陶醉 （类似于天天慷慨悲歌，打打杀杀的武将），对自己的弱点和短板缺乏基本认识，对于非技术人员有一种（出于无知而导致的）鄙视情绪，其状态和这些武将非常类似。

一旦行业变迁，老技术不再需要，突然失业，一切从零开始，则悔之晚矣。

古代名将即使如蒙恬者，埋头专注于自身业务的发展，缺乏对朝中权力中心决策层变迁的远见和敏感，以至于秦始皇去世后，李斯被赵高说服矫诏，把蒙恬和扶苏诛杀。蒙恬在掉脑袋之前，都没想清楚这背后的逻辑，否则不至于如此被动，而缺乏反击的意志。

如果稍微有些大局观，比如明朝的戚继光，就知道和上面的文官保持良好关系，经常给张居正送各种大礼，以保证信息传递的流畅和不失真，以及自身地位的巩固。

重要的东西，往往是看不见的。有些东西，看见的时候，才发现脑袋马上就要搬家了。

只有少数有心人，不断主动探索发掘，不断感知思考， 方可化解危险于无形，把握机会于无声。
