#+title: 乔纳森传(Jonathon Ive)

乔纳森不只在工艺方面非常熟练，还特别擅长与人交流他的想法。怀廷说：“他做的事情，别人都没做过。当你成为一名设计师的时候，就必须能够将自己的想法传达给不懂设计的人。这些人将来可能会为你提供资金或者生产这种产品，你必须得让他们对产品的性能以及产品的生产产生兴趣。而乔纳森就具备这样的能力。”

乔纳森在新的工作场所工作和在纽卡斯尔时一样高效。韦弗说：“一些设计师认为做的研究越多，解决方案越好。我个人更相信常识和直觉。乔纳森的优势就在于他能迅速地抓住挑战的本质，并设计出直观的解决方案，这些方案精妙可行、注重细节，这在年轻人中十分少见。”

合伙人对其信心十足，在他们眼中，他是个热情、勤劳又有团队精神的队友。格雷回忆说：“他性格安静，极具幽默感。在工作室里，他从来都不是一个爱招摇的人。他工作高效，能够很好地完成自己的任务。他工作特别努力、特别勤奋。工作量大得惊人，同时完成质量又极高。他是个非常多产的设计师，常常能够在很短的时间内想出很多好主意，而且他不仅能口头讲述这些好主意，还能通过完美的制图术将它们清楚地表达出来。”

乔纳森逐渐意识到他不适合做设计咨询工作。他热爱设计，但是他发现通过必要的让步来实现任务非常苦恼，他一直在抵制一个事实——那就是在小规模的合伙人关系中，每个设计师都要扮演推销员的角色。 “我太天真了，”乔纳森说道，“我刚从大学毕业不久，但是我通过设计一系列不同的产品学习到了很多：从发梳和陶器到重型机床和电视机。重要的是，我找到了我擅长的和不擅长的事情。我终于清醒地知道了自己想做什么。我真的只对设计感兴趣。我对创立事业既不感兴趣，也不擅长。”

某些员工认为，乔纳森年纪太轻、缺乏经验，这些都是值得争论的。他才29岁，但是布伦纳之所以推荐乔纳森，是因为布伦纳钦佩他坚决的执行力。布伦纳说：“他能做到始终如一，内心十分强大，而且很有野心，这里说的野心并不是很多人都有的那种‘把它扛在自己的肩膀上’的野心，他的强大表现在坚持不懈上，他要做的事一定会做好。”

那时乔纳森说：“这是个绝对不会创新的公司，我们失去了自己的特色，而只关注争夺领导权。”

在乔纳森辞职之前，他的新上司乔恩·鲁宾斯坦（Jon Rubintein）说服了他。鲁宾斯坦刚刚被任命为苹果硬件部门的负责人（也是接下来史蒂夫·乔布斯就任时他的工作），他提升了乔纳森，并告诉他，柳暗花明又一村。 “我们告诉他，我们会努力渡过当前的难关，一旦我们扭转了公司的情况，我们就创造了历史。这就是我们为了把他留在苹果所说的话——自此以后，设计在公司逐渐得到真正的重视。”

“苹果公司所进行的设计比我们任何一家同行业的竞争对手都要复杂得多。”邓恩说，“苹果一体机的表面不像是计算机产业的设计，而更像航空航天和汽车制造产业的设计……我们是在挑战极限。”

在iMac一体机没有软盘驱动器一事上，乔纳森站在苹果一边。他说：“关于新产品没有软盘驱动器这个问题，我不能代表苹果公司回答你。我只能给你我的回答，‘当人在前进的时候，总是需要把一些东西抛在身后。只要我还有一口气在，我就会继续争论下去，软盘驱动器实在是过时的技术了。我听过很多次这样的抱怨，但是如果前进的道路上没有摩擦，你的脚步就不会像自己希望的那样坚定。’”

如果你与我们一样怀揣抱负，就会发现以往那套产品开发的老方法不会奏效。当你面临极其复杂的挑战之时，开发产品就更要团结协作、统筹兼顾。

“当你的野心变得和我们这群人一样大时，你就会发现，传统的产品研发方式根本不合适。”乔纳森说道，“当你面临复杂的挑战时，你必须采取一种可以促进相互合作，使各个部门更加协调的方式来开发你的产品。”

乔纳森的关注点是设计，”鲁宾斯坦在2012年接受电话采访时说，“设计就是他所关心的全部。但是，尽管设计的重要性不言而喻，我们还是要去解决电气工程、规模化生产、售后服务以及技术支持等问题。公司有许多不同的部门，每一个部门都有他们自己的声音，他们的声音也许不具有投票表决的作用，但是却代表着他们各自的想法。而我的工作就是去平衡每一个人的需求。很多时候，大家都需要做出妥协和让步。”

关于iBook的最初设想千差万别。这些设想都来自于头脑风暴会议，而不是公司内部的焦点小组座谈会或是市场调查结果。“我们不会开焦点小组座谈会，因为这本身就是设计师该干的事儿，”乔纳森说，“让其他人根据当下的产品去设想未来的产品设计是不可行的，因为他们对未来可能出现机遇的感知能力几乎为零。”

“仅仅把狂热的激情放在显而易见的事物上是远远不够的，你需要把注意力和热情放在人们容易忽略的细节上，这才是起决定性作用的。”

库克也有着丰富的经验，在2004年和2009年乔布斯不在的时候，他曾临时担任CEO。根据接受本书采访的苹果内部人员透露，一般情况下，库克都是个和蔼可亲的人，他善于听取不同意见并希望得到每一个人的理解，这使得员工们跟他一起工作更简单，因为他不像乔布斯那样固执。

乔纳森的朋友们透露说，尽管一直以来，乔纳森用心地将自己的形象维护成一个说话轻声细语的英国绅士——但同时，他也是个具有竞争意识的人。虽然他对自己的工业设计团队慷慨大度，一直充当着保护者的角色，但乔纳森也很有自我意识，从来不怯于张扬自己在想法和创意上的功劳。在与福斯特尔以及鲁宾斯坦的竞争中，他也展露了性格中的另一面：完全不惧怕与主管们较量。在一些曝光了的公司事故中可以看出，当乔纳森决定进入诸如此类纠纷时，他不仅有决心，也有足够的实力让自己成为赢家。

乔纳森解释说，在苹果进入低谷期时，他在乔布斯身上学到了这一课。“苹果曾经濒临破产。但是，就像人们通过死亡能够学会更好地生活一样，我在一个濒临死亡的公司中明白了关于大企业的道理，”他在会上说道，“你可能会认为，当公司因为资金问题不得不破产时，你必须将注意力集中在赚钱上，才能救公司于水火之中。但是乔布斯却没有把这当成当务之急。他发现，问题在于产品还不够好。因此，他给出的救急方法是，‘我们需要做出更好的产品。’这与之前救助公司的方式完全不同。”

另一方面，乔布斯著名的专注精神也是乔纳森试图传承的重点。乔布斯总是说，所谓专注，并非是指认同产品，而是对产品说不。在乔纳森的带领下，对仅仅达到了“不错”而非“卓越的”的产品，苹果总是高度一致地“说不”。 “在很多时候，当我们一直准备某个产品的大批量生产时，却总是突然意识到，我们太过于将注意力集中在某些优点上了。在办公室讨论时，我们总是将优点讲得太大声。对我来说，这永远是危险的所在，因为当我大声谈论某事时，我同时也在不断说服自己，事实确实如此，产品确实很棒。”他说。

