#+title: 天才引导的历程(Journey through Genius)

https://book.douban.com/subject/1030974/

从一个特殊例子引出放之四海而皆准的一般结论，很可能是危险的，而历史学家注意到，在法老统治下的埃及这种独裁社会，必然会产生这种武断的数学方法。在古埃及社会，民众习惯了无条件地服从他们的君主。以此类推，当时，如果提出一种官方的数学方法，并断言“你会发现答案是正确的”，则埃及臣民是不会要求对这种方法为什么正确作出更详尽的解释的。在法老统治的土地上，民众只能唯命是听，让你怎么做你就怎么做，不论是建筑宏伟的庙宇，还是解答数学题，一概如此。那些敢于怀疑体制者必然不得善终。

通俗一点说，我们可以认为，代数数就是我们在算术和初等代数中遇到的那些“容易”或“熟悉”的量。例如，所有整数都是代数数，所有分数及其平方根、立方根等也都是代数数。 相反，如果一个数不是代数数，那么它就必然是超越数——也就是说，这个数不是任何带有整数系数多项式方程的解。同其比较简单的代数数亲族相比，超越数要复杂得多。根据定义，显然，任何实数不是代数数，就是超越数，但不可能两者兼之。这就是严格的二分法，犹如一个人不是男的，就是女的，绝没有中性可言。

从现代观点来看，一个逻辑系统总是始于一些未经定义的术语，而以后所有的定义都与这些术语有关。人们肯定会尽力减少这些未定义术语的数量，但这些术语的出现却是不可避免的。对于现代几何学家来说，“点”和“直线”的概念就始终未经定义。像欧几里得给出的这些陈述，有助于我们在头脑中形成某些图像，并非完全没有益处。但是，以精准的、合乎逻辑的定义要求来看，这最初的几条定义是不能令人满意的。

但是，按照欧几里得的规则，这种做法却是不允许的，因为在他的著作中，没有一个地方提出一种公设，允许用这种方法转移长度。因此，数学家们常常称欧几里得的圆规是“可折叠的”。就是说，虽然圆规完全有能力作圆（如公设3所保证的），但只要把圆规从平面拿起，它就闭拢了，无法保持打开的状态。

造成这种情况的原因究竟是什么呢？欧几里得为什么不再增加一条公设，以支持这一非常重要的转移长度的方法呢？答案十分简单：他不需要假定这样一种方法作为公设，因为他将这种方法给证明出来了，并将其作为第一卷的第3个命题。也就是说，虽然欧几里得的圆规一从纸上拿起来就变成“折叠”的了，但他的确提出了一种十分巧妙的转移长度的方法，并证明了他的方法为什么奏效。欧几里得令人仰慕之处就在于，他尽力避免假定他实际上能够推导出来的公设，因而使公设的数目控制在绝对最小的范围内。

实际上，许多数学家都坚信这第5条公设其实就是一条定理。他们认为，既然欧几里得不需要假定可用圆规转移长度，那他也不需要假定这样一条公设，因为他完全可以根据更基本的几何性质来证明这一点。有证据表明，欧几里得自己也对这个问题感到有点儿不安，因为他在第一卷的演绎中一直尽力避免应用这一平行线公设。也即，在前28个命题的推导过程中，他对其他的公设都运用自如，想多早用就多早用，想用多少次就用多少次，可唯独这第5条公设，他一直就没有用。但诚如“后记”中所述，怀疑是否需要这一公设是一回事，作出实际证明则是另一回事。

从这一命题中，可以很容易地得出一个令人吃惊的推论：在非欧几何中，并非所有三角形的内角和都相等！欧几里得几何中这一最基本的性质（在许多几何推理过程中都占据着重要的地位），在我们步入非欧几何领域时，却必须予以抛弃。

迄今为止，人们仍然劳而无功。18世纪的数学家莱昂哈德·欧拉在其遗作中证明，任何偶完全数都一定适合欧几里得的公式。换言之，如果N是一个偶完全数，那么就一定存在一个正整数n，使得 N=2n（1+2+4+8+…+2n） 其中，括号中的项必定是（梅森）素数。
