#+title: 凯恩斯大战哈耶克

#+BEGIN_EXPORT HTML
<iframe width="560" height="315" src="https://www.youtube.com/embed/zimtDfsTAUU" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
#+END_EXPORT

下面是歌词，视频看起来凯恩斯的思想在一开始就被接受，而大家对哈耶斯的自由市场理论最开始并不感冒。

#+BEGIN_VERSE
Fear the boom and bust
涨落可惧
We’ve been going back and forth for a century
我们这样针锋相对已经一世纪
[Keynes] I want to steer markets,
[凯恩斯]我想要掌舵市场，
[Hayek] I want them set free
[哈耶克]我想让市场自由，
There’s a boom and bust cycle and good reason to fear it
经济总是有涨有落，我们当然会畏惧
[Hayek] Blame low interest rates.
[哈耶克]责怪利率太低吧。
[Keynes] No… it’s the animal spirits
[凯恩斯]不…应该责怪人的“动物精神”
[Keynes Sings:]
[凯恩斯 唱：]
John Maynard Keynes, wrote the book on modern macro
约翰•梅纳德•凯恩斯，撰写了现代宏观经济学
The man you need when the economy’s off track, [whoa]
在经济偏离轨道时，你就需要他，[哇～]
Depression, recession now your question’s in session
经济萧条，经济衰退，现在你开始问这一连串的问题
Have a seat and I’ll school you in one simple lesson
找个座位做好，我立马就给你上这简单的一课
BOOM, 1929 the big crash
嘣，1929年的市场崩盘
We didn’t bounce back—economy’s in the trash
我们看不到反弹—经济情况一塌糊涂
Persistent unemployment, the result of sticky wages
持续失业，是粘性工资的结果
Waiting for recovery? Seriously? That’s outrageous!
坐等经济复苏？有没有搞错？完全不能接受！
I had a real plan any fool can understand
我有一个连傻瓜都能明白的计划
The advice, real simple—boost aggregate demand!
我的意见，非常简单—提高总需求
C, I, G, all together gets to Y
C(消费),I(投资),G(政府支出)，所有这些加起来就是Y(经济总量)
Make sure the total’s growing, watch the economy fly
只要确保总量增长，你就一定能看到经济走高
We’ve been going back and forth for a century
我们这样针锋相对已经一世纪
[Keynes] I want to steer markets,
[凯恩斯]我想要掌舵市场，
[Hayek] I want them set free
[哈耶克]我想让市场自由，
There’s a boom and bust cycle and good reason to fear it
经济总是有涨有落，我们当然会畏惧
[Hayek] Blame low interest rates.
[哈耶克]责怪利率太低吧。
[Keynes] No… it’s the animal spirits
[凯恩斯]不…应该责怪人的“动物精神”
You see it’s all about spending, hear the register cha-ching
你看，这事儿就是关于支出，听那收银机叮叮作响
Circular flow, the dough is everything
让现金流动，金钱就是一切
So if that flow is getting low, doesn’t matter the reason
所以如果流动性太低，其他一切都无能为力
We need more government spending, now it’s stimulus season
我们需要更多的政府支出，现在是采取经济刺激的时候了
So forget about saving, get it straight out of your head
所以储蓄去见鬼吧，把这个想法尽早扔出你的脑瓜
Like I said, in the long run—we’re all dead
就像我说的，从长期看来—我们都将不复存在
Savings is destruction, that’s the paradox of thrift
储蓄只有毁灭作用，这就是节俭的悖论
Don’t keep money in your pocket, or that growth will never lift…
不要把钱留在你的口袋，否则经济增长就不能实现

because…
因为…
Business is driven by the animal spirits
商业是由“动物精神”所驱使的
The bull and the bear, and there’s reason to fear its
牛市和熊市交替，我们有理由畏惧
Effects on capital investment, income and growth
它对资本投资，收入和增长的影响
That’s why the state should fill the gap with stimulus both…
这就是为什么国家应该用经济刺激填补这个空缺，
The monetary and the fiscal, they’re equally correct
财政和货币刺激应该双管齐下，他们都同样正确
Public works, digging ditches, war has the same effect
公共事业，开河挖沟，发动战争都有同样的效果
Even a broken window helps the glass man have some wealth
打破一扇窗户甚至也能给玻璃匠带来财富
The multiplier driving higher the economy’s health
乘数效应能带动经济向更高处发展
And if the Central Bank’s interest rate policy tanks
但如果中央银行搞砸利率政策
A liquidity trap, that new money’s stuck in the banks!
流动性陷阱就会把新钞都困在银行
Deficits could be the cure, you been looking for
赤字将被填平，这不就是你想要的么
Let the spending soar, now that you know the score
就让政府支出走高吧，然后你就知道会怎样了
My General Theory’s made quite an impression
我的经济总论会让你大开眼界的
[a revolution] I transformed the econ profession
[一场革命！]我改造了经济学界
You know me, modesty, still I’m taking a bow
你们都认识我，谦虚的我，我会向诸位鞠躬
Say it loud, say it proud, we’re all Keynesians now
大声说，自豪地说，我们现在都是凯恩斯主义者
We’ve been going back and forth for a century
我们这样针锋相对已经一世纪
[Keynes] I want to steer markets,
[凯恩斯]我想要掌舵市场，
[Hayek] I want them set free
[哈耶克]我想让市场自由，
There’s a boom and bust cycle and good reason to fear it
经济总是有涨有落，我们当然会畏惧
[Keynes] I made my case, Freddie H
[凯恩斯]我已经说明了我的立场， Freddie H（哈耶克，戏称）
Listen up , Can you hear it?
仔细听好，你都明白我说的了么？
Hayek sings:
哈耶克 唱：
I’ll begin in broad strokes, just like my friend Keynes
就像我的朋友凯恩斯所述，我也从大处说起，
His theory conceals the mechanics of change,
他的学说隐藏了变化产生的机理，
That simple equation, too much aggregation
那个简单的等式，把太多的东西加总在一起
Ignores human action and motivation
忽略了的是人类行为和背后的动机
And yet it continues as a justification
但是它还继续为一些错误的政策提供支持
For bailouts and payoffs by pols with machinations
比如，那些“紧急财政援助”以及那些为政客的阴谋而买的单
You provide them with cover to sell us a free lunch
你为他们提供掩护，让他们卖给我们免费午餐
Then all that we’re left with is debt, and a bunch
现在我们都为此负债，而且负债累累，
If you’re living high on that cheap credit hog
如果你想利用廉价的信用过上富足的生活
Don’t look for cure from the hair of the dog
就不要试图用同样的方法来解决当下的困局
Real savings come first if you want to invest
实际储蓄上升要先于投资
The market coordinates time with interest
市场用利率来协调时机
Your focus on spending is pushing on thread
你所强调的支出将不会奏效
In the long run, my friend, it’s your theory that’s dead
在长期看来，我的朋友，是你的学说将不复存在
So sorry there, buddy, if that sounds like invective
所以抱歉了，我的朋友，如果我说的太过恶毒
Prepared to get schooled in my Austrian perspective
你还是准备好来我的奥地利学派重新学习吧
We’ve been going back and forth for a century
我们这样针锋相对已经一世纪
[Keynes] I want to steer markets,
[凯恩斯]我想要掌舵市场，
[Hayek] I want them set free
[哈耶克]我想让市场自由，
There’s a boom and bust cycle and good reason to fear it
经济总是有涨有落，我们当然会畏惧
[Hayek] Blame low interest rates.
[哈耶克]责怪利率太低吧。
[Keynes] No… it’s the animal spirits
[凯恩斯]不…应该责怪人的“动物精神”
The place you should study isn’t the bust
你该研究的地方不是经济的低谷
It’s the boom that should make you feel leery, that’s the thrust
反倒是经济的高潮应该然给你提高警惕，这才是关键
Of my theory, the capital structure is key.
在我的学说里，资本结构是关键。
Mal-investments wreck the economy
错误的投资会搞垮经济
The boom gets started with an expansion of credit
经济高潮始于信用的扩张
The Fed sets rates low, are you starting to get it?
联邦储备把利率设的太低了，你开始明白过来了么？
That new money is confused for real loanable funds
这些新增的钞票让人错以为它们是实际可借的资产
But it’s just inflation that’s driving the ones
但其实那只不过是通货膨胀而已
Who invest in new projects like housing construction
而通胀让人们去投资住宅建设项目
The boom plants the seeds for its future destruction
那经济的走高为它未来的毁灭种下了种子
The savings aren’t real, consumption’s up too
储蓄增长并非实际，消费却也跟着增长
And the grasping for resources reveals there’s too few
但当人们开始寻求真正的经济资源，他们就会发现其实资源有限
So the boom turns to bust as the interest rates rise
所以经济增长就会随着利率上升而破灭
With the costs of production, price signals were lies
当生产的成本上升，价格上升的信号就成为了一个谎言
The boom was a binge that’s a matter of fact
经济增长只是一场狂欢，这就是事实情况
Now its devalued capital that makes up the slack.
而今贬值的资本将连本带利偿还一切
Whether it’s the late twenties or two thousand and five
无论是上世纪20年代末，还是2005年
Booming bad investments, seems like they’d thrive
错误投资所带来的经济发展，看上去好像一片繁荣（，实则不然）
You must save to invest, don’t use the printing press
你必须先有储蓄才能投资，别指望用印钞机来解决问题
Or a bust will surely follow, an economy depressed
否则泡沫必会破灭，而经济将会面临萧条
Your so-called “stimulus” will make things even worse
你所谓的“经济刺激”只会起反作用
It’s just more of the same, more incentives perverse
它犯了同样的错误，而且激励设计更加荒谬
And that credit crunch ain’t a liquidity trap
且信用紧缩并不是流动性陷阱
Just a broke banking system, I’m done, that’s a wrap.
这银行系统错误连篇，我说完了，就这样了。
We’ve been going back and forth for a century
我们这样针锋相对已经一世纪
[Keynes] I want to steer markets,
[凯恩斯]我想要掌舵市场，
[Hayek] I want them set free
[哈耶克]我想让市场更自由，
There’s a boom and bust cycle and good reason to fear it
经济总是有涨有落，我们当然会畏惧
[Hayek] Blame low interest rates.
[哈耶克]责怪利率太低吧。
[Keynes] No… it’s the animal spirits
[凯恩斯]不…应该责怪人的“动物精神”

“The ideas of economists and political philosophers, both when they are right and when they are wrong, are more powerful than is commonly understood. Indeed the world is ruled by little else. Practical men, who believe themselves to be quite exempt from any intellectual influence, are usually the slaves of some defunct economist.”
John Maynard Keynes
The General Theory of Employment, Interest and Money
“无论是对是错，经济学家和政治哲学家们的想法都是非常有力的。我承认，这个世界表面上来看是被一些微不足道的个体所控制着的。那些从事实际控制工作的个体会觉得他们的行为是不受学术世界的影响的。然而很多时候，他们只不过是那些已故的经济学家的奴隶而已。”
约翰•梅纳德•凯恩斯
《就业、利息和货币通论》

“The curious task of economics is to demonstrate to men how little they really know about what they imagine they can design.”
F A Hayek
The Fatal Conceit
“经济学有一个有意思的作用就是向人们证明，对于那些我们自以为可以设计好的机制，我们的知识其实远远不够。”
弗里德里希·奥古斯特·冯·哈耶克
《致命的自负》
#+END_VERSE
