#+title: 向前一步(Lean In)

女人内心的自我定位也常常让她们经历煎熬，如果不能做个“好”妈妈，首先跟她们过不去的是她们自己。美国前国务卿奥尔布莱特曾说：“职场中的母亲都有一个名字，叫内疚。”更有趣的是，女人也不肯轻易放过其他女人。“你这么忙一定没时间陪孩子吧。会不会很难过？”这样的提问绝对是一个女人对另一个女人的道德审判。

但是，女孩在学校里被赞赏的“善于服从”、“先举手，被叫到再回答”的行为，在工作环境中并不被倡导。事业发展所依赖的通常是敢于冒险和自我表现，然而人们并不鼓励女孩表现出这样的特质。这也许就解释了为什么女性在学习时期获得的成就，并没有相应地提高女性在高级职位中的比例。所以，在受过教育的劳动者中，初级岗位上挤满了女性；而同时期的领导岗位却被男性占满。

然而，在今天的世界中，人类不再像古代那样必须在野外觅食打猎，我们对领导意志的渴望在很大程度上是一种被文化催生和强化的特质。个人怎样决定自己能做什么、应该达到怎样的目标，在很大程度上是由我们的社会期望塑造出来的。

当父母都拥有属于自己的事业时，孩子、父母和婚姻三方面都能得到极大的发展。数据清楚地揭示，分担经济来源和抚养下一代的责任会减轻母亲的负疚感；若父亲提高对家庭的参与度，孩子也会成长得更开朗、更健康。

很多人尤其是女人，当她们所取得的成绩被人称赞时，会感觉那些称赞是骗取来的。她们常常感到自己不值得被认可，不配受到称赞，并心存负疚，就好像犯了什么错。即便那些在自己的领域成就斐然，甚至已是专家级别的女性，她们仍然摆脱不了这样一种感觉：我其实只是个技术水平或能力都很有限的冒牌货，现在的荣誉不过是因为碰巧被大家发现了而已。

事实证明，缺乏自信会成为一种自我实现的预言。我真的不知道怎么告诉自己或别人，一定要发自内心地相信自己就是做某项工作的最佳人选。

以我的经验而言，女性对于角色变化、寻求新的挑战则更为谨慎。我常常发现自己总是在试图说服她们进入新的领域工作。我已经和女性员工有过多次谈话，她们对我的鼓励通常作此回应：“我在这方面可能不是很擅长”，“这项新工作听上去很令人兴奋，但我没有类似的工作经验”，或“现在的工作中我还有许多要学习的”。印象中我似乎从没与男员工有过这样的对话。

当我的事业刚起步时，我拒绝过很多机会，因为当时我想‘我这个水平还胜任不了这项工作’或是‘我对这个领域还不了解’。现在回想起来，在某个特定时期，迅速学习并做出成绩的能力才是最重要的。如今我常跟人提到，当寻找你的下一个目标时，其实没有所谓的完全合适的时机。你得主动抓住机会，创造一个适合自己的机会，而不是一味地拒绝。学习能力是一个领导者必须具备的最重要的特质。”

从儿时起，被文化所强化的信号就警告我不要被贴上“太聪明”或“太成功”的标签。这一点在我很小的时候就深有体会。作为一个女孩，被认为很聪明尽管在很多方面都有好处，但这并不会让你在男生中变得特别受欢迎，或是变得更有吸引力。

谈判成功的目标是既要达到预期，又要继续让别人喜欢自己。哈佛大学肯尼迪政府学院研究性别与谈判的汉娜·鲍尔斯教授认为，女性可以通过将这两个目标结合到一起，来提高谈判的成功概率。

《赫芬顿邮报》的联合创始人阿里安娜·赫芬顿（Arianna Huffington）相信，学会接受别人的批评对女性来说是必要的一步。在她事业的初期，阿里安娜发现，直言不讳的成本就是不可避免地冒犯某些人。她认为，告诉女性不要把批评放在心上这并不现实，她也不想这么做。她建议我们应该让自己的情感有所释放，要去面对并体会因受到批评而产生的愤怒或伤感等情绪；之后，便立即继续前进。她以孩子为例：一个小孩子可以在这一刻大哭，下一刻就跑去玩耍。对我来说这是个很好的建议。我当然希望自己能坚强到对别人的话毫不在意，但经验告诉我，这通常是不可能的。不过，允许自己不开心甚至伤心难过，然后继续前行——这是我可以做到的。

在我加入脸谱网不到6个月时，扎克伯格和我进行了第一次正式的工作总结。他告诉我，想要“赢得每个人的欢心”这种想法会阻碍我的发展。他说，当你想要让事情有所改变时，你不可能取悦每个人；而如果你去取悦每个人，你就不会获得充分的进步。扎克伯格说得很对。

人们最常用“梯子”来比喻职业生涯，但这个概念已不再适用于大多数人。据统计，2010年至今，美国人在18~44岁之间会换11次工作。这就意味着加入一个组织或进入一个公司，待在那里一步步往上爬的时代已经过去了。戈勒引用了帕蒂·塞勒斯那个更为恰当的比喻：“职业生涯是方格架，而不是竖梯。” 正如戈勒所描述的，竖梯会限制人的行动——要么往上爬要么往下退，要么站在梯阶上要么跌下来；而方格架能让一个人拥有更多探索的可能。要爬到梯子的顶端只有一种方式，但要爬到方格架的顶端则会有很多方式。方格架的比喻适用于每个人，尤其适合那些处于事业初期、转行阶段、由于外部障碍止步不前，或休息一段时间准备重新进入职场的女性。和僵直的梯子相比，女性若能够走出一条时上时下、迂回曲折甚至偶尔会误入死胡同的独特路线，才会为自我实现提供更好的机会。此外，方格架可以为更多人提供更宽广的视野，而不是只有那些站在最顶端的人才能看到最美的风景。但是在竖梯上，大多数攀爬者都不得不盯着上面一个人的屁股。

一个人的事业并不总是需要在一开始就做好计划，这在当前就业市场不景气的大环境下尤其具有安慰作用，因为求职者总是不得不先接受能找到的工作，然后再稳步发展。我们都想找到能让自己兴奋并且感兴趣的工作或职位，但是，这个寻找的过程既需要明确的目标，也需要一定的变通。所以，我建议大家应该同时确定两种目标：长远的梦想和“18个月”的短期目标。

施密特给了我最好的建议：他用手盖住我的电子表格，告诉我不要犯傻了。他解释道，当选择一份工作时只有一个标准是重要的，就是它是否能让你快速成长。当公司快速发展时，要做的事情就会多到人手不够；而当公司发展放缓甚至停滞时，就会人浮于事；公司里开始钩心斗角时，其发展也会停滞，每个人都会动摇。他告诉我：“如果有人邀请你上一艘火箭，你不要问上去之后坐哪儿，你只要上去就可以了。”这番话让我当即就下定了决心。当时谷歌公司的规模很小，公司结构也还没理顺，但它就是一艘火箭。最重要的是，我已经深深地认同了这艘“火箭”的使命。

接受风险，选择成长，挑战自我，在应该晋升的时候主动争取更高的职位（当然，一定要面带微笑）——这些都是自我职业管理的重要内容。引用一句我最喜欢的话，它来自才华出众的黑人女作家艾丽斯·沃克（Alice Walker）：“放弃自己的力量最常见的方式，就是认为自己毫无力量。” 不要等着别人给你力量，就像那顶皇冠，它也许永远不会出现。你想想，谁会戴着皇冠攀爬方格架呢？

这样的提问会立刻毁了一个人的心情，这就好比追问情绪不佳的朋友：“你在想什么呢？”和我聊过这个问题的每位女性高管几乎都经常遭遇此类请求，她们的反应也很一致：“噢，每次遇到不认识的人要求我做他们的导师时，我都不知道该说什么。”建立互动让人很受用，但也很尴尬。即使是具有极大影响力的美国著名主持人奥普拉·温弗瑞也承认，当有人请她做导师时，她感觉“不太自在”。她解释道：“当我提及某件事时说‘我想看看它怎么发展’，这就已经是在做指导了。”

不管寻找导师有多重要，它都不太可能通过一句“你能当我的导师吗？”就能发展起来。只有在双方都感到这是一种通过努力才能获得的联结时，才能建立最强有力的指导关系。

研究显示，导师对门生的选择基于其外在表现和内在潜力。人们会本能地投资给那些才华出众以及能因资助而真正受益的人。在被指导者能善用时间、真心接受反馈时，导师会继续为之投入。这种关系可以发展为友谊，但仍然是以工作与职业关系为基础。考虑到这一点，我认为我们向年轻女性传达了错误的讯息，事实上不是“找个导师你就能变得优秀”，而是“脱颖而出，你才会得到一位好导师”。

交流的最佳效果来自谈吐得体且态度真诚，其关键点在于你不需要直愣愣地冒出大实话，而是适当修饰后的诚实表达。在不伤及别人的前提下又能实话实说，这对一些人来说轻松自如，而对另一些人来说则是一门需要学习的技巧。我在这方面也尚待提高，还好我得到了很多帮助。

分享自己的情绪，能够帮助我们建立更深层的人际关系。工作的积极性源自我们对事情的关注度，也源自对他人的关心。为了做到真正关心别人，我们必须理解他们——理解他们喜欢什么、不喜欢什么，理解他们的感觉和想法。不管男人还是女人，在做决定时都会受到情绪的驱使。承认情绪的作用，去面对它、接纳它，这会让我们更好地工作，建立更顺畅的人际关系。 我以前也不太理解这一点。我常常想，专业水准高意味着处事有条不紊，精力高度集中并且能把工作和个人生活分开。最初在谷歌的时候，奥米德·柯德斯塔尼和我每周都会一对一地开会。我会带着打印好的日程表走进他的办公室，开门见山地讨论工作。我以为这显得很有工作效率，但我的同事蒂姆·阿姆斯特朗（Tim Armstrong）（后来担任美国在线公司首席执行官）善意地把我叫到一边给我提了个建议。他说，既然只有我和奥米德两个人开会，那么在会前我应该先和他做一个简单的沟通与问候。很显然是奥米德托蒂姆告诉我这一点的。于是我做了些调整。之后，每次开会之前，我都会先问候奥米德最近怎么样。这是一堂很好的课，只谈公事并不总是最佳的工作方式。

当然，也不是所有公司和同事都会如此宽宏大量、富有同情心。但我还是认为这方面会有进步，至少个人生活和工作之间的界限正在变得模糊。而且，研究领导力的杰出专家，如马库斯·白金汉（Marcus Buckingham）等人正在挑战传统的领导力概念。他们的研究显示，把领导力理解为一连串精确定义的特征（比如有战略眼光、分析能力、以业绩为导向）的理论已经站不住脚了。正好相反，真正的领导力来自于真诚的表现，以及不太完美的个性。他们相信领导者应该勇于追求真实而非完美。这种转变对女性来说是个好消息，因为女性常常会感到在工作环境里应该压抑自己的情绪，努力表现得像男性一样。男性也有脆弱、无助的时候，所以这对他们来说也是个好消息。

经典的情景是这样的：一个雄心勃勃、小有成就的女性走在充满挑战的职业道路上，内心却在想着要一个孩子。在某种情况下，这种想法还会冲到她眼前，尤其是在她找到伴侣时。她会想到自己的工作那么辛苦，由此推论：准备要孩子就必须减少对工作的投入。一位律师助理也许不再为成为合伙人而努力；一位老师也许不再会在学校里带头进行课程开发；一位销售代表也许会选择一个更小的销售区域，或压根儿不去申请管理职位。很多时候，女性在无意中不再去争取机会，即便有人把机会摆在她面前，她也很可能会直接拒绝或犹豫不定，希望把项目交给别人。

好在戴夫和我达成了一致，我们都认为如果要等到所谓的“恰当时机”，那么机会也就消失了。

孩子的出生瞬间改变了我们对自己的定位——女人变成母亲，男人变成父亲，夫妻变成家长，我们生活的重心从根本上发生了变化。养育下一代也许是最值得尝试的人生体验了，但这也是最困难、最让人深感惭愧的经历。要是有一种万能的抚养孩子的方式，那么每个人都会要孩子了。显然，没有这回事。

我们可以把事业想象成马拉松——一项历时漫长、备受磨炼最后可能有所收获的运动。再想象一下，这条起跑线上既有男人也有女人，他们都做好了准备、受过专业训练。一声枪响，他们开始一起向前奔跑。一路上都有人为男人打气：“加油！坚持下去！”但女人听到的则是不同的声音：“你知道你并不是非得这么做！”或是“开始还不错……不过你很可能跑不完全程”。运动员跑得越远，给男人加油的声音也就越大：“坚持！你必须坚持！”但女人听到的却是越来越多的质疑声。外界的声音，加上内心的声音，都不断在质疑她们坚持跑下去的决心，甚至还会出现反对声。正当女性努力地承受激烈竞争带来的压力时，旁观者却大声喊道：“家里的孩子需要你照顾，你为什么还在跑？”

任何幸运到可以自由选择的人都应该保持这样的开放度，不要在刚刚驶入职场高速路时就寻找出口。不要踩刹车，要加速。把脚放在油门上，等待必须做出选择的那一刻。只有这样，才能够保证在那一刻到来时，你所做出的是一个正确的决定。

我们已经在用意识克服自身的生物性。比如，在食物匮乏时存储大量脂肪是生存的必要条件，所以我们会不断摄取并消耗脂肪。但在这个物质充裕的时代，我们的身体不再需要过分储备“燃料”，而是需要通过锻炼身体以限制热量的摄取。我们正在用意志力来对抗生物性，至少我们在努力尝试。所以，就算“妈妈最明白孩子需要什么”这种说法具有最根深蒂固的生物学基础，但只要父母双方愿意，这也不是不可改变的。

旁观者的议论让我们感觉自己在挣扎应对的同时还在滑向失败，这简直就是雪上加霜。

试图做到一切还期待做得超级完美，这必然导致希望落空。完美主义是我们的大敌。格洛丽亚·斯泰纳姆的话很贴切：“你不可能做到一切。没有人能做两份全职工作，不仅把孩子照看得很好、一天三餐都下厨，还可以在凌晨享受性高潮……女性运动反对的就是‘女超人’。”

时间长了，他就注意到，人们辞职只有一个原因：他们都感到筋疲力尽，厌倦了无尽的工作和出差。卡纳里克说，他很理解这样的抱怨，但他不能理解的是，其实每个辞职者都还没主动休过假。直到离职那天，他们才发现公司要求的事情他们都已经完成，而且自己的确做得太多了。

但有违直觉的是，在工作上不断取得成功，则需要尝试着不要去完成公司交代给我们的每一项事情。为生活和事业腾出空间的最好方法，就是有意识地做出选择，并设定好界限，然后严格地遵从这些界限。

从此，我开始早上9点到公司，下午5点30分离开公司。这样的时间调整让我可以在上班前、下班后及时地给孩子喂奶，然后再哄他睡觉。我很担心我全新的出勤记录会损害我的公信力，甚至让我丢了这份工作。为了弥补这一点，我不得不在早上5点就开始查收邮件。是的，孩子醒来之前我就起床了；每天晚上孩子入睡后，我会再回到电脑前继续当天的工作。我竭尽全力不让大多数人知道我的新时间表。我的天才助理卡米尔出了个绝妙的主意，建议我每天的第一个会议和最后一个会议都在其他办公楼进行，这样可以让我实际到达和离开办公楼时不至于太招摇。如果必须从我的办公室直接下班，我就会先在大厅里观察停车场，瞅准没人的时候才会冲出去发动我的车。（鉴于我的做法非常笨拙，大家都应该松口气，还好我只是为财政部而不是中情局工作过。）

渐渐地，我开始明白，我的工作并不真的需要让我每天都花整整12个小时待在办公室。我开始更加高效地工作：只有在参加或主持必要的会议时，我的注意力才会更加集中；在离开家的每一分钟，我都坚定地把自己的工作效率提升至最高水平。我开始留意那些以我为中心的工作时间，也取消了不必要的会议来保证这些重要的时间段。我试着只关注那些真正重要的事情。作为我的座右铭之一，我也坚信：“完成，好过完美。”完成，说明这件事虽然有挑战性，但结果证明它是能够实现的，也常常让人如释重负。因此，当我第二次休产假时，我不仅彻底放松了（在大多数时间里），而且真的非常享受和两个孩子在一起的时光。

名词和规范由位高权重者掌管，位卑言轻者只能拥有形容词。”

现实是有些残忍的：阻碍更多女性获得权力的因素之一，有时候来自那些已经拥有权力的女性。之前的几代女性相信（在很大程度上她们也是对的），任何一个公司只可能有一个女性进入高层。那个年代很流行在性别比例上做表面文章，当时的女性会观察四周，而不是联合起来去反对不公平的体制，并且常常把彼此看作竞争对手，她们在事业上的进取心又会加重这种敌意，最后，有些女性会遭到忽视，其权利也受到侵害，甚至还会被其他女性恶意陷害。

理想的工作者应该能为工作随时待命，而一个‘好妈妈’则应该总陪伴在孩子身边。所以理想的工作女性需要证明，自己不在孩子身边时他们也会很好。拒绝像理想的工作女性的另外一部分女性会选择节奏更慢的事业（或干脆放弃事业），以证明自己的妥协都是为了家庭。所以这等于是在让两个群体的女人互相指责，因为她们都没法达到本来就矛盾的理想境界。”

之后发生了一件古怪的事。在聆听那些穿着昂贵西装的专家讨论了几周之后，我开始关注自己一直在思考的东西：不管这些人年纪多大，经验多么丰富，多么自信，他们给人的感觉都像是在演戏。他们说话时总要使用很多专业术语，并且固执己见，坚持用自己的方法来解决问题。即使他们的论点缺乏理论基础，他们也毫不动摇。我开始明白了，从某种程度上来说，这些人在达成一致时便能够不计前嫌。

我意识到，努力学习和熬夜工作虽然可以让我达到自己设定的目标，但也会让我忽视自己真正的梦想。我将自尊和成就、奖励紧紧地绑在一起，当我无法取得成功时，我的自尊便会轰然崩塌。“我不知道自己是谁”，我这样告诉友人。

实际上，当我们从象牙塔走向职场时，我们要少听他人的建议，多听自己的心声。没有所谓的“完美”的下一步，就像世界上不存在你幻想的那种爱情一样。所以，我们怎么能期望别人告诉我们如何找到它？

很多学生都追求完美，希望自己成为一个有吸引力、有学术成就的全才。他们因为这种压力备受困扰。他们在追求完美的同时也会退缩，回避那些可能玷污他们名声的机会和挑战。他们是不会开口的，除非他们已经找到了正确的答案，或者选修的是一门很难却有趣的课程，又或者他们追求的是某个完全没有把握的目标。他们用倾听和成长的经验去交换表面的完美；而那些警告你突然改变职业方向可能会让你郁郁寡欢、没有成就感甚至造成混乱的教授、父母和职业发展人，也会促使你更加努力地追求所谓的“正确的道路”。

听到自己的心声再去行动，你的“肌肉”就能得到锻炼，才能渐渐养成习惯。这样的话，当老板给你开的工资是年薪3.5万美元，而你想要的是4万美元时，你就可以大胆地向他说出自己的想法了。只要你的人生多一些这样的时刻，你就会越来越接近你想要的那种生活。

当听到“你好，因为泰勒·斯威夫特现在正忙着和某人分手，所以不能接听电话”这类语音信息时，你的朋友可能会觉得好笑，但大部分招聘人员都不会认为你很幽默。
