#+title: 从国内亚马逊离职

这次离职过程可以说是极其不顺利。

大约上午10点到了单位楼下。因为自己没有badge，也不知道应该去几楼还IT设备，所以只能打电话联系经理。正巧今天上午10点左右有一个内部的team meeting, 所以经理大约20分钟之后才看到我的电话，下来接我。因为我手上只有IT设备，所以以为还掉IT设备就等着拿离职信了，所以在办公室等了一会就出去吃饭，觉得中午吃完饭会来就可以拿了。

离职信是FESCO开具的，他们工作时间是9:00am-4:30pm, 不过中间有1个小时吃饭的时间就是12:00-1:00。当时在FESCO那边留下了我的电话，他们一旦确认手续走完，就会电话通知我拿离职证明。走之前我大概弄清楚了离职手续，这个手续的中心环节是驻在马尼拉的团队。我们提离职申请，IT设备归还确认等等，都是马尼拉团队跟进。一旦那边确认所有手续都期权了，才会通知FESCO所有手续都走完，这个时候FESCO才能发出离职证明。

吃完饭大约12：30，回来就在座位上等了。等到大约2：00左右，感觉有点等不急了，所以又去FESCO那边问问情况怎么样了。他们说还没有等到马尼拉团队的确认信，并且建议我自己发邮件问问MNL-exits@amazon.com的具体进度。离职申请已经确认了，那估计就是IT设备那边还没有确认。过去一问，晕了，果然是那边的人一直没有恢复确认邮件。

IT团队恢复了确认邮件，我觉得已经就差不多了吧，于是坐回工位开始聊。大约到了3：30还是没有接到FESCO的电话，我有点受不了了，于是发了封邮件问问马尼拉团队我的离职进度。他们说卡在了badge clearance上。好家伙，我入职的时候因为是remote入职，所以没有拿到badge, 你怎么让我clear? 不过既然他们说卡在badge clearance上了，那就去问问badge中心吧。原来即便是远程入职，他们也会制作badge, 只不过临时被他们保管而已。OK，和badge中心说明了原因之后，他们帮助我确认了badge clearance. 重新回到FESCO，终于拿到了期待已久的离职信。

这件事情办成这样，有客观的原因，当然我自己也可以做的更好。我误以为所有的离职流程都是非常friendly的，并且经理知道所有的一切，事实证明并非如此。如果我早点去联系IT团队，早点联系badge团队，说不定吃饭前就可以搞完。但是因为我拿的是临时badge, 所有出入门都需要有人陪同，导致我也不能到处走，更别说去和他们确认了。离职流程很多很细，单独看每个环节处理起来都很高效。让我意外的是马尼拉团队的效率是非常的高，badge clearance一完成，FESCO那边就确认了。即便如此， 你也必须时刻盯着流程，看看它卡在什么地方。离职这种事情和其他很多事情一样，你要是不上心去推动，别人可是不管的。
