#+title: Life is just a Moment

A man died…
有个人死了

When he realized it, he saw God coming closer with a suitcase in his hand.
当他意识到时，他看见上帝手拎行李箱向他走来。
Dialog between God and Dead Man:
下面是死者和上帝的对话：

God: Alright son, it’s time to go
上帝：好了，孩子，我们走吧。

Man: So soon? I had a lot of plans…
死者：这么快？我还有很多计划没……

God: I am sorry but, it’s time to go
上帝：很抱歉，但时间到了。

Man: What do you have in that suitcase?
死者：你的行李箱里是什么？

God: Your belongings
上帝：你的遗物

Man: My belongings? You mean my things… Clothes… money…
死者：我的遗物？你的意思是我的东西，衣服和钱？

God: Those things were never yours, they belong to the Earth
上帝：那些东西从来就不是你的，它们属于地球。

Man: Is it my memories?
死者：是我的记忆吗？

God: No. They belong to Time
上帝：不是。它们属于时间。

Man: Is it my talent?
死者：是我的天赋？

God: No. They belong to Circumstance
上帝：不是。它们属于境遇。

Man: Is it my friends and family?
死者：是我的朋友和家人？

God: No son. They belong to the Path you travelled
上帝：不，孩子，他们属于你走过的旅途。

Man: Is it my wife and children?
死者：是我的妻子和孩子们？

God: No. they belong to your Heart
上帝：不，他们在你的心里。

Man: Then it must be my body
死者：那么一定是我的躯体。

God: No No… It belongs to Dust
上帝：不，不，你的躯体属于尘埃。

Man: Then surely it must be my Soul!
死者：那一定是我的灵魂！

God: You are sadly mistaken son. Your Soul belongs to me.
上帝：孩子你错得可悲，你的灵魂属于我。

Man with tears in his eyes and full of fear took the suitcase from the God's hand and opened it…
死者眼含泪水恐惧地从上帝手中接过并打开了行李箱……

EMPTY!!
空的！

With heartbroken and tears down his cheek he asks God…
他泪流满面，心碎地问上帝……

Man: I never owned anything?
死者：我从来没拥有任何东西吗？

God: That’s Right. You never owned anything.
上帝：正确。你从来没有拥有过任何东西。

Man: Then? What was mine?
死者：那么，什么是我的呢？

God: your MOMENTS.  Every moment you lived was yours.
上帝：你的时光，你生活过的每一刻都是你的。

Life is just a Moment.
生命仅仅是时光。

LIVE IT. 
LOVE IT. 
ENJOY IT.
经历它，热爱它，享受它！

