#+title: 临高启明

http://lingaoqiming.github.io/

* 第一卷 启航
----------
此时，他们并不急于扩大执委会。三人虽然出身、生活环境、学历、工作环境各不相同，却在很多方面能够彼此心领神会。有一些人要求立刻报到的时候，执委会没有讨论就异口同声的回答：目前的基础设施还没有完备，要再等一个阶段。他们心里很清楚，此时在自己手里积攒下的穿越资本越多，未来的穿越权力架构里他们的地位就越重要。

在[萧子山][y001]看来，无论在什么时候，资历永远是有价值的无形资产。特别这样的社会性组织内，资历长短往往决定了在组织中的发言权和威望的大小。现在他们对很多穿越者的状况了解有限，过早让他们加入会让某些人获得与本身能力不相配的资历，对以后的工作不利。

[文德嗣][y002]的考虑则比较现实：这个时空里最不缺的就是浮躁而夸夸其谈的人——成事不足败事有余。过滤这些人的最佳方式就是用时间来消磨他们的一时冲动。

当然，这个沉寂期不能过长。准备工作涉及太多的专业知识和技能，靠他们三个是无论如何也搞不定的，执委会需要新鲜血液。在开过一个小会之后，决定事不宜迟，马上再穿一次，搞到足够的钱以便进入实质性的准备工作。

----------
“这么说小瑞建议我们选Saiga308了？”

“他可没这么说，”时袅仁是何等人物，早就是滑不留手的职场精英了。这类选武器的事情算是国之大事，选得合适不过是个合理化建议，要是选得不好日后出了麻烦，错误就都是你的了，就算领导能谅解，群众也不会理解。“就是给大家一个建议。具体怎么决定，还是看执委会。”

这等于把皮球又踢会执委会了。这边都在议论纷纷，委决不下。与业余人员激情澎湃的讨论相比，体育组除了一个席亚洲之外，根本没人对这个问题感兴趣。在他们看来五六半就足够用了，何必扯出这么多莫名其妙的玩意。

----------

“赎人？亏你想得出。”这边已经有人愤愤不平了，“下软蛋的事，不干！”这话引起了一阵嗡嗡的附和声。穿越众虽然满嘴都是：“不要低估了古人的智慧、”“古人也是很厉害的”云云，其实心里是充满了现代人的优越感——“文明发达的现代人”向“愚昧落后的古人”妥协，光想一想就会严重伤害了他们的心灵。

----------

“穿，为什么不穿？”潘锋弹了下烟灰，“咱是穷忙族。读过大学，上班也不算不卖力，做了这么多年，辛辛苦苦的干活也就能赚点小钱，还得存点防着生病，结个婚买了房子当房奴——你要抱怨几句吧，还有人为了拿几毛钱要你去游太平洋。”他笑了笑，“兄弟们知道啥叫铤而走险吗？咱胆子小，从小是良民，本时空里不敢干那违法乱纪的事情，可是活得又郁闷，所以就来铤而走险了。”

----------

所谓的资源标准化，是为了执委会整合所有非物质资源的一个统一行动。来报道的每个穿越众无差别的都携带了笔记本电脑、无数TB级别的硬盘、数不清的光盘。包含了各种电子资源。除了日本AV这类群众喜闻乐见的东西，还有整套的各种论文、期刊数据库、几个国内主流的电子图书馆数据库；各种电影、电视剧、文艺节目；广播电视大学远程教育节目、大学讲座录像；电子版的各类图纸、CAD设计图、工业手册；各类软件……目前网络上能找到的和不能找到的，被电子化的图文媒体资源几乎都被带到了这里。这些海量的信息被分散在许多载体上，即有大量的重复浪费了空间又不够安全。因此由信息组负责，对每一批次报道人员带来的此类资源统一检查、归类、优化和备份，分门别类的进行归类编目，做出索引来以便查询。

----------

“说到这里，我现在有个很奇妙的感觉——像是一次十七世纪的远洋探险。”于鄂水兴奋的搓着手，“一群社会的失意者和幻想者希望能在另一个世界得到新的起点，到新的世界去发财去掠夺去满足欲望。他们有全新的杀戮技术和武器，他们有大堆的紧俏商品。他们冷酷无情地进入新世界。最初只是要求一小块土地容身。后来他们成为帝国的主人！

----------

这边议论停当，大家忙着收拾装备。冉耀把他的照相机和刑事侦察记录本带上，本来他还有指纹收集工具，但是没用——大明没指纹档案可查。体育组带去了三支五连发猎枪，子弹不够，一时间也来不及装填新的弹药。每支只配了十发子弹。另外还带了一些侦察设备：夜视镜、无线信标，窃听器一时半会买不到，不过录音笔、麦克风和摄像头还是能搞来的。至于对讲机、烟幕筒、催泪弹、防毒面具杂七杂八的东西有用没用的都装了两个大背包。

----------

郭逸的调查，通过钟利时和几位当地人士的社交活动，多多少少传到执委会的耳中。不过，消息能透出来本身就说明谁也没拿这事当回事。[萧子山][y001]多少有些担心，事情进行到这一步已经是临门一脚了，谁也不希望和男足一样的结果。

----------

[马千瞩][y005]不辞辛苦的带人检查了每个穿越者的携带物品打包情况，不由得大摇其头。几乎所有穿越众都带了各式各样的电脑，却很少人想到该带一本笔记本一支笔，不少人还带了MP3、PSP之类的娱乐设备。好像他们要去的地方到处都有电源插座。对个人卫生至关重要的内衣、袜子、盥洗卫生用品之类却带的很少。类似的不像去穿越，倒象去远足的装备不一而足。委员会决定对全部人员的装备做调整。说服他们不要带那么多无用的东西去。筛选下来的东西可以邮寄回家，但是多数人都坚决不同意把自己的电脑留下——就算穿越成功，大伙都成了离休干部级别，电脑在自己的有生之年还是不可能生产出来的。

* 第二卷 新世界
----------

“从你拿出那把油锯出来，我就知道中国的环境没有未来了！”在第三届全国环保工作会议上，戴谐的发言揭开了对林业部长吴旷明的批斗狂潮，在林业战线上奋战二十多年的吴旷明同志不得不在会上做出深刻检讨后黯然离职，转而就任林业大学任校长。但倒退回三十年前的那一天，他可是被执委会称为“一个人干了一个小组定量”劳动英雄——当然他能干这么多，主要是其他伐木工太废柴，倒不仅是油锯的功劳。

----------
这个犯罪团伙的能量也太大了吧！从美国走私武器，在越南造基地，雇佣退伍军人和警察……郭逸不寒而栗，完了，自己落在这伙人手里，肯定会备受严刑拷打，最后悲惨的死去。虽然小郭一上班就知道，他的工作的性质随时可能让他成为烈士，但是成为烈士的人毕竟是少数，几年也不会出一二个。再说烈士生前也不知道自己就一定会壮烈牺牲，这可比现在他等着做烈士好受多了。

----------
邬德笑了一下：“没可能。先不说大明会不会收留他们，你就看这七人团体多复杂，又有老百姓，又有人民警察，又有美国特务的——还有四个女的。我们都是为了一个目标走到一起的，还经历了一年多的磨合期。他们有什么共同目标去奋斗？遇到一点挫折，不马上闹翻才怪。”

----------
穿越者一共二十一人受伤，包括一个冒失的去捏SKS步枪枪管的烫伤在内。

----------
虽然有人提出俘虏的人权问题之类的疑问，但是许多人显然对如何保障当地土著的人权没兴趣，而对如何折磨俘虏有充分的兴趣，冉耀还没想好该怎么审问，就有人主动上来提出了各种刑具和拷打方法。

----------
屋子里没有人，邬德随手拿起桌子上的一张清样，像是张单开的小报，头版有两个歪歪扭扭的斗大毛笔字写着蝌蚪文般的文字，仔细看，原来是《临高快讯》，下面还有落款：席亚洲题。席亚洲的脑袋看起来已经好了，都给刊物题字了。邬德看了起来，该报纸大篇幅报道了“第一次反围剿”的胜利，夸张的报道当地官府出动了三千人的大军，但是在我天军神威的打击下，仅半个时辰便全部被消灭。虽然署名是本报军事评论员，但是那类似战棋游戏说明一样的文体，显然就是出自在D日不幸负伤的席亚洲之手。

然后是一篇社论，署名：本报特约评论员。评论道：反动的明朝政府必将被我英明伟大的穿越党彻底消灭。后是一篇理论文章，介绍马克思主义，当然，这位马先生成了出生于万历年间的一位隐士。落款是杜雯。不过这文章虽然很长，还列举了许多数字，邬德却始终没看明白写得到底是什么。估计连马克思自己看了也不知道。报屁股上，又是一篇文章《临高农民的血泪控诉》，里面写了许多农民的悲惨遭遇。邬德觉得很眼熟——这不就是小郭审问俘虏之后抄送给他的《审俘记要》里摘抄来的东西么。真是天下文章一大抄，里面还添油加醋的增加了许多内容，其想象力简直令人发指。作者很自觉的没有署名。

----------
当晚，军事组根据侦察和审俘的结果，开了一次简单的参谋会议。会议以邬德打头，他是本次行动的负责人，要按21世纪时空的说法应该是：苟家庄拆迁工程项目经理。

----------
根据掌握的情况来看，苟家庄的设防水平即使按这个时空的标准也谈不上多坚固，用武力直接打破不难。军事组提出了一种最简单对人员也最安全地方案：用步枪肃清寨墙上的乡勇，接着用有防护的工程机械直接撞门就是，再厚的木门就算包上铁皮也顶不住几百马力的推土机。不过这方案稍微奢侈了一点。工程机械从百仞城出发到苟家庄，一路上的地势平坦，对履带式车辆来说倒什么问题，但是路程远了点，除去费油之外，机械本身消耗的摩托小时也相当可观。

----------
只要对炸药稍微了解一些的人都知道：硝酸氨本身也是一种低威力的炸药。化工组当然不满足直接把化肥当炸药使——这第一显不出他们的水平，第二也是对有限资源的浪费。将硝酸氨升级成硝铵炸药的方法就是在其中添加一些其他成分，配方有好几种，有的是添加烈性炸药、有的是增加燃烧材料。硝铵炸药平时多是用在爆破工程上较多，也能用来装填地雷、手榴弹之类的爆炸性武器，抗战时期八路军和新四军都从敌占区买入硝酸氨加工之后作为炸药使用。好处是威力尚可，敏感度低，不管子弹打还是火烧、震动都不会让它爆炸。【注：这里就不写原料配比和制造流程了，大庆在即，大伙也别讨论这些敏感的东西了】

--------------------

苟布里站在台上原还有些打鼓，回头瞅了一眼台角，席亚洲冲他点点头，便一鼓勇气，开始说话了：

“我是个穷厨子，给苟家上上下下的老爷太太少爷小姐们做饭好些年了。这些年气候不好，不是旱就是雨，台风雹子轮番来。大家平日里都过得艰难，粥里下块番薯就算过年了。【注：这话毫不夸张，洪秀全没造反前的最大愿望就是天天能吃白米粥加番薯，一般老百姓的穷困可想而知】这苟家呢？我是个下等厨子，不知道什么道理，就说我知道的他们家的吃饭好了。

“他家用的头等厨师，都是能把一口猪做出几十道菜的高手艺，一盘炒肉，就用一头活猪背上的一块肉，其他都不要。吃鱼要吃张嘴吐气的，吃虾要吃活蹦乱跳的，米要碾过三次，做饭都是白米饭，里面一颗杂粮、番薯都不加！吃白米饭吃腻了，就做油炸的糕饼吃，一炸就是一大摞啊……喝酒是十年的，人参汤得辽东来的，还要半尺长的。最可恨的是苟循义的儿子苟大少，这个小挨刀的，从小时候吃包子，烫了不吃，冷了不吃，不冷不烫的时候，叫两个美貌的丫鬟各捏着一个角，送到他嘴边，他就当中咬一口，余下就全丢了喂狗——”

邬德皱起眉头，小声问席亚洲：“这谁编的，胡编乱造也得有个度吗？！”

席亚洲却一点都不动声色：“是杜雯带着张兴教他们搞得，不错吧？你觉得离谱，老百姓就爱这个调调。”

“这不扯淡吗……”邬德正说着，那被踢翻在地的苟家的本家老爷忽然站起来，颤颤巍巍的说：“胡说！没有——”

话音未落，身边的几个盐场村的民兵早就棍棒齐下，又往他嘴里塞了个麻核，拽一边去了。

--------------------

东门吹雨趁热打铁，赶紧递上一份文件：“这是我们商业组对东门市的经营规划方案，希望执委会尽快批准！”

“规划方案？”几个执委都一愣。虽然他们在百仞城外搞个自由市场，目的只是促进商品流通，增进穿越者和当地土著之间的感情而已。市场准备如何经营管理却没几个人仔细想过。大家就把这个集市想成了国内许多城市都有的自由市场模样：农民和小摊贩们来摆摊出售商品，最多就是有人想到免摊位费之类的。

“不错，规划方案。”东门乘机站了起来，“各位执委，现在就让我来介绍一下这个整体规划方案，我相信，有了这份规划，在执委会的正确领导下，在[文总][y002]的指引下，在程委员的大力支持下——”

“别扯废话了！都到了大明还搞这套！”独孤求婚已经不耐烦了。

“——我们的东门市将成为全临高，不，全海南最繁华的商业市场！”

东门吹雨好歹是非正式的混过官场的，哪里在乎求婚的牢骚，说完开场白之后，赶紧在身后的黑板上挂起一副新绘制的规划图。这是他跑了一趟建筑工程组，好话说尽又送了几包香烟才得到的。

--------------------

还有一位重要人物则是郭逸，他被委以重任的主要原因是团体中对秘密战线的工作的概念全来自电影和小说，他算是唯一真正接触过实务的人。一纸调令，郭逸忽然发现自己不是治安组打杂人员了，而成了先遣站负责人，要去大明的广州城里去搞特务活动了——这多少让他感到人生的无常，不到三个月前，他还在另一个时空的广州城里搞反特……

--------------------

所谓被俘说明手册，其实是执委会编写的一本穿越者的背景资料，正如一个特务要潜入敌占区必须有一套全新的身世一样。穿越者也需要这样的东西来说明自己的来历和目的。

整套资料是在于鄂水的主持下编撰的，大体上以[文德嗣][y002]在搞双向贸易的时候说的那套宋朝遗民开发澳洲的版本，添加了许多细节。最大限度的考虑了当时人的心理、文化方面的因素。当然，历史学家再高明，也不可能百分之百的掌握当时真实社会状况和心理，所以手册自D日之后还在不断修订。广州先遣站人员和自封海军输送大队的船员们是第一个配发试用版本的。

“如果平时在和土著交往的时候发现了什么问题，尽快和总部联系，这个手册会一直修订。”[萧子山][y001]说，“万一被俘，要记得交代的口径和那三层防线。”

来大明的原因，设置了三层保护。第一层当然说是来经商贸易的，如果遭遇拷打的威胁，则可以招认澳洲起了内乱，他们是为了躲避内乱到大明来的；万一还是不信继续拷打，就可以招认说穿越者是澳洲内乱中失败的一方。

至于铁船、机器、武器，穿越者的对外口径是从澳洲带来得，如何制造一概不知，民用的商品技术，在危及生命的状况下可以透露。

总体上执委会制定的被俘政策是：允许交代，不许叛变。穿越者在被俘后最恶劣的情况下可以招供——包括他们是穿越者的真相——虽然这个真相对方未必相信。但是不得以自身掌握的技术、讯息和其他各种能力主动为其他政权、势力进行服务。

--------------------

买来的奴仆除了生病的、年龄幼小的、身体弱的之外其他统统都被赶到了船上，一艘78吨的船装上将近一百号人还真是够拥挤，好在海路只走几天，只能委屈他们坚持坚持了，相比之下，穿越者在整个航渡过程中的忍耐力明显不如被关在底舱的人，一众人出海没多久就被底舱里不断散发出的尿骚味熏得直吐，这奴隶贩子的勾当还真不好干。谁也不在乎什么海盗不还海盗了，取最快航线直奔博铺。

--------------------

“——以上就是我的财务报告。”[萧子山][y001]在会议室里，面对着神情严肃的一群人做完了汇报，最后他还画蛇添足的加上了一句：“本人保证没有贪墨一文钱！”

“财务有没有问题，等金融部门审计过后就知道了，你就别保证了。”[马千瞩][y005]对发誓保证这类自由心证根本不信任。如果说现在没有人贪污，那是因为眼下没必要贪污而已。

--------------------

与照壁同时出现的是一批古怪的人：头戴藤帽，身穿短毛式的对襟黑色立领短衣，木头扣子，腰束宽皮带，小腿上打着白色的裹腿，脚穿草鞋。屁股上挂着带短横柄的短木棍。每个人的衣袖上还有一块盾牌样的绣布，有些看不懂的花样，只有几个字大概还认得出来：上面是治安，下面则是东门市。

“靠，这活脱脱的是安南巡捕啊！”独孤求婚看到后勤上送来的服装和装备，发出了绝望的惨叫声。他原先给警察队设计的制服是很漂亮的，大檐帽，黑色翻领制服，皮革武装带、马裤、长靴，还有胸口的证章，袖子上的红色袖标——活脱脱的就是一党卫军。

“萧委员，我送上去的服装设计不是这个模样的啊！这么土气的模样怎么威慑坏分子？”独孤给[萧子山][y001]打电话。

“你不就是把警察队搞成党卫军那模样吗？不成！”

--------------------


在整个过程里高音喇叭不断的播放着《关于清理整顿东门市治安环境的通知》：除了赌博业被取缔，赌博密切相关的小押当、放印子钱的也被限时离开市场，继续活动者严惩不贷。妓女必须限时到派出所登记，逾期不登记的，一律驱逐出市场……

妓院业幸存了。在市场内操持此业的都是游动户或者附近的“半掩门”，偷窃、盗取嫖客钱财的事情时有发生，但是考虑到本地悬殊的男女比例，这个行业属于可容忍的范畴。经过和民政、卫生部门的讨论，决定在东门市发放妓女执照。所有妓女必须向派出所进行登记后发给执照。没有执照经营的，一次发现驱逐，二次发现劳教。本来民政部门希望由卫生部门执行每月一次的体检，但是卫生部门的人手和器材、药品严重不足，所以暂时不执行。

整个行动过程进行了有条不紊，让周士翟刮目相看。别看这群“澳洲同志”对江湖不怎么了解，这一手可比官府衙门漂亮多了，不但行动干净利落，而且事事都有准备。处置宽严相济，与既黑又贪且酷的衙门相比，不啻云泥之别。

--------------------

随着船上的警铃响，渔船上的三十多人迅速各就各位，戴好钢盔，穿好防火战斗服——这个时代中国沿海的海战中，纵火是常见的攻击手段。准备好了武器，渔1号没有火炮之类的重型武器，最基本的火力配备就是靠水手用SKS步枪齐射。不过最近稍有改善，工业部虽然缺少金属材料，木材、竹藤和兽皮之类的东西还是不少的，加上有个号称除了原子弹什么武器都玩过的林深河的加盟，很快根据资料复制了几台Ballista。

所谓Ballista，是古罗马时代最成功的大型机械弩，也是世界上最有名的机械弩，严格说来它不能算弩，其发射机理跟弩不同，发射势能主要不再积蓄于弓身，而是积蓄于两侧的扭曲发条。Ballista有一个绰号：shield piercer（盾牌穿透者），它发射的巨箭能轻易洞穿任何已知的盾牌和铠甲。一部合格Ballista杀伤射程可达五百米，两百米内能穿透厚度约两英寸的匀质木板。而且它可发射的武器五花八门，包括箭，标枪，石弹，燃烧弹等等。在全盛时期的古罗马军队，每个军团装备的Ballista多达50部以上。


--------------------

有条件要上，没有条件创造条件也要上！毛主席的话在[马千瞩][y005]的心头回荡，为了保证党对军队，不对，执委会对军队的绝对领导，自己一定要坚持下来给这伙人瞧瞧——知识分子也不是好惹的。

--------------------

[马千瞩][y005]的拖拉机训练法几小时后就传遍了各处，有人很不客气的就给他取了个绰号叫马党卫，杜雯更是痛心疾首，专门打电话来质问马委员为什么要采用纳粹法西斯的训练法？还连声说“你太让我失望了”。据丁丁的报纸报道，杜雯女士还当场流下了眼泪……第二天[马千瞩][y005]一起来就发觉自己成了小报上的花边人物。

花边也好不花边也好，已经走上不归路的[马千瞩][y005]只好咬着牙坚持下去了。好在具体的队列、设计、军语、投弹之类的训练还是由原来退伍军人负责的，否责光靠一本《民兵训练手册》还真是有些难以为继。


--------------------

征集军装设计马上在全体穿越者掀起了兴奋的狂潮。在这个枯燥无味的环境下，这多少算是件有娱乐性的事情。很快[马千瞩][y005]手里就收集到了一百多份各式各样的图稿，从有中国特色的65式军装，到菲烈特戴着主教帽的掷弹兵，拿破仑的熊皮高帽近卫军、英国龙虾兵，布琼尼帽的苏俄红军最后到德国国防军……所有人在军装上的恶趣味都集全了。

经过汇总，[马千瞩][y005]悲哀的发现大伙没什么创造力，全是历史上各种著名军队的军服复刻版。归纳起来三大流派：一是中国传统派，以65军装为代表，也夹杂着55派和87派；二是排队枪毙派，以19世纪的欧洲军队制服为蓝本，强调华丽炫目；三是二战派，基本就是照抄德、苏、美军的制服，也有兼收并蓄，杂糅成四不像的。除此之外还有些小众爱好，比如国民革命军式样的小圆帽，甚至连日本旧陆军的那身昭和式军服也有爱好者。

--------------------

[马千瞩][y005]不止一次从安插在士兵中的眼线中得到这样的汇报：擦枪管就是浪费，有残渣把枪管倒倒干净不就是了，反正不擦干净也打得响。

也有人说这些澳洲海商，都有些“独”，就知道认死理，样样都有规矩，不像本地人那么会变通。

[马千瞩][y005]看到这样的士兵心理汇报，不由得想起了改革开放之初合资企业的中国员工们对外方的议论——两者倒有异曲同工的地方。

--------------------

[文德嗣][y002]发现张机器其实也是一个模型高手，他用很简单的木工工具就能做出各式各样的海船模型来，不仅能造，而且各个部件比例准确，还能拆卸自如。原来这就是他的技术秘密，说白了就是等比例放大法。这个办法虽然有点原始却十分有效。[文德嗣][y002]知道欧洲的造船师也采用过类似的办法，而且每造一船，先做模型的规矩也是这种方法的馀泽。

张机器对数学、几何所知甚少，绘图的水平也等同涂鸦，但是他把这些船的大小、结构、尺寸一切数据都牢牢的记在脑子里，这点让[文德嗣][y002]很佩服——中国古代的能工巧匠，很多不识字、不懂算法，但是却能依靠一代一代的经验传承做出巧夺天工的物品来，确实有他们的独到之处。

--------------------

敌人仿佛不太慌张，看的出都是训练有素的战士，他们霍霍的抽出战刀，仿佛在说：近战，我们不怕你。

独孤求婚看到这得意的一笑，心想：蠢材，谁跟你近战，不开枪，是怕你们卧倒隐蔽，浪费子弹。

50米，40米，30米，越来越近，对方狰狞的面孔都看见了。

近到20米了，一挥手，前排的战士迅速向左右分开，隐蔽在人墙后面的12磅山地榴露出了乌黑的炮口。

那一瞬间，能清楚地看到对方的表情：惊愕，他们的表情好像在说：太卑鄙了！！！！

--------------------

瓷酒瓶上贴纸标签不大好看，派遣站的几个人讨论下来，由严茂达设计，到牙雕店里定做一批古色古香的小象牙挂牌，用五彩锦绳串着挂在瓶子上，牙牌上是传统图案，商标是“大唐公主”。这个恶俗的名字让大家一致对张信表示藐视，张信说：

“你要说一高雅的，比如啥洛神之类的，外国人听得明白吗？你看法国那一水的名酒，不是拿破仑就是路易十三的，不更俗？我还没叫它康熙、雍正、乾隆呢。”

* 第三卷 新社会
--------------------

再看旁边的老狄比自己还惨——老狄原来在陆军干活，不知怎么的又想当海军陆战队的干活，仗着曾经在岸防部队服过二年役，一投奔海军就成了海兵连的连长。其人好谈军队建设问题，一天到晚K98、虎式坦克、88mm大炮不离口，属于海军众中少有的哈德派。一直说爬桅杆对他来说小菜一碟，没想到第一次上船海训就拉稀了。这会连桁架都没爬上来，半当间抱着桅杆双眼紧闭。NND，李海平心想按说我们现代人是不该恐高的，不管在哪里都得爬几层楼的……

--------------------

三人小组从棚子里出来，他们那血迹斑斑的罩袍又引起了一阵骚动。大家动手把器械清洗过，再用开水煮洗消毒一番。结束之后烧煮的陶器被砸碎掩埋。临时制做的罩袍、口罩全部都丢到火里烧掉。这番做法原本只是为了杜绝医疗垃圾的污染，没想到却被当地人理解成了一种巫术仪式。以至于多年之后穿越政权的工作队重返该地的时候，某个年轻的队员在社会调查笔记中记录下了这么一段：

“……给病人‘做鬼’驱病的最后阶段，是把一件染上斑斑点点红色，有时候就是染上血迹的白布丢入火中，最后把煮东西的陶罐子砸碎。所有的垃圾将会被掩埋掉。整个仪式才正式结束……”

--------------------

这下任何人都知道峒主的病是好了。在考察队庆幸这件事情终于善始善终之时，寨子里各种各样的病都雨后春笋般的出现了。寒热、牙疼、肚子疼到外伤发炎无一不包。何平到底只是个二把刀的卫生员，对如此丰富的实习机会当场就乱了手脚。他的药箱里也没多少药物可用。

当下只好把那些容易治疗和能够确诊的病都一一进行了治疗。又连着做了七八个小手术，现在何平下起刀来飘逸无比，连他过去觉得没法下手的麦粒肿也敢了动手了。不过他还是很注意，没敢乱给抗生素，生怕把这里的微生物环境给搞乱了。至于肚子疼之类病因难以判断的疾病，何平干脆用寨子里送来的米粉加上蜂蜜做了些药丸散发，居然有不少人宣称吃了之后病愈了——安慰剂的力量还是很强大的。

--------------------

“你个大变态。”文同对这类SM cosplay向来嗤之以鼻，幸好这家伙还算有点兄弟情意，没把阿朱也拉去上什么夜课——参加师范班培训他是很赞成的。可惜自己每天折腾糖厂的事情，每天回到院子就就想睡觉，连收用阿朱的精力都没了。到底还是老常的身体壮实啊，白天紧折腾，晚上折腾紧——文同不由得悲从心来：人与人之间的差别，咋就这么大捏。

--------------------

几个人想了半天也没想出合适的办法，这天常师德带着廖大兴去县城逛街散心。这算是他除了调教女奴之外唯一的爱好了：穿着绸缎的直缀，昂首阔步的走在泥土飞扬的街道上。他那异于常人的身高、体格和白皙的皮肤都让人敬畏的闪到一边——充当大佬的感觉是很不错的。常师德在逛街的时候很快发现了一个现象——徐闻这里的物价很高！

--------------------

外事部接到这封书信不敢怠慢，赶紧上报给执委会，一时间各部门立刻运转起来。情报委员会很快宣布，这个方案是可行的，葡萄牙人当年将中国砂糖运到越南的卖价是每石八两！这个行情比英国人在广州的收购价还要高一倍！海上贸易的暴利使得所有人都按捺不住了。吩咐要求执委会立刻打开越南贸易的大门。

“是时候了，越南丰富的资源不能再沉睡下去了。”狂热分子在执委会扩大会议上煽动着，“把它变成我们的原料基地和市场吧！”

“武力远征！”

“大炮所至，贸易开路！”

“让我们在越南的海岸线上架起几门大炮，从而彻底的奴役一个国家吧！”

“越南这条贸易线路，还是尽快建立起来为好。”[马千瞩][y005]对什么糖、米之间的贸易不怎么感兴趣，但是对鸿基的煤早就垂涎三尺了。

--------------------

“东家，我们自然是不怕他们去县里告状——本来就是捕风捉影的事。可是镖师们回来都说，这事情里面大有蹊跷，卖糖的人里混入了不少烂仔，眼下又是人心惶惶，这里华南一改价，这些人立马鼓噪起来，煽动着人群往里面一冲，这……这不是玉石俱焚吗？一旦事闹起来，连县里来人也未必立刻镇得下去！”

众人脑海里都出现了过去在论坛上看到群体性事件的报道，这种事情，当年大家看了还有些暗爽，颇有些为我等屁民出气的感觉，但是事到临头，外面围着屁民准备来闹群体性事件的时候，大家还是纷纷感到压力很大。

“还有……”廖大化又补充道：“这里还混了全雷州好几百家土糖寮的煮糖匠人——自从华南厂开张之后，土糖寮的买卖一落千丈，这些匠人要么失业，没失业的工钱也被压得很低，都是一肚子怨气，听说前几天已经有人去衙门交过状纸，要求官府干涉的，被县里的太尊驳了，要是乘机也闹起来就更不得了了。有人还预备着冲进来要烧机器。”

“我靠，这不成了捣毁机器运动吗？群众的革命觉悟真高啊！”梅林说。

“说这屁话有什么用，”文同一挥手，“我们可都是资本家，小心给外面的革命群众专政了，都拿主意出来！”

--------------------

他的传教团跟在杜雯的屁股后面，借着穿越众的余威，到处活动。许多人为了赶紧和穿越集团挂上关系，连天主和圣母到底是什么也没闹清，就跑到陆若华那地方去要求受洗了，慕道班每天人满为患，干脆在院子里上课。白多禄的嗓子都快哑了。量产的教徒一旦受洗完了赶紧都要求领一个十字架挂脖子上，还有人干脆领好几个，还挂一个在大门上。陆若华随身带来的十字架很快就发没了，赶紧写信回澳门要求定做一大批。

--------------------

“好了！”[文德嗣][y002]打断了大家的讨论，“这不是在BBS上开贴讨论，说什么都可以，越华丽越好。大家都把眼光放得现实一点！别一个劲的画大饼。”

“依我看，目前以扫盲班和简易师范教育为主。再加一个简单的干部讲习所就可以了。”[马千瞩][y005]说，“首先，我们不用管临高的普及教育，这不是我们的事。要培养的只是穿越集团目前需要的基本应用型人才——士兵会写字，会算100以内的加减乘除就够了。最多工兵、炮兵懂四则运算外加简单的几何应用。普通工人的要求不会比士兵高多少。担任行政干部再懂一些珠算之类……”

“反对！”钟博士说，“光造船厂的铆接工就需要懂高中水平的立体几何，扫盲班出来的工人怎么学习技术？”

“文盲也能当很好的工人。最多上夜校补补需要文化课就是了。”[马千瞩][y005]说，“我长辈工作过的企业，解放前目不识丁，但是技术好的产业工人有很多。解放后稍微经过夜校的培训，就能更上一层楼了。”

钟博士不以为然：“这是经验主义的低水平运用，暂时是没有问题，但是产业升级之后呢？科技总是要向前发展的。”

“照我看，我们的目标是在有生之年尽可能的复活那些对我们有用的科技，并且加以适应环境的改造，而非一味地复原科技。”[马千瞩][y005]说，“环境的不同使得我们的科技必然会走上一条与另一个时空完全不同的道路……”

“[督公][y005]的蒸汽朋克恶趣味又要来了。”下面有人窃窃私语。

蒸汽动力齿轮计算机、高速双层蒸汽火车、浮空战列飞艇。这是以[马千瞩][y005]为首的蒸汽朋克团最热衷的三个“未来科技”方案。

这时候教育委员会的头头胡青白站起来说：“根据大家的提案，我和教育部的同仁讨论了一下，认为在教育方面，我们可以秉承两条腿走路的原则。”

所谓两条腿走路，是既搞速成式的普及教育，也搞正规教育。前者用来应付眼前的需要，后者则为将来的发展进行人才储备。

--------------------

大门很威严，用的是特意从百仞采石场采来的大石块，三门洞式的欧式建筑——据梅晚说是抄袭清华大学的大门的。只是不伦不类地又在大门两侧添设了炮楼式的建筑。门口已经挂上了四块牌子：“临高国民学校”、“临高军政学校”、“南海职业技术学校”。

最后一块牌子则是“教育人民委员会”。

[萧子山][y001]问：“这怎么回事？”

“哦，[吴南海][y009]答应从农庄的盈余农产品中拨给学生一些额外的食品。所以算是投桃报李吧。”胡青白赶紧说，“[文总][y002]已经同意了。”

听说[文总][y002]已经同意了，[萧子山][y001]也不说什么了。看到教育委员会的牌子也挂在这里，便说：“这里环境挺好，倒是个好办公地点。”

--------------------

让一个班级的学生住在一起，彻底贯彻同吃同住同学同劳动，不管干什么都会很团结，有助于培养学生的集体荣誉感和纪律性。

[萧子山][y001]对整个宿舍的整齐和高度的纪律性感到很吃惊。每座宿舍的门口有戴着“值日”袖章的男女学生，他们一进来，一间接一间的寝室都会响起响亮的“长官查房”的口令声。随便走进哪一间，学生们已经在床边站得笔直。个人用品、服装全部整整齐齐地摆放到位，完全是一派军营的作风，连女生宿舍也不例外。

“纪律性很好！”即使[萧子山][y001]这样的军盲加理工盲也知道群众高度的纪律性对上位者来说有极大的好处：勇敢无谓的军队和能够忍受高强度单调劳动的产业工人。

“这是检疫营的军训效果好，”白雨说，“再刺头的人物也给收拾得服服帖帖了。另外，我们也推行学生自我管理体制。”

每个班按照十人一组设置小组，组设组长，班干部设有班长和三名班委员，分别负责学习、文体和生活。

“我们要求教师只安排任务下去，而不是具体经手安排。尽可能的让他们自我管理。”胡青白介绍说，“现在是在宿舍管理方面，包括搞卫生、安全保卫这些，未来还准备让各班轮流帮厨，管理校园环境，组织学习互助小组，做到学生‘自治’、‘自养’、‘自学’的目标。”

--------------------


氯气虽然普通却是现代战争史上第一种投入实战的毒气，一战时候可谓战果卓著，亡魂无数。而且氯气这东西制取容易，在本时空堪称超级大杀器。不管你是满洲白甲兵、关宁铁骑、御家人还是克伦威尔铁甲军，遇到了就只有一个“死”。

现在穿越者的工业还不能制造气体压力容器来，储存氯气是件不可能的事。但是徐营捷知道武器研究组的变态很多，说不定能搞出什么妖蛾子来。

这种黄绿色的气体在玻璃管内升起，在场的穿越众都屏住了呼吸。这时候，另一个玻璃管中安装的一个小风叶扇也忽然开始运转，这表明另一种无色的电解产物也出来了——氢气。

--------------------

[文德嗣][y002]对结盟的事情不感兴趣。在他看来此事投入太大，不合算。如果要挽救诸彩老集团，就得按照他的要求给予他银钱上的支持，同时向他销售武器。遗憾的是这两者穿越者都不大丰富。就算在数目上可以讨价还价，也是一笔很大的数字。再说火炮和火药对穿越集团本身也是急需的物资。

“我相信诸彩老提出的数目绝非狮子大开口，而是他确确实实的需要这么多钱来运转船队。而且这可能还只是一个开始。”

一旦在这个事业里开始投资，很可能就会成为无底洞——如果诸彩老集团在他们的支持下的状况没有好转——这是很有可能的，执委会的人大多数人都没狂妄到认为自己就能随意改变历史的走向了——就算他不来继续求援，穿越集团为了挽救自己的投资也不得不继续扩大赌本。这种事情往往就是开始是想花小钱办大事，结果花钱越来越多，事情越办越糟。参看美国人是如何陷入越南就知道。

此所谓此一时彼一时。[马千瞩][y005]心想，当初司娄拜宁建议和谈是为了稳住诸彩老，在不影响核心利益的情况下做出一些利益出让，尽可能的避免或者拖延他发动大规模的报复，为得就是让临高的建设能赢得多一些的时间。

诸彩老在他们最虚弱的时候没有出牌，是穿越集团幸运也好，是刘香的牵制也好，反正当初最危机的一段时间已经过去了。此时再和诸彩老和谈，他的价值已经不大了。如果于鄂水的提供的历史资料是准确的，诸彩老的寿命不到二个月了，再帮助他延续寿命，对己方有什么好处呢？

--------------------

“是的，首长。”十几岁的小通讯员胡来行了个普鲁士式的碰脚跟，转身跑了出去。在政治保卫总署当行政练习生的军政学校的学生都是苦大仇深的类型，基本上是裸身来投。冉耀收人的政审标准比执委会还苛刻：不许有任何亲人，最好连自己姓什么都不记得；最好记不起自己的家乡何处；受过极大的苦，如果是被穿越者救过命的最好。最后，还得通过一系列的测试，任何表现出贪吃、好动、软弱、喜欢聊天的孩子都会被淘汰。

敌工部部长林佰光很快走了进来。他原来在某县的县委办副主任，对做官很有一套自己的思路，年纪轻轻就爬上了相当高的位置。不过他志向远比在一个灰头土脸的小县城里当个公务员要大。冉耀知道这个人是典型的中国式官僚，脸上上永远带着笑容，说话永远带着章法，对任何事情评论都是点到为止，喝酒带劲，从来不倒；有时候待人比亲兄弟还好；也随时可以翻脸不认人。

冉耀还知道此人把自己上船的配重全部带了生活享用品，光香烟就有几十条——可又没见他抽过。冉耀每次召集保卫总署的会议，桌子上都有一二包不知来路的中华烟，应该就是他拿出来的。

最可疑的是他有一个用太阳能的PDA，晚上常会拿着它看来看去，时而还会写些什么。谁也不知道他在写什么。冉耀认为，他绝不可能是在写小说，倒可能是在写日记之类的东西。搞不好还是黑账本。

不过，林佰光这个人的工作能力的确很强，工作态度非常积极，堪称神人。不仅很快就学会了拗口难懂的临高土话，还自学了广东白话、闽南话和南京官话。最近他发现此人又在早晨反复念着一种奇怪的方言。

“这是满语。”对来询问的人，他如此回答。

冉耀心想：这小子的野心还真不小——不过有野心才会有动力。

--------------------

“我不知道你打算怎么卖味精。”张信说听了他的初步设想之后说，“要我说如果没有粮食管制上的问题，米粉干的思路不错，因为人人要吃的。但是味精就是锦上添花的东西了。有钱人不需要，穷人没必要。”

有钱人吃东西考究，用得是整鸡火腿慢火熬制出来的高汤，看不上你这人工鲜味剂。穷人吃饱饭都是个问题，想不到要这玩意——再者味精毕竟只是调味料不是罐头汤，放点味精没法“清水变鸡汤”，这使得它的销路大成问题。

--------------------

张信原本很担心计委不愿意支持他们——自从德隆银行进驻广州收走了广州站的财务权之后，郭逸一度有了想辞职回临高任职的念头，自己在广州势大财雄，加上出身有问题，算不上根正苗红，还是及早退位避嫌为好。但是张信力劝不可：眼下德隆刚刚进驻，如果立刻辞职不但不会被认为是避嫌，反而和被认为是对组织上不满的示威。

郭逸一想此言甚对，便打消了这一念头，好在孟贤此人在阿美利加待得久了，沾染了米夷的风气，为人还算爽直，干起活来又是一丝不苟，几个月下来倒也相得益彰。

--------------------

“各位兄弟！”林佰光这几天攒足了精气神，就等着这一刻。这一瞬间，县招商办主任的灵魂附体！他开始阐述起已经打了几周的腹稿。着重说明：目前临高正在百废待举之时，大家去投奔，必然受到重用。而且澳洲人占有临高，不论是船只休整驻泊都有根据地，而且人人都有宅院，不会象过去那样在海上四处漂泊，时时要受断水断粮的困苦。

--------------------

个人政治鉴定是在政治保卫总署成立不久之后开始搞的。在冉耀、[文德嗣][y002]、慕敏、邬德还有情报委员会的神秘胖子的主持下，很快搞出了一整套的评分方法、标准和等级。

根据这个体系。政治鉴定分为五个档次，用罗马数字Ⅰ到Ⅴ来进行标记。Ⅰ是完全可靠，Ⅱ是可靠，Ⅲ可控制使用，Ⅳ是不可靠，可利用，进一步观察，Ⅴ是完全不可靠。每个档次又有ABC三种不同的档次进行细分。穿越者自身的政治鉴定是从ⅡC起评；移民则根据他的年龄、职业、经历和鉴定官员的直观印象进行计分，最后得出鉴定结果。

文盲可以加分，只是识字不加减分。有任何形式的官府的学历的，哪怕是童生就要减分，书读得越多，在评定的时候得分越低。到秀才这一级，如果没有遭遇过被官府迫害之类的事情，基本上就是ⅢC级起评。对穿越集团来说，他们需要传统知识分子的帮助，但是传统知识分子在意识形态上面和穿越集团未必合拍，所以才闹出“知识越多越反动”的评分标准来。

--------------------

　“放心好了，每人不都有配了个翻译么。魏爱文说是一对一的搞洗脑，我说么——”邬德说，“重点是要教会他们新的生活方式——资本主义生活方式毒害了多少有为青年啊——等他们习惯了每天洗个热水澡，吃饭的时候来瓶冰啤酒，每周带老婆孩子去看场电影之后，除了临高其他地方给他多少银子和女人都不会走了。”

夏季渐渐过去了。1629年的夏天临高县城显得十分安静。一则天气炎热，城里人不想活动，农民忙着在烈日下夏收夏种，车水耘田，没时间进城。二来这座城市在经济上已经被逐渐被边缘化了，城里本来就不多的商户们逐渐被吸引到了东门市去开店做买卖，老百姓和士绅们也渐渐地习惯了这个新的市场，不管是买东西，还是闲着无事的散步闲逛，东门市可买的东西还有购物的环境上都比县城好得多。

城里的几户手工业匠人全部歇业关门了，包括县里唯一的铁匠铺。他们的产品和穿越者根本无法相比，甚至在价格上也完败。终于在自由竞争中落败。如今都不在县城了，据说在髡人那里当工匠，待遇不错。据看到的人说原本穷得叮当响的箍桶匠居然还娶到了个老婆，还带了四五个徒弟，天天在那里箍桶。

--------------------

原来髡贼送来的五十册书并不是那奇怪的《扫盲课本》，而是四书五经这样的“正经书”！想到这里，他竭尽全力的大吼一声：

“住手！”

王赐坐在厅堂上，脚下是个藤编的箱子。里面，正是劫后余生，从祝融口中抢回来的书籍。门子刚才烧水引火，已经烧掉了好几本书了。对王赐先逼着他烧书到后来又象疯了一样冲过来不许他烧的行为，门子很是迷惑，只能解释为天气太热，王老爷大约是有些痰迷心窍了。

王赐顾不得门子想什么，赶紧一本一本的捡看。

一箱子书，大多是“十三经”，也就是儒家的十三种经典著作，包括《尚书》、《周礼》、《论语》、《孟子》、《尔雅》等等。这是过去科举考试的基础。能通读十三经的人，古代就算是个知识分子了。

箱子里原来有一套完整的十三经，不过已经被门子烧掉了几本、这套十三经，除了开页向右和字体横排之外，全书没有一个俗体字，而且印刷的极其精良。一般书籍里的分隔字行的线格完全没有踪影，字句之间却排列的上下左右一边整齐，这种纯白底子上黑字白纸的效果，就是王赐过去见识过的最好的宋版书上都没有。不知道澳洲人是如何办到的。

王赐觉得唯一的不妥之处是都加了句读，自然这么一来读书就大大的省却了功夫，但是澳洲人的句读——他实在是放心不下，焉知这群海外蛮夷能不能领会圣人的语义呢？

随手选了一本，看了看，发觉其中句读并无分毫的错误，王赐纳罕：澳洲人也不是这么粗鄙么！

越想越想不通，又看了看里面的其他书，里面还有套十三经注疏的。实际上这是周洞天盗版的中华书局版的《十三经清人注疏丛书》。自古以来，为十三经做注疏的人不少，清代对十三经的注疏又是一个新的高峰，特别是经书文字的解释和名物制度等的考证上超越了前代。周洞天选择盗版的时候也考虑过：第一必须有较高的学术成就，第二不能是前代的作品——这样就显不出穿越集团的本事了，所以清代的研究成果就首当其冲被盗用了。

十三经注疏他自然是看过的，但是眼前的著作他自然是第一回看到。也自然就以为这注疏就是澳洲人所做。看了几页，不由得拍案叫绝——这注疏的水平之高，绝不次于他读过的汉唐宋元以来的前代注家。王赐不由得迷惑起来了。

--------------------

原来是一本送人情礼物用的账本，和州县官们师爷交接的时候要照例要讨价还价的“送礼账”是一码事。无非是需要打点的各路官场人物的资料和“三节”奉送的各种例规银的数目。苟家兄弟干的这种买卖，没有官府的照应是干不长的，就算没有勾结，也得照例打点，买个平安。

苟二的这本“人情底账”开列的十分详细，林佰光粗粗一看，有海南的临高县、澄迈县、儋州、琼山县、琼州府五套班子还有一个雷州的徐闻县的全部官吏名单，每个官吏都有籍贯、科名、生日这类私人资料，除了官吏本人，还有他们的家属子女资料。编写的十分详细。这本账本上更改的地方不少，有的人名被勾去了，后面不但注有去职的时间，还有去职的原因：升迁谋职、卸任、调任、死亡、获罪等等。

粗粗一看，大体从天启元年到天启七年之间本地和周边的官场的动向和贿赂价码一目了然。

上面，吴明晋、吴亚等临高官场上的主要人物的资料也一应俱全。也有三节一寿的馈送标准。

林佰光却没孙笑这么兴奋，这东西他早就见识过类似的。

“不会的，因为这不过是官场潜规则的底册而已。”林佰光道，“三节一寿、冰炭二敬这类馈赠，在明清两代算是当官的正当收入，皇帝老子都知道下面当官的有这个——起不了风浪的。要真正的大宗贿赂的底册。”

知道具体的代号指的是谁，这是关键。有了这个，这些材料就成了不折不扣的黑材料，丢出去的杀伤力可比一本“三节二寿”的送礼底单厉害多了。正如“潜规则”女艺人是花边娱乐新闻，强奸了女艺人就是刑事案件了。

--------------------

不管采用哪一种方式，穿越集团都有把握准时准点的把今年的秋赋缴清。这样就可以从容的丈田、清理户口。而不用赶着征税期限里来做这些事情——所谓慢工出细活，邬德的打算慢慢的熬制这“新税制”的粥。

这对穿越集团是个很大的工程，为此执委会已经下达了好几道命令给各部委员办局和公司。

雷州糖业公司接到指令：继续向越南销售食糖，同时可运销一部分当地需要的其他的货物，以大量套购越南的稻米。

给海上力量部的命令是要他们集中运力，抢运越南的稻米到临高。争取在农历十一月前将临高糙米的储备提高到三万五千石。

给外商委的指令是：利用越南的稻米在雷州的三县里用套购白银，额度是一万两。这笔银子是为了临高的“辽饷”而准备的。邬德预计临高的米价会因为征收“辽饷”而下跌，他们正好抛出高价卖米换来的银子再低价收购粮食。

给教育部的指令是要他们立刻开始在学生的实践课上安排测绘、简单的平面几何运算之类的课程，为全面丈量土地准备人手。

印刷厂也接到了通知：即刻印刷大批空白地契和产权登记本。

--------------------

暂收爪牙，雌伏在地自然是眼下最好的选择，但是他们认为髡贼是不会放过自己的。长治久安的法子，自然是引官军来进剿，才能一了百了。

本府的官军，理论上是遍及全岛，本县里也有卫所，但是真正堪称能打仗的，只有琼州府的海口千户所白沙水寨的二千多官军。

黄家父子在临高固然很受县里的器重，到底也只不过是个土豪而已。不要说琼山县的汤参将根本不会买他的帐，就算本县的千户百户们也懒得理会他。黄守统从少年时候起就受够了他们的白眼。

本事没有，却一个个眼高手低；自己无能，也不许别人显露本事；不愿办事，功劳要争。这是黄守统几十年来和官军合作之后得出的总得结论。除了镇压没有几件铁器，拿竹木为兵的黎人暴动的时候官军还堪称敢战之外，其他时候的表现实在不敢恭维。

就算汤参将肯倾巢出动，也不是这伙髡贼的对手。要剿灭髡贼，非得全省会剿不可。出动四千到六千战兵，二三百条大战船才有可能。黄守统自己都被这个数字吓了一跳。这不得出动一二万人了！

--------------------

拉拢周七的一个目的是要他充当顾问。旧的粮赋征收体制里有哪些弊病、作弊的方式……这是这一特殊行业里的秘密，是看多少古籍资料也看不来的，周七跟着陈明刚十几年，这方面的积累一定很多。

另一个目的是在清算胥吏的时候能让其搞揭发——周七既然是陈明刚的大徒弟，衙门胥吏阶层里的丑事肯定知道的不少，正是把人批倒批臭的好材料。一般人总把私德和公事联系在一起。私德上的丑闻不但可以整人，而且还能让整人变得群众喜闻乐见。

--------------------

“没有的事！”邬德矢口否认，“计划就是原先的计划。走到现在这步，多少有些机缘巧合，也是人心使然。”他说，“我们利用陈明刚的一点算计，陈明刚知道的很清楚。他何尝也不是在利用我们。他只是算错了二点，一是我们掌握有超越时代的科技和管理水平，不需要他那套视为瑰宝旧体制。第二，他不清楚我们的野心是在社会体制改革，而非简单的聚敛。这实在怨不得他，因为他不可能有这样的见识。”他吁了口气，“这大概就是时代差异的带给我们的优势。”

--------------------

缴粮的人流很快就挤满了德隆的三家支行。一时间业务量暴增。这一片大好形势让领导小组的成员欢欣鼓舞，不过也带来了忧虑。每天有好几百人在排队缴粮食的场面使得营私舞弊的可能性大大增加。邬德深知人性的弱点，在金钱面前绝不能把信心寄托在人的自律上——必要要有严格的制度。

德隆作为穿越集团的重点企业，所有的土著员工都是穿越集团精挑细选出来再加以培训的，不但业务熟练，而且忠诚度级别很高。

“忠诚不等于廉洁。想靠忠诚度来自律是痴心妄想。更不要相信所谓某种人信仰了什么就能例外。”严茗说。没有哪个贪官污吏不是衷心热爱提拔他、授予他权力的体制的，但这这种热爱并不妨碍他大挖体制的墙角来填满他自己的腰包。哪怕这样做会最终毁灭体制他也不在乎。

他对邬德的忧虑深有同感。他是学会计出身。出于职业的关系，对使用严格的制度来规范人的行为要比其他人的感受深得多。为此他早就在德隆内部建立起一套现代的会计制度，这套体制保证了德隆迄今没有发生过大的内部舞弊案件。

现在，他的制度又得到了文具厂开发的新产品的支持，首先就是复写纸。这样就能够开具笔迹完全相同的一式多联单据。过去也有手写的多联单，因为是分几次缮写的，在核对的时候就无法判明到底是一次性写成还是事后补写。

另一个重要的新产品就是水印纸。古代也有原始的水印方法，但是效果不好。印刷厂为征粮印刷的大批标准文书全部使用了新出品的水印纸，这种古代技术根本不能制造的新式纸张使得原先在征粮中相当猖獗的挖改凭证的手段再也无法实施——胥吏和师爷们尤其擅长这种手艺，能把文书、票子挖掉字句，使用纸片和浆糊进行补缀成完璧，再用墨笔改写。一般人绝难看出来。

除了严茗在内部加强监控，采用各种技术手段进行防控，邬德还专门组织了“飞行检查”，不定时突击检查各处支行的账目，核对征收进来的粮食和流通券数量。另外还派人进行暗访，看看已经命令禁止的大小斗、堆尖之类的舞弊手段现在是否还有人使用。

--------------------

凭借着现代管理经验和大批训练有素、经过培训的初级行政管理人员，救灾很快就步入正轨。原本县城内外的难民满街求乞的场面很快就消失了，取而代之的是井井有条的难民营。同时给受灾的村落提供救助的行动也在有条不紊的进行中。

但是邬德对此不甚放心。基层行政的一大特点就是不管上层有多么良好的愿望和决心，还是很难控制住每一个底层行政人员的作为，特别是在规章制度不完善有漏洞的情况下。而一个基层行政人员的为非作歹，足以败坏全体行政人员的形象。这使他绝对不想看到的状况。

自古至今，自然灾害之后的赈济最后总会变成基层当权者的盛宴，这已经成了公开的秘密。连朝廷也无可奈何——明知道救济钱粮下去会被层层盘剥，到灾民手里十不存一，还是要继续下拨，否则自然灾害就会激起民变——有时候就是拨了也一样激起民变来。所谓盛世和末世的一个重要区别就是前者救灾物资多少能分到一些给灾民，而末世就成了彻底的瓜分独吞。

“说到底，就是行政能力的衰退。”邬德在和冉耀的谈话中说道，“盛世的时候，机构运转正常，官吏的腐败程度还没有影响到行政执行能力。随着腐败越来越严重，行政体系的执行能力也跟着下降了。”

现在为了救灾，已经动用许多昨天还在培训班里的学员参加第一线的工作，通过他们的手散发大量的救灾物资——很多物资只要有心，要贪污起来并不难：糙米里掺点沙子稗子，只要量控制得好，绝对不会引人注目。而百姓们也没有现代人这样强烈的举报维权意识。

登记灾民又是一项有很多漏洞可乘的工作。正如邬德过去见识过的低保。需要低保的人没低保，倒是很多吃喝不愁的人拿了低保在打麻将。以现代社会的政府对基层的强大控制力尚且要漏洞百出，何况条件恶劣数十倍的穿越集团？邬德很清楚自己是不可能一个个的逐一核对那些领取赈济米获得粮赋豁免的灾民到底是不是真的受了灾？如果有人要浑水摸鱼，不被发觉的可能性很大。

--------------------

果然接下来他的发言就暴露了极权主义的强烈倾向。首先他就要把特别审计委员会的名字改成肃清腐败及怠工特别审计委员会，简称“契卡”。

“你看，来了吧？”冉耀嘿嘿的小声笑着，“这些人有点哈德分子，哈德分子一听铁十字勋章、坦克、88炮就要兴奋。他们一听KGB、盖世太保和契卡就会心花怒放。”

众人面面相觑，终于有人提出：就算是俄语，肃清腐败及怠工特别审计委员会的简称也不叫契卡。这么赤裸裸的抄袭是不是太过分了。

“不过分。”裔凡看起来神采飞扬，“反腐是一项长期工作，是公开活动和秘密侦查的综合体。”他慢条斯理的掏出眼镜布擦了下眼镜，“诸位大概也明白，反腐的关键是预防，而不是事后抓人。抓再多的人，办再多的大案要案，甚至把执委拉出去枪毙以显示我们的反腐决心也是无意义的——腐败的恶果已经产生了。”

“这小子够狠。一上来就要枪毙执委啊。”财政金融人民委员程栋笑道。

--------------------

驻当地情报站的情报员来源，他决定先由自己来担任这个情报站的站长，具体指导当地工作。现在情报工作训练班之类的短期训练班是办了不少，但是学员的年龄普遍偏小，这样的人要他们来独当一面显然是不行的。

林佰光对执委会在关键性岗位只进行土著青少年培养很有微词。青少年固然有接受能力强，容易被洗脑的优点，但是一味的强调培训少年儿童的结果就是在很多地方缺少可以主持大局的关键性干部。在他看来：人的忠诚度，并不是单靠洗脑就能完成的。

正如这世界上没有无缘无故的恨，没有无缘无故的爱，也没有无缘无故的忠诚。要想让下属忠诚，现实好处要给够，心理上也要常常拉拢，最好还有一面理想主义大旗竖着。三管齐下，大多数人都能搞定。赤胆忠心未必见得非要孩子才能办到。

以现在穿越集团对待土著员工的态度和做法来说，已经使得他们形成了相当的忠诚度。唯独有一点，林佰光认为是不够的，那就是理想主义的大旗。

到目前为止，穿越集团还没有提出过一个明确的意识形态。用大明的外壳做伪装固然方便又安全，也能抵消不少土著的涉及“造反”担忧心理，但是从某个角度来说也失去了给那些野心勃勃的人一个希望。任何时空中都存在着一大批不满现实秩序的人。他们充满了对现实的不满，渴望有所改变，但是他们又很清楚自己的能力不但不足以登高一呼，连当个土豪的本事也没有。

如果有人能给他们这样一个机会，这批人同样会爆发出很大的力量，来争取他们在旧秩序下原本得不到的东西。林佰光和招降来的海盗喝酒的时候，不止一次地听到他们打听澳洲人未来打算怎么样？几乎每个人都巴望澳洲人有一天会举旗放炮，来个逐鹿中原，自己也好混个从龙之臣，封妻荫子。

太平天国打下永安就迫不及待的称王封王，后人看来不免有过于猴急的感觉，可是当事人却是实实在在的过了一回出将入相的瘾，而且充分领导层“把革命进行到底”的决心，提升了士气。

现在执委会这样刻意模糊自己的企图，稳则稳矣，对鼓舞士气未免不利。很容易让大家陷入一种小富即安的局面。BOSS没有野心，如何能招揽能人？日本四岛上的织田信长还知道刻个“天下布武”的印章到处盖，让世人知道自己的野望呢。

这个思路回去之后一定要和执委会谈谈，把意识形态的大旗竖立起来。再就是用人问题上，现在用人体制太严了，简直比当年的共产党还厉害，对开展工作不利。

林佰光对用人的概念就是不拘一格，不管你是哪一种人，只要能为我所用就要用，当然前提是自己能够控制住他。他认为这才能体现出领导用人的水平，象执委会这样凡事先看是不是“可靠”、“历史清白”的用人办法，他是颇为嗤之以鼻的。当然这样的看法他是不会对任何人说的。正如他过去在县里也从来不和任何人谈自己对县委班子里某些人行事风格的看法。

--------------------

精英也好，狂热分子也好，林佰光打算以琼州府为舞台看看他们的实际工作能力。

他回到庙里的下处，陈同和高弟正在等他。林佰光出去的时候，故意没关照他们该如何如何，而且还每人给了他们一两银子的零用钱。

琼州府到底是比临高繁华得多的花花世界，他们又都是十五六岁的少年人，原本就是好动的年龄，手里有了钱，又有空闲，能不能把持得住安静的待在庙里等他回来是个很简单的测试。

--------------------

林佰光又抓紧时间走访了好几个部门，领了需要用的各种装备和物资。到处填表、开单子，盖章签字，让他恍然又回到了当公务员的年代了。

看来所谓的制度化本质上就是官僚化。看到机构不断膨胀的执委会，上下楼梯跑酸了腿的林佰光这样想。

几天之后，已经打扮成大明富商林佰光带着一众人从博铺坐船出发了。

林佰光走的时候觉得一身轻松，很多穿越众对临高、对百仞城已经有了特殊的感情，把这里视作自己的第二故乡和小安乐窝，每次因公要离开的时候总是不大愉快。但是林佰光却没有这样的感觉，反倒是有了一种天高任鸟飞的舒畅自由的感觉。他隐约有一种预感，自己将会以琼州为起点，踏上一条漫长的道路——他不会再回临高了。

--------------------

[萧子山][y001]太了解穿越众的业余生活了。除了少数技术狂人每天窝在自己的车间、办公室、实验室里忙个不停之外，大多数人的业余生活基本上是拿着有限的电力配额在电脑上玩游戏、看小说，看A片。荷尔蒙大量分泌，该发挥作用的器官却没用，时间久了未免影响健康。最近卫生部报告无菌性前列腺炎发作的病例呈上升趋势，[萧子山][y001]知道这多半是“憋”和“撸”双重影响的结果。所以这次在派遣人员的时候他特意提请给矿长配一个“生活秘书”。

--------------------

[马千瞩][y005]接着又遭到了张柏林的骚扰——他听说大炮和炮弹已经停产，正在全力转产民用机械，直接上执委会上“讨说法”了，

“[督公][y005]，你这是自毁长城啊！”张柏林摆出一副沉痛的面孔，“敌人打来，我们陆军弟兄们难道拿着二代矛和砍刀去抵抗吗？您要三思啊，呜呜呜。”

“只是停几个月的生产，再说最近的铸炮配额主要是为海军造舰炮。”

“是这样啊，”张柏林的眼泪没有了，“……不过海军舰炮也是穿越国的武备，不应该说削减就削减吧。再说炮弹，现在这点炮弹，打起仗来还不是片刻功夫就用完，没了大炮我们靠什么抵抗敌人的人海战术……”

“机械厂有人说能用混凝土做炮弹代用，比不上铁炮弹，凑合凑合也够了。”[马千瞩][y005]想到姜野在OA上写过这个想法。说起来混凝土炮弹以后还可以做教练弹用，铁炮弹的回收总有找不回来的损耗……

“这弹道性能能一样吗？”张柏林还想继续说下去。

“你要苏修一样多得炮和美帝一样无限的炮弹么？要得话就忍一下，我现在很忙，以后再谈吧。”[马千瞩][y005]说着好不容易的把他哄走，擦了下脑门子上的汗珠，看来以后必须建立规范会见制度，不能张三李四跑来就进他的办公室，这样一有重大举措就没法干活了。

--------------------

护航兵力为2艘8154渔轮，机帆炮舰“镇海”，风帆炮舰“伏波”，其他帆船上每船装备了8门48磅卡隆炮、2挺“打字机”作为自身防御之用。

“迅鲸”号在船台部分安装了2挺打字机，至于装上了柴油机的机帆化的“大鲸”，它用来搭载一个陆军炮兵排，2门12磅1857式加农炮直接架设在甲板上的沙袋炮垒内，另有1门12磅山地榴。安游乐市若是识相便好，不识相的话，炮兵教导队就要用它来练手了。

--------------------
开发三亚，建立三亚特区的执委会会议公报已经出了二十多期了，每期公报都包含会议上的“可公开内容”，其目的主要是用来征求建议。有心的群众已经发现，到目前为止，公报还没有涉及到派遣干部的具体人选上。

毫无疑问，三亚一开发，整套班子搭建起来，五百众里又有若干人会升职当官了，这对在前一阶段的机构扩充中没有捞到一官半职，继续处在无帽子首长地位的普通穿越群众来说是个绝好的掷升官图的机会，而且风传这次去三亚的干部比照去琼山的例子，全部给配生活秘书。这让极有上进心的同志们立刻产生了很大的遐想，有人便积极行动起来准备争取这些空缺的职位了。

于是执委会关于三亚开发项目的讨论组里，各种各样的意见和建议充斥着。高明一些的，以自己的专长和技能作为切入点，痛陈在三亚特区设立相关部门或者企业的重要性，引经据典的撰写可行性报告。这样的人大多掌握一定专业技能，而且比自己高明的已经在前几轮已经被选拔上领导岗位了，再设置这类职位就非自己的莫属了。

水平差一些的，只好简单直白的翻来覆去的强调某些机构和岗位的重要性，这些机构和岗位基本上是不需要什么专业技能的。

没有技能也不想玩曲线要官的人很直白的干脆得伸手要官当——自己当基本劳动力这么久了没功劳也有苦劳，现在给个行政小官当当总是应该得吧。

--------------------

一股暗流在内网BBS上涌动，抱怨的言论正在不断增加，不时某个帖子还会引起辩论。前几天就有一个帖子《如何教育生活秘书》，原本是某宅男的YY贴，讨论得是如何教育生活秘书使其符合穿越众的审美趣味。包括从传统高雅的琴棋书画，到不甚高雅的坐缸；从现代高雅的形体、芭蕾舞，到比较庸俗的按摩桑拿，献计献策极为踊跃，盖楼一度达250层以上。正在兴高采烈之际，某人忽然发飙歪楼，置疑执委会生活秘书分配到底以什么为标准。

这一问无疑引起了众人的心事，一时间群情汹汹，嘴炮横飞，大有“就差二个人”之势，直到有人喊出了“丰城轮一声炮响”的时候，这个帖子就被锁了。

虽然BBS上采用的是实名制，但是穿越群众显然比另一个时空要大无畏的多，马上就有许多人发贴质问锁贴的原因，有人试图为执委会开脱，立刻惨遭划时代的“五流通券”帽子，于是局面从一边倒的声讨变成了两边混战。不知道怎么的话题又转席亚洲身上了，当年删贴的积怨被人重提，群情激奋中有人提议“二次革命”之后立即就把他枪毙。正当双方刷贴盖楼的气氛达到高潮的时候，0点汽笛一响，[常凯申][y010]准时拉了电闸，全部讨论中止。

--------------------

[萧子山][y001]穿着暖和的外套和毛衣，在百仞城里的道路上走着。路上遇到的穿越众都要和他打个招呼，所以他一路上都是在点头，说：“早”、“今天真冷”、“这事一会考虑考虑”。他身为办公厅主任，负责管理五百众的吃喝拉撒，所以差不多每个穿越众都认得他。

办公厅主任的职务并不显赫，但是人头熟悉是一个很大的优势，[萧子山][y001]觉得现阶段做这样的工作比较好。

--------------------

*关于女仆革命中独孤求婚事件各位元老的回忆记录，写得也真是够生动的。*

几十年后，当帝国的旗帜在全球飘扬的时候，帝国的初期历史不再是禁忌的话题，史学家们对元老院的这段“禁忌之史”进行了系统的研究。由于元老院的特别恩准，许多初代目元老的非公开回忆录、会议记录、官方档案得以有限开放给历史学家们阅读——不得复制，不得携出。

发生在旧耶历1629年，大明崇祯二年，圣历1年12月底的“女仆革命”是史学家们最感兴趣的课题，而“女仆革命”当晚的许多历史细节至今依然扑朔迷离，说法不一。独孤求婚有没有率队进入百仞城，如果没有又是谁在独孤求婚到达东门之前把他拦住，迄今为止一直是史学界争论的焦点。

根据元老院的官方记载：当晚独孤求婚调动警察队向东门市开进的时候，被负责百仞城东门警备任务的特侦大队的几名军官所劝阻。在北炜和薛子良的劝说下，独孤求婚放弃了继续向城内开进的念头，退回了东门市派出所。

但是根据原叶孟言的回忆录《长刀第一夜（禁刊稿）》一文的记载，当时是他和薛子良两人同时执行拦截独孤求婚的政变队伍——精锐的SS警察团。当时百仞城内唯一的武装力量就是一个不满编的特侦大队，兵力极其悬殊。双方在百仞城东门外遭遇，我方当即向独孤求婚喊话，要求其解除武装，退回原驻地听候处理。忽然警察队中有人向特侦大队开枪，薛子良一听枪响就带头逃跑，造成我方很大的混乱。我方在叶孟言的奋战下得以扭转形式，经过激战将参与政变的SS警察团全部击溃歼灭，随即活捉了独孤求婚。

薛子良在自己的回忆文章《光明的灯塔指引我走向人生辉煌》一文中却是大相径庭，表示当时没有发生任何冲突，他独自一人带着几名警卫员赶到东门大街的时候，虽然独孤求婚的警察队武装到了牙齿，不但有米尼步枪，还装备了当时极为罕见的SKS步枪，当时多人企图对他实施人身威胁，但他还是一个人以大无畏的精神赤手空拳就解除了警察队的武装。“没有人敢发出反抗的声音，连不满的支吾声也没有。”

前工兵总监潘达的说法：当晚他正在连里和士兵一起准备新年庆祝晚会，听到消息之后，严守纪律，没有出动部队，更没有带武器，只身一人前去拦截独孤。他头戴安全帽，一手持工兵铲，一手持锅盖，以张飞独立当阳桥之势，在东门大街上昂然而立，乱兵到此，为之气夺，不战而溃。潘达在回忆录中写道，“后来有人问我面对如林的刺刀和黑洞洞的枪口有没有害怕，我说害怕是有得，但是想到背后就是执委会，我就什么也不怕了。”

但是前军工生产部部长林深河否认有这回事，在《帝国春秋》的一篇访谈文章中，他说道：“当时正是我带领工能委的群众一起用手持撬棍和扳手拦住了警察队。”林深河说到这里很激动，“来得警察队一个个都是顶盔贯甲，手持大棒，要是不把他们及时的拦住，恐怕城里不少人要头破血流，大业毁于一旦。”

记者问：“当时参加拦截的元老还有哪几位呢？您说的工能委的群众应该都是元老吧？”

林深河（迟疑了一下），拍了脑门：“哎呀，记不清了，人老了，记忆力衰退了……”

几个月后《帝国春秋》又刊登了一封帝国元老王瑞相的来信，信中郑重指出：当天林深河在博铺对“打字机”的陆军版进行改进，根本不可能在夜里赶回来拦截警察队。而当天奋不顾身，挺身而出，大义凛然的拦截警察队，劝说他们返回的正是他王瑞相，还有海军的几名军官——不过因为年老的缘故，他也记不清海军的几名军官姓甚名谁了。

由于宣传部的介入，《帝国春秋》很快声明将不再刊登其他元老关于此事的来信，但是在《帝国农业》杂志上，又刊登了原农业人民委员，元老[吴南海][y009]的回忆文章《稻熟猪肥忆往昔》，文中提到，当晚的示威队伍在农庄咖啡馆前就被他拦住了，带头的马某和单某后来在农庄了喝醉了，第二天一早才递交的请愿书，从来没有发生过任何示威活动，至于独孤有没有发动警察队企图进城，他不在城外，不清楚此事。

教会史的官方编撰集《在上帝和元老院的荣光下》关于此事是如此记载的：百仞修院的修女们上街祈祷，在圣歌声中，一道白色的光芒照耀在东门大街上，警察队的士兵们纷纷流着眼泪丢下武器，跪下祈祷。独孤求婚也被主显荣耀所感化，当即向赶来的白多禄大人忏悔，并且表示愿意将全部财产捐助给教会。

当事的另一方，被指斥为“野心家”、“叛徒”、“X公的走狗”，被轰杀成渣，差点就此一蹶不振的独孤求婚在自己的回忆录《我的钢盔我的团（内部发行）》中写道：当晚一小撮阴谋家、野心家、伪民主主义者、“职业民主闹事分子”（简称民闹），为了女人的问题，就煽动大批不明真相的群众围攻执委会，妄图推翻穿越大会选出的合法行政机构执委会。为了一己私利，一点下半身的福利，不惜发起暴乱来动摇大业的根基，这是典型的小脑指挥大脑。他在文中表示：自己集合了警察队，不过是防备有土著乘着百仞城的内乱发起暴乱而做得必要的戒备。事后居然遭到种种诬陷和打击，致使自己蒙冤多年，受到种种“不公正待遇”，这是一小撮野心家为了掩盖自己的罪行而施行的“欲加之罪”。至于教会向元老院荣誉法庭起诉要求公证他曾允诺死后捐献全部财产的事情，这更是子虚乌有——他从来不曾受洗，更未说过要把财产捐献给教会。

最后他指出，这一小撮野心家的历史旧账并没有得到完全的清算，而多年来元老院一直没有给他公平待遇，他的二十几个子女里还有十来个没有具体的出路安排。

--------------------
开弓没有回头箭，单良很清楚，女仆革命之后，执委会的一干人虽然权势根基不深厚尚不敢对他下手报复，但是自己被排挤出未来的中心权力圈子已经是必然，不仅如此，未来自己的脑袋上肯定会有玻璃天花板。他深思熟虑了几晚之后下了决心，自己不能就此沉默下来——恰恰相反，要不断的发出自己的声音才能保证前途。

“被遗忘就是死亡。”单良默默的想着，决定去找成默好好谈谈——他和成默之间没多少交情，但是这次游行之后自己面对的问题也是成默要面对的，大家有共同语言。

两个人见面之后在文澜河大堤上畅谈了一番，这次谈话之后，单良更坚定了自己要“从政”的决心——既然靠技术上位的道路已经不可能，就只有尽量利用女仆革命的余绪把自己打扮成为民请命的代表了。为此他积极的活动起来，把自己的业余时间全部贡献在“政治活动”中了。

--------------------
至于不做总结发言则是马甲对国人开会习惯的一种校正。但凡国人开会，习惯上领导主持会议，最后要做总结性的发言。这个总结看似是归纳大家的意见，本质上是一种“定性”结论。所以很多会议讨论来讨论去，与会者说得全是模棱两可的话，原因就在于此——无论你说多少，都拗不过最后的定性。

一旦总结定性，等于是变相指定了与会者的投票，与会者会自觉或者不自觉的按照定性的结果去投票，最后就会形成一边倒“全体通过”的局面。所以马甲的议事规章里特别注明：会议主持人不得进行总结，与会者——无论是谁，也不得进行所谓的“总结”。

--------------------
新版的执委会由9人组成，每人各分管一个方面，9名执委直接向元老院负责。

这9名执委分别是：

元老院议长：分管元老院，主持元老院全面工作，负责常务委员会的日常工作，监督执委会工作。（潜水艇）

执委会主席：主持穿越政权的全面工作，兼任穿越国家的武装部队总司令，对外是国家的代表。（文德嗣）

国务卿：分管经济，主持中央政务院全面工作。（马前卒）

企划院总裁：分管穿越国家经济、政治、军事的长期规划和布局，负责物资管理和配给。（伍德）

制造总监：分管工业和科技。（展无涯）

殖民及贸易长官：分管所有海外拓殖活动和贸易。（司开德）

财政总监：分管财政和金融工作。（程栋）

军务总管：分管军队建设和组织工作。（何明）

仲裁庭代表：分管司法、保密和政治保卫工作。（马甲）

除了这9人之外，执委会办公厅主任（萧子山）也属于执委会的一员，但是在会议上他仅是列席地位，只有发言权没有表决权。办公厅主任分管政权机构的日常事务，全体穿越众的生活福利，同时管理穿越众的组织人事工作，相当于兼任组织部长。

--------------------

法学俱乐部认为，在现阶段要解决这个问题，只有两个途径：一、花大力气提高全体穿越众的生活水平和待遇，使得当干部没有吸引力；二、迅速制订一套干部管理制度，对干部任用体制透明化、制度化，对大家反应强烈的干部享有的种种特权进行限制。

但是这些问题在大会上无法一一讨论，只有在新一界政府产生之后由他们去解决了。大会只做了一个原则性决议：责成新一届政府制订一部《干部管理条例》供元老院审议。当然，这事由法学俱乐部来承办最为合适了，董时叶按照事先安排的，不失时机的提出动议，要求在新一届政府内设立专门的机构来办理起草法案的事项。动议很快通过，法学俱乐部的人不由得喜上眉梢——这下可都混上编制了！

--------------------

[马千瞩][y005]则提出了另外一个缓和干群对立的动议：要求所有有职务的穿越众每周参加一次户外和重体力的义务劳动，他的本意是通过这个办法来提倡“同甘共苦”。这个动议提出之后立即得到了杜雯旗帜鲜明的支持发言，随后就陷入了冷场，无论赞成还是反对都没有人提出新的发言要求，马甲在三次询问是否有人要发言无结果之后宣布表决。

在座的元老们有一点是确信无疑的：第一个五年计划之内，他们迟早个个都能混上一个或大或小的职务，不用当现在这样的无帽子首长，现在订出一个劳什子“星期六义务劳动”，岂不是将来给自己找不痛快？再说现在干部来干体力活不过是来做SHOW而已，对自己又有什么好处？

群众们彻底的实用功利主义让[马千瞩][y005]觉得很郁闷，看来群众在本质上还是落后的，需要不断的教育。[马千瞩][y005]随后在自己的小本子上写下了如下的话语：“议会民主在本质上是落后的，是人为自己的弱点寻找合理性的一个场所……”他默默的读了好几遍，把纸条撕了下来，扯了个粉碎。

--------------------
赵曼熊斯基继续在他自己的办公室里办公，冉耀留给他的是一个即系统又残缺的组织体系——过去很多机构是强力部门共用的，比如审讯处，政保总署的审讯处既负责审问“危险分子”，也审问普通的犯罪分子。现在这个审讯处被一分为二了，负责人周洞天还是个兼职人员，很难说他会选择国家警察还是政保总局——或者更糟，他要求保持现状，继续当印刷厂的厂长，只是来兼职。

干部匮乏是政治保卫总局最难办的事情——不管是元老还是合格的土著干部，但是问题还不止于此。冉耀虽然对内保工作不陌生，但是他的主要精力并不在这上面——赵曼熊斯基敏锐的感觉到——冉耀不喜欢干特务工作，这从他接手以来了解到的情况就能体会到。

他故意没让这个机构发挥最大的作用——政治保卫总署的确干了许多工作，但是始终忙于最基本的事务性工作，它做什么都带有强烈的技术性的色彩，好比是一个熟练的画工，虽然能画出许多美丽的图案花样来，但是没有一点自己的想法和审美趣味。别得不说，这个部门连最基本的工作纲领和组织原则都没有。

--------------------

处理方式没有引起争论，唯一引起争议的是这批武器。CZ99手枪是无人争夺，但是自动步枪、冲锋枪和机关枪如何分配却引起了激烈的争论。海军和陆军的军官们为了这批枪在BBS上大打口水仗，各自历陈自动武器对本军的重要性和必要性。

这种讨论以心平气和的摆事实讲道理开始，最后毫不例外的以恶语相加告终，结果自然是被全部删帖。

这个争论随后到了报纸上：

“自动步枪、冲锋枪和机枪从来就是陆军的标准武器，陆军拥有和使用它们是天经地义的事情。”在《临高时报》上刊载了一篇署名“一个忠诚无畏的陆军军官”的文章。

第二天，报纸上又刊载了一篇《接舷战中自动武器的应用》的文章，从战术角度阐述，目前的海战中自动武器对海军的重要性。

海军这手很高明，不明白的人只以为这是学术性的讨论，实则搞得是“润物细无声”，给大众一种“海军也是需要自动武器”的概念。

接着海军又接连在临高时报上刊登了多篇“学术性”文章，包括：《新形式下海兵在两栖作战中的战术》、《两栖特种战》等等。

这些文章或者相当专业或者干脆就是胡掰，但是共同点是一致的，或明或暗的点出了自动武器对作战的重要性。

“这是在造声势啊！”魏爱文把报纸拍到了桌子上，他虽然现在在总参，本质上还是“一颗装甲兵的心”，自然站在陆军的立场上。他马上给张柏林打了个电话：

“柏林！你们这下可落了下风了！海军正在报纸上大造舆论！”

“没错，我也看到了，这伙汉奸，尽玩阴的。”

穿越国的海军因为在体制、称呼上一股旧日本海军的气味，特别是《军舰进行曲》被正式剽窃为海军进行曲之后陆军就给其戴上了这顶帽子，当然海军给陆军戴得帽子是“黄纳”，以至于在公开场合和BBS这两个词是不许公然谈起得，以免引起双方冲突。

“这样下去机关枪什么的就有可能落到海军手里了，起码也得给他们分掉一半。”魏爱文很着急——这几天执委会就这个问题正在商讨，一旦他们被影响了事情就不好说了。

“海军的笔杆子多，我们这里会摆弄这个的人太少。”张柏林也为这事情犯愁，要说打架，陆军绝对不比海军差，但是在文绉绉的骂人和写文章上，陆军明显不如海军会搞。

“这伙汉奸欺人太甚！”魏爱文骂了一句，他想了想，“自己写写不了，你不会去抄？去图书馆检索所有和自动武器有关的战术文章，拼拼凑凑也赶快发，一定要把舆论的阵地抢到！”

“好，我马上就办！”张柏林放下电话，找了几个人商量了下分头行动去找文章。他想，光靠抄现成的怕是不大行，最好要和本时空的环境进行结合才行。

于是他动手撰写了篇小短文：《机枪就是炮》。写完之后觉得挺寒碜的，这都是什么和什么啊，但是看到报纸上一篇根本就是胡扯的海军枪手文，张柏林想反正也是彼此彼此。

于是陆海军的“学术论文战”愈演愈烈，这股突如其来的军事学术潮的目的稍微明眼的人自然是看得明白。在持续几天之后已经没什么“学术”好谈的双方开始互相对对方的文章进行挑错，暗示对方的学术水平有问题。

这场“学术纷争”到最后的结果是双方几乎要拳脚相加，虽然在陆海军人民委员的大力弹压之下总算没闹成更大的事件。

--------------------

这些女人对严格执行学校的纪律非常乐意，下手毫不留情，被高墙阻绝的院落内经常可以听见女仆们的哭叫声。

这一手叫做“知畏”，通俗点就叫下马威。和在学员和士兵中培养的服从命令守纪律的上下级关系不同，这里是完全不提倡任何自主自立精神，核心就是“感恩”和“知畏”，充分建立起对元老的个人崇拜和极度畏惧。

这种做法被不少女仆对策委员视为没有必要，有人甚至怀疑[文总][y002]有SM的趣味，[文总][y002]却高瞻远瞩的表示这是“事关穿越集团未来的安定团结”。

“男人有各式各样的，”[文总][y002]在女仆对策委员会的一次会议上说，“有人很有男人气概，也有些同志太阴柔了！不好好的整治整治女仆，让她们从心底里就产生最大的畏惧，很可能会在有些元老的家庭中产生武则天式的人物！”

女仆对策委员们顿时笑了起来——众人觉得不可思议。

“你们笑什么？我们出发的时空是个过于阴柔的世界，你们还以为自己很有男人气概？”[文总][y002]很man的一挥手，“我看你们个个都是怕老婆的料！”

大家笑得更厉害。

“哼，有谁敢说自己情人节没买过花？没请过女人吃饭？”

“[文总][y002]，这个不是一码事吧……”

“是男人就不需要这样花花泡泡的事情！”[文总][y002]痛心地说，“现代时空的男人一个个都被女权分子洗了脑，又被韩剧减了智商，把女人当成了天使不算，还要当成女主人、女神。”

安熙说：“[文总][y002]说得有道理，历史上被女人蛊惑的事情是很多的，要不然也不会有‘英雄难过美人关’的说法了。”

“小安同志很有见地。”[文总][y002]表扬了安熙，“言归正传！这种被女人操纵的可能性是存在的，现在就要从源头上杜绝这种事情！”

“但是女穿越众会不会有意见？现在的下马威教育法有虐待妇女的嫌疑。”

“谁有意见可以要求开大会嘛，我们民主投票表决，”[文德嗣][y002]说，“大家言论自由。”

“我看是不会的，”马甲说，“有人狠狠地收拾‘小狐狸精’还不好？”

--------------------

勋素鸡这回是大吃一惊了。开始是食品厂厂长，屁股还没坐热就是粮油公司副总，连升三级的水平了。

“这个，”他有点语无伦次了，“责任太大了……”

“没事，谁得责任不大？过去当连长的，现在在当陆军总司令，过去的有个法学学士学位的人现在在当法院院长——看他的样子要当司法部长，你这个过去的厨师当粮油总公司经理属于专业对口。”

--------------------

“啪嗒啪嗒”符不二只管抽了他的水烟，木着脸就是不说一句话。万里辉急了，大声道：“政策你是懂得！我们穿越集团什么时候说话不算话了？你好好的思量了一下，对你只好有好处没有坏处！”

这话收到了奇效。符不二有蹲过战俘营的经验，去年他在帐篷外面听里面过堂的时候，经常听见里面有人再声色厉疾说：“政策你是懂得”——若是哪个人“不懂”，就要被赶出来围着火堆无穷尽的转圈子，直到他“懂了”为止。

--------------------

林佰光被他的眼睛看得胆寒——这种海商巨渠的威势真不是盖的，什么叫王霸之气，这TMD才叫王霸之气啊，就俺们执委会那群一天到晚故作深沉，满口理论的人民委员，简直就是天上地下。

----------

“为什么要成立这么个空头机构？直接让专业部门和海军协调不就是了？”事后马甲不解的问[马千瞩][y005]。

“便于协调。抬头太大了，就不好协调了。”[马千瞩][y005]含蓄的说。

马甲明白了。这纯粹是为了照顾海军的面子。否则堂堂的海军受海关或者海事法院指挥——哪怕只是暂时的执行任务，这群人的面子恐怕也会觉得落不下来。搞一个次级部门来对口，协调起来就容易多了。

[马千瞩][y005]还有另外一层想法没有挑明：目前的穿越集团还属于势单力薄，等他们占领海南、台湾，经略南洋之后，海上力量部的实力会急剧膨胀。为了避免一家独大的局面，势必要对海上力量部进行分割。现在的一个空头机构，到时候就可以直接分割出去——海岸警备队独立建军是国际惯例，海军也无话可说。

选择高晓松当这个队长不仅是因为他本行干这个，还考虑了他的出身并非PLA海军。一旦海岸警备队被独立分离出来，不容易受到海军的影响。

当然这些[马千瞩][y005]是不会向任何人说得。他相信这点思路，执委会的多数人都是看得出来的，不过世界上的很多事情就是心里明白就好了，用不着到处说。

----------

马甲在海关大楼里选了一间办公室作为海事法院的办公场所兼法庭。眼下估计也没什么案件可以审理，先徒具形式再说。

趁热打铁，先搭架子拉班底，造成既成事实，这是国人最擅长的一手。马甲也不例外。

马甲一朝权在手就把令来行，当即在周洞天那里印刷了一批海事法院抬头的空白公文纸，请他刻了个大号的公章：图案自然是老掉牙的海水纹加天秤。他又加上一对中国特色的飞鱼纹。在空白的公文纸盖了又盖。觉得这个比海关那个好看多了。又到邬德那里选了个写字写得漂亮端正的土著当文书。正式行文给各部门，宣告本单位已经成立。

----------

刘大霖见澳洲人的头目穿着竟然如此的朴素，很是意外。照他听说的消息，澳洲人生财有道，又善于制造各种奇巧淫技的货物，积攒的财富应该不少，看他们平日里做的事情：修路造桥，办学堂，造大船，哪一项都是一掷千金的事业，没想到个人享用上却如此的刻苦！心里不由生了几分敬意。

熊卜佑迎了上来，寒暄几句，当即将他和一行人都迎到二楼的会客室里。

一进会客室，刘大霖差点没笑出来。看来澳洲人本事虽大，其实很是粗鄙。很大的一间屋子，刷得雪白的墙壁，地板也是上好的木料。秋日的阳光从玻璃窗里透进来，极是敞亮。里面的家具陈设却毫无章法。

墙壁上，犹如卖画的摊子一般，密密麻麻的挂上了各种字画。不管是中堂、条幅还是插屏，甚至有几张扇面。山水、花鸟、工笔、写意、泼墨、青绿……各式各样的随意的到处悬挂。其中居然还有几张苏州片子。

墙角，随意的摆着几只大花瓶，里面不伦不类的插着鸡毛掸子——这种大花瓶有半人多高，工业上用不着，大伙也不要这玩意装饰屋子，毁掉又可惜，干脆就到这里来发挥余热了。

显然，澳洲人的鉴赏能力很糟糕。说他们是暴发户都抬举了。刘大霖暗暗摇头，本县的土财主的品位都要比他们强。

----------

这第二套方案就是搞个临高版的“天上人间”。

“大伙都知道，广州站的紫明楼搞得有声有色，洗浴、桑拿、男根保养什么的都很给力。”[文总][y002]说，“我们完全可以办个临高版么，没必要我们的创意和专业知识给土著服务不给同志们服务。”他接着说，“而且大明应该原本就有这样的专业机构，扬州的瘦马就很有名，大同娘们听说也不错，干脆派人出差去买一批回来，细皮白肉的小娘们，我们再搞搞专业培训——可惜当年东莞的几个技师没一块绑过来……”

说到这里他又咳嗽了一声，又接着说：“没专业人员可以給她们看AV，AV资源很多，公私都有，个人如果愿意提供专业资源或者指导的，发给打折券或者代金券就是了！”

“这个临高紫明楼消耗的资源也不会少，扬州瘦马的价钱可不低呀。”程栋表示担忧。

[文总][y002]一挥手：“这个么，我们养特侦队干什么？干脆派一批人到扬州，要不近点广州也成，看到合适的妹子就绑回来。喜欢大洋马的，上澳门、马尼拉去绑，大不了绑回来我们自己调教，即练兵又有了妹子，一举两得。”

时袅仁表示反对：“这样的做法很危险！我们没有橡胶资源，做不了安全套，这么多人无套中出，首先就有性病爆发的危险——我们无法保证搞回来的妹子全是干干净净的；其次是伦理问题，她们一旦怀孕，根本就查不清孩子的父亲是谁……”

“集中起来抚养就是了，”[文德嗣][y002]说，“孩子也是我们的资源，我们灌输全新的知识和理念給他们，他们从血缘上完全忠实于穿越集团，又没有土著的母系家族要照顾，这可是非常好的人力资源。”

“老大，这些孩子长大之后要恋爱要结婚，这就好比人工授精生出来的孩子长大了有血亲婚姻的伦理风险一样。”时袅仁说。

“而且有人根本就不喜欢这样的性公共厕所。”[萧子山][y001]说，“有人要有技巧的性生活，有人要的是夫妻生活，这两者很难平衡。”

显然大家就这个问题并不能达成共识，最终[萧子山][y001]问[马千瞩][y005]有没有库存的安全套能够配給。

----------

[文德嗣][y002]虽然是委员会的头，但是很少来这里，偶尔才会来看看汇总好的提案，顺便发表几句不着边际的评论。[萧子山][y001]倒是经常来这里表示下“关怀”，还不时送来点香烟茶水之类的“慰问品”，但是对具体措施不发表看法。于是这个委员会的具体的实施权落在了马甲的手里。

安熙提议这件事情由他来负责主办就好。

“马院，这事情虽然事关民生，到底格调不高，你亲自办理是不是有点……有点……”安熙想不出形容词，“……对将来的发展说不定会有影响。”

“没关系，这样的任务既然给了我们法学俱乐部就应该竭尽全力的办好。”马甲说，“这是考验我们的时候，我还是亲自负责为好。”他心想连[文总][y002]都要来挂这个名，可见格调高不高没关系，“事关民生”才是最要紧的。

----------

“不是玩花样，”吴石芒摇头，“我们教会应该争取作民众的思想工作这一重要的任务。现在给土著的洗脑工作还不够，也没有专门的机构在做，是个空白点。”他这个结论当然是有依据的，如果以为吴院长这一年来只是搞基本建设，顺便YY修女妹子就大错特错了。他对教义学习不感兴趣，但是空暇的时候读了许多教会史方面的书籍和论文，有了不少心得，还经常和教徒们交流思想，做了很多思想动态笔记。

吴石芒认为，临高的土著的精神生活极其空虚，甚至连传统型社会最常见的宗教生活都谈不上有多少。限于经济能力的问题，本县的寺庙虽然有几所，却大多处于半死不活的状态，很少庙宇能有常驻的和尚道士，各种民间迷信很有市场，不脱产的巫婆神汉普遍存在。

“现在对土著的宣传做得还很不够，除了几个笼统的口号之外，对体制内的土著关注大，对体制外的土著重视度严重不足，没有系统的对其进行洗脑工作。现在还看不出问题，将来的问题可就大了！”吴石芒说得很严肃，一本正经。

“教会应该抓住这个时机，利用本地民众信仰方面的空缺，迷信泛滥的状况及时的推进到他们社会生活的方方面面——而不是搞点小慈善活动就完事了。”

白多禄大吃一惊，没想到吴石芒这个人事招聘培训主管还真是野心勃勃。看这意思，他是把教会定位到“国家教会”的层次上了。吴石芒这么一说，白多禄也觉得穿越集团在上层建筑领域太匮乏，过于专注于爬科技树发展生产力上了。

----------

“风俗习惯是会变得，前提是有强大的力量来冲击这个社会。”吴石芒胸有成竹，“现在穿越集团就是在冲击这个传统型社会，要改变社会生活习俗这是绝好的机会！”

从日常生活的风俗习惯入手，使民众渐渐习惯于教会的存在。所谓信仰，在民众中多数情况表现为迷信，按照马林诺夫斯基的“社会功能学派”的主要理论，迷信和宗教是社会释放自身压力稳定社会结构的一种方式，如果压力不消失，迷信不可能被消灭，新的迷信只会层出不穷，除非消灭社会本身。

未来的帝国当然不会是人间乐土，社会压力既然存在，给民众提供所谓“精神鸦片”，给予其对死后世界的保证将是一个有效的方式。
* 第四卷 新澳洲

----------

十几岁的少男少女大多只能担任机关工作，派到外界去只能担任一些简单的跑腿和打听工作。这对大规模开展活动很不利。

“还有，情报培训应该有重点，而且必须有一定的技能。”谌天雄补充道，“我看了下他们的训练资料，实际上和政保总局的培训内容差不多——很多非法活动技巧——完全没必要。我们需要什么样的情报人员？无非是能够准确的报告敌人的动向、数量、当地的社会民情、经济状况，这些内容90%都是公开情报，只要多花点力气收集整理就行，用不着大费周章的去学什么跟踪、绑架、纵火之类的事情——这不是收集情报，是情报作战了。”

“我对土著情报人员的要求是：他们只要掌握基本的搜集情报的技能就可以，要会计数，认识几个字，能撰写报告最好，不行的话能够准确阐述所见所闻也够了。然后教授一些简单的秘密工作技能，其他一概不用。而且也用不着他们如何赤胆忠心久经考验。采取适合的保密和组织制度就可以让他们即使被抓或者叛变也影响不了大局——低级别的情报人员完全可以按照消耗品来培训。”

“还有应该教授一些掩护和生存技能。”林佰光补充道，“会一二门手艺，或者会念经算命之类，这样情报人员就能够利用职业作为掩护进行流动。”

“当然，也可以有针对性的培养一些高级的人才。但是我反对直接培养高级情报人员——这种所谓的直接培养情报精英的制度是不可行的。应该从工作了若干时间的普通情报人员中选拔优秀分子来进行继续教育。”谌天雄继续阐述他的情报人员教育理论。

----------

须知的内容大意是：你参加的是一项危险的工作。首先你将在糟糕的道路条件下奔波饱尝旅途的艰辛；不管你走陆路还是水路，都可能会遇到土匪。除非你有王八之气，能说得土匪倒头便拜，否则就是横尸当街的下场。

乡勇、衙役和士兵比土匪好不到哪里去，某些地方的百姓，在打劫和杀死一个过路人的时候也不会迟疑，即使这个过路人只有几块干粮和一件破衣服。

卫生上，城市不见得比农村更好，甚至可能更糟糕。一般来说疫病总是在人口密集的地方流行。当地人能够适应的水和食物，现代人的肠胃很可能会受不了。食物和水除了有细菌的感染，还有寄生虫的风险。

恶劣的卫生状况很可能使你患病，即使没有卫生问题你也可能得病，如果在执行任务的时候受伤，除了携带的少量药品和当地的中医，你没有任何的卫生服务。一次狗咬伤，被一柄生锈的小刀刺伤就可能让你送命——就算紧急送回临高，路途迢迢，很可能在路上就会死去。

你可能要面对跳蚤、臭虫和蜱子之类的寄生虫的袭扰——这种东西在本时空大量存在，不一定在穷人中才有——这些寄生虫不仅会让你浑身难受起疙瘩，还会带来各种稀奇古怪的疾病，有得病在现代时空都未必能够有效的治疗。

最后，一旦在大陆被捕，对外情报局并不能在第一时间展开救援：如果运气不好，附近没有电台或者无人及时通知，总部可能要过了规定的联络期才知道你被抓了。等到派出人来营救的时候时间也许已经过去了几个月。被捕不一定是因为你的工作出了纰漏，或者身份暴露。西班牙人会因为你是个中国人就把你抓起了，后金则可能因为你是个汉人；至于大明，也许仅仅因为你在做生意，有几个钱，就被某个希望搞点外快生发的东厂番子或者县官衙役之类的人物看上了；即使扮成穷人也不见得安全，你可能会仅仅是因为当地发生了命案官府需要找个外来的没根基的人当替罪羊就被抓去严刑拷打。

大明、后金或者欧洲殖民者的各级政府、专政机关甚至私人团体都会严刑拷打你，有的是为了口供，有的只是为了从你身上榨出钱财来，本时空的监狱不但没有基本人权，连生存权都未必有，你可能会被牢头禁子用各种方法弄死。而且这是一个好男风的时代，所以白白净净的现代人很可能会惨遭某个猥亵大叔的毒手……

----------

这下让兰度等人慌了手脚，东沙岛是台湾军队的地盘，上面有海军陆战队，自己的船要是被临检，哪国的王法都不许私运武器的，这怎么混得过去？而且台湾对自己的祖国比自己对自己的祖国还要忠诚，被逮住了那是肯定要给移送回去了。几条联邦重罪外加多少多少年不得假释，自己的下半辈子就得穿橘红连衣裤过日子了。

----------

这两个人，是他幕中两名心腹。吕易忠当过几任知府，李息觉是天启年间的进士，未曾授官，一直在家闲居。两人都是四十出头五十不到的年龄，正是精力健旺的壮年，两人即饱读诗书，又对各种实际政务了解颇深。

但是这两位赞画一时间也说不出什么高明的主意——谋略是建立在情报的基础上的，没有情报，连敌人是谁都闹不清，哪里有谋略可言。

----------

裴莉秀经过再三考虑，决定还是从这方面着手，搞个美容沙龙之类。大搞纯天然美容保养。穿越集团在这方面有大量的资料可用。特别是有人的电脑里还存了美容院的全套视屏教程。除了全套美容保养的课程，还有什么耳烛、子宫保养、全身按摩、药浴、香薰浴、胸部按摩等等，连美容灌肠都有。

----------

这个吕易忠因为是总督的赞画，自己对他是曲意奉承，不但三节两敬从优，平日里他到紫明楼来宴客会友也常常是不费分文。而这个吕易忠平日里对郭逸和她也是非常的客气，有什么棘手的事情，郭逸甚至自己的一个手条过去，立刻就办下来了。应该说双方在履行中国式传统的官商勾结方面堪称古今典范。

----------

想到这里，他暂时打消了让汤允文派遣人马救援澄迈的打算。然而澄迈万一失陷，汤允文身为琼崖陆路等处兼管白沙水寨海防参将，他的责任最大。但是自己既是广东的军事主官，又是征伐髡贼的主将，失陷县城的责任是跑不掉的。

“依学生看来，不如镇台即刻下一手令给汤参将，要他相机行事，速速救援澄迈。”

众幕僚纷纷点头：既然是“速速”，又可以“相机”，这里果然巧妙！何总兵反正是下了救援的命令了，救与不救的皮球就直接踢到汤参将脚下了。纵然澄迈失陷，也追究不到何如宾头上——他的标营人马已经渡海了，总不能说他见死不救。这是其一；其二，就算澄迈暂时失陷，等大军汇齐，收复澄迈不过是进军途中的举手之劳。

----------

“不管你是什么吧。当领导的话权力寻租这个词没听过？”[文德嗣][y002]笑着说，“真金白银不能给你，但是官府手里的权力漏一点给你，不就能补偿我们的损失了？”

众人露出了明白了的表情。

“我们不能明明白白地说：香港岛割让给我！还要对方白纸黑字的写下来。这事，全大明也没一个当官的敢这样答应。连崇祯皇帝都不敢——他不怕文官集团把他喷死还怕在史籍上落个‘割地’的名声。”[文德嗣][y002]说，“但是我们可以悄悄的把岛占了，在上面爱干什么就干什么——只要别搞得地方官府对上面交代不了就行，反正这种事情历来是瞒上不瞒下的。”

----------

村干部不采用选举制，元老们认为在现阶段采用选举制是毫无意义的，农民对选举这一新鲜事物了解很少，不懂手中的权力，也不理解公职的意义。很容易造成村级权力被窃取。

“……农民一般都不大愿意出头，这是乡村民主的一个特点，”做过很多社会调查、田野调查的方敬涵在讨论会上发表自己的看法，“这不仅是害怕担负责任或者担心利益受损，还有一种害怕被嘲笑的情绪在内。”

从历史上的经验来看，不加任何指导的完全采用村民选举，反而会让许多爱出头的所谓的“能人”占据村干部的位置，他们或者能说会道，或者是村里的泼皮无赖，靠着恐吓或者诱骗的办法迫使村民选举他们担任公职。这在旧时空是屡见不鲜的基层弊病。

根据杜雯在十三村地区的经验，由工作队接管村政，初步建设起村里的基本组织，然后从积极分子中逐步甄别培养出干部是最为合适的办法。不但可以确切的考察每个人的状况，而且在建立基层组织和行政上也提供了一个示范，避免了水平不高的村干部的想当然的执行。

----------

敌人以战士的身份战死或者被虐杀。无论对于敌人还是自己人都是一种榜样。虐杀一个有代表意义的敌人，对于任何统治者来说都不难，却是必须绝对避免发生。虐杀是会激起敌对方的同仇敌忾滴，得不偿失。

“最佳的办法就是‘搞臭’！”周洞天指出，没有什么比搞臭对手的名声更理想的了。

“大家明明知道，失败者是没有权力的，只有任人处置。为什么每次打完仗战胜方都要搞个法庭来审问战犯？”周洞天在会议上说，“就是为了搞臭对手，使得对手无法成为失败者一方的英雄——就算不能全部奏效，至少可疑部分奏效。我们的思路也是一样的。”

“老周的意思我明白了。”丁丁赶紧跳了出来，免得风头全被周洞天弄走了，“我们也要组织战犯法庭！并且将法庭的审讯实录到处散发……”

----------

在这种情况下还要葡萄牙人出兵，对方会怎么考虑他实在没有把握。

“此事甚是棘手。”李洛由决定实话实说，“高巡按的奏折，如今已经是满城风雨，佛郎机人多半也知道了，到时候问起来如何应付？”

“只说绝无此事便是。”

这简直是形同儿戏！李洛由心想，高巡按上奏折的事情不会是空穴来风，毫无解释就一口否决，万一以后葡萄牙人得到了确切的消息，不是视大明官员是毫无诚信之人？

“这个……万一以后真有其事了，岂不是大大的失了官府的颜面……”

何诚宗淡然一笑：“官府何曾说过这话？”面色的神情很是自得。

李洛由难以置信地看了他一眼——他完全明白何诚宗的意思，这话不是广东官府的任何人说的而是他这个代表说得。而李洛由并不是“官”，所以也不存在官府撒谎的问题。再说到那时候官府完全可以一口否认李洛由和官府有任何的关系。

这伙人想得真是太荒唐了！竟然把撒谎当作一种谋略！而从何诚宗洋洋得意，毫不隐晦地说出这句话看来，显然认为让李洛由这样一个商人撒几句谎没什么大不了的，顿时感到异常的心寒。

“这班读书人，一个个书都读到了狗肚子里去了。什么卑鄙无耻的主意都打得出来。”李洛由心中大怒。但是面上波澜不惊，只是微微一笑道：“这个，不大妥当吧？”

----------

总得来说，执委会并不很看重这份条约，因为这份条约总得来说不过是元老院和李逢节达成的一个私人协定而已，对大明官府的约束力仅限于李逢节抚粤期间。李逢节一旦去职，整个协定也就等于是失效了。

不过，中国官场的传统特点是陋规传承极其严重，只要这个协定顺利的运作几年，形成了一定环绕在其周围的利益群体，新换的粤抚也只能无可奈何。再者，按照现在的发展势头，大明在广东的统治还能维持多久，能换几任粤抚还是个未知数。

----------

许廷发对陈应元很恭敬，简直是言听计从。陈应元要他怎么做就怎么做。征询他的意见也一律以“唯大人马首是瞻”、“大人英明”、“末将读书不多，韬略更是浅薄”之类的话语来应付。

本来他一个小小的海防参将，在地位上与广东左布政也是没法相提并论的，力持己见不过是自讨没趣罢了，不过对陈大人的种种布置，他心中是极其不以为然的。
* 第五卷 进入

----------
林铭袭官的年头不算太长，但是官场的一套却很明了。事件的真相有时候并不是最重要的，如何尽可能减少“麻烦”才是最要紧的。高舜钦的失踪案看似官场上下都很紧张，但是他们紧张的不是高巡按的安危，而是此事最终会给仕途带来什么样的负面影响。广东官场现在已经禁不起新一轮的大风浪了——王督之死算是给琼州的惨败背了黑锅。再要闹出一个高舜钦案，广东官场可就再也没法糊弄了。

林铭到广州参见李逢节之后，何诚宗专门来见他，说了些场面上的客套话，临走又留下一张二百两的票子。林铭虽然是个锦衣卫世袭试百户，祖传的作威作福的套路，但他不是个二世祖，自己全家既然祖祖辈辈在广东地面上过日子，还是要卖官老爷的一个面子，尽量帮着官场掩饰对自己只有好处。巡抚的意思不用多说他也明白——一定要把责任给择出去。

最好得结果当然是直接把高舜钦找回来，各方面皆大欢喜。如果找不到，该如何上报就是费脑子的事情了。

林铭知道自从何镇兵败之后，幸而王尊德是及时死了，这才让一干幕僚师爷们有了充分发挥的余地——总而言之，王尊德成了罪魁祸首，李逢节在后方调度支应，何镇在前方奋勇拼杀，将士用命……最后官兵先败后胜，力战旬月，挫败髡贼攻府夺县的企图……髡贼穷极跳墙，窜犯广州，又为海防参将许廷发所败，琼州全府安堵，未有一府一县之失……
