#+title: 爱，金钱和孩子（Love, Money, and Parenting）

https://book.douban.com/subject/33462451/

笔记本导出
爱、金钱和孩子：育儿经济学
马赛厄斯·德普克; 法布里奇奥·齐利博蒂

** 序

是什么导致了不少当代的父母在度过了 20世纪七八十年代宽松的童年时代后，却突然成为“直升机父母”和“虎妈”呢？答案是经济激励发生了改变，这很大程度上是同时期经济不平等的加剧导致的。接下来，我们考察了世界上不同国家的抚育行为并试图解释其中的差异。答案依然与经济激励有关，经济激励在不同国家有所不同。最后，我们观察到在发达经济体，处于不同社会阶层的父母的教养方式有所差异。什么可以解释这种差异呢？即面对不同约束的父母的经济激励存在差异，而这些约束取决于他们的收入和教育水平。

** 引言

瑞典是鼓励宽容和放任的教养方式的典型。慈爱的瑞典父母们认为，要求一个学龄前儿童安静地坐在餐桌前是有违基本人权的。他们中的大多数人不赞同任何形式的纪律，包括言语恐吓，更不必说体罚，体罚自从 1979年就被认为是非法的了。被大多数国家的父母认为不恰当的儿童行为，比如打扰陌生人，在瑞典被认为是孩子的天性而得到原谅。

瑞典的学校也遵循了同样的自由主义哲学。大多数瑞典的学龄前儿童能够上免费的托儿所。这些都是平静欢乐的地方，由能干又积极主动的专业人士在禁止任何正式教学的指导原则下进行管理。在托儿所，孩子们几乎没有什么不可以做的事情。调皮捣蛋的孩子当然会被教导，但很少受到惩罚。在瑞典，正式的教育要到 7岁才开始，小学生在年满 13周岁之前不会收到任何成绩单。社会的共识是，让孩子承受压力和焦虑是罪大恶极的。一些教师甚至在公开场合劝阻雄心勃勃的小学生们不要“过于用功”，并且谴责“不负责任的”、咄咄逼人的父母给孩子们带来过多压力。瑞典孩子的竞争精神仅仅局限于体育活动，在这个领域瑞典人认为竞争是可以接受的。竞争心太强的父母们不被社会认可。当诺拉的父母去学校询问是否可以提前入学时（在 6岁而非 7岁），得到的回答是，“当然啦，她可以应付的，但我绝不会这样对待自己的孩子”。

按照国际标准来看，瑞士同样拥有着自由的育儿文化。但其育儿和教育实践绝对比瑞典的要严格得多。在低年级时，学生得开始适应老师的权威。任何年龄段的孩子在进入教室的时候都应当和老师握手，并礼貌而正式地尊称他们“您”（ Sie），他们从不直呼老师的名字，在老师讲话时一言不发地聆听。[ 3]孩子们从二年级开始接受评分并收到成绩单，但瑞典的同龄人此时才刚刚入学。在六年级，瑞士的孩子会面临一场入学考试， 20%的人被选入更偏向学术的高中系统（ Gymnasium）（在瑞士没有初中，孩子们直接从小学进入高中）。这场考试被俗称为高中入学考试（ Gymipr ü fung），它对于 12岁的儿童而言是一场严酷的考验。许多父母致力于为孩子提供额外的私教补习，大大削减孩子们的空闲时间，一些父母甚至请假辅导他们的孩子复习。这并不仅仅是某种偏执行为。学术型高中是获得大学教育的途径。尽管孩子们有机会在稍晚的年龄进入大学教育轨道，但学术型高中提供了更高级的课程以及筛选过的同龄人，因此，考试成绩无疑是非常重要的。

在我们的研究过程中，我们发现在低不平等和低教育回报率的国家，父母往往更宽容，在高不平等和高教育回报率的国家，父母可能会更专断，并更倾向于向孩子灌输出人头地的理念。不平等能够很好地解释我们之前讨论的各个国家的现象：不平等程度在宽容的瑞典很低，在以入学成绩为导向的瑞士较高，而在被忧心忡忡的“直升机父母”占据的美国则更高。

虽然我们的中产阶级父母并不声称他们是反权威的，他们仍然吸收了这一文化运动的许多价值观。在很多情况下，采取一种新的宽容的价值观并不是孤立行为，而是反映了整个社会价值观的变化。从小学开始，老师们会强调自由、独立和从传统价值观中解放的重要性。在法布里齐奥童年时期的意大利，任何形式的对权威原则的尊崇都会被迅速地（通常是过于迅速地）和“法西斯”这个词联系在一起。父母被敦促不要掺和孩子的家庭作业。

如果我们现在思考，自己受到的教育和我们子女的不同之处，最显著的差异是我们对孩子日常生活的参与和干预比我们的父辈想象的更多。这令我们十分惊讶。在有孩子之前，我们以为自己会成为宽松型的父母，因为这就是我们成长的方式。但与我们父母在 20世纪 70年代所经历的一样，我们的教养方式事实上很大程度取决于我们现在生活的经济社会环境，而并非我们小时候接触的育儿文化。事实上，我们开始研究育儿经济学的一个原因在于希望理解为何我们做父母时的行为和预期的如此迥异。

** 第一篇 在不平等的年代抚育子女

加州大学伯克利分校的黛安娜·鲍姆林德（ Diana Baumrind）对发展心理学中的教养方式理论作出了开创性贡献。鲍姆林德识别了三种主要的教养方式：专断型（ authoritarian）、放任型（ permissive）和权威型（ authoritative）。[ 4]

权威型父母试图以理性、问题导向的态度引导孩子的行为。他们鼓励交流上的互相让步，和孩子分享他们的方针背后的道理，当孩子拒绝遵循时征求他的反对意见。自主意愿和遵守纪律被认为同样重要。因此，父母在孩子和自己发生分歧时对孩子施加坚定的控制，但不完全限制孩子。父母强调自己作为成年人的观点，但也认可孩子的个人兴趣和独特的行为方式。权威型父母既肯定孩子目前的行为，但也为未来的行为设定了标准。父母使用理性与权力，通过规律的塑造和思想的巩固来达到目标，并且不基于群体共识或孩子的个人愿望作出决定。[ 12]

父母的利他主义的关键特征在于对孩子的完全共情。换言之，具有利他心的父母接受孩子自己认为的什么对他们有益的观点，他们通过孩子的视角看待孩子，而非给孩子强加他们的观点。在我们的定义下，利他主义的父母认可孩子的偏好，那么完全由利他动机驱动的父母总是会让孩子来规划，也因而采取一种放任型的教养方式。[ 23]

正如利他主义父母，父爱主义父母也关心孩子，但他们相信有时孩子的自主权应该受到限制，这是为孩子好。这是因为父爱主义的父母对什么对孩子有益有一套自己的看法，并且这些看法可能和孩子的看法相左。因此，父爱主义父母可能会反对他们孩子想要做的事情，并且试图影响孩子的行为。父爱主义的父母不仅仅关心孩子的福利，还从成年人的视角权衡孩子行为的利弊。[ 25]

或许，最常见的亲子分歧在于享受当下的乐趣和当前行为的长期后果之间的权衡。父母总是比孩子自己更关心孩子的未来。因此，父爱主义的父母时刻准备着做出可能减少孩子当前的幸福感、但他们判断符合孩子长期利益的代价高昂的行为。[ 27]父爱主义动机能够解释为什么许多父母采取了权威型或专断型教养方式，这两种教养方式不像完全利他主义的父母会选择的放任型教养方式，它们都旨在影响孩子的选择。[ 28]

基因因素的确对于基本的人格特征有很大影响，比如外向性格和内向性格。相反，教养则是培养技能的核心。权威型父母试图影响的大多数儿童特征都是所谓的非认知技能，比如耐心、风险厌恶和对于努力可以获得回报的信念。[ 35]例如耐心，可能部分取决于冲动等个人特征，但也部分由后天习得。当父母试图帮助他们的孩子变得更有耐心时，他们会教孩子仔细思考自己行为的后果，并设想这些行为在数年或数十年后对自身的长期影响。做出这些考虑的能力不是孩子天生具备的，而是一种需要后天教导的技能。

蔡美儿是专断型和权威型教养方式的典范吗？她的信条涉及了两者的要素。一方面，蔡美儿认为，建立孩子的自信心需要迫使他们做他们不喜欢的事情，这是专断型教养方式的要素。她说：“中国父母知道，在你擅长某件事之前，没有什么是有趣的。要善于完成你必须完成的任何事情。而且孩子自己永远不想工作，这就是为什么凌驾于他们自身的偏好至关重要。这通常要求父母表现得很强硬，因为孩子会抵抗；万事开头难，西方父母往往刚开始就放弃了。”[ 6]另一方面，蔡美儿也像权威型父母一样，相信孩子必须在追求成功的过程中自我激励。

在 1976年，美国的父母平均每周花 2个小时（母亲 76分钟、父亲 43分钟）陪孩子游戏、阅读与交谈，平均每周花 17分钟（母亲 10分钟、父亲 7分钟）指导孩子的家庭作业。在 2012年，美国的父母平均每周花 6. 5个小时（母亲 204分钟、父亲 184分钟）陪孩子游戏、阅读与交谈，平均每周花一个半小时多（母亲 65分钟、父亲 31分钟）指导孩子的家庭作业。总体来看，美国父母在这些活动上花的时间是原来的 3. 5倍，从每周小于 2. 5小时增加到每周 8小时以上。

为什么不平等上升了呢？人们通常把它归咎于同一时期的政治动荡，这导致了再分配经济政策的减少。然而，大多数经济学家认为政治变革不是首要原因。对于不平等加剧趋势的最广为接受的解释是技术变革。[ 27]信息技术革命极大地改变了劳动力市场条件，减少了对受教育程度较低的劳动者的需求，并增加了对受教育程度较高的劳动者的需求。同一时期的政治和制度变革降低了政府通过收入再分配和社会政策来减轻技术变革影响的能力，从而起到了加剧不平等的作用。

PISA还包含父母与子女进行的具体活动的信息。特别是 2009年调查问卷中询问了父母与孩子一起阅读书籍、讲述故事或讨论政治或电影等各种话题的频率。使用与之前相同的统计技术，我们可以计算控制父母受教育水平的情况下，这些亲子活动和考试成绩之间的相关性。由于许多父母参与多项活动（例如，阅读书籍和讲故事），我们在控制其他活动的效果的前提下估计每项活动的效果。与孩子一起阅读书籍的父母，其孩子在数学、阅读和科学测试中的分数增加 16—18分，而讲故事的平均影响在 2—7分之间。有趣的是，与孩子讨论政治的父母，其孩子的测试分数增加 9—12分，这是很大的进步。

所有这些证据都与我们的整体论断相一致：通过父母与子女互动的时间来衡量育儿强度发生了变化。这种转变发生在一个以不平等加剧、教育回报率提高以及抚养子女的重要性上升为特征的时期。结果，父母越来越担心孩子的学业表现，并通过更加密集的教养方式以及选择有利于孩子取得学业成就的教养方式来应对。因此，“直升机父母”的兴起可以理解为父母对变化的经济环境的理性反应。

在高不平等国家，许多父母会强调勤奋是孩子需要学习的重要价值观，而在低不平等国家，父母则更重视独立性和想象力。我们可以用称为“相关系数”的统计指标来度量不平等程度和价值观之间相关性的强度。这一系数可以在-100%至 + 100%之间取值。相关系数为 0意味着两个变量不相关。 + 100%是两个变量之间可能的最大正相关性（如果一个变量上升，另一个上升），-100%是两个变量之间可能的最大负相关性（如果一个变量上升，另一个下降）。[ 5]我们发现在不平等和选择“勤奋”这一价值观之间存在极强的正相关性（ + 89%）而选择“独立性”“想象力”和不平等之间存在强负相关性（分别为-48%和-68%）。

我们首先来看对于勤奋的选择情况。 65%的美国人认为勤奋是一种重要的美德，而在北欧国家这一比例可以低至 11%—17%。同样，低于 30%的德国父母们赞赏勤奋的价值观。这与我们认为德国人努力勤勉的刻板印象（马赛厄斯认为被夸张了）不符，但是和德国很低的不平等水平是相一致的。在中等不平等程度的国家，比如意大利和澳大利亚，父母对于培养勤奋的孩子的热情不如美国父母，但比德国和北欧国家要多。有少数几个国家不完全和一般规律相符。比如，法国和西班牙的孩子普遍被灌输勤奋的观念，尽管这两个国家的不平等程度都是中等。我们将在之后回到这些例外情况。然而，主要的规律是强烈的正向关联：一个国家越不平等，父母越认为孩子应该学习勤奋的美德。

我们是否可以断言，经济不平等和教育的高度重要性能够完全解释中国式的教养方式呢？虽然我们认为这些因素非常重要，但我们认为中国式育儿在某种程度上植根于古老的文化传统，而非当前的经济条件。比如，传统对权威和等级的尊重可以解释中国式育儿向专断型教养方式的偏向，这种偏向将中国式的密集型父母与类似经济社会状况的西方国家的父母区分开来。用蔡美儿的话来说：“中国父母相信他们知道什么对孩子最有利，因此会忽视孩子的欲望和偏好。”[ 18]

在教育回报率较高的国家，父母更倾向于权威型和专断型，而在教育回报率较低的国家，父母更多为放任型。[ 35]有趣的是，教育回报率可以帮助我们解释为什么在法国和西班牙这么少的父母是放任型的。如前所述，这一现象令人费解，因为这两个国家都不存在非常高的不平等。在这里，我们看到法国和西班牙的教育回报率是欧洲最高的。教育回报率可能是法国和西班牙父母比其他欧洲国家的父母更为咄咄逼人的原因之一，其他欧洲国家的教育回报率相对较低，例如北欧国家，或与法国和西班牙在文化方面有许多相似之处的意大利。

我们还考虑了一些额外的变量，这些变量对于使用密集型教养方式的动机至关重要。教育回报率会影响我们理论预测的对教养方式的选择：更高的教育回报使父母不那么放任。同样，保持其他一切（包括税前不平等）相同，在税收更加累进，安全网络更加完备的国家，父母更宽松（即放任）。除经济因素外，制度的质量也很重要。在那些对公民自由有强有力的保护、腐败程度低以及有独立和有效的司法系统的国家，父母知道他们的孩子得到了更好的保护，因此他们能够做到更宽松和放任。

我们再次强调，我们不持有任何价值判断。勤奋可能对经济增长有价值。然而，教育的高度重要性和密集型教养方式可能通过限制自发性、创造性，以及整体上降低了孩子的福利而对社会产生不良影响。有趣的是，瑞士和瑞典这两个拥有强有力的制度和民权保护、盛行放任型教养方式的国家，在 2016年全球创新指数（ Global Innovation Index）中名列前茅。[ 38]

我们的论点补充了罗伯特·帕特南在他《我们的孩子：危机中的美国梦》（ Our Kids： The American Dream in Crisis）一书中的分析。[ 4]像我们一样，帕特南也在写作中借鉴了个人经历。以 1959年他在俄亥俄州克林顿港的高中班级为例，帕特南认为当时社会分层是不明显的。来自不同社会背景的孩子尽管并不拥有完全相同的机会，但差异并不大。大多数家庭的收入相对稳定，学校也类似，孩子们生活在各阶层混居的社区。大多数他的高中同学成年后的生活比他们的父母要好得多。相比之下，现在这一代的孩子面临着截然不同的状况。特权家庭努力让他们的孩子在社会中站稳脚跟，并将他们隔离在学校普遍优秀的中上阶层社区中，贫穷的孩子却因为机会的减少而受损。

育儿的时间差异并不是因为受教育程度更高的女性更有可能成为家庭主妇。事实上，情况正好相反：平均而言，受教育程度更高的女性工作时间更长，同时会花更多时间照顾孩子。受过更多教育的母亲付出的育儿时间更多并不是从正式劳动力市场中工作时间的差异看出来的，而是可以用闲暇时间的差异来解释。接受过大学及以上教育的女性比最多只接受过高中教育的女性每周的闲暇时间少约 4小时，这与育儿时间的差异相符。这一结果表明，受教育程度导致的育儿时间差距不仅仅受时间限制的影响，尽管这一限制对于一些小群体，比如低收入单身母亲显然很重要。

如果向上流动性被定义为孩子移动到教育金字塔顶端的可能性，即获得研究生以上学历（如法律、医学博士及其他博士学位），那么教养方式对向上流动的影响要大得多。在父母双方最多只接受过高中教育的家庭中，从不参与型改变为专断型教养方式可以让孩子获得研究生学位的可能性提高近 3倍。在父母一方接受了高中以上教育的家庭中，从不参与型到权威型的转变将这一可能性提高近 5倍。即使使用了权威型教养方式，这样的家庭获得更高学位的孩子的概率也只有 10%左右。尽管如此，这一结果告诉我们，密集型育儿几乎是受教育程度较低的父母让孩子接受最高层次教育的必要条件。
书签 - 第4章 不平等、教养方式和育儿陷阱 > 位置 1784

有趣的是，专断型育儿对于父亲和母亲具有相反的效果：拥有一位专断型母亲会对教育产生积极影响（与不参与型的母亲相比），但拥有一位专断型父亲却会降低教育程度。[ 9]这一结果表明母亲和父亲专断的形式不同，母亲更可能严格要求与学业成就相关的事情（如让孩子做家庭作业），而父亲更关注其他方面的行为（如服从父母）。

单亲育儿不仅仅因为单亲父母的资源较少，还会因为父母之间关系的好坏影响到孩子。有证据表明离婚或父母分居的孩子往往比与双亲在一起的孩子的在校表现要更糟糕。[ 17]经济学家托马斯·皮凯蒂认为，父母分居本身不一定是问题的主要原因。[ 18]首先，决定分开的父母通常情况下彼此相处并不愉快。皮凯蒂证明，只与父母中一方生活在一起的孩子的学业成绩在分居前两年就受到了影响。此外，他发现法国 1975年法律改革令离婚变得更为容易，离婚率也随之大幅增加，主要是因为离婚人数增加了，故家庭冲突的强度没有受到显著影响。这些观察结果表明，生活在父母经常争执的不稳定家庭是子女学习成绩差的一个重要原因。平均而言，受过高等教育的人或许能更好地建立和谐的伴侣关系并处理家庭冲突。这可能会影响到他们选择的教养方式，并最终影响到孩子的学业成就。

补贴。提供更多的儿童保育服务为贫穷的家长（特别是单身母亲）提供了进入劳动力市场的激励，同时为不同社会经济背景的孩子提供共度童年的机会。在隔离日益严重的社会中，让孩子接触多元化的环境或许是遏制育儿差距的有力方法。虽然用高税率来支持免费的幼儿园的想法对一些读者来说难以接受，但这正是北欧和其他欧洲国家多年来采用的方法。虽然这些政策费用昂贵，但让不同社会经济背景的孩子互动却更有价值：法布里齐奥和玛丽亚发现，诺拉在瑞典公立幼儿园的经历要比在英国的任何精英预科学校更具持续性的影响。

意思。它们的主要作用渠道不是去改进可以通过智商测试等来度量的学术（或认知）技能。获得儿童早期干预计划帮助的孩子确实在智商测试的分数上有所提高，但提高的效果不大并且随着时间的推移逐渐消失。相反，儿童早期干预计划起作用的主要机制是通过改进非认知技能。这些技能包括使人们在学校和工作场所中成功进行社交互动的态度和行为，例如积极性、耐心、毅力、自我控制以及评判当前行动对未来影响的能力。一些研究表明，这些技能而非智商测试所度量的认知技能对于人的成功更为重要。[ 49]

** 第二篇 育儿简史

由于卢梭将自己的孩子遗弃在孤儿院，许多人认为他是一个育儿的伪权威。然而，卢梭的观点影响了几代教育改革者，包括裴斯泰洛齐（ Pestalozzi），弗罗贝尔（ Froebel），蒙特梭利（ Montessori）和杜威（ Dewey）。例如，玛丽亚·蒙特梭利（ Maria Montessori， 1870—1952）认为，儿童从小就有自发的学习和发展的倾向。[ 22]她的教学理论强调了引导独立性的价值：“独立的征程在生命之初就开始了。随着发展，孩子会自我完善并克服在路上遇到的每一个障碍。”[ 23]教师的主要任务是通过创造一个为独立学习提供机会的环境来引导这一过程。与卢梭不同，蒙特梭利认为，教师应该在孩子犯错时作出反应并纠正孩子，但他们的干预应该是建设性的、友好的而不是惩罚性的。

前工业化社会的一个共同特点是，父母和孩子在工作、教育和相互支持方面的联系比现在要更紧密。所有家庭成员都将作为为家庭提供服务的高效运转的部件，根据性别和年龄被分配了不同的任务。同样，知识和技能的传播主要局限于家庭内部：孩子需要学习的大多数知识来自父母和兄弟姐妹。家庭也意味着很强的隐性义务，例如照顾老人。抛弃家庭以追求个人成功的孩子将受到家庭和社会的谴责。这一讨论指出，在前工业化社会，独立的好处很少。当一个孩子必须在一个父母无法引导他们的世界中取得成功时，独立意识尤其重要。如果孩子一生大部分时间要与父母一起生活，并且在职业选择方面跟随父母的步伐，强烈的独立意识不再那么有价值，甚至可以说是危险的。在这种情况下，父母可以教会孩子们所有他们需要知道的事，并密切监视他们，防止他们逃避父母认为他们应该承担的职责。通过鼓励他们遵守社会规范并密切监督他们的行为，父母还可以减少孩子的危险行为，如婚前性行为或打架斗殴。

专断型教养方式的缺点在于限制孩子的选择，阻碍他们探索世界的能力并扼杀他们的内在才能和天性。正如卢梭所言，通过做出独立决策并从他们自身行动中的正面或负面结果中获得经验，孩子会变得成熟，变得更加坚定自信，并最终能够更容易地寻找到自己的人生道路。然而发现一个人的人生道路在较低社会和职业流动性的传统社会中不那么重要。比如，在一个阶层明晰的社会中，农民的孩子将成为农民，贵族的孩子将成为富裕的食利者，几乎没有留给孩子独立探索的空间。生活有它“自然的”进程，每个人必须学会安分守己、各司其职。

对孩子灌输独立意识在充满变化的社会中更具吸引力，因为在这些社会中，年轻人被要求独立做出重要决定。工业化社会中劳动分工的不断细化增加了职业的数量，使子女更有可能找到比从父母那里继承的更适合自己才能的职业。新的机会常常出现在新的部门。例如，现在的软件行业从业人员中几乎没有谁的父母也在同一领域工作。即使在同一行业内，快速的技术变革也会使传统知识过时，这会降低子女从父母那里学习的有效性，即使他们职业相同。[ 31]在农业方面，传统习俗和技术在农业机械化后失去了价值。作为会计的父母可能缺乏今天从事同一职业的年轻人所需的计算机技能。法布里齐奥的父亲是一名在意大利国家电视台工作的熟练技术工人。他的专业知识被卫星和数字化淘汰了。他的母亲是一名时装设计师，但不熟悉电脑，而这是现在的设计师必备的工具。总而言之，技术进步改变了育儿的游戏规则，使得专断型教养方式本身已经过时。

对于如今工业化国家的大多数父母来说，如果他们区别对待男孩和女孩，往往是对孩子不同行为和需求的回应。父母对子女的期望是相似的：无论男孩还是女孩，大多数父母希望他们的孩子能接受良好的教育，不需要依靠另一半将来也能过上好日子。然而，仅仅在几十年前，情况却很不一样。当时性别角色之间有更大的差异，父母为男孩和女孩规划完全不同的人生。在很多发展中国家，性别差异的情况至今仍非常普遍，不论是针对孩子还是成年人。

家和工作地分离的新情况影响了人们对女性和男性在社会中所应当扮演角色的预期。在那些丈夫出去工作可承担一家人开支的情况下，已婚女性不再参与正式的劳动力市场。新的性别角色马上改变了男孩和女孩的教养方式。古托姆松写道：“当男性面对越来越多商业和专业领域的机会时，女性只能把她们的活动限制在母亲身份和家庭事务上。女性需要奉献自己以服务于丈夫和孩子的需要，通过对他人的支持来表现女性气质，无论是作为妻子、母亲、女儿还是姐妹……同时，女孩的教育也致力于让她们成为好妻子和好母亲。”[ 9]

在 1900年，对一个母亲来说，全职工作是很困难的，除非她能负担得起雇佣仆人的费用。准备食物、洗衣服、打扫房间和照顾孩子需要大量的时间，以至于家务外的日常工作对于很多母亲来说是不可能完成的。家庭中的技术进步大大降低了家务劳动的时间需求，因此让更多女性能在正式的就业市场上追求自己的事业。节省人力的家电，比如冰箱、洗碗机、洗衣机和吸尘器的普及，在这样的转变中起到关键作用。以前的家庭生产活动现在有了市场化的多样选择，比如外卖和托儿中心，这些发展也是转变的相关因素。这些创新联合起来，给予女性更多分配时间的选择。

由于近几十年女性劳动力参与率大幅提高，我们可以预想在同一时期，对女孩的教养决策会逐渐从培养她们成为家庭主妇转变到让她们具备成为成功职业女性的能力。教育方式就是教养决策转变的一个例子。从就业市场参与度可以看出， 20世纪 40年代以前，女孩的父母几乎不会相信他们的女儿需要可以在劳动力市场取得高回报的教育，但是 60年代以后，那样的教育对男孩和女孩来说同等重要。因此，父母有越来越强的动力给他们的女儿提供良好的教育。虽然之前男孩比女孩接受了更多的教育，但是数据显示在女性的劳动力参与率和相对工资提高的同时，她们的相对教育水平开始追赶（并最终反超）男性的教育水平。

经济学家米歇尔·特里特（ Mich è le Tertilt）证明在一夫多妻制普及的国家，这种效应会导致高人口增长率和低储蓄率，从而使很多这类国家发展水平不高。[ 28]例如，在乍得、冈比亚、几内亚和塞拉利昂，超过 20%的已婚男性至少有两个妻子。这些国家都是世界上最穷的国家， 2016年冈比亚的人均收入水平为 473美元，而乍得为 664美元。[ 29]

今天，我们知道世界上大多数地区最终逃离了马尔萨斯陷阱。不管怎么说，马尔萨斯的理论提供了对前工业化时期收入与人口关系的准确描述。即使在早期，不同地区也存在生产力水平和技术进步的巨大差异。在我们的时代，生活在技术进步国家的人们享有更高的生活水平。与之相反，在马尔萨斯机制下，生产力的提高（比如，轮作方式的引进使亩产农作物增加）首先会造成更高的人口增长率。在马尔萨斯的时代，农业是主要的生产活动，由于具有生产力的土地上人口越来越多，而劳动的回报率递减，人口增长率就超过了食物生产的增长率。到那时，生活水平（用人均食物来衡量）会回到之前的水平，生产力提高的唯一永久性后果是更高的人口密度。与马尔萨斯理论的预测一致，前工业化时代的生产力差异主要反映在人口密度上，而不是人均收入。大多数国家的生活水平是类似的，都接近温饱线，但是生产力高的地区有更多人。例如，多个世纪以来，中国是技术最先进的国家，包括在农业领域，中国劳动密集型的水稻种植方式的生产率比欧洲农业高得多。但是平均而言，中国农民没有比欧洲农民生活得更好。中国的人口增长率更高，人口密度很大，使得中国成为世界上人口最稠密的国家，如今中国仍是人口最密集的国家。类似地，在工业化前的几个世纪，西欧经历了相对高的生产力增长。虽然这一增长确实带来了生活水平的一些进步，但是主要影响是提高了人口密度和西欧人口占世界总人口的比例。

我们认为伴随经济增长的生育率下降反映了投资孩子数量到孩子质量的转变，这个转变是由经济激励推动的。教育是孩子质量的最重要的形式。当我们谈论到投资于孩子质量时，我们会说把孩子送去学校而不是让他们工作，可能还有支付优质私立学校的学费而不是把他们送去一所普通的公立学校。学校教育不是最终目的；当父母投资孩子的教育时，他们期望这项投资将来能以孩子更好的经济前途为形式带来回报。在研究经济发展与生育决策关系的经济学家看来，对人口转型影响最大的经济趋势是人力资本投资回报率的增长，也就是教育的回报率提高了。尤其是经济学家奥德·加勒（ Oded Galor）和戴维·韦尔（ David Weil）做出的学术贡献，他们认为教育的高回报激励父母在孩子质量上投资更多，并且为了努力承担起这种投资比前几代人生的孩子更少。[ 8]

教育的兴起和童工的减少解释了为什么在父母眼中孩子开始变得“昂贵”起来。他们不得不支付学费；更重要的是，孩子不再通过劳动为家庭收入做贡献了。这些因素使父母的激励转向拥有小家庭。所以经济上对人力资本更高需求的变化，创造了现代教育导向的中产阶层家庭，解释了工业化时期最重要的一些社会趋势。

对马赛厄斯来说，通过比较他孩提时在德国的经历与他妻子成年时在美国的经历，政府政策和社会规范对女性两者兼顾能力的影响尤其明显。在 20世纪 70年代的德国，把家庭和职业有机结合是一个难题。公立的日托只针对 4岁以上的儿童；小于 4岁的孩子几乎都由母亲来照顾。因为学校一般只开上午几个小时，学生中午就回家，所以即使孩子已经上学，对在职母亲也是一个挑战。此外，即使在上学时间，学校也不总是可靠的：如果因为老师生病而上课被取消，孩子就只能回家。制度的设计使女性几乎不可能兼顾照看孩子和从事一份高要求的工作。很多工作的女性万不得已才选择做在职母亲，大多因为孩子的父亲过世、失业或被监禁。所以当时有年幼孩子的在职妈妈会背上一些污名并不奇怪。

在马赛厄斯最近与法比安·金德曼（ Fabian Kindermann）的研究中，他检验了在工业国家对提高生育率最有利的政策。[ 35]与已经得到的结果一致，他们发现如果政府政策和当地社会规范能演化发展，使父母能兼容养育子女与追求事业的话，超低生育率可以被扭转。而简单的生育补贴政策是相对无效的。值得注意的是，有些超低生育率的国家已经对生育进行高额补贴。例如在德国，政府通过减税和直接的货币转移来支持育有孩子的夫妻，补贴额度比美国慷慨得多，但是德国的生育率仍然显著低于美国。专门支持在职母亲的政策（比如普及幼儿的日托）比直接补贴更有效。但这一政策面临一部分挑战，即家庭内部的劳动分工：在很多例子中，低生育率的国家也是男性在家劳动量最少的那些国家。如果男性能够被说服分担更多育儿责任[例如，引进“爸爸月”（ daddy months），也就是专门为父亲设计的育儿假，在瑞典和其他一些国家已经实行]，那么女性决定生更多孩子时会更轻松。

由于努力工作不会在未来带来高额的经济回报，贵族父母几乎没有动力给孩子灌输职业道德。做相反的事反而会有回报，即教导孩子享受优雅的休闲活动，比如让男孩打猎或让女孩学习音乐。这样的休闲技能之后会在提升社会阶级和择偶上发挥作用。要不然，上层阶级也不是平白无故地被称为有闲阶级（ leisure class）的。不必靠工作谋生是这个社会群体的鲜明特征，也是强调他们与其余阶级相区分的条件。在《有闲阶级论》一书中，凡勃伦（ Thorstein Veblen）指出在强调阶级划分时“炫耀性消费”与“炫耀性休闲”的用处。他写道：“不用工作是财富的直接证据，因而是社会地位的传统象征；这种对财富崇拜的经久不衰造就了对休闲活动愈发执着的追求。”[ 4]

所以休闲本身不是最终目的。与休闲活动相联系的特定技能也可以作为向上层社会流动的方式。对女儿来说，成功主要由好的婚姻来衡量。重点社交领域的技能（比如音乐和舞蹈）可以帮助实现这个目标。即使对男生来说，进一步向上流动的机会更多取决于社交技能而不是工作。在英国，长子继承贵族头衔，这意味着小儿子们不得不找到其他的谋生方法。然而几乎所有的小儿子们都不会去工作，而是最终获得令人向往的地位，这些地位只有具备良好的社会关系的人才有机会得到。

另一个有趣的现象是贵族实际上几乎不亲自教养孩子。婴儿被交给奶妈照顾，年幼的孩子由家庭教师负责，而男孩一旦到十或十一岁，就被送去寄宿学校。[ 7]标准流程是父母每天与孩子相处一个小时，而见面前孩子由保姆精心打扮和准备。由于贵族有钱，这样花也不值得惊讶。雇人来照看孩子对上层阶级的父母来说是完全负担得起的。因为不是所有的孩子都讨人喜欢，把烦躁外包给别人，而只享受偶尔与孩子相处的乐趣是十分明智的选择。事实上，即便在今天，我们仍能观察到富人经常依赖保姆的服务，而且寄宿学校的服务对象仍然主要是富人。然而，在现今以人力资本驱动的社会，有一个因素会影响他们雇人照顾孩子，即这些父母会担心相较他们亲自教养，雇来的帮手没有足够的能力使孩子掌握成功所需的技能。工业化前，上层阶级没有这样的忧虑，是因为他们的财富建立在土地上，其他人也可以很轻松地教授与土地相关的必要技能。

显然地，在成为未来的师傅所必备的特征中，耐心是非常重要的一点。当时的父母所面对的经济激励也由此表明中产阶级也是耐心阶级：只有教导孩子拥有足够长远眼光的父母才可能令孩子取得成功。从这个角度来看，工业化前的中产阶级与现代的中上阶级相类似，对他们来说，教育至上，并且想要在需要研究生教育的行业，比如法律、商业、医药或者学术界中有所成就，长远眼光是必备的。

谈到开始创业时的财富可能会成为未来成功的障碍时， 19世纪美国钢铁业的领导者安德鲁·卡内基可能是这个观点最有名的拥护者。卡内基在苏格兰长大，生活贫困，他是一个织布工的儿子。为了逃离苏格兰低迷的经济状况，他的家庭移民到美国。他十三岁时开始在一家棉加工厂工作，最终一步步成为了当时最富有的人之一。[ 16]卡内基把他的成功部分归功于从小就不得不工作：“我的父母本身很贫穷，作为他们最年长的儿子，我幸运地不得不在很小的时候就开始做一些有用的工作来谋生，因此当我还是小男孩时，我的责任就是帮助父母，像他们一样，尽早成为赚钱养家的人。”[ 17]之后，卡内基直言支持父母不应该把财富留给子女，而应该效仿他，把财富捐给慈善事业。他的观点就包括继承的财富对孩子没有任何好处。在《财富的福音》（ The Gospel of Wealth）一书中，卡内基写道：“父母留给儿子巨大的财富通常埋葬了他的天赋和能量，诱惑他过一种更无用和没有价值的生活，否则他可以过得更有意义，这似乎能被不可辩驳地证明。”[ 18]卡内基的观点与上层阶级在工业革命中作用很小的现象相一致。

** 第三篇 政策如何影响教养方式

学校会从方方面面影响孩子。首先，通过所传授的知识和所传递的价值观，教育者对孩子有直接的影响。公共教育的组织就是由于国家想灌输给孩子一套共同的价值观和信念推动的。公立学校不仅是传授知识的工具，它的建立也带有各种目标，包括增强社会凝聚力、加强国家稳定，以及很重要的是，普及公民对兵役的接受度。其次，孩子在学校与同龄人交往，这些互动也帮助孩子形成他们的偏好和价值观。同群效应有时候是对学校和家庭教育的强化和补充，有时候则会抵消。最后，学校系统的组织形式影响父母的行为。父母会针对学校系统提供的激励而调整教养方式，也会调整生育决策。

教育系统组织方式所带来的激励可以解释这些不同的看法。在北欧，学校之间几乎没有质量差异，很少有按能力分班的情况，学生接受高质量的高等教育的机会很多。大多数孩子上当地的公立学校，只要能从中学毕业的话，进入公立大学并没有难度。所以当家长送孩子去参加各种活动时，他们只是想要孩子开心，或者至多不过是要提高孩子的独立性和成熟度。课外活动是“好学校”敲门砖的想法对他们来说是匪夷所思的。在德国，与北欧一样，大多数家庭依赖公立学校，但是在有些州，学生在四年级或六年级之后会分校，或是去更易考大学的学校（学术型高中），或是以后进行职业训练的学校（实科中学或职业预校）。从“有野心”的父母角度来看，让孩子进入学术型高中是一个重要的目标，但课外活动在录取流程中不发挥作用。但凭借任何学术型高中或其他大学认可的学校的毕业证书，学生都可以免费进入大多数公立大学，而且这些大学的质量相对统一。

关于高考制度的争论引发了教育体系改革的压力。改革者要求减缓过度竞争，推行以学生为导向的制度。改革的另一个动力来自对独立性和创造性的考量，现行的体系没有足够重视这些价值，但是如果中国的经济模式从模仿和生产已有的技术转型为更多地依赖创新创造，那么这些价值对学生来说会变得越来越重要。[ 25]

日本的公立大学录取分两个步骤。首先，学生必须通过全国大学入学中心考试，这个考试涵盖所有基础学科，包括文科和理科。然后，他们必须参加各个大学的考试。[ 29]顶尖大学的录取存在激烈的竞争，所以第二步是最大的挑战。有些学生花几年的时间不断尝试，以求被心仪的专业录取。这些学生有时被称为浪人，本义是称呼历史上没有领主或主人的武士。

芬兰教育者对他们的教育系统感到非常自豪。帕斯·萨尔伯格（ Pasi Sahlberg）以前是一位学校老师，现在是政府顾问，他写的一本关于芬兰教育系统的书还获过奖，他认为没有标准化考试是芬兰教育系统的一个关键优势。[ 32]他认为让孩子准备全国性考试会分散老师的注意力，使他们不能关注于提高孩子的学习能力和理解力。他认为公布标准化考试的结果和追求学校排名导致了“有毒的竞争”，这会阻碍学生合作能力的发展。[ 33]然而某种程度上与萨尔伯格的观点相矛盾的是，芬兰学校在国际上受欢迎，要归功于芬兰学生在标准化 PISA测试中的成功。什么能解释芬兰的成功呢？萨尔伯格认为是因为没有竞争性考试。然而，芬兰教育系统另一个鲜明特征是非常重视教师的资格。芬兰国家教育局坚持对所有层次老师的高学历要求，所有老师都要有硕士学位。此外，即使是教育专业的大学毕业生想要当小学老师，也需要在其他学院上课，精通至少两个其他领域。虽然当老师要求严格而且工资基本与国际平均水平一致，但是教师仍然是最受芬兰大学生欢迎的职业选择之一。很多学生会申请教师专业，大学得以在每一届中选出最有资质的学生来培养。

尽管工资不吸引人，但高教育水平和高能力的芬兰人愿意选择成为教师，原因之一是教师在芬兰有很高的社会地位。高学历要求保证了只有最好的学生才能成为老师，使他们受人尊敬。只有 10%到 15%的老师放弃他们的职业，这可以反映教师的受欢迎程度。[ 35]芬兰教师的心理满意度很高，这是纳税人的福气，他们所缴纳的税款能有高价值回报。在教师职业不那么受欢迎的国家，政府需要支付高额工资来吸引同等质量和教育水平的人。芬兰能够创造有吸引力的工作条件，使老师对自己的职业感到满足，这可以很大程度上解释芬兰在教育上所取得的成功。

有些国家主要采用“垂直”型教学实践，也就是等级系统，其中老师与学生的关系是教室互动的核心元素。老师讲课，而学生记笔记或看课本。对学生的评估标准是他们重现老师所讲内容的能力。在其他国家，学校更推崇“水平”型教学实践，学生之间的互动是师生关系的重要补充，师生等级关系更为弱化。在水平化的环境中，学生在群体中学习，一起做课题，老师鼓励学生提问甚至挑战自己。通过考虑各种指标，这项研究表明水平教学实践在北欧国家、荷兰和瑞士最常见，在英国和美国也颇为主流。垂直教学实践则盛行于法国、日本、比利时、土耳其、俄罗斯和东欧。介于两者之间的则是意大利、德国、西班牙、澳大利亚和（某种程度上出乎我们意料的）芬兰。阿尔刚、卡赫克和施莱弗证明教学实践影响人们成年后的信任程度和合作意愿。年轻时接受垂直教学实践的人更不信任别人、更不愿意合作，而学生时期经常参与小组合作和公开讨论的人，长大后则更具合作精神。

法国既有普通大学，也有“大学校”（ Grande É cole）。“大学校”是一系列与其他大学独立的精英机构，为法国政府、行政机关和私人部门的国家精英提供高质量的教育。只有不到 5%的学生能上“大学校”。为了进入这些学校，学生首先要在高中毕业后申请预备课程（ classe pr é paratoire）。在这些课程中，学生需要不停地学习（学生每周有四十个小时的课程，经常会有测试，还有大量作业）。两或三年之后，学生需要参加一场竞争激烈的考试，才能获得进入某一所“大学校”的机会。

侵入性的权威型教养方式能增强个人成功的驱动力，但这同时也阻碍了孩子独立思考能力和想象力的发展。此外，虽然权威型家长能成功提高孩子的学校成绩，但这对于社会而言并不总是有利的。在北欧国家，大多数家长采取放任型教养方式，孩子竞争心更弱，更不愿意进行持续不懈的努力，但是他们有极好的团队合作能力。而直升机父母，在我们看来，是权威型父母的溺爱版本，他们的爱护措施可能能够塑造孩子的偏好和态度，并且使孩子不惹麻烦。然而，随之而来的代价是孩子向成人的自然过渡阶段被推迟，如故事中所说的三十多岁还与父母住在一起的“妈宝男”一般。同样，我们也不认为放任型教养方式是万能灵药。放任型教养方式可能有利于培养孩子的想象力和独立性。然而在某些环境中，被放任自流的孩子可能会被诱导去尝试酒精、毒品等危险活动。家长管教的缺位也可能助长了有些孩子只顾眼前快乐、不顾长远后果的冲动。有些孩子在学习上不够努力，无法受到良好教育。高竞争性环境中，偷懒的不良后果更为严重。例如优秀的成绩对获得好大学的录取非常重要，偷懒的孩子在这场竞争中将被淘汰，失去了受高等教育的机会。

最近一个被广泛讨论的现象是“中产阶级的空心化”（ hollowing of the middle class）。[ 4]新技术和新机器逐步取代中等技能的工作，例如银行职员、白领工厂工人和公共部门职员等。公司组织形式的变化使得它们正在大幅削减底层管理岗，并给予高层管理者更多自主权和控制权（以及更高的报酬）。[ 5]在所有 OECD国家，相对于高技能和低技能职业，中等技能的职业正在缩水。这种两极化引起了人们的担忧，因为很多经济学家和政治学家将中产阶级共识视为将民主社会粘合起来的“胶水”。中产阶级的衰落会削弱社会凝聚力，这一方面会引起社会底层群体的更多不满，另一方面又导致精英阶层不愿意投资公共品，为大多数人提供服务。而就教养方式而言，这种技术趋势会加强对教育机会的竞争，因为教育能保证孩子在社会中提升的可能性。

然而，不必担心这种变化会导致大规模失业和普遍贫穷。未来社会会出现技能需求的重叠，以及不同职业工资的巨大变化。医生会需要掌握越来越多关于机器的复杂知识。对程序员、应用数学家、工程师和物理学家的需求会持续增长。高级律师将继续事业兴隆，但仅仅只有少数能够做到，而当机器接管日常工作时，法律公司收费时间的总量将会下降。顶尖大学，尤其是文理学院，则不得不调整教育服务的供给。如果这个场景实现了，那么当他们意识到多年的不懈努力无法得到回报，即使拥有名牌学校的学位，孩子的职业前景也不那么明朗时，一些权威型家长可能会感到沮丧。选择正确的专业将逐渐变得比进入正确的学校更加重要。
