#+title: 在Mac下面制作USB启动盘

自己的Ubuntu系统一直不太稳定，但是忍着用了下来。但是前几天因为想切换到Python3.6, 看到自己Ubuntu里面带了一个Python3.4觉得特别碍眼，所以就 `apt-get remove python3` 删除掉这个组件。我记得当时apt提示了一大串依赖于这个python3的组件，不过我没有上心直接就回车，直到删除的过程中出现了一些问题比如桌面好像发生一些奇怪的变化才反应过来，但是那个时候python3已经卸载了。重启之后登录发现自己的ubuntu desktop已经没有了边框和通知栏了。在网上找了很多帖子但是好像有不太管用，心想干脆重装系统得了。因为我大部分数据和安装软件都是放在单独的partition下面的，所以重装的话没有任何问题。（这次得到的教训是，不要随便删除软件，而且删除之前一定要看看影响的范围）

听说Ubuntu16.04出来了所以想试试，于是下载了一个16.04的iso. 我的USB硬盘之前除了故障，所以网购了一块U盘第二天才到。想到自己终于可以升级系统，觉得特别兴奋。可是当我插入USB的时候，原来的Ubuntu系统是无论如何都不能识别。 `dmesg`看来一下好像是 `set address failed to response` 这类错误。网上找了一圈解决办法，都不太work. 我想如果Ubuntu不能是识别这个USB不要紧，只要BIOS可以识别就行。不过这样就没有办法在Ubuntu下面制作启动U盘了，可是我之前只试过在Ubuntu下面制作过启动U盘，但是想Mac下面应该也有吧。

在 Ubuntu 官网下面找到了这个 [[https://tutorials.ubuntu.com/tutorial/tutorial-create-a-usb-stick-on-macos#2][链接]] ，按照这个办法做了一个启动盘，在BIOS里面可以识别出来，并且认为这个是一个Ubuntu系统盘。可是在选择 "Install Ubuntu" 之后，一直挂起。我无意中按了一下F10看了一下，后台一直出现 "stdin: not a typewriter" 这个错误。这个错误我不太理解，而且网上好像也没有什么靠谱的解释。

我只能怀疑是不是这个 Ubuntu16.04 版本太高，或者是ISO有点问题。还有一个可能是这个烧制软件 "Etcher" 有点问题，因为我之前在Ubuntu下面制作的U盘在Mac下面是可以查看的，并且里面还有一个 "wubi.exe" 这个文件。烧制软件错误概率可能较低吧，毕竟开机出现了Ubuntu的画面，应该是一个正确的盘。于是我尝试下载 Ubuntu14.04 再碰碰运气，但是问题还是在那里。

那么一定是烧制软件的问题了。我无意之间发现了 [[https://unetbootin.github.io/][unetbootin]] 这个软件，拿Ubuntu14.04.iso试试，得到的U盘里面还真的有 "wubi.exe" , 我觉得这次应该没有问题了。这次重启选择 "Install Ubuntu" 之后没有再出现 "stdin: not a typewriter" 错误了，而是直接卡住在黑屏上。当时我无计可施，后面又尝试了好几种办法都没有成功。

第二天我翻阅知乎的帖子，无意中看到了 "deepin" 这个Linux发行版本，评价是非常适合国人使用，有很多在Ubuntu需要自己去找的软件比如微信QQ以及搜狗输入法等。抱着试试看的心态下载了这个版本，用 unetbootin 创建启动盘，但是依然没有成功。这个时候我突然发现，我在格式化硬盘的时候选择的是 "GUID分区图", 而选项里面还有一个 "主记录分区". 会不会是这个问题？再试一把之后果然是这个问题。走了太多的冤枉路，花了太多的冤枉时间了。

-----

所以总结以下制作USB启动盘步骤：
1. Mac下面使用磁盘工具格式化
  1. 选择 "主记录分区" 选项
  2. 使用 MS-DOS FAT 文件系统
2. 使用 unetbootin 来创建USB启动盘
3. [[https://tutorials.ubuntu.com/tutorial/tutorial-create-a-usb-stick-on-macos#2][Ubuntu官网教程]] 是错误的方法（或者说不是我想要的方法）
