#+title: 大师访谈录（Making it Big in Software）

https://book.douban.com/subject/30238423/

如果你认为自己的价值在于能迅速响应，就容易打破生活和工作的平衡。如果我把自己看做一台回复邮件的机器，那么我的工作永远结束不了，因为邮件会源源不断地进来。相反，如果我觉得自己的价值体现在能区分重要和不重要的事，并且在重要的事情上做正确的决定，那么我就能在合理的时间下班回家，陪伴家人，整个周末不理会邮件和电话信息，并能保证回到工作时，有不错的状态，能做正确的决定。

这就是现实世界里提案的运作方式。这有点像联合国投票。你真的以为联合国对各国事务的决策是由出席联合国会议的各国大使表决的吗？真的以为那些重大决策事先没有核实关键投票方的意见就被提交到联合国吗？当美国或某个大国将解决方案拿到桌面讨论的时候，请放心，他们早就与盟友事先审核了该提案，而且关键的立场在投票前也已经被打听得一清二楚。决策前的反复评审与修改总能使得提案越来越完美，支持度也越来越高。

我们关心和思考的事情，构成了我们的关注圈（Circle of Concern）。这个关注圈里的很多事情，使我们很难或无法控制的，即使我们特别关注他们。我们的每一个关注圈里，都有一个叫做影响圈（Circle of Influence）的子集，这个圈子里的事情，使我们个人可以控制，或者至少能够影响的。想要提高个人效率，关键在于弄清楚那些事情位于我们的影响圈内，然后把时间都投入到这些事情上。把时间用在影响圈之外的事情，通常还会引发消极情绪。举个比较极端的例子，一个世界顶尖软件公司的高级架构师曾对我说，他从来不看报纸，因为这些内容不再他的影响圈之内！虽然我不提倡完全与世界隔离，了解世界大事和当地新闻还是有好处的。

所以，想要做事都紧迫感，首先得培养这种品质，其次压控制这种品质。若做不到后者，那么最好就别培养它。作为一种个人品质，紧迫感是一种微妙的平衡感能力。在此，我有三个建议：第一，自己带着紧迫感做事，但别期望或要求你身边的人和你一样。第二，尽量不要把工作上的紧迫感带到生活中。工作中事无巨细，礼貌地督促大家完成任务是有帮助的，但日常生活中有些事情不需要这样。最后，别让紧迫感成为别人讨厌你的理由。做事有紧迫感不是对人粗鲁的借口，相反，如果你既能保持紧迫感的艺术，又能对身边的人彬彬有礼，处处为他人着想，你就成为了自己的主人，享有真正的自由。

软件项目延期的根源：
- 范围蔓延，需求不断增加
- 人才市场无可代替的
- 项目滞后时借调人手只会适得其反
- 研发团队目标模糊
- 依赖关系管理，无法细数软件功能。
  - 软件的不同功能通常会使用公共组件
  - 如果在公共组件上交叠越多，代码相互牵绊也就越多
  - 所以项目时间会超过所有单个项目时间总和
- 对时间的预估不准确，时间比例分配不合理
- 对时间的预估过于激进
- “我不是项目延期的罪魁祸首”
  - 项目延期背后还有社交动力的原因
  - 他们觉得身边的同事们都在延期
  - 他们认为只要自己不是造成项目延期的原因，那么自己进度落后也没有什么关系
- 有人拒绝采用软件工程方法
- 没有考虑到员工做杂事的时间
- 天有不测风云（市场变化，客户需求变化，公司战略变化）

几种领导风格

| 风格   | 概述                                                                     | 一句话解释               |
|--------+--------------------------------------------------------------------------+--------------------------|
| 强制型 | 让下属按照自己的指示工作，为人果断，自信，做事有效率                     | “照我说的去做”           |
| 权威型 | 深谙行业内情，具有个人号召力，促使其他人跟着他的脚步                     | “跟着我”                 |
| 亲和型 | 首先考虑大家的诉求和利益，通过潜移默化的方式，令下属变得敬业和忠诚       | “以人为先”               |
| 民主型 | 强调参与，会有针对性地让团队参与到工作中，建立共同目标和连带责任         | “你收什么看法"           |
| 示范型 | 以身作则，做优秀的示范，要求其他人同样地专业和努力                       | "现在就按照我的方式去做” |
| 指导型 | 注重团队的进步和发展，培养团队成员来提高这些人的能力和公司的长期发展能力 | “尝试一下”               |

以目标为导向，知道你要做什么。如果你天资聪颖，见微知著，就可以实现目标。不一定要学过这些知识，不一定要上过相关课程，只要你够聪明就行。挑几本书读一读，研读几篇论文，琢磨怎么解决问题。无论如何，都要相信自己，你不需要什么书来指导，你自己就能写这么一本书。这是我个人的经验之谈。请牢记，革命性的突破和技术创新都来自在校的年轻人，而不是出自那些毕业多年的工作老手。 -- Steve Wozniak
