#+title: Making money along the way

[原文地址](https://signalvnoise.com/posts/3946-making-money-along-the-way)

不要老是惦记着growth, 也要考虑赚点钱养活自己。

There’s no natural law that states all products and services must endure forever and always. Some companies are glorious sprints, others are slugging marathons. Both can work, but the former is especially sensitive to making money along the way. 并不是所有服务和产品都需要last forever的，一些公司做的产品和服务就是短平快的。但是这种公司相比长线发展公司来说，对盈利更加敏感。

The problem is that everyone thinks they’re going to run a spectacular marathon in technology these days. There’s no amount too great to be invested in future growth, because the future is infinite, and you’d be a fool not to capture as much of that as you possibly can. 

**Don’t put it all on growth**

A lot of business administration is about managing risk. Thinking about how things might pan out if you’re not as clever as you think you are, or as lucky forever as you currently seem. 许多商业管理就是管理风险，所以你需要时刻关注风险。

Yes, investing in growth when you got a good thing going is smart. But so is thinking that you might currently be enjoying the very best years of the business, not just “the beginning of an amazing journey”. 

The smart choice is making sure you win in both cases. Don’t just keep putting it all on red and rolling. Eventually, everyone’s luck or skill runs out, and then it’s awfully nice if the entire time spent playing wasn’t all for nothing.
