#+title: 牛津通识读本-数学

https://book.douban.com/subject/25829287/

人们在学习高等数学时，走到一个证明的结尾处，通常会经历这样的思考：“我理解每一行是怎样由前一行得到的，但是我却不明白为什么这个定理是正确的，人们是怎样想到这个论证的。”我们经常想从证明中得到更多的东西，而不仅仅是确信它的正确性。读过一个好的证明之后，我们会感到它对定理进行了一番阐明，使我们理解了之前所不理解的一些东西。

总结上述做法的一种方式是，称之为把几何转化为代数，通过坐标系来把几何概念翻译为等价的但只涉及数之间关系的概念。尽管我们不能直接对几何进行拓展，但我们可以对代数进行拓展，而且将这种拓展称为高维几何似乎是合情合理的。五维几何显然不像三维几何那样与我们的切身经验直接相关联，但这并不妨碍我们去思考它，使它作为模型发挥作用。

于是，我具有了某种初步地将四维和五维图像化的能力。（如果你对“图像化”这个词感到困扰，可以换一个词，比如“概念化”。）当然，这远比三维的图像化要困难——比如，我无法直接回答，四维立方体旋转是什么样子，而三维的我就可以说出来——但是，这也明显要比五十三维的图像化要容易，要是它们都不可能的话也就谈不上谁比谁容易的问题了。有一些数学家专攻四维几何，他们四维空间图像化的能力得到了极大拓展。

对数学来说，这个心理学要素的影响已远远超出几何学的范围。投身于数学研究所能得到的乐趣之一就是，随着专业领域的经验越来越丰富，你能够发现自己“仅仅观察”就能得到越来越多问题的答案，不一定非得是几何问题，而这些问题你以前可能要艰难思考上一两个小时。

我们能否对维度做相似的事情呢？要想这么做，我们就必须找到与维度相关的某些性质，它和整数并没有直接的关系。这样就把与坐标数字相关的一切排除在外了，因为坐标看起来和维度这个概念联系实在太紧密了，让人很难思考其他东西。但是，的确还有另一种性质，在本章开头简短地提到过，它恰好给出了我们所需要的东西。 几何有一个重要特征会随维数变化，这就是当把形体沿各方向以因子t扩张时，有个规则决定形体尺寸如何变化。尺寸一词，我指的是长度、面积或者体积。在一维上尺寸变为t倍，或t1，在二维上尺寸变为t2倍，在三维上变为t3倍。因此，t的指数就告诉了我们形体的维数。

科赫雪花有一些很有趣的特征。和我们的主题相关的一个是，这个形状可以用它自身的微小版本建造出来。这仍然可以从图中看出来：它由四个小版组成，每一小版都是由完全版以因子三分之一收缩而得的。现在让我们来考虑，关于维数它告诉了我们什么。如果一个形体是d维的，那当它以因子三分之一收缩时，它的尺寸会除以3d。（如我们所见，当d为1，2，3时，这是正确的。）这样，如果我们能够用图形的微小版本来构建出原图形，那么我们就需要3d个小版本。因为对于科赫雪花来说需要四个，所以它的维数d应当满足3d=4。由于31=3而32=9，这意味着d介于1和2之间，所以并不是一个整数。实际上，这个数是log34，约为1.261 859 5。

为了把它用在不太熟悉的情形中，即用到三维上，我们必须努力找到弯曲表面易于扩展的性质，就像我们要定义23/2、五维立方体或科赫雪花的维度时所做的那样。因为我们最终要找到的性质应当是能够在空间之内察觉到的，所以我们应当去寻找，怎样在a不需要站到弯曲表面之外的情况下就能察觉到它的弯曲性。

我上面给出的近似值定义最主要的用途是作比较。例如，现在我们能够明显看出，对大数n而言，其对数要远小于立方根：比如，如果n有75位，它的立方根将会很大——大约有25位数，但它的自然对数则大约仅为75×2.3=172.5。类似地，数m的指数幂会远大于它的乘方，如m10。例如，若m有50位，那么m10大约有500位，但em大约有m 2.3位，远大于500。

没有接触过大学数学的人很少会提出这样的问题，其原因在于，他们没掌握将问题公式化表达并进一步思考所需的语言。不过，若是这章到现在为止你都看懂了，那么你就能够欣赏到数学中最伟大的成就之一：素数定理。定理陈述的是，在数n附近的素数密度约为1/logen，即1除以n的自然对数。

既然素数分布有零零散散、颇似随机的性质，而我们却能证明其如此多的特点，这足以令人十分惊讶。有意思的是，关于素数的定理通常都是通过利用这种看似随机的性质得到证明的。例如，维诺格拉多夫在1937年证明的一个著名定理认为，任意充分大的奇数都可以分解为三个素数之和。我无法在本书中解释他是怎样证明的，但他绝对没有找出将奇数表达为三素数之和的方法。这样的思路几乎注定会失败，因为即使是生成这些素数本身也非常困难。基于哈代和利特伍德之前的工作，他大体按照下述办法来论证。如果你能够按照和素数分布同样的密度来真正随机地选取一些数，那么概率论的某种初步理论就能够表明，你几乎一定能够将所有充分大的数表示为你所取的这些数中的三个之和。

数学中绝大多数影响深远的贡献是由“乌龟”们而不是“兔子”们做出的。随着数学家的成长，他们都会逐渐学会这个行当里的各种把戏，部分来自于其他数学家的工作，部分来自于自己对这个问题长时间的思考。是否能将他们的专长用于解决极其困难的问题，则在很大程度上决定于细致的规划：选取一些可能会结出丰硕成果的问题，知道什么时候应该放弃一条思路（相当困难的判断），能够先勾勒出论证问题的大框架继而再时不时地向里面填充细节。这就需要对数学有相当成熟的把握，这绝不与天赋相矛盾，但也并不总是会伴随着天赋。

数学中常常会引入重要的新思想，新思想会比旧思想更加复杂，每一个新思想的引入都有可能把我们甩在后面。一个很明显的例子就是用字母表示数，很多人对此糊里糊涂，但对某个层次以上的数学来讲这是基础性的。还有其他类似的例子，比如负数、三角函数、指数、对数以及初步的微积分。没有作好准备来进行必要的概念飞跃的人，一旦遇到这些新思想时，就会对其后建立在新思想基础上的一切数学感到并不牢靠。久而久之，他们就会习惯于对数学老师所说的东西仅仅一知半解，日后再错过几次飞跃，恐怕连一知半解也做不到了。同时他们又看到班上其他同学能够轻而易举地跟上课程。因此就不难理解，为什么对许多人来讲数学课成为了一种煎熬。

专业数学家能够很快地意识到，他们就著名问题所产生的几乎任何思想，都已经有许多前辈想到过了。一种思想要想成为全新的，就必须具备某种特征能够说明为何前人从来没有考虑过它。可能仅仅是这种想法极具原创性，出人意料，但这种情况十分罕见：总体而言，某种思想的诞生会有充足的理由，而不会是凭空冒出来的。如果你有了这种想法，那凭什么别人就不曾有过呢？一种更加合理的理由是，这个想法和别的某种思想相关，那种思想的知名度并不高，而你已经不畏艰难地去学习并且吸收那种思想。这样至少降低了别人在你之前已经有过同样想法的概率，虽然还是没有降到零。
