#+title: Mean People Fail

原文链接 http://www.paulgraham.com/mean.html

中文翻译 http://36kr.com/p/217440.html

最近我一直在思考，俗话说无奸不商，可为什么现在成功者中少有卑鄙的呢？当然也有例外，但是非常少。

卑鄙的人可不是少数。实际上，是互联网让我们了解到一个人能够被卑鄙到什么程度。过去只有名人和专家才能掌握舆论，现在互联网给了每个人传播的渠道，我们这才能看到那些过去被隐藏在长尾中的卑劣的人和事。

尽管卑鄙的人很多，但是成功者里鲜有存在，难道说，卑鄙和成功是互斥的吗？

我的这种判断，或许因为我视角的偏差。因为我只认识创业者、程序员、教授这些类型的人。我倒挺相信其他领域的成功者是手段卑鄙的，比如我总觉得那些对冲基金经理肯定是奸诈狡猾的，但我不了解这个领域，所以无法做出判断。又比如，那些大毒枭给人感觉都是手段极其残忍的。但是最少世界上还有很大一部分净土，在那里，卑鄙的人不会成功，而且这部分领土正在扩大。

我妻子，同时也是 YC 的创始人 Jessica，她有着能像 X 光扫描一样洞察他人品行的特异功能，娶她回家就像娶了一台机场的安检仪一样。她从投资银行进入到创业领域，一路走来她也同样注意到这样一个现象，那就是： *品行好的创业者总是能取得成功，而人品卑劣的人创业总是失败。*

这是为何呢？我觉得有以下几个原因。第一，卑鄙的行为让你变得愚蠢。这是我痛恨竞争的原因。在竞争中，你没办法发挥到最好。因为竞争不具有一般性，在竞争中获胜，需要考虑天时地利，还有人为的因素。取得胜利往往不是通过更好的去思考，而是通过一些在某些特定情形适用的伎俩。竞争和解决真实问题同样费脑子，对于那些珍惜自己脑细胞的人来说，这是一件非常痛苦的事情，就好像汽车轮子一直打滑，你的大脑飞速运转着但是却什么实质性工作都没做。

创业公司不是通过攻击对手来获胜的，他们取胜的方式是超越对手。当然也有例外，但通常创业者成功的方式是跑在前头，而不是停下来和对手干架。

耍手段的创业者会失败的另一个原因，是他们招不到最优秀的人为他们工作。确实有人能够忍受和他们一起工作，因为他们确实需要一份工作。但是最优秀的人会有其他的选择。一个卑鄙的人无法说服最好的人才为他工作，除非这人非常善于游说。而团队成员的质量对创业公司又至关重要。

第三个原因，仁爱的精神同时也是他们前进的辅动力。如果你想做伟大的事情，驱动你的通常是一种仁义的精神。最富有的创业者他们最想要的不是钱，被金钱驱使的创业者通常会在面临高价收购时，选择把公司卖掉。那些还继续坚持的创业者，他们内心有着比金钱更高的向往。虽然他们可能不会经常挂在嘴边，但是他们一直在努力改善这个世界。这意味着仁义的内心是一种天然的优势。

更让人激动的是，人品和成功挂钩的游戏规则，不是仅仅适用在创业领域，一个崭新的未来正在到来。

历史中，大部分的成功意味着掌控稀缺资源，获得它需要经过激烈的争夺。游牧民族通过侵略把食物采集者赶往贫瘠的土地，镀金时代的金融家通过激烈角逐来实现铁路垄断。过去，要想成功，就得赢得零和博弈（zero-sum games），把别人的抢过来，变成自己的。这种情况下，卑鄙不仅不是成功的障碍，反而成为了一种优势。

但是现在时代变了，没有你死我活，获得成功也不再是通过抢夺稀缺资源，而是通过创新和创造。

事实上，创新驱动成功的游戏规则早就存在了。在公元前三世纪，阿基米德的成功法则就是通过不断的创新，至少在他被闯进来的罗马士兵杀死之前。这也说明，以创新为驱动力的社会生存法则，需要社会秩序达到了一定的高度。这不仅仅是说没有战争而已，还包括避免 19 世纪的巨头之间的经济暴力，要能够营造出一种安全感，我的创新不会被随意窃取。

创造力在过去一直是思想家们的生存法则，他们是在浪潮之巅的人。你如果回想一下历史上那些不是依靠残忍手段获取成功的人，你首先会想到数学家，作者和艺术家。现在，知识分子的游戏规则已经开始渗透到了更广大的真实世界中，正在逐渐扭转过去成功和道德的历史性对立关系。这是多么振奋人心的时代！

我和夫人一直教育我们的孩子要做一个好人，我们可以忍受着噪音，拥挤，垃圾食品，但是我们不能忍受卑劣的人品。现在我教育孩子的时候又多了一套说词：卑鄙的人不会成功!

(note:1.我并不是说那些被收购的创业公司都是为了赚钱，我只是说那些没有选择收购的公司往往有更高的动机，而且很多改善世界的动机同时也很有商业前途。2.不是所有的创业公司都能够改善这个世界，但他们的创始人内心确实是这么想的。3.Sam Altman 提到很多创业公司也是通过垄断来大量盈利的，但他们并没有刻意去制造垄断，而是扑捉到了这个机遇。4.其实罗马士兵初衷并没有想杀死阿基米德，但无论如何他还是在这场混乱中丧生了)
