#+title: 做CTO都是出去过的

@2013-06-14

下午dyq来公司看望我们。年轻真好，趁着端午节的时候请假两天，来北京找一帮兄弟们骑自行车去郊区玩。车是借的，落脚的地方也是借住的，有朋友真好，至少到哪里都有着落。我们一帮人趁着CEO没有看到的时候，偷偷地留了出去，提议去上岛咖啡去叙叙旧。这里有最低消费，我们一行6个人点了一杯茉莉花茶，一杯普通的咖啡，一共消费210元。。。摸着空空的钱袋，羞涩地从同事手中借了110，才凑够钱。原来IT真的很苦逼。

dyq现在准确地说是负责后端的开发，不再单独搞Hadoop了，现在什么都做，按照他的话说，自己是成为了真正的多面手，能力得到了全面的提升。当问及如何盈利的时候，dyq说他们现在还在烧钱，不过因为团队非常小20人左右，机器也是20台左右，加上深圳租房价格不是很高，所以总的成本非常低。现在唯一盈利的办法就是给推荐的blog或者是site带去流量然后付费。mmliu期间提到说有一个网站，专门做文艺性质的图片，只有3个人很少的服务器，通过广告的方式每个月10w，着实有点让我心动，不知道以后单搞是否有可能。晚上和litao谈到了天津的IT行业，之前聊过很多，晚上突然蹦出了一个念头，在天津做IT培训，他觉得似乎比在天津做互联网要靠谱很多。anyway, just a idea.

不知怎么地说起了CTO这个东西。dyq说他们的CTO以前是在amazon做的，后来出去了一段时间回来做了。这时候rentian冒出了一句话让我有点开窍的感觉：“原来，做CTO都是出去过的啊”。这句话说的这么随意，但是仔细想想却异常有道理。国外尤其是北美，欧洲在计算机技术以及互联网开发方面，确实比我们强许多，并且他们的一些成功经验值得我们借鉴。在国内做技术，时间长了容易忘记什么才是正确的，有在外面见过的有经验的人提点和帮助的话，可以少走一些弯路，知道什么是正确的，什么是不正确的，以后技术会是什么样的，不是什么样的。

rentian有点把话题扯远了，开始聊起了肉身出去这件事情。我一直觉得肉身出去是一件非常奢侈的事情，大师则轻轻地对我说，你应该去看看ruby china的论坛上面，有专门一个板块讲如何移民的。并且告诉我，在国外有很多做web和app的startup, 而这些做web基本都是使用ROR来开发。看来为了这个东西，我是不是有必要学习一下ruby以及ROR？web, mobile app确实是以后互联网的趋势，client逐渐变thin，越来越多的计算在server完成，人们对于access internet的需求比以往任何时候都要强烈。
