#+title: 创业/小公司的优点和缺点

自由，包括工作时间以及工作内容。前提是在团队里面要有很强的话语权，至少是最开始的几个人 。自由有它的代价，自由需要人们有高度的自律性，不然外部给予限制会更好。曾经有一段时间我是一个远程工作者，我对那份工作内容兴趣不是很大，并且加上一些语言和交流问题，很快我便在工作上没有太多的激情。所以每次打开电脑，都会花很长时间看看网页或者是视频（不一定是很大块的时间，但是加在一起应该是不少时间了）。这段工作经历对我的负面影响非常大，让我意识到自己可能并不太适合远程工作。我个人很喜欢自由的生活和工作，但是同时也需要有一个office的环境大家可以每周在一起工作个1~2天。

执行力。有一个idea之后可以很快地applied，这个“很快”具有相对性。我是一个急性子，所以有了一个感觉比较靠谱的idea并且实践起来不难的话，就很想试试看看效果。这个过程感觉很好。前提是这个团队的氛围以及项目里面一些issues的优先级不会限制到执行，不过即便有所限制始终会比大公司要好。

影响力。因为团队成员非常少，所以一些贡献很容易被团队其他成员看见，同时因为小公司的产品始终是针对一个niche的市场，所以一些工作更容易带来产品上的爆发式增长，不过这个始终是个概率问题，并且和外部因素关系也比较大，有时候不能说是某一个人或者几个人的工作。

视野。相比大公司，更能接触到一些中小公司的情况，而这些中小公司的又是非常具有活力的，比如他们的early adoption会非常高，使用许多前沿的技术等；又或者用一些大公司鄙视的简单和土办法来解决许多实际问题。这些东西可能在大公司里面是接触不到的。不过反过来，大公司的格局大用户多，需要解决的问题都是非常具有挑战性的，所以很难说哪种视野更加正确。很早的时候，我认为大公司的一些技术都是屠龙之技，在许多中小公司没有办法很好地使用，sort of out of reality. 现在觉得，这些技术（不管是理论还是工程实践）都代表着人类智慧的高水平，即便它们很缺乏使用价值，光是它们本身就很有意义了。

UPDATE@201602: [[https://medium.baqend.com/parse-is-gone-a-few-secrets-about-their-infrastructure-91b3ab2fcf71#.5xko3ulrp][Parse关闭之后的一些经验分享]] 在创业公司能够随着公司发展，解决从0到N的问题，所以能够得到0到N的经验。而在大公司前人已经把框架和结构搭建好了，那么积累到的只能是N-1到N的经验。
