#+title: 没有妻子的婚礼

@2013-02-12

结婚对于女人来说非常重要，这一点我很早就了解到了。还在上学的时候就看老友记，monica为自己的婚礼费劲心思，从小就梦想有一个完美的婚礼，穿着白色的婚纱。而对于我的老婆而言，我却没有给她婚礼。

2012年元旦的时候，她就商量结婚的事情并且要办婚礼。我回去和爸妈商量，妈妈非常不愿意，总是拿爸爸的身体为借口说“办婚礼非常麻烦，你等等你姐到时候一起办一个，不然这样折腾你爸你心里也过意不去吧”。可是对于我老婆来说，按照她那边的风俗，没有一起办的这么一个说法，一起办的话等同于非常看不起这个儿媳。然而当时老婆非常急切地要结婚，我也没有多和她商量就答应下来了，并且和爸妈说“要是真的办婚礼的话，我肯定回去帮忙"，同时说好让她家挑选日子。

她家的风俗习惯是挑好日子就赶紧办，对于我和她来说有两个好日子，一个大概是11月份左右，另外一个是最近的3月份。“好吧，那就最近的三月份“，我答应她家了并且和父母说了。母亲明显不愿意：”那你要办的话让你爸自己办“，而我爸可能考虑到当时的情况，就先答应我了。

那年春节去她家过年，她爸妈多次问我”你爸妈什么意见”，当时老婆催我很紧而且我也比较顺着她，就不想逆着她的意思，就说家父在办，但是时间还没有订下来。岳父岳母听我这么说，也就没有多问。而我心里知道，要是这个事情真的搞不下来，那会让多少人失望啊。但是我相信，我爸答应了就应该会办的，不行我还可以去帮忙。人少是一回事，办不办是另外一回事。

大约初五的时候，岳父岳母又提起了这件事情。但是因为讲到了具体细节以及时间安排，要问我具体什么时候可以安排下来。我说我打电话问问家里。接电话的是我妈妈，我说婚礼的事情办得怎么样了，谁知道当时我听到了一生中让我最失望的话：”你告诉她家，我们肯定不办，要不就离婚！“。然后又说了一大堆理由，反正我是记不清楚了。

当时我脑袋就懵了：”我该怎么办？这件事情我怎么和她说？”。就在这个时候她进来了，我把实际情况和她说了。我老婆当时没有什么反应，但是我知道她一定很痛苦，于是拉着我出去和岳父岳母解释。我记得大概就解释了十来分钟吧，并且商量了一下怎么办，最终是我家不办婚礼，但是她家会为她办一个。但是我感觉那段时间是如此的漫长，商量完之后虽然如释重负，但是脚已经占不住了。

初五晚上我们就要回北京，岳父岳母还来送我们上车。嫂子把我和她送上车，临走的时候和她说：”你最好和妈解释一下，不然她心里太难受了”。我问她解释什么，原来她告诉嫂子我的母亲是后妈。到了北京之后，她给岳母电话了。让我感动的时候，岳母表示理解并且还答应为愿意为我和她照顾孩子。岳母的善良越加映衬出了后妈的恶心。

然而事情还没有结束。我们到了北京之后，我把岳父岳母的商量结果告诉了爸妈。我妈还专门打电话给她，来解释为什么没有办婚礼，并且答应说：“要是没有给我办婚礼，也就不给我姐姐办婚礼。”，同时应承给我们一笔钱做旅行结婚。 也不给姐姐办婚礼，那我姐姐自然也生气，而他让却姐夫来责骂我。这里我真的很想说一句，我姐夫是一个非常啰嗦的人，并且非常喜欢纠缠，和他谈话就非常不舒服，说过很多让我匪夷所思的话，当然这些都只会存在我的脑子里面，没有必要在这里写出来影响这篇记叙，时间成熟时候我也自然会写。

*我被姐夫骂了一顿，她没有婚礼，我姐也没有婚礼。fair enough*

但是奇葩的事情发生了，就在10月份的时候，我接到妈的电话：“你看我没有给你办婚礼，心里不太舒服。9月份的时候你姐也领证了，趁着过年回家我给你们一起办一个婚礼吧。”。我礼貌地说：“不用了，我们已经结过婚了。” “可是要是你不来的话，你爸就非常尴尬啊，到时候别人还说我偏心。” 我就不明白，为什么这么伤心的事情还要拿出来说一次，本来这件事情让她够伤心了，就在她快逐渐遗忘的时候，还要重新提出来。 *如果提出来，为什么不给出另外一个选项：”我和我姐都不要婚礼，只要旅行结婚即可。“* 。你的行为，让我很难相信这是你嘴上说的公平，而你更多的解释，只会徒增我们对你的厌恶和反感，让我们感到作呕。我和我老婆商量了一下，她答应我去，但是我知道这已经是她忍耐的极限了。

就在1月底左右的时候，我陪她去做几次B超检查，发现胚胎发育不是很好，最后在2.4做了人工流产，而之前又有一次生化妊娠，对于她肯定是不能去了，而我也想在她身边照顾她，可是母亲还打电话说务必让我参加，不然让我爸尴尬。我知道我爱我爸，所以我陪她过完年，初一早上就坐上了飞机晚上才到抚州。初二参加了婚礼。

婚礼晚上回去了，我姐非常不高兴地问我为什么她没有来。我不愿意隐瞒她，我和她说了流产的事情。她似乎很关心我的情况，告诉我说她认识的一个老医生说要是留了两次产就比较难怀上了，你当时为什么要流产啊为什么不多观察一下，可能你的精子质量有什么问题你需要检查一下，不然生不出孩子我爸可能非常失望，章家就会断子绝孙。好客观的分析啊，可惜没有什么太多建设性的意见，而说话的方式和语气和姐夫有七分相似。谢谢你姐姐。我也实在是不想多说，道完谢之后就上楼睡觉了。

初三，也就是今天，我坐上了飞机，写下了这一切。我想告诉你们这就是事实，而这只是众多事实中的冰山一角，只是因为这件事情伤到我，她太深，我才愿意写出来，让大家知道。谢谢你们阅读完这篇记叙。

*另外提醒大家，事情最终的结果是，我姐夫和姐姐得到了一场完美的婚礼，她没有得到婚礼，而我被我姐夫骂了之后，得到的是一场没有妻子的婚礼。至于那旅行费用，现在我还没有拿到，也许按照大家的思维后妈养我这么多年就不要提这些钱了。也罢，其实我也不关心=D*

祝大家新年快乐，身体健康，万事如意！
