#+title: NNT文字合集

 所有人都知道预防比治疗更重要，但预防只得到很少的奖赏。我们只赞美那些在历史书中留下名字的人，而忽略了那些我们的书本没有提到的贡献者。我们人类不但肤浅（这一点可能还有救），还非常不公平。

 这些美好的形式有一个侧面影响，就是当它们占据你的思想时，你会把它们具体化，并开始忽视其他那些不那么美好的事物，那些更为混乱和不可捉摸的事物（对这一点的逐步阐述会贯穿本书始末）。

 过去，不论好坏，这些无法自力更生的稀有哲学家和思想家靠资助者过活。今天，抽象学科的学者靠别人的观点过活，而不接受外部检验，从而导致他们将研究变为孤芳自赏的病态结果。不管过去的机制有什么缺陷，最起码它保证了某种程度的有用性。）

 对待历史问题，人类的思想会犯三个毛病，我称之为三重迷雾。它们是： 1. 假想的理解，也就是在一个超出人们想象之外的复杂（或随机）的世界，人们都以为自己知道其中正在发生着什么。 2. 反省的偏差，也就是我们只能在事后评价事物，就像只能从后视镜里看东西（历史在历史书中比在经验现实中显得更加清晰和有条理）。 3. 对事实性信息价值的高估以及权威和饱学之士本身的缺陷，尤其是在他们进行分门别类的时候，也就是进行“柏拉图化”的时候。

 历史事件以一种扭曲的方式展现在我们面前。我们来考虑一下信息的性质：在一个历史事件发生之前存在无数个事实，其中只有相当少的一部分会在后来你对历史事件的理解中有帮助。因为你的记忆是有限而且是被过滤的，所以你会倾向于记住那些事后看来与事实相符的信息，除非你不会忘记任何事情，从而不得不生活在不断积累的原始信息的重负下。

 分类总会造成复杂性的降低，这是黑天鹅事件的发生器，也就是我在序言中定义的柏拉图化的表现。我们对周围世界的任何简化都可能产生爆炸性后果，因为它不考虑不确定性的来源，它使我们错误地理解世界的构成。

 根据我所有的经验，我没有遇到任何……值得一提的事故。我在整个海上生涯中只见过一次遇险的船只。我从未见过失事船只，从未处于失事的危险中，也从未陷入任何有可能演化为灾难的险境。 ——E·J·史密斯，泰坦尼克号船长，1907年

 正面的黑天鹅事件需要时间来显现它们的影响，而负面的黑天鹅事件发生得非常迅速——毁灭比缔造要容易和迅速得多。

 具有重大影响力和低发生概率的事件造成悲剧的主要原因是，对人们进行补偿所需的时间与人们决定不赌这一稀发事件不发生所需要的时间不一致。人们总有冲动去赌它不发生，或者同整个系统博弈，因为他们能够获得反映他们年度表现的奖金，而实际上他们只是在制造盈利的假象，这些盈利终有一天会还回去。实际上，资本主义的悲剧在于，由于回报的质量从过去数据是无法观察的，所以公司所有者，比如股东，能够搭乘制造回报和盈利假象的经理们的顺风车，但实际上承担着隐藏的风险。

 这一实验启发了许多类似实验。再举一例：受试者被要求说出为了发现一个人是否外向应该问哪些问题，据说这是另一类实验。结果发现，受试者提供的大部分问题都属于肯定回答能够支持假设的问题。

 实际上，我们的环境比我们（以及我们的本能）意识到的更为复杂。为什么？现代世界是极端斯坦，被不经常发生及很少发生的事件左右。它会在无数白天鹅之后抛出一只黑天鹅，因此我们要在比我们所习惯的更长的时间里暂不下结论。我在第三章说过，我们不可能遇到身高几百英里的人，于是我们的本能排除了这类事件。但图书销量或者社会事件的影响不会遵守这类限制。断定一名作家没有天分、市场不会崩盘、战争不会发生、一项计划无可挽回、一家公司不会破产、一家证券公司的证券分析师不是在吹牛或者邻居不会袭击我们，需要比1 000天长得多的时间。在遥远的过去，人类能够作出准确和迅速得多的推理。

 这种证明问题在我们的现代生活中很普遍，因为大部分冲突从根源上有如下的思维偏差：当阿拉伯人和以色列人看新闻时，他们会从同样的事件中看出不同的故事。同样地，对相同的数据，民主党与共和党会侧重看不同的部分，并且永远不会达成一致。一旦你的思维被某种世界观占据，你会习惯于只关注证明你正确的事例。矛盾的是，你拥有越多的信息，你就越认为自己正确。

 我们喜欢故事，喜欢总结，喜欢简化（也就是减少事情的影响因素）。我们在本书的这一部分首先要讨论的人类本性问题（即如上所述的问题），我称之为“叙述谬误”。（实际上是一种欺骗，但为了礼貌起见，我称之为谬误。）之所以出现这种谬误，是因为我们习惯于过度解释，偏好简洁的故事，而不是原始真相。它严重扭曲了我们对世界的思维反应，在稀有事件上尤为严重。

 叙述谬误指的是我们无法在不编造理由或者强加一种逻辑关系的情况下观察一系列事实。对事实的解释会与事实混在一起，使事实变得更容易被记住，更符合道理。这种倾向的坏处在于它使我们以为对事物有了更好的理解。

 传统智慧认为，记忆是像计算机磁盘一样的序列存储器。实际上，记忆是动态而非静态的，就像一张纸，新的文字（或同一段文字的新版本）被不断记录在这张纸上，这正是后出现信息的强大之处。记忆更多是一台自动进行动态更新的机器：你记住的是你最后一次回忆的事件，并且在毫无意识的情况下，每次重新回忆就会改写一次故事。

 在回顾过去的过程中，记忆对大脑在某个区域活动的加强作出反应，这种活动越强烈，记忆就越深刻。我们以为记忆是固定不变而且有联系的，但事实却远不是这样的。对于那些根据后来的信息而变得有道理的部分，我们记得更为清楚。

 答案是有两种稀有事件：1. 叙述中的黑天鹅现象，即那些现在被人们谈到并且很可能从电视上听到的黑天鹅现象；2. 无人提及的黑天鹅现象，因为它们不符合任何模式，在公共场合谈论它们会让你觉得羞愧，因为它们看上去不合理。我可以非常肯定地说，第一种黑天鹅现象的发生概率被高估，第二种被严重低估，这是完全符合人的心理的。

 人们假设情绪是系统1在指导并迫使我们迅速反应时使用的武器，它比我们的认知系统更有效地控制着我们的风险回避行为。实际上，研究情绪系统的神经生物学家发现，情绪对危险的反应比意识对危险的反应早得多，我们在意识到面前有一条蛇之前几毫秒就感到了恐惧，并开始作出反应。

 神经生物学家对系统1和系统2作了类似的区分，只不过他们是按解剖学区分的。按照不同部位，他们把大脑划分为大脑皮层以及快速反应脑边缘。大脑皮层是我们用来思考的部位，它使我们与其他动物区分开来；快速反应脑边缘是情绪中心，它是我们与其他哺乳动物都拥有的。

 而且，我们以为，如果两个变量是具有因果关系的，那么对一个变量的稳定投入总会对另一个变量的产出产生影响。我们的情感功能是为线性因果关系设计的。例如，如果你每天学习，你会预期学到与你的学习行为成比例的东西。如果你感到什么进展也没有，你的情感就会使你丧失士气。但在现实中，我们很少获得令人满意的、线性的正面进展。你可能花一年思考一个问题，却什么收获也没有。然而，只要你不对这种徒劳无功的状况感到失望而放弃，某种成果就会突然冒出来。

 我们喜欢情感和极为显而易见的东西，这影响了我们评价英雄的方式。我们的意识中几乎没有空间留给那些没有可见成就的英雄，也就是那些关心过程而非结果的英雄。

 确实，这让你不去想生活的琐碎——咖啡太烫还是太凉，服务员太迟钝还是太机灵，食物太辣还是不够辣，酒店房间价格太高而且与广告照片不一致——所有这些问题都消失了，因为你在想更大、更好的东西。但这并不意味着从现实中逃离的人能够避免其他痛苦，比如受到轻蔑。黑天鹅事件的等待者经常因为努力而感到或被迫感到羞耻。“你辜负了那些对你有高度期望的人。”他们听到这样的话，更增加了负罪感。奖励向少数人集中的问题不在于使人们得不到奖励，而在于它造成的等级问题、体面的丧失和靠近底层的羞耻感。

 对叶夫根尼娅而言，一个人可能只喜欢一本书，最多几本，超过这个数目就是滥读了。把书当成商品的人不可能真正喜欢书，就像交友过多的人对友情的理解是肤浅的一样。一本你喜欢的小说就像一个朋友，你读了再读，对它越来越了解。就像对待朋友一样，你按照它本来的样子接受它，而不会评判它。

 学派使一个有着非凡思想而从中获益的希望很渺茫的人能够找到同伴，并为他们创造一个与外界隔绝的小环境。这群人可以共同自我放逐，这胜过被孤身放逐。 如果你从事一项依赖于黑天鹅事件的职业，加入一个群体是更好的选择。

 在尼罗的圈子里，尼罗是本性上最不适合这种策略的。他的大脑与身体严重不协调，使他处于一种持续的矛盾中。他的身体出了问题，由于整天都面临这种小而持续的损失——一种类似中国古代水刑的折磨，他的神经生物系统受到长期影响，从而导致身体脆弱。尼罗发现，这些小损失进入大脑的情感部分，绕过了更为高级的大脑组织，缓慢地影响他的海马状突起，侵蚀着他的记忆力。海马状突起是掌管记忆的组织，是大脑最敏感的部分，据说也正是这一部分会吸收反复遭到的打击造成的损害，比如由于每天持续少量的不良情绪造成的长期压力。长期压力会对海马状突起造成严重损伤，发生不可逆转的萎缩。与人们的普遍看法相反，那些看上去无害的紧张性刺激并不会使你变得坚强，反而会使你部分丧失自我。

 人们会相信你说的话，只要你不表现出一丝动摇。和动物一样，他们能够在你说出口之前察觉你自信中最微小的裂缝。你得用尽量自然的方式使用这种伎俩。在你表现得极为礼貌和友好的时候，传递出自信要容易得多。你可以在人们毫无察觉的情况下控制他们。尼罗认识到，商务人士的问题在于，如果你表现得像个失败者，他们就把你当失败者，标准由你自己决定。好与坏没有绝对的标准。关键不在于你对人们说什么，而在于你怎样说。

 我的存在是低概率事件的重大结果，而我经常忘记这一点。

 我再次强调，我们是寻找原因的动物，习惯于认为一切事情都有确定的原因，并且把最明显的那一个当做最终解释。但实际上可能并没有可见的原因，相反，很多情况下什么也没有，甚至没有任何可供选择的原因。沉默的证据掩盖了这一事实。每当涉及我们的幸存时，原因就被严重削弱了。幸存的条件消灭了所有可能的解释。亚里士多德的“因为”不是为了把两件事联系起来（如我们在第六章看到的），而是为了满足我们习惯寻找原因的潜藏弱点。

 只要涉及你的幸存，不要忙着寻找因果。我们可能根本无法了解我们从这种疾病中幸存下来的主要原因：我们活下来了，因为卡萨诺瓦式的温馨情境出现了，如果这看上去太难以理解，那是因为我们被因果观念洗脑了，而且我们以为说“因为”比接受随机性看上去更聪明。

 我之前说过，我们的认知系统对于不出现在我们眼前或不引起我们情感注意的事物可能没有反应。我们天生肤浅，只注意我们看到的东西，不注意没给我们留下生动印象的东西。我们向沉默的证据发动了双重战争。潜意识的推理机制（确实存在这样的机制）忽视沉默的证据，即使我们知道需要考虑它。不进入视线则不进入大脑：我们对抽象的东西怀有天性上的甚至行动上的蔑视。

 我所知道的不冒充内行的最好的金融书《损失100万美元教会我什么》（What I Learned Losing a Million Dollars），作者是D·保罗（D. Paul）和B·莫伊尼翰（B. Moynihan）。这两位作者不得不自己出版了这本书。

 可惜，现存的人类天性不愿理解抽象事物，我们需要具体背景。随机性和不确定性是抽象事物。我们尊重发生的事，忽视本来可能发生的事。也就是说，我们天生肤浅，却浑然不知。这不是心理学问题，它来自信息的主要特性。人们很难看到月亮的阴面，照亮它是花费能量的。同样，照亮没有被看到的事物既费力又劳神。

 对一个信息不完整或信息缺失的不具随机性的变量（比如凯瑟琳二世的情人数量）的猜测，与对一个随机变量（比如明天的失业率或明年的股票市场情况）的预测是没有区别的。从这个意义上讲，猜测（我不知道但别人可能知道的事情）与预测（还没有发生的事情）是同一回事。

 当你受雇于人，因此依赖于他人的评价时，显得忙碌能帮助你在结果不确定的环境中邀功。显得忙碌能够加强人们对结果与你的作用之间的因果关系的判断。对于那些鼓吹自己的“存在”与“领导”在公司业绩中的作用的大公司CEO们更是如此。我没有听说过谁研究他们用于谈话和接受琐碎信息的时间有多大有效性，也没有几个作者有勇气质问CEO在公司成功中究竟有多大作用。

 把一张模糊的消火栓图片——模糊到使他们无法认出图片上是什么——给两组人看。对其中一组，分10次逐步提高图片的清晰度，对另一组分5次提高清晰度。在某个使两组人看到相同清晰度图片的时候停下来，请他们说出看到的是什么。经过较少中间步骤的那一组可能更快地辨认出消火栓。这意味着什么？你提供的信息越多，他们就会形成越多假设，他们的结论就越糟糕。他们看到了更多的随机噪点并将其当成了信息。

 有些学科的确存在真正的专家。我们考虑下面这几个问题：你愿意让某报纸的科学记者还是有执照的脑外科医生为你做脑部手术？另一方面，你愿意听某个“著名”学院（比如沃顿商学院）毕业的金融博士还是某报纸的商业版作家对经济作出预测？虽然对第一个问题的回答非常明显，但对第二个问题不是。我们已经认识了“技术”和“知识”的区别。

 是专家的专家：牲畜检验员、宇航员、飞机试驾员、土壤检验员、国际象棋大师、物理学家、数学家（研究数学问题而非经验问题）、会计师、谷物检验员、图像分析员、保险分析师（研究钟形曲线统计问题的）。 不是专家的专家：证券经纪商、临床心理医生、精神病医生、大学招生负责人、法官、顾问、人事官员、情报分析师（虽然花了那么多钱，但美国中央情报局的历史表现很令人遗憾）。我还要加上我自己分析文献的结果：经济学家、金融预测者、金融学教授、政治科学家、“风险专家”、国际清算银行员工、国际金融工程师协会的傲慢成员以及个人金融咨询师。

 很简单，因变化而需要知识的事物，通常是没有专家的，而不变的事物似乎会有专家。也就是说，与未来有关，并且其研究是基于不可重复的过去的行业则通常没有专家（天气预测以及从事短期物理活动，而非社会经济活动的行业除外）。我并不是说任何从事未来预测的人都不能提供有价值的信息（如我之前指出的，报纸能够非常准确地预测剧院开门的时间），而是说那些无法提供具有可见价值信息的人通常从事预测行业。

 我已经提过结婚者对未来的不现实预期。想一想有多少家庭对未来进行筛选性假设，他们把自己锁在牢固的房产中，以为会在那里生活一辈子，而不知道人们过稳定生活的记录很糟糕。他们难道没有看见那些衣冠楚楚的房地产经纪人开着漂亮的德国轿车到处转吗？我们是极为漂泊不定的，比我们计划的不稳定得多，而且不得不如此。想一想有多少突然失去工作的人料到了这一点，即使只提前几天，或者想一想有多少瘾君子在一开始是打算长期吸毒的。

 为了开会，经理们满世界飞：巴塞罗那、香港等等。他们千里迢迢只为了一大堆空话。毫无疑问，他们通常没法睡觉。当一名管理者不需要非常发达的头脑，而是需要同时拥有人格魅力、忍受无聊的能力和草草执行匆匆制定的时间表的能力。除了这些“任务”之外，他们还有出席歌剧表演的“职责”。

 亨利·彭加莱虽然名声显赫，但通常被认为是价值被低估的科学思想家，因为他的一些思想过了近一个世纪才得到人们的赞赏。他或许是最后一位伟大的思想数学家（或者数学思想家）。每次我看到印有现代偶像爱因斯坦头像的T恤衫时，我就无法不想到彭加莱。爱因斯坦值得我们尊敬，但他掩盖了别人应得的许多尊敬。我们的意识空间太狭小了，这也是一种赢家通吃。

 彭加莱在30多岁时成为多产的论文作者，他似乎在赶时间。他58岁时便英年早逝。他如此匆忙，即使发现了文字中的打字和语法错误，也懒得改正，因为他认为改错是浪费时间。人类再也没有产生这样的天才，或者说再也不让天才以他们自己的方式写作。

 彭加莱的理论很简单：在预测未来的过程中，你所模型化的过程需要越来越精确，因为你的错误率会迅速上升。而仅仅达到近似的精确是不行的，因为你的预测会突然失效，最终需要对过去进行无穷精确的解释。

 20世纪60年代，麻省理工学院的气象学家爱德华·洛伦茨独立地再次发现了彭加莱的理论，同样是出于偶然。他正在建立一个天气变化模型，并对一个天气系统几天后的情况进行了模拟预测。后来他使用同一模型进行重复模拟，而且他认为自己输入的是相同的参数，但得到的结果却大相径庭。他起初以为差异来自计算机漏洞或计算错误。当时的计算机较为笨重和迟缓，与我们今天的计算机完全不一样，所以使用者受到时间的严重约束。洛伦茨后来意识到，计算结果的巨大差异不是来自计算错误，而是来自输入参数的小小的四舍五入。这就是著名的蝴蝶效应，一只在印度震动翅膀的蝴蝶能够引起两年之后纽约的飓风。洛伦茨的发现引起了人们对混沌理论的兴趣。

 在正统经济学中，理性成了一件紧身衣。柏拉图化的经济学家忽视了一个事实，那就是人们可能喜欢别的东西胜过喜欢最大化他们的经济利益。这导致一些数学技巧的诞生，比如“最大化”或“最优化”，保罗·萨缪尔森的大部分工作正是基于此。最优化是指为一个经济问题找到数学上的最优解决方案。例如，你对不同股票的“最优”购买数量是多少？它涉及复杂的数学，因此对非数学学者设立了进入障碍。我不是第一个提出这种最优化阻碍了社会科学的人，它把社会科学从一个思考和沉思的学科降低为一种“精确的科学”。“精确的科学”指的是那些假装热爱物理学或患有物理嫉妒病的人从事的二流工程问题。换句话说，它是智力骗局。

 我们在总体上高估了不幸事件的影响持续的时间。你以为你的财富或当前的地位遭受的损失将是灾难性的，但你很可能错了。更可能的情况是，你将能适应任何事情，正如你面对过去的不幸时所做的那样。你可能会感到痛苦，但不会像你预期的那样糟糕。这种错误预测可能存在一种目的：刺激我们采取重要的行为（比如购买新车或努力致富），防止我们冒不必要的风险。这是一个更为一般化的问题的一部分：人类喜欢不时地自我欺骗。根据特里弗斯的自欺理论，这会使我们以更有利的方式走向未来。但自欺在其自然领域之外不是一种值得期待的特点。它防止我们冒不必要的风险，但我们在第六章看到，它无法为我们阻挡现代风险的洪流。我们不害怕这些风险，因为我们根本没有觉察到，比如投资风险、环境危机和长期安全。

 不从事随机性工作的人不会明白其复杂性。通常，在哲学家（有时候是数学家）听我谈论不确定性和随机性的会议上，他们会向我提出最不相关的问题，比如我所说的随机性是“真正的随机性”，还是伪装为随机性的“确定性混沌”。真正的随机系统确实是随机的，而且不存在可预测的特性。混沌系统有完全可测的特性，但人们很难找到，所以我对他们的回答是双重的。 1. 这两者之间不存在重要差别，因为我们永远也区分不出来，差别是数学上的，不是现实中的。如果我看到一名怀孕的女性，她的孩子的性别对我来说是纯粹的随机问题（两种性别各50%的可能），但对她的医生不是，他可能已经为她做过超声波检查。 2. 一个人谈论这一区别，这表明他从未在不确定性的条件下做过有意义的决策，这正是他没有认识到在现实中不可能区分的原因。 随机性最终只是反知识。世界隐藏在迷雾中，而表象在愚弄我们。

 历史就像博物馆，人们可以进去看过去的收藏，感受昔日的魅力。它是一面奇妙的镜子，你可以看见我们的自我叙述。你甚至可以利用DNA分析追踪过去。我很喜欢文学史。古代历史满足我建立自我叙述、自我认同和与我（复杂的）东地中海的根源建立联系的愿望。我喜欢古老的、不那么精确的书胜过喜欢现代书籍。在

 历史能使我们陶醉地以为了解了过去，满足了我们讲故事的愿望（确实），只不过是非常有害的故事。人们应该极为谨慎地学习。如果没有谨慎的态度，历史显然不是一个理论化和得出一般知识的地方，也不会对未来有所帮助。我们能从历史中得到负面认知，这一点是无价的，但同时我们也得到了太多知识的假象。

 经验主义的医生对待归纳问题的方法是了解历史，而不是将它理论化。学会阅读历史，吸取所有可能的知识，不要对奇闻逸事皱眉，也不要建立任何因果链条，不要试图过多地求方程，但如果你这样做了，也不要大张旗鼓地提出科学观点。请记住，经验怀疑主义者尊重习惯：他们把它当做默认状态，行为的基础，但仅此而已。他们称这种对待过去的明确方法为结语主义。[40]

 对小问题的建议就是：保持人性！在你自己的问题中，接受人类存在认知自大这一事实。不要为此羞愧。不要试图总是不作判断，生活中离不开观点。不要试图避免预测，是的，在批判了预测之后，我不要求你不再犯傻，但要在正确的地方犯傻。[42] 你应该避免的是对大范围的有害预测的依赖，仅此而已。避免那些可能损害你的未来的大主题：在小事上当傻瓜，而不是在大事上。不要听经济预测者或社会科学预测者的话（他们只是演员），但要作你自己的预测。尽一切努力，确定下一次野餐的情况，但不要相信政府对2040年社会保障情况的预测。 学会根据观点可能造成的损害而不是好听的程度来辨别它们。

 我努力在此把我作为一名证券交易者所使用的“杠铃”策略推广到真实生活中。如果你知道容易犯预测错误，并且承认由于有黑天鹅事件的影响，大部分“风险管理方法”是有缺陷的，那么你的策略应该极度保守或极度冒险，而不是一般保守或一般冒险。

 这与“杠铃”策略是吻合的，在将正面黑天鹅事件的影响最大化的同时，保持对负面黑天鹅事件的警惕。要从正面黑天鹅事件中获益，你不需要对不确定性有任何精确的理解。有一点我很难解释，那就是在你只有非常有限的损失的时候，你必须尽可能主动出击，大胆投机，甚至“失去理智”。

 不要寻找精确和局部的东西。简而言之，不要狭隘。提出“机会青睐有准备的人”的伟大微生物学家巴斯德懂得，不要在每天早上寻找某种特定的东西，而要努力工作，并让意外进入你的生活。正如另一位伟大的思想家优吉·贝拉所说：“假如你不知道往何处去，请一定小心，因为你可能到不了那里。”

 所有这些建议有一个共同点：不对称性。请把你自己放入一个好结果比坏结果大得多的条件下。 实际上，不对称结果是本书的核心思想：我永远不可能知道未知，因为从定义上讲，它是未知的。但是，我总是可以猜测它会怎样影响我，并且我应该基于这一点做出自己的决策。

 有一个更微妙的认知问题。请记住，在正面黑天鹅行业，过去没有揭示的东西几乎一定对你有利。当你回顾生物科技行业的收益时，你没有看超级火暴的记录，但由于它们有可能发现治愈癌症（或者头痛、秃顶、缺乏幽默感等）的方法，这个行业在很小的可能性上会实现巨大的销量，比人们预料的大得多。另一方面，考虑一下负面黑天鹅行业。你看到的过去的记录很可能高估了相关特征。回忆一下1982年美国银行的纷纷破产：它们在天真的观察者眼中比看上去更赚钱。保险公司有两类：属于平均斯坦的常规多样化保险公司（比如人寿保险）和更危险的、易受黑天鹅事件影响的保险公司，它们通常会进行再保险。根据数据，再保险公司的再保险业务在过去20年里是赔钱的，但与银行家不同的是，它们进行了足够的反省，知道情况本可能更糟，因为过去20年里没有发生重大灾难，而100年里只需要一次灾难就能让这些公司破产。许多对保险进行“估值”的金融学者似乎都忽略了这一点。

 一切都是暂时的。运气缔造和毁灭了迦太基，运气缔造和毁灭了罗马。 我已说过，随机性是不好的，但并非总是如此。运气甚至比智慧更公平。如果人们严格根据能力获得报酬，有可能仍然不公平，因为人们无法选择自己的能力。随机性能够对社会进行重新洗牌，把那些大人物拉下马。

 记住：高斯钟形曲线都受到一种阻力，使偏离平均值的概率下降得越来越快，突破性分布或者曼德尔布罗特分布则不受这种限制。这基本上就是你需要知道的。[53]

 模型的构想者不得不浪费时间写关于哪些模型可以产生突破性分布的理论，似乎他们必须为此道歉一样。理论！我对这一点有一个认知上的问题，我不明白为什么我们要为世界不能满足某个理想模型找理由，而这个模型只不过是得到了对现实视而不见的人的追捧。

 我不知道的是，1987年并不是高斯方法第一次显露出欺骗性。曼德尔布罗特在1960年左右向经济学界提出突破性分布的观点，向他们展示高斯曲线不能描述当时的市场价格。但在兴奋之后，他们意识到他们不得不重新学习。当时一位具有影响力的经济学家、已故的保罗·库特纳（Paul Cootner）写道：“就像之前的丘吉尔首相一样，曼德尔布罗特不是向我们许诺乌托邦，而是向我们许诺血、汗、苦役和眼泪。假如他是正确的，我们几乎全部的统计工具都是过时或毫无意义的。”我要对库特纳的话作两点更正。首先，我要把“几乎全部”替换为“全部”。其次，我不同意血和汗的说法。我认为曼德尔布罗特的随机理论比传统统计学易懂得多。假如你是新入行的，就不要依赖老的理论工具，也不要对确定性有很高的期望。

 确实，该奖曾颁给一些有价值的思想家，比如经验心理学家丹尼·卡尼曼和思想经济学家弗里德里希·哈耶克。但评奖委员会已经习惯于把诺贝尔奖发给那些用伪科学和伪数学为经济学“带来严谨”的人。在股市崩盘之后，他们授奖给两名理论学家哈里·马克威茨和威廉·夏普，他们以高斯方法为基础，建立了漂亮的柏拉图化模型，对所谓的现代投资组合理论作出贡献。很简单，假如你去掉他们的高斯假设，把价格当做突破性变量，你就只剩下吹牛。诺贝尔委员会可能验证过夏普和马克威茨的模型，其作用就像网上出售的江湖偏方，但斯德哥尔摩似乎没人考虑这一点。委员会也没有征求我们这些实践者的意见；相反，它依赖于某种学术审查，而在有些学科，这种审查可能已经腐败到骨子里了。这次颁奖之后，我作了一个预测：“在这两个人能够获得诺贝尔奖的世界里，任何事都有可能发生。任何人都可能成为总统。”

 事情在1997年变得更加糟糕。瑞典学院再次将诺贝尔奖发给以高斯方法为基础的迈伦·斯科尔斯（Myron Scholes）和罗伯特·C·默顿，他们改进了一个老的数学公式，使它与现有的高斯一般金融均衡理论兼容，于是得到了经济学界的认可。这个公式现在“能用了”。它有许多被人们遗忘的先行研究者，包括数学家兼赌徒爱德华·索普（Edward Thorp）。他撰写了畅销书《击败庄家》（Beat the Dealer），告诉人们如何在玩21点时赢钱，但人们却认为是斯科尔斯和默顿发明了这种方法，实际上他们只是使它被学术界接受而已。那个公式就是我的谋生之道。交易员比学术界更知道它是怎么回事，因为他们日夜担心风险，只不过他们很少有人能够用术语表达想法，所以我感觉我代表的是他们。斯科尔斯和默顿使这个公式变得依赖高斯分布，而他们的“先驱者”没有对它作过这类限制。[59]

 小罗伯特·默顿和迈伦·斯科尔斯是一家大型投机性证券公司的创始合伙人，该公司就是长期资本管理公司，我在第四章提到过。它聚集了学术界的顶尖人才，他们被称为精英。投资组合理论是他们进行风险管理的灵感来源，他们会进行精密的“计算”。他们成功地把游戏谬误放大到整个金融业。 然后，1998年夏天，由俄罗斯金融危机引发的一系列大事件发生了，这些事件在他们的模型之外。这是一只黑天鹅。长期资本管理公司破产，并几乎把整个金融系统拖下水，它的影响太大了。由于他们的模型排除了大离差的可能性，所以他们把自己置于可怕的风险之下。默顿和斯科尔斯的思想以及现代投资组合理论开始动摇了。损失太惨重了，惨重到我们无法再忽略知识的闹剧。我和许多朋友以为投资组合理论家会面临烟草公司的命运：他们害得人们损失了积蓄，并很快为自己的高斯方法造成的后果负责。 但这并没有发生。 相反，商学院的MBA们继续学习投资组合理论。期权定价公式继续被冠以布莱克-斯科尔斯-默顿的名字，而不是其真正发现者的名字，如路易斯·巴切里亚（Louis Bachelier）、爱德华·索普等。

 我选出默顿是因为我发现他非常突出地体现了学术愚昧。我从他寄给我的一封7页的愤怒而带有威胁色彩的信中发现了他的弱点，这封信给我的印象是他对我们如何交易期权并不熟悉，而期权正是他的研究对象。他似乎以为交易员依赖于“严格”的经济理论，就好像鸟必须学习（糟糕的）工程学才能飞一样。

 最终存在一个小小的决策法则：当我能够受到正面黑天鹅事件影响时，我会非常冒险，这时失败只有很小的影响；当我有可能受到负面黑天鹅事件的袭击时，我会非常保守。当某个模型中的错误对我有好处时，我会非常冒险；当错误对我有害时，我会非常多疑。这可能并不十分有趣，但这正是别人没有做到的。例如，在金融业，人们使用脆弱的理论来管理风险，把狂野的思想置于“理性”的审视之下。

 藐视命运。我一直教我自己拒绝追赶时间表。这可能只是一条很小的建议，但它印在了我的脑海里。从拒绝追赶列车中，我体会到“优雅”的真正价值和行为中的美学，一种控制我的时间、行程和生活的感觉。错过列车，只有在你追赶它时才是痛苦的！同样，不能达到别人对你期望的成功，只有在它也是你所追求的东西时才是痛苦的。 你凌驾于争斗与名利思想之上，而不是之外，只要你愿意这样选择。 只要是你的决定，放弃一份高薪职位带来的回报会超过金钱带给你的效用（这似乎很疯狂，但我试过并且确实如此）。这是向命运说“随你怎么样”的第一步。如果你确定了自己的标准，你对自己的生活会有大得多的控制。 大自然给了我们一些防御机制：如伊索寓言中写到的一样，其中之一就是把我们不能（或没有）吃到的葡萄想成酸的，但如果你更加主动地在之前就鄙视并拒绝葡萄，你的满足感会更大。主动出击，主动辞职，只要你有勇气。

 年以来，我经历了诸多变化，其中大部分的变化都是令人鼓舞振奋的。像聚会一样，一本书会使你交到意想不到的好运，并且会使你有机会得到更多的聚会邀请。在那段艰难的日子里，别人都把我讽刺为巴黎的商人（极端粗俗的代表）、伦敦的哲学家（极端学究的代表）、纽约的预言家（当时我曾给出了错误的预言）以及耶路撒冷的经济学家（极端现实主义的代表）。而现在，别人都把我恭奉为以色列的预言家（这需要我付出很多的努力）、法国的哲学家、伦敦的经济学家和纽约的商人（商人在纽约备受尊重），这又令我受用不起。

 冗余的对立面是天真的优化。我会告诉每个人不要去参加一些所谓正统的经济课，并告诉他们，经济会使我们垮掉。（我们将会看到，我们有证据证明经济会搞垮我们。但是，正如我在书中所提到的，我们并不需要这些证据，我们需要的是看到科学的缺乏严密和道德的缺失。）之所以如此，是因为这在很大程度上依靠天真优化的观念。这一观念由保罗·萨缪尔森进行了数学化处理（拙劣的），这一数学行为为错误倾向社会的建立作出了贡献。经济学家会认为，两个肺与两个肾的效率并不高，他们会考虑这些器官的物流成本。这种优化最终会伤害到你。同时，如果我们的大自然由经济学家来控制，那么我们便会被省去一个肾，因为我们并不是任何时候都需要两个肾。更为“有效”的做法是我们将自己的肾脏卖掉，而仅在需要的时候使用公用肾。并且，你可以在夜间出租你的眼睛，因为你在夜间做梦时并不需要它们。

 正因为如此，我发现，目前关于全球化的观点（比如记者托马斯·弗里德曼所推崇的观点）过于天真，会对社会造成极大的危害。全球化看上去会带来高效率，然而运行杠杆不同部分之间的交互作用会引起某个点的裂隙，从而影响整个体系，结果就像是许多脑细胞同时崩溃而引发大脑癫痫发作。而我们知道，运作机制复杂的大脑体系并没有达到“全球化”的程度。

 大家都想当然地认为，规模大了便会更稳定，殊不知公司规模的扩大只是迎合了华尔街分析师们的胃口。华尔街的分析师们（MBA）会敦促公司出售多余的那只肾脏，冒着风险提高公司的每股收益率并提高公司的盈亏底线。然而这样做，最终只会导致公司的破产。

 后来，我便致力于极端斯坦生活方式的研究：在令人激动的城市环境中漫步与思考，偶尔小跑上一段，跑的时候我会想象自己正手握棍棒追赶银匪[67]罗伯特·鲁宾，试图将他抓住之后绳之以法。我会来到任意某处举重场所，进行一次彻底的随机测试——一般是在酒店里。像灰天鹅事件一样，这些虽非常罕见，但在一天的半饥饿状态过后，却使我精疲力竭。然后，我会在数周时间里无所事事，整日在咖啡店里度日。甚至连测试的时间都是随意的，多数情况下都很短，不超过15分钟。我尽量使我的测试充满乐趣。我对体育馆的员工彬彬有礼，尽管他们认为我的测试“不可理喻”。同时，我还使自己处于一种冷热变化的状态，偶尔不穿外套便在大冷天外出。由于环球旅行和飞行时差的原因，我经常会长时间不睡之后大睡一觉。每当我来到美食之都（比如意大利），我便会造访知名餐馆放开肚皮大吃一通，令那些肥头大耳的吃客都自愧不如。然后，我便会连续几顿不吃饭，倒也没什么事。在度过了两年半时间看上去“不健康”的生活方式之后，我却发现自己的诸多身体指标发生了显著的改善——多余脂肪消失，血压恢复正常，思维更加清楚敏捷等。

 然而，这些有关生活方式的观点并不仅来自自我实验或者某一种庸俗的理论。所有结论都来自有真凭实据的调查研究。饥饿（或者短暂的体能欠缺）会增强人的体质和免疫系统，并会激活大脑细胞，甚至会削弱癌细胞和预防糖尿病的发生。现在的思维方式（某些程度上类似于经济学）来自与实验法研究的同步。我能够通过最少的努力重新创造出饥饿者生活方式的90%的利益，而不受现代生活方式的约束（我对大自然的景色已经产生了厌倦心理，我宁愿选择在威尼斯的犹太人地区散步，也不愿意在旅游胜地波拉波拉岛游玩）。[

 没有知识，我们不能做任何事情，除非我们知道知识的止境和运用知识的代价。后启蒙运动科学及其后来者明星科学，非常幸运地大大促进了线性物理学、化学和工程学的发展。然而，在某种程度上，我们需要放弃精密，转而将视线投向长期不被重视的事情上：能够展示出现代知识和现代方法所不能展示的地图；对于一般科学医源性的严谨研究，科学可以引起何种伤害（或者说科学已经带来了哪些伤害）。我认为，这是最值得探寻的一点。

 过于专门化也不是一件好事。可以想象，一旦你完全丢掉你的工作，你会去做什么？面对金融危机，相对于单一的华尔街分析师（预测型的），在夜间跳肚皮舞作为第二职业的华尔街分析师受到的影响会更小。

 在自然状态下，我们永远不会重复同样的事情。在受到禁锢的状态下（办公室，健身房，上下班路上，体育运动），生活只不过是重复性的疲劳损伤而已，没有任何随机性可言。 把别人的缺乏常识当作借口，这本身就是缺乏常识的表现。

 冰与水之间并没有中间状态，但是生与死之间确实有中间状态：雇佣状态。

 当我们打算做一件我们潜意识里知道注定要失败的事情时，就会征询别人的建议，这样就可以把失败怪罪到别人头上。

 神圣的东西都是不求回报的，凡俗的东西都是求回报的。[2]

 长时间接触传媒的经历让我发现，没有哪种传媒不是在（笨拙地）试图卖给你什么东西。让我信任的就只有书籍了。拥有一本书并不会彰显出人性的弱点，不会迎合我们的表现欲，让我们显得高人一等；书籍之外的商业运作才会腐蚀我们。

 成功的反义词不是失败，而是把成功人士的名字时时挂在嘴边炫耀。 现代人需要弄清楚，“富有”和“变得富有”在数学层面、个人层面、社会层面和伦理层面上不是一回事。

 “财富”是一个没有意义的词，因为它没法准确衡量；不如换用“缺乏财富”这个词，意思是在任一时刻，你所拥有的和你想要拥有的之间的差距。

 罗马时代的奴隶跟今天的雇员之间唯一的不同，就是奴隶用不着奉承主人。[1]

 不要太过大声地抱怨别人对你的不公，你或许会提醒那些缺乏想象力的敌人该怎么做。

 在绝大多数争论中，人们似乎都在试图说服对方，但他们其实最多只能说服自己。

 世上有两类人：追求胜利的人和追求在争论中得胜的人。他们从来不是同一拨人。

 数学之于知识，好比义肢之于真正的肢体；有些人截肢就是为了能装上义肢。

 社会媒体严重反社会，健康食品非常不健康，知识工作者极度缺乏知识，社会科学根本就不是科学。

 二流思维方式的失败之处是：他告诉你一个秘密，想让你保守这个秘密，而他的行为刚好证明了他自己都没法保守它。

 让人上瘾的东西里，害处最大的三种是海洛因、碳水化合物和月薪。

 科技可以让愚人的生活在所有方面发生退化（甚至陷入危机），同时又让他相信自己的生活正在变得“更有效率”。

 我们是猎人；我们只有在随机应变的时候才真正活着；没有日程安排，只有来自周围环境的新鲜刺激。

 绝大多数人开始腐化的时候，是离开自由、热闹、纯净的校园，开始孤单地陷于职业生涯和小家庭中的时候。

 可以转移的技能：街头斗殴，荒野徒步，勾引异性，广博的涉猎。无法转移的技能：学习，运动，体育，实验室——总之是那些更加简单有序的东西。

 只有当你的谈话（或者文字）没法很容易地用别的谈话的片断重新构建出来时，你才算是真正地存在着。

 英国有时也会出现地中海式的天气，但英国人还是要到西班牙去度假，因为他们的自由时间并不能自由安排。

 真实生活和现代生活的区别，跟谈话和两个人分别背诵台词的区别一样大。

 他们所谓的哲学，我称之为文学；他们所谓的文学，我称之为新闻；他们所谓的新闻，我称之为闲话；他们所谓的闲话，我（宽容地）称之为窥淫狂行为。 作家让人记住的是他们最好的作品，政治家让人记住的是他们最糟糕的错误，商人几乎从来不会让人记住。

 你得随时提醒自己，魅力存在于没有说出来、没有写下来、没有展示出来的东西中。把握沉默需要境界。

 科学的过程是无聊的，结果是令人激动的；哲学的过程是令人激动的，结果是无聊的；文学的过程和结果都是令人激动的；经济学的过程和结果都是无聊的。

 像诗人和艺术家一样，官僚是天生的，不是后天形成的；正常人需要付出极大的努力，才能把注意力保持在如此无聊的任务上。

 一般人会在不同的故事（以及情境）中寻找相同点，高人会在相似的故事（以及情境）中寻找不同点。

 傻瓜把特例当成惯例，书呆子把惯例当成特例，有些人两样都犯，聪明人两样都不犯。

 你想做你自己，表现出独特性；群体（学校，规矩，工作，科技）则想让你做大众的一分子，完全没有自己的特点，哪怕得为此把你阉掉。

 信息时代的灾难在于，信息的害处远比它的益处增长得快。

 要衡量一个人的价值，考虑一下你第一次见到他时的印象，跟最近一次见到他时的印象有多大的差别。

 弱者行动是为了满足自己的需求，强者行动是为了履行自己的义务。

 尽量别把那些别无选择的人称为英雄。

 要衡量你对名誉损失的抵抗力，想想你收到一名记者的邮件时会有什么情绪反应（害怕，开心，无聊）。

 当仇恨对象改变时，原先的仇恨就结束了；一般人没法同时拥有多于一个的敌人。正因为如此，由时而结成同盟、时而互相征战的城邦组成的系统才是强壮的系统。

 当你在肉体上战胜了一个人时，你得到了锻炼，缓解了压力；当你在网上攻击他时，只不过是在损害你自己。

 关于我们思维的场地依赖，我能举出的最好的例子是我前段时间去巴黎的时候，午餐在法式餐厅吃，我的朋友们吃了鲑鱼肉，把鱼皮扔掉；晚餐在日式寿司餐厅吃，同样是这帮朋友，吃了鲑鱼皮，把鱼肉扔掉。

 知识的问题在于，由观鸟者撰写的关于鸟类的书籍，远比由鸟类撰写的关于鸟类的书籍和由鸟类撰写的关于观鸟者的书籍多得多。

 天才的想象力远远超过他的学问，书呆子的学问远远超过他的想象力。

 对古人来说，预言历史事件是对（诸）神的亵渎；对我来说，这是对人类的亵渎——对有些人来说，是对科学的亵渎。

 让我们脆弱的是，组织机构不可能拥有跟个人同样的美德（荣誉，诚实，勇敢，忠诚，坚韧）。

 在莫斯科的会场上，我眼看着经济学家埃德蒙·菲尔普斯因为写的东西没有人看，提出的理论没有人应用，发表的演讲没有人听得懂，而获得了“诺贝尔奖”。

 记者跟格言家的思路正好相反：我提出“你需要技能才能赢得宝马车，需要技能和魔鬼般的运气才能变成沃伦·巴菲特”。记者们对此的总结是，“塔勒布认为巴菲特不具有任何技能”。

 好奇的人喜欢科学，敏感而有天赋的人喜欢艺术，实干的人喜欢商业，剩下的人只好当经济学家了。

 普通人更容易为说出的话而不是沉默后悔，比较杰出的人更容易为沉默而不是说出的话后悔，伟大者没什么可后悔的。

 无论如何，尽量避免说话——威胁，抱怨，解释，叙述，重复，恳求，试图赢得争论的胜利——尽量避免说话！

 最关注你的人是那些恨你的人。朋友、追求者和伴侣都不可能对你如此好奇。

 思维可以作为一种很好的自我欺骗工具——它生来就不适合处理复杂性和非线性的不确定性。跟常见的观念正好相反，更多的信息意味着更多的错觉；由于现代化和信息时代的到来，我们发现虚假模式的速度越来越快。充满信息的现实世界是混乱的、随机的、复杂的，而我们对事物的直觉则是简单的——这两者之间并不匹配。结果是，我们的精神架构越来越跟不上我们所生活的世界。

 自启蒙运动以来，在理性主义（我们希望事物是什么样子，才能让我们觉得有道理）和经验主义（事物实际的样子）的对立中，我们一直在责怪这个世界不符合“理性”模型的普罗克拉斯提斯之床，一直在尝试改变人们以适应技术，改变伦理以适应我们对雇佣的需求，改变经济生活以适应经济学家的理论，努力把人生塞进某种叙事框架之中。

 读者从我的格言中可以看出，我对大自然维持强壮的方法心怀敬意（几十亿年的时间足够任何脆弱的东西土崩瓦解）；古典思想（对未知事物的尊重，认识论层面上的谦卑）比启蒙运动之后的现代伪科学自我中心主义更加强壮。因此，我的古典价值观驱使我强调博学、优雅和勇气的重要性，反对现代社会的虚伪、庸俗和书呆子气。[3]

 格言、警句、谚语、歇后语，甚至讽喻性的短诗，可以说是最早的文学形式——这些形式经常包含在我们今天所谓的诗歌里。它们具有经典言论的认知完整性（尽管它们比今天充满商业气息的所谓“经典言论”[4]更加强力也更加优雅），带着一点点炫耀的意味，展示了作者把强有力的观点压缩到寥寥几句话中的能力——特别是以口语形式来表达。的确，这肯定是一种炫耀，因为阿拉伯语中的“格言”一词本来就具有“展示男子气概”的意思，尽管这里所谓的“男子气概”并不像字面上听起来那样仅仅局限于男性，而是更适合翻译为“人类的气概与能力”[拉丁文中的“美德”（virtue）一词也是这样，发源于vir这个词根，而vir的意思就是“人”]。那些能够用这种方式表达出强有力的思想的人，似乎具有某种象征性的力量。

 反脆弱性偏好随机性和不确定性，这意味着——这一点非常关键——它也偏好错误，准确地说是某一类错误。反脆弱性有一个奇特的属性，它能帮助我们应对未知的事情，解决我们不了解的问题，而且非常有效。让我说得更直白些：由于有了反脆弱性，我们做的要比我们想象的更好。我宁愿做愚钝但具有反脆弱性的人，也不做极其聪明但脆弱的人。

 如果说一切自上而下的东西都会使我们变得脆弱，并且阻碍反脆弱性和成长，那么一切自下而上的事物在适量的压力和混乱下反而能够蓬勃发展。发现（或创新，或技术进步）的过程本身就取决于能增进反脆弱性的自由探索和积极的冒险，而非正规的教育。

 此外，我们发现在2008年金融危机期间，由于日益复杂的现代制度和政治事务，这些“危及他人的重大风险”很容易被隐瞒。过去，甘冒风险的人才会位高权重，他们必须为自己的不当行为承受损失，而英雄则是那些为了他人的利益承受损失的人，如今，情况却完全相反。我们正目睹一群反面“英雄”人物的涌现，他们多为政府官员、银行家，或者只知道借他人名气自抬身价，参加达沃斯会议的成员，以及权力过大的学者。这群人不会承受真正的损失，也不受问责制的约束。他们将整个系统玩弄于股掌之上，而公民却要为其埋单。 历史上从未有过如此多的非冒险者，也就是施加重大控制力而个人却不承担风险的人。 他们忘记了一条最主要的道德法则：你不应该为了获得反脆弱性，而牺牲别人的脆弱。

 历史上从未有过如此多的非冒险者，也就是施加重大控制力而个人却不承担风险的人。 他们忘记了一条最主要的道德法则：

 “黑天鹅”事件绑架了我们的思维，让我们感到自己“差不多”或“几乎”预测到了它们，因为它们都是可以进行回溯性解释的。由于存在可预测性错觉，我们没有意识到这些“黑天鹅”事件对生活的影响。现实生活远比我们记忆中的生活更加错综复杂——我们的头脑倾向于将历史以更平稳和更线性的状态呈现出来，这导致我们低估了随机性。一旦我们看到随机事件时，就会心生畏惧并反应过度。在逃避这种恐惧以及对秩序的渴求中，一些人类建立的系统往往会打乱事物的隐性逻辑，或者打乱不那么明显的逻辑，结果导致“黑天鹅”事件的发生，而且几乎得不到任何收益。当你寻求秩序，你得到的不过是表面的秩序；而当你拥抱随机性，你却能把握秩序、掌控局面。

 本书的每一句话都是我用自己的职业知识写就的，我只写了我做过的事情，我建议他人承担或规避的风险也是我一直承担或规避的风险。如果我错了，那么首先受到伤害的便是我自己。我在《黑天鹅》中已经对银行体系的脆弱性提出过警告，并打赌它会崩溃（尤其是当我的观点无人理会时）；否则，我会觉得这样写是不道德的。这种个人约束应该用于各个领域，包括医疗、技术创新和生活中的简单事务。这并不意味着一个人的个人经验就足以构成推导出理念结论的充分样本，只是说，一个人的个人经验是其观点的真实性和真诚性的背书。经验是不会受过滤式选择的影响的，而研究工作却会受影响，尤其是所谓的“观察性”研究，因为存在大量的数据，研究者在观察过去的模型会陷入叙述谬误的陷阱。

 我们知道的事情其实比我们认为的要多，比我们能说清楚的要更多。即使我们正式的思维体系总是诋毁自然，我们对反脆弱性也没有一个正式的名称，而且我们对这一概念总是充满抵触情绪，但这并不意味着我们的行动也忽略了这一概念。从我们的行为中反映出的感觉和直觉，会超越我们的所知和所记，以及我们的讨论和课堂内容。

 政治运动和叛乱具有高度的反脆弱性，愚蠢的行为就是试图用暴力压制它们，而不是想办法操控它们、以退为进，或找到更精明的策略，就像赫拉克勒斯杀死九头蛇怪一样。

 我的曾外祖父尼古拉斯·戈恩是一个老谋深算的政治家，尽管树敌众多（其中最知名的就是他的克星，我在塔勒布家族这边的高祖父），但是他却成功地长期把持政坛宝座，并大权在握。当我的外祖父，尼古拉斯·戈恩的大儿子开始从事行政工作，并有望从政后，他的父亲在临终前把他叫到面前说：“我的儿子，我对你很失望，”他说，“我从未听到外界对你的指责。你已经证明了自己根本无法激发别人对你的嫉妒。”

 反脆弱性的产生是有条件的。压力源的刺激频率非常重要：人类在急性刺激下会比在慢性刺激下表现得更出色，尤其是在急性刺激后给予较长的恢复期，这将使得这些压力源成为信息的传导渠道。比如，看到一条蛇从我的键盘中爬出来，或者一个吸血鬼进入我的房间，都会对我产生强烈的情绪冲击，随后，我当然需要足够长的舒缓期（伴着甘菊茶和巴洛克式的音乐），来重新控制自己的情绪，这会对我的健康有利，当然，前提是我经历了一番艰苦的甚至英雄式的激战后，战胜了蛇或吸血鬼，还能在我亲手击毙的袭击者身边拍一张照片留念。 这样的压力源肯定比一个温和但连续不断的压力源有益，后者大多是让你在生活中感到压抑的东西，包括按揭贷款、税务问题、因拖欠报税而产生的内疚、考试压力、琐碎事务、电子邮件回复、填写表格、每天上下班通勤，等等。换句话说，这是文明带来的压力。事实上，神经生物学家表明，第一种类型的压力源是必要的，而第二种类型的压力源对人的健康却是有害的。要想知道不给人以恢复时间的低水平压力源的害处，只要看看所谓的中国水刑：水滴连续滴在你头上的同一位置，而不给你任何喘息的机会。

 世界上有这么一种人，对他们来说，生活就是某种项目。在与他们交谈之后的几个小时内，你都会感觉很不舒服；生活开始变得像寡淡无味的食物。我是一个寻求刺激的人，我有一个刺激探测器，这似乎与我的无聊探测器很匹配，就好像我们天生配备着一个过滤器，天生厌恶无聊。我们先祖的生活中没有作业、没有老板、没有公务员、没有学业成绩、没有与院长的谈话、没有从工商管理学硕士（MBA）班上毕业的咨询顾问、没有日程表、没有申请表、没有去新泽西的旅程、没有语法难题，也不用与让你感到厌倦的人说话；生活充满了随机的刺激，所有事情，无论好坏，都与工作无关。[11]危险当然有，但你不会感觉无聊，从来不会。

 弗拉诺·巴罗维奇在读到本章时致信给我补充道：“机械体：使用的过程中会出现损耗；有机体：不使用时会出现损耗。”还需注意，所有有生命的物体都需要压力源，但所有机器都需尽量减少压力，我们将在后面的章节中再谈及这点。

 即使有一个物种因某种极端事件完全灭绝，这也没什么大不了的，因为它是整个游戏的一部分。这仍然是进化的作用，因为存活的物种是优胜劣汰的结果，它们从消失的恐龙手里接管了这个世界——进化不是服务于一个物种，而是服务于整个自然。

 为了促进进步，现代社会应该像纪念牺牲的士兵一样对待破产的创业家，也许不用给予那么多的荣誉，但应该基于完全相同的逻辑给予他们认可（创业者们仍然活着，但却被贴上了道德败坏、欺世盗名的标签，尤其是如果他生活在日本，这种情况更甚）。这个世上不存在“失败的战士”的概念，无论他是牺牲了还是活着（除非他做出了懦夫的行为），同样的，也不存在失败的创业者或失败的科研人员这种说法。但这个世界上存在着成功的胡说八道者、成功的伪哲学家、成功的评论员、成功的顾问、成功的说客，或成功的商学院教授，而他们根本不承担个人风险。（请原谅我这么说。）

 请注意瑞士的另一个特征：它也许是历史上最成功的国家，但一直以来，它的高等教育水平都要比其他富裕国家低。它的系统，比如银行系统，即使在我工作的时代，也都是基于学徒模式，更接近职业培训而不是理论学习。换句话说，是基于工艺和技术诀窍而非书本上的知识。

 从火鸡的故事中，我们可以看到所有有害性错误的根源：将证明有（危害）的证据较匮乏视为有证据证明不存在危害。我们将会看到，这种错误在知识界极为普遍，在社会科学领域也根深蒂固。 因此，在生活中，我们的任务就是“如何不让自己成为火鸡”，或者如果可能的话，争取与火鸡的特征相反，也就是具有反脆弱性。想要“不做火鸡”，就要了解真正的稳定和人为的稳定之间的差异。

 我祖父的一个朋友曾讲过一句话，让我非常震惊。那个人是一位从复兴党政权下逃离的富有的阿勒颇商人。黎巴嫩内战爆发后，我的祖父曾问过那个朋友为什么不回阿勒颇，他的回答很明确：“我们阿勒颇人宁愿打仗也不愿意蹲监狱。”我开始以为这位商人的意思是士兵会把他抓进监狱，但后来我意识到，这里的“监狱”指的是政治和经济自由的丧失。

 这一点也没有逃脱文艺复兴时期意大利著名的政治思想家马基雅维利的眼睛。让–雅克·卢梭引用他的话语写道：“马基雅维利写道，在谋杀和内战中，我们的共和国更为强盛，而公民也学到了美德……微小的骚动和焦虑滋养了灵魂，让物种繁荣的不是和平，而是自由。”

 再来看看冶金工业中的退火工艺，这是一种使金属更强韧、质感更均匀的技术。它需要给材料加热并控制其冷却过程，以增加晶体的大小，减少瑕疵。正如“布里丹之驴”一样，热量导致原子脱离最初的位置，随机地在高能状态下漫游；冷却则给予它们更多的机会，寻找新的、更好的结构。

 或者，有时系统会从不同类型的压力中受益。对伏尔泰来说，最好的政府就是间或玩弄政治暗杀伎俩的政府。弑君的效果类似于敲击木制晴雨表，以使其更好地工作。这产生了一些往往很有必要的重新洗牌，而且是从来没有主动要求过的洗牌。顶层出现的真空引发了退火效应，促使新领导人的出现。社会早亡率的下降对我们来说当然是好事，但它剥夺了自然管理下的优胜劣汰。谋杀是黑手党接班的标准程序，最后一次众所周知的退火行动是约翰·戈蒂在纽约牛排馆门口谋杀了前任黑手党教父，顺理成章地成为新的头领。而在黑手党之外，比如老板和董事会成员，他们的在位时间更长，这是在许多领域都存在的一个事实，比如首席执行官、终身学者、政治家们、记者——看来，我们需要随机抽签来决定他们的去留，从而打破僵化的局面。

 我会不断地重复这一点，直至声嘶力竭：古人开发了隐秘而复杂的方法和技巧来探索随机性。举例来说，实际上我在餐馆里也尝试过随机点餐法。由于菜单冗长复杂，往往置我于被心理学家称为“选择的暴政”的境地中，以至于每次做完选择心里就有一种不安的感觉，暗示自己其实应该点其他菜品。因此，我尝试盲目地、系统地跟随桌上最胖的那个人点单；如果没有这样的人，我就随机地从菜单上选择，根本不看菜名，心安理得地让太阳神帮我选择。

 扁桃体切除手术给那些实际上不必做手术的儿童带来了伤害，而这项手术给其他一些儿童带来的所谓康复的益处却被大肆鼓吹。这种净亏损或超过治疗益处的损害（通常被隐藏或延迟）被称为医源性损伤，从字面上来看就是“治疗师所造成的”损害，iatros在希腊语中是治疗师的意思。我们将在后文中指出，每次你去看医生并接受治疗，你就要承担治疗损害的风险，这与我们权衡其他利弊的方式一样：概率收益减去概率成本。

 塞梅尔维斯的故事是可悲的：一个人为挽救他人而说出了真相，却遭到惩罚、羞辱，甚至杀害，最糟糕的惩罚莫过于他在风险和不公平面前的无助。但是，这个故事也有积极的一面——真相终于大白，他的使命获得了回报，虽然是迟到的回报。最后的一个教训是，人们不应该指望在揭示真相后都能获得鲜花和掌声。

 我的生态学推理来说，一个人做事拖拖拉拉不是因为他不理性，而是他身处的环境不合理。称这个人不理性的经济学家和心理学家，其实才是不理性的。 事实上，人类是非常不擅长过滤信息的，特别是短期信息，而拖延则是帮助我们筛选信息的较好方式，它能避免我们由于冲动而轻信某个信息，我们下面还会就此做出详细讨论。

 现代化的发展为我们提供了大量的信息，这些信息却把人类从从容镇静的那类人变成神经过敏的人。出于讨论的目的，我们暂且把从容镇静的人视为懂得对真实信息做出反应的人，而神经过敏的人则大多在对噪声做出反应。两类人之间的差异让我们看到了噪声和信号之间的差异。噪声是你应该忽略的，而信号才是你需要注意的。

 在商业和经济决策中，对数据的依赖导致了严重的副作用。由于互联网的发展，数据空前丰富，你在数据中陷得越深，错误数据的比例就越高。我们很少讨论数据的一个属性，即大量数据实际上是有害的，即使是中等数量的数据也是有害的。

 在医学上，我们发现绝食有帮助身体自我康复的功效，因为这避免了因摄入食物而分泌过多的荷尔蒙。荷尔蒙会将信息传递给我们身体系统的不同部分，但荷尔蒙过高会导致生物机能的紊乱。就像接受新闻的频率过高会产生问题一样，过多信息有害无益——每日接受过多的新闻和摄入过多的糖都会让系统紊乱。在第23章的内容中我会阐述，太多的数据（特别是无效的数据）将导致统计数据毫无意义。

 总而言之，减轻干预的最好方法是限量供应信息，并以尽可能自然的方式来获取信息。这在互联网时代是很难让人接受的。我很难对人解释说，你获得的数据越多，就越不了解情况，导致的医源性损伤也会更多。如今，人们仍抱有“科学”就意味着更多数据的错觉。

 奥巴马的错误说明人们很容易在因果关系链条上产生错觉，也就是将催化剂当作起因，并以为大家可能知道哪些催化剂会产生哪些影响。所有观察者，尤其是卷入其中的观察者，都没有预测到埃及最近的那次动荡。因此，指责美国中央情报局或一些情报机构，与花钱资助它们来预测这些事件一样，都是很不明智的。政府浪费了数十亿美元，试图预测相互依赖的系统所产生的事件，因而在个体层面上，无法通过统计手段去理解。

 我们之所以需要将重点放在行动上，避开言词，还有另一个因素要考虑：依赖于外部的认可有损健康。人们在给予认可时是残忍和不公平的，所以最好跳出这种游戏。在别人的态度面前保持强韧性。尼罗曾经与一位有传奇地位的科学家交友，对这位科学巨匠无比尊重。虽然这个人几乎是其所在领域中最知名的人了（在他人的眼中），但他还是花时间查询每周自己在科学界所拥有的地位。哪个作者要是“没有引述”过他的文章，或者哪个委员会把他从未得过的奖授予某个他认为不如他的人，（哼，就那个骗子！）都会让他义愤填膺。

 确实是噪声：被浪费的努力、不和谐的声音、缺乏美感的行为、增加的熵值，导致纽约经济区局部升温的能源产量，以及将会蒸发的泡沫视为“财富”的错觉。

 让我用现代术语来复述这一概念。拿你可能失去的更多，得到的更少的情况举例。如果给你一笔财富（比如1 000腓尼基舍客勒）并不能给你带来很大的利益，但是如果失去同等金额的财富，则会使你感觉受到了更大的伤害，那么你就处于不对称之中。这不是一个好的不对称：因为你变得很脆弱。

 塞内加用以对抗这种脆弱性的实用性方法就是，通过心理练习来弱化财产在心目中的地位，这样，当损失发生时，他就不会受到刺激，这是从外界环境中夺回个人自由的方式。比如，塞内加常在旅行时随身带着遭遇沉船的风险时可能会用到的东西，包括一块可以铺在地板上睡觉的毯子，因为当时的旅馆很少（当然我也需要阐明，由于当时的背景使然，他在旅行中还有一两个奴隶跟随左右）。

 同样的，在做交易员时，我也会做一种类似的精神运动，这种职业充斥着高度的随机性，给我带来持续的心理伤害。因此，我就假设每天一大早，最糟糕的事情就已经真实地发生了，那么剩下的时间我会感觉好受一些。其实，这种把精神调节到应对“最糟情境”状态的方法比一些心理治疗方式更管用，因为它让我承担的这类风险的最糟情境是清晰和明确的，其伤害是有限的和已知的。但当一切都很顺利时，我们便很难坚持这种淡化式精神训练法，而此时恰恰是我们最需要这种训练方法的时候。此外，我偶尔也会按照塞内加的方式，在不舒服的环境中旅行（虽然我不像他还有一两个奴隶跟随左右）。

 知性的生活关乎如何进行情绪定位，以消除伤害的刺激，正如我们所看到的，方法就是淡化你所拥有的东西在你心中的地位，这样任何损失都不会给你带来伤痛。世界的波动性也不能给你带来负面影响。

 塞内加也为我们展示了一种社会行为，即对善行进行投资。我们可能会被剥夺一些东西——但是，善行和美德是不会被剥夺的。

 而反脆弱性的邮包在摇晃中得到的比失去的更多。最简单的判断测试：如果我“一无所失”，我获得的只有利益，那么我就是具有反脆弱性的。

 因此，我的工作就是用基础不对称结构将以下4个要素联系起来。 脆弱性等于失去的比得到的更多，等于不利因素比有利因素更多，即等于（不利的）不对称性。 反脆弱性等于得到的比失去的更多，等于有利因素比不利因素更多，即等于（有利的）不对称性。 如果潜在收益大于潜在损失，那么你对波动源就具有反脆弱性（反之亦然）。 此外，如果潜在的有利因素多于不利因素，那么你可能会因为波动和压力不足而受到伤害。

 换句话说，如果某个事物是脆弱性的，那么它破碎的风险会导致你做的任何旨在改善它或提高其“效率”的工作都变得无关紧要，除非你先降低其破碎的风险。罗马作家普布里亚斯·塞勒斯就曾写过：你无法既仓促又安全地做好任何事情，几乎没有一件事情能办得到。

 让我们选取一些事例来管中窥豹。在个人风险方面，你很容易通过消除任何领域的致命性风险而将自己置于杠铃结构之中。我个人就对某些风险非常谨慎，同时在其他的风险上又非常冒进。我的规律是：不吸烟、不吃糖（尤其是果糖）、不骑摩托车，不在城市以外的地方骑自行车——或者更广泛地说，不在没有交通的区域，如撒哈拉大沙漠里骑车，不与东欧的黑社会有瓜葛，不上一架不是专业飞行员（除非有副驾驶）开的飞机。但除了这些之外，我可以承担各种形式的职业和个人风险，尤其是那些不会给我带来任何终极伤害的风险。 社会政策往往保护弱势群体，同时让强者各尽其职，而不会帮助中间阶层巩固其特权，因为这样会阻碍进化，造成各种经济问题，最终还会给穷人带来最大的伤害。

 这就解释了为什么伦敦市中心的房地产价格泡沫是由俄罗斯和阿拉伯海湾的贫富不均决定的，完全独立于英国的房地产走势。某些卖给富人的房屋，每平方米的均价是几个街区之外建筑物均价的20倍。

 如果你有“可选择性”，那么你就不太需要智力、知识、洞见、技巧，或者那些在脑细胞中发生的复杂事情。因为你不必每次都正确。你所需要的只是不做不明智的事情，以免伤害自己（比如忽略某些事情），随后就能在有利的结果发生后乐享收益了。（关键是你的评估并不需要预先进行，只要在结果发生后进行即可。）

 但现在请你记住，进化可以产生令人惊讶的复杂而精密的事物，无须智慧，只需要可选择性和某些自然选择过滤机制，再加上接下来要探讨的随机性即可。

 本章和第四卷的另一观点是，选择权可以替换知识，其实我不太明白什么叫作贫瘠的知识，因为人的知识必然是模糊和贫瘠的。所以，我做了一个大胆的推论（我将在接下来的几章提供有说服力的论据），即我们以为靠我们的技能成就的许多东西其实大多来自选择权，而且是被妥善运用的选择权，很像泰勒斯的案例，也很像自然选择的情况，而不能归功于我们自认为掌握的知识。

 意第绪曾说过：“学生很聪明，受称赞的却是老师。”这些有关贡献的错觉大多来自于证实谬误：历史属于那些会写历史的人（不论是赢家或输家），这一事实已然可悲，但更糟糕的是，写这些文字的人虽会提供证实事实（也就是行得通的事情），却没有呈现一个完整的画面告诉我们哪些事实行得通、哪些事实行不通，由此让我们形成了第二种偏见。比如，定向研究会告诉你哪些项目依靠资金资助成功了（如艾滋病治疗药物或一些现代药物的研制），但不会告诉你哪些项目不成功，所以你会形成基金资助项目比随机项目更有成效的印象。

 创业者往往是实干家，而不是思想家，实干家重行动，而不是语言，因此用谈吐来衡量他们未免不公平，甚至是错误的，是彻头彻尾的侮辱。技术工人也是如此，我们应该以他们的产品，而不是表述能力来衡量他们的手艺——实际上，他们很容易产生错误的观点，这些错误的观念会产生副作用（反医源性损伤），促使他们做出更好的产品，所以一切又有什么关系？另外，对于政府工作人员，由于缺乏衡量成功的客观标准与市场力量，他们往往会因肤浅的外表和优雅的“晕轮效应”而当选，副作用是使其更加擅长交谈。我敢肯定，与一位联合国官员共进晚餐一定比与胖子托尼的某个亲戚或者一位痴迷于电路设计的计算机创业者更容易找到有趣的话题。

 与我谈话的第一位专家是一个名叫巴索的人，他穿着手工制作的布莱奥尼西装。有人告诉我，他是世界上最大的瑞士法郎交易商，是他所处时代的传奇——他曾预测到在20世纪80年代的美元大崩溃，并控制了巨额的头寸。但通过与巴索的简短谈话，我发现他竟然不知道瑞士在地图上的位置——与我一样愚蠢，我以为他是瑞士裔意大利人，但是他竟然不知道瑞士还有说意大利语的人，他也从未去过瑞士。当我意识到他并非交易员中的特例时，我开始害怕我这些年接受的正规教育在我眼前蒸发。从那一天开始，我停止阅读经济报告。在这个“去知识化”的过程中，有一阵子，我甚至对知识性的东西感到恶心，事实上，我可能到现在都没有恢复过来。

 伟大的经济学家阿里尔·鲁宾斯坦就领会了绿色木材谬误——这需要很大的智慧和诚实才能看清这个问题。鲁宾斯坦是博弈论领域的领军人物之一，博弈论中涵盖了假想实验；他也是你能在咖啡馆里遇到的最杰出的专家，在世界各地进行思考和写作。鲁宾斯坦拒绝声称他的有关理论问题的知识可以——由他——转化为任何直接实用的东西。对他来说，经济学就像寓言，寓言作家需要激发人们思考，或许间接启发了实践，但肯定不能指导或决定实践。理论应该与实践保持独立，反之亦然——我们不应该把经济学家从校园里请出来，放在决策者的位置上。经济学不是一门科学，不应该为政策建言。

 对他来说，经济学就像寓言，寓言作家需要激发人们思考，或许间接启发了实践，但肯定不能指导或决定实践。理论应该与实践保持独立，反之亦然——我们不应该把经济学家从校园里请出来，放在决策者的位置上。经济学不是一门科学，

 我在芝加哥做场内交易员时就注意到了一些蛛丝马迹，比如我观察到，资深交易员都拒绝接触数学公式，他们使用简单的启发法，并声称：“有本事的人可不用表格。”这里的“表格”指的是电脑中输出的复杂公式和计算。然而，这些人生存了下来。他们的定价比那些公式计算出来的还要精准且有效，最佳价格往往一目了然。比如，他们的定价考虑到了如何应对极端斯坦和“长尾”，而这些情况往往是标准公式所忽略的。

 实践者是不写文章的，他们只会放手去做；飞鸟果然会飞，但那些教导它们飞行的人，正是写故事的人。所以不难看出，历史实际上是由失败者撰写的，他们有大把的时间，学术地位也得到保护。

 现在，与其列出一份清单（太不体面了），我还不如推荐读者读一些书，除了迈尔斯的书，还有克劳德·波宇昂和克劳德·莫内雷的书《美妙的机会：药物发展史》，以及李杰的《笑气、伟哥和立普妥》。

 现在，我同意，没有通过学术界审查的大部分执业医生是流氓、江湖郎中、庸医，甚至比这些人更糟。但是，让我们不要轻易下错误的结论。形式主义者为保护自己的地盘，一直在玩弄一种逻辑错误，即认为：如果非学术类行医者中存在庸医，那么非学术类行医者就都是庸医。他们现在还是这么做的，而事实上，说“不严谨的都是非学术的”（假设你是愚蠢的人，你就会相信这一点）并不意味着“所有非学术的都是不严谨的”。“合法”的医生和其他行医者之间的争论就相当具有启发性，尤其是当你注意到，医生们总是在偷偷地（不情愿地）仿效其他行医者所开发和推广的补救措施和治疗方式。出于经济利益的考虑，医生不得不这样做，他们受益于非正规行医者的集体试错结果。这一过程推动了治疗方法的应用，如今已经融合到正式的医疗中。

 生物学家和知识分子威尔逊曾经被问道，什么是儿童发展的最大障碍；他的回答是足球妈妈。他并没有用普罗克拉斯提斯之床的概念，但他完美地诠释了这个概念。他的理由是，足球妈妈们压抑了儿童的生物自卫本能，以及他们对自然生物的爱。但这个问题的涉及面可能很广；足球妈妈们试图从孩子们的生活中消除试错和反脆弱性，使他们远离生态模式，而将他们改造成按照预设的现实模式（符合足球妈妈的想法）行事的书呆子。就这样，孩子们成为好学生，但也成为书呆子，也就是说，这些孩子就像是计算机，除了计算速度慢了一些。此外，他们完全没有受过任何关于处理模棱两可情况的训练。作为一个经历过战争的人，我不相信结构化的学习，其实我相信的是，一个人只要有一个私人图书馆，并花费时间漫无目的地（但理智地）遨游在我们随机学到的知识中，那他不上学也可以成为一个智者，而不会成为书呆子。只要我们的生活遵循正常的秩序，我们就需要一些随机性、混乱性、冒险性、不确定性、自我发现、非致命的挫折等来让生活变得更有意义，这总好过整日离不开排得满满的日程表和闹钟的、自以为是的、结构化的、虚伪的、低效的首席执行官的生活。这些人连休息的时间也要仔细算好，分秒必争，就好像他们的生活永远夹杂在各种约会中。现代化的使命，看起来是压榨出生活中的每一滴可变性和随机性（正如我们在第5章中所看到的），但结果却具有讽刺意味，因为这只不过徒增了世界的不可预测性，就好像机会女神不管如何都会掌握最后的话语权一样。

 在一个结构化的环境中，有些人可以比别人更聪明——其实学校就有选择性偏见，因为它喜欢在这种环境中反应更快的学生，喜欢搞竞争，但却以牺牲学生在校园外的能力为代价。虽然我还不熟悉健身运动，但我的想法是，那些使用昂贵的现代健身器材来增强力量的人，虽然可以举起很重的杠铃，消耗掉很多卡路里，锻炼出令人艳羡的肌肉，但是他们却无法搬起石头；他们在街头斗殴中会被那些在混乱的环境中磨炼过的人打得头破血流。使用健身器材的人的力量有极端的领域特定性，但他们能发挥作用的领域在健身这个组织化程度极高的框架之外根本不存在。事实上，他们的力量与过分专业化的运动员一样，是畸形发展的结果。我认为，这与那些被选为尖子生，只努力在少数科目上取得高分，而不是按照自己的兴趣爱好发展的人是一样的：只要让他们稍微远离一下他们的研究领域，你就能看到他们如何丧失信心和一味抗拒。（就像企业高管之所以被公司选中是因为他们忍受无聊会议的能力，许多人被选为尖子生也是因为他们专注于枯燥教材的能力。）我曾与许多据称专门从事风险和概率研究的经济学家进行讨论：当你稍微远离他们狭隘的专业领域，但仍在概率的学科范围内时，他们就已经溃不成军了，就好像一个健身老手在被职业打手教训了一顿后哭丧着脸。

 所以，我的诀窍是，你可以厌倦读一本特定的书，但不要厌倦阅读的行为。这样，你所阅读并消化的知识才能快速增长。随后，你就会毫不费力地发现，书中自有黄金屋，就像理智但无设定方向的试错研究所能带来的。这与选择权相同，失败了也不要停滞不前，必要时向其他方向摸索，跟随那种广阔的自由感和机会主义的引领，试错就是一种自由。

 我承认，在写这篇文章时，我仍在使用试错的方法。避免无趣是唯一值得推荐的模式，否则生活也太不值得过了。

 20世纪80年代的一天，我与一位取得巨大成功的著名投机商共进晚餐。他一语中的地表明：“人们了解的很多东西其实都不值得去了解。” 迄今，我仍然本能地认为，宝贵的知识，也就是你从事某一职业所需了解的知识，一定不在数据库中，所以要尽可能地远离中心。我在学校被灌输的东西，我已经忘光了；而我自己决定读的东西，我仍然记得很牢。追随自己的爱好来选择阅读的重要意义，莫过于此。

 正如胖子托尼所说，苏格拉底被处死是因为他破坏了在雅典政府眼里无可置疑的东西。事物过于复杂，乃至无法用言语表达，如果什么都要用语言表达出来就磨灭了人性。有人——比如在绿色木材案例中——可能关注的是正确的事情，但我们却不够聪明，没能意识到这个问题。 死亡和牺牲成了很好的营销手段，特别是当一个人在面临命运的审判时还能坚持自己的意见时。英雄往往是一个充满知性信心和自尊的人，死亡对他来说微不足道。我们听到有关苏格拉底的叙述都让他以英雄的姿态出现，这大多归功于他的死亡和他以一种哲学的方式献身。但是，仍有一些古典批评者认为，苏格拉底摧毁了社会的基础——那种由长者传递的，我们可能因不够成熟而没有资格质疑的启发法。 我们在第2章中提到的罗马思想家老加图，就对苏格拉底极为反感。

 哲学家谈论真与假。真正过日子的人谈论报酬、威胁和后果（风险和回报），也就是脆弱性和反脆弱性。有时，哲学家和思想家总是将真理与风险及回报混为一谈。 让我进一步阐释我的观点，真与假（我们所谓的“信仰”）在人类的决策中扮演着糟糕的、辅助性的角色；起主宰作用的是真与假所带来的回报，而这几乎总是不对称的，一个结果会比另一个结果更大，也就是存在积极和消极的不对称性（脆弱性和反脆弱性）。

 但是战争——以及20多倍的成本计算错误——仅仅说明美国政府低估了爆炸性非线性（凸性效应）的作用，以及为什么政府不配拥有任何财政大权或重大决策权。事实上，政府根本不需要战争就能将我们拖入赤字困境：低估项目成本是造成当代98%的项目超支的痼疾。政府总是在完成项目后告诉我们开支超过了预算。于是，我针对政府制订了一条黄金法则：不准借钱，强制实现财政平衡。

 请注意，全球化促进了集中化趋势的蔓延，就好像整个世界成了一个只有狭窄出口的巨大房间，所有人都争相涌向同一个出口，导致伤害加剧。正如当今几乎每一个孩子都读哈利·波特，都登录脸谱网站（Facebook）一样，每个富裕起来的人都会参加相同的活动，购买相同的商品：他们喝解百纳葡萄酒，希望在威尼斯和佛罗伦萨旅游，梦想在法国南部购置第二套房产；旅游景点变得不堪重负：7月时去威尼斯旅游就能体会到。

 有说服力和自信的学科，例如物理学科，往往很少使用统计数据支持本学科的论点，而政治学和经济学虽然从来没有产生过值得一提的东西，却充斥着复杂的统计和统计“证据”（你知道，一旦你揭开面纱，证据就不是证据了）。科学上的这种情况与侦探小说中相类似，不在场证据最多的人结果往往是有罪的。你也不需要收集很多数据来批驳经济学充斥着统计数据的大量论文：“黑天鹅”事件和“尾部”事件（这些事件是不可预测的）主宰着社会经济世界的简单论点，已足以驳斥统计数据的效用了。

 我花了不少时间才认识到这个原因：他们极其欠缺优雅。技术思想家往往有一种“工程思维”——不太客气地说，他们有自闭症倾向。虽然他们通常不戴领带，却显示出书呆子的所有气质——主要是缺乏魅力，对事物而非人感兴趣导致他们往往忽视自己的外表。他们喜欢精确，却牺牲了实用性，而且他们通常缺乏文学素养。

 而不会自然消亡的事物，情况则相反。为了清楚易懂，我在这里将数据简化一下。如果一本书已经出版发行了40年，我预计它可以再发行40年。但是，主要区别在于，如果它又存活了10年，那么预计它会再发行50年。简单地说，作为一项规律，它告诉你为什么已经存在了很长时间的事物不会像人类那样“老化”，而是会越来越“年轻”。每过一年，只要该事物没有灭绝，它的预期剩余寿命就会翻番。这也是强韧性的一个指标。一个物体的强韧性与它的当前寿命成正比！

 给特定人群的行为贴上“年轻”或“年老”的标签，是一种更危险的做法。如果大家不看网络上那种高调宣传的、精心包装的18分钟的宣传片，而是关注生活中十几岁和二十几岁的青年人（他们手中也许掌握着通向未来的钥匙），你们就会换种思考方式。许多进步都来自于年轻人，因为他们有相对不受系统束缚的自由与采取行动的勇气，而年长者则多囿于生活而失去了这些品质。但是，年轻人提出的想法大多都是脆弱的，不是因为他们年轻，而是因为大多数未经历练的想法往往是脆弱的。当然，很多人之所以吹嘘“未来主义”理念是因为宣传过去的理念赚不了那么多钱，新技术当然比较容易振奋情绪。

 我们对水的依赖要超过对手机的依赖，但因为水不会改变而手机一直在变，因此，我们很容易将手机发挥的作用想象得比它们的实际作用更大。

 但我们对古典艺术、老式家具——总之不归于技术一类的事物，似乎就没有这种跑步机效应。比如，你在同一间屋子里挂了一幅油画，还摆了一台平板电视。这幅油画绘于近一个世纪以前，呈现的是经典的佛兰德风景，佛兰德阴暗的天空、雄伟的树木，以及平凡但宁静的乡村景色。我敢肯定，你不会急于对你的油画升级换代，但你的平板电视机却有可能很快被你捐献给某个爱肾基金会的地方分会。

 此外，技术性的东西往往都很脆弱。我们对艺术家的作品很少产生跑步机效应，这些东西都带有一定的反脆弱性——比如，我脚上这双手工制作的鞋子，这得耗费鞋匠好几个月的时间才能制作完成。而带“开关按钮”的物品往往没有这种补偿性的反脆弱性。

 最后，我认为下文是对目的论设计的最好反驳。建筑物自诞生后常常会出现变化，就好像它们需要缓慢地进化以与周围变化的环境相契合：它们会改变颜色、形状、窗户和特征。斯图尔特·布兰德在他的书《建筑物如何进行学习》中登出了照片，显示建筑是怎样随时间而改变的，就好像它们需要蜕变成识别不出的形状——奇怪的是，这些建筑自兴建之时，就从未考虑到未来改变的可选择性。

 但很少有人意识到，自然形成的度量体系背后自然有其逻辑：我们用英尺、英里、磅、英寸、弗隆、英石等计量单位，因为这些都是古人直觉的产物，我们使用它们只需付出最低的认知努力。而且，所有文化中都有一些类似的度量方法，用实物去衡量每天遇到的事情。比如，公尺无法与任何实物匹配，但英尺却有相匹配的东西。我可以轻易地想象“30英尺”的长度。再看英里，该词源于拉丁文miliapassum，意思是走一千步。同样的，一英石（14磅）与什么相对应呢……当然，是石头。一英寸对应的是一个拇指的长度。一弗隆的距离是人们一口气可以冲刺的距离。一磅源于libra，就是你能想象你的双手可以捧得住的重量。回想一下我们在第12章中所说的泰勒斯的故事，我们用到了舍客勒这一度量单位：在闪米特人–迦南人的语言中，这个词的意思是“重量”，具有实体方面的内涵，与磅类似。这些单位出现在我们祖先的生活中绝非偶然——而数字系统本身与我们的10根手指也存在对应关系。

 另外，我一直在推荐丹尼尔·卡尼曼的书，因为这很大程度上是其34~40年之前的研究心血经过精心筛选和现代修订后的呈现。我的建议似乎是不切实际的，但是，经过一段时间，这位学生形成了一种阅读亚当·斯密、马克思和哈耶克等人原著的习惯，因为他相信这些书籍即使到他80岁的时候也会时常引用。他告诉我，在定下这个书籍选择规则后，他意识到他的同龄人读的往往都是最及时但很快就会过时的书籍。

 我认为，那些人类的技术，如幸存下来的写作和阅读技术，就像瓷砖之于狗，是自然的朋友之间的匹配，因为它们对应了我们内心深处的一些东西。只有时间颠扑不破的东西，才是属于我们永远需要的东西。 每当我听到有人试图将一本书和一个电子阅读器相比较，或者试图比较某种古老的东西与某种新技术时，各类“意见”就冒出来了，仿佛现实只关心意见和叙述一样。其实，我们的世界中深藏着秘密，只有实践可以发现它们，而意见或分析是无法全面捕捉这些秘密的。 当然，秘密只有随时间的流逝才会逐渐为人所知，谢天谢地，它只能等待时间来发现。

 实际上，他确实没有答案，因为我一碰到电脑，我就可以确认，没有令人信服的实证证据表明冰敷有利于消肿。

 这两个错误已经非常明显，因为在这两种情况下，益处似乎是显而易见且直接的，虽然这种益处很小，而伤害则会滞后多年才得以显现，至少得3/4个世代才会出现。那么，下一个要讨论的问题就是举证责任，因为你很容易想象，那些捍卫这些治疗方式的人会立即提出异议：“塔勒布先生，你的陈述有何证据呢？”

 我们始终找不到能让我们在健康的状况下无条件地增强体质（或无条件变强壮）的药品，原因很简单，可以从统计数据来看：大自然本应该可以找到这种神奇的药丸。但是，鉴于某种疾病是罕见的，而且人病得越重，大自然越不可能自己找到解决方案。所以说，偏离正常值3个单位的情况会比正常情况罕见300多倍；偏离正常值5个单位的情况则比正常情况罕见100万倍以上！

 我无法抗拒以下对干预性偏见（产生负凸性效应）的阐述。20世纪四五十年代，许多儿童和青少年接受了放射线治疗法，来治疗痤疮、胸腺肿大、扁桃体发炎，以及去除胎记和治疗头皮癣。除了甲状腺肿大和其他晚期并发症，接受这种放射性治疗的病人中约有7%的人在20~40年后患上甲状腺癌。但是，让我们不要摈弃辐射，如果它是来自大自然的话。我们对一定剂量的辐射水平（也就是自然的辐射水平）必定是有反脆弱性的。这种小剂量的辐射甚至可能防止来自更大剂量辐射带来的伤害和癌症，因为我们的身体会对辐射产生某种免疫力。谈到辐射我突然想到，几乎没有人知道，为什么过去几千年来我们人类的皮肤一直暴露于阳光下，现如今却突然需要防晒了，是不是因为大气发生变化了，晒太阳变得对我们有害了呢？还是因为如今人类生存的环境与皮肤的色素不相匹配了，或者更确切地说，是防晒产品的制造商需要赚取利润呢？

 抗生素。每当你服用抗生素时，你就在一定程度上帮助细菌突变，变成抗生素耐药菌株。同时，还会损伤你的免疫系统。你改变了身体对细菌的反脆弱性。解决方案当然是只在用药益处很大时才服用抗生素。卫生或过度的卫生，也有相同的效果，特别是在人们每次接触外界后都用化学物品来清洁双手的情况下。

 我们天生容易受理论的愚弄。但理论诞生又消亡，而经验却总能经受时间的考验。解释总是在变，在历史发展的过程中不断地变化（原因在于因果的不透明性和原因的隐蔽性），因而人们慢慢地养成了一种无明确理论支持就不能形成观点的习惯；但经验却能保持不变。

 让我重申一次：我并不是反对理性化的习得话语，只要它在错误面前不是脆弱的即可；我是第一个和最后一个哲学家–概率论者和决策者的混合体，而且我永远不会将哲学家–概率论者与决策者分离开来，所以我始终是混合体，无论是早上我喝古老的咖啡饮品的时候、中午我和朋友共进午餐的时候，还是晚上我随手拿本书上床睡觉的时候。我反对的是天真的理性化、虚假的习得话语、深陷绿色木材问题的论述——仅仅着眼于已知的，而忽略未知的。同样的，在衡量未知的重要性问题上，我也不反对运用数学——这是数学的强大应用。

 人类预期寿命的增加是因为许多因素的结合：卫生、青霉素、犯罪率的降低，以及挽救生命的手术的出现，当然，也归功于一些医学执业者对危重病患生命的拯救。我们活的时间更长，这是由于那些患了致命疾病、病情严重的患者能从医药和治疗中受益，因为此时的医源性损伤非常低。正如我们所看到的，这属于凸性效应的情况。所以，如果因为医疗能帮助我们活得更长，我们就推断说所有的医疗护理都能使我们的寿命更长，那是严重的错误。

 为什么呢？消除一些没有经过进化历练的事物，有助于降低“黑天鹅”这种极端事件的发生概率，同时使人类有机会得到改进。如果人们能够改进，我们可以相当确信，它将在很大程度上消除看不见的副作用。

 对止痛药的依赖鼓励人们不再使用试错法来寻找头痛的根源，原因可能是缺乏睡眠、颈脖肌肉僵硬，或者压力过大。止痛药纵容人们以削足适履的方式毁灭自己。但实际上要解决这些问题并不难，我们只要扔掉医生给你开的药物，或者最好是远离医生，正如老奥利弗·温德尔·霍姆斯所说的那样：“把所有药物都倒进大海对人类会更好，只是鱼类要遭殃了。”我的父亲是一位肿瘤科医生（他也做了些人类学研究），他就是根据这样的信条把我抚养长大的（虽然在实践上没有完全遵从，但他经常把这些话挂在嘴边）。

 至于饮料，我的原则是不喝少于1 000年历史的饮料——因为人体对古老饮料的适应性已经过测试。我只喝酒、水和咖啡，不喝软饮料。也许最可能带有欺骗性的有毒饮料就是我们让可怜无辜的人们在早餐桌上喝的橙汁了，但同时我们却通过营销手段说服他们这是“健康的”。（除了因为早年我们祖先吃的水果没有那么甜，还因为他们从来不会在摄取碳水化合物的同时摄入大量的纤维。吃一个橘子或苹果，在生物学上与喝橘子汁或苹果汁并不等效）。从这个例子我得出一个规律，被称为“健康”食品的东西一般都不健康，就像“社交”网络阻碍了人类的正常社交，“知识”经济也往往是无知的一样。

 需要注意的是，医源性损伤是富裕和复杂，而非贫困和单纯造成的结果，而且是知识不完全的产物，而非完全无知带来的恶果。因此，这种抛弃所有走进沙漠的想法，是一种相当有效的否定法式减法策略。很少有人认为，钱也有它自己的医源性损伤，某些人失去财富只会让他们的生活更简单，以健康压力因子的形式令其受益匪浅。所以说，只要做得正确，生活贫困一点儿也并非完全没有益处。

 在我看来，在人性深处，我们知道什么时候需要寻求宗教的安慰，什么时候需要回到科学思维上来。[36]

 请注意人体构造的微妙之处：牛和其他食草动物在食物摄取上的随机性比狮子要小得多；它们稳定地进食，但需要付出更大的努力来代谢所有这些营养成分，因此它们每天要花费好几个小时吃东西。更不要说站在那里吃草是多么无聊了。而狮子则不同，它需要依靠更多的运气，它的捕食成功率并不高，只有不到20%，但是一旦捕食到猎物，它便能快速而容易地摄入它的猎物通过艰苦和枯燥的进食工作所积累的进食所有营养成分。因此，我们可以从环境的随机结构中总结出以下原则：当我们吃素时，我们就需要稳定地摄取食物；当我们吃肉时，我们可以更随机地进食。因此，从统计上说，我们也应该随机消耗蛋白质。

 这里传统的“素斋”可谓登峰造极，具有极大的想象空间：黎凡特的羔羊肉饼是用植物和豆子取代肉类做成，肉丸是用未发酵的棕色小丸子在扁豆汤内做成。值得注意的是，虽然禁止吃鱼，但大多数时候，贝壳类食物还是允许食用的，可能因为它不被认为是奢侈品。日常饮食中某些营养元素的缺乏，在日后可以大量地补回来。我会在我能够吃鱼的日子里，补偿我这些天因少吃鱼而缺少的被研究人员（目前）称为蛋白质的东西，当然我也会在复活节狼吞虎咽地吃羊肉，随后再大量食用高脂红肉。现在，我就非常渴望在胖子托尼经常光顾的餐厅吃上一块牛排，而且毫无疑问要超大份的。 这就是禁食的压力所带来的反脆弱性，它使我们所渴望的食物品尝起来更美味，也能在我们的肌体系统内产生更多的快感。禁食后进食的感觉与吃喝过量的感觉完全相反。[37]

 让我们记住，我们最早可不是从送餐员手上获取食物的，在大自然中，我们必须费些力气才能弄到吃的。狮子要靠狩猎才有食物，它们可不是为了取乐而去狩猎的。因此，在人们还没有辛苦工作之前就供应食物，无异迷惑了他们的身体信号系统。

 在此之前，我们是现在的群体和未来子孙的一部分。现在和未来的群体都会利用个体的脆弱性来强化自身。人们勇于牺牲、寻求殉道、为集体献身，并因这样的做法而感到自豪；他们的努力是为了造福子孙后代。

 当我们听到幸福是根据经济或其他微不足道的物质条件来定义时，应该停下来思考一下。你可以想象，每次听到有人宣扬与英雄主义毫无关系的“中产阶层价值观”时，我就觉得极其厌烦。得益于全球化和互联网，这个所谓的“中产阶层价值观”已经传递到了英国航空能够轻松抵达的任何一个地区，原本被高贵的阶层所深恶痛绝的东西如今却被大肆推崇：为银行或烟草公司“卖力工作”；勤奋地阅读报纸；服从大多数（但不是所有）的交通规则；被某种企业结构束缚；一味听从老板的意见（因为工作记录都由人力资源部门保存）；遵守法律；依赖股市投资；去热带地区度假；住在郊区（以抵押贷款购房），养着一条非常漂亮的狗，星期六的晚上品酒消遣。取得一些成功的人便能跻身年度亿万富翁排行榜，期待在他们的化肥销售遭到来自中国的竞争对手的挑战之前，能在榜上多逗留一段时间。他们将被称为英雄——而不是幸运儿。此外，如果说成功是随机获得的，那么有意识的英雄主义行为就不是随机的。自称“合乎道德的”的中产阶层可能会为烟草公司工作——多亏他们高明的诡辩，这样做也能自称道德。

 技术助长了怯懦……这些都是相互关联的：社会之所以变得脆弱，是因为存在一些没有骨气的政治家、一些害怕民意的逃避者，以及只会编故事的记者，这些人导致了爆炸性赤字和代理问题的进一步复杂化，只因为他们希望粉饰短期内的业绩。

 关于勇气，我学到的最宝贵的一课，是来自我的父亲——孩提时期，我就非常钦佩我父亲的学问，但并未对他过分崇拜，因为学问本身并不能使你成为一个真正的男子汉。我的父亲有着强大的自尊心，他要求别人尊重他。黎巴嫩战争期间，他曾经受过一个在道口盘查的民兵的侮辱。他拒绝服从对方的指令，民兵对他不敬的态度使他非常生气。当父亲开车离开后，一名枪手对着他的背部开了一枪。在他的余生中，这颗子弹就一直留在他的胸部，所以每次他进入机场候机楼，他都必须携带X光片。这为我设置了非常高的门槛：除非努力进取，否则尊严将一文不值；除非你愿意为它付出代价。

 如果你勇于承担风险，有尊严地面对自己的命运，那么你做什么都不会贬低自己所做的事情；如果你不承担风险，那么你做什么都不会使自己伟大。如果你承担风险，那么，那些不承担风险的人带给你的侮辱只不过如同牲畜的吠叫：你不可能因为狗朝着你狂吠而感觉受到了侮辱。

 我们可以从胖子托尼的启发法中推导出大量的启发法，尤其是如何减轻预测系统的弱点。只要预测者在游戏中没有投注，即不涉及其切身利益，那么对他人来说就是危险的，就像没有工程师睡在现场的核电站。

 所以，那些骄傲、夸夸其谈的舆论制造者将最终赢得辩论，因为他们是写文章的人，而由于阅读他们写的文章而陷入麻烦的愚蠢的人，以后还会再次阅读这些文章以寻求未来的指导，然后再次惹上麻烦。

 不对称性（事后预测者的反脆弱性）：事后预测者可以采用过滤式选择法来挑选他们的意见为人接受的例子，并将失误的预测抛入历史的垃圾堆。这是一个免费选择权——对他们来说是这样；我们却必须为它付出代价。

 经济界也应该如此，但是经济机构搅乱了一切，让愚蠢的人也有机会发展壮大——它们通过纾困和中央集权阻止了进化。需要注意的是，从长远来看，社会和经济往往会以意外、突变和跳跃这些恶劣的方式完成进化。

 千万不要听信一个从来不放弃自己财富或者从不践行他希望别人追求的生活方式的“左翼”人士。法国人所说的“鱼子酱式左派”，或者是被盎格鲁–撒克逊人称为香槟式社会主义者的人就是那些崇尚社会主义，有时甚至是共产主义意识形态，或一些倡导节俭的政治制度，但却公开过着奢靡生活的人。他们往往靠继承下来的丰厚财产过活，从没有意识到这其中的矛盾之处——他们自己的生活方式正是他们希望别人避免的。这与追逐女色的教皇，比如约翰十二世或波吉亚没什么区别。真正的矛盾有时会达到荒诞不经的地步，比如法国总统弗朗索瓦·密特朗在就任社会党第一书记时，其就职典礼被弄得简直像法国君主盛大的加冕仪式。更具有讽刺意味的是，他的死对头——保守党的戴高乐将军，却过着一种旧式的简朴生活，连袜子都是他的妻子帮他缝补的。

 想想看先知们。预言是对信念的承诺，仅此而已。先知不是第一个产生某个想法的人，他是第一个相信这个想法的人，而且始终相信。

 顺便说一句，这个概念也适用于各种形式的思想和理论：理论背后的主要人物、所谓的理论创始人，应该是一个相信这个理论、以之为信念，并愿意以昂贵的代价承诺秉持这一信念、确保其自然得出结论的人；而不一定是在喝甜酒时第一个提出这一概念的人。 只有真正相信的人，才能避免最终自相矛盾，并且陷入事后预测的错误。

 商业世界的问题在于，它只能通过加法（肯定法），而不是减法（否定法）来运转：医药公司不会从你降低糖分摄取的行动中受益，健身俱乐部运动器械的制造商不会从你搬运石头和在岩石上行走（不带手机）的决定中获益；股票经纪人不会因你将资金投入你眼见为实的投资物上（比如你表弟的餐厅或你家附近的一栋公寓楼）而获益；所有这些公司都必须制造“收入增长”，以符合坐在纽约办公室里的那些思维迟钝——或者在最好的情况下——思维略显迟钝的工商管理硕士分析师的分析。当然，他们最终会自取灭亡，但这是另一个话题。

 那种根据给定规格提供最廉价产品的机制，渗透到了你在货架上看到的任何东西中。当公司卖给你它们称之为奶酪的东西时，它们有充分的动机为你提供制作成本最廉价的一块橡胶，里面含有适当的成分，所以还是可以称之为奶酪，它们还会做足功夫研究如何欺骗你的味蕾。其实，它们不仅有这种动机，它们从结构上也注定极其善于生产符合给定规格的最廉价的产品。商业书籍也是一样：出版商和作者都想抓住你的注意力，把他们可以找到的最易过时的新闻信息凑成一本勉强可以称之为书的东西。这就是优化在最大化（形象和包装）或最小化（成本和努力）等方面的作用。

 总而言之，企业是如此脆弱，长期来看，它终将不堪代理问题的重负而轰然倒塌，与此同时，经理人却能大口吃肉，却只给纳税人留点骨头。如果不是因为强大的游说机器，企业早就崩溃了：它们劫持了这个国家来帮助它们为消费者的消化系统注入含糖饮料。在美国，大型企业控制着一些国会议员。这样的做法牺牲了我们的利益，推迟了公司的死亡。

 告诉我你是否理解了这个问题的本质：受雇于公民，理论上应该代表公民最佳利益的前主管官员和公务员，可以利用他们的专业知识和在工作中积累的人脉，在加入私营企业（律师事务所等）之后从系统的缺陷中谋利。 进一步想想吧：法律规定越复杂，社会网络越官僚，就有越多深谙系统漏洞和缺陷的主管官员从中受益，因为他的主管优势将是其专业知识的凸性函数。这是一种特权，是以牺牲别人为代价获得的不对称性。（请注意，这种特权正在整个经济中蔓延；丰田汽车公司就曾聘请前美国主管官员，利用他们的“专业知识”来处理汽车缺陷调查案。）

 你总是可以找到一个论点或合乎道德的理由在事后捍卫你的观点。这种观点非常靠不住，为了避免过滤式选择，你应该在行动之前，而不是行动之后提出合乎道德的准则。你要防止牵强附会地用你编造的故事为你的行为辩护——很长一段时间以来，“诡辩”这种就决策中的细微差别进行争论的艺术做的就是此事，即想方设法地为你所作的决定辩解。
