#+title: 圆明园游

@2013-07-09

百度百科对圆明园介绍
#+BEGIN_QUOTE
圆明园（Yuanmingyuan Imperial Garden）坐落在北京西郊，与颐和园毗邻。圆明园始建于康熙46年（1707年），由圆明园、长春园、绮春园三园组成，为西洋兼中式皇家风格园林，建筑面积达16万平方米，是清朝三代帝王在150余年间创建的一座大型皇家宫苑，有"万园之园"之称。圆明园继承了中国3000多年的优秀造园传统，既有宫廷建筑的雍容华贵，又有江南园林的委婉多姿，同时又汲取了欧式园林的精华，把不同风格的园林建筑融为一体，被法国作家雨果誉为"理想与艺术的典范"。1860年10月，圆明园遭到英法联军的洗劫，并被放火焚毁，今仅存遗迹。

圆明园最初是康熙皇帝赐给皇四子胤禛（即后来的雍正皇帝）的花园。在康熙四十六年即公元1707年时，园已初具规模。同年十一月，康熙皇帝曾亲临圆明园游赏。雍正皇帝于1723年即位后，拓展原赐园，并在园南增建了正大光明殿和勤政殿以及内阁、六部、军机处诸值房，御以"避喧听政"。乾隆皇帝在位60年，对圆明园岁岁营构， 日日修华，浚水移石，费银千万。他除了对圆明园进行局部增建、改建之外，除在紧东邻新建了长春园，在东南邻并入了万春园。至乾隆三十五年即1770年，圆明三园的格局基本形成。嘉庆朝，主要对绮春园进行修缮和拓建，使之成为主要园居场所之一。道光朝时，国事日衰，财力不足，但宁撤万寿、香山、玉泉"三山"的陈设，罢热河避暑与木兰狩猎，仍不放弃圆明三园的改建和装饰。"圆明园"，这一名称是由康熙皇帝命名的。康熙皇帝御书三字匾牌，就悬挂在圆明园殿的门楣上方。对这个"圆明"雍正皇帝有个解释，说"圆明"二字的含义是："圆而入神，君子之时中也；明而普照，达人之睿智也。"意思是说，"圆"是指个人品质阶级标榜明君贤相的理想标准。
#+END_QUOTE

早上赶早起来去中央党校北医三院的住院部做完结算之后，就从安河桥北坐地铁到海淀黄庄回单位。路过圆明园的时候，寻思时间还不算太晚，而且前几天正好看过一个圆明园的纪录片，所以就想进去看看。从圆明园站下车之后从A口出来就是圆明园的南门了。从南门购买了套票25元，包括了遗址门票以及全景模型。所谓的遗址，其实就是长春园的西洋建筑残骸。

整个圆明园其实是由三个部分组成的，其中圆明园占据了整个西面，长春园占据了东面的北部分，绮春园占据了东面的南部分。园子非常大，我只是逛了绮春园和长春园就花费了近2个小时，圆明园还有很大的一片包括后湖都没有去。整个园林的设计大部分都是非常中国的，流水，长桥，门庭，等等，大部分都是比较相似的。我去的时候，荷花开得很好，柳树枝条基本上都压弯到地上了，正好前一天下过雨，站在桥上闭上眼睛，深呼吸一口气，感觉非常舒服。值得一提的是，里面大部分的东方建筑，都是 [[http://baike.baidu.com/view/37055.htm][样式雷]] 设计的，祖籍江西。

很快就到了西洋建筑遗址了，细数下来我应该看了这几个景点: 谐奇趣, 黄花阵, 方外观, 海晏堂, 蓄水楼, 大水法. 经过长年的日晒风吹雨淋虽然雕花的棱角有点磨损，但是看上去依然是非常精致的。石头的质地感觉也非常好，尤其是黄花阵的主体石头摸上去倍感凉意。

最后我从东门出来打车回到南门，然后做地铁去上班了。
