#+title: 浪潮之巅

-----
这正应了茨威格的话：“在命运降临的伟大瞬间，市民的一切美德 — 小心，顺从，勤勉，谨慎，都无济于事，它始终只要求天才人物，并且将他造就成不朽的形象。命运鄙视地把畏首畏尾的人拒之门外，命运 — 这世上的另一位神，只愿意用热烈的双臂把勇敢者高高举起，送上英雄们的天堂”。（人类群星闪耀时）

-----
近一百多年来，总有一些公司很幸运地、有意识或者无意识地站在技术革命的浪尖之上。 一旦处在了那个位置，即使不做任何事，也可以随着波浪顺顺当当地向前漂个十年甚至更长的时间。在这十几年间，它们代表着科技的浪潮，直到下一波浪潮的来临。

-----

但是在当时，即使AT&T的高管意识到这一点，他们对公司也没有绝对的控制。AT&T几个执行官们手上的股票远不如华尔街投资银行控制的多。说句不好听的，AT&T的总裁们并不真正拥有公司。他们之中不乏有远见者，但是根本左右不了董事会。更何况公司的长期利益和他们没有太大关系。如果能在任期内狠狠捞一把，何乐而不为呢？作为华尔街的投资公司，他们关心的是手中的股票何时能翻番。1995年正是一个机会，整个股市长势很好，在这时将设备制造部门和电信服务部门分开，那么前者的股票一定会飞涨。华尔街看到了这一点，公司的老总们懂得这一点，公司大量拥有股权的员工们也明白这一点。本来大家都是明白人，但是利令智昏。一场杀鸡取卵的分家就开始了。

从MCI和Sprint带来的销售额增长几乎是一次性的。华尔街在预测朗讯盈利时，已经把这笔收入计算进去了。朗讯的股票要继续增长，它的销售额和利润就必须不断超过华尔街的预期。（注：一般来讲，一个公司当前的股价，已经反映了当前和几年后的盈利能力。如果想让股价快速增长，公司的盈利就必须高于大家的预期）朗讯其实根本做不到这一点。为了能支撑得住一个高股价，朗讯走了一步后来被证明是败笔的险棋。在互联网泡沫时代，有无数的中小公司在兴起、大公司在膨胀，朗讯决定"促销"它的电信设备。具体做法是由朗讯借钱给各公司来买朗讯的设备。只要设备运出朗讯，它就在每季度财务报表中，计入销售额。如果仔细读它的财报，人们可以发现朗讯总有一笔很大的"应收款项"，这笔钱其实从未进到朗讯公司。到了2000年互联网泡沫破裂后，借钱买设备的公司统统倒闭，朗讯的这笔"应收款项"一下子变成了净亏损。2001年，朗讯公司不得不关闭贝尔实验室的几乎全部研究部门。

但是，这些科学家们也隐隐地感到一些危机。原来的贝尔实验室因为有AT&T这个大靠山，从来不发愁自己的经费。现在，朗讯的利润不足以养活有2万人的巨型实验室，开始要求那里的科学家和工程师开发能尽快赚钱的研究上来（我在以后会谈到AT&T这种大实验室的弊端）。贝尔实验室此时已不是过去以研究为主的地方了，它的创新能力不复存在，从1995年至今，贝尔实验室没有再搞出轰动世界的发明。本来，AT&T的电信服务和设备制造相辅相成，是个双赢的组合。分家对双方长远的发展都没有好处。AT&T和朗讯的衰落都从这时起。

在2000年前后，短线投资者发现最快的挣钱方法不是把一个企业搞好，而是炒作和包装上市。将公司的一部分拆了卖无疑挣钱最快。于是AT&T决定一拆四，分成长途电话，移动电话，企业服务和宽带四个公司。

在工业史上，一种新技术代替旧的技术是不以人的意志为转移的。人生最幸运之事就是发现和顺应这个潮流。投资大师巴菲特在谈到上个世纪初他父亲失败的投资时讲，那时有很多汽车公司，大家不知道投哪个好，但是有一点投资者应该看到，马车工业要完蛋了。巴菲特为他的父亲没有注意到这一点而感到遗憾。

-----

IBM能成为科技界的常青树，要归功于它的二字秘诀--保守。毫无疑问，保守使得IBM 失去了无数发展机会，但是也让它能专注于最重要的事，并因此而立于不败之地。

十几年后，硅谷一位最成功的CEO讲，凡是和微软合作的公司，最后都没有好结果。IBM也许是其中第一个吃亏者。

IBM里面的人常常讲这么一个故事，在IBM公司，如果要把一个纸箱子从二楼搬到三楼，需要多长时间。这件本来几分钟就能办成的事，在IBM需要几个月。原因是，要搬动一个箱子，你要先打报告，然后经过层层审批；审批后，审批报告再层层向下落实，最后交给替IBM 搬家的搬运公司。在搬运公司的任务单上，上个月的任务可能还没有完成呢，现在提交的任务单一个月以后能完成就不错了。这样，搬动一个纸箱花几个月时间一点也不奇怪。

接下来，他对公司的一些机构和制度进行改革。首先，他不声不响地将分出去的一些服务公司买回来（那时IBM快破产了，美国政府不反对它将服务公司买回来），然后将IBM的硬件制造、软件开发和服务合成一体。对比几乎同时代AT&T将公司拆分的做法，郭士纳完全是反其道而行之。他的目的是打造一只IT服务业的航空母舰。在公司内部，它引入竞争机制，一个项目可能有多个组背靠背地开发。为了防止互相拆台、加强合作，郭士纳将每个人的退休金和全公司的而不是以前的各部门的效益挂钩。 在研究方面，郭士纳将研发经费从营业额的9%降到6%。以前的IBM实验室很像贝尔实验室，有不少理论研究，郭士纳砍掉了一些偏重于理论而没有效益的研究，并且将研究和开发结合起来。一旦一个研究项目可以实用了，他就将整个研究组从实验室挪到产品部门。

到后期，他甚至要求IBM的所有的研究员必须从产品项目中挣一定的工资。这种做法无疑很快地将研究转化成产品。但是这样做无疑会影响IBM长线研究和基础研究，为了弥补这方面的损失，IBM加强了和大学的合作，在几十所大学开展了科研合作或者是设立了奖学金。

IBM在经营上相当的保守，它一直固守自己的核心领域，很谨慎地开拓新的领域。从机械的制表机到大型计算机，到今天的Linux开源服务器，IBM始终牢牢地控制者美国政府部门、军队、大公司和银行的业务，即使它生产的笔记本电脑，也是针对公司用户而不是个人用户的。在同档次的笔记本电脑中，它的价格比其他厂家的要贵很多，因此个人很少自己掏腰包购买IBM笔记本。IBM在自己一些非核心领域也常常处于领先地位，但是它也不轻易在那些领域快速膨胀。比如，它在很长时间里在存储技术、数字通信技术、半导体芯片设计和制造技术上都领先于世界，但是我们很少看到IBM花大力气开拓这些市场。保守的好处是不容易轻易出错，因为像IBM这样服务于美国乃至世界各国核心部门的公司，产品上出一点错就会造成不可弥补的损失，要知道美国主要银行对计算机系统的要求是一年宕机时间不能超过五分钟。IBM这种保守的做法让大客户们很放心，因此，即使它的产品和服务比别人贵，政府和公司还是很愿意，或者说不得不用IBM的。

IBM实验室迄今为止有两次大的变动。一次是在1993年郭士纳上台后大量削减研究经费，很多人离开了IBM去华尔街。其中很多人，主要是一些数学很强的科学家，去了后来最成功的对冲基金（Hedge Fund）文艺复兴技术公司（Renaissance Technologies），并撑起了半个公司。可见科学和金融也是相通的。文艺复兴公司迄今为止二十年平均投资回报率为每年37%，在世界上是独一无二的，而且远远超过股神巴菲特的旗舰公司伯克希尔-哈撒韦（Berkshire Hathaway）。这二十年来，两个公司的总回报率分别是200倍和20倍，而标普500指数是6倍。IBM实验室第二次大变动是在最近几年。现在，IBM的很多研究员只能从研究项目中拿到一大半而不是全部的工资，另一小半必须通过参加产品项目而获得，因此一些单纯搞研究的科学家不得不离开。对IBM的这种政策，仁者见仁、智者见智。IBM的目的是非常清楚的，科研必须和产品相结合。

-----

很多人问我雅虎有没有可能在搜索领域赶上谷歌，我明确地回答--没有，因为雅虎不可能专注在这个领域。有时，一个好的公司不能完全按华尔街的意愿办事。 如果时光可以倒流，让摩托罗拉和英特尔当时换个个儿，即IBMPC采用摩托罗拉的处理器，而将服务器厂家和苹果交给英特尔。那么二十年发展下来，摩托罗拉也很难成为半导体领域的老大，因为它内部的问题没法解决。

英特尔公司的商业模式历来是靠大投入大批量来挣钱，同一代的芯片，英特尔的销量可是太阳公司的十倍甚至更多，因此，它可以花几倍于其他公司的经费来开发一个芯片。但是，当一种芯片市场较小时，英特尔公司很难做到盈利。现在，这是它面临的最大问题。

整个计算机工业的规模上万亿美元，绝不是一家公司能吃得下的。诚然在这个领域生态链的不同环节需要垄断，但是各个环节之间需要互相扶持。尤其是在九十年代以后，整个计算机工业形成这样一种默契，由软件更新带动硬件更新。在更新软件时，软件公司先得到发展，但是，旧的硬件很快会显得性能不够。这时，用户不是抱怨软件做的不好，而是去更新硬件。这才使得诸多硬件公司得以快速发展速度，众人拾材火焰才能高。苹果既做硬件又做软件，很难平衡两者的速度。软件做得太快了硬件就跟不上，硬件做的太快了有没有合适的软件可用。

-----

在管理上，微软比硅谷的公司严格的多，在人事关系基本上是严格的自顶向下的树状结构，和硅谷公司松散的结构完全不同。在经营上，微软很少花钱做没用的东西。虽然微软的很多产品并不成功，但是，即使这些产品在开发时，其商业前景也是经过严格论证的。微软从不会像苹果那样，搞出有用无用的一大堆项目。在这一点上，华尔街很喜欢微软，因为它能保证高利润。另外，盖茨和华尔街合作很默契，每次报业绩时，微软每股的利润总是略高于华尔街预期一两美分，然后让华尔街替它把股票抬上去。

从生意经上讲，盖茨深知赚大钱和赚小钱的关系。盖茨和他的忘年交投资大师巴菲特做法相同，他们都是要从每一个人身上挣或多或少的一笔钱，而不是从富人身上狠宰一刀了事。

我非常喜欢黑格尔地一句话：凡是现实的都是合理的，凡是合理的都是现实的。(All that is real is rational; and all that is rational is real.)虽然这句话常常被误解成为当今不合理的现实来开脱，其实，如果我们动态地看待现实性和合理性，可以把这句话理解成，现在存在的现象，当初产生它的时候必然有产生它的原因和理由。如果这个理由将来不存在了，终究有一天它也会消亡。微软称雄于微机时代，自有它的合理性。但是，到了网络时代，显示改变了，微软再次称雄的合理性也就没有了。

-----

一个成功的公司的早期员工是非常宝贵的财富。他们一般是一些非常爱冒险的人，否则他们不会选择加入新开办的甚至是还没有投资的小公司，他们技术和能力非常强，常常每个人可以独挡一面，因为早期的公司要求员工什么都得能干。他们同时对新技术非常敏感，否则他们在众多新兴公司中就不会挑选中那些日后成功的。但是，他们也有他们的弱点。他们虽然善于开创，但不善于或者不愿意守成，而后者对于一个大公司发展至关重要。他们做事快，但是不够精细，因为在公司很小时，抢时间比什么都重要。因此在公司发展到一定阶段，他们会和新的管理层发生冲突--新的主管会觉得他们不好管。这就如同打江山的人未必能治理江山。这些员工很可能自己出去开公司。而即使留在公司的这些早期员工已经腰缠万贯，原先的动力也要大打折扣。因此，如何留住早期员工，并且调动他们的积极性，便成为了每一个上市的科技公司的难题。

另外，一个公司大到一定程度后，每个人的贡献就不容易体现出来，大锅饭现象几乎是全世界的通病。一些员工虽然有很好的想法，也懒得费功夫去推动它，因为自己多花几倍的时间和精力最多能多得百分之几的奖金。偶尔出来一两个人试图推动一下，又会发现在大公司里阻力很大。因此，有些员工一旦有了好的想法，宁可自己出来创业，也不愿贡献给自己的公司。这两个问题在硅谷普遍存在，而思科是这些问题解决得最好的公司。

思科具体的做法是，如果公司里有人愿意自己创业，公司又觉得他们做的东西是好东西，就让他们留在公司内部创业而不要到外面去折腾，而思科会作为投资者而不再是管理者来对待这些创业的人。一旦这些小公司成功了，思科有优先权把它们买回来，思科的地盘就得到扩大。而这些独立的小公司的创办者和员工，又可以得到很高的回报。这样本来想离开思科出去创业的人也就不用麻烦了，接着上自己的班，只是名以上换了一家公司。当然，如果这些小公司没办好关门了，那么思科除了赔上一些风险投资的钱，没有额外的负担。这种做法不仅调动了各种员工尤其是早期员工的积极性，也避免这些员工将来成为自己的对手或者加入对手的阵营。

思科内部存在一个和IBM类似的问题，一些部门虽然毛利率相比整个行业并不低，但是扣除研发、市场和管理等费用，就成为亏损部门。在华尔街的压力下，它不得不放弃这些低利润的产品。当然，思科在高端产品和新产品上的优势是华为短期内无法相比的，但是，如果一个公司只剩下高端产品，那么它就在也不能成为全行业的垄断者。

-----

一百年后，如果人们只记得两个对互联网贡献最大的人，那么这两个人很可能是杨致远和费罗（David Filo）。他们对世界的贡献远不止是创建了世界上最大的互联网门户网站雅虎公司，更重要的是制定下了互联网这个行业全世界至今遵守的游戏规则--开放、免费和盈利。

所有互联网公司都看到了流量的重要性，并且很快都复制了雅虎的商业模式。但是，这些二三流互联网公司却没有一个像雅虎那样盈利。当时大家还没有意识到"不是所有的流量都是平等的"。

在广告业，做品牌广告有个不成文的约定俗成，非常讲究门当户对，即拥有一流品牌的公司必须在第一流的媒体上做广告，即使一个二流媒体有着同样的观众群，那个公司也不能在上面做广告，因为那会影响自己的品牌。所以，那些做品牌广告的公司永远不会在二三流网站上做广告。

塞缪尔走了，留下了一个千疮百孔的雅虎。他的继任者首席财务官德克尔虽然是一位财务高手，但是对互联网行业的认识实在难以恭维。她留给所有投资者的一个笑柄是创下了出售Google股票的最低价。作为Google的投资者，雅虎拥有相当多的Google原始股，包括Google 上市前又给了雅虎两百七十万股。德克尔居然以低于Google上市价（85美元）的价钱82.62美元在Google上市前私下卖给了投资公司。这个低价始终没有人能接近过。这件事本身不仅说明德克尔对互联网市场一点感觉没有，而且作为公司第一把手的大局观很差。出身华尔街的德克尔应该深知投资公司为了降低风险常用的对冲（hedge）手段。在具体到Google的股票上，雅虎的做法应当是持有，因为如果Google失败，股票跌到零，雅虎在整个互联网就没有了对手，损失掉Google的股票无非是小的局部损失，但赢得的是整个互联网。反过来，如果Google股价倍增，说明相对来讲雅虎业绩在下降，这时再卖掉Google的股票可以成倍的得到现金，再回来和Google竞争（如果雅虎把Google的股票持有到今天，超过40亿美元，这笔钱比雅虎从成立至今运营利润总和还多50%）。现在，雅虎交到了德克尔手里，它的前景堪忧。

-----

二战后的信息技术，大多起源于美国，而硅谷更是世界创新的中心。尽管2000年硅谷收到互联网泡沫崩溃打击最大，但是，它依然是信息技术和（以Genentech为代表的）生物技术创新的中心，但是，和二战以前不同，每一项起源于欧美的新技术，用不了多久就会被日本人、后来还有韩国人和中国人掌握。于是，一种技术出来后，欧美公司在没有亚洲竞争对手时，可以打一个时间差，挣一个高额利润。以前，这个时间差有几十年，现在已经缩短到几年甚至更短。比如，五十年前日本的日立和松下等公司造出可以媲美惠普的示波器花了十几年的时间，而到了八九十年代，佳能仿制出惠普的喷墨打印机几乎没有花任何时间。这样一来，惠普等公司就不得不和亚洲公司面对面的竞争了。

为了抵消亚洲制造的冲击，欧美公司十分鼓励和支持代加工即OEM似的亚洲制造，这样可以降低它们的成本，但是会千方百计阻挠亚洲公司打自己的品牌，因为这样会对它们产生威胁。可以这样讲，美国公司很喜欢OEM大王郭台铭，不太喜欢松下幸之助和华为的任正非。

这是一次惨痛的教训，它说明如果一个公司不能挑选好掌舵人，以后替换掉他成本也是很高的。

更糟糕的是，惠普已经被打上了消费电子公司的标记，这样对于向往创新的工程师和科学家来说，惠普就不再是他们工作的首选了，这对惠普的长期发展不利。

-----

和所有大公司一样，在摩托罗拉也是最挣钱的部门嗓门最大，开发数字手机的部门当然不容易盖过正在挣钱的模拟手机部门，因此，摩托罗拉虽然在数字手机研发上并不落后，但是，进展缓慢。

公平地讲，摩托罗拉的手机仍然是同类手机中信号最好，最可靠的，作为只用手机打电话的我，在使用过各个厂家的手机后，还是最推崇摩托罗拉的。但是，在亚洲，手机不仅仅是一个电话，它是个人通信的平台，是生活的一部分，甚至有人在上面镶上钻石作为身份的象征。（这有点像两百年前欧洲人的手杖，其实不是为了支撑身体。）在满足后者需求上，诺基亚和以三星为首的亚洲做到更好。

摩托罗拉长期以来形成了高工资，高福利的大锅饭，员工干好干坏差别不大。摩托罗拉的本意是想避免员工之间不必要的攀比，每个人都有一个宽松自在的环境安心工作。这是四五十年前大公司吸引人才的方式，欧洲公司至今还采用这种办法。但是这不太适合喜欢冒险的美国人。八九十年代以来，美国的科技公司为了调动知识型员工的积极性，很多采用的股票期权制（我们以后再仔细介绍）。而摩托罗拉公司很晚都没有采用这种福利，直到今天，摩托罗拉公司给员工的期权依然数量很少。这不能不说是受摩托罗拉的传统管理方式所限。因此，很多人把摩托罗拉看成一个去养老的公司而不是一个创业的公司。

-----

一个小公司要想成功，有很多因素必须同时具备。首先，创始人很重要。任何梦想家都不足以成事，因为所有的成功者都是实干家。创业者还必须精力过人，因为他们必须能熬得住几年每天在简陋的车库里工作16-20小时的苦日子。他们又必须是多面手，因为在创业初期他们必须干所有的脏活。成功的创业者必须有一个小而精的好团队，里面每个人都得不计较个人得失，同甘共苦，否则成则争功，败则互相推诿。在技术上，他们必须有自己的金刚钻，他们的技术必须是不容易被别人学会和模仿的。如果看到雅虎挣钱，就去搞网站，那基本上可以肯定是要失败的。但是光有好的团体和技术又远远不够，他们有商业头脑而且必须找到一个能盈利的商业模型（Business Model）。Ebay和谷歌的成功很重要地在于它们很早就找到的好的商业模型。 但是找到一个好的商业模型有时比发明一项技术更难，即使最有经验的风险投资专家在这上面也经常栽跟头。再接下来是判断力和执行力。通常，办起一个公司并不难，把它从小做到大，并且做到盈利就不容易。在这个过程中有很多路要走，不免要遇到数不清的岔路，任何一次错误的选择都可能使原本看上去不错的公司运营不下去而关门大吉，因为小公司对抗大公司时是不能有任何一次失误的。执行力是保证正确的决定能够最终实现的因素。判断力和执行力很大程度上来自于经验。创业的年轻人天生具有非凡的判断力和执行力不容易，为了保证一个起步良好的公司能够成功，一般风险投资家在投资的同时，要为公司寻找一位专业的CEO，就是这个目的。真正具备这些条件已经很不容易了。而一个初创公司的成功很大程度上还要看外部环境好不好，很多很有前途的公司因为创办的时机不对，也会随着经济大环境的衰退而夭折。比如2000年成立的公司就鲜有成功的。这样，能生存下来的公司就凤毛麟角了。最后，也是最重要的，创业者必须有好运气。当一个小公司成功上市后，股票能涨上去的又只有百分之二到三。大部分公司上市后股价平平，甚至不如上市价（即在中国常说的原始股价）。根据美国证监会的规定，一个公司上市后员工（包括创始人自己）的股票在180天以后才能卖。因此，一个公司上市180天后，股价会大跌，因为员工能卖股票使得该公司股票可能供大于求。因此，通过创业成功能发大财的人终究是极少数。

-----

由于生活所迫，硅谷的人在外人眼里都相对急功近利和唯利是图。在硅谷不提供股票期权的公司，几乎找不到技术人员。按规定，一个雇员工作满一年就能按期权的价钱买下股票（这个过程叫Exercise），因此形成了一种在某公司工作满一年，拿到股票期权立刻走人，再到第二家、第三家公司的风气。如果说风险投资是通过分散投资来降低成本，那么很多硅谷雇员这是分散他们的生命来期望有朝一日在一家公司能中上硅谷彩券。在硅谷一两年换一个工作是很正常的，员工也就没有忠诚度可言。这不是个人的问题和错误，是生活压力使然。

对创业者来讲，资历固然有用，但就重要性而言远排不进前几位。名气大、职位高的创业者经验丰富、交际广，容易找到钱和市场，但是闯劲远不如初出茅庐的牛犊那么足。在风险投资家看来，一个人的能力，包括处理人际关系的"软"能力（SoftSkills）是决定创业成败的关键。一个人的职位只代表过去，而财富和地位有时反而成为创业的负担。这也是为什么硅谷很多著名的公司如思科、苹果、Yahoo和谷歌，包括中国人创办的Netscreen和Webex都是原来默默无名的年轻人办成的，但是却很少听说那个成功公司是一位原某公司老总办的。

硅谷相对于美国其它地方是机会最多也是最均等的。因此虽然这里工作压力大，竞争激烈，还是不断有人愿意来。全世界很多国家想学习硅谷建立自己的科技园，但是至今没有一个能像硅谷这么成功的。我想这些科技园的管理者们，也许首先应该问问自己是否为创业者提供了同等的机会，还是将人按照财富、经历、名气预先分为了三六九等。（我对一些科技园按照学历、职称引进人才和投资额招商很不以为然。）自古英雄不问出处，今天落魄的学子可能就是明天业界的领袖。

公司内上下级之间虽然有等级的差异但是彼此是互相尊重的。（有些时候，一个优秀员工的级别和收入可能比他的直接上级还要高。）这样大家在一起共事就会觉得相对"舒服"一些，每个人都容易安心做好份内的事，而不是必须勾心斗角往上爬。硅谷的基因科技和Google在最近的好几年中，被评为全美国最适合工作的公司。硅谷公司对员工的约束也很宽松，一般不会阻止员工跳槽，更不会因此打官司。甚至当员工利用职务之便搞发明创造（只要不是偷技术）然后出去创业，硅谷公司（包括各研究所）也不会像美国其它地方公司追究得那么厉害的，而一般采用入股的方式做到双赢。思科创始人和斯坦福之间就是这样解决了知识产权问题。

-----

但是，今天的太阳公司，不仅人数规模、市场股值、办公面积远不能和当年相比（能人都走了，办公楼也卖了，股票一落千丈），而且彻底退出了IT领域霸主之争。太阳公司从1982年成立到2000年达到顶峰用了近二十年时间，而走下坡路只用了一年，足以令经营者为戒。

在Google上市以后，华尔街一度担心Google是否会重复网景公司的先例，最终被微软靠捆绑手段击败。Google的共同创始人拉里.佩奇在一次会上谈到了这个问题，他的观点颇有新意而又切实可行。 佩奇的原话我已经记不清了，大意是讲，几乎所有的人都认为网景公司在微软捆绑推广自己的浏览器IE后，注定难逃破产的厄运。当然，微软这种非常规的竞争方法很厉害，但是，网景公司也有自己的问题，否则它有可能在微软的压力下生存并发展。网景公司在它的浏览器畅销到网络用户时，没有居安思危，它没有注意去控制互联网的内容，这样一来它失去了保护自己和反击微软的可能性。本来它最有可能成为雅虎。

-----

这里面要说几句"现成市场"的重要性，因为一个新兴公司不可能等好几年时间，等市场培养成熟才开始销售。事实上有很多失败的例子是技术、产品都很好，但市场条件不成熟。 比如当年甲骨文搞的网络PC，从创意到产品都不错，但是当时既没有普及高速上网，更没有强大的数据中心，因此失败了。直到十年后的今天，Google提出"云计算"的概念并建立了全球相联的超级数据中心，拉里o埃里森的这个梦想才可能成为现实。但是，没有一个小公司能等得起十年。

聪明的主导者会让出一些市场给第二、三名，以免惹上反垄断的麻烦。通常70%是一个魔法数字。一个主导者愿意强调自己是行业的领导者，这样可以给投资者和用户信心，但是永远会否认自己有垄断地位，以免给自己找麻烦。它们在提交到证监会和其它政府部门的官方文件中甚至会列举一些小的不能再小的竞争对手，表示自己在公平竞争。

诺威格定理决定了在一个市场占有主导地位的公司必须不断开拓新的财源，才能做到长盛不衰。到目前为止，开拓新的财源有效的途径只有两条，而胡乱的尝试倒有无数多种。被证明是可行的途径包括"扩展"（Leverage）现有业务和转型。

成熟期以后，很难在新的领域获得成功。最后的结论是，一个在某个领域特别成功的大公司一定已经被优化得非常适应这个市场，它的文化、做事方式、商业模式、市场定位等等已经非常适应，甚至过分适应自己传统的市场。这使得该公司获得成功的内在因素会渐渐地、深深地植入该公司，可以讲是这个公司的基因。当这个公司在海外发展分公司时，它首先会将这基因带到新的地方，克隆出一个新的公司。

不要以为成功的跨国公司内部是铁板一块，大家都是为了公司的利益，实际上大公司内部为了部门的利益也时常争得你死我活。

一旦新的业务和公司传统业务冲突时，一些公司甚至会牺牲掉新的业务。

同一个市场在不同的公司眼里是完全不同的东西。

红杉风投认为一个公司的基因在创办的一个月内就定型了，这也许有些夸张，但是一个成型的公司改变基因的可能却是非常小。越是以前成功的公司越是容易相信自己固有的基因是最优秀的。

公司的基因的决定作用如此之大，使得很多跨国公司都无法通过改变基因来逃脱诺威格宿命的厄运。这其实对整个工业界乃至我们这个世界是一件好事。就像自然界的任何事物都是从生到死不断发展的一样，一个公司、一个产业也应该如此。人类的文明和技术是不断进步的，旧的不去新的不来，只有清除掉阻碍我们进步的那些庞大的恐龙，才能为人类提供新的发展空间。从这个角度讲，一个昔日跨国公司的衰亡，也许是它为我们这个社会做的最后一次贡献。

-----

以职业教育而著名的哈佛商学院（HBS）其实把纽曼的这个理念发展到了极致。在这所全球最难进的商学院里，从没有考试。同学们互相学习获得的知识不比从教授那里得到的少。大家生活在一起，平时同吃同住，放假由学校组织到世界各地一起玩，那里的学生都是年轻、已经小有成就而又雄心勃勃的人。他们在宽松的环境下，可以自由地获取专业技能和社会知识，尤其是和人打交道的经验。可以毫不夸张地讲，在哈佛商学院里不能和同学们玩到一起的人是白交学费了。斯坦福在这方面当然没有哈佛商学院那么夸张，但是它给本科生一个类似的内紧外松自由发展的环境。

纽曼的教育方法要求受教育的人有很高的自觉性。俗话说近朱者赤，近墨者黑。如果一个大学大部分学生都是问题学生，而学校又不加管束，这个大学一定办得一团糟。所以很多州立大学，由于学生的来源参差不齐，很难实施纽曼的这个理念。和哈佛商学院一样，斯坦福大学的入学门槛都很高，它每年的招生人数只有伯克利的五分之一，来到这里的学生都是希望自己今后事业上有所成就，它们对知识的渴望和学习的主动性是不用人担心的。斯坦福大部分本科生，学习能力很强，能很快掌握专业知识，这样就有时间和精力去学习立足于社会的基本知识，也就是纽曼所说的Universal Knowledge。

纽曼教育方法成功的第二个关键因素是大学学生和文化的多样性。一个大学要想让它的学生掌握UniversalKnowledge，必须让他们有这方面的内容可以学习，也必须让他们互相之间有取长补短的可能性。大家可能有这样的体会，学习电脑的同学聚在一起常常谈论一些和计算机或者科技有关的话题，学习金融的在一起常常谈论对经济的看法。如果一个大学的都是由同一类年轻人构成，他们取长补短的结果不过是补充了专业知识，而不是Universal Knowledge。麻省理工学院、加州理工学院（CalTech）和卡耐基梅隆大学等优秀的大学虽然在工程上不比斯坦福差，但是无论是专业、课程和生源都太单一化。一个进入了麻省理工学院的高中毕业生很明确是为了学习理工的，而他们周围的同学也是如此。这些年轻人在一起不断交流，彼此在技术上越来越精深，内境逾宽、外延逾窄。我和麻省理工学院的一些博士生谈论过各种浏览器的好坏，他们不和你谈微软的IE或者Mozilla的火狐，而是Unix用户更常用的字处理器Emacs下一个很小的浏览网页的功能，这个东西不仅不好用，而且在全世界用它的网民连万分之一都不到。他们和你谈的是里面技术上谁实现的好。这些人以后可以是很好的科学家和工程师，但是很难创业。斯坦福大学则不同，它的学生来源非常多样化、多元化。他们从文理、工程、医科、商业到法律什么都有。很多人到了斯坦福并不把自己限定在一个专业上。可以想象，一个计算机博士在和一个住院医生谈论浏览器时，就必须用最通俗的语言和他交流，而不是对各种技术评头论足。同时，他可以得到一个医生对浏览器的需求，比如使用的方便性、安全性等等。

很多人办公司都本着捞一把的想法，而不是做一番事业，这些人归根结底是创业的境界不够高。而这种境界是不可能从课堂上学到的，只有经常和世界级的人物在一起切磋，一个人的境界才能有质的提高，他才能站在巨人的肩上。在世界上至今找不到第二所大学能够让任何一个普普通通的学生不停地接触到工业界和商业界的领袖。

环境是可以影响人的。在斯坦福这样创业成风的环境中，一个计算机系或者电子工程系的博士生不想自己创业有时可能都会不好意思。而创业失败也没有什么可耻的。佩奇原来所在的计算机系数据库实验室，前前后后出了无数开公司的学生，以后的博士生一进去就耳濡目染办公司的事情。而在绝大多数大学里包括麻省理工学院并不是这样，导师希望学生只专注学术，而博士生则是以进入学术界为荣。

在这样一种前提下，一个科技公司如何能和华尔街合作得很好，让那些投资银行和基金公司成为自己的吹鼓手而不是杀手，便是一个艺术了。事实上，在美国一个上市公司的首席财务官它的首要任务并不是替公司管账，而是和华尔街沟通。他应该能用财务的语言，将他的公司的长远规划向华尔街讲清楚并树立华尔街对他的公司的信心。

-----
泡沫过去后会剩下什么东西？云计算的泡沫不是百年前荷兰的郁金香泡沫和英国的南海泡沫，泡沫过去之后，什么都没有留下，而更像是上个世纪60年代的电子泡沫和2000年前后的互联网泡沫，会留下很强的，引领IT产业新秩序的公司。比如，上个世纪60年代是电子时代，诞生了许多著名的日本电器公司，包括索尼，东芝和松下等；而互联网泡沫后，留下了雅虎，出现了Google，亚马逊和Facebook这样的优秀公司；云计算泡沫后，在众多倒闭公司的尸体上和极度浪费的基础建设上，会出现捡到大便宜的优秀云计算公司。

既然我们有历史的教训，为什么不能制止这种低效率的投资，和必定会破灭的泡沫？很遗憾，我们不能对人类期望过高。在投资上，我们人类中的大多数基本上是贪婪而不长记性的，而这大多数人不理性的行为，恰恰造就了能清醒认识规律并且遵从规律的英雄。

-----
不过有一点值得强调，那就是在互联网特别是移动互联网高度发达的时代，连接比拥有更重要。Airbnb不拥有任何一个房屋，它只是连接房东和租户的桥梁，但是它的生意比世界上任何酒店集团都大。类似，Uber和滴滴出行不拥有任何一辆出租车，但是因为连接了司机和乘客，客流量超过任何出租车公司。通过互联网共享资源是未来社会的特点。
