#+title: 百年孤独(Cien años de soledad)
#+options: toc:nil

https://book.douban.com/subject/6082808/

笔记本导出
百年孤独
加西亚·马尔克斯

file:images/one-hundred-years-of-solitude.png

** 一

多年以后，面对行刑队，奥雷里亚诺·布恩迪亚上校将会回想起父亲带他去见识冰块的那个遥远的下午。那时的马孔多是一个二十户人家的村落，泥巴和芦苇盖成的屋子沿河岸排开，湍急的河水清澈见底，河床里卵石洁白光滑宛如史前巨蛋。世界新生伊始，许多事物还没有名字，提到的时候尚需用手指指点点。

何塞·阿尔卡蒂奥·布恩迪亚当初建功立业的雄心，迅速在磁铁迷狂、天文演算、炼金幻梦以及见识世上奇观的热望中消磨殆尽，曾经勇于开拓、仪表整洁的他，变成一个外表懒散、不修边幅的男人。他那野蛮人一样的胡须，乌尔苏拉费尽力气才能勉强用菜刀收拾干净。甚至有人将他视为某种诡异巫术的牺牲品。然而当他将开荒的工具扛上肩头，倡议全体村民共同开辟一条将马孔多与新兴发明相连的捷径时，即使是那些深信他已发疯的人也丢下活计与家人而去跟随他。

很长时间内，马孔多处在一个半岛上成为根深蒂固的观念，这源于何塞·阿尔卡蒂奥·布恩迪亚远征归来后武断绘出的地图。他绘图时满怀怒气，故意夸大交通的艰难，以此来惩罚自己竟如此荒唐地选择了这样一个地方。“我们一辈子哪儿也去不了，”他向乌尔苏拉抱怨道，“我们注定要在这里活活烂掉，享受不到科学的好处。”

何塞·阿尔卡蒂奥·布恩迪亚照妻子的话做了。他往窗外望去，只见两个孩子赤脚待在阳光暴晒的菜园里，他感觉从那一刻起他们才开始存在，从乌尔苏拉的咒语中诞生出来。随即他内心发生了某种变化，某种神秘而明晰的力量将他从当下拉扯出来，带往记忆中从未涉足的所在。乌尔苏拉继续打扫，此刻她已经确信有生之年再也不会离开这个家园，而他一直凝视着孩子们，直到双眼湿润。他用手背擦干眼睛，深深地叹息一声，接受了现实。

然而自从那个下午叫孩子们帮忙取出实验器具，他便将自己最宝贵的时间留给了他们。在僻静的小屋里，墙壁上渐渐挂满荒唐的地图和奇异的图画。他教他们读写和算术，向他们讲起世界上的诸多奇迹，不光涉及自己已知的事物，还充分发挥想象力达到令人难以置信的极致。就这样，孩子们得知在非洲的最南端有平和而智慧的人民，他们唯一的消遣是坐下来沉思；得知爱琴海可以徒步穿越，只需从一个岛屿跳上另一个直到萨洛尼卡港。那些光怪陆离的课程深深铭刻在孩子们的记忆中，以至于多年以后，在政府军军官向行刑队下令开枪的前一刻，奥雷里亚诺·布恩迪亚上校又回想起三月里那个温暖的下午：父亲在物理课上倏然顿住，一脸着迷的神情，手停在半空中，眼神凝固，倾听着远远传来的高音笛、串铃和鼓的声音。吉卜赛人又来到了村里，推销孟菲斯城的智者们最新最惊人的发明。

** 二

十分钟后他回来了，手持祖父嗜血的长矛。村里一半的人都聚集在斗鸡场门口，普鲁邓希奥·阿基拉尔正在那里等着。他还没来得及反抗，何塞·阿尔卡蒂奥·布恩迪亚就以公牛般的力气投出了长矛，以第一代奥雷里亚诺·布恩迪亚当年猎杀本地老虎的准头，刺穿了他的咽喉。

就这样，他们开始了翻越山脉之旅。何塞·阿尔卡蒂奥·布恩迪亚有许多像他一样年轻的朋友，他们因要探险而欢欣鼓舞，都拆掉自家房子，带上女人孩子上路，朝着没有人向他们应许过的土地进发。出发之前，何塞·阿尔卡蒂奥·布恩迪亚将长矛埋在院子里，又把自己那些出色的斗鸡一只只砍下脑袋，深信这样能够给予普鲁邓希奥·阿基拉尔些许安慰。乌尔苏拉只带了一箱嫁衣、少许家用物品以及那个小匣子，匣里装着从父亲那里继承的金币。他们没有预定的路线，只想朝着与里奥阿查相反的方向进发，为的是不留下任何踪迹，不碰见任何熟人。

那天晚上，何塞·阿尔卡蒂奥·布恩迪亚梦见那个地方耸立起一座喧嚣的城市，家家户户以镜子为墙。他询问这是什么城市，得到的回答是一个他从未听说、也没有任何含义的名字，但那名字却在梦中神秘地回响：马孔多。

突然，她伸手摸了他一下。“好家伙。”她实实被吓到，说不出别的话来。何塞·阿尔卡蒂奥感到骨头里充满了泡沫，并伴随着一种无力的恐惧，以及哭泣的强烈欲望。女人没有给他任何暗示，但何塞·阿尔卡蒂奥整夜都在烟味中寻找她，那气味本是从她腋下逸出，也渗入到他的皮肤里面。他想一直和她在一起，想让她做自己的母亲，想永远待在谷仓里，想听她说“好家伙”，想让她再一次摸自己并对自己说“好家伙”。

何塞·阿尔卡蒂奥的女伴请他们别来打扰，于是那一对就地躺下，紧靠他们的床边。他人的激情唤醒了何塞·阿尔卡蒂奥的欲望。刚一触碰，女郎的骨头像是散了架，仿佛一盒多米诺骨牌哗啦啦一阵混响，她的肌肤在苍白的汗水中融化，她的眼睛盈满泪水，她的整个身体发出悲惨的哀叹，散逸淡淡的淤泥气味。但她以坚强的性格和可敬的勇气承受住了冲击。何塞·阿尔卡蒂奥感觉身体悬空，飞向极乐之境，心灵融化在柔情色欲的泉源里，那情欲涌入女郎的耳朵，又从她的口中变成语言涌出。那天是星期四。到星期六晚上，何塞·阿尔卡蒂奥往头上缠了块红布，跟着吉卜赛人走了。

庇拉尔·特尔内拉自告奋勇要在乌尔苏拉回来之前帮忙料理家务。奥雷里亚诺凭着对厄运格外敏感的神秘直觉，在看见她进门的瞬间灵光一闪。他意识到哥哥的逃走以及随后母亲的失踪都与她有关，尽管这无法解释，于是以一种沉默而强烈的敌意相待。

何塞·阿尔卡蒂奥·布恩迪亚出门看见一片喧嚷景象，好半天才从困惑中恢复过来。那不是吉卜赛人，而是和他们一样的男男女女，直发棕肤，说的是同样的语言，抱怨的是同样的痛苦。他们的骡子驮着食品，牛车满载着家具、家居用品，都纯粹是些普通的人间物事，毫无噱头地出售；他们贩卖的乃是日常现实。这些人来自大沼泽的另一边，距此只有两天路程。那些村镇里的人们每月都能收到邮件，见惯了各样改善生活的机器。乌尔苏拉没有追上吉卜赛人，却找到了丈夫在失败的远征中没能发现的通向伟大发明的道路。

** 三

马孔多变了样。跟着乌尔苏拉一起来的人四处宣扬它土地肥美、位置又比大泽区优越，于是昔日僻静的小村落很快变成繁华的城镇，有了手工作坊和店铺，还开通了一条永久商道。第一批穿尖头靴戴耳环的阿拉伯人就沿商道而来，用玻璃珠链交换金刚鹦鹉。何塞·阿尔卡蒂奥·布恩迪亚一刻也不能平静。他着迷于眼前的现实，认为这比自己广袤的幻想世界更为神奇，因而对炼金实验完全丧失了兴趣。他将漫长时日中饱受锤炼的材料搁置一旁，又变回了创业之初那个富于进取心的男子，那时他忙于设计街道规划新居，以保证人人享有平等权益。他在新落户的居民中赢得极大尊重，任何人铺设地基或修造围栏都要先咨询他的意见，大家还一致决定由他掌管土地的分配。

但何塞·阿尔卡蒂奥·布恩迪亚也明确表示，梅尔基亚德斯以他悠远的智慧和神奇的发明对村子的发展壮大作出过不可磨灭的贡献，马孔多的大门将永远对他古老的部落敞开。然而据那些周游各地的旅人说，梅尔基亚德斯的部落由于逾越了人类知识的界限，已从大地上被抹去。

从女孩那里也无法获得更多信息。从来到的那一刻起，她就一直坐在摇椅上吮手指，一双受惊的大眼睛打量着所有人，不曾流露出能听懂别人提问的迹象。她穿着已显破旧的黑色斜纹布衣裳，脚上是漆皮脱落的短靴。头发拢到耳后，用黑带子束住两个发髻。披肩上的图案沁染汗渍已无法辨认，一颗食肉动物的犬牙配上铜托系在右手腕上当作抵抗“邪眼”的护身符。青绿色的皮肤，圆滚紧绷如一面鼓的肚子，都显示出她体弱多病、忍饥挨饿的历史甚至要比自身的年龄更久远，然而食物端上来的时候，她却任凭盘子搁在腿上尝也不尝。

天亮的时候，印第安人卡塔乌雷失去了踪影。他姐姐比西塔西翁留了下来，认定了自己的宿命：就算逃到天边，这致命的疫病也会穷追不舍尾随而至。没有人理会她的惊恐。“要是不用睡觉，那再好不过。”何塞·阿尔卡蒂奥·布恩迪亚说，“那样我们就有更多的时间可用。”但印第安女人向他们解释，失眠症最可怕之处不在于让人毫无倦意不能入睡，而是会不可逆转地恶化到更严重的境地：遗忘。也就是说，患者慢慢习惯了无眠的状态，就开始淡忘童年的记忆，继之以事物的名称和概念，最后是各人的身份，以至失去自我，沦为没有过往的白痴。何塞·阿尔卡蒂奥·布恩迪亚笑得喘不过气来，认为这不过是又一种印第安人杜撰的疾病。乌尔苏拉为防万一，还是将丽贝卡和其他孩子隔离开来。

他们聚在一起不停地聊天，一连几个小时重复同样的笑话，甚至把阉鸡的故事演化到令人无法容忍的地步。那是一个讲不完的故事，讲故事的人问大家要不要听阉鸡的故事，如果大家说“要”，他就说没让大家说“要”，而是问大家要不要听阉鸡的故事；如果大家说“不要”，他就说没让大家说“不要”，而是问大家要不要听阉鸡的故事；如果大家都不说话，他就说没让大家不说话，而是问大家要不要听阉鸡的故事；而且谁也不许走，因为他没让人走，而是问大家要不要听阉鸡的故事。就这样继续下去，整夜整夜重复这一恶性循环。

就这样，人们继续在捉摸不定的现实中生活，只是一旦标签文字的意义也被遗忘，这般靠词语暂时维系的现实终将一去不返。

在这张唯一的全家福照片上，奥雷里亚诺身穿黑色天鹅绒正装，夹在阿玛兰妲和丽贝卡中间，那倦怠的模样和深邃的眼神与多年以后面对行刑队时一般无二。但那时他尚未感觉到命运的预示。

梅尔基亚德斯在破解诺查丹玛斯预言方面取得了深入进展。他每每研究到深夜，缩在退色的天鹅绒坎肩里艰难喘息，用雀爪般的小手在纸上胡乱涂写，手上的戒指都已失去曾经的光彩。一天夜里，他相信已破译出一则有关马孔多未来的预言。它会变成一座光明的城市，矗立着玻璃建造的高楼大厦，却再没有布恩迪亚家的丝毫血脉存留。“

她准备修建一间正式的客厅，一间更舒适通风的起居室，一间能摆下十二个座位的餐桌、容纳全家人和所有宾客进餐的饭厅，九间窗户都朝向院子的卧室，以及一条带扶栏的长廊，扶栏上有盆栽的欧洲蕨和秋海棠，能借着玫瑰花园遮挡正午的阳光。她准备扩建厨房，砌起两座炉灶；拆掉庇拉尔·特尔内拉曾在里面为何塞·阿尔卡蒂奥算命的那座旧谷仓，盖一座比原来大上两倍的新仓，保证家里永远不会缺粮。她准备在院子里的栗树荫下分建男女浴室，在院子深处建一座大马厩、一间铁丝网鸡舍、一个奶牛棚和一处四面开放供迷途鸟儿自由栖息的鸟舍。乌尔苏拉仿佛染上了丈夫的狂热，在十几个木匠和泥瓦匠的簇拥下发号施令，决定采光与通风事宜，随意分配空间而不受任何限制。

当天下午士兵就离开了。没过几天，何塞·阿尔卡蒂奥·布恩迪亚为里正找到一处房子。一切都恢复平静，只有奥雷里亚诺例外。里正最小的女儿蕾梅黛丝，论年龄足可当他的女儿，但她的影子正折磨着他身体的某个部位。那是一种肉体上的感觉，几乎在他行走时构成障碍，就像鞋里进了一粒小石子。

** 四

蕾梅黛丝走近问了几个关于小金鱼的问题，奥雷里亚诺无法回答，因为他猝然间喘不过气来。他想永远这样待下去，守着她百合般的肌肤，伴着她翡翠色的眼睛，听她以对待父亲的尊敬，每问一个问题都叫一声“先生”。梅尔基亚德斯坐在角落里的书桌前，画着难以索解的符号。奥雷里亚诺恨他。他做不了别的，只能对蕾梅黛丝说要把小金鱼送给她，结果吓得她飞快地逃出了作坊。

家里充满爱情的气息。奥雷里亚诺寄情于无头无尾的诗行。他把诗句写在梅尔基亚德斯送他的粗糙羊皮纸上，写在浴室的墙壁上，写在自己的手臂上，而所有诗句中都有蕾梅黛丝幻化的身影：蕾梅黛丝在下午两点令人昏昏欲睡的空气中，蕾梅黛丝在玫瑰无声的呼吸中，蕾梅黛丝在蠹虫如沙漏般的暗地蛀蚀中，蕾梅黛丝在清晨面包的热气中，蕾梅黛丝无所不在，蕾梅黛丝无时或缺。

丽贝卡那般喊叫已经无法保守秘密，阿玛兰妲发现了她的痴恋后开始发烧。她也在为没有回应的爱情而饱受折磨。她把自己关在浴室里，写下一封封狂热的信，以摆脱没有希望的激情带来的折磨，然后把信深藏在衣箱内。乌尔苏拉同时照顾两个病人，几乎忙不过来。她费尽心机长时间询问，也没能问出阿玛兰妲委靡的缘由。最终，她又灵机一动，撬开衣箱，便发现了用玫瑰色丝带系好的信，信内塞满新鲜的百合花瓣，信上泪痕未干，封封都写给皮埃特罗·克雷斯皮，但从未寄出。

他就在那里吃下比西塔西翁每天两次送去的食物，但最后那段日子他没了胃口，只吃蔬菜过活。很快他就显出素食者特有的孤清模样。他的皮肤上覆着一层柔软的苔藓，与那件不分季节永不离身的坎肩上滋生的相仿，他的呼吸间散发出熟睡动物的臭气。

一个星期四，在叫他去河边之前，奥雷里亚诺听见他说：“我已经发热病死在新加坡的沙洲上。”那天他下水时弄错了路线，直到第二天早上才在下游几公里的地方被找到，尸身搁浅在一处明晃晃的河湾里，一只孤零零的秃鹫落在他肚子上。

死去多年以后，普鲁邓希奥·阿基拉尔对活人的怀念如此强烈，对友伴的需求如此迫切，对存在于死亡之中的另一种死亡的迫近又是如此惧怕，最终对他最大的冤家对头萌生出眷恋。他找了很久。他向里奥阿查的死人们问起他，向从巴耶杜帕尔、从大泽区来的死人们问起他，但没人知道。马孔多对亡灵来说是一处未知之地，直到梅尔基亚德斯死后，在五颜六色的死亡地图上用一个黑点标出。何塞·阿尔卡蒂奥·布恩迪亚与普鲁邓希奥·阿基拉尔一直聊到天亮。

星期四他又出现在作坊里，一副大祸临头的痛苦神情。“时间这个机器散架了，”他几乎哭了出来，“而乌尔苏拉和阿玛兰妲还在那么远的地方！”奥雷里亚诺像对待小孩一样训斥了他，他显出顺从的样子。他花了六个小时观察各种事物，试图找出一分一毫与前一天的不同之处，期待发现某种变化能证明时间的流逝。他整夜睁着眼躺在床上，呼唤普鲁邓希奥·阿基拉尔、梅尔基亚德斯以及所有的死人来分担他的忧虑。但没人出现。星期五，他在谁都还没起床时又去观察外界的状况，最后彻底确认了仍是星期一。

** 五

当奥雷里亚诺和庇拉尔·特尔内拉的儿子出生后被送到家里，并在家中举行仪式命名为奥雷里亚诺·何塞，蕾梅黛丝决定把他认作自己的长子。她这种母性本能令乌尔苏拉惊讶不已。就奥雷里亚诺而言，他在她这里找到了生存的意义。他整日在作坊干活，蕾梅黛丝会在上午送去一杯不加糖的咖啡。

此时此刻连重议婚期的念头也会被视为大不敬，恋人关系就此永远停滞不前，沦为无人再去理会的倦怠爱情，仿佛昔日为了亲吻而熄灭灯火的情侣已被抛弃，屈从于死神的淫威。方向迷失，希望破灭，丽贝卡又开始吃土。

她站在吊床前，流出冷汗，感到五脏六腑都纠结在一起，而阿尔卡蒂奥用指肚抚摸她的脚踝，然后是小腿肚，然后是大腿，嘴里喃喃地说：“小妹妹，啊，小妹妹。”一股强似龙卷风却又惊人精准的力量将她拦腰举起，三两下扯去内衣，像撕裂一只小鸟一般，她得努力支撑着才不至于死在当场。她感谢上帝让自己拥有生命，随即失去神志，沉浸在由无法承受的痛苦生出的不可思议的快感中，扑腾挣扎于吊床这热气腾腾的泥沼间，喷出的血液被泥沼像吸墨纸一般吸收了。

因此他们到公墓对面租了一间小屋，屋里唯一的家具是何塞·阿尔卡蒂奥的吊床。新婚之夜一只蝎子钻进拖鞋蜇了丽贝卡的脚，她的舌头为此都麻痹了，但这并不妨碍他们度过一个惊世骇俗的蜜月。邻居们因惊醒整个街区的叫声而恐慌—每夜八次，连午睡时段也有三次—祈祷那种肆无忌惮的激情不要侵扰死人的安眠。

他自己面对行刑队的时候，仍将无法理解一系列微妙又无可抗拒的偶然事件是如何将他引向那个结论的。蕾梅黛丝的死并未引起他所担心的震惊，而更像是一种沉郁的愤怒，渐渐转化为寂寞消极的挫败感，与当初他认命选择独身时的感受相仿。

当夜，在行刑枪声响起的同时，阿尔卡蒂奥被任命为镇上的军政首领。那些已成家的起义者甚至没有时间与妻子告别，只能任由她们从此自生自灭。

** 六

奥雷里亚诺·布恩迪亚上校发动过三十二场武装起义，无一成功。他与十七个女人生下十七个儿子，一夜之间都被逐个除掉，其中最年长的不到三十五岁。他逃过十四次暗杀、七十三次伏击和一次枪决。他有一次被人在咖啡里投毒，投入的马钱子碱足够毒死一匹马，但他仍大难不死。他拒绝了共和国总统颁发的勋章。他官至革命军总司令，从南到北、自西至东都在他的统辖之下，他也成为最令政府恐惧的人物，但从不允许别人为他拍照。他放弃了战后的退休金，到晚年一直靠在马孔多的作坊中制作小金鱼维持生计。他一向身先士卒，却只受过一次伤，那是他在签署尼兰迪亚协定为长达近二十年的内战画上句号后自戕的结果。他用手枪朝胸部开了一枪，子弹从背部穿出却没有损及任何要害部位。经过这一切，留下来的只有一条以他的名字命名的马孔多街道。然而据他寿终正寝前几年的自述，那天清晨他带着二十一个人投奔维多利奥·梅迪纳将军的时候，甚至连这事也没期望过。

一如染桌布、织绦带、绣孔雀那样，她耐心等待着皮埃特罗·克雷斯皮向内心的煎熬屈服。她盼望的时刻与十月不祥的阴雨一同到来。皮埃特罗·克雷斯皮拿过她膝上的绣筐，双手紧握她的手。“我不能再等了，”他对她说，“我们下个月就结婚。”阿玛兰妲触碰到他冰冷的双手时没有颤抖。她像只抓不住的小动物似的缩回手去，继续自己的活计。“别天真了，克雷斯皮，”她微笑着，“我死也不会和你结婚的。”

一天晚上，他唱了起来。马孔多在睡梦中惊醒，心神俱醉，那琴声不似这个世界所有，那饱含爱意的歌声也不会再现人间。一时间皮埃特罗·克雷斯皮看见镇上所有的灯火都亮了，唯独阿玛兰妲的窗前依旧黑暗。十一月二日，亡灵节，他弟弟打开店门，发现所有的灯都亮着，所有的八音盒都在奏乐，所有的钟表都停在一个永恒的时刻。在这纷乱的合奏中，皮埃特罗·克雷斯皮伏在店后的写字台上，双腕用剃刀割破，双手浸没在一盆安息香水里。

然而，当阿尔卡蒂奥还是个孤独的孩子时，时常担惊受怕，他经历了失眠症的肆虐，见证了乌尔苏拉的实干热情，何塞·阿尔卡蒂奥·布恩迪亚的疯癫，奥雷里亚诺的高深莫测，以及阿玛兰妲和丽贝卡之间的殊死对抗。奥雷里亚诺教他读写，但同时总想着别的事，仿佛一个陌生人。奥雷里亚诺的衣服小了，就送给他，让比西塔西翁裁改。阿尔卡蒂奥为着过大的鞋子、改小的裤子，以及自己女人般的臀部而深深苦恼。他从来没有像与比西塔西翁和卡塔乌雷用他们的语言交谈那样，与其他人自由地交流过。实际上梅尔基亚德斯是唯一关心他的人，给他念那些难以理解的手稿，教他银版照相技术。没有人想到他暗地里如何为梅尔基亚德斯的死哀哭，又以怎样的疯狂徒劳地钻研他留下的手稿，试图使他重返人间。

何塞·阿尔卡蒂奥已然低头负起婚姻的重轭。丽贝卡凭着不屈的性格、贪婪的情欲和执著的野心，吸纳了丈夫超常的精力，使他从一个游手好闲、寻花问柳的男人变成一头干活的巨大牲口。

数年以后，奥雷里亚诺·布恩迪亚上校审核地契时，发现从院落所在的小丘直到视野尽头所有的土地，包括公墓在内，都在他哥哥名下，而阿尔卡蒂奥在任职的十一个月内不仅收取地租，还向丧家索要在何塞·阿尔卡蒂奥的土地上下葬亲人的费用。

天亮的时候，经过军事法庭的即时审判，阿尔卡蒂奥被判处枪决，在公墓的墙前执行。在生命的最后两个小时里，他无法理解为什么自童年时代起一直折磨他的恐惧感消失了。他无动于衷地听着冗长的指控，甚至没想去展现自己刚刚获得的勇气。他想着乌尔苏拉，她这会儿应该和何塞·阿尔卡蒂奥·布恩迪亚在栗树下喝咖啡。他想着八个月大的女儿还没有名字，想着即将在八月出生的孩子。他想着桑塔索菲亚·德拉·彼达，昨天晚上他还给她留了一头鹿腌起来准备星期六中午吃；他想念她披散在肩头的发丝和她仿佛出自人工的睫毛。他想着他的亲人，并无感伤，只是在严格盘点过往时发现，实际上自己是多么热爱那些曾经恨得最深的人。

** 七

他开玩笑道，随即又严肃地补充一句，“今天早上他们押我过来的时候，我觉得这一切都已发生过。”实际上，当喧嚣的人群拦住去路，他一直沉浸在自己的思绪中，惊讶于短短一年间镇子就衰老如斯。巴旦杏树枝叶凋零；漆成蓝色的房子时而改漆红色，时而又改回蓝色，最后那颜色都变得难以辨别了。“你还能指望什么？”乌尔苏拉叹了口气，“时间过得很快。”“话是没错，”奥雷里亚诺附和道，“可也没那么快。”

当行刑队瞄准他的时候，怒气凝成黏稠苦涩的东西，麻痹了他的舌头又迫使他闭上眼睛。那一瞬间晨曦的银白色光芒隐没，他又看见了小时候穿着短裤系着领结的自己，看见了父亲在一个阳光明媚的下午带他走进帐篷见到了冰块。

何塞·阿尔卡蒂奥刚关上卧室的门，一声枪响震彻全屋。一道血线从门下涌出，穿过客厅，流到街上，沿着起伏不平的便道径直向前，经台阶下行，爬上路栏，绕过土耳其人大街，右拐又左拐，九十度转向直奔布恩迪亚家，从紧闭的大门下面潜入，紧贴墙边穿过客厅以免弄脏地毯，经过另一个房间，划出一道大弧线绕开餐桌，沿秋海棠长廊继续前行，无声无息地从正给奥雷里亚诺·何塞上算术课的阿玛兰妲的椅子下经过而没被察觉，钻进谷仓，最后出现在厨房，乌尔苏拉在那里正准备打上三十六个鸡蛋做面包。

在乌尔苏拉和军官们的坚持下，他无奈地又在床上躺了一个星期。那时他才知道他的诗稿并没有烧掉。“我想不用那么急。”乌尔苏拉向他解释，“那天晚上，我准备生火，就跟自己说最好还是等尸体送来了再说。”在身体初愈的恍惚中，奥雷里亚诺·布恩迪亚上校身边摆满了蕾梅黛丝落满尘灰的娃娃，他读起自己的诗来，生命中的关键时刻一一浮现。他又开始写诗。一个小时又一个小时，他远离这场徒劳战争中的惊涛骇浪，将自己与死亡擦肩而过的经历化作押上韵脚的诗行。他的想法由此变得分外清晰，经得起反复思索。

一个人的时候，何塞·阿尔卡蒂奥·布恩迪亚在一个有无穷房间的梦中得到慰藉。他梦见自己从床上起来，打开房门，走进另一间一模一样的房间，里面有同样铸铁床头的床、同样的藤椅和后墙上同样的救难圣母像。从这一间又进入另一间一模一样的，如此循环，无穷无尽。他喜欢从一间走到另一间，仿佛漫步在镜廊中，直到普鲁邓希奥·阿基拉尔轻拍他的肩头。于是，他一间间回溯，渐渐苏醒，他原路折返，在现实的房间里与普鲁邓希奥·阿基拉尔相会。然而一天晚上，就在他被拖回床上两个星期之后，普鲁邓希奥·阿基拉尔在居中的房间里拍了他的肩膀，他便永远留在了那里，认为那才是现实的房间。

** 八

一天凌晨，就在阿玛兰妲拒绝赫里内勒多·马尔克斯上校的那段日子，奥雷里亚诺·何塞在几近窒息中惊醒，感觉她的手指像滚烫的虫子在焦灼地向他的腹部蠕动。他装作熟睡未醒，调整姿势为她除去一切障碍，随即感到那只未缠黑纱的手宛如失明的软体动物在他饥渴的水藻间潜游。两人都装作不知道双方心知肚明的事实，都装作不知道对方已知情，自那天晚上起被一种不容侵犯的默契紧紧联结在一处。奥雷里亚诺·何塞不听到客厅里时钟午夜报时的华尔兹就无法安眠，而那位容颜开始枯萎的盛年处女没等到梦游人钻进蚊帐也一刻不得安宁。

他没有一刻不想她。在那些被攻陷村镇的阴暗卧室里，特别是在那些最下贱的地方，找到她的影子；在伤员绷带上干涸血迹的味道中，觅见她的身形；在致命危险所激发的恐惧中，随时随地与她相遇。他曾经从她身边逃开，试图在记忆中将她抹去，为此不仅远走他方，还表现出被战友们归为莽撞的凶悍冒进。他越是在战争的粪坑里摔打她的形象，战争本身就越像阿玛兰妲。

将死尸掩埋到公墓里的命令刚被执行，他就指派罗格·卡尔尼塞罗上校去敦促建立军事法庭展开审判，他自己则担负起推行激进改革的艰巨任务，决心将江河日下的保守党政权摧毁殆尽。“我们要赶在党内政客前面。”他对自己的顾问说，“等他们睁眼面对现实的时候，看到的就是既成事实。”就在此时，他决定审查百年来的地契，便发现了他哥哥何塞·阿尔卡蒂奥强占土地又将其合法化的行径。他将那些文书一笔勾销。最后出于礼貌，他搁下手头的事务，抽出一个小时去见丽贝卡通知他的决定。

** 九

那天下午赫里内勒多·马尔克斯上校收到了奥雷里亚诺·布恩迪亚上校的电报。那是一次例行公事的谈话，没有为胶着的战局带来任何突破。谈话即将结束时，赫里内勒多·马尔克斯上校望着荒凉的街道、巴旦杏树上凝结的水珠，感觉自己在孤独中迷失了。“奥雷里亚诺，”他悲伤地敲下发报键，“马孔多在下雨。”线路上一阵长久的沉默。忽然，机器上跳出奥雷里亚诺·布恩迪亚上校冷漠的电码。“别犯傻了，赫里内勒多，”电码如是说道，“八月下雨很正常。”

他处决蒙卡达将军后第一次到马纳乌雷时，一刻也没延误，就去完成死于己手的受害者的遗愿。将军遗孀接过眼镜、徽章、怀表和戒指，却不允许他进门一步。“请别进来，上校。”她对他说，“在您的战争里您说了算，但在我家里我说了算。”奥雷里亚诺·布恩迪亚上校没有显出丝毫不快，但在私人卫队将那位寡妇的家舍夷为平地化为灰烬之后，他的心才恢复平静。“

敌视。“最好的朋友，”那时他常这样说，“是刚死去的朋友。”他厌倦了战事无常，身陷这场永无休止的战争的恶性循环中总在原地打转，只不过一次比一次越发老迈，越发衰朽，越发不知道为何而战、如何而战、要战到何时。

那个漫无尽头的夜里，赫里内勒多·马尔克斯上校追忆着在阿玛兰妲缝纫间里度过的那些一去不返的午后时光，奥雷里亚诺·布恩迪亚上校则苦苦挣扎了数小时，试图抓裂自己孤独的硬壳。自从那个遥远的午后父亲带他去见识冰块，他唯一的快乐时光就是在金银器作坊里打造小金鱼的时刻。他被迫发动三十二场战争，打破与死亡之间的所有协定，并像猪一样在荣誉的猪圈里打滚，最后耽搁了将近四十年才发现纯真的可贵。

说这话的时候，他没有想到结束一场战争要比发动它艰难得多。他花了将近一年时间以血腥手段强迫政府同意对起义军有利的和平条件，又用了一年时间说服自己党派的人接受这些条件。他甚至不惜运用超出想象的铁腕手段来镇压手下那些不肯出售胜利果实的军官的反叛，最终还是借助敌人的力量才令他们屈服。

他对时光在家中侵蚀出的种种令人心碎的细微创痕毫无察觉，而任何一个还保有鲜活记忆的人，像他这样长久离家后归来都本该有触目惊心之感。壁上石灰墙皮剥落，角落里肮脏蛛网絮结，秋海棠落灰蒙尘，房梁上白蚁蛀痕纵横，门后青苔累累，然而乡愁的精巧陷阱徒然虚设，这一切都没能勾起他的忆旧伤怀。他在长廊里坐下，裹着毯子，连靴子也没换，仿佛只想等待雨停。整个下午，他都在观看落在秋海棠上的雨水。

然而这一切都已被战争抹去。就连蕾梅黛丝，他的妻子，此刻也不过是某个足可做他女儿的人的模糊形象。他在爱的荒漠中结识的无数女人，把他的血脉播撒在整个沿海地区，却不曾在他的情感中留下任何痕迹。她们大多摸黑进房，黎明前离去，次日给他留下的只是肉体的些许厌倦感。唯一经受了时间和战争考验的，只有孩提时代他对哥哥何塞·阿尔卡蒂奥的感情，但那却不是基于友爱，而是源于同谋。

** 十

但乌尔苏拉无法掩饰那隐隐的不祥预感。她从家族漫长历史上重复命名的传统中得出了在她看来无可争辩的结论：所有叫奥雷里亚诺的都性格孤僻，但头脑敏锐，富于洞察力；所有叫何塞·阿尔卡蒂奥的都性格冲动，富于事业心，但命中注定带有悲剧色彩。

在换名游戏中保留下奥雷里亚诺第二这名字的男孩变成和祖父一样的彪形大汉，而那个叫作何塞·阿尔卡蒂奥第二的却长得像上校一样瘦骨嶙峋，两人之间仅存的共同点就是家传的孤独气质。或许正是这种体魄、姓名与性格的交错，才使得乌尔苏拉怀疑他们从童年时起就互换了身份。

从那以后的好几年里，他们几乎每天下午都见面。梅尔基亚德斯为他讲起世上万事，想把古老的智慧传授给他，却不肯译出手稿。“不到一百年，就不该有人知道其中的含义。”他解释道。对于这些交谈，奥雷里亚诺第二终生持守秘密。

他只需带上佩特拉·科特斯去养殖场，和她一起骑马在自己的土地上绕一圈，就足以令所有带着自己标记的牲畜无可救药地染上多产症。

这种事情给乌尔苏拉带来巨大烦扰，在那段时间却时常发生。马孔多沉浸在一派奇迹般的繁荣景象中。泥巴和芦苇盖成的屋子已经被配有木制百叶窗和水泥地面的砖石建筑所替代，后者更有利于散去午后两点令人窒息的酷热。何塞·阿尔卡蒂奥·布恩迪亚时代的旧村庄唯一的残留，就是那些覆满灰尘的巴旦杏树，它们忍耐得了最恶劣的环境，而清澈见底的河里那些史前巨石都被何塞·阿尔卡蒂奥第二疯狂的长柄锤砸成了粉末，为的是清理河道开发航路。

从她纯粹的实用主义观念出发，她实在难以理解上校的生意意义何在：用小金鱼换来金币，随即把金币变成小金鱼，如此反复，卖得越多活计越辛苦，却只是为了维持一种不断加剧的恶性循环。实际上上校在乎的不是生意，而是干活本身。他必须全神贯注地投入，嵌上片片鱼鳞，用红宝石微粒镶鱼眼，锤出鱼鳃，添上尾鳍，再没有余暇为战后的失落而烦恼。这门精密的手艺极其耗费心神，令他在短短时间内比在整个战争年代衰老得更甚。不变的坐姿令他脊柱变形，精确到毫米的工艺使他视力受损，但不容丝毫分心的专注让他获得了心灵的平静。

沉默寡言的奥雷里亚诺·布恩迪亚上校对家中重新焕发的活力视若无睹，约略懂得幸福晚年的秘诀不过是与孤独签下不失尊严的协定罢了。

** 十一

到晚上七点，她仍穿着女王的盛装，在床上款待他。他结婚已近两个月，她却立刻觉察出他的婚姻生活并不美满，心中因实现报复而涌出甜美的快意。然而两天后他没敢再来，而是请别人居间解决分手的善后事宜，她便明白自己得比预期更具耐心，因为他看起来已决心牺牲自我来维持表面的婚姻。

他凭着何塞·阿尔卡蒂奥·布恩迪亚翻越山脉创立马孔多那样的蛮勇，凭着奥雷里亚诺·布恩迪亚上校一次次徒劳发动战争那样的盲目骄傲，凭着乌尔苏拉一心延续家族血脉那样的疯狂执拗，寻找费尔南达时不曾有片刻气馁。

他在孤寂的作坊里听见军乐声声，礼炮齐鸣，钟声敲响感恩赞，以及家门口飘来演说的只言片语，他们正宣布用他的名字为街道命名。他愤怒得眼眶湿润，恨自己的软弱，自战败后头一回因为再没有年轻时的勇气发动一场血腥的战争，将保守党政府消灭干净而深感痛苦。

到了圣灰星期三，在众人四散回到沿海各地之前，阿玛兰妲让他们穿上主日正装，陪他们去了教堂。他们更多是感到有趣而非出于虔诚，被领到祭坛围栏前，由安东尼奥·伊莎贝尔神甫用圣灰在前额上画上十字。回到家后，最小的奥雷里亚诺想要清洗前额，却发现那痕迹无法消除，他的兄弟们也是如此。他们试过清水与肥皂，试过泥土和瓜瓤，最后用上了浮石和碱液，仍然无法除去那痕迹。但阿玛兰妲和其他去望弥撒的人都轻而易举地洗掉了。“

时光流逝，战事频仍，加上平日里无数的不幸，她都把丽贝卡给忘了。自始至终清楚地知道她还活着并在蛆虫窝里腐烂的人，只有日渐衰老却毫不心软的阿玛兰妲。当天亮时心中的寒意将她从孤枕上唤醒，她会想起她；当她用肥皂擦洗自己凋零的乳房和枯萎的腹部，当她穿上老年人雪白的细棉布裙和胸衣，当她更换手上缠裹赎罪伤痕的黑纱，都会想起她。无论何时，或睡或醒，从最庄重到最卑下的时刻，她都会想起丽贝卡，因为孤独已经为她筛选记忆，将生活在她心中累积的无数垃圾尽行焚毁，并净化、升华了其他记忆，即那些最苦涩的记忆，使其永远存留。

奥雷里亚诺第二决定接她回家好生照料，但他的好意遭到丽贝卡的断然拒绝。她辛苦多年忍受折磨好不容易赢得的孤独特权，绝不肯用来换取一个被虚假迷人的怜悯打扰的晚年。

她任凭他们七手八脚完成了工程，随后估算了花销，让一直陪伴自己的老女仆阿尔赫尼妲送去一把在最后一场战事结束后就不再流通，而她以为还通用的硬币。这时人们才明白她与世隔绝到了何种程度，也知道只要她一息尚存，便不可能将她从顽固的自闭中解救出来。

** 十二

上帝仿佛决心要试验人类惊奇的极限，令马孔多人时时摇摆于欢乐与失望、疑惑与明了之间，结果再没有人能确切分清何处是现实的界限。真实与幻景错综纠结，引得栗树下何塞·阿尔卡蒂奥·布恩迪亚的鬼魂也按捺不住，大白天在家中四处游荡。

整个城区被一圈金属网环绕，仿佛电网保护下的巨大鸡笼。在夏天凉爽的清晨，网上缀满烧焦的燕子，远远望去黝黑一片。仍然没有人知道他们目的何在，或者真的只是些慈善家，然而这些人已经闹得天翻地覆，令当初吉卜赛人造成的混乱相形见绌，而且更持久也更难以索解。他们掌握了往昔唯有造物主才拥有的力量，能调节降水量，加速收获周期，令河流从亘古不变的路线改道，将河中巨大的白石连同冰冷的激流都移到了市镇另一端的墓地后面。就是这一次，他们在何塞·阿尔卡蒂奥退色的墓上加筑了一层混凝土，以免尸体散发的火药味污染水源。

这些淫靡放荡的风月高手，古老技艺无一不精，药膏器具无所不备，能够使无能者受振奋，腼腆者获激励，贪婪者得餍足，节制者生欲望，纵欲者遭惩戒，孤僻者变性情。

她简化事物的本性有个惊人之处：她越是抛开时髦只求舒适，越是罔顾成规仅凭感觉行事，她那不可思议的美貌就越发动人心魄，对男人也越有诱惑力。

在香蕉林中弥漫着湿润气息又杳无尽头的小径间漫步，那里的寂静仿佛刚刚从别处迁来，崭新未用，因此还不能正常传递声音。有时候在半米的距离内听不清别人说话，但在种植园另一头却能听得清清楚楚。

美人儿蕾梅黛丝独自留在孤独的荒漠中，一无牵绊。她在没有恶魇的梦境中，在费时良久的沐浴中，在毫无规律的进餐中，在没有回忆的漫长而深沉的寂静中，渐渐成熟，直到三月的一个下午，费尔南达想在花园里叠起她的亚麻床单，请来家里其他女人帮忙。她们刚刚动手，阿玛兰妲就发现美人儿蕾梅黛丝变得极其苍白，几近透明。

如果不是奥雷里亚诺兄弟惨遭屠杀使恐怖代替了惊诧，或许人们在很长时间内都不会有其他的话题。奥雷里亚诺·布恩迪亚上校从未认为自己事先感知过预兆，但他的确在某种程度上早料到了儿子们的悲惨结局。

赫里内勒多·马尔克斯上校曾躲过三次暗杀，五次受伤大难不死，身经百战安然无恙，却败给了无尽的等待，屈服于凄凉的晚景，在一间借来的光线昏暗的屋子里想着阿玛兰妲。

另一些人更有骨气，在社会救济的荫庇下仍苦苦等待回音，他们或因饥饿而死，或怀着一腔怒火苟活，或在精致的荣誉粪堆中衰老腐烂。

** 十三

她想起以前，上帝还没让岁月缩水如同土耳其商人丈量花布时偷减尺寸，那时候不像现在这样。如今不仅孩子们长得更快，连人的情感也变了样。美人儿蕾梅黛丝连身体带灵魂才升天，凉薄的费尔南达就在角落里踱来踱去，为那些被卷走的床单愤愤不平。奥雷里亚诺们在坟墓里尸骨未寒，奥雷里亚诺第二就又点亮家中的灯火，聚上一群醉汉拉起手风琴，浑身浇透香槟酒，仿佛被害的不是基督徒而只是几条狗，仿佛用无数的操劳和无数的糖果小动物换来的这个疯人之家注定要沦为堕落的垃圾场。

咖啡在沸腾，他纯粹出于好奇，不带丝毫怀旧的风险，想着那个他从未知晓姓名，从未见过她生前模样的女人，因为她是在黑暗中跌跌撞撞摸上他的吊床。然而，有太多女人以同样的方式进入他的生活，在他脑海中成为茫然一片，他记不起是否就是她在初会的狂热中几乎淹没在自己的眼泪里，并且在死前不到一小时还信誓旦旦要爱他到死。他不再想她，也不再想其他女人，端着热气腾腾的咖啡走进作坊，打开灯来数点存在铁皮罐里的小金鱼。有十七条。自从决定不再出售，他仍然每天做两条，等凑够二十五条就放到坩埚里熔化重做。

最后当队伍全部走过，街上只剩下空荡荡一片，空中满是飞蚁，几个好奇的人还在茫然观望时，他又一次看见了自己那可悲的孤独的脸。于是他向栗树走去，心里想着马戏团。小便的同时，他仍努力想着马戏团，却已经失去记忆。他像只小鸡一样把头缩在双肩里，额头抵上树干便一动不动了。家里人毫无察觉，直到第二天上午十一点桑塔索菲亚·德拉·彼达去后院倒垃圾，忽然发现秃鹫正纷纷从天而降。

** 十四

如果不是阿玛兰妲不合时宜的死亡引发新的动荡，布恩迪亚家衰颓宅院中安静恬和的日子或许能持续很久。这一事件出乎所有人的意料。她虽然衰老又孤僻离群，但看起来依然结实挺拔，一如往常健康得好像磐石。

她已作好决定要为丽贝卡的尸身装殓整容，用石蜡掩盖脸上的裂纹，再用圣徒像的头发为她做一顶假发。她将装扮出一具美丽的尸体，让它身着亚麻寿衣，并为棺材套上带紫色花边的丝绒衬面，还要举行最体面的仪式下葬到蛆虫的所在。她满怀怨恨地制定了计划，但心中一个念头令她战惊：纵然出于爱意，她也无法做得比这更好。但她没受困惑搅扰，继续完善各种细节，最后超越了丧葬专家的水准，不啻精通死亡仪轨的大师。在这可怖的计划中唯一没有考虑到的就是，她尽管曾向上帝祈求，仍有可能死在丽贝卡之前。事实上，事情就这样发生了。

随着完工日期不可避免地临近，她意识到除非发生奇迹，才能将活计拖到丽贝卡死后，但干活时的专注令她得以保持必要的镇静来接受失败。也就在那时，她理解了奥雷里亚诺·布恩迪亚上校制成小金鱼随即又销毁的举动。世界不过是身外之物，她的内心不再为任何苦痛而波动。她深深遗憾没能在多年前获得这样的领悟，那时还来得及净化记忆，在崭新的光芒下重建世界，平静地唤回傍晚时皮埃特罗·克雷斯皮身上的薰衣草味道，并且将丽贝卡救出悲惨的境地，而这不是出于爱也不是出于恨，而是出于对孤独的深切理解。那天晚上梅梅言语中的怨恨令她惊讶，并非因为她在情感上受到触动，而是因为她感觉到自己的经历在另一个少女身上重演，她表面看来纯洁无瑕，实际上却已遭到怨恨的玷污。但那时她已完全接受命运，明知纠正的一切可能都不复存在，也并不觉得失落。

这时，阿玛兰妲刚刚将自己的物品分发给穷人，只留下死后要穿的一套换洗内衣和一双普通的灯芯绒便鞋放在简陋的粗木棺材板上。她没有忽略这个细节，因为她还记得奥雷里亚诺·布恩迪亚上校死的时候只剩下在作坊里穿的拖鞋，自己不得不给他买一双新鞋。

灯光还亮着的时候，就有一只夜间活动的蝴蝶在她头顶盘旋。时候到了。灯光熄灭，马乌里肖·巴比伦坐到了她身边。梅梅感觉自己在惶然不安的沼泽中挣扎，而且就像她梦到的那样，只有那个身上带着机油味、黑暗中几乎看不见的男人才能拯救她。

** 十五

梅梅对穿越昔日着魔之地的旅行几乎毫无意识。她不曾看见铁路两侧遮天蔽日的香蕉种植园。她不曾看见美国佬的白房子，因尘土和酷热变得荒芜的花园，身穿短裤和蓝条衬衫在门厅里玩牌的女人。她不曾看见尘雾飞扬的路上满载着香蕉的牛车。她不曾看见如同鲱鱼般跃入清澈河水的少女，她们高耸的酥胸令火车上的乘客饱受折磨。她不曾看见工人居住的杂乱破烂的棚屋，马乌里肖·巴比伦的黄蝴蝶在那里盘旋，脸色青绿、瘦骨嶙峋的孩子坐在门口的便盆上，怀孕的女人们朝开过的火车高喊着污言秽语。这些飞速闪过的情景，当初在离校回家的路上曾令她兴奋不已，如今却无法在她心里激起一丝涟漪。种植园热烘烘的湿气消失了，火车穿过开满罂粟花，还矗立着西班牙大帆船烧焦的龙骨的原野，迎上与将近一个世纪前同样清凉的空气，驶向泡沫泛涌的肮脏大海边，驶向当年何塞·阿尔卡蒂奥·布恩迪亚梦想破灭的地方，而梅梅却不曾往窗外看过一眼。

梅梅握住她的手，跟了上去。那是费尔南达最后一次看见她，她正努力跟上修女的脚步，最后消失在修道院的铁栅后面。她仍在想念马乌里肖·巴比伦，想念他身上的机油味和身边的蝴蝶。她每一天都在想念他，直到多年以后一个秋天的早晨在克拉科夫一家阴森的医院里衰老而死，那时的她已改名换姓，终生一言未发。

不到三个月他们就获释了，因为政府与香蕉公司没能就哪一方应当负担囚犯在狱中的伙食达成协议。这一次工人的不满在于居住区缺乏卫生设施，医疗服务纯属欺骗，工作条件太过恶劣。另外他们还提出，公司从未支付现钞，总以代用券顶替，而那只能用来在公司的货栈购买弗吉尼亚火腿。

工人们厌倦了这些荒诞的诡辩，越过马孔多当局，直接上诉于最高法院。在那里操纵法律的魔术师们证明所有的指控都毫无效力，因为香蕉公司没有，从未有过，也永远不会有任何正式工人，一直以来都是招募临时工。由此，关于弗吉尼亚火腿、神奇药丸和移动厕所的谎言彻底破灭，法庭作出最终判决，颁布公告严正宣布根本不存在什么工人。

三个团的士兵踏着苦役犯划桨的鼓点行进，大地在他们脚下震颤。他们仿佛多头巨龙一般，在正午的阳光中呼出臭气。他们矮小，结实，粗鲁。他们像马一样流汗，发出太阳暴晒下的兽皮气味，带着内地人寡言的漠然和难以捉摸的神情。队伍走了一个多小时，但给人的印象似乎只是几个小队来回转圈，因为所有人都很相似，仿佛一个母亲生出的儿子，并且都同样呆滞地承受着背囊和水壶的重负、上了刺刀的步枪带来的耻辱、盲目服从与荣誉感之间的矛盾。

他喊叫后发生的事情并未令他产生恐惧，而是恍如幻觉。上尉下令开火，十四处机枪掩体立时响应。但一切宛似一场闹剧，仿佛机枪正在喷射的只是骗人的烟火，因为能听见急迫的枪声嗒嗒，能看见白炽的烈焰喷吐，却感受不到任何轻微的反应，听不到任何声音，甚至一声叹息。密集的人群仿佛瞬间石化，刀枪不入。突然，在车站一侧，一声垂死的呼号打破了着魔般的状态：“啊啊，妈妈呀。”一股翻天覆地的力量，一种火山爆发的气流，一阵大难临头的咆哮，在人群中以无比凶猛的势头猝然爆发。何塞·阿尔卡蒂奥第二几乎来不及抱起孩子，而他母亲和另一个孩子已经被四下奔逃的惊惶人群所吞没。

孩子看见一个女人双臂呈十字平伸，跪在一片神奇地未遭践踏的空地上。满脸鲜血的何塞·阿尔卡蒂奥第二在倒地的一刻将他推到那里，随后蜂拥而至的人潮淹没了空地，淹没了跪着的女人，淹没了旱季高远天空中的光线，淹没了乌尔苏拉·伊瓜兰曾售出无数糖果小动物的这个该死的世界。

只是当军方问及何时可以宣布签署协议，他望了望窗外闪电纵横的天空，摆出一副不置可否的表情。“估计要等到天晴。”他说，“只要雨还在下，我们的一切活动都取消。”此前三个月没有下过雨，正值旱季。但在布朗先生宣布他的决定后，整个香蕉种植区暴雨大作，何塞·阿尔卡蒂奥第二在回马孔多的路上正赶上这场暴雨。一个星期后雨仍未停。

** 十六

雨下了四年十一个月零两天。

看着他装门锁，修钟表，费尔南达不禁暗自担心他会不会也染上了且造且毁、且毁且造的恶习，就如同奥雷里亚诺·布恩迪亚上校做小金鱼、阿玛兰妲缝扣子做寿衣、何塞·阿尔卡蒂奥第二读羊皮卷、乌尔苏拉追忆往事那样。

环境如此湿润，仿佛鱼儿可以从门窗游进游出，在各个房间的空气中畅泳。一天早上乌尔苏拉醒来，觉得自己陷入一种恬静的恍惚中，叫人哪怕用担架也要将自己送到安东尼奥·伊莎贝尔神甫那里。就在此时，桑塔索菲亚·德拉·彼达发现她后背上密密麻麻全是水蛭。赶在乌尔苏拉的鲜血被吸干之前，她用未熄的木炭烫灼把水蛭一条条揭下来。家里不得不开沟排水，清除蟾蜍和蜗牛，这样才能晾干地面，撤去垫在床脚的砖块，重新穿鞋走路。

奥雷里亚诺第二带着自己的衣箱回到家里，心中确信不仅是乌尔苏拉，马孔多所有的居民都在等待雨停后死去。一路上，他看见他们坐在厅堂里，眼神迷茫，抱手胸前，感受着浑然一体、未经分割的时光在流逝。既然除了看雨再无事可做，那么将时光分为年月、将日子分为钟点都终归是徒劳。

随着谷仓存粮日渐匮乏，费尔南达的怨气也日益增长，偶尔的牢骚、少见的怨言终于爆发为势不可当的洪涛，在一个早上以仿佛吉他叠句的单调起始，一天里音调渐渐升高，音色越发丰富，韵律益显激越。奥雷里亚诺第二起初并未留心这反复的唠叨，直到次日早饭后才察觉那比雨声更流畅高昂的嗡鸣声，吵得他头昏脑涨。费尔南达在整个家中游走，痛诉满腹的哀怨，说自己原是照着女王的模子受的培养，结果却沦落成一个疯人院的女佣，有个游手好闲、崇拜偶像、放荡不羁、整天仰面躺着等天上掉面包的丈夫，而她却要累折了腰靠几个小钱维持这个用大头针撑起的家，从上帝开启新的一天到她晚上眼睛疼得像进了玻璃碴才上床睡觉，总有那么多事要做，总有那么多事要忍耐要纠正，却从没有人说一句“早上好，费尔南达”或“晚上睡得怎么样，费尔南达”，也从没有人哪怕是出于礼貌问一声她脸色为什么这样苍白或为什么早上起来眼圈发紫，

马孔多满目疮痍。街巷间的泥潭中残留着破烂家具，被红色百合覆盖的动物骨架，都是外来人潮留下的最后遗物，他们一拥而至又一哄而散。香蕉热潮期间匆忙盖起的房子都已废弃。香蕉公司撤走了一切设施。当初电网包围的城市只剩下一地瓦砾。那些木屋，那些午后常有轻松牌戏的清凉露台，都被飓风刮走，仿佛是多年后马孔多必将从世间被抹去的预演。

这时，她让他去卧室看一眼，他便看到了那头母骡。它和主人一样瘦得皮包骨，但也和她一样精神抖擞，神情坚定。佩特拉·科特斯用自己的怒气培育它，没有草料、没有玉米也没有树根时便把它安置在卧室，喂它棉布床单、波斯地毯、长毛绒床罩、天鹅绒窗帘，以及主教式大床上用金线刺绣、带真丝流苏的华盖。

** 十七

乌尔苏拉颇费了一番工夫，才兑现雨停就死去的诺言。雨天里她难得神智清明，八月后却频显清醒，那时开始刮起干燥的热风，令玫瑰萎谢泥沼枯涸，在马孔多遍撒滚烫的尘沙，将生锈的锌皮屋顶和百年的巴旦杏树永远覆盖。

她还发现，从墙壁到地基处处开裂，家具退色散架，房门脱轴，家中弥漫着一种在她那个时代无法想象的听天由命的悲戚氛围。她摸索着走过一间间空荡荡的卧室，听到白蚁蛀蚀木头低鸣不止、蠹虫在衣柜中沙沙大嚼，听到暴雨期间大肆繁殖的红色巨蚁挖掘地基时的毁灭之声。一天，她打开装圣像的箱子，里面跳出的蟑螂当即爬上身来，她不得不向桑塔索菲亚·德拉·彼达求助才得以脱身。箱里的衣服早已被咬噬成灰。“

何塞·阿尔卡蒂奥第二仍在研读羊皮卷，在他那蓬乱成团的须发间只能隐约辨出长着绿色苔藓的牙齿和木然的双眼。听出是曾祖母的声音，他转头往门口望去，努力挤出笑容，却在无意中重复了乌尔苏拉当年的一句话。“您还能指望什么？”他喃喃道，“时间过得很快。”“话是没错，”乌尔苏拉说，“可也没那么快。”话一出口，她便意识到正在重复奥雷里亚诺·布恩迪亚上校在死囚房里对自己说的话，再次在战惊中证实了时间并没有像她刚承认的那样过去，而是在原地转圈。

想起往昔，两人都把荒唐的欢宴、离奇的财富和毫无节制的私情当作妨碍，一同感慨浪掷了多少时光才找到共享孤独的天堂。两人在无儿无女的多年相伴之后疯狂相爱，奇迹般从桌上到床上都如胶似漆无比幸福，直到年老体衰时仍像小兔一样嬉戏，像狗一般打闹。

她死在圣星期四一早。人们最后一次帮她数算年龄是在香蕉公司时期，当时得出的结果在一百一十五到一百二十二岁之间。她被放进一口比当年装奥雷里亚诺的篮子略大的小棺材，只有很少的人出席葬礼，一方面是因为记得她的人已经不多，另一方面因为那天中午极其炎热，连飞鸟都昏头昏脑像霰弹一般纷纷撞向墙壁，撞破铁窗纱死在卧室里。

丽贝卡死于那年年底。毕生服侍她的女仆阿尔赫尼妲请求当局强行打开卧室的房门，她的主人已经在里面关了三天。人们看到她躺在孤寂的床榻上，像虾米般缩成一团，头发因生癣而落尽，大拇指含在嘴里。奥雷里亚诺第二负责料理了丧事，并打算把房子修葺好卖掉。然而那房子已破败得无可挽救，墙皮刚抹好即纷纷脱落，刷上再厚的灰浆也无济于事，只能眼看着杂草穿透地面、蔓藤侵蚀椽柱。

费尔南达闭门幽居的执著成为一道坚不可摧的堤坝，遏阻住乌尔苏拉积蕴百年的洪流。她不仅拒绝在热风经过时开门，还命人用十字木条钉死窗户，严格遵循娘家教导过着活死人的生活。她与隐身医生频繁的通信以失败告终。经过无数次拖延后，她在约定的日期和时间把自己关进卧室，头向北躺着，周身上下只裹了条白床单。到凌晨一点，她感到有人用浸过冰凉液体的手帕盖上自己的脸。等她醒来，阳光在窗前闪耀，她身上多了一道可怕的弧形伤口，从腹股沟一直延伸到胸前。

桑塔索菲亚·德拉·彼达履行了诺言，用菜刀砍下何塞·阿尔卡蒂奥第二的头，以保证他没有被活埋。两具尸体被放进同样的棺材，他们在死亡中重新变得酷似，就像童年时一样。奥雷里亚诺第二旧日的酒肉朋友在棺材上摆放了花圈，花圈的紫色缎带上写着一句悼词：让一让，母牛们，生命短暂啊。费尔南达对这一不敬举动大为光火，让人把花圈丢进了垃圾堆。在最后一刻的慌乱中，悲伤的醉汉们抬棺材出家门时弄混了，把两人各自下葬在对方的坟墓里。

** 十八

她觉得自己如此老迈、衰弱，离生命中的美好时光已如此遥远，竟开始怀念那些最不如意的时刻，而直到此时她才发现自己多么需要长廊里飘来的牛至香气、黄昏时的玫瑰芬芳，甚至渴望外乡人带来的野蛮生机。她本已心如死灰，在日常忧患的痛切打击下若无其事，却在怀旧伊始被击溃了防线。随着岁月的摧残，她对自怜自伤的需求渐渐沦为一种恶习。

奥雷里亚诺因此第二次出门上街。他只走了两个街区便来到了那间逼仄的药房，落满灰尘的橱窗里摆着带拉丁语标签的瓷瓶，一个宛似尼罗河水蛇般沉静美艳的姑娘按照何塞·阿尔卡蒂奥写在纸条上的药名给他拿了药。第二次看到的荒芜城镇在泛黄的街灯下犹显昏暗，仍像第一次那样并未唤起奥雷里亚诺的好奇。

** 十九

尽管刚结束长途跋涉，她却一天也没休息。她从丈夫骑摩托的行头里拣出一件旧粗布工装穿上，开始着手重整家宅。她把占据长廊的红蚂蚁赶走，使玫瑰复活，将杂草拔除，在扶栏上挂的花盆里重新栽下欧洲蕨、牛至和秋海棠。她率领一队木匠、锁匠和泥瓦匠补上地面裂缝，修好门窗合页，又将家具翻新，把里外墙壁刷得雪白。在她回来三个月后，屋里又充满了自动钢琴时代那种青春欢快的气息。家里从未有谁像她这般无论何时何地都能保持乐观，永远歌声不断舞步不歇，随时准备将陈腐的事物和习俗丢进垃圾堆。她扫帚一挥便抹去了守丧的惨淡记忆，将堆积在犄角旮旯里的一堆堆无用破烂和迷信物品扫地出门，仅仅出于对乌尔苏拉的感激才留下客厅里蕾梅黛丝的银版照片。“

她记得母亲曾在信中提到飞鸟的暴亡，因此特地将行程推迟几个月，搭上一艘中途在幸福群岛停靠的航船，在岛上精心选购了二十五对最好的金丝雀，准备用来重新装点马孔多的天空。这后来成了她众多失败举措中最令人遗憾的一项。随着鸟儿不断繁殖，阿玛兰妲·乌尔苏拉一对对放生，但它们乍出樊笼便立刻从市镇上飞走。她试图利用乌尔苏拉第一次扩建家宅时制作的巨大鸟舍吸引它们入住，却没能奏效。她用针茅草在巴旦杏树上搭鸟窝，又在屋顶撒草籽，还逗引笼中的鸟儿放声啼叫来挽留那些已出笼的同伴，却都归于徒劳，因为那些鸟儿全都毫不迟疑地振翅高飞，在空中打个转，只一辨出方位就立刻奔向飞往幸福群岛的归途。

她的丈夫加斯通一向不拂逆她的意愿，但他在那个可怕的中午一走下火车就已经明白，妻子作此决定完全出于对某种虚无蜃景的怀恋。

他向阿玛兰妲·乌尔苏拉要来这钱固然因为需要，但更多地是为了让她也以某种形式卷入自己的冒险，从而折辱她，占有她。尼格罗曼妲把他引向诱人的烛火映照下的卧室，引向那张因反复接客而脏污不堪的折叠床，引向她冷酷无情、精壮如母狗般的身体，她本打算像安慰受惊的孩子似的将他打发，不料遇上的却是一个勇猛异常的男人，搅得她五脏六腑都在巨震中错位。

奥雷里亚诺发表蟑螂宏论的那天下午，讨论最后在那些卖身糊口的女孩们家里结束，那是一家充满假象的妓院，位于马孔多郊区。老鸨是个笑容可掬的好心妈妈，有着喜欢开门关门的怪癖。她不变的微笑仿佛在嘲弄那些信以为真的主顾，他们真的把只在想象中存在的一切当作了实在，因为这里连可触可感的物品也同属虚假：家具坐上去便散架，唱机的空膛里藏了一只抱窝的母鸡，花园里全是纸花，日历上还是香蕉公司到来之前的年份，画框里的版画剪自从未出版过的杂志。连那些一听到老鸨招呼接客便从四邻赶来的羞怯小妓女，也同样当不得真。她们出现时并不打招呼，穿着五年前的印花小衣裳，怎样天真无邪地穿上也怎样脱下，在情爱的高潮则大声惊呼“好家伙，你看房顶都要塌了”，而一拿到那一比索五十生太伏就立即去老鸨那里买面包和干酪。每到这时老鸨的笑容更加欢畅，因为只有她知道那些食物同样并非真实。

他们谈起对工人的大屠杀，记忆变得更加扑朔迷离。每当奥雷里亚诺触及这个话题，不仅老鸨一人，一些比她年长的老人都会驳斥所谓工人被包围在广场、两百节车厢的火车满载死尸之类的谣言，并且坚决捍卫已然在法庭案卷和小学教科书中根深蒂固的说法：根本没有过什么香蕉公司。因此奥雷里亚诺和加夫列尔因着一种建立在无人相信的事实基础上的默契联结在一起，他们的生活被这些事实深深改变，他们在只余怀缅的末日世界的退潮中漂泊。

奥雷里亚诺笑了，双手将她拦腰抱起好像托着一盆秋海棠，仰面丢在床上。没等她反抗，他粗鲁地一把剥去浴衣，新浴后的胴体令他震撼不已，每一寸肌肤、每一丝茸毛，甚至连最隐秘处的痣斑他都在别处房间的幽暗中想象过。阿玛兰妲·乌尔苏拉奋力反抗，凭着训练有素的雌兽般的狡黠，如鼬鼠般扭动光滑、柔韧而芬芳的身体，同时试图用膝盖顶住他的腰，似蝎子般抓挠他的脸。但两人发出的声响极小，至多好像有人在敞开的窗户前观赏四月凝远的暮色时发出的轻叹。这是一场激烈的争斗，一场殊死的恶战，却好像与暴力无涉，因为其中只见似是而非的进攻，恍如幽灵的闪躲，缓慢、谨慎而庄重。于是在进攻间歇便有足够的时间让牵牛花再次绽放，让隔壁房间里的加斯通忘却关于飞机的梦想，他们俩就仿佛一双敌对的情侣在清澈的水塘深处寻求和解。在激烈而富于仪式感的争斗中，阿玛兰妲·乌尔苏拉想到刻意保持静寂更为反常，这比他们努力抑制的打斗声更容易引起隔壁丈夫的怀疑。她便抿着嘴笑出声来，同时并未放弃搏斗，不过防御时只是装模作样地撕咬，也渐渐不再扭动身体，最后双方都意识到彼此既是对手又是同谋，由此争斗沦为惯常的嬉闹，攻击变作爱抚。突然间，近乎玩耍或又一次恶作剧，阿玛兰妲·乌尔苏拉放松了防御，但当她被自己造成的后果吓住并试图应对的时候已经迟了。一种异乎寻常的震撼将她定在原处动弹不得，她的反抗意志被不可抵御的热切欲望压倒，她想要知道那些在死亡彼岸等待她的橙色呼啸和隐形球体究竟是什么。她只来得及伸出手臂摸索到毛巾用牙齿咬住，以免传出那撕心裂肺的牝猫尖叫。

** 二十

庇拉尔·特尔内拉死在藤摇椅上，那是在一个欢宴的夜晚，她当时仍在自己的乐园入口看门。根据她的遗愿，人们没有将她入棺，而是让她坐在藤摇椅上，由八条大汉用龙舌兰粗绳缒到舞池中央挖出的大坑里。那些混血姑娘身着黑衣，哭得脸色苍白，按她们即兴想出的告别仪式纷纷摘下耳坠、胸针和戒指扔到墓穴中，随后用一块全无姓名日期的墓碑封住，在上面用亚马逊山茶堆成小丘。而后她们将动物全部毒死，用砖头和灰泥封牢门窗，这才带着自己的木衣箱各奔他乡，箱内贴满了圣徒像、杂志彩画，以及那些遥远而神奇的露水情人的肖像，他们或屙钻石，或吃人肉，或在公海上被尊为纸牌之王。

他对文字的狂热中既有崇高敬意又有冷嘲热讽，对自己的手稿同样采取这种双重态度。阿尔丰索为翻译这些手稿学会了加泰罗尼亚语，常把一卷稿子揣在兜里—里面总满满塞着各色剪报和奇特行业的手册—结果一天晚上在卖身糊口的女孩们家里丢失了。老智者得悉后，居然没有大动肝火，反而大笑不已，说那正是文学的自然归宿。

然而尽管他自己表面上并未察觉，那些在心绪转好后写下的热情洋溢的信件，却渐渐变成了灰心丧气的牧函。冬夜，汤锅在炉上沸滚，他却在怀念书店后堂的闷热，烈日照在蒙尘的巴旦杏树上的嗡响，午休的昏恹中响起的火车汽笛，正如他在马孔多时怀念冬天炉上的热汤，咖啡小贩的叫卖，以及春天里疾飞的云雀。两种怀念如同双镜对立，他夹在其间不知所措，无法再保持高妙的超脱，最后甚至劝说他们全都离开马孔多，忘掉他传授的一切世道人心知识，让贺拉斯见鬼去，还说不论在什么地方都要记住，过去都是假的，回忆没有归路，春天总是一去不返，最疯狂执著的爱情也终究是过眼云烟。

在那个连飞鸟也厌弃，长久的扬尘与酷热令人呼吸艰难的马孔多，奥雷里亚诺和阿玛兰妲·乌尔苏拉被爱情、被孤独、被爱情的孤独幽禁在因红蚂蚁疯狂啃噬的轰响而难以入睡的家里，他们是唯一幸福的生灵，世上再没有比他们更幸福的人。

他们的情爱技艺登峰造极，在高潮后的疲惫中也能另辟佳境。他们全心膜拜对方的肉体，发现情爱的低潮里存在着未开发的领域，那比欲望的空间更丰饶幽美。

奥雷里亚诺和阿玛兰妲·乌尔苏拉接受了篮中弃婴的说法，并非因为相信，而是因为能够借此脱离恐惧。随着产期的临近，两人渐渐变得仿佛一人，不分彼此，在那幢吹口气就会倒塌的房子里的孤寂中融为一体。他们退到一个仅能栖身的空间，从费尔南达的卧室，在那里他们得以享受情爱的静谧之美，到长廊的起点，在那里阿玛兰妲·乌尔苏拉坐下来为即将降生的孩子缝制小靴子和小帽子，奥雷里亚诺则在一旁回复加泰罗尼亚智者偶尔的来信。家中其他地方已在毁灭的重围中沦降。金银器作坊，梅尔基亚德斯的房间，桑塔索菲亚·德拉·彼达当年料理之下的原始而沉寂的王国，都已沉陷在一片家居密林的深处，没人胆敢涉险探入。在大自然吞噬之力的重围中，奥雷里亚诺和阿玛兰妲·乌尔苏拉仍然栽种牛至与秋海棠，保卫自己用石灰圈出的领地，为永恒的人蚁之战挖出最后的战壕。

而最后一道防线，奥雷里亚诺在迷上阿玛兰妲·乌尔苏拉时就已隐隐猜到，那便是梅尔基亚德斯并未按照世人的惯常时间来叙述，而是将一个世纪的日常琐碎集中在一起，令所有事件在同一瞬间发生。

到这时，他才发现阿玛兰妲·乌尔苏拉不是他的姐妹，而是他的姨妈，而当年弗朗西斯·德雷克袭击里奥阿查不过是为了促成他们俩在繁复错综的血脉迷宫中彼此寻找，直到孕育出那个注定要终结整个家族的神话般的生物。

这座镜子之城——或蜃景之城——将在奥雷里亚诺·巴比伦全部译出羊皮卷之时被飓风抹去，从世人记忆中根除，羊皮卷上所载一切自永远至永远不会再重复，因为注定经受百年孤独的家族不会有第二次机会在大地上出现。
