#+title: 诗歌和电影
** A Hard Rain’s A-Gonna Fall (Bob Dylan)

#+BEGIN_VERSE
Oh, where have you been, my blue-eyed son?
Oh, where have you been, my darling young one?
I've stumbled on the side of twelve misty mountains
I've walked and I've crawled on six crooked highways
I've stepped in the middle of seven sad forests
I've been out in front of a dozen dead oceans
I've been ten thousand miles in the mouth of a graveyard
And it's a hard, and it's a hard, it's a hard, and it's a hard
And it's a hard rain's a-gonna fall

Oh, what did you see, my blue-eyed son?
Oh, what did you see, my darling young one?
I saw a newborn baby with wild wolves all around it
I saw a highway of diamonds with nobody on it
I saw a black branch with blood that kept drippin'
I saw a room full of men with their hammers a-bleedin'
I saw a white ladder all covered with water
I saw ten thousand talkers whose tongues were all broken
I saw guns and sharp swords in the hands of young children
And it's a hard, and it's a hard, it's a hard, it's a hard
And it's a hard rain's a-gonna fall

And what did you hear, my blue-eyed son?
And what did you hear, my darling young one?
I heard the sound of a thunder, it roared out a warnin'
Heard the roar of a wave that could drown the whole world
Heard one hundred drummers whose hands were a-blazin’
Heard ten thousand whisperin’ and nobody listenin’
Heard one person starve, I heard many people laughin'
Heard the song of a poet who died in the gutter
Heard the sound of a clown who cried in the alley
And it's a hard, and it's a hard, it's a hard, it's a hard
And it's a hard rain's a-gonna fall

Oh, who did you meet, my blue-eyed son?
Who did you meet, my darling young one?
I met a young child beside a dead pony
I met a white man who walked a black dog
I met a young woman whose body was burning
I met a young girl, she gave me a rainbow
I met one man who was wounded in love
I met another man who was wounded with hatred
And it's a hard, it's a hard, it's a hard, it's a hard
It's a hard rain's a-gonna fall

Oh, what'll you do now, my blue-eyed son?
Oh, what'll you do now, my darling young one?
I'm a-goin' back out 'fore the rain starts a-fallin'
I'll walk to the depths of the deepest black forest
Where the people are many and their hands are all empty
Where the pellets of poison are flooding their waters
Where the home in the valley meets the damp dirty prison
Where the executioner's face is always well-hidden
Where hunger is ugly, where souls are forgotten
Where black is the color, where none is the number
And I'll tell it and think it and speak it and breathe it
And reflect it from the mountain so all souls can see it
Then I'll stand on the ocean until I start sinkin'
But I'll know my song well before I start singin'
And it's a hard, it's a hard, it's a hard, it's a hard
It's a hard rain's a-gonna fall
#+END_VERSE

** Mr Tambourine Man (Bob Dylan)

#+BEGIN_VERSE
Hey! Mr. Tambourine man, play a song for me
I'm not sleepy and there is no place I'm going to
Hey! Mr. Tambourine man, play a song for me
In the jingle jangle morning I'll come following you

Though I know that evening's empire has returned into sand
Vanished from my hand
Left me blindly here to stand but still not sleeping
My weariness amazes me, I'm branded on my feet
I have no one to meet
And the ancient empty street's too dead for dreaming

Hey! Mr. Tambourine man, play a song for me
I'm not sleepy and there is no place I'm going to
Hey! Mr. Tambourine man, play a song for me
In the jingle jangle morning I'll come following you

Take me on a trip upon your magic swirling ship
My senses have been stripped
My hands can't feel to grip
My toes too numb to step
Wait only for my boot heels to be wandering
I'm ready to go anywhere, I'm ready for to fade
Into my own parade
Cast your dancing spell my way, I promise to go under it

Hey! Mr. Tambourine man, play a song for me
I'm not sleepy and there is no place I'm going to
Hey! Mr. Tambourine man, play a song for me
In the jingle jangle morning I'll come following you

Though you might hear laughing, spinning, swinging madly across the sun
It's not aimed at anyone
It's just escaping on the run
And but for the sky there are no fences facing
And if you hear vague traces of skipping reels of rhyme
To your tambourine in time
It's just a ragged clown behind
I wouldn't pay it any mind
It's just a shadow you're seeing that he's chasing

Hey! Mr. Tambourine man, play a song for me
I'm not sleepy and there is no place I'm going to
Hey! Mr. Tambourine man, play a song for me
In the jingle jangle morning I'll come following you

And take me disappearing through the smoke rings of my mind
Down the foggy ruins of time
Far past the frozen leaves
The haunted frightened trees
Out to the windy beach
Far from the twisted reach of crazy sorrow
Yes, to dance beneath the diamond sky
With one hand waving free
Silhouetted by the sea
Circled by the circus sands
With all memory and fate
Driven deep beneath the waves
Let me forget about today until tomorrow

Hey! Mr. Tambourine man, play a song for me
I'm not sleepy and there is no place I'm going to
Hey! Mr. Tambourine man, play a song for me
In the jingle jangle morning I'll come following you
#+END_VERSE

** Desolation Row (Bob Dylan)
#+BEGIN_VERSE
They’re selling postcards of the hanging
They’re painting the passports brown
The beauty parlor is filled with sailors
The circus is in town
Here comes the blind commissioner
They’ve got him in a trance
One hand is tied to the tight-rope walker
The other is in his pants
And the riot squad they’re restless
They need somewhere to go
As Lady and I look out tonight
From Desolation Row

Cinderella, she seems so easy
“It takes one to know one,” she smiles
And puts her hands in her back pockets
Bette Davis style
And in comes Romeo, he’s moaning
“You Belong to Me I Believe”
And someone says, “You’re in the wrong place my friend
You better leave”
And the only sound that’s left
After the ambulances go
Is Cinderella sweeping up
On Desolation Row

Now the moon is almost hidden
The stars are beginning to hide
The fortune-telling lady
Has even taken all her things inside
All except for Cain and Abel
And the hunchback of Notre Dame
Everybody is making love
Or else expecting rain
And the Good Samaritan, he’s dressing
He’s getting ready for the show
He’s going to the carnival tonight
On Desolation Row

Now Ophelia, she’s ’neath the window
For her I feel so afraid
On her twenty-second birthday
She already is an old maid
To her, death is quite romantic
She wears an iron vest
Her profession’s her religion
Her sin is her lifelessness
And though her eyes are fixed upon
Noah’s great rainbow
She spends her time peeking
Into Desolation Row

Einstein, disguised as Robin Hood
With his memories in a trunk
Passed this way an hour ago
With his friend, a jealous monk
He looked so immaculately frightful
As he bummed a cigarette
Then he went off sniffing drainpipes
And reciting the alphabet
Now you would not think to look at him
But he was famous long ago
For playing the electric violin
On Desolation Row

Dr. Filth, he keeps his world
Inside of a leather cup
But all his sexless patients
They’re trying to blow it up
Now his nurse, some local loser
She’s in charge of the cyanide hole
And she also keeps the cards that read
“Have Mercy on His Soul”
They all play on pennywhistles
You can hear them blow
If you lean your head out far enough
From Desolation Row

Across the street they’ve nailed the curtains
They’re getting ready for the feast
The Phantom of the Opera
A perfect image of a priest
They’re spoonfeeding Casanova
To get him to feel more assured
Then they’ll kill him with self-confidence
After poisoning him with words
And the Phantom’s shouting to skinny girls
“Get Outa Here If You Don’t Know
Casanova is just being punished for going
To Desolation Row”

Now at midnight all the agents
And the superhuman crew
Come out and round up everyone
That knows more than they do
Then they bring them to the factory
Where the heart-attack machine
Is strapped across their shoulders
And then the kerosene
Is brought down from the castles
By insurance men who go
Check to see that nobody is escaping
To Desolation Row

Praise be to Nero’s Neptune
The Titanic sails at dawn
And everybody’s shouting
“Which Side Are You On?”
And Ezra Pound and T. S. Eliot
Fighting in the captain’s tower
While calypso singers laugh at them
And fishermen hold flowers
Between the windows of the sea
Where lovely mermaids flow
And nobody has to think too much
About Desolation Row

Yes, I received your letter yesterday
(About the time the doorknob broke)
When you asked how I was doing
Was that some kind of joke?
All these people that you mention
Yes, I know them, they’re quite lame
I had to rearrange their faces
And give them all another name
Right now I can’t read too good
Don’t send me no more letters, no
Not unless you mail them
From Desolation Row
#+END_VERSE

** 俾面派对 (Beyond)

#+BEGIN_VERSE
穿起一身金衣装
取消今天的工作
挤身缤纷的色彩
来让我去告诉你
派对永无真意义

不管相识不相识
尽管多 D Say Hello
不需诸多的挑剔
无谓太过有性格
派对你要不缺席

你话唔俾面
佢话唔赏面
似为名节做奴隶

种种方式的捆绑
请柬一出怎抵挡
想出千般的推搪
明日富贵与闭翳
也要靠你俾下面

你话唔俾面
佢话唔赏面
似为名节做奴隶

你都咪话唔俾面
咪话唔赏面
似用人脸造钱币

你话唔俾面
佢话唔赏面
似为名节做奴隶

你都咪话唔俾面
咪话唔赏面
似用人脸造钱币

至惊至惊你地唔俾面
至惊至惊你地唔俾面
至惊至惊你地唔俾面
至惊至惊你地唔俾面
#+END_VERSE
** Stairway to Heaven (Led Zepplin)

#+BEGIN_VERSE
There's a lady who's sure all that glitters is gold（有一位姑娘她相信闪光的都是金子）
And she's buying a stairway to heaven（她想买一架通往天堂的阶梯）
When she gets there she knows if the stores are all closed（她明白即使商店都已关门）
With a word she can get what she came for（只要轻启朱唇她就能得到所要的东西）
Ooh ooh and she's buying a stairway to heaven（她想买一架通往天堂的阶梯）

There's a sign on the wall but she wants to be sure（墙上分明有告示但她却想打听确实）
'Cause you know sometimes words have two meanings（因为你知道有些词一语双关）
In a tree by the brook there's a songbird who sings（在溪边的树上有只鸟儿在歌唱）
Sometimes all of our thoughts are misgiven（有时我们所有的想法都值得重新思量）
Ooh it makes me wonder（这使我迷茫）
Ooh it makes me wonder（这使我迷茫）

There's a feeling I get when I look to the west（眺望西方一种感觉油然而生）
And my spirit is crying for leaving（我的心灵哭喊着想要离去）
In my thoughts I have seen rings of smoke through the trees（我臆想树林中烟雾袅绕）
And the voices of those who standing looking（伴随着那些眺望者发出的呼喊）
Ooh it makes me wonder（这使我迷茫）
Ooh it really makes me wonder（这真的使我迷茫）

And it's whispered that soon（消息会被迅速地悄声传开）
If we all call the tune（如果我们也有掌调的机会）
Then the piper will lead us to reason（吹笛人会为我们指点迷津）
And a new day will dawn for those who stand long（新的一天为那些坚守许久的人们而破晓）
And the forests will echo with laughter（森林也答以带笑的回音）
Ooh

If there's a bustle in your hedgerow don't be alarmed now（别惊慌如果灌木中传来喧嚷）
It's just a spring clean for the May Queen（那只是为五月皇后而做的春季扫除）
Yes there are two paths you can go by（有两条路你可以选择）
But in the long run（然而长远点说）
There's still time to change the road you're on（你仍有机会改变现在的路）
And it makes me wonder（这使我迷茫）
Ooh

Your head is humming and it won't go（你脑袋嗡嗡作响经久不绝）
In case you don't know（因为你不知道）
The pipers calling you to join him（那是吹笛人邀你与他同行）
Dear lady can you hear the wind blow（亲爱的姑娘你能听见风起的声音吗）
And did you know（你可知道）
Your stairway lies on the whispering wind（你的天堂之梯就横亘在这飒飒风中）
Ooh

And as we wind on down the road（当我们沿路蜿蜒而去）
Our shadows taller than our soul（影子高过我们的灵魂）
There walks a lady we all know（一位我们熟悉的姑娘走来）
Who shines white light and wants to show（她闪烁着白光要我们知道）
How evrything still turns to gold（怎么把世间万物变成金子）
And if you listen very hard（如果你细心聆听）
The tune will come to you at last（你最终会听到那曲调）
When all are one and one is all yeah（当万物合一一即万物）
To be a rock and not to roll（你就会成为磐石岿然不动）
And she's buying a stairway to heaven（她想买一架通往天堂的阶梯）
#+END_VERSE
** Do not go gentle into that good night (Dylan Thomas)

#+BEGIN_VERSE
Do not go gentle into that good night, 不要温和地走进那个良夜,
Old age should burn and rave at close of day; 白昼将尽,暮年仍应燃烧咆哮;
Rage, rage against the dying of the light. 怒斥吧,怒斥光的消逝。

Though wise men at their end know dark is right, 虽然在白昼尽头,智者自知该踏上夜途, 　　
Because their words had forked no lightning they 因为言语未曾迸发出电光,他们
Do not go gentle into that good night. 不要温和地走进那个良夜。 　　

Good men, the last wave by, crying how bright 好人,当最后一浪过去,高呼着他们脆弱的善行
Their frail deeds might have danced in a green bay, 本来也许可以在绿湾上快意地舞蹈,
Rage, rage against the dying of the light. 所以,他们怒斥,怒斥光的消逝。 　　

Wild men who caught and sang the sun in flight, 狂人抓住稍纵即逝的阳光,为之歌唱,
And learn, too late, they grieved it on its way, 并意识到,太迟了,他们过去总为时光伤逝,
Do not go gentle into that good night. 不要温和地走进那个良夜。 　　

Grave men, near death, who see with blinding sight 严肃的人,在生命尽头,用模糊的双眼看到
Blind eyes could blaze like meteors and be gay, 失明的眼可以像流星般闪耀,欢欣雀跃,
Rage, rage against the dying of the light. 所以,他们怒斥,怒斥光的消逝。　　

And you, my father, there on the sad height, 而您,我的父亲,在生命那悲哀之极,
Curse, bless, me now with your fierce tears, I pray. 我求您现在用您的热泪诅咒我,祝福我吧
Do not go gentle into that good night. 不要温和地走进那个良夜。
Rage, rage against the dying of the light. 怒斥吧,怒斥光的消逝。
#+END_VERSE
** 赛德克巴莱(Seediq Bale) 魏德圣

-----

花冈一郎：“头目，被日本人统治不好吗？我们现在文明地生活，有学校，有邮局，不必再像从前一样依靠野蛮的猎杀而生存……被日本人统治难道不好吗？”

莫那·鲁道：“被日本人统治难道好吗！男人被迫弯下腰来搬运木头，女人被迫跪下膝来帮佣陪酒，该领的钱全进了日本警察的口袋……我这个当头目的除了每天喝醉了假装看不见听不见，还能怎么样！邮局、商店、学校，什么时候让族人的生活变得更好过？反倒让他们感觉到自己有多贫穷了！”

花冈一郎：“头目，我们就再忍二十年好吗……”

莫那·鲁道：“再过二十年就不会再有赛德克人，不会再有猎场，孩子就全都变成日本人了！！”

莫那·鲁道：“达奇斯（花冈一郎），喝酒吧！回去以后喝他个大醉吧！……喝吧！我们酿的酒可以让人无拘无束，让人手舞足蹈、哭笑随性，大醉一场之后你就会懂了！回去吧！”

-----

花冈一郎：“您又不是不知道日本有多少军队……这么做只不过是白白牺牲而已！您上次不是还说日本人比森林里的……”

莫那·鲁道：“日本人比森林里的树叶还要繁密，比浊水溪里的石头还要多，但是我反抗的决心比奇莱山还要坚定！如果你所谓的文明是让我们卑躬屈膝，那我就让你们看一看野蛮的骄傲！……达奇斯，你这个从来不想了解自己民族的子孙给我听好，‘赛德克·巴莱’可以输掉身体，但是一定要赢得灵魂！！”

-----

塔道·诺干：“你明明知道这一战一定会败，为什么还要去打！”

莫那·鲁道：“为了就要被遗忘的图腾！你看这些年轻人白白净净的脸，没有赛德克人应有的纹面图腾，你忍心看他们死后的灵魂被祖灵遗弃？还是你觉得他们不够资格成为一个双手染血的‘赛德克·巴莱’？”

塔道·诺干：“……图腾？”

莫那·鲁道：“图腾！”

塔道·诺干：“用生命去换取图腾，那用什么来换回这些年轻的生命！！”

莫那·鲁道：“骄傲！！”

-----

莫那·鲁道：“十五岁那年，我第一次出草，我也紧张胆怯、手脚发抖，但是我的眼神如箭！挥下敌人首级的瞬间，我忘记了什么叫做害怕，因为我知道我将作为勇士回到部落参加欢庆的酒宴，因为我知道从今以后部落里的男女老少都将尊敬我的勇猛！可是这次不一样！今天我们虽然成功血祭祖灵，取得了走过彩虹桥的资格，但是我门接下来要面对的不是酒宴的欢庆，而是选择死亡的方式！早在起事之前你们就知道这种结果了，不是吗！孩子们，别急着害怕！你们今天表现得很勇猛，祖灵们一定都看到了。但接下来要面对的才是真正的战斗，是要让异族人吓破肝胆的战斗！森林的祖灵鸟正驱赶着吃腐肉的乌鸦，水汽后的阳光只会让彩虹更加艳丽。孩子们啊，不要害怕，祖灵会肯定我们是守护猎场的好战士，你们手上的血痕就是印记，你们已经是赛德克巴莱了！！记住，一定要保持骄傲！我们要一起通过彩虹桥！”

-----

莫纳·鲁道：“如果所谓的文明就是让我们卑躬屈膝，那么就让你看看野蛮的骄傲！”
** 闻香识女人(Scent of a Woman)

Frank: I’ll show you out of order. You don’t know what out of order is, Mr. Trask, I’d show you, but I’m too old, I’m too tired, I’m too ****in’ blind, if I were the man I was five years ago, I’d take a flame thrower to this place! Out of order? Who the hell do you think you’re talkin’ to? I’ve been around, you know? There was a time I could see, and I have seen, boys like these, younger than these, their arms torn out, their legs ripped off, but there is nothin’ like the sight of an amputated spirit. There is no prosthetic for that, you think you’re merely sendin’ this splendid foot solider back home to Oregen with his tail between his legs, but I say you’re executin’ his soul! And why? Because he is not a Baird man. Baird men, you hurt this boy, you’re gonna be Baird bums, the lot of you. And Harry, Jimmy, and Trent, wherever you are out there, **** you too!

斯莱德中校：让你见识见识什么是破坏规矩，你不知道什么叫破坏规矩，垂斯克先生，真该让你见识，可我太老了，太累了，我他妈的还是个瞎子。要是五年前，我会拿火焰喷射剂把这给烧了！破坏规矩？你以为在跟谁说话？我可是久经沙场，那时候我还能看得见，我看见的是象他们这么大，甚至还要小孩子们胳膊被炸断了，腿被截肢了，可但那些都不及丑陋的灵魂可怕，因为灵魂没有义肢。你以为你只是把这个好青年像落水狗一样的送回俄勒冈的老家？？你们泯灭的是他的灵魂！！为什么？！就因为他不够做一个拜尔德人？拜尔德人，你们若是伤害了这个孩子，你们就是拜尔德的混蛋，你们全是。哈瑞、吉米、特伦特，不管你们坐在哪，见你们的鬼！

Frank: I’m not finished. As I came in here, I heard those words: cradle of leadership. Well, when the bough breaks, the cradle will fall, and it has fallen here, it has fallen. Makers of men, creators of leaders, be careful what kind of leaders you’re producin’ here. I don’t know if Charlie’s silence here today is right or wrong, I’m not a judge or jury, but I can tell you this: he won’t sell anybody out to buy his future! And that my friends is called integrity, that’s called courage. Now, that’s the stuff leaders should be made of. Now I have come to crossroads in my life, I always knew what the right path was. Without exception, I knew, but I never took it, you know why, it was too damn hard. Now here’s Charlie, he’s come to the crossroads, he has chosen a path. It’s the right path, it’s a path made of principle that leads to character. Let him continue on his journey. You hold this boy’s future in your hands, committee, it’s a valuable future, believe me. Don’t destroy it, protect it. Embrace it. It’s gonna make you proud one day, I promise you.

斯莱德中校：我还没说完呢，我刚一进到这里，就听到那些话：”未来领袖的摇篮”。如果架子断了，摇篮也就掉了，它已经随落了。造就青年、培养未来的领袖的人们，看吧！要小心了，你们在培养什么样的领袖，我不知道！今天查理保持沉默是对还是错，我虽然不是法官，但我可以告诉你，他不会为了自己的前途而出卖任何人。朋友们！这就是人们常说的正直，这就是勇气，这才是未来领袖所具有的品质。现在我到了一个人生的十字路口，我一向知道哪条路是正确的，毋庸置疑，我知道，可我从没走它，为什么？因为它太艰难了。轮到查理了，他也在一个人生的十字路口，他选择了一条路，一条有原则、成全他人格的路。让他沿着这条路继续前行吧，这孩子的前途掌握在你们的手里，委员们，他会前途无量的，相信我，别毁了他！保护他！支持他！我保证会有一天你们会为此而感到骄傲！我保证。
** 低俗小说(Pulp Fiction) by Quentin Tarantino
[Ezekiel 25:17. "The path of the righteous man is beset on all sides by the inequities of the selfish and the tyranny of evil men. Blessed is he who in the name of charity and good will, shepherds the weak through the valley of the darkness. For he is truly his brother's keeper and the finder of lost children. And I will strike down upon thee with great vengeance and furious anger those who attempt to poison and destroy my brothers. And you will know I am the Lord when I lay my vengeance upon you]

以西结书第25章第17节。“正义的人的道路给邪恶的人自私和暴行的不公平所包围。以慈悲和善意祝福他，他带领弱者走出黑暗的山谷，他是兄弟的守护者，以 及是迷途孩子的寻找人。而对于企图毒害和消灭我的兄弟的人，我会怀着巨大的愤怒和无比的仇恨去杀死他们。当我复仇的时候，他们将知道我的名字是耶和华。

** 拆弹部队(The Hurt Locker)

你喜欢玩所有的毛绒玩具,你喜欢妈妈,喜欢爸爸,喜欢你的小睡衣.你什么都喜欢.是不是?知道吗,等你长大了,曾经喜欢的东西也许会变得不再特别,就像这个玩偶盒,你会发现那只是一片铁皮加一个人偶.那些原本钟爱的东西会渐渐被你遗忘,到了我这个年纪,钟爱的东西也许只剩下一两件了,对我来说只剩一件了.

** 林肯(Lincoln)(2012) by Steven Spielberg

罗盘可以指明前进的方向，但它不会告诉你路上那里有高山、湖泊、沼泽，如果你一味前行，可能永远到不了目的地。

** 致命魔术(The Prestige) by Chris Nolan

Every great magic trick consists of three acts. The first act is called The Pledge: the magician shows you something ordinary, but of course, it probably isn't. The second act is called The Turn. The magician makes his ordinary something do something extraordinary. Now, if you're looking for the secret...you won't find it. That's why there's a third act, called The Prestige. This is the part with the twists and turns, where lives hang in the balance, and you see something shocking you've never seen before.

每一项伟大魔术的完成，都与三个过程密不可分：一为“验证”，魔术师展示了看似平常、实则已经动过手脚的表演道具；二为“转移”，魔术师手中看似普通的事物，瞬间变得与众不同，这个时候，如果你想找魔术背后的秘密……那几乎是不可能的，这也是为什么还会有第三步；三为“蒙蔽”，这也是魔术中最关键的环节，是魔术师利用技巧进行掩饰的过程，一旦达成某种平衡，就会产生那种前所未见、让你无比震惊的现象--也就是魔术。

** 点球成金(Moneyball)

没错，我可能被炒掉。那样的话，我44岁只有高中学历，还很想送女儿上大学。而你才二十五岁，耶鲁大学毕业，还有很漂亮的见习履历。我想我们没有说到点子上，我们应该思考的问题是，你到底信不信我们会成功？你觉得我们还有必要向别人解释？不必，向任何人解释。

不，伙计，我可没付你七百万，洋基队付了你一般薪水。他们认为你就值那么多，他们付你三百五十万与他们对打。大卫，你已经三十七岁了，你我为何不开诚布公各取所需呢？我想榨干你最后一点棒球能力，你想继续留在赛场上。我付你薪水不是因为你以前的名声，而是你目前的能力。你很聪明，知道我们努力的目标，给年轻球员做个榜样，做个领袖。

你用四千一百万打造了一支打进季后赛的球队，没有Damon, Giambi, Isringhausen, Pena, 没有了他们，你还赢得了更多的比赛。你赢的场次和洋基队一样多，但是洋基队每赢一场花费一百四十万，你只用二十六万。我知道你不同意我的想法，但是第一个敢于打破陈规的人，必定会碰得头破血流。这是必然的，这不但威胁到他们的经营方式，他们的思维，还威胁到了比赛，真正受到威胁的是他们的生活和工作，威胁到他们的处世之道。每次发生这种事情，无论是一个政府，还是一种经营方式，无论主体是什么，那些大权在握掌控全局的人，都抓狂了。无论是哪个球队的经理，如果现在还不拆散自己的队伍，再按照你的模式重建，他们就是老顽固。到十月，他们就会坐在沙发上，眼睁睁地看着Boston Red Sox赢得世界职业棒球大赛。
** 让子弹飞(Let Bullet Flys)
看懂《讓子彈飛》这个信仰與人性並行的社會

#+BEGIN_EXPORT HTML
<iframe width="560" height="315" src="https://www.youtube.com/embed/aaVy2pDLz1Y" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe>
#+END_EXPORT

** Guess I’m Doing Fine (Bob Dylan)
#+BEGIN_VERSE
Well, I ain’t got my childhood
Or friends I once did know
No, I ain’t got my childhood
Or friends I once did know
But I still got my voice left
I can take it anywhere I go
Hey, hey, so I guess I’m doin’ fine


And I’ve never had much money
But I’m still around somehow
No, I’ve never had much money
But I’m still around somehow
Many times I’ve bended
But I ain’t never yet bowed
Hey, hey, so I guess I’m doin’ fine


Trouble, oh trouble
I’ve trouble on my mind
Trouble, oh trouble
Trouble on my mind
But the trouble in the world, Lord
Is much more bigger than mine
Hey, hey, so I guess I’m doin’ fine


And I never had no armies
To jump at my command
No, I ain’t got no armies
To jump at my command
But I don’t need no armies
I got me one good friend
Hey, hey, so I guess I’m doin’ fine


I been kicked and whipped and trampled on
I been shot at just like you
I been kicked and whipped and trampled on
I been shot at just like you.
But as long as the world keeps a-turnin’
I just keep a-turnin’ too
Hey, hey, so I guess I’m doin’ fine


Well, my road might be rocky
The stones might cut my face
My road it might be rocky
The stones might cut my face
But as some folks ain’t got no road at all
They gotta stand in the same old place
Hey, hey, so I guess I’m doin’ fine
#+END_VERSE
** 白日梦想家(The Secret Life of Walter Mitty)
美好的事物不要轻易惊扰。

#+BEGIN_VERSE
Beautiful things don't ask for attention.
#+END_VERSE

开拓视野，冲破艰险，洞悉所有，贴近生活，寻找真爱，感受彼此。 这就是人生的目的。

#+BEGIN_VERSE
To see the world,
things dangerous to come to,
to see behind walls,
to draw closer,
to find each other and to feel.
That is the purpose of LIFE.
#+END_VERSE

** Boots of Spanish Leather (Bob Dylan)
#+BEGIN_VERSE
Oh, I’m sailin’ away my own true love
I’m sailin’ away in the morning
Is there something I can send you from across the sea
From the place that I’ll be landing?


No, there’s nothin’ you can send me, my own true love
There’s nothin’ I wish to be ownin’
Just carry yourself back to me unspoiled
From across that lonesome ocean


Oh, but I just thought you might want something fine
Made of silver or of golden
Either from the mountains of Madrid
Or from the coast of Barcelona


Oh, but if I had the stars from the darkest night
And the diamonds from the deepest ocean
I’d forsake them all for your sweet kiss
For that’s all I’m wishin’ to be ownin’


That I might be gone a long time
And it’s only that I’m askin’
Is there something I can send you to remember me by
To make your time more easy passin’


Oh, how can, how can you ask me again
It only brings me sorrow
The same thing I want from you today
I would want again tomorrow


I got a letter on a lonesome day
It was from her ship a-sailin’
Saying I don’t know when I’ll be comin’ back again
It depends on how I’m a-feelin’


Well, if you, my love, must think that-a-way
I’m sure your mind is roamin’
I’m sure your heart is not with me
But with the country to where you’re goin’


So take heed, take heed of the western wind
Take heed of the stormy weather
And yes, there’s something you can send back to me
Spanish boots of Spanish leather
#+END_VERSE
** The Times They Are A-Changin’ (Bob Dylan)
#+BEGIN_VERSE
Come gather ’round people
Wherever you roam
And admit that the waters
Around you have grown
And accept it that soon
You’ll be drenched to the bone
If your time to you is worth savin’
Then you better start swimmin’ or you’ll sink like a stone
For the times they are a-changin’


Come writers and critics
Who prophesize with your pen
And keep your eyes wide
The chance won’t come again
And don’t speak too soon
For the wheel’s still in spin
And there’s no tellin’ who that it’s namin’
For the loser now will be later to win
For the times they are a-changin’


Come senators, congressmen
Please heed the call
Don’t stand in the doorway
Don’t block up the hall
For he that gets hurt
Will be he who has stalled
There’s a battle outside and it is ragin’
It’ll soon shake your windows and rattle your walls
For the times they are a-changin’


Come mothers and fathers
Throughout the land
And don’t criticize
What you can’t understand
Your sons and your daughters
Are beyond your command
Your old road is rapidly agin’
Please get out of the new one if you can’t lend your hand
For the times they are a-changin’


The line it is drawn
The curse it is cast
The slow one now
Will later be fast
As the present now
Will later be past
The order is rapidly fadin’
And the first one now will later be last
For the times they are a-changin’
#+END_VERSE
** It Ain’t Me, Babe (Bob Dylan)

#+BEGIN_VERSE
Go ’way from my window
Leave at your own chosen speed
I’m not the one you want, babe
I’m not the one you need
You say you’re lookin’ for someone
Never weak but always strong
To protect you an’ defend you
Whether you are right or wrong
Someone to open each and every door
But it ain’t me, babe
No, no, no, it ain’t me, babe
It ain’t me you’re lookin’ for, babe


Go lightly from the ledge, babe
Go lightly on the ground
I’m not the one you want, babe
I will only let you down
You say you’re lookin’ for someone
Who will promise never to part
Someone to close his eyes for you
Someone to close his heart
Someone who will die for you an’ more
But it ain’t me, babe
No, no, no, it ain’t me, babe
It ain’t me you’re lookin’ for, babe


Go melt back into the night, babe
Everything inside is made of stone
There’s nothing in here moving
An’ anyway I’m not alone
You say you’re lookin' for someone
Who’ll pick you up each time you fall
To gather flowers constantly
An’ to come each time you call
A lover for your life an’ nothing more
But it ain’t me, babe
No, no, no, it ain’t me, babe
It ain’t me you’re lookin’ for, babe
#+END_VERSE
** OP『红莲の弓矢』

#+BEGIN_VERSE
（他们是猎物而我们是猎人！）
花谢凋零终遭人践 残瓣之名至今难辨
坠地之鸟顾影自怜 急盼风起以了夙愿
一味祷告纵然心虔 世间又能有何改变
改变当下唯有信念 殊死一战不畏艰险
尸横遍野 跨步再向前
独桀骜 耻不前 猪猡笑 刍狗喧
家畜安宁槛内 繁荣亦虚伪
饿狼只求自由 至死不悔！
身困牢笼中 屈辱的体验
酝出反攻 破茧而现
猎手奋战 城墙另一边
戮敌如风 血染满云天
盈满的冲动 迸发在心间
点燃其身 肆意地宣泄
贯穿于暮天 绯红之烈焰
艳若红莲 疾似箭
#+END_VERSE
** 猜火车 Trainspotting

#+BEGIN_VERSE
Choose life.

选择生活。

Choose a job.

选择一份活儿。

Choose a career.

选择一项事业。

Choose a family, Choose a fu*king big television,

选择一个家庭，选择一个巨他妈大的电视机，

Choose washing machines, cars, compact disc players,

and electrical tin openers.

选择洗衣机、汽车、镭射音响，还有电动开罐器。

Choose good health, low cholesterol and dental insurance.

选择小心保养自己的身体、低胆固醇和牙科保险。

Choose fixed-interest mortgage repayments.

选择固定利率的抵押贷款。

Choose a starter home.

选择政府提供的低价而体面的住宅。

Choose your friends.

选择你的朋友。

Choose leisure wear and matching luggage.

选择休闲装和配套的旅行包。

Choose a three piece suite on hire purchase in a range

of fu*king fabrics.

选择用分期付款买回同系列的他妈什么织物做的三套件西装。

Choose DIY and wondering who you are on a Sunday morning.

选择自己动手做，然后在某个星期天的早晨问自己我这是在哪儿呀。

Choose sitting on that couch watching mind-numbing

spirit-crushing game shows, stuffing fu*king junk food

into your mouth.

选择坐在那张睡椅上看让脑子发木脑浆被挤成稀屎状的体育节目，一边往自己嘴里塞他妈的垃圾食物。

Choose rotting away at the end of it all, pishing you last

in a miserable home, nothing more than an embarrassment

to the selfish, fu*ked-up brats you have spawned

to replace yourself.

选择在这一切的末尾烂掉，最后在一个破破烂烂的家里遭儿女唾弃，当初你用精子弄出他们来代替你，现在对这些自私的、满不在乎的小子们来说，你只是一个老厌物。

Choose your future.

选择你的未来。

Choose life.

选择生活。

But who would I want to do a thing like that?

但我是谁啊？我会想去做那些事情？

I choose not to choose life: I choose something else.

我选择不选择生活：我选择一些别的什么东西。

And the reasons? There are no reasons.

理由？没有理由。
#+END_VERSE
