#+title: Portfolio versus resume
[[https://matt.might.net/articles/what-cs-majors-should-know/][
What every computer science major should know]]

这个主题是上面这篇文章的一个部分，是portfolio重要还是resume重要，这个毫无疑问是前者。令我吃惊的是，作者说resume几乎没有办法证明程序员的能力，如果作者是这么认为的话，那么有可能其他人也会是这么认为的。这种观点不是科学观点而是社会观点，所以我觉得influencer的观点可以基本认为是正确的。

很早之前看过这篇文章，主要是关注里面和技术相关的内容。最近重新翻出这篇文章，关注的点不同，感觉又学习到不同的东西。


#+BEGIN_QUOTE
[!NOTE]
Having emerged from engineering and mathematics, computer science programs take a resume-based approach to hiring off their graduates.

A **resume** says nothing of a programmer's ability.

Every computer science major should build a **portfolio**.

A portfolio could be as simple as a personal blog, with a post for each project or accomplishment. A better portfolio would include per-project pages, and publicly browsable code (hosted perhaps on github or Google code).

Contributions to open source should be linked and documented.

A code portfolio allows employers to directly judge ability.

GPAs and resumes do not.

Professors should design course projects to impress on portfolios, and students, at the conclusion of each course, should take time to update them.

Examples
- [[http://ezyang.com/][Edward Yang's web site]].
- [[http://www.mjbshaw.com/][Michael Bradshaw's web site]].
- [[http://pydanny.blogspot.com/2011/08/github-is-my-resume.html][Github is my resume]].

#+END_QUOTE
