#+title: 权利和垄断演化机制
from 硅谷王川公号2022合集

3/ 当你做和别人一样的事情的时候，不管多努力，你本质是陷入一个为所在系统的权力垄断者服务的弱势地位。而且往往越努力，你为当权者付出的就越多，你摆脱路径依赖争取自身权力的能力就越弱。学技术和做产品的人不钻研市场和商业模式，就好像武将只学玩枪弄炮，而不研究如何用武力获得更多真正的实权。

5/ 权力的获取，要从不断思考实践“如何做不同的事，占据独特的生态位”开始。自己的不可替代性，和别人的可替代性，本质都是一个长期积累耕耘的过程，没有一步登天的捷径。有些脏活累活开始没人愿意干，只有你愿意干，在干活的过程中悄悄的获得了各种资源的占用和支配，时间长了，如果运气好，做着做着就会发现自身竞争力越来越强，潜在竞争者进入和取代你的壁垒越来越高。在某个节点产生非线性突变，于是垄断地位自然涌现，就大权独揽了。

6/ 什么样的脏活累活更有价值？任何可以扩大你和外界连接的网络的工作，或者增加你的特殊技能的工作，即使累一点，有一定风险，也会提高你的价值。而那些孤立封闭的，技术含量低，重复性高的工作，则要尽量避免。

7/ 权力产生于具体事务的运作中，尤其是涉及到人与人的关系，资源的调配。运作过程中形成一个新的网络，网络上的节点越多，掌控的资源越多，其形成的生态惯性就越难被外界阻挡。在新的，还不被关注看好的，但有巨大增长潜力的权力网络上提前占据有利生态位，是权力从无到有的成本最低的道路之一。

13/ 很多公司并购的逻辑，本质不是看其孤立的收入和利润，而是看到其在增加传播渠道上的价值。比如 FedEx 收购 Kinko's，Microsoft 收购 LinkedIn。

14/ 从这个角度看，一个实体如果在社交媒体上没有大量粉丝，意味着他/它放弃了一个重要且高效的传播渠道。而社交媒体上如果不用自己的品牌或者实名，很容易因为被单个平台封杀，而丧失了之前的全部积累。

15/ 很多做题家因为从来没有长期建设自己的传播渠道的意识，所以无法理解自己的弱势是因为缺乏自己可控的高效传播/连接渠道，而只能把注意力集中在做产品上，但这只是隔靴搔痒，始终无法根本上改变其弱势的现状。

25/ 斯大林在苏联最后掌握权力的路径，也有类似之处。“总秘书”这个职位，最初只是管理繁琐的行政事务，很多人看不上眼。斯在组织内有愿意干脏活累活的良好记录，所以列宁把这个位置交给他。但这个机构最后人马越来越多 (类似第三方应用)，触角和影响力越来越大。在扩权过程中可以做很多手脚，悄悄扩大对竞争者的优势 (比如斯把高层的电话交换系统直接安装在自己办公室里，方便偷听对手的谈话)。到最后，人单势孤，只爱发表演讲的托洛斯基面对斯的压制，毫无抵抗能力，节节败退。
