#+title: 怀孕准备
** 时间选择
最佳受孕年龄 根据研究，女性24～30岁、男性27～35岁，是最理想的生育年龄。因为，此时男女双方的体能状态达到颠峰，生殖器官的发育也较完善，不论精、卵的质量都较佳，有助培育健康的下一代。

最佳受孕季节 虽然怀孕的时节没有明显的宜和忌之分，但若从综合角度考虑，在每年的5～7月怀孕，来年3～5月生产是最理想的选择。从新生儿护理方面来看，此时出生的宝宝，刚好避开冬季流感高峰、但又尚未进入细菌、蚊虫容易滋生的夏天，在照顾与护理上都较为容易。对妈妈而言，此时正值春夏交替，蔬果产量充足，对于产后月子调理也相对轻松。

最佳受孕时间 一般来说，每个月排卵前3天至排卵后2天，是妇女最容易受孕的时期，也就是俗称的"易孕期"。 月经周期规律固定计算法：若月经周期为28天，排卵日为月经后第28-14=14天，故危险期是月经来的第8－19天。不过“最佳受孕时间”的说法并不科学，在整个月经周期中，排卵日前一天的受孕率最高，所以临床医生往往希望她们在基础体温升高前同房，以提高受孕率。由此可能误导出所谓的“最佳受孕时间”的说法。其实精子在体内可以存活1天-3天，卵子可存活24小时。而在一个月经周期中，如果仅有单次的同房，其受孕率较低，最高不会超过20%。所以不必刻意同房时间，只要增加在排卵前5天至排卵后2天的同房次数，就能提高受孕概率。更不要去过分地在意受精卵的质量，一般只有活力好的精子才能更早地进入卵细胞，这不是医生或者未准爸妈们自己能决定的。过分地在意受孕时间，可能会导致精神过度紧张，影响排卵和受精，从而导致不孕。找出夫妻双方生理节律高潮时间。

-----

研究证实，夫妻双方在身体不疲劳并情绪愉快时无忧无虑地同房受孕，这种身心俱佳的状态，会使内分泌系统分泌出大量有益于健康的酶、激素及乙酸胆碱等，使夫妻双方的体力、智能处于最良好状态中。这时，性功能最和谐，非常容易进入性高潮，形成优良的受精卵。反之，夫妻双方或一方身体疲惫或心情欠佳，都会影响精子或卵子的活力，不利于形成优良的受精卵，并影响受精卵的着床和生长，导致胎萎、流产或影响胎儿脑神经的发育。准备受孕前几天，夫妻双方一定都要充分注意身体休息，放松心情。同时，最好停止性生活5-7天，以保证精子的活力。准备受孕前，既不要性生活过频，也不要性生活过疏，这样都不利于受孕。过频会使精液稀薄，精子数量少;过疏会使精子老化，活力欠佳。

情绪不佳时不宜过性生活在生气、恼怒、吃惊、悲哀等情况下，最忌男女交合。如著名医学家孙思邈说：“人有所怒，气血未定，因以交合，令人发痛疽”。这是说，若人在恼怒时过性生活会得痛疽病；我国现存最早的医学经典著作《黄帝内经》里也论述了小孩的癫痫病与其母亲受孕时受惊吓有关系。

身体疲倦时不宜过性生活医学名著《千金要方》里说：“远行疲乏勿入房，为五劳虚损，少子”。这里明确告诫人们，若在身体疲劳时过性生活，可得虚损病，甚至不孕症。原因是性生活本身对人体就有很大的消耗，再加上劳累，久而久之就会使人出现虚损的情况。因此，在身体感到疲劳，无精打采时，最好不过性生活。若性欲较强，可在第二天清晨5～6点钟，双方得到充分休息后进行。

气候异常时不宜过性生活所谓气候异常，是指天气太冷或太热，以及电闪雷鸣、大风大雨时。一般地说，气候适宜，环境舒爽，对性生活有利；若气候剧变，超出了人们的调节功能，就会打破人体阴阳平衡，发生气血逆乱、邪气乘虚而入的情况。孙思邈在《枕中记》里说：“大寒大热，且莫贪色欲。”从临床观察来看，小儿的某些先天性疾患就与妇女受孕时不良的气候因素有关。

** 生活习惯
- 不要酗酒 酒精与肝脏伤害人体的严重性人人皆知，酒精对身体可能造成的伤害，还包括胰脏炎、心肌病变、食道及头颈部恶性肿瘤、股骨头坏死、大脑病变、神经病变、痛风等。因此，有长期大量饮酒习惯的准爸爸或准妈妈，为了自身健康，以及精卵质量最好能戒酒后再怀孕。酒喝多了不宜过性生活《黄帝内经》里明确指出：“醉以入房，欲竭其精，以耗散其真……故半百而衰也”，意思是说，人在酒后入房，性交过程中往往难以自制，必欲竭其精而后快，致使恣欲无度、肾精耗散过多，从而引起早衰。为什么肾精耗散多了会早衰呢？这是因为精是人始生的基础，生命活动的根本，人体寿夭的关键。
- 不要吸烟 尼古丁具有中枢神经兴奋、提神的作用，也是造成香烟成瘾的主要物质，尼古丁不但容易致癌，也会增快心跳速率、提高血压，及引起末梢血管的收缩， 长期易致心脏血管疾病。加上一氧化碳会阻碍氧气和血红素结合，造成体内缺氧，严重时甚至死亡。其它像是焦油、香烟中其它刺激物质，也都是慢性阻塞性肺疾病 及各种癌症的元凶。
- 不要熬夜 熬夜对人体坏处多多，除了会影响隔日的精神状况、让皮肤干燥、容易长黑斑、青春痘之外，也会连带造成免疫力下降，更重要的是，会让男性减少精虫的数量及活动力，也会影响女性荷尔蒙的分泌和卵子的质量。一但准备怀孕，最好能将熬夜作息调整过来，避免疲劳影响生理状态；另外，要保持乐观开朗的心情，因为有许多不孕问题，都跟精神抑郁有很大关系。
- 如果长期服用药物须先停药 有长期服用避孕药的妇女，考虑药物的抑制作用可能会影响受孕，最好在怀孕前3个月就停药，让身体恢复自然机能。此外，有服用慢性病或精神科药物的人，要先征询医师建议看能不能停药，或是换成低危险性的药物，以免造成胎儿发育异常或畸形。
- 尽量不要喝咖啡或茶 咖啡或茶是许多人每日必备的提神饮品，但咖啡因对人体的影响除了会干扰睡眠外，也因有利尿作用，会经由小便而流失较多的钙。此外，咖啡因会经由血液透入胎盘，尤其是怀孕妇女每天喝两杯以上的咖啡，可能会导致早产。妇女一旦决定怀孕，最好能开始减少含咖啡因饮料的摄取，特别是怀孕初期最好完全禁绝，以防止意外产生。
- 不要忽视生殖健康 女性生殖系统疾病较男性多见，特别是感染和炎症。其中像是性传播疾病（如：淋病），或是输卵管阻塞、子宫内膜异位等疾病，都会导致不孕。而男性如果患有生殖系统疾病，也会影响精子质量。因此，维护生殖系统的健康，将有助于受孕成功机率。

-----

怀孕前男的需要做哪些准备
- 运动，但要适度：健康阳光的运动男，当然可以期待他的精子质量与他的皮肤、心脏和肌肉一样优秀，但是，运动绝不是越多越好。有研究显示，运动狂男的身体会释放更多的类固醇激素，而这可能会影响受孕。
- 警惕热水浴和桑拿：睾丸产生精子需要比正常体温低1 ～ 1.5 摄氏度。高温对睾丸的生精过程有抑制作用，虽然只是暂时的。
- 保持他的营养均衡：没有原料，再好的精子工厂也造不出优质产品来。专家发现缺乏叶酸和锌元素会导致精子数量不足。平时注意摄入瘦肉、鱼类、牛奶、蔬菜，保证蛋白质、维生素和微量元素的供给，对健康的精子制造者来说是必不可少的。
- 给他吃有机食物：食物中残留的杀虫剂可能会影响精子的质量，一天当然没什么关系，但是长期积累的效果可就难说了。家中天天消费的米、面、油、蔬菜，尤其值得多花些钱买有机的。
- 避免忧郁和过度疲劳：一个长期处于忧郁和疲劳状态的男人，可能连性趣都所剩无几了，你还指望从他那儿获得优质的精子吗？
- 让他赶快戒烟：这可能是所有影响孕力的外界环境中最重要的一个环节了。吸烟能急剧降低男性(和女性)的生殖能力，以及受孕率。因为吸烟会减少精子的数量及活性。据统计，男烟民的精子计数比平均值降低17%。而被动吸烟的你同样深受其害，受孕率会明显降低。不过，已经证实的好消息是，戒烟的男性，精子计数提高800% ！
- 规范他的性习惯：如果你的男人不注意性卫生的话，受损伤的将是我们宝贵的孕力。因为如果性生活中发生了细菌上行感染，引起输卵管反复炎症，可能会导致输卵管阻塞，最终发生不孕。而如果他有性传播疾病，就更要抓紧治疗。因为性传播疾病会从两个方面引起不孕。一是引起前列腺炎、附睾炎、输精管炎和精囊炎，影响精子的贮存、存活及输出，结果造成男子不育；二是传染给女性，造成女性生殖系统的炎症，从而引起女性不育。不过，大多数性传播疾病只要及时就诊，是可以治愈的。
- 自行车座不妨考究点：如果他经常骑自行车，那很好，这是既环保又健康的健身方式。但是，如果他的自行车座是那种细窄的，则可能使前列腺和其他附性腺受到慢性劳损和充血，加重慢性炎症，影响精子形成。所以，需要换一个比较宽，能把压力分散到臀部的车座。

** 营养补充
- 维生素A：每日的建议量是800RE或是2,700单位，在怀孕中维生素A的需要量并没有明显的增加，所以无须额外补充。
- 维生素B6：对于年轻的孕妇、多胞胎、药物滥用的人还是需要每天补充2毫克。早期怀孕服用维生素B6对孕吐有帮助。
- 维生素B12：全素食者可能无法获得足够的B12，建议每天补充2微克。
- 维生素C：维生素C不足则可能导致怀孕早期破水。
- 叶酸：缺乏叶酸可能导致胎儿的神经管缺损，少了它可能增加流产、早产、胎儿生长迟缓的机会。因此，正常低危险性的育龄妇女，建议是每天补充0.4毫克，解决的方法可以多食用含叶酸的食物，或是口服补充叶酸。但高剂量的叶酸可能让身体无法反应出维生素B12的缺乏，长期缺乏维生素B12可能会造成神经永久的 伤害，因此不要超过1毫克。一般女性只要在孕前3个月起服用0.4mg~0.8mg的叶酸即可，可以选用单纯剂量的叶酸制剂，如斯利安、叶维胶囊等。而对于孕前有贫血的女性，也可以 使用复合维生素片。一些意外怀孕的准妈妈也不必担心是否少补了叶酸，叶酸在许多食物中广泛存在，正常饮食的妇女一般不会存在叶酸缺乏。
- 钙：孕妇及喂奶者每日的钙质建议量是1,200毫克，其实平日食物中的牛奶、起司都含有大量的钙，一片起司或是一杯牛奶大约含300毫克的钙，对一般孕妇来说，只要多喝牛奶或是吃奶酪应该不会缺乏钙。不过对于有乳糖不耐症的人来说，额外补充钙片就比较重要了。市面上的钙片一般含柠檬酸钙或是碳酸钙200毫克至500毫克，一天补充500～600毫克是比较适合的。最好在进食时吃，吸收比较好，而类固醇、菠菜、麦麸等则会影响钙质的吸收，最好避免同时与钙片一起服用。
- 铁：如果身体缺乏铁质，容易造成贫血，建议除了多摄取肝脏、豆类、蛋、梅子汁、谷类等富含铁的食物之外，建议每天多摄取30毫克的元素铁。服用铁剂时不要同时喝牛奶、茶、或是咖啡，胃片中的钙、镁成分会阻碍铁的吸收
- 锌：在动物实验中如果缺乏锌的话，可能会造成骨骼、神经系统异常，生长迟滞、甚至胎儿死亡。虽然在人类比较没有这种现象，不过如果给予血中缺乏锌的孕妇适当的补充，胎儿的体重会增加，如果铁的补充少于30毫克，就要适当的补充锌。

** 孕前检查
主要是下面三类:
- 基本项目：全血液计数检查，梅毒血清，B型肝炎，德国麻疹抗体，水痘抗体
- 选作项目：艾滋病，弓浆虫抗体，男性精液检查，女性卵巢功能检查，双方染色体检查，其它身体健康检查，性病筛检
- 接种疫苗：风疹疫苗，乙肝疫苗，甲肝疫苗，流感疫苗，水痘疫苗

*基本项目*
- 全血液计数检查（CBC）：检查白血球，红血球，以及血小板的数目及型态是否正常，平均红血球容积若低于80，有可能为地中海型贫血带原者──配偶需做血球检查，以免生下重度地中海型贫血的胎儿。　
- 梅毒血清（VDRL）：若罹患梅毒而未治疗，有可能产下失明或智障等先天异常儿。
- B型肝炎（HbsAg,HbeAg）： 若母亲为B型肝炎带原者，同时为高传染性，有可能传染给胎儿。
- 德国麻疹抗体（Rubella IgG）：孕妇若在怀孕早期感染德国麻疹，有可能产下智障耳聋或其它多重障碍的婴儿。
- 水痘抗体（Chicken pox Ab）： 怀孕早期如果感染水痘，胎儿可能产生先天性水痘症候群，会发生视网膜炎、脑皮质萎缩、水肾、皮肤及下肢萎缩 。

*选做项目*
- 艾滋病（HIV）：母亲怀孕若患有艾滋病，有可能传染给胎儿。
- 弓浆虫抗体（Toxoplasma IgG,IgM）：感染弓浆虫有可能产下小头畸形和智能低下的婴儿。
- 男性精液检查：禁欲两天后以手淫方式取出精液置于容器中，于半小时内送检。
- 女性卵巢功能检查：包括：TSH、LH、FSH、PRL。
- 双方染色体检查：筛检基因异常机率，若家族中曾出现遗传病史者会做进一步追踪。
- 其它身体健康检查：肝肾功能，血糖，尿酸，胆固醇，癌症筛检。抽血前需禁食8小时。
- 性病筛检 爱滋：抽血检验（HIV）。梅毒：抽血检验（VDRL）。淋病：取局部分泌物做特殊细菌培养（Cervical swab culture）。披衣菌：抽血检测体内披衣菌抗体（Chlamydia IgG, IgM），或是取阴道分泌物检查披衣菌抗原。

*接种疫苗*

风疹疫苗 如果孕妈咪被风疹病毒感染，25%风疹患者会在早孕期发生先兆流产、流产、胎死宫内等严重后果。也可能会导致胎宝贝出生后先天性畸形或先天性耳聋。最好的预防办法，就是在孕前注射风疹疫苗。
- 注射时间：至少在孕前3个月。
- 免疫效果：有效率在98%左右，可达到终身免疫。
- 特别提醒：怀孕前未接种疫苗，怀孕早期怀疑可能感染风疹病毒，应尽快到医院做免疫性抗体IgM测定。一旦确定患有急性风疹，一般医生会劝说患者考虑终止怀孕。

乙肝疫苗 母婴传播是乙型肝炎重要传播途径之一。乙肝病毒是垂直传播的，通过胎盘屏障，直接感染胎宝贝，使85%-90%的胎宝贝一出生就成为乙肝病毒携带者。其中25%的患者在成年后会转化成肝硬化或肝癌。同时，乙肝病毒还可使胎宝贝发育畸形。所以，育龄女性为预防得肝炎，并使胎宝贝免遭乙肝病毒侵害， 可以注射乙肝疫苗。
- 注射时间：按照0、1、6的程序注射。即从第一针算起，在此后1个月时注射第二针，在6个月时注射第三针。建议在孕前9个月进行注射。
- 免疫效果：免疫率可达95%以上，有效期5-9年。如果有必要，可在注射疫苗后5-6年时加强注射1次。
- 特别提醒：部分人在打完第三针后还是不能产生抗体，或者产生抗体的数量很少。所以还需要进行加强注射，如果出现这种情况的话，最好把注射乙肝疫苗的时间提前到孕前11个月。

甲肝疫苗 甲肝病毒可以通过水源、饮食传播。而妊娠期因内分泌的改变和营养需求量的增加，肝脏负担加重，抵抗病毒的能力减弱，极易被感染。因此，经常出差或经常在外面就餐的女性，更应该在孕前注射疫苗。
- 注射时间：至少在孕前3个月。
- 免疫效果：接种甲肝疫苗后8周左右，便可产生很高的抗体，获得良好的免疫力。接种疫苗后3年可进行加强免疫。
- 特别提醒：甲肝病毒是通过饮食、水源的途径传播的，由于在怀孕后，孕妈咪抵抗病毒的能力减弱，很容易受到感染。所以注射甲肝疫苗是必要的。

流感疫苗 流感疫苗属短效疫苗，抗病时间只能维持1年左右，且只能预防几种流感病毒，孕妈咪可根据自己的身体状况自行选择。
- 注射时间：如果准备怀孕的前3个月，刚好是在流感疫苗注射期，则可考虑注射。如果已怀孕，应询问医生安全与否。
- 免疫效果：1年左右。
- 特别提醒：准备怀孕的女性，平时一定要养成锻炼身体的习惯，不断增强体质。疫苗毕竟是病原或降低活性的病毒，虽然有效，但也并不是打得越多越好。

水痘疫苗 孕早期感染水痘，可致胎宝贝先天性水痘或新生儿水痘;怀孕晚期感染水痘，可能导致孕妈咪患严重肺炎甚至致命。通过接种水痘-带状疱疹病毒疫苗，可在孕期有效防止感染水痘。
- 注射时间：至少在受孕前3至6个月接种疫苗。
- 免疫效果：可达10年以上。
- 特别提醒：由于对水痘-带状疱疹病毒没有特效药物治疗，主要是预防感染为主，育龄女性在怀孕前后避免接触水痘患者。

接种疫苗Tips：
- 并非所有的预防接种都是安全的，诸如麻疹、腮腺炎等病毒性减毒活疫苗，口服脊髓灰质炎疫苗以及百日咳疫苗，孕妈咪都应禁用。
- 凡有流产史的孕妈咪，为安全起见，均不宜接受任何防疫接种。
- 孕妈咪如果有接种疫苗的需求，则应该向医生说明自己怀孕的情况，以及以往、目前的健康情况和过敏史等，让专科医生决定究竟该不该注射，这是最安全可靠的方法。
- 准备怀孕的女性，在接种疫苗时应问清楚医生，接种多久后怀孕才安全，方可计划怀孕，尽可能避免疫苗对胎宝贝产生影响。一般接种疫苗，最好在孕前3个月，除非孕妈咪正处于疾病流行之中，必须接种。

** 辐射问题
*** 如何正确看待辐射
电脑周围存在的辐射包括有X射线、紫外线、可见光、红外线、特高频、高频、极低频、静电场。但是他们发射的强度都是非常微弱的。远低于我国和国际卫生组织 所要求的标准。世界卫生组织的专家认为，影响电脑操作的妊娠妇女妊娠结局的原因很多，主要是工作疲劳和过度紧张，其次才是来自电脑的极低频电磁场。
- 从事视屏作业的育龄妇女不必担心视屏辐射对下一代健康的影响。显示器辐射对生殖健康没有危害。
- 每周在电脑前工作时间不要超过20小时，防止流产的发生。
- 工作环境要通风，保持空气新鲜。
- 没有必要穿防护装置。
- 要避免疲劳和过度紧张，保持愉快的心情，不要担忧。
- 加强户外活动，注意锻炼身体。
- 定期产检，做好孕期保健，避免导致胎儿出生缺陷的高危因素。
根据以上情况，我们建议，在孕早期(前3个月)避免长时间(每周40小时以上)接触使用电脑，必须使用时，可每工作1小时，起身到室外或窗口活动呼吸新鲜空气10分钟，穿戴防辐射的衣物也是可以选择的办法。

*** 长期接触电脑的孕妇要如何防辐射
孕妇长期接触电脑不利于胎儿的发育，易导致流产。电脑的终端是监视器，它的原理和电视机一样，当阴极射线管发射出的电子流撞击在荧光屏上时，即可转 变成可见光。在这个过程中会产生对人体有害的X射线，不过VDT外面的玻璃罩可以大量吸收放射线，实际上人体所受到的射线照射量很小。但是在VDT周围还会产生低频电磁场，在体外实验中，这种电磁场可以在细胞膜水平上干扰细胞的代谢和增殖，从而影响胚胎的正常发育。调查结果显示，在长期使用电脑的妇女中，早期自然流产的发生率较高。另外，长时间以固定姿势坐在电脑前，将会影响孕妇的心血管系统及神经系统的功能，盆底肌和肛提肌也会因此而劳损，影响分娩的顺利进行。因此，妇女一旦怀孕，特别是在孕早期，应尽量避免持续操作电脑。
- 如果在开机的情况下，把显示器关了，是可以减少辐射的。
- 您可以购买能够减少辐射的电脑屏镜，就是那种夹挂在电脑屏幕前的那种类似镜片的。治愈专给孕妇用的防辐射的围兜，不是很清楚，不知道在那里能够买到。您可以到妇幼保健用品商店看看，也许那些地方会有。
- 孕妇可以看电视的离电视机的距离以2米为宜。一般不宜超过一个小时。
还有关专家认为，计算机监视器可产生对人体有害的射线，但外壳可吸收大部分放射线，具有资料统计，人体实际所受到的射线计量为6毫拉得，而国际放射防护委员会认为：整个怀孕期间接受X光剂量不得超过1拉德，这与6毫拉得相差甚远，所以不会对胎儿造成不良影响。同时人们也发现，孕早期长时间使用电脑，可能增加流产率，这主要和电脑周围的低频电磁场有关，至于致畸的可能性，目前没有大量的临床资料来证实。

*** 手机放哪儿才不会影响生育
随着无线通讯技术的发展，使用手机的人越来越多，而手机带来的相关健康问题也引起了人们更多的关注。手机的辐射到底对人体有多大危害，如何把危害的程度降到最低，成了手机用户最关心的问题。

当人们使用手机时，手机会向发射基站传送无线电波 ，而无线电波或多或少地会被人体吸收，这些电波就是手机辐射。一般来说，手机待机时辐射较小，通话时辐射大一些，而在手机号码已经拨出而尚未接通时，辐射最大，辐射量是待机时的3倍左右。这些辐射有可能改变人体组织，对人体健康造成不利影响。

*手机别放枕头边*

据中国室内装饰协会室内环境监测工作委员会的赵玉峰教授介绍，手机辐射对人的头部危害较大，它会对人的中枢神经系统造成机能性障碍，引起头痛、头昏、失眠、多梦和脱发等症状，有的人面部还会有刺激感。

因此，人们在接电话时最好先把手机拿到离身体较远的距离接通，然后再放到耳边通话。此外，尽量不要用手机聊天，睡觉时也注意不要把手机放在枕头边。

*莫把手机挂胸前*

许多女孩子喜欢把手机挂在胸前，但是研究表明，手机挂在胸前，会对心脏和内分泌系统产生一定影响。即使在辐射较小的待机状态下，手机周围的电磁波辐射也会对人体造成伤害。心脏功能不全、心律不齐的人尤其要注意不能把手机挂在胸前。有专家认为，电磁辐射还会影响内分泌功能，导致女性月经失调。另外，电磁波辐射还会影响正常的细胞代谢，造成体内钾、钙、钠等金属离子紊乱。

手机中一般装有屏蔽设备，可减少辐射对人体的伤害，含铝、铅等重金属的屏蔽设备防护效果较好。但女性为了美观，往往会选择小巧的手机，这种手机的防护功能有可能不够完善，因此，在还没有出现既小巧、防护功能又强的手机之前，女性朋友最好不要把手机挂在胸前。

*挂在腰部影响生育*

据了解，经常携带和使用手机的男性的精子数目可减少多达30%。有医学专家指出，手机若常挂在人体的腰部或腹部旁，其收发信号时产生的电磁波将辐射到人体内的精子或卵子，这可能会影响使用者的生育机能。英国的实验报告指出，老鼠被手机微波辐射5分钟，就会产生DNA病变；人类的精、卵子长时间受到手机微波辐射，也有可能产生DNA病变。

专家建议手机使用者尽量让手机远离腰、腹部，不要将手机挂在腰上或放在大衣口袋里。有些男性把手机塞在裤子口袋内，这对精子威胁最大，因为裤子的口袋就在睾丸旁边。当使用者在办公室、家中或车上时，最好把手机摆在一边。外出时可以把手机放在皮包里，这样离身体较远。使用耳机来接听手机也能有效减少手机辐射的影响。

** 饮食注意
*** 给孕妇加营养的九种零食
- 葡萄干-预防孕期贫血和浮肿
- 大枣-含丰富维生素C
- 核桃-促进大脑发育
- 酸奶-调理肠胃
- 奶酪-牛奶浓缩精华
- 苹果-构成胎儿骨骼及牙齿
- 板栗-健脾养胃、补肾强筋、活血止血
- 全麦面包-增加体内的膳食纤维，改善便秘
- 海苔-维持酸碱平衡

*** 怀孕要吃这些水果
- 【柠檬】帮助钙吸收，降血压、健脾开胃、祛暑安胎；
- 【香蕉】消除水肿、稳定血压、保护肠道；
- 【红枣】益智健脑、养血安神、增强免疫力；
- 【火龙果】美容养颜、减肥、抗衰老；
- 【木瓜】舒筋活络、软化血管、美容养颜、调理肠胃；
- 【板栗】补充叶酸；
- 【橙子】补充VC。

*** 孕妇是否可以喝豆浆
豆浆有很高的营养价值，它含有丰富的蛋生质，含有人身体所必需的8种氨基酸和维生素B。此外，豆浆还具有保健功能和美容作用。
- 保健功能
  - 豆浆中的不饱和脂肪酸能防止脂肪堆积在人体内，抑制脂肪吸收，促进脂肪分解，预防肥胖。
  - 降低血压中胆固醇，防止动脉硬化。
  - 补虚润燥、清肺化痰、通畅肠胃。
  - 豆花中含有丰富植物蛋白，它能与动物蛋白相互补充，增加了营养价值，此外它还含有磷脂、B族维生素和无机盐。
- 美容作用
  - 豆浆具有光滑滋润面部皮肤的功能，其中维生素还能防止皱纹的出现和预防浮肿。
所以豆浆为价廉物美的上乘营养食品。

喝豆浆的注意事项：豆浆是一种老幼皆宜、价廉质优的液态营养品，它所含的铁元素是牛奶的6倍，所含的蛋白质虽不如牛奶高，但在人体内的吸收率可达到85%，因此有人称豆浆为“植物牛奶”。清晨，喝一碗豆浆吃几个小笼包子，这种传统的吃法既方便又营养，可有时候，喝了豆浆肚子疼的事时有发生，甚至与“食物中毒”联系起来。
- 忌喝未煮熟的豆浆。很多人喜欢买生豆浆回家自己加热，加热时看到泡沫上涌就误以为已经煮沸，其实这是豆浆的有机物质受热膨胀形成气泡造成的上冒现象，并非沸腾，是没有熟的。没有熟的豆浆对人体是有害的。因为豆浆中含有两种有毒物质，会导致蛋白质代谢障碍，并对胃肠道产生刺激，引起中毒症状。预防豆浆中毒的办法就是将豆浆在100℃的高温下煮沸，就可安心饮用了。如果饮用豆浆后出现头痛、呼吸受阻等症状，应立即就医，绝不能延误时机，以防危及生命。
- 忌在豆浆里打鸡蛋。很多人喜欢在豆浆中打鸡蛋，认为这样更有营养，但这种方法是不科学的，这是因为，鸡蛋中的黏液性蛋白易和豆浆中的胰蛋白酶结合，产生一种不能被人体吸收的物质，大大降低了人体对营养的吸收。
- 忌冲红糖。豆浆中加红糖喝起来味甜香，但红糖里的有机酸和豆浆中的蛋白质结合后，可产生变性沉淀物，大大破坏了营养成分。
- 忌装保温瓶。豆浆中有能除掉保温瓶内水垢的物质，在温度适宜的条件下，以豆浆作为养料，瓶内细菌会大量繁殖，经过3～4个小时就能使豆浆酸败变质。
- 忌喝超量。一次喝豆浆过多容易引起蛋白质消化不良，出现腹胀、腹泻等不适症状。
- 忌空腹饮豆浆。豆浆里的蛋白质大都会在人体内转化为热量而被消耗掉，不能充分起到补益作用。饮豆浆的同时吃些面包、糕点、馒头等淀粉类食品，可使豆浆中蛋白质等在淀粉的作用下，与胃液较充分地发生酶解，使营养物质被充分吸收。
- 忌与药物同饮。有些药物会破坏豆浆里的营养成分，如四环素、红霉素等抗生素药物。

特别提醒
- 急性胃炎和慢性浅表性胃炎患者不宜食用豆制品，以免刺激胃酸分泌过多加重病情，或者引起胃肠胀气。
- 豆类中含有一定量低聚糖，可以引起嗝气、肠鸣、腹胀等症状，所以有胃溃疡的朋友最好少吃。胃炎、肾功能衰竭的病人需要低蛋白饮食，而豆类及其制品富含蛋白质，其代谢产物会增加肾脏负担，宜禁食。
- 豆类中的草酸盐可与肾中的钙结合，易形成结石，会加重肾结石的症状，所以肾结石患者也不宜食用。
- 痛风是由嘌呤代谢障碍所导致的疾病。黄豆中富含嘌呤，且嘌呤是亲水物质，因此，黄豆磨成浆后，嘌呤含量比其他豆制品多出几倍。所以，豆浆对痛风病人不宜。

可以添加：枸杞, 黑豆, 黑芝麻, 核桃, 花生, 牛奶, 红枣, 莲子

不可添加：蜂蜜, 红糖, 鸡蛋

*** 孕妇是否可以吃莲子
http://zhidao.baidu.com/question/94298536.html

-《本草纲目》亦云：莲子，难产多用之。
-《食物中药与便方》中还介绍：妇女子宫阵缩无力而难产：莲子10个，煮水，冲入黄酒半杯温服。故凡在怀孕早中期，切勿食之。另有莲子，性同海马。
-《本草纲目拾遗》中曾说：莲子功倍海马，催生尤捷效。由此可见，怀孕妇女非临产或难产之际，切勿服食。
- 适宜孕妇临产之前或难产之际食用。而正常怀孕期间不宜服食，因它有活血堕胎作用。
- 正如《本草新编》所说：莲子入肾经命门，更善堕胎，故能催生。

*** 孕妇如何饮食调养
孕妇是女人一生中的一个特殊时期，此时家人要给孕妇更多的关心和呵护，孕妇也要积极适应怀孕后的生活。为了生个健康的宝宝，孕妇的日常保健非常重要。 穿衣，孕妇要穿一些宽松舒适的衣服 ；饮食，孕妇要注意营养的搭配。

适宜食物
- 主食及豆类的选择：大米、小米、粳米、糙米、玉米面、燕麦、麦芽、黑米、红豆、红薯等米面杂粮、豆制品及薯类是能量、B族维生素和食物纤维的主要来源。
- 肉、蛋、奶类的选择：猪瘦肉、鲫鱼、兔肉、牛肉、鸡肉、羊肉、青虾、虾皮、牡蛎、鸡蛋、牛奶及动物肝脏、鱼肝油等。
- 蔬菜的选择：西红柿、笋、香菇、胡萝卜、海带、蒜苗、小白菜、香菜、甜椒等。
- 水果的选择：苹果、草莓、橘子等，还有榛子、松子、核桃、芝麻等干果类。

饮食禁忌
- 少吃油腻食物和甜食，这类食物热量高，营养价值低。
- 少用刺激性调料，如辣椒、咖喱、芥末等。
- 酸性食物吃的过多可改变母体血液酸碱度，影响胎儿的生长发育。
- 怀孕中末期会产生浮肿，需控制盐分摄入，禁食含盐过高豆腐乳、咸腌菜等。
- 油条中的明矾含铝，对胎儿大脑发育不利。
- 红枣吃多了会引起腹部胀气，孕妇不宜多吃，可以喝些红枣汤。
- 不喝咖啡、浓茶：咖啡导致不孕、骨质疏松；茶能影响对铁的吸收。

*** 食物热量参考
天津妇女儿童保健中心版本
| 食物     | 重量(g) | 热量(千卡) |
|----------+---------+------------|
|          |         |            |
| 内酯豆腐 |     200 |         90 |
| 米饭     |     100 |        360 |
| 杏仁     |      15 |         90 |
| 河虾     |     100 |         90 |
| 青鱼     |     100 |         90 |
| 蟹       |     200 |         90 |
| 鸡翅     |      60 |         90 |
| 瘦肉香肠 |      20 |         90 |
| 瘦牛肉   |      60 |         90 |
| 猪肝     |      60 |         90 |
| 鸭蛋     |      60 |         90 |
| 油       |      10 |         90 |
| 淡馒头   |      35 |         90 |
| 苏打饼干 |      25 |         90 |
| 饺子     |     3个 |         90 |
| 大豆     |      25 |         90 |
| 核桃仁   |      15 |         90 |
| 花生     |      15 |         90 |
| 绿豆     |      25 |         90 |
| 葵花籽仁 |      15 |         90 |
| 香干     |      50 |         90 |
| 百叶结   |      35 |         90 |
| 干奶酪   |      25 |         90 |
| 西瓜     |     500 |         90 |
| 猕猴桃   |     200 |         90 |
| 橙子     |     250 |         90 |
| 柿子     |     150 |         90 |
| 荔枝     |     150 |         90 |
| 桃子     |     200 |         90 |
| 香蕉     |     150 |         90 |
| 草莓     |     300 |         90 |
| 梨       |     250 |         90 |
| 花椰菜   |     500 |         90 |
| 甜椒     |     500 |         90 |
| 黄瓜     |     500 |         90 |
| 白萝卜   |     500 |         90 |
| 四季豆   |     300 |         90 |
| 芋头     |     150 |         90 |
| 南瓜     |     500 |         90 |
| 青菜     |     500 |         90 |

*** 孕妇妊娠糖尿病
推荐选用：每100克水果中含糖量少于10克的水果，包括青瓜、西瓜、橙子、柚子、柠檬、桃子、李子、杏、枇杷、菠萝、草莓、樱桃、黄瓜、西红柿等。此类水果每100克可提供20－40千卡的能量。 慎重选用：每100克水果中含糖量为11－20克的水果，包括香蕉、石榴、甜瓜、橘子、苹果、梨、荔枝、芒果等。此类水果每100克可提供50－90千卡能量。 不宜选用：每100克水果中含糖量高于20克的水果，包括红枣、红果，特别是干枣、蜜枣、柿饼、葡萄干、杏干、桂圆等干果，以及果脯应禁止食用。含糖量特别高的新鲜水果，如红富士苹果、柿子、莱阳梨、肥城桃、哈密瓜、玫瑰香葡萄、冬枣、黄桃等也不宜食用。此类水果每100克提供的能量超过100千卡。

如果是孕妇，吃水果过量可能会得糖尿病。一些准妈妈喜欢吃水果，甚至还把水果当蔬菜吃。有的为了生个健康、漂亮、皮肤白净的宝宝，就在产前拼命吃水果，她们认为这样既可以充分地补充维生素，将来出生的宝宝还能皮肤好，这种想法是片面、不科学的。虽然水果和蔬菜都具有丰富的维生素，但是两者还是有本质区别的。水果中的纤维素成分并不高，但是蔬菜里的纤维素成分却很高。过多地摄入水果，而不吃蔬菜，直接减少了孕妇纤维素摄入量。并且有的水果中糖分含量很高，孕期饮食糖分含量过高，还很有可能引发孕妇糖尿病等其他疾病。所以，专家建议，孕妇应该有选择地吃各种各样的食物，均衡营养。

少食或忌食事物：
- 精致糖类：白砂糖、绵白糖、红糖、冰糖等。
- 甜食类：巧克力、甜饼干、甜面包、果酱、蜂蜜等。
- 高淀粉食物：土豆、山芋等。
- 油脂类：花生类、瓜子、核桃仁、松子仁等。忌动物性脂肪油(奶油、猪油、黄油等)。
- 熬煮时间过长或过细的淀粉类食物，如大米粥、糯米粥、藕粉等。

** 给准妈妈
*** 坐月子的基本注意事项
- 居家通风 由于秋季气候变化无常，一些呼吸道病毒感染容易流行。孕妇要注意随着气候的变化，及时添加衣服；注意保暖，应尽量避免或少去人多拥挤的地方，居室要保持空气流通。
- 病毒感染 特别要当心一些致畸病毒的感染，如风疹、巨细胞病毒感染，这类病毒对胚胎有致畸的作用。尤其在怀孕早期，如有可疑风疹或巨细胞病毒感染的可能，最好去医院做有关病毒的特异性抗体检查。
- 秋季感冒 如果准妈妈们不小心患上感冒，原则上是能不用药物就不用，千万不要滥用抗生素，即便服用中药，最好也要接受医生的指导，不要自己买药服用。因为 大多数药物可从母体经胎盘进入胎儿体内，其中一部分可对胎儿造成损害，有致畸作用。此外，需要特别注意的是，妊娠早期感冒发烧可影响胎儿中枢神经系统发育，甚至导致胎儿畸形。感冒重在预防，孕妇要加强营养，适度活动，及时增减衣服，保持良好心情，多补充些维生素C以增强机体免疫力。室内要经常通风换气， 孕妇最好不要长时间待在人多的场合，以免交叉感染。
- 合理饮食 秋天食量一般都有所增加，稍不注意就会进食过量，造成血压波动和体重增加过快。因此孕妇应注意保持合理的膳食结构，控制食量，少吃油腻的食物， 可多吃含有丰富钾离子的蔬菜及水果，可以起到对抗钠离子对血压升高的作用，同时也能补中益气、生津润燥。此外，还可选择一些既有丰富营养又有降压作用的食物，如山药、莲子、银耳和百合等。蛋白质主要由动物类食品提供，是胎儿组织器官尤其是脑组织形成和发育所需的最重要成分。准妈妈要保证每天摄入充足的蛋白质，如鸡蛋、牛奶以及各种肉制品（鱼、肉等）。新鲜蔬菜水果中都含有大量维生素和无机盐。秋天蔬菜水果品种多、质量好，准妈妈每天应保证摄入1斤左右的绿叶或橙黄色类蔬菜，以及适量水果。除了膳食本身外，孕妇还应根据自身的需要，补充铁、钙、维生素A及维生素D等。虽然秋天上市的新鲜瓜果比较多，但这个季节也正是天气逐渐转凉的时候，早晚气温低，昼夜温差大，如果不注意食品卫生，抵抗力相对比较差的孕妇就容易腹泻，这对孕妇的威胁可比平常人大得多，可能引起子宫收缩甚至导致早产。另外，秋天气候干燥，孕妇如果不注意饮食调理就可能便秘。建议孕妇饮食中油腻食物和肉类要适量，要注意以清淡为主，少吃辛辣，要适当增加新鲜水果和蔬菜的比例。多喝水，养成定时排便的习惯。
- 应对干燥 秋季，气候温和，室内温度宜人，但是天干物燥，灰尘很多，新妈妈长期呆在室内会感到鼻干咽燥，这时可以用加湿器来调节湿度。为了防止鼻干咽燥， 最好多喝水或多喝些比较清淡的汤。对花粉不过敏者也可以在卧室摆放些盆花及鱼缸，一方面能够调节心情，另一方面也可以调节室内湿度，净化室内空气。
- 及时防风 秋季刮风多，夜间或晨间气温比较低，在日常通风的同时要注意及时关闭窗户。产妇坐月子期间，晚间、晨间如厕要注意保暖，防止诱发产后风。所谓产后防“风”，防的是外感风寒，并不是不能见风，更不能由于产妇怕风而将门窗紧闭，如果连正常的室内通风换气也不能保证，反而孳生病菌。在进行通风换气时， 可选择天不太冷、无风及日光充足的时候开窗换气，床不要靠近窗口或正对窗口，必要时产妇与婴儿可暂去别的房间休息或活动。天较暖，阳光好时，产妇和婴儿穿暖包好，一同晒晒太阳也有利健康。
- 生活饮食 在饮食和生活方式上，产妇一定要保证生活规律，拥有足够的睡眠，饮食要清淡，既富有营养又易于消化，不要吃刺激性的食物，要多食高蛋白食物、新鲜蔬菜及水果。产后滋补忌过量。
- 日常护理 应鼓励产妇早日下床活动，但应以不感到疲劳为宜，这样有助于产妇体力的恢复，还能促进子宫收缩、复旧及恶露的排出，促使其尽早排尿排便，避免或减少静脉血栓的形成，有利于盆底和腹肌张力的恢复。保持精神愉快，避免不良的精神刺激。新妈妈由于产后多汗、有恶露、喂奶等原因，要注意清洁卫生，勤洗澡，勤换衣被，但不要用冷水洗手或洗衣，以科学的态度来对待“坐月子”。

*** 坐月子的8大误区
*误区一：月子期间不能洗澡*

传统习俗：分娩后全身毛孔和骨缝张开，加之气血两虚，如果洗澡，风寒侵袭体内致周身气血凝滞，流畅不同，日后出现月经不调，身体肌肉疼痛。

现代医学：产后清洁身体具有活血，行气的功效，可助产妇解除分娩疲劳，保持心情舒畅；还可以促进会阴伤口的血液循环，加快愈合等。

结论：月子里洗澡有益于产妇健康，不过需要注意以下几点：
- 会阴无伤口，夏天在2-3天，冬天在5-7天即可淋浴。如果产妇身体较弱不能站立，或者会阴伤口大，撕裂严重，腹部有刀口，可先做擦浴。
- 产后洗澡讲究“冬防寒，夏防暑，春秋防风”。夏天，浴室温度保持常温，不可用凉水冲澡；冬天浴室温度也不宜过高，易使浴室弥漫大量水蒸汽，导致产妇缺氧。洗澡水温保持在35-37度左右。
- 控制洗澡时间在5-10分钟。
- 洗后尽快擦去身体水分，及时穿上御寒的衣服再走出浴室，避免着凉。

*误区二：月子期间不能洗头梳头*

传统习俗：分娩后毛孔长大，洗头易使湿寒邪侵入头皮，日后留下病根如头疼脱发等。

现代医学：洗头梳头可去掉产妇头发中的灰尘污物，保持卫生清洁；刺激头皮经络，促进血液循环。

结论：只要身体健康大可洗头梳头，但是需要注意下面几点：
- 水温要适宜，保持在37度左右
- 不要使用太刺激的洗发用品，可用生姜熬水，去湿
- 洗头时用指腹按摩头皮，切忌用力抓挠；洗完后最好用干毛巾稍许擦干，然后使用吹风机
- 不建议去理发店洗头，夏季那里往往冷气比较强，产妇容易受凉
- 梳理头发最好用木梳，避免产生静电刺激头皮

*误区三：月子期间不能刷牙*

传统习俗：生个孩子掉颗牙，月子里如果刷牙漱口会动摇压根，伤及牙肉，造成牙齿松动，脱落等。

现代医学：月子里每天要进食大量高蛋白食物，容易形成牙菌斑；如果不刷牙，食物的残渣留在牙缝中，在细菌作用下发酵，产酸，导致牙齿脱钙，形成龋齿或是牙周病，并引起口臭，口腔溃疡等。

结论：月子里一定要天天刷牙，只要体力允许产后第二天就应该开始刷牙，最好不要超过3天。但是需要注意以下几点：
- 注意摄取钙营养
- 要用温水刷牙，并用软毛牙刷，或者采用指漱
- 早晚各刷一遍，如有吃夜宵习惯，吃完后再刷一遍

*误区四：月子期间最好长期卧床*

传统习俗：因为生孩子消耗大量体力，月子里产妇必须躺在床上，这样才能让身体快速恢复

现代医学：如果产后较长时间不活动，易使产费用发生下肢静脉血栓及肠粘连，特别是剖宫产的产妇。如果在产后适时适度地进行一些活动，便可增加虚弱的腹肌收缩力，促进子宫复原，同时有助于恶露排出。

结论：产户需要休息，但是并不意味着需要长期卧床。需要注意以下几点：
- 特殊产妇（发烧，出血，高血压，严重贫血，剖宫产）需要限制活动或推迟下床活动时间
- 顺产的产妇身体疲劳如果消失，产后12小时可以坐起来进餐进水；24小时可以起床活动，如下床去卫生间；产后48小时可以在房间里面走动一下，每天走动2-3次
- 产后1星期可做产后保健操，平时可做给宝宝换尿布这些轻微动作，切忌久蹲或用力过猛
- 第一次下床活动必须有人陪伴，以防体虚摔倒，并注意不要站立过久

*误区五：月子期间不能看书看电视*

传统习俗：老人家认为坐月子期间看书看电视就会花眼，落下眼病

现代医学：女性产后眼睛本身并没有发生太大变化，“会花眼”或“落下眼疾”等都是不科学的。以前的说法主要针对照明设备不佳和电视辐射的。

结论：看书上网都是为了调剂新妈妈精神，况且现有良好的照明条件，可以允许但也要注意一些细节：文字尽量大，姿势要正确，时间不太要长（不要超过1小时），光线要充足，不看悲伤火爆或是情绪激烈的内容，最重要是不影响休息。若没有适度的休息，容易造成出血难止，腰酸腹痛，精神不济。

*误区六：月子期间不能吃盐*

传统习俗：产妇在坐月子期间吃的菜和汤里都不能放盐，否则会影响奶水甚至没有奶水

现代医学：盐中含有钠，如果缺钠就会出现低血压，头昏眼花，恶心呕吐；如果产妇限制钠的摄入，影响了体内电解质的平衡，同事就会影响食欲，进而影响泌乳。所以月子里的产妇不能“忌盐”。

结论：由于产后出汗较多，乳腺分泌旺盛，产妇体内容易缺水和盐，因此应该适量补充盐分，成人每天需要盐4.5-9克；当然如果产妇每天摄入盐量过多，就会加重肾脏负担，会使血压升高，因此也不能过多摄入食盐。

*误区七：月子期间不能喝白开水*

传统习俗：中国有些地方有提前做米酒供产妇坐月子时使用的习俗，说产妇毛囊呈打开状态，水又是大分子，摄入大量后容易背身体吸收随后导致产妇身体发胖；目前网上也盛传月子期间不能喝水，做菜做汤也不可以用水，都要用米酒水代替，俗称“月子米酒”

现代医学：产妇体虚，大量出汗，势必要补充水分；对于哺乳期的妈妈而言，水分“损失”更多，因而特别需要大量补充，建议每天喝8-12杯水。古时候的确使用米酒水作为坐月子妈妈的饮料，是因为当时没有自来水，水源也很难确保干净，所以用有杀菌功效的米酒来著称汤品饮料，在当时而言是最安全的方式。可现在有自来水，矿泉水，纯净水，实在不需要米酒水来代替水。

*误区八：妈妈不能在月子期间照顾宝宝*

传统习俗：产妇在月子期间就要好好养好身体，只管躺着，不能干任何费力事情包括照顾宝宝。一般而言，照顾新生儿的重任都丢给老一辈或是高薪聘请来的月嫂。

现代医学：月子里宝宝一定要由母亲来照顾，尤其提倡母乳喂养，它是妈妈与宝宝建立亲子交流的第一步；多和宝宝互动（比如给宝宝换尿不湿时候多和他笑笑讲讲话）对孩子以后成长都非常有利。带孩子确实很累，但累中得到的收获和乐趣是无法比拟的。

结论：面对软绵绵的小身体，很多新手妈妈不敢放手去照顾，然后把责任过多的交予月嫂。其实，新事物总是需要探索的，照顾孩子也不例外，要给自己犯错误的机会。

*** 育儿50个小细节
1. 十个月内不加盐
2. 周岁内不喝蜂蜜
3. 三月内只吃奶（纯母乳的四个月内不加果汁）
4. 牛奶最好在2周岁后喝，2岁之前可吃酸奶。脱脂牛奶比全脂牛奶对孩子更健康
5. 三岁前孩子的用盐量为成人的1/5-1/3, 吃盐多会导致钙质流失
6. 喝可乐等碳酸饮料会影响钙质吸收
7. 爸爸的情绪不好会使婴儿的哭闹增加2成
8. 爸爸遗传身高，妈妈遗传体型
9. 爸爸带孩子，孩子智商高；妈妈带孩子，孩子学习成绩好
10. 结束开裆裤最好不要晚于一岁半，尿路感染也会发烧，治疗不及时会上行，导致感染性肾炎
11. 纯母乳的4月内不用刻意喝水，只在喝奶后给点，当漱口了。6个月内不要多喝水，因为无论母乳还是奶粉都含有大量的水，多喝水会增加孩子肝肾负担
12. 周岁内忌久坐（1个小时），研究表明，周岁内久坐1个小时的孩子会增加猝死率
13. 孩子放在沙发上的猝死率是放在床上的4倍
14. 夜晚开灯睡觉会降低孩子的免疫力
15. 拍孩子胸部会诱发猝死
16. 太阳直晒脚心，妈妈的微笑会提高孩子的免疫力
17. 若保四时小儿按，常需三分饥与寒
18. 10月内的孩子禁止摇晃，伤害大脑，最重可致颅内出血和轻微脑震荡
19. 打孩子屁股会影响孩子成年后的性健康
20. 2周岁以下孩子禁看电视
21. 宝宝外出首选婴儿背带
22. 婴儿餐桌椅-妈妈的好帮手，培养孩子良好的生活习惯
23. ？？？
24. 1岁内不加味精
25. 一只炸鸡腿=60支香烟
26. 当室内温度超过24度，铺在地上防凉的泡沫垫会释放出甲醛
27. 不要用浴霸，因为孩子仰脸，会伤害孩子眼睛。可选用暖风机等提高温度
28. 家中有孩子的最好不用空调和地毯。国外统计，使用空调和地毯的家庭，其孩子得过敏性哮喘是不用家庭孩子的2-3倍（罪魁是尘螨）
29. 如果孩子已经得过敏性哮喘，那么每天睡前给孩子喝一碗蜂蜜水，此食疗需长期吃才有效
30. 3岁以下孩子不要喝纯净水，矿泉水；白开水对孩子是最好的
31. 孩子6岁后才可以喝茶
32. 孩子6岁前用很热的水烫脚会造成偏足平
33. 防止尿布疹，可以用喝过的茶叶再煮一下的茶水擦屁股
34. 防止尿布疹，也可以用香油擦小屁股
35. 如果孩子内八字，用反穿左右鞋的办法几个月后能扳回来
36. 孩子3岁前最好不要蹬三轮车，容易形成O型腿或X型腿
37. 如果已经形成X型腿，让他坐床上时多盘腿坐，能扳过来一些
38. 孩子1.5岁开始刷牙最能保护牙齿
39. ？？？
40. 别给孩子吹烫饭，容易传播龋齿。如果大人嚼过的食物再让孩子吃，龋齿率会更高
41. 孩子最好不用学步车
42. 幼儿积食也会引起发烧
43. 新生儿发烧首选物理降温
44. 6个月内的孩子慎用退烧药
45. “奶粉宝宝”更易暴饮暴食
46. 肥胖儿易患哮喘
47. 挨打的孩子智商低
48. 不宜给发烧的孩子吃鸡蛋
49. 6月内的孩子不宜吃鸡蛋精，产生过敏，发生湿疹，荨麻疹等疾病
50. 不宜给婴幼儿吃没煮熟的鸡蛋（煎鸡蛋要3分钟，煮鸡蛋要7分钟）

*** 胎儿最害怕的12件事
   1. 怕噪音。
   2. 怕烟酒。
   3. 怕妈妈情绪过度不安。
   4. 怕药物。
   5. 怕母体不健康。
   6. 怕放射线。
   7. 怕营养不良。
   8. 怕高过敏食物。
   9. 怕妈妈玩宠物。
   10. 怕未接受定期产检。
   11. 怕强烈撞击。
   12. 怕长途劳累旅行。
** 给准爸爸
<怀孕圣经>: 5种分担妊娠的方式
- 参加产前检查, 会了解许多妻子以及宝宝的进展情况.
- 观察宝宝. 超声扫描会让准爸爸惊喜地看到自己的宝宝, 还可以要一张宝宝的图片.
- 听宝宝的声音. 从妊娠30周左右开始, 就可以将耳朵贴到妻子的肚子上, 听宝宝的心跳.
- 感觉宝宝的运动. 从妊娠第5个月, 就能感觉到宝宝在变换位置, 甚至能确认他(她)的小手和小脚.
- 和宝宝说话, 阅读和唱歌. 他(她)可以从子宫中听到, 这一过程也可以使妻子感到愉悦.

<怀孕圣经>: 7件事情要记住
- 向老板预报并且请假. 记住灵活的安排最好, 因为只有1/20的孩子在预产期准时来临.
- 列出联系表. 列一个紧急电话单, 包括妻子的分娩陪伴人和医院的电话. 别忘了列出家人和朋友的电话, 以便把好消息告诉他们.
- 在最后的一个月内, 设法熟悉社区助产士或拜访医院, 以便能够了解分娩中和接生室内使用的技术和仪器.
- 和妻子交谈. 在产前的最后3周内, 当丈夫工作时也要保持正常交流, 这会使得双方都感到安心.
- 安排运输. 如果使用自家车, 要保证油箱装满, 并设计出到医院的最可靠的途径. 如果是雇出租, 联系最可信赖的公司, 并确保随叫随到.
- 检查, 检查, 再检查. 去医院之前, 确信带上了: 妻子的包, 旅游鞋, 分娩计划, 电话薄以及打电话的零钱.
- 委托. 到达医院时, 把分娩计划交给助产士. 如果她们还不知道这一计划, 就向她们解释.

** 个人经历
*** 时间安排
- 2014-10-05 末次月经
- 2014-11-04 试纸强阳. 因为从末次月经到排卵时间比较长(30d), 所以对外说末次月经是10-20(15d)，预产期按照2015.7.25计算
- 2014-11-16 发现双杠
- 2014-11-18 孕酮 17.91 HCG 650
- 2014-11-25 孕酮 19.18 HCG 11896
- 2014-12-31 社区医院建卡，每月28号体检
- 2015-01-14 NT 1.5mm，通常在11-13w
  - NT通常在11-13w
  - 3w左右就要开始预约. 不需要带什么材料. 中心妇产1区4诊室. 顺便可以预约四维彩超和心脏筛查
  - 如果没有预约成功的话，在11～12w左右在1区3诊室挂产科号做检查（每天都可以做），可以在etz上进行预约。
  - 中心妇产提前8天下午4点开始在ezt上放号。但是最早的号也是在8：30，开完单子做B超大概也要排到下午4点左右。
  - 做NT当天还必须做血液检查，两个必须放在一天做，先做NT然后做血液检查。血液检查下午5点下班，产科大夫下午4.30下班。所以如果4点左右做B超那么肯定做不了血液检查。B超单子6日内有效，所以可以在6天以内早起去排B超的队，这样可以上午昨晚B超然后接着做血液检查。我们是14号去开的B超单子，但是17号去做的NT检查和血液检查。
- 2015-01-27 血压60-100. 正常范围60-90/90-140. 血糖4.8mmol
- 2015-02-10 中期唐氏筛查，通常在15-20w
  - 分为血清筛查和无创DNA筛查两种方法，血清筛查准确率偏低但是经济，无创DNA准确率高但是不经济。
  - 如果前期唐氏筛查（也就是做NT时候的血检）没有问题的话，那么选择血清筛查即可。
- 2015-02-24 血压59-91，血糖5.1mmol, 心跳69
- 2015-04-10 四维彩超，通常在24-28w
  - http://baby.enorth.com.cn/system/2012/04/18/009065357.shtml
  - http://www.tjkrml.com/swcc/

*** 办理准生证以及建档
需要材料：
- 妊娠诊断证明
- 结婚证(原件和复印件)
- 双方户口本(原件和复印件)
- 双方身份证(原件和复印件)
- 夫妻双方单位(存档单位)出具的初(再)婚第一胎证明
- 外省市的一方还需要提供户籍地村(居委会)和乡, 镇(街道)计划生育部门出具的两级婚育证明
  - 需要材料：妊娠诊断证明，结婚证，户口本，身份证，一方单位证明
  - # 这个每个地方不太一样，最好托家人在当地先打听清楚
- 在现居住地居委会开具的领取一孩生育服务证的证明
- 在街道计生部门领取一孩生育服务证的证明（准生证）
- 在居住地所属的社区医院建档

*** 孕期菜目
- 菠菜 西红柿 青笋 芦笋 香菇 胡萝卜 白菜 油菜 油麦菜 青椒 黄豆 土豆 木耳
- 黄豆 山药 西兰花 韭黄 莴笋 冬瓜 藕片 西葫芦 茭白 豆腐 空心菜 豆芽 黄瓜
- 海带 紫菜 鲫鱼 鲈鱼 黄鱼 鸡蛋 猪肉 牛肉 鸡肉 羊肉 虾皮 虾仁 羊肉
- 柠檬 香蕉 火龙果 木瓜 橙子 柚子 脐橙 草莓 橘子 樱桃 桃子 葡萄 猕猴桃
- 牛奶 奶酪 葡萄干 红枣 核桃 酸奶 面包 海苔 花生 瓜子 芝麻 蜂蜜 黑豆
