#+title: Probability and Paradox

https://github.com/norvig/pytudes/blob/master/ipynb/ProbabilityParadox.ipynb

里面提到了很多有趣的问题，这类问题引出了很多心理学方面的知识，以及Reasonable Person Principle。

-----
我们对待悖论的态度，不应该是不假思索地判断对错，而是应该从其他角度考虑是否这个问题存在多种解释

When two methods of reasoning give two different answers, we have a paradox. Here are three responses to a paradox:

1. The very fundamentals of mathematics must be incomplete, and this problem reveals it!!!
2. I'm right, and anyone who disagrees with me is an idiot!!!
3. I have the right answer for one interpretation of the problem, and you have the right answer for a different interpretation of the problem.

If you're Bertrand Russell or Georg Cantor, you might very well uncover a fundamental flaw in mathematics; for the rest of us, I recommend Response 3. When I believe the answer is 1/3, and I hear someone say the answer is 1/2, my response is not "You're wrong!", rather it is "How interesting! You must have a different interpretation of the problem; I should try to discover what your interpretation is, and why your answer is correct for your interpretation." The first step is to be more precise in my wording of the experiment:

-----
理性人准则：你应该认为所有人都是平等，并且都是理性的。Broadly Speaking， 从Norvig给出RPP的这个链接上看，这个准则更像是构建一个和谐富有活力的社区的准则。

The Reasonable Person Principle

It is an unfortunate fact of human nature that we often assume the other person is an idiot. As George Carlin puts it "Have you ever noticed when you're driving that anybody driving slower than you is an idiot, and anyone going faster than you is a maniac?"

The opposite assumption—that other people are more likely to be reasonable rather than idiots is known as the [[http://www.cs.cmu.edu/~weigand/staff/][reasonable person principle]]. It is a guiding principle at Carnegie Mellon University's School of Computer Science, and is a principle I try to live by as well.


#+BEGIN_QUOTE
Reasonable Person Principle:

1. Everyone will be reasonable.
2. Everyone expects everyone else to be reasonable.
3. No one is special.
4. Do not be offended if someone suggests you are not being reasonable.

Reasonable people think about their needs, and the needs of others, and adjust their behavior to meet the goals of a common good for the community, i.e., expressing
what you want to say, but accepting and accommodating the needs of others. Mary Shaw's explanation:
The Reasonable Person Principle is part of the unwritten culture of CMU computer science. It holds that reasonable people strike a suitable balance between their own immediate desires and the good of the community at large.

As applied to bulletin boards, this would include things like observing the explicit or implicit ground rules about subject matter or tone. These vary from one bulletin board to another but usually include sticking to the expected subject matter and refraining from personal attacks. There are exceptions, though. For example, cs.opinion is no-holds barred and often both agressive and personal.

Not all people share the same model of reasonableness, so disagreements inevitably occur. Under the reasonable person principle, the first thing to do is work it out privately (perhaps in person, since e-mail is known to amplify feelings). Indeed, many people would find it unreasonable to bring in third parties before trying personal discussion.

More generally, the reasonable person principle favors local, unofficial actions over formal administrative ones. It assumes that people will be responsive when reminded of a conflict or asked to re-examine their behavior. It encourages requesting rather than demanding. And it leaves some room for difference of opinion.
#+END_QUOTE

-----
有些cases需要从细分的角度去观察，因为这些细分里面带有太多的biases；而有些cases需要从总体的角度去观察，这样才能排除biases. 所以对于数据分析，我们不仅要知其然，还要知其所以然。

For the kidney stone data, we trust the individual cases, not the overall, because there are biases that lead to patients being assigned to one treatment or the other. For the batting average data, we trust the overall numbers, because there are no such biases, and because larger numbers lead to a closer approximation to a true value. The data alone can't tell you what to believe; you need the story (and the model) behind the data as well.
