#+title: Programmers are distraction for your startup

原文链接 http://tightstartup.com/programmers-are-distraction-for-your-startup/

对startup来说，founder容易错误地认为product肯定需要编程program来完成，而其实不然。
#+BEGIN_QUOTE
One of the best examples is Pieter Levels. He started his famous project called Nomad List with a simple Google Sheet. At some point he got enought traction to build is own platform. He also did this with several other projects.

Another great example is Ryan Hoover. He started Product Hunt as a simple Email Newsletter. There are plenty more of projects who were build like this and are now successful.

You don't need a perfect product if you have a something that people want. Instead of procrastinating and building nice-to-haves, focus on the most important thing: building a product people will love.
#+END_QUOTE

当然现在许多互联网产品都需要code. 不过考虑到SaaS以及开源软件发展迅速，现在coding的门槛已经非常低了. 一些简单的编程工作，即便founder不是CS毕业的稍加学习也可以完成. 不过话说回来，文章强调的点是，focus on product, instead of coding.

#+BEGIN_QUOTE
That's why your project should start with the "No-code-principle", which means: Do not write a single line of code! See how far you can get with your product idea without writing code. Try to build your idea on an existing platform. There are plenty of platforms out there, which have features that might fit well with your product idea. If you can attract a few users and get some initial traction on a "foreign" platform, you can see that you are on the right track.

That's why we have set up a few principles when starting a project:
- Set up your project on an existing platform which fits best for your needs
- Attract users
- Learn
- Build or Microfail (= discard, restart at Step 1)

It forces you to start with tasks which, in my opinion, are the hardest to achieve for every startup - getting traction. By following this principle, you are not able to procrastinate or keep yourself busy with "unimportant" work like design, code or whatsoever. Your only focus is to find users, make them use your product and learn from them.

P.S. If you have to hire a programmer in an early stage startup, prefer the ones who have founded or worked in a startup before. Don't only proof their technical skills, furthermore proof their [[http://en.wikipedia.org/wiki/T-shaped_skills][T-shaped skills]] and if they fit well into your current team (which is another crucial part!).
#+END_QUOTE
