#+title: 购买MacBookAir

原来的compaq笔记本买了也挺长时间的了，并且因为自己从百度离职了，配备的thinkpad-x201i就被回收了，手头上也没有什么可用的笔记本。ipad阅读倒是非常方便，但是却不适合用来完成工作（周末在天津），所以想入手一个笔记本。

之前一直考虑必须购买Mac因为自己比较喜欢在Linux下面开发但是用Ubuntu遇到了很多问题，而OS X是Unix操作系统，同时有很多现成软件使用比如Evernote，EverBox，PPStream，QQ等。但是随着前一段时间自己开始习惯了Ubuntu之后，觉得其实自己有一个Ubuntu也已经足够了，所以Mac的诱惑力又回归正常了。自己也开始纠结于thinkpad和mba之间（mbp是没有考虑的，一方面是因为价格，另外一方面是考虑到重量）。

看过一些文章说MBA是如何的好：
- MacBook Air与工作效率 – Tim[后端技术] http://timyang.net/misc/macbook-air-productive/
- Why the MBA 11 is now my sole computer http://antirez.com/post/apple-mba11-my-sole-computer.html
- 为什么国外程序员爱用 Mac？ | vpsee.com http://www.vpsee.com/2009/06/why-programmers-love-mac/
- 为什么我认为每个程序员都应该用Mac OS X？ - Tinyfool的Blog http://tiny4.org/blog/2010/02/why-programmers-should-use-mac-os-x/

同时weibo上的朋友们推荐我选择mba，但是也有同学推荐自己买一个thinkpad然后换ssd。
#+BEGIN_QUOTE
dirlt：求笔记本推荐，不求mac，轻便同时高性能，最好ssd，thinkpad x201i就很好，但是似乎不是ssd。

陈尔冬：回复@dirlt:不好意思 目前笔记本只有mac我觉得还行 其他品牌我觉得太刻意打价格战导致设计都很平庸 所以没深入研究 你为啥不考虑mac呢？觉得性价比不高？

dirlt：回复@陈尔冬:其实我是觉得mac性价比相当的高了，不管是pro还是air。我现在习惯使用ubuntu了，好多东西不确定是否在mac os x上面有。当然可以自己更换系统，但是这样似乎就失去mac一半的意义了，所以看看是否有更好的选择。其实air现在在强烈考虑，只不过担心买了之后用不惯。

陈尔冬：回复@dirlt:这个放心 苹果系统很易用 可以bootcamp做双系统 而且相信你同事肯定有用mac的 可以先交流一下 我也是超级推荐air的 air只有一个缺点就是扩展性差 内存和flash不够了只能换代 和乔布斯的控制欲有关

n4mine:回复@dirlt:懒死吧，think就一个螺丝卸硬盘，再4个螺丝卸托架，一抽一插，搞定了[得意地笑] //@dirlt:关键是我比较懒：（ //@n4mine:买了之后换ssd呗，又不贵

idning：x201i换上8g内存 + ubuntu 10.04 x86_64 ，最好的组合~

zhpengg：回复@dirlt:我那个是去年的型号了，觉得主要是系统的易用性上比windows更好些，而且本身就是unix变种，做开发非常方便

dirlt：回复@zhpengg: 恩，确实确实。mac OS x支持bash这样的吗？还有有apt-get install这样的东西吗？我听说好像都是在App Store上下载的。

zhpengg：回复@dirlt:哥原生支持bash的，包管理器也有mac port或是homebrew都非常好用
#+END_QUOTE

后来仔细分析了一下，就价格来说mba相对thinkpad还是便宜的，不过mac的附加设备比较贵，而thinkpad以为是标准pc所以外围设备相对便宜。但是好在像我这样的用户，对于附加设备要求不过，最需要的或许就是thunderbolt转化器，以及额外的电源，而这些价格是不贵的。因此总的来说，mba价格上还是比较有优势的。而开发上因为mba也是unix-like系统，虽然和linux有些差别但是应该不会太大，因此易用性以及完成工作方面两者相当。最后确定我购买mba的原因比较扯淡，是因为 *老婆说想看看mba是什么个样子？* 。最后就决定买了。

听说从US或者是HK购买能够便宜不少，所以决定查查。果然相同配置，HK比Mainland要便宜1.5K左右，果然是天煞的。看来托同学从US或者是HK带还是必须的，大不了给他们0.5K作为酬劳吧。

正好CTO在USA CA，所以希望他可以在那边帮我购买一个，但是关税确实是一个问题。现在入境中国的话，对于笔记本这类商品来说有200的关税。但是因为这个抽查的，并且如果拆掉包装的话（相当于自己随身携带的），那么就不需要缴纳任何关税。但是问题是，在USA的话还有购物税，而且在CA（高达8.25%，USA其他州的税是不同的。不知道香港有没有？）。并且对于商品来说，标价都是税前的。在USA购物的话，还分网购和实体店购。如果是网购的话可能不需要上税，但是CTO说似乎现在amazon也需要上税了，而对于实体店来说肯定是需要上税。

终于决定从HK买air了，多亏了tp同学帮忙。http://store.apple.com/us/configure/MD224LL/A i7处理器，8G内存，128Gssd，折合人民币大概在8600.（看了一下在mainland买同样配置在9800左右，囧）因为更换了配置，所以大概需要等个1-2周才能够送到他住的地方（应该是我的生日8.15他才能收到），然后他坐车到深圳在那边用顺丰给我快递过来。辛苦了。给他的香港账户汇款是个问题，他的账户是恒生银行的，不知道招行或者是交行都啥办法汇款？如果没有的话有什么比较方便的途经可以汇款吗？(最后还是汇到他在深圳的建设银行了）

终于在2012-8-20寄到单位了，里面还是全新包装的，看来他也花了不少功夫。快递费用大概在44左右，我还是给了他9K。tp，非常感谢。

桌面截图 ;)

file:images/my-mba-desktop.png
