#+title: 网络文章@202306

-----

[[https://world.hey.com/dhh/wisdom-is-not-what-you-know-e8cf9191][Wisdom is not what you know --- 智慧不是你所知道的]](https://world.hey.com/dhh/wisdom-is-not-what-you-know-e8cf9191)

Ironically, this was a lesson I had to learn late in life myself. I used to find it silly when people would read the same book twice. With so much more knowledge to discover, why waste your efforts on what you've already explored?

讽刺的是，这是我自己在晚年必须学到的一课。我曾经觉得人们读同一本书两遍是很愚蠢的。有这么多的知识有待发现，为什么要把精力浪费在已经探索过的事情上呢？

Because wisdom doesn't stick just by reading it once.

因为智慧不会仅仅读一遍就被记住。

All the most valuable lessons in life require repetition. You don't get in shape by knowing how to do a push-up but by doing a hundred a week. Accept that wisdom is a form of mental exercise.

生活中所有最有价值的课程都需要重复。想要塑造身材，不是通过知道如何做俯卧撑，而是通过每周做一百个俯卧撑。接受智慧是一种精神锻炼的形式。

-----

[[https://www.youtube.com/watch?v=5J6jAC6XxAI&t=740s][Why you should define your fears instead of your goals | Tim Ferriss - YouTube]](https://www.youtube.com/watch?v=5J6jAC6XxAI&t=740s)

stoa(柱廊) -> stoic(斯多葛) -> stoicism (斯多葛学派)

we suffer more in our imagination than in reality -- Seneca

easy chocices, hard life; hard choices, easy life.

-----

[[https://world.hey.com/dhh/breaking-the-inertia-of-mediocrity-88048743][Breaking the inertia of mediocrity --- 打破平庸的惯性]](https://world.hey.com/dhh/breaking-the-inertia-of-mediocrity-88048743)

造成组织低效的原因不是那些迫在眉睫的事情，而是那些隐藏在日常流程中的低效率：我们不愿意去解决它，知道它拖垮整个组织。参考《积累出来的衰败》。

记住：easy chocices, hard life; hard choices, easy life. 在日常过程中就要不断地清除掉那些低效和肮脏的东西，不然未来会越来越难。

It's rarely the terrible decisions, processes, or even people that'll sink your organization. It's the accumulation and inertia of the mediocre ones. Dealing with the truly bad is easy. It's painfully obvious to all that change is required. The danger is imminent. It's much harder to find the will to act when the danger lurks in inadequate urgency, cumbersome collaboration, or just a missing spark. But act you must, before inertia sets in to devour you whole.

导致组织崩溃的很少是糟糕的决策、流程甚至人员。这是平庸者的积累和惯性。处理真正的坏事很容易。对于所有人来说，显而易见的是，需要做出改变。危险迫在眉睫。当危险因不紧迫、协作繁琐或只是缺少火花而潜伏时，就很难找到采取行动的意愿。但你必须采取行动，以免惯性将你整个吞噬。

The insidious nature of inertia is in its ability to compound the cost of action as time goes on. Letting go of an employee that just didn't meet the bar after three months is endlessly easier than doing the same after three years. Same with reverting a bad organizational restructuring or poor development practices or awkward reporting protocols. Every additional month you let mediocrity fester, you make it harder to undo.

惯性的阴险本质在于，随着时间的推移，它会增加行动的成本。三个月后解雇一名没有达到标准的员工比三年后解雇他要容易得多。与恢复糟糕的组织重组或糟糕的开发实践
或尴尬的报告协议相同。每多一个月，你就会让平庸恶化，你就更难挽回。

Whenever I find myself looking at a coward in the mirror, I remind myself: Easy choices, hard life. Hard choices, easy life. Make the hard choices. Even when it's possible to punt. The inertia of mediocrity will not break unless you break it.

每当我发现自己在镜子里看着一个懦夫时，我就会提醒自己：选择容易，生活艰难。艰难的选择，轻松的生活。做出艰难的选择。即使可以踢球。平庸的惯性不会打破，除非你打破它。


-----

[[https://world.hey.com/dhh/until-the-end-of-the-internet-439ccfce][Until the end of the internet --- 直到互联网的终结]](https://world.hey.com/dhh/until-the-end-of-the-internet-439ccfce)

软件行业对于“遗产”这个东西似乎真的不太重视，或者说这些“遗产”都是某种程度上的半成品，没有办法拿出手。

That's the nasty secret of SaaS. Even if the service doesn't just disappear entirely, like it often does, it might well "evolve" in a direction you don't care for one bit. But what choice do you have? Almost all companies will simply tell you to get with the program, find where they hid the cheese now, and just be grateful that updates are even rolling out.

这就是 SaaS 的令人讨厌的秘密。即使该服务不会像通常那样完全消失，它也可能会朝着您不关心的方向“发展”。但你有什么选择呢？几乎所有公司都会简单地告诉您使用该计划，找到他们现在隐藏奶酪的位置，并且庆幸更新甚至正在推出。


-----

[[https://liuyandong.com/archives/9804][No. 403 Nvidia创始人黄仁勋小时候移民美国的故事 – 栋哥的赛博空间]](https://liuyandong.com/archives/9804)

我对移民的观点是一贯的，移民和结婚，离婚一样，你不要试图通过这件事去寻找幸福。比如你在某个国家，你最大的爱好就是上街卖你家祖传的煎饼果子，你想一天卖200个，但是在某些地方，你没法做到这一点，因为可能你一上街，城管把你的煎饼摊子给砸了。这时候，你移民去一个没有城管的国家，那就是很幸福的，因为你可以快乐的卖煎饼了。如果你的想法是你要移民，去某个国家把你家的煎饼果子给上市了，去纳斯达克敲锣，那肯定不幸福。所以，移民的目的是避免痛苦，而不是追求幸福，虽然这有点相同，但是不是同一件事情。痛苦无下限，幸福无上限。

-----

[[https://zhuanlan.zhihu.com/p/39573490][PID控制算法原理（抛弃公式，从本质上真正理解PID控制） - 知乎]](https://zhuanlan.zhihu.com/p/39573490)

这篇文章对PID算法解释得不错。

-----

[[https://world.hey.com/dhh/you-can-t-trust-google-f7d64064][You can't trust Google --- 你不能相信谷歌]](https://world.hey.com/dhh/you-can-t-trust-google-f7d64064)

All I'm saying is you better have a backup plan. Be that for your collaboration, your email, your home security system. Anything that reads "Made by Google" implicitly has the subscript "until we don't give a fuck any more" printed below.

我要说的是，你最好有一个备用计划。无论是用于您的协作、您的电子邮件还是您的家庭安全系统。任何写着“由谷歌制造”的东西都隐含地在下面印有下标“直到我们不再在乎”。

-----

[[https://www.dedao.cn/course/article?id=5Mr9mzb36pP4JL5R0AXkWqB2EYNegL&source=search][山姆·奥特曼的系统性野心（下） - 得到APP]](https://www.dedao.cn/course/article?id=5Mr9mzb36pP4JL5R0AXkWqB2EYNegL&source=search)

奥特曼的行事作风异于常人。比如非常讲求效率。他总是用最快的速度处理邮件和会议。如果他对你讲的东西感兴趣，他会全神贯注地盯着你听你讲话；如果他没兴趣他会很厌烦。他这种专注力甚至让人感觉他是不是有阿斯伯格综合征——也就是大脑有问题、但是对某些知识掌握得特别细的那种怪人——奥特曼说他不是。他还开玩笑说，为了让人相信他是一个正常人而非AI，他要练习多去几次厕所。

奥特曼有强烈的目标感，每年都要列一份目标清单，每隔几周看一次，想方设法把这几件事都做成。为了达成目标，他会一直工作、不惜累到病倒的程度。格雷厄姆的说法是「奥特曼非常善于变强大」。

奥特曼对新科技、新思想特别感兴趣，不但了熟于胸而且会用在生活上……比如说，他会告诉你微量的核辐射对身体有好处。

那为什么非得出来冒险呢？因为你要做一件了不起的事情。奥特曼认为，「做难的事情其实比做容易的事情更容易」——因为难的事情会吸引别人的兴趣，人们会愿意帮你一起做。同样是出来创业，你要说你们公司是做基因编辑的，大家会觉得这很有意思，会很愿意支持你；你要说我要再搞一个做笔记的APP，那没人在乎。

为了做难的事情，你需要有「绝对的竞争力」。这意味着你能做一些别人想模仿也模仿不好的事情，这也意味着你会非常反感平庸的东西。


第四个野心是建立一个宪章城市。也许在美国也许在国外某个地方，搞一个由商人和科技人员运行的、自我管理的全新型的城市。这个城市可能会有10万英亩土地，有5万到10万的居民。

奥特曼设想这个城市是21世纪的雅典，是一个精英社区，可以测试适应新技术的新管理方式，并且把主要管理职责交给AI。比如说，这里只允许自动驾驶汽车，不允许人类开车。再比如不允许任何人从房地产中赚钱。

……如果将来世界其他地方都陷入动乱，至少这个城市还是一个样板，能给人类保留一个希望。不过可能因为政策性的原因，这个项目目前尚未启动。

-----
[[https://www.dedao.cn/course/article?id=g258WANERjwQJDzlmgKbOMG1rZqkPl&source=search][累积出来的衰败 - 得到APP]](https://www.dedao.cn/course/article?id=g258WANERjwQJDzlmgKbOMG1rZqkPl&source=search)

秦制以来中国历代政府收税有个普遍规律，差不多是按照这样的节奏走——

1. 一开始，官方规定的“正税”，税率都不高，老百姓可以承受；
2. 随着政府规模变大，正税的税收已经不能维持运行，于是特别是地方政府，会发明各种新的名目收老百姓的钱，也就是苛捐杂税；
3. 苛捐杂税因为是灰色税收，容易滋生腐败，时间长了百姓怨声载道；
4. 这时候中央会搞一次税收改革，把所有杂税都合并到正税之中，来个正规化，简化手续，减少腐败——像唐朝的两税法、北宋王安石变法、明朝张居正的一条鞭法、清朝的摊丁入亩，都是如此；
5. 然而又过了一段时间，发现扩大后的正税又不够了，于是又开始征收新的杂税……

=====

公司也有东西在累积。

为什么公司做大了就容易僵化呢？根据鲁梅尔特在《关键难点》一书中的分析，我们大约可以说是因为一种「功臣文化」。

一家公司在历史上曾经有过非常辉煌的时期，造就了一批功臣，那么这些人从此之后就会把当初的做事方法给偶像化：我们这里就是这样做事的。

那么时间一长，再来新人，可就不能讲创新了，而是要讲服从、讲条例，要尊重老人的权威。老人纷纷要求提升自己的地位和势力范围，就好像一群老革命整天在那摆资历。公司坚定地生长着官僚主义。

简单说，是老人的资历和地位、用老方法做事的惯性在累积。

那你说怎么才能减轻累积呢？最简单的办法就是勤换人。「人」这种「子系统」的「多余功能」实在太多了。做官也好做事也好，你本来只是让这个人来工作，可是他会要求地位、他会发展自己的势力，他会想把亲朋好友也带来——你吸收一个人就等于吸收了一大堆人和事儿，岂能不衰败。最好在一个人生根发芽之前把他换掉。

这可能就是为什么大城市里的公司变僵化的速度比较慢。大城市里的公司有频繁的人员流动，跳槽、裁员、招聘都是家常便饭，人们本质上不是为一家公司、而是在一个职场圈里工作，就不太容易搞成树大根深。现代化的人才要么就有可替代性，要么就有易对接性，每个人都可以随时在另一家公司开展工作，那自然不容易腐化。

=====

我们这一讲全部要说的是，一个系统的衰败跟思想教育、组织纪律什么的关系不大，也不是文化的问题，而是无组织力量在暗中累积这个客观规律所导致的。就如同灌溉必然导致土地盐碱化一样。

要想基业长青，就必须用特别的制度抗衡累积过程。我们见过很多尝试，也取得了一定的效果，但是我们远远不能说已经解决了这个问题。

-----

[[https://www.dedao.cn/course/article?id=R2Mo65zY4QZ3Vn6OaVqEdNAa98jGBO&source=search][YC掌门人：给年轻人的建议 - 得到APP]](https://www.dedao.cn/course/article?id=R2Mo65zY4QZ3Vn6OaVqEdNAa98jGBO&source=search)

第五个建议和风险有关。大多数人都不太愿意承担风险。但山姆认为，一定要敢于承担更多的风险，尤其是你刚开始工作的时候。年轻和默默无闻其实是一个重要的竞争优势，因为这时候你几乎没有什么可以失去的。就算你失败了，也不要担心有什么问题，因为在生活中遇到的危机越多，下一次再遇到危机的时候，你害怕的就会越少。

山姆的第六个建议是，工资不能让你变得很富有。他说自己年轻的时候，觉得挣个不错的薪水就能变得富有。但是后来他意识到，想要致富，正确的方法应该是拥有价值能上涨的东西，比如股份。市场上还有一个很重要的套利机会，那就是“时间”。人们都希望在很短的时间赚到钱，所以一些长期的机会往往被忽视了。山姆说，正是这些机会帮他赚到了钱。所以和短期机会相比，长期的增长能让你赚到更多钱。你最好是在早期就去找这样的机会，如果失败了，没关系，你还可以继续尝试。

-----

[[https://lemire.me/blog/2023/06/14/citogenesis-in-science-and-the-importance-of-real-problems/][Citogenesis in science and the importance of real problems – Daniel Lemire's blog --- 科学中的细胞发生和实际问题的重要性——丹尼尔·勒米尔的博客]]

介绍一种 citogenesis 的现象，这种现象在科学界里面也比较常见：如果某个 claim 没有办法或者需要很高的成本才能进行验证的话，只要这种东西一旦流入权威的信息源，那么人们就会不断地重复和放大它。只有现实才能对这些情况进行矫正，可惜有很多领域是做不到这点的。

-----

[[https://world.hey.com/dhh/acting-your-wage-will-atrophy-your-abilities-1ca261c4][Acting your wage will atrophy your abilities --- “拿多少钱，干多少事”会萎缩你的能力]]

这篇文章说的非常好。如果你的技能不使用的话，就会萎缩掉。你肯定不想浪费自己的才华。所以不要使用类似 act your wage 这种行动（拿多少钱，干多少事），这样下来你浪费的只有自己的才华，并且最终一事无成。

And companies make employees feel like that all the time. This is part of what drives the whole “act your wage” rebellion. Why should you put in your best if work never seems to return the favor? It’s a perfectly human response of spite in the face of unfairness, but you can’t avenge your grievances by squandering your potential.

公司让员工一直有这种感觉。这是推动整个“行动你的工资”叛乱的部分原因。如果工作似乎永远不会得到回报，你为什么要尽力而为？面对不公平，这是完全人类的怨恨反应，但你不能通过浪费你的潜力来报仇。

Whatever the situation, whatever the company, you should show up with your very best. Not for them, but for you. Use the discontent to become better, then bolt to another camp when the opportunity presents itself.

无论情况如何，无论公司如何，您都应该全力以赴。不是为了他们，而是为了你。利用不满变得更好，然后在机会出现时跳到另一个阵营。

Besides, you’ll appreciate a good place so much more if you’ve made it through some bad places.

此外，如果你通过了一些糟糕的地方，你会更加欣赏一个好地方。

Don’t play yourself by living down to their expectations. Show yourself the path out by shining bright whatever the weather.

不要通过辜负他们的期望来玩弄自己。无论天气如何，都要闪耀着明亮的光芒，向自己展示出路。

-----

[[https://world.hey.com/dhh/we-need-not-all-be-connected-all-the-time-a4633c0e][We need not all be connected, all the time --- 我们不需要一直保持联系]]

看来 DHH 也被学校和家长之间这种即时通讯搞得怕了。


But what these wretched apps have wrought is a constant stream of needless communication and updates about life at school. Worse still, it's facilitated endless threads amongst parents on this thing or the other. And you're essentially obliged to partake in these non-stop chain mails, lest you miss a truly important or urgent message.

但是，这些可怜的应用程序造成的是源源不断的不必要的交流和关于学校生活的更新。更糟糕的是，它促进了父母之间关于这件事或另一件事的无休止的线索。你基本上有义务参与这些不间断的连锁邮件，以免错过真正重要或紧急的信息。


Not all connections benefit from having the friction removed by digital systems. Some barriers to interaction are good, actually. The fundamental premise that everything will be wonderful if we could just all be linked together everywhere, all the time is false.

并非所有连接都能从数字系统消除摩擦中受益。实际上，互动的一些障碍是好的。如果我们能随时随地联系在一起，一切都会变得美好的基本前提是错误的。

-----

[[https://world.hey.com/dhh/when-promotions-become-punishment-b1cc1430][When promotions become punishment --- 当升职成为惩罚]]

To be an effective manager, you have to be empathetic, but not too empathetic. Because if you can't separate yourself emotionally from the process, at least in part, you can't make the difficult-but-necessary decisions required to service the broader team. And it's really hard to know whether you have this in you until you're faced with the reality of a tough situation.

要成为一名有效的管理者，你必须善解人意，但不要太善解人意。因为如果你不能在情感上将自己与流程分开，至少部分地，你就无法做出为更广泛的团队服务所需的困难但必要的决定。在你面对艰难处境的现实之前，很难知道你是否拥有这种能力。

This is one of the key reasons to pursue minimalist management. By setting up processes that handle much of the mechanics of reporting, and clearly reveals someone's progress for all to see, as well as distributing the human elements, like mentorship, you can reap much of the benefit of letting senior people provide parts of the management work without the dreaded promotion into management per se.

这是追求极简主义管理的关键原因之一。通过建立处理大部分报告机制的流程，并清楚地揭示某人的进步供所有人看到，以及分配人为因素，如指导，你可以获得让高级人员提供部分管理工作的大部分好处，而不必被提升到管理层本身。


-----

[[https://www.inc.com/jeff-haden/37-years-ago-steve-jobs-said-best-managers-never-want-to-be-a-manager-science-says-he-was-right.html][37 Years Ago, Steve Jobs Said the Best Managers Never Actually Want to Be Managers. Science Says He Was Right | Inc.com --- 37年前，史蒂夫·乔布斯（Steve Jobs）说过，最好的经理人从来都不想成为经理。科学说他是对的 |Inc.com]]

[[https://www.youtube.com/watch?v=fj0hpsJvrko][Steve Jobs On Recruiting People - YouTube]]

You know who the best managers are? They're the great individual contributors who never, ever want to be a manager, but decide they want to be a manager, because no one else is going to be able to do as good a job as them.

你知道谁是最好的经理吗？他们是伟大的个人贡献者，他们从来不想成为经理，但决定要成为一名经理，因为没有人能像他们一样做好工作。

The next time you make a promotion decision, make sure you consider the great individual contributor who may not want to be a manager, but desperately wants to get things done.

下次你做出晋升决定时，一定要考虑那些伟大的个人贡献者，他们可能不想成为经理，但迫切地想把事情做好。

Because success always comes down to what your business accomplishes.

因为成功总是归结为您的业务所取得的成就。

Not what it manages. 不是它管理的东西。

-----

[[https://world.hey.com/dhh/start-them-in-the-deep-end-8c9c77fe][Start them in the deep end]]

因此，新员工在进入需要完成的实际工作的深渊之前，很少花超过一周的时间来熟悉环境。我一直很高兴看到，只要有机会，经常有人一开始就表现出自己是个优秀的游泳者。

不是每个人都会立即让你眼花缭乱，这也没关系。有些人确实需要更长的时间来适应，才能向你展示他们最好的一面。但这仍然是一个接触的功能。接触的挑战越多，大多数人就会越快发现自己熟悉对他们的要求。

你能对一个新员工做的最糟糕的事情就是让他们在组织的大厅里徘徊，没有充实的、有意义的、令人着迷的事情可做。每个值得聘用的人都想尽快地做出贡献。让他们来吧!
