#+title: 网络文章@202505

----------
A very funny but tricky bug I came across recently (Still need to confirm in CI/CD env [[Bugfix] Fix avx512 unaligned store by dirtysalt · Pull Request #59035 · StarRocks/starrocks](https://github.com/StarRocks/starrocks/pull/59035))

if you write avx2 instruction like, compiler respects your intention and generates "unaligned store"

#+BEGIN_QUOTE
_mm256_storeu_si256((__m256i*)p, x);
#+END_QUOTE

however if you write avx512 instruction like, compiler maybe think you give a hint that `p` is aligned to 64B, and generates "aligned store"

#+BEGIN_QUOTE
_mm512_storeu_si512((__m512i*)p, x);
#+END_QUOTE

And according to gpt explanation, it's because definition of `__m512i` is

#+BEGIN_QUOTE
typedef long long __m512i __attribute__((__vector_size__(64), __aligned__(64)));
#+END_QUOTE

Here are the instructions that generated SIGSEGV

#+BEGIN_EXAMPLE
   0x0000000029b7382e <+331>:   je     0x29b7383d <starrocks::delta_decode_chain_int32_avx512(int32_t*, int, int32_t, int32_t&)+346>
   0x0000000029b73830 <+333>:   mov    $0x40,%esi
   0x0000000029b73835 <+338>:   mov    %rax,%rdi
   0x0000000029b73838 <+341>:   call   0x19824bf0 <__asan_report_store_n>
=> 0x0000000029b7383d <+346>:   vmovdqa64 %zmm0,-0x180(%r13)
   0x0000000029b73844 <+353>:   vpxor  %xmm0,%xmm0,%xmm0
   0x0000000029b73848 <+357>:   lea    -0x100(%r13),%rax
   0x0000000029b7384f <+364>:   mov    %rax,%rdx
   0x0000000029b73852 <+367>:   shr    $0x3,%rdx
   0x0000000029b73856 <+371>:   add    $0x7fff8000,%rdx
#+END_EXAMPLE


-------
ETH Zurich Talk Jeff 2025.Apr14

Gemini Structure & Ways of Working

Many people in many locations:
- ~⅓ in San Francisco Bay Area
- ~⅓ in London
- ~⅓ in many other places:
- NYC, Paris, Boston, Zürich, Bangalore, Tel Aviv, Seattle, …

Time zones are annoying! “Golden Hours” between California/West Coast and London/Europe are important

Lots and lots of large and small discussions and information sharing conducted via Google Chat Spaces (I’m in 200+ such spaces)

RFCs (Request for Comment): semi-formal way of getting feedback, knowing what others are working on, etc.

Leaderboards and common baselines enable data-driven decision making about how to improve
- Multiple rounds of experimentation.
- Many experiments at small scale
- Advance smaller number of successful experiments to next scale
- Every so often (every few weeks), incorporate successful experiments demonstrated at largest experimental scale into new candidate baseline
- Repeat

--------

https://weibo.com/1745358631/PpOLBuLNx

对于写作者来说，「阶级感」这个东西是无法靠想象力去弥补的。不说亲自经历过吧，你至少得亲自见过，才有可能写得出来。

因为不同的阶级之间遵循着不同的生活逻辑，而两边的人都认为自己的生活逻辑是「寻常」，这两套「寻常」很可能是完全相反的。

我第一次看《红楼梦》的时候，看到袭人的妈妈病重了，她要回家去，然后王熙凤过来亲自检查了一遍她的衣物首饰等等，我下意识地就以为王熙凤这是怕她夹带东西出去。

我就很困惑地去问朋友，这是为什么，贾府不是很有钱吗。朋友给我解释说，不是怕她偷东西，是怕她的衣物首饰不够富贵、体面、气派，她当时已经是按姨娘的规格回家去了，她代表的是贾府的脸面。

就这个逻辑和动机，你让我这个根本没看过大户人家怎么生活的人去想，不管怎么用力想，都是很难想得出来的。

想象力要有生活根基，没有根基的想象力就只是在纯胡说八道。
