#+title: 网络文章@202410
------------

[A Love for Legacy – Signal v. Noise](https://signalvnoise.com/posts/3933-a-love-for-legacy)

One of the things that’s most interesting to me at Basecamp is that we wear our legacy applications as a badge of honor. The very first Rails application ever built still exists as Basecamp Classic. That is the application Ruby on Rails was both created for and born from. It’s easy to forget the weight of that sometimes. (我们以维护遗留应用为荣)

There is something very special about getting to work on the first Rails application. You can see how the Rails framework was built out of necessity and how it has since evolved over time. The Rails framework will continue to be guided by the real-world needs of our applications and now scores of others.(通过遗留程序我们可以看到Rails框架是如何构建出来解决问题的, 以及是如何进化的)

In programming, there is often an obsession with using the latest and greatest technology. Programmers view the use of edge technology as its own badge of honor, and are quick to throw away legacy applications. We don’t do that at Basecamp. We move forward while not forgetting and discarding our past. Programmers don’t put enough weight on the importance of legacy applications and systems. They wonder “why would someone write code this way,” without understanding the history of how the code base evolved. A legacy application can actually teach you more because it has lived in a way a new application has not. (在编程行业里面, 人们总是沉迷于最新最棒的技术, 并且以使用它们为荣, 然后很快地丢弃遗留代码. 遗留代码记录历史, 可以让我们避免犯过去所犯过的错误)


----------

[Power of Small Optimizations](https://maksimkita.com/blog/power-of-small-optimizations.html)


Generally, you need to have good introspection for your application and always profile your application, both in production and during development. You also need to be curious to explore every possible performance optimization opportunity. Even highly optimized places in your application can be optimized even further.

Examples of some optimizations for algorithms and data structures choice:

1. Use hybrid algorithms. Some algorithms or data structures can work well when the amount of data is small, but when the amount of data grows, the underlying algorithm or data structure needs to be changed.
2. Use statistics for run-time optimizations. All algorithm’s performance is affected by data distribution. For example, if you know the cardinality of your data in advance, it is possible to choose a faster algorithm or data structure.
3. Use specializations. You can specialize your algorithms and data structures for specific data types. For example, if you know that you need to sort integers, it makes sense to use radix sort instead of general comparison-based sort algorithms like pdqsort. Another example is if you need to sort integers, but they are always sorted or almost sorted, radix sort will be much slower than pdqsort.

You always need to start optimization with places that take most of the time during application execution. But usually, after you optimize every such place, it is hard to understand which places to optimize next. For example, when you investigate some potential place, and you already know that this place takes 3-5% of the whole application execution time, it is important to still improve this place, even if you can improve this place’s performance only by a small amount. If you optimize many such places, the compound result of such optimizations will be visible for the whole application.

----------

[JIT in ClickHouse](https://clickhouse.com/blog/clickhouse-just-in-time-compiler-jit) 写的挺好的文章

---------------

[CPU Dispatch in ClickHouse](https://clickhouse.com/blog/cpu-dispatch-in-clickhouse)

```C++
__attribute__((target("sse,sse2,sse3,ssse3,sse4,avx,avx2")))
void plusAVX2(int64_t * __restrict a, int64_t * __restrict b, int64_t * __restrict c, size_t size)
{
    for (size_t i = 0; i < size; ++i) {
        c[i] = a[i] + b[i];
    }
}
```


告诉编译器利用这些指令集合来优化下面的函数.

使用cpu dispatch每次还是有cpu feature set的判断，好处是如果短小代码可以直接inline, 但是还是有分支判断，适合放在头文件里面。

另外一个实现是初始化使用cpu dispatch来安装函数指针，这样每次调用没有分支判断，但是有个function pointer call.

-------------------


[[https://jyywiki.cn/Letter.md][给各位天命人的劝退信]]

于是现在 “研究生生涯” 就成了多方在多种利益面前不得已做出的一个权衡和妥协。聪明的老板们已经把自己打造成了无情的营盘，提供实验的机器、几篇相关工作、一个粗犷的想法，还有一个还算靠谱的师兄，剩下你就跟打工人一样直面天命吧。往好的方面想，你从事了本专业的工作 (给老板搬了砖) 换来了老板的指导和学历学位。无论是做了真研究，还是做了工程写了代码，哪怕就是在论文流水线工厂上写了个 related work，对专业精进总还是有益的。至于和其他方面利益的权衡：(你和老板) 的职业生涯、(你和老板) 个人兴趣、各种需要完成的杂事 (杂事总有人要完成)，天命人自有天命。

天命人们要意识到国家和学校在博弈，学校和院系在博弈，院系和教师在博弈，教师和金字塔底层的吗喽们也在博弈。比如经济上行周期时的指挥棒是 SCI 论文，成就了今天的生化环材。我眼睁睁看着化院的精神小伙被导师催残得人样都快没了，博士毕业进了工业界立马满血复活。2010 年 CCF 发布了论文分级列表，计算机系立马行动制定了 “毕业套餐”。2011 年[[https://ics.nju.edu.cn/~xxm/][马所长]]发表了南大软件所第一篇软工 A 类会议论文 (FSE)。我在 PhD 期间发了 ICSE'14, ASE'15 和两篇 FSE'16，那时候 Program Committee 都没啥华人，甚至还有素不相识的 PC 在 pdf 上从头到尾批注论文，我这个产量在同龄人中也算是很可以了。再看看今天，软工四大会都快成 Chinasoft 了，论文迅速贬值 (没有像样的论文基本就直接出局了)，你还得去卷别的东西：系统工程实现、影响力、研究工作的企业转化，最终变成人才头衔……指挥棒的初衷都是好的，但是嘛，有人的地方就有江湖，至于怎么包装自己的成果，那就是八仙过海、见仁见智了。

所以本质的矛盾是，大部分天命人希望的是获得指导、提升自己、求得职位。但无论是哪种导师，想做大工作的、想做项目的、想躺平的，都很有可能和你的利益发生冲突。你最想要一秒立即毕业，不想浪费时间做没用的项目，但先富起来的人拉高了标准，老板还想叫你出活。吗喽们刚刚经历了 “上课耽误学习” 的本科四年，就被赶鸭子上架，只顾着焦虑地刷 GPA 和各种履历想让自己在竞争中能取得一些优势，结果反而导致了基础不牢，写代码都还是个半吊子，于是产生出许多因果的报应，看看[[https://www.zhihu.com/question/665648172][这个有趣的知乎问题]]吧。

知乎问题 “[[https://www.zhihu.com/question/609920887/answer/3413670376][博士是怎么废掉的]]” 下有一个很有趣的回答：

#+BEGIN_QUOTE
高效率组: 流水线 + 只抓问题关键 + 追热点，出成果快，正反馈多。由于科研压力大，是非很少。在这种组里只要能跟对高年级的就能顺利毕业。低效率组: 没有任何操作规程，每个人上手都得自己淌着石头过河，喜欢讨论问题，一个芝麻绿豆都能讨论几个月没有定论，一篇文章改到每句话都是导师写的，出成果非常慢，在无休止的重新分析和一遍一遍修改文章的过程中磨灭了对科研的热情。由于效率低，大家磨洋工，是非很多。在这种组里很容易废掉。

以上，高效率组在国内常见，低效率组在欧洲常见，请对号入座，慎重选择。
#+END_QUOTE


#+BEGIN_QUOTE
我现在觉得欧洲“低效率组”是在刷人。见过几个真正有潜力成为大教授的，在博士期间就展现出来很强的实力，能够靠自己提炼课题、非常专注、效率很高，擅于跟身边人合作、有个人魅力善于社交。毕竟在欧洲职位非常少，这种学术新星才是学界希望看到的。大多数资质平平的就躺着毕业，然后润工业界了
#+END_QUOTE

#+BEGIN_QUOTE
低效率组培养能力，让你从实验设计到写文章能自己走通，而不是当个流水线操作员。
#+END_QUOTE
