#+title: 网络文章@202502


--------

https://weibo.com/1261531020/PcJwhs37Y

你可以在油管搜Care less. 我觉得这是一个看透了大公司体制且有大智慧和大爱的人无私的分享。我也分享给你们：

1. 在大公司大机构里，智商高的人常常会困惑，这个是正常的。恭喜你自愿加入了权威体制的资本主义大公司。
2. 智商高对自己要求高的人常常想不自觉地改变一些什么，做出什么巨大的贡献。他劝告大家尽早放弃这种妄念。
3. 在权威体制的大公司里，每个人的作用都很小。每一件事，每一个流程和工具为什么会这样，背后都是有原因的。你不要去改变这些，这会得罪很多人，最后走人的是你。
4. 清楚了这些，你要做的就是用每天两小时的时间做好你分内的事情。其余的时间建立关系。跟那些关键的人搞好关系（这个好难的， 我从来没试过，感觉比工作还累）。
5. 你总想着如果你工作中能做出贡献带来impact，就能得到提拔。这也是所有公司的表现评估performance review里说的。他说，我做了大大小小很多公司的咨询，帮助设计performance review。 但实际上公司的performance review都是一个摆设而已。大部分情况下，你的提拔不是（仅仅）因为你的工作，而是上面某个人某个组织看上了你，批准了你的提拔。不然你的贡献都是假的。
6. 不要去质疑或者对现有的做法，工具，流程提意见，你会得罪一大堆人，吃力不讨好。
7. 除了流水线记件工人或者销售类的工作，大部分白领工作其实是无法直接测量生产力的。如果你效率提高了，自动化了一些流程，不要让人觉得你就很空了。因为你如果自动化了一些东西，很可能就不需要那么多人了，大家都需要一份工作的安全感。不要说破。你剩下来的时间做其他事情好了，要告诉大家你依然很忙。不管什么时候谁问你工作如何，你都要告诉他们你很忙。
8. 自动化越多的人，可能就是那个最早让你走路的人。这是大公司，缺了谁都照样转。再次提醒是你自己选择了在一个威权体制的工作。
9. 因为是威权体制，老板说啥就不要顶着干。他们说啥就是啥。不要有自己的想法，不要给自己加戏。
10. 不要在老板面前投诉任何人。你指望他们为你做啥？你也不知道你投诉的人在公司里盘根错节的关系。兴许他是哪个VP的心腹，兴许他做出过很大的贡献，兴许他是个表现很差的人，但干掉他需要很久很久。总之，你老板也不可能说第二天就干掉他。你不会知道会发生什么，而且老板还想你既然投诉了其他人，会不会也在背后投诉他等等。

永远永远记住，你就是一个COGS生产成本。不要给自己加戏。
