#+title: 网络文章@202410


-------------------


[[https://jyywiki.cn/Letter.md][给各位天命人的劝退信]]

于是现在 “研究生生涯” 就成了多方在多种利益面前不得已做出的一个权衡和妥协。聪明的老板们已经把自己打造成了无情的营盘，提供实验的机器、几篇相关工作、一个粗犷的想法，还有一个还算靠谱的师兄，剩下你就跟打工人一样直面天命吧。往好的方面想，你从事了本专业的工作 (给老板搬了砖) 换来了老板的指导和学历学位。无论是做了真研究，还是做了工程写了代码，哪怕就是在论文流水线工厂上写了个 related work，对专业精进总还是有益的。至于和其他方面利益的权衡：(你和老板) 的职业生涯、(你和老板) 个人兴趣、各种需要完成的杂事 (杂事总有人要完成)，天命人自有天命。

天命人们要意识到国家和学校在博弈，学校和院系在博弈，院系和教师在博弈，教师和金字塔底层的吗喽们也在博弈。比如经济上行周期时的指挥棒是 SCI 论文，成就了今天的生化环材。我眼睁睁看着化院的精神小伙被导师催残得人样都快没了，博士毕业进了工业界立马满血复活。2010 年 CCF 发布了论文分级列表，计算机系立马行动制定了 “毕业套餐”。2011 年[[https://ics.nju.edu.cn/~xxm/][马所长]]发表了南大软件所第一篇软工 A 类会议论文 (FSE)。我在 PhD 期间发了 ICSE'14, ASE'15 和两篇 FSE'16，那时候 Program Committee 都没啥华人，甚至还有素不相识的 PC 在 pdf 上从头到尾批注论文，我这个产量在同龄人中也算是很可以了。再看看今天，软工四大会都快成 Chinasoft 了，论文迅速贬值 (没有像样的论文基本就直接出局了)，你还得去卷别的东西：系统工程实现、影响力、研究工作的企业转化，最终变成人才头衔……指挥棒的初衷都是好的，但是嘛，有人的地方就有江湖，至于怎么包装自己的成果，那就是八仙过海、见仁见智了。

所以本质的矛盾是，大部分天命人希望的是获得指导、提升自己、求得职位。但无论是哪种导师，想做大工作的、想做项目的、想躺平的，都很有可能和你的利益发生冲突。你最想要一秒立即毕业，不想浪费时间做没用的项目，但先富起来的人拉高了标准，老板还想叫你出活。吗喽们刚刚经历了 “上课耽误学习” 的本科四年，就被赶鸭子上架，只顾着焦虑地刷 GPA 和各种履历想让自己在竞争中能取得一些优势，结果反而导致了基础不牢，写代码都还是个半吊子，于是产生出许多因果的报应，看看[[https://www.zhihu.com/question/665648172][这个有趣的知乎问题]]吧。

知乎问题 “[[https://www.zhihu.com/question/609920887/answer/3413670376][博士是怎么废掉的]]” 下有一个很有趣的回答：

#+BEGIN_QUOTE
高效率组: 流水线 + 只抓问题关键 + 追热点，出成果快，正反馈多。由于科研压力大，是非很少。在这种组里只要能跟对高年级的就能顺利毕业。低效率组: 没有任何操作规程，每个人上手都得自己淌着石头过河，喜欢讨论问题，一个芝麻绿豆都能讨论几个月没有定论，一篇文章改到每句话都是导师写的，出成果非常慢，在无休止的重新分析和一遍一遍修改文章的过程中磨灭了对科研的热情。由于效率低，大家磨洋工，是非很多。在这种组里很容易废掉。

以上，高效率组在国内常见，低效率组在欧洲常见，请对号入座，慎重选择。
#+END_QUOTE


#+BEGIN_QUOTE
我现在觉得欧洲“低效率组”是在刷人。见过几个真正有潜力成为大教授的，在博士期间就展现出来很强的实力，能够靠自己提炼课题、非常专注、效率很高，擅于跟身边人合作、有个人魅力善于社交。毕竟在欧洲职位非常少，这种学术新星才是学界希望看到的。大多数资质平平的就躺着毕业，然后润工业界了
#+END_QUOTE

#+BEGIN_QUOTE
低效率组培养能力，让你从实验设计到写文章能自己走通，而不是当个流水线操作员。
#+END_QUOTE
