#+title: 每年阅读500本书
from 硅谷王川公号2020年合集

1/ 人们遇到棘手问题时，直觉反应往往是加大马力继续强攻，把自己搞得悲壮不已，但没啥用。从更高的视角看，大部分路径都是死胡同或者非最佳选择。可行的策略，应当是不带预设立场，不断增加和外界的信息连接，这样尽可能接近甚至参与全球最优解的生成。这实际上就是摩尔定律真正的发展规律。这个话题，可以参见我的老文章《王川: 为什么摩尔定律一直没死, 但人们还会继续预测摩尔定律要死》

2/ 冥思苦想一些问题，尤其是战略问题，如果觉得没有进展的话，最好的方法是多读书，这相当于自然而然的引入一些新的外在的变量，然后发现想不通的问题有可能在别的地方联通。更好的办法是读一会书，再去打打太极拳，一打拳，大脑一放松，不再专注某个狭隘的角度，很多清奇的想法就冒出来了。

3/ 大部分时间在做执行和重复度比较高的工作的人，没机会接触新人新思想，没时间去向外探索，因此很难获得这种愉悦感，这对身心健康有很大害处。

6/ 非理性大脑 (limbic system) 有时可以比理性大脑提前预测感知一些趋势。比如有时遇到困难，意识到前面的某个路被堵住了，还没完全想清楚的时候，这种焦虑就已经影响到自己的情绪，让人感到不舒服了。

7/ 反之，如果在读书中有新的发现，意识到未来增加了很多全新的选择，理性大脑还没完全梳理清楚这个逻辑的时候，非理性大脑已经开始庆祝，多巴胺爆表，大脑不由自主地充满喜悦。这是个可以不断重复的，很有意思的现象。

8/ 从自己感兴趣的书开始慢慢读，如果读了五到十分钟还不觉得有趣就放下，也许以后再回头来读。读着读着你就会发现自己的认知慢慢螺旋式上升，像爬山一样，视野慢慢开阔，渐入佳境。读电子书做这种切换，比纸质书方便多了。

26/ 反思过去各种挫折的时候，意识到挫折的本质实际上不是努力不够，人不够聪明，而是信息不足。信息不足的时候，人们往往无法意识到自己真正的短板，在于信息不足！信息不足，选择就很少。选择少，意味着费牛劲试图解决一个完全错误的问题，很长时间没啥进步，内心痛苦而愤怒。但以过去的物质条件，实际上很难突破这种信息不足的困境。而现在一切都变了，信息是海量的廉价的。就等着有心人去开拓。

27/ 没有通过读书读史建立的全局视角和跨越长时间的视角，凭个人经验总结的原因和方法论会有大问题。很多跨越十几年，二十几年或更长的历史经验教训，只能从书里面找到。尤其是那些短期局部，看上特别有道理有诱惑性欺骗性，但长期全局，可能造成重大的甚至毁灭性损失的陷阱。这种教训，如果要靠亲自吃亏去学来，那代价是无法承受的。

33/ 人如果一天不读新书接触新思想知识，大脑就会内卷化。这里内卷化可以理解为同样一些想法思绪毫无新意地翻来覆去，浪费能量，人毫无进步，偏执顽固而不自知。一个地方的人如果不向外探索，开辟大量新的物理空间，也会内卷化，大家在红海市场里痛苦地玩零和游戏。

34/ 内卷化世界的人爱装 b，把一些底层逻辑本来很简单的事情，云山雾海绕来绕去，讳莫如深。外卷化的世界，逻辑简单清晰，干柴烈火，大家都很忙，有很多活要干，有很多新的空间要去探索。

35/ 内卷化的世界，会把各种约束和习惯当成理所当然，而只有在引入外界变量和增量发生巨大改变后，才会意识到当初的习惯和思维，何等低级可笑。对内挖潜是有限的，向外建立新连接引入增量是无限的，甚至指数增长的。

36/ 人的焦虑，本质是是来自低维度的认知，以为某些障碍自己一定必须要努力跨过去，然后心急火燎。而多读大量多学科的书籍，可以不断低成本地发现新的维度，让自己轻松绕过一些单维度上的障碍。这个过程没有上限。
