#+title: 网络文章@202505


-------

https://weibo.com/1401527553/HnKZrnXCu

作为一个讲文明懂礼貌说话温和的读书人，我偶尔也会表现得不太像读书人。

我有个老熟人，比我还温和，长得也面善。但他有个优势，他是东北人。虽然平时普通话说的特别好，但东北话也很流利。所以有朋友遇到无赖，比如欠钱不还什么的，就请他去出面，用东北话和别人交流。他一交流，事情就很容易交流好。

某个银行的人跟我说过，他们内部有看人下菜碟的培训。比如工作出错、理论上需要赔客户钱的时候，会根据客户的刺儿头指数来定赔偿金额。本来应该赔两万，如果发现是个好说话的，那就先赔五千试试，或者再拖一拖。如果发现是十级刺儿头，那么起码赔一万五，或者就赔足两万。

人类能演化到今天，贱是我们生存策略的一部分。当然有些人在有些时候能把这个贱压制住。但是啊，漫漫人生路，你这辈子一定会遇到贱人贱事。不止一个，不止十个，会遇到很多。同时呢，当人作为群体存在的时候，还可能出现群体性的贱，制度性的贱。所以，作为一个读书人，也应该学一学怎么面对贱人，怎么处理贱事。


--------

[[https://www.thecoder.cafe/p/complex-systems][在复杂系统中工作：我在谷歌工作时学到的东西 --- Working on Complex Systems: What I Learned Working at Google]]

Recognizing whether a system is complicated or complex is really important. Indeed, we mentioned that complicated systems are by definition repeatable, while complex systems require unique and customized approaches. Therefore, if we try to apply a common solution to a complex problem, **it may not lead to effective results**.
识别一个系统是复杂还是复杂，这一点非常重要。事实上，我们提到过，复杂系统顾名思义是可重复的，而复杂系统则需要独特的定制方法。因此，如果我们试图用通用的解决方案来解决复杂的问题，可能不会取得有效的结果。

To summarize this section, complex systems:
本节总结复杂系统：

- Are difficult to understand just by looking at its parts separately.
    单看其各个部分是很难理解的。

- Don’t always show their effects right away, consequences can be delayed.
    它们的影响并不总是立竿见影，后果可能是延迟的。

- Don’t always improve as a whole when one part is optimized and changes can sometimes make things worse.
    优化某个部分并不总能使整体得到改善，改变有时会使情况变得更糟。

- Can keep being influenced by past states, even after the original cause is gone.
    即使在最初的原因消失后，仍会继续受到过去状态的影响。

- Can react to small changes with big or unexpected effects.
    能对微小变化做出反应，从而产生巨大或意想不到的影响。

-------

https://news.ycombinator.com/item?id=44008843

I think we are going to be seeing a vast partitioning in society in the next months and years.
我认为，在未来数月或数年内，我们将看到社会的巨大分化。

The process of forming expressions just is the process of conceptual and rational articulation (as per Brandom). Those who misunderstand this -- believing that concepts are ready made, then encoded and decoded from permutations of tokens, or, worse, who have no room to think of reasoning or conceptualization at all -- they will be automated away.
表达的形成过程恰恰就是概念和理性的表述过程（如布兰多姆所言）。那些误解了这一点的人--认为概念是现成的，然后通过符号的排列组合进行编码和解码，或者更糟糕的是，根本没有思考推理或概念化的余地--他们将被自动淘汰。

I don't mean that their jobs will be automated: I mean that they will cede sapience and resign to becoming robotic. A robot is just a "person whose work or activities are entirely mechanical" ([[https://www.etymonline.com/search?q=robot][https://www.etymonline.com/search?q=robot]]).
我不是说他们的工作将实现自动化：我的意思是，他们将放弃智慧，甘愿成为机器人。机器人只是一个 "工作或活动完全机械化的人"（https://www.etymonline.com/search?q=robot）。

I'm afraid far too many are captive to the ideology of productionism (which is just a corollary of consumerism). Creative activity is not about content production. The aim of our creation is communication and mutual-transformation. Generation of digital artifacts may be useful for these purposes, but most uses seem to assume content production is the point, and that is a dark, sad, dead end.
恐怕有太多的人被生产主义（这只是消费主义的必然结果）的意识形态所俘虏。创作活动不是内容生产。我们创作的目的是交流和相互转化。数字艺术品的生成可能对这些目的有用，但大多数用途似乎都认为内容生产才是重点，而这是一条黑暗、可悲的死胡同。


----------
A very funny but tricky bug I came across recently (Still need to confirm in CI/CD env [[Bugfix] Fix avx512 unaligned store by dirtysalt · Pull Request #59035 · StarRocks/starrocks](https://github.com/StarRocks/starrocks/pull/59035))

if you write avx2 instruction like, compiler respects your intention and generates "unaligned store"

#+BEGIN_QUOTE
_mm256_storeu_si256((__m256i*)p, x);
#+END_QUOTE

however if you write avx512 instruction like, compiler maybe think you give a hint that `p` is aligned to 64B, and generates "aligned store"

#+BEGIN_QUOTE
_mm512_storeu_si512((__m512i*)p, x);
#+END_QUOTE

And according to gpt explanation, it's because definition of `__m512i` is

#+BEGIN_QUOTE
typedef long long __m512i __attribute__((__vector_size__(64), __aligned__(64)));
#+END_QUOTE

Here are the instructions that generated SIGSEGV

#+BEGIN_EXAMPLE
   0x0000000029b7382e <+331>:   je     0x29b7383d <starrocks::delta_decode_chain_int32_avx512(int32_t*, int, int32_t, int32_t&)+346>
   0x0000000029b73830 <+333>:   mov    $0x40,%esi
   0x0000000029b73835 <+338>:   mov    %rax,%rdi
   0x0000000029b73838 <+341>:   call   0x19824bf0 <__asan_report_store_n>
=> 0x0000000029b7383d <+346>:   vmovdqa64 %zmm0,-0x180(%r13)
   0x0000000029b73844 <+353>:   vpxor  %xmm0,%xmm0,%xmm0
   0x0000000029b73848 <+357>:   lea    -0x100(%r13),%rax
   0x0000000029b7384f <+364>:   mov    %rax,%rdx
   0x0000000029b73852 <+367>:   shr    $0x3,%rdx
   0x0000000029b73856 <+371>:   add    $0x7fff8000,%rdx
#+END_EXAMPLE


-------
ETH Zurich Talk Jeff 2025.Apr14

Gemini Structure & Ways of Working

Many people in many locations:
- ~⅓ in San Francisco Bay Area
- ~⅓ in London
- ~⅓ in many other places:
- NYC, Paris, Boston, Zürich, Bangalore, Tel Aviv, Seattle, …

Time zones are annoying! “Golden Hours” between California/West Coast and London/Europe are important

Lots and lots of large and small discussions and information sharing conducted via Google Chat Spaces (I’m in 200+ such spaces)

RFCs (Request for Comment): semi-formal way of getting feedback, knowing what others are working on, etc.

Leaderboards and common baselines enable data-driven decision making about how to improve
- Multiple rounds of experimentation.
- Many experiments at small scale
- Advance smaller number of successful experiments to next scale
- Every so often (every few weeks), incorporate successful experiments demonstrated at largest experimental scale into new candidate baseline
- Repeat

--------

https://weibo.com/1745358631/PpOLBuLNx

对于写作者来说，「阶级感」这个东西是无法靠想象力去弥补的。不说亲自经历过吧，你至少得亲自见过，才有可能写得出来。

因为不同的阶级之间遵循着不同的生活逻辑，而两边的人都认为自己的生活逻辑是「寻常」，这两套「寻常」很可能是完全相反的。

我第一次看《红楼梦》的时候，看到袭人的妈妈病重了，她要回家去，然后王熙凤过来亲自检查了一遍她的衣物首饰等等，我下意识地就以为王熙凤这是怕她夹带东西出去。

我就很困惑地去问朋友，这是为什么，贾府不是很有钱吗。朋友给我解释说，不是怕她偷东西，是怕她的衣物首饰不够富贵、体面、气派，她当时已经是按姨娘的规格回家去了，她代表的是贾府的脸面。

就这个逻辑和动机，你让我这个根本没看过大户人家怎么生活的人去想，不管怎么用力想，都是很难想得出来的。

想象力要有生活根基，没有根基的想象力就只是在纯胡说八道。
