#+title: 网络文章@202305

-----

[[https://www.benkuhn.net/blub/][In defense of blub studies | benkuhn.net]]

blub是指那些没有太多思想内容，但是却有助于完成我们日常任务的知识。

学习这些知识可以解决掉真正研究中出现的阻碍，提高工作效率甚至完成某些“不可能”的任务。

它似乎是某种“通行证”：如果你没有它，那么可能都没有办法展开non-blub study.

-----

[[https://www.benkuhn.net/rha/][Readability, hackability, and abstraction | benkuhn.net]]

复制粘贴代码具有可读性和可破解性，但抽象性差。

大型函数树是可读和抽象的，但很难破解。

有状态对象和虚拟调度都是可破解的和抽象的，但很难理解。

我还没有找到任何模式可以同时完成所有这三个。


-----

[[https://world.hey.com/dhh/the-luxury-of-working-without-metrics-02e5dbac][The luxury of working without metrics]]

数据驱动和直觉驱动，感觉就是理性和感性。我理解DHH的意思就是，不要太依赖于数据驱动/理性来打造在错误的方向上打造产品，如果方向错了，那么更加完善的数据驱动只会让这艘船在错误的方向上越走越远，最后迷失在海洋中。

Wu Wei(无为)就是需要依靠事物本身的发展规律行事。

-----
[[https://world.hey.com/jason/the-difference-between-time-and-attention-bdd955eb][时间和注意力的区别]]

时间和注意力的确是不同的东西。

有时候专心想事情，很难把自己在抽取出来，因为自己的状态在那件事情上。

即使自己很空闲，状态也还在那里。

-----

[[https://world.hey.com/dhh/compressing-a-million-dollar-commercial-into-37-000-0a99a38e][Compressing a million-dollar commercial into $37,000]]

广告运营成本不低，basecamp在这方面全年预算是5M. 投放成本可能是拍摄成本的4-5倍。如果你的预算有5M的话，那么实际上拍摄费用只能有1M.

这些做惯了大单的agency, 上来就是大手笔，要租几天风洞。这种风洞是只有F1和空气动力学专家使用的设施。

#+BEGIN_QUOTE
The agency wanted to spend one million dollars on a thirty-second spot, which, while funny and clever, involved renting an actual wind tunnel for a couple of days. You know, those facilities used by Formula 1 teams and aerodynamicists.
#+END_QUOTE

-----

[[https://world.hey.com/dhh/how-to-have-buckets-of-time-38693993][How to have buckets of time]]

避免上下文切换分散自己的注意力，DHH在各个方面都是这样做的：email，github issue, expense,

-----

[[https://world.hey.com/dhh/the-hardware-we-need-for-our-cloud-exit-has-arrived-99d66966][The hardware we need for our cloud exit has arrived]]

从云上面下来自己买机器，一共买了20台机器，每台机器384GB内存挺大的。

#+BEGIN_QUOTE
Each of these R7625s contain two AMD EPYC 9454 CPUs running at 2.75GHz with 48 cores / 96 threads. That means we're adding almost 4,000 vCPUs to our on-premise fleet! And a ridiculous 7,680 GB of RAM! And 384TB of Gen 4 NVMe storage! Serious horsepower and headroom for years to come. In addition to this, we have another ~six database servers showing up between now and this summer, and then we'll be set.
#+END_QUOTE

**UPDATE**: [[https://world.hey.com/dhh/cut-cloud-before-payroll-a4530ebd][Cut cloud before payroll]]

-----

[[https://world.hey.com/dhh/we-spent-300k-on-billboards-in-boston-and-it-was-a-bust-2ae8c9dd][We spent $300K on billboards in Boston and it was a bust]]

在SFO路上有很多这样的广告牌。老板们打上自家产品的广告，上下班看到这些牌子会有点小激动，但是实际没啥效果。

#+BEGIN_QUOTE
I will say that it felt pretty cool to see the irreverent Basecamp marketing messages appear on building-hugging billboards. There was an emotionally gratifying return on the investment. And perhaps that explains why it used to be common to see business software advertised in places like San Francisco where a lot of executives of such companies could feel good about seeing them. There's something gratifying about being in the real world like this.
#+END_QUOTE

#+BEGIN_QUOTE
But yeah, it didn't work. We won't be doing that again. But we'll always have the pictures
#+END_QUOTE

-----

[[https://world.hey.com/dhh/how-to-continue-making-kerosene-lamps-on-the-eve-of-electricity-5a8b8e1a][How to continue making kerosene lamps on the eve of electricity]]

这篇文章的标题真是漂亮 “如何在有电的前夕继续制造煤油灯“

#+BEGIN_QUOTE
这种可视化的目的不是要堕入职业虚无主义的墓穴中。我们现在所做的一切都不重要，因为即将到来的人工智能霸主将在瞬间解除我们的职责。但是要鼓起谦卑之心，接受这样的事实：是的，偶尔，甚至很少，世界真的会发生巨大的变化。培养对你无法改变的东西的生存恐惧是没有任何好处的。
#+END_QUOTE

#+BEGIN_QUOTE
我喜欢想象，我们所有从事软件开发的人，就像今天看起来的那样，正忙着制造各种形状和大小的漂亮煤油灯。我们在提高燃烧效率。我们在寻找更清晰的玻璃形式来让光线通过。我们在修补一个已经存在了很长时间的配方。但在我们这样做的时候，爱迪生和特斯拉正在另一个房间里忙着发明电力。
#+END_QUOTE

#+BEGIN_QUOTE
我确信，即使对爱迪生和特斯拉来说，也根本不清楚到底什么时候才会翻开那最后的灯泡时刻的开关。而与此同时，世界仍然需要在黑暗中看到东西，所以古老的灯仍然是必要的。这可能就是我们，现在，用可能很快成为过去的方式照亮通往未来的道路。
#+END_QUOTE

-----

[[https://world.hey.com/dhh/the-responsibility-is-the-reward-69e5b73f][The responsibility is the reward]]

责任就是奖励，承担更多的责任会让自己感觉被需要，人生也会更加有意义。

如果人们将开源项目认为是第二份收入微薄的工作的时候，那么他很快就会丧失动力。

我理解作者的意思还是应该将开源项目的贡献，看做是一种责任/奖励而不是一份工作，否则这个东西没有办法长期坚持下去。


-----

[[https://www.youtube.com/watch?v=oxj5mUYUqDk][(2) How to Learn a Language On Your Own - YouTube]]

起始阶段：
- 挑选几个入门书籍阅读，熟悉上下文之后也可以不断查阅
- 从各种角度的视频/音频涵盖学习内容，之间有交叉是好事
- 不要硬记所有东西，不断地洗脑就行(wash brain)
- 这个阶段主要就是建立语感，并且让自己感兴趣，然后了解一些上下文。

中间阶段：
- 阅读更多的视频/音频
- 挑选自己感兴趣的主题
- 设置目标不断驱动自己


提高阶段：找更多的人进行交流，这个时候你基本上已经掌握了这门语言。
-----

[[https://surma.dev/things/c-to-webassembly/index.html?continueFlag=713ef5f04016ab5f5772f45827d51233][Compiling C to WebAssembly without Emscripten — surma.dev]]

利用llvm把C代码编译成为wasm模块，并且在浏览器里面运行。

但是目前wasm里面比较难实现libc这些功能，因为libc通常都是和系统相关的实现。

这个正是 https://emscripten.org/ 要做的事情，端到端地实现C/C++编译到wasm，而不用考虑libc这些问题。

-----

[[https://world.hey.com/dhh/sitting-on-the-bench-ba937b84][Sitting on the bench]]

DHH 真的很擅长写爽文。能够将你的talent完全发挥固然很好，但是就怕这种单纯发挥没有任何回报，所以上一条行驶比较快的穿更加重要一些，而不是大公司还是小公司的问题。


-----

[[https://world.hey.com/dhh/even-amazon-can-t-make-sense-of-serverless-or-microservices-59625580][Even Amazon can't make sense of serverless or microservices]]

[[https://world.hey.com/dhh/how-to-recover-from-microservices-ce3803cc][How to recover from microservices]]

aws prime video 自己给 "microservices/serverless" 的檄文

以及如何正确地使用 "microservices/serverless". 不要觉得这个就是灵丹妙药

-----

[[https://world.hey.com/dhh/it-s-not-just-cloud-costs-that-are-out-of-control-efcd098c][It's not just cloud costs that are out of control]]

这个这没有想到datadog可以这么赚钱，一个搞加密货币的客户付费65M。

#+BEGIN_QUOTE
At the risk of invoking a tired cliche, this kind of outlay for a performance and monitoring service sounds like a 0% interest rate phenomenon. There's just no universe I can imagine where that's a reasonable commitment. One that couldn't be more than adequately replaced by open-source alternatives. Even if you needed a fair bit of in-house development on top for tailoring.
#+END_QUOTE

-----

[[https://world.hey.com/dhh/the-misallocation-of-tech-talent-6c3b4403][The misallocation of tech talent]]

感觉每天DHH都在写文章，而且还挺有深度的。

裁员可以让做狗屁事情的人才资源被更加合理地利用，但是为了还房贷做狗屁事情也不丢人。

#+BEGIN_QUOTE
Now arguing what is or isn't best for the individual is tricky business. I'm sure there are plenty of laid off tech workers who'd say they'd happily hold that bullshit job if it meant paying the mortgage. I get that. So let's return to the group perspective.
#+END_QUOTE

-----

[[https://lemire.me/blog/2023/04/21/will-emerging-artificial-intelligence-boost-research-productivity/][Will emerging artificial intelligence boost research productivity? – Daniel Lemire's blog]]

看上去大部分的文章都是灌水工作

#+BEGIN_QUOTE
The problem, as pointed out by Caplan, is that nobody cares about these research articles. In fact, if you asked engineers to pay the authors to access their research articles, they almost certainly would not be willing to pay.
#+END_QUOTE

-----

[[https://lemire.me/blog/2023/04/27/hotspot-performance-engineering-fails/][Hotspot performance engineering fails – Daniel Lemire's blog]]

youtube: https://youtu.be/x2EOOJg8FkA

为什么按照"hotspot驱动进行优化"的方式是不work的？

因为这种方式工作的前提是有个正确架构，然后才能在里面找hotspot, 否则处处都是hotspot.

这也是为什么许多优化项目最后只能被重写：房子地基不行只能拆掉重盖。

-----

[[https://www.youtube.com/watch?v=zMhCnb-TcUs&list=WL&index=9][【李自然说】《富人思维》解读，千倍回报投资人养成攻略 - YouTube]]

1. 富人思维与穷人思维最重要的是参与，不能旁观，打嘴炮。
2. 大部分对自己的能力都是高估的，如果你觉得他跟你一样厉害，大概率就是他比你厉害很多。
3. 投资与创业，都是想占用一个赚钱机器的股份。

-----

[[https://www.youtube.com/watch?v=JGHTcNmCcLU][【李自然说】人生如逆旅，我亦是行人 - YouTube]]

帮大家总结下：
1. 要敢于表达自己
2. 不要给自己设置障碍
3. 想办法接近牛人
4. 帮补一条，认知决定人生，性格和习惯都可以改变。

-----

[[https://www.youtube.com/watch?v=_JFQEPYmQ9I][【李自然说】如何获得更好前途？CEO的职场建议 - YouTube]]

1. 不要向平庸者要建議幾十年工人的建議也許對現代產業無效，不屬於這時代的經驗也往往是錯的，要向最優秀的人且願意幫助你的人請益，不要問身邊的人。 有兩種人是最值得請教的 1.成功的人或是說視角更高的 2.專業的人。
2. 不要同時打幾份工應該把時間投注學習，而不是用勞力去換取單位低的收入。
3. 錢少，就別搞理財了賺賠都是那點錢，還是把心力放在提高自己專業上，也不要走邪路去賺沒有過程的錢。
4. 公司不是學校沒有球員加入職業球隊說是來學習的，要從加入的第一天就為球隊創造更好的成績，在賽場上證明自己的價值。
5. 把看書的時間拿來研究同行。
6. 工作選擇看好壞也看大小 好的大公司>好的小公司>還好的小公司>差的大公司。
7. 可由公司前員工出路銷路判別公司好壞
8. 公司好壞的指標1.有沒有拿到好的融資2.有沒有厲害的高手或是值得追隨的人
9. 進優秀小公司是改變命運的途徑
10. 上司來指出你工作的問題時，通常代表對你還帶有希望
11. 不要沒搞懂隨便貿然給公司提建議
12. 如果同事或上司跟你說的話，從來不用再說第二次，你已經在職場中佔有很強的優勢
13. 及時匯報進度以及適時展現自己
14. 匯報工作談辛苦事非常不專業的展現，努力不努力沒有必要說
15. 不要硬撐該問就要問，但問題也要慎選，一邊培養獨當一面的能力
16. 外表非常重要，別太不修篇幅

-----

[[https://scylladb.medium.com/the-cost-of-containerization-for-your-scylla-a24559d17d01][Scylla 的容器化成本 | 通过 ScyllaDB | 中等的]]

如何修改docker配置来减少容器化带来的性能影响：
- 绑定cpu core, 之后相差10%
- 绕过容器化网络, 之后相差3%
- 安全配置检查, 之后就非常接近
