#+title: 网络文章@202308

-----
[[https://world.hey.com/dhh/not-everyone-can-be-the-best-ef9ebacd][Not everyone can be the best --- 不是每个人都能成为最好的]](https://world.hey.com/dhh/not-everyone-can-be-the-best-ef9ebacd)

我感觉这篇帖子应该是有点东西，但是我始终没有完全理解这篇文章。

-----

[[https://world.hey.com/dhh/et-tu-zoom-b90a0a0a][Et tu, Zoom? --- 你呢，变焦？]](https://world.hey.com/dhh/et-tu-zoom-b90a0a0a)

This is an opportunistic squeeze, because what's most tech workers supposed to do? The option of simply hopping to another company has been severely limited. Outside the small realm of AI experts, most other domains just aren't anywhere nearly as contested in hiring as they once were. So this is happening now because it can happen now.

这是一种机会主义的挤压，因为大多数科技工作者应该做什么？简单地跳槽到另一家公司的选择受到了严重限制。除了人工智能专家这个小领域之外，大多数其他领域的招聘竞争并不像以前那么激烈。所以这一切现在正在发生，因为它现在就可能发生。

I just hope that people who really did enjoy that remote work-lifetyle don't forget what it was like. The balance of power will presumably turn around one day again, and when it does, voting with your feet will be an option again.

我只是希望真正喜欢远程工作生活方式的人不要忘记它是什么样的。力量平衡大概有一天会再次扭转，届时，用脚投票将再次成为一种选择。

-----
[[https://world.hey.com/dhh/turns-out-nobody-cared-about-panel-gaps-914127d5][Turns out nobody cared about panel gaps --- 事实证明没有人关心面板间隙]](https://world.hey.com/dhh/turns-out-nobody-cared-about-panel-gaps-914127d5)

**弄清楚消费者真正关心什么是很困难的。破译他们实际上并不关心的事情更加困难。**

One of the most fascinating aspects of Tesla's rise to dominance has been how they discarded many of the traditional values of car making. While the rest of the industry was stuck competing on the size of their panel gaps, and other aspects of precision and quality assembly, Tesla didn't even show up to participate. Their cars are legendary for being delivered with shoddy paint jobs, rattling interiors, and even mismatched doors. But it just didn't matter! Consumers voted with their wallets for poorly built EVs because well-built gas-powered cars were deemed irrelevant in comparison.

特斯拉崛起的统治地位最令人着迷的方面之一是他们如何抛弃许多汽车制造的传统价值观。当该行业的其他公司在面板间隙的大小以及组装精度和质量的其他方面陷入竞争时，特斯拉甚至没有露面参与。他们的汽车因喷漆质量低劣、内饰嘎嘎作响，甚至车门不匹配而闻名。但这并不重要！消费者用钱包投票选择了质量较差的电动汽车，因为相比之下，质量好的汽油动力汽车被认为无关紧要。

Tesla decided not to compete in quality assembly, and instead focus on breakthrough ideas like owning the charging infrastructure for EVs. The former is a red-ocean realm of competition against legacy car makers who've had a century to perfect their panel gaps, the latter is so blue-ocean as to appear preposterous to anyone from the gasoline past.

特斯拉决定不参与质量组装方面的竞争，而是专注于突破性想法，例如拥有电动汽车充电基础设施。前者是与传统汽车制造商竞争的红海领域，这些传统汽车制造商花了一个世纪的时间来完善其面板差距，后者是如此蓝海，以至于对于任何过去的汽油车制造商来说都显得荒谬。

Figuring out what consumers truly care about is hard. Deciphering what they don't actually care about is harder still. When faced with nearly identical products in the same genre, they'll seemingly start comparing ever-more minute and subtle differences. But give them something entirely different, and suddenly half the shopping parameters go out the window.

弄清楚消费者真正关心什么是很困难的。破译他们实际上并不关心的事情更加困难。当面对同一类型的几乎相同的产品时，他们似乎会开始比较更细微的差异。但给他们一些完全不同的东西，突然一半的购物参数就消失了。

-----
[[https://blog.samaltman.com/american-equity][American Equity - Sam Altman --- 美国股票 - 萨姆·奥尔特曼]](https://blog.samaltman.com/american-equity)

美国人民持有美国（公司）的股票。

-----

[[https://blog.samaltman.com/tech-workers-values][Tech Workers' Values - Sam Altman --- 技术工人的价值观 - Sam Altman]](https://blog.samaltman.com/tech-workers-values)


As members of the community, we're interested in ways in which tech companies can use their collective power to protect privacy, rule of law, freedom of expression, and other fundamental American rights.

作为社区成员，我们对科技公司如何利用集体力量保护隐私、法治、言论自由和其他基本美国权利感兴趣。

We’d also like to discuss how tech companies can heal the divide in our country. We believe that tech companies can create a better economic future for all Americans by spreading high-paying technology jobs around the country and other measures. We also believe tech companies have an opportunity and an obligation to reduce the polarization we've helped create.

我们还想讨论科技公司如何弥合我国的分歧。我们相信，科技公司可以通过在全国范围内传播高薪科技工作岗位和其他措施，为所有美国人创造更美好的经济未来。我们还相信科技公司有机会也有义务减少我们帮助造成的两极分化。

-----
[[https://blog.samaltman.com/keep-the-internet-open][Keep the Internet Open - Sam Altman --- 保持互联网开放 - 萨姆·奥尔特曼]](https://blog.samaltman.com/keep-the-internet-open)

为什么要保持互联网开放？互联网和图书馆，电力，电话一样，被当作了公民的基本权利。

Yes -- in fact, the original notion about all this was to be in the same spirit as the 1936 Electrical and Telephone Federal Act which was specifically aimed at rural areas that the utilities didn't want to spend money to reach, so the fed mandated "power and phone" as a kind of universal right. This has also been a theme of the EFF. The basic impulse was also one of the drivers behind Carnegie's huge support of the free library system in the US (the whole story there is interesting, including some of the high minded stipulations in the Carnegie bequests, which I've on occasion tried to get the Internet communities to buy off on).

是的——事实上，关于这一切的最初想法是与 1936 年电气和电话联邦法案的精神相同，该法案专门针对公用事业公司不想花钱到达的农村地区，因此美联储规定“权力和电话”是一种普遍权利。这也是EFF的一个主题。这种基本冲动也是卡内基大力支持美国免费图书馆系统的驱动因素之一（整个故事很有趣，包括卡内基遗赠中的一些高尚的规定，我有时试图获得这些规定）互联网社区上购买)。

Every Carnegie library had to have two special rooms -- one just for children, and the other where people could be taught to read. Part of the Carnegie money for the libraries supported the reading teachers and sessions. Carnegie was an immigrant and child laborer who could read a little. One of his earliest bosses would open his home library to his workers on Saturdays. Carnegie used this to raise himself up, and never forgot how it happened. (He was also one of the few truly rich people ever who said he was going to give it all away to benefit the civilization around him, and actually did it.)

每个卡内基图书馆都必须有两个特殊的房间——一个仅供儿童使用，另一个可以教人们阅读。卡内基为图书馆提供的部分资金用于支持阅读教师和课程。卡内基是一名移民和童工，会读一点书。他最早的老板之一会在周六向员工开放他的家庭图书馆。卡内基以此来提升自己，并且永远不会忘记它是如何发生的。 （他也是少数几个真正富有的人之一，他说他将放弃一切以造福他周围的文明，并且实际上做到了。）

-----
[[https://blog.samaltman.com/greg][Greg - Sam Altman --- 格雷格 - 萨姆·奥尔特曼]](https://blog.samaltman.com/greg)

看看 Altman 对这个 OpenAI 联合创始人 Greg 的评价是怎么样的。

From then on he was fully in, with an average email response time of about 5 minutes to anything.  Elon and I were both busy with day jobs, but Greg kept everything moving forward with imperfect information and a very high-latency connection.

从那时起，他就全身心投入，对任何事情的平均电子邮件回复时间约为 5 分钟。埃隆和我都忙于日常工作，但格雷格通过不完善的信息和非常高的延迟连接使一切顺利进行。

He’s incredibly open to feedback.  Large or small, he’s always willing to hear it, never gets offended, and processes it very quickly.  I once suggested to him that he wasn't communicating a bold enough vision for the organization, and the next time I heard him talk about it (and every time since) it was a perfectly calibrated explanation of how we were going to succeed at something that really mattered.  Even on non-traditional ideas, like when I suggested he co-lead the organization with Ilya, he was always open-minded and thoughtful.

他非常乐于接受反馈。无论大小，他总是愿意听，从不生气，并且处理得很快。我曾经向他暗示，他没有为组织传达足够大胆的愿景，而下次我听到他谈论这个问题时（以及此后的每一次），这是对我们如何在某件事上取得成功的完美校准的解释这真的很重要。即使在非传统想法上，比如当我建议他与伊利亚共同领导该组织时，他也总是思想开放且深思熟虑。

Without someone dedicated to finding a solution to all problems, no matter how difficult, eventually a large problem will come along and kill you while you’re still weak.  Founding teams need a Chief Optimist to rally everyone to press on despite the difficulties, and it’s always hard on that person because they can’t really lean on anyone else in the hardest times.

如果没有人致力于解决所有问题，无论多么困难，最终都会出现一个大问题，并在你还很弱的时候杀死你。创始团队需要一位首席乐观主义者来团结所有人，克服困难继续前进，而这对那个人来说总是很困难，因为他们在最困难的时候无法真正依靠其他人。

-----
[[https://blog.samaltman.com/time-to-take-a-stand][Time to Take a Stand - Sam Altman --- 是时候表明立场了——萨姆·奥尔特曼]](https://blog.samaltman.com/time-to-take-a-stand)

如何应对政治气候的变化？ 团结并且坚决！

The tech community is powerful.  Large tech companies in particular have enormous power and are held in high regard.  We need to hear from the CEOs clearly and unequivocally.  Although there is some business risk in doing so, there is strength in numbers—if everyone does it early this coming week, we will all make each other stronger.

技术社区很强大。尤其是大型科技公司拥有巨大的权力并受到高度重视。我们需要清楚、明确地听取首席执行官的意见。尽管这样做存在一些商业风险，但人多力量大——如果每个人在下周早些时候都这样做，我们都会让彼此变得更强大。

If this action has not crossed a line for you, I suggest you think now about what your own line in the sand is.  It’s easy, with gradual escalation, for the definition of ‘acceptable’ to get moved.  So think now about what action President Trump might take that you would consider crossing a line, and write it down.

如果这个行为对你来说还没有越界，我建议你现在想想你自己的底线是什么。随着逐步升级，“可接受”的定义很容易发生变化。因此，现在想想特朗普总统可能会采取哪些行动让你考虑跨越界限，并将其写下来。

-----
[[https://blog.codingnow.com/2023/08/mobile_game_engine_optimization.html][云风的 BLOG: 手机游戏引擎的优化]](https://blog.codingnow.com/2023/08/mobile_game_engine_optimization.html)

手机游戏引擎的优化一些原则和方法

目前遇到最大的问题是游戏的能耗。优化游戏引擎让它尽量减少能耗，是过去在 PC 上做开发所没有过的经历。

让玩家的续航时间更长是一方面的原因，更重要的原因是：一旦让手机长时间工作在高能耗状态下，超过了手机的散热设计功耗 （TDP），必然会逐步发烫。最终会导致手机 CPU 自己降频，帧率也达不到了。

以前以帧率为唯一衡量标准放到手机上就行不通了。如果只为帧率达标的话，一般是在达标的基础上尽可能的提升画面质量，或是采用更简单易维护的算法。例如，有些算法为了简单，就直接每帧重复计算。而 cache 计算结果尽量避免重复计算，通常会增加代码的复杂度，却能减少 CPU 的使用。

为了得到准确的能耗情况，我没有采纳 xcode 给我的数据，而使用了更苛刻的测试方法：

每次测试前把电量充到 97% ，然后静置到刚好变成 96% 的那一刻开始启动游戏，加载足够复杂的场景，连续玩 16 分钟。以这样相同的测试条件，分别对全分辨率和半分辨率各测试两次（共四次），我发现全分辨率下的耗电几乎是半分辨率的一倍。

而考虑到能耗开销由 CPU 和 GPU 共同承担，修改分辨率丝毫不影响 CPU 的使用，那么 GPU 开销实际不只翻倍。或者说，我们引擎的 CPU 部分优化已经足够了，接下来需要重点考虑的是 GPU 开销。

------

[[https://www.zhihu.com/question/30809620/answer/3083388519][(28 封私信) 为什么坚持跑步之后感觉人变虚了？ - 知乎]](https://www.zhihu.com/question/30809620/answer/3083388519)

在开始前你就应该知道，跑步是有氧运动，有氧运动不宜于过量、持久，会导致加速衰老。当然你仅仅为了运动，那没问题，不讲究这些。人体的忍耐力极其的强大，几乎是哺乳动物里独一档的，当你疲惫、累的时候，咬牙一撑，就过去了，这是强大的忍耐力在发挥作用。可这不代表你的身体是健康的。人的健康运动上限，其实非常的低.......很多人完全没有仪器、没有监测，不可能知道自己真实的健康运动上限是多少，都是以累、疲惫为准，甚至很多挑战自我，直接“忍耐”过去继续战。遗憾的是，累、疲惫不是衡量你健康运动上限的标准，当感觉到累或者疲惫，你的健康运动上限值，早就被打爆了.......但是绝大多数人，对这些，一无所知。

健康的运动，会有一种精神、肉体都唤醒的感觉，而不应该是肉体疲惫、精神亢奋，而实际上很多3个月就跑5公里、10公里的，都是处于肉体开始累，精神极度亢奋的状态，这不健康，说明他的健康运动阈值早爆了，但是他自己不知道。除了个别的真大神，我没有见过几号人，能3个月内完成跑完5公里、10公里，是处于身体微微发热、汗将出未出的，因为普通人的健康运动上限，真没那么高。想达到这个高度，是需要非常非常长时间，用很缓慢的加量速度加上去的，这绝不是1年2年能做到的事情。

你身体绝大多数的细胞，代谢的周期差不多都在3个月，有些快点，有些慢点。当然也存在一些能7年才换一次的，肯定也有7天内一换的，但是整体来说，3个月，就是大更新的界限。一般来说，你今天运动刺激的效果，实际上要等新细胞出来，才会“适应”你的现在的量。所以你想运动，那没问题，你想健康的运动，那就得有讲究。运动量的提升，如果是为了健康，会是以季为核心，分月逐点增加的过程，每月增加的量，很少很少，别说什么20%提量，甚至不应该超过5%~10%。

而且运动不是单一动作越多越好，而是姿势越全面越好，尽量全身肌肉参与。你跑了步，就一定要找休息的时间训练自己的核心，回头再一天练手臂和背，都不要去加量撸铁，而是轻微的刺激即可。而越是静态的运动，越偏向于健康，越是动态的运动，越偏向于运动能力强大。或者说，尽可能用更慢的动作去完成动作，而不是极快的动作做更多的数量。比如俯卧撑，不要求数量，而是要求动作准确精准，而且要慢。

健康的运动一定不会去追量，而是维持自己稳定心率（ **正常人120是最好的运动心率，尽量不要超过140，150是红色警戒线** ），保持心率越恒定越好，而不要忽然静息到6、70，一下子又上到130、140。然后控制心率，运动时间在30到45分钟内。尽可能不要大汗淋漓，如果确实环境不允许，比如我在的广东沿海地区，那得事先准备好足够的水分，甚至运动过程里，要适当小口补水，还要毛巾擦汗、必要时候得湿毛巾降温，但是不要用冷水直接冲洗身体，可以用冷水冲洗手腕，特别是脉搏处。出汗并不是不好，但是短时间里大量出汗，就对身体不友好了。特别是这种短时间的大量出汗，会消耗“能量”，从而降低了你真正的运动能力。



------

[[https://world.hey.com/dhh/working-remotely-is-a-competitive-hiring-advantage-again-c182250e][Working remotely is a competitive hiring advantage again --- 远程工作再次成为具有竞争力的招聘优势]](https://world.hey.com/dhh/working-remotely-is-a-competitive-hiring-advantage-again-c182250e)

This is doubly so for workers who don't live in the few big cities, which most major tech companies settle in. For whom taking tech job with a big company that insists office attendance would require leaving life, family, and their preferred location behind. The world is full of wonderful, talented people who won't do this.

对于那些不住在少数大城市（大多数大型科技公司都驻扎于此）的员工来说，情况更是如此。对于那些在一家坚持上班的大公司从事科技工作的人来说，他们需要把生活、家庭和他们喜欢的工作地点抛在脑后。 。世界上充满了优秀而有才华的人，但他们不会这样做。

------

[[https://world.hey.com/dhh/pick-promise-over-proof-756604d3][Pick promise over proof --- 选择承诺而非证据]](https://world.hey.com/dhh/pick-promise-over-proof-756604d3)

The trick is to think of all your projects as a series of games. Whether you win or tie a few early ones matters far less than building your capacity to crush them consistently later. Giving everyone on your team the chance to be their absolute best as quickly as possible is how build that crushing capacity.

诀窍在于将所有项目视为一系列游戏。早期的几场比赛是胜是平，远不如培养你日后持续击败对手的能力来得重要。让团队中的每个人都有机会尽快发挥出自己的最佳水平，就是培养这种碾压能力的方法。
