#+title: 股票作手回忆录(Reminiscences of Stock Broker)

-----
UPDATE@2019-03-28T10:03:52

我很快就明白了另一个道理：华尔街没有新鲜事，因为投机像群山一样古老，股市上今天发生的事，过去曾经发生过，将来也必然再次发生；我一直牢记这一点。我必须努力记住它们是什么时候怎样发生的，我必须努力记住，因为经验可以让我在交易中少交学费。

我认为，图表能帮助读懂它们的人，或者说，能帮助那些能理解图表信息的人。但是，一般的图表阅读者太专注于股票的顶部、底部、主要波动和次要波动，他们认为那就是股票投机的全部。如果一个人把这些当成操作的唯一准则，并信心满满地进行投机，他就一定会倾家荡产。

现在回想起来，那时我的进步好像很慢，但是我觉得那个进步速度已经是自己能够达到的顶点了；因为那时我总体是在赚钱的，而赚钱会拖缓投资者进步的速度。如果常常赔钱，也许会激励我更加努力地研究，就能找出当时很多没发现的问题。我知道“赔钱”是有极大的价值的，但我无法确定“赔钱”的价值到底有多大，因为如果赔光，也就没有足够的资金来检验和改进我的投机方法了。

同时，我还发现另一件事：根据经验的深浅，傻瓜也分几种。 新手一无所知，每个人都清楚这一点，包括他们自己。而比他们高一级的，也就是二级傻瓜，自认为懂得很多，而且旁人也这么认为。其实他们只是经验丰富的傻瓜，研究的并不是市场，而是更高级别的傻子的市场理论。(6)二级傻瓜知道如何避免新手会犯的错误，以免亏损。经纪公司正是靠这些“半吊子”蠢蛋赚钱的，而不是主要靠吸新手的钱。胆敢冒犯华尔街的新手通常能熬三到三十个星期，而半吊子傻瓜平均可以支撑三年半左右。这些半吊子蠢蛋经常引述交易名言和游戏的各种规则，他们把经验丰富的老手传授的交易禁忌谨记于心，却忽略了最重要的一条：不要当傻瓜！(7)

如果你在大量交易，就得时刻铭记这一点：应该先研究所有相关条件，谨慎地做出操作计划，再付诸实践。如果一个人在大量交易而且已经积累了巨额账面利润，那他根本无法随意抛出，你不能指望市场像吸进100股那么容易地吸进5万股。他只有等，等到市场有能力吃进。这就要看他认为什么时候市场上会出现购买力，时机一来，就必须牢牢抓住，所以通常他得耐心等待，等待时机抛出。想抓住适当的时机，就必须观察、测试，想知道市场什么时候有能力吃进你要抛出的股票并不难，但一定不要一开始就押上所有赌注，一定要等到确定的正确时机再行动。记住，股价永远不会高到你不能买进，也不会低到你无法抛出。但是，第一笔交易后，除非真的有利润，否则不要进行第二笔交易，应该观望一阵，让你的行情分析结果帮你判断时机是否真正到来了。很多事情是否能成功，完全要看是否在适当的时机行动。

我安然渡过了这场灾难，报纸上都刊登着拉里·利文斯顿——那个年轻的“抢钱小子”——赚了几百万的消息。那天收盘后，我的身家超过了100万美元。但我最大的收获并不是钞票，而是无形的收获：我懂得了往长远看，制订并遵循明晰的规划。我明白了想赚大钱就必须要做一些事，我再也不是在赌输赢了，而是终于学会了在更高级的层面上更明智地进行交易。这是我一生中最重要的一天。

其实相比较而言，我更愿意做商品期货。毫无疑问，期货交易和实际商品离得更近，以前这样，现在也是。很简单，和股票相比，期货交易更像是在做商品生意。投资者可以用处理商业问题的方法来进行期货交易。当然你可以用虚构的理论来支持或反对市场的价格趋势，但这种方法只能带来短暂的成功，因为最终是否挣钱还是要看实物的买卖事实。所以，像做普通生意一样，在期货交易中，投资者必须通过观察和研究来赚取利润。他可以观察并权衡市场形势，不用担心有些消息别人知道而自己不知道，也用不着防范内线集团。期货市场上不会有增发或不发红利的突发事件发生。从长远来看，期货价格只受供需经济法则的主导。在期货市场上，不管它是小麦还是玉米，你只需要了解供求的现况和前景，用不着像做股票那样对许多情况进行猜测，所以期货交易总是更吸引我。

许多投资者都有很多类似的经历，所以我总结出以下规则：如果价格窄幅波动，波动幅度小到不值一提，试图预测下一次大的波动是上涨还是下跌便毫无意义。你应该观察市场，解读行情以确定窄幅波动价格的浮动上下限，并下定决心除非价格突破界限，否则绝不出手。投机商没必要强求走势按他的判断发展，一切要以赚钱为主。永远别和行情争执，也别企盼行情给你理由或解释。事后给股市解剖验尸不带来任何利润。

摇了摇头。 他说得对。我有时也觉得投机是一种反人性的行当，因为我发现投机商一般都要和自己的本性抗争。人性的弱点会阻碍投机的成功，会让一个人趋于平庸。人们在从事其他比较安全的行业时，都会特别防范这些弱点，可是遇到最危险的股票或期货交易时，却顾不上了。 投机者

投机者最大的敌人往往是他自己，因为人类有希望与恐惧的本性。在投机中，当市场对你不利时，你每天都希望这是最后一天亏损。抱着这样的希望，你会亏损得更多，虽然强有力的希望曾经让帝国的缔造者和开拓者们建立丰功伟绩，马前小卒改命王侯将相。当市场对你有利，你会害怕也许第二天利润就全没了，于是心急地退出。因为恐惧，你损失了本该赚到的钱。成功的交易者必须克服这两种根深蒂固的本性，彻底改变冲动的天性。他应该居安思危，处变不惊，时刻提防损失的扩大，同时尽可能增加利润。一个充满七情六欲的普通人进入股市赌博，这本身就是个错误。

那些居心叵测的空头因为自己的鲁莽遭受了惩罚，痛苦不堪，于是指责我一手策划了这次行动，其他人也这么认为。一两天后，世界上最厉害的棉花期货交易商之一碰到了我，他说：“利文斯顿，高！这是你做的最高明的操作。我当时还在想，你不知道得损失多少才能抛出那么多棉花呢。你知道，不压低价格这个市场至多能吸入五六十万包。而我非常好奇，不知道你会怎么做才能保全账面利润还把棉花都脱手。想不到你有这么一手，确实高明啊！”

不管你做什么，走对第一步是至关重要的。伯利恒交易之后，我的操作非常顺利，真的很棒，以至于你难以相信是同一个人在交易。其实我也变了，不再烦躁不安、漏洞百出，而是变得轻松自在、正确无误。没有债主的骚扰，也没有资金不足来干扰我的思考或干扰我倾听经验的指导，所以我一路赚钱。

必须指出的是，我并没有预料到市场会在这个特定时刻因为这一原因出现这样的下跌。但正像我告诉过你的，凭我30年的交易经验，利多和利空消息总会顺应大盘的最小阻力方向，而我正是根据最小阻力方向来确定自己立场的。还有一点要铭记于心：绝对不要妄图在最高价抛出，在最高点逃顶的心理是不明智、不健康的。如果没有上涨空间确定要抛出了，就在回档的第一时间抛出。

把大多数价格的突然下跌或者暴涨归因于作手操作，这种理论完全是编造出来搪塞那些盲目的赌徒的，他们不愿思考，又极易轻信别人。证券公司和编造金融谣言的人经常告诉那些不走运的投机者，说他们的亏损是由作手打压引起的，但这种解释实际上是扭曲的建议。正常的建议是：明确地告诉你这是熊市，让你卖空。扭曲的建议是：给你个算不上解释的解释吓唬你，阻止你明智地去卖空。股票暴跌时自然反应应该是卖空，但是如果你被告知是作手在打压股市，它就成了一个充分的理由，你会退场。可是，如果真的是作手打压导致的下跌，就不应该退出，因为一旦他停止打压，股价必定反弹。这就是扭曲的建议！

我一直认为靠内幕消息交易是愚蠢至极的行为。我从不听信任何内幕消息，有时甚至觉得那些听取内幕消息的人就像醉鬼一样无法抗拒这种热切的愿望，自觉陷入他们自己编织出来的幸福感中自娱自乐。张开耳朵听信小道消息是一件容易事。有人明确地告诉你如何做能得到快乐，而你又乐意听从别人的意见，从而迈向幸福，大跨步迈向内心欲望的满足。这不是被渴望蒙蔽了双眼的贪婪，而是被懒得思考束缚了的希望。

一位见多识广的老证券商告诉我：六七十年代的所有大作手都有一个梦想，就是操纵一次市场，大多数人是出于虚荣心理，其他人则是为了复仇。总而言之，如果有人被大家指指点点，说他成功操纵了这只或那只股票，其实是大家对他的智慧、胆量和财富的认可，这让他们有了骄傲的资本，他可以尽情享受同行的赞美。是虚荣心在这些冷酷的作手心中作祟，促使他们竭尽全力策划，他们并不是为了赚钱。

数学不能控制金融市场，而心理因素才是控制市场的关键。更确切地说，只有掌握住群众的本能才能控制市场。

事实上，想让所有的股票一下子涌进场，就像人寿保险公司的所有投保人同时死亡一样，是不可能的。就像有印着的人口死亡率的保险统计表一样，也有这样的股市风险统计表。

这些由“大股东”和“重要内线人士”卖出的内线持股成了专业交易商之间的足球，被踢来踢去，谁都不愿承接。股价不断下跌，似乎永远不会触底。内线人士知道现如今的业务状况会让公司收入继续下跌，所以在公司业务再次好转之前，不敢支撑这只股票。一旦公司业务再次好转，内线人士又会低调买进。

在我看来，这些投资者才是名副其实的大赌徒。他们投下赌注，一赌到底，一旦赌注压错了，就输得彻头彻尾。在这些投资者买进的同时，投机者或许也会买进同一只股票，但是，如果这是一位明智的投机者，而且一直维持股票行情记录的话，那么他将意识到市场的危险信号正在警告他，所有的形势都对他不利。此时如果他立即采取行动，就能及时止损，保存资金实力，这样就可以等待更有利的时机再入场。

显然，在今天的市场条件下，明智的投机者是不会允许自己还沿用多年前常用的方式来进行交易。他会集中精力研究少数的股票板块以及其中的领涨股。他还将学会先谋而后动。股票市场崭新的时代已经来临——这个时代将给明智、勤奋、能干的投资者和投机者带来更稳健的机遇。

长期以来，在经纪人那里，我得到的明确消息几乎只有一种，那便是追加保证金的通知。一旦得到这样的通知，就应该意识到情况的严重性，马上平仓，而不应该再追加资金了。因为该通知已经向你表明，你站在了市场错误的那一边。为什么要把资金继续投入到只赔不赚的股票上呢？此时最正确的做法应该是把这些资金妥善地保管起来，耐心等待新的一天、新的机会，然后明智地把它投入到其他更有吸引力、回报率更高的地方，而不应该再投放到已经亏损的交易上。

可以肯定的是，放在经纪人账户里的钱，或者放在银行账户里的钱，和你拿在手中的钱，尽管同样是你的财富，但给你的感觉却是完全不一样的。拿在手里的钱，你可以时常用手指去感受它们的存在，这样你就能从中感觉到某些实实在在的东西。你可以感受到一种对金钱的强烈占有感，在你做出任何刚愎自用的投机决策时，这种感觉会减弱你的这种冲动，因为刚愎自用的投机决策往往会导致你的利润受到损害。因此，一定要经常看一看，感受一下你所拥有的真正的金钱，尤其是在你这次交易和下次交易的间隙之间。

记得有一次，我曾经对华尔街之外的一项风险投资生意产生了强烈的热情和兴趣。于是，我竭尽全力地说服我的一位朋友，力图让他在这个生意中投入5万美元。他非常认真地听了我对这桩生意的介绍和想法，但是我刚一说完，他便告诉我：“利弗莫尔，除了你所擅长的投机领域外，你永远不可能在任何领域的生意上取得成功。如果你需要5万美元拿去投机，我完全支持你。但是，请你仅用于投机，千万远离那桩生意。”

我的经历自始至终都在证明一个道理，那就是如果我没有及时在行情启动后不久就入市，那么根本就不可能在这轮行情中获得可观的利润。因为一旦没有及时入市，就会失去前期大量的利润储备，而在行情的后续发展到结束的整个过程中，这段前期利润储备却是维持勇气和耐心的可靠保障。由此可见，及时入市是非常必要的！在整个行情的变化过程中，股价势必会不时出现不同程度的小规模回调或者反弹，而我完全不为之所动，一直坚守到最后的可靠保障正是这段前期的利润储备。

通过维持股票的行情记录，并将时间要素考虑进来，你就会发现许多可以获利的关键点，这些关键点将帮助你在变化莫测的市场行情中做出正确的判断。但是，一定要充分意识到，使用关键点交易法是需要付出极大耐心的。你必须投入足够多的时间来研究那些行情记录，并且亲自记录数据，亲自标记出哪些价位才是真正的关键点。

关键点的研究是如此令人着迷，简直令人难以置信。置身其中，你就会发现自己就像找到了个人研究的金矿。在经过独立判断而获得的成功交易中，你将享受到一种独特的快感和满足。也许内幕消息或者其他的指导同样也能使你获利，但你终究会发现，相比其他的任何方式，自己独立赢得的利润更能给你带来巨大的成就感。如果你坚持独自发掘机会，独自交易，耐心等待，密切留意危险信号，那么你会逐渐培养出一种适合自己的正确思维方式。

投机性市场允许卖空有很大的价值，因为持有卖空头寸的人会变成主动购买者，一旦市场出现恐慌，主动买入者的购买行为就会对市场起到至关重要的稳定作用。

-----
@FirstVersion

实战操作和虚拟操作的最大区别就是，同一个人的智商和情商都会急速降低或提升，以至于你都认不出还是那个人，其实这才是真正的他。

在信息不全的条件下当机立断也很重要，在股市上，你不可能把所有的事情都弄得清清楚楚明明白白再采取行动，因为那时候对赚钱来说已经为时已晚。

这是一个人的游戏。你为什么要告诉别人你在做什么？是为了拖他下水还是为了拖他下水？

乐意不乐意承担风险是投机业中的道德标准。能接受成功也能面对后果的投机客，便是有道德的；能接受成功却不能面对后果，就是不道德的。

限价交易只是我在空壳证券公司使用的方法，根本无法在大型证券公司采用。如果不是这样，我可能永远学不会真正的股票投机，只能根据自己浅陋的经验继续赌博。

判断对错并不重要，重要的在于正确时获取了多大利润，错误时亏损了多少。

不要相信投资专家的任何建议，不要相信所谓的内幕消息，不要相信证券公司的推荐，不要相信"至少不会损失"的鬼话，你只能相信自己的研究。

如果市场总是可有效预测的，我只会成为一个在大街上手拎马口铁罐的流浪汉。

在家乡，我能够平心静气地思考自己之前的一些愚蠢操作，隔一段距离与时间，你总能更清楚地看透事情的原委。所以，下次再去纽约，我一定能做得更好。

可我听了老行家的忠告，抑制了年少的冲劲，决定学聪明点，保守而谨慎地操作。众所周知，保守而谨慎的操作方法就是获利落袋为安，然后静待回档低吸。我就是这么干的，于是常常守着赚到的4个点的收益，等着股价回落，却眼睁睁地看着它继续上涨10个点，偶尔回踩。人们常说：获利落袋，必能敛财。但在牛市里赚4个点就急着套现的人永远也发不了大财。 本来可以赚2万美元，我却只赚了2000块，这就是我的保守主义带给我的回报。

我终于明白，当老帕特里奇一直告诉其他客户"啊，你知道的，现在可是牛市啊"时，他真正的意思是说，赚大钱不能靠股价的短期波动，而要靠大波动。换句话说，不能光看个别的起伏，而要判断个股的大趋势和大盘的行情走势。明白了这个道理，我又向前迈进了一大步。

现在，让我告诉你，在华尔街摸爬滚打了这么多年，累计输赢了几百万之后，我要告诉你：我的想法从来都没有替我赚过大钱，总是坚持不动替我赚大钱，明白吗？是我坚持不动！看对个股波动没什么了不起。你能在股市发现很多高手，看时机很准，总能在最佳利润点买卖股票，但他们都没能真正赚到钱。为什么呢？能看对波动方向的人很多，能看对波动并坚持不动的人才真正厉害。但是，一个股票投资者只有牢牢掌握了这个诀窍才能赚大钱。而这是最难学的。

不要去抓最初或最后的1/8点利润，那需要太大的代价。多少股票投资者为了抓住这1/8点利润付出了好几百万块的代价，这些钱都足以建一条横跨美洲大陆的水泥公路了。

投资者必需着眼于价格水平与潜在或核心价值的相互关系，而不是市场上正在做什么或将要做什么的变化。

当你经常去歌剧院而不研究股市的时候，那也就说明你不属于这个游戏了。

如果牌过三巡，你还不知道谁是牌桌上的傻瓜，那么你就是那个傻瓜。

当有机会获利时，千万不要畏缩不前。做对还不够，要尽可能多地获取。

地震发生的头一两天，华尔街并不关注这场灾难，他们会说这是因为首批报道的内容并不太严重，我倒认为这是因为改变大众的观点需要一个漫长的过程，甚至职业交易商也经常表现得反应迟钝、目光短浅。

我发现纸上谈兵比实际交易容易得多，有些家伙说话的口气真让人受不了。

持有一只股票，期待它每个早晨都上涨是十分愚蠢的。

生命总是迸发于混乱的边缘，所以，在混乱的状况中生存是我最擅长的。

朋友问他为什么睡不着，他说因为手上的棉花期货太多，一想到这些棉花他就睡不着，他精疲力竭。他问朋友该怎么办。朋友建议他卖点儿，卖到能睡觉为止。

股价下跌永远不是买入股票的理由，因为可能会跌得更低。

普通人总觉得自己的操作只是游戏，而且自以为是，从而导致思考不深刻、不透彻；专业人士则力求行事正确，这比赚钱更重要，因为他们知道只要做对每一件事，自然能赚到钱。投机者应该向职业大玩家学习，高瞻运瞩而不是只看到眼前利益。

如果总是做显而易见或大家都在做的事，你就赚不到钱。对于理性投资，精神态度比技巧更重要。

再聪明的投资者也可能需要坚强的意志才能置身于"羊群"之外。

我得到了另外一个代价惨重的经验：一个人犯错不需要理由。几百万美元还换来了另外一个经验：对交易者来说，最危险的敌人就是聪明的朋友的热切规劝和人格魅力。

卖出有盈利的股票，保留亏损股票，就像把花园里的花拔掉，而去灌溉野草一样；股市就像玩扑克牌，只要手里的牌显示有可能赢，就要紧紧握住。

欠别人的钱，我可以用钱去还，但是我必须用同样的方式去偿还人情和善意，而你很容易发现这些人情账有时候是非常昂贵的，而且你不知道还到什么时候才算完。

所以，我的情感再一次胜过了理智，我让步了。我让自己的判断臣服于他的意愿，这就是我毁灭的原因。任何一个正派的人都有感恩之心，但是人不应该被这样的感情牵绊。毁灭的开始就是我不但亏掉了所有的利润，还欠了公司15万美元的债务。我觉得很难过，可丹让我不必担心。

作为一般人，我在丹·威廉森公司的做法无可厚非。但身为一个投机者，我任凭违背自己判断的看法影响操作，真是太不应该太不明智了。感恩是一种美德，却不该在股市上履行，因为你对别人侠义忠诚，行情可不会对你侠义，也不会奖励你的忠诚。但我意识到自己当时只能那么做，我不会仅仅为了能在股市上交易就改变自己懂得感恩的本性。不过生意终究是生意，作为一个投机者，我应该始终坚持自己的判断。

我远离威廉森与布朗公司。我的意思是说，连续六周，我一心研读行情，刻意不去他们公司。我担心一旦我去了那里，知道自己可以买500股，就可能禁不住诱惑，在不正确的时间交易不适当的股票。交易商除了要研究基本形势、牢记市场先例、考虑大众心理、了解证券商的限制之外，还必须认识并防范自身的弱点。你大可不必和自己身上的人性弱点生气。我发现解读自己和解读行情同样重要。我研究了自己，知道活跃市场会对自己产生不可避免的诱惑，知道自己看到某些市场动态时会忍不住出手。我研究自己弱点时怀有的情绪和心情，就像我分析作物行情和收益报告时怀有的情绪和心情一样，客观而冷静。

绝对不要妄图在最高价抛出，在最高点逃顶的心理是不明智、不健康的。如果没有上涨空间确定要抛出了，就在回档的第一时间抛出。

承认错误是件值得骄傲的事情。我能承认错误，也就会原谅别人犯错。这是我与他人和谐共事的基础。犯错误并没有什么好羞耻的，只有知错不改才是耻辱。

对于听信内幕消息的蠢货，我们还能说什么呢？人们听信内部消息，不是因为他们太蠢，而是像我所说的那样，他们喜欢沉溺于希望之中。

只有在得到对企业的定性调查结果的支持的前提下，量化的指标才是有用的。

如果你是一遇见什么事儿就慌着脱手的人，就该远离股票市场。

经验能教会人很多事情，违背经验行事就是重复交学费，而且会败得很惨。违背常识行事更是不应当。但不是只有外行才会成为华尔街傻瓜。

普通人总是不考虑股票真正的价值，而只考虑现实的价格，他们的行为受控于恐惧而不是市场形势。此时，这些人就采取了最容易的方法——相信这只股票会一直涨下去。这就是为什么这些外行虽然知道不应该在最高价买进，却总在最高价买进故而赔得一塌糊涂的原因。繁荣时期，广大股民总能获得高额账面利润，不过，这些利润却永远停留在了账面上，无法套现。

股民们应该铭记这一点：股价长期低迷的原因绝不会是空头掼压。一旦某只股票持续下跌，你可以肯定其中一定有问题，不是市场有问题，就是公司本身有问题。如果这种下跌没有道理，价格很快就会跌到股票的实际价值以下，股民就会买进，股价随着大家的买进停止下跌。实际上，空头只有在股价过高的时候卖出股票才能赚大钱。可以肯定的是，内线人士绝不会向世界宣布任何事实。

华尔街专家的意见及看法，绝不能带给散户任何优势，你的投资利器就在你自己身上，投资你了解的产业和企业，才能发挥自身的优势。

买股票和养孩子差不多，别生太多让自己手忙脚乱，持股最好不要超过五只。

不要持太多只股票，最高的利润来自少量的股票的组合，这些股票你能充分了解。

这个游戏的本质就是这样，所以，股民们应该认识到，知情人是少数人，而且他们绝对不会透露真相。

大家应当时刻谨记股票交易的基本原则。股价上涨时，不要问它为什么涨，持续买进自然会推动股价上涨。只要股价持续上涨——上涨中偶尔会出现合理的小幅回落——继续跟进就是稳妥的操作。但如果经过长时间的持续上涨后，股价突然回档，逐渐开始下跌，其间虽偶尔小幅反弹，你就明白，很显然，最小阻力方向已经从上涨变为下跌了。情况就是这么简单，为什么要苦苦寻求解释呢？

我的经验足以证明，在投机买卖中真正赚得的利润，都来自那些一开始就保持盈利的头寸。 投机者必须对最初的小额亏损进行及时止损，以免给自己带来更大的损失。只有这样，才能将资金账户维持在很好的状态，最大程度地保存自己的资金实力。

当一只股票的价格开始下跌时，没人能够预测到它的底部在哪。同样，在一轮显著的上涨行情中，也没人能够预测到它的顶部在哪。绝对不要因为某只股票看起来价格太高就卖掉它。反过来，绝对不要因为某只股票从前一个最高点大幅下跌就买进它。

在等到股市变化本身验证你的判断之前，千万不要轻率地认定自己的判断就是正确的，只有在通过股市本身的验证之后，才能对自己的判断盖棺定论，因为股市的市场效应未必如你所预期的那样明确。你的预期反应的是"是怎样"，而市场效应反应的则是"应该怎样"。下面

对投资者或投机者来说，除非你的个人观点能左右市场的变化，否则你的个人观点将变得一文不值。

举个例子，某只股票当前的成交价为25美元，此前它已经在22美元到28美元的这个区间徘徊了很长一段时间。假如你预测这只股票最后将上涨到50美元，也就说现在这只股票的成交价格是25美元，而你预测它能上涨到50美元。别激动！一定要耐心等待！等这只股票表现出活跃的态势，等它越过28美元这个关键点，创下历史新高，比如上涨到30美元。这时，你才能从这只股票的真正走势中证实你的判断是正确的。这只股票已经进入了极其强势的状态，不然根本达不到30美元的交易价格。只有观察到这只股票出现了这些变化后，你才能判断，这只股票很可能处在大幅上涨过程中——大趋势已经开始启动了。到了这个时候，你就可以为自己的判断盖棺定论了。如果你没有在25美元的时候买进，也千万不要懊恼。也许，如果你真的在那个价位买进的话，结果很可能没有你想象的那么乐观。我们可以设想一下：如果你在25美元买进，此后股票价格在22美元到28美元的区间内徘徊了很长一段时间，在此期间，你耐心地等啊等啊，直到被折磨得疲惫不堪，也没等到股票大幅上涨行情的到来。于是，在真正的上涨行情启动之前，你就已经痛苦地抛掉了原来的仓位。正因为你是在上涨行情没有真正到来之前以较低价格卖出的，所以你也许会懊恼自己过去不明智的行为，从而错失了后来本可以再次买进的机会。

总之，我认为：作为一个成功的投资者或投机者，他在入市做多或做空之前必定会有非常充分的理由，而且他们必定是根据自己独特的股市判断准则来确定首次入场建仓的时间。

在这里我必须再次强调，当股票行情真正启动时，一定会出现明确的交易时机。我坚信，任何具有投机者本能和耐心的人都一定会想方设法建立某种股市判断准则，借以正确预测入场建仓的最佳时机，成功的投机者绝对不会允许自己仅仅依靠单纯的猜测来进行市场操作。

请努力让自己熟悉一只股票，或者熟悉很多不同的股票板块。如果你能根据自己的行情记录准确推算时间要素，那么总有一天，你能准确判断出重大行情到来的时机。如果你可以针对行情记录进行正确解读，那么你就能在任何股票板块中挑选出它的领涨股。再重申一遍，你必须亲自维护行情记录，亲手记录数字，千万不能让任何人代替你做这些工作。在你身体力行的过程中，你会惊奇地发现你的脑海中会时时涌现出各种各样的新点子。最为可贵的是，这些点子是任何人都没法教给你的，因为它们是你自己观察和思考得来的，只有你自己知道，因此你应当保守这些秘密。

在本书中，我告诉了投资者和投机者一些"禁忌"。其中一条主要规则就是，绝对不能把投机和投资混为一谈。投资者之所以常常遭受巨大的亏损，没有别的原因，就是因为他们当初抱着投机的心态来进行股票交易，结果可想而知，他们因此付出了极大的代价。

另一个原则是：如果第一笔交易已经处于亏损状态，就绝不能为了摊低亏损而继续跟进。请把这个原则深深地铭记在心。

那些终日企图在市场小规模的波动中获利，甚至不愿意放过任何一次微小的赚钱机会的投机客，永远不可能在下一轮重大行情发生时占据一席之地。

每年仅有屈指可数的几次大机会，也许只有四五次，碰到这样的机会时你才能允许自己全身心投入股市。其他时间里，你应该耐心等待市场逐步形成的下一次大行情。

我要再次强调一点，对于每一个普通投资者或投机者而言，人性内在的弱点就是自己最大的敌人。也许，总有人会想不明白，一只股票在经历了一轮大幅度的上涨后开始下跌，为什么就不能再次上涨呢？当然，下跌之后它也许会再从某个价格水平上开始上涨。但是，你凭什么指望它在你希望它上涨的时候，它就恰好上涨呢？还有一种更大的可能是，它不会上涨了。退一步说，即使它如愿地上涨了，优柔寡断的投机者估计也可能把握不好这个机会。

必须彻底抛弃一切一厢情愿的想法；一个人不可能在所有的投机中始终保持成功；每年仅有屈指可数的几次大机会，也许只有四五次，碰到这样的机会时你才能允许自己全身心投入股市；其他时间里，你应该耐心等待市场逐步形成的下一次大行情。

一轮真正的行情绝不会在它启动的那天就马上结束，而是会运行一段时间才终结。我身处远离股市的山中，这有利于我保持耐心，为这些真正的大行情留下它们所需的充足时间。我会把在报纸上看到的股票价格记入我的行情记录中，一旦某天我观察到刚刚记录下来的价格与已经明确持续了一段时间的行情发展不一致时，我会立刻做出决定，下山亲自进行交易。"

众所周知，股市价格总是不断上下波动的，过去如此，将来也会一直如此。我一直认为，在那些股市的重大行情背后，必定存在着一股不可抗拒的力量。事实上，你也只需了解这一点就足够了。如果你对价格波动背后的一切原因都想深究，那么这种过于琐细和好奇的行为反而会弄巧成拙。你的思维可能会被这些旁枝末节的琐事遮蔽，你对股市行情的判断也会因此受到影响，这就是这种行为带给你的风险。

所有投机者几乎都有一个通病，那就是急于求成，企图在极短的时间内赚得钵满盆盈。他们根本就没打算花费两到三年的时间来让自己持有的资本增值500％，而是妄图在两三个月之内就达到这一目标。

还有一点，也许值得一提。投机者每当结束一笔成功交易之后，都应取出其中一半的利润储存起来。这一点必须当成一项规则来执行。因为只有投机者结束一笔成功交易后从账户里取出的那部分钱，才是唯一真正从华尔街赚到的钱。

太多的投机者总是任凭一时冲动买进或卖出股票，这导致他们几乎会在同一个价位上满仓买入。这种方式是极其错误而且危险的。

市场会简单明了地告诉我们什么时候在犯错误，因为犯错误时我们一定在赔钱。当我们第一次认识到自己正在犯错误时，就是当机立断清仓离场之时，我们应该勇于接受亏损的事实，努力保持微笑，并仔细研究行情记录，尽量找出导致错误的原因，然后耐心静候下一次大机会。

坦率地说，对于来自内心的莫名奇妙的不安和警告，我总是秉持怀疑态度，通常我更青睐于采用客观的科学准则。但是，实际情况却总是倾向于我突然萌发的感知力，而不是科学准则。有时，当所有事情似乎都一帆风顺时，内心却会突然涌起一种忐忑不安的感觉。恰恰是通过密切关注这种感觉，我才能在很多场合获益颇丰。

终日在股市中买进卖出，捕捉小规模的日内波动。这是不对的，幸亏我及时清醒地认识到这个错误。从此以后，我决定忽略所有股票价格的微小波动。

频繁的交易便是盲目的交易，是华尔街上甚至最专业的投机者都会亏损的主要原因，他们把股票交易当成了一份有固定收入的工作，总觉得自己每天都应该赚些钱回家。不过请理解我，当时我还只是个孩子，并不懂得后来学到的这些东西，并不知道15年后发生在自己身上的事能让我大彻大悟。

我当时很年轻，很多人都想占我的便宜，所以我面临很多障碍，但这也让我学会了自强。那些同行看我年轻，都认为我能赚到钱纯属瞎猫撞着死老鼠。可是他们不明白，如果瞎猫总能碰上死耗子，那也就不太一样了。

即使在短期投资中，抄底和逃顶的结果是值得羡慕的，但是不值得追随，因为这些人没有一个起初以抄底或逃顶为目的。以抄底和逃顶为目标，就像提着灯笼找影子一样。

"躁"，是一种通病，这和"快"是两个完全不同的概念。

我输得只剩下在哈丁公司的保证金了，但我并没有生气。很明显，我准确地解读了行情，却像个傻子似的让艾德·哈丁动摇了自己的决心。谴责别人是毫无意义的，它并不能改变什么，只会浪费时间。

这只是众多事例中的一件。在华尔街，那些想从股市赚钱买汽车、手镯、摩托艇或油画的人，无一例外都亏了。股市是吝啬的，它拒绝替任何人支付任何生日礼物，它拒付的这些生日礼物都可以用来盖一座大医院了。想让市场成为乐善好施的仙女的动机，是在华尔街亏钱的原因之一，也是最常见最顽固的原因。
