#+title: Remote

http://jianshu.io/notebooks/41672/latest

-----

远程工作的关键是：独处以进行深度地思考。当你一个人工作，远离总部的吵杂，你将会很快进入工作状态，迅速地完成工作。是的，那些你在总部的正常办公时间无法完成的工作。当然，远程办公也有很多挑战。即使独处，你也可能被来自其他方面的影响打断。如果在家，可能被电视机打断。如果在咖啡馆，可能被隔壁桌吵闹的讨论声打扰。但是关键是：这些因素是我们可以控制的。你可以选择一个适合你自己的工作环境。你可以带上耳机而不必在意另外一个协同办公的同事在你身边游荡。同样，你也不必在意会被打扰而去参加一个临时出现而又无关紧要的会议。你的工作环境，工作氛围，是你自己的。

除了工作场地之外，在工作时间上，人们逐渐也由同步时间模式转变为异步时间模式。是的，我们不但不需要被困在一个固定的地方一起工作，我们甚至不需要在同一个时间段内一起工作。当然，不是所有的工作都能在完全没有约束的情况下完成。在37Signals，我们的客户团队是按照美国当地时间为客户提供服务的，所以我们必须保证他们必须按照这个时间段正常工作。摆脱即有的朝九晚五的工作时间观念。这个过程肯定需要花点时间。但是很快你将会发现，我们真正需要关心的是所完成工作的质量，而不是完成这些工作的地点或者时间段。

人们普遍认为，只有在湾区，才能找到最优秀的开发人员。而事实上，我们在那儿一名员工也没有，这个结果并不是我们有意为之。但是我们觉得整个湾区的创业和投资环境有些浮躁，程序员们每天都会面对层出不穷的新公司，并且收到他们的招聘需求。在这种环境下，很难安心地工作。如果在你的员工周围，每天都会出现更有挑战性的工作机会，那么频繁地跳槽也不会是一件意外的事情。我们发现，公司里的明星员工，往往能够远离周边浮躁的环境的影响，集中精力在自己的事情上。而他们，往往工作地也更加快乐。

远程办公的初衷：是为了提供员工的生活质量。同时能够雇佣来自全球各地最优秀的员工。当然，如果采用远程办公，可能也会带来办公室租金费用的削减，人员开支的削减 （数量更少但是效率更高的员工）。但是这些只是附带的结果，并不是我们采取远程办公这种模式的初衷。此外，一般我们认为最适合远程办公的工作有：写作、编程、设计、广告、客服等。暂时在大规模制造业当中，远程办公没有什么可做的。工作的目的，不是为了将所有员工聚集到一个房间，在同一个时间段内压榨他们的劳动力。这样的话，员工们工作的并不快乐，工作的产出也很一般。让他们自由选择一个良好的工作环境，保持愉快的心情，好的结果也是顺理成章的事情。

在远程办公的初期，你可能会感觉周围没有其他同事一起工作是一种解脱。但是从长期来看，你可能也会失去一些东西。例如，当你想讨论一件事情的时候，发现身边没有同事可以与你头脑风暴，或者争论。另外，由于没有硬性的规章制度和监督，所以每个实行远程办公的同事，自己都需要有很高的自觉性和责任感。对于很多有拖延症的人来说，这点很难做到。

-----

大部分好的解决方案，是在实际工作中产生的。是根据过去6个月、甚至6年实际的操作经验总结后得出的。单单希望大家聚拢在一起头脑风暴，是无法产生好的解决方案的。另外，过多的头脑风暴，只会伤害你自己和你的团队。一次新的头脑风暴，意味着否定上一次头脑风暴所产生的结论。那些时间被浪费了，而那些所谓的新创意又不断被叠加累积。这就是为什么在37Signals，我们不经常面对面讨论。我们认为，在进行一次真正的面对面交流之前，我们需要事先就把问题思考清楚。所以，每年只有3次的时间，我们会在芝加哥的总部聚会。

大部分人不敢于尝试远程办公，原因在于缺乏信任。老板们会担忧： 如果我不呆在员工身边的话，他们会认真工作吗？他们会不会整天上网聊天，或者溜出去玩视频游戏？然而实际情况是：如果你的员工真是要上网聊天或者玩游戏，那即使他们在自己办公室的座位上，也会偷偷这么做的。懒惰是一种天性，你不能总是幻想所有员工都会120%专心投入工作。所有员工都非常敬业，对于每一件小事都要求近乎完美。如果你必须要时刻监督和看管着你的员工，那么你只是个保姆，不是管理人员。你的问题在于招聘了错误的员工，无论是否采用远程办公，他们都不会高效地工作。

问题的本质是，不要录用那些你不信任的人。同样，不要为那些不信任你的老板工作。如果老板们不相信你会敬业地在远程办公，在其他事情上他会相信你吗？作为老板，你要么信任现在与你共事的员工。要么尝试去寻找那些你愿意相信的员工。

有些时候，如果你被其他的一些事情分心。这反而是一个很好的机会，反思一下你的工作是否没有被分配好，或者被分配到的工作内容太微小，甚至正在做的工作是不是完全没有意义。与其把时间花在电视游戏或者肥皂剧上，是否应该花时间思考一下这些问题。如果不是工作内容本身的问题，房间环境对人的潜意识也有一定影响。如果你身在厨房，可能潜意识里会想清理水槽。如果你坐在客厅的沙发上，可能潜意识里会去拿遥控器开电视。所以，如果你身在一件封闭的办公室内，你可能会自动进入想要工作的状态。如果以上这两点，都不是影响你在家办公效率低下的主要原因。你也可以尝试在家以外的地方办公。你可以在咖啡馆、图书馆或者公园内办公。大部分人都希望能够正常工作，只要工作充满刺激和意义。但是如果你被困在工作的死胡同里，呆在办公桌前感觉完全没有意义。那么你需要的完全不是更换一种工作方式，你需要的是一份新的工作。

传统公司内部一般效率低下，而且盛行官僚主义，但是外表看上去都运转良好。原因是，一旦一家公司有了稳定的带来现金流的业务，一般他们不会在意为了这项业务需要招聘多少员工或者有多少低效的员工在其中。所以在大型公司内部推行节省时间促进效率的新技术是不现实的。他们在意更多的是利润，以及如何保持这种利润，而不是需要投入多少人力成本，以及人力投入性价比的高低。

你所唯一需要的，就是保持自信。相信你正在使用一种更加聪明的方式工作，即使大部分人都还没意识到这一点。相信所有创新的产品，在初期看上去都很疯狂，之后才慢慢被大众接受。相信远程办公也是一种创新，当越来越多的人尝试远程办公，它也将慢慢变成大家都认同的办公方式。所以不要等待，现在就开始吧。

当工作结果能实时展示在所有人面前的时候，我们就能在短时间内判断一个人是否聪明和高效了。如果项目在操作过程中总是遇到这样或那样的问题，说明这个人对手头上的工作并没有很熟练或在行。如果某些人的项目经常性发生拖延，那么他的效率就有待提高。通过远程的方式，你就能很快识别出那些真正优秀的员工。能够快速学习，并且产生实际成果的人。快速识别并且留住这些人，让其他不适应远程的平庸的员工离开公司。

不是所有的员工都要聚集在一个办公室内才能创造出良好的公司文化。真正的文化来源于所有员工的实际做法。新的员工来到公司，自然而然会观察内部是如何运作的，老员工如何上班，决策是如何被做出的，问题是如何被解决的。之后，他们自然而然也会效仿。

-----

在37Signals，我们总结，每个团队每天只需要4个小时“重叠”办公的时间，就可以避免类似拖延的情况发生。讽刺的是，即使只有一半的时间，是你和你的同事在一个时间段协同工作的。反而你会发现，你在另外一半"独立"工作时间内完成的工作量及工作效率惊人的高。相比于，把一天的时间都花在处理紧急的邮件、会议、电话上。你可以完全控制另外一半自己的工作时间。另外，你会发现，大部分的人都愿意接受这种非传统的工作方式。也许因为这样，他们能够有更多的时间陪伴家人，或者从事自己业余的兴趣爱好。又或者只是因为他们在深夜、或者凌晨反而工作效率特别高...

远程办公能够大幅度地提高工作效率。更少的被打扰，更多的完成工作。但是，整天没日没夜的工作也不是很好的方式。在8小时的工作之外，能够陪团队成员放松一下，也是很有必要的，所以我们引入了"虚拟茶水间"。在37Signals，我们使用Campfire作为聊天室工具，某种意义上是一间"虚拟茶水间"。我们的目的是有一个统一、长期的IRC沟通软件。让所有员工能够发发段子、共享有趣的照片等等。当然，有时也可以作为日常工作沟通用。但是，主要的目的还是提供一个员工社交凝聚力的平台。聊天室的好处是，不需要我们24小时全天盯着。同事们每天在休息的时候，可以签到或签出。你刚刚完成了关于首页的设计？太好了。那就上传一张有趣的照片作为奖励吧。你会发现其他的同事可能没有看到过这张图，并且给他们带来一天的好心情。聊天室同样也是讨论新闻，交流肥皂剧，讨论午饭吃什么，这些经常会在公司茶水间讨论的事情。我们的聊天室经常被用来讨论一些实时的重大新闻，例如苹果最近又发布了什么重大消息。聊天室能够给远程办公的同事带来一定的社交联系的感觉。刚开始，你可能会感觉大部分花在聊天室的时间都是被浪费的。但是我们认为，这些所谓被浪费的时间，是值得的。我们都需要这样一间"虚拟茶水间"。

我们需要做到的是，让整个项目内所有的成员都能了解项目的情况和进度，让他们都感觉自己是被融入项目的。在37Signals，我们每周都会固定进行一个例会交流，主题是："你上周都干了些什么"。每个人都会简单的说几句，回顾上周的工作，以及下周工作的计划。不需要做到特别详细和精确的阐述和预测。这么做的目的是，让每位项目成员都能了解自己在整个项目中的情况和位置，感觉融入整个项目。另外一个潜在的目的是，能够提醒每位成员每周都需要有一点小小的进展。没有成员愿意在分享的时候说："ok，我这周大部分的时间都花在了玩光晕4，吃Pizza，看肥皂剧上面了"。我们都有一种潜意识，不想让自己成为拖延整个项目进度的人。最后，在这样的场面下，你很难忽悠你的老板。与一个没有技术背景的项目经理沟通，一些开发人员经常会把一些30分钟就能解决的工作，描述成需要一周的工作时间。这点，如果在有其他开发人员在场的情况下，就很难再作为借口了。

一旦开始尝试远程办公，你会发现，结果本身成了衡量员工唯一的标准。当我们以结果为导向，我们可以很清楚看到有哪些员工是实际在完成一些工作，而哪些只是在低效地浪费时间。

-----

与其他同事在一起上班可能会经常被干扰，但是完全隔离独处也不是最好的解决方式。即使是性格最内向的人也需要与外部社会有沟通交流，这是一种基本的需求。这就是为什么监狱内的囚犯非常害怕被关到禁闭室的原因。我们所指的远程办公，并不意味完全与世隔绝。即使是远程协作，你也能随时感觉到"周围的同事"。他们都在IM或者Campfire上，你会收到他们即时的Email。但是缺点是，这仍然不是一种真实的，面对面交流沟通的方式。我们每个人每天仍然需要有一段时间，在线下与其他人有真正的沟通交流。幸运的是，经过这么多年对远程办公的实践。我们发现，人与人之间线下交流的需求，并不是非要来自于同事之间。它们同样可以来自于你的孩子们、家人、朋友和邻居。与你的同事们在线上虚拟的交流，与家人和朋友们在线下真正的沟通。

管理人员需要建立的是合理的预期。在37Signals，我们希望并且鼓励员工实行40小时/周的工作制度。我们不鼓励投入更多的工作时间。当然，难免有赶进度的时候。但是长期来看，我们觉得这是一场马拉松，公司需要保持节奏，不要急功近利。设立一种好的工作制度，让员工自己衡量和定义："什么是一个好的工作日"。在每一天的工作结束之后，能够反问自己："我今天的工作有成效吗？"通常，如果我们能够很轻易的回答："是"。那么你可以停下手头的事情，因为一天中最重要的部分已经被完成了。如果答案是："不"，那么你也需要停下来，反问自己为什么效率这么低。高效地工作是一种很好的感觉。如果能够连续几天保持，那么渐渐就会变成一种良好的工作习惯。

你不能只是表面的理解远程，粗暴得把员工放在另外一个地点工作。正确的方式是，你必须让整个团队都远程，不管是项目经理或者团队核心成员，大家都需要一个长期的工作时间来不断调整和适应，来能慢慢体会到远程的真正作用。即使你的身边都是对远程充满热情的人，如果采取了错误的方式开始，结果也是一样糟糕。抛弃传统的工作习惯，适应新的工作方式，这都是需要时间的。当你已经习惯了在任何时候遇到问题就询问身边的同事，如果你刚开始尝试远程，会感觉非常难受。重要的是，让所有人，或大多数人都能感受到远程带来的好处。否则，人们会很容易将注意力放在那些负面情况上。当所有人都呆在办公室，他们会特别珍惜那些浪费在通勤路上的时间，那些本可以用来陪伴家人孩子，用来阅读，或做其他事情的时间。

-----

如果说有什么方式，能够快速训练并且适应远程协作，那就是多参与短期交付项目。为了完成一个短期项目，你必须有一份合理的时间安排。在每个时间节点做出相应的里程碑，把一些模糊的需求转变成实际可交付的产品。所有这些技能，都是远程协作办公所需要的。无论是对于公司进行远程招聘，还是那些开始逐渐尝试远程的人来说，短期的项目都是非常好的练习。在整个过程中，双方都可以观察和试探对方。你可以观察你的客户是不是一个笨蛋。如果是的话，那么在合同到期之后，你可以更换而自由选择其他的客户。

-----

远程方式，大家没有聚在一起工作，甚至没有一个固定的办公室。但这并不意味着定期聚会对团队不重要。事实上，在37Signals，我们每年至少有2次公司内部的聚会，每次4-5天。一般我们会安排很多交流、了解项目进展，确定未来计划。但是最重要的是，让同事彼此之间能够熟悉起来，了解其他人的真实性格。事实上，要很好的践行远程办公，同事们之间最好之前已经有过一些线下真实的交流，相互交谈，或者一起吃饭等。聚会是帮助新进同事融入团队很有效的方式。我们把芝加哥的总部办公室重新装修了一遍，所有现在的公司聚会都会在新办公室举行。之前我们的聚会地点遍布各地，威斯康辛，圣地亚哥，加利福尼亚，等等。

公司内所有同事聚在一起是非常重要的。如果不能同时所有人，偶尔部分成员聚在一起完成一个小项目的功能迭代有时也非常必要。如果项目非常紧急，期限又短，交付的压力将会非常大。这种情况下，项目成员短时间聚在一起，即是完成项目，更能增进大家的交流。在37Signals，过去我们经常这么操作，当我们要发布一个新产品，或者完成一个特别早期的功能需求。另外，参加行业论坛，也是一种很好的方式。大家聚在一起，白天可以学习新的东西，晚上可以相互交流。远程只是一种工作方式，并不意味着你所有的时间都必须独自一人。更多的交流，会让个人的生活更加丰富有趣。

远程协作共同完成项目，关键的一点是，保证任务随时都能取得进步。我们不能允许，无所事事地等待3个小时，就是为了上级的批准，或者等待你的远程同事能够起床开始工作，只是因为需要和他沟通之前项目的进度。当你在传统办公室朝九晚五工作的时候，一般不会察觉到这类的障碍。如果需要知道新版本部署上线后是否有问题，你只要转身询问同事就可以了。为了扫除远程工作的这些障碍，一开始就需要授权每位员工都能自主的做出决定。如果公司内有大部分员工，都没有被充分地授权，而必须等待更上级领导的安排，那么公司内部结构一定有很大的问题。有更大的问题，大部分的员工都不敢自主做出决定，因为害怕承担失败的责任。作为一名远程工作的管理者，你必须理解并且容忍错误。这些都是自我学习和充分授权，前期必须要付出代价。其次，你必须保证所有同事在必要的时候，都能得到他所需要的信息。但是大部分公司采取的都是相反的策略：每名员工只能获取与她的职位相匹配的信息。这完全是没有必要的，除非你是在军队，或者从事其他高度机密的工作。设置这类的信息壁垒，只会给远程工作的同事造成障碍，无法完成工作。而且，造成这种情况大部分的原因在管理人员自身。所以，不要低估这些障碍将会造成的问题。我们需要将更少精力放在获取审批上，把更多精力集中到创造有价值的产品，为客户提供更好的服务上面。其次，在休假上面，我们也没有任何的审批流程。我们的要求只有：自己把握尺度、休假日期记录在公共日历上、事先和其他配合同事沟通好。把一旦你放手这样做，雇员们表现出来的高度责任感会超乎你的想象。

-----

我们大多时候很难划清工作和生活的界限。特别是，当我们在家和在公司使用同一台电脑。在家的时候，你仍然会打开工作邮箱和聊天软件，否则内心会感到不安。一种可行的解决方案是，使用不同的设备进行区分。如果你的娱乐设备甚至都不支持工作需要的软件，那是最好的了。部分开发和设计软件在iPad上也有，但是大都不太好用。另一种方法，将家里的键盘、鼠标、显示器都藏起来。制造一个充分舒适的休闲环境，让自己充分休息。我们发现，在家中使用一台手持设备，而不是笔记本，效果也不错。如果整个白天都是对着电脑的键盘工作，到了晚上换一台更加轻便的设备，感觉非常好。更复杂一点的方法，使用不同的邮件和聊天账户来区分。如今我们在家中，一般都有2、3台的电脑设备。我们建议入手一台iPad在家使用。

如果人们对于工作的积极性不高，很有可能是因为他们的工作没有被清楚的界定，或者工作本身缺乏意义，又或者只是因为团队其他的同事都没有作为。这个现象很普遍。大多数缺乏激情的工作者，往往都会先责备自己。"问题出在我自己身上，我是严重的拖延症患者。""我为什么就不能更加投入一点呢？"但实际上，主要的问题不是出在你自己身上，而在于你所处的环境上。所以一旦认识到这个问题，就立即停止自我责备，将注意力转到如何调整和改变身边的环境上面。

如果你是以远程的方式在工作，那么工作本身就不能成为你放弃追求梦想的借口。大部分智力劳动的工作，你所需要的仅仅是一台电脑和无线网络。你可以随身带着笔记本电脑，并且现在全世界大多数的地方都能方便的接入互联网。记住，我们并不关心你的工作具体是在哪个城市、哪个地点完成的。当然，你还是需要遵守远程工作的一些基本规则。例如，保持定时和同事们的沟通。

一成不变的生活会消磨你的创造力。每天在同一个时间点起床、乘坐同样的交通工具、走同一条路、在同一张办公桌前坐下，这样周而复始的环境和工作，很难产生灵感。然而不定期的更换工作环境，往往能给你带来很多新的想法。所以，不要单纯的把远程工作理解为把办公室从公司搬到了家里。远程真正的意义是，能够有机会接触更多的事物，从更多的角度看待问题。
