#+title: Remove the stress, pick a deadline
[原文链接](https://signalvnoise.com/posts/3963-remove-the-stress-pick-a-deadline)

**论deadline对remove the stress的重要性**

The purpose of a self-imposed deadline is to sharpen the edge of your prioritization sword and stake a flag of coordination for the team. It’s not a hill to die on. It’s not a justification for weeks of death marching. It’s a voluntary constraint on scope. (感觉DHH真的很会用词. self-imposed(voluntary constraint) deadline来改进工作优先级以及团队协调)

DEADLINE的要义是, 必须是按照大家开发节奏商议出来(这样不会大家burn out, 觉得deadline是death march), 同时要能有约束作用(不管是为了克制大家的懒惰, 还是为了后面说的解决各种debates)
 
Yes, deadlines are wonderful! They’re the tie-breaker on feature debates. They suck all the excess heat out of the prioritization joust: “Hey, I’d *love* to get your additional pet feature into the first release, but, you know: THE DEADLINE”.

The opposite of the deadline, the once much heralded [[http://www.urbandictionary.com/define.php?term=When+it%27s+done][When It’s Done]], is the oppression of a blank canvas. Unless your system has fewer moving parts than you can count on two hands, objective perfection is impossible. It’s always a trade-off, but one that now needs to happen in the uncharted territory of a team-sized illusion of agreements. (deadline的方面是宣称的'When It's Done'. 这种方式比较适合系统中只有有限的moving-parts, 否则objective prefection根本无法做到)

Putting in [[https://signalvnoise.com/posts/3180-a-good-days-work][a good day’s work]] relies on the knowledge that you just moved a little bit closer to the finish line. If the finish line is constantly moving and constantly in dispute, it’s impossible to reap that satisfaction. Which in turn leads to stress and misery. 

Don’t let the self-imposed deadline kill you, let it free you. (看完DHH的文章感觉神清气爽)
