#+title: 任正非文集

我们要重视对爱尔兰的投资，它离纽约只有6个小时的航程，但税收比美国和中国低很多，所以很多美国大公司的资源都放到了爱尔兰。我们在那里能够亲身感受美国文化，轻松获取美国人才，而且它的生活环境更美。美国可以在全世界建立基地，我们可以围着美国周边建人才基地。

产品、解决方案及服务技术能力上，重在为我所用，但在关键控制点上要为我所有。 在基础技术能力上，侧重为我所用，但在核心技术上要为我所有。在基础理论能力上，做到为我所知、为我所用就可以了。

在变革的过程中，你有两个事情要做：第一个，你要忍耐。我们是大兵团作战，没有规则是不行的，规则也不可能适合每一个人，所以忍耐是必须的；第二个，你要提出来，他们怎么考你，你认为最好，因为只有你自己最了解怎么评价你。只有这样双方积极地互动，我们才有可能在以前的基础上改革，走向更科学合理。所以你应该积极地提出对自己怎么考核，给有关部门作为参考，这样他们制定的政策就能正确。

如果我们不断退出艰苦地区、战乱地区……，退到只有中国市场，再退缩在北上广深这些发达城市，最终会像蚂蚁一样被别人轻易消灭。所以，用低端产品来保卫我们高端产品多一些盈利，很重要。虽然低端机在商业成功上赚的钱少，但是保卫了高端机的市场，它为你流血牺牲，高端机为什么不能分点钱给你呢？人力资源价值系统需要调整。艰苦地区也能出将军，低端产品也能出将领。

我强调公司要开放，见识比知识还重要，交流常常会使你获得一些启发。 我觉得你们年年青青就走出国门，就到了艰苦地区，不要自闭于代表处，自闭于首都，要大胆融入当地社会，更重要的要融入当地的上层社会，市场的机会、格局的形成，都在他们手里。西方人好运动，你们固守在“闺房”中，如何交朋友？打球去、滑雪去、水上运动去……，一切运动都是接近客户的机会。没咖啡，胜似咖啡。

需要总结，一根绳子抓不到鱼，打成一个个的结就成网了。总结就是打结，多打结就结成一张网了。 不要龟缩在首都，不要龟缩在代表处，要多去了解合同场景、以及未来的合同场景，旅游时，也估估这个地方的工程难度。不然怎么叫上过战场。

我们的合同是在上层社会手里面，融入不进上层社会就没有这个机会。 从我们走过的这个道路来说，首先舍得花钱，才会挣钱。年青人首先不要存钱，要存本事不存钱，存人脉不存钱，没有人脉能做成啥呢？但，你没有本事，有人脉也白搭。当然我也理解有人要存钱娶媳妇，有出息是不是更容易一些？

对于过去的规章制度，持“祖宗之法不可变”的态度是错误的，但“变法”一定要保证科学性，要保持不断的协调，要先“立”后“破”，这样才能避免旧的已经废除，新的还未产生，制度上的真空地带引起的混乱。

我们公司的工资在相当长时间里都要实行倾斜，向市场、开发、向创造性工作倾斜。我们不能保证公正、公平。摆平的作法，抹去了不同人员承受的压力是有巨大差别这一现实，是对那些公司最有价值人员的视而不见。这反而是真正的不公正。 我们公司最大的浪费是人才的浪费。我们的效率很低。一方面我们要精兵简政，一方面市场系统、开发系统还要扩充，形成火车头。

但是，年青也是我们最严重的缺陷，好奇心代替了成熟；重视成果，轻视文档，特别是轻视状态文档（生产指导文件、检验文件、用户指导书、培训教材、故障处理路标……），还十分严重。 重视技术、功能的开发，轻视可生产性、稳定性、可靠性的默默无闻的劳动；面向客户还是面向未来，在价值评价体系上还未根本解决……与竞争对手相比差距仍然十分巨大。

幼稚还体现在复杂的产品做得十分好，而同类技术应用在简单地方如此之差，远远不是科学的商人，这种不成熟性，处处都展示着公司的危机。我们必须，而且也是唯一，从今年起，推行产品的市场验收标准，这就是日本的低成本、德国的高稳定性、美国的先进水平，只有同时达到这三项标准，才有可能与国际著名公司竞争。

为了使我们的研发人员能够铭心牢记'从对科研成果负责转变为对产品负责'这句话，我们年终将把库房里的呆滞物料打成一个个包，发给研发人员做奖状，每人一包，你可拿到市场去卖，请你回答，我们这历史累积上亿元的呆滞物料是怎么产生的？ 今年我们发中研部呆滞物料奖，明年我们要把用户中心的飞机票，也打成一个个包，再发给中研人员做奖状，让他拿回家去对亲人说是自己得的浪费奖！

曾经看到过一句话，崇高是崇高者自己的墓志铭。这多少说明了我们在产品研发上不能技术导向，一味追求技术领先，在公司的动作发展上，也要把握好自己的节奏。现在技术发展很快，大大地超过了客户需求，不能及时发生效果，时代已经赋予你们新的使命。 我们要永远抱着理性的客户需求导向不动摇，不排除在不同时间内采用不同的策略，坚持理性的客户需求导向

研发体系大多数人都是工程师，渴望把技术做得很好，认为把技术做好才能体现自己的价值。简简单单地把东西做好，在研发中也许评价是不高的，而把事情做得复杂，显得难度很大，反而评价很高。这就不是以客户为中心，客户需要实现同样目的的服务，越简单越好。我们要使那些能把功能简简单单做好的工程商人得到认可，才能鼓励以客户为中心在研发中成长。因此我希望大家不仅仅做工程师，要做商人，多一些商人的味道。

在看待历史问题的时候，特别是做基础科学的人，更多要看到你对未来产生的历史价值和贡献。

高级干部与专家要多参加国际会议，多“喝咖啡”，与人碰撞，不知道什么时候就擦出火花，回来写个心得，你可能觉得没有什么，但也许就点燃了熊熊大火让别人成功了，只要我们这个群体里有人成功了就是你的贡献。公司有这么多务虚会就是为了找到正确的战略定位。这就叫一杯咖啡吸收宇宙能量。

要敢于改变商业模式，敢于关闭一些盈利不好的国家，敢于关闭一部分客户，少一点国家少消耗，我们聚焦提供好的服务，为什么一定要覆盖170个国家呢？要保证软件的合理利润，要从“迁就客户”变成“为优质客户服务”。

当我们逐步走到领先位置上，承担起引领发展的责任，不可以自己为中心，不能以保护自己建立规则。 我们要向ITU/3GPP/IETF学习，建立开放的架构，促使数万公司一同服务信息社会，以公正的秩序引领世界前进。 没有开放合作，我们担负不起为人类信息社会服务的责任，所以，我们要向3GPP一样的开放，向苹果、Google……一样的链接数十万合作伙伴，持续建设和谐的商业生态环境。以自己为中心迟早是要灭亡的。

这次从国外回来，我有一个很深的感觉，觉得国外的中青年人有一个很伟大之处，就是他们没有什么空洞的理想，脚踏实地做好每项不起眼的工作。搞焊接的，对每一焊点质量充分保证，能钻研进去，在这方面成为专家，也有价值上的承认，照样拿高工资。他们是为生活好而奋斗，多挣钱买房、买车、旅游。干什么爱什么。而我们的青年人，干干就想着提升，就想脱离自己的岗位，一辈子熟练程度都不够

公司推行效益优先，兼顾公平原则，让优秀分子先富裕起来，但要反对富裕起来后的不良行为，不要做违法乱纪的事，要加强精神文明教育，要作风正派，在公司按公司的纪律办事，在公司以外按国家法律办事，违反公司纪律和国家法律的，公司决不迁就。
