#+title: 共和和民主的区别有哪些？

作者：姜源
链接：https://www.zhihu.com/question/20516024/answer/40435829
来源：知乎
著作权归作者所有。商业转载请联系作者获得授权，非商业转载请注明出处。

民主更侧重体现多数人的意志，而共和更侧重不同人群和力量的平衡。我们更熟悉的民主理论一般认为，一个国家的人民在法律上是平等的，通过民主制度可以产生多数人民的意志，而这种多数人的意志转化为人民的共同意志，进而转化为这个国家的意志。但是共和制在历史上则被描述为一个国家不同阶层之间的巧妙结合，比如在罗马平衡贵族与平民，在英国平衡国王、贵族与平民。即使现在不再存在国王、贵族这样的特权阶级，共和制的传统相对倾向于认为共同意志产生于不同人群之间更复杂的互动，比如在美国强调联邦和州的平衡，而不是单纯靠人数决定共同意志。

共和制更愿意承认精英的重要性。在决定国家政策时，共和制更能够接受少数精英基于其经验和智慧推翻大多数人的意志，而民主制要解释为什么各别精英可以对抗大多数人就要麻烦一些。举个例子，在美国平权运动的年代，美国最高法院的行动常常领先于立法系统，特别是南方各州的立法系统，所以南方各州当时广泛存在这样的疑问：为什么远在首都的九个老人可以推翻本州大多数人通过立法机关确立的法律？对于这个问题，一种解释当然是民主制度不是单纯的多数决，司法系统也是美国民主制度的重要组成部分；另一种解释则是民主并不是美国政治的唯一原则，司法系统本身就是共和制度下约束多数人暴政的工具。

共和制更强调公民的政治参与。在现代民主制度中，如果一个人在每次选举的时候，认真负责的去投票点投票，大概可以算得上是合格公民了。但是按照共和制的要求，光做到这一点是远远不够的。共和制最重要的要求就是公民积极的参加政治生活，关心政治体的存亡和发展，具体而言包括接受政治教育，担任陪审员，民兵，甚至是担任公职和参与立法。这意味着公民应该花费更多的时间学习政治、思考政治、与他人讨论政治并且参与政治。所以正面描述上面第2点的话，并不是说共和制主张精英统治公民，而是每一个公民应当成为精英参与统治。但是这里需要再补充的一点是，共和制要求公民积极的参与政治生活本身隐含了一个很苛刻的条件，即公民不必为了谋生而终日奔波。因此，就我个人观点，共和制这一概念逐渐衰落，和19世纪之后各国开放普选权允许穷苦大众拥有政治权利是有联系的。

此外，传统上，共和制和公民的道德是有直接关系的，通过上面提到的政治参与，良好的政治制度可以塑造和培养公民的美德，而公民以其美德使共和国得到更好的发展。而国家发展和个人道德之间的关系在现代政治社会中是不相关的，而个人道德纯粹是一个私人事务，所以更多的人相信国家在公民道德的问题上应当持中立的态度，甚至应该直接退出道德教育的领域。
