#+title: 理想国(Republic)

理想国是柏拉图的代表作，该书不仅仅是哲学家的宣言书也是哲人政治家所写的治国计划纲要。虽然是柏拉图所著，但是里面大部分是恩师苏格拉底和其他哲学家的精彩辩论，辩论中涉及到了诸多问题比如国家专政，独裁，正义与非正义，善与恶，民主，法律，宗教，道德，妇女参政，教育等问题。这部分只是涉及到了国家政治，正义和非正义，以及民生这3个部分。书里面翻译的辩论过程虽然不觉得有多精彩，但是那个时候也确实有很多人有独到的见解[比如正义和非正义的问题上格劳孔对于正义的观点],里面涉及的辩论人有这些
- 苏格拉底
- 波勒霍斯马
- 克法洛斯
- 阿德曼托斯
- 格劳孔
- 色拉叙马霍斯
需要紧记的是，一些观点虽然看上去即使大部分人的态度很明显但是却说服不了另外一方的话，那么就没有辩论成功。所以里面的论题虽然看上去非常明显是谁对谁错，但是却需要完全的解释一番和辩解一番，就像是数学题目一样知道这个结论是对的和证明这个结论是对的是两回事。

-----

- 论财产与老有所福[老人的幸福是否有他所拥有的财产所决定]
- 理想国与理想政治[理想的国家人员应该是如何配备]
- 国家的力量与法律问题[在国家的力量下凭借法律我们应该限制那些东西]
- 论定国安邦[国民包括统治者被统治者之间如何对待才能够保持社会稳定]
- 论希腊内讧和战争[虽然是说希腊内讧问题，但是在书里面说的却是应该如何对待那些守卫国家的战士]
- 从寡头到无政府的政体形式[对比寡头和无政府政体形式]
- 正义和非正义[书中是分为几个部分探讨的，正义和邪恶，正义和非正义的区别，正义的起源和本质，最后是正义的最终定义。这个部分是最有意思的，其中色拉叙马霍斯几次可以说是挑衅苏格拉底，但是都被反驳回去了。在正义的起源和本质这个问题上，格劳孔的认识是相当精辟的，虽然看上去像是错误但是却无懈可击]
- 论国民教育[那些措施有利于国民教育]
- 智慧勇敢和节制的性质[评价智慧勇敢和节制对于国家的重要性]
- 论妇女天赋[应该如何去让妇女去发掘自己的天赋.不是探讨性别而是探讨我们对于妇女去发掘自己的天赋这件事情上应该持什么态度]
- 论哲学治国兼知识的存在[哲学即使是追求完美但是依然有可取的地方，知识不同于意见需要深入发觉并且抽象才能够感受其存在]
- 哲学家的德行[哲学家必须具备智慧，勇敢和节制才配得上哲学家，但是按照这个标准的话有太多伪哲学家了]
- 黑暗与光明的选择[黑暗类似于无知识的状态，光明是了解知识后状态]
- 独裁者的生活方式

-----

- 年老不是问题，真正会出现问题的是人性格的因素。一个乐观的，心境淡泊的人是不会因为年岁的增长而增加压力的。反之那些具有相反性格的人，即使年纪再轻或者也是一种负担。一个人贫穷并不可怕只要他善良，可怕的是富有了却充满了邪恶，邪恶的夫人老了也不是得到安宁的。
- 不要按照你的意思去解释守卫我们城邦的人的幸福观
- 国家的领袖们必须时刻注意到绝对不能够让自己的国家在不知不觉中败坏了，必须始终守护自己国家的一切，包括不能够让体育和音乐推出新花样，违反固有的秩序。
- 真正的立法者无论是在政治井然有序还是杂乱无章的国家里，也不无论是在法律还是宪法上，都不应该标新立异自寻烦恼。因为在政治秩序混乱的国家里，法律和宪法根本就是一纸空文，但是在政治秩序良好的国家里，制定法律和宪法就相对简单甚至还可以参考前人留下的相关规章制度
- 一个从小立志长大要当军人的人，如果在小时候不演练一些关于战争的知识，未来就难以成为一个出色的战士。所以在小时候让他们见证一些战争是非常重要的，为了这个冒点险也是应该的
- 推翻寡头政体形式而建立起的无政府，很容易进入这么一种民主制度就是本着宽容的精神，根本不去管理我们那些琐碎的事情。他们对我们缔造的理想国所宣布的庄严原则全然藐视，除了极少数天赋极高的人以外，没有一个善良的人不是从小就在一个良好的环境下游戏学习受到好的教养
- 孩子的初始教育是非常重要的，所以在故事选编上应该建立一个严格审查制度。同时宣扬诸神做的都是合乎人间意愿的事情，神是正确的公正的。同时神是神圣的不会在言行方面欺骗百姓。
- 勇敢就是一种坚持，坚持拯救内心存余的懦弱的灵魂。勇敢的人无论是在苦恼还是在快乐之中，或是处于欲望还是害怕中，都永远坚持这种信念而不抛弃它。
- 节制是指人的一些快乐的欲望有秩序且有理性地得到控制，按照现在人的话说”就是自己做自己的主人”。
- 了解知识的过程是非常痛苦的，就好像在黑暗的洞穴里面待久了让他们看到眼光会刺眼一样。但是只要花上一点时间的话，他们是会最终接受洞外的一切事物的，因为长期受到囚禁，想要重新认识外面的东西总要给他们适应的过程的:-)

-----

格劳孔关于正义的观点
- 人们从非正义的事情上获得了甜头但是也因为行使非正义而遭罪。于是人们想出一个名堂就是立法来进行正义的定义。正义的本质实质上是折中。两个极端是干了最大坏事但是却没有受惩罚，遭受非正义但是却没有能力报复。这样一来，正义被置于两者的中间地带，并非他本身就是善良，而是因为没有去行恶的胆略和能力，才被冠以正义之称。
- 一般人行使正义并非出于真心，而是因为他们想非正义但是却得不到条件的许可。一旦他们有条件去行使非正义的话，就会去行使非正义的事情
- 非正义的人去行使非正义的事情，然后从非正义带来的利益中挑出一部分充作诸神的祭品，借此逃过上苍的惩罚。

最后苏格拉底对于正义的定义[比较精辟]:正义就是能够使得勇敢，智慧和节制在这个城邦产生，并在它们产生之后一直保护他们的这个品质.
