#+title: 回顾2017

@2018-02-22

今年过年本来打算去山西大同的，但是大年30晚上临时取消了行程，所以我，金玉和胖子最后在家里过年了。回顾2017年，我们三个人在一起的时间不多，所以春节7天全家窝在一起，对我们每个人来说，都是非常需要的，是个非常好的安排。

今年最重要的事情，可能就是她父亲的过世。她的父亲离开时并不孤独，我和金玉过世当天晚上就赶到了玉田老家，陪在他的身边。我记得那天晚上我们很早就睡觉了，大约晚上8点左右的时候，她妈突然很大声地叫她父亲，于是我赶紧过跑到她父亲的床前。她父亲眼睛张得很大，只有出气没有进气，我赶紧握住他的手，在他耳边说我们全家人都在他身边。大约过了5，6秒之后，她父亲就没有呼吸了。家里很早就准备好了葬礼的衣服和物品，我们赶紧去通知邻里，他们都过来帮忙，把她父亲放在一块板子上，然后将房间布置成为灵堂。后面几天就是火化，吊唁，下葬这些事情，忙了大概3，4天左右。

她父亲离开了之后，按照当地的规矩，她母亲1个月内不能离开当地。金玉怕妈一个人在家孤单，所以想把胖子带回老家，一方面可以缓解妈的孤独，另外一方面也可以让妈有点事情做，可以分散注意力。但是又怕让妈一个人带胖子又累到了，所以我也跟着去了老家，[[file:a-few-days-at-village.org][帮妈一起带胖子]]。 我觉得和胖子在老家的几天，让我和胖子还有妈的感情加深了不少。所以如果想维系好感情的话，最好的办法还是要经常在一起生活，一起经历苦难和分享喜悦。过了一个月之后，妈离开了玉田县老家，来到天津，和我们住在一起，也帮助我们看着胖子。

妈来了之后，金玉轻松了不少。孙姨照顾胖子也非常费心，但是毕竟孙姨还是外人，很多话金玉也不太好和她说。比如晚上下班回来，如果金玉很累的话，孙姨也不太可能看着胖子，还是需要金玉自己来带。但是妈就不同了，如果金玉很累的话，妈晚上还是继续看着胖子，让金玉早点休息。而且和自己亲人在一起，可以说很多心里话，心中的负担不会那么的重，心里会更加轻松不少。金玉照顾胖子，身体上的累，可能仅仅占据一小部分，主要还是心灵上的疲惫以及迷茫，缺少交流和积极的反馈。好在最近这段时间，通过不同渠道的学习交流，情况好转不少。

迷茫的不仅仅只有她，17年我也比较迷茫。如何提高自己的能力，如何打开自己的视野和格局，如何规划自己以及家庭的生活，如何更好地培养胖子，在17年似乎没有找到什么答案。这些问题我也经常和金玉在一起讨论，总的来说，说的多做的少，谈话多行动少。新的一年，希望自己在做事情上应该更加讲究原则，合理地安排好时间，多走出去和别人接触，多系统地去学习非技术方面的知识。

最近这段时间，《随口说美国》放出了在上海和北京几场线下分享会的录音剪辑，金玉一直在家里用外放听。我觉得分享会里面大家的生活经历都非常精彩，他们说到了很多我们不敢想或者是觉得离自己很遥远的事情，但是当听到他们说时，我突然觉得这些事情都是可能的。原来世界很大，原来梦想离自己很近，原来生活是可以这样的。
