#+title: 回顾2021

@2022-2-1

在家里看孩子。今年1月中旬天津就开始闹疫情了，所以从中旬到过年都在天津，没有去北京。大姑大约是在1.25号启程回唐山，楚楚还要继续上班到过年，我便承担起了看孩子+上班的责任。实话说做的不是特别好，早上弄完早饭，基本就让这两个孩子自己呆着，等忙着差不多了再出去走走。中午回来炒两个菜，然后继续工作，老大就自己呆着，老二就睡觉了。等到下午差不多4点左右起来，闹腾一阵子，等我工作搞的差不多了，继续带他们出去遛遛，直到晚上他们妈回来。晚上吃完继续搞一阵子，然后上床睡觉。我自己倒是没有什么问题，就是感觉对他们两个小的不是很好，一天大部分时间都窝在家里，可能在学校也是这样的吧。好处就是突然发现自己还能炒两个菜，花点时间的话，基本上还能给家里整个比较合理的饮食菜谱啥的，不用再为吃饭（吃什么东西）而发愁了。前两天弄个西红柿鸡蛋汤，觉得后放鸡蛋有点麻烦，直接连着炒西红柿最后的余热一起炒了，然后加水做汤，完全是凭借自己的感觉而不是指导规则来做饭。

过年这几天在家有点憋的慌，这两个小孩子在我身边走来走去，问这问那。整理了一下假期要做的事情：整理一下前段时间看的几篇文论；看完复旦大学王建德的《中西文化差异渊源》的视频；做完Leetcode最近一周赛事的题目；然后就是整理一下这个《回顾》系列。我发现其实自己并不太喜欢写文字，可能喜欢用嘴说，不太喜欢键盘敲字，有点不太流畅的感觉：敲几个字，就要按几次回退键进行修正。要是能找到一种特别高效的输入法就好了，这样我可能会比较喜欢写作（在电脑上）。

今年大约4月份的时候终于从微软撤了，实在是待不下去。我任职的部分属于Bing QA Team，大部分工作就是帮业务团队设计一下质量体系工具：让他们的service利用offline traffic跑跑测试，看看success rate以及latency，以及做做output diff.  微软有套比较成熟的集群管理系统叫做autopilot, 东西是比较牛B，但是使用起来就比较困难了（或者说在容器化普及的现代来看），尤其是上了规模之后许多操作延迟都比较长。你不确定什么时候某个操作可以ready，必须不断地去客户端（非常复杂的客户端）上刷新查看，非常痛苦。而且Bing内部也在不断地迁移到Azure上面来，基本上需要熟悉两套复杂环境。从我的观察来看，Beijing Team基本上没有什么实质性工作，不知道是不是整个Bing就没有什么实质性工作。从上到下老板倒是比较鼓励Deep Dive去深入研究某个系统或者是组件，但是很难说学习是不是真的cost effective. 不是说这些东西做的不好，而是考虑这些组件的复杂程度，以及最后面学习到的内容，这个比例是不是真的足够高。总之我4月份从微软离开了，期间我基本上完成了mit分布式课程的材料，并且在离开前一个月阅读了一下liborc的代码，为入职StarRocks做准备。mit os课程只完成了了前面两节，compiler, database, comparch都没有看。不过后面花了一段时间把CMU DB Andy Pavlo的课程过了一遍，就算是完成了database的入门吧。

入职StarRocks的时候，产品还不叫做StarRocks，而是DorisDB。DorisDB是在10月份的时候改名叫做StarRocks的，当时受到了不少关注，当然都是负面性的。许多人认为DorisDB高调改名StarRocks，是为了碰瓷Apache Doris, 再次为自己做一次PR. 网上有很多讨论，其实许多人不知道真相，都是按照自己的猜测和臆断来写的，我也没啥好说的，因为这种争论不是基于事实而是立场。我一直觉得，只有StarRocks不断地改进，不断地发展，大家才会改变他们的看法。入职头几个月把CMU DB的课程都过了一遍，后面几个月也把Advanced Course也看了，都是草草看的，不能当真，后面真的做到这块的时候，还是需要回头来看的。在SR遇到了不少牛人，他们的牛是方方面面的不同维度的。我觉得只有这样看待同事/人才，才能真正地从他们身上挖掘到闪光点以及可以学习的地方。如果只盯着别人的缺点，按照佛家的说法，就是住了净相。在这里我学习到了不少东西，数据存储，执行引擎，查询优化，各种各样的，让我打开眼界。我是从执行引擎这块入手的，做了一些工作比如orc解析，global runtime filter, 高基数group by/count distinct优化，CTE复用以及最近做的hive on s3. 有点遗憾的是，我做的都比较杂，都是许多小点，没有机会把他们link在一起。组里面有很多这样的能人，他们对于系统理解更加深入，可以看到更大的picture, 也能做更加复杂和有挑战的事情。我今年35岁了，按照互联网公司的标准，属于被优化的年龄段了。不过我还希望自己能做些和技术相关的工作，做些有技术挑战的事情。非常感谢SR能够提供给我这个机会，让我这种中老年选手发光发热。

说到中老年，让我想起今年读的一本书《当我跑步时我在说些什么》，中间村上说到随着年龄增长，生命中会有越来越多的生活琐事需要自己应对。吴军也说过，30-40岁的人，必须承担起家庭和社会的某些责任，不能再像刚毕业的学生。生活的琐事犹如给孩子选幼儿园，选小学，请阿姨带老二，这些很感谢楚楚同学搞好了许多大后方的事情。今年3月妈去了山西，楚楚请了一个阿姨，有很长的磨合期，后面8月份家里有事情也撤了。楚楚请大姑过来看老二，发现带的还挺好，也是因为老二比较皮实可爱，小区的人都非常喜欢他。11月中旬的时候，我和父亲回趟抚州，带着姑姑去看病，自己也帮着做了比较重大的决定。后面这种事情会越来越多的吧，自己要做好心理准备。老大准备上小学，老二准备上幼儿园，花更多的时间陪老大成长，可以的话夏天去些其他地方散散心。

既然生活上的琐事会越来越多，自己对于技术上就不做什么目标设定了，看工作需要吧。还要要做些设定，那就把mit OS以及comparch搞完把， 数据库看看sqlite或者是duckdb啥的。
