#+title: 回顾2009

新年总是反思的最好时候，一年下来发生过很多事情，自己回忆一下也不见得不好。基本上这一年发生了相当多的事情，下面按照时间发展顺序描述一遍:
- 论文的写作。终于知道论文是怎么写作的了，内容格式，外部格式以及种种规定，也至少知道会议是怎么投的了。大部分来说只要有钱的话基本上就搞得定，剩下的就等会议帮你发表和被EI收录了[SCI档次高一些所以很可能不是这样的情况]。
- baidu astart,youdao,GCJ.前面两个分别是在6月份举行的，初赛都没有进去。而GCJ是在9月份举行的，也只是到了Round2，没有混到T恤。对于GCJ没有什么后悔因为自己实在是实力不济了。而对于前面两个比赛就感觉非常不可接受，居然初赛都没有[astar的初赛对于我这种水平还是比较难的，但是youdao那年非常简单]，所以下了一点狠心需要补一补算法方面的东西。所以买了一本算法导论读从6~9月份，同时把POJ的题目做到150[承认里面有相当部分的是水题]。而且也因为youdao知道了TC这个东西…..现在还偶尔会做做TC SRMDIVII的题目，因为我觉得我大概就是这个level…。同时还接触到了ProjectEuler,虽然里面都是数学问题但是大部分还是涉及算法了，大概做了110多道，以后大概就是有空看看吧。不过现在看起来自己的算法水平也就是那样，想要更上一层楼更多的训练是必须的，但是却错过那个时候了，现在想到能够了解一些常用的算法解决日常问题就够了。
- linjiang和wjp的谈话。约摸是5月份的时候linjiang跟我谈过一次话，大致内容也是以后的职业规划。算法[其实确切地说是研究]和工程都是非常重要的。虽然那次谈话没有太多意思，但是我知道了其实工程和研究有时候是相去很远的[至少在国内环境下]。实习之后wjp告诉我的东西也记得非常清楚，那就是如果一旦选择工程的话，那么可能你进行的工作可能不会太深入更多的关注是实用，调研项目也会存在但是却没有到达研究的level，一旦完成预期的调研目标就不会有深入的[除非个人完成]。当时wjp还好心的告诉我，你要想清楚了是选择什么东西。3ku…但是现在我看上去好像有点不是很适应，不过我却有信心。
- wjp的谈话。这个谈话实际上和3中的谈话是一次谈话，但是侧重点却不一样。这个谈话主要关注的是在组内的工作，这也是让我最深的感触到:”啊，原来还有这么多很重要的东西没有学”，也让我深刻的意识到虽然进了这里但是基本上自己的基础还是0，所以自己会有很长的路要走，多线程，网络框架，分布式系统，数据库等…同样现在看上去也还是非常不适应，但是却有信心。
- 流程的熟悉。流程的熟悉也是在负责一次模块升级中学会和理解的，多亏了lgong的教导。半年前我就接触到了流程这个东西但是当时却是非常的抵触，认为这个东西无用延缓了开发进度并且工作复杂化。但是在那在模块升级中，lgong的教导让我这到了这个东西的好处，而且在之后的其他模块升级中也发现了流程的好处。有时候会很繁琐但是对于开发质量的提升会有一定的帮助。
- baonh的教导。在指导的2个月里，虽然没有太多的交流，但是却教了相当的多得东西。虽然是细节，但是作用却非常大。比如他对于很多问题思考非常深入，考虑问题非常周密，code review的时候也是非常的仔细，了解一个需求的时候也会同时了解这个需求的背景，在进行邮件回复的时候也是将问题阐述得非常的清楚，同时对于词语的选择也是非常细心的，总之是一个非常具有模范作用的导师。协调了组内的工作任务，同时也基本上手把手教着我们几个人。科学称号实至名归。算是心中有一个榜样吧。
- yufan的离开还有年前的一个bug。他的离开其实不是直接影响，关键是是他一走然后就需要分配工作。然后我所接到的模块工作非常的多，所以就需要阅读yufan的代码。然后就能够知道什么是规范的代码了。在我回家之后原来的一个模块升级出现了一个bug，为了这个bug我确实想过自己是一个合格的程序员，而自己心里合格的程序员就是像yufan这样的。代码非常规范，而且附带的wiki资料也是非常详尽。同时他会很多种语言比如Java，而我们组内对Java熟悉的人不多，以致于走后的话模块接受起来都比较麻烦。而且他的工作效率也是非常高，了解这一点其实只要接手他以前做的模块就了解了。代码的效率也是没得说。嗯，也算是心中一个榜样吧。
- bae和kwestion的成功。他们让我感受到了真的真的必须接受这个时代是互联网时代了。互联网的东西做出来通常都比较酷而且非常实用，同时我们很大程度上也会依赖于互联网了。而很多服务都是都是放在互联网上的，GAE,wordpress,drupal,…，如果还是老古董的话可能真的不太好了。bae的成功对于我的另外一个影响就是让我认识到了自己的水平。网路上流传程序员十大境界，我相信bae的xiaowei是牛人级别，我也知道自己的level大约就是大虾级别，所以路还是很长的。清楚地认识自己的水平，在前方有个榜样，这种感觉还是相当不错的。
- 春节回去购买车票。我回去购买车票的方式还是停留在去站点购买，而不是网路上购买飞机票[因为有时候提前预订实在便宜]。我没有taobao帐号，没有youa帐号，没有chinapub帐号，没有网银帐号，没有twitter，不知道如何翻墙，因为我从来不在乎。但是这次回去我买的火车票大概是300多没有卧铺是坐票，但是我的同学说要是提前订飞机可能就200多就搞定。大概这个时候脑子开窍了。作为一个IT民工连这些基本的便利网络服务都没有使用过，就像是一个文秘不会使用email和word一样，大概这也是我搞了一个twitter的原因吧[话说twitter还是真的很好玩的，虽然现在follow的人不多，但是那些人说的东西却特别有意思]。

#note@2013-03-19:
- 2008.8月在百度开始实习，实习到了大概2009.2月
- 2009.2月回家过年。如果没有记错的话，那年春节是在海南过的。
- 2009.2过完年之后就去学校开始准备论文并且做助教，一直到2009.10月。
- 2009.10在北大南门宿舍遇到了高中同学冯小和，他要考经济方面硕士。之后我搬到了胖子家遇到了余雷。
- 2009.10一直实习到了年末，年末拿到了录用书。年末的时候外公去世了，2010年年初奶奶也去世了。
- 2010年春节我记得是和姑姑在宾馆住同一件房子。那天晚上写下了这些。
