#+title: 回顾2024

@2024-12-26

今年年底又出差来美国了，3月份过来差不多3个月，这次12月底过来差不多又要待上3个月。每次过来心情比较复杂，来这边某种程度上可以暂时离开在北京的繁重的工作责任，但是心里又有点放不下家里的事情。现在回过头来看，感觉自己应该还是关心家里多些，有时候做事情的时候不免就想到家里。事业上估计就这样，其实再怎么折腾短期也不会有什么效果，不过多花点时间在家里，好好规划一下家里的事情就挺好。

今年年初随手翻了一些《道德经》，感觉挺适合我这个年纪的，许多事情开始需要放下，可能才能更好地拿起来，有时候太执着某件事情，反而做不太好，举重若轻是境界。后来又看了南怀瑾说《金刚经》，越发感觉到执着是苦，想要获得幸福就要学会放下。现在想想其实某种程度上是挺消极的想法，或者是我理解错《金刚经》的意思了。谋事在人成事在天，应该是更好的理解，现在想想那段时间确实有点“不谋”的感觉。

3个月时间都在硅谷，哪里也没有去，趁着周末去附近跑跑步，来公司看看《深度学习》和各种视频，还手抄了一遍《金刚经》。话说念金刚经，确实可以得到静心的效果。那段时间也是挺自在的，就是对未来依然有点不甘心的感觉，似乎感觉自己没有在正确的track上。

6月中旬回去之后依然是每天上班，8月份的时候去了一趟太原亲戚家，在周边转了一下，尤其是去看了晋祠。太原是一个很有历史的地方，挺喜欢晋祠里面的古建筑那份厚重感，还去平遥古城转了一圈，那边的商业化氛围就有点严重了，不是特别喜欢。

9月份骐骐开学之后就按部就班地生活吧，那段时间感觉自己身上的湿疹有点起来了，原因就是那段时间又开始没有节制地喝咖啡，最高每天差不多能到4杯。其实当时已经感觉皮肤有点痒了，也意识到是因为咖啡引起的，但是没有太在意这件事情，确实有点不太应该。后面必须控制咖啡的摄入量，另外就是如果咖啡摄入太高的话，必须补充大量的水分，减少咖啡因对身体的影响。另外咖啡因影响睡眠，这个也会影响到免疫力和皮肤。

9月份之后就差不多每个月去单位一次，差不多在11/12月取北京工作和同事的聊天中，我突然感觉自己过去许多行为其实非常不合理，为此也和老婆讨论了一下这些过去的行为以及内部可能的成因。然后公司最近也开始做一些政策调整，感觉是机会，所以想抓取这次机会做出改变。年纪大了有更多需要顾虑的事情，做出改变不太容易，但是如果不改变的话，一眼就看到头的生活其实挺恐怖的。尤其是对我这种突然意识到自己过去不对的人，如果在不进行改变的话，那么未来留下的似乎只会有遗憾。我愿意失败，但是不想留遗憾。

从工作到现在，感觉自己似乎对各种事情都不太关心，所有事情似乎都是放任自流没有计划和目的。如果自我安慰地来看，或者是没有任何对比的话，那么可以认为这样生活也没有错误，但是其实某种程度上是牺牲了身边的亲人给于自己的支持。 如果时代和命运给了我们这样的机会，让我们可以更好地获得资源，如果不去关心也不去尝试抓住，似乎是有点对不起这个时代和命运。
