#+title: 回顾2020

@2020-11

covid19到现在还没有过去，估计会成为一种常态了。现在美国2020总统大选还在进行，拜登264 vs. 川普214. 拜登只要在拿下内华达州就是270票了。

covid19在过年期间肆虐着，本以为过完年之后就能完全控制住，但是过完年之后却没有控制住的迹象。经过了一段时间的远程办公之后，最后包括我们公司在内的许多公司，都要求在某个时间点必须回单位上班。

我可能是在3月初的时候开始动身去北京的。我记得那个时候城际列车也很少有人做了，所以我是开车从天津到北京的。不管之前去过那里，只要到了北京之后就需要自己隔离14天，每个小区居委会都会严格地要求本小区的人这么做。
办法是每个人在进小区的时候发一张证件，上面登记着你什么时候进入小区的，然后应该自我隔离到什么时候，期间只需要叫外卖。那段时间我用了好多次山姆的极速达，我相信那段时间大家也开始养成了网购一切的习惯。
自我隔离了14天之后就开始去单位上班了。期间理论上是不能离开北京的，但是实际上小区是没有办法追踪到你是否离开北京。只要你有小区的通行证，并且上面写着隔离14天，那么就都是可以出入的。

或许是在家呆的时间太长的原因，我始终提不太起工作的兴趣。聪哥让我调研了一个微服务框架go-micro, 我花了2-3周的时间做了调研，觉得这个框架挺强大的。不过考虑到好像没有强大的公司在后面支持，我始终觉得它的生命周期不会太长，未来还很难说。
另外关于go语言，我不太好说它之后的发展趋势，也不想投入太多在上面。相比它，我后面可能更愿意花时间在java/jvm这样的生态上。

covid19另外一个影响就是全球经济的下行，让我对现在的项目不太看好，所以在6月份我选择了离开。当时我对自己的职业规划还有些想法，就是希望可以在某个方面长久持续地做下去，大公司是个选择（HC其实还有，但是要求更高了），有些做开源软件的小公司也不错，
比如做性能剖分的openresty公司，和我之前主管出来做doris的公司。

明年岳母3月份就要去大哥家帮嫂子看孩子了，这样一来老婆就必须一个人带两个孩子。考虑到老大马上就要上小学了，所以年底的时候我们还商量要不要让老大来北京上学。计划是这样的，老大在附近的花家地上学，下课后接到托管班去，然后我下午尽可能早点走，然后回家陪他。这样一来，老婆那边只需要照顾一个一岁半的小子，压力会减轻不少。而且我比较担心老婆一直对老大比较宠溺，这样在小学期间不太容易养成良好的习惯，所以放到我这边来，让父亲用比较严厉的方式相处，在头两年会是比较好的选择。现在过来上学就只有两个问题，工作居住证我之前没有办理随迁需要赶紧办上，另外就是当时买的房子不是特别确定房主的孩子是不是用了这套房子的学位，这两个问题目前看上去都没有问题，希望一切顺利。等老大上二年级左右了，然后老婆也过来，这样老二也差不多可以上幼儿园了，这样白天她就可以轻松不少，可以做点自己的事情。

这件看了一下附近的托管班，在方舟苑的那家可以托管到比较晚，可以到晚上九点之后。当然我也不会那么晚回去，不过就当是保险吧。我看了一下公司，感觉基本上7点左右就可以撤了，另外WFH也相对比较自由，而且公司也比较注重work-life balance, 从经理到同事也是尽量营造出这样一种氛围。7点半从单位打车，通常人不是很多，大约30分钟就可以到家。早上相对堵一些，但是大约8:50打车的话也可以在10:00之前到单位，这样一天在办公室的时间就有9个小时，经理和同事应该也不会说什么。

为了保证良好的体力，从12.14左右我开始养成一个习惯，就是大约6点左右起床去跑半个小时。要是胖子过来了，我可以更早点起来去跑跑步，回来之后给他弄点东西吃，然后就送他去上学校。要是实在不行的话，那就每隔2天下午在单位跑跑步，反正每隔2天要活动一下，保持充沛的体力。晚上回去就带他看看书，或者是带他去附近走走也行，和他聊聊天什么的。我觉得头两年应该没有问题，对他来说可能也比较新鲜吧，最好是能养成阅读和锻炼的良好习惯。

我自己的话也安排了不少任务，但是都是优先级相对较低的任务：
1. 阅读几篇分布式系统论文
2. 完成MIT的OS,Compiler,Database,体系结构课程
3. 可以考虑阅读sqlite, lua代码
4. 看看一些杂书，历史，经济，社会，自传等

明天要做的事情不少，但是控制好节奏，不要把自己搞的太累。未来几年，带好两个孩子，把自己的生活逐渐正常化，才是最重要的任务。
