#+title: 回顾2023

@2024-02-14

年前姑姑去世了，当时我们正在做一个短途旅行，去南京和杭州看看。在南京的第一天就接到爸爸的电话，说姑姑已经昏迷不醒了。两周之前我还和姑姑通过电话，她当时说自己感觉有点身体和魂魄分离的感觉，飘飘然，然后过了一会说我爸爸来了电话就挂断了。那次视频就是我们最后一次通话。不过之前我们也陆陆续续通过好几次视频，说的都是有的没的事情。我自己倒是希望她可以早点睡过去，每天躺在床上也是一种折磨，所以我并不觉得伤心。对她是一种解脱，对大家都是一种解脱。

今年3月份左右的时候就去美国出差，大概在那边待了大约3个半月，现在回想起来没有太多印象，每天就是上班和吃饭，然后周末和同事去爬爬山，中间几个周末还去附近的城市去转了转。在那边和之前百度以及友盟的同事吃了两顿饭，感觉在那边的同学都生活得不错，主要是看上去气色挺好的。我大约6月份回来的，老婆说我在那边待了几个月，气色是变得更好了。我觉得除了吃的东西和空气之外，主要是操心的事情比较少，操心事情少了心情就容易放松下来。在国内需要自己有意识地调整生活节奏，调整自己的心情才能让自己放松下来，在那边基本上被动地就可以放松下来。

回来之后感觉骐骐和二堃都长大了不少，章钰骐感觉变聪明了不少，二堃则更加活泼了。后来发现应该是长久不见面的原因，导致对他们期望有点降低，所以看到他们就觉得发展特别好。接下来的半年，每天和他们相处，慢慢地要求就开始高了，和他们生气的时间也变得越来越多。所以客观地所，只要是适当的环境，每个孩子都会发展的非常好，只不过我们成人的欲望增加更快，期望增加更高，所以感觉他们没有什么进步，不自然地就会揠苗助长的冲动。这点的确值得反思，外部环境会影响自己的观点和看法，而如果不让这种影响反过来去影响孩子正常发展，是家长必须的修行。

今年工作上似乎没有什么太多进步，自己没有什么印象做了什么比较好的工作。6月份回来养成了慢跑/慢走的习惯，慢跑/慢走的时间会去听书。快到年底的时候把蒋勋说红楼梦听完了，趁着兴头又把家里买的一个红楼梦少儿读本翻了一遍，把其中一些细节或者是漏掉细节补充上了，差不多知道完整的故事了。今年打算再结合原著再听一下蒋勋的解读，蒋勋的解读非常好，会把红楼梦中许多细节以及作者的意图都解释一下，知道作者为什么这么写，这么写都什么好处以及文学上的美感在哪里。我看他还有解读庄子，金刚经等视频，今年有空在一起听听。今年还打算看看庄子和道德经，结合傅佩荣的解读一起来看，古籍非常不好阅读，还是需要注释。另外就是打算在看看/听听几本世界名著，听了几节《静静的顿河》感觉里面人物名字都记不太住，看了CCTV6拍摄的译制片才大约是怎么回事。

去年写了许多todo list, 基本上都没有完成，今年继续去做这些todo list
- MIT OS课程，选修一门编译器课程
- 程序设计语言：kotlin, rust etc.
- Lealone, StarRocks, DuckDB (代码阅读)
- https://cp-algorithms.com/ （学习一些算法技巧等等）
- 数学建模，机器学习等偏数学方面的知识

今年差不多是37-38岁了，越来越感觉到身体健康的重要性，这个应该比所有其他东西都更加重要。不要为了学习去牺牲自己的睡眠时间，如果感觉自己困了就要休息。休息好了就要进行适当的活动，提高自己的心率以及肌肉含量。调整好自己的心态，不要求一时之功，要从长远来看自己的进步。不要想能增加什么，要想能减少什么。
