#+title: 旧金山印象

-----
2014.03.30

去时飞机JAL(Japan AirLines)在东京羽田(Tokyo Haneda)机场转机，在机场等待大约3个小时之后飞到SFO。从北京飞到东京大约4个小时，然后从东京飞到SFO大约8个小时。在飞机上遇到了一个父母是墨西哥然后移民到USA，出生在USA的小伙子Romo，在去东京一段和我坐在一起。他在美国有许多来自世界各地的朋友，所以有空的时候就会到各个地方玩，当地的朋友就会负责接待，因此他也坐过许多国际行航班。根据他的经验，JAL是服务质量比较好的航班，东西好吃，服务周到，位置也宽敞。路上聊了很多(大部分时候是他在说)，说到来这次来中国旅行的各种感受，说到他高中老师兼职adviser for NASA, 说到他父亲如何和他母亲私奔然后移民USA，也教我许多乘坐国际航班的技巧等。

到了Haneda机场之后在附近的免税店突击了部分化妆品。本来想也想买一些当地比较有特色的工艺品比如木屐或是和服，不过好像携带起来不方便，最后就买了几个小挂坠当做纪念。Romo告诉我到达USA之后是当地时间Apr.1 5pm, 当时我惊呆了. 后来他说Mar.31 5pm, 我还是不太相信，因为机票上面写的达到时间就是Mar.30 5pm. Romo怕我到达之后没有和同伴会和会比较无助，所以好心地留给了我联系方式。不过上飞机我看到地图之后才发现，原来从东京飞到USA会穿过国际日期变更线(international data line), 这样日期就要减去1。做我旁边是一个日本女生。两趟飞机都选择的都是close to window而不是close to aisle的，不过幸运的时候旁边都是比较瘦小的乘客，yeah. 

file:images/sfo-haneda-airport.jpg

飞机快飞到SFO的时候，那景色着实漂亮。海岸线一侧是蔚蓝的大海，另一侧则是密密麻麻的建筑(这些建筑都不高大，看上去非常统一), 然后蓝色天空上漂浮着白云，gorgeous. 可惜我没有打开手机拍下来。入境的时候需要填写一张申报单，海关批准最长呆到Sep. 碰巧的是在入境检查的时候我也看到了同伴们。然后我们乘坐机场免费的Train到Rental Cars, 在Budget租了一辆车开到了SunnyVale大约30分钟，然后在一个motel住了下来。

file:images/sfo-airport.jpg

-----
2014.03.31

早上在附近转悠，大部分房子都是如下图。几乎每家都有garden和garage，一般2-3辆车。和赫尔辛基一样，这边车看到行人的话通常都会等待行人先过去然后再走，并且每到有stop的地方，不是慢速行驶而是真的stop下来。地上比较干净。天气温度有点偏凉，凉风习习，空气非常好。

file:images/sfo-house1.jpg file:images/sfo-house2.jpg

会上看到 Peter Zaitsev, Vadim Tkachenko, Monty Widenius.

#note: and Baron Schwartz.(Alex told me I have to pay attention to him because he is smart, philosphyic, mathematician.

-----
2014.04.01

-----
2014.04.02

时差影响是越来越强烈了。早上不到3点就醒了，然后下午吃完饭1点左右就开始犯困。这边VTA light rail非常便宜，从Great America到Downtown Mountain View, Single Pass只需要2美元。

file:images/sfo-golf.jpg

-----
2014.04.03

口语其实没有那么重要，基本上对于所有人来说，只要发音不要差太远，大家都是可以相互理解的，而且大家也不介意你说慢。有待提高的一个是词汇包括短语，另外一个是写作能力。写作能力让我感觉有点头疼，因为我的中文写作能力都好像不怎么样...。写作能力确实可以通过写blog来提高，但是blog内容肯定不应该像我的主页一样写得比较潦草，而是应该包括user case or intention, background, analysis, 然后附上解决办法。

-----
2014.04.04

整个SFO市中心都是建在山上的，所以有很多上下坡。在Bay Bridge一侧有Pier，Pier#39有sealion可以观看，从#39上看也可以看到Golden Gate Bridge. 市中心和类似Mountain View, Sunny Vale这种郊区地方差别很大。市中心灯红酒绿，并且非常拥挤。街上可以看到各种乞讨和卖艺的人。临时住处在King George Hotel, 附近有Union Square. 然后从Powell St做地铁$8.65可以到SFO Airport. 

file:images/sfo-pier39.jpg

-----
2014.04.05

早上在附近转了一下，没啥特别有意思的。不过早上一会功夫看到好几辆fire truck, rescue truck, police car, 不禁对这个城市的安全问题感到深深的担忧(可是好像和我也没有毛线关系)

file:images/sfo-union-square.jpg

做飞机回来的时候我没有忘记拍下俯瞰SFO的景色，[[http://7u2hx7.com1.z0.glb.clouddn.com/%E4%BF%AF%E7%9E%B0SFO.mp4][这里还有一段起飞时候拍摄的视频]]。

file:images/sfo-coast.jpg

飞机航向是先往北极圈飞，然后从俄罗斯到中国。经过北极圈的时候我拍下来了那里的冰雪，甚为壮观。

file:images/sfo-north-polar.jpg

file:images/sfo-north-polar2.jpg
