#+title: 沉默的大多数

但是照我的标准，那不叫说话，而是上着一种话语的捐税。我们听说，在过去的年代里，连一些伟大的人物都“讲过一些违心的话”，这说明征税面非常的宽。因为有征话语捐的事，不管我们讲过什么，都可以不必自责：话是上面让说的嘛。但假如一切话语都是征来的捐税，事情就不很妙。拿这些东西可以干什么？它是话，不是钱，既不能用来修水坝，也不能拿来修电站；只能搁在那里臭掉，供后人耻笑。

我认为，可以在话语的世界里分出两极。一极是圣贤的话语，这些话是自愿的捐献；另一极是沉默者的话语，这些话是强征来的税金。在这两极之间的话，全都暧昧难明：既是捐献，又是税金。在那些说话的人心里都有一个税吏。中国的读书人有很强的社会责任感，就是缴纳税金，做一个好的纳税人——这是难听的说法。好听的说法就是以天下为己任。

谈到思想的乐趣，我就想到了我父亲的遭遇。我父亲是一位哲学教授，在五六十年代从事思维史的研究。在老年时，他告诉我自己一生的学术经历，就如一部恐怖电影。每当他企图立论时，总要在大一统的官方思想体系里找自己的位置，就如一只老母鸡要在一个大搬家的宅院里找地方孵蛋一样。结果他虽然热爱科学而且很努力，在一生中却没有得到思维的乐趣，只收获了无数的恐慌。他一生的探索，只剩下了一些断壁残垣，收到一本名为《逻辑探索》的书里，在他身后出版。众所周知，他那一辈的学人，一辈子能留下一本书就不错。这正是因为在那些年代，有人想把中国人的思想搞得彻底无味。我们这个国家里，只有很少的人觉得思想会有乐趣，却有很多的人感受过思想带来的恐慌，所以现在还有很多人以为，思想的味道就该是这样的。

恕我直言，能够带来思想快乐的东西，只能是人类智慧至高的产物。比这再低一档的东西，只会给人带来痛苦；而这种低档货，就是出于功利的种种想法。

知识虽然可以带来幸福，但假如把它压缩成药丸子灌下去，就丧失了乐趣。当然，如果有人乐意这样来对待自己的孩子，那不是我能管的事，我只是对孩子表示同情而已。

人既然活着，就有权保证他思想的连续性，到死方休。更何况那些高尚和低下完全是以他们自己的立场来度量的，假如我全盘接受，无异于请那些善良的思想母鸡到我脑子里下蛋，而我总不肯相信，自己的脖子上方，原来是长了一座鸡窝。

菲尔丁曾说，既善良又伟大的人很少，甚至是绝无仅有的，所以这种脑移植带给我的不光是善良，还有愚蠢。在此我要很不情愿地用一句功利的说法：在现实世界上，蠢人办不成什么事情。我自己当然希望变得更善良，但这种善良应该是我变得更聪明造成的，而不是相反。更何况

假设我相信上帝（其实我是不信的），并且正在为善恶不分而苦恼，我就会请求上帝让我聪明到足以明辨是非的程度，而绝不会请他让我愚蠢到让人家给我灌输善恶标准的程度。假若上帝要我负起灌输的任务，我就要请求他让我在此项任务和下地狱中作一选择，并且我坚定不移的决心是：选择后者。

我认为，在人类的一切智能活动里，没有比作价值判断更简单的事了。假如你是只公兔子，就有作出价值判断的能力——大灰狼坏，母兔子好；然而兔子就不知道九九表。此种事实说明，一些缺乏其他能力的人，为什么特别热爱价值的领域。

当年冯定老先生就栽在这上面，所以现在的知识分子都学乖了，只管呼吁不管干，并且善用一种无主句：“要如何如何。”此种句式来源于《圣经·创世记》：“上帝说，要有光，于是有了光。”真是气魄宏伟。上帝的句式，首长用用还差不多。咱们用也就是跟着起哄罢了。

还有一支出于狂信的歌曲，歌词如下： 无产阶级文化大革命， 就是好！ 就是好来就是好啊， 就是好！…… 这四个“就是好”，无疑根绝了讲任何道理的可能性。因为狂信，人就不想讲理。我个人以为，无理可讲比尸横遍野更糟；而且，只要到了无理可讲的地步，肯定也要尸横遍野，“文化革命”里就死人不少，还造成了全民知识水平的大倒退。

时隔十年，再来考虑信仰问题，我忽然发现，任何一种信仰，包括我的信仰在内，如果被滥用，都可以成为打人的棍子、迫害别人的工具。渎神是罪名，反民族反传统、目无祖宗都是罪名。只要你能举出一种可以狂信而无丧失理智危险的信仰，无须再说它有其他的好处，我马上就皈依它——这种好处比其他所有好处加起来，都要大得多啊。

我对国学的看法是：这种东西实在厉害。最可怕之处就在那个“国”字。顶着这个字，谁还敢有不同意见？这种套子套上脖子，想把它再扯下来是枉然的；否则也不至于套了好几千年。它的诱人之处也在这个“国”字，抢到这个制高点，就可以压制一切不同意见；所以它对一切想在思想领域里巧取豪夺的不良分子都有莫大的诱惑力。

中国的近现代学者里，做“好消息信使”的人很多，尤其是人文学者。比方说，现在大家发现了中华文化是最好的文化，世界的前途倚赖东方文明。不过也有“坏消息信使”，此人叫做马寅初。五十年代初，马寅初提出了新人口论。当时以为，只要把马老臭批一顿，就可以根绝中国的人口问题，后来才发现，问题不是这么简单。

我上大学时，老师教诲我们说，搞现代史要牢记两个原则，一是治史的原则，二是党性的原则。这就是说，让历史事实按党性的原则来发生。

假如把世界上所有的学者对本学科用途的说明作一比较，就可发现大致可以分为两种：一种说科学可以解决问题，但就如中药铺里的药材可以给人治病一样，首先要知识完备，然后才能按方抓药，治人的病。照这种观点，我们现在所治之学，只是完备药店的药材，对它能治什么病不做保证。另一种说道，本人所治之学对于现在人类所遇到的问题马上就有答案，这就如卖大力丸的，这种丸药百病通治，吃下去有病治病，无病强身。中国的学者素来有卖大力丸的传统，喜欢做妙语以动天听。这就造成了一种气氛，除了大力丸式的学问，旁的都不是学问。在这种压力之下，我们有时也想做几句惊人之语，但又痛感缺少想象力。

我认为，一个人快乐或悲伤，只要不是装出来的，就必有其道理。你可以去分享他的快乐，同情他的悲伤，却不可以命令他怎样怎样，因为这是违背人类的天性的。

科学家维纳认为，人在做两种不同性质的事，一类如棋手，成败由他的最坏状态决定，也就是说，一局里只要犯了错误就全完了。还有一类如发明家，只要有一天状态好，做成了发明，就成功了，在此之前犯多少次糊涂都可以。

“文化革命”里的两派之争，有一个阶段，虽不属论战，但也非常有趣，那就是两派都想证明对方成分不纯或者道德败坏，要么发现对方庇护了大叛徒、走资派，要么逮住他们干了有亏德行的事。在后一个方面，只要有某派的一对青年男女待在一个屋子里，对立面必派出一支精悍队伍埋伏在外面，觉得里面火候差不多了，就踹门进去。我住的地方知识分子成堆，而这些事又都是知识分子所为。从表面上看，双方都是斯文人，其实凶蛮得很。这使我感到，仅用言辞来证明自己比对方道德优越，实在是件不容易的事；因此有时候人们的确很难抑制自己的行动欲望。

前年夏天，我到外地开一个会——在此声明，我很少去开会，这个会议的伙食标准也不高——看到一位男会友穿了一件文化衫，上面用龙飞凤舞的笔迹写着一串英文：OK,Let's pee！总的来说，这个口号让人振奋，因为它带有积极、振奋的语调，这正是我们都想听到的。但是这个pee是什么意思不大明白，我觉得这个字念起来不大对头。回来一查，果不出我所料，是尿尿的意思。搞明白了全句的意思，我就觉得这话不那么激动人心了。众所周知，我们已过了要人催尿的年龄，在小便这件事上无须别人的鼓励。

我提到这件事，不是要讨论如何小便的问题，而是想指出，在做一件事之前，首先要弄明白是在干什么，然后再决定是不是需要积极和振奋。

我举这个例子是想说明：伦理道德的论域也和其他论域一样，你也需要先明白有关事实才能下结论，而并非像某些人想象的那样，只要你是个好人，或者说，站对了立场，一切都可以不言自明。不管你学物理也好，学数学也罢，都得想破了脑袋，才能得到一点成绩；假设有一个领域，你在其中想都不用想就能得到大批的成绩，那倒是很开心的事。不过，假如我有了这样的感觉，一定要先去看看心理医生。

当然，这位老爷子不是在玩深沉，他的意思是说，你要明辨是非，就要把与此有关的一切事都搞清。这是最高的智慧，绝不是最低的一种。这件事绝不轻松，是与非并不是不言自明的。

我觉得西方的智者有一股不管三七二十一，总要把自己往聪明里弄的劲头儿。为了变得聪明，就需要种种知识。不管电磁感应有没有用，我们先知道了再说。换言之，追求智慧与利益无干，这是一种兴趣。现代文明的特快列车竟发轫于一种兴趣，说来叫人不能相信，但恐怕真是这样。

我宁可做个苏格拉底那样的人，自以为一无所知，体会寻求知识的快乐，也不肯做个“智慧满盈”的儒士，忍受这种无所事事的煎熬！

傻大姐是个知识的放大器，学点东西极苦，学成以后极乐。某些国人对待国学的态度与傻大姐相近。说实在的，他们把它放得够大了。拉封丹寓言里，有一则《大山临盆》，内容如下：大山临盆，天为之崩，地为之裂，日月星辰，为之无光。房倒屋坍，烟尘滚滚，天下生灵，死伤无数……最后生下了一只耗子。中国的人文学者弄点学问，就如大山临盆一样壮烈。当然，我说的不只现在，而且有过去，还有未来。

总的来说，哲人王藐视人类，比牢头禁子有过之无不及。主张信任哲人王的人会说：只有藐视人类的人才能给人类带来更大利益。我又要说：只有这种人才能给人类带来最大的祸害。从常理来说，倘若有人把你当做了nothing，你又怎能信任他们？

七〇年，我在云南插队，离边境只有一步之遥，对面就是缅甸，只消步行半天，就可以过去参加缅共游击队。有不少同学已经过去了——我有个同班的女同学就过去了，这对我是个很大的刺激——我也考虑自己要不要过去。过去以后可以解放缅甸的受苦人，然后再去解放三分之二的其他部分；但我又觉得这件事有点不对头。有一夜，我抽了半条春城牌香烟，来考虑要不要过去，最后得出的结论是：不能去。理由是：我不认识这些受苦人，不知道他们在受何种苦，所以就不知道他们是否需要我的解救。尤其重要的是：人家并没有要求我去解放，这样贸然过去，未免自作多情。这样一来，我的理智就战胜了我的感情，没干这件傻事。

其次，蛊惑宣传必定可以给一些人带来快感，纳粹的千年帝国之说，肯定有些德国人爱听；“文革”里跑步进入共产主义之说，又能迎合一部分急功近利的人。当然，这种快感肯定是种虚妄的东西，没有任何现实的基础。这道理很简单，要想获得现实的快乐，总要有物质基础，嘴说是说不出来的：哪怕你想找个干净厕所享受排泄的乐趣，还要付两毛钱呢，都找宣传家去要，他肯定拿不出。最简单的做法是煽动一种仇恨，鼓励大家去仇恨一些人、残害一些人，比如宣扬狭隘的民族情绪，这可以迎合人们野蛮的劣根性。煽动仇恨、杀戮，乃至灭绝外民族，都不要花费什么。煽动家们只能用这种方法给大众提供现实的快乐，因为这是唯一可行的方法——假如有无害的方法，想必他们也会用的。我们应该体谅蛊惑宣传家，他们也是没办法。

白薯干原来是猪的口粮，这种可怜的动物后来就改吃人屙的屎。据我在厕所兼猪圈里的观察，它们一遇到吃薯干屙出的屎，就表现出愤怒之状，这曾使我在出恭时良心大感痛苦——这个话题就说到这里为止。由此可见，我姥姥在村里时，四十户人家、一百多条驴是符合经济规律的。当然，我在村里时，一百多户人家没有驴，也符合经济规律。前者符合省钱的规律，后者符合就业的规律。只有“一百户人家加一百条驴”不符合经济规律，因为没有那么多的事可做。于是，驴子就消失了。

众所周知，我们国家的传统文化是一种人本的文化，但是它和西方近代的人本主义完全不同。在我们的文化里，只认为生命是好的，却没把快乐啦、幸福啦、生存状态之类的事定义在内；故而就认为，只要大家都能活着就好，不管他们活得多么糟糕。由此导致了一种古怪的生存竞争，和风力、水力比赛推动磨盘，和牲口比赛运输——而且是比赛一种负面的能力，比赛谁更不知劳苦，更不贪图安逸！

西方人以为，人的主要情感源于自身，所以就重视解决肉体的痛苦。中国人以为，人的主要情感是亲亲敬长，就不重视这种问题。这两种想法哪种更对？当然是前者。

据说，旧时波兰的农妇在大路上相遇，第一句话总说：圣母玛丽亚是可赞美的！外乡人听了摸不着头脑，就说：是呀，她是可以赞美，你就赞美吧。这就没有理解对方的意思。对方不是想要赞美圣母，而是要表示自己有思想。

海明威在《钟为谁鸣》里说过这个意思：所有的人是一个整体，别人的不幸就是你的不幸。所以，不要以为丧钟是为谁而鸣——它就是为你而鸣。但这个想法我觉得陌生，我就盼着别人倒霉。五十多年前，有个德国的新教牧师说：起初，他们抓共产党员，我不说话，因为我不是工会会员；后来，他们抓犹太人，我不说话，因为我是亚利安人；后来他们抓天主教徒，我不说话，因为我是新教徒，……最后他们来抓我，已经没人能为我说话了。众所周知，这里不是纳粹德国，我也不是新教牧师。所以，这些话我也不想记住。

所谓幽闭类型的小说，有这么个特征：那就是把囚笼和噩梦当做一切来写。或者当媳妇，被人烦；或者当婆婆，去烦人；或者自怨自艾；或者顾影自怜；总之，是在不幸之中品来品去。 这种想法我很难同意。我原是学理科的，学理科的不承认有牢不可破的囚笼，更不信有摆不脱的噩梦；人生唯一的不幸就是自己的无能。举例来说，对数学家来说，只要他能证明费尔马定理，就可以获得全球数学家的崇敬，自己也可以得到极大的快感，问题在于你证不出来。物理学家发明了常温核聚变的方法，也可马上体验幸福的感觉，但你也发明不出来。由此就得出这样的结论，要努力去做事，拼命地想问题，这才是自己的救星。

除了不想懂，还有不敢懂的情形。美国的年轻人常爱用这样一句感叹语：Holy shit！信教的老太太就听不懂。holy这个词常用在宗教方面，就如中国人说：伟大、光荣、正确，shit是屎。连在一起来说，好多人就不敢懂了。

我问一位导演朋友中国为什么没有科幻片，人家就火了。现在我设身处地地替他想想：假设我要搞部科幻片，没有科学知识，我可以到大学里听课。没有想象力，我可以喝上二两，然后面壁枯坐。俗话说得好，牛粪落在田里，大太阳晒了三天，也会发酵、冒泡的。我每天喝二两，坐三个小时，年复一年，我就不信什么都想不出来——最好的科幻本子不也是人想出来的吗？搞到后来，我有了很好的本子，又有投资商肯出钱，至于演员嘛，让他们到大学和科研单位里体验生活，也是很容易办到的——搞到这一步，问题就来了：假设我要搞的是《侏罗纪公园》那样的电影，我怎么跟上面说呢？我这部片子，现实意义在哪里？积极意义又在哪里？为什么我要搞这么一部古怪的电影？最主要的问题是，我这部电影是怎样配合当前形势的？这些问题我一个都答不上来，可答不上来又不行。这样一想，结论就出来了：当初我就不该给自己找这份麻烦。

影视方面的情形就是这样：编导们利用“一切尽在不言中”的文化氛围，确实是大有可为。但我们写稿子的就倒了霉：想要使文字暖昧、可意会不可言传，就只好造些新词、怪词，或者串几句英文。我现在正犯后一种毛病，而且觉得良心平安：英文虽然难懂，但毕竟是种人话，总比编出一种鬼话要强一点吧。前面所写的homo、S/M，都是英文缩写。虽然难懂，但我照用不误。这主要是因为写出的话不够暖昧，就太过直露，层次也太低。这篇短文写完之后，你再来问我这些缩写是什么意思，我就会说：我也不知道，忘掉了啊。我尤其不认识一个英文单词，叫做pervert，刚查了字典马上就忘。我劝大家也像我这样。在没忘掉之前，我知道是指一类人，害怕自己的内心世界，所以鬼鬼祟祟的。这些人用中国话来说，就是有点变态。假如有个pervert站出来说：我就是个pervert，那他就不是个pervert。当且仅当一个人声称：我就不知道pervert是什么时，他才是个pervert。假如我说，我们这里有种pervert的气氛，好多人就是pervert，那我就犯了众怒。假如我说，我们这里没有pervert的气氛，也没有人是pervert，那恰恰说明我正是个pervert。所以，我就什么都不说了。

某一天成为节日或者纪念日都是有原因的，我和别人一样，对此不敢有分毫的不敬。六月一号是小朋友的节日。到了这一天电视台就不需费心安排节目，只管把平日没人看的儿童题材影片弄上去演。有些影片质量很次，有些则是过时的黑白片。大人看了不满意，编导可以说，今天是儿童节，为了孩子，您就忍着点吧。小孩不满意，则可以说，叔叔阿姨们特地给你安排了节目，亲爱的小朋友，你不要给脸不要脸哪。总而言之，各方面都交待得过去，还省了买好节目的钱。但是这样的儿童节目别指望小朋友会爱看。

现在我母亲楼下住了另一位师傅，他在门前堆满了捡来的易拉罐和废纸板，准备去卖钱。他还嫌废纸板不压秤，老在上面浇水。然后那些纸板就发出可怕的味道来，和哈喇的臭咸鱼极为相似。

顺便说一句，英国的牛津城里，所有的旧房子，屋主有翻修内部之权，但外观一毫不准动，所以那座城市保持着优美的旧貌。所有的人文景观属于我们只有一次。假如你把它扒掉了，再重建起来就不是那么回事了。

按我这种说法，工作是人一生的主题。这个想法不是人人都能同意的。我知道在中国，农村的人把生儿育女看做是一生的主题。把儿女养大，自己就死掉，给他们空出地方来——这是很流行的想法。在城市里则另有一种想法，但不知是不是很流行：它把取得社会地位看做一生的主题。站在北京八宝山的骨灰墙前，可以体会到这种想法。我在那里看到一位已故的大叔墓碑上写着：副系主任、支部副书记、副教授、某某教研室副主任，等等。假如能把这些“副”字去掉个把，对这位大叔当然更好一些，但这些“副”字最能证明有这样一种想法。顺便说一句，我到美国的公墓里看过，发现他们的墓碑上只写两件事：一是生卒年月，二是某年至某年服兵役；这就是说，他们以为人的一生只有这两件事值得记述：这位上帝的子民曾经来到尘世，以及这位公民曾去为国尽忠，写别的都是多余的，我觉得这种想法比较质朴……恐怕在一份青年刊物上写这些墓前的景物是太过伤感，还是及早回到正题上来吧。

乌托邦是前人犯下的一个错误。不管哪种乌托邦，总是从一个人的头脑里想象出来的一个人类社会，包括一个虚拟的政治制度、意识形态、生活方式，而非自然形成的人类社会。假如它是本小说，那倒没什么说的。要让后世的人都到其中去生活，就是一种极其猖狂的狂妄。现世独裁者的狂妄无非是自己一颗头脑代天下苍生思想，而乌托邦的缔造者是用自己一次的思想，代替千秋万代后世人的思想，假如不把后世人变得愚蠢，这就无论如何也不可能成功。现代社会的实践证明，不要说至善至美的社会，就是个稍微过得去的社会，也少不了亿万人智力的推动。无论构思乌托邦，还是实现乌托邦，都是一种错误，所以我就不明白它怎能激励人们向上。我们曾经经历过乌托邦鼓舞出的蓬勃朝气，只可惜那是一种特殊的愚蠢而已。
