#+title: 费曼讲物理-入门(Six Easy Pieces)

我们所谓的“理解”某一事物，究竟是什么意思呢？我们可以把组成这个“世界”的这些运动事物的复杂组合，想象成天神们下的一盘巨大的象棋[5]，而我们是这局棋的观众。我们不知道弈棋的规则，允许我们做的就是观看这场棋赛。当然，如果我们看的时间够长，我们终归能看出几条规则来。这些弈棋规则就是我们所说的基础物理学。但是，即使我们知道每一条规则，我们也可能不懂在棋赛中为什么要走具体某一步棋，这仅仅是因为情况太复杂而我们的智力是有限的。如果你会下棋就一定知道，学会所有的规则是容易的，而要选择最佳的走法或理解人家为什么这么走则往往很难。在自然界中也是如此，只是程度更厉害，但我们至少能够发现所有的规则。实际上，今天我们还不知道所有的规则。（比方，偶尔发生的“王车易位”我们就还不懂。）除了我们还不知道全部规则之外，用已知的规则我们确实能解释的事物也是非常有限的，因为几乎所有的情况都极其复杂，我们不能用这些规则领会这盘棋的走法，更不用说预言下一步将发生什么情况了。因此，我们只能满足于弈棋规则这个比较基本的问题。如果我们知道了规则，就认为我们“理解”了世界。

物理学中的情况正是这样。在一段长时间里，我们有一条总的说来工作得很好的规则，尽管我们不清楚它的细节；然后在某个时候我们可能发现一条新规则。从基础物理的角度来看，最有趣的现象当然是那些新情况，那些老规则不适用的情况，而不是老规则适用的情况！这是我们发现新规则的途径。

历史上的一些进行统一的例子如下。首先，是热学和力学的统一。当原子在运动时，运动越剧烈，系统包含的热量就越多，因此，热和所有的温度效应可以用力学定律来说明。另一次极大规模的统一是发现了电、磁和光之间的关系，弄清楚了它们是同一事物即我们今天所称的电磁场的不同侧面。另一次统一是化学现象（各种物质的各种性质）和原子的行为的统一，这发生在量子化学中。

这里我们关心的是对自然的描述。按照原子论的观点，气体和实际上一切物质，都是大量运动着的粒子。这样，我们站在海边看见的许多事物立即就可以联系起来。首先是压强，它来自原子与器壁或别的什么东西的碰撞。原子的移动如果平均而言沿着一个方向运动，那就是风；而无规的内部运动则是热。过多的粒子积聚在一起使密度超过平均值，它们将成堆的粒子不断向外散开，这就生成了波，这种过剩密度的波就是声音。能够理解这么多的事物，这是一个重大的成就。

电力比万有引力到底强多少呢？考虑两粒沙子，大小为1毫米，距离30米。如果它们之间的力不被抵消，也就是说，如果所有的电荷都互相吸引而不是同号电荷相斥，因此没有抵消，那么，它们之间的力有多大呢？有300万吨！你瞧，正电荷或负电荷的数目只要超过或不足很少一点点，就足以产生可观的电效应了。当然，这就是你（用非电学方法）看不出带电物体和不带电物体的差别的原因——涉及的粒子数目如此之少，它们很难对一个物体的重量或大小造成什么差别。

如果频率再高，我们就得到X射线。X射线不是别的，只不过是频率很高的光。频率再高，就得到γ射线。X射线和γ射线这两个名称，几乎是当作同义语来使用。通常把从原子核发出的电磁波射线叫做γ射线，而从原子发出的高能电磁波则叫做X射线，但是不论它们起源在哪里，当它们的频率相同时，它们在物理上是无法分别的。频率更高的波，比方说1024周/秒，我们可以人工生成，比方用我们加州理工学院的同步加速器。在宇宙线中，我们可以发现频率极高的波，其振荡频率甚至更快1000倍。这些波我们还不能控制。 表

是什么原因使电子不掉进去呢？就是上面这条定理：如果电子都掉进原子核，我们就知道它们的精确位置，于是不确定原理就要求它们具有一个非常大（但是不确定）的动量，也就是一个很大的动能。有了这个能量，电子就将摆脱原子核。于是它们达成一个妥协：电子为这种不确定性给自己留下一点空间，同时按照这条定则以最小的运动量振动着。（记得我们前面说过，当一块晶体冷却到绝对零度，它的原子并不停止运动，仍然在振动。为什么？因为如果原子停止振动，我们就会知道它们的精确位置同时知道它们的运动速度为零，而这是违反不确定原理的。我们不能同时知道它们的位置和它们运动的速度，因此它们必须在那里不断地扭动。）

结果之一是，我们习惯于视为波的事物也具有粒子的习性，而粒子也具有波的习性。事实上万事万物的行为都是这样，不存在波和粒子的区分。因此量子力学把场及其波的概念和粒子的概念统一起来，成为一个统一体。的确，当频率低时，现象的场的一面更明显，或者是一种更有用的通过日常经验对现象的近似描述。但是随着频率增高，对于我们通常用来进行测量的仪器，现象的粒子的一面就变得更明显。实际上，虽然我们提到过许多频率，但是迄今并没有探测过任何直接涉及1012周/秒以上频率的现象。我们只是根据一条假定量子力学的波粒二象性成立的定则，从粒子的能量推出更高的频率的存在。

不止如此，量子电动力学这个伟大的理论，还预言了许多新的事实。首先，它说明了甚高能光子、γ射线等的性质。它还有另一个重要的预言：在电子之外，还应当存在另外一个质量相同、但是电荷反号的粒子，叫做正电子，这两种电子碰到一起时，会彼此湮没而发射光或γ射线。（归根结底，光和γ射线是一回事，只是频率不同。）这个事实的推广，即每一种粒子都有一种反粒子，也被发现是正确的。在电子的场合，反粒子有另一个名称——正电子，但是对别的粒子，其反粒子就叫做反什么什么子，像反质子、反中子。在量子电动力学中，引进了两个数值，认为世界上大部分其他数值都可以从这两个数值推导出来。这两个基本数值就是电子的质量和电子的电荷。实际上，事情并非完全如此，因为化学中还有一套数据，告诉我们不同的原子核有多重。

这里我们看到一系列的分子，它们在由一串不多几步构成的循环中从一种变成另一种。这个循环叫做克雷布斯循环[10]或呼吸循环。从分子里发生的变化来看，每种化合物和每步反应都不复杂，但是这些反应在实验室里却相对地难以完成——这是生物化学中一个非常重要的发现。如果我们有一种物质和另一种很相似的物质，前者并不顺当地转变成后者，因为二者之间通常隔着一个能量障碍或“位垒”。

可是，如果真的能够把分子拿在手中，把它的原子扒拉来扒拉去以使得出现一个缺口，让新原子进来，然后再把缺口很快堵上，那么我们就找到了另一个办法，即绕过小山，这就不需要额外的能量，而反应就容易进行。在细胞里实际存在一种很大的分子，比我们刚刚描述过其变化的分子大得多，这种大分子以某种复杂的方式使较小的分子处于正好的状态，使得反应容易发生。这些大而复杂的分子叫做酶。（

什么是“绿色标志”呢？它们是不同的同位素。我们还记得，原子的化学性质是由电子的数目决定的，而不是由原子核的质量决定的。但是，比方说碳，碳原子核中，和一切碳核都有的6个质子在一起，可以有6个中子或者7个中子。在化学上，两种原子C12和C13是相同的，但是它们的质量不同，核的性质不同，因此是可以辨别的。利用这些不同质量的同位素，或甚至利用像C14这样的放射性同位素（它提供了更灵敏的追踪微量物质的手段），就能够追踪反应的进程。

接下来的问题是，精确地说，A、B、C、D的顺序如何决定蛋白质中氨基酸的排列？这是今天生物学中还没有解决的中心问题。不过，已有了一些初步线索或零碎的信息：在细胞中有一些微小粒子，叫做微粒体，现在知道它就是蛋白质生成的地方。但是微粒体不在细胞核内，而DNA及其指令却在细胞核里。这似乎是个麻烦。然而，现在也知道，有小的分子断片从DNA中放出，它没有携带全部信息的巨大DNA分子本身那么长，而像是它的一小段。它叫做RNA，但名字无关紧要。它是DNA的一种拷贝——一份缩微的拷贝。RNA以某种方式携带着生成哪一种蛋白质的信息去到微粒体中，这我们已经知道了。当它到达那里后，微粒体就合成出蛋白质，这我们也知道了。但是，氨基酸是怎样进来以及它们是怎样根据RNA上的密码而排列成某种蛋白质的，其细节我们仍然还不知道。我们不知道怎样去解读密码。比方说，如果我们知道一段序列ABCCA，我们也无法告诉你要生成的是哪种蛋白质。

给人印象最深的发现之一是使星星不断发热发光的能量的来源。它的发现者之一，在认识到恒星中必须进行着核反应才能发光之后，有一天晚上和他的女友出来散步。女友对他说：“看哪，这些闪耀的星星多美啊！”他回答说：“是啊，此时此刻，我是世界上惟一知道它们为什么发光的人。”女友只对他一笑。她并不对同当时是世界上惟一知道星星为什么会发光的人出来散步这一点有什么特别深的印象。是的，不为人理解是可悲的，但是这个世界就是这样。

构成我们的身体的材料，是在某个星球上一次“烹制”好后喷射出来的。我们是怎么知道的呢？因为有一个线索。不同的同位素的比例——C12占多少，C13占多少，等等，是化学反应改变不了的，因为化学反应对两种同位素是相同的。它们的比例完全是核反应的结果。通过考察这些熄灭了、冷却了的炉灰（我们自己就是这种产物）中各种同位素的比例，我们就能够发现制造组成我们身体的材料的火炉是什么样子。这个火炉很像恒星，因此很可能我们的元素是在恒星中制造并且在爆炸中喷射出来的，我们管这种爆炸叫新星和超新星。

在物理学中目前不研究历史问题。我们没有这样的问题：“这些物理学定律是怎样变成这个样子的？”在目前，我们不想象，物理学定律会以某种方式随时间变化，物理学定律在过去和现在有什么不同。当然也不排除有这个可能，一旦发现物理学定律真的随时间变化，物理学的历史问题就将与宇宙的历史的其他问题交织在一起，而物理学家就将谈论天文学家、地质学家和生物学家同样的问题。

原来，用温度计你可以发现，弹簧或杠杆事实上比以前更热了，这确实表明动能有一定数量的增加。我们把这种形式的能量叫做热能，不过我们知道其实它并不是一种新形式，它就是动能——内部运动的动能。（我们在大尺度上对物质所做的一切实验都有一个困难，即不能真正演示能量守恒，不能实际做出可逆机，因为我们每次使一大块材料运动，原子都不会绝对不受扰动，因此总会有一定数量的无规运动进入原子系统。我们看不见它，但是我们可以用温度计等测出它。）

最后，我们说一说今天我们可以从哪里获得能量供应的问题。我们的能量来源是太阳、雨水、煤、铀和氢。雨水是太阳造成的，煤也是，因此所有这些都来自太阳。虽然能量是守恒的，但是大自然似乎对节约能量并不感兴趣；她从太阳释放出大量的能量，但是其中只有二十亿分之一落到地球上。大自然有能量守恒，但是并不真正在乎它；她向四面八方散发着巨大数量的能量。我们已经从铀获得了能量；我们也可以从氢得到能量，不过现在还只是在爆炸和危险的条件下。如果它可以在热核反应中受到控制，那么可以证明，每秒从大约10升水中得到的能量就等于整个美国的发电功率，也就是说，每分钟用600升水，就有了足够的燃料来供应今天美国所用的全部电能！因此，该由物理学家想办法，把我们从对能量的需要中解放出来。这是可以做到的。

于是开普勒的三条定律是： 1.每个行星沿一条椭圆轨道绕太阳运行，太阳是椭圆的一个焦点。 2.从太阳到行星的径矢在相等的时间间隔里扫过相等的面积。 3.任何两个行星的周期的平方正比于它们各自的轨道的半长轴的立方：T～a3/2。
