#+title: 非对称风险(Skin in The Game)


https://book.douban.com/subject/30417612/


“风险共担”有助于解决类似“黑天鹅”的突发事件以及其他层面的（包括个人或者集体所遭遇到的）不确定性事件。那些在“风险共担”中存活下来的个体或者集体，证明了他们抵御“黑天鹅”事件的韧性，我们如果人为地排除“风险共担”，就会破坏这种筛选机制。如果没有“风险共担”，我们就无法理解“造物主”通过“时间”显示出来的伟大智慧（后面将有一章专门讨论涉及“时间”的“林迪效应”，其中包括了两个方面的内容：第一，时间筛掉了脆弱的个体，留下了强韧的个体；第二，那些强韧个体的生命由此得以延长）。其实很多思想也是实践的产物，所以拥有这些思想的人必须懂得亲身参与“风险共担”的道理。 时间是伟大的智者，它通过“风险共担”塑造了理性——这是一种任凭深思熟虑后仍然无懈可击的理性。设想这样一个场景：对于法国某规划部门的公职人员（他因受过太多的教育而变得天真，但每天准时上班）来说，某项惯例可能看起来并不合理，但它已经运行了很长时间。也许他会问：这是否是理性的？尽管他心里有这样的疑问，但是他并没有充足的理由去推翻这项惯例。相对而言，我们更容易知道哪些事情是明显非理性的——首先是那些威胁集体生存的事情，其次是威胁个体生存的事情。从统计学角度来看，如果某自然规律符合统计学意义上的显著性特征，那么违背这个自然规律就是明显不理性的（除了由杀虫剂公司赞助的反对者以外，其他人都对此深信不疑）。我们的惯性思维使我们相信，那些有效的做法不可能是不合理的。天哪！这些年来我遇到的每一个最终投资失败的人都会被这个思维定式所害，他们无法理解为什么某些愚蠢的做法（可能在相当长的一段时间内）不仅有效，而且能让你赚到钱。他们坚信，一个做法只要有效，就不可能是愚蠢的。



书评家们读一遍书之后就发表评论是不恰当的，熟悉我之前的作品《反脆弱》的读者都知道其中的“非线性凸性效应”，把一本书读两遍的收获要远大于读两本不同的书，这就是“非线性凸性效应”（前提当然是这本书的内容是有深度的）。“凸性”一词在闪米特语中是“mishnah”，这个词在希伯来语有文字记载之前，口口相传的意思就是“重复”。犹太经典著作Midrash（《米德拉什》），该词本身就有“反复研磨”和“留下印记”的意思。与之对应的是，古代阿拉伯人的孩童学校“马德拉撒”（madrassa），这个词也有类似的含义。 一本书应该按照读者的需求来组织编写，同时也应该遵循作者的意图（即作者本人希望把问题解释到什么程度），而不是为书评家提供谋生的手段。书评家是很糟糕的中间人，在优步公司掀起的去中介化浪潮中，书评家这一职业很快就会消失得无影无踪。



对无节制的全球化以及中央集权的多民族大国，我始终是持怀疑态度的，而这背后的原因其实就是对扩大规模后原有的规律是否适用的一种担心。物理学家、复杂系统研究者亚尼尔·班杨（Yaneer Bar-Yam）曾经做过一个非常令人信服的比喻，“扎紧篱笆才有好邻居”。然而近东地区的政府和政策制定者都没有意识到这一点。“适用规模”很重要！我会不遗余力地大声重复这一点，直到我把嗓子喊哑了为止。强行把什叶派、基督徒以及逊尼派拉在一起，让他们为了人类的团结，以兄弟之名手挽手，绕着篝火齐唱赞歌《昆巴亚》（Kumbaya），这种做法注定是失败的。干涉主义者至今还没有意识到一个国家不可能按照他们设想中那份完美的、“理应如此”的蓝图来构建。干涉主义者最愚蠢之处就是他们总是谴责别人秉持“教派”观念，而不能意识到这其实是人们固有的“部落”归属感。将不同的部落分开来给予一定的自治权（奥斯曼土耳其人的做法），不仅会使国家治理变得容易，而且会使部落之间的关系变得好起来。黎凡特曾经并且正在遭受的厄运，完全是由那些从不亲身参与当地“风险共担”的西方阿拉伯问题专家（目前主要是盎格鲁–撒克逊人）造成的。他们似乎背负着某种邪恶的使命，总想彻底破坏当地固有的文化和语言，将黎凡特特有的地中海文明的历史渊源连根拔掉。



杰夫·格拉汉（Geoff Graham）和文森·格拉汉（Vince Graham）兄弟俩的一段俏皮话，道出了不区分受众规模的政治普世主义的可笑之处： 在联邦层面上，我是一个（推崇个人权利的）自由主义者；在州层面上，我是一个（主张加强联邦的）共和党人；在地方县域层面，我是一个（主张各州权力的）民主党人；在家族和朋友层面上，我是一个（提倡个人服从集体的）社会主义者。 如果上面这段文字还不足以让你明白乱贴“左派”和“右派”标签有多么愚蠢，那么你真是无药可救了。



参加波士顿烧烤活动的前一天，我在纽约街头闲逛。顺道拜访了我的老朋友拉尔夫·杜阿迪，我一直劝他不要变成工作狂（因为，沉溺于抽象思维不仅会让人头脑变得迟钝，而且会让人举止失态、相貌丑陋）。当天一位名叫塞尔·格兰的法国物理学家恰好也到访他的办公室，我们俩还一起品尝了拉尔夫味道不佳的浓缩咖啡。格兰率先把重整化的方法应用到社会和政治科学领域。我听说他的名字已经很久了，因为我很早以前买过一本他写的书，但是这本书一直躺在地下室里，连包装都没有被打开。他向我展示了他的研究成果，那是一个计算机选择模型，该模型显示只要少数派达到某一特定的水平，那么他们的选择就会成为压倒性的全体选择。



所以在这一地区，伊斯兰教凭借自身更强的顽固性取代了基督教。其实基督教当年在罗马帝国的传播，在很大程度上也归因于早期基督徒的顽固性。他们对其他人信仰的宗教有一种盲目的不妥协和不包容，表现为无条件地、蛮横无理地劝化其他人改宗。罗马的万神教徒起初并不排斥基督徒，因为罗马人的传统就是与帝国的全体成员一起供奉各自的神。但是后来罗马人发现情况不对，基督徒们完全是另起炉灶，自己搞一套独立的宗教，他们既不接受帝国万神殿里其他民族的神，也不把自己信奉的神像请进万神殿。罗马人暗忖：“难道我们的神不如你们的神吗？”其实，早期罗马帝国针对基督徒采取的宗教迫害主要起因是基督徒不能容忍罗马万神教的其他神，而不是因为万神教不容忍基督教。但是我们今天读到的历史绝大多数讲的都是基督徒无辜受迫害的故事，相反的记载却很少见。毕竟我们读的历史书是基督教徒，而不是罗马万神教徒写的。



罗马人当初是怎样看待基督教崛起的呢？对此，我们知之甚少，因为我们今天读到的记载主要都是圣徒传记，里面包含了大量殉道者的故事。比如殉道的圣徒凯瑟琳直到被押上断头台前一刻也不忘劝她的狱友改宗，另有一种说法是历史上或许根本就没有圣徒凯瑟琳这个人。但是迦太基主教圣徒西普里安（Cyprian）被送上断头台的故事确实是真实存在的。记述基督教殉道者和圣徒的英勇故事不胜枚举，但是万神教方面的英雄人物却鲜有记载，即使是那些早期遵奉诺斯底教派传统的基督徒事迹也未见记载。叛教者尤里安曾经想要恢复古代的万神教，他的处境就像是在新泽西州南部叫卖法国大餐一样——无人问津。这就像是在水下拿住气球一样困难，但是出现这种情况并不是因为万神教徒（或称异教徒）在智力上有缺陷，恰恰相反，我倒是认为一个人越能够宽容地对待异教，越说明他头脑聪明，处理复杂、模糊和抽象事务的能力越高。而信奉纯粹一神论宗教的人，如基督教新教、萨拉菲（salafi）派的伊斯兰教徒和宗教激进主义无神论者，往往智力平庸，无法处理模糊概念。



有时候“一根筋”的思维方式可以帮助我们揭开问题的真相，澄清许多误解。比如，一本书怎么就变成了禁书？可以肯定的是某些书被禁，并非因为它们冒犯了普罗大众，因为绝大多数人要么是胆小懦弱的，要么是被动承受的，要么是满不在乎的，即便有些人很在意，感觉自己被某本书冒犯了，但他们也不至于要求把相关书籍直接封禁。我们发现禁止某些书的传播或者将某些人列入黑名单，其实只需要少数几个热情高涨的积极分子就行了。伟大的哲学家、逻辑学家伯特兰·罗素，曾经因为一位愤怒而固执的母亲给校方写信而丢掉了其在纽约城市大学的工作，这位母亲在信中说，她不希望自己的女儿与行为不检点、思想不规矩的人同处一间教室。 热情高涨的少数派能推动各种禁令，美国历史上那次声名狼藉的禁酒令就是这么来的，其结果呢？合法的酒类专营许可被注销以后，黑社会顺利地接管了酒精买卖。 我们由此可以推断当今社会的道德并非是由大多数人的共识演变而来的，而是由社会中那些最顽固的少数派把他们所推崇的道德强加给了社会，又因为少数派的极端不容忍，最终成了全社会普遍接受的美德。同样，公民权利也是通过这样的途径争取来的。



所以，道德标准一旦被建立起来，只需要满足几个条件就足以在全社会维护整个道德体系：（1）极小部分人对道德禁止的事情极为厌恶，对道德提倡的事情极为热衷；（2）这一小部分约占总人口的3%~4%；（3）这部分人永不妥协，极为固执；（4）这部分人平均分布在社会的各个阶层和国家的各个地区。在揭示这个规律的同时，我也告诉了你一个坏消息，那就是我们绝大多数人并不热衷于捍卫道德体系，我们并不会自觉地、自发地和自愿地想成为更崇高、更美好、衣着更优雅和口气更清新的人，真相是我们只想摆脱顽固少数派不停的骚扰，于是不得不按照他们定的规矩行事。



民主，字面上的定义是按多数人的意见做决定，但它可以容忍敌人的存在吗？或许下面这个问题更有助于你的思考：“如果有一个政党在其章程里明确提出要禁止言论自由，那你同意剥夺该政党的言论自由吗？”再换一个问题：“如果我们建设这个社会的初衷是保持宽容，那么我们是否应该对威胁这种初衷的事情保持宽容呢？”这实际上涉及逻辑大师库尔特·哥德尔在参加公民入籍考试时发现的美国《宪法》中的存在的逻辑悖论。传说哥德尔当时就这一问题与主持宣誓仪式的法官展开辩论，最终还是一起等着宣誓成为美国公民的爱因斯坦把他从辩论中解救了出来。科学哲学家卡尔·波普也在民主政治体系所依赖的逻辑中发现了这个悖论。



现在我们来说一下市场。市场不是全体参与者的总和，市场价格变动仅仅是由其中最积极的买方和卖方驱动的。是的，就是由他们这些人决定的。在这个问题上，似乎只有当过交易员的人才能理解，为什么仅仅因为卖家的某个行为，市场价格就能瞬间下跌10%。事实上，只要存在这样一位固执的卖家，这种情况就可能发生，而且市场的反应程度与其所受刺激的猛烈程度是不成比例的。全球股市的总市值大约是30万亿美元，但是在2008年，仅仅500亿美元的交易，还不到总市值的2‰，就导致全球股票市值下跌了10%，由此给投资人造成了3万亿美元的损失。我在《反脆弱》一书中曾经提到过这个例子，当时法国兴业银行发现了自己雇用的一个“流氓”交易员未经授权就做了一笔秘密交易，法国兴业银行想撤回这笔交易，由此激活了相应的抛出指令。为什么市场反应会如此剧烈？因为那笔卖出指令是单向的、不可撤销的，法国兴业银行的管理层不顾一切地要抛出，没有任何办法劝他们住手。我自己总结了一句谚语： 市场像一个巨大的电影院，但出口很窄。 鉴别一个笨蛋最好的办法，就是观察他到底是关注电影院的大小还是出口处的大小。只要有人喊一声“着火了”，恐慌性撤离就会在瞬间演变成拥堵，因为人们都想逃出去而不想被困在里面。这其实跟恐慌性抛售是一样的道理。



科学探索过程中也有类似的案例。就像我们刚才提到的卡尔·波普的思想背后就是少数派主导规则。但是波普实在太严肃了，所以我们把他留到以后探讨，先来看科学界的轻松达人——理查德·费曼（Richard Feynman），他是那个时代一个剑走偏锋的科学家。他在《你干吗在乎别人怎么想》一书中用诙谐调侃的口吻写了很多有关科学的奇闻轶事。从他的叙述来看，科学探索其实是一个由少数派主导的过程。科学并不是科学家思想的总和，而是如市场一样，充满了固执的偏见，一旦某领域的真相被揭示以后，我们才突然发现我们以前掌握的都是错的。如果科学探索奉行多数人共识的原则，我们现在就可能还在中世纪，爱因斯坦可能终其一生都是一个“有爱好，没成果”的专利局职员。



为什么这些云游僧侣遭到了禁止？其原因很简单，因为他们太自由了。他们的财务既自由又安全，但这并不是因为他们省吃俭用，而是因为他们缺少需求。具有讽刺意味的是，他们仅靠乞讨就能赚到钱，我们却要从社会最底层开始打拼积累——他们比我们自由多了。 如果你负责运营一个有组织的教会，你最不希望看到的就是僧侣拥有完全的自由；如果你经营的是一家公司，那么完全自由的员工对于你来说绝对是噩梦。因此，本章我们来谈谈员工自由的问题，以及公司的组织特性。



其实每个机构都希望其成员失去一部分自由，只有这样才能把人“组织”起来。那么你用什么办法才能把人“组织”起来呢？第一，以培训的名义对他们进行心理操纵。第二，把他们拧在一起，让他们在某种程度上参与“风险共担”，和公司共担风险；让他们明白如果不服从组织权威，就会失去某些重要的东西——你现在明白了吧？为什么你很难控制那些以乞讨为生的云游僧侣，因为他们轻慢地对待任何物质财富，以至你很难让他们失去什么。在黑手党的组织体系中，事情就变得简单了，如果一个小头目怀疑某马仔（正式受戒入道的成员）不忠诚，就可以把他“做掉”，让他在汽车后备厢里安静一段时间。然后，大头目会出席他的葬礼，这样做的目的是让其他马仔更忠诚



你会发现凡是接受正式雇用合同的员工，都喜欢固定工作带来的稳定收入，他们喜欢在月底最后一天看到桌子上那个特殊的信封。没有了工资，他们就像是断奶的婴儿。你现在意识到了，如果鲍勃是一名正式员工而不是看起来更便宜的承包商，你就不会遇到这些麻烦了。 但是正式员工成本很高，即使在没有活儿的时候，你也得给他们付工资，这样你就失去了灵活性。但他们毕竟是你的员工，他们的成本虽然高，但是喜欢固定工资的人通常是安于现状的人，他们不会是鲍勃那样的机会主义者，因此不会发生上述情况，他们不会让你失望。 正式员工不会临阵逃脱，是因为这份工作是他们亲身参与的“风险共担”，事关他们的切身利益，他们必须共担风险，而甩手不干的风险大到可以震慑他们灭掉这个念头。他们会因不可靠的行为，比如不能按时上班而受到惩罚。实际上，你给他们创造的工作使他们对你产生了依赖性，这种依赖性使得他们变得可靠，你支付的工资正是在购买这种可靠性。 可靠性是许多交易背后的推动力量。在乡间买一个别墅的性价比远不如去宾馆租房间或上网租民居，但是仍然有人会去买别墅，他们希望无论什么时候——比如自己一时兴起，都有房子可以用来度假。一位交易员曾经说过三个“不该买”原则（这三种东西因性价比差，所以只要能租到就尽量不要买），它们分别是海上漂的、天上飞的，还有床上躺的。但是仍然有很多有钱人买了游轮和飞机之后，最终和自己的飞机游轮一起被那最后一个“不该买”的控制起来了。



我记得曾经有人问我为什么上班不系领带，在那个年代，这种行为相当于在第五大道上裸奔。“为了我的傲慢，为了我的审美，为了我的方便。”我通常都是这样回答的（但他们通常只记住了我的傲慢）。如果你能给公司带来盈利，那么，你无论对老板多么无礼都可以。他们都会忍气吞声，因为他们需要你，他们自己也害怕失业。冒险者在社交方面的行为是不可预测的。自由常与冒险相关，你今天的自由来自你昨天承担的风险，而这种自由可能把你带向明天的风险。如果你承担了风险，你就会感受到你所经历的一切都是历史的一部分。冒险者甘愿去过冒险的生活，是因为他们天生就是野生动物。 说完了着装，我们再来说说谈吐，交易员要从各方面使自己看起来和那些不敢承担风险、没有自由的平庸雇员有所不同。我当交易员那会儿，除了黑帮成员和那些想要表明自己不是奴隶的人以外，没有人会在公众场合说脏话，唯有交易员像粗鲁的水手一样满嘴脏话。我一直保持着有策略性地说脏话的习惯，我只在写作和家庭生活之外的场合使用脏话。那些在社交网站（比如推特）上使用脏话的人，正在用昂贵的方式（承担社会压力）传达这样一个信号：他们是自由的。而且，具有讽刺意味的是，他们往往也很有能力。几乎没有什么低风险策略能够使你向社会公众展现你的能力。所以在今天的社会，说脏话是地位的象征，莫斯科的商业寡头们会在正式的社交场合，特意穿蓝色牛仔裤来彰显他们的权力和地位。即使银行也会在安排客户参观公司时，带他们参观交易员的工作大厅，就像参观动物园一样。交易员一边拿着电话对经纪人破口大骂，一边撮合成交的场景也是一道风景。



普京的态度使他的追随者痴迷，尤其是黎凡特地区的基督徒——这一地区的东正教徒更是欢欣鼓舞，人们仍然记得当初正是俄国的叶卡捷琳娜大帝派舰队来此巡弋，迫使奥斯曼帝国当局允许贝鲁特的圣乔治大教堂在沉寂多年以后再次鸣响了钟声。叶卡捷琳娜大帝被认为是“最后一位有胆识的沙皇”，她从奥斯曼帝国手里夺取了克里米亚，而在那之前，逊尼派奥斯曼人严禁他们统治下的沿海地区的基督徒在教堂鸣钟，只有一些遥不可及的偏远山区的基督徒能享有这种自由。1917年，这些基督徒失去了沙皇的有力保护，现在他们希望拜占庭帝国能够在百年以后的今天卷土重来。



到目前为止，我们可以把历史上的独身主义视为个人为了避免社会对其家人实施惩罚而采取的预防措施。这从一个方面证实了自古就有惩罚家人的现象存在。这种惩罚不会明说或者明文规定，但一定普遍存在，如果你惹毛了一家大型农药企业，它不会明确威胁你说要惩罚你的家人，但是事实上它可能就这样做了，你可能会发现你家圣诞树下的礼物少了，冰箱里的食物质量变差了。



我们进一步做出总结： 要免于道德困境，你就不该交朋友。 这就是为什么克里昂在其执政期间，宣布与他所有的朋友断绝关系。



我们阻止自杀式袭击者的唯一办法，就是让他们知道引爆自己身上的炸弹对于他们来说并不是最坏的结果，更不是最终的结果。他们的家人还有他们所爱的人都会因此承受沉重的经济负担，就像德国人还要为祖辈承担战争罪责那样。如此，他们的所作所为就有了需要承担的后果。罚金的数量和执行方式要事先制定合理的方案以便真正起到震慑作用，绝对不能让他们的家人把这种行为看成一种英雄行为或者光荣的殉道行为。



否则，你就会像下一章我们将要讨论的人一样，读书虽多，却不求于心，以至知识沦为他们炫耀自己的工具。这几乎已经成了现代世界的通病，那些读书万卷、倚马万言的人，正在帮助企业做生意上的重大决定。这些人在迈出公司大门接触第一线实际情况之前，不应该做出任何决策。



我得创造一个新词“白知”（intellectual yet idiot），它特指那些高智商的聪明的白痴。“白知”是现代化的产物，他们从20世纪中期就开始扩散，如今已是遍地开花，我们现在的生活正由这群没有参加过“风险共担”的人控制着。在绝大多数国家，政府在整体经济中的影响（占国内生产总值百分比）与一个世纪之前相比，要大5~10倍。“白知”看似无处不在，但其实在绝对数量上仍是一小部分人，他们常见于专门的机构、智库、媒体以及大学的社会科学系。他们大部分人都有体面的工作，而招聘“白知”的岗位并不多，这就是为什么他们数量少却影响大。 “白知”总是将那些自己无法理解的行为定义为反常、特例、病态和非理性，却没有意识到可能是自己的理解力有限。他们认为人们的行为应该遵循利益最大化原则，而他们能够知道别人最大的利益是什么，尤其是那些乡下的农民和发不出清脆元音并支持英国脱欧的底层人士。当平民按照自己认为合理而“白知”却不能理解的方式做事情的时候，“白知”就会说他们“没有教养”。我们考虑政治问题时常侧重普遍参与性，而“白知”则只有两个不同的概念，当公众投票结果符合他们的期望时，他们称之为“民主”，当投票结果与自己意见相左时，他们称之为“民粹”。在事关国家发展和公众福祉的投票上，有钱的人希望一美元算一票；普通人希望一个人算一票；孟山都公司希望一个说客算一票；而“白知”则希望一个常春藤学位算一票，或者外国著名学府的博士学位也算一票，因为这些头衔在他们的俱乐部里很重要。




人们憎恶的并不是那些自己承担风险的富人，他们真正憎恶的是那些身处高位却不承担风险的人，这些人并没有用身家性命参与“风险共担”，他们也不可能从他们目前的地位和财富水平上摔下来，更不可能穷困潦倒到排队领救济的地步。同样的道理，那些批评唐纳德·特朗普（当时还是总统候选人）的人从某种程度上帮助了他，因为这些诋毁他曾经经商失败的人不仅误解了伤疤的价值（伤疤标志着他曾经亲自承担风险），而且他们也没有意识到，宣扬特朗普公司破产和他个人损失近10亿美元这件事，反而消除了人们可能对他产生的憎恶（第二种不平等）。损失10亿美元成了值得尊敬的事，因为他输掉的是他自己的钱。 那些不参加“风险共担”也不承担公司经营风险的高管，只会享受公司业绩增长带来的好处，而不会承担公司业绩下滑的损失（就是那种总能在各种会议上侃侃而谈的高管）。他们根据某些指标获得报酬，但这些指标并不真实反映公司运营的健康情况，这样他们就可以操纵指标、掩盖风险、获得报酬，然后退休（或者去其他公司继续做同样的事）。他们可以将离职后公司暴露的风险，轻易地推卸给继任者。



在接下来的分析中，我们将重新定义不平等，将这一概念置于更加严格的基础之上，但是我们先要介绍两种方法的差异：静态和动态，因为“风险共担”可以将一种不平等转化为另一种不平等。 还请记住以下两句话： 真正的平等是概率上的平等。 只有“风险共担”能防止系统崩溃。 静态和动态 很明显，经济学家们，尤其是那些从未亲身涉险的经济学家的通病就是：他们无法理解动态变化的事物，看不到动态事物和静态事物之间有着不同的属性。这就是为什么他们不熟悉复杂系统和胖尾现象（我们稍后会详细解释）。他们也缺乏理解更艰深的概率理论所需的数学基础和本能直觉。他们对遍历性完全无知（稍后几段我们将开始介绍遍历性），而在我看来，是否理解遍历性是区分一个真正了解世界的学者和一个只会写八股文式论文学者的最好标准。 请先看几个定义： 静态的不平等只是一张瞬间抓拍不平等现象的照片，它不能告诉你在今后漫长的历程中还会发生什么。 请考虑以下事实：10%的美国人在其有生之年将有机会挤进前1%的收入排行榜，并待上1年；超过一半的美国人将挤入前10%，并待上一年。[插图]很显然，美国的数据和更加静态（但名义上更加平等）的欧洲是不同的。例如，美国最富有的500个人或家族，只有30年历史；但在法国的名单中，60%的富豪是靠继承得来的财富；1/3最富有的欧洲人，在几个世纪之前就已经属于最富有的家族了；而佛罗伦萨的情况更为严重，几大家族控制了那里的财富已达5个世纪之久。 动态的（遍历的）不平等，需要完整地考虑未来和过去。


还请记住以下两句话： 真正的平等是概率上的平等。 只有“风险共担”能防止系统崩溃。


静态的不平等只是一张瞬间抓拍不平等现象的照片，它不能告诉你在今后漫长的历程中还会发生什么。动态的（遍历的）不平等，需要完整地考虑未来和过去。



经济学家为什么会犯这样的错误？因为他们并不真正理解不平等现象。不平等可以视作一种尾部的不协调现象，富人位于财富分布的尾部。系统内越不平等，赢者通吃效应越强，我们就越偏离“平均斯坦”（见术语表之薄尾平均斯坦，thin-tailed Mediocristan）。不平等的根源在于财富过程是由赢者通吃效应主导的，任何一个在官僚体系帮助下的财富积累过程，都会倾向于将富裕阶层不可逆地锁定在社会顶层。所以解决办法是，允许系统存在一种机制，这种机制使得最强大的、最富有的人有可能因其承担的风险过大而垮塌，这种机制在美国运行良好。



考虑一下这样的现实：保罗·克鲁格曼和皮凯蒂之流，不会有阶层下降的风险，我们消除社会不平等的努力，只会让他们的人生更上一层楼。除非美国的大学系统或者法国的政权崩溃，否则他们还会继续领取他们的工资。而你刚刚在牛排店遇到的那个戴着金项链的陌生人，正在承受着如果生意失败就要去排队领救济的风险，克鲁格曼和皮凯蒂却没有这种破产风险。古语说得好，以剑谋生的人会死于剑下，靠承担风险谋生的人也会被风险夺去生计。



知识分子为什么如此关心社会的不平等问题？那是因为他们本能地用等级社会的眼光看世界，他们关心自己的社会地位。其实还有一个深层次的病理学原因，那些培养了他们的名牌大学平时讨论的话题大都是有关等级社会的，而现实世界的大多数人并不为此感到困扰。 在古老的乡村，忌妒并不是一个困扰大家的社会问题。富人之间相互接触的机会很少，他们各自住在自己的领地里，缺乏那种营造相互攀比心理的环境。富人在自己的领地被一群依靠他们谋生的农民包围着，除了偶尔进城以外，他们的社交生活相当垂直，他们的孩子会和仆人的孩子一起玩耍。 发展到商业社会以后，相同或相似阶层的人才开始居住在同一个社区，社交演变成同一阶层内的活动。工业化社会以后，富人开始向城市或郊区聚集，他们的财富状况相似但又不完全相同，这种财富差异使得他们相互攀比。于是，比赛开始了。



因此，工业化社会以后的富人在社交上隔绝了穷人，穷人对于他们而言变得理论化了，成了教科书上的概念。正如我在上一章所讲的那样，我从未见过一个正统的剑桥大学讲师和一个巴基斯坦来的出租车司机一起闲逛，或者和操着伦敦腔英语的工人一起举重。因为知识分子认为他们有权把穷人当成一个观念来对待，一个由他们创造的观念。因此，他们确信自己知道什么才是对穷人最有利的。



我从皮凯蒂的恢宏巨著中学到了另外一课：他的书里充满了各种图表。这其实是一个教训：如果我们在真实世界里遇到一个专家使用各种图表呈现大量数据，那么这并不能说明他很严谨。我作为一个概率专业人士，在《黑天鹅》那本书中并没有使用大量的数据和图表（除非个别说明性目的的展示），因为我相信堆满了数字和图表的作品，恰恰缺乏逻辑严密的论述和坚实可靠的观点。而且，人们误以为实证主义就是堆砌数据。当我们的逻辑是正确的时候，只需要一些有意义的数据稍加修饰；而当我们试图证伪某一观点时，一个反例就足够了。只要有一个数据显示存在极端偏差就足以表明黑天鹅的存在。 当交易员们赚钱的时候，他们懒得搭理你；当交易员们输钱的时候，他们会把你拖入细节、理论、数据和图表的汪洋大海之中，以便证明他们自己是无辜的。 概率论、统计学和大数据分析的核心不是数据，而是基于观测得出的逻辑——尤其当观测数据不足时，逻辑就至关重要了。



他没有意识到，统计学并不关心数据本身，核心是通过数据提炼逻辑，从而避免被随机产生的数据愚弄。但是无论我怎么苦口婆心，普通大众和他那些崇拜国家机器的白知同事，都认为这是一本很了不起的书（至少他们这会儿是这么想的）。



一个公职人员可以制定对某些行业（银行业）特别友好的监管规则，然后去摩根大通银行把他当公务员时工资和市场差额的几倍统统赚出来（你可能还记得，监管者总想把监管规则制定得越复杂越好，这样一来，他们就可以凭借专业知识被高价雇用了）。


因为时间是“风险共担”的组织者和裁判者。那些经过时间的洗礼、磨炼和筛选而幸存下来的事物，向我们揭示了它们强韧的生命力（尽管我们是事后知道的）。如果没有“风险共担”把各种事物的脆弱性暴露在现实世界，任其承受各种潜在伤害，那么筛选机制就会被打破：任何事物都有可能以某种规模生存相当一段时间，然后突然崩溃，造成很多附带的伤害。



让我们列举几个古代传说就有且经现代心理学证实的想法，这些想法都是自然而然产生的，并不是刻意研究的结果，都是灵光一闪浮现出来的。 认知失调（利昂·费斯廷格关于酸葡萄的心理学理论，人们为了避免想法之间存在矛盾，就会使其合理化，也就是说，自己吃不到的葡萄一定是酸的）：第一次看到这个故事是在《伊索寓言》里，拉封丹寓言重新包装了一下，但是起源看起来更古老，可能源自阿伊卡寓言。 厌恶损失（一个心理学理论，认为损失带来的痛苦大于盈利带来的快乐）：李维在《编年史》中写道，人类对于愉悦事物的感知不如对悲凄事物的感知那么强烈。塞内加在几乎所有文字中都流露出厌恶损失的情绪。 负面建议（通过负面认识事物）：相对于什么是正确的，我们更容易知道什么是错误的。想想银律打败金律的逻辑优势。恩尼乌斯说过，如果没有“坏”，“好”也就没那么好了。西塞罗重复过他的话。 风险共担（字面意思）：我们先从意第绪语的谚语开始，“你不能用别人的牙齿咀嚼”“你的指甲最能挠你自己的痒”，斯卡利杰在1614年出版的《阿拉伯谚语丛刊》中记载了这样两句话。 反脆弱：这方面有几十条古代谚语，我们只提西塞罗的一句话：“当我们的灵魂安宁时，蜜蜂都刺不痛我们。”马基雅弗利和卢梭把反脆弱理念应用在了政治体系中。 时间贴现：“一鸟在手胜于十鸟在林。”（古代黎凡特谚语）。 群体疯狂：尼采说，“疯狂对于个人来说是罕见的现象，对于群体、党派和国家来说则是必然的规律”。尼采应该算是一位古典主义者，他的话也应该算是古代智慧，另外我还见过柏拉图多次表达过类似的意思。 少即是多：“太多的争吵稀释了真理。”普布里乌斯·西鲁斯这样写道。当然这句话最早完整地出现在罗伯特·勃朗宁写于1855年的诗中。 过度自信：“我因为过度自信而丢了钱。”伊拉斯谟的这句话明显受到了迪奥尼斯和埃庇卡摩斯的影响，前者说“自信让我失去一切；蔑视让我拯救一切”，后者说“保持清醒，时刻提防”。 进步的悖论和选择的悖论：大家都很熟悉银行家度假的故事，它说的是一个纽约的投资银行家去希腊某岛上度假，他遇到一个当地的渔夫，突发灵感想到了一个好主意，可以把渔夫的生意做大，他鼓动渔夫听从他的建议，渔夫却一脸疑惑地问他：“赚那么多钱有什么用处呢？”银行家回答道：“等你有了一大笔钱，就可以像我一样到希腊的海岛上去度假了。”渔夫笑道：“可我天天都在度假啊。”


吉米·鲍尔斯是爱尔兰人后裔，性格强硬，我曾经和他在一家投资银行共事，我们都是交易员。他除了从大学辍学，还曾经是布鲁克林区街头的小混混。每次开会的时候，他都会向一头雾水的公司高管这样介绍我们的交易：“我们先做了这个，然后做了那个，哼哼哈嘿！利润就来了。”所有人都没有听懂。但是只要我们部门继续保持盈利，这些高管根本就不在意他说了些什么，也不在意自己有没有听懂。过了一段时间，我终于明白了，我其实根本就不用去试图理解吉米说了些什么。我刚20出头的时候就明白了这个道理：如果一个人说的话很容易被人理解，那么他一定是在吹牛（因为他会刻意地把话说得让人易于理解）。



许多发展中国家都存在着营养失衡和营养不足的问题，我的合作伙伴亚尼尔·班杨和乔·诺曼，这个问题直接归结于一个简单的原因：运输系统的效率不高。简单说吧，我们在运输仓储和批发等流通环节浪费了1/3以上的食物，因此，解决发展中国家孩子营养不良的问题，最简单的办法是提高整个食物配送系统的效率，而不是花钱去研发新的转基因作物。想想吧！西红柿的成本中有将近80%~85%都源于运输、仓储和浪费（包括滞销和腐烂等因素），而来自农民生产环节所占的成本很低。所以很明显，我们应当在技术含量较低的物流领域下功夫。



常春藤名校正逐步成为亚洲新富阶层心中的终极奢侈品。哈佛大学就像一个路易威登的包或者卡地亚的表。它们对于中产阶级来说是一个巨大的负担，他们把积蓄越来越多地投在教育机构中，但这些钱又都被转移给了官僚、房地产开发商、一些根本不应该存在的学科（性别研究、比较文学或国际经济学）的终身教授，以及其他寄生虫式的人。在美国，我们已经堆积起了巨额的学生贷款，而这些钱最后都自动落入了各种收租者的口袋里。一个人要靠一张体面的大学文凭才能在生活中出人头地，这无异于绑架一个年轻人的前途，然后对其父母进行敲诈勒索。我们有证据表明，社会进步并非是由高水平的教育机构推动的，恰恰相反，一个国家的教育水平是由居民财富水平决定的（从这个意义上讲，教育就是一种奢侈的消费）。


我饿着离开了三星米其林餐厅，如果当初让我选择的话，我肯定会选那些经受时间考验的餐厅，那里有食材新鲜的比萨、多汁的汉堡，而且食物充满了活力，我只要花相当于三星米其林餐厅账单5%的价钱就能吃一顿可口的饭菜。但是因为一起去吃饭的朋友吃得起昂贵的饭店，最后拜米其林官僚体系选出来的主厨所赐，我们成了他复杂烹调实验的牺牲品。这违反了林迪效应：西西里每个祖母做出来的饭都是不一样的，一点儿细微的差别就能让饭菜更可口。这段经历让我突然明白了，有钱人很容易成为别人的靶子，就像塞内加悲剧中梯厄斯忒斯的哀叹，小偷不会光顾穷人，毒酒总是放在金杯而不是普通杯子里——因为放在金杯里更容易让人喝下去。 把事情搞复杂，就能轻易地骗到富人的钱。穷人当然是不用担心这方面风险的。这种把事情复杂化的做法正如我们在第9章中提到的，学术结论要尽可能地复杂化，避免使用简单易懂的语言概括。而且，有钱人喜欢征求“专家”和“顾问”的意见。这下可好了，整个行业的人都想骗你的钱了，于是就有了更多的财务顾问、饮食顾问、健身教练、生活设计师、睡眠顾问、呼吸专家等。


法国作家法尔儒纳是一名道德主义者，他也意识到较小的社区更受欢迎，这可能和我们前面讲的适用性规模问题有关。有些东西可能大了以后就超出了你的心理承受范围。他写道：“当罗马还是一个小村庄的时候，人们很容易爱上它，而当它变成一个大帝国以后，就不那么招人喜爱了。” 这就是为什么有些富人看起来不像富人的原因，这些富人内心明白这个道理，所以他们住在邻里距离近的老街区里，他们知道搬到大房子只会带来精神负担，许多人仍然住在他们原来的房子里。 很少有人真正了解自己到底想要什么，结果就被那些想卖东西给他们的人操纵了。对于这些富人来说，变得穷一些反而可能是好事。看看沙特阿拉伯吧，现在他们被一群阿谀奉承的外国人包围着，其实这些外国人都是来剪他们羊毛的，他们应该逐步恢复到发现石油以前的生活中去，那样的话，沙特阿拉伯也许会变得更好。



在任何情况下，你如果有了钱之后还想拥有朋友，就一定要隐瞒你的富有。这一点可能人人都知道，还有一点不太广为人知但同样重要的是，你还需要隐藏你的博学和知识。只有当人们不试图去攀比和超越对方的时候，他们才会成为朋友。


我在那次谈话中提出的审慎性原则值得在这里重复一遍，即人们不需要使用复杂模型来作为自己行为的依据（无论你打算做什么，或者打算不做什么，都不要以复杂模型为决策依据）。尤其当我们对一个有系统性影响的事物还不了解的时候，我们应该尽量避免对它采取行动。我混迹金融领域的时候就很清楚地知道模型很容易出错。而大多数风险只有在事后统计损失的时候才会被发现。我们只有一个地球，经不起试错，所以我认为与其针对地球大气层引进一个新的未经验证的保护机制，不如建立一个让那些污染环境（或者大量排放新合成物质）的人承担尾部风险的机制。实际上，模型越是不确定，我们就越是应该慎重行事。


所以，当我们考虑宗教问题以及（在某种程度上）古代迷信问题的时候，我们应该关注它们在当时的社会发挥什么作用，而不是把关注点仅仅局限在“信仰”这个概念上，更不要把信仰严格地定义在认识论的范畴内。从科学角度来看，信仰就是其字面上的意思，无关对错，亦无其他隐喻。在现实生活中，信仰是做事的方法，而非最终的结果。因此，信仰对人生的意义和视觉的作用相似：眼睛的功能是帮助你辨认方向，并在需要的时候帮助你摆脱困境找到出路，或者帮助你发现远处的猎物。你的眼睛并不是为捕获电磁波而设计的传感器，因此，它的职责不是以科学研究为目的将事物精准地呈现给你。眼睛就是眼睛，它是你非常有用的生存工具。



显示偏好的理论（源于保罗·萨缪尔森，或者可能是闪米特众神）说了以下内容：只通过询问的手段，你永远都不会知道人们真正在想些什么，下一步打算做些什么，因为他们自己都不知道。重要的是观察他们花钱买了什么，而不是问他们对某商品怎么“想”，因为你会得到各种千奇百怪的理由。你仔细想想，这个道理讲的就是“风险共担”。现在心理学家也明白这个道理了，在他们的实验中，他们要求实验对象在测试中必须使用真金白银，以便得到“科学”的结果。他们会给实验对象一些钱，然后观察他们如何花掉这些钱，以此来研究他们的选择。但是，还有很多心理学家不理解显示偏好，仍然奢谈理性。这意味着他们仍然在评判人的信仰而不是他们的行为。


100个赌徒在1天时间里的成功概率，并不适用于你表弟在100天时间里的赌运。我们把第一种情形称为集合概率，第二种情形称为时间概率（第一种情形涉及的是一群人，而第二种情形则涉及一个人穿越一系列时间）。所以当你在阅读金融学教授、投资大佬或者当地银行根据市场长期回报提出的投资建议时，你一定要格外小心。即使他们的预测是对的（其实不对），个人也无法获得与市场相同的回报，除非他有源源不断的资金可以注入市场，而且不存在“爆仓点”。如果有人认为自己能够取得和市场相同的回报水平，那么他犯了这样一个错误：混淆了集合概率与时间概率。投资人要么是出现损失以后本金减少（以后追不上指数上涨了），要么是他即将退休，要么是打算和原配离婚、迎娶邻居的老婆，要么是他在接受阑尾炎手术后染上了毒瘾，要么是他改变了生活态度，无论出现哪种情况，此投资人的回报都会低于市场总体回报水平。



如果没有参加过“风险共担”，又想理解涉及概率的问题，那么这个人一定要具备超高的智慧。对于那些接受了过度教育又严重缺乏实战经验的人来说，理解这些事情是很困难的。当然，除非他是一个天才，有着敏锐的头脑，能看透思维的迷雾，而且对概率论有深刻的理解。可以肯定的是，盖尔曼就是这样的天才（彼得斯或许也是），盖尔曼发现了“夸克”（这使他获得了诺贝尔物理学奖）。彼得斯说当他向盖尔曼阐述这一观点时，“他立刻就明白了”。克劳德·香农、艾德·索普、J.L.凯利和哈拉尔德·克拉梅尔毫无疑问都是天才。我可以以个人名义为索普担保，他有绝对清晰的头脑和深刻的思考，你在和他交谈的时候就能感受得到。上面所说的这些人因其极高的天赋，可以不必亲身体验“风险共担”，便能理解我提到的观点。但是经济学家、心理学家和决策理论家就没有这样的天分了，而且可以肯定他们以后也不会有。不过，偶尔从事心理学研究的赫布·西蒙是个例外。把一群没有真知灼见的人聚集在一起，即使人数再多也不会产生真知灼见。在经济学家当中寻找对概率问题有清晰而正确理解的人，就如同在计算机黑客蜗居的小屋或者懒散电工的阁楼里寻找和谐的美感一样。



现在我们再来考虑一个比赌场实验更极端的例子，其实这个例子也是《随机漫步的傻瓜》书中的核心案例。假设有一群人在玩俄罗斯轮盘赌，单次获胜的奖金是100万美元，每6个人中有5个人可以获胜，如果有人用标准的成本收益模型来分析，那么他很可能会得出结论，声称参与游戏的人有83.33%的机会赢得奖金，因为每次平均收益是83.33万美元。但是如果你不停地玩这个游戏，最终的结局一定是躺在坟墓里，这时候你的预期收益还能作数吗？



在现实生活中，情况往往更糟，每个看起来微不足道的风险，累积起来就会降低你的预期寿命。如果你喜欢爬山，骑摩托，爱和流氓混在一起，驾驶小型私人飞机，喝苦艾酒，抽烟，还有星期四晚上玩跑酷的话，你的预期寿命会大大缩短。这些行为通常不会造成非常严重的后果，但是它们如果集于一身且持之以恒的话，就不是那回事了。由此看来，人们对重复发生的低概率事件的担心并不是一种“偏执”，而是具有相当的合理性的。



遍历性框架解释就是，在俄罗斯轮盘赌游戏中我的爆仓对于我本人而言不是遍历性的（由于我爆仓出局导致我无法实现时间概率的遍历性），但对于系统而言是遍历性的（对于系统而言，有人爆仓出局体现了集合概率的遍历性）。正如我与几位同事提出的那样，预防系统因遍历性而产生的极端情况应该成为我们首要关注的事物——要防止自己成为系统遍历性的牺牲品。



所有的风险都不相同。比如，我们经常会听到有人说“埃博拉病毒造成的死亡人数比在自己家的浴缸里淹死的人还要少”，或者是其他类似的基于所谓“证据”得出的说法。这类问题你的祖母会很容易理解，但是对于那些半吊子学者来说却是难以理解的。 永远不要将倍增的、系统性的胖尾风险和不倍增的、特殊的薄尾风险相提并论。


现在，我的读者，这段旅程即将结束，这是不确定性系列丛书的第五本。我想为这本书做一个总结，仿佛我有天然的责任为你们提炼这本书的精华，此刻我正站在餐厅的镜子前，我看到镜子里的我络腮胡已经变白，那种我生来就有的东地中海（希腊–腓尼基）人特有的不屈不挠和抗争精神已随岁月老去。25年前我开始写不确定性系列丛书时，我用的还是纸和笔，那时我的胡子还没有变灰。林迪一直对我说，对某些事情，不必努力去证明，去解释，去总结。有一次我在餐厅无意中听到一个人说出了我的心里话，“事情本来就是这样的”，这句话后来不断地在我脑海中共鸣和回响。 接下来我不做总结了，以后也不再做任何总结了，我们来听听林迪怎么说： 当一个人胡子还是黑的时候，要注重推理，忽略结论；当他的胡子变灰的时候，要推理和结论并重；当他的胡子变白的时候，那就跳过推理，直接关注结论吧。
