#+title: 出卖了我的灵魂，换得了学生贷款


我的穷学生在债务陷阱中爬不出来，每星期打工30多个小时。我怎么教他们呢？

加州州立大学California State University, Sacramento的这个讲师。刚刚出版了一本书。Sold my souls for a student loan, 也许可以译为《出卖了我的灵魂，换得了学生贷款》

他自己还有学生贷款没有还完。他讲美国4500万人，还有学生贷款没有还清，每个人平均还有三万多美元。他现在自己当大学老师，看到很多学生每个星期要打工30多个小时，还来上课。他的学生在债务陷阱中越陷越深，疲惫不堪，“我怎样教我的疲倦不堪的学生呢？”

他说，“男女老少都说，教育是百年大计。政客说美国高等教育是我们的未来。学校特别是那些牟利的学校，巴不得每个人都上大学。贷款机构乐坏了，不断地煽风点火。老师们呢？无耻的老师们更是乐不可支。学校不断地加学费，给教职人员涨工资，创造所谓的就业机会。美国全国就是一个大合唱。教育教育教育。很多的教育根本没有任何的经济价值和社会价值。但是教育膨胀的越来越厉害。英国的情况，澳大利亚的情况，加拿大的情况都是一样的”。

中国的情况更恶劣。我写过一篇很受关注、很受争议的文章。老师们、做教育的人、政府官员必须要有良心，告诉人民：花你的血汗钱是没有回报的！链接在后面。

#+BEGIN_QUOTE
作者：Daniel T. Kirsch.

书名：Sold My Soul for a Student Loan: Higher Education and the Political Economy of the Future.

With free college in the national conversation, there’s been no better time for Daniel T. Kirsch’s new book Sold My Soul for a Student Loan: Higher Education and the Political Economy of the Future (Praeger, 2019). Kirsch teaches at California State University, Sacramento. American colleges and universities boasts an impressive legacy, but the price of admission for many is now endless debt. As Kirsch shows in the book, increasing educational indebtedness undermines the real value of higher education in US democracy. To help readers understand this dilemma, he examines how the student debt problem emerged and what the long-term effects of this might be. Sold My Soul for a Student Loan examines this vitally important issue from an unprecedented diversity of perspectives, focusing on the fact that student debt is hindering the ability of millions of people to enter the job market, the housing market, the consumer economy, and the political process. Learn more about your ad choices.

#+END_QUOTE

----------

基本99%的年轻人不知道自己未来会干什么，你让他们不读书，他们也不会干别的更有意义的事情，比如去安心学门手艺。反而学了知识，有了学习的能力，并不构成再学习实用技术的障碍。

个人感觉以经济上的回报率来衡量学习不太恰当，原因有两个：

学习就像登山，曾经去过山顶和从来没有去过山顶的人眼界是不一样的，因此学习对人生的影响不是立竿见影，而是细水长流；

学习不是固定资产投入，一旦终止，以前的投入全部打水漂。如果经济能力跟不上，随时可以终止。社会上确实有很多人因为让孩子读书导致家庭经济困难，但仅仅是困难，没有导致他们生存受到影响。客观的说，这个世界绝大部分人都是普通人，无法做出惊天动地的大事情。与其让大家无所事事，简单快乐，不如让大家重视教育，负重前行。

我理解您的意思是社会有点走偏，重视文凭，不重视实用技能。学点什么货币银行学，远不如水电安装实在。这个很对。难点在于，我们没有一个权威机构来进行鉴定，说某人你适合学习高深知识，某人适合学习水电安装，也不可能有这样的机构。鼓励社会读书，追求学位，无法让社会资源完美配置，但我们并没有更好的解决办法。

曾经在拉美地区呆过一段时间，对当地大众的教育水平比较吃惊。比如你花26元，给侍者30 + 1 块，他们绝对会给你4 + 1 块，而且会使用计算器。矫枉必然过正，虽然全民精英教育无法实现，也不经济，但对社会素质提升很有帮助。
