#+title: 一些想法（关于工作，人生，以及最近做的梦)

@2016-08-15

关于工作的：
- 个人的技术能力是有天花板的，想要突破天花板，就要能拉来更多的人。那这是另外一种能力。
- 找来了更多的人，也是要精心管理的。有些人驱动力很强也很负责，那么就可以少操心，但是大部分人不是那种可以少操心的（绝对没有任何贬义，有时候和具体工作性质和难度有关）。
- 补充下上面一条：比如这件事情本身就偏探索性质，或者是需要团队紧密协作的话，那么操心肯定是比不可少的。
- 员工如果是你带过来的话（更准确地说，你非常喜欢或者是欣赏这个人，想和他成为朋友），那么就要对他工作环境以及薪水负责。
- 如何成为令人讨厌的领导，非常容易：对于自己不太熟悉的领域，经常来个here is my two cents, 可是two cents充满着浓浓的大便味。
- 即便在你所最尊敬的公司工作，你依然会遇到一些和你三观不太搭的人，而这种人又是你的上司。那么你最好做好心态调整：永远做那些对你自己收益最大的事情，然后时刻准备离开这家公司，所以擦屁股的活绝对不能碰。
- 补充上条：好像这种心态调整不仅限于上面这种情况，在任何一家公司工作都应该这样。
- 友情提示：凡事都有例外。这个世界是残酷的，有些事情是不得不做，这种情况下就认怂吧。

关于人生：若在言语上猛地使劲，那么行动上容易乏力。所以你看到那些背后捅人刀子的人，言语上不太会去得罪人。因此反过来，如果你真的对某个人恨之入骨，不要在谈话中表现出来这种憎恨，也不要在争论中非得争取胜利，把这些都收回心里放在脑里。你会发现，当你真正地有机会去报复这个人的时候，你不会有任何手软，也能够找到千百种理由去下手，行动的时候你也不会表现得特别兴奋，以至于让别人怀疑你是否行为不公或有私仇，所有的一切都是顺其自然的。

最近的做的梦，两个。梦一般都记不太清楚，而我就比较只喜欢记录事实，不想瞎编乱造，所以就打算潦草地写写。

第一个梦是，我上飞机之前有一支军队正好过来搜身检查，他们对已经上飞机的乘客不再检查，正打算从我开始。就正要对我检查的时候，我的书包从身上掉了下来。好像还是一位级别非常高的军官过来帮我拾起书包，看了看我书包里面的东西，便让我上了飞机。和我一起坐飞机的还有好几个同事，但是我发现他们都被扣留下来。下了飞机之后我听说我，那支军队把所有扣留的人全部都枪决了。我通过某种方式（时光隧道，又或许是一个巫师）知道，我包里面某个设备，在掉下来的一瞬间，打印了一张可能是通关证类似这样的东西。

第二个梦是昨天晚上做的，好多细节都记不起来了。梦里面我是我老板的男炮友，刚完事了，这时候进来了一个帅哥。我立刻明白老板的意思了，我满足不了他，那个帅哥可以。正当我要收拾起地上的衣服离开时，帅哥说你不用穿衣服，滚回你的平民窟吧。我转过头想请求老板，但是老板转头不看我。我回到了平民窟，巨大的空间被隔成了一个个小房间，肮脏，臭气冲天。我试图想找个房间歇歇脚，但是都被他们赶了出来。最后有一家好心地把我收留了起来，梦便到此结束了。我隐隐地感觉到这个可能是我这辈子的写照。比较可惜的是，我不记得最后收留我的那家人的相貌或者是特征，否则我肯定会好好对待在真实世界中有这类相貌或者是特征的人。或许神还有其他的安排也说不好。



