#+title: Some advice from Jeff Bezos

[原文地址](https://medium.com/@jasonfried/some-advice-from-jeff-bezos-28b3c2938968)

He said people who were right a lot of the time *were people who often changed their minds.* He doesn’t think consistency of thought is a particularly positive trait. It’s perfectly healthy — encouraged, even — to have an idea tomorrow that contradicted your idea today. 那些right a lot的人想法经常会改变，明天的idea可能和今天的idea完全相悖。

He’s observed that the smartest people are constantly revising their understanding, reconsidering a problem they thought they’d already solved. They’re open to new points of view, new information, new ideas, contradictions, and challenges to their own way of thinking.

This doesn’t mean you shouldn’t have a well formed point of view, but it means you should consider your point of view as temporary. 并不是说没有一个well formed的观点，而是应该将自己的观点当做是临时的观点。

What trait signified someone who was *wrong* a lot of the time? Someone obsessed with details that only support one point of view. If someone can’t climb out of the details, and see the bigger picture from multiple angles, they’re often wrong most of the time.
