#+title: [职场感言] [周末码字时间]审简历得到的一点成长小心得

http://www.1point3acres.com/bbs/thread-435871-1-1.html

----------

所以，什么是亮眼的简历呢？其实这个问题，怎么把自己简历改好的具体操作，在地里的置顶帖子已经讲得很多了。我今天想讲的是，hiring manager和recruiter看什么？.我自己的方法：

第一眼，前几份工作的公司和职位。大厂的senior，小公司的cto/director of eng/architect/senior eng会继续认真看，大厂junior次之，小厂junior再次。你的title和公司的层次，一定程度上是你的能力的最直接证明。New grads的话就看intern经历和project。

第二眼，毕业学校。虽然现在唯学校论也已经非常过时了，但是如果之前工作的公司完全没听说过，或者很junior，会看看学校（大厂senior我应该完全不会在乎学校）。如果是好学校，那我可能会回头再仔细看工作的内容。如果小厂Junior然后学校也不好，可能到这里就pass了……（对不起呀 m(_ _)m——但是地里的小朋友们发的信我都还是坚持认真看完的）。学校可以说是一个年轻人学习能力比较好的近似。

第三眼，工作内容。Senior的话主要看工作内容是不是match以及deliverable，junior主要是看有没有deliverable。（所以小伙伴们不要写“会用xxx”“知道xxx”或者堆砌技术词汇，而要写“完成了xxx”“发布了xxx”）但是如果senior没有令人信服的deliverable那就是个big red flag，甚至可能会直接拒。另外就是，如果你的工作内容很match，如果前面优势不明显，这里还是有挽救的余地的。（所以对心仪的公司好好针对Job description改简历真的是必要的啊，海投的小伙伴们至少对最重要的几家公司不要不上心）

第四眼，其他projects。这个很不幸在我看过的experienced hires里面占的比重很小……毕竟自己做的project，怎么吹都可以，所以 >"<

----------

如何透过简历的亮点看一些关键的工作选择呢？

因为工作经历>学校>课外project，所以首先比较适用于普遍规律的一个建议是抓大放小，该认真学习的时候，该埋头工作的时候，不要太分心，把当时该做的做好。

另外，也说明从任何时候开始努力都不晚，本科没考好可以申个好研究生学校，研究生学校也不好可以找个有点名气的公司，公司不好可以在里面好好做些project有拿得出手的deliverable，然后升到好的title~

这个不是鸡汤，是真心建议，毕竟HM/recruiters每天要看那么多简历，竞争那么激烈，一个candidate本科学校/研究生学校/公司/project全都没亮点的话，人家真的没有义务去相信他的能力够强（下面会说早期startup特例的情况）。

----------

一些具体的问题，因此也有了比较实际的答案（again，都是个人见解哦，不同意的欢迎探讨）：

1.毕业了，是去大公司还是创业公司对以后找工作最有好处呢？
如果你是名校毕业，那么我觉得可以任性一点（单纯指码工而言）大公司~=技术创业公司大title(cto, vp, director)>技术创业公司小title>非创业小公司
如果你是非名校毕业，我觉得是大公司>技术创业公司大title>技术创业公司小title>非创业小公司.


2.我真的很想去startup耶，但是如果做挂了，咋办？以后怎么找工作？
没事没事~姐姐我最喜欢在startup打拼过的小朋友啦。。。你的startup有啥能吹的地方没？Valuation多少？founding多少？怎么exit的？有没有参加过哪个著名孵化器？等等等等。一定要说清楚是startup哦。（这个也一定程度上说明你选startup的话也最好选以上这些条件好的，不要别人随便画画饼你就去了）
然后，你在里面做了什么重要的project？给公司metrics涨了多少？有没有做team lead？都可以写哦。
在startup里，更要好好工作，work your ass off! 不要公司不靠谱的小朋友们周末出去High了你也傻乎乎跟着去哦。


3.我现在在大公司打酱油好无聊，做的东西也没啥可吹的，怎么办？要不要把时间都用来刷题？
首先恭喜你，如果你有大公司的背景，就已经有很多advantage啦。
刷题是一方面啦。但是说实话我觉得刷题和实际工作经验，真的是，两手抓两手都要硬。除非是new grads，如果问你以前做过的东西，你说出来给人很浅的感觉，面试的时候被刷的可能性很大……
为什么说大公司总的来说是个好选择呢？毕竟大公司的系统够深够复杂，你就算平时工作无聊，看看别的code了解一下总行吧……也算是一种积累……
所以我建议，刷题和花时间想想自己工作的系统，至少得一半一半吧~

----------

我觉得如果以每份简历看几分钟的时间而言，你要突出以下几点：

1.verb.
你的project尽量用verb开头，而且要选用强调成果的verb，比如Built, delivered, launched, designed, re-architected, increased, led, etc.
不要用强调过程的verb，比如learned, used, applied, etc.
我只要一看句子开头是learned之类的就直接路过那句话了……

2.project内容
尽量先强调project本身的特点和优势，比如规模多大，是不是distributed，有多少transactions，有什么特别的features, 等等
不要把一堆language和framework堆在最前面。如果一个人在project描述的第一句就开始说用了python, java, c++ AWS blabla，我会觉得他只是想说他对这些东西有所了解，但是并不能体现他用这些东西实现了啥或者有多精通，但是project本身并没什么深度。
当然，如果是某种先进技术的深入应用，你可以放在前面。

3.你自己在project中的作用
光说你learned xxx也是不行的.
如果你是project lead，一定要说。如果你帮忙了其他的Junior members，也可以说。如果你只是干活的，也要说你负责了项目的哪个部分，取得了什么好的成果
如果也没有什么好的成果……
