#+title: StranglerApplication

https://www.martinfowler.com/bliki/StranglerApplication.html

重构的一种办法：在新应用中不断地实现老应用的不断功能，直到把老应用完全替换掉。使用这种办法可以减少风险并且可以很快看到回报。
Martin在最后面还建议，在编写新的应用中应该考虑，如何可以让当前应用程序被后来的应用strangled.

When Cindy and I went to Australia, we spent some time in the rain forests on the Queensland coast. One of the natural wonders of this area are the huge strangler vines. They seed in the upper branches of a fig tree and gradually work their way down the tree until they root in the soil. *Over many years they grow into fantastic and beautiful shapes, meanwhile strangling and killing the tree that was their host.*

An alternative route is to gradually create a new system around the edges of the old, letting it grow slowly over several years until the old system is strangled. Doing this sounds hard, but increasingly I think it's one of those things that isn't tried enough. In particular I've noticed a couple of basic strategies that work well. The fundamental strategy is EventInterception, which can be used to gradually move functionality to the strangler and to enable AssetCapture.

The most important reason to consider a strangler application over a cut-over rewrite is reduced risk. A strangler can give value steadily and the frequent releases allow you to monitor its progress more carefully. Many people still don't consider a strangler since they think it will cost more - I'm not convinced about that. Since you can use shorter release cycles with a strangler you can avoid a lot of the unnecessary features that cut over rewrites often generate.
