#+title: 硅谷王川电子书第一卷

https://zhuanlan.zhihu.com/p/20252392

许多聪明人，容易落入的陷阱是，觉得自己在某个领域成绩不错，误以为解决别的领域的问题也驾轻就熟，没有做太多功课，就冒然的对别的行业下结论，做投资。但大多数聪明人的投资表现并不好，还不如傻傻的把资金放在指数里面。

为什么人们总爱把辛苦挣来的血汗钱投到自己完全不熟悉的行业？这里有一种“邻居的草更绿”和“老婆是别人的好”的心态作祟。人们对于自己熟悉的行业，对于里面的风险和问题都看得比较清楚，产生审美疲劳。而对别的行业可能的巨额回报产生完全不切实际的幻想，并且对其风险视而不见。

一个公司核心的产品性能，是这个公司的灵魂。如果你可以深刻体会产品的各个细节，那你就处于战场上可以听到炮火的一线位置，这就是在你的能力的边界之内。你对公司的理解远远超出那些华尔街上简单搬弄财务数据的分析师了。

十年前，我战斗在美国次贷狂潮的第一线，奔波在美国西部内华达，亚利桑那，新墨西哥和加州之间炒房，天天感受前方的炮火。印象极深的是，2005年六月在亚利桑那凤凰城的中餐馆，店小二得意地向我的经纪人吹嘘自己已经定了三套新房，还没过户就都涨了好几万美元。从2005年10月开始，凤凰城的房价明显疲软下跌，击鼓传花的次贷游戏难以为继。2006年底就陆续有次贷公司宣布巨额亏损，直到2008年九月雷曼兄弟宣布破产，这场灾难缓慢地拖了三年才达到高潮。一些唯大数据是从的分析师，听不到前方的炮火，机械地根据美国房市的几十年历史数据模型来指导交易，最终在金融海啸中覆灭。有诗为证：“当年鏖战急，弹洞前村壁，装点此关山，今朝更好看。”

对于金融资产在极端价位发生的波动，许多基金经理事前都会信心满满的说，“这种情况绝对不可能发生！”他们会事前诸葛亮地断定：油价不会超过140美元一桶！不会跌破40美元！股价一天内波动不会超过30%！汇率一天内波动不会超过5%！ 于是他们为了提高短期收益，不断加大杠杆。

投资大师索罗斯曾经说过一句名言：“当你赚钱时，你往往并不忙碌；当你奋力工作（为提高短期回报）时，你往往对自己的回报业绩感到愤怒。” “When you are making money, you are not busy.if you work furiously, you would be furious at your results.”

你有成千上万的投资选择，股票、债券、期货、外汇、房地产等等，你只要找到几个属于你的强项，就可以轻松的胜出。没有人强迫你一定要用某种投资方式。往往你周围的人趋之若鹜的投资产品，因为过于拥挤，而无法获得理想的回报。

财务造假是要命的，通常关于造假的公开信息往往只是一小部分。如果看到一只蟑螂，肯定还有许多蟑螂没有看到。财务造假和其他重大法律问题，意味着公司管理层完全不可信任，这时要赶快抛售，不可存一丝幻想。

一个公司真正打翻身仗，往往意味着要把过去的商业模式，产品结构，内部人士组织进行一次彻底的，触及灵魂深处的革命。这一切，都要耗费很长时间。即使天才如乔布斯者，当他97年回到苹果公司后，经过了六年的整改，苹果公司的股价仍然在2003年上半年达到二十年的新低。等到2004年，苹果的ipod终于在市场上火起来后，苹果的股票才真正一骑绝尘而去，开始了几十倍的增长。

平庸的管理者，多是靠大量举债，增加金融杠杆，四处收购别的公司，获得短期，表面的增长，应付华尔街的压力。极品的管理团队，有战略远见，了解客户和市场，非常接地气。能够以较少的内部资金，不断发现创造新的商机和全新的蓝海市场，促成公司增长。当你见的管理团队多了，你就很容易区分谁是大言欺人，谁是善于创新，出奇制胜。

作为一个一秒钟三美分的高薪临时工，我实在没什么好抱怨。但做项目时，明显感觉到工程师，管理层，市场部都对这个滑稽的披着皇帝新衣的项目有着不同的理解和解释。惠普在这个项目上投入了一亿美元，后来无疾而终，2002年项目停掉。卡莉即没有产品经理那样接地气，也没有战略家的大局观。忽悠完大众，该开始干活了，她唯一可以想到的就是举债收购公司。这个风格，其实和我见到的不少硅谷阔太太，没事做，就想贷款买投资房的心态很像。但买房一般可以保值，收购公司，可是个大技术活。

王川投资第一法则是： 如果你可以用简单直接的方式投资获利，就不要用复杂费力的方式去投资。仔细把这句话重复一下，想想有没有说你自己。看看周围，有多少人挖空心思较尽脑汁为去寻找更高的回报，去从事耗时费神自己不胜任的活动而伤痕累累。可以一剑封喉，就不要多余的花拳绣腿。可以用简单算术获利，就不要去搞复杂数学模型，在N阶导数的计算中去捡钢镚。可以用国债获利，就不要浪费时间分析公司报表技术曲线炒股票。

这种毫无章法的投机方式，和没受过训练的人打架一样，毫无二致。初学太极的人，师傅会让你先靠着墙练站桩，锻炼大腿力量。刚开始，你可能坚持不到三十秒，大腿就急剧地抽搐，慢慢地坚持时间可以越来越长，大腿肌肉越来越有力。这种看似枯燥的练习，为搏击实战打下了坚实的基础。基础打好之后，下面的学习提高都会自然而然。

这实际上有个矛盾。资金越少的投资者，希望完全靠投资收入为生，赚快钱的欲望强烈。往往没有章法，频出昏招，回报不好。经验丰富，资金充裕的投资者，有别的收入来源，不需要马上赚钱，可以非常耐心地等待时机，在自己选择的战场，自己选择的时机，用自己选择的方式战斗，轻松地获得丰厚的回报。然后形成良性循环，生意越做越大。

我后来通过自己的公司，两周就把贷款做下来，顺利完成房子的交割。这件事给我的教训是，在生意场上，“不要低估别人侮辱你智商的决心，永远要有第二个选择以防不测。”

弗老师的故事, 也是对迷信简单数学模型, 喜欢跟风追涨的投资者的一个 严重警告: 对于金融资产，过去七十年的历史纪录也不能保证未来的趋势。变化有时突如其来，再加上流动性的突然消失,资产的价格变动,没有神圣不可逾越的边界。

2001年初，互联网泡沫破灭的时候，亚马逊现金流吃紧，为了尽快实现短期 盈利，公司财务总监说服贝索斯悄悄把部分书籍的售价提高。但是不久，在 贝索斯和Costco(好事多)的创始人之一，Jim Sinegal会面之后，他又变 了主意。Sinegal在给贝索斯介绍自己的商业模式时说:“客户的忠诚度是最重要的。 好事多所有的产品价格都只比成本高14%。即使有时可以多赚，也不会这样做。好事多的利润主要是来自于每年的会员费。但是客户知道，他们来好事多买东西，肯定都是非常便宜的。最终，由于每个客户购买量大，好事多再以自己的巨大体量，向供应商施压，要求获得最低的供货价格。 ”Sinegal 说到:“我的哲学是, 价值胜于其它所有东西。人们来我们这里买 东西，是因为我们提供价值。我们坚持每天做到这一点。”

那么为什么那么多人不愿意和别人分享呢? 我觉得这里面有两个原因:第一，虽说文人相轻，其实理工科的人相轻也毫不含糊。潜意识里总是和别 人攀比，看不得别人比自己好。但这是一个资源共享，共同协作的时代。周 围的人做得好，你也有更多的资源提升自己的事业。第二，许多理工男只局限在自己的小圈子、小天地里。他们完全没有意识到， 也看不到，主动多和别人分享，广结善缘，对扩大自己视野和圈子，对事业 进步的潜在回报，要远远大于那一点点付出。

真正的英雄，在事业的发展途中，他们会不断问，这个东西真的那么重要， 必不可少吗?他们不人云亦云，他们谢绝那些不重要的东西，集中自己的精 力在重要的，力所能及的事上。他们可能短期会得罪一些人，但是他们知道，只有依靠聚焦, 把重要的事情做好了，才能真正驾驭自己的生活和事业,赢得长期的尊重。

什么是投资的顶层设计?在我看来，它有这么几个组成部分:
1. 身体健康和心理健康。
2. 广泛的人脉关系和深厚的信誉资本。
3. 宽广的知识面，和分析解决新问题的能力。
4. 资本在各类资产中的合理配置和稳健的风险控制体系，慎用杠杆，最好不用杠杆。
5. 适合个人风格的，学习发现和捕捉新的投资机会的体系。

第二，要正确应对工作生活中的压力。这里打一个太极拳的比方。工作生活中的压力，就像搏击中对手的出拳。上策是躲开，让对手扑空。如果无法躲开，太极高手的应对方法通常是，通过身体的移动，多点和对方的出拳不同角度的分几次接触，把本来对手十分的打击力，化解为只有两三分，这样把自己受到的伤害降到最低。工作生活中的压力，一种是完全心理上的，可以彻底忽视，完全躲开的压力。比如要面子，和朋友各种攀比，小孩教育上唯恐“输在起跑线上”的各种忙 碌，面对世俗的流言蜚语等等。躲开这种压力，靠的只是强大的内心自信和独立。另一种压力，来自客户，老板等等，不能完全躲开。这时就要学太极了，不可直面被动挨打, 把自己累得半死，而要通过和对方的不断沟通,完成力所能及的工作量, 缓解稀释不合理的要求, 但始终坚持不损坏自己身体健康的红线。暂时得罪客户和老板，天不会塌下来;但得罪自己的身体健康，天真的会塌下来。
