#+title: 婚纱摄影

从个人经历来看的话，真心觉得《蒙娜丽莎》不错，算是给《蒙娜丽莎》做一个广告吧。如果朋友们在迷茫选择哪一家的话，我希望自己的经历可以给《蒙娜丽莎》加一些分。但是不管怎样，都真心希望朋友都可以拍出自己满意的婚纱照。

准备拍婚纱摄影之前，对于婚纱摄影没有任何了解。不知道价格以及自己会拿到那些东西（可能自己不太敏感，感觉老婆对于这方便相当敏感，毕竟一生也就拍这么一次）。听同事说有影楼以及摄影工作室，都说摄影工作室价格相对便宜一些，而且通过后期制作能够得到和影楼一样的效果。不过说实话，看来这么多家我确实没有分出哪家是影楼，哪家是工作室。现在基本上稍微好点的婚纱摄影都会有自己的室内布景以及后期制作团队，所以差别真的不是很大。以自己现在体会来看的话，主要是看重三个方面：
- 口碑。主要是在大众点评上面看的。当然上面有托也有枪手，所以只是作为小部分参考意见。
- 价格。相同效果或者是效果相差不大的话，当然希望价格便宜最好。
- 服务。有几套衣服，拍摄多少张，后期制作多少张，多少张入册，几个景，室内室外各几个，外景的话是否会有包车和管饭，拍摄几天，是否一对一服务，以及最后拿到的东西有哪些等等。

自己在网上搜索婚纱馆确实是非常费力（http://jiehun.55bbs.com /这里倒是列举了很多，不过好多东西还是当面了解才更清楚），还好在找婚纱馆的时候，大概2011冬季的北京婚博会举行了。当时听说有很多和婚礼相关的单位都会去哪里做宣传以及介绍自己的服务。通过这种方式来更多地了解不同的婚纱馆是一种很方便的方式。（婚博会提前注册，但是告诉朋友们，婚博会其实你只能进去一天，而且中途是不能出来的，所以还是必须之前先了解自己有意向的商家。婚博会只是方便当前沟通，之前还是必须做好功课的）我和老婆在网上看了下面这些婚纱馆的评价：
- 爱视觉高端婚纱摄影私人会所(图)-北京-大众点评网
- V2视觉摄影(大悦城店)(图)-北京-大众点评网
- 薇薇新娘(东四店)(图)-北京-大众点评网
- 纽约纽约时尚婚纱摄影(西单店)(图)-北京-大众点评网
- 八月照相馆(图)-北京-大众点评网
- 施华洛婚纱精品概念馆(崇外店)(图)-北京-大众点评网
- 艺蒂视觉摄影工作室(图)-北京-大众点评网
- 蒙娜丽莎婚纱摄影(东单总店)(图)-北京-大众点评网
- 巴黎婚纱摄影(东四店)(图)-北京-大众点评网
- 聚焦摄影(世界公园店)(图)-北京-大众点评网
- 城市花园尊贵婚纱电影城(南三环店)(图)-北京-大众点评网
- 金夫人婚纱摄影(东单店)(图)-北京-大众点评网
- 水晶之恋(世界公园店)(图)-北京-大众点评网
- 悦己视觉婚纱摄影(图)-北京-大众点评网
- 零点视觉摄影工作室(左安门店)(图)-北京-大众点评网
- 茱莉雅婚纱摄影(西四魅丽店)(图)-北京-大众点评网
我记得婚博会那天是2011.12.17，我老婆还有伟子三个人一起去的。当时比较看好的就是八月，蒙娜丽莎以及聚焦摄影。因为我们急着要拍摄，所以打算放弃外景让影楼多给点内景的优惠。但是八月以及聚焦摄影的话，坚持都是说分两次拍摄。12月份拍摄的是内景，然后等到来年的3-4月份再拍摄外景。感觉八月后期制作是很不错的，但是拍摄照片本身来说的话就有点过于单调。聚焦摄影的话后来也不知道为什么排除了，所以就定在了蒙娜丽莎。虽然婚博会说至少能省1000元，但是事后发现那是扯淡。那天我们去谈蒙娜丽莎的话，店员给出一个5888的套系，实际回去后发现那个就是蒙娜丽莎官网上的4888的套系，难怪能节省1000元呢。反正老婆最后面也磨破了嘴皮子，以5888元要下了上面写的6888的套系，并且附加一个伯爵庄园的场景还有1对1服务，不过回去发现要求的内容基本上和官网上的5888套系相当，至少稍微多了一些服务罢了。

关于价格的话就是5888.很多婚纱店可能会存在后期费用，但是蒙娜丽莎没有。其他的费用无非就是请参与我们摄影的化妆人员以及摄影师吃一个简单的中午餐，大概也就是200多。取件的时候如果你还想得到更多的精修片的话那么需要加额外的费用。除此之外，我没有给其他的费用。另外从拍摄，到看片，到选片，精修以及取件都非常按时完成，这点非常省心，而且工作人员也是非常地积极配合。在拍摄之前可能需要试纱相当于找找穿婚纱的感觉，我记得是2011.12.24去的。因为第二天2011.12.25去看了金陵十三钗以及买了一件Vero Moda的衣服1400（但是元旦之后就降价到了700）。因为那周周六周日摄影师都去学习了，所以也就安排在了周一也就是2011.12.26拍摄。关于服务的话，我大致列一些主要的（因为没有了清单可能有些项目会遗漏）
- 1天拍摄完成。大概从早上8:00到晚上8:00。（所以是非常累的，而且如果要拍摄外景的话会更累）。
- 六个场景。必须确保每个场景都有不同衣服，已经平均多的照片数。
- 六套衣服。衣服用场分为4个区。经理说我们是VIP的时候，感觉我们就是最好的了。其实还有皇室VIP区。所以一定不要相信名字，而要看清楚一共有多少个衣服区。这种东西会害死人的，尤其是如果去了之后发现自己衣服不好看，而又不能换成其他区的衣服，心里就会不舒服。
- 160张原片，70张精修片。其实70张精修片已经很多了，好好挑选就是。
- 化妆师以及摄影师是否是1对1.
- 化妆用品是否摄影店提供。如果是要拍外景的话，那么门票以及行车费用是怎么计算的。
- 取件的物品有哪些。这个我忘了，可能她想得提来。
- 我记得大概有很大的绢丝海报，三幅壁画，两个大相册，两个小相册以及四个桌摆吧。不过其实个人感觉差不多就行了，要是拍摄质量好的话，后期自己也可以在淘宝上要人加工制作。

拍摄经历到没什么特别的。因为早上8点拍摄，需要6：30左右在三元桥等班车。所以大概4:30就起来了。老婆化了一个淡妆我整理了一下头发就出发了。到了那里等班车带我们到摄影基地就开始摄影。我倒是忘记了化妆师的名字，就是还记得摄影师叫做宋立光，造型师或者是说是摄影师的助手叫做太郎。他们拍摄过程中不断地告诉我们应该怎么做pose，并且告诉我们这么做pose为什么不好看等等。进入拍摄状态之后就会感觉那么紧张了。可能拍完一个景之后老婆需要换妆，时间可能30-40分钟左右。摄影基地也有两个电视用于点播DVD电影的，比如人在囧途，Avatar，让子弹飞等这些电影，所以等换妆时间就不会那么无聊了。大概拍摄到晚上8点左右才全部完成（才拍摄180张左右，所以想要拍250张的同学自己算算，一天拍完的话是否真的会吐血）。总之感觉拍摄基地的服务人员态度真的非常好，而且拍摄环境也是很不错的。8点左右我们从拍摄基地打车到三元桥，然后坐地铁回去了。后面就是选片已经看精修效果了，这些到都没什么。最后取件确实坑爹了一把。老婆有事情，所以让我一个人去取件。蒙娜丽莎店面在灯市口那个地方一个十字路口处。怎么说那个地方呢？那个地方确实非常方便，因为临近地铁并且很繁华，打车也非常方便。但是如果你是想搬东西的话，那么可以说非常不方便。我当时觉得就这么几个东西，我可以一个人拿回家，大不了分两次，做地铁很方便。但是谁知道，蒙娜丽莎在取件的时候不允许分两次拿，必须一次拿完。那几个壁画又巨沉，反正拎着这个东西之后几天我感觉我的腕子被扭伤了。开始一经理好心地让一个工作店员陪同这个店员的朋友，帮我提到离店面200米左右的地方去拦出租车，但是那个店员相当低不靠谱啊说有事就走了，而那个店员的朋友和蒙娜丽莎没有半毛钱关系，不过还是好好心地帮我拎回到了蒙娜丽莎。当时我非常生气，和经理说要不你就找个出租车过来拿上去，不然这东西我是不会收的。最后经理让一个靠谱一些的工作店员带我走了向北面走了400米左右（我感觉我的腕被扭得不行了），最后拦下了一个出租车从灯市口运到了立水桥（50+RMB）。总之取件过程非常扯淡。但是最后凭心而论，可能门市店员非常势力（也有非常好心的店员），但是蒙娜丽莎的摄影基地人确实不错，所以总体觉得还是很不错的。谢谢拍摄基地为我们服务的工作人员：）. –end

-----
update@201509:

比较扯的是, 他们不管配送相册线框, 得去自取. 但是相册相框非常多, 私家车根本放不下, 况且我北京也从没有过车, 请个搬家的打车又觉得略亏. 而且他们要求一次全部取完. 最后一个人去提片, 寄希望出租车可以放下. 可是那个地方是绝对的繁华地带, 很难达到出租车. 最后是我和一个店里的小哥, 提着N多相框, 走了一段路到一个比较偏的路口, 硬生生地将相册相框塞到了出租车里面, 然后拿回家.

后来从北京搬家回天津, 本来想这不要那些相册相框, 因为那些相册相框实在无法用快递. 最后我还是请了搬家公司, 开了一趟车把在北京几年留下来的东西, 全部搬回了天津, 当然也包括了这些相框. 事实证明我的选择是对的, 这些结婚照放在家里非常合适, 也很有意义.
