#+title: Taking PHP Seriously

[[https://slack.engineering/taking-php-seriously-cf7a60065329#.9b02c655s]]

生态环境和语言本身一些特性非常适合Web开发. Hack和HHVM在一定程度上弥补了PHP的部分缺陷，包括类型检查，错误处理以及性能提升。

Most programmers who have only casually used PHP know two things about it: that it is a bad language, which they would never use if given the choice; and that some of the most extraordinarily successful projects in history use it. This is not quite a contradiction, but it should make us curious. Did Facebook, Wikipedia, Wordpress, Etsy, Baidu, Box, and more recently Slack all succeed in spite of using PHP? Would they all have been better off expressing their application in Ruby? Erlang? Haskell?

Perhaps not. PHP-the-language has many flaws, which undoubtedly have slowed these efforts down, but PHP-the-environment has virtues which more than compensate for those flaws. And the options for improving on PHP's language-level flaws are pretty impressive. On the balance, PHP provides better support for building, changing, and operating a successful project than competing environments. I would start a new project in PHP today, with a reservation or two, but zero apologies.

Finally, the fact that PHP programs operate at a request level means that programmer workflow is fast and efficient, and stays fast as the application changes. Many developer productivity languages claim this, but if they do not reset state for each request, and the main event loop shares program-level state with requests, they almost invariably have some startup time. /*For a typical Python application server, e.g., the debugging cycle will look something like "think; edit; restart the server; send some test requests." Even if "restart the server" only takes a few seconds of wall-clock time, that takes a big cut of the 15–30 seconds our finite human brains have to hold the most delicate state in place.*/

/*I claim that PHP's simpler "think; edit; reload the page" cycle makes developers more productive. Over the course of a long and complex software project's life cycle, these productivity gains compound.*/
