#+title: Ten Rules for Negotiating a Job Offer

part1: https://medium.freecodecamp.org/ten-rules-for-negotiating-a-job-offer-ee17cccbdab6

part2: https://medium.freecodecamp.com/how-not-to-bomb-your-offer-negotiation-c46bb9bc7dea

** What it means to “get a job”

求职也可以认为是双方之间的劳动力买卖。就像买商品一样，不可能别人出什么价就给什么价，至少要货比三家吧。

Employment is just striking a mutual deal in the labor market.

Like any market, the labor market only functions well if it’s competitive. This is the only way to ensure fair and equitable pricing. Imagine you were a farmer selling watermelons. Would you just sell your watermelons to the first buyer who agreed to purchase them? Or would you survey the marketplace of buyers, see the best price (and business partner) you could get, and then make an informed decision on which buyer to sell to?

** The role of negotiation

协商是达成交易的过程中一个非常自然的部分，所以不会有人因为你协商而怪你。

Negotiating is a natural and expected part of the process of trying to make a deal. It’s also a signal of competence and seriousness. Companies generally respect candidates who negotiate, and most highly attractive candidates negotiate (if for no other reason, because they often have too many options to choose from).

At the risk of spouting truisms: always, always negotiate. It doesn’t matter how good or bad you think you are. You never damage a relationship by negotiating.

** The ten rules of negotiating

总结下来的十条原则：
- Get everything in writing（各种条件最好都记录下来）
- Always keep the door open（永远保持开放状态，不要commit）
- Information is power（对自己的信息要保管好）
- Always be positive（保持积极的态度，不管是对现在的公司，还是正在谈的公司）
- Don’t be the decision maker（不要做决策制定者，不要让自己一个人承担压力）
- Have alternatives（保持备选项）
- Proclaim reasons for everything（对所有事情找到一个可以解释的原因）
- Be motivated by more than just money（除了钱之外还要找其他动力）
- Understand what they value（了解他们所需要的人）
- Be winnable（？？我理解这点是，自己要有意向去这个公司，不要play games)

** Rule #1 of negotiating: have everything in writing.

The rule from here on out is that everything significant you discuss will have some kind of a paper trail. Often, the company won’t even send you an official offer letter until a deal is finalized. So it falls to you to confirm all of the important details in subsequent e-mails.

** Rule #2 of negotiating: always keep the door open.

在自己完全确定之前，不要将自己承诺给某个offer，保持自己的机会优势。虽然recuriter会不断地push你尽可能地早的完成决定，但是不要在这种压力下面屈服。

#+BEGIN_QUOTE
Your recruiter will now say something along the lines of “so what do you think?”

This seems innocuous, but your reply here is critical, because there’s a lot you can say to weaken your position. This is your first decision point.

A decision point is a moment in the negotiation where your interlocutor wants to compel you to make a decision. If they succeed in tying you to a position, they will close the door on further negotiating. Of course “what do you think?” is a subtle prod. But it is the beginning of many attempts to get you to make a premature commitment.

Never give up your negotiating power until you’re absolutely ready to make an informed, deliberate final decision.

This means your job is to traverse as many of these decision points as possible without giving up the power to continue negotiating. Very frequently, your interlocutor will try to trick you into making a decision, or tie you to a decision you didn’t commit to. You must keep verbally jiu-jitsu-ing out of these antics until you’re actually ready to make your final decision.
#+END_QUOTE

** Rule #3 of negotiating: information is power.

下面是典型的两种错误回复：
1. 直接接收offer
2. 亮出自己的底价

#+BEGIN_QUOTE
There’s an uncomfortable silence by now, and their “what do you think?” is hanging in the air.

If you say “yes, that sounds amazing, when do I start?” you implicitly accept the offer and completely close the door on the negotiation. This is your recruiter’s number one favorite thing to hear. It stands to reason you probably shouldn’t do this.

But their second favorite thing to hear you say is “can you do 90K instead of 85K?” This also closes the door, but for a different and more subtle reason. And it’s the number one reason why most people suck at negotiation.
#+END_QUOTE

无论如何这两种行为都是暴露自己的位置，让自己在协商中处于不利的地位。现在的猎头可能在招聘一个重要的人员之前已经从很多渠道了解到这个人的基本情况（比如工作时间，当前薪资，曾经担任的职位等等），除非你对这个公司也有很深入的了解，否则在信息对称上来说，你是处于不利的地位的。不过即便如此，还是有很多信息猎头是没有办法知道的，所以这些信息你一定要保护好，因为他是协商的砝码。

#+BEGIN_QUOTE
To protect your power in the negotiation, you must protect information as much as possible.

A company doesn’t give you insight into what it’s thinking. It doesn’t tell you its price range, how much it paid the previous candidate with your experience, or anything like that. It intentionally obfuscates those things. But it wants you not to do the same.

A company wants to be like a bidder in a secret auction. But unlike the other bidders, it wants to know exactly how high all of the other bids are. It then openly intends to exploit that knowledge, often by bidding one cent more than the second highest bid.

Yeah, no. Screw that. It’s a silent auction, and to keep it that way, you must protect information.
#+END_QUOTE

** Staying positive is rule #4 of negotiation.

无论最后协商的结果如何，你都需要对公司保持积极的态度，愿意来这家公司工作，而不是带着消极情绪来的。

#+BEGIN_QUOTE
A company is making you an offer because they think you’ll do hard work for them if they pay you. If you lose your excitement for the company during the interview process, then they’ll lose confidence that you’ll actually want to work hard or stay there for a long time. Each of those makes you less attractive as an investment. Remember, you are the product! If you become less excited, then the product you’re selling actually loses value.

So despite whatever is happening in the negotiation, give the company the impression that 1) you still like the company, and that 2) you’re still excited to work there, even if the numbers or the money or the timing is not working out. Generally the most convincing thing to signal this is to reiterate you love the mission, the team, or the problem they’re working on, and really want to see things work out.
#+END_QUOTE

** Rule #5 of negotiation: don’t be the decision-maker.

怎么说呢？即便是最坏的事情发生了，你也可以不是需要负责的人，而是其他与这个面试不相关的decision maker.

#+BEGIN_QUOTE
Even if you don’t particularly care what your friends/family/husband/mother thinks, by mentioning them, you’re no longer the only person the recruiter needs to win over. There’s no point in them trying to bully and intimidate you; the “true decision-maker” is beyond their reach.

This is a classic technique in customer support and remediation. It’s never the person on the phone’s fault, they’re just some poor schmuck doing their job. It’s not their decision to make. This helps to defuse tension and give them more control of the situation.

It’s much harder to pressure someone if they’re not the final decision-maker. So take advantage of that.
#+END_QUOTE

** Getting other offers

手中同时拥有几份offer对于自己加码会更加有利。这点非常容易理解，文章对这个原因也做了深入分析。

#+BEGIN_QUOTE
The truth is, knowing that someone has passed your interview just doesn’t say that much about whether they’ll be a good employee. It’s as though you knew nothing about a student other than their SAT score. It’s just not a lot of data to go off.

Nobody has solved this problem. Not Google nor anyone else.

And this is precisely why it’s rational for companies to care that you’ve received other offers. They care because each company knows that their own process is noisy, and the processes of most other companies are also noisy. But a candidate having multiple offers means that they have multiple weak signals in their favor. Combined, these converge into a much stronger signal than any single interview. It’s like knowing that a student has a strong SAT score, and GPA, and won various scholarships. Sure, it’s still possible that they’re a dunce, but it’s much harder for that to be true.
#+END_QUOTE


** How to approach exploding offers

对于exploding offers, 方法是保持礼貌的态度，表达自己需要时间来进行决定。可能对于他们来说，exploding offer类似于一种态度和傲娇（我认为我们公司非常牛，所以我们发出的offer都是exploding offer, take it or not)，他们会不断地强化这点。你不能对这种exploding offer置之不理，对大家都没有好处，最好的方式就是表达自己的意愿，需要延长offer的时间。

** The Negotiating Mindset

尝试从各种角度来最大化双方的利益

#+BEGIN_QUOTE
Do not fall into the trap of valuing companies solely along one dimension. That means don’t just value companies based on salary, equity, or even on prestige. Those are all important dimensions, but so are cultural fit, the challenge of the work, learning potential, later career options, quality of life, growth potential, and just overall happiness. None of these inherently trump any of the other. Anyone who tells you “just choose wherever you think you’ll be happiest” is being just as simplistic as someone who says “just choose the one that offers the most money.” All of these things matter, and your decision should be genuinely multi-dimensional.

The more companies you talk to, the more likely you are to find a company to which you are significantly more valuable than the rest. Chances are this is where you’ll be able to negotiate your strongest offer. It might surprise you which company this turns out to be; keep an open mind, and remember that a job search is a 2-sided process.

One of the most valuable things you can do for yourself in this process is to really try to understand how employers think and what motivates them. Understanding your interlocutor is extremely important in negotiation, and we’ll be exploring that a lot in the next blog post.
But most of all I want to emphasize: be curious about the other side. Try to understand why employers think the way they do. Be sympathetic toward them. Care about what they want and help them try to get it. Adopting this mindset will make you a much stronger negotiator, and accordingly, a much better employee and team member.

#+END_QUOTE

一个job offer在福利上可能有下面这些，所以不要从单一的维度来协商：
- salary
- signing bonuses
- stock
- year-end or performance bonuses
- commuter benefits
- relocation expenses
- equipment
- an educational stipend
- a childcare stipend
- extra vacation time
- a later start date
- getting a dedicated hour a day to work out or study or meditate or play solitaire.

** Rule #6 of negotiating is: have alternatives.

alternatives除了其他公司的offers之外，还意味着其他的可能性，比如是进入学校等等。另外注意，你现阶段的工作可能也是你的best alternative, 因为不接受这份offer你可以还继续呆在这个单位。

#+BEGIN_QUOTE
Note: one of the biggest mistakes I see here is from people who are currently working. If you already have a job, staying where you are is often your BATNA.

This means if you tell your interlocutor that you hate your job, then they know your BATNA sucks, and have no incentive to negotiate with you (on top of potentially thinking that you’re a negative person). Always emphasize the pros of your current company, your seniority, your impact, and whatever else you like about where you currently work.

You should make your decision seem like a genuinely difficult one — then it will appear to be a strong BATNA.
#+END_QUOTE

** What a Job Negotiation Means to an Employer

Job协商成本非常高，所以你也要利用好这个优势，他们不太可能因为你协商而就直接fail你，考虑到招聘成本问题。

** How to Give the First Number

当对方要你给出报价时，尽量把这个报价先丢给对方，以免透露出自己的低价。如果对方一定要你给出范围的话，

#+BEGIN_QUOTE
“Well, okay. I know that the average software engineer in Silicon Valley makes roughly 120K a year in salary. So I think that’s a good place to start.”
#+END_QUOTE

给出业界报价，但是留有余地。

** rule #7: proclaim reasons for everything.

很多人不想表现出贪婪，但是有时候，尤其是在这个时候必须表现出。我们可以为他们找一个合理的理由。

#+BEGIN_QUOTE
I suspect this is the primary reason why so many candidates recoil from negotiating. They don’t want to feel greedy. It goes against all of their social conditioning. And yet, there are some situations in which most people would be totally fine negotiating.

Specifically, when they have to.

If you had to raise your salary or you wouldn’t be able to afford rent, or if you had to negotiate health insurance to cover a medical condition, you’d negotiate without a twinge of regret. The difference? That you have a reason for what you’re requesting.

It’s kind of a brain-hack, both for yourself and for your negotiating partner. Just stating a reason — any reason — makes your request feel human and important. It’s not you being greedy, it’s you trying to fulfill your goals.
#+END_QUOTE

** rule #8: be motivated by more than just money.

#+BEGIN_QUOTE
Actually be motivated by other things. You should be motivated by money, too, of course, but it should be one among many dimensions you’re optimizing for. How much training you get, what your first project will be, which team you join, or even who your mentor will be — these are all things you can and should negotiate.
#+END_QUOTE


** rule #9 is: understand what the company values.

公司不太可能从在工资上给你增加的时候，可以尝试从其他方面增加比如奖金或者是股票，又或者是休假时间等，还可以是工作的团队，都是不错的选择。

#+BEGIN_QUOTE
salary is almost always the hardest thing to give, for a few reasons:
- It must be paid year after year, so it becomes part of a company’s long-term burn rate.
- It is almost always the thing that people gossip about, so paying someone significantly more salary can cause unrest.
- It tends to be the most tightly constrained by pay bands, especially at large companies.

So if you want more financial compensation, you should think about structuring as much of it as possible outside of salary. A signing bonus, for example, is easier to give than salary. A signing bonus has the advantage of only needing to be paid once. It gets the candidate excited about joining (because everyone likes wads of cash), and it’s generally not as public.
#+END_QUOTE

** Rule #10: be winnable.

#+BEGIN_QUOTE
This is more than just giving the company the impression that you like them (which you continually should). But more so that you must give any company you’re talking to a clear path on how to win you. Don’t BS them or play stupid games. Be clear and unequivocal with your preferences and timeline.

If there is nothing that a company could do to sign you, or you don’t actually want to work for them, then don’t negotiate with them. Period.

Don’t waste their time or play games for your own purposes. Even if the company isn’t your dream company, you must be able to imagine at least some package they could offer you that would make you sign. If not, politely turn them down.

It costs each company money to interview you and to negotiate with you. I didn’t negotiate with every company I received an offer from, but if there was one key mistake I made in my job search, it was that I still negotiated with too many (in large part because I didn’t think my job search would be successful).
#+END_QUOTE
