#+title: Ten Career Lessons
https://rishadt.wordpress.com/2015/04/18/ten-career-learnings/

10条职业规划的建议，早中晚三个阶段各有不同的建议。

- The First Decade
  - Find the least sucky job you can. 刚入职场的时候需要调整好心态，不要过分强调自己的想法。在这个阶段学习和积累是最重要的。
  - The Trend is your Friend. 不要过分在意初期薪酬，更应该在意自己做的方向是不是未来趋势。Shakespeare wrote “we must take the current when it serves. Or lose our ventures”.
  - Plan and make decisions over a long horizon. 因为从业生涯时间会非常长，所以在做规划和决定的时候应该考虑长远。
  - Even the best jobs are only good seventy percent of the time. 你可能要做很多未知的事情，你会怀疑自己是否做的好，但是这正是你快速发展的标识。
  - Compete against yourself rather than with others. 不要和别人竞争，而应该和自己竞争，这样可以省去很多政治斗争和口舌之争，并且这才是你自己的竞争力。"learning from those you admire and respect or expertise you appreciate".
- The Middle Years
  - Who you work for is critical so choose your boss well. 选对老板。好的老板可以给你提供更多的机会，并且不断地对你发起挑战来推动你的发展。
  - Find Fit. 综合自身优势，兴趣，以及市场需求，来选择自己做的事情。
  - Build a Personal Brand. 创建个人标签
- The Later Years
  - Unlearn. Transform. Re-Invent. 保持学习。如果之前你帮助过许多人的话，现在他们反过来也会帮助你。
  - Build a portfolio career and start giving back aggressively. 工作性质应该逐渐转向咨询，建议，教学方面来回馈社会
