#+title: 那个人好像一条狗

http://www.guokr.com/question/185206/

我习惯把看《大话西游》分成三个层次。你看大话西游，看得捧腹大笑，龇牙咧嘴，那么你是第一层。你看完大话以/后，突然感觉被一种无法名状的痛击中，你发现你眼里不知道什么时候已经有了泪水，有了无奈，那么你是第二层。当演员表开始滑动，你才意识到“end”三个字母直接滑进你的脑海，不知不觉泪流满面，傻傻坐在那里，不知道该去哪里，你感到一股深入骨髓的悲哀无无奈，那么，你是第三层了。

我说的《大话》，自然是两部一起说了。小时候被疯疯癫癫的周星驰征服，笑得比谁都欢，常常和同学讨论经典台词，他的无厘头伴我走了一个童年。 人们总是喜欢有意无意谈起看过书或者电影的次数来提醒别人自己有多了不起，看得多么透彻。可是理解这种东西，还是靠年龄，或者说阅历。

今天看韩寒博文，让我思绪万千，就那一句话，我突然顿悟了。 一直处在第二层，认为《大话》就是一无比凄美的悲剧爱情，一场无比搞笑的闹剧，今明白了什么。那是一种无奈，叫“男孩到男人”的成长。 大话西游是个寓言，躲在神话故事里看似很搞笑很浪漫，那种深深的痛，我不愿意再体会。 ”那个人样子好怪。” “我也看到了，他好像一条狗。” 大话西游 的最后一句对白你还记得么。其实这一句，就是整个电影的主题。用男人的思想就是：一个男人的无奈。 他骂的人，不就是自己吗？这种感觉，我说不清啊。曾经也接触过这类藏在深处的寓言，是《悟空传》，同样是一种无奈，没看过的真需要去看看，不扯多了。

大话西游里，你喜欢孙悟空还是至尊宝？答案不言而喻。至尊宝放荡不羁，无拘无绊，但敢爱敢恨，纯真可爱。孙悟空到处受限，爱不能言，残忍无情。可是谁是英雄？至尊宝是男孩，而孙悟空是男人，男人总是多了些什么，我们把它叫做成熟。从至尊宝到孙悟空，我们叫做男人的成长。

”等你明白了舍生取义的道理，你自然会回来和我唱这首歌的。”唐僧是谁？是那首only you让我们捧腹的人？你有没有想过他像我们的父母老师，说着那些我们不爽的话，然后我们就不听话地对着干叛逆了。长大以后，感谢就成了我们的主流思想，或者是后悔没有听他们的话。 ”我知道有一天他会在一个万众瞩目的情况下出现，身披金甲圣衣，脚踏七色云彩来娶我。”紫霞仙子是那种让任何男人都爱的女人，事实上也代表了所有女人。她的要求难吗？不难。至尊宝做到了吗？没有。其实每个女人要的都不多，但是男人就是做不到。

那风光不可一世的牛魔王，我认为他像一只无形的大手，抢走你要的东西，你爱的紫霞，我们叫它困难。作文我们写过太多了，就不说它了。 说来真是讽刺，要打败“牛魔王”，就需要戴上那个束缚自由的圆环，这就是一种无奈，逼着我们屈服。你想要得到吗？那么好吧，你先放弃吧。你必须做出选择，作至尊宝，那么快乐总是很短暂，作孙悟空，你就要忍受无尽的痛苦。这个世界的规则好象是牛魔王制定的，那么恶毒，在它面前，那段经典的台词显得多么的苍白无力，只能成为一个男孩子蜕变成男人的时候留在心底最深的伤痛。 最后，他还是戴上了那条锁键，他醒悟了吗？没有，他别无选择，他要就紫霞，要杀牛魔王。 他还是不满，于是就虚构了一段，借夕阳武士的口，说自己的生活就像一条狗。
