#+title: 创业维艰：如何完成比难更难的事

-----
直到那一刻之前，我从未真正做出过任何重大选择。我觉得我精力无限，生活中，我可以同时做很多事情，但父亲的话却突然令我明白，如果沿着现在的轨道继续前进，我也许会失去的自己的家庭。所有事情一起抓，就会在最重要的事情上遭遇失败。我第一次迫使自己不要只按轻重缓急的标准来看世界。过去的我一直以 为，自己既能干好事业，又能兼顾所有的兴趣爱好，同时还能维护好家庭。而且，我总把自己摆在首位。当你成为某个家庭或某个团体的一分子时，这种思维方式会令你陷入麻烦。在我心里，我坚信自己是个好人，毫不自私，但我的所作所为却暴露出我并非送祥的好人。我绝不能像这样继续幼稚下去，我必须分清主次轻重，成熟起来。我必须先考虑自己最关心的人, 然后再考虑自己。

-----
健康的企并文化就像过去的路由器协议：好事不出门，坏事传千里

纵观那些失败的公司，你会发现很多员工在公司倒闭之前就知道公司的症结是什么。既然知道这些致命的问题，他们为什么不说呢？原因往往是该公司的文化阻碍了坏消息的传播，真相始终处于稳匿状态，等到采取行动时却为时已晚。

健康的企业文化会鼓励员工公开坏消息。只有允许自由并公开讨论问题，公司才能迅速解决同题。企图掩盖同题与只会令所有员工感到灰心。因此，CEO应该采取的做法是：建立一种奖励文化，而不是惩罚文化,，对那些公开提出同题并为其找到解决办法的人予以奖励。

可见，我们要谨防那些阻止信息在公司内自由流动的所谓管理箴言。例如，“不出解决方案，就不要把问题报告给我。”如果有一个重大问题，员工解决不了怎么力？如果有一名工程师发现一个产品的营销方式存在一个重大缺陷，他该怎么办？难道你真想让他将这一问题埋在心里吗？诸如此类的所谓管理箴言在理论上也许是员工们追求的理想，但是也有可能阻碍信息的自由流动，而且这些信息对公司的发展至关重要。

-----
和平时期的世界和你每天必须为生活苦苦挣扎的世界完全不同。和平时期，人们有时间关注言行是否得体​​，长远的文化影响以及人们的情感这类问题。而在你为生活苦苦挣扎的时期，最重要的是奋勇杀敌，带领自己的队伍安全抵达目的地。我正处于这种状态中，需要一名作战的将军。我需要马克· 克兰尼。

招聘的最后一步是我向马克· 安德森进行汇报。作为公司创建者和董事会主席，马克·安德森的意见对董事会影响极大。可惜他对克兰尼的感觉依然不太好。马克·安德森非常信任我，无论他本人对应聘者是否喜欢，他都会让我自己决定招聘人选，但是对我来说他的认可很重要。

我让马克·安德森先说，因为尽管他一直是这个办公室里甚至全世界最聪明的人，他自己却非常谦逊，从不相信人们夸他聪明的活，这一点令他很容易被人忽视。他开始列举克兰尼的缺点：长相和声音都不适合当一名销售主管，毕业学校名不见经传，令他感觉不舒服。认真听完之后,我回答说：“你说的每一条，我都同意。但是，克兰尼是一个销售专家，他的销售管理水平远远超过我所认识的每一个人。如果他身上没有你说的送些毛病，他也不全愿意加入我们这样的公司，说不定他会成为IBM的CEO呢！”

-----
对管理人员的培训需遵循一条黄金法则：自己的员工要自己亲自辞退，不能将这项工作推卸给人力资源部或某个更严厉的同事，更不能像电影《在云端》中那样雇用一家外包公司来完成。

为什么这么严格？为什么不能找些强势的管理者出面，替你完成这一棘手任务？因为人们不会记得自己在公司效力的每一天，但他们一定会记得你将他们开掉的那一天。他们会记得那一天的每一个细节，这些细节关系重大。公司的声誉和管理人员的声誉都取决于你的表现：昂首挺胸，勇敢面对那些曾经信任你为力你辛勤工作的员工们。员工们会想：既然你雇用了我，我勤勤恳恳地地为你理头苦干，我希望你能有勇气亲自辞退我。

-----
你想促成的事情有些或许可以量化，有些则不可以。你不能只汇报量化目标，而忽视质化目标，因为质化目标才是最重要的目标。仅仅按照数字进行管理就像利用数字进行绘画，从严格意义上说，这完全是业余爱好者的做法。

-----
选拔员工时要衡量对方的野心有多大。前文涉及的人都有野心，但不一定每个人都是天生的权谋家。如果你想把自己的公司变成美国参议院的缩影，最保险的途径就是去选拔那些野心勃勃的人。安迪格鲁夫认为，那种以公司的发展为依托，实现个人发展的野心才是恰如其分的，个人的成就仅仅是以公司成就为前提而形成的伴生物。相反，只关注个人成功而将公司利益置之不顾的人拥有的只是不当的野心。

-----
初次雇佣一个身经百战的资深员工会让你觉得好像把自己给卖了。要是你疏忽大意，那最后很可能连全部家当都得拱手奉上。但是，要想为一穷二白的公司添砖加瓦，你必须承担这个风险，而且必须在分秒必争的市场竞争中取得胜利。资深人士出类拔萃的才干，广博深厚的知识，久经沙场的阅历都是你需要的，即便你为此不能不应付他们带给你的种种难题。

-----
如何最大限度地减少办公室政治：

在商界多年。我从未听说有人对办公室政治心怀好感，大多数人对此都是满腹怨气，就连那些公司老板们也不例外。既然大家都反感办公室政治·，为什么它还是如影随形呢?

几乎所有的办公室政治都是由公司老板开的头。你可能会觉得委屈：“我讨厌政治、不爱耍手腕，但我的员工们却恰恰相反。这绝不是我的原因。”你错了。公司内部的办公室政治并不在于你本人是否爱耍政治手段。事实上，那些最缺乏政治头脑的老板往往会带出一支最善于钩心斗角的队伍（为什么我立刻想到了百度呢？）。这些对政治不感兴趣的老板们常常在不经意间助长了公司内部激烈的政治斗争。

我所说的政治，是指员工在职场进阶的过程中依靠手段，而非业绩和贡献为自己谋取空间。我们生活中的政治形态有很多种,但这种形式的政治确实让人头疼。

-----
办公室政治是如何产生的？

公司CEO无意间对政治行为的鼓励抑或放任，往往是办公室政治发端的源头。就拿给管理人员定薪酬为例。如果那些资深员工不时地找你加薪，示意他们的所得远远低于应得，甚至暗示他们手头还有别家公司伸出的颇具诱惑力的橄榄枝，你会怎么办？如果对方的要求合情合理，你也许会酌情考虑，然后给他加薪。这种做法听起来无可厚非，但其实你已经就此为办公室政治的蔓延埋下了祸根。

具体来说，你所奖励的并不是推动公司发展的行为。员工获得加薪是因为他们提出了加薪的要求，并非因为他真的工作出色。这会产生什么样的危害？让我们来梳理一下：

1. 公司里其他跃跃欲试的员工很快就会效仿。没有不透风的墙。无论是这一轮竞争者还是那个现吃螃蟹的人，加薪与否都将与工作表现无关。你花时间考虑的，不是对方的工作业绩，而是政治问题。如果你对员工的驾驭能力较强，那就无须满足所有人计划外的加薪要求。最终，这些资深员工的加薪标准将演变为：先到先得。

2. 仅仅因为对政治手腕不敏感，公司里那些默默无闻的员工将无缘这份计划外加薪。

3. 你的员工从此次事件中总结出：会哭的孩子有奶吃，会耍手腕的员工有钱赚。准备好听他们的集体号哭吧。

下面我们举个复杂点的例子。你的财务总监对你说他相当经理，最终目标是常务总经理，希望你指点一二。为了鼓励他的积极性，你可能会赞赏他的梦想，表达对他的信心，并建议他努力拓展自己的知识面。此外，你还告诉他，只有强有力的领导方式才能让手下人心服口服。一周后，另外一个中层管理人员惊慌失措地找到你，说财务总监已经问过他是否有意为他工作了，并听说你已经有意提拔他为常务总经理。意外吗？好戏才刚刚开始。

-----
多年后，我曾问赫布，为什么会在那时向我们公司伸出援手。要知道，Allen&Company公司当时还没有涉足技术领域，更别说数据中心自动化了。赫布的回答是：“我对你们的业务一无所知，对你们的行业了解也很有限。我只是看到两个年轻人亲自来找我寻求帮助，而不是像其他上市公司的老板那样遇到麻烦就逃避。不仅如此，和那些大公司的老板比起来，你们成功的决心和信念要更加强烈。所以，我其实是给勇气和决心在投资，这个决定并不难做。”

专注于目标，然后力求实现，不再为过去曾有或者将来可能会有的错误而担心，懊恼，这也许是我从企业家的角色中获得的最大领悟。

在过去的10多年间，科技进步极大地降低了开班新公司要求的经济门槛，但是打造一流公司所需要的门槛--勇气--始终没有降低过。

-----
现在，我们回过头来看看开篇提到的那个问题，考虑下面这几个因素：

1. 他是资深员工吗？如果他是你公司的总设计师，那你就得让他好好提高一下自己规划的能力，以免拖累公司。如果他入行时间不久，那就借此机会好好点拨点拨他，而不是一味的指责。

2. 任务的难度如何？如果是一次足以改天换地，创造奇迹的任务，就不能大发雷霆，相反你得感谢他。如果仅仅是一个拖沓了太长时间的小项目，你就得认真解决。

3. 这是一次正确的大胆尝试吗？新产品能否在中短期占领市场？如果是，无论他只用了3个月还是9个月，这都是一次正确的尝试。今后再遇到类似情况时，你也应该持这个态度，而不必绞尽脑汁苦苦思索。

在高科技产业中，你很难未卜先知。平庸与杰出之间的差距往往就源于你的态度，源于你是否放手让员工大胆创新，不折不扣地实行问责制。责任固然重要，但也并不是唯一的重点。

-----
能力预期谬论：

有一回， 我和两个朋友聊天、 他们中一个是风险投资家，另一个是CEO。我们谈到了这个CEO手下的一位主管。他觉得这名主管表现优异，但是在更大规模的管理中缺乏经验。我的风险投资家朋友善意地提醒这名CEO，该认真考虑一下这个主管是否能胜任公司未来发展需求。我当即粗暴地大声说道：“无稽之谈！”这让二人大吃一惊。一般情况下，我的自控力还不错，不会口不择言，心里想什么嘴上就说什么。为什么当时会如比激动？以下是我的解答。

你必须时常对手下管理人员的工作表现进行评估。这是你身为CEO的分内之事。但是，拿公司未来的发展规模作为标准来衡量他们现在的表现，毫无凭据地妄加评判，这只会适得其反。原因如下：

1. 在一定程度上，管理能力是后天掌握的一种技能，而不是先天具备的禀赋。没有人一生下来就能管理一家上千人的公司，经验都是在一定阶段通过学习而获得的。

2. 不能提前下结论。你如何能预知某个主管是否能胜任未来的工作？你如何知道比尔盖茨当年从哈佛辍学事就已经知道把控企业的规模？你是凭什么得出这个结论的？

3. 提前下结论会阻碍别人的发展。如果你断定某个人将无法胜任更复杂的管理工作，那给他们传授管理经验或者指出他可能存在不足还有没有意义？也许毫无意义，因为你已经判定他技不如人。

4. 切勿操之过急换主管。这世上没有所向披靡，战无不胜的主管，只有在特定时刻特定环境下取得成功的主管。马克扎克伯格为Facebook创下了奇迹，却不可能成功领导甲骨文公司。同样拉里埃里森在甲骨文公司功勋显赫，却不适合管理Facebook。如果你拿将来的发展规模来衡量现在的管理队伍，操之过急的更换人员，还聘请了高级别人才，那他们可能无法胜任眼前的工作，而眼前的工作才是最迫切需要应对的。所以这样做的后果是得不偿失。

5. 你必须等公司发展到更大规模时再做决断。即使你没有换掉主管，也没有阻碍现有主管的职业发展，你都不该为时过早的下结论。无论你当初对他曾有过什么样的看法，你都得记住：时移事易，当公司真的发展到更大规模时，你再用充分的依据来考量他也为时不晚。

6. 腹背受敌的日子不好过。有人为你的公司鞍前马后，忠心耿耿，立下了赫赫战功，而你却因为微不足道的几条理由决定放弃他，这样的做法只会让你腹背受敌。你将深陷信息的盲区，被欺瞒和假意所包围。那就是一个被偏见主导的局面，不再有善意的提醒，只剩下盲目的判断。那将是一个内部战火频发的境地，千万别让自己陷进去。

如果不能预先判断人们能否胜任将来的工作，那该怎么做？建议你至少每个季度开展一次针对管理人员的全方位评估。为避免做出错误的能力预期判断，你需要注意两个关键点：

1. 要结合当前的工作规模的评估。你需要从评估中了解该主管能否胜任现有的工作，而不是其以后的表现。要全面宏观的去进行评估，不要排除当前规模这个因素，以免做出不明智的判断。

2. 做判断时要基于相对尺度而非绝对尺度。纠结于这个“主管够不够优秀”这样的问题只会让你无所适从。更科学的问法是：在公司发展的特定时期，我是否还能找到一个更好的主管？如果有这样一个人选，却被我最大的竞争对手招入旗下，那会对我们之间的胜负之战产生多大的影响？

总之，进行能力与其判断既有失公允，又缺乏依据，对公司的管理有百害而无一利。 

-----
CEO是后天磨练出来的

事实上，大部分人都持相反观点，认为当CEO的能力是与生俱来的，不是后天培养的。我常常会听到一些风投资本家和董事会成员在短暂接触某个企业创始人后，就认定他根本不是“当CEO的料”。我不明白他们如何能在这么短的时间内发现这点。一个企业的创办者往往需要花费数年的时间才能掌握当CEO的技能。对我来说，判断一个人究竟能否当好CEO，其实是一件很难的事情。

在运动领域，短跑这类技能可以在相对短的时间内掌握，因为它是以身体的自然摆动为基础，只需要稍加完善即可。和其他一些技能，比如拳击，这需要你花更长的时间去掌握，因为这项运动要求你凭借有违本能的动作和特定的技巧去完成。像我们前文中说过的，当你在拳击比赛中想要后退时，务必要先退后脚，如果你像平时那样先抬前脚后撤，对方一定能打得你眼冒金星。要想将这种有违常规的身体动作转化为自然而然的本能反应，大量的练习必不可少。当CEO也是一样，不过你带着寻常人的思路去管理公司，你同样会被对手打得措手不及。

当CEO意味着要做许多有违本能的事情。从适者生存的角度来看，人们一般会通过自己的所作所为去拉拢人心，这有助于提高他们的生存概率。然而，作为一个出色的CEO，想要获得大家的长期认可，就必须做出在短期内有违民意的事。这颇有违常情。
