#+title: 经济学人(The Economist)

俄克拉荷马大学（University of Oklahoma）的马克·博利诺（Mark Bolino）指出，协作有隐性成本。有些员工对协作高度热衷，以至于被邀请参与每项议题。但过不了多久，这些顶级协作者就成为了瓶颈：在他们发言之前事 情就没法定下来。而且，他们对许多自身能力以外的议题拥有发言权。

协作最大的问题就是，它致使纽坡特所说的“深度工作”即便不是全无可能展开，也将变得很困难。深度工作是知识经济的杀手级应用：你只有聚精会神才能掌握一门困难的学科或解决一个棘手的问题。许多最高产的知识工作者都竭力避免开会并排除电子设备的干扰。管理思想家彼得·德鲁克（Peter Drucker）认为，你可以做实际工作或者参加会议，但不能同时做这两件事。作家乔纳森·弗兰岑（Jonathan Franzen）写作时会拔掉网线。计算机科学家高德纳（Donald Knuth）拒绝使用电子邮件，原因是他的工作是“基础性的”而不是要“尽在掌握”。传奇物理学家理查德·费曼（Richard Feynman）在谈到参加学术会议时，高度赞扬“积极的不负责任”是一种美德。

为什么众多机构对于协作会如此天真？一个原因是，协作远比“深度工作”更容易衡量：任何一个傻瓜都能记录下来有多少人在Slack上发帖或是在会议上发言，但要发现一个独坐办公室的人是在取得突破还是无所事事，可能需要好几年。知识型工作者的资历越浅，越可能把时间花在做容易衡量的事情上，而非完成要求更高但模糊不清的工作。另一个原因是，管理者往往感到必须让别人看到自己在做管理：任其自由发挥时，他们会自动地用会议和备忘录占满所有人的时间，而不是让他们继续各自的工作。

上了年纪的一大好处是可以对年轻人大放阙词。据说，柏拉图曾抱怨年轻人既“不尊重长辈”，又“目无法纪”。隐士彼得埋怨他们“一副心思只为自己”，且“厌烦一切束缚”。今天，商界前辈在抱怨之余，往往还不忘略加赏识之辞，但他们倚老卖老之心其实不亚于从前时代的众人。

泰勒的吸引力在于他让人看到管理可以成为一门科学，而工人可以成为工业机器上的齿轮。他认为，提高生产率的最佳方式是运用三条准则：将复杂的工作分解成简单的；衡量工人的每项工作；将薪酬与绩效挂钩，给高产者发奖金，解雇偷懒的工人。

《纽约时报》文章引起的反响表明，数字泰勒主义就像它那个以秒表为基础的前身一样不受欢迎。批评家提出了一些有力的观点。他们认为，将知识型工作“碎片化”限制了员工创造性地发挥才能。一切都要考核则剥夺了工作的快乐。把人推向极限使得“吃不消，换工作”成为制度。频繁的同事互评助长了暗箭伤人的习气。其实，有些曾实行员工排名的公司，包括微软、通用电气和埃森哲（Accenture）发现这一做法适得其反，最终弃之不用。

投资者们似乎也偏爱泰勒主义：被《纽约时报》曝光后，亚马逊的股价有所上扬。技术的进步正在产生越来越复杂精妙的测量和监督人力资源的方式。信奉泰勒主义的管理者将甜和苦混合起来：自称“亚马逊机器人”的员工似乎乐于忍受 微观管理，只要年终能拿到不错的奖金。管理学最基本的原理是“能量化的就能被管理”。因此，量化技术越进步，我们就越多地把权力交给了泰勒的继任者们。

唯一能成为真正思想领袖的方法就是要对所有这些噪音充耳不闻，而只聆听少数几位伟大思想家的真知灼见。阅读修昔底德（Thucydides）写给伯里克利（Pericles）的赞美诗，能比你从上千个领导学专家那里学到更多的领导哲学。阅读孔子的著作，能比你从所谓的“文化顾问”身上获得更多在华经商的知识。彼得·德鲁克（Peter Drucker）在五十年里能保持管理大师中翘楚的地位，不是因为他参加更多的会议，而是因为他的思想长期浸淫在名著之中：比如他在写关于商业联盟的内容时，联系到的是简·奥斯丁（Jane Austen）笔下的婚姻联盟。

内省式课程所起的作用甚至比这更重要：它们为企业高管既提供了立身之锚，又提供了远离喧嚣的庇护所。企业高管们存在这样的风险：他们变得对物质成功过于执着，以致于忽视了自己的家庭，甚至违法。以哲学为基础的课程会帮助企业高管们克服对身份象征的执着。当你沉浸在柏拉图（Plato）中的时候，就很难以收集了多少大玩具来衡量自身的价值。抛开所有的电邮、推文和领英的更新，专注于少数几件真正重要的事，这将对思绪烦乱的老板们有所助益。

我们行业中的思想领袖不是埋头苦干、一步一步爬上来的那些人，”他说，“而是勇于冒险，独具视野的那些人。”

美国大公司一般老板的在位时间为八年。任期越长，晚节不保的机会越大。在位时间过长大大增加了犯灾难性错误的机会，也很可能变得年久乏味。

即便任由集体怀旧和唱颂歌之需，果断的高管们在最后九十天一如最初九十天，毫不感情用事。他们继续倾听可靠局外人的建议，关注重要的事情，尤其关注自身。他们遵从第三道法则：睁大眼睛盯着自己的退休薪酬。现在大部分的退休薪酬受长期合同的约束。但董事会保留对这些协议的解释权，包括竞业限制条款。明智的高管懂得对董事们拍马溜须，令其飘飘然到最后一刻。他们自己出面讨价还价，而不是通过律师或薪酬顾问。他们也不要什么乡村俱乐部会员资格或是 汽车这类小福利，因为如果这些要求公开的话，会显得自己很愚蠢。

在事迹流传、薪酬满载之后，狡黠的领导者还有最后一道法则须遵从：确保继任人不会功高盖“己”。若不喜欢继任人，即将离任的高管可以不让 其接触到公司的重要客户、供应商和投资者，关键流程也不予解释。美国前总统杜鲁门给继任人德怀特·艾森豪威尔（Dwight Eisenhower）只预留了半小时来交接工作。两人实际会面仅15分钟。

正如管理学大师彼得·德鲁克（Peter Drucker）曾经指出的那样，“如果需要天才或超人来管理，这样的机构不可能存活。机构的组织方式一定要让它能够在由普通人组成的领导层的管理下生存。”

福特和卡耐基成为CEO-政治家是出于自我选择。今天的CEO-政治家似乎常常觉得拥有令人赞赏的产品和坚实的财务业绩尚且不够。一位首席执行官要有价值观，并且要为之宣讲布道。从星巴克的霍华德·舒尔茨（Howard Schultz）到联合利华的保罗·波尔曼（Paul Polman），各行各业的老板已经在种种争议话题上选定了立场，包括种族关系、气候变化和同性婚姻。但是没有谁比科技界的CEO-政治家更高调。

中国耗时多年、投入巨资，试图成为吸纳外国技术的“创新海绵”。尽管如此，MGI的研究报告指出，中国在研制世界一流药物、民用飞机和汽车方面仍然落后于西方。

但报告发现，在许多其他行业，中国目前正在两个创新领域引领全球：一是改进消费品以及销售这类 产品的商业模式；二是让制造工艺更便宜、更快、更好。因此，中国公司如今在销售如家用电器、互联网软件和消费电子产品等方面超越外国对手。它们有庞大的本土市场相助，但确实也是行动迅捷。中国消费者已成为智能手机、社交媒体和电子商务的拥趸，他们重实用而轻品牌。如果消费品公司能在中国立足，就能无往而不利。

谢祖墀认为政府的角色之一是为创新打造平台，这是对的。然而，在民用航空和汽车制造业，政府同时也对产业结构独断专行：在航空业是通过位居全国之冠的国有企业中国航空工业集团公司来施加影响；在汽车制造业则是迫使企业与外国公司合作。中国的公司能够创新，但是中国政府还未学会区分什么是有益的支持，什么是适得其反的干预。

这些公司早早退出无异于涸泽而渔。这也导致了以色列的脆弱感：过早退出的习惯加深了人们对不平等的担忧，2011年正因如此才爆发了大规模游行示威。普通以色列人担心年轻的创业者对赚钱比创造就业更感兴趣，因此跟那些企业集团一样可恶，比起提供服务，它们抽租的本事可高明得多。


许多科技创业公司都倾向采用与悬浮滑板业类似的手法——利用法律的灰色地带，认为只要行业发展壮大，立法者和法官就只好调整法律以适应新的商业现实。这是场豪赌：今天许多最大的企业就像脚踩悬浮滑板的人们那样奔向颠簸的前


对企业而言，这一切自是美妙。但顾客呢？在新书《影子工作》（Shadow Work）中，克雷格·兰伯特（Craig Lambert）呈现了自助服务革命的反乌托邦一面。为什么现在那么多人感到工作过于劳累，原因是他们总被要求去做许多“看不见”的工作。亚马逊、美国国税局、本地学校董事会等等都能给你下达任务。人们之所以变得疏远，是因为他们花了大量时间在按按钮，与机器说话，而不是跟其他人互动。

但兰伯特提到的一点是对的——自助服务取代人员服务的累积效应会让人身心俱疲。能自己完成一两件事情让人感觉自由放松，一切都得自己做 则令人感到沦为了机器的奴隶。而且这种趋势远未结束。一些酒吧正在尝试一项名为iPourIt的技术，酒客得佩戴一款无线腕带以监测自己从啤酒龙头自斟的酒量。不要怀疑，用不了多久，自助理发店将请顾客把头探到剪发机里，然后旋动转盘选择头发修剪的长短。

