#+title: 投资中最简单的事

https://book.douban.com/subject/26163553/

笔记本导出
投资中最简单的事（更新版）（投资本身是一件很复杂的事，我们是否可以化繁为简、直接追问什么才是投资的本质?）
邱国鹭

在热点纷呈的中国一二级资本市场，如果没有定力，不能保持智力上的独立与诚实，很难不随波逐流。同时，如果不始终保持和发掘好奇心，很难在这么高强度的工作中保持青春与活力。

最后，还是要有个好心境、好家庭、好身体。投资到最后，反映的是你个人的真实性情和价值观。健康的环境和心情是长期修行的结果。成功诚然需要运气和际遇的配合，但能否幸福地去做投资则掌握在你自己手里。

投资本身是一件很复杂的事，宏观上涉及国家的政治、经济、历史、军事，中观上涉及行业格局演变、产业技术进步、上下游产业链变迁，微观上涉及企业的发展战略、公司治理、管理层素质、财务状况、产品创新、营销策略等方方面面。

价值投资和成长投资殊途同归，都是希望现在以五毛钱的价格购买未来价值一元钱的企业（ P0 < < Vn），两者的区别无非是企业的价值支撑的来源不同。成长投资的价值支撑主要来自企业未来收入和利润的高增长，更强调公司未来的价值 Vn要远大于公司现在的价值 V0，但这种投资需要预测未来的远见，只有极少数的人能够做到。价值投资的价值支撑主要来自企业现有资产、利润和现金流，更注重公司现在的价格 P0是否远小于公司现在的价值 V0，这种投资需要分析现在，难度相对较小，大多数人通过学习都能够掌握。

我还努力奉行一些简单的原则，例如：第一，便宜是硬道理。即使是普通公司，只要足够便宜，也会有丰厚的回报。 A股市场鱼龙混杂，发现“价格合理的伟大公司”的难度远远超过寻找“价格被低估的普通公司”。第二，定价权是核心竞争力。有核心竞争力的公司有两个标准：一是做的是自己可以不断复制的事情，比如麦当劳和星巴克可以不断地跨区域开新店，在全世界成功复制；二是做的是别人不可能复制的事情，具备独占资源、品牌美誉度、专利、技术、寡头垄断地位、牌照准入限制等特征，最终体现为企业的定价权。第三，胜而后求战，不要战而后求胜。百舸争流的行业，增长再快也很难找投资标的，不妨等待行业“内战”结束、赢家产生后再做投资。许多人担心在胜负已分的行业中买赢家会太迟，其实腾讯、百度、格力、茅台等企业在 10年前就已经是各自行业里的赢家了，但是 10年来它们的涨幅依然惊人。第四，人弃我取，逆向投资。无论是巴菲特、索罗斯，还是邓普顿、卡尔·伊坎，投资领域的集大成者大多数都具有超强的逆向思维能力。 A股的情绪波动容易走极端，任何概念和主题，无论真假，只要够新够炫，都能在短期内炒翻天，但是爆炒之后常是暴跌，因此对于如我这般手脚不快的人来说，“人多的地方不去”更是至理名言。

多数人喜欢成长，但我喜欢门槛。成长是未来的，难预测；门槛是既成的，易把握。高门槛行业，新进入者难存活，因此行业供给受限，竞争有序，有利于企业盈利增长。低门槛行业，行业供给增长快，无序竞争，谁也赚不到钱。（门槛，即行业护城河）

十几年前我刚进入基金业的时候，曾问过公司的一位资深合伙人，怎样才能成为一名优秀的基金经理。他说，其实很简单，你只要记住两条：第一，把客户的钱当作自己的钱来珍惜；第二，把二级市场的股票投资当作一级市场的实业投资来分析。

我们再来比较一下房地产公司的商业模式，北上广深随便卖栋别墅都是几千万元利润，顶得上一部好电影了。拍电影不一定每部都能火，而别墅几乎每栋都卖得掉。再从现金流的角度看，地产公司只要出钱拍了地，挖个坑、做个沙盘就可以预售了，客户会排着队把钱交上，它用你的钱盖你的房子，公司本身对现金流的要求其实并不高（盲目高价拿地的除外）。

互联网的本质是“人生人”，优势在于能以极低成本服务无数客户，规模效应体现在“人多”，“二八”现象不明显，是典型的散户经济，得散户者得天下。银行业的本质是“钱生钱”，规模效应体现在“钱多”， 80%的业务来自 20%的客户，“二八”现象显著，得大户者得天下，而且那 20%的大客户是需要线下的高端服务的，这就是网上银行至今在欧美日韩都没有很成功的案例的重要原因。看一下日本最成功的网上银行乐天银行：成立十几年，拥有 420万客户，才 600亿元人民币的存款，人均存款 1. 5万元。再比较一下国内某股份制银行的私人银行部门：拥有 2万客户， 4 000亿元存款，人均 2 000万元存款。两者高下立现。

在美国的互联网金融发展过程中，真正受冲击的其实是传统的券商经纪业务，迄今为止银行业受的影响并不大。那些认为互联网应该能够轻易地击败传统银行的观点，严重地低估了中国银行业的竞争力。事实上，银行在 IT和科技上的投入丝毫不比互联网公司少，互联网金融崛起的结果更可能是科技进步帮助传统银行业更好地服务于既有客户，而不是颠覆性地改变行业现有格局。

回顾过去 5年，寡头垄断行业的利润增长往往不断超出预期，而市场集中度低的行业则常常陷于恶性竞争和价格战的泥潭之中。白色家电（空调、冰箱和洗衣机）和黑色家电（电视）两个行业的不同发展历程就是最好的明证。所以，投资制造业时更应关注工程机械、核心汽配、白色家电这样的寡头行业。

很多人认为小股票的成长性普遍好于大股票。如果这是事实的话，那么大多数行业的集中度就会越来越低。但是只要关注一下工程机械、汽车、家电、啤酒、原料药、互联网等众多行业，你就会发现这些行业的集中度在过去几年都是持续提高的，这说明还是有许多行业里的大企业增长快于小企业。在这些行业里，低估值、高成长的行业龙头的投资价值就远高于行业内的小股票。

投资中影响股价涨跌的因素是无穷无尽的，但是最重要的其实只有两点，一个是估值，一个是流动性。估值就是价格相对于价值是便宜了还是贵了，估值决定了股票能够上涨的空间；流动性则决定了股市涨跌的时间。现在我们对市场做一个基本的判断，应该说估值不高所以是有上涨空间的，但是大家却没有看到流动性的显著改善。虽然央行已经降低了存款准备金，但是经过了一年多的时间，大家仍然感觉资金比较紧张。流动性的改善需要时间，也就是说政策从预调、微调，到最终能够成为市场向上的推力，这个转变也需要时间。

所谓的投资，就是牢牢抓住这个定价权。就像茅台，整天在涨价，日子太好过了，怎么提价都有人买，为什么呢？就是有这个定价权。而我们会发现另一些企业，比如钢铁和化工，总是没有定价权，稍微涨一点钢价得到的利润就被铁矿石涨价给赚走了。行业太分散，而且产品没有差异化，没有差异化就没有定价权，除非你是垄断企业。我之所以对中国 A股未来的基本面比较乐观，关键在于我们现在行业的竞争格局跟以前不一样了，现在的上市公司特别是蓝筹股，虽然有一些是不值得买的管理很差的国有企业，但的确有一些盘子不大，管理层又比较有执行力、领导力和有战略眼光的行业龙头公司在中国经济中占据不可动摇的地位。

这和一个年轻人在选择行业的时候，一定是找那种有积累的行业一个道理。比如投资就是有积累的行业，一个做过 10年的投资人和只做过一年的就是不一样，因为他见过大风大浪。刚从学校出来的小伙子不管多聪明就是没有经验，所以说一定要在有积累的行业。但是有的行业因为技术变化太快而很难有积累，你也许积累了很久，拼命挖了很深的护城河，人家可能不进攻这个城，绕了过去又建了新城。最明显的就是高科技行业，电子、科技、媒体和通信技术更新换代太快了。再看空调跟电视，空调比较持续，电视就不持续，因为电视技术老是变，以前我们看的是 CRT的，后来变成 DLP的，后来又变成 LCD，接着是等离子，然后又变成 LED，现在又变成 3D。每两三年就更新换代一次，这样的企业很辛苦，要不要投资更新换代？如果不投，别人超过你，你的品牌就会受损，消费者也不买你的产品；如果投，投 20亿元、 30亿元甚至 100亿元只能做个两年。技术变化快的行业就是这样辛苦，而像可口可乐，一个配方可以一两百年不变。中国也有很多传统的东西可以几百年不变，这种不变的东西，反而能够有积累，长期回报更值得期待。

从投资者的角度来看，有霸王条款的公司就是好公司，因为这说明他有定价权。有的公司服务姿态很低，很辛苦却赚不到钱，原因是竞争太激烈了。我们要找行业竞争不激烈、赚钱很容易的公司。这种行业和公司确实存在，但是不多，大概有 5 ~ 10个行业有这样的公司。长期来看，这样的公司赚钱的概率大得多。和巴菲特所说的找那种“傻子都能管”的公司类似，我一般都是看这个公司如果我去当 CEO是不是可以管好，如果我也能管好，那就是“傻子都能管”的公司，如果傻子能管好我就买，这些因素决定了谁管都可以。许多大公司每年利润几百亿元、几千亿元，但不见得是靠管理层的本事，谁都能做管理层的公司就是好公司。

这个世界是在不断变化的，你要是静止不动，就会被人家落在后面。有一定资产的人，必须不断思考一个问题：我的财富以什么样的形式存在才最容易保值增值。过去 10年，最好的形式无疑就是房地产，但是今后 10年会是这样子吗？我看不一定。过去是一面后视镜，没有那种只涨不跌的资产，特别是大类的资产类别，周期经常是 10年、 20年。如果一样东西 10年内涨得好，今后 10年也可能不涨了。过去 10年是涨还是跌跟今后会涨还是会跌，其实并不一定相关，关键是这个东西是不是物有所值。

两个卖鞋的人到了光脚岛。悲观者说，这里人不穿鞋，卖鞋根本没市场。乐观者说，这里人没鞋穿，卖鞋市场巨大。短期看来，悲观者是对的，因为短期内要改变岛民的穿鞋习惯是很难的。长期看来，乐观者是对的，因为岛民迟早会认识到穿鞋比光脚舒服。同一事情两种解读，往往是考虑的时间跨度不同。

老虎基金（ Tiger Fund）的朱利安·罗伯逊（ Julian Robertson）说过，他曾经只喜欢买低估值的价值股，直到招了几个天才研究员之后才开始喜欢成长股，因为这些天才研究员能够有预见性地把成长行业里的最终赢家在萌芽期发掘出来。的确，最大的牛股有不少是成长股，但个例不代表规律。能消化高估值的高成长其实并不多见，有眼光事前预知高成长的天才研究员更是凤毛麟角。

正如乔尔·格林布拉特（ Joel Greenblatt）所说，第一，价值投资是有效的；第二，价值投资不是每年都有效；第二点是第一点的保证。正因为价值投资不是每年都有效，所以它是长期有效的。如果它每年都有效，未来就不可能继续有效。听起来像是个悖论，但事实就是这么简单。在资本市场，如果有一种稳赚的方法，就一定会被套利掉的。正因为有波动性，才保证不会被套利。

很多人会讲，买便宜货这种方法是捡烟屁股，是“烟蒂投资”。巴菲特也说过，宁可用合理的价格买一个伟大的公司，也不要以很低的价格买一个一般的公司。这句话我是完全认同的，但是在实践中我做不来。为什么呢？你认为中国有多少家公司可以被称为“伟大的公司”？市场整天在炒的这些 50倍市盈率的公司，都说会是“下一个伟大公司”，又有几个真的能兑现的？我认为彼得·林奇说得对，他说当有人告诉你“ A公司是下一个 B公司”的时候，第一要把 A卖掉，第二要把 B也卖掉。因为第一， A永远不会成为 B；第二， B已经被当作成功的代名词，说明它的优点可能已经体现在现在的股价中了。

近年来，我问过许多基金经理一个问题：你认为哪个公司是最伟大的公司？大家公认伟大的那个公司，其实很可能已经不那么伟大了，你一定要在大家之前认识到这家公司的伟大，这其实是很难的。便宜不便宜我可以判断得出来，但对于伟大不伟大，我觉得真正能够判断的人不多。因为中国大多数公司的商业模式都挺一般的，我们在国际分工中分到了一个相对吃力不讨好的环节，那些创新的、有定价权的、有品牌的公司，在 A股中相对较少。

有的东西是需要时间积累的，不是你想转型就能转型的。像美国在 100多年以前就已经是世界经济第一大强国了，但在品牌，特别是奢侈品品牌上，美国也就只有蒂芙尼、凯迪拉克等有限几个。超高端品牌有很多是欧洲人创建的，因为很多东西都讲传承、讲路径依赖，不是你想做就能做得到的。

当时，我们有很多竞争对手在 1999年的时候没有扛住，放弃了价值投资，开始去追高科技股成长股。 2000年泡沫破灭的时候两边挨了巴掌，客户彻底放弃了他们，因为机构客户最不能忍受的就是基金经理的风格飘移。

条条大路通罗马，不存在谁好谁坏，我只是更重视统计数据。你可以看看全世界的统计数据， 10个国家中有 9个国家是价值股跑赢成长股的，而且跑赢是在什么时候呢？就是在季报公布后的那两三天。比如价值股一年能够跑赢成长股 7个百分点，在美国这 7个百分点基本就在 8个交易日内实现 70%——就在每次季报公布之后的两天。这说明在季报公布出来的业绩中，成长股很容易低于预期，而价值股很容易超出预期，因为未来不会有乐观者想象的那么好，也不会有悲观者想象的那么差。成长股的成长比价值股快，但没有大家预期的那么快。

电动车最后成功的是特斯拉（ Tesla），而且它的技术路线和 2010年热炒的那些技术路线都是不一样的，它的技术路线是几千块小电池并联在一起。当时市场炒作新能源，每个人都说自己是比亚迪的供应商，后来调研结果显示，只有卖包子的老阿婆没有撒谎——她真的为比亚迪食堂提供早餐的肉包子，比亚迪根本就没有向当时大家热炒的那些 A股厂商采购过。

政府扶持 　政府今天扶持这个明天打压那个，但有些行业越打压越赚钱，有些行业越扶持越亏钱。不是因为政府的力度不够，而是因为有些经济规律是不以人的意志为转移的。扶持其实是鼓励更多的人进入行业而加剧了竞争，打压却限制了新增供给，反而改善了竞争格局并且让行业龙头做大。

尽管美国的科技股是美国过去 30年涨得最好的行业，出了不少涨幅几百倍甚至上千倍的牛股（ 20世纪 90年代雅虎涨了几百倍、思科涨了上千倍），但为什么长期业绩好的投资大师如巴菲特、芒格、索罗斯、彼得·林奇、约翰·内夫（ John Neff）、杰里米·格兰桑（ Jeremy Grantham），没有一个爱投科技股？一个重要的原因就是这个行业技术变化太快，先发优势不明显，护城河每 3 ~ 5年就要重新挖一次，太难把握。

许多人对财务分析不屑一顾，但是对季报利润比预期多一分钱还是少一分钱耿耿于怀。其实随便一点会计手段（向渠道压货、改变折旧方式、存货价值重估、信用销售）都可以轻易地改变每股盈余几分钱。对行业格局的分析和对公司核心竞争力的理解是“道”，财务分析只是“术”，但是后者对前者起着验证和把关的作用。

我作为一个基金经理比较愿意读到的报告，是把一个公司与它的直接竞争对手做比较的报告，这对我的帮助是最大的。现在看 10篇报告，有 9篇都是孤立地讲这个公司多么多么好，和竞争者的比较都是一笔带过，这样的报告对我其实帮助不大。绝对的好没有意义，一定要和别人比较。我一直强调胜而后求战，愿意买已经把竞争对手打趴下的公司，而不是战而后求胜，在百舸争流中猜赢家。

另外，我认为行业研究员能够给基金经理提供的附加值在于讲出这个行业的特点。 2013年最火的行业是传媒业，因为电影的票房很高，但是“电影的商业模式到底是怎样的？”这个问题却很少有人探讨。作为一个内容行业，电影的特点就是它的利润缺乏可预测性和可持续性。这个电影可以有 10亿元票房，下一个电影可能就只有 3亿元票房。观众的口味是在不断变化的，特别现在 80后和 90后是看电影的主力军，他们的口味是很难把握的。

我是在 1995年申请美国大学的时候开始使用互联网的，是中国的第一批网民。当时要访问美国大学的网站，输入网址后可以先去洗个澡，洗完澡出来，这个大学的网站才加载完成，而且出现的页面是纯文字版的，连图片都没有，当时的网速就是这个水平。 1999年时我不买互联网股票并不是因为不看好互联网的未来，而是因为它们太贵，而且当时行业还处于百舸争流的阶段，不知道谁是最终赢家。回头看，现在最大的互联网公司——谷歌、 Facebook、腾讯 1999年时还都没有上市呢，苹果当时也不被大家看好。在 1999年上市、存活至今并且做大的其实也只有亚马逊、 eBay、 Priceline等少数几家，其他的几百家公司全都销声匿迹。在 A股市场 1999年恶炒的网络股中，更是连一家成功的互联网公司都没有走出来。因为好的互联网公司常常在天使投资、风险投资和私募股权投资阶段就有外资介入了，最后往往会去美国或者香港上市。 1999年 A股“ 5· 19”行情爆炒的那些公司，事后证明都只是讲故事而已。

密歇根大学金融学教授内贾特·赛亨（ H. Nejat Seyhun）对 1926—2004年美国市场指数进行研究后发现，不到 1%的交易日贡献了 96%的市场回报。同样的数据，出发点不同就有不同解读。长期投资者说，这说明长期投资是对的，这样才能保证那 1%的日子出现时你有持仓。短线选时者说，这说明波段操作是对的，因为其他 99%的日子里你根本就不需要有仓位。二种观点的分歧在于，这 1%的交易日是否事前可预知。

从行业配置的角度看，有的行业集中度高，两三个龙头企业就占据了行业中绝大部分的市场份额，研究这样的行业就像数月亮一样简单；有的行业集中度低，参与竞争的企业多如繁星，要把行业的竞争格局搞清楚就像数星星一样困难。研究后者肯定比研究前者困难得多，但是投资收益的高低与研究的难易却常常不成正比。

如果比较长期的利润增长，数月亮的行业常常战胜数星星的行业。为什么呢？原因很简单。数月亮的行业一般门槛高，参与竞争的企业少，所以竞争有序，坐地收钱，旱涝保收；数星星的行业门槛低，谁都能进来，竞争激烈，经济好时担心成本上升，经济差时担心需求下降，好日子总是不长久。前者是赚钱不辛苦，后者是辛苦不赚钱，比较之后，哪一类公司更适合投资，其实是一目了然的。

“数月亮”的行业还有一个不太好听的名字：寡头垄断行业。寡头垄断也分两种：国家给的和市场给的。国家给的寡头垄断（例如公用事业）往往伴随着价格管制，长期投资回报一般不会太高。只有市场竞争、行业洗牌后产生的寡头垄断才有定价权。中国的行业大多竞争激烈，真正靠市场洗牌后产生的寡头行业并不多。

债券投资者对债市波动往往能有逆向思维，而股票投资者对股市波动却总是追涨杀跌。造成这一差别的原因表面上是债券有固定的息票和到期日而股票没有，实质上却是许多股票投资者不太成熟，对股票投资的本质缺乏认识，所以华尔街有句老话：股票是小孩子玩的，债券才是大人们玩的。

早在 1977年巴菲特就说过，股票不过是穿着股票外衣来参加华尔街化装舞会的、长期资本回报率为 12%的债券。想清楚了这一点，对股市进行逆向思维也就容易了。
