#+title: 谁建造了美国(The men who built America)

- [[http://open.163.com/movie/2014/4/2/V/M9OI1SF08_M9OIE9N2V.html][铁路帝国的兴衰与石油帝国的崛起：范德比尔特与洛克菲勒]]
- [[http://open.163.com/movie/2014/4/V/B/M9OI1SF08_M9OIEGKVB.html][钢铁帝国的铸造与危机：安德鲁·卡内基]]
- [[http://open.163.com/movie/2014/4/2/J/M9OI1SF08_M9OIEMT2J.html][金融与电力的联姻：摩根与爱迪生]]
- [[http://open.163.com/movie/2014/4/P/5/M9OI1SF08_M9OK6LSP5.html][美国建造者：亨利福特和反托拉斯]]

讲述了这些人是如何创造美国工业的。这些人基本上处于同一个时代或者是交叠时间比较长，所以影片也着重表现了这些人之间是如何相互影响和相互较量的。他们就是美国的工业历史。

铁路 Cornelius Vanderbilt, Tom Scott（Andrew Carnegie as prentice) # 铁路建设过剩导致美国的经济大萧条

石油 John D. Rockfeller # 石油开始使用铁路运输，但是之后为了不受铁路巨头控制，改为使用自建的输油管道运输。开始从石油中提取出了煤油用于照明，后发现提炼过程中会产生作为燃料使用的汽油。

钢铁 Andrew Carnegie # 钢铁最初用于铁路，随着铁路建设的泡沫破裂，逐渐转移到建筑上。依靠当时建筑对于钢铁的巨大需求，成就了自己的钢铁帝国。

投资 J.P.Morgan # 当时Thomas Edison的DC(direct current)和Nikola Telsa的AC(alternating current)竞争非常激烈。J.P.Morgan开始投资在DC上后来转向AC并成立通用电气公司(General Electric Company)，之后买下了卡内基的钢铁帝国并且重组成美国钢铁(U.S. Steel), 并且同时拥有了自己铁路企业集团。 *投资业是统领其他行业的行业，真是一点都不错。*

Morganization, J.P.Morgan惯用手段，通过合并相互竞争的企业来达到行业垄断以提高利润。J.D.Rockfeller, Andrew Cargnegie以及J.P.Morgan在当时都在使用这种手段来提高利润，不断地压榨工人延长工作时间和降低薪水。人民开始不满，许多政客（尤其是民主党派）也声称要打破和惩罚这种垄断企业，所以三家打算合作来干预总统选举，可是结果还是出乎意料。

不久之后卡内基就选择退出，将自己的钢铁帝国卖给了J.P.Morgan. Morgan整合这些钢铁企业组成美国钢铁(U.S. Steel)并且继续大幅度剥削工人。虽然他们成功地让麦金利当选总统，可是不久就被刺杀了，接替总统职位的是副总统罗斯福。罗斯福属于共和党派，对这些垄断企业非常反感，同时具有非常独立政治倾向和强烈政治态度，完全不受人摆布。说来也巧，罗斯福当时正是这三家一起推荐的副总统，原因是副总统在当时基本上没有任何实权，这三个巨头想通过这种方式削弱罗斯福的政治影响力。

虽然标准石油(Standard Oil)被迫拆分成为很多小公司，讽刺的是，这些小公司现在发展成为埃克森(Exxon), 美孚(Mobil)和美佛龙(Chevron)这样的企业巨头，而Rockfeller在这些公司都持有大量股份，赚的钱比之前还要多。
