#+title: 极简欧洲史

希腊人的观点：这是一个简单、符合逻辑、能以数学表达的世界。基督教的观点：这是个邪恶的世界，唯有耶稣能拯救它。日耳曼蛮族的观点则是：打仗是好玩的事。这些看似天差地远的元素组合在一起，造就了欧洲的文明。

东方的专制暴君把领土上的一切都据为己有，如果需要什么物资，只要没收某人物产或派兵到市集拿一堆东西回来就是。反观欧洲的政府，虽然号称“绝对权力”，却从未这样做过。“并非所有东西都归国王所有”，是欧洲政府思维的基石。从私有财产权出发，衍生出人权观念，是西方价值的核心。政府权力必须有所限制，这样的观念之所以勃兴，其实是因为这些政府从一开始就处处受限。

被分裂、被撕扯、被困惑，是欧洲的宿命。其他的文明只有单一传统，不是这种具有三重元素的大拼盘，欧洲在道德和智识生活上一直受到煎熬、困扰和瓦解。欧洲的血统来自一种非常混杂的渊源，没有一个可以称为“家”的地方。

奥古斯都非常精明能干。他保留共和体制：公民大会照旧，执政官依然民选。他不把自己叫做皇帝，而以“第一公民”自称。他认为自己的职务是推动者，或者说他扮演了推动者的角色，推动这个国家机器做适当的运转。他朴实无华，没有一堆扈从前呼后拥，时常连个贴身护卫都不带就漫步街头，与平民百姓无异；他会在元老院开会期间走进会堂，细听立法诸公进行辩论；他的个性平易，人人都能亲近。当时大家打招呼以及表示顺从的姿势依旧是高举手臂为礼。当你来到奥古斯都面前，你不必躬身或做出屈从的表示，只要跟这位皇帝互行招呼礼就好。

依据罗马自然法的观念，每个人都拥有与生俱来的生存权、财产权和自由权，而透过政府的成立，人民有如和政府签下契约：人民授予政府权力，为的是让自己的权利得到保护；如果政府不能保护人民的这些权利，人民有权解散政府，重新建立新的政府。过去有关国王如神癨一般的地位、臣民服从君命的义务，这些观念通通都被扫到一边，成立政府已与签订一纸商业契约无异。

我们现在所认知的科学始于四百年前的17世纪科学革命，古希腊的两千年后。现代科学一开始就推翻了当时依然是主流和权威的希腊科学的中心教义，但它之所以能推翻希腊科学，遵循的正是这种希腊灵感：答案应该简单、符合逻辑、能以数学表达。

虽然犹太人相信自己是上帝的选民，但他们并没有逐梦的空间。他们常常遭受屈辱，被外族占领、放逐；可是，他们从不怀疑上帝的存在或他对他们的关爱。当苦难降临，他们的结论是自己没有恪遵上帝的规定，以至于触怒了神。因此，在犹太民族的宗教里，一如基督教中，道德与宗教是密不可分的，但其他宗教就不见得如此。

罗马帝国崩灭后，教会把希腊和罗马的学术保存了下来（它先前就已经这么做）。这是个令人惊讶的发展，因为古希腊和罗马的作家、哲学家和科学家全都是异教徒，不是基督徒。

基督徒并没有自订一套教育体制，因此，在基督教会下令将这套信仰制度化之初，非常仰赖熟谙希腊罗马传统的高级知识分子的协助。这些人利用希腊的哲学和逻辑学替基督教教义解释、辩护。信奉基督的学者认为，古希腊和罗马的伟大哲学家与道德学家只触及了部分的真理，基督教教义才理所当然是完整的；不过，这些希腊哲学家可以作为引导，让大众走向真理、辨明真理。因此，虽然他们是异教徒，基督教会还是保存了他们的著作并善加利用。这是第三个连结：基督教会将希腊和罗马的智识成就保存下来。

日耳曼蛮族首领想当然耳，也就开始以总督自居。很快地，这些战士就被主教们说服了——主教告诉他们，只要接受基督教的上帝，就更能克敌制胜。这是一群很特别的征服者：他们接受了被征服者的宗教。教会明白告诉这些新来的统治者、国王和贵族，他们的职责之一就是奉行基督信仰。这是最后一个连结点：日耳曼蛮族支持基督教。

保护女士、敬重女士的风范在欧洲文化中源远流长。骑士绝迹之后，演变成为“绅士”风度。绅士是基督教骑士的后裔，有女士进入屋内，即刻起身以示尊重；女士不落座，自己不可就座，见到女士必须点帽檐致意。这些都是我以前在学校里学到的，而学到后就很难忘记。在这方面，我发现自己活脱是个中世纪的遗迹。

无可否认，这是很极端的看法。启蒙运动不是革命运动，甚至不是政治性的运动。它是由一群学者、作家、艺术家和历史学家推动，这些知识分子相信，一旦理性与教育变得普及，迷信和无知自然会消弭于无形，人民也就不会相信神迹或君权神授这类的胡说八道。只要人民得到教化，民智自然开启。

浪漫主义运动崇尚感受、情绪以及所有的强烈的情感。在这方面，它和一心一意信奉理性的启蒙运动形成截然的对比。这场运动延烧整个欧洲，但尤以德意志地区（今日的德国）为烈，理念在此也得到最充分的发挥。浪漫主义的信徒并不想用理性去控制情绪和激情。在他们心目中，光是优雅地将古典曲调重新演绎出来，称不上是伟大的作家或艺术家；穷尽灵魂，掏心剖腹地将热情、痛苦、绝望赤裸裸地摊在第一线的才是。艺术应该是情感激荡、表达淋漓、惊天撼地的。

对于傲慢自大的法国知识分子关于理性的夸夸之言，他们的答复是：穿上你的靴子去走走路吧，走向平民百姓，走向农村耕民，记下他们的故事和歌谣，从中你会找到真正的启迪。浪漫主义的信息是：文明是人为的，它束缚了我们、局限了我们，唯有活在传统文化当中，你才算是活得完整。

浪漫主义运动也催生了民族主义的意识形态，这个观念在当今世界里依然是一股强大的力量。民族主义主张，拥有相同文化和语言的民族必须生活在一起、成立自己的政府。光是闭门造车、空想好的政府是不够的；而如果这个政府不是由你自己的民族所组成，它也不可能是个好政府。

在雅典，死刑通常都是立刻执行，这次却往后推迟了，因为宗教庆典的关系。苏格拉底大可趁机潜逃，说不定那些官员还暗自希望他逃之夭夭，但他却拒绝逃跑。他问：“既然我不能永远活着，那又何必苟且偷生？活着不是目的，好好活着才是。我曾在雅典的法治下过着很好的生活，如今我已准备好接受惩罚。”直到最后一刻，他还是充满了哲学思辨。直到他的镣铐被取下，他还在发表高论，说痛苦和享乐只是一线之隔。

这三位希腊大哲学家对雅典的直接民主提出严重质疑，拜他们的批评之赐，我们对它的运作方式有了了解。他们指出，人是善变无常的、优柔寡断的、浅薄无知的、容易被操弄的，而政治是一种精细的艺术，需要智慧和良好判断，这不是每个公民都拥有的特质。这三位哲人对我们目前的代议式民主应该会欣赏得多。无论我们对现在的民意代表有什么样的不满，相较于全体普罗大众，他们的教育水准还是高些，识见也丰富通晓些。
