#+title: 香港的未来-江南愤青

一个微信朋友发给我的。结合我的写在李嘉诚退休的文章。挺有意思。

----------

今天从香港参加展会回来遇到一个老司机，看到他年龄这么大（我同事说他可能有70岁了，我估计至少也有60多岁），还可以开出租，我很好奇，于是就和他聊了起来。听他耐心的解释完香港为老年人怎么申办驾照之后。我问他，您对香港最近的发展怎么看？

他居然说到：香港没有前途。


我以为他是一个立场不同的人士才会这么说，于是我问他，您是哪一年到香港的？他说他是香港本土出生的！原来年龄将近70岁的正宗香港人！[流汗]
还有很多亲戚在上海那边发展的很不错。


但是他居然这么悲观。


而且从他之前讲解香港老年人申办驾照的言辞来看，他是一个很有知识面、很有个人见解的港人，所以我有很强烈的欲望了，想了解他为什么会有这么悲观？
1. 为什么香港没有前途？
2. 一个香港人买房的悲惨故事。
3. 为什么香港精英男不来大陆发展？
4. 为什么外国人会迷失在深港边界？

----------

1.为什么香港没有前途？他给我打了一个震撼人心的比方。

香港的经济主要靠外贸，而香港和台湾的外贸做得尤其的好，原因很简单，就是他们没有护照的限制和语言的不便，所以他们可以全球到处去飞，去谈大业务。但是大概是2000年出头Sars病毒肆虐的时候，所有的香港人都不被欢迎，于是很多企业倒闭很多港人跳楼。


于是国家拨入了大量的财力物力来支持香港。但是他给我打了一个，让人意想不到的比方。他说在那边很多人都认为这是一剂吗啡。虽然让香港一下振奋了起来，精神抖擞，但是却失去了自力更生的能力，从此只有吗啡提神。


这种说法是否成立有待商榷，但是一个出租车司机居然能谈出这样的观点，让我很意外。


我怀疑他是否是一个反对人士。于是我就旁敲侧击的问了他一下家族根底，发现他虽然是在香港生长的正宗港人，但并不是原著民，而且以前也有很多亲戚在大陆，甚至有亲戚在部队里面开战斗机，军衔很高。所以我一步步打消了他是否有ZZ倾向的念头。


他说以前香港也有安居计划，但是被叫停了。他认为现在的香港长官，都没有太大的作为，不是没有能力，也不是不想作为，而是自主能力不强，一有作为就会被地产财团向上打小报告。香港的安居计划就是这样被撤销的。幸运的是他九几年的时候买了一套。当时的优惠就是免掉了政府的土地费和税。但是现在政府已经没有这样的计划了。


很诧异于他能够有这样的Z治见解，因为这是中国电视描写过去的官-场常见的情节，但是我看他也不像在编小说。


听了之后无言以对。于是我只能安慰他，国家也很关心香港，国家现在建高铁建这些跨湾区的大桥，见你刚才所说的那一条快捷隧道，都是为了未来能够更高效的扶持香港的经济得给香港同胞去大陆发展、安居提供便利。我问他小孩多大了，可以去大陆发展。

他说他小孩已经工作十年了是个女孩。

----------

于是他说到第三个问题：

3.香港精英男为什么不去大陆发展？

我告诉他，现在大陆的工资涨得飞快，两三万的工资在大陆很常见了，而且还有汇率差，大城市很快就会赶上香港了。

他一针见血的告诉我：这不只是钱的事，他说一个男人如果离开家庭时间太长，是会出问题的，因为大陆的小妹妹太好找了[捂脸]

我恍然大悟：现在的职场生力军都是八零九零后，很多都是刚刚成家，一是舍不得分开，二是一分开就要出事[捂脸]


虽然不见得这个观点很科学，但是确实很贴近生活和人性。

----------

2.一个香港人买房的悲惨故事。为什么是悲惨故事呢？现在香港房价咋那么高，按道理说买房应该是大欢喜啊？

他的故事背景还是回到SARS那个时候。

他老婆所在的公司一个同事，在2000年出头的时候贷款买了一套350万港元左右的房子。刚住进去不久，SARS来了，因为老板出不了境（别人也不敢来），损失了大量的订单，结果公司倒闭了。靠他老公的工资撑了一段时间，结果她老公的公司也倒闭了。双双下岗。不巧的是房价这时候也在下跌，350万的房子跌到了300万，于是银行让他补交五十万的抵押就同意让她继续供住。但是因为双双下岗连供楼都难，别说拿这50万了。结果房子被银行无情拍卖，清算之后房子没有了还倒欠银行几十万。家庭惨到无边了。

现在那一套300多万的房子价值1000多万。


----------

4.外国人为什么会迷失在深圳和香港的边境？

他又说了一个很有趣的故事：如果把一个外国人蒙着眼睛带到深圳与香港的边境，外国人一定会指着深圳说那是香港。


因为香港的边境都是棚户区太破旧了。但是住在棚户区的人惨吗？他们才是香港真正真正的有钱百姓——原住民，他们的下一代都将是衣食无忧的拆二代，亿万富豪！所以那些棚户区里面停满了豪车。


为什么他们是原住民，而开出租的这一位出生在香港的老港人不是呢。


他说原住民是在香港人进来之前就已经住在香港的人，是在清朝年间就已经拿到过地契的人。（是否都有没有考证）。而他是父辈过来的，大概战乱时期。


为什么靠香港的深圳地区特别繁华？而靠深圳的香港地区又是发展不佳的棚户区呢？这个让老外都迷惑的问题，只有我们的精英能够解答了。
