#+title: The Crowd 乌合之众

笔记本导出
乌合之众：大众心理研究（豆瓣图书Top 250，98871评价，评分8.2，经典畅销版本）
古斯塔夫.勒庞

https://book.douban.com/subject/1012611/

** 民主直通独裁的心理机制

人们似乎热爱自由，其实只是痛恨主子。——托克维尔：《旧制度与大革命》

勒庞是何许人物？本来我们对这位当年法国的才子式人物不该完全陌生。他的《乌合之众》一书，包括汉语在内被翻译成 17种语言。[ 3]惜乎近代以来，国人长期面对内忧外患的时局，总是摆脱不了“保种图存”的国家主义意识，因此最有现实意义的学说，是民族主义和社会主义之类的集体主义意识形态，像《乌合之众》这种反集体主义的著作几乎没有机会进入人们的视野，当然也就不足为怪。

勒庞讨论群体心理的另一个出发点，说起来也许为今人所不齿，却是激发他在这个主题上不断著书立说的一个重要因素，而且我们也不能轻言它已完全成为过去。他强调，遗传赋予每个种族（ race）中的每个人以某些共同特征，这些特征加在一起，便构成了这个种族的禀赋。勒庞对这种“种族特性”的强调，在一百多年前不但是西欧精神生活中的流行话，而且波及许多处在现代化过程边缘的地区，这在鲁迅先生的“国民性”（这正与勒庞喜欢用的“ genius of race”一词含义相同）反省，以及我们至今余韵犹存的“民族生存”意识中，都有很明确的反映。

群体中的个人会表现出明显的从众心理，勒庞称之为“群体精神统一性的心理学定律（ law of the mentalunity of crowds）”[ 17]，这种精神统一性的倾向，造成了一些重要后果，如教条主义、偏执、人多势众不可战胜的感觉，以及责任意识的放弃。用他的话说：“群体只知道简单而极端的感情；提供给他们的各种意见、想法和信念，他们或者全盘接受，或者一概拒绝；将其视为绝对真理或绝对谬论。”勒庞认为，他这里所描述的其实也不完全是一种现代的现象，从古至今，与宗教或准宗教信仰有关的偏执“对人们的头脑实行的专制统治，早就为大家所知”，它甚至是一切伟大文明最基本的动力。

由于这种简单化的思维方式，群体并不认为真理，尤其是“社会真理”，是只能“在讨论中成长”的，它总是倾向于把十分复杂的问题转化为口号式的简单观念。在群情激奋的气氛中的个人，又会清楚地感到自己人多势众，因此，他们总是倾向于给自己的理想和偏执赋予十分专横的性质。“

于此，我们也许更容易理解像韦伯和罗素这些曾经有志于参政的大思想家为何失败了。在观念简单化效应的作用下，凡是有抱着怀疑的精神、相信在政治和社会问题上极不易发现“确定性真理”的人，尤其是一个习惯于用推理和讨论的方式说明问题的人，在群体中是没有地位的；当面对群情激奋时，他尤其会生出苍白无力的感觉：因为他意识到他要与之作对的，不仅仅是一种错误的行为，而且还有“多数的力量”，还有贯彻这种行为时的偏执态度。我们更能理解，所谓专业精英，不管他智力多么高强，他陈明利害得失的理性努力，面对被空洞的观念冲昏了头脑的群体，反而会产生一种自己十分迂腐的无聊感觉。更为可悲的是，面对群众的荒谬与狂热，明智之士更有可能根本不会作出这样的努力，而是同群体一起陷入其中，事后又惊叹于自己连常识都已忘却的愚蠢。
书签 - 位置 257

他用和后来的哈耶克几乎完全一样的语气，认为“对历史事实最细致的观察，无一例外地向我证实，社会组织就像一切生命有机体一样复杂，我们还不具备强迫它们在突然之间发生深刻变革的智力”。因此他反对一个民族热衷于重大的政治和社会变革，他认为，这种变革的计划从理论上说无论多么出色，都不会使民族气质即刻出现变化（因为“只有时间具备这样的力量”）。采用激进的方式，借助于抽象的原则贯彻一种社会改造的蓝图，只会“使一个高度精致的文明倒退到社会进化更早期的阶段”[ 39]。
勒庞《乌合之众》的得与失

勒庞在布朗热的迅速崛起中，也许找到了他用于全书的一条公理，即就名望的起源而论，取得成功就是最大的成功，正像他从布朗热的突然垮台中也看到另一条相关的公理一样，虽然他没有把它明说出来，这就是，就名望危险的衰落而言，失败就是最大的失败。

事情就是这样，过去时代的历史事件，既不是勒庞的群体行为理论的唯一来源，也不是其主要的经验证据。人们所以能够得出这样的看法，至少是因为他对于把历史用于学术研究的目的，表现出一种十分矛盾的态度。这本书里，他发现对于作为当时复杂事件和人类社会行为结果之真实记录的史学，或更确切地说是历史记载，他可以不予理会。在这一点上，虽然无据可查，但是按照他所宣布的原则，他持的是“历史全是一派胡言”的观点，（据说）这句话后来由亨利·福特说出而广为人知。如果福特确实说过这句妙语，他也只是简单一提，而且是出于无知，而勒庞却说得很多，并且不像是出于无知。怀着这样的心情，勒庞相信“只能把史学著作当作纯粹想象的产物。它们是对被歪曲了的事实所作的无根据的记述，并且混杂着一些对思考结果的解释。写这种书是彻头彻尾的虚掷光阴。”（见第 1卷第 2章第 2节）为了得出这种虚无主义的判断，勒庞首先认为历史记载难逃两种噩运：第一，这是因为记录历史真相的证据并不存在或已散佚；第二，对碰巧可以利用的文献进行有倾向性的选择，他认为这是史学家不可避免的事情。

就像同矛盾心理作斗争的大多数人一样，勒庞也提出了一种妥协的理论。这使他既可以和历史生活在一起，又能够否认与它同居的事实。这个合理化的理论迷人而简单：不错，“关于那些在人类历史上发挥过重大作用的伟大人物的生平，如赫拉克利特、释迦牟尼或穆哈默德，我们拥有一句真实的记录吗？”但是勒庞又说，这些人的“真实生平对我们无关紧要。我们想要知道的，是我们的伟人在大众神话中呈现出什么形象。打动群体心灵的是神话中的英雄，而不是一时的真实英雄”。（见第 1卷第 2章第 2节）

读一下此书便可知道，勒庞显然并不具备方法论的头脑。他的著作从来不为系统搜集证据所累，以便使自己的思想能够经受住公正的（即没有偏见的）检验。他所采用的方法，是社会哲学家、社会心理学家和社会观察家的方法，不但他那个时代十分流行，我们这个时代也远没有消失：把历史上的奇闻异事用作思想资源，误以为这种资源多少能够证明由此得出的解释的真实性的方法。他的方法固然有缺陷，但是正如我们所见，他的某些观点却是正确的。它仍然有些粗糙，有待后来的社会科学家再付出大量平凡无奇的艰苦工作，他们不想从一个观念高峰跳向另一个观念高峰，他们在认为自己已准备好攀登之前，先要长途跋涉于方法论研究的峡谷之中。

勒庞另一项颇有道理的预见是，他把群众人描述为日益被大众文化所湮没，这种文化把平庸低俗当作最有价值的东西。在他的笔下，与过去的社会相比，（勒庞认为）群众人更易于接受自己周围的人的判断和爱好，他这一观点不可能不让人想到今天人们对所谓当代人失去自我判断能力的关切。社会学家帕克和伯吉斯承认，勒庞预见到了我们这个群众运动的时代，并且描述了这些运动的若干特点，其方法已被这方面的社会学研究所继承并作了重要的发展。

勒庞有先见之明的最后一个例子是，他认识到群体的日益重要性，这是一群缺乏组织的人，他们关注着同样的社会热点，在一定程度上表现出与同处一地、有组织的群体一样的心理行为。勒庞当然不能预见到广播电视这类影响巨大的新大众媒体（他毕竟不是真正的先知）。不过他确实注意到了编报纸的人对群众意见的影响，他们先是迎合群众的感情，然后把这些感情引入特定的行为渠道。

社会科学家所作的预测，同与他貌合神离的先知相比，在另一个方面也有所不同。他希望从自己的失败中学习。假如社会科学家有理由认为应当发生的预期后果没有出现，如果研究表明，假定的条件事实上已经出现但没有发生预期的结果，他会坐下来重新评价自己的证据，彻底反省自己的思想，就像有人对他发出指示一样。先知对自己落空的预言会更加关爱，他不会丢弃这种预言，也不会重新整理自己关于事物如何发展的认识。相反，他习惯于轻描淡写地对待预测的结果与实际结果的不一致，使预言避开对立的证据，得以原封不动地继续存在下去。成功的先知能够很有效地做到这一点，正如古人所言，他用娴熟的辩解“保住面子”，使他的信徒从看来已经落空的每一次预言中，往往只能很快看到自己的先知更为深刻的力量。
作者前言

因此，在研究一种社会现象时，必须分清先后，从两个不同的方面对它加以考虑。这样就会看到，纯粹理性的教诲经常同实践理性的教诲相反。这种划分几乎适用于任何材料，甚至自然科学的材料也不例外。从绝对真理的观点看，一个立方体或一个圆，都是由一定的公式做了严格定义的不变的几何形状。但是从印象的角度看，这些几何图形在我们眼里却会表现出十分不同的形状。从透视的角度看，立方体可以变成椎形的或方形的，圆可以变成椭圆或直线。但是，考虑这些虚幻的形状，远比考虑它们的真正形状更重要，因为它们，也只有它们，是我们所看到并能够用照相或绘画加以再现的形状。有时不真实的东西比真实的东西包含着更多的真理。按照事物准确的几何形状来呈现它们，有可能是在歪曲自然，使它变得不可辨认。我们不妨设想一下，如果世界上的居民只能复制或反拍物体，但无法接触它们，他们是很难对物体形态形成正确看法的。进一步说，如果有关这种形态的知识只有少数有学问的人才能掌握，它也就没有多少意义了。

社会事实如此复杂，根本不可能全盘掌握或预见到它们的相互影响带来的后果。此外，在可见的事实背后，有时似乎还隐蔽着成百上千种看不见的原因。可见的社会现象可能是某种巨大的无意识机制的结果，而这一机制通常超出了我们的分析范围。能够感觉到的现象可以喻为波浪，它不过是海洋深处我们一无所知的湍流的表象。就群体的大多数行为而言，它在精神上表现出一种独特的低劣性，在另一些行为中，它好像又受着某种神秘力量的左右，古人称它为命运、自然或天意，我们称之为亡灵的声音。我们虽然不了解它的本质，却不能忽视它的威力。

如果我们打算待在狭小而安全的界限之内，利用科学来获取知识，不想步入模糊的猜测与无用的假设的领地，则我们必须要做的事情仅仅是，留心这些我们能够接触到的现象，把我们自己限制在对它作些思考。从这些思考中得出的每个结论肯定都是不成熟的，因为在这些我们能够明确观察到的现象背后，另有一些我们只能隐约看到的现象，而在它背后，还有一些我们一无所知的现象。
导言：群体的时代

迄今为止，彻底摧毁一个破败的文明，一直就是群众最明确的任务。这当然不是只有今天才能找到的迹象。历史告诉我们，当文明赖以建立的道德因素失去威力时，它的最终解体总是由无意识的野蛮群体完成的，他们被不无道理地称为野蛮人。创造和领导着文明的，历来就是少数知识贵族而不是群体。群体只有强大的破坏力。他们的统治永远无异于一个野蛮阶段。有着复杂的典章制度、从本能状态进入能够未雨绸缪的理性状态的文明，属于文化的高级阶段。群体无一例外地证明，仅靠他们自己，所有这些事情是不可能实现的。由于群体的力量有着纯粹的破坏性，因而他们的作用就像是加速垂危者或死尸解体的细菌。当文明的结构摇摇欲坠时，使它倾覆的总是群众。只有在这个时刻，他们的主要使命才是清晰可辨的，此时，人多势众的原则似乎成了唯一的历史法则。

只有对群体心理有一定的认识，才能理解法律和制度对他们的作用是多么微不足道，才能理解除了别人强加于他们的意见，他们是多么没有能力坚持己见。要想领导他们，不能根据建立在纯粹平等学说上的原则，而是要去寻找那些能让他们动心的事情、能够诱惑他们的东西。譬如说，一个打算实行新税制的立法者，应当选择理论上最公正的方式吗？他才不会这样做呢。实际上，在群众眼里，也许最不公正的才是最好的。只有既不十分清楚易懂又显得负担最小的办法，才最易于被人们所容忍。因此，间接税不管多高，总是会被群体所接受，因为每天为日常消费品支付一点税金，不会干扰群体的习惯，从而可以在不知不觉中进行。用工资或其他一切收入的比例税制代替这种办法，即一次性付出一大笔钱，就算这种新税制在理论上仅是别的办法带来的负担的十分之一，仍会引起无数的抗议。造成这种情况的事实是，一笔数目较多因而显得数量很大从而刺激了人们想象力的钱，已经被感觉不到的零星税金代替了。新税看起来不重，因为它是一点一点支付的。这种经济手段涉及眼光长远的计算，而这是群众力不能及的。

因此，只从实践的角度看，群体心理学就很值得研究。即使完全是出于好奇，也值得对它加以关注。破译人们的行为动机，就像确定某种矿物或植物的属性一样有趣。我们对群体禀性的研究只能算是一种概括，是对我们的研究的一个简单总结。除了一点建议性的观点外，对它不必有太多的奢望。别人会为它打下更完备的基础。今天，我们不过是刚刚触及到一片几未开垦的处女地的表层而已。

** 第一卷 群体心理

与人们在机智的哲学家赫伯特·斯宾塞笔下发现的观点相反，在形成一个群体的人群中，并不存在构成因素的总和或它们的平均值。实际表现出来的，是由于出现了新特点而形成的一种组合，就像某些化学元素——如碱和酸——反应后形成一种新物体一样，它所具有的特性十分不同于使它得以形成的那些物体。

无意识构成了种族的先天禀性，尤其在这个方面，属于该种族的个人之间是十分相似的，使他们彼此之间有所不同的，主要是他们性格中那些有意识的方面——教育的结果，但更多的是因为独特的遗传条件。人们在智力上差异最大，但他们却有着非常相似的本能和情感。在属于情感领域的每一种事情上——宗教、政治、道德、爱憎等等，最杰出的人士很少能比凡夫俗子高明多少。从智力上说，一个伟大的数学家和他的鞋匠之间可能有天壤之别，但是从性格的角度看，他们可能差别甚微或根本没有差别。

群体一般只有很普通的品质，这一事实解释了它为何不能完成需要很高智力的工作。涉及普遍利益的决定，是由杰出人士组成的议会作出的，但是各行各业的专家并不会比一群蠢人所采纳的决定更高明。实际上，他们通常只能用每个普通个人生来便具有的平庸才智，处理手头的工作。群体中累加在一起的只有愚蠢而不是天生的智慧。如果“整个世界”指的是群体，那就根本不像人们常说的那样，整个世界要比伏尔泰更聪明，倒不妨说伏尔泰比整个世界更聪明。

从以上讨论得出的结论是，群体在智力上总是低于孤立的个人，但是从感情及其激起的行动这个角度看，群体可以比个人表现得更好或更差，这全看环境如何。一切取决于群体所接受的暗示具有什么性质。这就是只从犯罪角度研究群体的作家完全没有理解的要点。群体固然经常是犯罪群体，然而它也常常是英雄主义的群体。正是群体，而不是孤立的个人，会不顾一切地赴死犯难，为一种教义或观念的凯旋提供了保证，会怀着赢得荣誉的热情赴汤蹈火，会导致——就像十字军时代那样，在几乎全无粮草和装备的情况下——向异教徒讨还基督的墓地，或者像 1793年那样捍卫自己的祖国。这种英雄主义毫无疑问有着无意识的成分，然而正是这种英雄主义创造了历史。如果人民只会以冷酷无情的方式干大事，世界史上便不会留下他们多少记录了。

一些可以轻易在群体中流传的神话之所以能够产生，不仅是因为他们极端轻信。这也是事件在人群的想象中经过了奇妙曲解之后造成的后果。在群体众目睽睽之下发生的最简单的事情，不久就会变得面目全非。群体是用形象来思维的，而形象本身又会立刻引起与它毫无逻辑关系的一系列形象。我们只要想一下，有时我们会因为在头脑中想到的任何事实而产生一连串幻觉，就很容易理解这种状态。我们的理性告诉我们，它们之间没有任何关系。但是群体对这个事实却视若无睹，把歪曲性的想象力所引起的幻觉和真实事件混为一谈。群体很少对主观和客观加以区分。它把头脑中产生的景象也当作现实，尽管这个景象同观察到的事实几乎总是只有微乎其微的关系。

从以上情况得出的明确结论是，只能把史学著作当作纯粹想象的产物。它们是对观察有误的事实所作的无根据的记述，并且混杂着一些对思考结果的解释。写这样的东西完全是在虚掷光阴。假如历史没有给我们留下它的文学、艺术和不朽之作，我们对以往时代的真相便一无所知。那些在人类历史上起过重大作用的伟人，如赫拉克利特[ 6]、释迦牟尼或穆哈默德，我们拥有一句真实的记录吗？我们极可能一句也没有。不过实事求是地说，他们的真实生平对我们无关紧要。我们想要知道的，是我们的伟人在大众神话中呈现什么形象。打动群体心灵的是神话中的英雄，而不是当时的真实英雄。

专横和偏执是一切类型的群体的共性，但是其强度各有不同。在这个方面，支配着人们感情和思想的基本的种族观念，会一再表现出来。尤其在拉丁民族的群体中，可以看到专横和偏执能够发展到无以复加的地步。事实上，这两种态度在拉丁民族的群体中的发展，已经彻底破坏了盎格鲁 ￼萨克逊人所具有的那种强烈的个人独立感情。拉丁民族的群体只关心他们所属宗派的集体独立性，他们对独立有独特的见解，认为必须让那些与他们意见相左的人立刻强烈反对自己的信念。在各拉丁民族中间，自宗教法庭时代以来，各个时期的雅各宾党人，对自由从未能够有另一种理解。

然而，如果以为群体中的革命本能处在主导地位，那就完全误解了它们的心理。在这件事上使我们上当的，不过是它们的暴力倾向。它们的反叛和破坏行为的爆发总是十分短暂，群体强烈地受着无意识因素的支配，因此很容易屈从于世俗的等级制，难免会十分保守。对它们撒手不管，它们很快就会对混乱感到厌倦，本能地变成奴才。当波拿巴压制了一切自由，让每个人都对他的铁腕有切肤之感时，向他发出欢呼的正是那些最桀骜不驯的雅各宾党人。

如果不考虑群体深刻的保守本能，就难以理解历史，尤其是民众的革命。不错，它们可能希望改朝换代，为了取得这种变革，它们有时甚至发动暴力革命，然而这些旧制度的本质仍然反映着种族对等级制的需要，因此它们不可能得不到种族的服从。群体的多变，只会影响到很表面的事情。其实它们就像原始人一样，有着坚不可摧的保守本能。它们对一切传统的迷恋与崇敬是绝对的；它们对一切有可能改变自身生活基本状态的新事物，有着根深蒂固的无意识恐惧。在发明机器织机或出现蒸汽机和铁路的时代，如果民主派掌握着他们今天拥有的权力，这些发明也不可能实现，或至少要付出革命和不断杀戮的代价。对于文明的进步而言，值得庆幸的是，只是在伟大的科学发明和工业出现之后，群体才开始掌握了权力。

群体虽然经常放纵自己低劣的本能，他们也不时树立起崇高道德行为的典范。如果不计名利、顺从和绝对献身于真正的或虚幻的理想，都可算作美德，那就可以说，群体经常具备这种美德，而且它所达到的水平，即使最聪明的哲学家也难以望其项背。他们当然是在无意识地实践着这些美德，然而这无碍大局，我们不该对群体求全责备，说他们经常受无意识因素的左右，不善于动脑筋。在某些情况下，如果他们开动脑筋考虑起自己的眼前利益，我们这个星球上根本就不会成长出文明，人类也不会有自己的历史了。

观念只有采取简单明了的形式，才能被群体所接受，因此它必须经过一番彻底的改造，才能变得通俗易懂。当我们面对的是有些高深莫测的哲学或科学观念时，我们尤其会看到，为了适应群体低劣的智力水平，对它们需要进行多么深刻的改造。这些改造取决于群体或群体所属的种族的性质，不过其一般趋势都是观念的低俗化和简单化。这解释了一个事实，即从社会的角度看，现实中很少存在观念的等级制，也就是说，很少存在着有高下之分的观念。一种观念，不管它刚一出现时多么伟大或正确，它那些高深或伟大的成分，仅仅因为它进入了群体的智力范围并对它们产生影响，便会被剥夺殆尽。

不过从社会的角度看，一种观念的等级价值，它的固有价值，并不重要。必须考虑的是它所产生的效果。中世纪的基督教观念，上个世纪的民主观念，或今天的社会主义观念，都算不上十分高明。从哲学的角度考虑，它们只能算是一些令人扼腕的错误，但是它们的威力却十分强大，在未来很长一段时间里，它们将是决定各国行动的最基本因素。

让观念在群众的头脑里扎根需要很长时间，而根除它们所需要的时间也短不了多少。因此就观念而言，群体总是落后于博学之士和哲学家好几代人。今天所有的政客都十分清楚，我刚才提到的那些基本观念中混杂着错误，然而由于这些观念的影响力依然十分强大，他们也不得不根据自己已经不再相信的真理中的原则进行统治。

只会形象思维的群体，也只能被形象所打动。只有形象能吸引或吓住群体，成为它们的行为动机。

侵略者的权力和国家的威力，便是建立在群体的想象力上。在领导群体时，尤其要在这种想象力上狠下功夫。所有重大的历史事件，佛教、基督教和伊斯兰教的兴起，宗教改革，法国大革命，以及我们这个时代社会主义的可怕入侵，都是因为对群体的想象力产生强烈影响所造成的直接或间接的后果。

由此可见，断言群众需要宗教，实在是十分无用的老生常谈，因为一切政治、神学或社会信条，要想在群众中扎根，都必须采取宗教的形式——能够把危险的讨论排除在外的形式。即便有可能使群众接受无神论，这种信念也会表现出宗教情感中所有的偏执狂，它很快就会表现为一种崇拜。

** 第二卷 群体的意见与信念

对这种状况不必感到遗憾。脱离了传统，不管民族气质还是文明，都不可能存在。因此自有人类以来，他一直便有着两大关切，一是建立某种传统结构，二是当它有益的成果已变得破败不堪时，努力摧毁这种传统。没有传统，文明是不可能的；没有对这些传统的破坏，进步也是不可能的。困难——这是个极严重的困难——在于如何在稳定与求变之间取得平衡。如果一个民族使自己的习俗变得过于牢固，它便不会再发生变化，于是就像中国一样，变得没有改进能力。在这种情况下，暴力革命也没多少用处，因为由此造成的结果，或者是打碎的锁链被重新拼接在一起，让整个过去原封不动地再现，或者是对被打碎的事物撒手不管，衰败很快被无政府状态所取代。因此，对于一个民族来说，理想的状态是保留过去的制度，只用不易察觉的方式一点一滴地改进它们。这个理想不易实现。使它变成现实的几乎只有古罗马人和近代英国人。死抱着传统观念不放，极其顽固地反对变革传统观念的，正是群体。有地产的群体更是如此。我坚持认为群体具有保守主义精神，并且指出，最狂暴的反叛最终也只会造成一些嘴皮子上的变化。上个世纪末，教堂被毁，僧侣们或是被驱逐出国，或是殒命于断头台，人们也许会想，旧日的宗教观念已经威力尽失。但是没过几年，为了顺应普遍的要求，遭禁的公开礼拜制度便又建立起来了。[ 3]

因此，时间是我们最可靠的主人，为了看到一切事物有何变化，应当让它自由发挥作用。今天，面对群众可怕的愿望以及它所预示的破坏和骚乱，我们深感不安。要想看到平衡的恢复，除了依靠时间，再无他法。拉维斯先生所言甚是：“没有哪种统治形式可以一夜之间建立起来。政治和社会组织是需要数百年才能打造出来的产物。封建制度在建立起它的典章之前，经历了数百年毫无秩序的混乱。绝对君权也是在存在了数百年后，才找到了统治的成规。这些等待的时期是极为动荡的。”

进一步说，一个民族并没有真正改变其各种制度的能力。毫无疑问，以暴力革命为代价，它可以改变其名称，但是其本质依然如故。名称不过是些无用的符号，历史学家在深入到事物的深层时，很少需要留意它们。正是因为如此，英国这个世界上最民主的国家[ 4]仍然生活在君主制的统治下，而经常表现得十分嚣张的最具压迫性的专制主义，却是存在于那些原属西班牙的美洲共和国，尽管它们都有共和制的宪法。决定着各民族命运的是它们的性格，而不是它们的政府。我曾在前一本书中，通过提出典型事例来证实这一观点。

因此，把时间浪费在炮制各种煞有介事的宪法上，就像是小孩子的把戏，是无知的修辞学家毫无用处的劳动。必要性和时间承担着完善宪政的责任，我们最明智的做法，就是让这两个因素发挥作用。这就是盎格鲁 ￼萨克逊人采用的办法，正像他们伟大的史学家麦考利[ 5]在一段文字中告诉我们的，拉丁民族各国的政客们，应当由衷地学习这种方法。他指出，法律所能取得的一切好处，从纯粹理性的角度看，表现出一片荒谬与矛盾，他然后又对拉丁民族一拥而上发疯般制定出来的宪法文本与英国的宪法进行了比较。他指出，后者总是一点一滴慢慢地发生变化，影响是来自必要性，而不是来自思辨式的推理：

要想说明各民族的法律和各项制度在多大程度上表达着每个种族的需要，因此没有必要对其进行粗暴的变革，就要对它们逐一进行审查。例如，对集权制的优点和缺点，可以沉溺于哲学上的考究。但是，当我们看到，一个由不同种族构成的国民用了一千年时间来维护这种集权制；当我们看到，一场目的在于摧毁过去一切制度的大革命也不得不尊重这种集权制，甚至使它进一步强化，在这种情况下，我们就该承认它是迫切需要的产物，承认它是这个民族的生存条件。对于那些奢谈毁掉这种制度的政客，我们应当对他们可怜的智力水平报以怜悯。如果他们碰巧做成了这件事，他们的成功立刻会预示着一场残酷的内战[ 6]，这又会立刻带来一种比旧政权更具压迫性的新的集权制度。

在医院、矿山和工厂，在建筑师或律师的办公室里，十分年轻便开始学业的学生们，按部就班地经历他们的学徒期，非常类似于办公室里的律师秘书或工作室里的艺术家。在投入实际工作之前，他也有机会接受一些一般性教育过程，因此已经准备好了一个框架，可以把他们迅速观察到的东西储存进去，而且他能够利用自己在空闲时间得到的各种各样的技能，由此逐渐同他所获得的日常经验协调一致。在这种制度下，实践能力得到了发展，并且与学生的才能相适应，发展方向也符合他未来的任务和特定工作的要求，这些工作就是他今后要从事的工作。因此在英国或美国，年轻人很快便处在能够尽量发挥自己能力的位置上。在 25岁时——如果不缺少各种材料和部件，时间还会提前——他不但成了一个有用的工作者，甚至具备自我创业的能力；他不只是机器上的一个零件，而且是个发动机。而在制度与此相反的法国，一代又一代人越来越向中国看齐——由此造成的人力浪费是巨大的。

因此，当群体因为政治动荡或信仰变化，对某些词语唤起的形象深感厌恶时，假如事物因为与传统结构紧密联系在一起而无法改变，那么一个真正的政治家的当务之急，就是在不伤害事物本身的同时赶紧变换说法。聪明的托克维尔很久以前就说过，执政府和帝国的具体工作就是用新的名称把大多数过去的制度重新包装一遍，这就是说，用新名称代替那些能够让群众想起不利形象的名称，因为它们的新鲜能防止这种联想。“地租”变成了“土地税”，“盐赋”变成了“盐税”，“徭役”变成了间接摊派，商号和行会的税款变成了执照费，如此等等。

哲学不管取得了多大进步，它迄今仍没有给群众提供任何能够让他们着迷的理想。然而群众无论付出多大的代价，他们必须拥有自己的幻想，于是他们便像趋光的昆虫一样，本能地转向那些迎合他们需要的巧舌如簧者。推动各民族演化的主要因素，永远不是真理，而是谬误。如今社会主义为何如此强大，原因就在于它是仍然具有活力的最后的幻想。尽管存在着一切科学证据，它依然继续发展。它的主要力量是因为这样一个事实，即它的鼓吹者是那些非常无视现实，因而敢于向人类承诺幸福的人。如今，这种社会主义幻觉肆虐于过去大量的废墟之上，未来是属于它的。群众从来就没有渴望过真理，面对那些不合口味的证据，他们会拂袖而去，假如谬论对他们有诱惑力，他们更愿意崇拜谬论，凡是能向他们供应幻觉的，也可以很容易地成为他们的主人，凡是让他们幻灭的，都会成为他们的牺牲品。[ 15]

这种根据讲话的效果不断改变措辞的必要性，使一切有效的演讲完全不可能事先进行准备和研究。在这种事先准备好的演讲中，演讲者遵循的是自己的思路而不是听众的思路，仅这一个事实就会使他不可能产生任何影响。

以上所说的这种名望，是由人来体现的，在这些名望之侧，还有一些名望体现在各种意见、文学和艺术作品等事物中。后者的名望往往只是长年累月重复的结果。历史，尤其是文学和艺术的历史，不过就是在不断地重复一些判断。谁也不想证实这些判断，每个人最后都会重复他从学校里学到的东西，直到出现一些再没人敢于说三道四的称号和事物。对于一个现代读者来说，研读荷马肯定是极令人生厌的事，然而谁敢这么说？巴台农神庙[ 25]按其现存的状态，不过是一堆非常没有意思的破败废墟，但是它的巨大名望却使它看起来不是那个样子，而是与所有的历史记忆联系在一起。名望的特点就是阻止我们看到事物的本来面目，让我们的判断力彻底麻木。群众就像个人一样，总是需要对一切事情有现成的意见。这些意见的普遍性与它们是对是错全无关系，它们只受制于名望。

他们被带来了，波拿巴让他们等在外边。他终于佩戴着自己的剑出现在他们面前。他带上帽子，说明了他采取的措施，下达命令，然后让他们离开。奥热罗一直沉默不语。直到出门后他才重新找回了自信，让自己能够像通常那样骂骂咧咧地说话。他同意马塞纳的看法，这个小个子魔鬼将军让他感到敬畏，他搞不懂那种一下子就把他压倒的气势。

用一时的意见影响群众的头脑不难，想让一种信仰在其中长久扎根却极为不易。不过，一旦这种信念得到确立，要想根除它也同样困难。通常只有用暴力革命才能对它们进行革新。甚至当信念对人们的头脑几乎已完全失去控制力时，也要借助于革命。在这种情况下，革命的作用是对几乎已经被人抛弃的东西作最后的清理，因为习惯势力阻碍着人们完全放弃它们。一场革命的开始，其实就是一种信念的末日。

哲学家的任务，就是研究古代的信念在其表面变化背后有什么东西支撑着它们，在不断变化的意见中找出受普遍信念和种族特性决定的成分。如果不作这种哲学上的检验，人们会以为群众会经常随意改变他们的政治或宗教信念。一切历史，无论是政治的、宗教的、艺术的或文学的历史，似乎都证明了事情就是如此。

目前，群体中易变的意见比以往任何时候都多，这有三个不同的原因。首先，昔日的信仰正在日甚一日地失去影响力，因此它们也不再像过去那样，能够形成当时的短暂意见。普遍信仰的衰落，为一大堆既无历史也无未来的偶然意见提供了场所。第二个原因是群众的势力在不断增长，这种势力越来越没有制衡力量。我们已有所了解的群体观念的亟其多变这一特点，得以无拘无束地表现出来。最后，第三个原因是报业最近的发展，它们不断把十分对立的意见带到群众面前。每一种个别的意见所产生的暗示作用，很快就会受到对立意见的暗示作用的破坏。结果是任何意见都难以普及，它们全都成了过眼烟云。今天，一种意见还来不及被足够多的人接受，从而成为普遍意见，便已寿终正寝。

今天，密切关注各种意见，已经成为报社和政府的第一要务。它们需要在没有任何中间环节的情况下知道一个事件、一项法案或一次演说造成的效果。这可不是件轻松的任务，因为没有任何事情比群众的想法更为多变，今天，也没有任何事情，能够像群众对他们昨天还赞扬的事情今天便给予痛骂的做法更为常见。

大多数人都需要宗教、公开的礼拜仪式和僧侣。认为有可能通过普及教育消除宗教偏见，这不过是些我本人也一度受其误导的哲学家的谬论。宗教偏见是大量不幸的人求得安慰的来源……因此必须允许广大民众有他们的牧师、圣坛和公开的礼拜仪式。

** 第三卷 不同群体的分类及其特点

在本书阐述过的某些影响的作用下，这两种人群可以转变成有机的或心理学意义上的群体。我们把这些有机的群体分为以下两类： （1）异质性群体 a．无名称的群体（如街头群体） b．有名称的群体（如陪审团、议会等） （2）同质性群体 a．派别（政治派别、宗教派别等） b．身份团体（军人、僧侣、劳工等） c．阶级（中产阶级、农民阶级等）

考虑到受指控的人数众多，他们决定把贵族、僧侣、官员和王室仆役一律处死，没有必要对他们的案件一一进行审判——这就是说，在一个杰出的爱国者眼里，对于所有的个人，只凭职业就可证明他是罪犯。其他人将根据他们的个人表现和声誉作出判决。群体幼稚的良知以这种方式得到了满足。现在可以合法地进行屠杀了，残忍的本能也可以尽情地释放了。

候选人写成文字的纲领不可过于绝对，不然他的对手将来会用它来对付他。但是在口头纲领中，再夸夸其谈也不过分。可以毫无惧色地承诺最重要的改革。作出这些夸张能够产生巨大的效果，但它们对未来并没有约束力，因为这需要不断地进行观察，而选民绝对不想为这事操心，他并不想知道自己支持的候选人在实行他所赞成的竞选纲领上走了多远，虽然他以为正是这个纲领使他的选择有了保证。

不必怀疑，普选的弱点十分突出，所以人们很难视而不见。无可否认，文明是少数智力超常的人的产物，他们构成了一个金字塔的顶点。随着这个金字塔各个层次的加宽，智力相应地也越来越少，它们就是一个民族中的群众。一种文明的伟大，如果依靠仅仅以人多势众自夸的低劣成员的选票，是无法让人放心的。另一件无须怀疑的事情是，群众投下的选票往往十分危险。它们已经让我们付出了若干次遭受侵略的代价，我们眼看着群体正在为其铺设道路的社会主义就要大获全胜，异想天开的人民主权论，十有八九会让我们付出更惨重的代价。

一涉及一般性问题——推翻一届内阁、开征一种新税等等——就不再有任何固定的意见了，领袖的建议能够发挥影响，虽然与普通群体中的方式有所不同。每个政党都有自己的领袖，他们的势力有时旗鼓相当。结果是，一个众议员有时发现自己被夹在两种对立的建议之间，因此难免迟疑不决。这解释了为什么经常会看到他在一刻钟之内就会作出相反的表决，或为一项法案增加一条使其失效的条款，例如剥夺雇主选择和解雇工人的权利，然后又来上一条几乎废除这一措施的修正案。出于同样的理由，每届议会也有一些非常稳定的意见和一些十分易变的意见。大体上说，一般性问题数量更多，因此在议会中议而不决的现象司空见惯——所以议而不决，是因为永远存在着对选民的担心，从他们那里收到的建议总是姗姗来迟，这有可能制约领袖的影响力。不过，在无数的辩论中，当涉及的问题议员们没有强烈的先入之见时，处在主导地位的人依然是那些领袖。
