#+title: The Almanack of Naval Ravikant

https://www.yuque.com/qingmiyang/naval

我看的是别人翻译的中文版本，遇到不太通顺的地方可以跳回到英文版本对照一下，原版是可以免费获取到的。

----------

我认为我一直喜欢阅读，是因为我其实是一个不爱社交且内向的人。我从小迷失在文字和思想的世界里。我认为其中有一部分原因是来自我小时候快乐的环境，那时我还年轻，没有人强迫我去读某些特定的东西。

我认为父母和老师都有一种偏向会说，“噢，你应该读这个，而不是读那个。”我读了大量被认为（以今天的标准）是精神垃圾食品的书。

读你所爱读的直到你爱上阅读。

你几乎必定会读你正在读的东西，因为你已沉浸其中。你不需要任何其它的原因。没有什么必须要完成的任务。就纯粹是阅读，因为你乐在其中。

看一本书不是一场比赛——越好的书，就越要慢慢地理解和吸收。

我不知道你们的情况，但是我的注意力非常差。我略读。我快速阅读。我跳读。我无法告知你书中特定的段落或引文。在更深的层次上，你理解了它们，它们就成为了你心灵网络中的线。它们被编织在里面。

----------

我肯定你会有这样的感觉，你拿起一本书开始读的时候，你可能会说，“这是十分有趣的。这是十分好的。”你越读越有种似曾相识的感觉。接着，读到一半的时候，你意识到，“我以前读过这本书。”那是很好的。这就意味着你准备重读这本书。

事实上，我读过的书不多。我挑选了很多书，但仅看完了那几本构成我知识的基础的书。

事实是，我其实没有像人们所认为的那样读了很多书。我大概每天读一到两小时。那个使我进入0.00001%的行列。我认为单单用这个就足以说明我生命中已经取得的任何物质成就，以及我所可能拥有的智慧。真正的人不会每天读一小时。我认为，真正的人，每天读一分钟或更少。使它成为实际的习惯才是最重要的事情。

你读什么几乎不重要。最终，你会读到足够多的东西（你的兴趣将会引导你到那里），这能显著改善你生活。就像对你来说最好的锻炼就是每天都能充满激情地去锻炼，我要说的是，对于书籍、博客、推特或任何东西——任何有想法、信息和学习的东西——最值得去读的是那些一直能让你兴奋的东西。

如果书籍有些无聊，我就会跳读。有时，我会从中间开始读一本书，因为有些段落会吸引我。我将会从那里继续读下去，我觉得没有任何义务去读完这本书。突然间，书籍又回到了我的阅读库。那是极好的，因为书中有古老的智慧。

解决问题的时候：问题越老，解决方法也越老。

如果你尝试去学习如何开小车或开飞机，你应该读一些现代人写的东西，因为这个问题在现代才出现，最好的解决方法在现代。

如果你说的是一个老问题，像如何保持身体健康、如何保持心态平和、什么类型的价值系统是好的、怎么养家糊口以及其它类似的问题，老的解决方法可能更好。

任何一本能存活两千多年的书，都是经过很多人筛选的。一般原则更有可能是正确的。我想重新开始读这类书籍。

----------

如果它（幸福）是你内心的目的，是你最想去做的事情，那么可以确定的是，你做这个将是快乐的。但一个外在强加在你身上的目的，像“社会需要我去做X”，“我是这个人长子的长子，所以我应该要做Y”，或者“我背负着这些债务或负担”，我觉得这些不会让你快乐。

我想我们中大多数人都有这种低级而普遍的焦虑感。如果你关注你的思想，有时你只是绕着你自己的事在兜圈子，你感觉不太好，以及你注意到你的思绪不断地念叨着什么。也许你坐不住.....有这种“下一步”的事情，你坐在一个地方，想着你下一步应该去哪里。

总是下一件事，然后是下一件事，接着又是下一件事，再接着下一件事，制造了普遍的焦虑感。

焦虑感最明显的时候是在，你曾经只是坐下来，试图不去做任何事，是不做任何事。我所说的什么事都不做，是不看书，是不听音乐，只是真正地坐下来，什么事也不做。你不会这样做，因为总是有焦虑感促使你起来继续走，起来继续走，起来继续走。我觉得重要的是意识到焦虑正在令你不快乐。焦虑只是一系列流动的想法。

我是怎样去对抗焦虑：我不尝试和它斗争，我只是注意到因为这些想法我才焦虑的。我尝试弄清楚，“我是宁愿拥有现在这样的想法，还是宁愿拥有我的平和？”因为只要我有想法，我就不可能有平和。

----------

我觉得人类最常见的错误是相信自己会因为一些外在条件而得到快乐。我知道这不是最原始的。这也不是新的。这是基本的佛教智慧——我不会相信它。我想我真的只是在基础的层面认出它，包括在我自己身上。

我们买了一辆新车。现在，我正在等新车到来。当然，每晚，我会在论坛上看车子的消息。为什么呢？因为它是个傻货。这是一辆傻车。它不会给我的生活带来太大改变，甚至可能一点改变也没有。我知道车子到手的那一刻，我就不会再关心它了。问题是，我对欲望上瘾了。我沉迷于外在事物会给我带来某种幸福和快乐的想法，而这完全就是妄想。

在自身之外寻找任何事物是根本的妄想。不是说你不应该在外面做事了。你绝对是要做的。你是个活生生的人。有些事你是要去做的。你做了局部熵减的事情。这也是你在这里的原因。

你应该做点什么。你不应只是躺在沙地上和终日冥想。你应该自我实现。你应该做你注定要去做的事。

期望通过改变外在世界的某些事物，能给你带来平和、永恒的快乐以及你应得的幸福，是一个我们所有人都在遭受的根本错觉，包括我在内。这个一遍又一遍错误是说，“噢，当我得到那个东西我就会快乐了”，不管它是什么。这是我们每周7天，每天24小时，都在犯的根本错误。

欲望是你与自身定下的契约，直到你得到你想要的之前，你都不会快乐。我觉得绝大多数人无法意识到那是什么。我想我们一整天都在渴求着什么，然后想知道为什么我们不快乐。我喜欢对此保持清醒认识，因为那样我可以非常谨慎地选择我的欲望。我试图在我生活中的任何时候都不拥有多于一个的大欲望，我也认识到它是我生活痛苦的轴心。我意识到我已选择了不快乐的领域。

----------

当你年轻健康的时候，你可以做得更多。由于做得更多，事实上，你承担越来越多的欲望。你意识不到这正在慢慢摧毁你的幸福。我发现年轻人更少快乐但比较健康。老年人是更快乐但更不健康。

当你年轻的时候，你有时间。你有健康，但你没有钱。当你人到中年，你有钱有健康，但你没时间。当你老了，你有钱有时间，但你没有健康了。所以三连胜就是尝试同时拥有这三样东西。

等到人们意识到他们有足够的钱时，他们已经失去了时间和健康。

----------

你认为谁是成功的呢？绝大多数人认为，赢得游戏的人是成功的，不管他们自己玩的是什么游戏。如果你是一名运动员，你会想到一名顶级运动员。如果你是做生意的，你也许会想到埃隆·马斯克。

几年前，我会说史蒂夫乔布斯，因为他创造了驱动人类发展的一部分，改变了全人类的生活。我认为马可·安德森是成功的，不是因为他最近成为风险资本家，只是因为他在网景公司所做的不可思议的工作。中本聪成功在于他创造了比特币，这是种难以置信的技术创造，将会在未来几十年产生影响。当然，埃隆·马斯克也是，因为他改变了大家对于现代科技和创业中什么是合理的看法。我认为那些创造者和商业化者是成功的。

对我来说，真正的赢家是那些彻底从游戏中走出来的人，他们甚至不玩游戏，他们超越了游戏。那些人拥有内在的心智，自我控制以及自我意识，他们不需要任何人的帮忙。在我的生活中，我认识几个这样的人。杰瑞·格雷戈雷克（Jerzy Gregorek），我认为他是成功的，因为他不需要任何人的帮忙。他是平和的，它是健康的，与人相比，赚的钱多或少，对他的精神状态是没有影响的。

历史上的，我会说传说中的佛陀或克里希那穆提，我喜欢看他们的东西，他们是成功的，他们彻底超脱了游戏。输赢对他们来说并不重要。

我看过布莱斯.帕斯卡的一句话。本质上，它是说：“所有人的麻烦出现，是因为他不能独自静静地坐在房间里。”如果你能坐上30分钟，并快乐地度过，你就是成功的。那是一个非常强大的地方，但是很少人会走到那。

----------

我不觉得生活有那么难。我觉得是我们让它变得很难的。我正在试图摆脱的一件事是“应该”这个词。无论什么时候，“应该”这个词出现在你的脑海，它就是自责或是社会规定。因为你”应该“才去做的某些事，基本上意味着你其实并不想做这件事。它只是让你痛苦，所以我试图从我的生活中尽可能多消除“应该”。1

内心平和的敌人是社会和其他人灌输到你脑里的期望。

社会上，我们被告知，“去健身吧，去打扮自己吧。”那是一种多人竞争游戏。其他人可以看到我是否做得很好。我们被告知，“去赚钱吧，去买间大房子吧。”这是另一个外部的多人竞争游戏。训练你自己获得快乐，完全是内在的。没有外部的进度条，也没有外部的验证。你在和你自己竞争--这是一个单人游戏。

我们就像蜜蜂或蚂蚁。我们就是这样的社会生物，我们受外部限定和驱动。目前还不知道如何去玩和赢得那些单人游戏。我们完全是在多人游戏中竞争。

事实上，人生就是一场单人游戏。你是独自一个人来到世界的。也将独自死去。你所有的解释都是独自的。你所有的记忆都是孤独的。你三代人都走了，没有人在乎。你出现之前，也没有人关心。都是单人游戏。

这也许是瑜伽和冥想难以持续的一个原因：它们没有外在价值。是纯粹的单人游戏。

----------

**********选择做你自己**********

今天发生的很多事情就是你们很多人现在正在做的事情——自责和潦草的笔记，还会说，“我需要做这个，我需要做那个，我需要做......”不，你们不需要去做任何事。

所有你应该做的事是你想要去做的。如果你不再试图去弄清如何按照其他人想要你去做的方式去做事情，你就能听到你脑海里想让你以某种方式来做事情的小声音。然后，你就可以做你自己。

我从没遇见我最伟大的导师。我很想成为他那样的人。但他的信息是截然相反的：满带激情去做你自己。

世界上没人能够在做你自己方面打败你。你永远都做不到像我一样善于做我自己。我也永远做不到像你一样善于做你自己。当然，可以去倾听，可以去理解吸收，但不要试图去模仿。这是一种愚蠢的做法。相反，每个人在某些方面都有独特的资格。他们有一些特殊的知识、能力和欲望，是这个世界上其他人做不到的，完全来自于人类DNA和发展的组合学。

人类DNA和经验的组合学是惊人的。你永远也不会遇到两个可以互相替代的人。

你的人生目标是找到那些最需要你的人、事业、项目或艺术。那里有一些东西是为你量身定制的。你不想做的是以别人正在做的事情作为基础建立清单和决策框架。你永远无法成为他们。你永远都不擅长成为别人。

要想做出原创性的贡献， 你必须非理性地着迷于某些事。

----------

我学到的另一个方法是，坐在那里，闭上你的眼睛，每天至少一个小时。你向任何发生的事情屈服——不做任何努力。你不为做某些事情而努力，也不为反对某些事情而努力。如果有想法在你的脑海流动，你就随这些想法流动。

在你的一生中，事情总是会发生在你身上。有一些好的，有一些坏的，大部分你都已经处理和消失了，但还有一些留在你身边。随着时间的推移，越来越多的事情会黏住你，它们几乎像藤壶（译者注：常见于海边岩石的一种节肢动物）那样黏住你。

你失去了童年的惊奇感，失去了存在感和幸福感。你失去了内在的幸福感，因为你养成了这种未解决的痛苦、错误、恐惧和欲望的个性，这些东西像一堆黏住你的藤壶。
你是怎样把那些藤壶从你身上弄下来的？冥想中发生的事是你坐在那里，不去抵抗你的思想。这些东西就会开始冒出来。这就像一个装满未回复电子邮件的巨大收件箱，可以追溯到你的童年。它们会一个接一个冒出来，而你将被迫去处理它们。

你将被迫去解决他们。解决他们不需要任何工作——你只需要观察它们。现在你是一个成年人，和以前的事情有一些的距离、时间和空间，你可以解决它们。你可以更客观地看待他们。

随着时间的推移，你会解决很多这些深藏于你心中的事情。一旦它们被解决了，总会有一天，你静下来冥想的时候，你会进入到“收件箱零”的心境。当你打开你的心灵 “邮箱”，里面没有任何邮件，那是一种十分奇妙的感觉。

这是一种快乐、幸福和平静的状态。一旦你拥有它，你就不想放弃它。如果你每天早上只需坐着闭上眼睛，就能获得一个小时幸福的自由时光，那是超值的。它将改变你的生活。

我建议每天早上冥想一个小时，因为少于一个小时的时间都不足以让你真正深入冥想。如果你真的想去尝试冥想，可以先试着做六十天，每天一小时，而且要把它作为早上要做的第一件事。大概六十天之后，你就会厌倦倾听你的心声。你可能解决了很多问题，或者你已经听够了它们，看透了那些恐惧和问题。

冥想并不困难。你所要做的就是坐在那里，什么也不要做。就只是坐下来。闭上你的眼睛说出，“我只是想让自己休息一个小时。这是我远离生活的一个小时。这个小时我什么也不做。”

----------

佛教徒谈论意识与自我。他们真的是在讨论把你的大脑和你的意识当做一个多层次的机制。有一个核心基础，内核级的操作系统在运行，然后，还有一些应用程序在上面运行。（我喜欢这种把它看作是计算机和极客的说法）

事实上，我正在回到我意识层的操作系统，它总是平静的，总是平和的，通常是快乐和满足的。我试着保持在意识模式下，而不是激活心猴，它总是担心、害怕和焦虑，它有不可思议的作用，但我尽量不激活心猴，直到我需要它。当我需要它的时候，我想只专注于此，如果我24个小时不间断地运行它，我就会浪费能量，而心猴就会成了我，我比我的心猴更重要。

另一件事：灵性、宗教、佛教或任何你追随的东西，都会随着时间的推移教会你，你不仅仅是你的心灵。你不仅仅是你的习惯。你不仅仅是你的爱好。你是一个层次的意识，你是一个身体。现代人，我们活在自己的身体里还不够。我们活在我们的意识里不够。我们活在脑海里的内心独白中太多了。所有这些都是社会和环境在你年轻的时候强行给你编的程序。

你基本上是一堆DNA，在你年轻的时候对环境的影响做出了反应。你记录了好和坏的经历，你用它们来预判一切抛向你的东西，然后你再利用这些经验，不断尝试和预测，改变未来。

随着年龄的增长，你所积累的偏好总量越来越大。这些习惯性的反应，最终会像失控的货运列车一样操控你的情绪。我们应该控制自己的情绪。我们为什么不研究如何控制自己的情绪呢？如果你可以说出来，“现在我想处于好奇的状态。”然后你就可以真正的让自己进入好奇状态，那这将是一件很美妙的事情。或者说，“我想处于哀悼的状态，我在哀悼一位亲人，我想为他们哀悼，我真的想感受一下，我不想因明天要交的电脑编程问题而分心。”

心灵本身就是一种肌肉——它可以被训练和调节。它已经被社会胡乱地调教成了我们无法控制的样子，如果你带着意识和意图去审视你的心智（一份全天候的工作，你每时每刻都在做的工作），我想你可以把自己的思想、情绪、思想和反应都提取出来。然后你就可以开始重新设置了。你可以按照自己的意愿来重写这个程序。

冥想就是关掉社会，倾听你自己。它只为自己的利益而“工作”。徒步旅行是经行（或译行禅）。写日志是写作冥想。祈祷是感恩冥想。洗澡是偶然冥想。静坐是直接冥想。

----------
我不想具体的目标。斯科特·亚当斯有句名言，“建立系统，而不是目标。”运用你的判断力去找出你能在什么类型的环境中成长，然后在你周围创造一个环境，这样从统计学的角度来看你就有可能成功。

当前环境会对大脑进行编程，但聪明的大脑可以选择它即将到来的环境。

我不会成为这个星球上最成功的人，我也不想成为。我只想在尽可能不努力工作的同时，成为最成功的自己。我想以这样的一种方式生活，如果我的生活玩了1000次，我成功了999次。他不是亿万富翁，但他每次都做得很好。他可能没把生活的方方面面都做到位，但他建立了系统，所以他只在很少的地方失败了。

我觉得现在人们读的所有东西几乎都是为了得到社会认可而设计的。

我知道有人读了一百本关于进化论的反刍书籍，但从未读过达尔文。想想外面有多少宏观经济学家。我认为他们大多数都读过大量的经济学论文，但没有读过亚当·斯密的任何著作。

在某种程度上，你这样做是为了得到社会认可。你这样做是为了融入其它猴子的圈子。你很适合与羊群相处。这不是生活中的回报。生活中的回报是脱离群体。

社会认可是群体内部的。如果你想得到社会认可，一定要去读群体正在读的东西。需要一定程度的逆向思维才能说出，“不。我只是去做我自己的事。无论社会结果如何，我都会学习任何我认为有趣的东西。”

我想这就是为什么我认识的最聪明最成功的人最初都是失败者。如果你把你自己看作一个失败者，一个被社会抛弃的人，在正常的社会中没有任何作用的人，那么你就会做你自己的事情，你更有可能找到一条胜利之路。一开始就说，“我永远不会受欢迎。我永远不会被接受。我已经是个失败者了。我不会得到其他孩子所拥有的。我只要快乐地做我自己就好了。”

磨砺和汗水，辛劳和流血，直面深渊。这是一夜成名的全部。

----------
如果你必须把一两个原则传给你的孩子，它们会是什么？

第一是：阅读。尽你所能地阅读。不仅仅是社会告诉你的好东西，甚至是我告诉你要去读的书。只是为了自己阅读。培养你对它的热爱。即使你是读言情小说、平装本或漫画书。没有垃圾这种东西。都读一遍。最终，你会引导你自己去读你应该读和想要读的东西。

与阅读技能相关的是数学和说服技能。这两种技能可以帮助你在现实世界中航行。

拥有说服技能很重要，因为如果你可以影响你的人类同胞，你就可以做成很多事情。我认为说服技能是一项实际的技能。所以，你可以学习它，而且并不难。

数学有助于解决生活中复杂和困难的事情。如果你想赚钱，如果你想搞科学，如果你想理解博弈论、政治、经济、投资、计算机，所有这些东西都是以数学为核心的。数学是自然的基本语言。

自然用数学来说话。数学是我们逆向工程的自然语言，我们只是触及了表面。你只需知道基本统计学、算术等。你应该对统计学和概率了如指掌。

----------
就业自由

生活水平远远低于自己经济收入的人，享受着忙于改善生活方式的人无法理解的自由。

一旦你真正掌控了自己的命运，不管是好是坏，你将永远不会让别人告诉你该做什么了。

尝到自由的滋味，可能会让你失业。

----------

自我意识和自我发现没有终点。这是一个终生的过程，你希望能越来越好。不会有一个有意义的答案，也没有人能完全解决它，除非你是这些最开明的人物之一。也许我们中的部分人会达到那里，但我不太可能，因为我参与了这场激烈的老鼠竞赛。最好的情况是，我是一只偶尔能抬头看看云彩的老鼠。

我认为意识到自己是老鼠竞赛中的一只老鼠是我们大多数人都能做到的。

现代斗争：孤独的个体召唤非人的意志力，禁食，冥想和锻炼......去对抗大量的科学家和统计学家将丰富的食物、屏幕和药物改造而成的武器，这些武器就是垃圾食品、点击诱导新闻、无限的色情、无尽的游戏和上瘾的药物。
