#+title: 巴菲特致股东的信(The Essays of Warren Buffett)

囫囵吞枣地过了一遍，一些细节比如会计税务啥的因为不懂都是很快地浏览过去。

https://book.douban.com/subject/30164963/

----------

《巴菲特致股东的信：投资者和公司高管教程（原书第4版）》
沃伦E.巴菲特 劳伦斯A.坎宁安
84个笔记

◆ A．完整公平的信息披露

>> 第二，不知所云的注脚往往意味着靠不住的管理层。如果你看不懂财务报告中的某个注释或其他管理解释，这通常是因为CEO们不想让你明白。在安然公司欺诈案例中，对于某些交易的描述依然困扰着我。
第三，对于那些大肆鼓吹盈利成长预测的公司保持警惕。企业很少能在波澜不惊、毫无意外的环境中一帆风顺地发展，所有盈利也不是简单顺利地可以预知。（当然，投资银行家们的招股说明书除外。）

◆ B．董事会与公司高管

>> 我们通常会远远地在一个安全距离上，观察其他公司很多CEO的表现，这与我们可以近距离观察的（我们自己投资的公司中，那些CEO的表现），有着明显的不同。有时候，这些CEO们显然不能胜任工作，然而，他们却尸位素餐，能牢牢地待在自己的位置上。最大的讽刺莫过于，一个能力不足的下属或许很容易丢掉饭碗，而一个能力不足的CEO却不是这样。

>> 董事会成员应该精通业务，乐于本职，具有股东利益导向的精神。在很多情况下，董事会成员的组成往往基于其社会名声，或纯粹出于增加董事会的多元化因素的考量。这种做法是错误的。更有甚者，挑选董事的错误特别严重，因为董事任命一旦生效，就很难被解除，和和气气但无所事事的董事一旦被任命之后，再无丢失工作之虞。

>> 问责制和管家精神在过去十年里变得日益缺失，在大泡沫时代这些品质已经不再被认为是重要的。当股价大幅上升时，公司经理人的行为准则却在下降。但是，到了20世纪90年代后期，那些在高速公路上狂奔的CEO们并没有遇到严重的交通大拥堵。
应该注意的是，CEO们本应该是这样的一些人，无论男女，他们应该是你所喜欢的，并且放心选之作为下一代或邻居的财产信托人。然而，这些年来，太多的CEO们，他们在办公室里行为不端、蒙混数字、报以平庸的业绩，却为自己支取着高额报酬。
为什么聪明又体面的董事会未能防止这样可悲的事情发生？这并不是因为法律不健全。事实上，法律非常清楚地规定，董事们负有维护股东利益的责任。造成这种现象的原因正是我所说过的“董事会氛围”。

>> 这些斯文又聪明的人，对于企业没有足够的了解，对于股东利益也没有足够的关心，他们对于那些愚蠢的企业并购和可恶的赔偿政策不会提出质疑之声。反观我自己的行为，我必须可悲地承认，我也经常犯这样的错误：当我判断管理层做出的决策并不利于股东利益时，我也保持沉默。在这些例子中，“配合”式的和谐显示出了独立的特质。

>> 芒格和我都知道，只要有优秀的队员，每个领队都会成绩斐然，就像奥美广告公司（Ogilvy & Mather）的天才创始人大卫·奥格威（David Ogilvy）的哲学：“如果我们雇用的都是比我们矮的人，我们将成为一家侏儒公司；但如果我们雇用的都是比我们高的人，我们会成为一家巨人公司。”
作为一种副产品，我们的管理风格赋予我们一种能力，那就是我们可以较为容易地拓展伯克希尔的经营活动。我们曾读过一些管理学的研究成果，其中特别指出，在管理中，一位高管应该管理多少位下属才合适，但这对我们毫无意义。当你拥有的经理人都具有高度的工作热情，你可以与一打或更多的经理人打交道，并且与此同时，你还有午后小憩的时间。反之，如果经理人缺乏诚信、愚蠢或无趣，即便只有一个，你处理起来也会力不从心。芒格和我可以将打交道的经理人数目再提升一倍，只要他们与目前的经理人具有同样的出类拔萃的品质。
我们只愿意与我们喜欢并尊重的人一起工作，这不仅仅将我们获得好结果的机会最大化，同时可以给我们带来非同一般的美好时光。与此相反，与大倒胃口的人一起工作就像为钱而结婚，这在任何情况下，都是个糟糕的主意，尤其是在你已经富有的情况下，如果这么做，你绝对是疯了。

>> 我们给每一位经理人一个简单的任务，就像如下三种情况一样运营公司。
（1）你拥有100%的股份；
（2）将公司视为你和你的家族在世界上拥有的唯一资产，并且一直拥有；
（3）至少在100年的时间里，不可以出售公司或与其他公司合并。
作为一种推论，我们告诉这些经理人，不要让任何会计因素影响他们的决策，哪怕是一丝一毫的影响。我们希望我们的经理人队伍考虑什么是重要的，而不是考虑什么被认为是重要的。

◆ C．企业变化的焦虑

>> 随着伯克希尔的多元化发展，纺织业务在集团回报中所占的比重日渐缩小。我在1978年的年报中（在其他场合也曾总结过）提到过保留伯克希尔纺织厂的原因：
（1）我们的纺织工厂在当地是非常重要的就业雇主。
（2）纺织工厂高管在汇报问题时直截了当，在解决问题时干劲十足。
（3）面对共同的困难，工人们精诚合作，通情达理。
（4）相对于其他投资，这项业务还能产出适当的回报。
此外，我还说过：“只要这些条件都还存在——我们希望如此，我们就会继续支持纺织业务的存在，即便有其他更为动人的投资方向。”

>> 我不会关闭那些低于正常盈利水平的公司，以试图在整个集团回报率上增加小数点之后的一点点。然而，我同时也认为，不断资助一个一直亏损，没有盈利前景的公司是不合适的，即便它曾经非常盈利。亚当·斯密不会同意我的前一个观点，卡尔·马克思不会同意我的后一个观点。看来，只有保持中庸路线，能让我感到舒适些。
我应该再次强调一下，纺织业务的先后两位负责人——肯和加里，他们都是足智多谋、干劲十足、富于想象力的人，他们一直试图令我们的纺织厂走向成功。为了取得可持续的盈利，他们更新了生产线、机器配置和分销布局。为此，我们还进行了一项重大收购，收购了沃姆贝克纺织厂（Waumbec Mills），希望能产生协同效应（这是在业界被广泛使用的术语，用于解释收购行为，除此之外，毫无意义），但最终一无所获。没有更早些停止这些运作，这是我的错。

>> 在合同谈判中，无论是工会的领导人还是工会成员，他们都对不利的成本情况很敏感，他们从来不会提出不现实的提薪，或进行无效的生产活动。相反，他们像我们一样努力，试图保持工厂的竞争力。即便在清算期间，他们也表现出色。（但具有讽刺意义的是，如果工会前些年的行为没有这么友好的话，我们早就从财务上脱身纺织业务了，因为，我们会意识到面临的无望的未来，会迅速关闭工厂，以避免未来更大的亏损。）

>> 我经常设身处地地想，导演伍迪·艾伦在他的一部电影中说过的话：“历史上不止一次出现过这样的情况，人类面临十字路口的抉择。一条道路通往失望和彻底的绝望，另一条通往完全的灭绝。让我们祈祷我们有正确选择的智慧吧。”


>> 伯灵顿公司的例子表明，当头脑和精力贡献于错误的前提下，股东们所能得到的就是这种灾难性后果。这让人联想起英国作家塞缪尔·约翰逊（Samuel Johnson）关于马的比喻：“一匹能数到10的马是一匹非凡的马，但不是非凡的数学家。”与此类似，一家能聪明配置资本的纺织公司，是一家非凡的纺织公司，但不是一家非凡的公司。
以我自己的经历和对其他很多公司的观察，一个良好的管理记录（以经济回报衡量）的产生，更多取决于你上了什么样的船，而不是你划船的效率。（当然，在任何企业中，无论好坏，聪明和努力都很有帮助）。如果你发现自己上了一艘长期漏水的船，那么，换一艘船所花费的精力可能比修补漏洞更富成效。

>> 然而，拥有新闻抱负的人们必须小心谨慎，没有什么规定可以保证一家报纸的收入不能滑落到成本之下，到那时，亏损就像雨后的蘑菇一样疯长。在新闻报纸行业，固定成本非常高，当单位发行量下降时，这更是一个坏消息。当报纸的重要性消失之后，拥有报纸所带来的“超级”优越感也随之消失。

◆ D．社会契约

>> 所有这些加在一起，意味着我们背负着巨大的责任。我们是美国经济流通系统的主要和重要的部分，我们有责任不断维护并改善我们23000英里铁路，及其辅助的桥梁、隧道、发动机和车辆。为了完成这项工作，我们必须预见社会的需求，而不是仅仅进行反馈。为了完成我们的社会责任，我们会定期花费更多的折旧用于维护和改进，这些数字在2011年超过了20亿美元。我有信心在这些巨大的增量投资中，我们将获得合理的回报。智慧的监管和智慧的投资是同一枚硬币的两面。

◆ F．公司高管的报酬原则

>> 在安排股票期权时，会发生一个常见的错误，那就是期权的价格没有随着公司留存利润带来的价值增加而增高。的确，一个为期十年的期权、低派息率、复利增长，这些因素综合在一起可以给经理人带来巨大收益，即便他在工作中碌碌无为，随便扑腾，也能获益丰厚。对此愤愤不平的人或许会发现，当付给股东的越少，持有期权的经理人获得的就越多。

>> CEO是如何失去控制的，这事并不难理解。当公司管理层雇用员工，或者公司与卖家进行谈判，谈判桌的两边，双方的利益权重是平等的。一方的获利就是另一方的损失，其中涉及的金钱利益具有现实的意义，这样的结果是一场真诚面对上帝（honest-to-God）的谈判。
但是，当CEO们（或他们的代表）与薪酬委员会开会的时候，常常会比谈判对方更加看重利益。例如，一个CEO会非常看重是收到10万股期权还是50万股期权作为纪念。对于另一方——薪酬委员会而言，这个不同似乎不那么重要，特别是在很多公司，无论哪一种期权授予方案，对于财务报告的盈利都看不出来有什么不同影响。在这种情况下，谈判经常就是一种“玩钱”的性质。

◆ A．市场先生

>> 另一方面，在20世纪70年代早期，大多数机构投资者在决定交易价格时，认为企业价值与价格的关系不大。现在看来，这简直是难以置信。然而，这些机构都中了名牌商学院的学术魔法，他们鼓吹一种新型时尚的理论，认为股票市场是完全有效的，因此，企业的价值计算——甚至计算本身，在投资活动中无足轻重。（我们非常感激这些学者，在一场理智的竞赛中——无论是打牌、下棋还是选股，如果你的对手被教育说“思考纯属浪费精力”，还有什么比这能使你更具优势呢？

>> 对于投资建议的客户而言，市场秘籍的价值完全是不同的故事。在我看来，投资成功不可能是神秘公式、电脑程序或股票及市场价格变动引起的闪烁信号的产物。一个投资者如果想成功，必须将两种能力结合在一起，一是判断优秀企业的能力，一是将自己的思维和行为与市场中弥漫的极易传染的情绪隔离开来的能力。在我自己保持这种隔绝的努力中，我发现将格雷厄姆有关市场先生的概念放在心中，非常有用。

>> 遵循格雷厄姆的教诲，芒格和我希望我们持有的可流通的股票，用它们的企业运营结果，而不是它们每天的价格，甚至也不是每年的价格告诉我们，这些投资是否成功。市场或许会有一段时间对于企业的实际运营成果视而不见，但最终将会肯定它。正如格雷厄姆所言：“短期而言，市场是一台投票机；但长期而言，市场是一台称重机。”企业成功被市场确认的速度并不重要，只要公司能以令人满意的速度提升内在价值。实际上，被认可的滞后性也有一个好处：它会给我们以便宜的价格购买更多股票的机会。

>> 然而，我们的态度是，选择适合我们的个性以及我们想要的方式度过一生。英国前首相丘吉尔曾说：“你塑造你的房子，然后，房子塑造你。”我们知道何种方式是我们所希望被塑造的。为了这个原因，我们宁愿与我们喜欢与尊重的人合作，获得100%的回报，也不愿意与那些无趣或不喜欢的人合作，获得110%的回报。

>> 所以，当你读到类似“投资者因股市大跌而亏损”的新闻头条时，应该感到高兴。你们应该在心里将其重新编辑为：“撤资者因股市大跌而亏损，但投资者在获益。”记者们常常会忘记这条常识：每一个买家都对应着一个卖家，一个人受到的伤害往往成就另一个人。（就像在高尔夫球赛中，人们常说的“每一次进洞都令一些人高兴”。）

◆ C．戳穿标准教条

>> 于是很自然地，那些受到市场有效理论伤害的学生和受骗上当的投资者，实际上为我们以及其他格雷厄姆的追随者提供了非同一般的服务。无论是哪一种形式的竞赛，无论是财务上、心理上还是体力上，面对一群被灌输了“努力也会徒劳无益”的对手，我们于是拥有了巨大的优势。从利己主义的观点出发，格雷厄姆的信徒们应该捐助大学里的教学职位，以确保市场有效理论的教学能一直持续下去。
对于所有这些，有必要发出一个警告。近来，套利看似很容易，但这并不意味着它是一种永远能保证每年20%回报的投资方式。正如所观察到的那样，在很多时候，市场是有效的，在过去63年中，除了我们所抓住的套利机会外，其他很多机会都被放弃了，因为它们看起来价格已经到位了。
一个投资者不可能因为简单地掌握了一种特定的投资方法或投资风格，而获得超额利润。他只能通过认真地评估事实，并且持续执行纪律，而获得这种利润。在套利环境中的投资，本质上讲，并不优于扔飞镖选组合的投资策略。

>> 很久以前，芒格和我认为，在一生的投资生涯中，很难做出数以百计的明智决策。随着伯克希尔的资本规模急剧增长，决断的压力变得愈加巨大，而且，能影响我们业绩的投资空间急剧缩小。因此，我们采取的策略是，对自己仅仅要求次数有限的聪明，而不是过分聪明。的确，我们现在每年只落实一个好主意。（芒格说，现在该轮到我了。）

>> 我们一直坚持不动如山的原则，这种行为表达了我们的一个观点：股市是一个不断重新定位的地方，在这里，钱会从活跃者手中流向耐心者手中。（根据在有限范围内进行的调查，我认为近来发生的事件表明，那些饱受诟病的“有钱有闲的富人”已经遭到了负面评价：他们维持或提升了财富水平，而同时那些“精力旺盛的富人”——进取的不动产运作商、公司并购者、石油钻探商等——则眼看着自己的财富消失。）
我们继续寻找那些业务易懂，可持续经营，具有令人垂涎的经济特征，拥有杰出才能和股东利益导向的管理层的大型公司。我们既必须以合理价格购买，又需要让企业的表现证明符合我们的预期。仅仅关注于这些并不能保证结果，但是，这个投资方法——寻找超级明星——为我们提供了真正成功的唯一机会。考虑到我们打交道的资金数量巨大，芒格和我还没有聪明到，可以通过熟练地买进、卖出平庸公司获得高额利润的程度。我们也不认为，会有其他很多人，可以通过在不同花朵之间跳来跳去的方式，取得长期的投资成功。实际上，我们认为将那些频繁买卖的机构称为“投资者”，就像将那些喜欢一夜情的家伙称为浪漫主义者一样可笑。

>> 他们喜欢说，在当前大机构飘忽不定的行为主导的市场中，小投资者已经没有赚钱的机会。这个结论是相当错误的。这种市场无论对任何投资者都是理想的，无论大小，只要他坚守自己的投资系统。由那些握有巨资的基金经理所导致的市场波动，恰恰为真正的投资者提供了更多的明智投资的机会。只有在市场艰难的时候，投资者被迫卖出——无论是来自财务压力，还是心理压力——他才会被股市波动所伤害。

◆ D．“价值”投资：多余的两个字

>> 如果我们控制了一家公司，我们就能支配该公司的资产配置；而当我们仅仅是投资了一些可流通股票，我们对于公司资产的配置则毫无话语权。这一点可能非常重要，因为，很多公司的领导人并不擅长资产配置。大多数老板获得今天的领导地位，往往由于他们在某一领域的优秀，或是市场，或是生产，或是工厂，或是行政，甚至机构政治。
一旦他们成为CEO，他们将面临新的责任。他们必须做出资产配置的决策，这是一项他们从来没有做过、非常重要、但并不容易掌握的工作。推而言之，就像一位杰出的音乐家，他正准备在卡内基音乐厅完美呈现音乐生涯的最后一步，却忽然被任命为联邦储备委员会主席，这个跨度有点儿大。

◆ E．聪明的投资

>> 通过研究我们无论是对于子公司的投资，还是对于普通股的投资，你会发现我们喜欢的公司和行业，不大可能经历重大的变化。这样做的原因很简单：无论哪一种投资，我们寻找那些我们相信在未来10年、20年几乎可以肯定依然具有竞争优势的公司。一个环境迅速变化的行业或许会提供巨大的胜利机会，但是它不具备我们寻找的确定性。
应该强调的是，作为一个公民，芒格和我欢迎变化，新鲜的想法、新颖的产品、创新的过程，以及那些提升我们国家生活水平的东西，这些当然很好。然而，作为投资者，对那些处于发酵中而迅速膨胀、变化的行业，我们的态度就像我们对于太空探索的态度一样：我们会鼓掌欢迎，但不会参与其中。

>> 当一家杰出公司的管理层改弦易辙，忽视其完美的基础业务，去收购一家业务平平或平庸的公司时，一个更为严重的问题出现了。如果发生了这种事情，投资者的痛苦将是漫长的。不幸的是，这样的事情多年前在可口可乐和吉列身上都发生过。（你相信吗？可口可乐养过虾，吉列搞过油。）当芒格和我考虑对哪些通常看起来杰出的公司的投资时，失去专注是最令人担心的。一次又一次，当傲慢存在时，或当管理层出离正道无聊时，这个时候，我们看到价值变得停滞不前。然而，在可口可乐和吉列不会再发生这种事情——在不考虑现任和未来管理层的情况下。

>> 去年，几家我们有着大量投资的公司表现不佳。然而，我们依然相信它们具有可持续的重要竞争力。这种可以为长期投资带来良好结果的特质，芒格和我偶尔相信，我们还是有能力识别的。然而，在更多的时候，我们无法做到这一点——至少没有高度的自信可以做到。这就顺便解释了，为什么我们不买高科技类公司的股票，即使我们也同意大家认同的观点——高科技公司的产品和服务改变了我们的社会。我们的问题是，对于这个领域中哪些参与者具有真正持久的竞争力，我们毫无洞见，而且我们无法通过学习来解决这个问题。

◆ F．捡烟蒂和惯性驱使（机构强迫症）

>> 首先，最初看似“便宜”的价格可能最终根本不便宜。一家处境艰难的公司，在解决了一个难题之后，不久便会有另一个问题冒出来，就像厨房里如果有蟑螂，不可能只有一只。
其次，任何你得到的初始优势会很快被公司的低回报所侵蚀。例如，你以800万美元买下一个公司，能迅速以1000万美元卖出或清算，而且可以立刻执行，那么你能实现高回报。但是，如果这家公司是在十年之后以1000万美元处理掉，即便在此期间每年有几个点的分红，那么这项投资也是令人失望的。时间是优秀企业的朋友，是平庸企业的敌人。

>> 关键词：优秀的骑手只有在良马上，才会有出色的表现
我最为惊讶的发现是：在企业内部，有一种看不见的力量足以压倒一切，我们可以称其为“惯性驱使”或“机构强迫症”。在大学的商学院里，我从未听说过这种强迫症的存在，而且在我进入商界时，也没有直观地感受到它。我本以为那些正派的、聪明的、经验丰富的公司管理层会自然做出理性的商业决策。但是，历经多年之后，我发现现实并非如此。相反，当惯性驱使的强迫症发作之时，理性经常会枯萎。

>> 犯下一系列错误之后，我学会了只与那些我喜欢、信任和尊敬的人做生意。正如我之前提到过的，这条原则本身或许并不能保证成功。一个二流的纺织厂或百货公司，固然不会仅仅因为管理层是你想嫁女儿的对象而变得繁荣昌盛。但是，一个主人——或股东——如果能够设法将自己与那些经济特征不错的公司中的人结合在一起，也能够成就奇迹。相反，我们不希望与那些不值得尊敬的经理人为伍，无论其公司的前景多么诱人。与坏人打交道做成一笔好生意，在这方面我们从来没有成功过。

>> 我们一贯保守的财务政策，或许看起来是一个错误，但以我的观点并非如此。回溯过往，有一点是肯定的，如果我们在伯克希尔使用了更高的杠杆，尽管这样做仍然符合传统负债习惯，会取得远远高于我们已实现的23.8%的年回报率。甚至在1965年，我们或许完全可以判断，动用杠杆能以99%的概率带来更高的回报率，几乎可以说是“十拿十稳”。相应地，我们大约有仅仅1%的机会看到，由于外部的或内部的一些突发因素，会导致即便是传统负债比率也会发生从暂时痛苦到违约之间的结果。
我们不喜欢这种99∶1的发生概率，永远不会。我们认为，一个小的丢脸或痛苦不可能被一个大的额外回报所抵消。如果你的行动是合理的，你肯定会得到良好的结果。在绝大多数情况下，杠杆只会加速事情的运动。芒格和我从来不会匆匆忙忙，我们享受投资过程远胜于收获的结果，我们学会了与之朝夕相处。

◆ G．生命与负债

>> 毫无疑问，一些人通过使用财务杠杆变得非常富有。然而，这种方法通常也会令人穷困潦倒。当使用杠杆时，它会放大你的收益。这时，你的配偶会认为你很聪明，你的邻居会羡慕你。但杠杆这个东西是会令人上瘾的，一旦你奇迹般获利，很少有人会愿意再回到从前保守的状态。就像我们在三年级所学习的，一些人在2008年再次学习了，任何序列的正数，无论多么大的数字，只要乘以一个零，都会蒸发殆尽，一切归零。历史告诉我们，所有的杠杆通常导致的结果会是零，即便使用它的人非常聪明。
当然，杠杆对于企业的危险也是致命的。拥有巨额负债的公司通常会假设，这些债务到期之时，自然会再次得到融资。这种假设通常是有效的。然而，偶尔的情况下，或是因为企业内部的特别原因，或是因为市场正常的资金短缺，使得到期债务必须即刻偿还，不得延展。这时，只有现金才能解决问题。

>> 短缺之时，渴望借钱的人才知道，信用就像氧气。此二者，在充足的时候，人们不会注意到它们的存在；当它们消失的时候，人们才会发现它们的重要性。甚至，信用的短暂缺失都会让公司陷入困境。2008年9月的危机中，国民经济中的很多部门的信用在一夜之间消失，令整个国家陷入崩溃的危险边缘。
对于那些给伯克希尔的幸福造成丝毫危险的任何行为，芒格和我都毫无兴趣。我们俩加在一起已经有167岁了，从头再来不是我们的人生目标。我们确知你们和我们的父母，在很大程度上，将身家的大部分委托给我们管理。此外，一些重要的慈善机构也依赖于我们的谨慎行事。最后，我们保险公司承保的出险客户，他们将依赖我们提供的保险赔偿金，从现在延续到未来数十年。背负着所有这些人的托付，为区区额外几个点的回报而冒险，这样做是不负责任的。

◆ A．三类投资资产

>> 这个资产大类中包括黄金，现在的投资者对于黄金有着巨大的热情，因为他们信不过其他投资产品，特别是纸币（它们的价值的确令人担心）。然而，黄金有两大缺点，既没有太多用处，也不能自我繁殖。的确，黄金有一些工业和装饰上的用途，但是，这两种用途的需求都很有限，而且无法吸收新的产能。同时，如果你拥有一盎司￼的黄金，你会一直拥有一盎司，不会有增长。

>> 大多数黄金购买者的最大动机，是他们相信恐惧程度的升高会推升黄金价格。过去十年，这种想法是正确的。此外，黄金价格本身的上升被购金者视为自我观点的验证，更是增加了购买的热情。当“赶时髦”的投资者加入舞会，他们可以创造自我的真理，但其维续的时间可能仅仅是“一阵子”。
在过去的15年中，互联网公司的股价和房屋价格的表现证明了，最初原本合理的观点，一旦与高调飙升的价格结合在一起，就会导致异乎寻常的过量。在这些泡沫中，原本持有怀疑态度的投资者屈从于市场表现出来的“证据”，并且买家的队伍会在一定时间里持续地扩大，推动某个潮流继续向前发展。但是，吹大了的泡沫终究会爆裂。

◆ B．垃圾债券

>> 最后，他们都能坚守于自己所了解的业务，用他们的理性能力进行决策，而不是想当然地感情用事。（IBM的托马斯J．沃森爵士（Thomas J. Watson Sr.）遵循同样的原则，他说：“我不是天才，我只是有几个优点，但我能坚守这些优点。”）

>> 在金融界，对于过去表现进行统计所产生的“证据”要小心，如果历史书是致富的关键，那么福布斯400的富豪榜单将由图书管理员组成。

◆ C．零息债券

>> 制作恶作剧的最高荣誉应该归于那些零息债券的发行人，因为他们无法支付当前的利息。对此，我们的建议是：每当一位投资银行家开始大谈EBDIT，或其他什么人创建了一套新的资本结构，无论是需要当前支付的利息，还是累积到后面需要一起支付的利息，他都支付不起，你应该赶快合上你的钱包。反过来，你可以建议这个推销员和他高薪聘请的团队，在零息债券到期足额偿还之前，不准拿走他们的酬金；换言之，只有在这些债券按期兑付后，他们才可以拿钱，这时，再看看他们对这类生意的热情还能持续多久。

◆ D．优先股

>> 无论结局如何，我们都会留心一条投资基本的原则：你不必以失去它的方式，将它找回来。

>> 当维珍航空公司富有的老板理查德·布兰森（Richard Bran-son）被问及“如何成为一名百万富翁”时，他迅速回答：“实际上这没什么秘诀，你开始是一名亿万富翁，然后买一家航空公司。”由于不愿意盲从布兰森的观点，你们的董事长在1989年决定试一下，用3.58亿美元买了美国航空公司9.25%的优先股。
我喜欢并敬佩公司当时的CEO埃德·科洛德尼，到今天也是如此。但是，我对于美国航空公司的分析既肤浅又失当。我被公司长期盈利的运营历史所陶醉，并轻信于高级证券（意指优先股）表面上看起来提供的保护。我忽视了关键的地方：美国航空公司的收入，会逐渐受到结束价格管制所带来的激烈市场竞争的影响，而它的成本结构却依然是管制年代的延续。如果这些未有抑制的成本预示着灾难，那么沿用航空公司过去的记录可能也是。


>> 这种所有航空公司都遭遇的价格问题，揭示了一个重要真理：当一个公司销售的是普通商品型产品（或服务）时，它不可能比最为愚蠢的竞争对手聪明多少。


◆ E．衍生品

>> 想关闭衍生品业务说起来容易，做起来难。实际上，再保险行业与衍生品行业很类似，就像地狱，都是进去容易，但几乎不可能出来。在这两个行业里，一旦你签署了合约，就会一直背负着合约，合约涉及支付的绝大部分金额往往发生在数十年之后。的确，有一些方法可以转移风险，但大部分这样的策略依然无法让你免除连带赔偿责任。

>> 保险行业和衍生品行业的另一个共性是，二者报告的账面盈利通常都被过分夸大了。的确如此，因为，今天的盈利在很大程度上基于假设，这些预估的不准确数字可能在很多年后才会被暴露出来。
错误往往是坦诚的，它是对于一个人承诺的乐观倾向的反映。衍生品合约的双方也有着巨大的动机在账目上做手脚。从事衍生品交易的人所赚取的报酬（全部或部分）取决于按照市场结算的账面“盈利”，而实际上，这个市场并非真实的存在（想想我们之前提到的内布拉斯加双胞胎合约），这样常常最终变成了“按公式结算”。
这种结算方式的替代往往埋下巨大的祸根。通常而言，这些衍生品合约往往涉及多个变量，再加上结算日期的遥远，这都增加了合约双方采用不实假设的机会。例如，在双胞胎的例子中，合约双方很可能使用不同的假设模型，使得双方在各自的账面上都显示出巨额利润的存在，而且这种情况会维持很多年。在极端情况下，这种按公式结算的方式会堕落成我所说的“按神话结算”。

>> 银行体系中，意识到连锁反应引发的严重问题，是美联储成立的原因之一。在美联储成立之前，一家体质欠佳的银行的倒闭有时会引发突然的、未有预期的流动性需求，这会导致原本健康的银行也出现问题。美联储现在将有问题的银行隔绝起来，以防止问题的蔓延。但是在保险行业或衍生品行业，没有一个类似美联储式的中央银行来防止多米诺骨牌效应的发生。在这些行业中，一些基本面良好的公司很有可能仅仅由于其他公司发生问题而受到拖累。当一个行业存在这种“连锁反应”的威胁时，有必要将彼此这种形式的牵连最小化。这就是我们的再保险公司正在做的事情，这也是我们退出衍生品交易的一个原因。

◆ F．外汇和国外权益

>> 有一点大家一定要搞清楚，我们在外汇方面的投资不代表我们质疑美国。我们生活在一个富有的国度，这个体系相当重视市场经济、法制原则和机会平等。我们仍是当今世上最强大的经济体，我们非常幸运生活在这样的国度。
但我们国家的贸易政策终将拖低美元，美元价值的下跌已经非常巨大，且没有任何好转迹象。如果政策不变，外汇市场的无序情况会继续发生，并会在政治层面和金融层面上产生溢出效应。没有人知道这个问题最终会演变成什么样，但是，问题并非遥不可及，政策制定者应该现在就正视它的存在。

>> 如果经常账目项下的赤字继续发展下去，那么从今天起的十年之后，其他国家及其公民所拥有的美国资产将达到大约11万亿美元。如果外国投资者能从其持有的资产中获得5%的收益，那么，整个美国每年需要输出5500亿美元的产品和服务给外国人。十年之后，我们的GDP预期能达到18万亿美元（假设低通胀，虽然这个假设远不能确定），到那时，我们美国这个大“家庭”需要将3%的每年产出交给世界其他国家，作为过去放纵挥霍的代价。这种情况可不像预算赤字的情况，这是真正的父债子偿，前人作孽、后人买单。

>> 除非美国人从现在开始大幅度省吃俭用、勤俭度日，并开始持续保持贸易顺差，否则的话，目前每年美国需要支付给世界其他国家的“版税”，将毫无疑问地引发美国政治的不稳定。现在，美国人仍然会过得很不错，因为经济的成长，将来也会过得更好。但一想到需要向外国的债主和所有权人不断地进贡，他们便会很恼火。我在这里必须夸张一点以显示强调，在一个现在强调“所有权社会”的国家里，这种“佃农社会”现象的出现不会令人感到愉快。但这正是我们的贸易政策导致的结果，共和党和民主党都在支持这样的政策。

>> 我对这种重商主义的做法也持谴责态度，但事实上，就算不是有意的，世界上其他国家实际上在对美国实行重商主义，觊觎我国丰厚的资产以及良好的信用历史。确实，除了美国，世界上再也没有其他国家可以像我们一样使用几乎无上限的信用。截至目前，大部分的外国投资者还是相当乐观，他们认定我们是花钱如流水的瘾君子，而且是极其富有的瘾君子。

◆ G．房屋产权：实践和政策

>> 当前的房地产崩溃应该让购房者、贷款提供商、经纪人、政府部门学到一些简单的教训，以确保未来的稳定。购买房屋时，至少应该实打实地支付10%的首付款，购房者的收入应该可以轻松负担之后的月供，购房人的收入情况应该被仔细地审核。
居者有其屋，这当然是个美好的愿望，但不应该成为我们国家的首要目标。让购房者能待在他们的房屋里不毁约，才应该是目标。

◆ A．交易的祸害：交易成本

>> 接下来，就到了我们今天的结论。本来，如果G家族的成员只是躺在摇椅上，什么都不做，就可以获得所有的盈利，但现在，有相当部分的盈利流进了日益膨胀的帮手大军的口袋里。特别是近来流行的盈利奖励分配制度，使得这类问题愈加突出。当帮手们或是因为聪明，或是因为运气好而取得盈利之时，他们会获得盈利的大部分；当帮手们或是愚蠢，或是运气差（或压根就是欺骗）而导致损失之时，所有的损失以及巨大的固定费用，都留给了家族成员承担。

◆ B．吸引正确的投资者

>> 我们的目标是吸引长期投资者，他们在买入股票之时，并没有卖出的时间表，或卖出的股价目标，他们打算与我们休戚与共，直到永远。对于那些希望自家股票交易活跃的CEO，我们无法理解，因为交易活跃就意味着公司的股东持续地离去。

◆ C．分红政策与股票回购

>> 首先要明白的一点是，并不是所有的收益都是在同等的情况下创造的。在很多公司，尤其是那些具有高资产/利润比特征的公司里，通货膨胀会侵蚀财报中显示的部分甚至全部收益。这个会被通胀侵蚀的收益部分，我们称之为“受限定收益”，不能被用于派发红利，以利于公司保持其经济竞争地位。如果这部分受限定收益被用于分红，公司会在如下的一个或若干方面丧失其根基，如维持销量的能力、长期竞争力、财务实力。对于这样的公司，无论其分红率多么保守，持续地派发受限定收益都注定会完蛋，除非有新的资本注入。

>> 回购股份的另一个好处不那么容易精确地测量，但是随着时间的推移也非常重要。通过股份回购，管理层清楚地证明，他们关心提升股东财富，而不是目无股东，只顾拓展企业帝国版图，以至于干出无益于股东利益甚至损害股东利益的事。看到这些行为，股东以及未来潜在的股东会提升他们对于企业未来回报的信心。这种向上的预期调整，会反过来推动股票的价值更加与内在价值趋于一致，使得股价更为理性。相比一家掌握在自私自利的管理层手中的公司，投资者应该给那些被证明关心股东利益的管理层手中的公司出更高的价。

>> 芒格和我都承认，我们有自信可以评估仅仅一部分交易股权的内在价值，而且是当我们拥有一系列有价值的，而不是伪精确的数字之后。然而，我们看到很多公司在进行回购时过度支付了那些离去的股东，而将代价转嫁给了后面继续留下的股东。在为这些公司辩护时，我必须说，公司的CEO对于自家公司的前景持有乐观态度是很自然的。对于公司整体情况，他们也会比我了解的多得多。但是，我仍然还是忍不住要说，今天太多的市场上的回购活动，与其说是为了提高公司每股价值，不如说是管理层“秀”信心、赶时髦的方式。

>> 这中间的逻辑很简单：如果未来你只是买入股票，无论你用自己的资金直接买入，或通过你的公司间接买入，上升的股价只会对你不利。反倒是股价平平对你有利。然而，情感这个东西经常是复杂的：大多数人，包括那些未来只是打算买进的人，看到股价上升会感到舒服。这些股东的心态，就像一个天天开车上下班的人，刚刚加满了当天的汽油后，发现油价上升而心怀喜悦一样。

◆ D．拆股与交易活动

>> 如果我们分拆股份或采取其他关注股价的措施，而不是关注企业价值，那么，势必会引来逊于现有股东的新晋股东。在1300美元/股的价位，能负担得起1股的投资者不多。如果我们实施1股分拆为100股的方案，那么新股的潜在卖家会是更好的股东吗？
持有这种想法的人，以及那些冲着分拆预期而来的买家，毫无疑问将会稀释现有股东群体的质量。持有9张10美元钞票，会比持有1张100美元钞票感到更富有吗？如果用一帮敏感易变，关注数量胜于质量的新股东，来替代我们思维清晰的现有股东，这样会提升我们的股东质量吗？那些因非价值因素买进的人，同样会因非价值因素而卖出。这些人的存在，加剧了股价与企业无关的飘忽不定的动荡。
我们试图避免采取这样的政策，如果它们的存在可能吸引短线股价的投资者。我们会采取那些可以吸引关注企业价值的长期投资者。就像你在充满理性、拥有充分信息的投资市场中，去购买伯克希尔的股票一样，同样，在你需要卖出伯克希尔的股票时，你也值得拥有一个同样的市场环境。我们会为这样的市场存在而努力工作。

>> 股市上，具有讽刺意味的现象之一是强调所谓的活跃性，使用的术语称之为“市场性”“流动性”。经纪商们为那些换手量巨大的公司大唱赞美诗（他们不能填满你的口袋，但能填满你的耳朵）。但是，投资者应该明白，对于赌场管理员有利的事情未必对客户也有利。过度活跃的股市是企业的扒手。
例如，一个净资产收益率为12%的典型公司，假设它的股票具有非常高的换手率——比方说，每年100%。如果换手以其净资产进行，这家假设公司的股东将支付作为交换所有者权力的成本，合计起来，高达每年净资产的2%。这项活动对于公司的盈利没有任何贡献，同时，意味着其中的1/6损失于交易的“摩擦”成本。（这还没有将期权交易计算在内，否则，摩擦成本将更高。）

◆ A．错误的动机和高昂的代价

>> 经历了几次这样的失败，我最终记住了从一位职业高尔夫球手那里得来的有用建议。（这位职业球手就像参与我游戏的其他人一样，希望保持匿名。）他说：“多练习未必能完美，但多练习能保持恒定。”

>> 我们必须成长。”
似乎应该问一问，“我们”是谁？对于现有的股东而言，他们面临的现实是，现有企业的估值在发行新股时已经缩水。如果伯克希尔公司明天发行新股去进行并购，那么伯克希尔的商业版图将会包括目前所有的加上新的公司业务。但是，在这个过程中，你所占的那些难得的优秀企业权益份额，例如禧诗糖果、国民保险公司等，会自动减少。

>> 在考虑企业并购时，很多管理层倾向于关注是否该项并购对于每股盈利有稀释或非稀释的效应（或对于金融机构，在每股净资产方面的影响）。这种过于关注的强调，蕴藏着巨大危险。设想一下，一个25岁的MBA（工商管理硕士）一年级学生正在考虑，将其未来的经济利益，与一个25岁的做零活的民工未来的经济利益进行合并。MBA学生会发现，将自身的权益用“以股换股”的形式与民工的权益合并，会提升他的近期收益（而且是大规模的提升）！但是，还有什么交易比这更加愚蠢呢？

>> 收购产生的问题常常因其生物学的偏差而被放大。很多CEO们能够获得他们今天的社会地位，是因为他们具有丰富的动物精神和自负秉性。如果他们具有这些强烈的品质——应该承认，有时这正是他们的优势所在——那么，当他们达到辉煌顶峰的时候，这些特点并不会消失。当这样一个本来就雄心勃勃的CEO，被他的顾问们鼓动着进行并购交易时，他的反应可想而知。这样鼓励性的推动原本就是多余的。
前些年，我的一位CEO朋友——必须说明这是一个玩笑——无意中对很多大型的交易进行了病理学的描述。这位朋友管理着一家经营财产险、灾害险的保险公司，曾经试图向董事会解释为什么要收购一家人寿保险公司。在进行冗长沉闷的、经济学和战略理论分析之后，他突然扔掉了手中事先准备的脚本，带着孩子般顽皮的表情，说了一句：“哦，哥们儿，别人家的孩子都有。”

◆ D．稳定的收购政策

>> 在伯克希尔，我们与其他有意收购的公司一样，对于预测未来面临很多困难。就像大家一样，我们面临的内在固有的问题是，卖家对于公司的了解远远超过买家，而且他们会挑选出售的时机——一个可能正好是“走路没有问题”的时机。
即便如此，我们还是有一些优势的，或许我们最大的一个优势就是我们没有什么战略规划。这样，我们没有必要向一个特定的方向推进（一条最终总是推高愚蠢收购价格的道路），我们只是简简单单地去决策，选择什么对我们的股东有利。在这样做的过程中，我们总是在心中将我们的行动与很多遇见的机会相比较，包括在股市上购买世界上最好公司的部分股票。主动收购还是被动投资，我们做这样的比较是一种纪律，这种纪律是那些仅仅关注扩张的管理层很少考虑的。

>> 我们愿意看到中间商在替我们思考做事的基础上赚取费用，在此，我重申一下我们寻找目标公司的标准：
关键词：目标公司的六个特征
（1）规模够大。
（2）具有被验证了的持续盈利能力（那些对于未来做出的预测，我们毫无兴趣；对于所谓“困境反转”型的公司，我们也没有兴趣）。
（3）在负债极少或没有负债的情况下，公司具有良好的净资产回报率。
（4）具备管理层（我们无法提供管理人员）。
（5）业务简明（如果有太多的科技成分，我们可能搞不明白）。
（6）明确的报价（我们不想在不确定价格的情况下，浪费彼此的时间进行讨价还价）。
我们不会参与恶意收购带来的公司接管。对于我们感兴趣的对象，我们承诺完全的保密，以及非常迅速的回复，通常不会超过5分钟。对于收购的方式，我们倾向于用现金支付，但如果我们得到的内在价值物有所值的话，我们也会考虑以发行新股的形式进行支付。

◆ A．伊索寓言和失效的灌木丛理论

>> 投资与投机之间的界限永远不是明确清晰的，尤其当大多数市场参与者沉浸在巨大愉快的氛围中时，二者的界限更是模糊得厉害，没有什么比不劳而获却能大笔捞钱更容易让人失去理性了。有了这样令人陶醉的经历之后，任何正常理智的人也都会像参加舞会的灰姑娘一样被冲昏头脑。这些参与者会继续投机的游戏，投机于那些相对于未来现金流，有着巨大估值的公司。
他们明明知道，在舞会逗留的时间越久，南瓜马车和老鼠现出原形的概率就越高，但他们还是舍不得错过这场盛大舞会的每一分钟。这些轻佻疯狂的参与者都打算在午夜来临的前一秒离场，问题来了：舞会现场的时钟没有指针！

>> 近来，我们最为看好的“灌木丛”是通过协议谈判购买整个公司，这种方法的确令我们满意。但是，你们应该明白，这类收购顶多带给我们一个合理的回报。要想获得超额回报，必须等到整个资本市场极其惨淡的时候。整个市场感到悲观之时，才是超额回报机会出现之日。我们现在距离这种情况还远。


◆ B．内在价值、账面价值和市场价格

>> 尽管内在价值的计算非常重要，但它却无法精确计算，甚至计算起来经常是伴有严重的错误。公司未来的不确定性越高，计算内在价值的出错偏差可能性就越大。在这一点上，伯克希尔具有一些优势：我们拥有多元化的、相对稳定的现金流，同时拥有极佳的流动性和极少的债务。这些都意味着，与绝大多数公司相比，伯克希尔的内在价值更容易准确地计算。
然而，虽然说伯克希尔的财务特征有助于计算的准确性，但仅仅依靠众多稳定的现金流来计算内在价值依然是极其复杂的工作。回到1965年，那时我们只有一个小小的纺织厂，计算它的内在价值简直是小菜一碟。现在，我们拥有68家公司，分布在不同的行业，具有不同的财务特征。这些互不相干的企业，加之我们巨大的投资金额，使你根本不可能轻易地分析我们的合并报表，然后准确地预估其内在价值。
为了更好地解决这个问题，我们尝试将我们的业务合理地分为四类，在这个报告稍后的部分对于每一类进行一一分析。当然，伯克希尔公司的整体价值可能大于或小于这四个部分业务价值之和。最终的实际结果取决于两个因素：一是，作为一家大公司的各个组成部分是运营得更好还是更差？二是，在母公司的管理之下，公司的资本配置是更优还是恶化？

◆ C．透视盈余

>> 伯克希尔公司自己的财报盈利在某些重要方面也存有令人误解的成分。我们进行了大量的对外投资，被投资公司的盈利远远大于其分红数额，但我们的账面上只能记录分红的数字，而不是相应的盈利数字。
最为极端的明显例子是大都会/ABC公司，我们持有这家公司17%的股份，相应的盈利约为8300万美元。但是，根据GAAP，伯克希尔的损益表中只能反映收到的分红53万美元（它派发60万美元红利，其中含税7万美元），余下的8200多万美元的留存利润，会继续为我们工作，但却不被记录在我们公司的账上。

>> 我们对于这种“被遗忘，但却存在”的盈利的态度很简单：如何记录这些数字并不重要，重要的是，它们的归属以及之后的运用效益。至于审计师们是否听到森林中有一棵树倒下，我们并不关心，我们关心的是，这棵树属于谁以及拿它做什么。
当可口可乐公司用它的留存利润回购股份之时，等于提高了我们在这家世界上最有价值的公司的所有权比例。（当然，可口可乐在很多方面都有运用留存利润提升价值的行为。）除了回购股份之外，可口可乐还会将利润以分红形式派发给股东，我们则可以用这些分红买入更多的可口可乐股票。
只是相对于前一种方式——“公司回购股份”而言，以“分红再买入”的后一种方式是效率较为低下的方式，因为我们需要为分红支付税金。如此一来，对于公司同样的资金支出，后一种方式使得我们提升的持股比例不如前一种高。然而，具有讽刺意义的是，后一种方式在伯克希尔的财报上会体现出更多的“盈利”。

>> 这样的方式会强迫投资者思考企业的长期前景，而不是短期的股价表现。观点会改变结果。当然，长期而言，投资决策的记分牌是市场价格。的确如此，但是，决定价格的是未来的盈利。就像打棒球一样，投资者需要盯着的是场上，而不是记分牌。

◆ D．经济的商誉vs．会计的商誉

>> 实际上，即便你们从来没想过商誉及其摊销的问题，也能过着充实而有意义的生活。但是，投资和管理专业的学生应该明白这个主题所包含的细微差别。我自己的想法与35年前相比已有了巨大的变化。那时，我所受到的教育看重的是有形资产，而避开那些倚重经济商誉的企业。这种偏见令我错失良机，犯了很多重大错误，尽管我们的原则是“宁可错过，避免犯错”。
凯恩斯发现了我的问题所在：“最难的不在于接受新思想，而在于如何摆脱旧思想的束缚。”我摆脱旧思想的过程可谓太迟了，部分原因是我从同一位老师那里所学到的东西实在太有价值了，它们在过去有用，并将继续有用。最后，直接或间接的从商经历，让我对那些拥有巨大持久商誉而仅需极少量有形资产的企业兴趣浓厚。

◆ E．退休福利估计

>> 所有这些公司的退休基金平均持有债券和现金的比例为28%，这些资产的预期回报率不会超过5%。当然，获得更高回报的可能性是存在的，但是，随之而来的是相应的（或更大的）损失风险。
这意味着其余72%的资产——主要是直接或通过对冲基金、私募基金持有的股票投资——必须取得9.2%的回报，才能使全部资产达到假设的8%回报。而且，这个回报必须是扣除所有费用之后的回报。但是，这个9.2%的要求远远超出了它们过去的历史成绩。

>> 一些公司在欧洲的企业也有像美国一样的退休金计划，在他们的会计准则中，几乎所有的美国退休金回报假设都比非美国退休金高。这种不一致令人迷惑：为什么这些公司不将其美国的经理人派到非美国地区去，让他们将那些公司的资产回报也提高呢？我从来没有见到谁对此进行过解释。但是，负责审核这些假设回报的审计师和精算师们，似乎也从来没有对此提出过异议。

◆ A．并购

>> 有点咬文嚼字，事实上这与合并背后所代表的真实情况大不相同。毫无疑问，既然有交易，就一定有购并方与被购并方，不管你如何构建交易的细节，一定有一方是被另一方买下。其实很简单，只要你问问交易双方的员工，谁是征服者，而谁又是被征服者，就知道是怎么一回事了，绝对不会搞混。所以从这个角度来看，FASB的坚持绝对是正确的，在大部分的购并案中，绝对有买卖的性质存在，当然确实也有真正的“对等的合并个案”发生，但出现的概率实在是少之又少。

◆ D．退休福利

>> 在进行购并时，芒格和我也会尽量避开那些背负高额退休金负债的公司。因此伯克希尔虽然目前拥有超过数以万计的员工，但在退休金方面的负债和未来的退休后负债成本并不严重。不过，我还是必须承认，在1982年时我曾经差点犯下大错，买下一家背负沉重退休金福利负债的公司。所幸的是，后来交易因为某些我们无法控制的因素而告吹。

>> 最近几十年来，没有一家公司的CEO会想到，他应该向董事会提出这种没有上限的退休后健康福利计划，就像其他公司一样。他不必具有专业的医学知识，也能知道越来越高的预期寿命以及福利支出将会把一家公司拖垮。但是即便如此，很多经理人还是闭着眼睛，让公司透过内部自保的方式，投入这种永无止境的大坑洞，最后导致公司股东承担血本无归的结果。就福利而言，没有上限的承诺所代表的就是没有上限的负债，这种严重的后果，甚至危及了一些美国大企业的全球竞争力。
我认为之所以会有这种不顾后果的行为，部分原因是由于截至目前，会计规则并没有要求公司将这种退休后的健康成本呈现在会计账上。相反地，会计原则允许采取现金发生制，此举大大地低估了累计的负债。而公司管理层和他们的会计师采取的态度就是眼不见为净。具有讽刺意味的是，同样是这批管理层，竟然还常常批评国会对于社保或其他计划采取现金发生制的思维，根本就不顾未来年度所可能产生的庞大负债。

◆ A．公司税负的分配

>> 我们的结论是，在一些情况下，公司税率降低的好处会全部或者几乎全部地落在公司以及股东身上；在另外一些情况下，这种好处会全部或者几乎全部传递给消费者。最终的结果取决于，公司商业特许权的强弱，以及特许权的利润率是否受到监管。

◆ 后记

>> 美国天文学家卡尔·萨根（Carl Sagan）生动有趣地描述了这种现象：想想细菌的命运，它们每隔15分钟分裂一次自我繁殖。萨根说：“这意味着一小时的时间，细菌的繁殖翻四番，一天能繁殖翻96番。尽管一个细菌的重量仅有大约1克的一万亿分之一，经过一天无性繁殖的放纵之后，它的后代会像一座大山一样重……两天之后，比太阳还重。照这样发展，用不了多久，宇宙中所有东西都会由细菌构成。”
但是，不用担心，萨根说，总有某种障碍会阻止这种指数级的增长，“这种障碍或是食物中出来的小虫，或是它们自己之间相互毒杀，或是它们羞于在公众场合进行繁殖。”
即便在艰难的日子里，芒格（伯克希尔的副董事长和我的合伙人）和我也没有将伯克希尔看作细菌。让我们感到无限悲伤的是，我们还没有找到让伯克希尔的净值每15分钟翻番的方法。此外，我们对于在大庭广众之下进行财务上的自我繁殖成长并无羞愧。然而，萨根的观察结果仍然适用。

>> 资金太多是获得超级投资回报的敌人。伯克希尔公司现在的净资产是119亿美元，而当年，芒格和我接手管理之时是2200万美元。尽管市面上一如既往有很多优秀的公司，但是考虑到伯克希尔目前的资本规模，很多机会已经不值得考虑。我们现在只考虑那些至少可以投资1亿美元的机会。鉴于这个最低限额，伯克希尔的投资空间大大缩小了。

>> 尽管如此，我们仍然会坚守来时的路，不会放松我们的标准。著名的棒球选手泰德·威廉姆斯在他的著作《我的生活故事》（The Story of My Life）中，解释了其中的原因：“我认为要成为一个优秀的击球手，你必须等到出现好球的机会才去击打，这是本书的第一原则。如果我不得不去抓住我的幸运区以外的球，我就不会成为0.344的优秀击球手，我可能只是0.250的平庸击球手。”芒格和我同意这个观点，并会等待出现在我们自己“幸运区”的机会。

>> 我们会继续对政治和经济的预测置之不理，对于很多投资者和企业家而言，这些是非常昂贵的消遣。30年前，没有人能够预见到越战的扩大，工资管制和物价管制，两次石油震荡，总统辞职，苏联解体，道琼斯指数一天大跌508点，或国债收益率在2.8%到17.4%之间巨幅波动。
但是，令人吃惊的是，这些重磅炸弹式的事件都未能对本·格雷厄姆的投资原则产生丝毫的打击和动摇，这些事件也没有动摇“以合理价格购买优秀企业”的原理。试想一下，如果出于对未知的恐惧而延迟或改变资本的使用，我们的代价会有多大？事实上，当对于宏观事件的忧虑达到顶峰之时，恰恰是我通常做出最佳买卖的时机。对于那些跟风追求时尚的人而言，恐惧是敌人，但对于那些关注基本面的人而言，恐惧是朋友。
未来30年，一定会出现一批不同类型的流行股票。我们既不会预测它们是哪些股票，也没有打算从预测中获利。如果我们能找到像过去所购买的公司一样的公司，外部的惊喜对于我们长期的表现结果几乎没有什么影响。

>> 我们可以向你们承诺的是，所有人会得到与其持股相匹配的收益，在你们持有伯克希尔期间，你们所获得的与芒格和我一样。如果你们遭受痛苦，我们也会遭受痛苦；如果我们发达，你们也会一样发达。我们不会引入一些所谓报酬机制，来破坏这种纽带式的联系，这些报酬机制在股市上升时给予我们（作为管理者）更多比例的报酬，而在下跌时却没有太大损失。
我们进一步向你们承诺，我们个人财富的绝大多数都会集中在伯克希尔股票上。我们不会让你将投资的钱放在我们这里，而自己却将钱放在别处。此外，由于伯克希尔承载了我们家庭大多数成员，以及那些从20世纪60年代就追随芒格和我的伙伴和朋友们的投资，我们没有任何理由不尽全力做好我们的工作。

>> 对人并非易事。当然，发现一个聪明的人并不难，他们之中，有的具有令人印象深刻的投资记录。但长期的投资成功，仅仅凭当下的头脑聪明和短期的业绩优秀是远远不够的。
长期来看，市场一定会发生非同寻常甚至离奇的事件。一个单次、重大的事件可能会将多年以来累积的、一系列的成功一笔勾销。我们需要的是从基因排序上能够识别和避开这类风险的人，包括那些之前从未遭遇过的重大风险。有些潜伏在投资策略中的危险，用今天金融机构普遍使用的模型是无法发现的。
性格也是极其重要的。独立思考，情绪稳定，对人性和机构行为具有敏锐的了解，这些都会在长期投资成功中起到非常重要的作用。我见过很多非常聪明的人，但他们缺乏这些美德。
