#+title: The Secret to Career Success

[原文链接](http://algeri-wong.com/yishan/the-secret-to-career-success.html)

这个秘诀有三个缺陷:
- I could be wrong. (不一定正确:)
- If I'm right, it'll only make your career as successful as mine, so there is a natural implicit cap here. I am not like, you know, Jawed Karim or Mark Zuckerberg or anything. (存在一个隐式上限)
- This probably only works as well as it does at fast-moving internet companies like the ones I tend to work at. (可能只能在SV这种地方的快速发展的互联网公司起作用)

**Focus primarily on making everyone around you succeed.** 秘诀就是帮助别人成功

First, realize that your career success is not primarily or significantly determined by you. You can work hard, you can strategize, you can plan your career, but there are a lot of other larger forces at work. You might make an incremental difference if you do all those things, but overall you will be swept along in the tide of whatever macroeconomic or industry or company-wide force comes along. Accept this.(职业成功很大程度不取决于自己,  相反取决于你所在的公司和平台)

**另外一种策略是只关注自己的成功**

If you do things that advance yourself, you will face envy, resentment, passive-aggressiveness, or at the very least, no assistance from others around you. You may even face active opposition. Instead, if you do things that advance others around you, those same people will help you readily. No one is going to try to stop you from helping them succeed. (但是这种策略会招来嫉妒, 憎恶, 被动激进, 至少周围没有人愿意来帮助你)

Self-advancing strategies are friction-generating and thus burn effort, while strategies that involve helping others tend to be met with assistance, and hence multiply effort. Ultimately, by focusing most of your effort on making others succeed, you will simply cause more things to get done and more things to move forward - more total effort will go towards Getting Real Things Done. You will also be happier, because psychologically-speaking, you are meeting with fewer small obstacles to your efforts, and research shows that tiny day-to-day frictions make people unhappy. If you are able to proceed through your day with your efforts being assisted on all sides, you will be happier and this will give you more energy to pursue even more efforts. The effect compounds itself.

**Helping Everyone Else Succeed Helps You Advance**

It is also the route to advancement most likely to engender the least amount of resentment. When someone gets promoted, there are natural bitter feelings that arise from envy as that person's peers ask why it was that person who was promoted and not them. The person who is most broadly recognized as being someone who is focused on the success of others is the one that everyone wants to see advance, as they are simultaneously the least threatening and the one who, in their new position, is most expected to use it to continue benefiting others rather than themselves (which is a latent fear in people whenever they see someone being promoted).(那些帮助别人成功的人, 通常别人也更希望看到他成功. 对于他们来说, 他没有任何威胁, 并且如果他可以promoted的话, 对于他们来说可以继续受益)

Be that person! Focus on helping others succeed, and because people are naturally reciprocal, they will want to help you and they will likely advocate for your advancement. And if you are promoted as a result of it, remember that you are now in a position where you have even *more* ability to help others, so make sure you keep doing it!(人们都是reciprocal的, 互助互惠)

Thus will your effort be multiplied and amplified through a cooperative and willing network, one that will eventually begin to imitate your ethic, and hopefully develop into a tidal wave of success that sweeps you and everyone along with it.
