#+title: 程序员健康指南(The Healthy Programmer)

https://book.douban.com/subject/25981248/

** 关于跑步
步行是一项很强大的活动。它可以促进创造性思考，而且是让身体健康起来的最好方式。说真的，几次轻快的散步比健身房里的一次有氧运动效果要好得多。在本章，你会了解到，定期的散步如何显著地影响患病的风险值，甚至是影响一个人的生死。我们会探讨这些问题：每次散步该走多久，散步时该走多快，多久散一次步，甚至连走路的方式我们都会涉及。到最后，你将了解到，为什么这个简单的锻炼方式会是你生活中能做到的最重要的事情之一。反正对怀尔斯来说，确实如此。

对于步行或者进行其他运动时应该控制什么样的强度，上文信州大学的研究为我们提供了很好的基准。研究中强调，受试者的步行强度应该以个人最大摄氧量（VO2max）的50%为准。和心率比较，这个说法好像复杂了些，因为每个人情况都各不相同。一般来说，最大摄氧量（VO2max）的50%%大约是最大心率率（HRmax）的60%。最大心率可以用220减去你的年龄得出。平均30岁左右的人，其基准心率需达到每分钟11下（114BPM）达到这个数值的运动才是最有效果的。这与CD经常推荐的那个“快步走”的建议，可谓是英雄所见略同。

事实上，信州大学的研究里还有一个在更短时间内完成更高强度步行锻炼的小组实验。实验取得的效果比匀速步行的效果还要好，因此这个实验强烈建议你将锻炼活动分为两个10分钟，或者四个5分钟，随便你怎么分都行只要确保缩短了锻炼间隔，同时也提高了锻炼强度即可。

** 站立办公

凡事都有两面，站立也是，既有好的影响，也有坏的影响。这样说来，使用站立式办公桌，既要利用它的优点，也要缓解赫奇博士提到的那些对身体的不利因素。下面我们提供一些建议。.
- 经常换姿势赫奇博士建议，每次坐着不要长于20分钟，但每次站着也不要超过20分钟。因此，关键就是要让身体保持活动时常调整姿势，工作时多歇息。
- 不舒服就换姿势如果站了一会儿后，大腿或脚掌开始有疼痛感时，那就坐一会儿吧。以此类推，如果坐久了感觉后背和肩膀开始疼痛时，就站一会儿吧。不管是站还是坐，都不该让自己感觉不舒服，最好的判断方法是以能让你保持良好的站姿或坐姿为准。
- 一有机会就出去走相对于站立，还是尽可能步行吧。步行能消除绝大多数与站立有关联的风险，还能燃烧更多热量（大概每小时燃烧100卡路里）。总的来说，站立相关的健康风险都和站着不动有关。如果能在站立时找机会活动一下，就会对健康有好处，比如打电话就不失为一次很好的机会。

不过，我们从这些实验中可以大体地得出一个结论：把健身球当椅子对健康是有好处的，但是使用时间不宜过长。事实上，每次大概使用10到20分钟就差不多了。本章在开头不就说了嘛，长时间保持单一姿势都是不妥当的。对健康最有利的办公桌，应该能让人在每天的时间里，既能坐着，又能站着，还能保持身体平衡，偶尔还能弹跳一下。

** 灵活的饮食方案

灵活的饮食方案并不是一份减肥计划。实际上，它是为你的个人健康需求而量身打造饮食计划的方法。因此，本章的重点不在于减肥，而在于改变饮食习惯中不健康的环节。在阅读本章时，请明确一点，你需要给自己定制两份饮食方案：一份是能帮你减肥用的，一份是能让你一生受用的。这两份饮食方案的内容不一定非得一致，重要的是，你得保证后者能让你心情愉快。

** 放松眼睛

我们在单元测试中提及的因素，都会加剧剧CVS。因此，这些问题因素迫在眉睫，必须尽快解决。除了改变工作站，也可以改变使用工作站的方式。使用下面的这些建议，能有效降低罹患CVS的风险。
-进行眼部锻炼：眼部疲劳的首要原因，就是它们总是长时间保持对某个点的聚焦。想象一下长时间提着某一样重物，过一会儿你就得换个手，对不对？因此，锻炼眼部也是很有必要的。记住“20-20-20法则”：每在电脑前面工作20分钟，就看看20英尺（6米）远的物体，大概看20秒钟。
-摘掉眼镜：许多近视者在使用电脑其实不需要戴眼镜。尝试摘下眼镜，你会发现没戴眼镜也能看清楚。事实上，很多验光师都建议，尽可能不要总戴着眼镜。
-使用滤光眼镜：如果在用电脑时可以不戴眼镜，还可以试试滤光眼镜。滤光眼镜制造商声称，这种眼镜能提供更舒适的佩戴体验和视觉环境，从而过滤“人造”光线，降低眼压。有一些早期的研究显示这种技术有助于减少眼部刺激、眼睛干涩、流泪及眼部疲劳。但是，也没有明确的证据表明它们一定有用。这方面还需要进一步研究和验证。

** 避免头疼诱因

| 诱因           | 详细说明                     |
|----------------+------------------------------|
| 天气           | 低气压，高温，高海拔         |
| 荷尔蒙         | 月经期，怀孕期，更年期       |
| 感官刺激       | 香水，清洁用品，强光，吸烟   |
| 高强度体力活动 | 有氧锻炼，举重，脱水，性行为 |
| 生活方式       | 缺乏睡眠，压力               |
| 饮食方式       | 咖啡因，谷氨酸钠，阿斯巴甜，酒精             |

- 咖啡因：大多数程序员对咖啡因应该都不陌生。IT界甚至有一个Jol大奖，就是由Jolt可乐公司赞助的。咖啡因有一定好处，却也能导致头痛。矛盾的是，咖啡因还能暂缓头痛，有人将其视为偏方。问题是，虽然它能够暂时缓解头痛，但同时也会导致反弹性头痛。因此，摄入咖啡因一定要谨慎。如果你有头痛，应该完全避免摄入咖啡因。
- 味精：许多人坚持认为，谷氨酸钠会导致或加重头痛，也有一些医生认同这个观点。与这个导致头痛的食物清单上的其他项一样，你也得格外留心谷氨酸钠。尽管谷氨酸钠有害健康的传言没有什么根据，但如果在摄入谷氨酸钠时伴有头痛，那你就应该有意识地避免食用含有大量谷氨酸钠的食品。这些食品包括速食汤、肉羹汤、咸味小吃、调味肉汁、加工过的肉类制品、素食汉堡，或者任何在广告中自称“天然风味”的食物。
- 阿斯巴甜：很多人认为人造甜味剂会引起头痛，尤其是阿斯巴甜。但也不是所有的人造甜味剂都会这样，糖就不会。如果感觉到某个牌子的节食饮料会加重头痛，那就尝试换一个牌子吧。天底下好吃的东西多了去了，更何况甜味剂。
- 酒精：有一些酒精饮料导致头痛的效果最为严重。红酒、干邑或其他深色酒水一般含有高浓度的乙醇同族元素，这些元素会引发头痛。而像伏特加这类酒，在制作中对酒品的蒸馏工艺有非常严格的要求，所以乙醇同族元素的含量要低很多，可能就不会引发头痛。一般来说，颜色较浅的酒精饮料中乙醇同族元素的含量都会偏低。留意自己在喝哪种酒精饮料时会感觉头痛，这样你就能找到那些不会引发头痛的饮料了。
- 脱水：脱水问题能在多方面引发头痛。脱水会导致人体内一些有益矿物质（如钠和钾）的流失，导致身体内化学物质失衡。另外，它还会使身体内的血液量减少，导致大脑缺乏血液和养分的供给。这会使大脑内的血管扩张和肿胀，从而让人感觉头痛。按照这个说法，预防头痛的最好方法就是喝足量的水。

** 对抗头疼症状：

治疗头痛最好的方法，就是把灯光调暗，躺下来，闭上眼睛，试着放松。这个方法没有副作用，不会导致反弹性头痛。要是有可能，在前额放一条浸湿的凉毛巾。这个方法虽然简单，但经证明确实有效。

其他一些研究表明，像冥想、太极拳和瑜伽等放松技巧，都能有效缓解头痛。有些人也会尝试在头痛发作时做一些简单的运动，不过头痛还是得自己消停，这样只是分散了对头痛的注意力，并没有真正缓解头痛。

** 认识背部肌肉

长期以来，背部疼痛的处方都是卧床休息，严重的甚至要进行手术。在一些极端的案例中，许多医生甚至使用一种与中世纪拉肢刑架相类似的设备来拉伸脊椎。不过在今天，人们基本都认识到，大多数背部疼痛和身体核心肌群太弱有关，而且最好的治疗方法就是运动。

医生之所以要花这么长时间才意识到肌肉问题是背部疼痛的关键因素，是因为肌肉疼痛往往无法被孤立看待。你被针刺了一下，这种疼痛很尖锐很直观，但肌肉疼痛不一样，痛感说不准会延展至附近的肌肉群，或者同一个肌群的其他部分。这种情况被称为牵涉性疼痛。人们相信，牵涉性疼痛是一种身体的自我保护，这种疼痛能够提醒你减少使用身体对应的部位，防止对身体造成进一步损害。

普拉提是一套系统的锻炼方法，以专注、呼吸和控制为原则，通过锻炼提高身体的能量源（即核心肌肉群，主要包括腹部、髋部和背部的肌群）的力量和柔韧性。大量新近的研究都发现，普拉提可以帮助慢性非特异性下背痛患者缓解疼痛、改善肌体功能。而且，很多医生也开始向他们的患者推荐这种锻炼方法。

** 背部治疗性运动 P96
** 预防手腕疼痛/神经滑动运动 P112
** 到户外运动去

我们的确需要摄取更多的维生素D，但绝对安全的方法几乎是没有的。毫无疑问，来自太阳的辐射对人体是有害的，过分暴露在紫外线中会引发皮肤癌。而光照是否过量则取决于你的肤色、所处的纬度、光照的时间、光照时的云量、你的衣着、你涂抹的防晒霜，等等。总的来说，如前所述，对肤色浅的人来说，晒10分钟太阳是安全的。如果你是西班牙裔，或者本身的肤色较深，晒太阳的时间就得翻倍。如果你的肤色非常深，你可能就需要六倍于前的日照时间。

森林浴是日本的一项传统活动，就是到森林里悠闲远足，在令人放松的大自然环境中，体会森林的气味和声音。日本林野厅已正式对森林浴开展研究，自2004年以来，在相关研究上的投入已累积超过400万美元①。这些大规模的投入取得了回报，人们已经发现了户外活动可能对人体健康产生深远影响。比起在城市的大街小巷漫步，在森林里进行一次简单的步行更有利于增强免疫系统、降低血压和舒缓压力。

** 健康的5个维度

- 身体组成：身体组成是指人体内脂肪、肌肉、骨骼及身体其他组成部分的相对量。一般采用皮褶厚度计来测量，不过也有使用水下称重法来测的，后者的测量结果更加精确。
- 心血管状况：心血管状况是指人体在持续的身体活动中循环和呼吸系统供应氧气的能力，通常被称为有氧适能或者有氧耐力。人们一般通过跑步的几种不同形式进行测量，但在实验室环境下，人们则会使用先进的仪器测定人体呼吸氧气和呼出二氧化碳的比率（尤其是最大摄氧量），以此了解心血管状况。
- 灵活性：灵活性是指身体关节所能达到的最大活动范围。每个关节都有相应的灵活等级，因此不像其他的健康测试，针对关节灵活性目前还没有通用的测试方法。
- 肌肉耐力：肌肉耐力是指肌肉持续运动，对抗疲劳的能力，一般通过让某个肌群进行重复动作来进行测量（如引体向上或者俯卧撑）。
- 肌肉力量：肌肉力量是指肌肉发挥力量的能力，一般通过一次性完成某个动作来测量（如完成一次最大重量的杠铃仰卧推举）。

** 健康单元测试 P148
** 升级身体硬件 P155
