#+title: 支付战争(The PayPal Wars)

以在纳斯达克上市的直营银行BOFI为例。BOFI于2005年上市，股价在2010年前几乎没有太大变化。而从2010年至今，在业绩的带动下，其股价翻了8倍，已拥有100多家机构投资者，这也从另一方面说明直营银行的商业模式开始得到认可。

可以说，注册和信息披露构成了美国P2P行业的进入壁垒。这个进入壁垒，连同完善的个人信用体系，以及完备的证券、借贷和消费者保护方面的法律，构成了保障P2P健康发展的“三驾马车”。

诡计多端的黑手党成员、反复无常的监管者、机会主义的律师、精明的网络窃贼、资本市场的波动不定，以及带有敌意的媒体——事后证明，这些外部因素带来的挑战是无与伦比的。现代商业环境对于企业家们的敌意，竟然比凶猛的竞争对手更大。虽然熊彼特创造“创造性破坏”这一术语的时候，是刻意暗示这其中存在着一定程度的不稳定性，但他并非有意要表明，创业者必须更加担心非竞争性威胁，而不是去担心推向市场的产品。然而，PayPal的经验表明，今天的创新者必须经常考虑非竞争性威胁。

但是我们团队的总合伙人却气得面红耳赤，怒吼着说我是过河拆桥。他气急败坏，说我轻率地放弃了学习市场所需技能的大好机会，却跑去追求“愚人金”。他强烈的反应让我动摇了，直到那时我才意识到对于新的工作，我甚至还没有拿到书面邀请，更不用说工作描述了。

我究竟陷入了什么局面啊？我在一台借来的电脑上测试我的康菲尼迪邮箱是否开通了，心里琢磨着：我没有得到工作描述，我的同事不知道我是谁，而且整个办公楼里甚至没有我的桌子！就连安达信，至少也会给新人安排位子坐！

虽然我不愿有这种想法，但在第一天的中午，我发现自己还是禁不住地想，我对彼得的盲目信任，以及自己急功近利想快点挣钱的想法，是不是导致我犯下了一个可怕的错误。

康菲尼迪的员工现在几乎担任了所有的管理职务，但是“康菲尼迪政变”之后，X.com那边的员工辞职的却很少，这令彼得·蒂尔脸上甚是有光。他不仅创建了康菲尼迪，与合并者谈判并完成了1亿美元的融资，而且还与愤愤不平的员工们修复关系，保持公司的士气并修改业务模式，这对他来说也是个不小的成就。

彼得·蒂尔的语气富有同情心，他的战略调整在逻辑上也能站得住脚，这使得许多恼火的员工平复了心情。他愿意应对仇视性的问题并且强调自己只是暂任首席执行官一职，这使得埃隆·马斯克的支持者们不再害怕受到打击报复，并且他也鼓励员工们坦率表达他们的真情实感。接下来的几天，走廊上再也没有窃窃私语，办公楼里的氛围也渐渐恢复了正常。

这种毫无事实根据的指控使得监管者们更像是为了一己之私做出这一决定的，受益的只有金融机构办公室自身。金融机构办公室也许是希望通过这种笨手笨脚的行为让其他公司明白它不是一个好惹的角色。退一步说，这肯定会让自己声名大振——我想路易斯安那州的金融机构应该很少得到别人关注吧。

我茫然地坐在那里，我的左脑思考着他跟我说的话并想象着即将到来的血雨腥风。埃隆·马斯克不是坏人——绝不是坏人！他有高尚的职业道德，戴维·萨克斯决定让我承担大量职责他也同意了，所以我真的很难说出他的不是。他也给公司带来了很多积极的改变，他将公司重组，使得公司在合并后第一次作为一个整体运营。如果我支持戴维·萨克斯让埃隆·马斯克下台的话，那么我是不是对不起他？我们能不能劝他改变对于2.0版本和PayPal品牌的看法？我静静地思考着这两个问题，而保罗·马丁终于开口：“我需要怎么做？” 保罗·马丁黑白分明的语气让我回过神儿来，重新考虑眼前这个令人不快的问题。虽然埃隆·马斯克本人很有能力，也给公司做出了贡献，但是公司现在走的路是错的，两个多月的讨论也于事无补。我已经反对过用X.com品牌的决定，并且提议在推出2.0版本之前，建立向上促销机制，但是我的反对和倡议都没有通过。以前在康菲尼迪时大家比较自由，有什么想法都会事先讨论一番，但是合并后的公司日益成为一个集权的管理体系，一切都是首席执行官说了算。

显然这些银行完全没有理解“创造性破坏”，他们并没有在市场中与新科技公司竞争，而是怂恿政府打压有潜力的新秀，而这些新秀已经经历了非常激烈的竞争。第一银行和花旗银行在支付市场的失利，再加上富国银行从Billpoint撤资，这肯定吹响了行业号角。如果他们要阻止PayPal等新公司支配在线支付业来彻底改变金融行业，那么他们必须让各州的监管者帮忙，把新公司清理出去。

我自己也是感慨万千，试图理解彼得·蒂尔为什么会接受eBay的这一最新提议。一周后的一天在吃午餐时，我问他是什么动机让他最后决定接受这一交易，他回答说，“觉得这种持久的战争状态让每个人都精疲力竭”。他说公司与eBay的冲突，再加上我们业已动荡的股票价格，有可能使员工因过度劳累或因股价的下降而离职。但是，他急忙又说与eBay联合也能创造价值。

总体上说，了解了eBay的内部运营之后，我们理解了为什么多年以来Billpoint在创新方面都无法与PayPal匹敌——我们更加快速，而且我们鼓励才华横溢的员工们大胆提出意见。这已经成为我们公司的竞争优势，这些特点体现在我们的产品开发周期更短、推广活动更同步上。

如果在eBay内部，“PayPal是我们的购物车”的心态占了上风，很明显，开发PayPal非拍卖的功能，就不会被这个组织优先考虑。真希望这种悲观情绪是一种错误想法，希望eBay充满智慧的高管能够认识到PayPal最终所具有的潜能，这种潜能甚至可能让他们自己的拍卖业务都显得渺小，进而采纳彼得·蒂尔和马克斯·列夫琴最早所确立的愿景。如果eBay不断致力于为消费者创造一种转移现金的新方式，而不是沾沾自喜于自己拍卖网站的购物车，那么它为世界各地的人们所带来的积极影响，可能会非常深远。充分发展的PayPal最终是否能成功地把对货币的控制权从腐败的政府手中夺走，目前尚不清楚，但是它肯定会给全球范围内中等收入和低收入公民更多权利，使他们可以前所未有地对自己的财务有更好的控制权。

对于我们这个年轻的公司来说，监管制度可能是最大的障碍。一旦PayPal成为公开上市交易的公司，遇到法律上的模糊地带，监管机构似乎特别愿意按照自己的意愿为所欲为。在不能确定如何对我们的业务进行分类时，路易斯安那州曾威胁要禁止PayPal，而艾略特·斯皮策和密苏里州的律师对于博彩业务的指控，都证明了这一点。在每个事件中，PayPal都自认为遵循了现有的法例，但是在我们成名之后，这些官员往往选择将含糊不清的法律按照他们的思路进行解释，为开罚单寻找理由。从我们的角度来看，很多监管机构似乎更有兴趣把监管的绳索再勒紧一些，而不是为消费者提供保护。关于

相比之下，法律制度也规范不到哪儿去。虽然像监管机构一样，法院是保持资本主义轮子转动的一个关键机构，但是，今天来看，似乎它们对刚开始做生意的人充满恶意。与监管机构的情况一样，公司在成立的头3年里，很少遇到法律麻烦，但是自从我们申请上市之后，这种情况就明显改变了。除了前面提到的集体诉讼之外，我们还遇到了大量的知识产权纠纷，包括CertCo、Tumbleweed以及后来的第一银行和AT&T 14。无须考虑每个案例的具体情况，看看发生的时间，就能看出这些诉讼背后的主要因素，就是PayPal的成功。手中握有很多专利和专门进行集体诉讼的律师事务所，肯定觉得PayPal这里的钱好赚，由于没有任何法律能够阻止这些无聊的小官司，他们更加有恃无恐。

考虑到所能获得的回报，出现这种激烈竞争是可以理解的，而且对于社会来说，这是一种求之不得的状态，因为这会迫使公司巧妙地做出应对，并对客户的需求做出回应。要创业的企业家必须要做好准备，应对竞争，这是天经地义的。但是还要求企业家必须应付反复无常的监管者、投机取巧者的诉讼、资本市场的不稳定和延迟的执法，这简直就是自讨苦吃。

如果我们允许监管制度变得更加迟钝，法律环境变得更争强好胜，资本市场变得更不稳定，法律执行更缺乏效率，那么迟早有一天，这些因素的合力将压倒最聪明最专注的企业家们。到了那个时候，我们就会有效地摧毁“创造性破坏”。
