#+title: The Product-Minded Software Engineer 以产品为中心的软件工程师

[[https://blog.pragmaticengineer.com/the-product-minded-engineer/][The Product-Minded Software Engineer - The Pragmatic Engineer --- 以产品为中心的软件工程师 - 务实的工程师]](https://blog.pragmaticengineer.com/the-product-minded-engineer/)

以产品为导向的工程师是对产品本身非常感兴趣的开发人员。他们想要了解为什么做出决策、人们如何使用产品，并且喜欢参与产品决策。如果他们决定放弃工程的乐趣，他们很可能会成为一名优秀的产品经理。我曾与许多优秀的具有产品意识的工程师一起工作，并认为自己就是这种开发人员。在打造世界一流产品的公司中，具有产品意识的工程师将团队的影响力提升到了一个新的水平。

- Proactive with product ideas/opinions 积极提出产品想法/意见
- Interest in the business, user behavior and data on this  对该业务、用户行为和数据的兴趣
- Curiosity and a keen interest in "why?" 好奇心和对“为什么？”的浓厚兴趣
- Strong communicators and great relationships with non-engineers  沟通能力强，与非工程师关系良好
- Offering product/engineering tradeoffs upfront   预先提供产品/工程权衡
- Pragmatic handling of edge cases   边缘情况的务实处理
- Quick product validation cycles 快速的产品验证周期
- End-to-end product feature ownership 端到端产品功能所有权
- Strong product instincts through repeated cycles of learning  通过反复学习，具有强烈的产品直觉

Tips to become a more product-minded engineer  成为更具产品意识的工程师的秘诀

If you work on a user-facing product, here are a few tips I've seen work well, to growing your product-minded muscle.

如果您开发面向用户的产品，这里有一些我认为行之有效的技巧，可以增强您的产品意识。

Understand how and why your company is successful. What is the business model? How is money made? What parts are most profitable, what parts of the company are expanding the most? Why? How does your team fit into all of this?

了解您的公司如何以及为何取得成功。商业模式是什么？钱是怎么赚的？哪些部门利润最高，公司哪些部门扩张最多？为什么？您的团队如何适应这一切？

Build a strong relationship with your product manager. Most product managers jump at the opportunity to mentor engineers. Having engineers be interested in product means they can scale themselves more. Before coming in, asking a lot of product questions, take time to build this relationship and make it clear to your product manager, that you'd like to get more involved in product topics.

与您的产品经理建立牢固的关系。大多数产品经理都会抓住指导工程师的机会。让工程师对产品感兴趣意味着他们可以更大程度地扩展自己。在进来之前，询问很多产品问题，花时间建立这种关系，并向您的产品经理明确表示您希望更多地参与产品主题。

Engage in user research, customer support, and other activities, where you can learn more about how the product works. Pair with designers, UX people, data scientists, operations people and others, who frequently interact with users.

参与用户研究、客户支持和其他活动，您可以在其中详细了解产品的工作原理。与设计师、用户体验人员、数据科学家、运营人员和其他经常与用户互动的人员结对。

Bring well-backed product suggestions to the table. After you have a good understanding of the business, the product and stakeholders: take initiative. You could bring small suggestions to a project you are working on. Or you could suggest a larger effort, outlining the engineering effort and the product effort, making this easy to prioritize in the backlog.

提出有充分支持的产品建议。在您对业务、产品和利益相关者有了很好的了解之后：采取主动。您可以为您正在从事的项目提出一些小建议。或者，您可以建议进行更大的工作，概述工程工作和产品工作，以便在待办事项中轻松确定优先级。

Offer product/engineering tradeoffs for the projects you work on. Think of not only making engineering tradeoffs for the product feature your team is building but suggest product tradeoffs that result in less engineering effort. Be open to the feedback on these from others.

为您从事的项目提供产品/工程权衡。不仅要考虑对团队正在构建的产品功能进行工程权衡，还要考虑建议产品权衡以减少工程工作量。对其他人的反馈持开放态度。

Ask for frequent feedback from your product manager. Being a great product-minded engineer means you have built up good product skills, on top of your existing engineering skillset. The best person to give you feedback on how you're doing on the product skillset is your product manager. Reach out for feedback on how valuable they see your product suggestions and ask for thoughts on areas for further growth.

经常向你的产品经理寻求反馈。成为一名优秀的具有产品意识的工程师意味着您在现有的工程技能基础上建立了良好的产品技能。向您提供产品技能方面的反馈的最佳人选是您的产品经理。寻求反馈，了解他们认为您的产品建议有多有价值，并询问对进一步发展领域的想法。
