#+title: 法国阿尔斯通高管皮耶鲁齐写的《美国陷阱》

https://www.weibo.com/6120483044/Hw0V6g5WE?ref=collection

法国阿尔斯通高管皮耶鲁齐写的《美国陷阱》，里面披露了很多东西：

----------

1：美国司法部的起诉胜率高达98.5%，那么为什么会有如此惊人的胜率呢？

一个是辩诉交易，也就是检察官会利用美国法律的繁杂性，以大量罪名起诉被告，在皮耶鲁齐的案件里面，美国检察官就以10项罪名起诉，合计的刑期高达125年，给被告造成巨大的心理压力，而皮耶鲁齐只要认罪，那么一切顺利的话，只会有一项罪名成立（腐败同谋罪），刑期最多5年。

那么能不能不认罪呢？当然可以，但是后果就是高昂的专业辩护律师费用，在皮耶鲁齐的案件里面，其辩护律师告诉他，美国检察官搜集了其14年来的所有邮件记录，以及通过无间道手段获得的录音音频，各种物证高达150万件，专业律师全部分析完需要3年以及几百万美元。而阿尔斯通公司也比较操蛋，给皮耶鲁齐的条件是，如果胜诉就支付辩护律师费用，如果败诉则由皮耶鲁齐本人承担，造成其进退两难。所以美国90%的案件的被告都会放弃申辩直接认罪。

而量刑的宽松度之大，也超出他的想象，在怀亚特监狱里面和皮耶鲁齐关系最好的一个囚犯，外号叫做运输机，美国检察官第一次提议监禁27年，要求他认罪，他拒绝了；于是在关押1年之后，经过漫长的心理折磨，美国检察官第二次提议他认罪，条件是监禁14年；在这之后继续漫长的监禁了一年，检察官第三次提议他认罪，只要在认罪书上签字，检察官承诺起诉书上的建议刑期不超过7年，于是他签字认罪，最终实际判了5年。美国的法官一般都会按照检察官建议的刑期量刑。

在“运输机”这个例子里面，美国检方一开始提出的高额要价，然后通过在监狱漫长的等待折磨（通常长达几年）考验被告的心理，然后不断放宽认罪条件，最终迫使被告屈服。

高大98.5%的起诉有罪率，大大的超过其他国家的水平，这里面一定有很多人其实是可以无罪的，但是美国检察官都会强烈的倾向证明其有罪。那么为什么美国的司法体系会如此强烈的逼迫被告认罪呢？以皮耶鲁齐的案件为例，只要认罪，美国司法部就可以获得阿尔斯通的高额罚款，以及完成背后的美国通用公司对阿尔斯通的收购交易。

另外在皮耶鲁齐关押的这个怀亚特监狱，居然是一个私人监狱，是一家需要盈利的企业，从香皂，牙膏，毛巾到塑料水杯，都需要付钱，看电视图像免费，但是没有声音，如果要听声音，就需要在监狱的商店购买耳机或者收音机。监狱可以获得美国政府的补贴，同时大批的罪犯成为了监狱的盈利来源。监狱背后的资本家和美国的检察官们有没有利益关系？简直不太敢想。

----------

2：美国人的长臂管辖，

《反海外腐败法》让美国政府自认为可以追诉任何一家公司，只要用美元计价签订合同，或者仅仅通过设在美国的服务器（例如谷歌的gmail或者微软的邮箱）收发，存储（甚至只是过境）邮件，就都能被美国管辖。

同时美国司法部的罚款标准，对于外国公司明显的高于美国本土企业，1977-2014年，《反海外腐败法》只有30%的调查是针对非美国公司，但是支付的罚款总额占到了67%，也即是说，外国公司支付的罚款平均金额是美国本土公司的四倍以上。在26个罚款超过1亿美元的企业里面，有21家是外国企业。

去年中兴事件，就有人拿出波音等美国企业曾经被美国政府罚款的例子（图一），显示美国执法的公正性，其实从大数据来看，并不是这样，明显的内外有别。例如同样是违反美帝出口禁令，2016年中兴第一次被罚，因为出口民用产品交了9亿美元罚款，而波音是出口了敏感涉及军用的产品，最终罚款金额为6.15亿美元。而2018年中兴的第二次被罚，则是根本没有出口任何东西到伊朗，因为给涉事员工发了年终奖，被美方认为违反了协议并且涉嫌欺诈，其实这是双方对协议理解的不一致造成的，中兴并没有违反协议的故意，结果就罚了14亿美元。

和美国检察官对自然人的起诉类似，对企业的诉讼也是采取同样的手段，一旦怀疑企业行贿，就会和涉案企业的首席执行官取得联系，一个选择是认罪缴纳罚款，99%的企业都会选择这条路，一个选择是企业反抗走诉讼（在皮耶鲁齐研究的几百个案件中，只有2个企业选择抗诉），但是这样风险很高。

更为有趣的是，在皮耶鲁齐的研究里面，美国司法部对于美国本土企业的反腐败诉讼，大部分时候是发生在该美国企业已经在海外被其他国家起诉之后，这个时候美国司法部出面对该美国企业进行诉讼，随后宣布收回“调查权”，由美国法院对该美国公司的情况进行处理，这样就可以减少该美国企业在海外被诉讼造成的经济损失。实际上司法部对本国企业的起诉，反而成为了保护本国企业免遭外国高额罚款的手段。


另外一个是，在美国司法部对全球企业的起诉案例里面，一旦企业认罪，美国司法部在99.9％的情况下不到10天就发出罚款通知。而阿尔斯通进行认罪谈判并达成协议后，美国司法部却拖到法国政府、当事公司均通过通用电气并购手续才开出罚单。这不得不猜测为美国司法部把罚款金额作为一张牌，如果被通用收购那么就可以减少罚款金额，如果不批准被收购就开出高价罚单获取利润。更为重要的是，阿尔斯通与美国司法部谈判时，通用电气的人居然一起参与。皮耶鲁齐认为“美国司法部不是独立的，而是处于强大的美国跨国公司的控制之下”


--------------------

3:书中认为，2013年的棱镜门事件是个转折点，因为全世界发现，所有的美国公司，包括谷歌，脸书，微软，雅虎，美国在线和苹果等，全部在为美国政府分享信息。

----------

看完以上的部分，我有一些想法，

第一点是，如果孟晚舟被引渡到美国，那么将会极为不利。

以皮耶鲁齐为例，一个跨国公司高管，在怀亚特监狱里面住的是4人监狱，跟一个越南罪犯和一个大块头黑人罪犯关押在一起，幸而两个狱友并不变态和暴力。

但是其他人未必有那么幸运，皮耶鲁齐一开始在监狱的公共浴室洗澡，就被人警告必须穿短裤和拖鞋，一方面是为了卫生，一方面是为了避免性侵。美国方面可以通过各种手段进行心理和生理折磨，逼迫人认罪，这是一种煎熬。

另外就是，抗诉的成本会非常高，起诉罪名动辄就是数十项，每一项要自证清白面临极高的时间和资金成本，而一旦抗诉失败，将会面临海量罪名罗织下的漫长刑期，因此必须要阻止被引渡到美国，美国的司法体系设计就对被告极为不利，尤其是对弱者，可以说是任人宰割。

另外就是，罚款已经成了美国执法部门的重要收入来源，2017年的财富世界五百强，全世界每年净利润超过10亿美元的公司只有320家，也就是即使是世界500强，也有180家净利润达不到10亿美元的门槛。我们参考下，光是中兴2018年就总共交了14亿美元的罚款。


第二点是，对谷歌之类的美国互联网企业退出中国要有更多角度的认识，中国国内一直有强大的声音认为完全是中国政府的问题，是控制言论。

关于言论方面，我自己深有体会，我认为其实可以更开放，就不展开讲，然而言论这只是事情的其中一面，还有另外一面。

不管是从2013年的棱镜门事件，还是2019年发生的华为断供事件，都可以看出，不管是提供情报给美国政府，还是对华为的元器件断供，美国企业执行美国政府的法律是非常坚决的，响应速度非常快，完全的执行美国的长臂管辖。

也即是说，他们认同在中国的分支企业也必须接受美国法律的管辖。而在中国，中国政府是坚决不接受和承认美国的长臂管辖权的，而是要求在华美系企业按照中国政府和法律的要求接受监管，以保证国家安全。这样中美两国的法律就出现了冲突。


最为简单的，如果美国政府要求中国谷歌共享信息，按照美国法律谷歌是应该要提供的，按照中国法律谷歌中国把信息提供给美国则是违法的。
而美系谷歌等企业选择遵从美国法律，不愿意接受中国政府的监管，退出中国市场，是其自主选择行为。
还有人夸奖谷歌不作恶，总不能说提供信息给美国政府就不作恶，提供信息给中国政府就是作恶，这就是双重标准行为了。
这方面中国其实已经比美国更加宽容了，毕竟谷歌曾经长期在中国是可用的，而华为在美国从来就没有被允许大规模应用，即使华为愿意保证不向中国政府提供情报支持。。

目前谷歌对华为的全球暂停服务事件，华为声明是在中国不受影响，因为中国市场并不使用谷歌的地图，邮箱，youtube等各种生态。
如果当年谷歌继续在中国提供各种服务，旗下生态成为中国的主流，今天谷歌中国必然也会接受美国政府的长臂管辖，对华为暂停服务，那么对华为的打击就大的多了。
当年中国政府的坚决行为，反而在今天保护了中国顶尖企业，这恐怕也是没有想到的。
