#+title: 银河系漫游指南(The Hitchhiker's Guide to the Galaxy)

《银河系搭车客指南》就毛巾谈了不少事情。毛巾，《银河系搭车客指南》这样说，基本上是星际搭车漫游者所能拥有的用途最广泛的物品了。部分原因是毛巾有着巨大的使用价值。你可以裹起毛巾取暖，跳跃着穿过贾格兰贝塔星的冰冷卫星群；你可以垫着毛巾躺在桑特拉金斯五光辉灿烂的大理石沙粒海滩上，呼吸醉人的海水蒸汽；你可以盖着毛巾在荒漠星球卡克拉弗恩睡觉，头顶的星光红得那么耀眼；可以用毛巾当帆，扎个小筏子驶下缓缓流动的蛀虫河；可以浸湿毛巾，在徒手格斗中充当武器；可以包在脸上抵挡有毒烟气或闪避特拉尔星球贪婪虫叨叨兽的视线（这种动物蠢得令人难以置信，认为如果你看不见它，它也就看不见你了——迟钝堪比灌木丛，但非常、非常贪婪）；可以在紧急时刻挥舞毛巾发出求救信号。另外，只要毛巾看起来还足够干净，你当然也可以拿来擦干身体。 更重要的是，毛巾还具有巨大的心理学价值。出于某些原因，如果一名“斯卓格”（斯卓格：非搭车漫游者）发现一名搭车漫游者身边有毛巾，他就会自然而然地假定漫游者同时也有牙刷、洗脸巾、香皂、饼干筒、烧瓶、指南针、地图、毛线球、防蚊喷剂、雨具、太空服，等等等等，不胜枚举。更进一步，斯卓格便会欢欢喜喜地出借搭车漫游者不小心“遗失”了的以上及几十种其他物品。斯卓格会这样认为：要是一个人能搭车穿越如此宽阔、如此漫长的银河系，吃过了苦头，逛过了贫民窟，在可怕的劣势中做过了斗争，成功走到这里的时候仍旧知道他的毛巾在哪儿，那么很显然这个人值得信赖。

故而搭车客俚语中存在这个说法，例句如“嘿，你萨斯那个胡皮福特·大老爷吗？那位弗洛德可真知道他的毛巾在哪儿”。（萨斯：知道，了解，相遇，与……性交；胡皮：非常成熟老练的人；弗洛德：真正非常成熟老练的人。）

就在这时候，传来了一阵轻微的低沉声音，这空旷的低沉声音来得突然，是一种无间断的环境噪音。全世界所有的高保真系统、收音机、电视机、磁带录音机、低频扬声器、高频扬声器、中频扬声器都悄悄地自行开启了。 所有的铁皮罐头、垃圾箱、窗户、汽车、葡萄酒杯、锈迹斑斑的金属片也都被激活，变成了在声学上足够完美的共振板。 在黯然退场之前，地球首先被改造成了最终极的声音重放器件，这是有史以来建造过的最伟大的播音系统。但伴之而来的不是演奏会，不是音乐，没有开场号曲，而仅仅是一条简短的信息。

有几件事情福特·大老爷一直搞不太明白，其中之一是人类为啥那么喜欢不停表述和重复最最显而易见的事实，比方说“天气可真好啊”，或者“你个子可真高啊”，或者“噢，天哪，你看起来像是掉进了三十英尺深的井里，你还好吧”。刚开始的时候，福特琢磨出了一套理论用以解释这种奇怪行为。他认为，要是人类停止锻炼嘴唇的话，他们的嘴巴或许会自动封起来。经过几个月的思考和观察，他放弃了这套理论，转而接受一套新的解释。他认为，要是人类停止锻炼嘴唇的话，他们的大脑就会开始工作。过了一阵子，他也放弃了这套理论，因为这种解释过于愤世嫉俗，阻碍了他的思路。另外一方面，他觉得他还是挺喜欢人类的，但他始终为人类感到近乎于绝望的担忧，因为有太多太多的事情他们毫不知晓。

沃贡施工舰队。假如你想让沃贡人搭你一程，请接受如下忠告：忘记这念头吧。他们是全银河系最令人不愉快的种族——倒也不特别邪恶，但脾气极为糟糕，官僚习气浓厚，好管闲事，铁石心肠。即便是为了从特拉尔星球的贪婪虫叨叨兽口中救出自家祖母，要是没有一式三份签署过的命令书，并经历递上去、退回来、受质询、弄丢、寻获、接受公众质询、再次弄丢、最终在软泥炭里埋放三个月和回收用作引火物的整套流程，他们连哪怕一根手指头也不肯动一动。 让沃贡人请你喝一杯的最好方法是把你的手指头插进他的喉咙，惹恼沃贡人的最好方法是拿他的祖母去喂特拉尔星球的贪婪虫叨叨兽。 无论如何也不能让沃贡人念诗给你听。

“巴别鱼，”《银河系搭车客指南》平心静气地说，“很小，呈黄色，状如水蛭，很可能是宇宙间最奇怪的东西。巴别鱼靠脑电波的能量为生，但所需脑电波并非来自其寄主，而是来自寄主周围的生命。巴别鱼从脑电波能量中吸收所有的潜意识精神波频率，转化为营养供其维生。接下来，它将脑电波中有意识的思想频率与收集自寄主语言中枢的神经信号结合起来，以心电感应矩阵的形式排泄入寄主的意识中。上述过程的实际后果是这样的：把一条巴别鱼塞进耳朵，你就能立刻听懂任何物体以任何语言形式向你表述的意思。巴别鱼喂入你的意识的脑波矩阵经过译解，就是你实际听见的言语模式。

毫无疑问，沃贡人的诗，是全宇宙，第三糟糕的。第二糟糕的来自科瑞纳星的阿兹哥特人。他们的伟大诗人“胀气”格伦索斯在朗诵其作品《献给一个仲夏早晨我在腋窝里找到的一小坨绿色垢泥的颂歌》时，四名听众死于内出血，中银河系艺术剽窃委员会的主席咬掉了自己的一条腿，这才得以幸免于难。据报导，公众对这首作品的反应使得格伦索斯甚是“失望”，于是着手准备朗诵他名为《我最喜爱的洗浴时间汩汩声》的十二卷史诗，这时候，他本人的一大截肠子为了拯救生命和文明，在绝望下拼死一搏，径直冲过他的脖子，勒死了他的大脑。

比方说神话般美丽的贝丝萨拉敏星球现在对每年上百亿游客所带来的累积浸蚀非常担忧，担忧到了要在你离开星球时用外科手术去掉食物总量和排泄物总量之间的净差额，所以每次上完厕所千万记得讨要收据，性命攸关。）

《银河系搭车客指南》说，假如你吸满一肺的空气屏住，你在太空的完全真空中可以存活大约三十秒。然而，《银河系搭车客指南》接下来又说，考虑到太空那令人瞠目结舌的无垠宽广，你在这三十秒内被另外一艘飞船接起的概率是一比二的二十七万六千七百零九次方。 有个巧合真是巧得令人惊诧莫名，276709同时也是伊斯林顿一套公寓的电话号码，而亚瑟曾经在那里参加过一场棒得不得了的派对，遇见了一个好得不得了的姑娘，他对那姑娘始终耿耿于怀，那姑娘却跟着一个擅闯聚会的家伙离开了。 尽管行星地球、伊斯林顿的那套公寓和那部电话此刻都已经被摧毁，但考虑到二十九秒后福特和亚瑟双双获救，因此通过某种微不足道的方式纪念了这几样东西，事情还是挺安慰人的呢。
