#+title: 极简欧洲史

https://book.douban.com/subject/5366248/

笔记本导出
你一定爱读的极简欧洲史（简约不简单的“最短”欧洲史，钱理群、钱文忠、公孙策联合推荐！）
约翰•赫斯特(John Hirst)
推荐序 历史，是最好的避险秘笈！

欧洲文明源于希腊，经过罗马帝国、中世纪到近代欧洲。第一个感想是庆幸，因为中国文明始终没有中断，没有如作者在书中所言的“绕一圈回来”（回到希腊）的问题。第二个感想却是悲哀，中国文明由于没有中断，因而没有反思的机会，也就没有文艺复兴、宗教改革、科学革命那种再生的动力。第三个感想是自豪，原来欧洲的几次文明变革，动力都来自中国：印刷术、火药、指南针。第四个感想又是悲哀，中国人的发明“绕一圈回来”，却是欧洲列强的船坚炮利！

** PART 1 欧洲，是个混合体

而从希腊人学习几何的动机，也可窥见他们的心智。我们在学校里做几何，是把几何当习题来做，但希腊人并不仅以习题视之，也不是因为它在测量或导航方面有实际用途。在他们眼里，几何学是引导人类认知宇宙本质的一个途径。当我们环顾四周，被眼前形形色色、丰富多样的世界吸引，所有事物都随机又漫无章法地出现。但希腊人相信，这一切都可用简单的道理来解释。这些多元样貌的背后，必然有种简单、规律、有逻辑的原理在支撑，像几何学就是。

我们现在所认知的科学始于四百年前的 17世纪科学革命，古希腊的两千年后。现代科学一开始就推翻了当时依然是主流和权威的希腊科学的中心教义，但它之所以能推翻希腊科学，遵循的正是这种希腊灵感：答案应该简单、符合逻辑、能以数学表达。牛顿和爱因斯坦，这两位分属于 17世纪和 20世纪的伟大科学家异口同声说，唯有答案简单，才可能近乎正确。这两位科学大师都能用数学公式提出解答，用方程式描述物质的组成和物质的移动。其实，希腊人的灵感常常是错的，有时候还错得离谱。希腊人认为答案应该简单、符合逻辑、能以数学表达的基本直觉也可能是错的。不过后来事实证明，欧洲文明的最伟大成就仍应归功于希腊人。

虽然犹太人相信自己是上帝的选民，但他们并没有逐梦的空间。他们常常遭受屈辱，被外族占领、放逐；可是，他们从不怀疑上帝的存在或他对他们的关爱。当苦难降临，他们的结论是自己没有恪遵上帝的规定，以至于触怒了神。因此，在犹太民族的宗教里，一如基督教中，道德与宗教是密不可分的，但其他宗教就不见得如此。

结果胜出的是另一方。他们说，这是一种完全不同的崭新宗教。你不必先变成犹太人，所有法规都可以置诸脑后，基督已经把我们从那些戒律当中解放出来；他关于爱的教诲凌驾于一切律法之上。这是早期基督教会一位伟大传教士保罗的观点，有人甚至尊保罗为基督教的鼻祖，因为耶稣死的时候，这个信仰还只是犹太人的家务事。耶稣是犹太人，他的徒众也是，有些人希望就这样保持下去，而因为保罗确凿地指出这是所有人的宗教，自此而后，基督教就成了一种世界性的宗教——至少开启了这样的可能。接下去的三百年间，它被广为传播，在罗马帝国的每个角落开花结果。

这些蛮族对和平毫无胃口，在危难中博得名声比较容易，更何况，要养得起旗下的战士大军，唯有凭借暴力和打仗一途。战士们总是伸手向首领要东西：把你的战马赐给我吧，要不那根血迹斑斑、代表胜利的箭矛也行。至于吃饭，不管伙食是丰盛还是普通，都被当做报酬看待。既然这样慷慨，你非得靠战争和掠夺，才供养得起。你会发现，要劝动一个日耳曼人下田耕种，耐心等着一年一度的收成，要比劝他去挑战敌人、赢得受伤的奖赏来得困难。他认为，能靠流血换到的东西却去流汗得来，是没骨气、等而下之的事。

希腊人的观点：这是一个简单、符合逻辑、能以数学表达的世界。基督教的观点：这是个邪恶的世界，唯有耶稣能拯救它。日耳曼蛮族的观点则是：打仗是好玩的事。这些看似天差地远的元素组合在一起，造就了欧洲的文明。

可是，奇迹发生了。公元 313年，君士坦丁大帝成为一位基督徒，或者说至少公开表态支持基督教会。他认为基督教的神可以眷顾他，让他的帝国超越其他所有帝国。当时基督教距离跻身主流信仰尚远，这个一国之尊的统治者却张臂拥抱；他拿钱资助教会，为主教的统治权背书。五十年后，另一位信奉基督教的君主更禁止异教，独尊基督教为国教。如此这般，在耶稣于罗马帝国一个纷争不断的偏远省份传教四百年后，基督教成了这个帝国正式也是唯一的宗教。

这时候的教会跟早期教会已有非常大的不同。一开始，基督教团体是在私人屋宅里聚会，如今，三四百年之后，他们已有完整的层级组织：堂区司铎（神父）、主教、大主教，神职人员不但是全职，还有薪资可拿。其中一名主教，也就是罗马的主教，更让自己坐上教皇的尊座，掌理了整个教会。这个教会有它自己的法律制度，也设有法庭、监狱以执行法律。而教会不只管教务，还管到其他重要大事，例如婚姻、继承。教会也有它自己的税收体系，因为所有人民都有义务掏钱来供养它。

日耳曼蛮族侵犯罗马帝国的时候，并没有摧毁它的意图。他们的目的在于攻城略地，想占夺最肥沃的土地以安家落户，好好享受人生的美好东西。他们愿意承认罗马君主的统治权。问题是，在公元 400年之后，太多蛮族来到，侵占了太多土地，罗马的君王已落得无辖地可治。事实上，罗马帝国之所以走到尽头，就是因为疆土已无剩余，没有领地可以统治了。至于日耳曼蛮族们，发现必须开始统治自己所占领的社会，这不但令他们始料未及，而且处境非常棘手。他们目不识丁，在他们所制造出的混乱中，一息仅存的罗马政权终于断了气，而商业交易和所有城镇都在萎缩。各拥武装的蛮族首领们纷纷自立为王，建立起小邦小国；王国之间自相残杀，迅速楼起迅速楼塌。在西欧，一直要到数百年后，现代国家的雏形——法国、西班牙和英国——才终于出现。

国王长年征战不休，原因可能是为了争权，为了保住统治权以免落入贵族手里，为了自订税收，为了拥有一支自己能完全掌控的军队，为了设立自己的官僚体制。可是，因为他们一开始就立足薄弱，有些事永远也威吓不了人。私有财产变得神圣不可侵犯，那些贵族已把借着条件交换得来的土地变成了私有财产。这对政府来说永远是个束缚，因此，虽然欧洲国王的权力日增一日，却不曾演变成东方的专制君王。东方的专制暴君把领土上的一切都据为己有，如果需要什么物资，只要没收某人物产或派兵到市集拿一堆东西回来就是。反观欧洲的政府，虽然号称“绝对权力”，却从未这样做过。“并非所有东西都归国王所有”，是欧洲政府思维的基石。从私有财产权出发，衍生出人权观念，是西方价值的核心。政府权力必须有所限制，这样的观念之所以勃兴，其实是因为这些政府从一开始就处处受限。

不过，教会虽然跟蛮族成为搭档，对他们的价值观却不是照章全收。经过几个世纪，这些战士已经演变成骑士。骑士热爱战斗，对自己的战斗能力深以为傲，但他们是为了正当理由而战。教会鼓励他们去攻打非基督徒——这个理由确实再正当不过。教会也鼓励十字军远征，前往已落入伊斯兰教手中的东方圣地。如果你愿意出征到那边打仗，你会得到特别的奖赏。骑士也要保护弱者，尤其是保护出身贵族的名门淑女。由于战斗被赋予了这种新的道德意涵，一个男人要借由一种犹如宗教的仪式才能成为骑士。他把剑放在基督教堂的圣坛上，由国王为他佩戴后，这名骑士才能拿它到外头去行善除恶。

保护女士、敬重女士的风范在欧洲文化中源远流长。骑士绝迹之后，演变成为“绅士”风度。绅士是基督教骑士的后裔，有女士进入屋内，即刻起身以示尊重；女士不落座，自己不可就座，见到女士必须点帽檐致意。这些都是我以前在学校里学到的，而学到后就很难忘记。在这方面，我发现自己活脱是个中世纪的遗迹。

基督教会对古希腊和罗马学术进行了积极主动的保存；教会并不光是把一些智慧典籍放在橱柜里束诸高阁。这些文献能够留存下来，让今天的我们有机会拜读，是因为整个中世纪基督教会都在抄写，一再地抄写。当年没有印刷术，书本会腐烂、会枯朽。诸多希腊罗马的珍贵文物之所以留存至今，是拜修道院里的修士之赐，虽然他们常常不知道自己在抄写什么，因此错误百出。

文艺复兴常被描述为古希腊罗马学术的发现或再发现。不过，这并不是说这些智识成就曾经遗失，而今重新被找回，虽然当时确有若干新的发现问世。它的改变在于不再使用古代知识来支持基督教会的神学，而是有许多学者，主要是在教会体系之外，向往希腊和罗马在创造这些知识时的世界样貌而意图加以拟造。他们希望像古代艺术家那样从事艺术创作，希望建造出类似他们的建筑，跟他们一样读写拉丁文，所思所想俱与他们相同。他们想回到过去那个非基督教的世界——但这样的世界已被教会藏匿起来，因为教会只把这些知识利用于遂行自己的目的上。

这也是一个比较“入世”的世界。古典时代之前的人对死后的生命其实没有那么看重，对人在地球上的所作所为关注更多，他们对人的力量和能耐欢喜拥抱，不会满脑子想的尽是人的邪恶堕落。文艺复兴学者现在进入了一个思想奔放的世界。怎样生活最好，想些什么最好，古代哲学家和道德家早就百花齐放，在观点上百家争鸣，但他们的辩证和推论并没有被传承下来，因为基督教会已经给人民的思想紧紧裹上了束缚衣。

不过，文艺复兴学者并没有直接攻击基督教。他们的个人态度或有不同，但大致上对基督教采取的观点颇类似于古人的宗教观，那就是：宗教是个基本的存在，大体而言是件好事或者说有存在的必要，只是世界上还有更多的事情值得关注。宗教不该钳制生活和思想的一切，而这正是教会一贯的目的。这样的钳制一旦被打破，欧洲的思想反而变得比过去更大胆开阔、天马行空。

文艺复兴是中世纪世界遭遇的第一个重大冲击， 16世纪的宗教改革运动是第二个，这回是对基督教会的直接攻击。宗教改革的目的，是要基督教会回复到尚未罗马化之前的样貌。我们说过，基督教会因为跟着罗马帝国一起成长，各种特性深得罗马真传；在罗马帝国灭亡后，教会的教皇依然屹立，地位俨然君王一般，而各教区的主教和大主教，也犹如古罗马帝国的行政百官，辖下更有不计其数的地方神父教士。这个圣职体制不单有自己的法律、刑罚和监狱，还有自订的税收制度。

马丁·路德攻击罗马，一些德意志王侯见猎心喜，是他能幸免于难的另一个原因。当时的德意志并不是一个单一制国家，它是一个由许多小国组成的邦联。罗马教廷在德意志的影响力要大过在英国、法国，这即是部分原因——英国和法国是统一的国家。在德意志，教会握有广大的土地，有些地区甚至占据泰半；剥削人民、聚敛钱财不说，各教区的主教也由教皇任命，这些王公贵族全无置喙余地。若是跟着马丁·路德走，他们便可占据教会土地，任命领地内的主教，对罗马停止金钱捐输，于是，这些王族成了马丁·路德的保护者，并在领土内广建路德的新教教会。日耳曼民族有一半的土地都设有新教教会，路德派教义也从现在的德国北传到了瑞典、丹麦和挪威。英国则是创立了自有的新教品牌，称为英国国教。

文艺复兴和宗教改革都是向过去看齐的运动，两者皆是意图将欧洲这个混合体的某个部分独立分离出来。文艺复兴着眼的是古希腊和罗马的智识成就，新教改革者则是频频回顾罗马教廷承袭罗马习性之前的基督教会。天主教教会保存的文献在这两个运动中都占有核心地位。它所保存的希腊和罗马学术，被文艺复兴运动拿来规避它对知识的钳制，而它所创造并予以神圣化的《圣经》，则被新教改革者拿来颠覆它的神学和单一性。

科学革命之后，那个时代的人并不认为科学的种种发现贬低了人的重要性。恰恰相反的是，他们认为，如果人类做得到这一步——借由理性思索出整个自然体系的运作，又能用数学精确表达，当然就可以利用理性更上层楼。我们可以把这份理性用于人类生活，让它得到脱胎换骨的改善，这份以理性为尊的渴望，就成了启蒙运动的驱动力。这场 18世纪的智识运动，目的是发挥理性，将它运用在政府、道德观念、神学和社会的改造上。

无可否认，这是很极端的看法。启蒙运动不是革命运动，甚至不是政治性的运动。它是由一群学者、作家、艺术家和历史学家推动，这些知识分子相信，一旦理性与教育变得普及，迷信和无知自然会消弭于无形，人民也就不会相信神迹或君权神授这类的胡说八道。只要人民得到教化，民智自然开启。

浪漫主义运动崇尚感受、情绪以及所有的强烈的情感。在这方面，它和一心一意信奉理性的启蒙运动形成截然的对比。这场运动延烧整个欧洲，但尤以德意志地区（今日的德国）为烈，理念在此也得到最充分的发挥。浪漫主义的信徒并不想用理性去控制情绪和激情。在他们心目中，光是优雅地将古典曲调重新演绎出来，称不上是伟大的作家或艺术家；穷尽灵魂，掏心剖腹地将热情、痛苦、绝望赤裸裸地摊在第一线的才是。艺术应该是情感激荡、表达淋漓、惊天撼地的。

浪漫主义运动也催生了民族主义的意识形态，这个观念在当今世界里依然是一股强大的力量。民族主义主张，拥有相同文化和语言的民族必须生活在一起、成立自己的政府。光是闭门造车、空想好的政府是不够的；而如果这个政府不是由你自己的民族所组成，它也不可能是个好政府。塞尔维亚人必须住在一起，成立塞尔维亚政府；克罗地亚人必须住在一起，自组克罗地亚政府。要是一个国家有塞尔维亚人又有克罗地亚人，这表示不管是塞尔维亚人或克罗地亚人都无法充分表达自己。塞尔维亚民族的精髓不可能开花结果，除非它有自己的国家。这是民族主义的意识形态。

你似乎被分裂成两半。对我们的孩童，你希望他们懂得科学就好，可是你也羡慕那些传统信仰没有断裂的人。被分裂、被撕扯、被困惑，是欧洲的宿命。其他的文明只有单一传统，不是这种具有三重元素的大拼盘，欧洲在道德和智识生活上一直受到煎熬、困扰和瓦解。欧洲的血统来自一种非常混杂的渊源，没有一个可以称为“家”的地方。

** 间奏篇 古典情怀今犹在

苏格拉底并没有说他教的是真理，他只是奠定了迈向真理的方法，基本上就是质疑一切、任何事物不能只看表面，他认为一般人的意见并不具备理性基础。他会问这种看似简单的问题：什么叫做好人？弟子回答后，他就告诉对方，这个答案哪里有个大漏洞。对方或许会再次反驳，不过这次比较谨慎；接着是更多的询问、更多的修正。苏格拉底认为，如果你的心智清明而敏捷，终究会掌握到真理。不必上穷碧落下黄泉，或是做什么研究。真理是存在的，但你必须耕耘你的心智，才能掌握它。

在雅典，死刑通常都是立刻执行，这次却往后推迟了，因为宗教庆典的关系。苏格拉底大可趁机潜逃，说不定那些官员还暗自希望他逃之夭夭，但他却拒绝逃跑。他问：“既然我不能永远活着，那又何必苟且偷生？活着不是目的，好好活着才是。我曾在雅典的法治下过着很好的生活，如今我已准备好接受惩罚。”直到最后一刻，他还是充满了哲学思辨。直到他的镣铐被取下，他还在发表高论，说痛苦和享乐只是一线之隔。

希腊人几乎在所有学问上都胜罗马人一筹，只除了法律。罗马人按部就班扩充律法，将法官的裁决、司法专家的意见都囊括于内，作为法律的组成元素。罗马人的民族性虽比希腊人务实得多，法学思维却带有浓厚的希腊理想主义色彩。他们征服其他民族之后，会仔细研究对方的律法，冀图找出它们的共同点。所有人对法律的共识是什么？这个提问催生了自然法的概念——所有致力于公义的社会都应该遵循这套以自然为源的终极规范，用以修订它的律法。

** PART 2 迈入文明

罗马军队将定居于境内的日耳曼人网罗进来，因此，在 5世纪的侵略行动中，两方都有日耳曼人参与战斗。罗马军队里的日耳曼人占了一半甚至更高的比例，有的甚至高居将领。罗马人必须找日耳曼人来替他们打仗，似乎是国力薄弱的明显迹象。在种族意识高涨的 20世纪初叶，有人认为罗马帝国覆亡的原因不言而喻：罗马人犯了大错，把自己的命运交到一个不如他们优秀的民族手里。当然，这是个浅薄的识见，现在已经被扬弃。不过，一个帝国得靠新来者抵御外侮，体质孱弱可见一斑。

有一段时间，日耳曼法律和罗马法令是同肩并行的。罪犯要依据何种法律受审，视其种族血统而定。罗马法律秉持的是清楚分明的公平正义原则，让法官依据案情做出定夺。早期的法官就是立法的人，他们的判例被汇整成法典，其中最伟大的一部当属 6世纪东罗马帝国查士丁尼大帝下令所编；反观日耳曼法律，简直是私人恩仇录之大成，法官的角色只是坐壁上观。有人要是侵犯他人，受伤者及其亲族会去找对方及其亲属讨赔偿，即使是杀人案件，只要付钱给死者亲属便能了事。数目多少端视受害者的身份地位而定，贵族阶级的赔偿金要比普通百姓高出三倍。罗马人判决有罪无罪是以证据和证人为准，日耳曼民族则是用火烧、水淹等酷刑或打仗。例如，把嫌疑犯的手臂泡在沸水里，如果三天后这只手臂没有痊愈，这人就是有罪；或是把犯人丢进水里，浮起来就是有罪，沉下去就是无罪。双方若是因土地起争执可以开战，打胜的一方可以名正言顺宣称所有权。

第二次的大侵略来自穆斯林，时为 7世纪到 8世纪，距离日耳曼蛮族入侵仅仅两百年。伊斯兰教始祖穆罕默德原为阿拉伯商人，得到神的天启后创立该教。他这支借由神助发展出来的宗教，与犹太教和基督教有紧密联系；穆斯林也承认耶稣和耶稣之前的先知们确实是先知，但深信穆罕默德是世上最后一位先知，能指引大家走向唯一真神安拉的怀抱。伊斯兰教比起基督教来说简单许多。他们没有希腊人那种奇思妙想，认为基督教的神是三位一体——圣父、圣子、圣灵，三者各有所司但地位相等，各有分别却又形同一体。在伊斯兰教看来，唯一的神就是安拉而已。穆斯林对基督徒和犹太人相当宽容，基督徒却总认为穆斯林欺世盗名，是真正信仰的毁灭者。

露天的长船只能在夏天出海航行。一开始，维京人会在夏天出征，返家过冬。他们的目的在于掠夺：抢走贵重物品，一些能够运载回去的东西。不过，在搜猎贵重物品的同时，他们也靠掠夺为生，食物、马匹、女人什么都抢，并不仅是取其所需。他们是意志坚定的恐怖分子；不只偷袭、抢劫，更大举烧杀掳掠，拿不走的东西也全部摧毁。他们的目的是制造全面的恐慌，他们心狠手辣，民众闻风莫不丧胆逃命。北欧传奇故事中有个维京战士被称为儿童卫士，因为他拒绝用矛尖刺穿小孩，把他们开肠剖肚。

十字军是多国合作的成果，对比之下，从 15世纪开始跨海朝美洲和亚洲发展的扩张，则是几个新兴民族国家间的竞赛——首先是西班牙和葡萄牙，接着是英国、法国和荷兰。这些国家的首要目标是取得亚洲的香料与财富。它们兵分两路：以海路绕过非洲南部，或是跨过大西洋直接西进。哥伦布原本要去中国，结果无心插柳发现了美洲大陆，这个发现的回报远远超过失望，因为资助他的西班牙王朝从此掌握了中美洲和南美洲的金山银矿。最早抵达亚洲的是葡萄牙人，但被竞夺印度统治权的英法两国和争夺东印度群岛（现在的印尼）的荷兰后来居上，给扫到了一边。

因此，你或许会想，由此看来代议制度也还不错，人民的无知和偏见不至于让国家失序。如果你也抱持着这样的立场，那你的看法就跟苏格拉底、柏拉图、亚里士多德很接近了。

这三位希腊大哲学家对雅典的直接民主提出严重质疑，拜他们的批评之赐，我们对它的运作方式有了了解。他们指出，人是善变无常的、优柔寡断的、浅薄无知的、容易被操弄的，而政治是一种精细的艺术，需要智慧和良好判断，这不是每个公民都拥有的特质。这三位哲人对我们目前的代议式民主应该会欣赏得多。无论我们对现在的民意代表有什么样的不满，相较于全体普罗大众，他们的教育水准还是高些，识见也丰富通晓些。

开放、文明的社会，热心投入、富使命感的公民，任何关心民主的人都会认为这个理想令人向往，虽然我们知道，雅典人能这样投入休闲娱乐与美学艺术，是归因于它的奴隶制度。公民有钱有闲，才得以经常参加集会。然而，伯里克利这篇演说的正面效应，直到许久之后才发挥出来。数百年间，欧洲精英分子不断提出警告反对民主，这不只是攸关利益，也是因为他们所受的教育——他们饱读古典诗书，而那些经典的作者对民主多半都抱持反感。

慢慢地，平民开始和贵族及富人对抗，为自己争取更多权力。这个过程如何演变而成我们倒是很清楚——他们运用自己的军事势力遂其所愿。当战事爆发，一般士兵亦即三等、四等及五等兵，全都拒绝去打仗。他们说，除非你让我们在国内拥有更多权力，我们才肯上战场。透过这样的威胁，他们成立了新的平民大会，并任命了一些称为护民官的政务官。如果政府让一般百姓受到不公平待遇，这些护民官随时有权介入干涉。这个平民大会后来再度拒绝作战，经过又一回合的过招，终于在立法方面拿到了重要角色。

罗马人对布鲁图斯自然赞佩有加；要谈对共和制度的投入，这是最精髓的展现：你必须将所有的私人束缚、个人包袱置之度外，全心全意只以公众利益为念。罗马人称之为“ virtus”，意思是共和国美德——如今已无需服从王命的捆绑，共和体制要存续下去，共和国美德实属必要。你或许会认为布鲁图斯简直不是人，怎么忍心坐视自己的亲生骨肉遭受这样的酷刑？这种共和国美德创造了怪物。

这是一场惨烈、恐怖的殊死战，罗马史家李维笔下描述得丝丝入扣。结果只有一人活着归来，是荷瑞希家的兄弟之一，胜利因此归于罗马。胜利者回到家来，发现妹妹正在悲泣，因为她的未婚夫已被自己的兄弟杀死了。胜利者立刻取出佩剑，刺死了自己的亲妹妹，因为她在应该为罗马的胜利欢庆之际却在哀泣。这幅画传递的是同样的信息：为了国家，家族必须做出牺牲。这个兄弟因刺死自己的妹妹被带上法庭接受审判，但随即获得无罪的判决，因为荷家的父亲现身法庭，批评自己女儿的不是，对儿子的获释功不可没。

奥古斯都非常精明能干。他保留共和体制：公民大会照旧，执政官依然民选。他不把自己叫做皇帝，而以“第一公民”自称。他认为自己的职务是推动者，或者说他扮演了推动者的角色，推动这个国家机器做适当的运转。他朴实无华，没有一堆扈从前呼后拥，时常连个贴身护卫都不带就漫步街头，与平民百姓无异；他会在元老院开会期间走进会堂，细听立法诸公进行辩论；他的个性平易，人人都能亲近。当时大家打招呼以及表示顺从的姿势依旧是高举手臂为礼。当你来到奥古斯都面前，你不必躬身或做出屈从的表示，只要跟这位皇帝互行招呼礼就好。

领主和国王之间端赖个人的盟誓作为约束。宣誓服从的仪式是：领主屈膝跪下，双手合掌高举，国王以双手紧握对方的手，领主随即宣示自己今后是国王的人马，誓言效命于他。宣誓服从后，臣子起立，君臣两人并立，互亲脸颊。因此，这是一种代表服从也代表平等的仪式，象征着这种关系的本质：只要国王保护他，臣子便矢志效忠。自西欧有王国开始，统治者与被统治者之间就是一种不成文的契约关系，这个信念从来不曾完全消逝。

这里的“ estate”意指“地位”而非“阶级”；在中世纪，这个词是一群人的意思。当时的封建社会公认有三种组成分子：神职人员职司祈祷，贵族负责出兵打仗，然后就是平民百姓，也就是所有其他各行各业、从事劳动与赚钱营生的社会工作者。“地位”和阶级（ class）有很大的不同。阶级和经济能力有普遍的关联，而这三种社会地位却是以功能作为分野：祈祷、打仗、劳作。同样地位的人贫富差距极大，拿神职人员来说，其中包括腰缠万贯的大小主教，也有一穷二白的地方神父；贵族当中有的地主富甲一方，也有的一贫如洗；至于平民，有的大商贾和金融家比贵族还有钱，还雇用许多平民替他们工作。能够派代表进入国会殿堂的是这些财力雄厚、坐拥恒产的平民，那些苦力劳工可不行——他们是有如半奴隶的农奴。

弱势的君主和他们的贵族时有扞格，跟国会也是角力不断，直到进入近代，公元 1400年左右，君主开始居于上风，封建君主慢慢转变成绝对的君主专制，不再仰赖议会鼻息。事实上，这些君主并没有真的废除议会，只是不再费事去召集国会诸公来开会，因为他们找到了其他筹措财源的途径。法国国王开始变卖公职，如果你想当个税商，只要预付一大笔钱给国王，再从你向商人收取的费用里补回来就好。至于西班牙国王，则是因为发现了新世界——墨西哥和秘鲁的金矿而得到大笔横财。

“君主专制”这个词可能有误导之嫌。它不表示欧洲的君王能够恣意地为所欲为，他们并不是暴君；一般情形下他们有义务维护法律，确保司法以公平对待臣民；若是国家安全有虞，他们自己也可以处理。只是他们提倡“君权神授”的观念，指称国王是上帝派到凡间的使者，所以万民必须服从，这比起早期君王的说辞更为浮夸，但君主自己也得受这个规范的限制，因为他们知道，自己的治国成绩终究要受到上帝的审判。当然，比起之前的封建君主来，他们显得更尊贵、更遥不可及。君主与臣子互相亲吻的仪式不再，现在你得跪在国王面前，看他要不要把手伸给你亲。

尽管自知不得人望，詹姆斯二世却没有因此更加谨言慎行。他公然提倡天主教，深信它是唯一的真理。在饱受内战蹂躏和接踵而来的军事独裁后，英国很多国会成员打算对詹姆斯二世公然提倡天主教的所言所行睁只眼闭只眼，偏偏他的皇后、笃信天主教的第二任妻子，为他生下了一个儿子，眼看英国即将产生一系血脉相传的天主教国王时，国会上上下下都决定要除掉他。几个国会领袖私下邀请某个信奉新教的国王进侵英国，取得了王位。这人是个荷兰人，世称威廉三世，他的妻子是詹姆斯二世与第一任信奉新教的皇后所生的女儿玛丽。威廉三世是欧洲捍卫新教的斗士，为了保护荷兰不受路易十四的侵犯而奋战不屈。

这是一份光彩耀目的文件，是现代民主的奠基文献，可是它注定要引发一场不光彩的革命。拟定这些原则的人希望法国效法英国施行君主立宪，但如果统治权寄托在全民手里而且号称人人平等，那国王有何保障可言？而且，这份文献的起草人在研拟宪法时，不只希望自己成为执政者，还规定只有拥有资产的人才能投票。可是，既然口口声声说人人平等，怎么可以把一般庶民排除在外呢？庶民眼见这款宪法草案，只有诉诸行动抗争，路易十六才不得不假意接受这项宣言——大批市民涌向巴士底狱，逼国王离开他的凡尔赛王宫，跟巴黎的市民一起生活。推动这场革命成功的平民百姓，并没有退场的打算。

革命党很快就陷入内斗。大卫一直没把《网球场誓言》的草绘图变成完整画作，原因之一是当年在场的许多人都被以“革命之敌”的罪名送上了死刑台。这些激进分子因为都在一所称作雅各宾（ Jacobins）的修道院开会，因此称为雅各宾派。他们奉手段冷血、意志如铁的罗伯斯庇尔（ Maximilien Robespierre）为领袖，摇身成了一个专制独裁的革命党。他们把路易十六推上断头台，在国民议会中铲除异己，关闭不同意见的报社，私设非法法庭处决革命叛徒。他们义正词严，为自己的独裁行为辩护，说法国如今正处于存亡危急之秋，为了逼迫其他欧洲君主遵循《人权宣言》的原则，不得不与他们为敌。为了达到这个目的，革命党征召全国所有男性加入，创建了一支全民皆兵的新形态军队。
