#+title: 麦田里的守望者

你不管做什么事，如果做得太好了，一不警惕，就会在无意中卖弄起来。

你最好去男校念书试试。里面全是些伪君子。你要干的就是读书，求学问，出人头地，以便将来可以买辆混账凯迪拉克；遇到橄榄球队比赛输的时候，你还得装出挺在乎的样子，你一天到晚干的，就是谈女人，酒和性。再说人人还在搞下流的小集团，打篮球的抱成一团，天主教徒抱成一团，那张混账的书呆子抱成一团，打桥牌的抱成一团，连那些参加他妈的什么混账读书会的家伙也抱成一团。

女孩子就是这点好笑。遇到那种地地道道的杂种，十分卑鄙，或者十分自高自大，你每次只要一跟姑娘们提起，她们就会说他有自卑感。也许他确实有自卑感，可在我看来这也不能构成他不成为杂种的理由。

耶稣可能真正喜欢的恐怕是乐队里那个敲铜鼓的家伙。我从约莫八岁开始就看他的表演。他是我生平见过的最好的鼓手。整个演出中他只有机会敲一两次鼓，可他没事做的时候从来不露出腻烦的神色。等到他敲鼓的时候，他敲得那么好，那么动听，脸上来露出紧张的表情。

他不知道我他妈的在说些什么，所以只是“哦”了一声，就送我上楼。那倒挺不错，嘿。而且也挺好笑。你只要说些谁也听不懂的话，她们就会俯首听命，要他们干什么他们就干什么。

不管怎样，我老是在想象，有那么一群孩子在一大块麦田里做游戏。几千几万个孩子，附近没有一个人，没有一个大人，我是说除了我。我呢，就站在那混账的悬崖边。我的职务是在那儿守望，要是有哪个孩子往悬崖旁边奔来，我就把他捉住。我是说孩子们都在狂奔，也不知道自己是在往哪儿跑，我得从什么地方出来，把他们捉住。我整天就干这样的事。我只想当个麦田里的守望者。我知道这有点异想天开，可我真正喜欢干的就是这个。我知道这不像话。

一个不成熟的男子的标志是他愿意为某种事业英勇地死去，一个成熟男子的标志是他愿意为某种事业卑贱地活着。

学校教育还能给你带来别的好处。你受这种教育到了一定程度，就会发现自己脑子的尺寸，以及什么对它合适，什么对它不合适。过了一个时期，你就会心里有数，知道像你这样尺寸的头脑应该具有什么类型的思想。主要是，这可以让你节省不少时间，免得你去瞎试一些对你不适合，不贴切的思想。你慢慢就会知道你自己正确尺寸，恰如其分地把你的头脑武装起来。

我又想起来一个主意，打算到了那儿，就装作一个又聋又哑的人。这样我就可以不必跟任何人讲任何混账废话了。要是有人想跟我说什么，他们就得写在纸上递给我。用这种方式交谈，过不多久他们就会腻烦的要命，这样我的下半辈子就再也用不着跟人谈话了。人人都会认为我是个可怜的又聋又哑的杂种，谁都不会来打扰我。他们会让我把汽油灌进他们的混帐汽车里，他们会给我一份工资，我用自己挣来的钱造一座小屋，终身住在里面。我准备把小屋造在树林旁边，而不是造在树林里面，因为我喜欢屋里一天到晚都有充足的阳光。一日三餐我可以自己做了吃，以后我如果想结婚什么的话，可以找一个同我一样又聋又哑的美丽姑娘。我们结婚以后，她就搬来跟我一起住在我的小屋里，她如果想跟我说什么话，也得写在一张混账纸上，向别人一样。我们如果生了孩子，就把他们送到什么地方藏起来。我们可以给他们买许许多多书，亲自教他们读书写字。

菲比-威塞菲尔-考尔菲德 霍尔顿-考尔菲德


