#+title: The Feynman Technique: The Best Way to Learn Anything

[[https://www.farnamstreetblog.com/2012/04/learn-anything-faster-with-the-feynman-technique/]]

费曼学习技巧，可以分为下面4个步骤：
- Choose a Concept 选择一个概念
- Teach it to a Toddler 尝试把它教给一个孩子
- Identify Gaps and Go Back to The Source Material 发现不能解释清楚的地方，然后重新学习
- Review and Simplify (optional) 重新检查并且简化这个概念

这个世界上有两种知识：对于某个东西，你可能是完全理解它，另外有可能你只是理解它的名字（你不能很清楚地知道这件事情的背景和原因）。只有你完全理解它了，而不是仅仅是它的名字，那么你才真正地拥有了知识
#+BEGIN_VERSE
There are two types of knowledge and most of us focus on the wrong one. The first type of knowledge focuses on knowing the name of something. The second focuses on knowing something. These are not the same thing. The famous Nobel winning physicist Richard Feynman understood the difference between knowing something and knowing the name of something and it's one of the most important reasons for his success. In fact, he created a formula for learning that ensured he understood something better than everyone else.

“The person who says he knows what he thinks but cannot express it usually does not know what he thinks.” — Mortimer Adler
#+END_VERSE

-----
*Step 1: Teach it to a child*

Take out a blank sheet of paper and write the subject you want to learn at the top. Write out what you know about the subject as if you were teaching it to a child. Not your smart adult friend but rather an 8-year-old who has just enough vocabulary and attention span to understand basic concepts and relationships. 不要选择那些很聪明的朋友，而是选择一个8岁的有足够的词汇量和注意力的小孩。只有这种观众才能保证让你理清所有的头绪。

A lot of people tend to use complicated vocabulary and jargon to mask when they don’t understand something. The problem is we only fool ourselves because we don’t know that we don’t understand. In addition, using jargon conceals our misunderstanding from those around us. 用那些黑话和名词只会掩盖我们真实的物无知，这也是为什么需要挑选小孩的原因。

When you write out an idea from start to finish in simple language that a child can understand (tip: use only the most common words), you force yourself to understand the concept at a deeper level and simplify relationships and connections between ideas. If you struggle, you have a clear understanding of where you have some gaps. That tension is good –it heralds an opportunity to learn. 接下来一个更加重要的步骤就是写下来。写下来，你可以不用选择一个真实的8岁小孩，只要你头脑里面有这个一个小孩就行。写下来，表达清楚。让我想起了linsd的一句话："if you can not write it, you do not know it"

*Step 2: Review*

In step one, you will inevitably encounter gaps in your knowledge where you’re forgetting something important, are not able to explain it, or simply have trouble connecting an important concept. 在上面过程中，你会发现你不可避免地忽略一些东西或者是无法解释清楚一些东西，而这些东西正是理解前面的知识和概念的必需的；

This is invaluable feedback because you’ve discovered the edge of your knowledge. Competence is knowing the limit of your abilities, and you’ve just identified one!

This is where the learning starts. Now you know where you got stuck, go back to the source material and re-learn it until you can explain it in basic terms.

Identifying the boundaries of your understanding also limits the mistakes you’re liable to make and increases your chance of success when applying knowledge. 不断地完整你所理解的知识，不断地推进你的知识的边界。

*Step 3: Organize and Simplify*

Now you have a set of hand-crafted notes. Review them to make sure you didn’t mistakenly borrow any of the jargon from the source material. Organize them into a simple story that flows. 你对某件事物的理解，可以能组织成为一个简单的故事一样，可以很容易清晰地传达给所有人。

Read them out loud. If the explanation isn’t simple or sounds confusing that’s a good indication that your understanding in that area still needs some work.

*Step 4 (optional): Transmit*

If you really want to be sure of your understanding, run it past someone (ideally who knows little of the subject –or find that 8-year-old!). The ultimate test of your knowledge is your capacity to convey it to another.

-----

Not only is this a wonderful recipe for learning but it's also a window into a different way of thinking that allows you to tear ideas apart and reconstruct them from the ground up. (Elon Musk calls this [[https://www.farnamstreetblog.com/2015/04/elon-musk-framework-thinking/][thinking from first principles]].) This leads to a much deeper understanding of the ideas and concepts. Importantly, approaching problems in this way allows you to understand when others don't know what they are talking about. 和Elon Musk的第一性原理完全一致，把你的认知完全打破然后重建。

Feynman's approach intuitively believes that intelligence is a process of growth, which dovetails nicely with the work of Carol Dweck, who beautifully describes the difference between [[https://www.farnamstreetblog.com/2015/03/carol-dweck-mindset/][a fixed and growth mindset]].
