#+title: 引爆点：如何制造流行(The Tipping Point: How Little Things Can Make a Big Difference)

引爆点：如何制造流行(The Tipping Point: How Little Things Can Make a Big Difference)

格拉德威尔的流行理论包括三部分。第一个是个别人物法则，就是我前面讲到的包括我的同事小新在内的三类人：联系员，内行和推销员；第二法则是附着力因素，这条法则讲的是流行事物本身所应具备的要素，它应该具备让人过目不忘或至少给人留下深刻印象的附着力，比如iPod漂亮的外形和一般随身听无法比拟的容量；第三法则是环境威力法则，意思就是发起流行的环境极端重要。注意，不是重要或者很重要，而是极端重要，甚至外部环境的一个微小变化，都能决定它流行或者不流行。

换句话说，引爆一种流行病，并不是只有一种途径。流行病爆发需要三个条件：能传播传染病病原体的人，病原体本身和其发生作用所需的环境。当一种流行病爆发时，三个条件就失去了平衡。疫情被引爆，是因为一些事情的发生让其中一个甚至两三个条件发生了变化。我将这三个变化条件称为：个别人物法则(Law of the Few)，附着力因素法(Stickiness Factor)则和环境威力法则(Power of Context)。

（关于联系员）但是我的问题似乎令他不解，不是因为他的这些人际关系对其没什么帮助，而是因为他并没有把与人交往作为自己的商务策略。他只不过把交友看成一件平常事（他乐于此道），他就是这样一个具有建立社会关系的本能和天赋的人。他在这方面也并没有做得过分积极，他不是那种过分主动进行社交，让人觉得他别有所图的人。他更像是一位旁观者，一个阅历丰富而且热心的局外人。他只不过是乐于与别人在一起，而且他采取了真诚而有效的方式，他觉得人们相识和交往具有无穷的乐趣。

（关于内行家）促使马克阿尔伯特这类人在流行浪潮爆发中扮演如此重要角色的因素到底是什么呢？显然，他们掌握了一些不为人知的信息，他们比常人赌过的杂志和报纸都多，而且只有他们才可能去仔细阅读邮寄宣传品。马克尔伯特恰巧又是一位电子设备行家，如果电视或摄像机有新突破，而你又是他的朋友，那你肯定会马上听说这一切的。内行们了解内情，也有能力把信息迅速口头传播出去。但是，内行的与众不同之处并不在于他们掌握了这么多的内情，而在于他们把内情散播出去的方式。不是为别的目的，而仅仅出于助人为乐的原因而帮助他人，这反而是一种更有效引起别人注意的方式。

（关于推销员，影响力在发挥巨大作用）在社会潮流中，内行们就是数据库：他们为大家提供信息。连续员是社会粘合剂：他们四处传播信息。但是，还有另外一个特定的群体-推销员。如果人们对传来的信息并不相信，他们就有能力说服大家，而且，与其他两种人一样，这些人对于发起口头信息传播潮也至关重要。

后来的研究表明，对话中的人们不仅姿势动作和谐同步，而且对话节奏也协调一致。当两个人在交谈时，他们的音量和音高总是平衡的。语言学家们所说的音速，即每秒发出的声音数量也是均衡的，等待时间（即前一个人停止讲话与下一个人开口之间的这段时间）也是均衡的。两人刚开始交流时的讲话方式可能大相径庭，但是，他们会马上达成一致。我们实际上总是在这样做着。就连一两天大的婴儿也会根据成人的讲话模式同步活动头走，肘，肩，臀和脚。人类间的相互交流和猿猴间的相互交流过程也都存在着同步运动现象。这是把人们客观联系起来的方法之一。

我们所要谈的是一种超级感染力，这是一种人们几乎没有意识到的基本生理能力。就像所有专业人员都应该具备某些特点一样，有些人对超级感染力的掌握比别人要强很多。人们常说某人非常具有个人魅力或者说服别人的能力，一部分意思是指此人能把别人纳入自己的节拍，而且还能决定谈话的范围。一些研究发现那些与教师很配合，同步运动程度高的学生比较愉快，学习热情比较高，学习兴趣比较浓，而且比较容易和老师相处。

广告研究公司所做的研究。在2.5分钟的商业广告时间里，如果出现了至少四个持续15秒的不同广告，那么，任何一则15秒广告的效果都会降低到几乎为零。因为我们谁也记不住自己听到，看到，读到的大多数信息。信息时代使信息的附着力成了难题。

儿童看电视并不是因为他们的兴趣被激发出来了，而他们转移注意力不再看也不是因为感到厌倦。事实上，儿童看电视是因为他们看懂了节目内容的意思，而转移注意力不再看是因为他们看不懂意思。如果你从事电视教育工作，这一点就显得至关重要。也就是说，如果你想知道孩子们是否从电视节目中学到了知识，或者学到了什么知识，你所要做的就是观察他们在看些什么内容。如果你想知道孩子们没有学到哪些知识，你要做的就是观察他们不看哪些内容。学前儿童的看电视行为非常复杂，但我们可以通过简单的观察来确定儿童节目的附着力所在。

（对附着力的研究）学龄前儿童的世界充满了他们未知的事物，即对他们来说新奇的事物。所以，学龄前儿童背后的驱动力不像年龄较大的孩子那样，是对新奇事物的探寻，而是想要理解事物和预测事物。对于年幼的儿童来说，重复的确很有意义，他们需要重复。在一遍又一遍的看故事时，他们的理解力也在不断提高，这是他们的一种能力体现。同时，我认为他们通过预测未来要发生的事情，会产生一种确定感和自我价值感，当然，儿童并不总是喜欢重复，无论他们在看什么节目，重复出现在眼前的内容，必须是有助于他们进一步理解的。与此同时，重复的内容不能过于复杂，否则孩子们第一次看到后就会迷惑不解，并马上关闭电视。

这就是犯罪流行潮理论。该理论认为，犯罪可以传染，就像时尚潮流一样。它可以由一扇破碎玻璃窗蔓延到整个社会。不过，这种流行潮的引爆点不是某个人，而是一些物质如公共场所的涂鸦。这么说，促使人们发生某种行为的推动力不是来自于某类人，而是来自于其所处环境的某个特征。破窗理论和环境威力法则给了我们什么启示？它们揭示的原因恰好是相反的。两种理论认为犯罪根本不是出于本能行事，也不是只生活在自己的世界里，而是对自己周围的环境非常敏感，对各种暗示非常警觉，总是按照自己，对周围世界的感知，并在身边事物的触动下萌发犯罪念头。

如此说来，性格不再是我们所认为的那样，甚至不是我们所希望的那样。它不是固定不变，容易辨别，密切相关的一些特征的组合，我们之所以那样认为，是因为我们大脑发生了小故障。性格其实更像是在某个时刻，某种情况和环境下流露出来的习惯倾向和兴趣的结合体。这些东西互相联系，却不是密不可分。大多数人看起来好像性格稳定一致，那是因为我们能够很好的控制我们的环境。我喜欢参加宴会，于是我经常举行宴会，朋友们看到我就会想到我是个风趣的人。但是如果不能常常举办宴会，如果朋友们经常看到我在许多其他不同的场合，比如肮脏不堪在地铁里遭遇几个恶意小子，他们可能就不会认为我很风趣了。

-----
*关于互动记忆系统*

韦格纳据此证明，互相熟悉的人之间会无形中产生一种联合记忆系统，或称互动记忆系统。这一系统建立在对哪个人更适合记忆哪些事情的了解之上，互动记忆是构成亲密关系的一部分。“正是这种互动记忆能力的缺失致使离婚变得痛苦。感觉压抑和认知功能失常的离婚者，可能正在忍受失去外部记忆系统的损失。他们原本可以通过讨论来达成某个共识，原本可以依赖对方的记忆存储，但是现在这一切都不复存在。失去了互动记忆，人就像失去了大脑的一部分。”

人的脑力是有限的，因此我们只专注于我们做的最好的事情。女人们往往在抚养孩子方面是行家，即使在女方在社会上有自己的职业的现代家庭中也是如此。女性在孩子的出生和最初的育儿任务中付出最多，因而家庭在关于抚养孩子的问题上就更多的依赖女性。最初的情形导致后来的更多责任，直至最后，孩子的智力开发也成了女性的责任，而在这一过程中没有人要刻意如此。“如果每个人都肩负其所在群体认同的特定职责，每个领域都尽可能的少安排几个行家来负责，而不是根据情况随机布置给哪个人，如此长期下去，就一定会有更高的效率。”

当然，如果你负责一家纸巾公司或者是制作螺栓螺母的公司那就无所谓了，并不是任何公司都需要有如此密切的人际关系。但对戈尔这样的高科技公司，这种整体记忆系统，就显得至关重要了，因为它保持市场优势靠的是创新能力，对市场需求及客户要求快速作出回应的种种能力。具有这样的整体记忆系统，公司就能高速运转：任务可以很快完成，问题能得到迅速解决，一个部门的员工得以接触其他部门的员工，并借助他们的专门技能完成自己的职责。

-----

中转规律就是指这个意思。内行，联系员和推销员在传播思想的过程中所做的就是，省掉那些细枝末节，夸张某些细节，从而使得信息本身具有更深的意义。如果哪个人想要发起什么流行潮，不管是关于某一品牌的鞋还是某种行为方式或者是某一软件，他必须聘用我们所说的联系员，内行和推销员这样的人。也就是说，他们必须找到某个人或某种方法，把革新者的意图，转变成我们这些普通大众能够明白的语言。

研究人员认为这一现象并不是巧合，而正是这一现象证明了自杀的实质是：同一社会亚文化成员之间通用的特有语言。这一论断值得我们引用研究人员完整的原文：“许多试图自杀的病人均来自某个社会阶层，在这个社会阶层中，自我攻击通常被看作传递某种特定信息的方式。在这个团体中，自杀这一举动被看成是可以理解的，而且与这一文化模式的其他部分是相符的。如果情况属实，那么我们可以推断出：在某些特定情况下，处于困境中的某个人希望通过这种传递媒介，把他处于困境的信息传递给别人，而不必重新发明另一种传递媒介。在图谋自杀亚文化中的个体能做出含有预定含义的举动，他需要做的只是去执行这个举动。从本质上说，这个过程与某人开口使用这个词时的过程是相似的。”

相反，所有的研究结果都有力的证实了，在人格和智力的塑造过程中，环境起了很大的作用，即使这种作用并不比遗传作用强。但这里要强调的是，无论是哪一种环境影响，都不来源于父母，而是来源于其他事物。朱蒂哈里斯认为这种影响实际来源于同龄人。

像“郁乐复”和“百忧解”之类药物之所以有效有疗效，是因为它们能刺激大脑分泌更多的复合胺，以此来弥补抑郁症患者体内缺少的复合胺。尼古丁似乎对其他两种主要的神经传递素多巴胺和降肾上腺素的不足，发挥了同样的补偿作用。简而言之，这些郁郁寡欢的烟民实际上是把烟草当做某一种廉价代替物，用来缓解他们的抑郁情绪，并促进大脑分泌出能使他们行为正常的化学物质。疗效如此之显著，以至于当有精神病史的烟民一旦戒烟，又面临着抑郁症复发的极大风险，就形成了一种报复性附着力。一方面，吸烟者因此对尼古丁有依赖性而难以戒烟，但另一方面如果他们离开了尼古丁，又有患上神经衰弱的风险。

尼古丁释放出的多巴胺，会进入大脑皮层，这也是大脑的快乐中枢。人们认为这里负责产生人的快乐感和幸福感。这正是吸烟给人带来快感的地方，也是戒烟最困难的原因之一。尼古丁还增加了降肾上腺素的分泌，因此，当你一旦戒烟，将身上限速的供应就会不足，你就会感到焦虑烦躁。布鲁平具有双重功效，一方面增加了多巴胺的量，因此吸烟者并不想在吸烟；另一方面它代替了一部分降肾上腺素，因此，吸烟者不会有焦虑之类症状出现。

至少尝试服用过一次可卡因的人数，告诉我们，青少年几乎都有尝试危险事物的迫切愿望。这正是青少年的行为特征，也是他们了解世界的方式，而且在大部分情况下，尝试并没有导致不良后果发生。因此我们不必强烈反对此类尝试，我们必须接受这类尝试，甚至欢迎这种尝试。青少年总是被诸如女学生玛姬，比利和帕姆所吸引，而且他们只有变得反叛好动，不负责任，才能体验青春期的幻想，因为这是体验生命的好方法，因此，他们必然会被这些人所吸引。可见我们所应该做的，不是阻止尝试，而是确保尝试不会产生严重后果。

（这本书的一句话总结）但是，如果说在引爆点世界里存在困难和多变性，也可以说在这个世界里同时存在很大希望。仅仅通过控制一个小组的规模，就有可能在很大程度上改善人们对新观念的接受能力；通过对信息传播方式的微小调整，就有可能大幅度地降低其传播难度；仅仅找到和接触那些有着极强社交能力的人，就有可能掀起一股社会流行潮。引爆点，最终再次证实了我们存在改变一切的能力，和采取明智行动的力量。看看周围的世界吧，它看上去似乎雷打不动，无法改变，但只要你找准位置轻轻一触，它就可能倾斜。

我的感觉是，青少年社群在这些年的发展，增加了这种隔绝的潜能。我们给孩子们更多的钱，这样他们可以更轻易的建立自己的社群和物质世界。我们给了他们更多的时间让他们彼此相处，而不是和成人相处。我们让他们使用电子邮件，给了他们各种电器，其中最重要的是手机。有了手机，他们一天中的每一时刻都能和同龄人联系上，而这些时刻本来可以由成年人的话语来填充。但他们的世界被口头信息传播的逻辑统治着，被青少年之间口口相传具有传染性的信息统治者。科伦拜恩案现在是与世隔绝的青少年中最红的流行潮，但它也不会是最后一个。

-----
*网络效应的陷阱*

归属于一个大网络，可能是一件很棒的事。因为理论上，网络越大，它就越有力量。但是还有一个现象是，网络在规模上扩大的同时，网络的成员所必须忍受的糟糕事物也增多了。这就是为什么人们不赞同电话推销员交谈，这就是为什么我们中的大多数人，装了电话答录机和来电显示，这些东西可以让我们不必接自己不想接的电话。我们对电话已经产生了免疫力。

我认为“传真机效应”所犯的错误，正在被商人和交流者们一遍一遍重复着。广告代理商们决定在哪家杂志或电视台投放广告所经常依据的是成本核算：他们购买最便宜同时又能让尽可能多的观众看到广告的时段。但是他们有没有考虑到免疫性呢？广告商的逻辑结果是，电视上的商业广告前所未有的多。因此，很难相信人们还在像从前那样密切的关注这些商业信息，并认认真真的看电视上的商业广告，刊登了成百上千条广告的杂志，马路边几步就能矗立着的广告牌。当人们被铺天盖地的信息淹没，他们就对这种形式的交流产生了免疫力。作为代替手段，他们向生活中自己尊敬的人，仰慕的人，和信任的人征询意见，从他们那里获取信息。对于信息交流免疫症的治疗方法是，找到内行，联系员和推销员。
