#+title: The Scientist

[原文链接](https://signalvnoise.com/posts/3966-the-scientist)

文章的逻辑有点奇怪, 看了评论才get point. 
#+BEGIN_QUOTE
Elon is definitely the scientist. I bring up the guppies just to show how important it is to evolve and adapt in order to survive. But the thing with evolution and guppies is that it’s still the luck of the draw for those survivors. The drab guppies are just at the right place at the right time to not get eaten. And many people who are stuck in their projects and careers, often feel like the successful people around them are like that too. The successful folks were just lucky.

But we aren’t guppies. Elon’s not a guppy. We as humans can experiment and adapt. We can get things around us to adapt. We can get nature and our environment to change, and when we can’t, we can still change ourselves.
#+END_QUOTE

Guppy适应环境并不是主动的行为, 而是因为predator对他们发起攻击才导致colorful one数量急剧减少, 而drab one则可以存活下来. Guppy所谓的适应是被动的.

但是Scientist却不应该是这样的. Scientist应该去主动去adapt to environment. 就像Elon Musk一样去适应在Paypal和SpaceX遇到种种问题时候的环境(并且积极主动去解决这些问题)
#+BEGIN_QUOTE
Elon persists through obstacles. But he's also a quitter. He changes. He adapts. If something gets in his way, instead of plowing through it, he steps back to look to see if there's actually something much more worthwhile to attack. And he adapts himself to go there. He gives himself more opportunities. Because here's the thing. In this story…We aren't the guppies. We're the scientist.
#+END_QUOTE
