#+title: 策略思维(Thinking Strategically)

https://book.douban.com/subject/1084435/

** 第二章 准备接招

对于任何一种相继选择并且数目有限的博弈，总是存在某种最佳策略。

在这个典型的谈判过程里，蛋糕缓慢缩小，在全部消失前有足够时间让人们提出许多建议和反建议。这表明，通常情况下，在一个漫长的讨价还价过程中，谁第一个提出条件并不重要。除非常谈判长时间陷入僵持状态，胜方几乎什么都得不到，否则妥协的解决方案看起来还是难以避免的。不错，最后一个提出条件的人可以得到剩下全部的成果。不过真要等到整个谈判过程结束，大概也没剩下什么可以赢取的了。得到了“全部”，但“全部”的意思其实什么都没有。这就是赢了战役却输掉了战争。

一个普遍的观点是，若要应用向前展望，倒后推理的原理，不可缺少的前提是后者可以观察到先行者的行动。另一个条件是，策略必须是不可逆转的。

从这个故事的可总结的教训之一在于，假如你不得不冒一点风险，通常都是越早冒险越。这一点在网球选手看来再明显不过了：人人都知道应该在第一发球的时候冒风险，第二发球都必须谨慎。这么一来，就算你一发失误，比赛也不会就此结束。你仍有时间考虑其他策略，并借此站稳脚跟，甚至一举领先。

** 第四章 走出囚徒困境

以牙还牙策略缺少的是一个宣布“到此为止”的方法，因此若将这一策略用于必然包含误解的情形就会变得很危险。以牙还牙策略实在太容易被激发起来。当某一作弊行为看上去像是一个错误而非常态举止的时候，你应该保持宽容之心。即便这一作弊是故意的，经过一个漫长的惩罚循环之后，也许到了该叫停并尝试重新合作的时候了。

** 第五章 策略行动

你大约也觉得，保留选择余地总归是有好处的。不过在博弈论的王国里，这一点却不成立。你虽然少了自由，却在策略上得了益，因为这么做改变了其他参与者对你以后可能采取什么反应的预期，而你可以充分利用这一点，为自己谋利。其他人知道只要你有行动的自由，你就有让步的自由。引用奥斯卡王尔德的名言就是：“我就是没办法拒绝诱惑。”

** 第六章 可信的承诺

现在我们提供8种手段，有助于建立可信的承诺：
- 建立和利用一种信誉。
- 写下合同。
- 切断沟通。
- 破釜沉舟。
- 让后果超出你的控制。
- 小步前进。
- 通过团队合作建立可信度。
- 雇佣谈判代理人。

设想一下，在双方谈判达成协议后，政府却突然背弃自己的承诺，向劫机者发起攻击。这么做的结果是，政府对劫机者的处理方式值得信赖的信誉将会丧失殆尽。政府失去了做出可信的许诺的能力，同时不可逆转的断绝了自己对劫机者发出的威胁进行回应的后路。这种破坏许诺的可信度的做法，将使得绝不谈判的威胁变得非常可信。

不过这份合同有一个致命的缺陷，没有防止再谈判的机制。拉索先生眼瞅着精致的法式小甜饼，嘴上却会争辩说，按照目前合同的承诺，没有人可以得到25,000美元赏金，因为他永远不会违反这份合同的规定。因此，这份合同也就一文不值了。在谈判符合双方的共同利益，拉索先生可能说他愿意请客支付一轮酒水费用，以此换取在座各位放他一马。在饭店吃饭的人一定愿意免费享用一份饮料，无论如何总比一无所获更好，因此也就乐意让他暂时丢开那份合同。

这个过程从新兵训练营开始。世界各地的武装部队的基本训练，其实都是一次伤痕累累的历程。新兵遭到虐待，羞辱，同时面临巨大的体力与精神压力，这些压力如此巨大，以至于要不了几个星期，他的个性就会发生改变。在这一历程当中，学会的一个重要习惯是，自动自觉而不问是非地服从。为什么袜子必须叠好，或者床铺必须整理，而且要按照一个特定方式完成，完全没有理由可言，唯一理由就是军官下了这样的命令。这么做的目的是，将来听到更加重要的命运时，士兵也会照样服从。一旦训练出不问是非的士兵，这支军队就会变成一台战斗机器，承诺就会自动形成。

这有一个问题，假如消费者估计IBM差不多要降价了，他们就会稍等一下再购买。一旦大多数消费者都在观望，IBM就有动机加速减价过程，希望早日俘获消费者。这个想法，首先是由芝加哥大学法学教授罗纳德科斯提出的。他认为对于耐用产品，一个垄断者实际上是在跟以后的自己竞争，从而使市场变得富有竞争性。

** 第七章 不可预测性

你可能已经注意到，从两位选手的不同角度计算最佳混合策略，会得到一个有趣的共同点：两次计算会得到同样的成功回球概率，即48%。接收者若采用自己的最佳混合策略，就能将发球者的成功概率拉低到，发球者采用自己的最佳混合策略所能达到的成功概率。这并非巧合，而是两个选手的利益严格对立的所有博弈的一个共同点。

这个结果称为最小最大定理，由前普林斯顿数学家约翰冯诺依曼与奥斯卡摩根斯顿创立。这一定律指出，在零和博弈里。参与者的利益严格相反，每个参与者尽量是对手的最大化收益最小，而他的对手则努力使自己的最小收益最大化。他们这样做的时候，会出现一个令人惊讶的结果，即最大收益的最小值，等于最小收益的最大值。双方都没办法改善自己的地位，因此这些策略形成这个博弈的一个均衡。

所有混合策略的均衡具有一个共同点：每个参与者并不在意自己在均衡点的任何具体策略。一旦有必要采取混合策略，找出你自己的均衡混合策略的途径，就在于使别人对他们自己的具体行动无所谓。虽然这听上去像是一种倒退，其实不然，因为它正好符合零和博弈的随机化动机：你想阻止别人利用你的有规则的行为占你的便宜。假如他们确实倾向于采取一种特别的行动，从你的角度观察，这只能表示他们选择了最糟糕的方针。

** 第八章 边缘策略

美国贸易政策的做法，代表了一种缺乏控制机制的边缘政策。美国贸易当局企图以国会将要通过更具保护主义色彩的行动作为威胁，迫使日本和韩国向美国出口货物敞开大门，同时减少对美国的出口。经常动用这样的战术存在一个问题，即这些战术可以创造风险，却不能将风险控制在一个必要的范围。只要立法者的心思转向其他一些事情，国会采取保护主义行动的风险就会下降到一个很低的水平，以至于这个威胁一点也不管用。另一方面，假如国会正在讨论解决贸易赤字问题，那么这个风险要么会高到我们的政府自己也难以承受的水平，要么就是对外国的限制迟迟没有反应，从而同样变成一个没有效力的威胁。换而言之美国政府机构之间的相互制衡，可以创造风险，却不能有效控制风险。

** 第九章 合作与协调

“看不见的手”最多也就适用于一切能标出价格的情况。但在经济学以外的许多情况，甚至经济学内部的许多情况中，人们并不会由于损害社会其他人的利益而被征收罚金，也不会由于造福其他人而得到奖励。比如生产商几乎不会，由于将清洁的空气消耗殆尽，而被迫支付一笔足够高的费用。也不会由于一名培训工人而得到补偿，而这名工人可能上完培训课，就辞职找另一份工作。在这个广泛的主题下，“看不见的手”可能在许多方面是失灵的，每个人可能去做个人看来最好的事情，却得到了从集体看来最坏的结果。

基于向前展望倒后推理的原则，在野党可以分析出来自己的最佳立场在中点，在这个位置鼓动向右和鼓动向左的人在数目上势均力敌。而执政党的最佳策略就是模仿在野党，两党选择的立场完全一致。于是，他们将在只有议题关系大局的情况下，各得一半选票。这一过程的失败者是选民，他们得到的只是两党互相复合的回声，却没能作出政治抉择。在实践中两党不可能选择完全一致的立场，但大家都想方设法靠近中点，这一现象最早是由哥伦比亚大学经济学家哈罗德霍特林在1929年发现的。他指出经济和社会事务存在相似的案例：“我们的城市大道毫无经济效益，其中的商业区也太集中，卫理公会以及基督教长老会的教堂简直一模一样，苹果酒也是一个味道。”

这些故事的关键在于，自由市场并不总能正常运行。存在两个根本问题。一是历史因素。我们选择汽油引擎，Qwerty键盘和轻水核反应堆的经历，可能迫使我们不得不继续使用这么一些相对比较差的技术。历史上出现的偶然事故不一定可以由今天的市场加以修正。若是我们向前展望的时候，发现其中一个技术一旦占了支配地位，有可能变成一个潜在的问题，政府就有理由在技术标准确立之前制定有关政策，鼓励开发更加多样化的技术。又或者，假如我们已经使用了一个相对比较差的标准，公众政策可以引导大家协调一致从一个标准转向另外一个标准。将度量衡的英寸和英尺转换为公制就是一个例子，另一个例子是为了充分利用日光而协调一致转用夏时制。

自由主义的另一个普遍问题在于，生活当中很有影响的事情，有很多发生在经济市场之外。从一般礼仪到清洁空气，这些东西并没有价格，从而也就没有什么“看不见的手”引导人们的自利行为。有时候创造一个价格可以解决这个问题，好比解决海湾大桥堵塞问题的例子。但是有时候给物品标价会改变它的本质，比如一般而言，捐献的血液应该比购买的血液更好，因为那些急于卖血换钱的人很可能自己的身体也不那么健康。

** 第十章 投票的策略

这里我们看到个人收益与成本的计算，不是激励人们投票的决定性因素。不过为了维持民族的正常运转，人们参与投票至关重要，这就是我们需要社会调节的原因。从小学的公民课程，到选举前夕呼唤公民的爱国热情，社会总是想方设法使大家出来参加投票，即便每一个投票者本人对选举结果没有任何重大影响。在爱国热情并不足够的时候，法律就会要求人们参与投票，这正是发生在包括澳大利亚在内的其他几个国家的情况。

** 第十三章 案例分析

同样的事情见于许多联盟。许多国家，一个大政党和一个或多个小政党，必须组成一个联合政府。大政党一般愿意扮演负责合作的一方，委曲求全，确保联盟不会瓦解，而小政党则坚持他们自己的特殊要求，而选择通常可能偏向极端的道路。以色列联合政府的小宗教团体的影响就是一个很好的例子。北约内部有另外一个例子：美国承担了防务开支一个不恰当比例的份额，大大便宜西欧和日本。美国经济学家曼库尔奥尔森将这一现象非常简洁地称为“小国对大国的剥削”。

大学教授马丁苏比克设计了下面这个陷阱游戏：一名拍卖人拿出一张1美元钞票，请大家给这张钞票开价。每次叫价以5美分为单位，出价最高者得到这一张1美元钞票，但出价最高和次高者都要向拍卖人支付相当于出价数目的费用。这个游戏或博弈有一个均衡，即从一美元起拍，且没有人再追加叫价。假如起拍价低于一美元又如何呢？这样的层层加价可能是没完没了的，唯一的上线就是你钱包里的数目。

因此，一个更好的规则是，如果申报单申报的收入低于申报者所在职业的合理收入，那么这份申报单接受审计的可能性应该更高。与此同时，如果申报者为某一方面的收益申报一个较高的税收减免额且超出了合理范畴，那么这项申报也应该成为审计的目标。实际的做法正是这样。
