#+title: 像火箭科学家一样思考（Think Like a Rocket Scientist）

https://book.douban.com/subject/35228079/

** 被降级

>> 在道格拉斯·亚当斯（Douglas Adams）令人捧腹的著作《银河系漫游指南》（The Hitchhiker's Guide to the Galaxy）中，超级计算机“深思”被要求回答“关于生命、宇宙和万物等终极问题的答案”。经过750万年深思之后，它给出了一个明确但基本上毫无意义的答案：42。尽管这本书的书迷试图为这个数字赋予某种象征性的意义，但我觉得它没有任何意义，亚当斯只不过是在借此嘲笑人类多么渴望和执着于确定性。

** 我们一直都是这样做的

>> 问题就出在这里。顾名思义，流程是一种守旧的做法，它是为了应对过去的难题而制定出来的。如果我们把流程当作一份神圣的契约，不对其提出质疑，那它就会阻碍事物向前发展。随着时间的推移，过时的流程便阻塞了我们组织的大动脉。
然后，遵守这些流程成为成功的标杆。“我们经常听到初级领导者为不好的结果找理由。”杰夫·贝佐斯（Jeff Bezos）说，“比如他们会说：‘呃，我们是按流程办事的。’如果你不小心提防的话，流程就会变成大麻烦。”不过，你无须把标准操作流程扔进碎纸机，使公司变得混乱不堪。相反，你需要养成一个习惯，像贝佐斯那样问自己：“是我们主导流程，还是流程主导我们？”
必要时，我们要忘记自己所掌握的知识，重新开始。正因为如此，解决了延续数百年的费马最后定理的安德鲁·怀尔斯说道：“如果你想成为数学家，记性太好可不是什么好事。你需要忘记上一次处理问题的方式。”
总而言之，埃米尔·费伯的观点是正确的。知识确实是个好东西，但知识的作用应该是给人们提供信息，而不是起约束作用；知识应该启发智慧，而不是蒙蔽心智。只有让现有的知识不断进化，我们的未来才能变得越发清晰。
知识的专制性只是问题的一部分。我们不仅受限于自己过去所做的事情，还受到其他人所做事情的束缚。

** 来自无形规则的阻力

>> 如果你发现自己有各种理由来维持某种事物的现状，请务必小心。“只要提出不止一个理由，你就是在尝试着说服自己去做些什么。”作家兼学者纳西姆·尼古拉斯·塔勒布（Nassim Nicholas Taleb）说道。
你要找到当前支持自己做某件事的证据，而非历史证据。许多无形规则是为了解决某些问题而制定的，可这些问题当下已经不再存在（就像寓言中的那只猫）。病原体离开很久之后，免疫反应仍然发挥作用。
揭露无形规则的最佳方式就是违反这些规则。倘若你觉得自己不可能登月，就去实现一次看似疯狂的想法；倘若你觉得自己不配加薪，就去要求上司给你加薪；倘若你认为自己得不到某份工作，就去大胆申请吧。
你会发现，就算没有那只猫，冥想也是有可能进行下去的。

** 你为什么要去冒险

>> 我们告诉自己：我是一个严肃的学者，而严肃的学者不为公众发博客或播客。我们告诉自己：我是一名严肃的喜剧演员，而严肃的喜剧演员不会放弃自己蒸蒸日上的单人脱口秀事业。我们告诉自己：我是一位严肃的创业者，而严肃的创业者不会把自己的净资产投入到风险极大、几乎不可能成功的太空冒险领域中。
这样的说法存在某种确定性，让我们感受到重要和安全，让我们觉得自己很受欢迎。它把我们和上一辈的严肃学者、喜剧演员及创业者联系在一起。
但是，这样做就不是我们塑造故事，而是故事塑造了我们。随着时间的推移，故事成为我们的身份。我们不会改变故事，因为改变它意味着改变了我们的身份。我们害怕失去一切我们努力打造的事物，担心别人会笑话我们，害怕自己做傻事。

** 破坏的艺术

>> 如果你想改变一个行业，在行业外寻找人才是合理的做法。你会发现，行业外的人才不会被那些束缚思维的无形规则（比如白色桌布）蒙蔽双眼。在创立初期，SpaceX经常聘请来自汽车和手机行业的员工。这些领域技术更新速度很快，需要快速学习和适应，而这恰恰是第一性原理思考者的标志。

** 奥卡姆剃刀

>> 据传，NASA用了10年时间，花费数百万美元开发了一款圆珠笔，它能在零重力和极端温度环境下工作。苏联人则在太空中使用铅笔。
这个关于“书写工具”的故事纯属虚构。铅笔尖容易断掉，碎屑会进入角落和裂缝里。在地球上，这可能问题不大，但在宇宙飞船上就有问题了。断掉的铅笔尖可能会进入关乎任务成败的设备中，或者四处飘浮，进入宇航员的眼球。

** 好奇心杀死了薛定谔的猫

>> 我们之所以不鼓励好奇心，另一个原因在于这需要承认自己无知。若我们问一个问题，或者提出一个思想实验，就意味着我们不知道答案，所以我们很少有人愿意这样做。由于担心别人觉得我们很蠢，我们认为大多数问题简直太简单了，不值得去问，于是就不做这件事。
更重要的是，在这个“快速行动、打破一切”的时代，好奇心似乎是一种不必要的奢侈品。随着“清空收件箱”思潮的兴起，以及人们专注于喧嚣的生活节奏和执行力，效率似乎才是答案。它照亮了前进的道路，让我们明白人生匆匆，要赶紧做待做清单里的下一件事情。另一方面，提问题是极其低效的。如果它们无法立刻产生答案，就不太可能在我们已经过度繁忙的日程表中占据一席之地。

>> 对结果的恐惧是我们逃避好奇心的另一个原因。当我们害怕可能看到的结果时，就不会问一些棘手的问题（正因为如此，人们不愿意看医生，因为他们害怕诊断结果）。更糟糕的是，我们担心自己可能根本找不到任何结果，也就是我们的求索毫无结果。这会把整个思想实验变成对时间的巨大浪费。
我们还认为，思想实验需要做复杂的思想训练或者靠天赐的灵感。我们告诉自己，如果这个问题值得问的话，某个比我们聪明得多的人一定早就问过了。
但是天才并不垄断思想实验——没有被选择的少数。你不需要拥有像爱因斯坦那样仿佛通了电的乱糟糟卷发，就可以进行思想实验。你可能没有意识到，但是我们都是实验者，这些实验都潜伏在我们的潜意识中。

** 终身幼儿园

>> 但是，顽皮和聪明应该是互补的，而非相互对立。换一种说法，顽皮可以成为通往聪明的入口。詹姆斯·马奇（James March）在他的开创性文章《愚蠢的技术》（The Technology of Foolishness）中写道：“顽皮是一种故意暂时放宽规则的做法，以探索制定其他规则的可能性。”他认为，个人和组织“需要不带任何充分理由的做事方式，这种做法方式不常用得上，一般情况下也不会用得上，但有时用得上”。只有对自己的信仰采取一种游戏的态度，我们才能挑战和改变它们。

** 多做点无聊的事情

>> 换言之，“无聊”现在处于一种濒临绝种的状态，这并不是一个好趋势。如果没有无聊，我们的创造力就会因为没有派上用场而退化。“我们淹没于大量信息之中，与此同时，我们又渴望智慧。”生物学家E.O.威尔逊（E.O.Wilson）说。如果我们不花时间去思考，不停顿下来去理解和深思，就无法找到智慧或形成新的想法。最终，我们还是继续采用了首先进入脑海的解决方案或想法，而不是继续研究问题。但是，那些值得解决的问题是不会立即产生答案的。作家威廉·德雷谢维奇（William Deresiewicz）说过：“首先进入脑海的想法永远不是最好的想法。最初的想法别人也能想到，它是我们经常听说的想法，往往属于传统思维。”
无聊时，我们似乎在浪费生命，但事实恰恰相反。在一项研究中，两位英国研究人员经过几十年的调查，得出一个结论，即无聊“应被视为一种合理的人类情感，它对于学习能力和创造力至关重要”。陷入无聊之后，我们的大脑不再对外部世界产生反应，而是听从内心感受。这种心态释放出我们已知的最复杂工具，把大脑从收敛模式转换为发散思维模式。当心灵开始漫游和做白日梦时，我们大脑中的默认模式网络便自动连接了起来，而一些研究表明，该网络在发挥创造力方面起关键作用。
俗话说得好，音符间的沉默造就了音乐。

>> 正如我们早先所看到的那样，安德鲁·怀尔斯在证明费马最后定理之后，成为数学界的名人。按照怀尔斯的说法，停滞不前是“这个过程的一部分”，但他说，“人们不习惯这样，他们觉得压力很大”。他经常陷入停滞不前的困境中，每当此时，他都会停下来，让自己的头脑放松一下，去湖边散个步。他解释说：“散步有非常好的效果，因为你处于这种放松的状态，与此同时你也允许自己的潜意识工作。”怀尔斯知道，心急喝不了热粥，你得时不时远离问题，才能给答案腾出空间。

** 把苹果和橘子进行比较

>> 专业化是目前流行的趋势。在英语世界里，“通才”（generalist）是指博而不精之人。希腊谚语说，一个人“懂得的手艺越多，反而会家徒四壁”。韩国人认为，一个“有12种天赋的人没饭吃”。
这种态度代价很大，它阻断了不同学科思想的交融。我们停留在人文学科或自然科学各自的领域内，从不接受彼此的观念。如果你是英语专业的，量子理论对你有什么用？如果你是工程师，何苦去读荷马（Homer）的《奥德赛》（Odyssey）？如果你是医科学生，何必去学习视觉艺术？

>> 这些例子表明，要让苹果和橘子建立起关联，你必须先收集它们。你收集的东西越多样化，输出的信息就越有趣。不妨拿起一本杂志或图书，去看某个你一无所知的话题；参加不同行业的会议，观察周围不同职业、背景和兴趣爱好的人。不要去谈论天气或重复一些无谓的陈词滥调，而是问他们：“您在做的事情中，哪些最有趣？”下一次，当你发现自己陷入缺乏创造力的困境时，问问自己：“其他行业以前面临过哪些类似问题？”

** 关于孤独天才的谬论

>> 一次火星探测任务将科学家和工程师聚集在一起，团结协作，从而产生了美第奇效应。按太空探索领域的流行说法，科学家和工程师往往合二为一，但是其实他们属于截然不同的职业。科学家是试图理解宇宙运作方式的理想主义者，而工程师们则更加务实，他们必须设计出能够实现科学家愿景的硬件，同时还要努力解决现实难题，比如有限的预算和时间。
对立的事物并不总是相互吸引的。斯奎尔斯写道，每次执行任务时，“理想主义、不切实际的科学家”和“固执、注重实际的工程师”之间总会剑拔弩张。如果任务成功，这种剑拔弩张的态势就能营造一种创造性的氛围，使科学家和工程师都发挥出最佳水平；但如果任务失败，“它就会变成一种酸性物质，侵蚀团队协作精神，直至其腐烂殆尽”。

>> 但先别急，在下结论之前，请先思考一项研究的结果：研究人员将实验对象分成三组，并要求他们解决一个复杂的难题。第一组完全独立工作，第二组持续进行互动，第三组则在互动和独立工作之间交替。
第三组的表现最为出色。研究人员称：“间歇性互动提高了集体的智力。”独立工作和互动之间的循环提高了第三组的平均分，同时也使该小组更频繁地找到最佳解决方案。重要的是，小组中表现最差的人和表现最好的人都从间歇性互动中受益。这些结果表明，知识是双向流动的，一个人得出的结论会被另一个人吸纳。
现代职场环境大多类似于第二组，即存在持续的互动，对于发挥员工创造性而言，这并非最理想的环境。研究表明，人际互动很重要，但独立思考的时间也同样重要。创造的过程可能是令人尴尬的。阿西莫夫写道：“每产生一个好的新创意，都会伴随着成千上万个愚蠢的想法，这些想法你自然不想展示出来。”人们应该具备培养独到见解的能力，并且能够聚在一起交流这些见解，然后回去独自工作，在独处与协作之间循环。该模式与我们之前探讨过的专注和无聊周期相似。

** 探月思维的力量

>> 我们天生就是喜欢“探月”的物种，只不过大部分人已经忘记了这一点。
“探月”迫使你根据第一性原理做出判断。如果你的目标是做微小的改进，那就可以保持现状；但如果你的目标是做出10倍改进，就必须改变现状。探月思维使你跟你的竞争对手处于不同阵营，而且往往是完全不同的阵营，使那些老牌玩家和惯例做法落后于潮流。

>> 问题是，探月思维的障碍并非源自金钱或现实难题，而是来自心理上。“没有多少人相信自己可以移动山峦，因此，没有多少人会这么做。”《大思想的神奇》（The Magic of Thinking Big）作者大卫·舒瓦茨（David Schwartz）在书中写道，“探月”的主要障碍存在于你的大脑中，而社会几十年来让你形成的条件反射，强化了这一障碍。传统观念诱使我们相信，低空飞行比振翅高飞更安全，惯性滑行比高飞更安全，小小的梦想比胸怀大志更明智。
我们的期望改变现实，成为自我应验的预言。你追求的事物决定了你人生的高度，追求平庸，你充其量也就是个平庸的人。就像滚石乐队（Rolling Stones）提醒我们的那样，你不可能想要什么就得到什么。但是如果你朝着“月球”的正确方向前进，而不是坠向地面，你就会比以前飞得更高。《终结者》（The Terminator）和《泰坦尼克号》（Titanic）等卖座大片的导演詹姆斯·卡梅隆（James Cameron）说：“如果你为自己设定一个极高的目标，就算失败了，也比其他人的成功来得耀眼。”

>> 很多人不喜欢“探月”，因为我们觉得自己天生不是这块料。我们认为，那些飞得更高的人拥有更好的翅膀，不会融化。米歇尔·奥巴马（Michelle Obama）在2018年的一次采访中驳斥了这种错误想法。“我接触过的政商界要员数量可能超乎你们想象，”她说，“我曾在非营利组织、基金会和企业工作过，我曾在公司董事会任职，参加过多国集团峰会，也曾出席过联合国会议。可以这么说，他们没那么聪明。”
“他们没那么聪明”——他们只是知道我们大多数人从未学到的知识。争夺“羚羊”的人比争夺“老鼠”的人要少得多，其他人都忙着在拥挤且迅速缩小的同一片地域里追逐老鼠，意味着你不得不去“探月”。如果你观望时间过长，或是继续以更高代价追求越来越小的商业利润，其他人就会抢先一步“探月”，让你失业或让你的企业被市场淘汰。

** 激荡大脑

>> 按照阿诺德·施瓦辛格（Arnold Schwarzenegger）的说法，举重训练见成效的最大障碍是“身体调整得太快”。“如果你每天按相同顺序举重物，那么即使不断增加重量，你还是会发现肌肉长得很慢，然后完全停止生长。只有按肌肉期待的顺序去锻炼，肌肉增长才会变得非常高效。”他写道。
换句话说，肌肉有记忆。在坚持完单调的例行训练之后，它们开始思考：我很清楚你今天会让我经历什么。你要上跑步机跑27～33分钟左右；每周一，你都要做卧推和引体向上，我对你了如指掌，完全能应付得来。为了解决肌肉力量上不去的问题，施瓦辛格采用休克疗法，即趁着肌肉还没适应过来，做不同类型的重复负重练习。
有规律的锻炼容易使人受伤，不规则的锻炼使人灵活。

** 回到未来

>> 反溯法不仅能让我们仔细审视通往目的地的路径，还能让人清醒地反思现实。我们常常会喜欢某个目的地，却不会喜欢道路。我们不想爬某座山，而只是希望自己已经爬过某座山。我们不想写书，而只是希望自己已经写了一本书。
反溯法让你转身看来时路。如果你想爬一座山，你可以想象自己背着背包训练，在高山徒步旅行以适应低氧环境，爬楼梯以锻炼肌肉，跑步以提高耐力。如果你想写一本书，可以想象自己每天坐在电脑前，在两年时间里字斟句酌，起草一章又一章不知所云的内容，然后润色，调整，再调整（尽管你自己也不喜欢这些文字），却得不到任何认可和赞赏。
如果你完成了这些练习，而且觉得这个想法听起来像是一种折磨，那就到此为止。如果你觉得这其中有任何异常有趣的地方（正如我觉得写作很有趣一样），那么无论如何都要坚持下去。反溯之后，你还得要求自己从这个过程中获取内在价值，而非追求难以捉摸的结果。


** 如果反其道而行之

>> 德鲁里是西罗（Xero）会计软件公司的创始人和管理者，2005年，他问自己：“现有竞争对手最不希望我们做什么？”正是通过这个问题，他战胜了规模比西罗大得多的竞争对手。他全力以赴，打造了一个云数据平台，而他的竞争对手当时仍然停留于桌面应用程序服务。
德鲁里知道一个许多商业领袖都忽略了的秘密：容易摘的果子早就被人采摘完了。你无法通过抄袭来击败比你强大的竞争对手，但你可以做截然相反的事情来打败他们。
不要采用惯常的最佳做法或行业标准，而要重构问题。问问自己：“如果我反着来呢？”即使你不付诸行动，逆向思考这个过程也会让你质疑自己的假设，摆脱当前视角的束缚。

** 事实不会改变想法

>> 思想不会被事实牵着走。正如约翰·亚当斯（John Adams）所说的那样，事实是顽固的东西，但我们的思想却更加顽固。即使是那些最开明的人，无论事实多么可靠和令人信服，人们在面对事实时也并非总会放下心中的疑惑。大脑赋予我们理性思维，但它也会扭曲我们的判断，带入主观的想法。
我们倾向于扭曲的判断，在一定程度上是由验证性偏见造成的。我们低估那些与我们的信念相矛盾的证据，却高估与我们的信念一致的证据。“这是件令人费解的事情，”罗伯特·皮尔西格写道，“真理在敲门，而你却说：‘走开，我在寻找真理。’于是它就走开了。”

** 杀死你喜欢的假设

>> 虽然科学家们终生致力于审视自己的想法，但这种做法与人性背道而驰。举个例子：在政治上，一致性胜过准确性。当政治家承认自己改变想法时（因为事实已经改变，或者他们被一个更有力的论点说服），他们会因出尔反尔而受到反对派的严厉批评。反对派诋毁他们，给他们烙上反复无常、优柔寡断的标签，认为他们不适合做一个强硬的、有思想的民选公务员。
对于大多数政治家来说，“本论点无可辩驳”这句话是一种美德；但对于科学家来说，这句话是一种罪恶。如果我们无法验证某种科学假说并反驳它，那这种假说毫无价值。正如萨根所解释的那样：“必须让怀疑论者有机会理解你的推理过程，重复你做过的实验，看看他们能否得到同样的结果。”

>> 如果你难以挑战自己的信念，可以假装这些信念是别人的。在写这本书时，我采用了斯蒂芬·金的策略。他会先把书稿放置一旁，几个星期后再重新审阅稿件。当他带着一些心理上的抽离感去看这些稿件时，就更容易假装那是别人写的东西，从一个新鲜的角度来看待这部作品，从而摘掉有色眼镜，对内容进行大刀阔斧的修改。有一项研究表明，金的方法很合理。研究人员把实验对象的想法以其他人的角度呈现出来，结果，实验对象对自己的想法变得更加吹毛求疵。

** 测试存在的问题

>> 我们日常生活中的大多数决定靠的不是测试数据，而是直觉和有限的信息。我们推出一款新产品，更换职业，或者尝试一种新的营销手段，所有这些都没有做过实验。我们常找借口说，我们之所以不做测试，是因为缺乏资源。但我们没有认识到，新方法若最终失败，将会让我们付出极大代价。
即使我们做测试，也只是走走过场，这只是自欺欺人的做法罢了。我们进行测试的目的不是为了证明自己是错的，而是为了确认那些我们认为正确的事物。我们调整测试条件，或者解释模棱两可的结果，以确认我们的先入之见。

** 弗兰肯斯坦的缝合怪

>> 这些例子表明，倘若不进行系统测试，就可能产生无法预测的后果。产品出厂前的最后一刻，如果你要对产品做修改，却不重新测试整个产品，那你就要冒灾难性的风险。如果你想更改诉讼案情摘要的部分内容，却不考虑更改的内容如何与整体互动，那你就是在玩忽职守；如果你把政府一个大型项目的设计环节外包给60家承包商，却没有对综合体系进行测试，那灾难就会等着你，正如healthcare.gov网站的结局。

** 太空先锋

>> 1965年，美国空军79名人员穿上航天服，走进一个安装在冲击平台上的太空舱。他们在太空舱里“上下左右颠来倒去，呈45度角后退、前进或斜向一边”。虽然普通人会在5g重力时失去知觉（g指地球表面的重力加速度），但这些人承受的重力加速度达到了36g的峰值。
这些实验的目的就是测试人们在飞行时的感受，让毫无防备的空军人员承受宇航员在登月之旅中所经历的同类冲击。志愿者们耳膜受损，还有其他部位受到挤压性损伤。一名男性志愿者在太空舱里“屁股悬在空中”，导致腹腔破裂；另一名志愿者的一只眼睛“有点掉出来”。在一份新闻稿中，负责这些实验的约翰·保罗·斯塔普（John Paul Stapp）上校总结如下：“几名志愿者脖子僵硬，背部扭曲，肘部擦伤，偶尔有人破口大骂。付出了这些代价之后，我们可以确保‘阿波罗’号太空舱里3名宇航员的安全。他们首次飞往月球，未知的旅途充满未知的危险，他们会处于各种险境之中。”

>> 但模拟器无法产生微重力，这恰恰是“呕吐彗星”（V o m i t Comet）可以大展身手的领域。“呕吐彗星”是一架飞机的名字，它的飞行轨迹是一条抛物线，有点像过山车，先爬升后俯冲，以此来模拟失重状态。在每条抛物线的顶端，乘客会体验大约25秒的微重力。这架飞机之所以得名“呕吐彗星”，是因为这些陡然爬升和急速俯冲的动作往往会导致乘客产生一阵阵严重的恶心感。宇航员登上“呕吐彗星”，在失重状态下练习诸如吃、喝等动作。
但25秒时间不足以练习更复杂的动作。为了获得更长的失重时间，宇航员跳入一个被称为中性浮力实验室（Neutral Buoyancy Lab）的大型室内水池中，水的浮力模拟了他们将在太空中体验到的微重力。“在水池里，我真的觉得自己像一个经过充分训练的宇航员。”哈德菲尔德写道，“我穿着太空服，借助辅助设备呼吸，就像在太空行走一样。”池中放置了国际空间站模型，宇航员们练习维修设备，而他们最终会飘浮在外层空间进行同样的工作（也称为“太空行走”）。他们练习行走每一步，直到它成为第二天性。对于哈德菲尔德来说，要达到这种熟悉程度，他得花250个小时在水池里行走，才能为6个小时的太空行走做好准备。

>> 这种训练策略的适用范围远远不止于火箭科学。以美国最高法院的口头辩论为例：作为美国最高等级的司法机构，该法院每年审理的案件不足100起，只有少数首席律师有幸向最高法院陈述观点。
我记得我第一次以访客身份走进最高法院审判庭的情形。我首先注意到的不是宏伟高大的天花板或者大理石墙壁，而是律师的发言台居然与9位最高法院法官坐的红木长凳如此之近。当律师向法院陈述观点时，他们会被法官们尖锐的、往往咄咄逼人的问题打断。每半个小时的辩论中，律师平均要回答45个问题。律师还没说完第一句话，法官就连珠炮似地提出问题。由于发言台与红木长凳之间距离很短，所以律师常被视线之外的法官攻其不备。
在陪审团面前打感情牌或许有用，但在全国9位最伟大的法官面前，这招就不管用了。律师们必须保持冷静和镇定，同时还要对一连串问题做出即时反应。“你不能只想着用这个问题的答案说服法官。”经常出现在最高法院的辩护律师泰德·奥尔森（Ted Olson）解释道，“还要考虑到这个答案对其他尚未被问及的问题会造成何种影响。千万不要只取悦一位法官，却疏远了另外几位法官。”

** 舆论的火箭科学

>> 在重新设计病人就医体验时，IDEO公司使用了同样的策略。医院本应悉心照顾病人，挽救病人生命。然而，大多数医院的病房却恰恰相反，它们没有丝毫特色——清一色呆板乏味的白色病房，用荧光灯提供照明。
当一家医疗机构聘请IDEO重新设计病人的就医体验时，该机构的高管们原本期待的可能是一份漂亮的演示文稿，展示新颖的、富有创造性的病房设计方案。但恰恰相反，他们看到的是一部令人头脑麻木的6分钟视频剪辑。视频显示的只有医院房间的天花板。“当你整天躺在病床上的时候，”IDEO公司首席创意官保罗·本内特（Paul Bennett）解释说，“你能做的就只是看看天花板，而这是一次非常糟糕的经历。”
本内特把这套方案称为“瞎子都能看到的”好创意，它是IDEO员工设身处地站在病患的立场上想出来的点子。IDEO公司的一名设计师以病人身份住进医院，并在一张真正的病床上躺了几个小时，被人用担架推来推去，一直盯着天花板吊顶看。他用摄像机录下了这次糟糕的体验。这段6分钟沉闷的天花板吊顶视频剪辑，只是对病人整个就医过程的一瞥。正如IDEO公司CEO蒂姆·布朗（Tim Brown）所说的那样，这是一次“无聊和焦虑的经历，让人感觉失落、不知所措和失控”。
6分钟短片足以让医院的员工投入行动。他们装修天花板；安装白板，让来访者给病人留言；改造病房的风格和颜色，使它们更具个性。他们还把后视镜安装在医院的担架上，让病人看到推担架的医生和护士，并与他们交流。最终，IDEO的视频推动了一次更大范围的讨论——如何改善患者的整体就医体验，从而使患者获得“更人性化的对待，不要像物体那样被搬来搬去，而更像是承受压力和痛苦的人”。

** 观察者效应

>> 但现在假设一种情况：我要找的不是眼镜，而是一颗电子。为了观察一颗电子，我做了同样的事情，向它所在的方向发送了一些光子。我的眼镜比较大，所以当光子与镜片碰撞时，眼镜是不会动的。可是，当光子与电子碰撞时，它们就会移动电子。你也可以把它想象成一枚夹在沙发垫和沙发之间的硬币，你越想抓住这枚硬币，就越使它变得遥不可及。
“观察”这种行为，以不同方式扰乱人类。当人们知道自己被人观察时，他们的行为就会有所不同。

** 失败是可以选择的

>> 亚马逊的Fire手机项目损失了1.7亿美元，不是每个人都能容忍如此规模的失败。你的投资规模也许远未达到这个水平，但基本原则仍然是一样的——唯有允许失败，才能激发原创性。“当涉及想法的产生，数量是对质量最可预测的因素。”亚当·格兰特（Adam Grant）在《离经叛道》（Originals）一书中写道。举个例子：莎士比亚以其少量的经典作品而闻名，但在20年的时间里，他创作了37部戏剧和154首十四行诗，其中一些作品一直被抨击为“未经润色的散文，情节和人物性格发展不够完整”。巴勃罗·毕加索（Pablo Picasso）创作了1800幅画、1200件雕塑、2800件陶瓷和12000幅画，但只有一小部分作品闻名于世。爱因斯坦数百篇出版论文中，只有几篇产生了真正的影响。汤姆·汉克斯（Tom Hanks）是我最喜欢的演员之一，他承认说：“我拍了很多既没有任何意义、也不卖座的电影。”

** “快速失败”的问题所在

>> 快速失败”这个口号不适用于火箭科学。我们不能为了尽快失败，就带着一枚问题多多的火箭匆匆前往发射台，因为每一次失败都会带来金钱和生命的损失，代价极其高昂。
即使是在火箭科学领域之外，这种“追求快速失败”的说法也是错误的。当创业者忙于快速失败并庆祝失败时，他们就不再从错误中吸取教训。觥筹交错间，他们可能接收不到失败发来的反馈信号。换句话说，快速失败并不能变戏法似的孕育成功，当我们失败时，我们往往并没有变得更聪明。

>> 当我们失败时，我们往往会隐瞒、歪曲或否认失败。我们使事实符合我们自私自利的理论，而不是调整理论以适应事实。我们把失败归咎于那些超出自身控制范围的因素，高估了坏运气在失败中发挥的作用，总是说：“下次运气会更好。”我们把失败归咎于别人，常说：“她之所以得到这份工作，是因为老板更喜欢她。”我们用一些肤浅的理由去解释为什么事情没有做好，比如：“要是我们有更多的现金储备就好了。”但是，我们很少把失败归咎于个人过错。
以积极的眼光看待失败，可以帮助我们挽回面子。但问题在于，如果我们不承认自己失败，不真正去反思失败，那就什么也学不到。事实上，如果我们从失败中得到错误的信息，事情只会变得更糟。当我们把自己的失败归咎于监管机构、客户、竞争对手等外部因素时，就没有任何理由改变自己。我们想弥补损失，却损失得更多；我们按照同样的策略加倍投入努力，希望时来运转。

** 要快速学习，而不是快速失败

>> 我们经常把“聪明人的失败”看作是损失，比如，“我浪费了人生的五年光阴”“我们损失了数百万美元”。但是，只有当你把它们称为“损失”的时候，它们才会真正构成损失。你也可以把它们视为投资。失败就是数据，而且往往是你在励志书中找不到的数据。如果你适当关注“聪明人的失败”，它们就能成为你最好的老师。

** 开局与结局

>> 对于科学家来说，每一次迭代都是进步。只要我们能瞄一眼漆黑的房间，那就是一种贡献；如果我们没有发现预期的事物，那就是一种贡献；如果我们把一个未知的未知事物变成了已知的未知事物，那就是一种贡献；如果我们提出一个比以前更好的问题，即使我们找不到答案，那也是一种贡献。
这不禁让我们想起了马特·达蒙（Matt Damon）。在由《火星救援》（The Martian）一书改编而成的同名电影中，达蒙所饰演的角色马克·沃特尼（Mark Watney）教受训的宇航员们遇到灭顶之灾时该如何应对。沃特尼说：“在某个时候，所有事情都会变得不顺，你要对自己说：‘就这样吧，这就是我的宿命。’”你要么接受失败，要么着手去应对危机。“你要权衡利弊，先解决一个问题，接着解决下一个问题，再解决下下个问题。如果你解决了足够多的问题，你就可以踏上归途了。”
如果你解决了足够多的问题，你的探测器就可以在火星上着陆；如果你解决了足够多的问题，你就可以建立罗马帝国；如果你解决了足够多的问题，你就能在月球上着陆。
这就是你改变世界的方式——一次解决一个问题。

** 多么迷人啊！

>> 尼科尔斯的方法揭示了一个秘密，即如何从失败的阵痛中走出来。好奇心战胜了失败，把副作用降到最低，让失败变得有趣。它让我们从情绪和视角上远离失败，有机会从一个完全不同的角度来看待事物。

** 如何体面地失败

>> 测试还有另一个好处。顾名思义，测试就是允许你在相对安全的环境中练习如何失败。火箭科学家们经常失败，但对于我们很多人、尤其新一代人来说，失败可能是一种陌生的体验。正如杰西卡·班尼特（Jessica Bennett）在《纽约时报》上所写的那样：“斯坦福和哈佛的老师们创造了‘缺少失败经历’一词来描述他们所观察到的现象：尽管学生在考试中表现得越来越出色，但他们似乎无法应对最简单的竞争。”
想克服这种恐惧感，就需要采用“暴露疗法”。换句话说，我们必须经常将自己暴露在失败面前，这与接种疫苗道理相同。身体引入弱抗原以后，可以激发体内免疫系统的“学习能力”，防止未来受病毒感染；同样地，暴露在“聪明人的失败”中，可以让我们识别这些失败并从中学习，每一次失败都能增强我们的快速恢复能力，并让我们更加熟悉失败；而每一次危机都成为下一次危机的提前演练。

** 为何成功是一位不称职的老师

>> 正如比尔·盖茨所说的样，成功是“一位不称职的老师”，因为它“诱使聪明人认为自己不会失败”。研究证明，这种直觉是正确的。在一项有代表性的研究中，金融分析师在4个季度内做出了优于平均水平的预测，于是他们变得过于自信，后期预测的准确度低于其基准线。
“天欲灭之，必先捧之。”文学评论家西里尔·康诺利（Cyril Connolly）写道。认为自己已经成功的那一刻，就是我们停止学习和成长的时候；当我们处于领先地位时，便自以为是，听不进别人的意见；当我们认为自己注定要成为伟人时，就会把事情的不顺归咎于别人。成功让我们自认为拥有点石成金的本领，随意挥动手指就能化腐朽为神奇。

** 永远未完成的作品

>> 让我们回顾一下“挑战者”号的灾难。在发射前夕，莫顿聚硫橡胶公司的工程师认为，除非环境温度高于11.6摄氏度，否则不应发射“挑战者”号。然而，“挑战者”号项目负责人马洛伊犹豫不决：“你的建议是，在发射前夕，我们要重新制定一份发射标准，却置此前24次成功飞行所采用的发射标准于不顾吗？”马洛伊以为只要遵循以前成功的规则，就不会有坏的结果。
当我们假装某项活动是常规作业的时候，我们就会放松警惕，固步自封，而补救办法是把“常规”两字从我们的词汇表中删除，并把我们所有项目，尤其是那些成功的项目，视为永远未完成的作品。执行“阿波罗”号、“水星”号和“双子星”号飞行任务的过程中，NASA没有在太空中失去任何一名机组成员，而当时载人航天被视为高危工作。阿波罗登月计划项目早期，唯一的死亡事故发生在地面的发射演练中，“阿波罗1”号航天器起火，造成人员伤亡。直到载人航天飞行常规化之后，我们才在飞行过程中失去了NASA机组人员。“我们对探索太空已经习以为常，也许忘记了我们才刚刚起步。”里根总统在“挑战者”号事故发生后说道。


>> “人类就是未完成的作品，但他们误认为自己已经是成品了。”社会心理学家丹尼尔·吉尔伯特（Daniel Gilbert）说。五届世界田径冠军莫里斯·格林（Maurice Greene）并没有犯这样的错误，他认为自己永远是一个未完成的作品。即使你是世界冠军，格林也会提醒你，必须把自己当作第二名，或者至少假装是第二名，加倍努力地训练，你就不那么容易自满了。求职面试之前，你要反复演练自己的发言，直至你对它了如指掌；你还要做足准备，比你的竞争对手更努力。

** 间断式成功

>> 哈斯廷斯希望放缓成功的速度，也许你会觉得这种做法太荒谬，但他早就心里有数。我们时常认为，若我们无法持续实现个人成就和职业成就，就是一种过失。如果有得选的话，我们情愿一直保持最佳竞技状态，而不是在成功的巅峰和失败的低谷之间游走。然而，诚如商学院教授西姆·希特金所言：“常规化和不间断的成功是存在问题的，它是软弱的表现，而非强大的明显标志。”
“挑战者”号和“哥伦比亚”号事故提醒我们，成功的常规化可能预示着未来大祸将至。研究表明，成功和自满是相伴相生的。我们取得成功的时候，就不再突破原有界限，舒适的现状给我们安装了一块天花板，我们的边界不断缩小，而不是继续延伸。公司高管很少因背离过去的成功战略而受到惩罚，但是如果一名高管放弃成功的战略，转而去推行一个最终失败的战略，那他被惩罚的风险就会大得多。因此，我们不再为新事物冒险，而是继续采用那些“经过实践证明的”能带来成功的公式。这种战术效果很好，但迟早会失效。

** 原因背后的原因

>> 但问题在于，无论是一枚火箭还是一家企业，复杂系统的失败原因通常是多重的，包括技术因素、人力因素和环境因素在内的多重因素可能会共同导致失败的产生。若只纠正一阶原因，则二阶和三阶原因并未获得纠正。这些都是潜伏在表面之下的深层原因，它们是一阶原因的始作俑者，而且可能会令一阶原因卷土重来。
沃恩在她对事件的决定性描述中发现，“挑战者”号事故的深层原因藏匿于NASA的阴暗面中。她说，与罗杰斯委员结论相反的是，“挑战者”号事故之所以发生，正是因为管理层尽了本分，他们按规则行事，而不是违反规则。
沃恩用“偏差正常化”一词来描述这种异常状态。NASA的主流文化使高风险飞行正常化。“过去一直发挥作用的文化理解、规则、程序和规范，这次不管用了。”沃恩写道，“这场悲剧的起因并非管理者毫无道德感、精于算计或擅自违反规则，而是因为他们遵守规则。”换句话说，NASA不仅仅存在O形环问题，还存在墨守成规的问题。
