#+title：思考,快与慢(Thinking, Fast and Slow)

这就是直觉启发法的核心观点：当面对难题时，我们往往会对相对简单的问题进行回答，却忽略了自己已经置换了原始问题这个事实。

这里我且采用由心理学家基思·斯坦诺维奇（Keith Stanovich）和理查德·韦斯特（Richard West）率先提出的术语，用以说明大脑中的两套系统，即系统1和系统2. ·系统1的运行是无意识且快速的，不怎么费脑力，没有感觉，完全处于自主控制状态。 ·系统2将注意力转移到需要费脑力的大脑活动上来，例如复杂的运算。系统2的运行通常与行为、选择和专注等主观体验相关联。

系统2的运作是高度多样化的，但所有这些运作方式都有一个共同特征：所有运作都需要集中注意力，如若注意力分散，运作也会随之中断。

系统1和系统2的分工是非常高效的：代价最小，效果最好。通常情况下，这种分工很有效，因为系统1很善于完成自己的本职工作：它在熟悉情境中采取的模式是精确的，所作出的短期预测是准确的，遇到挑战时做出的第一反应也是迅速且基本恰当的。然而，系统1存在成见，在很多特定的情况下，这一系统易犯系统性错误。

尽管系统1和系统2是本书的主题，但我必须要澄清一个事实，即两个系统并不是真实存在的，它们只是我杜撰出来的角色。系统1和系统2不是标准意义上的实体，没有错综复杂的组成部分，也不是大脑中某个固定的部位。

这一点很重要，因为任何事物占用了大脑的工作记忆，都会削弱你的思考能力。

这个实验使我们对在日常生活中做出的推论丧失了信心。这个实验使我们认为，当人们相信某个结论是正确的时候，他们很可能会相信支持这个结论的论证，哪怕这些论证不正确。如果系统1也参与到活动中来，人们总会先得出结论，然后才进行论证。

上述所有发现有一个共同主题，即钱这一概念会滋生个人主义：不愿和他人在一起，不愿依赖他人，也不愿接受他人的请求。心理学家凯瑟琳·沃斯（Kathleen Vohs）完成了这项意义重大的研究，值得赞赏的是，她并未将自己的众多发现向公众和盘托出，而是留给读者更多的思考空间。凯瑟琳的研究意义深远，她的发现表明我们所处的文化环境中有很多能让人想起钱的事物，这些事物以我们意识不到的方式影响着我们的行为和态度，这些方式也许并不那么光彩。有些文化常常提醒人们尊重他人，另外一些文化则常让人们想起上帝，还有一些国家的人们会对着伟大领袖的照片顶礼膜拜。在一个专制国家中，到处挂着领袖的肖像不仅能向你传达“老大哥在看着你”①的感觉，还会使你逐渐丧失自主的思想和独立的行为能力。

此外，只是想到背后中伤某位同事就会使人更想去买香皂、消毒剂或清洁剂，而不是去买电池、果汁或者糖果。当人们感觉自己的心灵受到了玷污，往往也会引发他们清洗自己身体的想法，这种冲动被称为“麦克白效应”。

人们清洗的身体部位往往是那些令他们深感罪恶的部位。一项实验要求受试者通过电话或者电子邮件对一位假想中的人“说谎”。在随后对不同产品的需求测试中，那些通过电话说谎的人更想要漱口水，而不是香皂；而那些通过电子邮件说谎的人更想要的则是香皂，而不是漱口水。

如果一个句子印刷清晰，或是被多次重复，或是已经深植于脑海，人们就能在认知放松的状态下顺畅地将其解读出来。听别人说话时，如果心情好，或者咬一支笔迫使自己“笑”，都能使认知放松。反之，若说明书印刷模糊，颜色浅，句子冗长，语言晦涩，也许心情也不好，甚至在皱眉，这些情形都会使人处于认知紧张状态。

想让人们相信谬误有个可靠的方法，那就是不断重复，因为人们很难对熟悉感和真相加以区别。权威机构和营销商都深谙这个事实。

如果你很在意自己在别人眼里是否值得信赖、是否聪明睿智，那么说话时就言简意赅吧，能用简单句的时候就别用复杂句。在研究生中有一个广为流传的段子，说的是很多教授眼中那些最令人难忘的词汇。我在普林斯顿大学的同事丹尼·奥本海默（Danny Oppenheimer）反驳了这些学生的说法。在一篇名为“不切实际地运用华丽辞藻的后果：使用长句毫无必要”的文章中，他指出用浮夸的语言来表达熟悉的概念是一种智商低下、可信度差的。

曝光效应并不依赖对熟悉程度有意识的体验，事实上，曝光效应完全脱离了意识：当重复的单词或图片迅速闪过，快到观察者根本没有意识到看见它们时，观察者同样还是更为喜欢重复率高的单词或图片。现在我们应该清楚的是，系统1能对系统2意识不到的那些事的印象做出回应。事实上，当人们完全没有意识到自己看见了刺激物时，其曝光效应会更强。

然而，只有在每个人的观察相互独立、每个人所犯错误之间不相关联的情况下，降低错误率的奇迹才能出现。如果观察者持有相同偏见，就算将他们的判断汇总起来也难以降低错误率。允许不同观察者之间相互影响会减少样本量，进而影响小组估值的准确率。

眼见即为事实的理念有助于达成连贯性和认知放松的状态，从而使我们相信某个陈述是真实的。这一理念解释了我们能够快速思考的原因，解释了我们是如何弄清楚一个复杂领域中那些信息片段的含义的。很多时候，我们拼凑出的连贯情节与事实是无限接近的，完全可以用来支持理性活动。
