#+title: 三体(Three Body)

#+BEGIN_EXPORT HTML
<iframe width="560" height="315" src="https://www.youtube.com/embed/HL_o_if5it0" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
#+END_EXPORT

“七十年后又续了产权，但接着住了不长时间就拆迁了，后来买的那一套倒是还在，我也没去看过。”史晓明指指外面，“现在城里的人口还不及我们那时的百分之一，知道这里最不值钱的是什么？就是爸你一辈子供的房子，现在都空着，随便住了。”

张延喝干了一杯酒，两眼发直地说：“我见过饥饿大进军，几千万人逃荒，大平原上沙土遮天，热天热地热太阳，人一死，立马就给分光了……真他妈是人间地狱，影像资料多的是，你们可以自己看，想想那个时候都折寿啊。大低谷持续了半个世纪吧，就这么五十来年，世界人口由八十三亿降到三十五亿，你们想想吧，这是什么事儿！”

章北海：“成吉思汗的骑兵，攻击速度与二十世纪的装甲部队相当；北宋的床弩，射程达一千五百米，与二十世纪的狙击步枪差不多；但这些仍不过是古代的骑兵与弓弩而已，不可能与现代力量抗衡。基础理论决定一切，未来史学派清楚地看到了这一点。而你们，却被回光返照的低级技术蒙住了眼睛。你们躺在现代文明的温床中安于享乐，对即将到来的决定人类命运的终极决战完全没有精神上的准备。” 舰队司令：“你来自一支伟大的军队，他们曾战胜了装备远比自己先进的敌人，甚至仅凭缴获的武器就打胜了一场世界罕见的大规模陆战。你的行为，辱没了这支军队的荣耀。” 章北海：“尊敬的司令官，我比您更有资格谈论那支军队，因为我家祖孙三代都在其中服役。我的爷爷曾在朝鲜战场用手榴弹攻击美军的‘潘兴’坦克，手榴弹砸到坦克上滑下来爆炸，目标毫发未损，爷爷在被坦克上的机枪击中后，又被履带轧断双腿，在病榻上度过了后半生，但比起同时被轧成肉酱的两名战友来，他还算幸运......正是这支军队的历程，使我们对战争中与敌人的技术差距刻骨铭心。你们所知道的荣耀是从历史记载中看到的，我们的创伤是父辈和祖辈的鲜血凝成的，比起你们，我们更知道战争是怎么回事。”

几乎与此同时，发自木星基地的实况图像也到达了地球，人们在电视中看到，漆黑的太空中，突然出现了两千个太阳！它们排成一个长方形的严整阵列，赫然出现在永恒的宇宙之夜中，让人们不约而同地想起了一句话：上帝说要有光，于是有了光。在两千个太阳的照耀下，木星和它的卫星都像在燃烧，木星大气层被辐射电离，引发的闪电布满了行星面向舰队的半个表面，构成了一张电光闪烁的巨毯。舰队开始加速，但阵列丝毫不乱，这堵太阳的巨墙以雷霆万钧的气势向太空深处庄严推进，向整个宇宙昭示着人类的尊严和不可战胜的力量。两个世纪前被三体舰队出发的影像所压抑的人类精神，终于得到了彻底的解放。这一时刻，银河系的星海默默地收敛了自己的光芒，大写的“人”与上帝合为一体，傲然独步于宇宙间。

章北海停下手中的笔，抬头看着舱外的东方延绪，他的目光平静如水，“同为军人，知道我们之间最大的区别在哪里吗，你们按照可能的结果来决定自己的行动；而我们，不管结果如何，必须尽责任，这是唯一的机会，所以我就做了。”

这时，人们发现了一个奇异的对比：机械臂显然是一个在设计上只重功能的东西，钢骨嶙峋，加上那些外露的液压设备，充满了繁杂的技术秉性和粗陋的工业感：而水滴则外形完美，这颗晶莹流畅的固态液滴，用精致的唯美消弭了一切功能和技术的内涵，表现出哲学和艺术的轻逸和超脱。机械臂的钢爪抓着水滴，如同一只古猿的毛手抓着一颗珍珠。水滴看上去是那么脆弱，像一只太空中的暖瓶胆。所有人都担心它会在钢爪中破碎。但这事终于没有发生，机械臂开始回缩了。

两个多世纪前，阿瑟.克拉克在他的科幻小说《2001：太空奥德赛》中描述了一个外星超级文明留在月球上的黑色方碑，考察者用普通尺子量方碑的三道边，其长度比例是1：3：9，以后，不管用什么更精确的方式测量，穷尽了地球上测量技术的最高精度，方碑三边的比例仍是精确的1：3：9，没有任何误差。 克拉克写道：那个文明以这种方式，狂妄地显示了自己的力量。现在，人类正面对着一种更狂妄的力量显示。

后来的分析者在察看这条航线时震惊地发现，水滴的每一次转向都是一个尖锐的折角，而不是像人类的太空飞行器那样成一段平滑曲线，这种魔鬼般的飞行展示了一种完全在人类理解力之外的太空驱动方式，这种驱动之下的水滴仿佛是一个没有质量的影子，像上帝的笔尖一样可以不理会动力学原理随意运动。在毁灭第三队列的过程中，这种急剧的转向以每秒钟两到三次的频率进行，水滴就像一枚死神的绣花针，灵巧地上下翻飞，用一条毁灭的折线把第三队列的一百艘战舰贯穿起来。

“宇宙就是一座黑暗森林，每个文明都是带枪的猎人，像幽灵般潜行于林间，轻轻拨开挡路的树枝，竭力不让脚步发出一点儿声音，连呼吸都小心翼翼......他必须小心，因为林中到处都有与他一样潜行的猎人。如果他发现了别的生命，不管是不是猎人，不管是天使还是魔鬼，不管是娇嫩的婴儿还是步履蹒跚的老人，也不管是天仙般的少女还是天神般的男神，能做的只有一件事：开枪消灭之。在这片森林中，他人就是地狱，就是永恒的威胁，任何暴露自己存在的生命都将很快被消灭。这就是宇宙文明的图景，这就是对费米悖论的解释。”

罗辑抬起左手，露出了戴在手腕上的手表大小的东西说：“这是一个生命体征监测仪，它通过一个发射器与一套摇篮系统联结。你们一定记得两个世纪前面壁者雷迪亚兹的事，那就一定知道摇篮系统是什么。这个监测仪所发出的信号通过摇篮系统的链路，到达雪地工程部署在太阳轨道上的三千六百一十四枚核弹。信号每秒钟发射一次，维持着这些核弹的非触发状态。如果我死去，摇篮系统的维持信号将消失，所有的核弹将被引爆，包裹核弹的油膜物质将在爆炸中形成围绕太阳的三千六百一十四团星际尘埃，从远方观察，在这些尘埃云团的遮挡下，太阳将在可见光和其他高频波段发生闪烁。太阳轨道上所有核弹的位置都是经过精心布置的，使得太阳闪烁形成的信号发送出三张简单的图形，就像我两个世纪前发出的那三张图一样，每张上面有三十个点的排列，并标注其中一个点，它们可以组合成一个三维坐标图。但与那次不同的是，这次发送的，是三体世界与周围三十颗恒星的相对位置。太阳将变成银河系中的一座灯塔，把这咒语发送出去，当然，太阳系和地球的位置也会同时暴露。从银河系中的一点看，图形发射完成需要一年多的时间，但应该有很多技术发展到这样程度的文明，可以从多个方向同时观测太阳，那样的话，只需几天甚至几个小时，他们就能得到全部信息。”

“生存本来就是一种幸运，过去的地球上是如此，现在这个冷酷的宇宙中也到处如此。但不知从什么时候起，人类有了一种幻觉，认为生存成了唾手可得的东西，这就是你们失败的根本原因。进化的旗帜将再次在这个世界升起，你们将为生存而战，我希望在座的每个人都在那最后的五千万人之中，希望你们能吃到粮食，而不是被粮食吃掉。”

程心担忧地看着罗辑，后者却几乎没有停顿，果断地说：“我考虑好了，下面是我的问题：如果从宇宙尺度的远距离观察，三体世界显现出某种危险特征，那么，是否存在某种安全特征，或者叫安全声明，可以向宇宙表明一个文明是安全的，不会对其他世界构成任何威胁，进而避免黑暗森林打击？地球文明有办法向宇宙发出这样的安全声明吗？”

大多数的自残方案都着眼于技术，主张人类主动退出太空时代和信息时代，建立一个低技术社会，比如19世纪末的电气和内燃机社会，甚至农耕社会。考虑到世界人口的急剧下降，这个方案是可行的。这样，安全声明就变成了低技术声明。 自残派中还出现了极端想法：智力自残。使用某种药物或脑科学技术降低人类的智力，并在基因水平把这种低智力在遗传上固定下来，低技术社会自然就实现了。这种想法其实是走向极端的技术自残，让大多数人厌恶，但仍广为流行。按照这种设想，安全声明就是弱智声明。

还有一个名为“绿色拯救者”的组织，在全球拥有几百万成员，主张人类通过退回农耕社会向宇宙发布安全声明。该组织中的两万多人又回到了澳大利亚，在这个大移民后重新变得空旷的大陆上，开始建立一个示范型农耕社会。“绿色拯救者”在澳大利亚的农耕生活被不间断地全球直播。这个时代已经找不到传统农具，只好由赞助者为他们专门制造。澳大利亚的可耕地很少，全部用于种植昂贵的高档农作物，他们只好在政府指定的地块自己开荒。不过，集体劳动只持续了不到一个星期就没人再干了，这倒不是因为“绿色拯救者”的人懒惰，仅凭热情他们也能维持一段时间的勤劳，而是因为现代人的身体素质已经发生了很大的变化，虽在柔韧性和灵活性方面优于过去的人，却不再适合单调重复的体力劳动，更何况人力开荒在农业时代也是一项很繁重的劳动。在“绿色拯救者”的领袖表达了对自己农民祖先的敬意后，众人一哄而散，示范型农耕社会的事业不了了之。

对安全声明的变态理解还引发了一些恶性恐怖事件，出现了一些主张降低人类智力的“反智慧”组织，其中的一个组织策划了一次大规模行动，在纽约的城市自来水系统中大量加入一种名为“神经元阻遏剂”的药物，该药物能够对大脑产生永久性伤害。好在发现及时，没有造成太大伤害，只是使纽约的供水系统瘫痪了几个小时。令人不解的是，这些“反智慧”组织却无一例外地要求自己保持高智慧，严禁组织成员示范性地使用降低智力的药物或其他技术手段，声称自己有责任做最后一批“智慧人”，以完成低智慧社会的建立并领导其运行。

以迄今为止人类对三体种族极其有限的了解，三体人两性结合的方式是双方的身体融为一体，之后这个融合的躯体将发生分裂，裂解为三至五个新的幼小生命，这就是他们的后代，也是云天明所说的孩子。但这些个体继承父母的部分记忆，出生后思想上已经有一定程度的成熟，所以并不是人类意义上的真正的孩子，三体世界真的没有童年。三体人和人类学者都认为，这是造成两个世界社会文化巨大差异的根源之一。

房间里只剩下程心一人，她在小桌前坐下来，开始复述她记住的一切。一个小时十分钟后，她完成了。她喝了一点水和牛奶，稍稍休息了一会儿，就开始第二遍复述，然后是第三遍。在第四遍复述时，她被要求从后向前回忆。第五遍是在一个心理学家小组陪同下进行的，他们用某种药物使她处于半催眠状态，她都不知道自己说了些什么。不知不觉间，六个多小时过去了。

黑洞的边界称为视界。黑洞外的物质和辐射可以通过视界进入黑洞内部，而黑洞内的任何物质和辐射均不能穿出视界，因此又称视界为单向膜。视界并不是物质面。它表示外部观测者从物理意义上看，除了能知道（指视界）所包含的总质童、总电荷等基本参量外，其他一无所知。球状黑洞的视界半径就足史瓦西半径。

低光速的太阳系黑洞从远处观察是什么样子，不得而知，但只能有两种可能：在落后的观察者眼中太阳系消失了；对于先进的观察者，低光速黑洞应该能被远程观察到，但观察者立刻就明白它是安全的。 有一颗遥远的星星，那是夜空中一个隐约可见的光点，所有望了它一眼的人都说：那颗星星是安全的—这曾是一件被认为不可能的事，现在真的有可能做到。 这就是宇宙安全声明。

除了宇宙安全声明所产生的保障外，进一步研究还发现，黑域本身就是一个高效防御屏障。来自外界的高速攻击体，如光拉，进入低光速区域后其速度立刻大大超越光速，而按照相对论原理，它只能以低光速行，剩余的巨大动能则转化为巨大的质量，攻击体首先进入低光速区的部分质量急剧增大，速度则瞬间骤降，而仍在原光速区的后面部分将以原光速高速撞击到前部，这一效应将彻底摧毁攻击体。据计算，即使用强互作用力材料制造的像水滴那样的超坚固物体，在通过黑域边界时也将被完全粉碎。所以，人们把黑域称为宇宙保险拒。

在光速为每秒16.7千米的世界里生活是什么样子现在还不得而知，但可以肯定的是，那个世界中的电子计算机和量子计算机只能以极低的速度运行，人类可能退回到低技术社会，这是比智子更强的技术锁死。所以，黑域安全声明除了自我隔绝外，还有技术自残的一面。这也就意味着人类将永远没有力量飞出自造的低光速陷阱了。

其实，普通大众对该计划只是持冷漠态度，他们认为，即使光速飞船在自己的有生之年造出来，也不是属于自己的东西。大众更关注掩体计划，这毕竟是最现实的生存之道；当然也关注黑域计划，三个世纪的恐惧经历使人们强烈向往平安的生活，黑域能够提供这种生活；至于与宇宙的隔绝，人们当然感到遗憾，但太阳系本身已经足够大了，这种遗憾是可以接受的。人们对黑域的关注度低于掩体计划，是因为普通人也能看出这种技术的超级难度，大众普遍认为，凭人类的力量很难完成这样的上帝工程。

她突然又有了一百一三十多年前在联合国大厦前怀抱婴儿的感觉，现在，她感到自己怀抱着的婴儿面对一群恶狼，只想尽自己的力量保护怀中的孩子。

“失去人性，失去很多；失去兽性，失去一切。”

判断坐标的诚意有一些可遵循的规律，比如群发的坐标往往都没有诚意。但这些规律都是很粗略的，要想真正有效地判断坐标的诚意，主要靠直觉，这一点种子上的主核做不到，甚至母世界的超核也做不到，这就是低嫡体不可取代之处。歌者有这种能力，这不是天赋或本能，而是上万个颗粒的时间积累起来的直觉。一个坐标，在外行看来就是那么一个简单的点阵，但在歌者眼中它却是活的，它的每一个细节都在表达着自己。比如取点的多少，目标星星的标注方式等等，还有一些更微妙的细节。当然，主核也会提供一些相关信息，比如与该坐标有关的历史记录，坐标广播源的方向和广播时间等。这些合而成为一个有机的整体，在歌者的意识中浮现出来的将是坐标广播者本身。歌者的精神越过空间和时间的沟壑，与广播者的精神产生共振，感受它的恐俱和焦虑。还有一些母世界不太熟悉的感情，如仇恨、嫉妒和贪婪等，但主要还是恐惧，有了恐惧，坐标就有了诚意——对于所有低熵体，恐惧是生存的保证。

歌者从种子仓库取出一个质量点，然后把目光投向坐标所指的星星，主核指引着歌者的视线，像在星空中挥动一支长矛。歌者用力场触角握住质量点，准备弹出，但当他看到那个位置时，触角放松了。 三颗星星少了一颗，有一片白色的星尘，像深渊鲸的排泄物。 已经被清理过了，清理过了就算了，歌者把质量点放回仓库。 真够快的。

首先，由另一个坐标广播了一条信息，原始膜广播，那个世界（歌者把它叫弹星者）的低熵体笨拙地拨弹他们的星星，像母世界上古时代的游吟歌者弹起粗糙的墟琴。就是这条广播信息中包含自译解系统。 虽然那个自译解系统也是很笨拙很原始的东西，但足以使歌者把死者随后发出的一条信息的文本模式与之进行对比，很显然是回答广播信息的。这已经很不可思议了，但先前发广播的弹星者居然又回答了。

“蒸发的是它的封装力场，这种封装力场把那片二维空间与周围的三维空间隔开了，现在两者全接触了。你们还记得‘蓝色空间’号和‘万有引力’号看到的吗？”

人类已经观测到的两次黑暗森林打击确实都来自光粒，但人们忽略了一个事实：这两个星系与太阳系有着不同的结构，187J3X1有四颗类木巨行星，但它们的运行轨道半径极小（以公元世纪的观测技术也只能发现这样的太阳系外行星），平均仅为木星与太阳距离的百分之三，比水星与太阳的距离还近，几乎紧贴恒星，在恒星爆发时将被完全摧毁，不能用作掩体；而三体星系，只有一颗行星。 恒星的行星结构是一个能够在宇宙中远程观测到的星系特征，这种观测对于高技术文明而言可能膘一眼就行了。 人类知道掩体，难道它们就不知道？ 弱小和无知不是生存的障碍，傲慢才是。

有人提出这样一个想法：从理论上说，有可能存在这样一个图像处理软件，用它处理三维物体跌落到二维的图像，就能够恢复这个物体的三维图像。我们希望，在以后遥远的时间里，能有某个智慧文明从二维的太阳系中恢复我们世界的三维图像，虽然只是死的图像，人类的文化也不至于全部湮灭。冥王星上建有地球文明博物馆，原来地球上的相当一部分珍贵文物都存放在那里。博物馆建在冥王星的地下，我们担心，在二维化的过程中，这些文物与地层物质混杂在一起，结构可能遭到破坏，想让你们用‘星环’号把部分文物运出冥王星散落在太空中，让它们单独跌落到二维，这样它们的结构就能以二维形式完整地保存下来，这也算是一种抢救吧……当然，这种事情近乎幻想，但现在，有点事情做总比闲着好。另外，罗辑在冥王星上，他也很想见你们。”

“科学家发现，要论信息保存的时间，咱们那个时候的存储器还好些，他们找了些公元世纪的U盘和硬盘，有些居然还能读出来。据实验，这些存储器如果质量好，可以把信息保存五千年左右；特别是我们那时的光盘，如果用特殊金属材料制造，能可靠地保存信息十万年。但这些都不如印刷品，质量好的印刷品，用特殊的合成纸张和油墨，二十万年后仍能阅读。但这就到头了，就是说，我们通常用来存储信息的手段，最多只能把信息可靠地保存二十万年。而他们要存十亿年！

我向他们保证，不会有什么东西比我的经历更离奇和离谱的，我不会笑话他们。于是他们告诉我，基于现代科学在各个学科最先进的理论和技术，根据大量的理论研究和实验的结果，通过对大量方案的综合分析和比较，他们已经得出了把信息保存一亿年左右的方法，他们强调，这是目前已知的唯一可行的方法，它就是——”罗辑把拐杖高举过头，白发长须舞动着，看上去像分开红海的摩西，庄严地喊道，“把字刻在石头上！”

画面中的三维太空里出现了许多更大的物体，那是更早的时候飞离欧洲六号的小型飞船和太空艇，它们的聚变发动机都开到最大功率，但仍在跌向二维的三维空间中向着平面无助地坠落。有一瞬间，程心感觉飞船和太空艇喷出的长长的蓝色烈焰能够烧穿那没有厚度的平面，但等离子体射流只是首先被二维化了。在那些区域，二维建筑物被二维火焰烧得变形扭曲，紧接着，飞船和太空艇纷纷成为巨图的一部分，按照不重叠的规则，二维城市整体扩大为它们让开位置，看上去像是在平面上激起的水波扩散开来。

程心觉得她说的有道理，最早的尼安德特人距今不过十几万年，按乐观的预测，二维的太阳系在几百万年后有第一批观察者，在“他们”眼中，尼安德特人与现代人已经是同一时代的物种了。再看看别的文物，程心也感觉心灰意冷，无论是对现在的自己还是对遥远未来的“他们”，这些东西还不如正在毁灭的现实世界有意义。

“星环”号飞越太阳系到DX3906间的二百八十六光年只用了五十二个小时，但以亚光速从这个星系的边缘行驶到那颗类地行星，这仅仅六十个天文单位的路程却用了整整八天时间。在飞船接近蓝星时，程心和AA发现它与地球外观上的相似是虚假的。这颗行星的蓝色并不是海洋的颜色，而是陆地上植被的色彩。蓝星上的海洋呈淡黄色，面积只占星球表面积的五分之一。蓝星是一个寒冷的世界，它的陆地除了约三分之一的蓝色区域，大部分被白雪覆盖，海洋也大部分封冻，只有靠近赤道的小片区域处于融化状态。

与地球相比，蓝星上的生态系统十分简单，除了蓝色的可迁移的植物外，海洋中还有种类不多的鱼类，陆地上没有高等动物，只有简单的小昆虫，很像简化版的地球。这个世界可以生长地球的植物，所以，即使不借助任何技术，地球人类也能在这个世界生存下来。

关一帆问道：“你猜一下，对于一个在技术上拥有几乎无限能力的文明，最有威力的武器是什么？不要从技术角度想，从哲学高度想。” 程心想了一会儿，挣扎似地摇摇头，“我不知道。” “你经历过的事情可以给你一些提示。” 她经历过什么？她刚刚看到，为了毁灭一个恒星系。残忍的攻击者把那里的空间维度降低了一维。空间维度，空间维度是什么？ “宇宙规律。”程心说。 “你很聪明，正是宇宙规律。宇宙规律是最可怕的武器，当然也是最有效的防御手段。无论在银河系还是仙女座星云，无论在本星系群还超星系群，在真正的星际战争中，那些拥有神一般技术力量的参战文明，都毫不犹豫地把宇宙规律作为战争武器。能够作为武器的规律有很多，最常用的是空间维度和光速，一般是把降低维度用来攻击，降低光速用于防御。所以，太阳系受到的维度打击是顶级攻击方式。怎么说呢，这也算地球文明的荣誉吧，动用维度攻击是看得起你们。在这个宇宙中，让人看得起已经很不容易了。”

“我知道你想不出来，因为你太善良了。很简单：攻击者首先改造自己，把自己改造成低维生命，比如由四维生命改造成三维生命，当然也可以由三维改造成二维，当整个文明进入低维后，就向敌人发起维度打击，肆无忌惮，在超大规模上疯狂攻击，不需要任何顾忌。”

不顾程心的震惊，关一帆接着说下去：“光速也是被频繁使用的规律武器，但为自己建造光墓或你说的黑域不在此列，那只是我们这些弱小的虫子保命的举动，神们不屑如此。在战争中，可以制造低光速黑洞把敌人封死在里面；但更多还是用来防御，作为城墙和陷阱。有的低光速带规模之大，横穿整个星系旋臂，在恒星密集处，大量的低光速黑洞融为一体。连绵千万光年，那是星际长城，无论多么强大的舰队一且陷进去就永远出不来，这是很难逾越的障碍。”

“也叫重启者，可能是一群智慧个体，也可能是一个文明，或者几个文明，我们不知道，但已经确认它们的存在。归零者想重新启动宇宙，回到田园时代。” “怎么做呢？” “把时针拨过十二点。比如说空间维度，把一个已经跌入低维度的宇宙重新拉回高维，几乎不可能；但从另一个方向努力，把宇宙降到零维，然后继续降维。就可能从零的方向回到最初，使宇宙的宏观维度重新回到十维。” “零维？！你们见过把空间零维化？！” “没有。只见过二维化，连一维化都没见过，但在什么地方肯定有归零者在做，谁也不知道是不是成功过。相对来说，把光速降到零容易一些，它们做得也比较多，试图把光速拨过零，重现无限光速。”

“关键不是光速，而是体系模式，人脑中的化学信号传递更慢，只有每秒两三米，和人走路的速度差不多。神经元计算机就是模拟高等动物大脑的全并行处理，所用的芯片都是为低光速专门设计的。”

有时候，他们也设想新宇宙中的生活。智子告诉他们，按照宇宙学理论，新宇宙在宏观上一定是高于四维的，甚至很可能高于十维。当新宇宙诞生后，647号宇宙能在其中自动建立出口并检测周围的环境。如果新宇宙高于四维，小宇宙出口可以跨越空间进行移动，直至寻找到合适的生存环境；同时，还可与三体世界其他小宇宙的移民进行联系，当然，也可能与银河系人类的移民联系上。在新宇宙中，旧宇宙的移民几乎属于同一个种族了，应该可以共建一个世界。智子特别强调，在高维宇宙中，有一个因素使生存的几率大大增加：在众多的维度中，可能有多于一个的维度是属于时间的。
