#+title: 西藏(林芝-波密-拉萨)游记

-----
Day1

我们从重庆做飞机到林芝的米林机场，之前约好的梁师傅提前在那里等我们了。坐上车后，就沿着一条不知名的公路开去了索松村。西藏地区平均海拔在4000米，所以许多高山上都是常年积雪，所以看到积雪的山峰是稀松平常的事情。在公路上看到了雅鲁藏布江和尼洋河的交汇处。因为是4月份雨水比较少，所以雅鲁藏布江江底的沙子都露出来了，在雨水充沛的6，7月份应该是可以看到比较壮观的景色。

这边的藏民非常友好也很热情，但是卖的东西价钱比较贵，有点令我这种城里来的人提高警惕并且望而却步。不过还好，大部分的商品价钱都还是可以接收的，比如鲁朗的石锅鸡（288小锅）和红烧藏香猪（98）。这边的动物，可能是常年因为和藏民友好相处，所以看到人也不怕且性格温顺。

除了看雅鲁藏布江之外，观南迦巴瓦峰是今天行程的重点。在去索松村的路上，有两个南迦巴瓦峰的观景点，但是因为云雾比较大，所以只能看到附近山脉，看不到南峰。大约2点钟我们入住了索松村的吉美旅馆，我们找了一个可以观看南峰的客房，正对着南峰。梁师傅给我们挑选的客房位置不错，价格也很合理（180一天）。但是到吃晚饭前我们也一直没有看到南峰，基本上我们是要放弃了。不过大约就在晚上7：30左右的时间，突然南峰方向的云散去，露出了南迦巴瓦峰的主峰。景色非常壮观，难以用语言表达，仿佛附近的山峰之后都是为了凸显那主峰存在的。

（第一张是南峰出现之前，第二张是南峰出来时）

file:images/tibet_travel_0.jpg file:images/tibet_travel_1.jpg

-----
Day2

今天的行程是沿着318国道开到波密附近，路上再次经过了雅鲁藏布江和尼洋河的交汇处，不过是从对面的方向看到的。这个交汇处处在雅尼湿地公园里面。雅鲁藏布江其实非常长，雅鲁藏布江大拐弯是在从波密到鲁朗的途中，并且需要徒步进去使用航拍才可以完全看到。离开湿地公园之后，我们就验证318国道开向波密县。

中途首先经过了色季拉山口，山口高度是4700多米，公路是盘旋而上的，从公路向下看是大片林海，向上看则是积雪覆盖的绵延山脉。这段路程非常险峻，只能恰好允许两辆车会车，然后公路旁边就是悬崖，经常是几个连续的180度转弯，而且海拔也在不断地上升。大约在3000多米的时候，我可以明显地感觉到耳鸣，但是习惯一阵子就好多了。

（鲁朗林海和色季拉山口）

file:images/tibet_travel_2.jpg file:images/tibet_travel_3.jpg


送色季拉山口下来，我们经过了鲁朗小镇。今天没有在小镇做停留，只是在一家叫做何大妈石锅鸡的饭店里面吃午餐，吃的就是288元的石锅鸡。味道还可以，3个人点一个小锅就足够了。先吃鸡肉，然后喝鸡汤，最后把蔬菜放到鸡汤里面泡着吃，这是梁师傅给我们的建议。鲁朗号称是东方瑞士，我没有去过瑞士，但是从百度图片里面的瑞士看来，的确是有点味道。从公路向两边看，由近及远，首先是大片的农田和农舍，然后是大片的牧场，最远则是长满了绿树的青山。过两天我们再回来好好在看看这个地方。

下午经过了古乡湖，然后在波密县附近的仁青旅馆下榻，同样也是观景房，同样也是180的价格，但是相比索松吉美旅馆，这里没有电视和WIFI，晚上只能围着篝火看表演以及在床上写日记了。晚上点了个98元的藏香猪，和普通的猪肉感觉味道差别不大，就是比较肥而已:D

-----
Day3

今天的安排是徒步波密县附近的岗乡原始森林。其实从仁青客栈出发也可以行走到岗乡原始森林里面，但是距离那里的位置太远了。早起我们在仁青客栈下了两碗面30元，后来我和梁师傅吐槽这事，他说这算是合理消费，在羊卓雍措（羊湖）那边一碗面可能就要到40，50元。早饭之后我们就沿着岗乡原始森林的方向徒步了一段，但是只是转转，没有进入原始森林景区内。

（我所住的仁青客栈，价钱合理，还是观景房）

file:images/tibet_travel_4.jpg

中午到了波密县吃午饭。截止到现在，所以行程包括旅店基本上的都是四川开的，本地藏民的饮食对于我们肯定是吃不惯的。梁师傅说到，藏民开的旅店很少人去入住，两个原因，一个是他们在装修方面不好住进去不舒服，二是他们对司机朋友不太好，比如司机远途去接客人，四川人开的旅店会给司机提供免费住宿，而藏民则要求司机给钱，这样司机在推荐客人住旅店时肯定是送到四川人家旅店。波密县就是在318国道上，人多车多，路边有市政府，超市，酒店，诊所以及各种商店，只是没有什么景色。

从波密县沿着扎墨公路（扎木镇-墨脱，墨脱这个地方除了有雅鲁藏布大拐弯之外，还专产石锅鸡的石锅）就可以找到去岗乡原始森林的路。这条路前半段比较险峻，公路一侧在悬崖边上的，悬崖边上就是迫龙藏布（藏布在藏语里是江的意思，措就是湖的意思，所以雅鲁藏布江其实应该叫做雅鲁藏布）。开到中途海拔变低，景色一变，可以看到大片的牧场，然后远处是白雪覆盖的雪山，甚是令人吃惊。这边有很多人家和客栈，我们就在这里住下了，梁师傅给我们推荐的是一家叫做惜臧源的客栈。在3，4月份的时候，这里房间爆满，我现在住的观景房可能需要500-600元，现在200元就可以拿下，淡季有淡季的好处，景色少点，但是人也少点，价钱也更便宜。

（第一张是从观景房看过去的景色，第二张是观景房本身）

file:images/tibet_travel_5.jpg file:images/tibet_travel_6.jpg

岗乡原始森林的中途一段的景色。可以看到国家在西藏的建设上还是投入了很大力量的。

file:images/tibet_travel_7.jpg

-----
Day4

很惊喜的是，在惜藏源这家旅店里面，还可以看大军师司马懿之军师联盟。这家旅店有大约14间客房，每个客房都是WIFI覆盖的，在院子中间主主人打算种些花草，这样客人会更加喜欢这里。他们家有两个小孩，斯郎邓巴是哥哥，次仁扎西是弟弟，非常可爱。

早上8点起床后，我们沿着进入岗乡的反方向溜达了一圈。早饭是青稞饼，稀粥，咸菜以及酥油茶。刚出炉的青稞饼很香很软，好吃。吃完早饭我们就从岗乡出发了，今天的行程是回到林芝市，然后后天从林芝市去拉萨市。从岗乡到林芝市大约250公里，从林芝市到拉萨大约400公里，大部分时间都是在坐车。

从岗乡到林芝市最期待的就是鲁朗小镇了。在快进入鲁朗小镇之前，我们在扎西岗村吃中午饭。这家饭菜的确不错，一荤一素一汤全部打扫干净了。快吃完饭时，有一个骑行的小哥也来吃饭，看得出他应该是骑行了很久，从他的油腻的头发上可以知道。扎西岗村就在318国道上，从这里可以看到加拉白垒峰，和南迦巴瓦峰相距20公里。

file:images/tibet_travel_8.jpg

鲁朗有三个景区，一个是小镇本身，一个是花海牧场景区，还有一个是鲁朗林海。花海景区据说这个时候去花全部都没有了，但是售票的小哥依然坚持说里面各种各样的花开的很好，虽然不收门票，但是里面需要徒步10公里才能到花海牧场深处，如果不想徒步的话就只能坐他们指定的电车。这种景点我是绝对不会进去的。林海在从色季拉山口下来的时候就可以看到，大片的原始森林在群山怀抱之下。

我觉得小镇本身可能才是最美的。小镇里面有很多酒店和饭店等等，弄得这里商业化味道很重，但是如果只是欣赏景色的话，这些景色并没有被商业包装起来。它和我在电视里和脑海里想象出来的瑞士地区很像。从色季拉山口下来到林芝市途中，有个尼洋河的观景点。观景点不大但是景色却不小。图片中的远处是尼洋河，这个季节水量偏少。

file:images/tibet_travel_9.jpg file:images/tibet_travel_10.jpg

林芝市相比波密县繁华多了，我们在一个叫做艽野尘巨的客栈安置下来。老板是个湖南的小姑娘，因为想近距离地领略西藏这边的风景，所以干脆就在林芝这边开了一家客栈。她和很多导游司机提供方便，和他们结交朋友。我挺佩服小姑娘的想法和勇气的，祝她好运。

-----
Day5

今日的行程比较赶，要从林芝市开到拉萨市，全程400多公里。因为要路过巴松措，所以也打算进去看看，可是这一进一出又要多出100公里，所以这一天下来需要走500公里的路。从林芝开往拉萨可以走林拉公路，这条公路和318国道基本是平行的，318更绕可以看到沿途不同的景色，而林拉公路就是一条高速。

巴松措的有两个观景点，一个是在湖心亭上，一个则是在可以看到湖心亭的一个小山上。从小山上拍摄下去，不仅可以看到大片的湖，还可以看到湖心亭漂在湖面上。不过我偷懒没有爬上那个小山上，只是在湖心亭上走了一圈。天气不好，没有能拍出蓝天白云绿水的感觉，就这样吧。

file:images/tibet_travel_11.jpg

继续往拉萨市开，下一个景点就是米拉山口。米拉山口海拔在5000米以上，挡住了来自印度洋的暖湿气流，所以使得拉萨以及后藏地区和前藏比如林芝波密地区的气候差异很大。过了米拉山口向拉萨驱车途中，变过好几次天，有冰渣，有雨天，还有大晴天。米拉山口的景色远不如色季拉山口，但是可能是因为海拔比较高或者是位置原因，很多游客在那里拍照留念，在山口石碑那里合影需要排队，有几个大爷因为顺序问题还起来争执。

拉萨常年日照时间比较长，在郊区附近我看到远处铺设了大面积的太阳能面板。进入拉萨市城郊区的时候，林拉公路旁边就是拉萨河，因为刚经历过大雨，阳光从云朵中射出来的照在拉萨河以及青山上，非常美丽。

file:images/tibet_travel_12.jpg

晚上虽然很疲惫，但是我还是在从酒店走了2公里左右，去看布达拉宫。布达拉宫正对着人民广场，广场中央是一面飘扬的国旗，和西藏和平解放纪念碑。另外西藏自治区人民政府就在附近，并且四周都是红墙，这个布局和北京很相似。

file:images/tibet_travel_13.jpg

------
Day6

早上很早出发就往羊湖那边赶。羊湖在山南地区，离拉萨市区大约100多公里，但是快到羊湖那边有很长一段是绕山而上的路程，非常难走，开过去大约需要两个半小时。在经过羊湖的路上，可以看到雅鲁藏布和拉萨河的交汇处，然后梁师傅还特意给我们指出了一处水葬的河边。水葬的河边有山，山上画满了白色的梯子，是死去的人的亲人希望死者可以沿着梯子爬到天空，进入天上的极乐世界。

在盘旋而上的公路也有非常美丽的景色，还没有到岗巴拉山口（这个地方是观赏羊湖的一个观景点。这个岗巴拉山口和日喀则亚东县的岗巴拉山口不是一回事，在藏文化里面很多地名，人名重复度很大），已经感觉到身在白云中了。

file:images/tibet_travel_14.jpg

岗巴拉山口上人非常多，和米拉山口一样，那里有块石碑写着“羊卓雍措”，海拔在4900多米，同样是很多大爷大妈等着和石头拍照留念。从山口上看，风景的确不错，但是我的直觉告诉我，如果站在湖边，说不定会有更好的景色。从山口开到湖边不远，大约也就10公里左右的路，可以说下去看是非常值得的。上山途中很多景点，以及在羊湖边上，可以和藏獒合影，那些藏獒看上去体型巨大却非常温顺，回来的时候梁师傅和我们说，这些藏獒都是被打驯化成这样的。

（第一张是从山口拍摄，第二张是在湖附近拍摄）

file:images/tibet_travel_15.jpg file:images/tibet_travel_16.jpg

------
Day7

今天的计划就是在拉萨市里面逛逛，准确的说就是看看布达拉宫（从药王山的角度）和大昭寺（看看释迦摩尼的十二岁等身像）。

我们住在江苏路上的全季酒店，离大昭寺不远大约1公里左右，离布达拉宫大约2.5公里需要做公交车。拉萨，我估计西藏也是，听梁师傅说，不愿意收取钢镚，只愿意收纸币，做公交车投币也必须是纸币。据说是因为硬币上没有藏文，梁师傅和我们认为这其实是一种变相的抵制中央的控制。市区内公交车都是一元，没有分段计价，还比较便宜，但是整个拉萨的消费水平却不低。我们在大昭寺里面的玛吉阿米吃了点东西：辣炒藏牛肉，青稞饼，一瓶喜孜青稞酒， 一块小份的酸奶蛋糕， 140块，味道还算过得去。不过其他地方就是又贵又难吃。

早上我们乘坐公交车去了布达拉宫，据说那里有两个很好的摄像点，分布在布达拉宫的左右两侧。一个是50元纸币上的角度，从药王山上拍摄可以把白塔也纳入进来，另外一个是在湖上可以拍出布达拉的倒影。我早晚各去了一次，白天拍摄旅游的居多，都是拍完就走，还有一对拍婚纱的；晚上去的就相反，都是摄影爱好者，等布达拉8：40亮灯拍摄，都是延迟曝光的那种，都是早早地去抢机位。

file:images/tibet_travel_17.jpg file:images/tibet_travel_18.jpg

因为我们在昨天就去看了小昭寺（5月1之前是不收门票的），所以今天就只看大昭寺。小昭寺我记得是没有看到释迦摩尼八岁等身像的，大昭寺里面看到了十二岁的登身金像。大昭寺里面供奉了很多佛像，还有松赞干布，尺尊公主以及文成公主的像，庄严肃穆。

file:images/tibet_travel_19.jpg file:images/tibet_travel_20.jpg
