#+title: Tips for work-life balance

http://matt.might.net/articles/work-life-balance/

My high-level tips are to:
- Explicitly acknowledge priorities
- Avoid workaholism
- Avoid perfectionism
- Set and enforce boundaries
- Avoid over-commitment
- Use a work-flow system
- Communicate
- Keep hobbies
- Exploit opportunity cost
- Continuously adapt

** Explicitly acknowledge priorities 健康, 快乐, 家庭永远是第一位

#+BEGIN_QUOTE
Start by listing your priorities in life.

If factors like "health", "happiness", or "family" rank below professional goals, your long-term priorities are not stable.

It is too easy to implicitly prioritize work ahead of everything else.

If those inverted priorities persist, a crisis--injury/sickness, depression or divorce--is inevitable.

The first step in avoiding (or resolving) a crisis is to explicitly acknowledge your priorities.
#+END_QUOTE

** Avoid workaholism 不要成为工作狂
应该通过提高效率来减少工作时间

#+BEGIN_QUOTE
The "work more; sleep less" mentality is misguided.

To be clear, I'm not advocating getting any less work done.

I'm not necessarily arguing for working fewer hours either.

Rather, I advocate efficiency.

I've observed the "work more; sleep less" types in many professions. They brag about working late nights and long weekends.

The equation for work is: *output = unit of work / hour × hours worked* "Work more, sleep less" people tend to focus too much on the hours worked part of the equation.

The unit of work / hour part of the equation--productivity--is just as (if not more) important.

The book [[http://www.amazon.com/gp/product/0307463745/ref=as_li_ss_tl?ie=UTF8&camp=1789&creative=390957&creativeASIN=0307463745&linkCode=as2&tag=ucmbread-20][Rework]] by Jason Fried and David Heinemeier Hansson does an excellent job debunking the necessity of "work more; sleep less."

Hacking productivity boosts your maximum theoretical output.

When crunch time hits for a "work more; sleep less" individual, he stresses and panics. He cannot throttle up on output. He is at capacity.

When crunch time hits for a high-efficiency individual, her output skyrockets, because she can ramp up the hours worked part of the equation.

*Are you a workaholic?*
When you talk to colleagues about work, do you talk about what you didn't do--didn't sleep, didn't eat, didn't go to the movies, didn't watch TV?

Or, do you talk about what you did--shipped a grant proposal, wrote a manuscript, explored a new idea, gave a great lecture?

If you emphasize the things you sacrifice over the things you accomplish, perhaps you're too focused on one part of the work equation.
#+END_QUOTE

** Avoid perfectionism 避免完美主义
- 应该将完美看做一个过程而不是目的
- 你会因为不原意delegation而使得workload膨胀许. 
- 它将吞噬你的时间, 而这部分时间已经不能产生任何回报. 
- 你恰好要做的, 就是用这段时间来balance.

#+BEGIN_QUOTE
It is good to use perfection as a guide, but recognize that it is unattainable.

Perfection is a process; not a destination.

Iterate toward perfection but launch once you pass "good enough."

Perfectionism inflates your workload by preventing delegation.

It also sinks time into work well past the point of diminishing returns.

That is time you could have spent on balance.
#+END_QUOTE

** Set and enforce boundaries 设置和强化工作/生活边界
#+BEGIN_QUOTE
Maintaining work-life balance require setting boundaries.

If necessary, it requires harshly enforcing those boundaries.

For example, my home router disables internet access for my laptop after 6:30pm and before 8:00am.

It allows a 30-minute reprieve at 5:30am and 9:30am for quick synchronization with email and repositories.

If you're having a meal, put your phone away or turn it off.

If you must, schedule recurring "life" time into your calendar, and set reminders/alarms.

Harsh boundaries sting when first enforced, but as you grow to accept and appreciate them, you will force yourself to get your work done around them.
#+END_QUOTE

** Avoid over-commitment 避免过度承诺
#+BEGIN_QUOTE
It takes a few minutes to entangle yourself in commitments that can take years to unwind.

Learn when and how to say "no."

If you're over-committed, say, "I'd really like to take on that task/role, but I'm concerned that with my current commitments, I might not be able to perform the this task to the high standards to which I hold myself."

Before you say "yes" to anything, sleep on it.

If you find yourself over-committed, start delegating, canceling, recusing and refusing.
#+END_QUOTE

** Use a work-flow system (GTD)
** Communicate 与家人沟通
#+BEGIN_QUOTE
In a family or a relationship, every member needs to know the stress level and work load of every other member.

A shared calendar system like Google calendar helps with implicit communication of stress level.

I also created a web app for my wife that graphs my inbox size over time. Any upward deviation indicates an increase in stress.

It is also important to maintain explicit, dispassionate communication of stress level: if you're stressed or becoming stressed, warn your family.

They may be able to adapt or help you compensate for short periods if you communicate your needs.

Relying on telepathy is the most efficient way to doom a good relationship.
#+END_QUOTE

** Keep hobbies (译注: 学会找乐子)
#+BEGIN_QUOTE
Even if you love your work (as many in my profession do), it is important to have hobbies outside of work.

Even the best jobs create stress.

Hobbies are a way of letting stress go before it explodes.
#+END_QUOTE

** Exploit opportunity cost 利用机会成本
计算机会成本, 尽量只做喜欢的事情.

#+BEGIN_QUOTE
Decide on a list of essential personal tasks.

If you have a partner, split them up.

Each should claim preferred tasks.

For the remaining unwanted tasks, divide them evenly or consider hiring someone to do them.

For every task, ask whether it is worth your time to do it, given how else you could spend that time.

For example, while I'm capable of cutting the lawn each week, I don't enjoy it, and my time is better spent on research, writing a blog post or playing with my kids. So, we hired a neighborhood college student to cut our lawn.

Or, for instance, if you don't like to clean (or would better utilize that time on another task), consider a home-cleaning service.
#+END_QUOTE

** Continuously adapt 持续不断地适应(balance)
#+BEGIN_QUOTE
Realize you won't always strike the right balance.

You will make mistakes.

That's okay.

Listen to your partner and if they're not satisfied, take action. Move the boundaries; change your habits; or reduce your workload.

Recognize that achieving work-life balance is a never-ending process.

Don't treat the balance in "work-life balance" like a noun.

Treat it like a verb.
#+END_QUOTE



