#+title: 给离去的亲人们

*给妈妈*
妈妈是自己大约在8-9岁的时候去世的，很多事情已经记不清楚了，只有依稀的几个镜头：
- 妈妈让我跪小红木凳，然后拿鸡毛掸子打我。一定是我做错什么事情了。
- 妈妈在住院的时候我在和小伟姐姐玩
- 是我亲手将妈妈的双眼合上的。

*给外公*
对于外公的去世其实我还是能够接受的，在一定程度上我还很高兴，因为在过去一年内他都躺在床上生活不能够自理。今年过年的时候还是在他家过的年，那个时候虽然身体有病但是还是能够活动的。然后2月份我开学之前他住院了，我走之前他和我说话还是非常有力的。但是这个暑假回来之后，他还是躺在床上没有什么差别，但是明显说话就缺乏了力气。舅舅们说在我走后的几个月外公高烧了几次，那是因为过去已经打了很多很多针所以血管基本上都坏了很难找到一个好的血管进行输液，无奈之能够从脖子那里插入管子进行输液，但是插入管子的过程中可能被感染了所以发了很多次高烧。我看过脖子边的管子，当时我希望我有勇气拔掉那些管子然后让他得到解脱。之后暑假的两个月我会经常去看看，但是情况基本上没什么改善。然后暑假的一天晚上我再去医院，外公身上装上了心电仪手指上也夹了一个东西。外公几次和我说夹那个东西很痒，他很想脱下来，但是医生不让。所以我都是一边看住医生一边让外公脱去那个东西。我可以看到他的手已经弯曲得变形了，并且很红，但是医生来了之后又之能够夹上。有时候舅舅不在然后外公想上大号，我首先需要在厕所那里放一个椅子然后把外公扶过去然后帮他脱掉裤子，我能够看到他的大腿基本上都是骨头了，然后把他扶在椅子上的时候能够感觉到他的胳膊也基本都是骨头了。但是这些都不是最痛苦的，最痛苦的是他在走之前头脑一直都是清醒的。暑假的时候他还会和我说他长征时候的故事，还会说想吃什么东西，还会问我奶奶可好，还会跟我说我小时候住在三元楼的事情，还会想念已经去世的外婆，三舅还有我的妈妈。甚至我现在觉得最后的财产分配的时候他也有自己的道理，关于分配财产的事情舅舅们都颇有意见都希望外公不要订立任何遗嘱让他去世之后舅舅自己来弄，但是外公还是坚持自己来分配财产我猜想也是不希望他的儿子们在以后为财产闹矛盾而宁愿自己背上一些东西。

和爷爷过世时候是一样的，本来我觉得我不会有什么感觉，但是下午去殡仪馆擦身体的时候，我看到了他最后一眼。那个时候我才意识到这可能是最后一次的见面了，我才知道我并不是没有感觉。我猜想让我有感觉的东西就是那种称之为习惯的东西。”今天带点东西到外公那里去”，”你应该去外公那里看看了”，”你知道近来外公身体不好吗?”这是过去一年在我耳边最常听到的话，而在更久以前那种称之为习惯的东西就是和外公一起吃饭，和外公坐在一起吹风扇，和外公一起去园子里摘菜和除草，问外公一些长征的事情，问一些妈妈和外婆的事情。现在才发现原来突然抹去那些记忆和习惯是非常伤感的意见事情，你必须接受空间里面永远没有这个人的现实[这个和失恋的感觉是差不多的，虽然我经历过，但是那个失恋的对象依然活在那个空间只不过从你的心灵空间里开了，而这种事情那个人是永远接触不到了]。其实也好，下午在烧钱的时候就在想其实外公已经忍受了近20年的痛苦生活，也应该给一个了解了，从88年三舅，外婆，95年我的妈妈，外公撑住了。直到今年暑假我第一次看到外公在床上流眼泪，我知道其实他已经承受不住了，剩下来的时间就是煎熬。外公，我想和你说今天你已经解脱了，你不用隔着一个空间去想念他们三个人，你能够和他们在一起了，那里才是属于你的地方。从你身上，我看到一个男人最可贵的东西坚强。

外公在2009年12月圣诞节左右离开了.

*给爷爷奶奶*
奶奶是在2010年1月份走的, 就在外公离开不就. 而爷爷是在5年前就是2005年1月23号走的，具体因为什么病就不知道了，但是我知道他有非常严重的支气管炎，每到冬天和我一样都会发作的非常厉害，有时候喘气不过来。奶奶比爷爷小5岁，所以他们都是86岁。具体因为什么病我也不知道，但是我能看到她的两边胸口有淤血所以觉得可能是心脏病去的，前夜她还跟姑姑说心脏很痛。虽然给了她吃救心丸但是还是在早上过了。之所以把两人的悼词放在一起是因为大部分的记忆是他们两个人健在的时候留给我的，而另外一个原因就是爷爷是5年前过的那个时候没有写什么东西所以这次补上。

扯一个东西就是，奶奶的去世看上去非常扯淡但是我觉得确实很和她性格:生不进官门死不进医院。其实她这次犯病离现在大约就是一个月的时间，虽然之前也一直跟我说有时候她心脏很痛但是看上去都没有什么事，能吃也能睡。这次犯病开始是因为骨质疏松，所以她卧床大约就是一个月的时间。但是由于长期不活动所以她的两个脚就起了水泡，这样她每天就坐在椅子上，但是每天就是钩着头。开始的时候还会吃东西，但是逐渐就不愿意吃了。虽然爸妈都和她说过几次去医院但是她一直不答应。大概是因为每天钩着头的原因血液都集中在了胸部，加上她的心脏病已经很久了，所以怀疑是这样原因。奶奶很小的时候就作为童养媳送进了我爷爷家，没有什么文化但是做事能力很强，所以有时候显得非常固执，每次我过去看她她都和我说自己是那个村上最会做事情的人[不过我觉得也很可能是]，而且每次都和我说要是她读书的话一定比我聪明[奶奶，一定吗?]。但是她还有非常非常重要的一点，那就是节省，这个东西也影响到了我毕竟我很小就被她带大的。家里面后面都堆满了她到处捡来的东西，可能也是因为她年老无聊吧。捡回东西之后总是和姑姑说”这个东西洗洗的话还能穿”,”这东西还可以卖很好的钱”，就是因为这点所以这几天我还要和姑姑卖掉家里面成吨的她捡来的杂货。去世的时候也把这点贯彻到底了，基本上这一个月她没有花去任何医药费用，而且生前她也和我说了大概她留下了多少钱给姑姑[对于姑姑来说应该是还不错的一笔，这些就是她生前和爷爷一起存给姑姑的]。通常我和奶奶没有什么距离感交谈也是非常随意的，如果这里她能够听到的话，我想说”你真够狠的”。外公过世的那次我回去也看到了，这也是最后一次看到她还很健康的样子，她和我抱怨养那两只鸭子很烦而且吃了她不少米，走之前像以往一样我抱了一下她闻闻她的头发，大概我也没什么遗憾了。

爷爷的性格特点就是非常的老实。他在林业局工作，但是他是小学文化所以注定和领导班子无缘，事实上他是在林业局食堂当厨师，必须承认他是很会做饭的。我们记得厨房里面他的那把刀非常重但是却异常锋利。每次过年都回弄很多好吃的，但是我不太记得了。我能够确认他很会做做饭是某年他无聊给我自己弄小笼包子吃，非常好吃非常牛。现在想起来小的时候我非常调皮，某年我想把家里的那个黑白电视放在房间里面自己看也方便自己打游戏机，但是那个电视机已经相当古老了，所以我缠着爷爷帮我弄好，爷爷也是花了很大的功夫不断的调台才帮我弄好的[现在想起来，如果上天再给我一次机会的，我宁愿坐在他旁边拿本书念给他听]。个人感觉爷爷这辈子很累而且身体也不是非常好…再加上我这么一个沉重的负担[爷爷奶奶还是非常依我的]…唉

守灵的那个晚上我和妹妹说起了以前我在爷爷奶奶家住的日子。早上6点多的时候，爷爷就会出去走走然后提着一个保暖盆去医院买小笼包子给我吃，通常我起来然后去实验小学踢球，奶奶就是弄稀饭给我们吃，姑姑就去上班。踢球回来就开始吃饭，通常我会把饭拿到客厅里面去吃，因为那里有电视可以看，印象里面就是看”大头儿子小头爸爸”。吃完饭爷爷就坐到藤椅上，如果没有什么事情就一直坐[有时候会去劈劈柴要不就去烧炉子，是因为我们那里有很多煤炭，这个时候我也会去帮忙]。看完电视就会和爷爷一起下下棋，大部分时候是下象棋[在我的印象里他很厉害，可能是因为我很菜，每次都是我耍赖]，有时候下五子棋[通常我都能够虐我爷爷]，然后就是等中午吃饭。吃完饭后就会打开风扇然后躺在地上睡觉，那个时候感觉很好，爷爷奶奶姑姑还有我:)…起来之后奶奶就急着要拖地因为晚上睡起来就凉快，我和爷爷有时候也会帮抹床擦凉席。5，6点的样子我又会去实验小学踢球，然后回来洗澡吃晚饭。等奶奶洗完碗后，就围着电视看新闻联播。奶奶没有什么文化所以听不懂但是她能看懂画面说什么，比如98年的洪水解放军去救人。爷爷是小学文化，还能够听懂，听完一些之后就会告诉奶奶说了什么事情。这个时候我和姑姑就没有什么事情做，等看完焦点访谈之后姑姑就要看娱乐频道。大概9点的样子我们就睡觉了。晚上爷爷不怕凉到了就睡在床上，我奶奶姑姑就睡在地上盖个毛毯，很舒服……..

想起来真的为以前的事情感到有点后悔，小时候给他们添了很多麻烦，现在也没有给他们什么东西。但是他们却给我了很多东西，爷爷的遗言，奶奶的勤俭，都已经刻在了我的心里。这份伤痛一直会守护我。
