#+title: 解放生产力的工具

这几天折腾了不少工具，有翻墙工具(ss, ssr, kcptun)，有编辑器(emacs, evernote, vscode, pycharm)，也有一些workflow(dash, be focused), 还有存储工具（dropbox, icloud, git etc），还有一些电子工具（比如我之前的mab book air以及ipad2，很长时间都没有使用了）。

折腾这些工具的原因，很大程度上是希望自己可以是consistent workflow来工作，好处是可以减少context switch of mindset, 坏处也非常明显就是需要花费很多时间在这些工具的熟悉以及习惯的养成上。另外一个折腾这些工具的动力是，因为很多工具我都是付费了的，所以我希望这些付费工具可以物有所值（比如Alfred，Dropbox, Evernote, Dash）

不过我逐渐发现，刻意地花费大块的时间来整理这些工具，其实是非常inefficient的。这个和心态和上下文有关。先说上下文吧，整理这些工具的初衷肯定是希望更好地做某些事情（比如整理网页，做笔记，方便开发，观看视屏等等），而刻意地整理这些工具的时候并没有一个明确的上下文，很大程度上是回想过去可能遇到过什么问题，然后came up ideas来如何使用工具。这种方式是非常刻意，别扭，强制，最后可能是完全无用的。而心态上则更加复杂：首先我希望自己可以提高效率，可是当前手上可能有很多事情需要做，花费大把时间来研究工具就会占用我当前的时间，这个平衡需要处理好，不然急躁的心态就会导致自己很快放弃。

我总结一下可能最好的方式还应该是：
1. 结合手头任务来优化效率。在完成手头任务的同时，花点时间来研究可以如何改进工具。
2. 工具是可以很容易切换的。前些时间我尝试使用spacemacs, 为了方便自己切换，我增加了一个shell命令可以在我原来的emacs配置和spacemacs两个模式下面切换。
3. 每次改进一小点，尝试在小区域内实验。这点适用于所有的项目。心理学上好像也支持这点，就是人在一个可以承受的范围内进行实验，如果失败了的话也并不会对自己造成太大的打击。fail fast, fail often, 这是facebook motto, 是非常有道理的。

在折腾存储存储工具（dropbox，icloud，自己的备份硬盘等）以及电子工具(mba, ipda2)的时候，我还有点想法。在整理文件上，我是存在一定洁癖的，希望所有的files都可以被清晰地归类，而且希望冗余度尽可能地低。比如在dropbox上面有的话，就不要在硬盘上备份一把。然后如果资料可以不备份的话，就尽量不进行备份，虽然硬盘空间容量是绰绰有余的。这些洁癖浪费了我很多时间在整理上，但是却没有什么效用：如果磁盘空间容量够的话，多备份几个也完全没有问题；spotlight, alfred, google都是非常好的检索工具，没有必要过分地清晰归类。

人的创造力其实是和注意力关联起来的。如果一个人把过多的经历花费在无关紧要的事情上，那么他可能会成为这些无关紧要事情方面的专家(比如非常擅长整理iPhone存储空间，这都是些毫无意义的事情），但是他同时会浪费很多时间在更多有价值的事情上，比如探索某些算法，或者是深入理解数据库内核，又或者是创造企业为其他人创造价值等等。

维护好自己的工具，但是要时刻清醒地意识到，工具的最终价值。工具的价值不是工具本身，而是要让人从无关紧要的事情中解放出来。
