#+title: Tools of Titans (巨人的工具)

[[https://book.douban.com/subject/30400712/][巨人的工具 (豆瓣)]]

但我的确希望这个问题能够成功地打破你的思维局限，让你能像蝴蝶破茧而出一样获得新生。在回答这样的问题时，你头脑中的“正常”思维、你已内化的社会规则和标准化的框架都是没用的。你必须像蜕皮一样摆脱这些人为的束缚，明白自己有能力重新规划自己的生活。而这需要你付诸实践。

本书包括三部分内容：健康、财富和智慧。当然，这几部分内容之间有大量重叠，因为这三个元素是相互依赖的。事实上，你可以把这三部分看作一个三脚架，你的生活正是建立在三元素相互平衡的基础上的。人们需要所有这三个方面才能够获得可持续的成功或幸福。本书中的“财富”所代表的不仅是金钱，它的意义可以延伸出去，指代时间、关系等许多方面的富足。

“在这些游戏中，你能够看到视觉闪回现象——比如方块下降或方块覆盖，它们会占据大脑中的视觉处理中心。这样你就没有余裕去想自己渴望或者沉迷的事情（这些事情极具视觉影响力）了。这种效果能够持续3~4小时。还有证据表明，如果你在目击了一次创伤性事件之后立即玩俄罗斯方块游戏（最好是在6小时之内，但事实证明24小时之内都可以），其能有效抑制视觉闪回，同时降低创伤后应激障碍的症状。”

“吉姆·德特说过的一句话：‘任何关于未来的论断乍看起来都不靠谱。’还有阿尔文·托夫勒说过的一句：‘说到未来，想象力远比正确性重要得多。’这两个人都是著名的未来学家。这些话提醒我，改变世界的思想在大多数人看来都是荒诞可笑的，我所能做的最有意义的工作就是挑战可能性的极限。如果我现在的工作在大多数人看来是合理的，那就表明我的工作的创新性还不够。”

“视觉覆盖”是我入睡前会做的一个练习，目的是消除头脑中有可能阻碍睡眠的所有视觉回放画面（比如电子邮件、工作计划、与他人的争执以及“我本应该这样说……”之类的念头）。下面是我发现的两种比较有效的具体方法。

记得戴上睡眠眼罩和防噪声软枕硅胶耳塞。你选购的睡眠眼罩最好能把你的耳朵也捂住，而不是挂在耳朵上面。这个设计看起来不起眼，但确实是一次巨大的改进：它降低了环境噪声的影响，不会刺激耳朵，并且很牢固。 软枕硅胶耳塞可以用来阻断鼾声、防水（游泳时）或者阻挡任何来自外部的刺激。对侧身睡觉者来说，其佩戴起来也是很舒适的，因为它们对耳朵来说很柔软，同时还能有效阻断噪声。

应对没有取得进步而带来的暂时性挫折是通往成功之路的必然组成部分。事实上，这也是每一个体育精英必须要学会应对的事情。如果成功唾手可得，那所有人都可以成功了。事实上，对待挫折缺乏耐心是大多数人无法实现自己目标的主要原因。时间方面的不理性期望会导致不必要的沮丧，因为这会让你产生失败的体验。而取得非凡的成功显然并非一帆风顺。 成功的秘诀在于参加训练，完成训练，然后回家。

请记住，高质量的长期效果需要高质量的长期专注。在这期间你不能感情用事，不能找借口，不要因为途中的小挫折就妄自菲薄，要学会享受和欣赏这一过程——最后一点尤其重要，因为与最终短暂的成功时刻相比，你更多的时间是花在实际训练的过程中的。

如果你告诉我一家当前无法适应变化的大公司的名字，我就可以告诉你那些因为完成了季度和年度目标而获得巨额现金奖励的高管的名字。 • 每一位亿万富翁都面临着一个同样的问题：他们周围没人会跟他们说，“喂，你刚才那个愚蠢的想法真的是蠢到家了！” • 彼得·林奇曾经说过：“投资人浪费在预期修正带来的效果上的资金远远高于公司用在修正行为本身上的资金。”

面对压力他格外镇定、头脑清晰。我曾亲眼看到他在面对多个数据中心瘫痪的困境时，表现得近乎无动于衷，甚至依然镇定自若地抿着啤酒，等着台球落袋。我问他，我该如何回答那些极具影响力的记者对此事的提问呢？“告诉他，我们已经准备就绪。”然后他又把另外一颗球打入袋中。他是那种典型的认为“沮丧对事情没有帮助”的人。

托尼认为，当我们的情绪状态处于低谷时，我们只能看到问题本身，却看不到解决问题的方法。举个例子来说，如果你醒来后感觉疲惫不堪，而此时你想坐下来找到某个问题的解决方法，那是不会有任何结果的，你反而会感觉更糟。这是因为你在最开始时状态低迷，然后在试图找到解决方法时又因状态低迷而无法成功（原因在于你观察问题的视野受到了限制），然后你可能会自暴自弃。（例如，你可能会想：“我就是这么没用！为什么我会这么紧张、思路不清呢？”）为了解决这个问题，托尼鼓励我们首先要把自己调整到“最佳”状态。这种情绪上的改善可以让我们进入一种“觉得自己能做到”的模式之中。只有处于这个模式，你才能考虑策略方面的问题，才能发现机会，而不是让自己陷入穷途末路。 把自己调整到“最佳”状态通常就像做5~10个俯卧撑或者进行20分钟的日光浴（参见后文里克·鲁宾）那样简单。即使我在前一天晚上做了十分剧烈的运动，在第二天早晨我也会做1~2分钟的健身操或者壶铃运动，为这一天调整好状态。

*你认为影响未来的最重要的技术趋势是什么？ “我不喜欢谈论技术‘趋势’，我认为一旦产生了某种趋势，那就表明已经有许多人在从事这一领域了。而一旦很多人都在从事某个领域，那就会产生大量的竞争，品牌间的差异就会变小。一般来说，我们都不希望成为某种流行趋势中的一员，不希望成为20世纪90年代末的第4家网络宠物食品公司，不希望成为近十年来的第12家太阳能聚能板制造公司，不希望成为某种趋势的第N家公司。因此我认为，趋势是我们应当避免的事物。与趋势相比，我更喜欢使命感，也就是说你正在解决的这个独特的问题并没有其他人在试图解决。

“我不喜欢谈论技术‘趋势’，我认为一旦产生了某种趋势，那就表明已经有许多人在从事这一领域了。而一旦很多人都在从事某个领域，那就会产生大量的竞争，品牌间的差异就会变小。一般来说，我们都不希望成为某种流行趋势中的一员，不希望成为20世纪90年代末的第4家网络宠物食品公司，不希望成为近十年来的第12家太阳能聚能板制造公司，不希望成为某种趋势的第N家公司。因此我认为，趋势是我们应当避免的事物。与趋势相比，我更喜欢使命感，也就是说你正在解决的这个独特的问题并没有其他人在试图解决。

*你最希望改变自己或提高自己的地方是什么？ “这个问题一直很难回答，因为这就类似于在问我为什么还没有改进、提高自己。但我想说的是，在回顾自己的年轻时代的时候，我觉得自己当时过于追赶潮流，过于争强好胜了。如果你也十分好胜的话，那你在与人竞争的方面可能会做得很好，但其代价就是在其他事情上会失利。 “如果你是个好胜的象棋选手，那你可能象棋下得很好，但你可能会忽略发展其他方面的能力，因为你把自己的精力全用到了击败对手上面，从而忽视了那些重要的或者有价值的事情。因此我认为，这么多年来我已经清楚地看到了竞争的本质。我们还会遇到各种各样的竞争，我也不会假装自己已经摆脱它们了。我所做的改变是，每天都去思考，‘为了能让自己变得更加成功，我怎样才能变得不那么争强好胜？’”

“那些想不出好主意的人在跟你实话实说的时候会告诉你，他们也想不出太多糟糕的主意。但是那些能想出许多好主意的人在跟你实话实说的时候会告诉你，他们想出的糟糕的主意要比好主意多得多。因此，目标不是想出好主意，而是想出糟糕的主意，因为一旦你想出了足够多的糟糕的主意，好主意自然就会出现在你的脑海中。”

“我的建议是，只要有可能，就问自己：我能够达成的最小的目标是什么？值得我付出时间的最小的项目是什么？我能够为其带来改变的最小的群体是什么？因为这一目标是你能想到的最小的，所以它很容易实现。但是设定最小的目标也有风险，因为如果你选择最小的目标，结果失败了，那此时你可能真的会遭受重大打击。

“父母迟早要担负起责任，把他们的孩子放在某种制度下接受教育。这样，孩子们不仅会被教育成一个契合当前体制的人，而且还要因接受这种教育而负债。父母需要做出决定……对于从下午3点到晚上10点孩子们都待在家里的这段时间——他们是在家里观看动画片《摩登原始人》，还是在家里接受教育，学习有用的知识呢？

“我认为我们应当教会孩子两件事：（1）如何领导；（2）如何解决有趣的问题。因为世界上许多国家的人们愿意服从领导，愿意拿着更低的薪水做更辛苦的工作。我们不能靠让自己比别人更具服从性来取胜，而是应当表现出卓越的领导才能或者与其他人相比更具备解决问题的能力……

“教给孩子解决有趣问题的方法，就要给他们有趣的问题，让他们去解决。如果他们失败了，不要批评他们，因为孩子们并不笨。如果每次他们试图解决有趣的问题时都有可能因为失败而被骂，那么他们就会为了得到表扬而去死记硬背教科书上的答案。我在孩子们身上花了大量的时间……我认为，能够看着一个对你充满信任、精力充沛、聪明伶俐的11岁的孩子的双眼，告诉他这个世界的真理，那将是一件非常荣幸的事。我们能够对这个11岁的孩子说的是：‘我真的不在乎你的词汇测试考得怎么样，我只在乎你是否有什么话想对我说。’”

“我自己烘烤咖啡豆，这是关键。这一招是马可·阿蒙德（Tumblr公司的合伙创始人、Instapaper公司和Overcast公司的创始人）教给我的。如果你想自己做咖啡，那么自己烘烤咖啡豆比其他的步骤都重要。这里面有个隐喻，那就是你可以在后期再花时间进行调整，但不管怎样，在最开始使用正确的原料才是决定成败的关键。”

正如迈克·泰森极富传奇色彩的第一位助理教练库斯·达马托所说的那句名言：“在被击中面部之前，每个拳击手都有自己的计划。”对于未来的天使投资者，我的建议是：前往赌场或赛马场，在你花光你拿来赌博的这笔钱的20%之前不要离开，你要眼睁睁看着这笔钱消失得无影无踪。

从根本上说，“体系”可以这样理解，你可以问自己：“我能够培养出哪些持久的技能或者人际关系”，而不是“我可以取得什么样的短期目标”。前者具有强大的滚雪球效应，而后者要么“成功”要么“失败”，没有鼓励奖这一说法。

“你会听到各种背景噪声：‘嘚啵嘚嘚啵嘚，‘蒂姆·费里斯’，嘚啵嘚嘚啵嘚’。此时你会想，在这么多噪声中我是如何听到自己的名字的呢？从本质上说，你的大脑无法处理环境中的所有事物，或者密切关注所有的事物。因此大脑最好的做法是设立一些小型过滤器。大脑会设立怎样的过滤器是由你关注的事物决定的，具体而言，它取决于你对什么事物付出了最多的努力……这就是你设立自己的过滤器的方式。你的过滤器以你的名义自动进行了设定，因为这是你最关心的事情。 “你可以利用这个观点，借助这些自我肯定的想法，让自己的思维和记忆专注于某件十分具体的事情。这可以让你注意到自己周围可能已经存在的相关的事。也就是说，你的过滤器本来被设定成对这些事物采取忽略模式，而你只需要通过记忆和重复等手段对其进行调整，增加过滤网的宽度，让另外一些事情渗透过来，你就能从背景噪声中注意到它们了。当前，某些科学理论可以为此提供支持……

“这一模式的原理是这样的：你的大脑无法发现合适的信息切入点。我的意思是说，当我在思考阅览这些信息，让它们从我的脑海中滑过的时候，我监测的是自己的身体，而不是自己的思维。当我的身体发生变化的时候，我就找到了其他人也会关注的那个问题。”
    对于素材选择非常重要,能否有共鸣

许多方法与你看待世界的方式有关，其中大部分都与“多元化”有关。如果我有100个朋友，那我就不会担心失去其中的一个了；但如果我只有两个朋友，那我可就真的要担心了。我不会因为一个老板解雇我就担心自己丢掉工作，因为我在世界各地的报社中有数不清的老板。不担心压力的办法之一是要消除压力。我不担心自己的股票，因为我有多元化投资组合。多元化减压法对你生活中各方的压力几乎都能起作用。” 有关

资本主义奖励的是那些既稀有又有价值的人和事。你可以让自己变得稀有，具备两种或多种“优秀才能”，直到无人能与你匹敌……在你的综合技能中，至少有一种应当是沟通技能，无论是口头沟通还是书面沟通。这非常简单，就像学习如何比世界上75%的人更具推销能力一样。这是一种真正值得学习的技能。

最流行的节点只有一键之隔。换句话说，

或者想法距离最畅销的书籍、歌曲或者想法只有一线之隔。在互联网兴起之初，一些大型的内容和产品整合者，比如亿贝、亚马逊和网飞公司等，都注意到一种现象：所有销量最低的不知名产品的销售总额等同于，或者在有些情况下超过了少数最畅销产品的销售额。克里斯·安德森（我在《连线》杂志的专栏的继任者）称这种效应为“长尾效应”，因为这种销售分布曲线的形状看起来像是一条长长的尾

当你开始自己的某项事业时，我们能够确定这样几个基本现实：（1）你根本没有自己认为的那么好或那么重要；（2）你有一个需要重新调整的观念；（3）大部分你认为你知道的或大部分你在书本上或在学校中学到的都是过时的或者错误的。 有一个很棒的方法可以解决你所有的问题：让自己依附于那些已经取得成功的人或组织，让自己融入他们，同步前进。追求你自己的荣耀当然更有魅力，但是这很难做到。尊敬就是你应有的态度。 这个态度还有其他的效果：它可以在职业生涯的关键时刻减弱你的自大，让你不为阻碍他人的视野和进步的障碍物所影响，从而从自己所经历到的每一件事中吸收经验教训。

这就是画板策略——帮助别人就是帮助自己。想方设法用自己在短期内令人满意的工作换来长期的回报。别人可能想要获得声誉、得到尊敬，而你可以彻底忘掉它们，当他人借着你的工作成果获得荣誉时，你应当感到高兴——因为那就是你的目标：让他人借助你的工作获得他们的声誉，你只是延期获得而已，并且会连本带利地赚回来。

对于我来说，只有经过一个更偏重于运用情商的思考过程之后，我才会决定是否投资某家创业公司。在最开始，我会从情感上思考这个投资计划怎么样。一旦它通过了这道考验，接下来我才会做一些传统的严格评估，利用客观数据来验证创始人给出的关于其业务在量化方面的指标。

“在与我的一个亿万富翁朋友交谈时，我对对方说：‘我真想写一本有关你的思维方式的书。’对方当时正在评论亿万富翁与非亿万富翁之间的不同之处……他说：‘你能犯的最大错误就是接受自己时代的标准。’无论对于技术、书还是其他任何事，不接受时代标准就是你开拓创新的起点。因此我认为，不接受时代的标准是取得巨大成功并改变世界的秘诀。”

尼尔分三个阶段编辑自己的作品。他的解释如下： 首先，我为自己编辑。（我喜欢什么？） 其次，我为粉丝们编辑。（粉丝们最喜欢、对他们最有帮助的是什么？） 再次，我为批评者编辑。（批评者可能会大肆批评、怀疑或取笑的内容会是什么？）

“其实作家的创作瓶颈并不存在……就像阳痿一样，正是你强加在自己身上的性功能压力阻碍了自己去做本应自然而然就能做到的事情。”

乐队内部达成了一致，决定坚持自己的风格。他们给唱片公司提供了两种选择：要么让他们走人，要么让他们做他们该做的事情。这招果然奏效。我自己也“错失”了许多利用噱头赚大钱的机会。正如托马斯·赫胥黎的名言：“自由状态下犯错，远比戴着枷锁做正确的事要好得多。”如果你足够优秀，那你的机会一定不止一次。

当然，没有人愿意指出的是，通过购买打包包装的度假产品来寻求一种更为简单的生活，就跟想用镜子来照一下自己长什么模样，但同时又不看镜子一样。真正被售卖和消费的只是简单生活的浪漫想法。而且，无论你转多少次头或抬多少次眼，你也不会自觉地照镜子。同样的道理，一周或10天的假期也不会真的让你摆脱自己一贯的生活方式。 最终，这种时间与金钱上的勉强妥协让我们将自己置于一种固定模式之中。我们的体验与资本价值的联系越密切，我们就越会觉得金钱是我们生活的必需品。而我们把金钱与生活联系得越密切，就越是确信自己穷得难以买到自己的自由。怀着这种心态，也难怪有这么多美国人认为，长期的海外旅行是学生、主流文化的反对者和游手好闲的富人们的专利。

流浪会让人获得勇气，放松自己对所谓的确定性的掌控。流浪拒绝把旅行留到其他一些所谓的更合适的时间。流浪是掌控环境而不是消极地等待环境来决定你的命运。

在英国小说家约瑟夫·康拉德的作品《黑暗的心》中，书中人物马洛说道：“我不喜欢工作，但是我喜欢工作的内涵——一个发现自我的机会。”马洛没有提到流浪，但这句话对于流浪同样适用。工作不仅仅是产生收益和创造欲望的行为——它也是流浪的酝酿阶段，你在工作中赢得自己的信用，开始制订计划，把口头的梦想转化为行动。工作既是一个梦想着旅行，给自己写计划的过程，也是一个处理琐事，把自己收拾好的过程。工作是直面问题——那些在其他情况下你可能忍不住想要逃避的问题；工作是处理自己的经济债务和情感债务——这样你的旅行就不是为了逃离自己的真实生活，而是为了发现自己的真实生活。

“我（曾为我的书《勇气》）采访过奥斯托·泰勒。奥斯托是谷歌X（现在就叫‘X’）、谷歌“臭鼬工程”……的负责人。他说：‘当你想去实践一个疯狂的设想——那通常是大出原来10倍而不是大出原来10%的东西——的时候，会有许多事情发生……’ “首要的事情是，当你想要发展得比现在大10%的时候，你是在与每个人对抗。因为每个人都在尽力大10%。但当你想要大出10倍时，那里就只剩你自己了。对于我来说（以行星资源开发为例），并不存在很多类似的公司在与我竞争或者正在行星上勘探。拿人类寿命来说，对于尝试利用人类白细胞干扰素为人类在正常的寿命范围基础上增加40年寿命这个领域，也没有许多公司在那里（尝试做这项工作）。 “第二件事是，当你试图尽力做到比之前大10倍的时候，你必须从一张白纸开始，而且你必须采用完全不同的处理问题的视角和方法。我给你讲讲我最喜欢的例子：特斯拉。埃隆是如何开创性地建造特斯拉汽车并把它打造成不仅是美国，而且是世界上最安全、最非凡的电动汽车的？他肯定不是靠着昔日的、他人的经验做到的。这一点很重要。 “第三件事是，当你试图用10倍大小对抗大出10%的时候，你不一定需要付出100倍的努力，但你能获得的回报则比100倍多得多。”

向太多貌似“很酷”的事情妥协会将你活活埋葬，让你沦为板凳球员，即使你具备首发球员的能力。要想优先发展自己的优势，你必须学会分清事情的轻重缓急；而为了继续保持自己的优势，你需要捍卫自己的时间和精力，不要让别人的事情占据你自己的日程安排。 一旦你的事业发展到了相当不错的水平，错失一两次机会不会对你产生根本性的影响，而沉溺于“听起来很酷”的承诺则会让你翻船。

我在依赖牛市的风险投资界所看到的关于“对冲”的最佳做法是，投资像优步这样的企业，其特点是：（1）具有广泛的国际知名度（如美国蓝筹股）；（2）可以被看作遵循宏观经济反循环规律。例如：股市回调或崩盘可能同时导致买汽车的人数减少，以及更多的人注册成为优步司机以作为自己的替代性工作或兼职工作，这一点是可以预料到的。爱彼迎及其他一些公司也是如此。相对于现有的一些企业（如希尔顿集团），它们的变动成本比固定成本占比更大。

“当你在生活中苦苦挣扎时，抬头仰望一下星空。盯着夜空凝望一分钟，此时你会意识到所有人此时此刻都处于同一星球。就我们所知，地球是附近唯一一个有智慧生命的星球。在你看星星时，你会意识到你看到的星星已经历了漫长的岁月，其中的一些星星在星光照射到你身上的时候已经不复存在了。单单是思考一下有关宇宙的那些赤裸裸的事实就足以让我心生敬畏，感到自我的渺小，所有的焦虑也会随之消失在九霄云外。很多人——当他们站在自己的人生尽头，站在死神门前的时候，都感受到了自身与宇宙的共鸣。”

“你不能因为老板没有满足你的需要就指责他。很多人会说：‘这是我的上级的过失。’这样说不对，实际上这是你的过失，因为你没有以他能理解的方式影响他，训练他，向他解释你为什么需要这种支持。这就是极限控制，我们必须掌控全部。”

在阿韦扎诺大地震中，大约95%的当地居民遇难。这一死亡人数令人难以置信，就像当地遭遇了核打击一样……当时，人们必须互相帮助，所有人——上流社会的人们，底层社会的人们，贵族，农民——都围在同样的篝火旁边。一位幸存者说道：‘此次地震带给我们的是法律许诺过但事实上并没有实现的事物，即人人平等。’”

“新闻的关键是报道真实社会，而不是改良社会。的确，有些事实和真相会让人感觉文明倒退，但这没关系，因为新闻的关键不是改进事物，而是向人们提供准确的信息。”

乘坐商务舱的旅客为何经常遭到绑架？ 有组织的犯罪分子擅长通过贿赂航空公司员工获取航班信息（旅客名单），然后借助谷歌搜索名单中的每一个名字，并据此制作一份“具有较高价值”的目标旅客清单。之后他们会提前到达机场接站处，寻找豪车司机手中举牌上与其清单一致的名字。他们会买通或威胁这些司机，把他们打发走，然后找自己人来取代他们，等候目标人物。 “从纽约、旧金山或者伦敦飞来的高管走下飞机，看到写着自己名字的迎客牌，便走到那个豪车司机打扮的人面前，钻进汽车，结果他们就遭到了绑架。有不少人就这样死于非命了。”

“我可以给你举一个典型例子。有种药物名叫‘华法林’，是一种抗血凝剂。少数人体内有一种遗传标记，使他们对这种药物过敏，摄入这种药物对他们而言是致命的。这就是个典型例子。这种药物如今很常见，而且从外表看你无法得知某人是否对华法林过敏。但是，如果某人掌握着过敏者的基因数据，又恰巧知道这个知识，那你就该明白，这将是致命的威胁。”

“如果我们一味愚蠢鲁莽地发展技术，我们的仆人就可能会成为我们的刽子手。”——奥马尔·N.布拉德利

在Windows系统中你可以使用磁盘加密工具BitLocker，在苹果系统OS X中，你可以使用加密解密工具FileVault。在关闭设备或暂停使用设备时，这些工具能帮助你将数据进行加密处理。假如设备丢失或被盗，为了保护你的机密数据，你可以采用“全盘加密”技术对你的硬盘进行加密，防止别人从你未经加密的设备中窃取信息。

对那些行事随意的非技术人员来说，我建议使用随机密码生成器1Password或者密码管理器LastPass（或者密码管理工具KeePass，如果你偏好开源软件）来记住所有这些密码。我个人使用的是加密软件VeraCrypt，这个软件更复杂。它与1Password这样的软件之间的差别是，1Password被内置在浏览器内，如果计算机出现安全隐患，那么通过解码该软件，他人就可以拿到我的密码了。这种情况不大可能发生，但还是有一定的可能性。

你也可以考虑使用免费的跨平台软件VeraCrypt。如果你觉得自己可能会被迫透露自己的电脑密码，比如在过境时或被“武力威胁”要求说出密码时，你可以使用“隐藏加密卷”，用两个密码来隐藏数据，让自己可以给出貌似可信的“口供”。

你可以使用适用于Windows的网络流量控制软件NetLimiter或者适用于苹果OS X的应用程序控制软件Little Snitch，来检测和决定是否允许或阻止特定程序的出站连接，并且掌握其连接的目的地。

你可以在苹果OS X系统中使用BlockBlock软件，它可以通知你某个程序是否企图进行自动安装，改写开机启动项，哪怕该程序正隐藏在系统的某个角落里。之后，如果你想，你就可以选择阻止该程序。一些病毒或恶意软件，包括一些烦人的常用软件都会企图这样做。你可以自己决定是否一开机就自动运行某些程序。 •

在我事业起步之初，我遇到了一位了不起的人生导师，他给过我一个建议，我至今还在照做。这个建议就是：你必须要有个不断变更的人选名单，其中列出的是3位你始终在观察的人：一个是你的前辈，你希望以他为榜样；一个是你的同辈，你认为他的工作比你出色，你很尊敬他；一个是你的下属，他做的工作是你曾经（1~3年前）做过的并且比你做得好。如果你能一直保持并更新这个3人名单，不断地以此评估自己，不断地向他们学习，那么你一定会不断地超越自我。”

除了保持个人形象和体能方面的原因外： “锻炼还可以保证一天的生活具有一定的纪律性。我发现，如果哪一天糟糕透顶，但我进行锻炼了，那么在这一天结束时我就会想：‘至少我锻炼得不错。’《

蒂姆：“如果要为那些没有这种经历的人提点儿建议的话——‘下次如果你感到恐惧，就这样做……’你建议他们怎么做？” 卡洛琳：“我确实希望人们区分开每一种情绪，将每一种都当作一块单独的小砖头，然后将其排成一排。一旦你能够冷静下来评估自己的能力和处境，在通常情况下，事情就会发生变化。实际上，只要你停下来用这种方法仔细观察，你的生活将会发生根本性的变化，对女性来说尤其如此，因为女性总是会说自己感到害怕，而这正是我真正想要改变的东西。”

为了获得想法而写作，而不是为了表达想法而写作 “和许多其他的作家一样，我们都是为了思考而写作的。我可能会说：‘我认为我有个想法。’但当我开始动笔的时候，我往往会意识到：‘我没有什么想法。’只有在我试着把自己的想法写下来之后，我才会确切地知道自己想的是什么……这就是写作的本质。”

“不要‘过早达到最佳状态’” “我真心推荐松弛的生活态度。‘功成名就’是为中年阶段准备的。年轻的时候要富于创造性，要去丰富人生阅历，但不要以成功与否来衡量你的经历，而应该根据极致表现和极端满意度来衡量它们。”

因此，作为成年人，我发现自己会对那些不按我的方式做事的人感到失望……‘我不喜欢你的做事方式，我不喜欢你的说话方式，我不喜欢你的坐姿’，我几乎不喜欢别人做的每一件事……但那只是一种回避关注我自己的方式。最终我意识到，当我们评判他人的行动时，我们只是在逃避关注我们自己，寄希望于从别人那里获取优越感或诸如此类。我的创伤治疗师说，每当你遇到某个人，在与之交谈之前，你只需要在心里说‘我爱你’，那么谈话就会进行得更顺利。

“世界上只有四种故事：两个人之间的爱情故事，三个人之间的爱情故事，争权夺利的故事和旅行故事。书店中的每一本书都逃不脱这四个原型、这四个主题。” “世界只会因你的行为而发生改变，不会因你的观点而改变。”

*新手小说家最常犯的错误或普遍具有的弱点是什么？ “写作要简洁。相信你的读者，他们具有丰富的想象力，不要尽力去描述每一件事。只要你给出一个线索，读者们就会用自己的想象力沿着这一线索补完整个地图。这就是我不愿出售自己作品的电影改编权的原因所在，因为在电影里什么都显而易见，（观众）不需要思考。然而在小说中则不同，例如在小说《阿莱夫》的开头，我说：‘我在我位于比利牛斯山的家中，那儿有一棵橡树。’我不需要再去解释我的家位于比利牛斯山的何处。我只需要给出重要的元素：橡树、我自己以及我在与之交谈的人，这就足够了……相信你的读者，你要明白读者能够自己填补空白的空间，不要过度解释。” *如何

*有团队或调研人员帮助你吗？ “我没有团队，没有，没有……如果你的书充斥着过量的研究信息，你会让自己和自己的读者感到无趣。出书不是为了显示你有多么聪明、多有文化，而是为了展示你的内心、你的灵魂，并告诉你的读者，‘你们并不孤独’。”

“她说：‘格伦，你要记住，正直的人不是突然变得正直的，他们只是拒绝同其他人一起奔向悬崖。’这就是我们需要做的一切：清楚我们今天应当遵循的原则是什么，而不是我们的利益是什么。即使世人都奔向悬崖，我也不会改变自己的原则。对待人们要充满关爱和尊重，无论他们是否跟我一样，无论他们的信仰是否跟我一样。”

我慢慢意识到：（1）如果你一直很严肃，那么在完成真正严肃的工作之前你就会累垮；（2）如果你不能经常感恩小的成功，那你就永远不会感恩大的成功。在你一心只想着下周、下一个任务、下一件事的时候，成功的体验就会像沙子一样从你的指缝间滑落。这就使得“成功”变成了一场得不偿失的惨胜。

乔希注重深度而不是宽度。他经常使用的一个原则被称作“从微观中学习宏观”。其意思是说，专注于某一领域（无论是国际象棋、武艺还是其他领域）非常细小的某个方面，将其内化为强大的宏观原则，并应用于其他所有的领域。在应用中，这一原则有时会跟“从残局开始”结合起来。

这一原则非常务实，也很重要。大多数人都认为自己可以等到大场面来临时再调动自己的积极性，但是如果你在小场面中不培养自己的‘启动能力’，而小场面的数量是大场面的几百倍，那在大场面中你是不会有机会取胜的……我认为你如果不在平常培养对高质量的追求，那就等于是在培养懈怠的作风。”

在最近的5年中，我的问题变成了：“我怎样才能让自己人间蒸发4~8周呢？”这也是我最经常问那些感觉自己心力交瘁的企业家的一个问题。2周的时间是不够的，因为其他人可能会等你回来让你收拾残局。但在4~8周（或者再长一点儿时间）之后，你就没有充当救火队员的必要了。前提是，你需要从制度上、政策上安排好工作，抛开电子邮件之类的杂务，赋予其他团队成员以要求和工具，只留下最关键的需要你做决策的工作，其他事务统统交给他人，或者干脆制造一台无须你24小时操控的机器。

或许只是因为我正在变老，随着时间推移，我对“奢侈”的定义也发生了变化。现在在我看来，“奢侈”与拥有大量高价商品无关，它是一种闲庭信步的感觉：不慌不忙，不止不休。

“在抚养孩子的过程中，父母是弓，孩子是箭。父母会尽可能瞄准最正确的方向，希望结果不会距离目标太远。这是我祖母教给我的。”

*是否有一句名言指引着你的生活？ “人生不是等着暴风雨过去，而是要学会如何在雨中跳舞。”（改写自薇薇安·格林的一句话）
