#+title: Top 10 Things that Makes You a Good Programmer

http://infocreeds.com/top-10-things-that-makes-you-a-good-programmer/

Continues learning. The learning period of the programmer tends to infinity. Every programmer needs to learn new things every day. Even after 3 or 5 years of experience he/she should not stop the learning.

Basic fundamentals. For learning every new programming language you should know the basic fundamentals of programming like procedure oriented concepts (POP), Object-oriented Concepts(OOPs), inheritance, polymorphism etc. Without basic knowledge of these, you can’t be a good programmer.

Debugging skills. Writing Code is not only the job of the good programmer. When the output is not as same as expected he/she should also have skills to find the mistakes in the code instead of making blindly changes in the code.

Writing human-friendly code. A good programmer cannot write code not only for machines but also for humans that they can understand. A good code is like the poem everyone should understand easily.

Use of latest software’s for coding. A good programmer always uses the latest software’s for programming like eclipse,NetBeans,Dreamweaver etc. The use of latest software helps the programmer to avoid common mistakes and use of many built-in features of the software which save the time of programmer.

Plan before programming. I know it’s hard to plan before you programming but you have to make a scratch plan of your code you want to do in the project. This thing gives you a basic idea about what kind of output you want and what kind of code you want to write.

Ability to handle failure. An error is a common thing while doing programming. The successful completion of the program does not happen only in one try, the programmer has to handle all the failure effectively. There has been days or week to take the successful output for your programmer, Instead of being frustrate a programmer has to be persistent in order to handle the errors in the program.

Time management. The programmer has to manage time for writing code because the after writing the code the programmer also have to look at the errors, optimization of the program, time complexity, Space complexity etc.

Algorithmic thinking. Algorithm is step by step solution to every problem. Many programmers create algorithms to simplify the solution of the problem. So every programmer should have the ability to create algorithms so that he/she can achieve goals in the short time manner.

Mathematical thinking. Programming in areas like graphic design, cryptography, Signal processing should have a good knowledge of math. The programmer should have a good knowledge of maths so that the programming can be done in few days instead of spending lots of time in solving the equation.
