#+title: 参观Google北京

@2016-05-21

终于通过各种关系，认识了一个Google北京的同事LSB，带我今天参观了一下公司。

我们原先是约在中午11点左右，但是因为太兴奋了，大约10点左右就到了。感觉太早去了会打扰同事LSB开会，所以先参观了一下清华园。

大约就在2，3年前吧，我带我爸妈参观过一次清华园。印象已经非常模糊了，只记得特别特别地大，正常走路从西向东至少30分钟。所以这次我从清华东门进去，只是看了一下整个清华园的右翼。作为计算机系毕业的学生，还很幸运地找到了清华的计算机系，清华美院也在附近。正门进去看到那么最大的建筑，我猜想应该是图书馆吧。

file:images/google-bj-tour-1.jpg file:images/google-bj-tour-2.jpg file:images/google-bj-tour-4.jpg file:images/google-bj-tour-3.jpg

也就走了快40分钟，出来到了Google北京公司的楼下。虽然还是比原先定的时间早，但是好在LSB今天老板没在也没有什么会要参加。

不得不说Google的办公环境真的是我见过最好的，每层工作区域附近都有巨大的冰箱里面放满了各种饮料。当时我有巨大的冲动想多装一些饮料把我的书包装满!(汗，我就这点出息) 然后冰箱旁边的架子上也摆满了各种各样的零食，然后还有一个巨大的咖啡机可以做美式，卡布什么的。因为不太会用，所以很厚脸皮地要求那里的一位同学帮忙做了一杯美式。接着就是各种休息室(沙发是那种窝在里面就不想再起来的那种), 健身室(跑步机，器械), 瑜伽室, 淋浴室, 电话会议室(设备看上去非常高档，可以和世界各个地方做视频通话)。午餐就不说了，这个网上已经有很多提到Google餐饮的文章了。

file:images/google-bj-tour-5.jpg file:images/google-bj-tour-6.jpg file:images/google-bj-tour-7.jpg file:images/google-bj-tour-8.jpg

在Google最幸福的还是工程师了，LSB带我到6楼工程师楼层转了一圈。基本上每个人都配备了两个超大的显示器，还有专门的cube给他们工作。他们所有买的技术书籍都可以报销，然后每年还可以报销2000院的眼镜费用(要是我能在Google工作，就不用整天带着这幅玻璃已经有刮花的眼睛了, 唉!)

file:images/google-bj-tour-9.jpg file:images/google-bj-tour-10.jpg file:images/google-bj-tour-11.jpg file:images/google-bj-tour-12.jpg

总之参观下来，给我的印象就是为员工提供的环境实在是太好了，所以搞的里面工程师根本挖不出来啊:)
