#+title: 春节逛圈故宫

@2019-02-13T08:14:27

今年过年我们还是打算不出去，但是呆在天津似乎有点无聊，所以打算去北京住两天。北京的房子虽然小，
但是还是可以挤下三个人，在里面做做简单的饭菜还是没有问题的，顺带带胖子去动物园，带丈母娘去故宫看看。

故宫的门票需要提前在网上预约，我估计是在年28那天开始预约的。每天放8万张票，我记得初二余票比较少，
初三的话还有2万张左右，但是需要排队到下午了。

那天打车可能没有和小哥说清楚，他把我们放到了东北角上，在去神武门/景山和东华门的路口。我虽然很早的时候来过故宫，
但是那都是高一的事情了，基本上就没有什么印象了。该从那个门进去（正门也就是午门进），从那个门出来，完全没有概念，也怪我事前
没有太花时间好好做些功课。还好丈母娘是一个比较随和的人，我们就从角上开始开始往午门方向走。正确的路线应该是
做地铁到天安门东站，然后从天安门进去，然后从神武门或者是东华门出来。附近都没有什么地铁，只能打车或者是公交。
我估计这边也是龙脉所在，不敢随便动工。

紫禁城里面非常大，前半部分（南面）像是工作区域，后半部分（北面）是生活区域。工作区域特别恢弘，生活区域就很紧凑别致，
这个分界线就是中间的乾清门。乾清门的旁边有个小卖部，就是当时的军机处。我注意到工作区域在设计上留白特别大，比如太和门/殿
前面的广场，然后为了气势把殿抬得特别高，我记得看介绍说太和殿本身20多米，总高30多米，也就是下面垫高了接近10米。

然后还有一个印象是英语翻译也特别有气势，我把我当时印象几个深刻的宫殿翻译全找了出来
- 门/殿/宫 Gate/Hall/Palace of
- 文华殿 Hall of Literary Glory
- 武英殿 Hall of Warroir Valour
- 奉先殿 Hall of Ancestral Worship
- 午门 Meridian Gate
- 太和殿 Hall of Supreme Harmony
- 中和殿 Hall of Central Harmony
- 保和殿 Hall of Preserving Harmony
- 乾清宫 Palace of Heavenly Purity
- 坤宁宫 Palace of Earthly Tranquility
- 翊坤宫 Palace of Earthly Honor
- 交泰殿 Hall of Union
- 养心殿 Hall of Mental Cultivation
- 东华门 East Prosperity Gate

我们路线是从午门进去，直走到御花园，然后从西六宫往回走，然后从东华门出。没有看东六宫，也没有去看神武门，有点可惜，
但是奈何我是体力不支，而且估计丈母娘也吃不消。故宫值得多去看几次，每次最好只看某些部分，不要贪图一次看清。据说
从神武门出去上景山，从那里可以看到故宫的全貌，完全是另外一副画面。

file:images/tour-of-forbidden-city-0.jpg

file:images/tour-of-forbidden-city-1.jpg

file:images/tour-of-forbidden-city-2.jpg
