#+title: U of T, Geoffrey Hinton

[[https://beta.theglobeandmail.com/news/toronto/u-of-t-professor-geoffrey-hinton-hailed-as-guru-of-new-era-of-computing/article34639148/]]

前面很长的篇幅介绍了他和当前火热的深度学习之间的关系，我不是特别感兴趣。反倒是觉得他的求学经历很有意思，以及在70-80年代一片对神经网络看衰的环境下面依然坚持着。

Born in Wimbledon and raised in Bristol, England, Prof. Hinton's mother was a math teacher and his father was an entomologist with a fondness for beetles. His great-great-grandfather was 19th-century logician George Boole, the inventor of Boolean algebra, a foundation of modern computing. Prof. Hinton attended what he described as a second-tier private school (called a public school in Britain): "I wasn't particularly good at math at school. I liked physics. And soccer."

He went to the University of Cambridge for physics and chemistry but only lasted a month, dropping out and switching to architecture, where he said he only lasted a day. He re-enrolled in physics and physiology but found the math in physics too tough and so switched to philosophy, cramming two years into one.

"That was a very useful year, because I developed very strong antibodies against philosophy," Prof. Hinton said. "I wanted to understand how the mind worked."

To that end, he switched to psychology, only to decide "that psychologists didn't have a clue." He spent a year as a carpenter before heading to graduate school at the University of Edinburgh in 1973 to study artificial intelligence under Christopher Longuet-Higgins, whose students included Nobel Prize winners John Polanyi, the U of T chemist, and theoretical physicist Peter Higgs.

Even then Prof. Hinton was convinced that the discredited neural-net concept was the way forward. But his supervisor had recently converted to the traditional AI camp.

"I had a stormy graduate career, where every week we would have a shouting match," Prof. Hinton said. "I kept doing deals where I would say, 'Okay let me do neural nets for another six months and I will prove to you they work.' At the end of the six months, I would say, 'Yeah, but I am almost there, give me another six months.' And since then I have been saying, 'Give me another five years,' and people have been saying, 'You have been doing it these five years, this never worked.' And finally, it worked."

He denies ever doubting that neural nets would one day be proven superior: "I never had doubts, because the brain's got to work somehow. The brain sure as hell doesn't work by somebody programming in rules."
