#+title: 急得蛋碎了也没有用

@2013-06-17

最近这几天技术总监出去考察了，出发之前嘱咐了我一些事情，简单地来说就是分为两类，开发新feature，另外就是保持现有平台的稳定（做IT的都知道啊！）。技术总监平时也没有托过我什么事情，这次这么看得起我，必须不能够辜负期望。自己心中已经酝酿了几个能够加快现有平台运行的功能，并且在次之前也考虑过很多东西都将计划列举出来了，以及如何推进其他模块功能的开发。

刚开始搞得还是很不错的，把任务分发下去大家，大家干得很热火朝天。因为一些功能都在开发中并且自己脑力里面已经成型了，所以时间相对来说还算是充裕，每天都时间和大家聊聊天，了解一下进度以及遇到的情况。现在想想另外一个比较重要的原因还是因为大家都知道自己要做什么。对于新人来说是需要把活分细了，并且告诉具体需要做什么事情。随着自己开发的功能完成了之后开始需要进行测试上线，时间开始有点不足了。因为feature不能够一起上，不然就不太好回滚了，所以统筹安排了一些哪些feature先上，哪些后上，所以一些feature就开始挤压了。在上线的同时，我也不断地想出一些新的需要改进的地方，好吧这些也算是一些feature（或者是说要做的事情）。

突然，要做的事情变得好多了，而且事情generate的速度，远远超过事情done的速度，在自己的笔记里面留下了长长的一串to be done的list. 开始每天都需要花时间过这些list，可是从中划掉的速度却异常的慢。一些事情需要大家讨论的，看上去也没啥结果，大致情况就是发出了一个post希望大家讨论，但是没有人回复的那种，可是自己也不太好擅自做决定，所以也只能一直停留在list当中不能删除。

我是一个性子比较急的人，一旦觉得有什么idea自己能做的话，就会实现它并且马上上线。很明显，处在这个角色上面不太容易做这件事情，因为出了问题是你来承担的。一天晚上我修改了配置导致我们计算延迟，第二天CEO问技术总监为什么会这样。总监帮我顶住了，但是很明显这个错误来自于我。可能因为着急，想上线一个新的版本，想修改一个参数配置，有可能会成功，但是也有可能会失败。这里我所说的失败是把情况弄糟糕，而不是仅仅没有改进效果。所以在这个位置上，急得蛋碎了也是没有用的，事情还是只能一件一件地做，安排妥当才是最重要的。当然，很多事情急不得，有时候没有啥效果，有时候会弄得更乱，还把自己弄得非常闹心。这点和积极进取表现上非常类似，但是差别是，积极进取懂得轻重缓急，懂得如何拿的起放的下。

搞了这几天，除了知道“急得蛋碎了也没有用”的道理之外，还有一些其他的感受。对于新人来说，他们是不知道big plan的，因此必须split job并且告诉他们做什么，当然里面具体的细节也可能需要指导。但是对新人来说比较大的问题就是，他们不知道什么时候应该和你商量。可能会从一个小需求做成一个大框架。虽然这很彰显能力，但是不一定是需要的，对于这种事情只能哭笑不得，当然你还不能打消同学积极性，只能告诉他以后多商量，这种事情经常发生。而对于老人来说，他们是有big plan的，可以告诉他一件事情并且他会有一些经验来完成这件事情，同时不会犯多余工作这件事情。他知道公司有哪些现成的资源可以完成这件事情，流程如何代码编写需要注意什么。但是对老人来说同样的问题是，同学不一定能够积极地push一件事情，即使能够积极push的话，也不一定会定时sync过来，当然这个问题较新人来说还好了，毕竟工作方向应该不会存在错误，定时sync一下就好了。一个对于老人更加重要的问题就是，老人懂很多东西但是他不担当。经理提出一个plan，当然希望老人们可以多多提出一点意见把这件事情搞起来，即使意见作用不大，但是也不至于让经理孤立无援。其实一些plan完全是规划性质的，一个人根本不能够想清楚，所以希望大家可以讨论一下，老人们的作用就是要积极参与，让更多的人参与到其中，把一个plan想得更加的清楚和彻底，这样实践起来会更加容易。

晚上扯得情绪有点失控，洗洗去睡了！

-----

@2013-06-18

hi，自己的一些粗浅认识，发在网上不太好意思，直接给你写邮件吧。

其实从工作上的事情，总结起来就是两件：做事和管人。在做基层员工的时候，主要是做事。如果慢慢转向管理岗位的话，就会需要管人。你在空间里写的遇到的一些情况，也是我遇到过的，而且有的问题我现在也没有好的解决方法，只能说是分享一下我的体会。

对于做事，方法比技能重要。我一直和新人强调的一点就是，技术能力很重要，但更重要的是能把一件事情做完整，做好，不留尾巴。可以理解为“结果导向”，对于这点的认识是新人最缺乏的一点。其实和我们所受的应试教育有很大关系。我自己的体会是，如果这点能想明白，那人的成长就会有质变。手下人做事方式的好坏直接影响到管人的难度。

对于管人，要调整好心态。团队里有新人和老人，不同人有不同人的特点。我们作为IT公司，大部分开发人员都是理工科学生出身，这种环境已经相对单纯了。在管理这样团队时，只要你能把握公平公正的原则，多给别人机会，并且在做事方式上多加引导和教育，就不会出太大问题。很重要的一点就是，当你管人的时候，必须明白，你是在带领大家做事，不是和大家搞关系。团队成员的表现不可能都能让你满意，所以该说的时候还是要说，不能因为担心别人对你有看法，就隐瞒自己的不满，这样只会让事情更难做好。乔布斯说过：一流人才的自尊心不需要你来照顾。当然，我们的团队成员肯定比不上乔帮主的，但他说的意思我觉得很有道理。只有把事情做好，团队才有希望。

其实很多事情都是说起来容易，实践起来困难。所以对自己的反思很重要，有时候一些想法可能比较肤浅，但是如果每天都能想想自己今天有什么事情可以改进，长期积累，也会有可观的进步。

以后有什么体会，我们可以再交流。
