#+title: 风险投资

摘自《浪潮之巅》

任何一个公司的创办都离不开资金。传统上创业资金的合法来源只有两种渠道：一种是靠积累（比如继承遗产或者是自己多年的积蓄），第二种是靠借贷（比如从家人、亲戚和朋友那里凑钱，或者从银行抵押贷款）。如果要求创业者将自己一辈子的积蓄全部拿出来创业，很多人可能会知难而退，更何况最喜欢创业的年轻人恰恰是积蓄最少的群体。从银行贷款必须要有财产可抵押，对于有房子的人来讲最值钱的就是房子，但是房子一旦抵押出去很可能赎不回来，自己便无家可归了，而且不是人人都有房子可抵押。因此，年轻人要通过这两种传统的方法获得创业资金很不容易。这样，资金就成了创业的瓶颈。在很多国家，包括几乎整个欧洲，很少能看到新的公司兴起，原因就是没有人愿意提供创业的资金。

美国是一个富于冒险精神的年轻的国度。二战后，尤其是六十年代后，一些愿意以高风险换取高回报的投资 人 发明了 一种非常规的投资方式- -风险投资（VentureCapital Investment，or VC），在中国又简称风投。风险投资和以往需要有抵押的贷款有本质上的不同之处。风险投资不需要抵押，也不需要偿还。如果投资成功，风投资本家将获得几倍、几十倍甚至上百倍的回报，如果不成功，钱就打水漂了。对创业者来讲，使用风险投资创业即使失败，也不会背上债务。这样就使得年轻人创业成为可能。几十年来，这种投资方式总的来讲非常成功，硅谷在创造科技公司神话的同时，也创造出另一种神话--投资的神话。对私有企业的投资大致有两种，一种是收买长期盈利看好但暂时遇到困难的企业，比如投资大师巴菲特经常做的就是这件事，他很成功的案例是在美国大保险公司Geico（原名政府雇员保险公司，Government Employee Insurance Company）快要破产时，百分之百地以超低价收购了该公司，并将其扭亏为盈，从而获得了几十倍的收益；另一种是投资到一个新的小技术公司中，将它做大上市或者被其它公司收购。后者就是风险投资的对象。

和抵押贷款不同，风险投资是无抵押的，一旦投资失败就血本全无。因此，风投资本家必须有办法确认接受投资的人是老老实实用这笔钱创业的实业家，而不是卷了钱就跑了的骗子（事实上，风险投资钱被骗的事件还时有发生）。第二次世界大战后，经过罗斯福和杜鲁门两任总统的努力，美国建立起了完善的社会保险制度（SocialSecuritySystem）和信用制度（Credit System），使得美国整个社会都建立在信用（Credit）这一基础之上。每个人（和每个公司）都有一个信用记录，通过其社会保险号可以查到。美国社会对一个人最初的假定都是清白和诚实的（Innocent and Honest），但是只要发现某个人有一次不诚实的行为，这个人的信用就完蛋了--再不会有任何银行借给他钱，而他的话也永远不能成为法庭上的证据。也就是说，一个人在诚信上犯了错误，改了也不是好人。全美国有了这样的信用基础，银行就敢把钱在没有抵押的情况下借出去，投资人也敢把钱交给一无所有的创业者去创业。不仅如此，只要创业者是真正的人才，严格按合同去执行，尽了最大努力，即使失败了，风投公司以后还会愿意给他投资。美国人不怕失败，也宽容失败者。大家普遍相信失败是成功之母，这一点在世界其它国家很难做到（当然，如果创业者是以创业为名骗取投资，他今后的路便全被堵死了）。美国工业化时间长，商业发达，和商业有关的法律健全，也容易保护风险投资。

高回报的投资一定伴随着高风险，但反过来高风险常常并不能带来高回报。任何一种长期赚大钱的金融投资必须有它内在的动力做保证。股票长期来讲总是呈上涨趋势，因为全世界经济在发展。风险投资也是一样，它内在的推动力就是科技的不断发展进步。由于新的行业会不断取代老的行业在世界经济中的地位，专门投资新兴行业和技术的风险投资从长期来讲回报必定高于股市。因此风险投资看上去风险大，但是并不是赌博，它和私募基金都是至今为止收益最高的投资方式（回报率分别在15%和20%上下）。正是鉴于它的高回报，不断有人和单位（Institute）愿意将越来越多的钱放到风险投资基金中去，比如斯坦福大学将其退休基金的很大一部分放到在风投公司KPCB去投资。近三十年来，风投基金越滚越大，从早期的一年几万美元，到2006年的每季度六七十亿美元。由于风投公司不公开财务报告，很难准确了解美国风投的准确规模，但是普遍估计2007年的美国的风投基金规模大约是二三百亿美元。现在，美国自己已经消化不了全部的风投资本了，因此这些年美国大的风投公司也开始在海外投资，其中相当大一部分投在了中国和印度（欧洲的风投至今仍然很少）。

从财务和税务上讲，风险投资和传统的私募基金（以下简称私募基金）类似，但是它们的投资对象和方式完全不同。私募的投资对象大多数是拥有大量不动产和很强的现金流（Cash Flow）的传统上市企业，这些企业所在的市场被看好，但是这些企业因为管理问题，不能盈利。私募基金收购这些企业，首先让它下市，然后采用换管理层、大量裁员、出售不动产等方式，几年内将它扭亏为盈。这时或者让它再上市，比如高盛收购汉堡王（BurgerKing）后再次上市；或者将它出售，比如Hellman & Friedman基金收购双击广告公司Double Click，重组后卖给Google。运作私募基金要求能够准确估价一个问题重重的公司、具有高超的谈判技巧和资金运作本领，但是最关键的是要能摆平劳工问题，其中最重要的是蓝领的工人和工会（因为私募基金一旦收购一个公司，第一件事就是卖掉不良资产和大规模裁员）。从这个角度上讲，私募基金是在和魔鬼打交道，但他们是更厉害的魔鬼。风险投资则相反，他们是和世界上最聪明的人打交道，同时他们又是更聪明的人。风险投资的关键是能够准确评估一项技术，并预见未来科技的发展趋势。所以有人讲，风险投资是世界上最好的行业。

-----

要了解风投首先要了解它的结构和运作方式，然后了解风投的结构和决策过程。

风险投资基金（Venture Capital Funds）主要有两个来源：机构（Institutes）和非常有钱的个人。比如哈佛大学和斯坦福大学的基金会就属于前者。当然，为了让投资者放心，风险投资公司自己也会拿出些钱一起投资。

风险投资基金一般是由风险投资公司出面，邀集包括自己在内的不超过499位投资者（和投资法人），组成一个有限责任公司（Limited Liability Company，LLC）。为了避税，在美国融资的基金一般注册在特拉华州，在世界上其它地区融资的基金注册在开曼群岛（Cayman Islands）或者是巴哈马(Bahamas)等无企业税的国家和地区（如果读者创业时遇到一个注册在加州或纽约的美国基金，那一定是遇到骗子了）。为什么不能超过499人呢？因为根据美国法律规定，一旦一个公司的股东超过五百人，就必须像上市公司那样公布自己的财务情况和经营情况。而风险投资公司不希望外界了解自己投资的去处和资金的运作，以及在所投资公司所占的股份等细节，一般选择不公开财务和经营情况，因此股东不能超过五百人。每一轮基金融资开始时，风投公司要到特拉华等地注册相应的有限责任公司，在注册文件中必须说好最高的融资金额、投资的去处和目的。风险投资公司会定一个最低投资额，作为每个投资人参与这一期投资的条件。比如红杉风投一期融资常常超过十亿美元，它会要求每个投资人至少投入两百万美元。显然，这只有机构和非常富有的个人才能拿得出。

风险投资公司每一次融资便成立一个有限责任公司，它的寿命从资金到位开始（Close Fund）到所有投资项目要么收回投资、要么关门结束，通常需要十年时间，前几年是投入，后几年是收回投资。一个风险投资公司通常定期融资，成立一期期的风险基金。基金为全体投资人共同拥有。风险投资公司自己扮演一个称作总合伙人的角色（General Partner），其它投资者称为有限合伙人（Limited Partner）。总合伙人除了拿出一定资金外，同时管理这一轮风险基金。有限合伙人参与分享投资回报但是不参加基金的决策和管理。这种所有权和管理权的分离，能保证总投资人能够独立地、不受外界干扰地进行投资。为了监督总投资人的商业操作和财务，风投基金要雇一个独立的财务审计顾问和总律师（Attorney in General），这两个人（或者公司）不参与决策。风险投资比炒股要凶险得多，一旦出错，基本上是血本无归。为了减少和避免错误的决策，同时替有限合伙人监督总投资人的投资和资本运作，一个风投基金需要有一个董事会（Board of Directors）或者顾问委员会(Board of Advisors)。这些董事和顾问们要么是商业界和科技界的精英，要么是其它风险投资公司的投资人。他们会参与每次投资的决策，但是决定由总投资人来做。

风险投资基金的总合伙人的法人代表和基金经理们一般都是非常懂技术的人，很多人是技术精英出身，很多人自己还成功创办过科技公司。比如被称为世界风投之王的约翰多尔（JohnDoerr）原来是英特尔公司的工程师。中国最大最好的两个风投公司北光（Northern Light）和赛伯乐（Cybernaut）的创始人以前都是非常成功的企业家。比如创办北极光创投的邓峰和柯岩博士，原来是世界上最大的网络防火墙公司Netscreen的创始人，同时是网络安全的专家。赛伯乐的创始人朱敏博士是世界上最大的电话电视会议技术和服务公司Webex的创始人。为了确保对最先进技术的了解，风险投资公司会招很多技术精英，同时还会请外面的技术顾问，比如斯坦福大学的教授，一起来帮助评估每一项投资。

风险投资基金一旦进入被投的公司后，就变成了该公司的股份。如果该公司关门了，相对于公司创始人和一般员工，风投基金可以优先把公司财产变卖后的钱拿回去。但是，这时能拿回的钱通常比零多不了多少。如果投资的公司上市或者被收购，那么合伙人或者直接以现金的方式回收投资，或者获得可流通的股票。这两种方式各有利弊，都有可能被采用。前者一般针对较小的基金和较少的投资，总合伙人会在被投资的公司上市或者被收购后的某一个时间（一般是在解禁期Lock Period以后）将该基金所拥有的全部股票卖掉，将收入分给各个合伙人。这样基金管理的成本较低。但是，如果基金占得股份较大，比如风险投资在很多半导体公司中常常占到股份的一半以上，这种做法就行不通了。因为上市后统统卖掉其拥有的股票，该公司的股价会一落千丈。这时，风险投资的总合伙人必须将股票直接付给每个合伙人，由每个合伙人自己定夺如何出售股票。这么一来，就避免了股票被同时抛售的可能性。

为了降低风险，一轮风投基金必须要投十几家到几十家公司。当然，为了投十家公司，基金经理可能需要考察几百家公司，这笔运作的费用不是个小数，必须由有限合伙人出，一般占整个基金的2%。风投公司总合伙人为了挣钱，还要从有限合伙人赚到的钱中提取一部分利润，一般是基本利润（比如8%）以上部分的20%。比如某个风投基金平均每年赚了20%的利润，总合伙人将提取（20%-8%）×20%=2.4%，外加2%的管理费共4.4%，而有限合伙人得到的回报其实只有15.6%，只相当于总回报的四分之三。因此，风投公司的收费其实是非常高昂的。

-----

大的风险投资公司每一轮融资的资金都很多，比如红杉风投一轮基金动辄十几亿美元，如果每家公司只投资一两百万美元，一来没有这么多公司可供投资，二来即使有，总合伙人要在几年里审查几千几万家公司，也是明显不现实的，因此它们每一笔投资不能太小；而另一方面，新成立的公司本身都很小，尤其是初期，它们只需要融资几十万甚至几万美元就可以了，大风险投资公司就不会参与。对于这些公司的投资就由一类特殊的风险投资商--天使投资人来完成。天使投资（AngelInvestment）本质上是早期风险投资。天使投资人，简称天使，常常是这样一些有钱人：他们很多人以前成功地创办了公司，对技术很敏锐，又不愿意再辛辛苦苦创业了，希望出钱让别人干。在硅谷这样的人很多，他们的想法就是"不愿意当总（经理），只肯当董（事）"。

一些天使投资人独立寻找项目，进行投资，但是更多的情况是几个人凑到一起组成一个小的有限责任公司LLC或者有限伙伴关系（LimitedPartnership，简称LP），通常称作天使投资社Angel Firm来共同投资。天使投资社的经营管理方法千差万别，有的是大家把钱凑在一起，共同投资；有的是每个人自己选项目各自投资，同时介绍给社里，社里会加倍投入（Match）该天使投资人所投金额。当然，有些天使投资社管理更灵活，当某个天使投资人投资一个公司后，其他合伙人可以选择跟进（Follow），也可以不跟进（Pass），没有什么义务，大家坐到一起只是为了讨论一下问题而已，共同使用一个律师和会计。


-----

我遇到了许多创业者，他们在接触投资人时几乎毫无融资的经验，有些漫天要价，有些把自己贬得一钱不值。我们从这个例子中可以看到，风险投资必须是渐进的，在每一个阶段需要多少钱投入多少钱，这样对投资者和创业者都有好处。对投资者来讲，没有任何一家投资商会在刚开始时就把今后五年的开销全包了的，这样风险太大。对创业者来讲，早期的公司股价都不会高，过早大量融资会使得自己的股权占得太低，自己不但在经济上不划算，而且还会失去对公司的控制，甚至在创业的一半就被投资人赶走。

上面的情况是一个简化得不能再简化的投资过程，任何一个成功的投资都会比它复杂得多。比如，通常天使投资人可能是几家而不是一家，很多人都会要求坐到董事会里去，这样在真正风险投资公司投资时，董事会已经变得很庞大。在这种情况下，风投公司通常会以当时合理的股价（FairMarketValue）从天使投资人手中买回股权，并把他们统统从董事会中请 出去。否则每次开董事会坐着一屋子大大小小的股东，大家七嘴八舌，还怎么讨论问题。大部分天使投资人也愿意兑现他们的投资收益，以降低自己的投资风险。

上面这个例子是一个非常理想的情况，该公司的发展一帆风顺，每一轮估价都比前一轮高，实际情况可能并非如此。不少公司在某一轮风险投资资金用完的时候，业绩上并没有太大的起色，下一轮融资时估价还会下降。我的一个朋友曾经在这样一家半导体公司工作，他们花掉了近亿美元的投资仍然不能使公司盈利，这样必须继续融资，新的风投公司给的估价只有前一次估价的三十分之一，但是创始人和以前的投资人不得不接受这个估价，以避免公司关门，那样他们的投资一分钱也拿不回来。

-----

我们从上面的例子可以看出，风投常常是分阶段的，可以有天使投资阶段、第一轮和后一轮（或者后几轮）。天使投资阶段的不确定性最大，甚至无章可循，很多成功天使投资回想起来都不知道是如何成功的，包括开始投资Google的一些天使投资人都搞不清楚Google是干什么的。我的一位朋友是世界上该领域最大的公司的创始人之一，该公司先在纳斯达克上市，后来又以几十亿美元的高价卖掉。这位共同创始人对我讲，他们创业的第一笔钱，是从一个台湾的天使投资人那里拿到的五十万美元。这个投资人根本就不是IT领域的人，也搞不懂他们要干什么，最后请了一位相面先生给他们三个人看了看相，这三个人身材高大，面相也不错，于是那位投资人就投资了。当该公司以几十亿美元的高价被收购时，这位天使投资人也许应该感谢那位相面先生，为她带来了上百倍的投资收益。

正是因为这种不确定性，很多大的风险投资公司都跳过这一轮。一些更加保守的风投基金只参加最后一轮的投资。有些清清楚楚地说明在下面几种情况下不投资：
   1. 不盈利的不投
   2. 增长不稳定的不投
   3. 公司达不到一定规模的不投
甚至有些风投基金只投已经有了十二到二十四个月内上市计划的公司。当然，到了这一步，常常是融资的公司挑选风投了，能在这一步拿到合同的风投要么是在IT界关系很广的公司，要么是很有名的公司，以至于新兴公司上市时要借助它们的名头。通常，当股民们看到某家将要上市的公司是KPCB或者红杉风投投资的，他们会积极认购该公司上市发行（IPO）的股票。

要做到高回报必须首先选对题目。一个好的创业题目最要紧的是具有新颖性，通常是别人没想到的，而不是别人已经做成功的。很多创业者喜欢模仿，虽然这样也有成功的可能，却不可能为风投挣到几十上百倍的投资回报。比如中国九十年代出现了很多做DVD机的厂家，早期的几家挣到了钱，后面的几百家都没挣到什么钱；其次，创业的题目不能和主流公司的主要业务撞车。九十年代时，风投公司对软件公司的创业者问的第一个问题是"你要做的事情，微软有没有可能做？"这是一个无法回答的问题。如果回答"可能"，那么风投基金的总合伙人接下来就会说"既然微软会做，你们就不必做了。"如果回答是"不会"，那么总合伙人又会说"既然微软不做，看来没必要做，你们做它干什么？"2000年后，风投公司还是对软件和互联网的创业者问这个问题，只是微软变成了Google。这个例子说明，如果创业的项目和微软和Google这样的公司的业务有可能撞车，那么失败的可能性极大。

风投公司一旦确定什么生意、什么公司可以投资，接下来的问题就是如何估价一家投资对象了。和投资股市不同，风险投资的对象大多没有利润甚至没有营业额可言，其估价不能按照传统的市盈率（P/E值）或者折扣现金流（Discounted Cash Flow）来衡量，关键是看今后几年该公司发展的前景以及看到目前为止该公司发展到哪一步了。和投资股市另一个不同之处，新创公司因为没有什么业绩可以衡量，创始人和早期员工的素质就变得很关键。

对风险投资家来讲，最理想的情况是能当一个甩手掌柜：把钱投到一家公司，不闻不问，几年后几十倍的利润拿回来。这种情况对于天使投资确实发生过，比如有一个从洛杉矶募集资金的天使投资团将钱投入了早期的Google，等Google上市时，该投资团的合伙人，包括NBA明星奥尼尔、加州州长施瓦辛格和一些好莱坞明星，稀里糊涂地就挣到了一大笔钱。对于比较大的风险投资，反而很少发生。大多数办公司的人的经验总有局限性，尤其是IT行业的创始人大多是技术出身，没有商业经验和"门路"（在美国，门路和在中国一样重要）。风投公司就必须帮助那些创始人把自己投资的公司办好。毕竟，他们已经在一条船上了。风投公司介入一个新兴公司后的第一个角色就是做顾问。这个顾问不仅需要在大方向比如商业上给予建议，而且还要在很多小的方面帮助创始人少走弯路。我在前一章"硅谷的另一面"中提到，创办一个小公司会遇到形形色色的问题，而创始人常常缺乏处理这些问题的经验，这时风投公司（坐在被投公司董事会席上的那个人）就必须帮忙了。

当然，风投不可能替公司管理日常事务。这就有必要替公司找一个职业经理人来做CEO （当然，如果风投公司觉得某个创始人有希望成为CEO，一般会同意创始人兼CEO的职位）。 每个风投基金投资的公司都有十几到几十家，要找到几十个CEO也并非容易的事。因此，有影响的老牌风投公司实际上手里总攥着一把CEO候选人。这些人要么是有经验的职业经理人，要么是该风投公司以前投资过的公司的创始人和执行官。风险投资家给有能力的创始人投资的一个重要原因就是锁定和他的长期关系。如果后者创业成功固然好，万一失败了，风投资本家在合适的时候会把他派到自己投资的公司来替自己掌管该公司日常事务。一个风投公司要想成功，光有钱，有眼光还很不够，还要储备许多能代表自己出去管理公司的人才。 这也是著名风险投资公司比小投资公司容易成功的原因之一，前者手中攥着更多更好的管理人才。

风投公司首先会帮助被投资的公司开展业务。自己开公司的人都知道，一个默默无闻的小公司向大客户推销产品时，可能摸不对门路。这时，"联系"广泛的风投公司会帮自己投资的小公司牵线搭桥。越是大的风险投资公司越容易做到这一点。风投公司还会为小公司请来非常成功的销售人才，这些人靠无名小公司创始人的面子是请不来的。风投广泛的关系网对小公司更大的帮助是，它们还会帮助小公司找到买主（下家）。这对于那些不可能上市的公司尤其重要。风投行业经过几十年的发展，就形成了一种马太效应。越是成功的风投公司，投资成功上市的越多，它们以后投资的公司相对越容易上市、再不济也容易被收购。因此，大多数想去小公司发财的人，选择公司很重要的一个原则就是看它幕后的风投公司的知名度。

风投是新兴公司的朋友和帮手，因为它们和创始人的基本利益是一致的。但是通常也有利益冲突的时候。任何一个公司的创办都不是一帆风顺的，当一个被投公司可能前景不妙时，如果投资者对它是控股的，可能会选择马上关闭该公司或者贱卖掉，以免血本无归。这样，创始人就白忙了一场，因此创始人一定会倾向于继续挺下去，这时就看谁控制的股权，更准确的讲是投票权（Voting Power）多了。当一家公司开始盈利有了起色时，风投会倾向于马上上市收回投资，而一些创始人则希望将公司做得更大后再上市。投资人和创始人闹得不欢而散的例子也时常发生，投资人甚至会威胁赶走创始人。

创业者和投资者的关系对于成功的创业至关重要。首先，创始人总是在前台扮演着主角，风投在幕后是辅助者。如果投资者站到了前台，要么说明创始人太无能，要么说明投资人手伸的太长，不管是哪一种情况，公司都办不好；其次，创业者和投资者的关系是长期的，甚至是一辈子的。对投资者来讲，投资的另一个目的是发现并招揽人才。对投资人来讲，创业者能一次成功当然是最好的，但是，非常有能力能干事的创始人也会因为时运不济而失败，这时投资者如果认定创始人是个人才，将来还会为他的其它项目投资，或者将他派到新的公司去掌舵。因此，对创业者来讲，虽然风险投资的钱不需要偿还，但是，拿了投资者的钱就必须使出吃奶的力气尽力将公司做好，以获得投资者的青睐。一些短视的创业者把风投公司当作一次性免费提款机，只拿钱而不承担应尽的义务，实际上便永远地断了自己的后路。和很多行业不同，不同风险公司的投资家们一般会经常通消息，一个人一旦在风投圈子里失去了信用，基本上一辈子就失去了获得风投资金再创业的可能。
