#+title: Vinod Khosla: Failure does not matter. Success matters.

[[https://www.youtube.com/watch?v=HZcXup7p5-8][youtube]] 挺喜欢这个老爷子的发音，虽然也是印度口音，但是不至于满是咖喱味。

The funny thing is, with enough persistence, most things seem impossible become possible.

The point is, if you actually believe something, you try your best to make it happen. It does not always happen, but it happens most of time.

Failure does not matter, it's success that matters. And nobody remembers what you failed at.

Try and fail, and don't fail to try.

Only those who fail greatly can succeed greatly.

没有人可以预测未来，即便是来自麦肯锡的那些专家们做的关于十几年的未来预测的准确度，和猴子扔飞镖差不多。所以与其听那些专家的预测，不如亲身参与到可能改变未来的行动中。

这个老爷爷绝对是时间管理方面的高手，把时间按照15min分为一个slot, 任何事情都按照优先级做排序，绝对不会浪费时间(=I highly recommend you come up with your own priorities and measure them=)。而且他坚信work-life balance是可行的，只要你能够足够自律。为了能有更多的时间陪孩子，推掉了许多工作和应酬时间，因为他坚信family is the most important, 所以family thing priority is the highest.

另外老爷子还强烈推荐 [[https://book.douban.com/subject/25782902/][反脆弱]] 这本书，他承认自己的许多哲学观点都源自于这本书上。
