#+title: VP Engineering vs. CTO

http://avc.com/2011/10/vp-engineering-vs-cto/

- Like VP Finance & CFO, the differences in the two positions are not just about seniority. In fact, in the case of CTO and VP Eng, seniority is often a non-factor. They are often peers. A VP Eng can report to a CTO. And a CTO can report to a VP Eng (although this last one is less frequent). # 和职位高低无关. 但是通常VP Eng.向CTO汇报
- A VP Engineering is ideally a great manager and a great team builder. He or she will be an excellent recruiter, a great communicator, and a great issue resolver. The VP Eng's job is to make everyone in the engineering organization successful and he or she needs to fix the issues that are getting in the way of success. # VP Eng.主要组织技术团队
- A CTO is ideally the strongest technologist in the organization. He or she will be an architect, a thinker, a researcher, a tester and a tinkerer. The CTO is often the technical co-founder if there is one (and you know I think there must be one). # CTO则是规划未来的技术方向
- The CTO makes sure the technical approach is correct and the VP Engineering makes sure the team is correct. They are yin and yang. # CTO确保技术对路而VP Eng.确保团队靠谱.
- Startup companies in their earliest stages will have neither position. The ideal web/mobile startup will have a CEO/founder who will also wear the VP Product hat. It will have a technical co-founder who will wear both the CTO and VP Eng hats. And it will have a few more engineers. And maybe a community manager. # 早期CEO同时负责VP Prod, 而CTO同时负责VP Eng. 部分工程师和社区经理.
- It is very rare to find a person who can do both the VP Eng and CTO jobs at the same time. They require very different skills and very different time allocations. I've seen it work a few times, but it is the exception that proves the rule in my mind. # 同时担任两个角色还是非常需要技巧的.
