#+title: 晚明 - 檄文

作者：小小峰
链接：https://www.zhihu.com/question/37159763/answer/142852125
来源：知乎
著作权归作者所有。商业转载请联系作者获得授权，非商业转载请注明出处。

建州奴儿哈赤者，我大明养奴之遗种也。初依辽帅李成梁为鞍下马弁，摇尾乞怜如穷状求食之獒犬;叩头捣蒜哀容比偷生之虱虮。终怜其遗孑孤苦之丧家，得赐一东隅，与彼依边糊口之地，锡替无涯，春给炊种，冬予暖叚，盖圣光普照之无余。奴不思汉民养育之恩，反暗怀狼子野心，乃乘援朝之半隙，盗甲欺边。于今亦二十有年矣！

今奴酋黄台吉者，天殛老奴之完卵耳。乘甲扬兵，寇关入犯，不思先人叠荷大明之恩重，反觊中原世累生聚之财丰，未知一已穷兵寡义之窘德，竟窥赤县圣嗣无疆之神鼎，滋徒抢掠，如蝗过境，堕城毁垒，万姓流离，举火焚天，涂炭生灵。

是欺我神州扳荡之际，荷戈无人耶？今有登州镇总兵陈新，既亲睹塞上妖氛之披猖，遑可按肘下龙泉之激扬？虽非世胄，一身惟华夏之赤胆；更受君恩，两肋披齐鲁之忠肝。连营义勇，三军皆决死之虎贲；英旗烈猎，万里尽摧敌之铁流。双亲在后，已备捐躯之棺椁；儿郎敢前，誓效卫国之忠魂。三餐无肉，可啖建奴之筋血；怒气冲霄，必捣鞑虏之旧巢。

排帆遮海，驾鱼龙其击角亢；联旌蔽日，绝雪域而卷白山。蛮夷猾夏，虽五刑而未尽辜；奉辞罚罪，总四岳以撼北冥。天其申命，肆雄师以麾紫电；运数匪躬，逞跳梁而戮青锋。

今檄传天下，关山处处，草莽俱敌寇之野茔；鼓动九边，江海涛涛，尺浪亦中国之长城。东起沧海，西至榆关，凡尔军民将吏、士农商贾，见此檄如闻吾之军令，杀鞑官、烧鞑仓、刺鞑情、绝鞑交。王师艨艟巨艘不日东指，汝作怒潮，军民一心，席卷东奴。吾之十万虎贲为汝前锋后盾，汝其无畏，一乃心力。

尔其儆听吾命，其克有勋。倘有一意孤行，阴持逆命者，吾必加以显戮，用彰大汉同仇之义，尔其慎之勿犯。

东虏贫民士庶，牛录章京以下，有畏威怀德者，弃兵可以免死，提牛录以上奴官首级来降者，保其身家财物，另赐田地官职，倘不知天命，一意跳梁，吾十万锋镝正专为汝辈而设，引颈一试可也。

神州光武，奄有百代，英雄踵继，是成汗青。今日之英雄者，登州镇万千将士是也。

----------

《出军歌》

#+BEGIN_QUOTE
黄沙莽莽不见人，但闻战斗声，
枪林弹雨天地惊，壮哉我军人，
嘘气乾坤暗，叱诧鬼神惊！
拼将一倨英雄泪，洒向沙场见血痕。
鼓勇前进！可谓草木皆兵！
一夫当关万夫雄，为国增光荣！
牺牲此躯壳，为吾国干城；
人生万古皆有死，何如做征魂！
身死名犹列，骨朽血犹馨！
何惧弹如雨，浩气压征尘。
#+END_QUOTE

晚明中改了2个字，把2个“弹”改成了“箭”，更切合时代

#+BEGIN_QUOTE
黄沙莽莽不见人，但闻战斗声，
枪林箭雨天地惊，壮哉我军人，
嘘气乾坤暗，叱诧鬼神惊！
拼将一倨英雄泪，洒向沙场见血痕。
牺牲此躯壳，为吾国干城；
人生万古皆有死，何如做征魂！
身死名犹列，骨朽血犹馨！
何惧箭如雨，浩气压征尘。
#+END_QUOTE
