#+title: 为什么需要更多 8 位单片机?

https://www.eejournal.com/article/what-more-8-bit-microcontrollers/

我看的是一个中文翻译版本。

本科的时候接触过8位单片机，当时实在是不知道能用这个东西来做什么，觉得就是一个微缩版的PC：什么地方需要这个单片机的话，直接上一个微缩/阉割的PC就好了，为什么还需要这个东西的存在呢？还要使用专门的汇编语言进行编写，大部分都是功能开发，没有任何性能上的挑战。

年纪大一些之后，才慢慢理解有时候对于这个世界理解还不够：当自己要急于反驳某个事物的时候，不如好好学习学习这个事物的现状和背景，通常能解决自己许多疑惑和错误。

我只是看了看8位单片机的背景和使用场景，里面许多具体知识没有看。在我看来，8位单片机的优势就是成本和功能完备性。

#+BEGIN_QUOTE
微处理器(μP)也称为微处理器单元(MPU)。早期的MPU仅包含一个中央处理单元(CPU)。随着时间的推移，添加了其他功能，如高速缓存、浮点运算单元(FPU)以及存储管理单元(MMU)等。关键是:除了任何高速缓存以及FPU和MMU之类的东西，微处理器不包含任何内部存储器或外设。相比之下，单片机(μC)，也称为微控制器单元(MCU)，包含闪存等非易失性存储器，SRAM等易失性存储器，计数器、定时器、模数转换器(ADC)等外设以及UART、I2C和SPI等通信接口。从本质上讲，单片机是一种小型独立计算机，存在于包含自己的程序的单个硅芯片上。它一上电，程序就开始执行。这就解释了为什么单片机出现在嵌入式系统中，以及为什么嵌入式系统随处可见。

除了传统的单芯片系统(即MicrochipMCU是板上唯一的处理器)外，8位处理器作为系统管理IC和协处理器的作用也越来越大，尺寸、空间、低功耗和寿命等方方面面的特征都很重要。这在很大程度上是因为我们看到分布式智能在物联网边缘节点、汽车安全、工业控制系统、医疗电子和家用电子等应用领域的急剧增长。即使是最先进的5G系统，通常也可以从将某些任务分配给更小的8位处理器中受益，从而释放更高级处理器来发挥它们的魔力并做它们最擅长的事情。

Greg说:“尽管听起来很奇怪，很多8位的增长是由32位的增长推动的，其中32位处理器正在将人机界面(HMI)功能和内务管理任务等传递给8位处理器。此外，8位器件越来越多地用作协处理器，执行诸如获取传感器读数和预处理此传感器数据等任务，然后将其传递给更高级处理器。”
#+END_QUOTE
