#+title: What Every Engineer and Computer Scientist Should Know: The Biggest Contributor to Happiness

https://cacm.acm.org/opinion/articles/256926-what-every-engineer-and-computer-scientist-should-know/fulltext

每个工程师和计算机科学家都应该知道的事情：什么对于获得幸福感至关重要。保持良好的人际关系，是获得幸福感的关键要素。工程师和计算机科学家习惯去解决问题，不过有时候我们甚至不需要去解决具体问题，就可以保持良好的人际关系。我们只需要在实践中做到下面几点就行。

几乎没有人在临时的时候抱怨说，自己没有发明什么什么东西，或者是没有获得什么什么奖项，反倒是觉得自己亏待了家人，或者是希望对其他人好点。这个发现并不只是针对某个特定人群的，穷人富人，受教育或者是没有受教育的，几乎都是这样。

#+BEGIN_QUOTE
Researchers have studied what brings happiness in life, and what, at the end of life, people wish they had done. While many factors contribute, do you know the biggest one?

Almost never late in life do people say: "I wish I had invented a smarter or faster device," "I wish I had made more money," "I wish I had given more TED talks," "I wish I had climbed higher in my business," or "I wish I had authored more books." Even this pinnacle of achievement is not uttered: "I wish I had written an article for an ACM magazine." Instead, almost always, people wish that they had done a better job at building meaningful authentic human relationships, and spending time in those relationships.
This finding is a general one, whether studying human happiness or end-of-life reflections. They apply to hard-working, well-educated computer scientists or engineers and also to many kinds of people, different races and cultures, rich and poor, male and female, uneducated or over-educated.
#+END_QUOTE

下面是保持良好人际关系的几个原则：

1 反馈对于学习和改进非常重要。

#+BEGIN_QUOTE
Principle #1: Feedback is essential to learning and improving. A machine learning algorithm can improve its performance if you give it accurate feedback such as +1 "correct" or -1 "wrong," or other corrective labels or procedural guidance; similarly, your relationship skills get better when you seek and incorporate feedback. Here are two examples how to do this, and you can invent variations:
#+END_QUOTE

2 交谈中可能会存在错误信息，你需要有技巧性的识别出来。（通常交流者意图是好的，或者我们可以假设是好的，如果存在错误，可能是他们没有表达清楚。不要全盘否定，试图引导出来）可以尝试复述他的话，并且确定其中的关键。直接说"I understand you"甚至会有负面效果。

#+BEGIN_QUOTE
Principle #2: Conversations contain errors that need to be detected and processed intelligently. The speaker may not accurately encode their meaning into words, or you may hear their words inaccurately, or you may hear accurately, but perceive them differently than the speaker intended. Other kinds of errors can happen too. Here is a two-step way to fix errors, and you may develop others:

Note that you could say back to them exactly what they said, and they might still say you got it wrong. "How is that rational?" you might ask. It is rational because, by hearing it reflected back from you, they may suddenly realize that what they said was not actually what they intended to communicate. The error may have been theirs, encoding their message unsuccessfully. In short, you can help engineer better communication and a better relationship by putting redundancy into the channel, and making observable to them what it is that you heard. The result is that the other person feels better understood.

Note that the shortcuts, "I understand you" or "I understand what you feel" are usually counterproductive. "I understand" does not communicate to them what you understand. It is essentially a time-wasting phrase. The communication is not complete until you tell them what it is that you understand. It can be especially productive to try to put into words what feeling it is that you think they are having, for example, "It sounds like you might be feeling frustrated …" and keep trying to get it right until they say "That's right." The process of showing you understand well enough to restate it in your own words makes for a stronger relationship, which moves you both closer to happiness.
#+END_QUOTE

人们需要被其他人所理解。所以我们不用总试图去想着解决问题，有时候只需要倾听就好。

#+BEGIN_QUOTE
An intriguing fact is that none of the principles described here involve saying anything clever, or coming up with good fixes to problems. Computer scientists and engineers are almost always trying to fix things and make them better. The method above actually does something more powerful: It gives the other person the gift of feeling understood. This gift often has the result of freeing up their cognitive-affective resources so that they can fix their own problem. Sometimes, showing understanding of feelings can make the relationship better than the cleverest "fix."
#+END_QUOTE

3 充满建设性的回复，并且这种回复可以产生更多的喜悦。下面各种回复其实有花不了多长时间，但是差异确实巨大的。

#+BEGIN_QUOTE
Principle #3: Active, constructive responses generate joy. Suppose you are really busy working on your own deadline, and your colleague interrupts with news he's super-happy about, "Hey, you know that proposal I worked on? It got selected to get complete funding!" Which of the following would be your likely response?

1. They selected your ideas? Don't you realize this is going to be so much extra work—maybe they are exploiting you?
2. "Oh? Really?" (Then look back at your screen, "Ugh, so much email.")
3. Congratulations!
4. Congratulations! What a nice recognition of your effort! (Perhaps you raise your hand to high-five.) How do you feel about that? (You listen and share smiles, celebrating the moment's joy.)
While none of these options takes more than a minute, which of them is likely to deepen and improve the relationship? Of all of the options, generally the strategy in (d) is best—it actively amplifies the moment's positive feelings into something even larger and greater, helping construct a better relationship. By speaking words (less than 10 seconds), you give them a gift of sharing and enlarging their joy.
#+END_QUOTE
