#+title: 大开眼界(What the Dog Saw: And Other Adventures)

大开眼界：用另一双眼睛看透这疯狂世界、奇妙生活和美丽人生（What the Dog Saw: And Other Adventures）

塔勒布也有不少迷信的忌讳，如果基金操作的情况不错，他就会每天选同样的位置停车。又如，他因为把马勒与去年市场长期低迷状况联想在一起，所以变得不喜欢马勒。施皮茨纳格尔说，塔勒布每次都说在公司里少不了我，我相信那是真心话。施皮茨纳格尔的存在是在提醒塔勒布，等待是有意义的，他是在帮助塔勒布抗拒人性的冲动，即宁愿放弃一切，也要消除损失的痛苦。

塔勒布说：“关键不在于有想法，而在于有实现想法的处方。我们谢绝说教，我们需要一套诀窍。”他的诀窍是事先讲好规则，而对于每种情况应该怎么处理都规定得一清二楚。我们定好这套规则，这么做是为了告诉大家不要听命于我，而要听从一定的规则。当然我有权利改变规则，可是改变规则也有一定的程序。从事这一行一定要严于律己，我们在尼德霍夫身上看到的偏见，在自己身上也看得到。

如此小心谨慎，自然看似非英雄所为，反倒像是会计人员和主日学校老师那样谨慎无趣的作风。其实我们会被尼德霍夫这种人所吸引，是由于我们内心也有相同的想法：认为愿意冒极大的风险，以及能够从惨败中东山再起，都代表勇敢。可是在这一点上我们错了。这是塔勒布和尼德霍夫带给我们的一课，也是这个多变的时代教给我们的教训。能够抗拒人类冲动的天性，采取刻意而痛苦的步骤，为无法想象的未来做准备，反而需要更多的勇气和英雄气概。

但是整体来说，她认为初潮晚，怀孕次数多，密集哺乳导致长期无月经，这种模式原本几乎是普遍现象，直到100年前“人口形态转变”，生育率由高转低，才有所改变。换而言之我们现在认为的正常，就是经常来月经，而从演化的角度来看反而是不正常的。斯特拉斯曼说：“很可惜，现今的妇科医生认为，女性应该每个月都有月经。这些人根本不了解真正的月经生物学。”

他们认为近年来这种转向“不停排卵”的变化，对妇女的健康构成严重的威胁。对大多数女性来说，不停排卵并无任何意义，只是突然增加腹痛，情绪起伏，偏头痛，子宫内膜异位，子宫肌瘤和贫血发生的概率。其中贫血属于世界上最严重的健康问题之一。更严重的是这会大大增加罹患某些癌症的风险，毕竟在细胞分裂和复制的过程中倘若出现错误，导致防御细胞增生的机制遭到破坏，便可能诱发癌症。这便是通常随着年龄增加，患癌风险会升高的一个原因：体内细胞有更多时间犯错。可是这也表示，任何会促进细胞分裂的改变，均有可能增加患癌的风险，而排卵似乎就属于这类变化。

国家安全顾问格雷戈里-特莱沃顿（Gregory Treverton)曾经说迷有两种，一种是只要再多点消息就能迎刃而解的拼图般的谜团(puzzle)，另一种是需要费劲心机抽丝剥茧才能拨开云雾见青天的迷雾(mystery)，两者有所区别。

华约解体后，特莱沃顿等人认为情报界如今面对的局面已经彻底反转。全球大部分地区是开放的，因此情报人员不再依赖其他间谍的零星情报，转而面对的是海量信息，解决谜团仍然无比重要：我们仍需要知道本拉登的下落，仍需要知道朝鲜的武器设施位置。但是解决迷雾的重大责任，逐渐走向舞台中央。东方与西方世界可以预期的稳定对立局面已经动摇，现在情报分析员的工作是，协助决策高层在失去的世界中找出正确航向。后冷战时期，一切信息都可以公开取得的阶段，你需要的是具有外语能力，对观察对象之宗教文化有深入了解的观察员。我们不需要那么多间谍，却需要许多稍许疯癫的情报解读人才。

“长尾理论"的解决方法对右派没有太多吸引力，因为它涉及到要对不值得受到特别照顾的人一群人给予照顾。它也对左派缺乏诱惑力，因为它强调效率多于公平，充满芝加哥学派冷冰冰的成本效益观点，即便可以解决游民问题，减少空气污染或改良警察纪律，这些崇高的目的都不能完全让社会大众心动。

可是在压力下，有时“显性学习”会接手，这便出现了紧张失常的状况。诺沃特那在温布尔登决赛中节节败退，是因为她再度开始思考自己的击球。她的流畅度与个人特色完全不见了，她发球出现双误，对于需要在力道与时机上作出高度敏锐反应的杀球，却挥拍失误。她好像成了另外一个人：击球时缓慢而谨慎，好像又成了一个初学者；发球，迎截杀球或高吊球的方式，回到她孩提时代初学网球时的练习招数。此时她依赖的是显性学习。

从这个例子来看，“惊慌失措”与“紧张失常”刚好相反。紧张失常是因为想太多，惊慌失措是因为未经思考。紧张市场跟失去本能有关，惊慌失措则会促使人回归本能，两者可能看似相同，但是有天壤之别。

在NASA，有问题是常态，“异常”这个词每天都被挂在嘴上，“偏离正常”可以控制但无法消除，整个航天飞机系统都是根据这个前提在运作。NASA制造出的是一种封闭的文化，在这种文化中常态化的偏离(normalized deviance)，对外界来说虽然有可争议之处，但对他们自己人来说，却是审慎而合理的。

类似“挑战者号”这样的灾难带给我们的教训是，我们构建了一个世界，在这个世界中，高科技的潜在灾难深深镶嵌在我们日常生活当中。在未来某一刻，因为某一最世俗平常的原因，在最好的用意下，NASA的航天飞机可能还会爆炸，我们至少应诚实承认这一点。如果我们做不到，如果这种可能性叫人无法承受，那么我们唯一的选择是：诸如航天飞机的一切，我们是否应全面弃而不用。

加兰森认为，天才如毕加索者，很少进行这样无止境的探索。他们一切都从观念出发，而且有清楚的念头知道自己要往哪里去，接着便是执行。有次接受艺术家马里厄斯-扎德亚斯采访：“表示我很难体会’探寻’这一词的重要性。在我看来，’探寻’对绘画来说一点意义都没有，’发现’才重要。我在绘画中采用的几种形式，绝不能视为是向某种未知的理想，我从未做过试验或实验。”

加兰森说，大器晚成的方法却刚好相反，他们比较喜欢采用实验法。他们的目标不明确，因此过程也是暂时与渐进的。因为目标不明确，这些艺术家很少感觉自己已经成功，结果他们的事业也受单一目标追求所影响。这些艺术家不断反复的画着同一主题，在“从错误中学习”的实验过程中，渐渐改变绘画的处理方式；每件作品都把他们带向下一件，没有一幅比其他作品特别。因此，学院派画家很少打预备的草稿或设计轮廓，而是将绘画创作视为一种搜寻过程，他们的目的是要在过程中发现作画的形象，并认为学习是比完成作品更为重要的目标。实验艺术家在事业发展之际也逐渐强化了他们自己的技巧，在漫长的过程中提升自己的作品水平。这些艺术家是完美主义者，他们都因为不能达到目标而感觉沮丧，这是他们的特质。

这也是方丹长期努力要博得文学界青睐过程中恼人的课题，在达到功成名就的漫漫长路上，晚成者有时就像一无所成的废人。大器晚成的人，虽然不断的在失望之余，撕毁或重新修改作品，不断改变自己的方向，但这些作品有时看起来真的称不上大家的手笔。天才的一切看起来都无比轻松，一开始就有人吹捧；大器晚成者则备尝辛酸，不但要坚韧，还要有盲目的信心（幸亏塞尚在高中阶段没有遇到这样一类辅导老师，在看了他的早期素描手稿之后，劝他不要自不量力，干脆改学会计算了）。每当我们发现一位大器晚成的人，我们走，不免要想，有多少人像他一样，却因为我们有眼不识泰山，而未给予该给的鼓励，污染人家的前程，当然我们也必须接受的事实是对他人的天赋我们可能是爱莫能助，我们怎么知道，一个人早年的失败是他晚年的成功之母呢？

麦肯锡要找的是会在体制外思考的人才，但他们从未想到，如果每个人都要在体制外思考，也许关于那个体制本身，也需要重新思考了。
