#+title: 中国人的焦虑从哪里来

在过去的人类社会中，有权有势的人可以凭权势剥夺别人所创造的财富，所以人们追求权势而不追求财富。可是权势具有排他性，皇帝只有一个，我当了你就不能当，所以纷争不断。而财富没有排他性，你能发财，我也能发财，所以大家都去争创财富。当特权受限制时，人们开始努力创造财富，而不是追求权势，这个社会的财富创造有了突飞猛进的发展。其结果是社会中最穷的人，境况也能有所改善。

地位的平等比财富的平等更重要，还有一层原因，就是金钱和权势的勾结。财富不平等的原因之一是依靠权势获得财富，而且这部分财富的不平等不利于社会财富的增加，它是掠夺性的。比如以权谋私，贪污腐化，它们造成财富的差别，但是没有财富的创造。在市场规则之下，财富的差别是和财富的创造相联系的。

现在看来，在发达国家里收入差距依然存在，但是地位的不平等基本已经消除。可见收入的不平等不容易纠正，而地位的不平等是可以纠正的。我们应该对收入差距保持宽容，对地位的不平等要努力消除。可惜我们似乎正在走一条相反的路。当前大家关注我国的贫富分化，成为全社会的焦点。但是大家对社会地位的不平等熟视无睹，任其存在，甚至还在发展。这种轻重失据的社会关注可能会严重误导我国的进一步改革开放。

分析到这儿，我们明白了，经济上的不平等是为了鼓励财富的生产，没有这点不平等，大家都想搭便车，社会将要越来越穷。要将财富分配给创造它的人，这样造成的不平等虽然不好，但又不得不如此。

这样分析下来，经济适用房根本不符合保障性住房的原则。可是为什么这样一个不靠谱的政策居然能够在全国大行其道？原因有二。 一是政府想讨好老百姓。政府自己又不创造财富，就是拿大家的钱帮助大家，乐得做顺水人情。百姓其实是受蒙骗的，以为得到了好处。这个好处是以其他更多的人受损为代价的。有时候经济适用房就是靠强制性向郊区农民低价征地造起来的。损害的是郊区农民的利益。许多拆迁冲突，上访闹事，就是因为建经适房而发生的。这时候受损的人明显可见。用损害农民的方法让城里人买便宜房显然是不合理的。也有些情况是用公有土地建经适房。表面上看没有人受损，实际上是全国人民受损，也毫无合理性可言。 二是政府官员自己有好处。分配经适房的权力在政府手里。分配经适房的官员可近水楼台先得月。事实上经适房很大一部分就分给了有权有势的政府官员。一般平民百姓能分到手的很少。是政府官员的私利驱动了经适房政策的通过和实施。要想取消它还真不容易。

更糟糕的是经适房创造了贪污腐败的机会。如果不是经济适用房的政策，这种腐败本来根本不会出现。为了一个完全不必要的政策，又创造出许多贪污腐败的机会，进一步败坏了社会风气。各地因经适房分配不公出的问题已经不计其数

这样看来，保障性住房应该就是廉租房或公租房等不涉及产权的政府建房，以低于市场价格的租金出租给贫困户。这类廉租房的建筑标准是比较低的，可能没有私人厕所，只有公用厕所（例如香港地区的做法）。这样能降低造价，为更多的贫困户提供帮助。

政府是不创造财富的，政府的资源就是全国人民的资源。拿全国人民的资源帮助穷人，大家不会有太大的意见。但是为什么拿全国人民的资源帮助中产阶级买房，就没有太多的理由了。政府有责任解决每个人的住房问题，但是没有责任满足每个人对房产的占有欲望。这是性质完全不同的两件事。不论是谁，买房只能靠自己，靠政府是讲不通的。没有地方住，可以找政府想办法，但是不涉及所有权。

房价为什么高？关键是有人不怕贵。这和我国的宏观形势有关。我国的经济增长率很高，每年的财富生产能够增加10％左右。这么多的财富被生产出来，但是消费掉的并不多，有大约40％储蓄起来了。再加上财富分配的不均，收入高的人年增收入远超过10％。他们手中的钱很多，又找不到合适的投资机会，于是就拿他们的储蓄买房。要想房价下降，这几个条件必须有所改变。或者是经济增长率下降，消费扩大储蓄减少，财富分配均匀化，有更多的投资机会；或者是大大增加房屋的供给，关键是增加土地的供应。我国房屋供应的限制就在于用于开发的土地不足。特别是为了粮食安全考虑，而过度限制农田转用于开发用地。这项政策应该改变。

我国房地产市场偏向档次高的客户，普通的低档房盖得很少，正是与我国财富分配中贫富差距悬殊有关。房地产市场反映了收入分配的状况，不改变收入分配，房地产业的结构同样改变不了。

一个市场中有少量的投机是好的，此时投机能够创造财富。但是投机过多时，价格被投机者控制，投机变成赌博，就不能创造财富。不光房地产市场是这样，其他一切市场都是这样。 股票市场上的投机者，低价买进高价卖出，如果价格预估正确，他们在赚钱的同时也能为企业的优劣变化指出方向，所以对社会是有贡献的。他们所赚的钱就是社会给他们的回报。但是如果他们判断错误而赔钱，把走向恶化的企业看成好企业，把坏企业的股票价格抬上去，最后事实证明企业的股票价格下降，社会就会对他们惩罚。这是很公平的。 但如果投机者人数太多，会扰乱正常的市场秩序，使价格陷入混乱。投机者失去方向，投机就变成了赌博。投机能创造财富，而赌博是不能创造财富的。比如我国的股票市场，一年的换手次数达到7次，外国的换手率只有一两次，说明投机活动太多。不改变这样的状况，股票市场很难正常化，金融危机也更容易发生。房地产市场也是同样的道理，我们必须防止过度投机，它有害于国民经济。

回过头来总结，我们有三方面的问题：收入分配不均、土地和资金市场缺乏竞争、金融市场没有更多的投资渠道，是造成房地产业扭曲的根本原因。这些原因不改变，扭曲就不会得到纠正。

政府用强制手段从农民手里低价拿地，再用所造成的价差补贴城里人以低价买房。这就是经济适用房政策背后的游戏。它的实质是让农民补贴城里人，是一种倒行逆施的收入分配政策，是在我国已经扭曲了的收入分配现状中火上浇油。最近全国各地大量农民上访，官民冲突的一个主要原因就是和土地有关的纠纷。

解放前的农业是一个相当高效的行业，后来变成一个非常糟糕的行业。其区别何在？一言以蔽之，在于有没有参与者的自由。不论出于什么好心，如果违背了自由的原则，好心也会办坏事。反之，如果有了自由的选择，虽然是坏的政策，也不会实施。自由可以屏蔽掉坏事，不让它发生。因为当事者最知道自己的利益何在。这条原则是一切经济问题的基本道理，从政者万万不可违背这个原则。

不但在农业方面是这样，在其他方面也一样。切记：自愿原则，不容随便破坏。政策的好坏不在乎制定者的判断，而在乎能不能在自愿的基础上行得通。除了税收、环保、防止不良外部性等少数几种情况需要强制干涉，政府切忌自以为是，强迫实施大家不愿意做的事。什么是市场？其实就是顺乎自然。计划为什么不好，就因为它违背民意。是谁有权强迫别人做不愿意做的事？只有政府才能。所以政府千万要小心谨慎，不可违背自然，造成严重后果。

由于对土地没有明确的所有权，发生了公地悲剧，大家只管使用，不管维护，地力下降，有机质减少，而且生产积极性不能保护。为了解决这个问题，政策规定土地承包30年不变，甚至50年不变。可是所有权还是模糊的。更准确地讲，农民还是没有对土地的所有权。

为了解决和所有权相关的问题，政府可以说是费尽了心思。再三强调承包制不变，延长承包期，又说要加强土地的流转，又是土地入股，土地可以作抵押，土地可以置换出租，还有小产权制，花样多得眼花缭乱。但是最根本的所有权问题始终避而不谈。而恰恰所有权才是问题的根子。它是绕不过去的。

作为慈善事业的扶贫，只能有少量人士参与，它成不了正规的金融业。要使小额贷款成为农村金融的一个角色，必须能够商业化，能够吸引大批资金进入，所以商业化是必需的。

现在社会上出现了一种现象，我认为很不好。那就是一方面为穷人说话的人很多，替富人说话的人很少；另一方面为富人办事的人很多，为穷人做事的人很少。 出现这种现象的原因很简单。为穷人说话能够得到社会上大多数人的赞同。穷人是弱势群体，需要有人为他们说话。哪怕说错了，也不用担心。因为立场不错，顶多是技术性错误。说话的人考虑自己的社会影响和对自己的舆论评价，为穷人说话是不会出问题的。我国是一个特别讲究立场的国家。立场错了一切都错。谁敢犯立场性的错误去为富人说话呢。所以都站在保险的立场上为穷人说话。 为富人说话则不同。由于大众受马克思剩余价值学说的灌输，富人被认为是剥削者。为剥削者说话当然错了。所以话还没有说，立场先已经错了。谁会去做这种吃力不讨好的事呢！ 至于做事，为富人做事是有酬劳的，所以大多数人愿意为富人做事。而为穷人做事很难有酬劳，所以为穷人做事的人比较少。于是结果是许多人为富人做事，为穷人说话；很少人为富人说话，为穷人做事。这样一个社会是很不正常的，是容易出问题的。所以我要反其道而行之，为富人说话，为穷人做事。

有不少情况，企业家犯法是因为政府当局处置不当。例如税务局征税，有许多不合理的规定。企业家多次反映，当局起初不认错，后来各方面反映实在太强烈，不得不承认有毛病，但是至今不改。企业和政府完全不在一个平等的地位上，吃亏的永远是企业。企业家对这种种不合理的做法无法抗衡，只好以恶治恶，用做假账来对付。这样企业家显然是犯法了，但是确实是事出有因，起因还在政府一边。类似的情况不仅发生在企业家那里，也发生在一般人民群众那里。要说犯罪，就不仅仅是企业家的事了，所以光怪企业家是没有多少道理的。

社会表扬做慈善的人，这是一个正常社会所应有的习惯。过去有些人强调做好事要不留名，留了名就不是真正的好事。这种理论非常有害。为什么我们对待做好事的人如此苛刻呢？正因为做好事的人不够多，所以需要社会的表扬，鼓励大家多做好事。哪怕人们做好事是为了得到表扬，只要是真正的好事又有何妨？我们不否认有些企业做慈善有广告宣传的动机，但只要他们做的事真正帮助了有困难的人，得到表扬是很公平的。而且这对全社会有益，有什么理由反对呢？如果我们真正对贫苦人充满着同情心，我们一定会欢迎一切对穷人有益的活动。至于出钱做慈善出于什么动机，根本不是我们要关心的问题。穷人的生活能否得到改善才是我们关心的事。有些人自己不参加慈善活动，还要对别人的参与吹毛求疵，这种心理很不健康，对社会是不利的。

在中国做慈善并不能给富人带来财产的安全和社会的名望，而是恰恰相反。富人露富的结果是更不安全，名声更糟。这是中国富人不愿意出钱做慈善的根本原因。中国的环境很不同于美国。在美国财富象征着个人的成功，是大家学习的榜样。在中国则不同。中国的富人是挨骂的对象，是剥削的典型。不露富还好一点，露富是一点好结果都不会有的。

拥有财产会带来剥削者的坏名声，财产的安全缺乏保障。在这样的社会中露富是最愚蠢的做法。所以富人的对策是不声不响地把财产转移去外国安全的地方，而不是捐款做慈善。这就是近年来大批富人移民西方国家的背景。

这条道路就是李连杰所倡导的壹基金，每人每月捐一元钱。我认为这个方向符合中国的国情，能有广阔的发展前途。但是壹基金曾经遭遇很大困难。原因和国家对慈善事业的垄断企图有关。中国政府的基本态度是鼓励民间拿钱，但是操作要由政府来做。如果民间自己拿钱，自己操作，政府是不鼓励的。这一点很明显表现在慈善组织注册的规定条文，在善款纳税的区别对待上。特别是民间的慈善极难获得合法身份，因此他们不能在银行开设账号，没有自己的图章，也开不出捐款的合法收据。因此也不能向公众募捐，这些事只有挂靠政府的慈善机构才能做。当然，如果政府的慈善做得很好，也未尝不可。问题在政府的慈善事业往往毛病丛生。救济目标缺乏合理的针对性，操作不透明，没有热情，是冷冰冰的照章办事，还有不少贪污浪费。使得大家出钱不放心。这就大大阻碍了中国慈善事业的发展。

政府不同于一般民间组织，它最重要的特点是具有武力做后盾，可以用强制措施来达到某一特定的目标，如国防、公安、纳税、食品安全，甚至环保，但是不包括慈善。做慈善不需要任何强制性的力量，相反，要的是热情和细致。这正好是政府所缺乏的。所以世界各国的政府都不做慈善（但是政府调整收入差距，提供社会保障），慈善是留给民间做的事业。

经济学中的享受是指对物质消费的满足感，而不是从攀比得到的满足感。买几千几万元的手表或手袋，得到的是从炫耀来的攀比满足感。严格讲，攀比的满足是为了别人，不是为了自己。如果没有别人在场，就不会有攀比的满足感。为了别人的羡慕而消费是愚蠢的消费。为了别人的福利而消费是聪明的消费。比如买路边小摊的商品，不但满足了自己的需求，又帮助摆摊的人提高了收入，利人利己，是聪明的消费。这种消费有利于缩小贫富差距。

从这个角度看，贪污分子最倒霉。他们贪污得来的钱很多，但是不敢露富，到处装穷，一点也没享受着，天天还要担心受怕。物质享受没得到，倒是精神负担非常重。两头都没捞着，非常不合算。如果他们想通了，就不会贪污了。

值得注意的是我们千万不要做相反的事，拿穷人的钱去补贴富人。当然，很明显这种政策是不会发生的，但是隐蔽地补贴富人是可能有的。这值得大家密切注意。比如说，为了照顾穷人保持低电价，实际上富人得到的好处远远大于穷人得到的好处。因为富人用电量远超过穷人用电量。结果是拿广大电力用户的钱去更多地补贴了用电量大的富人。这种为了穷人而被富人搭便车的例子比比皆是。本来是想缩小一点贫富差距，结果适得其反。而且这种政策很难纠正，因为表面上这是为了穷人，叫起来振振有词，反对它要冒很大的风险。

当前我国税收的主要来源是从交换中征税。比如增值税、营业税、消费税、关税都和交换有关，他们占了总税收的56％。这部分税收的主要成分具有累退的性质。因为交换是和消费成正比的。消费越多缴税越多。富人在总收入中消费所占的比例较低，储蓄所占的比例较高，而储蓄是不交税的。相反穷人的收入大部分都用于消费，都要交与交换有关的税。虽然穷人的人均消费比富人少，但是从消费占收入的比例看穷人所占的比例高，所以纳税的比例也高。这就是为什么现在的税制是累退税的缘故。

关于福利国家的争论由来已久。对于普通百姓而言，有福利总比没有强，所以都赞成福利国家。但是对于专家来说，他们多了一层思考，提出的怀疑很多。最基本的一个问题是，福利所用的钱是从哪儿来的？又用到哪儿去？普通人总以为政府的钱自有其来源，有钱用在自己身上总是好事。其实政府并不创造财富，反而要消耗财富。归根结底，政府的钱就是从纳税人手里征得来的。而且政府越大，管的事越多，花的钱必然也多。总体上看，政府从纳税人身上征税，再用在纳税人身上，有点多此一举。而且让政府多征税，扩大了政府的权力。与其征税再返回不如少征点税，还能节省许多征税的成本和再分配的费用，总体上提高了效率。这是反对福利国家的主要理由。

那么副作用是什么呢？就是改变了人们努力的方向。在市场经济中，人们努力去赚钱，也就是创造财富。而在福利制度中，人们会努力去钻空子，交钱的时候躲着走，分福利的时候抢在前。整个社会的奋斗方向被扭曲，从财富创造变到了财富分配，人们的力量用于互相抵消的内耗，而不是增加社会财富。用纳税人的钱扶贫也有类似的问题，但扶贫是必要的，产生些副作用可以想办法克服。

当然，老百姓要实行监督权，也必须意识到，中国的改革开放如果没有共产党的领导是不可能取得这样的成就的。所以，现阶段我们要研究的不是三权分立、全民选举、多党制等问题，而是从技术层面上帮助改善执政效率，增加执政透明度，保障人民的权益，聚焦政府的公共治理问题，尤其是提高城市的公共治理水平。

有些贫困的国家，其所以贫困并不是没有生产能力，而是自作孽造成的。我们中国人对此最有亲身感受。还是这块土地，还是这些人民，改革开放以后，生产增加了若干倍，原因是我们不再自己斗自己。

提倡无私对不对？可以直截了当地回答，不对。有私心的人提倡无私，是叫别人无私，他们可以为所欲为地侵犯别人的私。即使真正做到毫无例外地人人无私，这个社会也并不美好。人都没有了私心，人还追求什么？人活在世界上为了什么？人们以为自己无私可以服务于别人，让别人改善处境。可悲的是别人也已经不再追求自己的利益，你为别人着想，别人并不领情。无私的社会是一个非常滑稽的社会。我们简直无法想象。不过一部分人有私，另外一部分人无私，倒是能够互相配合的。问题在于谁应该当无私的那部分人？谁应该当有私的那部分人，倒是一个难题。其实这个问题从另外一个角度倒是能够解决的，那就是承认人可以，甚至应该有私心，但是不得侵犯别人的私。或者说，私是平等地赋予每一个人，不允许一部分人有特权可以侵犯别人的私。而这就是人权。

首先他没有想到，公有制不可能让全体公民共同参与生产资料的经营管理，只能由少数人代表公众来实施，结果把真正的所有者排除在外，变成了旁观者，经济权力的集中导致政治上的独裁。其次，他没有想到私有制固然有问题，但是公有制的问题更大。因为大家对公共财产漫不经心，缺乏责任感，官僚风气盛行，企业普遍亏损，效益低下，社会弥漫着懒惰气氛。生产萎缩，民众生活困难，连粮食都不够吃，成为短缺经济。这和私有制经济的蓬勃发展相比较，确有天壤之别。所以后来发展的趋势不是公有化，而是世界性的私有化浪潮。

如果是因为“以人为本”而为国捐躯，那是完全应该的。比如日本人侵略中国，要把中国人当亡国奴，我们坚决不干。因为我们的人受到了伤害，我们要誓死捍卫祖国。这不是国家的尊严，而是百姓的死活。如果只是国家的尊严，与百姓的利益无关，我们要不要关心就是值得讨论的问题了。这样的看法恐怕很难为大多数人接受，因为“以国为本”的思想已经根深蒂固，很难扭转。这个思想已经贯彻了几千年，谁也不会去想一想这里有什么问题。由于以国为本的误导，枉死了不计其数的人。可是因为国家的观念太强烈，以至于连性命都显得不重要。其实这完全是本末倒置。人的生命才是最重要的，以人为本是对的。今天是我们重新考虑这个问题的时候了。

我们常说少数人的利益要服从多数人的利益，意思是少数人应该为多数人牺牲。比如为了建设水库要求当地百姓移民迁走，这就是少数人的利益为多数人的利益作牺牲。迁移搬家不是不可以，但是必须给必要而且足够的补偿，不能让他们为多数人而牺牲。少数人应该为多数人牺牲，听起来好像讲得通，这往往是因为自己属于多数，不需要自己作出牺牲。但如果不保护少数人，说不定多数中的人，在另外一种分类时忽然变成了少数；在某种情况下自己属于多数，换了一种情况就可能变成少数。所以，不能因为是少数，利益就可以随便被侵犯。少数服从多数，只有在不涉及基本权利的范围内可以行得通。即使在这种情况下，也必须尽量照顾到这些少数人的利益。在基本权利的范围内，任何个人的权利都应该同样得到承认和保护。比如我们没有理由用举手表决的方法剥夺一个人的自由，也不能因为民愤极大而将某人处死。这些行为只有通过严格的法律程序才可以实施。

孔子说，“己所不欲，勿施于人”。他没有说“己所欲，施于人”，可见这二者是有区别的。毋宁说：“己所欲，慎施于人。”总之，强加于人是不可以的，哪怕出于公心。

一般情况下，人民的利益和国家的利益是一致的。因为国家之所以出现，正是因为人民有集体利益，需要有公共事务的管理者，于是出现了国家组织。市场可以提供百姓的吃、穿、用，但是市场的秩序需要有市场之外的权威来维持。过去还有外族的侵略，需要用集体的力量来保护自己。国家能够组织分散的百姓，成为可以抵御外侮的力量。所以国家本来就是为了人民而存在的。

近年来发达国家越来越多地废除了死刑，即使还没有完全废除，真正执行的死刑也越来越少。一个死刑犯被判了死刑，要等许多年才可能被执行，有许多一直等到自然死亡也没有执行。这是因为，死刑完全没有教育意义。就算死刑犯人认识到了自己的错误，也没有机会改正了。死刑也有报复的目的。但是现代社会极不鼓励报复。社会要和谐，就要讲究宽容。冤冤相报，永无宁日。死刑也用于威慑。可能犯罪的人，想到死刑的后果，可能停止犯罪。但是近来的研究并不支持这种警告的作用。死刑对减少犯罪并没有明显的效果，有时候为了杀人灭口，避免自己被判死刑反而增加了犯罪。所以总的趋势是，处死一个人的理由越来越被怀疑，死刑越来越难以通过。最后很可能是每个人的生命是至高无上的，不论什么人、什么机构都无权处死人。人民的生命得到最完全的保护。

交换不是零和游戏，它有净的产出。这和传统经济学所说的“等价交换”正好相反。之所以有等价交换的想法，是由于劳动价值论。它认为物品的价值多少取决于生产该物品所花去的劳动量，交换前后物品没有变，所以其价值也不变。殊不知物品的价值取决于是谁拥有它，以及时间、地点等条件。同样的香蕉，在广州消费掉和在北京消费掉，其价值是不同的，因为广州人经常吃香蕉，而北京人难得吃得到香蕉。

“有计划，按比例”之所以错，是因为经济事务中不存在固定不变的比例。物理、化学中有许多固定不变的比例，但经济事务中没有。拿居民的消费结构来看，拿多少钱买吃的，买穿的，买娱乐，买住房，等等，都随收入和偏好变化。人们的收入提高后买吃的比例会降低，买旅游等娱乐品的比例会提高。当居民的收入很快提高时，旅游业会更快地得到发展，而不是和收入成正比例增加，因为吃的比例在减少。

为某种资源规定一个红线，用行政的方法使用各种资源，不相信市场能够合理配置资源，是计划经济的思想。其实，如果我们反思现在每年生产的各种商品的产量，从钢铁混凝土到鞋帽方便面，以及生产它们所用的资源量，人力、资金、淡水、土地等的投入，都不是事前计算好的，而是市场在引导人们的决策。企业按照市场的需要，按照各种商品的相对价格，以降低成本为目标，决定技术工艺路线、营销方案等，从而决定各种资源的用量。各个企业决策的加总，形成全国的资源配置状况。这里面没有任何一样是按照事前计算的计划决定的。不但现在市场经济如此，过去搞计划经济的时候，也从来没有能够完成计划目标。好在人是健忘的，下次做计划的时候从来也不回顾上次的计划执行得如何。如果每次都认真总结经验，计划经济老早就被放弃了。计划唯一的作用就是扰乱市场的配置，造成经济的巨大混乱，最后搞得连饭都吃不上。

现在大家日子过得很舒服，将来子孙后代要还债。搞清这个问题的关键在于认清一个事实：当代人的消费都是由当代人的生产提供的，不是由前人的储蓄提供的。当代人吃的粮食是由当代人生产的，不是几十年前的祖先储蓄在米缸里的。更不用说当代人需要的医疗、教育等，也都是当代人提供的。所以解决老龄化社会的问题，不是简单增加储蓄所能解决的。要思考当代人如何能把钱借给未来的人，现在这一代人生活苦一点，将来的人活得容易一点。也包括如何避免向将来的人借钱，现在的人活得容易一点，但是苦了将来的人。比如通过破坏环境来发展经济，被破坏了的环境将来是要治理的，这笔钱要由将来的人承担，因此就变成向将来借钱的事。

对价格的看法也常常因为观察者的立场而被扭曲。大多数人都从消费者的立场看问题，总是希望价格越低越好。价格低总是受欢迎，抬价总是遭反对。但是如果从生产者的立场看，结果就相反，提价才受欢迎。所以价格不是低了好，也不是高了好，而是恰当最好。什么是恰当的价格？竞争条件下自由浮动的价格最好。供不应求必须涨价，否则会使商品长期脱销。计划经济时代就是反对涨价，搞得什么商品都紧张，样样都缺。我们不要怕涨价，怕的是没有公平竞争，取消公平自由的竞争才是最可怕的。要取消政府对价格的干扰，让价格自由浮动。价格低并不能改善大家的生活。效率高，浪费少，才能提高生活水平。这是一般人常常误解的地方。

至于经济适用房，表面上有人买了便宜房，谁也没有受损失。可是从经济学分析，任何住房的建设都有其成本。经济适用房为什么便宜？是土地的价格降低了。土地是谁所有？或者是郊区农民，或者是公有的，或全国人民所有。经济适用房是损害了郊区农民或全国人民的利益，让一部分人买了便宜房。买房的人是谁？绝不是生活最困难的人，多半是已经有了几十万元存款的人，特别是一些有特权的人。如果拿全国人民的钱补贴最穷的人，大家不会有多大的意见。如果补贴了有钱有势的人，就成问题了。这样看，经济适用房是一个极不公平的政策。它之所以能够欺骗大家，就因为大家没有深入想一想，便宜所得的钱从哪儿来。

提供给贫困农民的小额贷款利息率都很高，一般在20％以上。这是世界银行总结各国成功的经验所得的结论。这引起许多人的批评，他们认为给贫困人口贷款，这么高的利息率无异于剥削，于是强烈反对。这是一项大大有利于穷人的政策受阻的主要原因。我们用经济学分析一下，就能够看清楚问题在哪里。 利息率是使用资金的价格，它同样服从供求规律。资金充足时利息率降低，资金紧张时利息率上升。小额贷款的高利息率，正是因为做小额贷款的资金太缺。为什么做小额贷款的资金少？因为它的成本高，获利并不大。有钱人并不愿意拿钱去做小额贷款。有些地区用低利息率提供小额贷款，结果和一般商品低价供应的后果一样，就是供不应求，需要排队。此时利息率不能起分配资金的作用，就会有别的方式，例如按人际关系，或走后门来分配贷款。结果是有权有势的人，例如一些社队干部、宗族领袖能够拿到小额贷款。他们一转手就能放高利贷，贫困百姓只能望洋兴叹。所以低息的小额贷款往往是帮了社队干部等有权势的人。更何况如果高利息真能赚很多钱，就会有大量资金进入，资金就不缺了，利息率就下来了。可事实上小额贷款事业极度缺乏资金，这证明高利息也不能赚很多钱，因为贷款额度小，运作成本高，风险大。

财富是如何创造的？过去很多人认为，是劳动创造的，这就是劳动价值论。现在的经济学已经否定了劳动价值论。比如讲，土地不是劳动的产物，但是有些土地非常值钱。再如改革开放后我们的劳动并没有增加多少，但是创造的价值增加了15倍以上。又如美国人的收入比我们高出许多，并不是因为他们劳动得多。当然也有多劳多得的时候，干得多，收入也多，比如计件工资。

将回报率低的钱调动到回报率高的地方去，这就是金融业创造财富的奥秘。过去认为金融业是服务业，没有参加生产劳动，所以是不创造财富的。那时候银行业的工资水平属于服务业，和理发师的档次一样。现在金融业的从业人员工资很高，因为他们创造的财富很多。家庭储蓄的钱如果放在抽屉里，其回报率等于零。存进了银行，就有了一点回报，因为存钱能够得到利息。银行把客户的钱贷给有效益的项目，能够得到更高的回报，这就是贷款利息。如果银行无能，把钱贷给了亏损的项目，变成了坏账，银行就要受罚，账目上出现赤字。从这一点来看我国的银行是相当低效的。贷出了许多坏账，所挣的贷款利息也不高。有许多很好的项目，能够支付高利息的项目贷不到款，却把钱给了效益较低的项目。这正是我国需要金融改革，提高银行经营能力的原因。
