#+title: Why I work remotely (hint: it has nothing to do with productivity).

原文链接 https://m.signalvnoise.com/why-i-work-remotely-hint-it-has-nothing-to-do-with-productivity-34ace30f74fc#.f3ayawgvj

file:images/why-i-work-remotely.jpeg

remotely不一定是为了可以更高效地工作，而是可以让你有时间更多地和家人在一起，为他们做一些事情。让我想起一句话'work to live, not live to work'

#+BEGIN_QUOTE
If you have little kids (or no kids) what I’m experiencing may seem like it’s irrelevant (or at least a long way off) but I promise you it’s not. You won’t remember working a little later or catching up on Saturday because the people you love interrupted you but you’re certain to remember those little interactions. And even more, they will remember them, too. This is why I work remotely. I worked a day job and freelanced all night (while putting myself through college) when these same kids were little. I barely remember those years. Be grateful that you’re home to be interrupted at all.

Now take all of that and cut yourself some slack. The work will get done. *The people you love aren’t interruptions, they’re the reason you work at all.* Give ’em a hug.
#+END_QUOTE


