#+title: Why I stopped paying attention to industry news

[原文地址](https://medium.com/@jasonfried/why-i-stopped-paying-attention-to-industry-news-2e5821ea264c)

过度关注行业消息是一种病态！

A couple of years ago, I did an experiment: I kicked sugar for three months. I’d have whatever naturally occurred in foods, but I wouldn’t eat anything with added sugar. The goal wasn’t to eat like this forever. I just wanted to know what it felt like to get all that sugar out of my diet. How would I react? What would be different? Would I like it?

The short answer: I felt great. I had way more energy, more balanced days, better mental clarity. But the most surprising outcome came when I reintroduced extra sugar into my diet. During the sugar fast, I wasn’t eating apples, but I tried an apple again. And wow, did I feel it. A sugar high from an apple? That was an eye opener. Even today, with my just-a-tad-of-sugar diet, I can feel the effects of the sweetener in ways I never could before. (戒糖一段时间之后，对糖分会更加敏感)

The incredible thing is that a few months into the industry-news detox, I felt better not only mentally, but physically, too. My mind wasn’t on edge, waiting for the next big thing to hit. I was calmer, I found myself with more time, and I was far more focused on stuff I could control, like my product, my company, my person, rather than stuff I couldn’t, like the next “[Basecamp](http://basecamp.com/) killer” or some hot new startup.

It’s now a year later and I still don’t read industry news. Sometimes I’ll accidentally run into it. Sometimes someone will mention something to me wondering whether I’ve heard of it. I’ll often say no and ask for details. And then he or she will tell me about it in a way that’s actually useful, not sensationalized, as most coverage of new things is. I don’t feel disconnected. In fact, it’s quite the opposite. It’s no longer just empty calories: I eventually hear about what’s really important. (依然可以通过和朋友交流获取到最新的业界消息)
