#+title: 为什么某个领域的英雄人物总是在某一个时期一起涌现呢？

https://www.dedao.cn/article/zl12vGeNAM0YVpPYZ2VdmxjOQBP5oL

为什么某个领域的英雄人物总是在某一个时期一起涌现呢？这绝对不仅仅是论资排辈的问题，这是抓住关键时机抢占关键位置的问题。格拉德威尔在《异类》这本书里讨论过，为什么比尔·盖茨这帮IT巨头都差不多是同一个时期出生的？因为那一代人长到青年时期，正好赶上计算机这个行业能赚大钱。你生早了，计算机开始流行的时候你已经是个四十岁的化学家了；你生晚了，等你会用电脑的时候满大街已经是微软的东西。

那为什么会有关键时机和关键位置呢？这里面有两个原因。

一个原因是很多事业都有窗口期。活跃的领域才能造就英雄。新中国只能建立一次，如果现在不打仗，军事天才也不可能留下姓名。再比如说物理学，1900 年到 1940 年是物理学的黄金年代，新测量技术突破了，新理论还不成熟，简直遍地都是低垂的果实。用朗道的话说就是二流的物理学家都能做出一流的工作。可是等到 1970 年以后，理论已经非常成熟了，而实验手段已经到了极限，那么对不起盛宴已过，你再想弄一个像爱因斯坦、玻尔那个水平的大新闻就不可能了。

之所以有窗口期，是因为世界不是无限的、也不是连续变化的。新大陆是有限的，美洲只能被正式发现一次……完了地球上就没有别的大洲可供发现了。当然理论上你可以去别的星球探索，但是那不会是明天开出的一班车。

另一个原因是先发优势。如果计算机芯片和操作系统的研发必须跟用户的使用同步成长，微软、英特尔已经占据了市场，用户熟悉他们，他们也熟悉用户，这个业务的门槛越做越高，后人很难进了。

人对岗位的占位也是如此。跟着朱元璋起兵的将领大多都是他的同乡，而这帮人之中就出现了好几个军事天才。难道说中国军事天才的分布密度那么高吗？一个小地方就有那么多天才将领？当然是实战经验成就了他们。

再聪明的人如果只能做一些小事儿，也不会有什么大的成就。你说我是哈佛的计算机博士兼工商管理硕士，你只有本科学历，你把阿里巴巴副总裁这个位置让给我吧 -- 那当然不行。人家在创业实战中经历的东西比你在书本上和实验室里经历的高太多了。这些人被事情所塑造，而且他们也塑造了事情：他们已经是公司不可缺的角色。

所以当历史发出召唤的时候，应该不顾一切地抢占关键的位置。这班车没赶上，下班车没有了。我记得有一个科学家的同伴跟这个科学家说，在A和B两个领域中我想去A领域，因为A领域已经成熟了，我知道该怎么做，可是B领域还很混乱，我不知道怎么做 -- 那个科学家说，你想什么呢？当然应该去B领域啊！A领域都成熟了还有好位置给你吗？B才是可以争夺的地方。

只有两个力量能打破这种占位。一个是颠覆式创新。新的出来了，旧的位置就没意义了。所以新东西出来是新人抢占位置的好时候。另一个是旧人总会死的。如果侯宝林他们那一代相声演员一直年轻没死，现在哪有只会唱太平歌词和编排于谦他爸爸的郭德纲的位置。
