#+title: 野生问题

[[https://www.dedao.cn/course/article?id=7NqeGmE2w4bnK4EqpdVP31lv5WZ9rj&source=search][《野生问题》（上）：你愿意变成吸血鬼吗？ - 得到APP]](https://www.dedao.cn/course/article?id=7NqeGmE2w4bnK4EqpdVP31lv5WZ9rj&source=search)

[[https://www.dedao.cn/course/article?id=oezW9aA7r8pGX8BOM4VlY4jRMdvmbE&source=search][《野生问题》（下）：从r策略到K策略 - 得到APP]](https://www.dedao.cn/course/article?id=oezW9aA7r8pGX8BOM4VlY4jRMdvmbE&source=search)

-----

什么叫「野生问题」呢？首先你要知道，世间的难题之所以叫难题，是因为它们往往不像你在学校里做的那些数学题一样有明确的定义和结果。

像我们专栏以前讲过的「棘手问题」[2]，就是没有正确解法，没有结局、甚至无法评论胜负的问题。比如新冠疫情就是个棘手问题，不管你怎么应对，结果都不会很理想，你再怎么做也只是勉强维持局面而已。

而罗伯茨说的「野生问题（wild problems）」，则是另一类问题。野生问题可能会收获一个圆满的结局，但当你一开始面对它的时候，你可能连题意都没搞明白。

-----

按照这个思路，罗伯茨把生活中的问题分成「野生问题」和「驯化问题」两类，对应野生动物和驯化动物。被驯化的动物是可预测的，你非常知道猪马牛羊都是怎么回事儿；野生问题，是不可预测的，你甚至都不了解它是什么。

对于驯化问题，我们有各种成熟的、科学的、理性的办法。

最基本的方法是权衡利弊。你看一看自己有多少个选项，测算各个选项的价值都有多大，然后选价值最大的那个。

-----

有一位女哲学家叫劳里·安·保罗（Laurie Ann Paul），曾经提出一个比喻。假设普通人都可以变成吸血鬼，那请问，你愿不愿意变成一个吸血鬼。如果你变成吸血鬼，就必须吸别人的血为生，每天都睡在棺材里，不能见阳光。对于身为普通人的你来说，当然不想过这种生活，你觉得这太荒唐。但你去采访那些吸血鬼，发现吸血鬼对自己的生活评价极高，都很快乐！他们喜欢做吸血鬼，他们喜欢吸血，喜欢住在棺材里，不愿意见阳光。

如果设定是成为吸血鬼会让你的生活很愉快，你愿不愿意成为吸血鬼呢？

这个局面最怪异的一点是，当你成为吸血鬼之后，你喜欢的和不喜欢的，会发生改变。

这就是野生问题的关键。选专业、结婚、生小孩、搬家去另一个城市，这些问题其实都是吸血鬼问题。还没有去上海的你，不知道在上海的你会是怎样的状态，会有怎样不同的喜好。

那你还怎么决定要不要去上海？什么道德算数、算法、公式又有什么用？

-----

你在直觉中其实已经决定了。那个直觉是什么呢？它显然不是功利主义的东西，不是计算出来的。

罗伯茨认为，那个直觉是你想要的人生意义。是你的目的、你的渴望、你想参与something bigger than yourself，你想要超越现有的生活。

更准确的说法，罗伯茨再次使用了我们专栏以前介绍过 [7] 的来自古希腊的一个词：Eudaimonia。中文一般翻译成“幸福”，但更精确的意思是说，你去从事一项事业，这个事业能把你的特长发挥出来，从而使得它一直发展壮大。罗伯茨建议这个词应该翻译成「繁荣（Flourishing）」——对个人来说，繁荣就是你要活得蒸蒸日上，你的生命很蓬勃。

你想去上海，是因为你觉得上海会让你繁荣。你的生活质量不一定会上升，你会更忙碌，你可能会被迫住在更小的房间里，你的钱可能会不够花——但是你身上的潜能可以在上海发挥出来，你的能量更高了。

繁荣，就是人要充分地生活。不仅仅是离苦得乐，而且要有意义、有美德、有尊严、有自主权地生活，要把自己的各种可能性施展开。就如同一棵树，你希望自己开花结果、枝繁叶茂。

-----

要这么说的话，我们大约可以把世界上的人分成三种——

第一种是欲望的奴隶。什么事吸引他他就做什么，被自身好恶和外界的威逼利诱驱使，缺少思考，没有通盘的规划。

第二种是精致的利己主义者。他是高度理性的，想让自己人生的幸福最大化。但是他舍不得自己，不会投身到一个了不起的事业之中，总在斤斤计较。

第三种则是追求繁荣的人。他人生的目的不是让幸福最大化，而是想要把自己各方面潜能都发挥出来，过得有意义，最好能留下痕迹。为此，他愿意牺牲一定的幸福。

也可以说每个人都是这三种人某种比例的混合体。

-----

我们在生活中总要学会对一些事情说不，否则就会被各种琐事困扰，什么事也干不成——但是你又不能对所有“无关”的事情都说不，否则你就会错过很多好东西。你不能没有计划，可是你也不能有太强硬的计划。

对野生问题要大胆尝试，同时保留无情结束的选择权。但是你终将要做出选择，不过选择也不是一次性就选定了以后的所有，而是做出承诺、继续探索，寻找最好的成长方式。

探索的方向要始终追求繁荣。这就意味着我们并不是总在问自己“喜不喜欢”，我们更想要的是意义、目的、爱这些更伟大的东西。
