#+title: 狼图腾

陈阵说：应该说，对中国对世界的影响更大。自从出了成吉思汗和他率领的蒙古骑兵，中国从金、南宋以后的历史全部改写。中亚、波斯、俄罗斯、印度等国家的历史也全部改写。中国的火药，随着蒙古骑兵开辟的横跨欧亚的大通道传到西方，后来轰破了西方的封建城堡，为资本主义的崛起扫清了障碍。再后来火炮又轮回到东方，轰开了中国的大门，最后轰垮了蒙古骑兵，世界天翻地覆……可是，狼在历史上所起的作用，在人写的历史中被一笔勾销了。如果请腾格里作史，它准保会让蒙古草原狼青史留名。

整个马群踏破冰壳全部陷入泥塘，马群绝望长嘶，拼死挣扎，马对狼的恐惧和仇恨已达极顶，陷进泥塘的马群稍稍犹豫一下，便众心一致地拼尽最后的力气，在黏稠的泥浆里倒着四蹄向泥塘深处爬，即便越陷越深，也全然不顾，它们宁可集体自杀葬身泥塘，也不愿以身饲狼，不让它们的世仇最后得逞。这群被人去了势、剜去了雄性的马群，即使已到生命的尽头，仍在拼死作出最后的反抗，以集体自杀来反击狼群复仇的自杀进攻。它们都是古老蒙古草原上最强悍的生命。

陈阵宠爱通人性的黄黄，不怪它不仗义，但开春以来，他越来越喜欢二郎了。它的兽性似乎更强，似乎更不通人性。在残酷竞争的世界，一个民族，首先需要的是猛兽般的勇气和性格，无此前提，智慧和文化则无以附丽。民族性格一旦衰弱，就只能靠和亲、筑长城、投降称臣当顺民和超过鼠兔的繁殖力，才能让自己苟活下来。他站起来，用望远镜向西北边的苇地望去，希望看到二郎的去向。

如果爆竹大量流入草原，再加大药量，加上辣椒面，催泪粉，用于掏狼杀狼，那么称霸草原几万年的狼就难逃厄运了，草原狼从此以后真有可能被斩尽杀绝。火药对于仍处在原始游牧阶段的草原，绝对具有划时代的杀伤力。一个民族的图腾被毁灭，这个民族的精神可能也就被扼杀。而且，蒙古民族赖以生存的草原也可能随之消亡……

在草原上，人完全掌握着狗的生杀大权，人是靠强大的专制暴力和食物的诱惑将野狗驯成家畜的。任何胆敢反抗主人的狗，不是被赶出家门，赶到草原上饿死冻死或被狼吃掉，就是被人直接杀死。狗早已丧失了独立的兽性，而成为家畜性十足的家畜，成为一种离开人便无法生存的动物。陈阵替伊勒们感到深深地难过。与此同理，在人类社会，如果专制镇压的力量太强大，时间又太久，人群也会渐渐丧失人性中的兽性，而逐渐变为家畜性十足的顺民。顺民多了，民族内部的统治也顺利了，可是一旦遭受外部强大力量的入侵，这个民族就丧失了反抗能力。或者俯首称臣变成异族的顺民，或者被彻底毁灭，变成后人考古发掘的废墟。多少灿烂辉煌的农耕文明，现在只能到历史博物馆去看了。

狼从路沟里费力地爬起来，斜过身蹲坐着，沾满血迹的胸下又沾了一层沙，不屈而狂傲的狼头正正地对着两位追敌。狼没有忘记自己的身份和习惯，用力地抖了抖身上的沙土和草渣，力图保持战袍的整洁和威严。但它还是控制不住露骨的断腿，翘在胸前不停地发抖。然而狼的目光却凶狠得大义凛然，它大口喘气，积攒着最后一拼的体力。张继原感到自己不敢与狼的目光对视，站在这片古老的草原上，也就是站在草原的立场上，正义仿佛已全被狼夺去……

眼前是一大片人迹未至、方圆几十里的碧绿大盆地。盆地的东方是重重叠叠、一层一波的山浪，一直向大兴安岭的余脉涌去。绿山青山、褐山赭山、蓝山紫山，推着青绿褐赭蓝紫色的彩波向茫茫的远山泛去，与粉红色的天际云海相汇。盆地的北西南三面，是浅碟状的宽广大缓坡，从三面的山梁缓缓而下。草坡像是被腾格里修剪过的草毯，整齐的草毯上还有一条条一片片蓝色、白色、黄色、粉色的山花图案，色条之间散点着其它各色野花，将大片色块色条，衔接过渡得浑然天成。 一条标准的蒙古草原小河，从盆地东南山谷里流出。小河一流到盆地底部的平地上，立即大幅度地扭捏起来，每一曲河湾河套，都弯成了马蹄形的小半圆或大半圆，犹如一个个开口的银圈。整条闪着银光的小河宛若一个个银耳环、银手镯和银项圈串起来的银嫁妆；又像是远嫁到草原的森林蒙古姑娘，在欣赏草原美景，她忘掉了自己新嫁娘的身份，变成了一个贪玩的小姑娘，在最短的距离内绕行出最长的观光采花路线。河湾河套越绕越圆，越绕越长，最后注入盆地中央的一汪蓝湖。泉河清清，水面上流淌着朵朵白云。 盆地中央竟是陈阵在梦中都没有见过的天鹅湖。望远镜镜头里，宽阔的湖面出现了十几只白得耀眼的天鹅，在茂密绿苇环绕的湖中幽幽滑行，享受着世外天国的宁静和安乐。天鹅四周是成百上千的大雁、野鸭和各种不知名的水鸟。五六只大天鹅忽地飞起来，带起了大群水鸟，在湖与河的上空低低盘旋欢叫，好像隆重的迎新彩队乐团。泉湖静静，湖面上漂浮着朵朵白羽。 在天鹅湖的西北边还有一个天然出口，将湖中满溢的泉水，输引到远处上万亩密密的苇塘湿地里去了。 这也许是中国最后一个从未受人惊扰过的原始天鹅湖，也是中国北部草原边境最后一处原始美景了。陈阵看得痴迷，心里不由一阵阵惊叹，又掠过一丝担忧。一旦人马进驻，它的原始美很快就会消失，以后的中国人再也没有机会欣赏这样天然原始的处子之美了。陈阵想如果边防公路通过他趴伏的地方就好了，这才是真正应该划为禁区的地方。

老人说：狼群杀那么多的黄羊，不是为了好玩，也不是为了抖威风，它们是为了给狼群里的老弱病残留食。老虎花豹为啥在蒙古草原站不住脚？狼群为啥就能霸住草原？就是因为狼群比老虎花豹抱团齐心。老虎打了食就顾自个儿吃，不顾妻儿老小。狼不是，狼打食想着自个儿也想着狼群，还想着跟不上狼群的老狼、瘸狼、半瞎狼、小狼、病狼和产崽喂奶的母狼。 你别看黄羊倒了一大片，今儿晚上头狼一嗥，半个额仑草原的狼，还有跟这群狼沾亲带故的狼都会上这儿来，一晚上就把这些羊都吃完了。狼想着别的狼，别的狼也想着它，狼群才抱团；狼群抱团，打起仗来才厉害。有时候狼王一声嗥，能调来上百条狼集体打仗。听老辈的人说，原来草原上也有老虎，后来全让狼群赶跑了。狼可比人顾家，比人团结。

繁殖能力很高的草原狼，真正能存活下来的，可能连十分之一都不到。毕利格老人说，腾格里有时惩罚狼，也是六亲不认的，一场急降的没膝深的大雪，就能把草原上大部分的狼冻死饿死。一场铺天盖地的狂风猛火，也会烧死熏死成群的狼。从灾区逃荒过来的饿疯了的大狼群，也会把本地的狼群杀掉一大半。加上牧人早春掏窝、秋天下夹、初冬打围、严冬枪杀，能侥幸活下来的狼便是少数了。老人说，草原狼都是饿狼的后代，原先那些丰衣足食的狼，后来都让逃荒来的饥狼打败了。蒙古草原从来都是战场，只有那些最强壮、最聪明、最能吃能打、吃饱的时候也能记得住饥饿滋味的狼，才能顽强地活下来。

陈阵逐渐发现，蒙古草原狼有许多神圣的生存信条，而以命拼食、自尊独立就是其中的根本一条。陈阵在喂小狼的时候，完全没有喂狗时那种高高在上救世济民的感觉。小狼根本不领情。小狼的意识里绝没有被人豢养的感觉，它不会像狗一样一见到主人端来食盆，就摇头摆尾感激涕零。小狼丝毫不感谢陈阵对它的养育之恩，也完全不认为这盆食是人赐给它的，而认为这是它自己争来的夺来的。它要拼命护卫它自己争夺来的食物，甚至不惜以死相拼。在陈阵和小狼的关系中，养育一词是不存在的，小狼只是被暂时囚禁了，而不是被豢养。小狼在以死拼食的性格中，似乎有一种更为特立独行、桀骜不驯的精神在支撑着它。

蒙古草原鼓励男儿钻狼洞、驯烈马、斗恶狼、摔强汉、上战场、出英雄。蒙古草原是战斗的草原，是勇敢者的天下。蒙古大汗是各部落联盟推选出来，而不是世袭钦定的。蒙古人在历史上一直从心底里拒绝接受无能的“太子”登基，蒙元时平庸无能的太子，经常被强悍的皇兄皇弟、勇将悍臣取而代之。

陈阵思索着说：劳动之中还有无效劳动，破坏性劳动和毁灭性劳动。两千多年以前，修建阿房宫的劳动，就把整个四川的森林砍光了，“蜀山兀，阿房出”，这种劳动多可恶。世界上许多农耕民族的垦荒劳动，其结果是劳动出一片大沙漠，最后把自己的民族和文明都埋葬了。而且，世界上最重要的一些东西，都不是劳动可以创造出来的。比如，劳动创造不了和平、安全、巩固的国防；劳动创造不了自由、民主、平等及其制度；劳动创造不了强烈要求实现自由民主平等的民族性格。不会战斗的劳动者，只是苦力、顺民、家畜、牛马。自由民主平等不可能成为他们的战斗口号。世界上人口最多、最勤劳、劳动历史最长、并且从未中断过劳动的华夏人民，却创造不出劳动历史短得多的西方民族所创造的先进发达的文明……
