#+title: You don’t need to work on hard problems

https://www.benkuhn.net/hard/

起因是我们无法找到明确的问题定义：问题在哪里？怎么分解这些问题？那些问题比较重要？

#+BEGIN_QUOTE
出于某种原因，许多聪明的大学生最终都认为“解决技术难题”是他们一生中能做的最好的事情。这是Hacker News 评论、招聘广告和面试问题中的常见说法。

为什么会这样？可能是因为这是他们在过去 15 年中获得的唯一回报。

学校是一个封闭的世界领域——你正在解决明确定义的难题（将这两个数字相乘，实现这个算法，根据这个标准写一篇读书报告），你的解决方案是在一个维度（字母等级）和性能上限上进行评估的（A+）很低。唯一的进步形式是参加更难的课程。如果你试图在这个奖励函数下最大化你的奖励，你最终会寻找越来越棘手的谜题来获得 A+。

现实世界是相反的。你会有一些非常模糊的最终目标，比如“帮助撒哈拉以南非洲的人们解决他们的金钱问题”，你需要根据这些目标确定许多不同的子问题的优先级。解决方案的性能有许多不同的维度（速度、可靠性、可用性、可重复性、成本……）——您可能甚至不知道所有维度是什么，更不用说哪些是最重要的了。可能结果的范围涵盖数量级，上限是拯救数十亿人的生命。你通过解决问题集而学到的习惯在这里对你没有帮助。

#+END_QUOTE

因为我们不知道要解决什么问题重要，我们自然就会找一个代替品：最难的问题最重要。学校会因为你解决了困难的问题而奖励你。想想自己的读研和读博的经历：要发sci/ieee/nature的文章，顶会多少篇才能毕业，学术论文最看重原创性。似乎我们在不断地竞争着，谁能更快地解决更难的问题。

#+BEGIN_QUOTE
由于这些差异，大多数精英学校的毕业生——包括我在内——一开始完全无法确定哪些工作才是真正重要的。（如果一些重要的工作确实碰巧让我们头疼，它不会以带有评分标准的拼图形式出现，所以我们不知道如何很好地执行它。）相反，我们会继续尝试运行我们的大学剧本，并寻找难题。

通常，我们会通过使简单的问题变得困难来找到它们，结果是欢闹/沮丧。Big Tech 的上层充满了以编写奇怪的 自定义 数据库或构建可以用笔记本电脑代替的大数据基础设施为职业生涯的人。

刚毕业的时候，我担心如果我从事枯燥的技术工作，我会感到无聊。相反，我了解到在其他维度上进行优化或玩不同的游戏是可能的，而且很有趣。我可以尝试尽快解决一个简单的问题（例如 Wave 的会计），而不是在难题上竞争 A+，或者找到最简单的解决方案有用的问题（例如识别肯尼亚人的名字），或者雇用一个团队比我自己更快地解决简单的问题。

事实上，这些结果更有趣！为什么？因为“困难的技术问题”不是我的根本目标——我的根本目标是利用我的技能获得最大可能的影响力来改善世界。

在学校里，如果你选择一个简单的问题而不是一个困难的问题，你就会失去影响力，因为你额外的解决问题的能力会被浪费掉。但在现实生活中，您可以将其重定向到优先解决哪些问题，或者更快地工作，或者构建一台可以为您解决问题的机器。
#+END_QUOTE

--------------------

我觉得评论区里面一些人的问题/回答也非常好，这里也抄下来。

一个提问

#+BEGIN_QUOTE
作为一个拥有“解决难题是你能做的最好的事情”心态的大学生，这篇文章非常有用。尤其如此，因为解决最困难的问题不是我的比较优势，而且我一直对此感到有点不好。那么关于如何找到重要的未解决问题有什么建议吗？

====================

好问题！

不幸的是，这有点像问“我如何打败市场”，即如果有一个奇怪的把戏，问题就已经解决了:)

也就是说，这是我不奇怪的非技巧性答案：找到重要的未解决问题需要 (1) 接触问题，(2) 注意到它，以及 (3) 意识到它很重要/可以解决。

这暗示了一些不奇怪的非技巧：
- 做很多事情
- 做的时候非常好奇
- 认真想想
#+END_QUOTE

另外一个提问

#+BEGIN_QUOTE
根据我在技术方面的经验，我完全同意这一点。您认为什么形式的非学校教育/在家教育/教育最适合从小就避免这种情况？（目前为我 1.5 岁的孩子考虑了很多）。

====================

好问题！（另外，嗨，好久没说话了，迟来的祝贺你 1.5 岁！）我也一直在考虑这个问题，尽管此时纯粹是理论上的。

想想我小时候做过的真正有用的事情：

- 读很多书
- 学习编码并尝试制作视频游戏/其他大型编码项目
- 在教孩子们编程的夏令营找一份暑期工作（高中一年级/二年级）
- 以真正的程序员身份获得暑期实习（HS 大三/大四）
- 与人争论事情
- 看了很多奇奇怪怪的网络哲学
- 我在高中的最后一年上了一门非常棒的写作课，我认为它至少让我的写作能力提高了 +1 西格玛
- 可能经常玩乐高积木（这是你从小就可以做的涉及实际创造力的事情）
- 可能是反舞（作为与比我年长的人互动的媒介）

如果我试图将其归结为一套原则，它会是这样的：
- 学习具有明确价值和改进轨迹的特定技能——阅读、写作、基础数学、统计、编程，其他人可能有明显不同的设置。（FWIW 我想实现这一目标的最佳方法实际上看起来很像正规学校，除了节奏快得多，减去不是这个的废话，减去滥用）
- 做有创意/无限制/没有“性能上限”的事情（例如制作视频游戏，而不仅仅是解决编程难题——尽管有些难题可能对练习或其他事情很重要）
- 花很多时间与“现实世界”互动——与不同年龄的人一起工作、活动等。

免责声明/此建议可能不好的原因：
- 可能只适用于喜欢和我一样的东西或大脑工作方式相似的人
- 也许我从学校学到的东西我没有意识到很重要
- 这与我实际所做的事情非常不同（先去一所昂贵的私立高中，然后是哈佛），也许这些正在以我没有意识到的方式帮助我，例如从一个花哨的学位发出信号
#+END_QUOTE
