#+title: 禅与摩托车维修艺术(Zen and the Arts of Motorcycle Maintenance)

https://book.douban.com/subject/6811366/

** 第一部
骑摩托车可就不同了。它没有什么车窗玻璃在面前阻挡你的视野，你会感到自己和大自然紧密地结合在了一起。你就处在景致之中，而不再是观众，你能感受到那种身临其境的震撼。脚下飞驰而过的是实实在在的水泥公路，和你走过的土地没有两样。它结结实实地躺在那儿，虽然因为车速快而显得模糊，但是你可以随时停车，及时感受它的存在，让那份踏实感深深印在你的脑海中。

现在我们在度假，想走一走支线，石子铺的乡间小路是最好不过的选择了。然后才是州际干道，下下之选才是高速公路。我们打算好好欣赏一下沿途的风光景致，所以要好好享受旅游的过程，不会干那种在很短时间之内游览几个景点的煞风景的事。这样一来我们心情大好，崎岖的山路虽然漫长，但是骑摩托车却是一种享受—倾斜的身体可以顺着山势忽左忽右，不像在车厢里被晃得东倒西歪。要是一路上车子少那就更好了，同时也比较安全。我认为路边要是没有广告牌或是休息站什么的，景色一定更美：不论是路旁的树丛，地上的小草或是园里的果树都长到齐肩高，沿途时不时还有小孩向你挥手，也有大人从屋里走到廊前看看是谁经过。一旦你停车问路或是想了解什么当地的情况，你得到的回答往往出乎意料：他们会问你打哪儿来，已经骑了多久，热情而又滔滔不绝地和你神侃半天，简直比你还要兴奋。

我们经常这么骑，后来才明白道理其实很简单：这些乡间小路和一般的干道迥然不同，就连沿线居住的居民的生活步调和个性也不一样。他们一直都没有离开过本地，所以可以很悠闲地和你寒暄问候、谈天说地，那感觉好极了。反而是那些早就搬到城市里的人和他们的子子孙孙迷失了，忘记了这种情怀。这实在是一个宝贵的发现。我在想，为什么我们这么久之后才会对其着迷。我们早已看过却仿佛没有看到，或者说是环境使我们视而不见，蒙骗了我们，让我们以为真正的生活是在大都市里，而这里只不过是落后的穷乡僻壤。这的确是件令人迷惘的事，就好像真理已经在敲你的门，而你却说：“走开，我正在寻找真理。”所以真理掉头就走了。哎，这种现象真是让人不解。

除非你很喜欢大声喊叫，否则一路上便很少说话，主要的精力都花在观赏风景和沉思上，想想自己看到了什么，听到了什么，看看天色如何，或是回忆一下往事，偶尔也看看摩托车的状况，欣赏一下我们来到的乡野。日子就是这样随意，忘掉时间，没有人会催促你，也不会担心浪费时间。

这些看法始于我和约翰对一件小事有了不同的意见：一个人保养车子究竟应该到什么程度？对我来说，尽量使用买摩托车时附送的小工具箱和使用手册，然后自己保养，是一件再自然不过的事；但是约翰反对这么做，他认为应该让师傅负责修理和保养才不会出错。这两种看法都很平常，如果我们没有骑摩托车一起旅行，没有坐在乡村路旁的野店一起喝啤酒，或是随兴闲聊，那么这点意见上的分歧就不会扩大。只要我们谈的内容是天气、路况、民情、往事或是新闻，谈话自然就很愉快。然而一提到车况，话就说不下去了。大家都保持缄默。就好像是两个老友，一个是天主教徒，另一个是基督徒，两人一起喝啤酒，享受人生，只要一谈到节育，谈话马上中断。

在摩托车维修方面我并不同意他们的看法，并不是我没有同情心，而是我认为他们的逃避和厌恶只是一种自欺的行为。（佛陀或是耶稣坐在电脑和变速器的齿轮旁边修行会像坐在山顶和莲花座上一样自在。如果情形不是如此，那无异于亵渎了佛陀——也就是亵渎了你自己。）这就是我想在这次肖陶扩旅程当中讨论的主题。

约翰有些担心思薇雅会不适应这种状况，想要她搭飞机直接飞到蒙大拿的比林斯，但是思薇雅和我都劝他打消这个主意。我认为只有在情绪不对的时候，身体上的不适才更加明显，那时你就会把不适的原因归咎于环境。但是如果情绪很正常的话，身体上的不适就无关紧要了。看看思薇雅，我不觉得她有任何不快。

几个礼拜之后，我找到故障的原因，在内部供油系统上有一根二十五分的销子被剪断了，以至于在速度高的时候，油没有办法流进来。为什么会发生这种事情呢？这个问题不断在我脑海中出现，这就是我想要写这本书的原因。为什么他们的动作这样粗鲁呢？他们不像约翰和思薇雅一样害怕科技，他们都是专门人员，然而做起事来却像猩猩一样，没有真正地投入，似乎没有明显的原因。我试着回想那间修理店，就是让我做噩梦的那个地方，想要找出问题的真正答案。

但是最重要的线索似乎是他们脸上的表情。然而实在很难解释，虽然他们看起来很随和、友善、轻松自在，但是却没有投入工作之中，他们就像旁观者一样，你会觉得他们只是在那儿晃来晃去，然后接过别人递给他们的扳手。他们对自己的工作没有认同感，不会说：“我是师傅。”一旦到了下午五点，八个小时一满，你知道他们会立刻放下手中的工作，即刻离开，然后尽可能地不去想他们的工作。在这一方面，他们与约翰和思薇雅一样，虽然想运用科技的成果，但是却不愿和它发生任何关系。或者说他们之间的确有关系，但是他们都没有投身其中，而保持冷淡疏离的态度，他们参与了这方面的工作，但是却没有真正地关心它。

但是让我惊讶的是，这些手册编写者的态度和这些修理人员的态度一样，竟然都是旁观者，所以它们可以被称为旁观者的手册。在字里行间，你隐约可以嗅到这样的意味：“这是机器，它和周围环境中的一切都没有关系，和你也没有关系，你和它也没有关系；你只需要懂得操纵某些开关，维持电压的强度，检查某些毛病等等。”就这么一回事。修理人员对这些机器的态度就和这些手册所透露出来的态度是一样的，都是保持旁观者的立场。于是我联想到市面上没有一本手册谈到保养、维修摩托车究竟是怎么一回事，这是最重要的一点。人们认为关心自己所做的事一点都不重要，要么就视之为理所当然。

在这次旅行当中，我想应该注意这一点，更深入地研究，看看是否能够了解究竟是什么把人和人的工作分离开来，进而了20世纪的人究竟是出了什么问题。我并不想仓促行事，因为仓促本身就20世纪最要不得的态度，当你做某件事的时候，一旦想要求快，就表示你再也不关心它，而想去做别的事。所以我想慢慢来，用我找到被剪断了的销子的态度，有了这种态度才能发现原因，这样才能仔细而且透彻地进行这件事，除此之外，别无他法。

这个时候，酒精、倦意和微风纠缠于我心中，一起影响着我，我又说道：“当然，科学定理也不占用任何空间，也没有能量，因此也只存在于人的心中，所以完全科学的态度就是既不相信鬼，也不相信科学，这样你就安全了。然而这样一来，你就没有多少可以相信的了，但是唯有这样才是科学的态度。”

梭罗的《瓦尔登湖》。……克里斯从来没有听过这本书，但我可以读上一百次也不觉得累。通常我会选一本他不懂的书，作为我们以后对答之用，我先读一两个句子，然后等他一连串地发问，然后再回答他的问题，之后再读一两个句子，用这样的方法读古典作品很有用，它们一定是用这种方式写成的。有的时候整个晚上我们都不断在阅读、讨论，而往往只读了两三页，这是一个世纪以前的阅读方式……当时肖陶扩非常流行，除非你也这样做，否则你就不知道究竟有多么愉快。

昨天我曾经谈过关心，我关心这副皮手套，我微笑着看它们被风吹拂，因为它们已经在那儿陪伴了我这么多年。它们已经磨损老旧了，但我却在它们身上发现了一种幽默感。整副手套都沾满了油渍、汗水、灰尘，而且还有地方发霉了。现在把它们放在桌上，即使天气不冷，它们也没有办法平平地躺着。它们似乎有属于自己的往事。虽然只值三块美金，而且已经补到无法再补，但是我仍然花了许多时间和精力去清理它们。我不能想象戴一副新手套的感觉。这种想法似乎很不实际，但是手套并不仅仅需要实际，其他事情也是如此。

这部旧车子的发动机有些金属声，仿佛里面有许多松散的叶片在噼啪作响，听起来很难听。其实这是气门正常的声音，一旦你习惯了这种声音，并且学会期待它的出现，那么当发动机的声音有所不同时，你很自然地就能听出来。如果你什么都听不到，那就最好。我想让约翰对那个声音感兴趣，但是根本不成，他所听到的只是噪音；他所看到的只是摩托车和我手中拿着沾满油污的工具，此外别无他物，这样当然引不起他的兴趣。

有些东西你忽略是因为它们非常细微，但有些却是因为它们过于庞大。我们两个人讨论相同的事，思考相同的事，然而他的出发点却和我的完全不同。他的确关心科技，但是他的观点已经被扭曲了，所以虽然他想要接近它，但是因为缺乏理性的思考，任他怎么反复运用，这一切对他来说都只不过是一种诅咒。他想不通这个世界上竟然会有这样令人难以置信的事。这就是他所处的角度，一种常规的角度。我一直都是从一个十分理性的角度来谈论一切有关机械的事物，因为机械是零部件、是各种关系、是分析、是组合、是明了事物的原委，但它并不真的在此处。它总是在别处，我们都以为别处即此处，但是实际上它却远在千里之外，这就是机械的本质。

古典的认知认为这个世界是由一些基本形式组成的，而浪漫的认知则是从它的表象来观察。如果你拿一部发动机或是机械图，或是电子仪表给浪漫的人看，他一定不感兴趣，因为他所看到的只是表象，枯燥无味，只是列出一大堆复杂的专有名词、线条和数字，没有让他觉得有趣的事。但是如果你把这些东西拿给一个偏向古典思想的人看，他会仔细地观察，然后就会着迷，因为他看到在这些线条和符号之后是丰富的基本形式。浪漫的模式主要有丰富的灵感、想象力、创造力和直觉。最主要的是情感而非事实。和科学相对的艺术往往就是很浪漫的，它的存在不依赖于理性或是法则，而是依赖于感情、直觉和美学。在北欧的文化当中，浪漫往往和女性有关，但这并不是必然的现象。相对的，古典的思想往往依赖于理性和法则——它们是思想和行为的基本形式，在欧洲的文化当中主要与男性有关，同时科学、法律、医药等各学科都受到了古典思想的影响，因此对大部分的女性来说毫无吸引力。所以虽然骑摩托车旅行是件很浪漫的事，但是要维修、保养摩托车却全然是古典的行为。修理车子的时候，必然会弄脏手，而且全身都是油污，这些基本形式往往和浪漫的精神相冲突，因而女性很不喜欢这样。

对于一个浪漫的人来说，这种古典的方式往往显得很沉闷，呆滞而且丑陋。就像保养车子一样，车子的一切都可以分解成零部件和它们之间的关系。所有的一切都必须经过测量和证明，这就给人一种沉重的压迫感，一种永无止尽的灰暗，这就是一股死亡的势力。然而对于一个古典的人来说，浪漫的人就很轻浮而没有理性，心情起伏不定，不值得信任，只对享乐感兴趣，是一种肤浅的人，就像寄生虫一样没有内涵，无法养活自己，是社会的负担。从这里我们就差不多可以看出他们彼此之间的冲突了。

首先我们发现前面所记叙的这一段文字有一个特点，你必须先压制住自己的看法，否则你就无法读下去，它是一个比沟里的死水还要沉闷的东西，你会读到化油器、齿轮、压缩机等等，活塞、火花塞、进气等等，如果从浪漫的角度来看就会觉得非常沉闷、丑陋而且十分笨拙，浪漫的人很少能突破这一点。但是一旦你能控制最初的反应，就会继续发现其他的内涵。

比如说，自动控制系统包括凸轮链、凸轮轴、梃杆和配电盘，之所以会这样划分，就是因为这把分析的小刀。如果你到一家摩托车用品店购买摩托车的自动控制系统，他们根本就不知道你在说什么，因为他们不是这样分类的。没有任何两家制造商的分类完全相同，而每一位修理师傅所熟悉的问题和你的认知也是不同的。所以了解这把小刀是非常重要的，不要因为它把摩托车划归某一类型，你就完全相信，因而受到愚弄，把精力集中在这把小刀的本身才重要，后面我会继续介绍如何有效地运用这把刀子，作为解决古典和浪漫冲突的依据。

古典的认知法就是针对这些不同的沙堆以及分类法还有彼此之间的关系，而浪漫的认知则是针对分类之前的那把沙子。它们彼此互不相容，但是都是观察世界的方法。现在有一件很重要的事，就是如何把这两者融合为一，却不伤害到彼此，这种认知法不会拒绝分类，也不会拒绝不分类。这种认知法就是直接把重点放在沙子的来源，也就是无穷的景致之中，这就是我们这位悲惨的博士斐德洛想做的。

他是一个疯子，如果你直接面对疯子，你所了解的就是他疯了，这等于是根本不了解他。要了解他，你就必须从他的角度看事情；如果你想要从疯子的角度来看事情，那么崎岖的路是唯一一条去了解他的路。不然你自己的看法会阻挡了你的视线。所以我认为只有一条路可以通到他那里，而且我们幸好还有这一条路可以走。

** 第二部

在这里要提到逻辑的两种方法，归纳法和演绎法。归纳法是从观察摩托车开始，然后得到普遍性的结论。比如说，如果摩托车在路上碰到坑洞，发动机就熄火了；然后又碰到了一次，发动机又熄了；然后再碰到一次，发动机仍然熄了；之后，行在平坦的路上，就没有熄火的情形，然后再碰到一次，发动机又熄火了。那么这个人就可以合理地推断，发动机熄火是坑洞造成的，这就是所谓的归纳法，由个别的经验归纳出普遍的原则。演绎法正好相反，它是从一般的原则推论出特定的结果。比如说，我们知道摩托车有一定的结构、体系，修理人员知道喇叭是受电池的控制，所以一旦电池用完了，喇叭自然也就不会响了，这就是演绎法。要解决一般思维无法解决的难题，就要通过你的观察和手册当中所提供的结构，不断交替运用归纳法和演绎法，如此才能找到解决之道。这种交织混杂的正确程序，如果正统化，就是所谓的科学方法。

事实上，我没有看过任何一个摩托车的问题会使用到全部的科学方法。一般需要修理的问题并没有这么困难。当我一想到这些科学方法，心里就会出现一个影像，那就是一座巨大的推土机——它的行动缓慢，它的工作枯燥乏味，走起来声音轰隆直响，而且动作十分笨拙，但是它所做的没有人能比。它需要的技巧很可能是非正规修理的两倍、五倍甚至十二倍，但是你知道最终必能得到成功。没有任何摩托车的问题能把它难倒，一旦你遇到真正的难题，试过了所有的办法，绞尽了脑汁仍然没有任何进展，你就会知道，这一回你真的和老天爷较上劲了。“好吧！老天爷，我所能做的就是这些了。”于是你只好祭出正统的科学方法。

科学方法最主要的目的就是让你能够准确地知道事情的真相，而不会误入歧途。每一个维修人员、科学家或是工程师都曾经因为没有准确地思考而大伤脑筋。这就是为什么大部分科学和机械方面的研究总是显得非常沉闷而小心谨慎，如果你很草率或者面对科学材料的时候怀有浪漫的想法，那么你很快就会被它蒙蔽。即使你不给它这样的机会，仍然有可能会发生。所以在研究科学的时候，一个人必须非常地谨慎，而且严守逻辑的法则。不要在逻辑上面摔跤，否则整个科学结构很快就会垮下来。只要你的推论稍有差错，你就会陷入无底的深渊当中。

研究电视的科学家如果很悲哀地说：“这个实验失败了，我们没有达到预期的结果。”这其实是报道人员的错误，因为一个实验并不会因为没有达到预期的结果就被称为失败了，只有它的结果无法测出假设的真假时才会被称为失败了。

一名没有受过训练的旁观者只看到修理人员所付出的劳力，就以为他最主要的工作在于劳力。事实上，这正是他最轻松也是工作上最小的一部分，他最重要的工作就在于仔细观察和精确思考，这就是为什么技术人员往往显得沉默寡言，甚至在做实验的时候有些畏缩。他们不喜欢在做实验的时候讲话，那样就无法专心地思考问题了。他们借着实验推论出问题的结构，然后与心里正常的运作结构相比较，所以他们看到的是基本形式。

在科学的殿堂里有许多深宅大院……有各种人住在其中，而他们住在这儿的动机也是形形色色，五花八门。有些人倾心于科学是因为有优越的智力，科学成了他们独有的活动，在其中他们得到了生动的经验，也满足了他们的野心。有一些人则完全是为了实用的目的，而将自己思考的产物献在祭坛上。如果斐德洛研究科学为的是自己的野心，或是实用的目的，那么他就永远都不会去研究科学的假设是否是一种实体。然而他的确是跨入了这个领域，但是却对答案不满意。

爱因斯坦曾经说过：人类用最适合自己的方式，描绘了一幅最简洁、最容易了解的世界图像。然后试着用经验取代某种层次的世界，然后征服它……他创造了这个宇宙和他感情生活的支柱，这样才能由中找到安宁，而这安宁是无法从个人狭窄的经验当中获得的……最崇高的工作……就是要建立这些宇宙基本的法则，这些法则经过演绎就能创造出现今的世界。而要通往这些法则没有合乎逻辑的路；只有靠着直觉和对经验的体谅才能进入其中……直觉？体谅？用来形容科学的源头是很奇怪的字眼。

斐德洛开始对假设的本身就是一种实体非常感兴趣，这是他实验的结论。在工作中他注意到，一般认为假设可以说是科学工作中最难的一部分，但是他却认为是最简单的。很正规地把一切都精确地记下来就为假设作了提示。首先在他实验假设是否正确的时候，其他的假设又不断地涌现出来；以后在进行其他的实验时，又会涌现更多的假设。在他继续研究下去的时候，仍然会涌现出更多的假设，直到最后他才非常痛苦地发现，在他作了这么多研究之后，不论是否定或是肯定原先的假设，假设并没有减少，反而不断在增加。如果这条定理属实，那么它在科学的思维上就不只是一个小瑕疵了，这条定理完全摧毁一切，因为它否认所有科学方法的效用。如果科学方法的目的就是要从一大堆的假设当中选出正确的，然而假设出现的速度远远超过实验所能处理的速度，那么很明显地就来不及证明所有的假设。如果不能够证明所有的假设，那么任何实验的结果都变得很不可靠。这样一来，整个科学的方法就缺乏建立实证知识的目标。关于这一点爱因斯坦认为：“根据进化所显示的，在历史上任何一刻，所有可想见的存在，总有一个会证明它比其他的一切要优越。”这个答案在斐德洛看来脆弱无比，然而“在任何一刻”倒给他深深的震撼。难道爱因斯坦认为真理是一种时间的功能？这种论点会把所有科学的最基本假设都毁掉。

研究过科学真理之后，他对它们出现一瞬就消失的情况很懊恼，因为科学20真理存留的时间和他所付出的努力正好相反。所以世纪，科学研究成果的19寿命似乎世纪要短得多，就是因为科学研究的规模现在大多了。如果下一个世纪科学研究的速度是现在的十倍，那么任何科学研究成果的寿命，很可能只有现在的十分之一。是什么缩短了它的寿命？最主要的就是假设的增加，假设愈多，研究成果的寿命就愈短。近几十年来假设大量增加的原因似乎来自于科学方法的本身。你看得愈多，知道得就愈多。你不是从一大堆假设当中筛选出一项真理，你是不断地提供大量的假设。这也就是说，你想要借着科学方法接近真理，实际上你根本没有任何进展，甚至离它愈来愈远，这是你所运用的科学方法造成的。

斐德洛所看到的只是个人之见，但是却反映出科学最真实的特性。许多年来它都被人忽视，人们期望从科学研究当中得到的结果和实际上所得到的结果，在这里正好互相冲突。然而似乎没有多少人正视这个问题。运用科学方法的目的，就是要从许多假设当中找出正确的一个，这就是科学的目的。然而我们从科学的历史来看，事实恰恰相反。各种资料、史料、理论和假设不断大量地增加，科学把人从唯一绝对的真理，引向多元、摇摆不定、相对的世界，是造成社会混乱、思想价值混淆的主要元凶。而这一切现象原本是科学要消灭的。在许多年前，斐德洛在实验室中已经觉察到的结果，现在在这个科学世界中我们随处可见。科学反而制造出反科学的混乱。

他认为引起我们目前社会种种危机的原因是理性天生的一种缺憾。除非这种缺憾能得到弥补，否则危机会一直存在。我们目前所谓的理性模式并没有把社会带向更美好的世界，反而离它愈来愈远。自从文艺复兴以来，这些模式就一直存在。只要人们主要的需求还在于衣食住行，这些模式就会存在下去，而且还会继续运作。但是对现在大部分的人来说，这些基本的需要不再是主要的问题，因而从古代流传下来的理性结构已经不符合所需，从而显露出它真正的面目——在情感上是空虚的，在美学上没有任何表现，而在灵性上更是一片空白。这就是它的现状，而且它还会持续很长的一段时间。

斐德洛从没遇到过一个人能够真正关心这个困扰他的问题，他们似乎都这样说：“我们知道科学方法很有效，为什么要这样问呢？斐德洛不理解这种态度，也不知道该怎么办。由于他研究科学并不是为了个人或是实用的目的，所以这使他完全停顿了下来。这就如同他在观赏爱因斯坦曾经描述过的那座澄静的山，突然在山与山之间裂开了一道沟，里面什么也没有。然后你得慢慢地、十分困难地解释它的由来。起初这些山岭看起来好像会永远存在，其实却可能变成别的东西……很可能只是他自己的幻想，所以他停下来了。

他沉思着，四周的钢板突然发出一阵沉重的巨响，这时他才发现整个房间都在随着海浪忽上忽下。他以为是因为这些起伏他才无法专心阅读手中的书，后来才知道是书太艰深了。这是一本有关东方哲学的书，是他读过的最难的一本，他很高兴能够独自一个人在空旷的船舱里读这本书，否则他永远不可能读进去。

我曾提到过斐德洛的飘荡时期，最后他开始接受哲学思想的训练。他认为哲学是所有知识里面最高级的，所有的哲学家都这么认为，所以它几乎已经变成了一种陈词滥调。但是对他而言却是一种启示，他才发现他曾经一度认为的世界上唯一的知识——科学，其实只是哲学的一支，哲学比科学宽广许多，甚至更基本。他所问的有关无限假设的问题科学家并不感兴趣，因为这不是科学问题。科学没有办法在研究科学方法的时候不落入会摧毁它所有答案的陷阱。所以他问的问题比科学的层次还要高。于是，斐德洛在哲学当中发现了引领他走向科学那个问题的自然延伸。这一切究竟意味着什么呢？这一切的目的又是什么？

我现在想要谈谈思想上的高山区，最起码对我而言，和到这里的感觉很接近，所以称它为心灵的高山地带。如果人类所有已知的知识是一个巨大的体系，那么心灵的高山地带就出现在这个体系的最高处，它是所有思想当中最抽象也是最普遍的。很少有人到此一游，因为你不能从这一趟旅程当中获得任何实质上的利益。但是就像我们周遭的这一片高山区，它有它自己庄严的美感，所以对某些人来说，即使费尽九牛二虎之力到此一游也是值得的。来到心灵的高山地带，一个人必须习惯不稳定的稀薄空气，还有大量的问题以及各种假设的答案。这种情形会不断地扩大，一直到这个人几乎无法控制，因而迟疑是否要接近它，因为他害怕很可能会在其中迷失，而且永远找不到出路。

事实上休谟认为我对于这辆摩托车的了解完全来自于我的感官系统——情形一定是这样，没有别的方法。如果我说它是由金属和其他物质造成的，他就会问，“什么是金属？”如果我说金属摸起来很坚硬、光滑而且冰冷，如果用一个更坚硬的材料来撞击它，并不会断裂，休谟就会认为这些都是眼睛、耳朵和手所感受到的，并没有实体存在。除了这些感觉之外，金属究竟是什么？当然这时候，我无言以对。但是如果没有实体，我们又怎么解释接收到的讯息呢？如果我看向左下方，能看到车把手、前轮、装地图的位置还有油箱，我从感官得到一种印象；如果我往右下方看，又看到另外一种稍有不同的情形。这两种印象不一样，平面的角度和金属的曲线也不一样，太阳照射的角度也不一样。如果没有实体，那么我无法证明这两种印象得自于同一辆摩托车。

这个时候康德的说法救我们脱离了险境。他说，不能由感官认知摩托车并不能证明摩托车就不存在。在我们心中有一种直觉能认知摩托车。它在时间和空间上有一种连续性，所以当一个人转头的时候，摩托车的形象也跟着改变，所以它和我们在感官上所接收到的讯息并不冲突。所以，我们前面提到的那个躺在床上十八年毫无知觉的病人，如果有一天突然让他感知到摩托车的存在，然后再去除掉他的感官知觉，那么我想在他的心中就会有休谟式的摩托车印象，也就是不具有因果观念的摩托车。但是就如同康德所说的，我们并不是那个人，在我们心中有一种直觉的摩托车形象，我们不需要怀疑它，我们能随时证实它的存在。

它只是一部机器，一部通过直觉所了解到的摩托车，如果你停下来仔细地想一想，就会发现它才是主体。你的感官所得到的讯息只能证实它的存在，但是这些讯息并不等于它。我通过直觉所了解到的摩托车，就像我存在银行里面的钱。如果我到银行要求看我的钱，他们一定会很奇怪地看着我。因为我的钱并没放在他们的抽屉里，他们没法拿出来给我看，我的钱其实只是电脑存档里面的一个数字。但是这样就够了，因为我相信如果我需要钱的时候，银行会通过他们的系统让我取到钱。同样的，即使我的感官并没有看到真正的钱，但是我仍然有能力感受到我的钱在那儿，随时可以取用。康德的《纯粹理性批判》就是探讨我们如何得到这种直觉的知识，以及如何运用它。

在所有东方的宗教当中，梵文教义“ tat tvam asi”被推崇备至，“彼即汝”，它宣称，你认为你所是的与你认为你所感的是不可分割的。完全认识到它们是一个整体，就是开悟。逻辑就是把主客观分开，所以逻辑不是最高的智慧，想要消除这种因划分主客观所产生的幻觉，最好的方法就是减少生理、精神和情感上的活动。为了达到这个目的，有许多修炼的方法，其中最重要的一种方法，就是所谓的“禅”了。斐德洛从来没有打坐的经验，因为他不认为这有任何意义。他在印度时，一直坚持逻辑自洽才有意义，他找不到任何可以信服的理由抛弃这种信仰。我想他这么做是值得称赞的。但是，有一天在教室里，哲学教授愉快地解说世界的虚幻本质，这似乎是第五十次了。斐德洛举起手来，冷冷地问他是否相信落在广岛和长崎的原子弹是一场幻觉。教授笑了笑说是的。于是斐德洛的游学就到此终止。

斐德洛认为学校就存在这种混淆不清的状况。这就是为什么失去认证会令人难以理解了。真正的大学本质上并不是物质的，也不是警察所能保护的一些建筑。他解释说，一所大学如果失去了它的认证，没有人会封锁学校，不会有法律的制裁，也没有罚款，更不会被判决入狱。学校不会停课，一切还是照常进行，学生就像学校没有失去认证一样接受教育，所发生的只是撤销了对这所学校的官方承认而已，这和开除教籍颇为类似。真正的大学并不听命于任何民意机关，也不是由任何建筑物所构成的，只要它自己宣布这个地方已不再是圣所，真正的大学就已经消失，所遗留下来的只是一些砖墙、藏书和种种物质的结构罢了。

斐德洛认为，理性教堂追求的最主要目标，就是苏格拉底一向认为的真理。只不过随着理性的发展，它不断以不同的面貌出现在历史中，其他的一切都隶属于它。平时，这个目标和提高市民的水准不相冲突，但是在某种情况下就会出现对立，和出现在苏格拉底身上的情形一样。每当贡献了大量时间金钱的执事人员和立法者，与教授的言论以及公开的看法有出入时，他们就会借着行政力量，威胁要削减预算，强迫教授听命于他们。

我批评这种糟糕的交叉引用带来的恼人的混乱，但同时有一种感觉：这并不是狄威斯感到难以理解的真正原因。真正的原因是它缺乏整体性和顺畅的描述。工程技术人员常使用这种僵硬、破碎又突兀的语言风格，却令狄威斯很难消化。科学工作的内涵是把一个整体分解成条条块块加以研究，而狄威斯的工作则是把本不相关的这一条那一块组合成有意义的整体。他真正希望我批评的是其中缺乏艺术性的连贯，这一向是工程人员最不关心的东西。它和其他与科技相关的事物一样，经常出现在古典和浪漫的对立中。

“这是一种新观念，”我说，“但是它的来源却很传统。客观的物质，比如说，自行车或是烤肉架，本身无所谓对错，分子仍然是分子。机器没有感受力，除了人施加给它们的东西。要想测试机器的好坏，全看它给你的感受，没有别的测试方法。如果你面对机器时心静如水，机器一定是好的，如果你心烦意乱，那就表示机器有问题，除非你或机器任一方有所改变。所以测试机器也是对你的一种测试。没有别的测试。”

接着我又说：“比较常见的情形是，即使它已经恢复正常了，你仍然忐忑不安。我想这才是现在的状况。现在，如果你担心，就表示它有

问题。这意味着你没有彻底检查过它。在工厂里，任何一台机器没有彻底被检查过，就不能上线运转，即使它可能会运转良好。你对烤肉架的忧虑也是一样。你还没有完成让你内心平静的必需步骤，因为你觉得说明书太复杂了，很可能无法正确理解。”

我说：“情况就是这样，没有作者抵制这种做法，因为科技原本就假定只有一种正确的方法。然而情况完全不是这样。所以一旦你有这样的假设，说明书当然就只限定于说明烤肉架。但是一旦你需要从几百种组装的方法中作出选择，就要同时考虑到你和机器之间的关系，还有你

和你的机器与外界的关系。这样一来，工作的艺术便不仅依赖于机器的物质层面，还依赖于你自己的思想和心灵。这就是为什么你需要内心平静。”我接着说：“其实这种想法并不奇怪，有时候你只要把新手或蹩脚的人和高手作比较，就会发现其中的差异。老手根本就不会照着指示去做，他边做边取舍，因此必须全神贯注于手上的工作，即使他没有刻意这样做，他的动作和机器之间也自然地有一种和谐感。他不需要遵照任何书面的指示，因为手中物质的本质决定了他的思路和动作，同时他的思路和动作也在不断改变他手中物质的本质。所以物质和他的思想一同不断地改变，直到他的内心与物质同时达到正常与平静。”教艺术的朋友说：“听起来好像艺术一样。”我说：“的确就是艺术，把艺术和科学分离是完全违反自然的，两者分离太久了。你必须像考古学家一样，追溯到两者最初分离之处。其实组装烤肉架是雕刻艺术早已失传的一支，多少世纪以来，由于知识错误的分野，造成两者的分隔，因而如今一旦把它们连接起来，就会显得有些荒谬。”

“而现在的状况是，每一年我们都发现，传统的理性越来越无法处理现有的经验，因而造成目前世界上价值观十分混乱的现象，结果越来越多的人开始进入非理性的世界。比如占星术、神秘主义、吸食毒品，等等，因为他们觉得古典的理性无法处理真实的经验。”“我不太了解你所谓古典的理性。”“就是分析式的、辩证式的理性。这种理性，有时在大学里被认为是学会知识的唯一方式，你从来不曾真正地了解它。但一谈到抽象艺术，理性就完全派不上用场了，艺术的不可言传正是我所谓的对根基的体验之一。有一些人很可能会诅咒抽象艺术，因为它毫无道理可言。但是错不在于艺术本身，而是所谓的道理——它来自于古典的理性，无法掌握艺术的现象。大家一直想从理性的枝节进展当中，找到能够涵盖抽象艺术的理论，但是答案并不在理性的枝节当中，而在根本。”

在大一修辞学的课堂上，只需要读一小段论文或是短篇故事，然后讨论作者为了产生某种效果所运用的技巧，然后让学生运用同样的技巧模仿着写论文和短篇故事，看看他们是否做得到。斐德洛不断试着这样做，但还是无法让学生真正学到什么。经过这种精心设置的模仿，学生写出来的东西和原作往往相去甚远，甚至在更多情况下，他们的写作能力变得更糟，因为在这些规则之中，总是充满了各种例外、矛盾、混淆不清以及限定好的条件，以至于他希望一开始就不曾谈过这些规则。

有一个学生，总是喜欢问在某种特定的情况下该如何运用这些规则。斐德洛这时候就必须作出选择，是编造一套如何运用的解释，还是坦白地告诉对方他真正的想法。而他真正的想法是，这些规则是作品写好之后才归纳出来的，作者不是依照这些原则来写作的。他最后终于确信，这些学生想模仿的作家，根本就没有所谓的原则，只是把他们认为对的东西写下来，然后再回头看看是否有问题，如果修辞不妥，可以再修正。的确有些作者经过精心构思后才动笔，这从他们的作品中显而易见。但在斐德洛看来，这种写作风格十分糟糕，就如格特鲁德·斯泰因[ 20]所说：其中的确有点蜜汁，却无法汹涌而出。但是你又如何教学生那些无法事先周密策划的东西呢？这似乎是不可能达到的要求。于是他就拿起教科书随兴评论，希望学生能够由此得到一些东西，但是情形并不令人满意。

那是一幅油画，我早已忘了有这幅画，但是现在我知道，是斐德洛买来挂在这里的。突然间我想起它不是原画，而是他从纽约邮购的一幅印刷复制品。狄威斯看到它的时候皱皱眉，因为这只是一幅印刷品，印刷品复制了艺术，却不是艺术，当时他并不明白二者的区别。这是法宁格[ 21]所作的《少数派的教堂》（ Church of the Minorities）的印刷复制品，对他有一种强烈的吸引力。吸引他的并不是它的艺术性，而是它的题材。半抽象的线条、块面、色彩、阴影，呈现出一座哥特式教堂，这正画出了他脑中理性教堂的景象，这就是他把它挂在这儿的原因。完全想起来了。这里是他的办公室，找到了！这就是我在寻找的房间。

另外一件让斐德洛沮丧的事是僵化的文法。这一部分早该作废，但是仍然存在，都是那种“主语错置打手心”的东西。你必须要有正确的拼写、正确的标点以及正确的用词。有数以百计的各种规则为那些喜欢零零碎碎的人而设立。没有人在写作时还会记得那些。这就好像餐桌上的繁文缛节一样，不是从真正的礼貌和人性出发，而是为了满足自己像绅士和淑女一样表现的欲望。绅士淑女般良好的餐桌礼仪以及说话、写作的合乎文法，被认为是挤进上流社会的晋身阶。

在所有东方的宗教当中，梵文教义“ tat tvam asi”被推崇备至，“彼即汝”，它宣称，你认为你所是的与你认为你所感的是不可分割的。完全认识到它们是一个整体，就是开悟。逻辑就是把主客观分开，所以逻辑不是最高的智慧，想要消除这种因划分主客观所产生的幻觉，最好的方法就是减少生理、精神和情感上的活动。为了达到这个目的，有许多修炼的方法，其中最重要的一种方法，就是所谓的“禅”了。斐德洛从来没有打坐的经验，因为他不认为这有任何意义。他在印度时，一直坚持逻辑自洽才有意义，他找不到任何可以信服的理由抛弃这种信仰。我想他这么做是值得称赞的。但是，有一天在教室里，哲学教授愉快地解说世界的虚幻本质，这似乎是第五十次了。斐德洛举起手来，冷冷地问他是否相信落在广岛和长崎的原子弹是一场幻觉。教授笑了笑说是的。于是斐德洛的游学就到此终止。

斐德洛认为学校就存在这种混淆不清的状况。这就是为什么失去认证会令人难以理解了。真正的大学本质上并不是物质的，也不是警察所能保护的一些建筑。他解释说，一所大学如果失去了它的认证，没有人会封锁学校，不会有法律的制裁，也没有罚款，更不会被判决入狱。学校不会停课，一切还是照常进行，学生就像学校没有失去认证一样接受教育，所发生的只是撤销了对这所学校的官方承认而已，这和开除教籍颇为类似。真正的大学并不听命于任何民意机关，也不是由任何建筑物所构成的，只要它自己宣布这个地方已不再是圣所，真正的大学就已经消失，所遗留下来的只是一些砖墙、藏书和种种物质的结构罢了。

斐德洛认为，理性教堂追求的最主要目标，就是苏格拉底一向认为的真理。只不过随着理性的发展，它不断以不同的面貌出现在历史中，其他的一切都隶属于它。平时，这个目标和提高市民的水准不相冲突，但是在某种情况下就会出现对立，和出现在苏格拉底身上的情形一样。每当贡献了大量时间金钱的执事人员和立法者，与教授的言论以及公开的看法有出入时，他们就会借着行政力量，威胁要削减预算，强迫教授听命于他们。

我批评这种糟糕的交叉引用带来的恼人的混乱，但同时有一种感觉：这并不是狄威斯感到难以理解的真正原因。真正的原因是它缺乏整体性和顺畅的描述。工程技术人员常使用这种僵硬、破碎又突兀的语言风格，却令狄威斯很难消化。科学工作的内涵是把一个整体分解成条条块块加以研究，而狄威斯的工作则是把本不相关的这一条那一块组合成有意义的整体。他真正希望我批评的是其中缺乏艺术性的连贯，这一向是工程人员最不关心的东西。它和其他与科技相关的事物一样，经常出现在古典和浪漫的对立中。

“这是一种新观念，”我说，“但是它的来源却很传统。客观的物质，比如说，自行车或是烤肉架，本身无所谓对错，分子仍然是分子。机器没有感受力，除了人施加给它们的东西。要想测试机器的好坏，全看它给你的感受，没有别的测试方法。如果你面对机器时心静如水，机器一定是好的，如果你心烦意乱，那就表示机器有问题，除非你或机器任一方有所改变。所以测试机器也是对你的一种测试。没有别的测试。”

接着我又说：“比较常见的情形是，即使它已经恢复正常了，你仍然忐忑不安。我想这才是现在的状况。现在，如果你担心，就表示它有

问题。这意味着你没有彻底检查过它。在工厂里，任何一台机器没有彻底被检查过，就不能上线运转，即使它可能会运转良好。你对烤肉架的忧虑也是一样。你还没有完成让你内心平静的必需步骤，因为你觉得说明书太复杂了，很可能无法正确理解。”

我说：“情况就是这样，没有作者抵制这种做法，因为科技原本就假定只有一种正确的方法。然而情况完全不是这样。所以一旦你有这样的假设，说明书当然就只限定于说明烤肉架。但是一旦你需要从几百种组装的方法中作出选择，就要同时考虑到你和机器之间的关系，还有你

和你的机器与外界的关系。这样一来，工作的艺术便不仅依赖于机器的物质层面，还依赖于你自己的思想和心灵。这就是为什么你需要内心平静。”我接着说：“其实这种想法并不奇怪，有时候你只要把新手或蹩脚的人和高手作比较，就会发现其中的差异。老手根本就不会照着指示去做，他边做边取舍，因此必须全神贯注于手上的工作，即使他没有刻意这样做，他的动作和机器之间也自然地有一种和谐感。他不需要遵照任何书面的指示，因为手中物质的本质决定了他的思路和动作，同时他的思路和动作也在不断改变他手中物质的本质。所以物质和他的思想一同不断地改变，直到他的内心与物质同时达到正常与平静。”教艺术的朋友说：“听起来好像艺术一样。”我说：“的确就是艺术，把艺术和科学分离是完全违反自然的，两者分离太久了。你必须像考古学家一样，追溯到两者最初分离之处。其实组装烤肉架是雕刻艺术早已失传的一支，多少世纪以来，由于知识错误的分野，造成两者的分隔，因而如今一旦把它们连接起来，就会显得有些荒谬。”

“而现在的状况是，每一年我们都发现，传统的理性越来越无法处理现有的经验，因而造成目前世界上价值观十分混乱的现象，结果越来越多的人开始进入非理性的世界。比如占星术、神秘主义、吸食毒品，等等，因为他们觉得古典的理性无法处理真实的经验。”“我不太了解你所谓古典的理性。”“就是分析式的、辩证式的理性。这种理性，有时在大学里被认为是学会知识的唯一方式，你从来不曾真正地了解它。但一谈到抽象艺术，理性就完全派不上用场了，艺术的不可言传正是我所谓的对根基的体验之一。有一些人很可能会诅咒抽象艺术，因为它毫无道理可言。但是错不在于艺术本身，而是所谓的道理——它来自于古典的理性，无法掌握艺术的现象。大家一直想从理性的枝节进展当中，找到能够涵盖抽象艺术的理论，但是答案并不在理性的枝节当中，而在根本。”

在大一修辞学的课堂上，只需要读一小段论文或是短篇故事，然后讨论作者为了产生某种效果所运用的技巧，然后让学生运用同样的技巧模仿着写论文和短篇故事，看看他们是否做得到。斐德洛不断试着这样做，但还是无法让学生真正学到什么。经过这种精心设置的模仿，学生写出来的东西和原作往往相去甚远，甚至在更多情况下，他们的写作能力变得更糟，因为在这些规则之中，总是充满了各种例外、矛盾、混淆不清以及限定好的条件，以至于他希望一开始就不曾谈过这些规则。

有一个学生，总是喜欢问在某种特定的情况下该如何运用这些规则。斐德洛这时候就必须作出选择，是编造一套如何运用的解释，还是坦白地告诉对方他真正的想法。而他真正的想法是，这些规则是作品写好之后才归纳出来的，作者不是依照这些原则来写作的。他最后终于确信，这些学生想模仿的作家，根本就没有所谓的原则，只是把他们认为对的东西写下来，然后再回头看看是否有问题，如果修辞不妥，可以再修正。的确有些作者经过精心构思后才动笔，这从他们的作品中显而易见。但在斐德洛看来，这种写作风格十分糟糕，就如格特鲁德·斯泰因[ 20]所说：其中的确有点蜜汁，却无法汹涌而出。但是你又如何教学生那些无法事先周密策划的东西呢？这似乎是不可能达到的要求。于是他就拿起教科书随兴评论，希望学生能够由此得到一些东西，但是情形并不令人满意。

那是一幅油画，我早已忘了有这幅画，但是现在我知道，是斐德洛买来挂在这里的。突然间我想起它不是原画，而是他从纽约邮购的一幅印刷复制品。狄威斯看到它的时候皱皱眉，因为这只是一幅印刷品，印刷品复制了艺术，却不是艺术，当时他并不明白二者的区别。这是法宁格[ 21]所作的《少数派的教堂》（ Church of the Minorities）的印刷复制品，对他有一种强烈的吸引力。吸引他的并不是它的艺术性，而是它的题材。半抽象的线条、块面、色彩、阴影，呈现出一座哥特式教堂，这正画出了他脑中理性教堂的景象，这就是他把它挂在这儿的原因。完全想起来了。这里是他的办公室，找到了！这就是我在寻找的房间。

另外一件让斐德洛沮丧的事是僵化的文法。这一部分早该作废，但是仍然存在，都是那种“主语错置打手心”的东西。你必须要有正确的拼写、正确的标点以及正确的用词。有数以百计的各种规则为那些喜欢零零碎碎的人而设立。没有人在写作时还会记得那些。这就好像餐桌上的繁文缛节一样，不是从真正的礼貌和人性出发，而是为了满足自己像绅士和淑女一样表现的欲望。绅士淑女般良好的餐桌礼仪以及说话、写作的合乎文法，被认为是挤进上流社会的晋身阶。

** 第三部

在许多禅学的书以及世界各大宗教的记载当中，我们都会发现这样的山岭和登山的旅人，以及发生在他们身上的种种故事。而实体的山往往能象征人们灵性成长的路。就好像我们身后山谷里的那些人，大部分望着灵性的高峰，但是一生从来不曾攀上去过，只是听听别人的经验就已经满足，而自己不愿意花费任何心血。另一些人则是靠着有经验的向导，他们知道最安全的路，因而能够顺利到达他们的目的地。但是还有另外一批人，不但没有经验，而且不太相信别人的经验，想要走出自己的路。其中很少有人能成功，但是总有一些靠着自己的意志、运气，还有上天的恩典而做到了。那些成功的人要比别人明白，其实登山并没有唯一或是固定的路线，有多少这样的人就有多少条路。

这名像驴子一样、假设出来的学生会继续游荡一阵子，他可能得到另外一个像他抛弃的教育一样珍贵的学习机会，就是所谓的“社会大学”，不再浪费时间和金钱去做一头高级的驴子。他可能找到一份工作，安然地做一头低级的驴子，比如，一名技工。然而事实上他真正的地位会提高，因为这样才可能有所贡献而带来改变。可能他终身就做这份工作，也可能他达到一定的水平，然而并不满足于此。短则六个月，长则五年，很可能会发生变化，他对自己每天机械化的工作越来越不感兴趣，过去被学校的理论和分数所压抑的创造本能，现在很可能因为工作的无聊而被唤醒了。他花了数千个钟头去解决机械方面的问题，因而对机械设计越来越有兴趣。他可能想要自己设计机器，因为他相信自己会做得更好，于是尝试改造一些发动机。成功之后，就想要更大的成功。然而这个时候，他可能会遇到瓶颈，因为他没有理论基础。于是，他就会发现以前自己丝毫不感兴趣并觉得一无是处的理论，现在变得有了一些值得敬重之处。

爬山必须尽可能地少费力，不要着急，而要以自身的状况决定速度。如果你已经觉得很不耐烦，那就加快速度，如果有点气喘就慢下来，要在这两者之间保持平衡。当你的思想不再集中于行动的目标，每爬一步不是为了爬上山顶，你会发现，这里有一片锯齿状的叶子；这块岩石有点松动；从这儿不太容易看见山顶上的雪，即使越来越接近山顶。这些都是你应该注意的事。只为了未来的某个目标而生活是肤浅的，生命萃聚在山的四面，而不是在山顶，我们脚下才是万物生长之地。

现在，正统的修辞学教科书终于以富有意义的面目回到学生的视野中，里面的原则不再是令人反感的教条，更不是目的本身，不过是些技巧、手法，但它们有助于达成真正重要的目标——良质。原本不见容于传统修辞学的良质，现在却成为通向修辞学的美妙开端。他把良质的各个层面列出来，比如说：统一、生动、可信、简洁、敏锐、清晰、强调、流畅、悬疑、出色、准确、比例适当、有深度，等等。由于这些抽象名词都很难定义，所以他就利用刚才的比较手法介绍给学生们。比如说文章的统一，也就是故事如何前后连贯，可以借撰写大纲改进自己的技巧。而要提高文章的可信性，则可以增加注释，因为注释能够提供更多权威性的参考。在大一的课程里面都会提到大纲和注释，但现在却被作为提高良质的方法。如果学生交来的报告中罗列一堆凑数的注释或是大纲松散，就表示他只是敷衍了事，没有达到报告应有的良质，所以毫无价值可言。

因为有强烈的个人目标，所以夏令营里的同学在参与这些活动的时候，都非常合作而且非常热忱，但是这种动机却会有不良的结果。任何追求个人荣誉的目标，结局都非常悲惨。现在我们就开始付出代价了。如果你想通过爬上山顶来证明你有多么伟大，那你就几乎不可能登顶。即使你做到了，那也是一种虚幻的胜利。为了维持这种成功的形象，你必须在其他方面一再地证明自己，结果始终处于虚荣心的驱使之下，而内心则常常恐惧别人会发现这种形象是虚幻的。所以这么做是错的。

有许多人将会失业，但这可能是短暂的现象，因为我们以后会在基本而无关良质的事物中找到工作。应用科学和技术都会急剧地改变，但是纯粹的科学、数学、哲学，特别是逻辑不会变动。斐德洛觉得最后一条非常有意思。纯粹的知识最不受影响。如果抽离了良质，只有理性仍然不变。这是很奇怪的一点，为什么会这样呢？

他同时看到两个世界。在知识这一边，也就是朴质这一边，他看见良质是一个分裂的字眼，也就是每一个有知识的分析者所寻求的。拿起你分析的刀子，把它放在良质这个字眼上，轻轻地敲它，不需要费多大的劲，整个世界就会一分为二——嬉皮式的和严谨的，古典的和浪漫的，科技的和人性的——分得十分清楚，不会乱成一团，也不会有任何遗漏。切割得不但很有技巧，而且很有运气。有时候，最优秀的分析者，即使面对最明显的分裂线，一敲之下，也可能什么都得不到，只有一堆垃圾。而良质，就像是我们宇宙这个概念中一条不合逻辑的线，微小得几乎注意不到，但如果你轻敲剖析它的刀子，整个宇宙就会裂开，利落之至，简直无法置信。他真希望康德仍然活着，康德会欣赏这种做法的。他将发现那把超级的钻石刀——而不要给良质下任何定义，就是关键之处。

可是我说得太快了，所以他听得出我语气上的厌恶，很是羞愧。他露出了怒色，但是什么也没有说，因为他害怕再背行李，于是紧皱着眉。在我轮流往上背背包的时候，他故意不看我。我在来回奔走中放下心中的恼怒，我知道，和他比起来，这些辛苦不算什么。如果你把登上山顶作为目标，你会辛苦得多，而这只是名义上的目标，真正的目标，是体验登山的每一分钟，同样是到达山顶，却要愉悦得多。我们慢慢往上爬，不把怨怒背在身上。

我们就这样读了一会儿梭罗的书，但是大约半个钟头之后，我惊讶又失望的是，梭罗并没有起作用。克里斯跟我都有一些不安。句子的结构与我们身处的高山森林不太搭配，至少这是我的感觉。这本书读起来有些消沉，我从来没想过梭罗是这样的。但实际情形就是这样。

他在想为什么这句话一开始就强烈地激怒了他，听起来似乎非常自然，为什么他花了那么多时间才知道它真正的意思。这句话实际是在说：“你的喜好是不好的，起码是不重要的。”在这句自以为是的假设中暗示的是，让你快乐的事是不好的，起码是不重要的。这正是他全力加以反击的朴质之精髓。大人训练小孩子不去做他们喜欢的事，但是……但是什么呢？当然！要去做别人喜欢的事。而别人是指谁呢？父母、老师、督学、警察、法官、上司、国王、独裁者，这些都是权威。一旦你被训练得轻视自己的喜好，那么当然你就会对别人更加顺服——变成好奴隶。一旦你学会不做自己喜欢的事，那么你就会为系统所接受。但是假设你去做你喜欢的事呢？难道这就表示你会跑出去开枪杀死英雄？去抢劫银行，或是强暴老妇人吗？劝你不要做自己喜欢的事，等于这个人在作一种大胆的假设，他似乎不了解，别人考虑过抢银行的后果之后，很可能就不喜欢去抢银行了。他不明白银行存在的首要理由就是因为它是人们所喜好的，因为银行能够提供贷款。于是斐德洛开始思考，为什么社会如此自然地反对你做自己所喜好的事。

所谓“其他的含义”代表的是深厚的古典科学的信念：为什么你所喜好的是不重要的？因为它来自于非理性的情感。他研究了很久这个论点，然后把它切割成两部分，他称之为科学的物质主义和古典的形式主义。他说这两者往往在同一个人身上出现，但是理论上却是分开的。科学的物质主义出现在对科学感兴趣的一般人身上的次数，远比出现在科学家身上的为多。他们认为，能用科学仪器测量的由物质和能量构成的事物才是真实的，其他的都不真实，或者最起码不重要。你所喜欢的事是无法用科学仪器测量的，因此就不真实。你喜欢的可能是一个事实，也可能是一种幻觉，感觉无法分辨这两者。科学方法的全部目的就是要分辨真假，然后消除主观、不实、想象的因素，进而得到客观而真实的现实。当他说良质是主观的，在他们看来，就是在说良质是想象出来的，因而从严肃考量现实的角度来讲，应该予以摒弃。另外一面则是古典的形式主义，也就是认为没有从知识角度去理解的事就根本没有被理解。良质在这种情况之下是不重要的，因为它是一种不能被理性知识因素分析的情感认知。

于是他又提到其他的科学观念，一个一个地揭示，它们都无法脱离主观的考量而存在。他以万有引力法则结束，也就是在我们旅行的第一天晚上，我给约翰、思薇雅以及克里斯举的例子，如果主观被视为不重要的，那么整个科学体系也会随之瓦解。这种对于科学的物质主义的攻击，似乎将他归入了哲学唯心主义的阵营——贝克莱、休谟、康德、费希特、谢林、黑格尔、布拉德雷、鲍桑葵[ 6]，全都是些伟大的人物。但是我们很难用普通的言语证明这在他对良质的辩护上是有害还是有益。唯心论的说法虽然可能在逻辑学上比较合理，但是在修辞学上却不然。对大一作文来说，这个主题实在太枯燥，而且十分困难，他们确实无法理解。

而事实上，他所谓的良质并不是古典的良质或是浪漫的良质。它超越两者之上，既不属于主观，也不属于客观，它超出了这两个范畴之外。事实上，把整个主观-客观、唯心-唯物的两难困境与良质扯上关系是不公平的。因为唯心、唯物的争论已经出现了几百年，他们只是用这个争论把良质拖下水。既然何为心何为物尚未明确，他又如何能够说出良质究竟是唯心的还是唯物的呢？如此一来，他便摆脱了左角。良质不是客观的，它不存在于物质的世界。然后他又避开了右角，良质也不是主观的，它不单单存在于人心之中。

他认为知识分子最难了解这种良质，因为他们反应过快，立刻将一切化成思考的形式，又对此持有固执的自信。而最容易看见良质的是儿童以及未受过教育的人，还有被剥夺受教育权利的人。他们很少受到文化的影响，因而较少接受正规的训练，没有让文化渗透他们的心灵。他认为，这就是为什么朴质是一种独特的知识性的疾病。他发现由于学校教育在他身上的失败，使他偶然地拥有了对这种疾病的免疫力。最起码在某种程度上来说，不具有这种习惯。之后他自然就不认同知识，可以带着同情审视那些反知识的教义。
