#+title: 曾国藩的六戒！


*第一戒：久利之事勿为，众争之地勿往*

一直都能获利的事不要做，所有人都想得到的地方不要前去。危城莫入！所有人都向往渴求的，可能有有害。
前半句说：不可贪求过多！日中则移，月满则亏，物盛则衰。世界上没有一劳永逸的事情，也不可能有长久获利的事情。如果有这种能够一直获利的事情，那只能说这种事是表面现象或者骗局，这时候一定要保持头脑清。

后半句是说的安全，众人争执、争斗的地方你不要去，容易惹麻烦或者招致祸患。《论语》上说，“危邦不入，乱邦不居”就是这个意思。当然，这句话里的争，也可以理解为，争利。意思是说，大家都去争抢的利益，你就不要去争抢了，因为那肯定是薄利。

*第二戒：勿以小恶弃人大美，勿以小怨忘人大恩*

不要因为别人小的缺点就忽视他的优点，不要因为小小的恩怨就忽略了别人的大恩。
人只要做事就会犯错，这两句话都是告诉我们，不要因为别人的一点小过失，一点道德上的小瑕疵，一点小恩怨，就全盘否定别人的好，忘记别人的恩情。

《礼记》上说，“好而知其恶，恶而知其美者，天下鲜矣。”意思是喜爱一个人而知道其缺点，厌恶而知道其优点。这就是告诫我们，在待人接物的时候，一定不要太感情用事，一定要客观、公正地看待别人的缺点和不足。

*第三戒：说人之短乃护己之短，夸己之长乃忌人之长*

经常说别人短处的人，经常夸耀自己长处的人，可以说是“存心不厚，识量太狭。”俗话说，“打人不打脸，揭人不揭短。”经常谈论别人的短处，夸耀自己的长处，不仅是情商低的表现，也必然给自己招来怨恨，埋下祸乱的种子。
汉高祖刘邦曾经随便和韩信讨论各位将领的才能。刘邦问道：“像我自己，能带多少士兵？”韩信说：“陛下不过能带十万人。”刘邦说：“那对你来说呢？”韩信回答：“像我，越多越好。”韩信后来被杀，不能说与他这种性格无关。

曾国藩这句话的意思，入目三分地画出了可这种人的精神肖像。那种经常谈论别人缺点的人，内心其实是借此在掩饰自己的缺点；经常夸耀自己长处的人，内心其实是嫉妒或者想掩盖别人的长处罢了。

*第四戒：利可共而不可独，谋可寡而不可众*

利益，往往是众人都渴望得到的，如果谁独占了利益而不与大家分享，那么一定会招致怨恨，甚至成为众矢之的。刘邦攻破咸阳，却不敢占据其地；曹操能够“挟天子以令诸侯”，却终其一生不敢篡汉自立，他们都是怕成为众矢之的。所以，面对利益，一定要权衡取舍之道。
谋划事情，一定要跟有主见的几个人一起，而不要与众人一起谋划事情。正如《战国策》上说，“论至德者不和于俗，成大功者不谋于众。”通俗地说，就是谋求特别重大的事情，不必与众人商量。因为谋求大事的人，自己必定有非同一般的眼光、心胸与气度，自己看准了，去做就是了，如果和别人商量，反倒麻烦。如果别人见识低下，心胸狭小，气度平凡，必定不理解你的想法。七嘴八舌，会动摇你的意志，也会破坏你的信心和情绪。

*第五戒：古今之庸人，皆以一惰字致败，天下古今之才人，皆以一傲字致败*

庸人，就是普通人，一般的人。对于一般的人来说，没有什么才气，只有勤奋工作才能成就事业，所以最忌讳一个“懒”字。曾国藩是勤劳的好例子，他其实并不聪明，但是却能以“勤”成就大学问和大事业，可以说正是普通人的榜样。
而那些有才的人呢，虽然可凭才气走捷径，更容易成功，但也容易孤傲自大，故步自封，不肯向别人学习，这也是容易失败的。如项羽、李自成等，占尽天时地利，却因为骄傲而败亡。

*第六戒：凡办大事，以识为主，以才为辅；凡成大事，人谋居半，天意居半*

凡是办大事，首先需要有深厚的阅历和识见，并以才能作为辅助；凡是要成就大事的，一半在于人的谋划，另一半就要看天意了，看时机会不会来到。所谓谋事在人，成事在天。
曾国藩明确告诉我们，办大事要以“识”为主，才气、才能不过是辅助罢了。所以恃才傲物的人，往往难以成就大事。当然这里的“识”，不单单指知识，更指的是经验和见识。

而“人谋居半，天意居半。”则是说，我们无论做什么事情，都要抱着“尽人事以听天命”的态度。不要因为有自己不能左右的的因素就不去努力，更不能因为自己努力了，最终却失败了而去怨天尤人。
